### PR TITLE
colexec: make "on" the default vectorized mode and rename "auto" to "201auto"

### PR DESCRIPTION
**Pull request by asubiotto**
This commit turns on vectorized execution for all supported queries.

Release note (sql change): the default vectorized execution mode is now "on",
which means that all queries that can use vectorized execution will do so. To
revert to previous behavior
SET CLUSTER SETTING sql.defaults.vectorize='201auto'

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48059)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by asubiotto** [comment]
Forgot to respect the row count threshold. Updated this PR with that and rewrote/fixed logic tests.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 41 of 41 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48059#-:-M65QU2_1FAyn1J9DEej:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by asubiotto** [comment]
Latest failures are interesting. Since we respect the vectorize row count threshold with `vectorize=on`, we were running through the row execution engine. In logic tests we only set the vectorize row count threshold to 0 if the config does not override vectorize. Configs still "override" vectorize to "on", so the threshold is set.

I think we should still be testing with the vectorize row count threshold set to 0. I added a slight change to set it if the override config is "on" as well. We could just remove the `overrideVectorize` options to tests that set this to "on", but it's making me think that we're also losing some testing coverage of "auto". @yuzefovich what do you think?

**Review by yuzefovich — COMMENTED** [review]
I think we want to update to update the logic test configs so that we have `vec-off`, `vec-201auto`, and "default", with the last one using the default value `vectorize=on` (i.e. we want to switch current "local, local-vec" with updated "local, local-vec" in which we have an empty `overrideVectorize` and `overrideVectorize=201auto`). And then we want to set the row count threshold to 0 in all cases except for `overrideVectorize==201auto` - this will make test coverage of `201auto` exactly as before this PR, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48059#-:-M66FOxI1ze2uaIldlyV:b-nw7oae)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

**Comment by yuzefovich** [comment]
Never mind, I'm confused, what I said was wrong. I think we simply want to always override the threshold to 0 now (and still update the logic test configs, because without that we'll have redundant `local` and `local-vec`, etc).

**Comment by asubiotto** [comment]
Update the logic test configs. I changed the configs that `overrideVectorize=on` to override to `201auto` instead and renamed configs. The config changes are `s/local/local-vec-auto` and `s/local-vec/local` which apply to fakedist and 5node as well.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 2 of 2 files at r4, 14 of 14 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48059)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/logictest/logic.go, line 1283 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48059#-M6Bl2H2ArPYRTksc_av:-M6Bl2H2ArPYRTksc_aw:bsm88fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c974172a73f3d54f1f4ca731181d65bc54416fd/pkg/sql/logictest/logic.go#L1283)):*
> ```Go
> 	}
> 
> 	if strings.Compare(cfg.overrideVectorize, "off") != 0 {
> ```

nit: we actually could override the row count threshold always, regardless of the vectorize setting, because with `vectorize=off` that parameter is ignored anyway. Up to you.
___
*[pkg/sql/logictest/testdata/logic_test/tpch_vec, line 1 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/48059#-M6Bld9V53cMCP4QmojS:-M6Bld9W7YjmC10Vj3m-:bcy3d8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c974172a73f3d54f1f4ca731181d65bc54416fd/pkg/sql/logictest/testdata/logic_test/tpch_vec#L1)):*
> ```
> # LogicTest: local
> ```

Interestingly, there is a failure on this test which seems to occur because for some reason we're falling back to planning `rowexec` filter whereas before we used vectorized.

**Comment by asubiotto** [comment]
It seems to be because the filter condition of the hash joiner is a `tree.Subquery` which is not pre-evaluated since `local` runs with `distsql=off`, this cause us to say we don't support the filter expression. I `--rewrote` the test. This also happens in query 15 and 22. I think it's fine to keep `distsql=off` in local since that's the point. Most of the tests are run with the default configs so I don't think we're sacrificing much test coverage.

**Review by yuzefovich — APPROVED** [review]
> Reviewed 20 of 21 files at r6, 14 of 14 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48059)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by asubiotto** [comment]
bors r=yuzefovich

**Comment by ericharmeling** [comment]
@asubiotto Is the `vectorize_row_count_threshold` ignored if `vectorize=on`? (This is [what we have documented for v20.1](https://www.cockroachlabs.com/docs/stable/vectorized-execution.html#setting-the-row-threshold-for-vectorized-execution)).

**Comment by asubiotto** [comment]
Yes in 20.1 because it's not the default mode, but it won't be in 20.2 since `on` is going to become the default.

**Pull request merged**
