### PR TITLE
sql: populate more of pg_catalog.pg_proc for routines

### LINKED ISSUE #121527: pgcatalog: update pg_proc contents for routines
We can now meaningfully populate some fields like `proallargtypes` and `proargdefaults`.

Jira issue: CRDB-37306

### PR DESCRIPTION
**Pull request by yuzefovich**
See each commit for details.

Fixes: #121527.

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, 7 of 7 files at r2, 10 of 10 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/121966#-:-Nv32-Z8-hyqXYGCXdDO:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by yuzefovich** [comment]
Thoughts on backporting this to 24.1?

**Comment by DrewKimball** [comment]
>Thoughts on backporting this to 24.1?

Hm, do you think reordering/removing fields could cause problems for anyone reading from this table?

**Comment by DrewKimball** [comment]
Maybe with a setting as an escape hatch?

**Comment by yuzefovich** [comment]
Reordering would probably be ok, but removing columns could be a breaking change. I found some concerns with reordering mentioned in [this](https://github.com/cockroachdb/cockroach/pull/60758#issuecomment-998273936) discussion. I don't think there is a pressing need to get this into 24.1, so let's not do that. I'll add a release note though to call out this change.

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
