### PR TITLE
sql: localized cleanups related to SQL AST formatting

### PR DESCRIPTION
**Pull request by eisenstatdavid**

### CODE REVIEW

**Comment by knz** [comment]
LGTM but coordinate with radu to ensure no merge skew between this one and #15796.

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, 18 of 19 files at r4, 1 of 1 files at r6, 2 of 2 files at r7, 19 of 19 files at r8.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/function_name.go, line 42 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15817#-KjjACegh8xvBPlwesA6:-KjjACeh91PQuwE5hs_y:bnfjxw6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec089bbc2d42bc76bd3f8bcbfc68bd459dab238c/pkg/sql/parser/function_name.go#L42)):*
> ```Go
> // Format implements the NodeFormatter interface.
> func (fn ResolvableFunctionReference) Format(buf *bytes.Buffer, f FmtFlags) {
> 	FormatNode(buf, f, fn.FunctionReference)
> ```

Please double check, this might be an exception. (re the failing tests)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15817#-:-KjjAaMGAkuC8CJ-u97N:b-jird7c)*

**Comment by eisenstatdavid** [comment]
I'll wait for #15796.

**Comment by eisenstatdavid** [comment]
Review status: 1 of 25 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/function_name.go, line 42 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/15817#-KjjACegh8xvBPlwesA6:-Kjjj_G6qqNJw8aqqw5W:b-f5cs0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec089bbc2d42bc76bd3f8bcbfc68bd459dab238c/pkg/sql/parser/function_name.go#L42)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Please double check, this might be an exception. (re the failing tests)
</blockquote></details>

This one was fine, but others weren't. I marked those. One I call site I changed along with the expected plan output -- the new output reports types more consistently.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15817)*

**Comment by knz** [comment]
still looks good. Thanks for checking.

---

Reviewed 1 of 1 files at r10, 2 of 2 files at r11, 21 of 21 files at r12.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15817#-:-KjmL7pznWa6nDxcy44K:b-u68jaa)*

**Pull request merged**
