### PR TITLE
all: move to lib/pq

### PR DESCRIPTION
**Pull request by andreimatei**
Stop using our forked lib/pq in anything but the CLI. This is because
the newest version of our fork doesn't register the driver with Go's sql
package any more.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9393)

### CODE REVIEW

**Comment by andreimatei** [comment]
This will have a glock update too once the update to our lib/pq lands.

**Comment by tamird** [comment]
I also instinctively think it should go to master for practical reasons,
but according to the code yellow rules, develop is right.

Perhaps it's time to adjust the code yellow guidance.

**Comment by tschottdorf** [comment]
`master`.

**Comment by petermattis** [comment]
This primarily affects test code. `master` seems appropriate.

**Comment by andreimatei** [comment]
rebased on master

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9393#-:-KRoRR1dHBw7MAtPsVKx:b-9r6maq)*

**Comment by tamird** [comment]
Sorry for the late drive-by, but we should consider a lint to prevent this from regressing. See `TestForbiddenImports` in check-style.

**Pull request merged**
