### PR TITLE
sql, server, statusccl: synchronously collect index usage stats

### PR DESCRIPTION
**Pull request by Azhng**
Follow up PR: #73179

---

Previously, index usage stats were collected asynchronously using
a buffered Golang channel. However, this has led to performance
regressions for SQL Flow setup and also observable increases in
TPCC-2500 tail latency.

This commit switches away from async index usage stats collection with
buffered Golang channel to using synchronous stats collection in order
to reduce the overall performance impact.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
I added backport-21.2 label since we do want to backport it there.

:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73307#-:-MpmdRFDBXcZiF9u4CzS:b-tdc567)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @Azhng)

___
*[pkg/sql/idxusage/local_idx_usage_stats.go, line 239 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73307#-MpmdFSgDEDDKSJfLuIi:-MpmdFSgDEDDKSJfLuIj:b-wwlnpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c19fdea7f74a5bde03579cf2577b9b143e3cd39/pkg/sql/idxusage/local_idx_usage_stats.go#L239)):*
> ```Go
> 
> func (s *LocalIndexUsageStats) insertIndexUsage(key roachpb.IndexUsageKey, usageTyp usageType) {
> 	// If the index usage stats collection s disabled, we abort.
> ```

nit: `s/s disabled/is disabled/`.

**Comment by Azhng** [comment]
Just want to hold off on holding this PR. I've chatted with @jordanlewis earlier this week about this performance regression. 
We think that, from a long-term perspective, our stats collection code within the DB will only get more and more complicated. Having synchronous stats collection might be an easy escape hatch for now, but it might cause more problems for us later.

#73174 is a different PR that will face a very similar problem, and we are already seeing pretty big performance drop by introducing the transaction ID cache. I've been trying out different prototypes and I think I have found a promising lead where we can still have performant async stats collection. I'll keep on testing and see if the similar technical can be applied here.

**Comment by yuzefovich** [comment]
> We think that, from a long-term perspective, our stats collection code within the DB will only get more and more complicated. Having synchronous stats collection might be an easy escape hatch for now, but it might cause more problems for us later.

That's a fair point. However, we did introduce a noticeable (on micro- and macro-benchmarks) regression with the current asynchronous index usage stats ingestion on 21.2, and we won't make that more complicated going forward, so I think it's still worth making the change on 21.2 branch to fix the regression even if we don't make the change on master anticipating the expansion of the async ingestion during 22.1 release. In other words, we currently know that we have slowed down then hot path on 21.2, we have the fix, so I don't see what's stopping us from applying it. @jordanlewis thoughts?

**Comment by Azhng** [comment]
I see, that makes sense, I'll merge this PR for now. 

bors r=yuzefovich

**Pull request merged**
