### PR TITLE
rowexec: add test to verify uncertainty errors are properly returned

### PR DESCRIPTION
**Pull request by asubiotto**
This PR fixes a bunch of instances that would swallow uncertainty errors in the vectorized engine and adds a test for this. This also uncovered a query termination edge case in the vectorized Inbox we weren't handling properly.

Release note (bug fix): fix edge cases where the vectorized execution engine would drop some results under contention

### CODE REVIEW

**Comment by asubiotto** [comment]
BTW I set `_, err = db.Exec("SET CLUSTER SETTING sql.defaults.results_buffer.size = '0'")` which I would expect would disable retries.

**Review by andreimatei — COMMENTED** [review]
> This is currently a WIP. The test is timing out under stress with the row execution engine and I'm looking for feedback on what I'm doing wrong. @andreimatei it looks like the query is retried indefinitely:
```
returning rwue error for key /Table/53/1/20 :0:
distsql receiver got error ReadWithinUncertaintyIntervalError: read at time 1594649777.533202000,0 encountered previous write with future timestamp 1594649777.533202001,0 within uncertainty interval `t <= 1594649778.033202000,0`; observed timestamps: [{1 1594649777.533202000,0} {3 1594649777.534206000,1}]
returning rwue error for key /Table/53/1/20 :0:
distsql receiver got error ReadWithinUncertaintyIntervalError: read at time 1594649777.534206000,1 encountered previous write with future timestamp 1594649777.534206001,1 within uncertainty interval `t <= 1594649778.033202000,0`; observed timestamps: [{1 1594649777.533202000,0} {2 1594649777.534797000,0} {3 1594649777.534206000,1}]
returning rwue error for key /Table/53/1/20 :0:
returning rwue error for key /Table/53/1/20 :0:
distsql receiver got error ReadWithinUncertaintyIntervalError: read at time 1594649777.534206001,2 encountered previous write with future timestamp 1594649777.534206002,2 within uncertainty interval `t <= 1594649778.033202000,0`; observed timestamps: [{1 1594649777.533202000,0} {2 1594649777.534797000,0} {3 1594649777.534206000,1}]
returning rwue error for key /Table/53/1/20 :0:
returning rwue error for key /Table/53/1/20 :0:
<...>
```
> Is there a way to turn off these retries?

(haven't looked at the patch)
Automatic retries are disabled once results are returned to the client - which happens when rows are produced *after* the buffer size is exhausted. An error encountered before the first row in a txn is returned is always retried. In particular, making this guarantee is the point of specific effort to swallow RWUI: a `limit 1` query in an implicit txn is always retried automatically.
If you want to disable auto-retries for a txn, you can run a dummy query in the txn's beginning.
Does this help?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-:-MC7mlvBCq_0zu6NoRI-:bz8x9kn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @yuzefovich)

**Comment by rohany** [comment]
> We should also add a test for cockroachlabs/support#513 cc @rohany

Sure, once we know what's actually going on there.

**Comment by asubiotto** [comment]
Thanks, that's probably the issue. Will try that and update.

> Sure, once we know what's actually going on there.

If we have the plan/query, once this test is stable, it might be easier to add that query to this test to reproduce deterministically and make it easier to track down the root cause.

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 7 of 7 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51375)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/routers.go, line 109 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC8yeXCAi_fcymu7AnY:-MC8yeXCAi_fcymu7AnZ:b-o387s4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ef6eb48f5e18b6091f6291022eb195ce468414/pkg/sql/colexec/routers.go#L109)):*
> ```Go
> 		syncutil.Mutex
> 		state routerOutputOpState
> 		// forwardedErr is an error that was forwarded by the HashRouter. It set,
> ```

nit: `s/It/If/`.

By "always returns" do you mean that it will be returning this error on all calls to `Next` once the error is set? It might be worth spelling this out.
___
*[pkg/sql/colexec/routers.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC8zRmw6Lx5xPm16yGE:-MC8zRmw6Lx5xPm16yGF:bo6uz20) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ef6eb48f5e18b6091f6291022eb195ce468414/pkg/sql/colexec/routers.go#L352)):*
> ```Go
> 
> func (o *routerOutputOp) forwardErrLocked(err error) {
> 	if err != nil {
> ```

Is it possible that `o.mu.forwardedErr` is already non-nil here?
___
*[pkg/sql/colexec/routers_test.go, line 715 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC9-0Pl2log70BF9uL-:-MC9-0Pl2log70BF9uL0:b-xvrs6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ef6eb48f5e18b6091f6291022eb195ce468414/pkg/sql/colexec/routers_test.go#L715)):*
> ```Go
> 	r := newHashRouterWithOutputs(in, typs, []uint32{0}, unbufferedCh, routerOutputs, nil /* toDrain */, nil /* toClose */)
> 
> 	verifyAtLeastOneOutputGotCancellationError := func(t *testing.T) {
> ```

super nit: maybe `s/verify/assert/`.
___
*[pkg/sql/colexec/routers_test.go, line 719 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC9-DX-B4nGiJiKTpTM:-MC9-DX-B4nGiJiKTpTN:b-d9rkef) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ef6eb48f5e18b6091f6291022eb195ce468414/pkg/sql/colexec/routers_test.go#L719)):*
> ```Go
> 		for _, output := range outputs {
> 			if errors.Is(output.forwardedErr, context.Canceled) {
> 				return
> ```

I think we're actually missing a check that at least one output got the error: the way I see it right now, it is possible that `forwardedErr` of all outputs is `nil`, and we don't fail the test.
___
*[pkg/sql/colflow/vectorized_flow.go, line 733 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC9-ncGClvTlsBjVFoA:-MC9-ncGClvTlsBjVFoB:bphnh4h) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a31e41bf291842cc5967ffa5f827f2e7add839/pkg/sql/colflow/vectorized_flow.go#L733)):*
> ```Go
> 				return nil, nil, nil, err
> 			}
> 			inbox, err := s.remoteComponentCreator.newInbox(ctx, colmem.NewAllocator(ctx, s.newStreamingMemAccount(flowCtx), factory), input.ColumnTypes, inputStream.StreamID)
> ```

nit: this line is now longer than 100 characters.
___
*[pkg/sql/colflow/vectorized_flow_shutdown_test.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC9-vuP0InnFvI6S_4_:-MC9-vuP0InnFvI6S_4a:br2108s) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a31e41bf291842cc5967ffa5f827f2e7add839/pkg/sql/colflow/vectorized_flow_shutdown_test.go#L210)):*
> ```Go
> 					inboxMemAccount := testMemMonitor.MakeBoundAccount()
> 					defer inboxMemAccount.Close(ctxLocal)
> 					inbox, err := colrpc.NewInbox(context.Background(), colmem.NewAllocator(ctxLocal, &inboxMemAccount, testColumnFactory), typs, execinfrapb.StreamID(streamID))
> ```

nit: it'd probably be nice to have a separate `ctxFlow` variable or something.

Also the line is too long.
___
*[pkg/sql/colflow/vectorized_flow_shutdown_test.go, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC90-Of7r_hs4fNNSUE:-MC90-Of7r_hs4fNNSUF:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a31e41bf291842cc5967ffa5f827f2e7add839/pkg/sql/colflow/vectorized_flow_shutdown_test.go#L300)):*
> ```Go
> 					inboxMemAccount := testMemMonitor.MakeBoundAccount()
> 					defer inboxMemAccount.Close(ctxAnotherRemote)
> 					inbox, err := colrpc.NewInbox(context.Background(), colmem.NewAllocator(ctxAnotherRemote, &inboxMemAccount, testColumnFactory), typs, execinfrapb.StreamID(streamID))
> ```

ditto
___
*[pkg/sql/colflow/colrpc/inbox.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC90RwQ8AByDkWzahlE:-MC90RwQ8AByDkWzahlF:bvcpkfb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a31e41bf291842cc5967ffa5f827f2e7add839/pkg/sql/colflow/colrpc/inbox.go#L203)):*
> ```Go
> 		return fmt.Errorf("%s: streamCtx while waiting for reader (remote client canceled)", streamCtx.Err())
> 	case <-i.flowCtx.Done():
> 		return fmt.Errorf("%s: flowCtx while waiting for reader (remote client canceled)", i.flowCtx.Err())
> ```

I don't thinks it's "remote client" canceled, right?

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51375)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/routers.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC8zRmw6Lx5xPm16yGE:-MCBZtv2232BtlEVJn0I:b-18srve) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ef6eb48f5e18b6091f6291022eb195ce468414/pkg/sql/colexec/routers.go#L352)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Is it possible that `o.mu.forwardedErr` is already non-nil here?
</blockquote></details>

Yes, although not in practice. I think it's fine to overwrite the error in this case, added a comment. What do you think?
___
*[pkg/sql/colexec/routers_test.go, line 715 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC9-0Pl2log70BF9uL-:-MCB_qr877tiVPRllW8u:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ef6eb48f5e18b6091f6291022eb195ce468414/pkg/sql/colexec/routers_test.go#L715)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

super nit: maybe `s/verify/assert/`.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/routers_test.go, line 719 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC9-DX-B4nGiJiKTpTM:-MCBa2tP4ZNpqCAv4BL_:bu7tvcp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ef6eb48f5e18b6091f6291022eb195ce468414/pkg/sql/colexec/routers_test.go#L719)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think we're actually missing a check that at least one output got the error: the way I see it right now, it is possible that `forwardedErr` of all outputs is `nil`, and we don't fail the test.
</blockquote></details>

Done. It actually doesn't make sense to verify this in this test (since we're using a mock output and we'd just be testing testing code). This behavior is tested in the randomized test.
___
*[pkg/sql/colflow/vectorized_flow.go, line 733 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC9-ncGClvTlsBjVFoA:-MCBd-NNASqRrlxAbtW6:b139ah) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a31e41bf291842cc5967ffa5f827f2e7add839/pkg/sql/colflow/vectorized_flow.go#L733)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: this line is now longer than 100 characters.
</blockquote></details>

Shouldn't a linter would catch this? Done.
___
*[pkg/sql/colflow/vectorized_flow_shutdown_test.go, line 210 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC9-vuP0InnFvI6S_4_:-MCBdd8x23-y4EDf048r:b-f4nrin) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a31e41bf291842cc5967ffa5f827f2e7add839/pkg/sql/colflow/vectorized_flow_shutdown_test.go#L210)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: it'd probably be nice to have a separate `ctxFlow` variable or something.

Also the line is too long.
</blockquote></details>

Changed to use the test flow contexts which I think is the actual thing.
___
*[pkg/sql/colflow/vectorized_flow_shutdown_test.go, line 300 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC90-Of7r_hs4fNNSUE:-MCBdkyD-IjEku1XfT7b:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a31e41bf291842cc5967ffa5f827f2e7add839/pkg/sql/colflow/vectorized_flow_shutdown_test.go#L300)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/colflow/colrpc/inbox.go, line 203 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC90RwQ8AByDkWzahlE:-MCBdzPH9bdAg54v4Wee:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a31e41bf291842cc5967ffa5f827f2e7add839/pkg/sql/colflow/colrpc/inbox.go#L203)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't thinks it's "remote client" canceled, right?
</blockquote></details>

Done.

**Comment by asubiotto** [comment]
This is no longer a WIP. Will look into adding a test case for https://github.com/cockroachlabs/support/issues/513

**Comment by rohany** [comment]
Let me know if you need help reproing / explaining what I've found

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 5 of 11 files at r4, 7 of 7 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51375)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/routers.go, line 352 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC8zRmw6Lx5xPm16yGE:-MCDYHvo89DvQlFLxaB4:b-81nlyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5ef6eb48f5e18b6091f6291022eb195ce468414/pkg/sql/colexec/routers.go#L352)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Yes, although not in practice. I think it's fine to overwrite the error in this case, added a comment. What do you think?
</blockquote></details>

SGTM.
___
*[pkg/sql/colflow/vectorized_flow.go, line 733 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MC9-ncGClvTlsBjVFoA:-MCDYPPs92-TxMl_tthg:b3jlida) ([raw file](https://github.com/cockroachdb/cockroach/blob/c9a31e41bf291842cc5967ffa5f827f2e7add839/pkg/sql/colflow/vectorized_flow.go#L733)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Shouldn't a linter would catch this? Done.
</blockquote></details>

I don't think we have a linter for that, I have set up Goland to show lines at 80 and 100 characters as our style guide says that we should aim for no more than 80 characters per line, and 100 characters is a pretty hard limit.
___
*[pkg/sql/rowexec/processors_test.go, line 714 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MCD_1ZF1rSmpt_iS0L7:-MCD_1ZF1rSmpt_iS0L8:b-d86m21) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab616d9becfa30660c52165c207ca394386f3237/pkg/sql/rowexec/processors_test.go#L714)):*
> ```Go
> 	)
> 
> 	// Best thing to do in this case I think is to
> ```

nit: incomplete comment.
___
*[pkg/sql/rowexec/processors_test.go, line 783 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MCDa4tM5utSWPdpvXKb:-MCDa4tM5utSWPdpvXKc:bmg8rux) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab616d9becfa30660c52165c207ca394386f3237/pkg/sql/rowexec/processors_test.go#L783)):*
> ```Go
> 		// overrideErrorOrigin, if set, enables the request filter on the node
> 		// indices provided.
> 		overrideErrorOrigin func() int
> ```

Do you intend to add more test cases that actually use `overrideErrorOrigin` and `overrideConn` knobs?

**Review by asubiotto — COMMENTED** [review]
Added a skipped test that repros #51458. There still seems to be an issue where we're overwriting an uncertainty error with context canceled somewhere. I'll look into this but I'm also happy to get this in with a small change to not fail in this case before I leave and investigate when I'm back.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-:-MCHo57NCQYDMQy8zvWn:b-g0dr96)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/rowexec/processors_test.go, line 783 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/51375#-MCDa4tM5utSWPdpvXKb:-MCHnpOf-PrHsnalTOAT:b-kwcsi0) ([raw file](https://github.com/cockroachdb/cockroach/blob/ab616d9becfa30660c52165c207ca394386f3237/pkg/sql/rowexec/processors_test.go#L783)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do you intend to add more test cases that actually use `overrideErrorOrigin` and `overrideConn` knobs?
</blockquote></details>

Removed `overrideConn`, but I'm using `overrideErrorOrigin` in a new test I added that simulates #51458

**Comment by yuzefovich** [comment]
I took a quick glance at why we're seeing context cancellation error instead of the expected RWUI error, and nothing jumped out to me, so I added a skip for `vectorize=true` config.

bors r=yuzefovich

**Comment by yuzefovich** [comment]
bors crashed

bors r=yuzefovich

**Pull request merged**
