### PR TITLE
sql: divide udf logic tests into separate files

### LINKED ISSUE #106471: pkg/sql/logictest/tests/fakedist/fakedist_test: TestLogic_udf failed
pkg/sql/logictest/tests/fakedist/fakedist_test.TestLogic_udf [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/10835929?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_BazelUnitTests/10835929?buildTab=artifacts#/) on master @ [43c26aec0072f76e02e6d5ffc1b7079026b24630](https://github.com/cockroachdb/cockroach/commits/43c26aec0072f76e02e6d5ffc1b7079026b24630):

Fatal error:

```
panic: test timed out after 14m55s

```
Stack: 

```
goroutine 730556 [running]:
testing.(*M).startAlarm.func1()
	GOROOT/src/testing/testing.go:2036 +0x8e
created by time.goFunc
	GOROOT/src/time/sleep.go:176 +0x32
```
<details><summary>Log preceding fatal error</summary>
<p>

```
=== RUN   TestLogic_udf/regression_93314
[06:20:37] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/udf: 496 statements
    logictestbase.go:488: statement/query skipped with reason: unsupported configuration fakedist, statement/query only supports local (no issue given)
=== RUN   TestLogic_udf/variadic
=== RUN   TestLogic_udf/array_flatten
=== RUN   TestLogic_udf/ddl
=== RUN   TestLogic_udf/execution
[06:18:27] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/udf: 351 statements
=== RUN   TestLogic_udf/regression_104927
=== RUN   TestLogic_udf/udf_regproc
=== RUN   TestLogic_udf/cross_db
=== RUN   TestLogic_udf/disallow_udf_in_table
=== RUN   TestLogic_udf/return_type_assignment_casts
=== RUN   TestLogic_udf/udf_with_unresolved_names
=== RUN   TestLogic_udf/volatility
=== RUN   TestLogic_udf/disallow_udf_in_views_and_udf
=== RUN   TestLogic_udf/seq_qualified_name
=== RUN   TestLogic_udf/show_grants
[06:18:24] --- progress: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/udf: 310 statements
=== RUN   TestLogic_udf/subquery
=== RUN   TestLogic_udf/udf_create_privilege
=== RUN   TestLogic_udf/drop_function
=== RUN   TestLogic_udf/event_logging
    logictestbase.go:488: statement/query skipped with reason: unsupported configuration fakedist, statement/query only supports local-legacy-schema-changer (no issue given)
    logictestbase.go:488: statement/query skipped with reason: unsupported configuration fakedist, statement/query only supports local-legacy-schema-changer (no issue given)
    logictestbase.go:488: statement/query skipped with reason: unsupported configuration fakedist, statement/query only supports local-legacy-schema-changer (no issue given)
    logictestbase.go:488: statement/query skipped with reason: unsupported configuration fakedist, statement/query only supports local-legacy-schema-changer (no issue given)
    logictestbase.go:488: statement/query skipped with reason: unsupported configuration fakedist, statement/query only supports local-legacy-schema-changer (no issue given)
    logictestbase.go:488: statement/query skipped with reason: unsupported configuration fakedist, statement/query only supports local-legacy-schema-changer (no issue given)
    logictestbase.go:488: statement/query skipped with reason: unsupported configuration fakedist, statement/query only supports local-legacy-schema-changer (no issue given)
=== RUN   TestLogic_udf/regression_97130
    logic.go:2952: let $pre_search_path = public
=== RUN   TestLogic_udf/regression_tests
=== RUN   TestLogic_udf/show_create_function
=== RUN   TestLogic_udf/alter_function_name
=== RUN   TestLogic_udf/alter_function_options
=== RUN   TestLogic_udf/args
=== RUN   TestLogic_udf/execute_dropped_function
=== RUN   TestLogic_udf/regression_100915
=== RUN   TestLogic_udf/regression_95364
    logic.go:2952: let $dropped_fn_id = 284
    logic.go:2952: let $dropped_fn_id = 287
    logic.go:2952: let $dropped_fn_id = 289
=== RUN   TestLogic_udf/cte
=== RUN   TestLogic_udf/udf_under_virtual_or_temp_schemas_102964
    logic.go:2952: let $temp_schema_102964 = pg_temp_1688796944953548129_1
=== RUN   TestLogic_udf/udt_rewrite
=== RUN   TestLogic_udf/alter_function_owner
=== RUN   TestLogic_udf/end#01
[06:20:43] --- done: /home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/6326/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/sql/logictest/tests/fakedist/fakedist_test_/fakedist_test.runfiles/com_github_cockroachdb_cockroach/pkg/sql/logictest/testdata/logic_test/udf with config fakedist: 592 tests, 0 failures
```
</p>
</details>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/sql-queries
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestLogic_udf.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-29576

### PR DESCRIPTION
**Pull request by rharding6373**
Break up the UDF logic test into multiple files based on functionality in order to reduce risk of timeouts in long-running configurations.

Epic: none
Fixes: #106471

Release note: none

### CODE REVIEW

**Comment by rharding6373** [comment]
You can hold off on reviewing until I've added some of the newly proposed logic test style to the new test files (i.e., use subtest end, include pg error codes).

**Comment by mgartner** [comment]
> You can hold off on reviewing until I've added some of the newly proposed logic test style to the new test files (i.e., use subtest end, include pg error codes).

👍 Nice! But if that becomes onerous, don't feel obligated to clean all that up now.

**Comment by rharding6373** [comment]
Ready for review now. I did not investigate the few questionable pg error codes yet, opting to leave them as a TODO for https://github.com/cockroachdb/cockroach/issues/107369.

**Review by mgartner — APPROVED** [review]
Thanks for doing this! Looks like it was very tedious... :lgtm: 

> Reviewed 1 of 16 files at r1, 21 of 21 files at r2, 17 of 17 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106729#-:-N_uAE3L-QahI8-ulEOa:bciv7qv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rharding6373)

**Comment by rharding6373** [comment]
TFTR!

I wrote a script [0] to try to make parts of the logic tests runnable in postgres to try to get the expected error codes, which was somewhat helpful but far from 100%. Needs some tweaking before it could be used to get error codes for all logic tests. Or maybe there's an easier way to run logic tests against postgres.

[0] https://gist.github.com/rharding6373/c6982084a2f810ebc8b754cd179a98bb

**Comment by rharding6373** [comment]
Bors says that CI for this batch succeeded, but the overall state failed: https://bors.crdb.dev/batches/35879, which seems like a test infra problem.

Going to try one more time, since it seems like the UDF logic tests themselves finished well under the timeout.

bors r+

**Pull request merged**
