### PR TITLE
admission,storage: change elastic shaping to start at score represent…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…ing sublevel 2

There is an interaction between AC shaping and the dynamic adjustment of the number of concurrent compactions, in that we don't want AC to aggressively shape before we have increased to the maximum number of concurrent compactions (if increasing to this maximum number does not affect foreground latency by saturating CPU or IO bandwidth). The elastic shaping used to start when sub-levels were >= 1, which ignored this interaction, since at that point we may only have 1 concurrent compaction.

The fix here does not change the fact that ioLoadListener uses constants for much of its overload computation, but does have a long comment on how these two behaviors interact and how one can probably achieve desired behavior by fiddling with
COCKROACH_L0_SUB_LEVEL_CONCURRENCY.

Epic: none

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111213)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @jbowens)

___
*[`pkg/util/admission/testdata/io_load_listener` line 718 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfI7o0a0_yNx9zLClEE:-NfI7o0a0_yNx9zLClEF:b-8mnwkc) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5258fb71c03c331b9ca8709dc1237f2369085de/pkg/util/admission/testdata/io_load_listener#L718)):*
> ```
> 
> # Score is decided by max sub-levels, which is 50000/5000=10. So score is 10/20=0.5.
> set-state l0-bytes=50000 l0-added-write=260994 l0-files=21 l0-sublevels=21 print-only-first-tick=true
> ```

I had to fiddle with this l0-added-write input since the float calculation on my mac M1 is slightly different than on gceworker (and CI) so the test would fail on CI.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111213)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfOYE5HB70RcLhDBVgB:-NfOYE5HB70RcLhDBVgC:bfhv2or) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5258fb71c03c331b9ca8709dc1237f2369085de/pkg/storage/mvcc.go#L164)):*
> ```Go
> // For elastic traffic, admission control starts shaping traffic at sub-level
> // count of 2, with tokens equal to 1.25x the compaction bandwidth (tokens
> // representative of 1.25*floor(1+2/2)=2.5 compaction concurrency), and at
> ```

I think I understand what this entire pr is saying, but it's pretty hard to understand even given the context I have. Maybe I'm misunderstanding too.

Basically, AC will try and stabilize at 10 sublevels, so if we increase compaction concurrency to something like 10, but keep `l0SubLevelCompactionConcurrency` at 2, we will allow only upto 6(1 + 10/2) concurrency in Pebble, even though MaxConcurrentCompactions is set to 10. We want Pebble to be able to use more concurrency.

Some thoughts and confusion:

At 6 sublevels, tokens are equal to 0.75x times the compaction bandwidth. Number of concurrent compactions pebble will allow is 4. So, we may grant tokens representative of up to 3 compaction concurrency for elastic work. I don't understand how the previous statement interacts with the fact that pebble will actually cap compaction concurrency to 3. So, we're only granting tokens representative of 0.75x * 3 = 2.25 compaction concurrency.

Let's say we increase pebble compaction concurrency to 10, but do not increase `l0SubLevelCompactionConcurrency`. Let's say we're at 6 sublevels. Pebble has an allowed compaction concurrency of (1 + 6/2) = 4. So, we'll allow tokens representative of up to 3 concurrency.
___
*[`pkg/util/admission/io_load_listener.go` line 944 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfJ21cI0jVOuz2XFDEC:-NfJ21cI0jVOuz2XFDED:bydtbdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5258fb71c03c331b9ca8709dc1237f2369085de/pkg/util/admission/io_load_listener.go#L944)):*
> ```Go
> 	// NB: score == (num-sublevels / 20) * 2 = num-sublevels/10 (we are ignoring
> 	// the rare case where score is determined by file count). So score >= 0.2
> 	// means that we start shaping when there is 2 sublevel.
> ```

there are 2 sublevels

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-:-NfRjGXr19kzydp_Rgza:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @jbowens)

___
*[`pkg/storage/mvcc.go` line 164 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfOYE5HB70RcLhDBVgB:-NfR5BXy01AULE_WYqTK:b1d8abn) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5258fb71c03c331b9ca8709dc1237f2369085de/pkg/storage/mvcc.go#L164)):*

The following sentence was the key
```
// This upper bound computation is important, since an upper bound that is
// not high enough will cause admission control to give out fewer tokens and
// thereby shape traffic before we have an opportunity to increase the compaction
// concurrency to accommodate that traffic.
```

Your understanding in the first para is correct.

But this is more nuanced than what I wrote earlier. I've completely rewritten the comment and added some ascii art, which crlfmt keeps trying to ruin :-(

> At 6 sublevels, tokens are equal to 0.75x times the compaction bandwidth. Number of concurrent compactions pebble will allow is 4. So, we may grant tokens representative of up to 3 compaction concurrency for elastic work. I don't understand how the previous statement interacts with the fact that pebble will actually cap compaction concurrency to 3. So, we're only granting tokens representative of 0.75x \* 3 = 2.25 compaction concurrency.

This is one of the problems that the new description fixes. The objective stated in terms of `upper-bound-ac-tokens` only looks at that value until `upper-bound-cc` reaches `MaxConcurrentCompactions`.
___
*[`pkg/util/admission/io_load_listener.go` line 944 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfJ21cI0jVOuz2XFDEC:-NfRemfy2C6SPOirThZn:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b5258fb71c03c331b9ca8709dc1237f2369085de/pkg/util/admission/io_load_listener.go#L944)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

there are 2 sublevels
</blockquote></details>

Done.

**Review by bananabrick — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111213)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jbowens and @sumeerbhola)

___
*[`pkg/storage/mvcc.go` line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfTCyL28n8oJqn-ORKf:-NfTCyL28n8oJqn-ORKg:b-knmrw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e859678612b67f0ba4741014ca4a80b6a255adae/pkg/storage/mvcc.go#L183)):*
> ```Go
> // tokens that shape the incoming traffic. The tokens are a function of l and
> // the measured compaction bandwidth out of L0. But the measured compaction
> // bandwidth is itself a function of the tokens and upper-bound-cc(l) and
> ```

nit: (l, lscc)
___
*[`pkg/storage/mvcc.go` line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfTE8hoA8NZ0qxe9Yjy:-NfTE8hoA8NZ0qxe9Yjz:b-knmrw0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e859678612b67f0ba4741014ca4a80b6a255adae/pkg/storage/mvcc.go#L192)):*
> ```Go
> // tokens, and this will repeat until Pebble has no ability to further
> // increase the compaction bandwidth. This simple analysis suffices when
> // upper-bound-cc(l) is always infinity since Pebble can increase up to
> ```

nit: (l, lscc)
___
*[`pkg/storage/mvcc.go` line 248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfTKJM51Z0vRsBhjczB:-NfTKJM51Z0vRsBhjczC:b-gdk0qt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e859678612b67f0ba4741014ca4a80b6a255adae/pkg/storage/mvcc.go#L248)):*
> ```Go
> // simplification), which we can write as ac-tokens(l,
> // permitted-concurrent-compactions). Furthermore, we consider a value
> // upper-bound-ac-tokens, which is a function of only l and upper-bound-cc,
> ```

I think rather than calling this `upper-bound-ac-tokens`, we should just call it `ac-tokens`, but treat ac tokens as a piecewise function.

When `upper-bound-cc` is less than `MaxConcurrentCompactions`, the function is `ac-tokens(l, upper-bound-cc)` and when upper-bound-cc is >= `MaxConcurrentCompactions`, the function is `ac-tokens(l, MaxConcurrentCompactions).

Thinking about it that way makes it clearer for me.
___
*[`pkg/storage/mvcc.go` line 254 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfTNd8d7SLljdFUPF0w:-NfTNd8d7SLljdFUPF0x:b-snhod0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e859678612b67f0ba4741014ca4a80b6a255adae/pkg/storage/mvcc.go#L254)):*
> // it should be equal to or greater than upper-bound-cc when
> // upper-bound-cc becomes equal to MaxConcurrentCompactions

If `upper-bound-ac-tokens` is greater than `upper-bound-cc` once `upper-bound-cc` is equal to max concurrent compactions, then sublevels will increase, and upper-bound-ac-tokens will go down. Just stating this for myself.
___
*[`pkg/storage/mvcc.go` line 270 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfTMXOa5nj-8c7amzO4:-NfTMXOa5nj-8c7amzO5:bvj7g4k) ([raw file](https://github.com/cockroachdb/cockroach/blob/e859678612b67f0ba4741014ca4a80b6a255adae/pkg/storage/mvcc.go#L270)):*
> Note that the objective does not say anything about upper-bound-ac-tokens
> // after upper-bound-cc reaches MaxConcurrentCompactions

This is confusing. The objective states:
```
// upper-bound-ac-tokens should be greater than upper-bound-cc as l increases,
// and it should be equal to or greater than upper-bound-cc when
// upper-bound-cc becomes equal to MaxConcurrentCompactions.
```

So it is stating what `upper-bound-ac-tokens` should be once `upper-bound-cc` reaches `MaxConcurrentCompactions`.

Maybe this should be states as "Note that the objective does not say anything about upper-bound-ac-tokens
// after upper-bound-cc becomes greater than MaxConcurrentCompactions ..."

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111213)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bananabrick and @jbowens)

___
*[`pkg/storage/mvcc.go` line 183 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfTCyL28n8oJqn-ORKf:-NfX6EJk5FEqyZeh1VfQ:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e859678612b67f0ba4741014ca4a80b6a255adae/pkg/storage/mvcc.go#L183)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: (l, lscc)
</blockquote></details>

Done
___
*[`pkg/storage/mvcc.go` line 192 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfTE8hoA8NZ0qxe9Yjy:-NfX6ExI3ZxcjvtVdFdo:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/e859678612b67f0ba4741014ca4a80b6a255adae/pkg/storage/mvcc.go#L192)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

nit: (l, lscc)
</blockquote></details>

Done
___
*[`pkg/storage/mvcc.go` line 248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfTKJM51Z0vRsBhjczB:-NfX9N2FBB1eMZ8MyDn8:b-6bqk6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/e859678612b67f0ba4741014ca4a80b6a255adae/pkg/storage/mvcc.go#L248)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

I think rather than calling this `upper-bound-ac-tokens`, we should just call it `ac-tokens`, but treat ac tokens as a piecewise function.

When `upper-bound-cc` is less than `MaxConcurrentCompactions`, the function is `ac-tokens(l, upper-bound-cc)` and when upper-bound-cc is >= `MaxConcurrentCompactions`, the function is `ac-tokens(l, MaxConcurrentCompactions).

Thinking about it that way makes it clearer for me.
</blockquote></details>

Good idea. Done. This makes the examples below a bit more involved since they need to say things like min(6,MaxConcurrentCompactions) but overall I think this is clearer.
___
*[`pkg/storage/mvcc.go` line 270 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-NfTMXOa5nj-8c7amzO4:-NfX9laXDFqCqt23pT2k:b9dfuu3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e859678612b67f0ba4741014ca4a80b6a255adae/pkg/storage/mvcc.go#L270)):*
<details><summary><i>Previously, bananabrick (Arjun Nair) wrote…</i></summary><blockquote>

> Note that the objective does not say anything about upper-bound-ac-tokens
> // after upper-bound-cc reaches MaxConcurrentCompactions

This is confusing. The objective states:
```
// upper-bound-ac-tokens should be greater than upper-bound-cc as l increases,
// and it should be equal to or greater than upper-bound-cc when
// upper-bound-cc becomes equal to MaxConcurrentCompactions.
```

So it is stating what `upper-bound-ac-tokens` should be once `upper-bound-cc` reaches `MaxConcurrentCompactions`.

Maybe this should be states as "Note that the objective does not say anything about upper-bound-ac-tokens
// after upper-bound-cc becomes greater than MaxConcurrentCompactions ..."
</blockquote></details>

Rephrased.

**Review by bananabrick — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111213#-:-Nfi070P-5xCy8_GhibQ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jbowens)

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=bananabrick

**Pull request merged**
