### PR TITLE
authors: add michae2 to authors

### PR DESCRIPTION
**Pull request by michae2**
Release note: None

### CODE REVIEW

**Review by jlinder — APPROVED** [review]

**Comment by michae2** [comment]
bors ping

**Comment by michae2** [comment]
bors retry

**Comment by michae2** [comment]
bors delegate+

**Comment by michae2** [comment]
Does this work?
bors ping

**Comment by michae2** [comment]
Having trouble with the GitHub status checks, so I'm closing this pull request and will open another.

**Pull request closed without merging**
