### PR TITLE
upgrades: migrate old-style PTS records

### PR DESCRIPTION
**Pull request by jayshrivastava**
This change adds an upgrade for 24.1 which migrates all old-style
protected timestamp records. This is done through a migration
which reads all PTS records which are protecting spans. These
spans are decoded so all targeted table IDs can be targeted.
Then, each record is updated to store targets instead of spans.

Release note: None
Epic: None
Informs: https://github.com/cockroachdb/cockroach/issues/82888

### CODE REVIEW

**Comment by jayshrivastava** [comment]
For more context, this needs to go in for https://github.com/cockroachdb/cockroach/pull/112093 to work correctly. 

We want to stop updating the PTS meta table. If we stop, the cache will stop updating. If the cache stops updating, replicas will keep seeing old timestamps in the PTS cache. Ultimately, we must stop reading from the cache / disable the cache. To do this, my plan is to make sure all old-style PTS records are migrated in 24.1, and have a version gate which disables the cache in 24.1. Under the same version gate, we will stop writing to the meta table.

**Review by rharding6373 — COMMENTED** [review]
Nice work! I have a handful of questions/comments.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-:-Nq-_qX7-tYQ4YBVLdco:b-ksxx0t)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @jayshrivastava)

___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-WpT5-IIZUkeeNhTC:-Nq-WpT5-IIZUkeeNhTD:bip5wzw) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records.go#L49)):*
> ```Go
> 		err := deps.DB.Txn(ctx, func(ctx context.Context, txn isql.Txn) error {
> 			rows, err := txn.QueryBufferedEx(ctx, "pts-migration-read-record", txn.KV(), sessiondata.NodeUserSessionDataOverride,
> 				"SELECT spans FROM system.protected_ts_records WHERE id = $1", id)
> ```

Is it possible that a new id is added to `system.protected_ts_records` while the migration is happening?
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records.go` line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-D8uQ8wDAMdAD6Rp_:-Nq-D8uQ8wDAMdAD6Rpa:btytulu) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records.go#L104)):*
> ```Go
> 
> 			_, err = txn.ExecEx(ctx, "pts-migration-write-record", txn.KV(), sessiondata.NodeUserSessionDataOverride,
> 				"UPDATE system.protected_ts_records SET spans = $3, target = $2 WHERE id = $1", id, encodedTarget, encodedTarget)
> ```

nit: this order of placement variables is confusing. Is it possible to put them in order (i.e., $1 then $2 then $3)?
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-aHyvBssVTEXr80le:-Nq-aHyvBssVTEXr80lf:b-3ba9tu) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L81)):*
> ```Go
> 		_, err = sqlDB.Exec(fmt.Sprintf("create table table_%d (i int)", i))
> 		require.NoError(t, err)
> 		_, err = sqlDB.Exec(fmt.Sprintf("create changefeed for table_%d INTO 'null://'", i))
> ```

Should we also add some CFs with queries? Or do they not matter since they weren't supported in <22.1?
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-NpzddKy5aICNXrk9LCe:-NpzddKy5aICNXrk9LCf:br92znf) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L90)):*
> ```Go
> 		descIDsArr = append(descIDsArr, tableDesc.GetID())
> 	}
> 	_, err = sqlDB.Exec("create changefeed for table_0, table_1, table_2, table_3, table_4," +
> ```

nit: instead of listing out "table_0, table_1", etc., you could create/append the table names a string in the loop above. Then if we ever want to change the test it's less brittle.
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-NpzeeIY-HKX05AGsJ-6:-NpzeeIY-HKX05AGsJ-7:b-usq4vx) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L93)):*
> ```Go
> 		"table_5, table_6, table_7, table_8, table_9 INTO 'null://'")
> 	require.NoError(t, err)
> 	descIDsArr = append(descIDsArr, keys.DescriptorTableID)
> ```

Why is the descriptor table part of the targets?
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-7VNV1E6-HvxPlNhU:-Nq-7VNV1E6-HvxPlNhV:bqeu4ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L99)):*
> ```Go
> 	allTargets = append(allTargets, descIDsArr)
> 
> 	upgrades.Upgrade(
> ```

Before upgrading, it would be good to validate that we have PTS entries in the old style.
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-Ak5t3y4NpqwS1iKL:-Nq-Ak5t3y4NpqwS1iKM:b-jt6jwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L133)):*
> ```Go
> 			return false
> 		}
> 		return a[1] < b[1]
> ```

Is it guaranteed that len(a) > 1 and len(b) > 1? Is this making an assumption that there are always two and only two ids in each seenTargets slice?

**Review by jayshrivastava — COMMENTED** [review]
Thanks! Posted replies below.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-:-Nq818xQ95Jzqbf4lDKJ:btsza7d)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt and @rharding6373)

___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-WpT5-IIZUkeeNhTC:-Nq7wN7L2abeEqCS4KR_:blgny3k) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records.go#L49)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Is it possible that a new id is added to `system.protected_ts_records` while the migration is happening?
</blockquote></details>

Yes, but that's okay because it's guaranteed that the new record will have the new format, so we would ignore them anywaysstorage. 
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 81 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-aHyvBssVTEXr80le:-Nq7x4Vg2wLI3IylBHNN:btqw40u) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L81)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Should we also add some CFs with queries? Or do they not matter since they weren't supported in <22.1?
</blockquote></details>

Yup they should not matter because they are old. You also cannot currently alter the targets of a changefeed which has a select statement https://github.com/cockroachdb/cockroach/blob/8b27376208229124d2a2b5138ed00f14e8c14567/pkg/ccl/changefeedccl/alter_changefeed_stmt.go#L481-L487
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-NpzddKy5aICNXrk9LCe:-Nq7yU9K7F-4nYvHvbkO:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L90)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

nit: instead of listing out "table_0, table_1", etc., you could create/append the table names a string in the loop above. Then if we ever want to change the test it's less brittle.
</blockquote></details>

Done!
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-NpzeeIY-HKX05AGsJ-6:-Nq7xVSw4Xl3fKo3mOI9:b-wrtgt4) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L93)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Why is the descriptor table part of the targets?
</blockquote></details>

All changefeeds do this to ensure schema history is available. For an event at time t, we need to read the schema at time t before emitting it. This is done by the schema feed. 
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-7VNV1E6-HvxPlNhU:-Nq815gQ3_U-B5U6HD6U:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L99)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Before upgrading, it would be good to validate that we have PTS entries in the old style.
</blockquote></details>

Done.
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-Ak5t3y4NpqwS1iKL:-Nq7z4HyCfo62XhNkziN:b-fv46en) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L133)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

Is it guaranteed that len(a) > 1 and len(b) > 1? Is this making an assumption that there are always two and only two ids in each seenTargets slice?
</blockquote></details>

Ill add a comment. 10 of the changefeeds are protecting 2 tables each (table_n + descriptor table). The last one is protecting 10 tables + the descriptor table.

**Review by rharding6373 — APPROVED** [review]
:lgtm: Looks good! Only one optional nit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-:-Nq9IjmX6ia0TYJonBpD:b-olzrcy)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @dt and @jayshrivastava)

___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records.go` line 49 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-WpT5-IIZUkeeNhTC:-Nq9H45z1kD3eMtqqGn6:b513kxn) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records.go#L49)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Yes, but that's okay because it's guaranteed that the new record will have the new format, so we would ignore them anywaysstorage.
</blockquote></details>

Thanks for the info!
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-NpzddKy5aICNXrk9LCe:-Nq9Hei-4dThP_kqN71c:b-4iwmu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L90)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Done!
</blockquote></details>

follow up nit: make a variable `tbl := fmt.Sprintf("table_%d", i)` and use that throughout the body of the loop
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 93 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-NpzeeIY-HKX05AGsJ-6:-Nq9HwEv7_8uG6TxebOy:bcr5s2o) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L93)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

All changefeeds do this to ensure schema history is available. For an event at time t, we need to read the schema at time t before emitting it. This is done by the schema feed.
</blockquote></details>

Got it, thanks!
___
*[`pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go` line 133 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/118772#-Nq-Ak5t3y4NpqwS1iKL:-Nq9IceQ7Co8F9mILQoi:bi7asgm) ([raw file](https://github.com/cockroachdb/cockroach/blob/efb21ef61addd9d8c737ac71f2ac17f9281d2e35/pkg/upgrade/upgrades/v24_1_migrate_pts_records_test.go#L133)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Ill add a comment. 10 of the changefeeds are protecting 2 tables each (table_n + descriptor table). The last one is protecting 10 tables + the descriptor table.
</blockquote></details>

Oh I see now. Thanks!

**Comment by jayshrivastava** [comment]
TYFR!

**Comment by jayshrivastava** [comment]
bors r=rharding6373

**Pull request merged**
