### PR TITLE
sql: basic ARRAY support + CURRENT_SCHEMAS()

### PR DESCRIPTION
**Pull request by cuongdo**
This is to progress further with ActiveRecord initialization. I haven't actually tested this against ActiveRecord, because to do that I need @nvanbenschoten's  `pg_catalog` changes, which haven't been merged). However, I've tested that `psql` can successfully display the result of `SELECT CURRENT_SCHEMAS(true|false)`, and I've added a SQL logic test.

This is out for early feedback.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9604)

### CODE REVIEW

**Comment by knz** [comment]
@nvanbenschoten I don't know what you think but it feels like it's soon time to start thinking about algebraic types a bit more, i.e. having separate type structs for tuples/arrays of different element types. This will enable between other things to refuse "(int, string)  = (string, int)" during typing and not evaluation, and support array types more fully (including arrays of arrays).

---

Reviewed 7 of 7 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/builtins.go, line 773 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSn58ZOkeN1UDXYftNS:-KSn58ZOkeN1UDXYftNT:b2uy59s) ([raw file](https://github.com/cockroachdb/cockroach/blob/b866a047237c3eef2ec8561c7729eb5085614113/sql/parser/builtins.go#L773)):*
> ```Go
> 		Builtin{
> 			Types:      ArgTypes{TypeBool},
> 			ReturnType: TypeString,
> ```

I think the ReturnType should be TypeArray here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-:-KSn5c1JDKfgTSVS563g:bis49tl)*

**Comment by nvanbenschoten** [comment]
:lgtm: but because of the reference to `pg_catalog`, this should probably wait on #9565.

@knz I agree that we're going to need some notion of algebraic types soon. For instance, I'm not sure how we would currently enforce a function that takes `int[]` during type checking. I think we'd have to defer to enforcing the parametrized type constraint during evaluation.

---

Reviewed 7 of 7 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[sql/parser/builtins.go, line 779 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSqnHT7k4r1SiOv4yZM:-KSqnHT8HupUYElF2D6-:b-9p8wd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b866a047237c3eef2ec8561c7729eb5085614113/sql/parser/builtins.go#L779)):*
> ```Go
> 					schemas = append(schemas, NewDString(ctx.Database))
> 				}
> 				if args[0].(*DBool) == DBoolTrue {
> ```

Assign `args[0].(*DBool)` to a well-named variable so that it's clearer what the parameter is used for.

---

*[sql/parser/builtins.go, line 779 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSqncFgYU_iDIF1S2-A:-KSqncFgYU_iDIF1S2-B:b-pmm68c) ([raw file](https://github.com/cockroachdb/cockroach/blob/b866a047237c3eef2ec8561c7729eb5085614113/sql/parser/builtins.go#L779)):*
> ```Go
> 					schemas = append(schemas, NewDString(ctx.Database))
> 				}
> 				if args[0].(*DBool) == DBoolTrue {
> ```

What will happen if I call `current_schemas(NULL)`?

---

*[sql/parser/builtins.go, line 780 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSqmz5g0pxaiOv80LCg:-KSqmz5g0pxaiOv80LCh:bhc8i1x) ([raw file](https://github.com/cockroachdb/cockroach/blob/b866a047237c3eef2ec8561c7729eb5085614113/sql/parser/builtins.go#L780)):*
> ```Go
> 				}
> 				if args[0].(*DBool) == DBoolTrue {
> 					schemas = append(schemas, NewDString("pg_catalog"))
> ```

Could you leave a comment that this is kind of a hack because we don't currently support a schema search path. On top of this, pg_catalog isn't even merged yet.

---

*[sql/parser/datum.go, line 1416 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSqnq7HnKUyFesovfkX:-KSqnq7InSR2TYZQ7Vmi:b-ub7gf7) ([raw file](https://github.com/cockroachdb/cockroach/blob/44d9c87f5b350d51e716730efc914e592571cf71/sql/parser/datum.go#L1416)):*
> ```Go
> // Type implements the Datum interface.
> func (*DArray) Type() string {
> 	return "text[]"
> ```

Throughout: one of our deviations from Postgres is that we use the term `string` over `text` by default. I think `string[]` would be more appropriate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-:-KSqp4vjlvmm9y4Qodmx:b9mbhz1)*

**Comment by cuongdo** [comment]
@nvanbenschoten: yes, I will wait on #9565 

---

Review status: 4 of 11 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 773 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSn58ZOkeN1UDXYftNS:-KSr6tlWGulZ-X1QO3pA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b866a047237c3eef2ec8561c7729eb5085614113/sql/parser/builtins.go#L773)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I think the ReturnType should be TypeArray here.
</details>
Done.

---

*[sql/parser/builtins.go, line 779 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSqnHT7k4r1SiOv4yZM:-KSrCcjhX-1cBwegwMPY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b866a047237c3eef2ec8561c7729eb5085614113/sql/parser/builtins.go#L779)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Assign `args[0].(*DBool)` to a well-named variable so that it's clearer what the parameter is used for.
</details>
Done.

---

*[sql/parser/builtins.go, line 779 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSqncFgYU_iDIF1S2-A:-KSrCd3o7HETBO5LB2Ax:b-uq0vsz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b866a047237c3eef2ec8561c7729eb5085614113/sql/parser/builtins.go#L779)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> What will happen if I call `current_schemas(NULL)`?
</details>
root@:26257> SELECT CURRENT_SCHEMAS(NULL);
pq: unknown signature for CURRENT_SCHEMAS: CURRENT_SCHEMAS(NULL)

This is different from Postgres, which returns NULL, but it's unclear to me what needs to be done here. Should I try to make it consistent?

---

*[sql/parser/builtins.go, line 780 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSqmz5g0pxaiOv80LCg:-KSrD2mUu9LB4LK4hgBP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b866a047237c3eef2ec8561c7729eb5085614113/sql/parser/builtins.go#L780)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Could you leave a comment that this is kind of a hack because we don't currently support a schema search path. On top of this, pg_catalog isn't even merged yet.
</details>
Done.

---

*[sql/parser/datum.go, line 1416 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSqnq7HnKUyFesovfkX:-KSrHWYkHbbUdp1GLqTv:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44d9c87f5b350d51e716730efc914e592571cf71/sql/parser/datum.go#L1416)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Throughout: one of our deviations from Postgres is that we use the term `string` over `text` by default. I think `string[]` would be more appropriate.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-:-KSrJpPFKQMBEbdJ-yeb:br8bjr9)*

**Comment by knz** [comment]
:lgtm:  modulo checking (with a test) this doesn't fall apart on nulls.

---

Reviewed 2 of 7 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 779 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSqncFgYU_iDIF1S2-A:-KSrKUtzReq82CMK6EB1:bvxi23v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b866a047237c3eef2ec8561c7729eb5085614113/sql/parser/builtins.go#L779)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> root@:26257> SELECT CURRENT_SCHEMAS(NULL);
> pq: unknown signature for CURRENT_SCHEMAS: CURRENT_SCHEMAS(NULL)
> 
> This is different from Postgres, which returns NULL, but it's unclear to me what needs to be done here. Should I try to make it consistent?
</details>
I think what Nathan had in mind was `current_schemas(null::bool)`  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-:-KSrKf_qOR7qblWjNIJL:b7i6mzv)*

**Comment by tamird** [comment]
As a courtesy, can this sit for a day after the prerequisite is merged? I'd
like to review it without the cognitive overhead of ignoring the pg_catalog
stuff.

**Comment by cuongdo** [comment]
@tamird: sure

---

Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[sql/parser/builtins.go, line 779 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KSqncFgYU_iDIF1S2-A:-KSrcbvdBQy7Vq7uHjVk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b866a047237c3eef2ec8561c7729eb5085614113/sql/parser/builtins.go#L779)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I think what Nathan had in mind was `current_schemas(null::bool)`  
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-:-KSrcnmkwsFDFw5P1Lnv:bjrwb9t)*

**Comment by knz** [comment]
:+1:

---

Review status: 9 of 11 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-:-KSrkO_P5HtkXZNdtg_Q:bb6mt9b)*

**Comment by nvanbenschoten** [comment]
Reviewed 2 of 7 files at r3, 3 of 5 files at r4, 2 of 2 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604)*

**Comment by tamird** [comment]
@cuongdo can you rebase this and test against AR before merging?

**Comment by cuongdo** [comment]
Sorry, what's AR?

**Comment by tamird** [comment]
ActiveRecord.

**Comment by cuongdo** [comment]
Going to let this sit a bit while @nvanbenschoten gets another round of `pg_catalog` changes in that are needed for ActiveRecord. The main purpose for this change is ActiveRecord support, so it doesn't make sense to merge at this point.

**Comment by cuongdo** [comment]
PTAL. The "only" change is a rebase. However, the merge was involved because of the `pkg` merge and the `Datum`/`Type` split.

This is needed for #10075, so I'd like to merge as soon as this gets a good re-review.

cc @eisenstatdavid for the `Datum`/`Type` stuff

**Comment by nvanbenschoten** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 920 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KUsoPTaOy_0xpepAMFe:-KUsoPTaOy_0xpepAMFf:b4nixd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ea2fc9b0e8f915821ec6a58c4caaa39aed8265/pkg/sql/parser/builtins.go#L920)):*
> ```Go
> 				showImplicitSchemas := args[0].(*DBool)
> 				if showImplicitSchemas == DBoolTrue {
> 					// TODO(cuongdo): This is hack, because we don't yet have a schema
> ```

Is this still true?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604)*

**Comment by cuongdo** [comment]
Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/builtins.go, line 920 at r7](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-KUsoPTaOy_0xpepAMFe:-KUtU9lQ8n3ji_mXWnv2:b-xmrswg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a4ea2fc9b0e8f915821ec6a58c4caaa39aed8265/pkg/sql/parser/builtins.go#L920)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Is this still true?
</details>
Done. I was so preoccupied with the nasty rebase & merge that I forgot about this. Good catch.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604)*

**Comment by knz** [comment]
Still :lgtm: thanks for tackling this.

---

Review status: 0 of 12 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-:-KUuhfo6FdBVVzBP_4H4:b-qvkoge)*

**Comment by nvanbenschoten** [comment]
:lgtm: again, thanks!

---

Review status: 0 of 12 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9604#-:-KUwLi80uiI9HcvGuvjt:bn0sv2r)*

**Pull request merged**
