### PR TITLE
ui: adds insights statement overview page

### LINKED ISSUE #86720: ui: add insights statement overview page
A new component needs to be added to insight page based on this figma. It's showing the data from the `crdb_internal.cluster_execution_insights`. 

https://www.figma.com/file/xpnRkP9cLXERVceRC4cec4/22.2_SQL-obsrv_query-performance?node-id=1086%3A86673

Jira issue: CRDB-18889

### PR DESCRIPTION
**Pull request by j82w**
ui: adds insights statement overview page

Screen Shot 2022-08-24 at 4 20 25 PM

https://loom.com/share/7b93781bf1cb489dbf039d1df924eaef

closes https://github.com/cockroachdb/cockroach/issues/86720

Release justification: Category 2: Bug fixes and
low-risk updates to new functionality

Release note (ui change): Adds insights overview
page for statements to show if there are index
recommendations, high retry count, and unknown for
scenarios that don't fall into those categories.

### CODE REVIEW

**Review by ericharmeling — COMMENTED** [review]
Looking very nice!

After a first pass, I just had a few comments/suggestions, but nothing too serious. There are also some formatting updates that you might have to revert/reformat to get the linter tests to pass.

Looks like https://github.com/cockroachdb/cockroach/pull/86596 will be merged soon too so you can rebase on that and resolve the conflicts.

> Reviewed 6 of 6 files at r1, 13 of 13 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-:-NAB74fA-65gniwUlDZn:biodj26)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB1SSt6JvA0fnyaM0T:-NAB1SSt6JvA0fnyaM0U:by5lsee) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e58b156591f9181fac5c96c49dcacb7e1544e49/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L59)):*
> ```XML
>   statementID: string;
>   transactionID: string;
>   statementFingerprintID: string;
> ```

Did we not want to intersect with the `InsightEvent` type here? IDK if it really makes a difference TBH (especially since we want to consolidate the two insight event types eventually).



_Code quote:_
```XML
export type StatementInsightEvent = {
  // Some of these can be moved to a common InsightEvent type if txn query is updated.
  statementID: string;
  transactionID: string;
  statementFingerprintID: string;
  transactionFingerprintID: string;
  startTime: Moment;
  elapsedTimeMillis: number;
  sessionID: string;
  timeSpentWaiting?: moment.Duration;
  isFullScan: boolean;
  endTime: Moment;
  databaseName: string;
  rowsRead: number;
  rowsWritten: number;
  lastRetryReason?: string;
  priority: string;
  retries: number;
  problems: string[];
  query: string;
  application: string;
};
```
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB4TrJ2gv3e-F2TgtL:-NAB4TrJ2gv3e-F2TgtM:b-4e4xeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L15)):*
> ```XML
> 
> export enum InsightNameEnum {
>   highWaitTime = "HIGH_WAIT_TIME",
> ```

I'm wondering if we want to change the high wait time name too.

Another place where we are using these names: `pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx`

Maybe we wait for a different PR to consolidate the names though...



_Suggestion:_
```XML
 highWaitTime = "HighWaitTime"
```
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB6Qtx1EJPie14cRBg:-NAB6Qtx1EJPie14cRBh:b-7h32o8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L156)):*
> ```XML
>     `This ${execType} was slow because of being retried multiple times, again due ` +
>     `to contention. The "high" threshold may be configured by the ` +
>     `'sql.insights.high_retry_count.threshold' cluster setting.`;
> ```

For high wait time, we actually pass the threshold in from the insight event object (see https://github.com/cockroachdb/cockroach/pull/86576/files#diff-f23a971328f9032e66010b8bc9b0779fefe9cfd39a9969ebf6a192208f5c04bbR89). 

IDK if it's worth adding here, as it would require updating the SQL API query to get the cluster setting value... but it's something to consider if you think it's worth surfacing the threshold value in the UI.



_Code quote:_
```XML
`'sql.insights.high_retry_count.threshold' cluster setting.
```
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB2Dzv-u8Sf4ENDgeO:-NAB2Dzv-u8Sf4ENDgeP:b5xdx62) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L186)):*
> ```XML
>   latencyThreshold?: number,
> ): Insight => {
>   switch (problem) {
> ```

Should we put this function in the `util` file?



_Code quote:_
```XML
export const getInsightFromProblem = (
  problem: string,
  execOption: InsightExecEnum,
  latencyThreshold?: number,
): Insight => {
  switch (problem) {
    case InsightNameEnum.highWaitTime:
      return highWaitTimeInsight(execOption, latencyThreshold);
    case InsightNameEnum.failedExecution:
      return failedExecutionInsight(execOption);
    case InsightNameEnum.planRegression:
      return planRegressionInsight(execOption);
    case InsightNameEnum.suboptimalPlan:
      return suboptimalPlanInsight(execOption);
    case InsightNameEnum.highRetryCount:
      return highRetryCountInsight(execOption);
    default:
      return unknownInsight(execOption);
  }
};
```
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsView.tsx` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB3_SS4c3Em7PJ-EKr:-NAB3_ST1wzeEtQL3Vda:bp62w6d) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsView.tsx#L19)):*
> ```XML
> import {Search} from "src/search/search";
> import {calculateActiveFilters, defaultFilters, Filter, getFullFiltersAsStringRecord,} from "src/queryFilter/filter";
> import {getInsightEventFiltersFromURL} from "src/queryFilter/utils";
> ```

You probably need to revert/reformat these formatting changes or the linter is going to fail.



_Code quote:_
```XML
import React, {useEffect, useState} from "react";
import classNames from "classnames/bind";
import {useHistory} from "react-router-dom";
import {ISortedTablePagination, SortSetting,} from "src/sortedtable/sortedtable";



import {Loading} from "src/loading/loading";
import {PageConfig, PageConfigItem} from "src/pageConfig/pageConfig";
import {Search} from "src/search/search";
import {calculateActiveFilters, defaultFilters, Filter, getFullFiltersAsStringRecord,} from "src/queryFilter/filter";





import {getInsightEventFiltersFromURL} from "src/queryFilter/utils";
import {Pagination} from "src/pagination";
import {queryByName, syncHistory} from "src/util/query";
```

**Review by maryliag — COMMENTED** [review]
> Reviewed 7 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB7q5q0G8fhTYP1yG_):*
can you add a little more details, showing the list of possible insights you can have now

also add the issue number
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 145 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB80eMBemkSdJx3ebV:-NAB80eMBemkSdJx3ebW:bv8bje6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L145)):*
> ```XML
>   return {
>     name: InsightNameEnum.suboptimalPlan,
>     label: "Suboptimal Plan",
> ```

nit: Sub-Optimal Plan
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsTable.tsx` line 38 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB8zZ31Oe-Qg62iKFw:-NAB8zZ31Oe-Qg62iKFx:b-iykp5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsTable.tsx#L38)):*
> ```XML
>       title: insightsTableTitles.executionID(execType),
>       cell: (item: StatementInsightEvent) => String(item.transactionID),
>       sort: (item: StatementInsightEvent) => String(item.transactionID),
> ```

nit: you don't need to convert to string here
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsTable.tsx` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB9NrwArpi-ISWIN2D:-NAB9NrwArpi-ISWIN2E:b-uyqvs2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsTable.tsx#L44)):*
> ```XML
>       title: insightsTableTitles.query(execType),
>       cell: (item: StatementInsightEvent) =>
>         QueriesCell({ transactionQueries: [item.query], textLimit: 50 }),
> ```

you don't need to use this function, because the statement is always one, you can just use directly the tooltip/limit text combo. I don't want to risk use something specific for txn on the stmts

**Review by ericharmeling — COMMENTED** [review]
One more nit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-:-NABlHz9CqJRrra0EjRW:b-r17eoj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsTable.tsx` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NABjgcPBFVlaSiPjk_Q:-NABjgcPBFVlaSiPjk_R:undefined) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsTable.tsx#L37)):*
> ```XML
>       name: "executionID",
>       title: insightsTableTitles.executionID(execType),
>       cell: (item: StatementInsightEvent) => String(item.transactionID),
> ```





_Suggestion:_
```XML
      cell: (item: StatementInsightEvent) => String(item.statementID),
      sort: (item: StatementInsightEvent) => String(item.statementID),
```

**Comment by j82w** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 59 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB1SSt6JvA0fnyaM0T:-NACDXQo3kNz7bSKT2MC:b-iz6eaj) ([raw file](https://github.com/cockroachdb/cockroach/blob/3e58b156591f9181fac5c96c49dcacb7e1544e49/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L59)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Did we not want to intersect with the `InsightEvent` type here? IDK if it really makes a difference TBH (especially since we want to consolidate the two insight event types eventually).
</blockquote></details>

@xinhaoz what is the reason the intersect was removed? 
https://reviewable.io/reviews/cockroachdb/cockroach/86596

**Comment by j82w** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB6Qtx1EJPie14cRBg:-NACENvH6y2JivxPnXJo:bwrq9eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L156)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

For high wait time, we actually pass the threshold in from the insight event object (see https://github.com/cockroachdb/cockroach/pull/86576/files#diff-f23a971328f9032e66010b8bc9b0779fefe9cfd39a9969ebf6a192208f5c04bbR89). 

IDK if it's worth adding here, as it would require updating the SQL API query to get the cluster setting value... but it's something to consider if you think it's worth surfacing the threshold value in the UI.
</blockquote></details>


I agree with this, but I think for a v1 this should be good enough. It seems like we should probably get and cache all of these settings to avoid the overhead of getting them on every query.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @j82w, @maryliag, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 15 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB4TrJ2gv3e-F2TgtL:-NACDU8S8QR65eZGN7nw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L15)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I'm wondering if we want to change the high wait time name too.

Another place where we are using these names: `pkg/ui/workspaces/cluster-ui/src/insightsTable/insightsTable.tsx`

Maybe we wait for a different PR to consolidate the names though...
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsTable.tsx` line 37 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NABjgcPBFVlaSiPjk_Q:-NACE_xZ-xVUH079cq8H:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsTable.tsx#L37)):*
> ```XML
>       name: "executionID",
>       title: insightsTableTitles.executionID(execType),
>       cell: (item: StatementInsightEvent) => String(item.transactionID),
> ```

Done.

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @j82w, @maryliag, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAFAc2L-r7pgxuhbIJn:-NAFAc2L-r7pgxuhbIJo:b-avgay5) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdddf4ab93e8e73649e3c220594cb8fdb65a43d8/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L268)):*
> ```XML
>   rows_read: number;
>   rows_written: number;
>   priority: string;
> ```

I was getting `0` for `priority` values and then saw that the `priority` column type is `FLOAT8`:

```
root@localhost:26257/defaultdb> show columns from crdb_internal.cluster_execution_insights;
       column_name      | data_type | is_nullable | column_default | generation_expression | indices | is_hidden
------------------------+-----------+-------------+----------------+-----------------------+---------+------------
  session_id            | STRING    |      f      | NULL           |                       | {}      |     f
  txn_id                | UUID      |      f      | NULL           |                       | {}      |     f
  txn_fingerprint_id    | BYTES     |      f      | NULL           |                       | {}      |     f
  stmt_id               | STRING    |      f      | NULL           |                       | {}      |     f
  stmt_fingerprint_id   | BYTES     |      f      | NULL           |                       | {}      |     f
  problems              | STRING[]  |      f      | NULL           |                       | {}      |     f
  query                 | STRING    |      f      | NULL           |                       | {}      |     f
  status                | STRING    |      f      | NULL           |                       | {}      |     f
  start_time            | TIMESTAMP |      f      | NULL           |                       | {}      |     f
  end_time              | TIMESTAMP |      f      | NULL           |                       | {}      |     f
  full_scan             | BOOL      |      f      | NULL           |                       | {}      |     f
  user_name             | STRING    |      f      | NULL           |                       | {}      |     f
  app_name              | STRING    |      f      | NULL           |                       | {}      |     f
  database_name         | STRING    |      f      | NULL           |                       | {}      |     f
  plan_gist             | STRING    |      f      | NULL           |                       | {}      |     f
  rows_read             | INT8      |      f      | NULL           |                       | {}      |     f
  rows_written          | INT8      |      f      | NULL           |                       | {}      |     f
  priority              | FLOAT8    |      f      | NULL           |                       | {}      |     f
  retries               | INT8      |      f      | NULL           |                       | {}      |     f
  last_retry_reason     | STRING    |      t      | NULL           |                       | {}      |     f
  exec_node_ids         | INT8[]    |      f      | NULL           |                       | {}      |     f
  contention            | INTERVAL  |      t      | NULL           |                       | {}      |     f
  index_recommendations | STRING[]  |      f      | NULL           |                       | {}      |     f
```

We might want to cast this to a number, since it's a `FLOAT8` (or at least put a comment in with the underlying type, as is done for the others). Also, is there a reason why this isn't `INT8`?

I'm assuming the mapping on the transaction priorities is as follows: (0: low, 1: normal, 2: high). Is that right?



_Suggestion:_
```XML
priority: number;
```

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @j82w, @maryliag, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB6Qtx1EJPie14cRBg:-NAFD9VC7-wC7E0kyFX9:bf8znzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L156)):*
> I agree with this, but I think for a v1 this should be good enough. 

Sounds good.

> It seems like we should probably get and cache all of these settings to avoid the overhead of getting them on every query.

Agreed. I made an issue: https://github.com/cockroachdb/cockroach/issues/86760

**Review by ericharmeling — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @j82w, @maryliag, and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 187 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAGIkA35KPcH7AU8Nsw:-NAGIkA35KPcH7AU8Nsx:b-2p8hdh) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad55857e7bea1fa2eb27dfef24f7364feae791f/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L187)):*
> ```XML
>                    blocking_txn_id,
>                    encode(blocking_txn_fingerprint_id, 'hex') AS blocking_txn_fingerprint_id,
>                    waiting_txn_id,
> ```

nit: IDK if we want all the extra whitespace here and above (it won't make a difference to the API, but the linter might not like it and it's hard to read).



_Code quote:_
```XML
                   blocking_txn_id,
                   encode(blocking_txn_fingerprint_id, 'hex') AS blocking_txn_fingerprint_id,
                   waiting_txn_id,
                   encode(waiting_txn_fingerprint_id, 'hex')  AS waiting_txn_fingerprint_id,
                   contention_duration,
                   crdb_internal.pretty_key(contending_key, 0) as key,
```

**Comment by j82w** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 187 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAGIkA35KPcH7AU8Nsw:-NAK9M4c4ZtChbpAvQdw:b8riyzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad55857e7bea1fa2eb27dfef24f7364feae791f/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L187)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

nit: IDK if we want all the extra whitespace here and above (it won't make a difference to the API, but the linter might not like it and it's hard to read).
</blockquote></details>

I did used GoLand to format the file and it added the white space. It doesn't fail the lint test, but I figured it was better to be follow the GoLand formatting.

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86688)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ericharmeling, @j82w, @maryliag, and @xinhaoz)

___
*[`-- commits` line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB7q5q0G8fhTYP1yG_):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

can you add a little more details, showing the list of possible insights you can have now

also add the issue number
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAFAc2L-r7pgxuhbIJn:-NAKA74bA7smo3o-hMAp:bt9ykeb) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdddf4ab93e8e73649e3c220594cb8fdb65a43d8/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L268)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

I was getting `0` for `priority` values and then saw that the `priority` column type is `FLOAT8`:

```
root@localhost:26257/defaultdb> show columns from crdb_internal.cluster_execution_insights;
       column_name      | data_type | is_nullable | column_default | generation_expression | indices | is_hidden
------------------------+-----------+-------------+----------------+-----------------------+---------+------------
  session_id            | STRING    |      f      | NULL           |                       | {}      |     f
  txn_id                | UUID      |      f      | NULL           |                       | {}      |     f
  txn_fingerprint_id    | BYTES     |      f      | NULL           |                       | {}      |     f
  stmt_id               | STRING    |      f      | NULL           |                       | {}      |     f
  stmt_fingerprint_id   | BYTES     |      f      | NULL           |                       | {}      |     f
  problems              | STRING[]  |      f      | NULL           |                       | {}      |     f
  query                 | STRING    |      f      | NULL           |                       | {}      |     f
  status                | STRING    |      f      | NULL           |                       | {}      |     f
  start_time            | TIMESTAMP |      f      | NULL           |                       | {}      |     f
  end_time              | TIMESTAMP |      f      | NULL           |                       | {}      |     f
  full_scan             | BOOL      |      f      | NULL           |                       | {}      |     f
  user_name             | STRING    |      f      | NULL           |                       | {}      |     f
  app_name              | STRING    |      f      | NULL           |                       | {}      |     f
  database_name         | STRING    |      f      | NULL           |                       | {}      |     f
  plan_gist             | STRING    |      f      | NULL           |                       | {}      |     f
  rows_read             | INT8      |      f      | NULL           |                       | {}      |     f
  rows_written          | INT8      |      f      | NULL           |                       | {}      |     f
  priority              | FLOAT8    |      f      | NULL           |                       | {}      |     f
  retries               | INT8      |      f      | NULL           |                       | {}      |     f
  last_retry_reason     | STRING    |      t      | NULL           |                       | {}      |     f
  exec_node_ids         | INT8[]    |      f      | NULL           |                       | {}      |     f
  contention            | INTERVAL  |      t      | NULL           |                       | {}      |     f
  index_recommendations | STRING[]  |      f      | NULL           |                       | {}      |     f
```

We might want to cast this to a number, since it's a `FLOAT8` (or at least put a comment in with the underlying type, as is done for the others). Also, is there a reason why this isn't `INT8`?

I'm assuming the mapping on the transaction priorities is as follows: (0: low, 1: normal, 2: high). Is that right?
</blockquote></details>

I think this should be a string, and needs to be converted in the db. I think this should be fixed/discussed in a follow up issue because it's not being displayed/used in this PR.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB2Dzv-u8Sf4ENDgeO:-NAFWBV273a8P26E3V4R:b-cr0maq) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L186)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

Should we put this function in the `util` file?
</blockquote></details>

The reason I kept in types is it prevents all the types needing to be exported and then imported in the util class. This way only thing that has to be exposed in the one method.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsTable.tsx` line 44 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB9NrwArpi-ISWIN2D:-NAFW1mvBDuNi5V6pq8N:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/statementInsights/statementInsightsTable.tsx#L44)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you don't need to use this function, because the statement is always one, you can just use directly the tooltip/limit text combo. I don't want to risk use something specific for txn on the stmts
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsView.tsx` line 19 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB3_SS4c3Em7PJ-EKr:-NAFW50h9bDpQ06G21lC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsights/transactionInsights/transactionInsightsView.tsx#L19)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

You probably need to revert/reformat these formatting changes or the linter is going to fail.
</blockquote></details>

Done.

**Review by maryliag — APPROVED** [review]
Awesome job on this!! :lgtm: 

> Reviewed 2 of 13 files at r2, 1 of 5 files at r4, 7 of 9 files at r5, 7 of 7 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-:-NAKEZPo81URGZ00WGNl:bv4ywha)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 156 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB6Qtx1EJPie14cRBg:-NAKDadk1CBpanx4H0A3:buv5bgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L156)):*
<details><summary><i>Previously, ericharmeling (Eric Harmeling) wrote…</i></summary><blockquote>

> I agree with this, but I think for a v1 this should be good enough. 

Sounds good.

> It seems like we should probably get and cache all of these settings to avoid the overhead of getting them on every query.

Agreed. I made an issue: https://github.com/cockroachdb/cockroach/issues/86760
</blockquote></details>

Can you also create an issue to update this message so the cluster setting is the link for the docs of this setting? You won't have the doc yet, so create the issue so we don't forget about it

**Review by ericharmeling — APPROVED** [review]
Nice!!

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-:-NAKIsQQ1T7tWcqtc-5-:bwuv9uq)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ericharmeling and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 268 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAFAc2L-r7pgxuhbIJn:-NAKHx5_DSt20ukYA73y:be2qahg) ([raw file](https://github.com/cockroachdb/cockroach/blob/cdddf4ab93e8e73649e3c220594cb8fdb65a43d8/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L268)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

I think this should be a string, and needs to be converted in the db. I think this should be fixed/discussed in a follow up issue because it's not being displayed/used in this PR.
</blockquote></details>

SGTM

https://github.com/cockroachdb/cockroach/issues/86867
___
*[`pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts` line 187 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAGIkA35KPcH7AU8Nsw:-NAKI-1xA5jt1Wy9ocAD:b-4hvi0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad55857e7bea1fa2eb27dfef24f7364feae791f/pkg/ui/workspaces/cluster-ui/src/api/insightsApi.ts#L187)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

I did used GoLand to format the file and it added the white space. It doesn't fail the lint test, but I figured it was better to be follow the GoLand formatting.
</blockquote></details>

Got it.
___
*[`pkg/ui/workspaces/cluster-ui/src/insights/types.ts` line 186 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/86688#-NAB2Dzv-u8Sf4ENDgeO:-NAKHqTH5C6rJzQD8Jgq:b-4hvi0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d8c540baf14a96035acf44f679073d40b3f23c39/pkg/ui/workspaces/cluster-ui/src/insights/types.ts#L186)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

The reason I kept in types is it prevents all the types needing to be exported and then imported in the util class. This way only thing that has to be exposed in the one method.
</blockquote></details>

Got it!

**Pull request merged**
