### PR TITLE
sql, opt: avoid full scans in mutation queries

### LINKED ISSUE #79683: opt: the optimizer cost model should consider contention
Currently, CockroachDB's optimizer tries to find the best plan for a query in isolation and doesn't concern itself with the possibility that reading more rows than needed could cause write conflicts. Consider the following example:
```
CREATE TABLE tab (
  a INT,
  b INT,
  INDEX (b)
);
INSERT INTO tab SELECT generate_series(1,500), 1;
INSERT INTO tab SELECT generate_series(501,1000), 2;
ANALYZE tab;
EXPLAIN UPDATE tab SET a = 2000 WHERE b = 1;
                                             info
-----------------------------------------------------------------------------------------------
  distribution: local
  vectorized: true

  • update
  │ table: tab
  │ set: a
  │ auto commit
  │
  └── • render
      │ estimated row count: 500
      │
      └── • filter
          │ estimated row count: 500
          │ filter: b = 1
          │
          └── • scan
                estimated row count: 1,000 (100% of the table; stats collected 2 seconds ago)
                table: tab@tab_pkey
                spans: FULL SCAN
```
The optimizer chooses a full scan of the primary index instead of using the index on `b`, since in isolation, this is less expensive than performing an index join with half the rows in the table. However, it means that any other query that wants to update rows where `b = 2` will block, even though technically there is no conflict.

Ideally, the optimizer would almost never choose a full scan for mutation queries such as this one where a suitable index is available, due to the impact on contention.

Epic CRDB-37836

Jira issue: CRDB-14977

gz#11932

gz#18109

### PR DESCRIPTION
**Pull request by rytaft**
**opt,sql: support hint to avoid full scan**

Informs https://github.com/cockroachdb/cockroach/issues/79683

Release note (sql change): Added support for a new index hint,
`AVOID_FULL_SCAN`, which will prevent the optimizer from planning a
full scan for the specified table if any other plan is possible. The
hint can be used in the same way as other existing index hints. For
example, `SELECT * FROM table_name@{AVOID_FULL_SCAN};`. Note that a
full scan of a partial index may still be preferred by the optimizer,
unless `AVOID_FULL_SCAN` is used in combination with a specific partial
index via `FORCE_INDEX=index_name`. This hint is similar to `NO_FULL_SCAN`,
but will not error if a full scan cannot be avoided.

**sql,opt: add setting avoid_full_table_scans_in_mutations**

Fixes https://github.com/cockroachdb/cockroach/issues/79683

Release note (sql change): Added a new session setting
`avoid_full_table_scans_in_mutations`, which when set to true, causes
the optimizer to avoid planning full table scans for mutation queries
if any other plan is possible. It now defaults to true.

**opt: remove a stale comment above optbuilder.buildScan**

Removed a comment that references a function parameter that no longer
exists.

Release note: None

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137781)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained

___
*[`pkg/sql/opt/exec/execbuilder/testdata/update` line 404 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OEWx8DXA6FsszuGcWYm:-OEWx8DXA6FsszuGcWYn:b-1ad072) ([raw file](https://github.com/cockroachdb/cockroach/blob/e599fcda78d73ec0b5d7895897bc4572da9644fc/pkg/sql/opt/exec/execbuilder/testdata/update#L404)):*
> ```
> └── • render
>     │
>     └── • limit
> ```

Need to investigate why we lost the top k here
___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 5707 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OEWwzlx6Ik0B-7AqiPF:-OEWwzlyEK3afMAks-XJ:b14saqe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e599fcda78d73ec0b5d7895897bc4572da9644fc/pkg/sql/opt/exec/execbuilder/testdata/unique#L5707)):*
> ```
> vectorized: true
> ·
> • root
> ```

This seems concerning that we're no longer getting the insert fast path here.

**Review by mgartner — COMMENTED** [review]
> Reviewed 20 of 20 files at r1, 87 of 87 files at r4, 87 of 87 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137781)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mw5h and @rytaft)

___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 5707 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OEWwzlx6Ik0B-7AqiPF:-OE_S1hiEAcNZJsqOlhE:b-9u7zw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e599fcda78d73ec0b5d7895897bc4572da9644fc/pkg/sql/opt/exec/execbuilder/testdata/unique#L5707)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This seems concerning that we're no longer getting the insert fast path here.
</blockquote></details>

For some reason the optimizer no longer picks lookup joins into the partial indexes...
___
*[`pkg/sql/opt/exec/execbuilder/testdata/update` line 404 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OEWx8DXA6FsszuGcWYm:-OE_SPy-A1YVmKAWE1tW:buapukm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e599fcda78d73ec0b5d7895897bc4572da9644fc/pkg/sql/opt/exec/execbuilder/testdata/update#L404)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Need to investigate why we lost the top k here
</blockquote></details>

I think it's similar to the distinct change—the hugeCost/2 has made the cost of everything else irrelevant. 
___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_LzWI5dJL-ud4NiT3:-OE_LQhc9jsflsrnm5N4:beyzr0g):*
nit: I find the language about this partial index behavior in the comment in `coster.go` easier to understand, maybe consider using that for the release note? Or add another sentence to make it ultra clear that a full scan of a partial index on only avoided if the partial index is forced.
___
*[`pkg/sql/opt/optbuilder/mutation_builder_arbiter.go` line 687 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_PA4NBaIYYN-LqkEv:-OE_PA4NBaIYYN-LqkEw:bf3fsb4) ([raw file](https://github.com/cockroachdb/cockroach/blob/89adbc83712a2b587b43968b3d2d1306813849fe/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L687)):*
> ```Go
> 		if h.mb.b.evalCtx.SessionData().AvoidFullTableScansInMutations {
> 			indexFlags = &tree.IndexFlags{AvoidFullScan: true}
> 		}
> ```

The expression built by `tableScope()` is never part of a query plan and is never optimized with exploration rules—it is only used to build scalar expressions (partial index predicates) into the metadata. We really shouldn't be building a whole scan expression just to do that, but it was the simplest way to build all the necessary columns into a scope that the partial index predicate may reference (think of virtual computed columns which are a projection over a scan—to support partial index predicates that reference those, we can't simply use the standard table columns). #61298 tracks making this better.

Anyway, the TLDR is that there is no need to use index flags here.
___
*[`pkg/sql/opt/exec/execbuilder/testdata/cascade` line 928 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_Qz4v8GOf1uwyElRs:-OE_Qz4v8GOf1uwyElRt:b2y0j4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfcdbe27df40f4418f36b3410b04942f8a3f3239/pkg/sql/opt/exec/execbuilder/testdata/cascade#L928)):*
> ```
>         │               │ estimated row count: 10
>         │               │ distinct on: a
>         │               │
> ```

This change is odd. I guess the hugeCost/2 has made the plan without the disctint more-or-less the same cost as the plan with the distinct?
___
*[`pkg/sql/opt/exec/execbuilder/testdata/fk` line 671 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_RaLyCEH8C7SzzHfK:-OE_RaLyCEH8C7SzzHfL:b-vui83r) ([raw file](https://github.com/cockroachdb/cockroach/blob/89adbc83712a2b587b43968b3d2d1306813849fe/pkg/sql/opt/exec/execbuilder/testdata/fk#L671)):*
> ```
> EXPLAIN (OPT) UPDATE child SET p = 4
> ----
> distribute
> ```

Do you know why this distribute operator was added in some of these tests?
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 195 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_T51-7_h6oTafK4mH:-OE_T51-7_h6oTafK4mI:b-x5pv2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/89adbc83712a2b587b43968b3d2d1306813849fe/pkg/sql/opt/optbuilder/testdata/delete#L195)):*
> ```
>       ├── columns: x:6!null y:7 z:8 crdb_internal_mvcc_timestamp:9 tableoid:10 column11:11
>       ├── internal-ordering: -11
>       ├── sort
> ```

This looks like a regression too.
___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2775 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_U0bs9Y5ghPcUhFnX:-OE_U0bt1Nuex4cL9fhp:b-e7x1e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/89adbc83712a2b587b43968b3d2d1306813849fe/pkg/sql/opt/xform/testdata/rules/limit#L2775)):*
> ```
>                 │    │    ├── [/1000000001 - /1999999999]
>                 │    │    └── [/2000000001 - ]
>                 │    ├── flags: avoid-full-scan
> ```

I'm not really sure the purpose of this test, but this scan over all partitions + index join is a regression.
___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2848 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_U9leE6TS9n9Yu6fA:-OE_U9leE6TS9n9Yu6fB:bwq3zhc) ([raw file](https://github.com/cockroachdb/cockroach/blob/89adbc83712a2b587b43968b3d2d1306813849fe/pkg/sql/opt/xform/testdata/rules/limit#L2848)):*
> ```
>                 │    │    ├── [/2 - /4]
>                 │    │    ├── [/6 - /4999999]
>                 │    │    └── [/5000001 - ]
> ```

This is a regression, too, same as above.

**Review by rytaft — COMMENTED** [review]
TFTR! I'm going to close this PR in favor of https://reviewable.io/reviews/cockroachdb/cockroach/137781. All the comments should be addressed in the new PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-:-OF2k0Eu8M7QFfBPZ51O:b5br82o)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @mw5h)

___
*[`-- commits` line 13 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_LzWI5dJL-ud4NiT3:-OF2k9Gy1mWDQzA11Ozi:bhchyzv):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: I find the language about this partial index behavior in the comment in `coster.go` easier to understand, maybe consider using that for the release note? Or add another sentence to make it ultra clear that a full scan of a partial index on only avoided if the partial index is forced.
</blockquote></details>

Fixed in https://reviewable.io/reviews/cockroachdb/cockroach/137781
___
*[`pkg/sql/opt/optbuilder/mutation_builder_arbiter.go` line 687 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_PA4NBaIYYN-LqkEv:-OF2kBIa99TxPZnMQGh5:bxamxt7) ([raw file](https://github.com/cockroachdb/cockroach/blob/89adbc83712a2b587b43968b3d2d1306813849fe/pkg/sql/opt/optbuilder/mutation_builder_arbiter.go#L687)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The expression built by `tableScope()` is never part of a query plan and is never optimized with exploration rules—it is only used to build scalar expressions (partial index predicates) into the metadata. We really shouldn't be building a whole scan expression just to do that, but it was the simplest way to build all the necessary columns into a scope that the partial index predicate may reference (think of virtual computed columns which are a projection over a scan—to support partial index predicates that reference those, we can't simply use the standard table columns). #61298 tracks making this better.

Anyway, the TLDR is that there is no need to use index flags here.
</blockquote></details>

Thanks for the info! Fixed in https://reviewable.io/reviews/cockroachdb/cockroach/137781
___
*[`pkg/sql/opt/exec/execbuilder/testdata/cascade` line 928 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_Qz4v8GOf1uwyElRs:-OF2kEjKASQvM3U1VzHf:bhchyzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/dfcdbe27df40f4418f36b3410b04942f8a3f3239/pkg/sql/opt/exec/execbuilder/testdata/cascade#L928)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This change is odd. I guess the hugeCost/2 has made the plan without the disctint more-or-less the same cost as the plan with the distinct?
</blockquote></details>

Fixed in https://reviewable.io/reviews/cockroachdb/cockroach/137781
___
*[`pkg/sql/opt/exec/execbuilder/testdata/fk` line 671 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_RaLyCEH8C7SzzHfK:-OF2kGc614GremHpPbLc:bhchyzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/89adbc83712a2b587b43968b3d2d1306813849fe/pkg/sql/opt/exec/execbuilder/testdata/fk#L671)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Do you know why this distribute operator was added in some of these tests?
</blockquote></details>

Fixed in https://reviewable.io/reviews/cockroachdb/cockroach/137781
___
*[`pkg/sql/opt/exec/execbuilder/testdata/unique` line 5707 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OEWwzlx6Ik0B-7AqiPF:-OF2kIAhCzwjuoW_2ASd:bhchyzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e599fcda78d73ec0b5d7895897bc4572da9644fc/pkg/sql/opt/exec/execbuilder/testdata/unique#L5707)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

For some reason the optimizer no longer picks lookup joins into the partial indexes...
</blockquote></details>

Fixed in https://reviewable.io/reviews/cockroachdb/cockroach/137781
___
*[`pkg/sql/opt/exec/execbuilder/testdata/update` line 404 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OEWx8DXA6FsszuGcWYm:-OF2kJy54l9PWTLGbyGa:bhchyzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e599fcda78d73ec0b5d7895897bc4572da9644fc/pkg/sql/opt/exec/execbuilder/testdata/update#L404)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I think it's similar to the distinct change—the hugeCost/2 has made the cost of everything else irrelevant.
</blockquote></details>

Fixed in https://reviewable.io/reviews/cockroachdb/cockroach/137781
___
*[`pkg/sql/opt/optbuilder/testdata/delete` line 195 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_T51-7_h6oTafK4mH:-OF2kLe5-rkjbCkM1_hJ:bhchyzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/89adbc83712a2b587b43968b3d2d1306813849fe/pkg/sql/opt/optbuilder/testdata/delete#L195)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This looks like a regression too.
</blockquote></details>

Fixed in https://reviewable.io/reviews/cockroachdb/cockroach/137781
___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2775 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_U0bs9Y5ghPcUhFnX:-OF2kNAA4tyhSICnIkVs:bsuwjhd) ([raw file](https://github.com/cockroachdb/cockroach/blob/89adbc83712a2b587b43968b3d2d1306813849fe/pkg/sql/opt/xform/testdata/rules/limit#L2775)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

I'm not really sure the purpose of this test, but this scan over all partitions + index join is a regression.
</blockquote></details>

This is an unrelated bug, see https://github.com/cockroachdb/cockroach/issues/137994
___
*[`pkg/sql/opt/xform/testdata/rules/limit` line 2848 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/137781#-OE_U9leE6TS9n9Yu6fA:-OF2kS8Z3Km_EUmBD5j9:bthha92) ([raw file](https://github.com/cockroachdb/cockroach/blob/89adbc83712a2b587b43968b3d2d1306813849fe/pkg/sql/opt/xform/testdata/rules/limit#L2848)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is a regression, too, same as above.
</blockquote></details>

See https://github.com/cockroachdb/cockroach/issues/137994

**Comment by rytaft** [comment]
Oops, everywhere I said #137781, I meant #137984

**Comment by rytaft** [comment]
Closing in favor of #137984

**Pull request closed without merging**
