### PR TITLE
sqlsmith: a couple of minor fixes

### LINKED ISSUE #107458: sqlsmith: concurrent map read and write panic
During the Roachtest Nightly run on Jul 24 [1], we observed a crash coming from concurrent use of `sqlsmith.Smither`:

```
[06:19:08]W:	 [Step 2/3] fatal error: concurrent map read and map write

[06:19:08]W:	 [Step 2/3] goroutine 87642 [running]:
[06:19:08]W:	 [Step 2/3] github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeCreateFunc(0xc004814000)
[06:19:08]W:	 [Step 2/3] 	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:1102 +0x15b8
[06:19:08]W:	 [Step 2/3] github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.makeCreateFunc(0xc0013d0570?)
[06:19:08]W:	 [Step 2/3] 	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:882 +0x32
[06:19:08]W:	 [Step 2/3] github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).makeStmt(0xc004814000)
[06:19:08]W:	 [Step 2/3] 	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/relational.go:26 +0x35
[06:19:08]W:	 [Step 2/3] github.com/cockroachdb/cockroach/pkg/internal/sqlsmith.(*Smither).Generate(0x12?)
[06:19:08]W:	 [Step 2/3] 	github.com/cockroachdb/cockroach/pkg/internal/sqlsmith/sqlsmith.go:181 +0x31
[06:19:08]W:	 [Step 2/3] github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerSQLSmith.func3.2.1({0x0, 0x0})
[06:19:08]W:	 [Step 2/3] 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/sqlsmith.go:209 +0x93
[06:19:08]W:	 [Step 2/3] created by github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests.registerSQLSmith.func3.2
[06:19:08]W:	 [Step 2/3] 	github.com/cockroachdb/cockroach/pkg/cmd/roachtest/tests/sqlsmith.go:197 +0x1aa
```

The issue happens in the sqlsmith roachtest when multiple statements are generated concurrently:

https://github.com/cockroachdb/cockroach/blob/771d3f7f3e546086465220171d68fd106e4f75f8/pkg/cmd/roachtest/tests/sqlsmith.go#L182-L209

Closing this issue would encompass two separate changes:

* fixing the concurrency issue itself;
* replacing use of `go` in the test code above with `monitor.Go`. The panic in the goroutine created by the test caused the entire `roachtest` process to crash, so we only ran a fraction of the roachtests we were supposed to run in the nightly build. By using `monitor.Go` instead, the panic would have been caught and the run proceeded as usual.

[1] <https://teamcity.cockroachdb.com/viewLog.html?buildId=11030269&buildTypeId=Cockroach_Nightlies_RoachtestNightlyGceBazel>.

Jira issue: CRDB-30054

### PR DESCRIPTION
**Pull request by yuzefovich**
Fixes: #107458.

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: Thanks for the fix!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107514#-:-Na9xUvN90AeueLgC2Mi:b-72sm86)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @renatolabs)

**Review by renatolabs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107514#-:-NaC6KgM-nOiyrsIoplF:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Comment by yuzefovich** [comment]
TFTRs!

bors r+

**Comment by renatolabs** [comment]
@yuzefovich any reason why you removed the backport label? I was thinking of backporting this change.

**Comment by yuzefovich** [comment]
I initially thought that cac2b72155cad81a578b97c3331c44f8bef9b679 (which introduced UDF support to sqlsmith) was on 23.1 but then realized it wasn't, so I removed the label. In other words, there is nothing to backport in the first commit.

As for the second commit, I deemed it not worthy of a backport either because we do have `recover` catcher in that goroutine started with `go func`, and my guess is that only fatal errors (like concurrent map read and write) aren't recovered from.

**Comment by renatolabs** [comment]
Ah, makes sense, it seems that concurrent map read write is unrecoverable. SGTM then, thanks for explaining.

**Pull request merged**
