### PR TITLE
pkg/util/log: introduce `fluent.sink.conn.errors` metric to log package

### PR DESCRIPTION
**Pull request by abarganier**
Logging is a critical subsystem within CRDB, but as things
are today, we have very little observability into logging
itself. For starters, we have no metrics in the logging
package at all!

This makes it difficult to observe things within the log
package. For example, if a fluent-server log sink fails
to connect to FluentBit, how can we tell? We get some STDOUT
message, but that's about it.

It's time to get some metrics into the log package.

Doing so is a bit of a tricky dance, because pretty much every
package in CRDB imports the logging package, meaning you
almost always get a circular dependency when trying to make
use of any library within pkg/util/log. Therefore, this PR 
injects metrics functionality into the logging package.
It does so via a new interface called `LogMetrics` with
functions that enable its users to modify metrics.

The implementation of the interface can live elsewhere,
such as the metrics package itself, whe circular dependencies
aren't such a pain. We can then inject the implementation
into the log package.

With all that plumbing done, the PR also introduces a new metric,
`fluent.sink.conn.errors` representing fluentbit connection errors 
whenever a fluent-server log sink fails to establish a connection.

We can see the metric represented below in a test, where no
fluent-server was running for a moment, before starting it.
Note that the connection errors level off once the server was 
started:
Screenshot 2023-07-11 at 1 32 57 PM

Release note (ops change): This patch introduces the counter
metric `fluent.sink.conn.errors` to the CockroachDB tsdb,
which is exposed to `/_status/vars` clients as
`fluent_sink_conn_errors`. The metric is incremented whenever
a `fluent-server` log sink fails to establish a connection to
the log sink pointed to by the `address` for the sink in the
provided log config.

Epic: CC-9681

Addresses: https://github.com/cockroachdb/cockroach/issues/102753

### CODE REVIEW

**Review by knz — COMMENTED** [review]
My main feedback concerns the structure of the new package and the ownership of the registry (1st and 2nd commit). The rest checks out.

> Reviewed 5 of 5 files at r1, 12 of 12 files at r2, 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-:-N_98uG34JVBPDenplFw:b-y2sj6j)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/cli/demo.go` line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_98dB-8DMArV_uaERv:-N_98dB05PB51KHom5jr:b-o24jtr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1196262a16006e3c2da41d60ab222d6f485e72/pkg/cli/demo.go#L235)):*
> ```Go
> 			// decide how to enable logging.
> 			serverCfg.Stores.Specs = nil
> 			logMetrics := metric.NewLogMetricsRegistry()
> ```

I believe this change should be moved form the 3rd commit to the 2nd commit.
___
*[`pkg/server/tenant.go` line 651 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_98hgo7W439W3rglO-:-N_98hgp4vCt6W5Z8rc8:b-g7gkf8) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1196262a16006e3c2da41d60ab222d6f485e72/pkg/server/tenant.go#L651)):*
> ```Go
> 		lr, ok := r.(*metric.Registry)
> 		if !ok {
> 			panic(fmt.Sprintf("unexpected type for LogMetrics registry: %T", r))
> ```

`panic(errors.AssertionFailedf(...))`
___
*[`pkg/util/log/flags.go` line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_987T38WZROZWRWlFd:-N_987T38WZROZWRWlFe:b-5bgbpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2ae357d40c28f2447622a96782597ecdf0cf132/pkg/util/log/flags.go#L93)):*
> ```Go
> //
> // The returned logShutdownFn can be used to gracefully shut down logging facilities.
> func ApplyConfig(config logconfig.Config, metrics LogMetrics) (logShutdownFn func(), err error) {
> ```

I don't love this change.

It seems to me that the (new) `logmetrics` package should instantiate the registry in a `init` function as a singleton, inject it into the log package only once (with a specific function just for that purpose).

Then the `cli/start` code would retrieve a reference to that singleton for passing to the server initialization.

(I am especially concerned by CLI unit tests that call `start` repeatedly. I don't think we want each iteration of the unit test to create a new metric registry.)
___
*[`pkg/util/metric/log_metrics.go` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_97NHrDg6N22zUNOr0:-N_97NHrDg6N22zUNOr1:bfa6gns) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb242bfc615370048046180adf2e726b7bb23d87/pkg/util/metric/log_metrics.go#L11)):*
> ```Go
> // licenses/APL.txt.
> 
> package metric
> ```

my preference would be to have the log metrics defined in a sub-package of `log`, e.g. `util/log/logmetrics`.
This way someone who is exploring the code around logging gets a "full picture" from the sub-directory tree.
___
*[`pkg/util/metric/log_metrics.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_97Zf78HLYp8yNpPOx:-N_97Zf8A-LeZbqmkT_1:bcamknz) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb242bfc615370048046180adf2e726b7bb23d87/pkg/util/metric/log_metrics.go#L68)):*
> ```Go
> 	l.mu.Lock()
> 	defer l.mu.Unlock()
> 	if counter, ok := l.mu.counters[metric]; ok {
> ```

It seems to me that if the metric does not exist, the program should crash -- it would be an implementation bug.
Maybe a panic? `panic(errors.AssertionFailedf(...))`

**Review by abarganier — COMMENTED** [review]
Thanks for the feedback, it was very helpful. RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-:-N_9VXFH5m2ceWOlUy7g:b-7r42gt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/server/tenant.go` line 651 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_98hgo7W439W3rglO-:-N_B5jDKCte_GutSXqSA:bvanro6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1196262a16006e3c2da41d60ab222d6f485e72/pkg/server/tenant.go#L651)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

`panic(errors.AssertionFailedf(...))`
</blockquote></details>

Ack, but no longer needed as we don't need to worry about this case anymore :relieved: 
___
*[`pkg/cli/demo.go` line 235 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_98dB-8DMArV_uaERv:-N_B5smlCbyiLFXysT1h:b-gf6iic) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec1196262a16006e3c2da41d60ab222d6f485e72/pkg/cli/demo.go#L235)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I believe this change should be moved form the 3rd commit to the 2nd commit.
</blockquote></details>

Ack - no longer relevant as this entire init process has been greatly simplified thanks to your other comment :slightly_smiling_face: 
___
*[`pkg/util/log/flags.go` line 93 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_987T38WZROZWRWlFd:-N_B5znC0S8y-zOnD-rG:bj7zpt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2ae357d40c28f2447622a96782597ecdf0cf132/pkg/util/log/flags.go#L93)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I don't love this change.

It seems to me that the (new) `logmetrics` package should instantiate the registry in a `init` function as a singleton, inject it into the log package only once (with a specific function just for that purpose).

Then the `cli/start` code would retrieve a reference to that singleton for passing to the server initialization.

(I am especially concerned by CLI unit tests that call `start` repeatedly. I don't think we want each iteration of the unit test to create a new metric registry.)
</blockquote></details>

Thanks for this advice, I somehow felt the entire thing was still too brittle.

Using an `init` function made everything much simpler & we no longer have to worry about `nil` log metrics. 

I ended up adding an `init` to the `MetricsRecorder` file for this, since the new logmetrics package isn't imported many places otherwise. LMK if you think there's a better place for this.
___
*[`pkg/util/metric/log_metrics.go` line 11 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_97NHrDg6N22zUNOr0:-N_B5ndzCrXHcKjANrMj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb242bfc615370048046180adf2e726b7bb23d87/pkg/util/metric/log_metrics.go#L11)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

my preference would be to have the log metrics defined in a sub-package of `log`, e.g. `util/log/logmetrics`.
This way someone who is exploring the code around logging gets a "full picture" from the sub-directory tree.
</blockquote></details>

Done.
___
*[`pkg/util/metric/log_metrics.go` line 68 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_97Zf78HLYp8yNpPOx:-N_B5q1R8mFyrg6IQDwm:b-slc4s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb242bfc615370048046180adf2e726b7bb23d87/pkg/util/metric/log_metrics.go#L68)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

It seems to me that if the metric does not exist, the program should crash -- it would be an implementation bug.
Maybe a panic? `panic(errors.AssertionFailedf(...))`
</blockquote></details>

Agreed & Done.

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 23 files at r5, 2 of 16 files at r6, 4 of 17 files at r7, 14 of 14 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @abarganier and @dhartunian)

___
*[`pkg/server/server.go` line 1844 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E4GOnCnBK1wYlrn7l:-N_E4GOnCnBK1wYlrn7m:bf0expc) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/server/server.go#L1844)):*
> ```Go
> 
> 	// Grab the log metrics registry.
> 	r := log.LogMetricsRegistry()
> ```

nit: you could retrieve the registry directly with the right type (`*metric.Registry`) if you put the accessor in package `logmetrics` instead.
___
*[`pkg/server/tenant.go` line 646 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E4MXw5xB_x0PBUOph:-N_E4MXw5xB_x0PBUOpi:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/server/tenant.go#L646)):*
> ```Go
> 
> 	// Grab the log metrics registry.
> 	r := log.LogMetricsRegistry()
> ```

ditto
___
*[`pkg/server/status/recorder.go` line 134 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E4RGz3sbWIEdgMeht:-N_E4RGz3sbWIEdgMehu:b-wjsj0z) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/server/status/recorder.go#L134)):*
> ```Go
> 		nodeRegistry *metric.Registry
> 		// logRegistry contains the global metrics registry used by the logging
> 		// package. NB: code paths exist where this registry is never initialized,
> ```

nit: pls provide an example of such code path.
___
*[`pkg/server/status/recorder.go` line 159 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E4VIK0XRZdeTnHr7B:-N_E4VIK0XRZdeTnHr7C:b-imc0wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/server/status/recorder.go#L159)):*
> ```Go
> 	// The logmetrics package is not imported by much, meaning
> 	// that its own init function is not a reliable place to initialize
> 	// log metrics. Being that the recorder is the primary user of
> ```

I disagree. you can use

```go
import (
   _ ".../util/log/logmetrics"
)
```

at the top of this file, and you'd get the right behavior.
___
*[`pkg/server/status/recorder.go` line 254 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E4jUg77Vl1Hfx7T9h:-N_E4jUg77Vl1Hfx7T9i:b90vota) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/server/status/recorder.go#L254)):*
> ```Go
> 			nodeReg.AddLabel("node_id", strconv.Itoa(int(desc.NodeID)))
> 			if !mr.hasLabel(logReg.GetLabels(), "node_id") {
> 				logReg.AddLabel("node_id", strconv.Itoa(int(desc.NodeID)))
> ```

This does not work for me. The log metric registry should be read-only. 

If we have multiple in-memory servers running one after the other (e.g. think about multiple go tests in one package), the logic here would make the first one "win" the right to get its `node_id` in there. The others that then access the log package afterwards would not have "their" node_id in there and the person looking at the log output would be utterly confused


Is there a way to have the _counters_ in the singleton in `logmetrics`, and the _labels_ in an object that's different in each serveR?
___
*[`pkg/util/log/clog.go` line 115 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E5Mre3Fqt3_BFX1Xj:-N_E5MrfCsMLvsXSbAKs:bj770a5) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/util/log/clog.go#L115)):*
> ```Go
> }
> 
> // LogMetricsRegistry returns the metrics registry used by
> ```

As explained above, you can put this accessor in `logmetrics`. The Set function below can remain here.

**Review by abarganier — COMMENTED** [review]
Again, great feedback. I've made some changes, PTAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-:-N_oowI-DuUQbyw8C70W:b-tptnje)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @knz)

___
*[`pkg/server/server.go` line 1844 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E4GOnCnBK1wYlrn7l:-N_ondgKB-kTB6Xhaobc:b-jeds2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/server/server.go#L1844)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: you could retrieve the registry directly with the right type (`*metric.Registry`) if you put the accessor in package `logmetrics` instead.
</blockquote></details>

Thanks for the tip, this worked well and cleaned up the interface. Done.
___
*[`pkg/server/tenant.go` line 646 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E4MXw5xB_x0PBUOph:-N_onzJJ5qxKgRrQmNlk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/server/tenant.go#L646)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`pkg/server/status/recorder.go` line 134 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E4RGz3sbWIEdgMeht:-N_oo-Hw-gFbZ7nGIyDO:b-8ihar1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/server/status/recorder.go#L134)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: pls provide an example of such code path.
</blockquote></details>

Ah, this was leftovers that I missed/forgot to remove. No such case exists anymore, since the recorder imports `pkg/util/log/logmetrics`, which ensures initialization. 

Removed.
___
*[`pkg/server/status/recorder.go` line 159 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E4VIK0XRZdeTnHr7B:-N_ooDpV3SAGJo-52vzB:b-3q3f0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/server/status/recorder.go#L159)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

I disagree. you can use

```go
import (
   _ ".../util/log/logmetrics"
)
```

at the top of this file, and you'd get the right behavior.

</blockquote></details>

Thanks for this, it worked nicely. Done.
___
*[`pkg/server/status/recorder.go` line 254 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E4jUg77Vl1Hfx7T9h:-N_ooH9S7QzpwZNHaTt3:bcpoi04) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/server/status/recorder.go#L254)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

This does not work for me. The log metric registry should be read-only. 

If we have multiple in-memory servers running one after the other (e.g. think about multiple go tests in one package), the logic here would make the first one "win" the right to get its `node_id` in there. The others that then access the log package afterwards would not have "their" node_id in there and the person looking at the log output would be utterly confused


Is there a way to have the _counters_ in the singleton in `logmetrics`, and the _labels_ in an object that's different in each serveR?
</blockquote></details>

Good point, thank you for bringing this up. 

What we can do is export a function from the package, `logmetrics.NewRegistry()`, that adds the same singleton counters to a fresh registry per-server. This way, each server can add its own labels without anything colliding. 

I've implemented this and found it worked nicely during testing. LMK your thoughts. 
___
*[`pkg/util/log/clog.go` line 115 at r8](https://reviewable.io/reviews/cockroachdb/cockroach/106607#-N_E5Mre3Fqt3_BFX1Xj:-N_oosyA34I0tjtkrqZV:b-h7qx3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea63366a3eb371f1cd2379898689ff6384a52157/pkg/util/log/clog.go#L115)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

As explained above, you can put this accessor in `logmetrics`. The Set function below can remain here.
</blockquote></details>

Done, great tip! Thanks.

**Review by knz — APPROVED** [review]
> Reviewed 7 of 14 files at r9, 2 of 3 files at r10, 5 of 5 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106607)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian)

**Comment by abarganier** [comment]
TFTR! 

bors r=knz

**Pull request merged**
