### PR TITLE
crosscluster/producer: lock producer side tables from schema changes

### PR DESCRIPTION
**Pull request by msbutler**
Informs #133456

Epic: none

Release note: none

### CODE REVIEW

**Comment by msbutler** [comment]
unrelated unit test flake

**Review by rafiss — APPROVED** [review]
nice; thank you for the refactor, it made this very intuitive

just had non-correctness related nits.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134115#-:-OAtAsgE0vlKXwH6Qt0x:b-b8oaje)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @msbutler, and @stevendanna)

___
*[`pkg/ccl/crosscluster/logical/create_logical_replication_stmt.go` line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134115#-OAt99ad6rnH29L5lgYX:-OAt99ad6rnH29L5lgYY:ber7wev) ([raw file](https://github.com/cockroachdb/cockroach/blob/46db2b15503909d92ada54772dd831429820a968/pkg/ccl/crosscluster/logical/create_logical_replication_stmt.go#L212)):*
> ```Go
> 		defer func() {
> 			if err != nil {
> 				err = errors.CombineErrors(err, client.Complete(ctx, spec.StreamID, false))
> ```

nit: the `err != nil` check is not needed, since `CombineErrors` has that already. 

also, since we're changing the return value here, i find it helpful to use the convention that the return variable should be named `retErr`. otherwise, it's easy to mix this `err` up with various other shadowed declarations.

so this would just be
```
defer func() {
  retErr = errors.CombineErrors(retErr, client.Complete(...))
}()
```

here's an example of this pattern: https://github.com/cockroachdb/cockroach/blob/774f2a133d6002a96ade499c528a2d414a20505b/pkg/ccl/backupccl/system_schema.go#L198-L200
___
*[`pkg/ccl/crosscluster/replicationutils/utils.go` line 386 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134115#-OAtAX31A7W6X34GAEuN:-OAtAX31A7W6X34GAEuO:bhfniw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/f94706bee773798bb7f04bca5d8936447fa66a59/pkg/ccl/crosscluster/replicationutils/utils.go#L386)):*
> ```Go
> }
> 
> func LockLDRTables(
> ```

super nit: Lock/Unlock is accurate in terms of the resulting effects, but maybe it would be more accurate to name this `AddLDRReferences`/`RemoveLDRReferences`?

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134115)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @rafiss, and @stevendanna)

___
*[`pkg/ccl/crosscluster/replicationutils/utils.go` line 386 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/134115#-OAtAX31A7W6X34GAEuN:-OAwT2Np5ZMfEEKvSmyf:bsc6s29) ([raw file](https://github.com/cockroachdb/cockroach/blob/f94706bee773798bb7f04bca5d8936447fa66a59/pkg/ccl/crosscluster/replicationutils/utils.go#L386)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

super nit: Lock/Unlock is accurate in terms of the resulting effects, but maybe it would be more accurate to name this `AddLDRReferences`/`RemoveLDRReferences`?
</blockquote></details>

I'm inclined to leave the names as is. Since this helper is in DR land, I think the current naming is friendlier for a DR engineer that wants to quickly reread the logic on schema locking. What matters most to the DR engineer is the effect of this helper ( that it locks the tables), not necessarily how we implement the locking behavior (via references in the table descriptor).

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134115)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @rafiss, and @stevendanna)

___
*[`pkg/ccl/crosscluster/logical/create_logical_replication_stmt.go` line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134115#-OAt99ad6rnH29L5lgYX:-OAwrDleDkJCwyLdaw8o:bviymg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/46db2b15503909d92ada54772dd831429820a968/pkg/ccl/crosscluster/logical/create_logical_replication_stmt.go#L212)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: the `err != nil` check is not needed, since `CombineErrors` has that already. 

also, since we're changing the return value here, i find it helpful to use the convention that the return variable should be named `retErr`. otherwise, it's easy to mix this `err` up with various other shadowed declarations.

so this would just be
```
defer func() {
  retErr = errors.CombineErrors(retErr, client.Complete(...))
}()
```

here's an example of this pattern: https://github.com/cockroachdb/cockroach/blob/774f2a133d6002a96ade499c528a2d414a20505b/pkg/ccl/backupccl/system_schema.go#L198-L200
</blockquote></details>

er, actually, we do need the retErr !=nil condition because if retErr is nil, we do not want to call client.Complete() which shuts down the producer job.

**Review by msbutler — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/134115)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @dt, @rafiss, and @stevendanna)

___
*[`pkg/ccl/crosscluster/logical/create_logical_replication_stmt.go` line 212 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/134115#-OAt99ad6rnH29L5lgYX:-OAwrPcu22x5V41sdqno:bb2hji8) ([raw file](https://github.com/cockroachdb/cockroach/blob/46db2b15503909d92ada54772dd831429820a968/pkg/ccl/crosscluster/logical/create_logical_replication_stmt.go#L212)):*
<details><summary><i>Previously, msbutler (Michael Butler) wrote…</i></summary><blockquote>

er, actually, we do need the retErr !=nil condition because if retErr is nil, we do not want to call client.Complete() which shuts down the producer job.
</blockquote></details>

i did change err to retErr though

**Comment by msbutler** [comment]
TFTR!

bors r=rafiss

**Pull request merged**
