### PR TITLE
client: add a new WriteBatch command

### PR DESCRIPTION
**Pull request by danhhz**
This command takes a BatchRepr, which is the serialized form of a
RocksDB WriteBatch, and applies it directly to the underlying Engine.
The command cannot span Ranges and must be run on an empty keyrange.

WriteBatch is added as a performance optimization for restore and bulk ingest,
which it speeds up considerably (4MB/s -> 18-24MB/s).

BenchmarkKVInsert10000_Native-8             10     111227094 ns/op    97846956 B/op      222610 allocs/op
BenchmarkKVInsert10000_SQL-8                10     154972326 ns/op   129806703 B/op      328366 allocs/op
BenchmarkKVInsert10000_WriteBatch-8         50      23408738 ns/op     5700528 B/op       52803 allocs/op

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13104)

### CODE REVIEW

**Comment by danhhz** [comment]
I'm hoping to split the c++ code under ccl, which wasn't done in the feature branch. Everything else should be good to go.

Reviewers, any particular pointers to existing tests for mvcc stats on commands?

**Comment by petermattis** [comment]
The `storage/engine` portion of this change :lgtm:

---

Review status: 0 of 21 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/storage/engine/rocksdb/db.cc, line 2114 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbFxEtbr69ijKz1ayWO:-KbFxEtbr69ijKz1ayWP:b-8d1fn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/storage/engine/rocksdb/db.cc#L2114)):*
> ```cpp
> // is a chance that we run into values ahead of now_nanos. Instead, now_nanos
> // should be taken as a hint but determined by the max timestamp encountered.
> MVCCStatsResult MVCCComputeStatsInternal(
> ```

This should be moved to the "unnamed" `namespace' so the symbol doesn't leak into the global namespace. Probably confusing to do that move in this PR and not urgent. Add a TODO.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-:-KbFxTiZVeWYsP0d4ubR:b-rx3lug)*

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/ccl/storageccl/writebatch.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbFytxrFwgYOqhQsqAs:-KbFytxrFwgYOqhQsqAt:b-4u128x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/ccl/storageccl/writebatch.go#L28)):*
> ```Go
> 
> // WriteBatch applies the operations encoded in a BatchRepr.
> func WriteBatch(
> ```

The new naming convention for functions like this is `EvalWriteBatch` (`storage.Command` is going to get at least one new field soon). Make it unexported if you can.

---

*[pkg/ccl/storageccl/writebatch.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbFzTH9unwKAeTYQPnj:-KbFzTH9unwKAeTYQPnk:b1ey8bo) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/ccl/storageccl/writebatch.go#L45)):*
> ```Go
> 
> 	if args.DataSpan.Key.Compare(args.Key) < 0 || args.DataSpan.EndKey.Compare(args.EndKey) > 0 {
> 		// TODO(dan): Add a new field in roachpb.Error, so the client can catch
> ```

Does this need a new field or can we reuse RangeKeyMismatchError? That already triggers a retry of separate sub-batches at the DistSender level. (so if you're sending this through DistSender you may need a new error type to reach up to the higher-level restore code)

---

*[pkg/ccl/storageccl/writebatch_test.go, line 72 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbFzjApvuAaSuXwOZh4:-KbFzjAq1h-pnIpMBMPa:blx8wlg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/ccl/storageccl/writebatch_test.go#L72)):*
> ```Go
> 
> 	// Key range in request spans multiple ranges.
> 	// TODO(dan): What's the current best practice for these sorts of sentinel
> ```

If it's only caught in tests (and not too frequently), then `Errorf` and `testutils.IsError` are fine. If it's caught in production code we should add a new error type to `roachpb`.

---

*[pkg/storage/replica.go, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbG-DHzkWWRQtTWMM2p:-KbG-DHzkWWRQtTWMM2q:b-7aeda) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/storage/replica.go#L104)):*
> ```Go
> 
> // PropEvalKVEnabled returns whether to enable experimental support for proposer-evaluated KV.
> func PropEvalKVEnabled() bool {
> ```

We have the same function in `helpers_test.go` (with `Proposer` spelled in full); rename this one to match and delete the one in `helpers_test.go`.

---

*[pkg/storage/replica_command.go, line 2140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbG-ght1zCqll_RhcCP:-KbG-ght1zCqll_RhcCQ:b-sydp8w) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/storage/replica_command.go#L2140)):*
> ```Go
> // implementation of the WriteBatch command.
> func SetWriteBatchCmd(cmd Command) {
> 	writeBatchCmd.Eval = cmd.Eval
> ```

Assign the entire Command, not just the Eval field. 

Why the extra indirection instead of just doing `commands[roachpb.WriteBatch] = cmd`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-:-KbG0BHlXkXnF3Y7lQ-Q:bnfp4nl)*

**Comment by danhhz** [comment]
Rebased on top of the c++ part, which got split out and PR'd separately.

@bdarnell Can you take another close look at how the command hook works? I worry about concurrent use of that map and relying on it only being called at Init seems fishy

---

Review status: 7 of 18 files reviewed at latest revision, 6 unresolved discussions.

---

*[pkg/ccl/storageccl/writebatch.go, line 28 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbFytxrFwgYOqhQsqAs:-KbGtv7UO-HK8dFIhF_j:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/ccl/storageccl/writebatch.go#L28)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The new naming convention for functions like this is `EvalWriteBatch` (`storage.Command` is going to get at least one new field soon). Make it unexported if you can.
</blockquote></details>

Done.

---

*[pkg/ccl/storageccl/writebatch.go, line 45 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbFzTH9unwKAeTYQPnj:-KbvzxuJTqSfXeilvU_m:bc7qnrz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/ccl/storageccl/writebatch.go#L45)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Does this need a new field or can we reuse RangeKeyMismatchError? That already triggers a retry of separate sub-batches at the DistSender level. (so if you're sending this through DistSender you may need a new error type to reach up to the higher-level restore code)
</blockquote></details>

Nah, we can't. Added a comment

---

*[pkg/ccl/storageccl/writebatch_test.go, line 72 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbFzjApvuAaSuXwOZh4:-Kbw-Rnl8BXICVcRZInH:b-q05qw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/ccl/storageccl/writebatch_test.go#L72)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If it's only caught in tests (and not too frequently), then `Errorf` and `testutils.IsError` are fine. If it's caught in production code we should add a new error type to `roachpb`.
</blockquote></details>

this overlaps the other TODO you commented on. removed this one because we don't really need two of them

---

*[pkg/storage/replica.go, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbG-DHzkWWRQtTWMM2p:-KbGqpa6reqgNSY6TtRk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/storage/replica.go#L104)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

We have the same function in `helpers_test.go` (with `Proposer` spelled in full); rename this one to match and delete the one in `helpers_test.go`.
</blockquote></details>

Done.

---

*[pkg/storage/replica_command.go, line 2140 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-KbG-ght1zCqll_RhcCP:-KbGtdhk9ZKFpWOcobnL:b-wx500t) ([raw file](https://github.com/cockroachdb/cockroach/blob/d77ba8aa7b18f745b0bd134ccbe966f8813862d4/pkg/storage/replica_command.go#L2140)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Assign the entire Command, not just the Eval field. 

Why the extra indirection instead of just doing `commands[roachpb.WriteBatch] = cmd`?
</blockquote></details>

Something like this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-:-Kbw0FgdrXS7p7087Joo:b55it2s)*

**Comment by bdarnell** [comment]
:lgtm:

I'm OK with relying on `init`-only updates to that map.

---

Reviewed 15 of 15 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13104#-:-KbzRgBZjKXZ3VC8gf9T:b-x0gt42)*

**Comment by danhhz** [comment]
Thanks for the reviews!

**Pull request merged**
