### PR TITLE
importccl: Add DROP TABLE [IF EXISTS] support for import pgdump.

### LINKED ISSUE #53112: importccl: support DROP TABLE [IF EXISTS] for PGDUMP
A pgdump generated by default from `ogr2ogr` or using `pg_dump -clean` includes a `DROP TABLE [IF EXISTS]` line that after https://github.com/cockroachdb/cockroach/commit/921c60a0af19226b57274c070cdb5ca5d14a54d7 we no longer ignore and explicitly error out. An example of a PGDUMP i expect to work using `IMPORT PGDUMP`:

```
DROP TABLE public.pgdump_test;
CREATE TABLE public.pgdump_test (
    a integer
);
```

```
DROP TABLE IF EXISTS public.pgdump_test;
CREATE TABLE public.pgdump_test (
    a integer
);
```

Ideally we should be able to handle these -- it makes sense, especially from the geospatial perspective -- for a user to have a dump that nukes a table and overwrites it if necessary.

Might be a good start project / first issue, fwiw.

### PR DESCRIPTION
**Pull request by mokaixu**
Previously, whenever a DROP TABLE statement was parsed, an
error was thrown and the import would fail since DROP TABLE
statements were not supported.

Now, when we encounter a DROP TABLE statement for a target table
foo, if foo exists, then we throw an error indicating to the user
to drop the table foo. Otherwise, if foo does not exist, we silently
ignore the DROP statement and proceed with the pgdump import.

Resolves: #53112

Release note: None

### CODE REVIEW

**Review by adityamaru — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @mokaixu)

___
*[pkg/ccl/importccl/read_import_pgdump.go, line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56920#-MMaWtJ3E-p7RR_uDSt2:-MMaWtJ3E-p7RR_uDSt3:b-w00d0l) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5d41874d80a7ffa3a2de4ff633e05c872a56ec1/pkg/ccl/importccl/read_import_pgdump.go#L511)):*
> ```Go
> 		}
> 	case *tree.DropTable:
> 		names := stmt.Names
> ```

can we just add a short comment documenting the behavior. If we find a table with the same name in the DB being imported into and public schema then we....else....
___
*[pkg/ccl/importccl/read_import_pgdump.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56920#-MMaW6ty8WYRFaBROXrm:-MMaW6ty8WYRFaBROXrn:b90svpf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5d41874d80a7ffa3a2de4ff633e05c872a56ec1/pkg/ccl/importccl/read_import_pgdump.go#L525)):*
> ```Go
> 				)
> 				if err != nil {
> 					return errors.Wrapf(err, `drop table "%s" to proceed with import`, tableName)
> ```

nit: drop table foo and then retry the import
___
*[pkg/ccl/importccl/read_import_pgdump.go, line 910 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56920#-MMaXX0RAa1LZoWXOwTp:-MMaXX0RAa1LZoWXOwTq:bgzjzag) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5d41874d80a7ffa3a2de4ff633e05c872a56ec1/pkg/ccl/importccl/read_import_pgdump.go#L910)):*
> ```Go
> 				return errors.Errorf("unsupported %T statement: %s", i, i)
> 			}
> 		case *tree.DropTable:
> ```

can we just add this to the list of tree.CreateTable etc cause it is "handled during schema extraction"

**Review by mokaixu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/ccl/importccl/read_import_pgdump.go, line 511 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56920#-MMaWtJ3E-p7RR_uDSt2:-MMptHEJCUO5cd8bCYiM:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5d41874d80a7ffa3a2de4ff633e05c872a56ec1/pkg/ccl/importccl/read_import_pgdump.go#L511)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

can we just add a short comment documenting the behavior. If we find a table with the same name in the DB being imported into and public schema then we....else....
</blockquote></details>

done
___
*[pkg/ccl/importccl/read_import_pgdump.go, line 525 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56920#-MMaW6ty8WYRFaBROXrm:-MMpu_qh3bVTKAmA-K87:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5d41874d80a7ffa3a2de4ff633e05c872a56ec1/pkg/ccl/importccl/read_import_pgdump.go#L525)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

nit: drop table foo and then retry the import
</blockquote></details>

done
___
*[pkg/ccl/importccl/read_import_pgdump.go, line 910 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56920#-MMaXX0RAa1LZoWXOwTp:-MMq4oJK-FNZahbiU5KD:bejeyqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c5d41874d80a7ffa3a2de4ff633e05c872a56ec1/pkg/ccl/importccl/read_import_pgdump.go#L910)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

can we just add this to the list of tree.CreateTable etc cause it is "handled during schema extraction"
</blockquote></details>

makes sense, done

**Review by adityamaru — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56920)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by mokaixu** [comment]
bors r=adityamaru

**Pull request merged**
