### PR TITLE
opt: create key for UNIQUE WITHOUT INDEX constraints

### LINKED ISSUE #58944: opt: teach the optimizer that columns with a valid UNIQUE WITHOUT INDEX constraint form a key
The optimizer maintains functional dependencies (FDs) on all relational expressions during query optimization. These FDs can enable certain types of optimizations that wouldn't be possible otherwise. We should use the fact that columns are part of a valid `UNIQUE WITHOUT INDEX` constraint as an indication that we can add a key on those columns to the FDs.

### PR DESCRIPTION
**Pull request by rytaft**
**opt: don't add unique constraints with an index to test catalog**

This commit updates the test catalog so that it is consistent with the
real catalog and doesn't add unique constraints with an index to the
catalog table. This also prevents some tests from failing unnecessarily.

Release note: None

**opt: create key for UNIQUE WITHOUT INDEX constraints**

This commit teaches the optimizer that columns with a valid `UNIQUE WITHOUT INDEX`
constraint form a key, and the functional dependencies should reflect that. This will be
necessary to support locality optimized search.

Fixes #58944
Informs #55185

Release note (performance improvement): The optimizer now knows that
the unique columns in an implicitly partitioned unique index form a
key. This can be used to enable certain optimizations and may result
in better plans.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
[nit] The PR description doesn't include the first commit.

:lgtm: 

> Reviewed 6 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-:-MTb4KdC1qhTDW6nbXtD:b3ngwv3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/unique, line 1153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTb5tL02j3DcgqpCKib:-MTb5tL02j3DcgqpCKic:b500fyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3dd20a83234385e0526f15ee3ee6ca60efe9461/pkg/sql/opt/exec/execbuilder/testdata/unique#L1153)):*
> ```
> 
> # Same test as the previous, but now that the constraint has been validated, it
> # can be treated as a key.
> ```

So the only difference is that this test includes the `equality cols are key`? How does that affect the lookup join? Does it allow it to be more efficient?
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 495 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTb42o3726aTl55r6IB:-MTb42o3726aTl55r6IC:b-5601l) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae8b848ea71b4884ea3ec568e97726e5e450f86/pkg/sql/opt/testutils/testcat/create_table.go#L495)):*
> ```Go
> 	if !withoutIndex {
> 		return
> 	}
> ```

You beat me to this. Thanks!

**Review by rytaft — COMMENTED** [review]
TFTR! Updated and fixed a previous oversight. PTAL.

> [nit] The PR description doesn't include the first commit.

Done.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-:-MTbpkxn6pKuxyFX9h5J:b-2pj352)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/testdata/unique, line 1153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTb5tL02j3DcgqpCKib:-MTbSb_T1kpqnBBbEJsp:b-1rlpbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3dd20a83234385e0526f15ee3ee6ca60efe9461/pkg/sql/opt/exec/execbuilder/testdata/unique#L1153)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

So the only difference is that this test includes the `equality cols are key`? How does that affect the lookup join? Does it allow it to be more efficient?
</blockquote></details>

I realized that the lookup join case was actually incorrect (after the update we can't guarantee that the constraints are unique... which is why we need the uniqueness checks in the first place), but the hash join cases are correct (right cols are key). This is because the right side is from the buffered row that was updated, and we know that only a single row was updated since the filter `a=5` was applied to the table before the update.

But anyway, you're right that both "equality cols are key" and "right cols are key" will make the join more efficient -- added a comment.
___
*[pkg/sql/opt/testutils/testcat/create_table.go, line 495 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTb42o3726aTl55r6IB:-MTbSQX8B1QcdIw3Nuv7:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae8b848ea71b4884ea3ec568e97726e5e450f86/pkg/sql/opt/testutils/testcat/create_table.go#L495)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

You beat me to this. Thanks!
</blockquote></details>

:thumbsup:

**Review by mgartner — APPROVED** [review]
> Reviewed 10 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/exec/execbuilder/testdata/unique, line 1153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTb5tL02j3DcgqpCKib:-MTbu27SBQ8UBfur1otM:b-em4diw) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3dd20a83234385e0526f15ee3ee6ca60efe9461/pkg/sql/opt/exec/execbuilder/testdata/unique#L1153)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I realized that the lookup join case was actually incorrect (after the update we can't guarantee that the constraints are unique... which is why we need the uniqueness checks in the first place), but the hash join cases are correct (right cols are key). This is because the right side is from the buffered row that was updated, and we know that only a single row was updated since the filter `a=5` was applied to the table before the update.

But anyway, you're right that both "equality cols are key" and "right cols are key" will make the join more efficient -- added a comment.
</blockquote></details>

Cool! Good catch too!
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 257 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTbvxDR0KGyCZ8LTk_2:-MTbvxDSCs39w2cDYT7x:b-o0cqkg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5330e7773f0fd5c6bd6a36ec65ea9130cd70da4/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L257)):*
> ```Go
> 		tabMeta,
> 		h.uniqueAndPrimaryKeyOrdinals,
> 		&tree.IndexFlags{IgnoreUniqueWithoutIndexKeys: true},
> ```

[nit] add your explanation of why this is required ("after the update we can't guarantee that the constraints are unique... which is why we need the uniqueness checks in the first place")

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/opt/exec/execbuilder/testdata/unique, line 1153 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTb5tL02j3DcgqpCKib:-MTcRILWASOrhLfuJn49:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3dd20a83234385e0526f15ee3ee6ca60efe9461/pkg/sql/opt/exec/execbuilder/testdata/unique#L1153)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Cool! Good catch too!
</blockquote></details>

Thanks!
___
*[pkg/sql/opt/optbuilder/mutation_builder_unique.go, line 257 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTbvxDR0KGyCZ8LTk_2:-MTcRLn8CBVLIazBdc9D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f5330e7773f0fd5c6bd6a36ec65ea9130cd70da4/pkg/sql/opt/optbuilder/mutation_builder_unique.go#L257)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] add your explanation of why this is required ("after the update we can't guarantee that the constraints are unique... which is why we need the uniqueness checks in the first place")
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-:-MTflcVx5KK7OE_zsWd2:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/testutils/testcat/testdata/foreign_keys, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTfl3P5-9kC_JD9vIkd:-MTfl3P5-9kC_JD9vIke:b-1gzfbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae8b848ea71b4884ea3ec568e97726e5e450f86/pkg/sql/opt/testutils/testcat/testdata/foreign_keys#L15)):*
> ```
>  ├── p int not null
>  ├── crdb_internal_mvcc_timestamp decimal [hidden] [system]
>  ├── INDEX primary
> ```

[nit] Strange that there's nothing left indicating `p` is a key, are we missing a "unique" mention for the index?

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-:-MThL5EyDZF2jjct0CDx:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/testutils/testcat/testdata/foreign_keys, line 15 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTfl3P5-9kC_JD9vIkd:-MThI7sn7SQHY3J-cLP5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3ae8b848ea71b4884ea3ec568e97726e5e450f86/pkg/sql/opt/testutils/testcat/testdata/foreign_keys#L15)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Strange that there's nothing left indicating `p` is a key, are we missing a "unique" mention for the index?
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
> Reviewed 22 of 22 files at r5, 11 of 11 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/cat/utils.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTh_ZY70-pbya9NRTOB:-MTh_ZY70-pbya9NRTOC:b3bxylw) ([raw file](https://github.com/cockroachdb/cockroach/blob/214d9cbb2fd46bc53ee2b1c5c5e532428e072083/pkg/sql/opt/cat/utils.go#L194)):*
> ```Go
> 	if idx.IsUnique() {
> 		unique = "UNIQUE "
> 	}
> ```

We could have a special case for the primary index like:

```
 ├── PRIMARY INDEX primary
 │    └── x int not null
```

But I guess that'll alwasy be redundant because "primary" will always be the name of the index..

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/cat/utils.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTh_ZY70-pbya9NRTOB:-MThd_uW9G9FYeT20nNV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/214d9cbb2fd46bc53ee2b1c5c5e532428e072083/pkg/sql/opt/cat/utils.go#L194)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

We could have a special case for the primary index like:

```
 ├── PRIMARY INDEX primary
 │    └── x int not null
```

But I guess that'll alwasy be redundant because "primary" will always be the name of the index..
</blockquote></details>

Done.

**Review by mgartner — APPROVED** [review]
> Reviewed 22 of 22 files at r7, 11 of 11 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @rytaft)

___
*[pkg/sql/opt/cat/utils.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTh_ZY70-pbya9NRTOB:-MThfJyh9RGVeLOqCCWN:b-un1wkt) ([raw file](https://github.com/cockroachdb/cockroach/blob/214d9cbb2fd46bc53ee2b1c5c5e532428e072083/pkg/sql/opt/cat/utils.go#L194)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Haha well I didn't have conviction that this was a great suggestion, but as long as you're for it then :thumbsup: 
___
*[pkg/sql/opt/cat/utils.go, line 192 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MThfbk95v01MFQ5V0N1:-MThfbk95v01MFQ5V0N2:bu6ycrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7205b194ceff841b0bdac56331b48431488feba2/pkg/sql/opt/cat/utils.go#L192)):*
> ```Go
> 	}
> 	if idx.IsUnique() {
> 		if idx.Ordinal() == PrimaryIndex {
> ```

[nit] I think we could check only the ordinal for the PRIMARY case, because there's no such thing as a non-unique primary index, correct?

**Review by rytaft — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-:-MTk0MJa8BFoHAGIIz23:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/cat/utils.go, line 194 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MTh_ZY70-pbya9NRTOB:-MTjxBPNBaym7tbxS8Au:b-biimn8) ([raw file](https://github.com/cockroachdb/cockroach/blob/214d9cbb2fd46bc53ee2b1c5c5e532428e072083/pkg/sql/opt/cat/utils.go#L194)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Haha well I didn't have conviction that this was a great suggestion, but as long as you're for it then :thumbsup: 
</blockquote></details>

Yea, I think it's a slight improvement, since it gives more information and more closely matches the real output of SHOW CREATE TABLE
___
*[pkg/sql/opt/cat/utils.go, line 192 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/60591#-MThfbk95v01MFQ5V0N1:-MTjx4Il5gqxxKFp5a1D:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/7205b194ceff841b0bdac56331b48431488feba2/pkg/sql/opt/cat/utils.go#L192)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

[nit] I think we could check only the ordinal for the PRIMARY case, because there's no such thing as a non-unique primary index, correct?
</blockquote></details>

Done.

**Pull request merged**
