### PR TITLE
sql/sem/tree: TestEval improvements

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38784)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @mjibson)

___
*[pkg/sql/sem/tree/eval_test.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38784#-LjPimiD6c3RnDvwPV84:-LjPimiD6c3RnDvwPV85:byywaep) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b6a6d23df8fdfb22c58881c02de5c83645236f/pkg/sql/sem/tree/eval_test.go#L111)):*
> ```Go
> 				return "NULL"
> 			}
> ```

Ok what's going on after this line -- why don't you simply do ``return res.String` here and be done with it?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38784)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/sql/sem/tree/eval_test.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38784#-LjRdbLm8Cr1R5n0HKVy:-LjRdbLm8Cr1R5n0HKVz:bw0tqsr) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b6a6d23df8fdfb22c58881c02de5c83645236f/pkg/sql/sem/tree/eval_test.go#L53)):*
> ```Go
> 
> 	walkExpr := func(t *testing.T, getExpr func(tree.TypedExpr) (tree.TypedExpr, error)) {
> 		walk(t, func(d *datadriven.TestData) string {
> ```

Don't we need to do something with the string that gets returned here to make sure the tests still fail on error? Or is that somehow handled by `datadriven.RunTest` already?
___
*[pkg/sql/sem/tree/main_test.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38784#-LjRdrBU4gPYLVbKTPId:-LjRdrBU4gPYLVbKTPIe:b-hyqxbf) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b6a6d23df8fdfb22c58881c02de5c83645236f/pkg/sql/sem/tree/main_test.go#L25)):*
> ```Go
> )
> 
> //go:generate ../../util/leaktest/add-leaktest.sh *_test.go
> ```

It doesn't like this but I'm not too sure why, maybe not enough ..?
___
*[pkg/sql/sem/tree/testdata/eval/overflow, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38784#-LjRdzpq6ZiabuiGOl1h:-LjRdzpq6ZiabuiGOl1i:b-rpahry) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d446eb312ab3c607eb62f2966df57e1e850145c/pkg/sql/sem/tree/testdata/eval/overflow#L55)):*
> ```
> 9223372036854775807
> 
> # We would expect that this expression has the same result as -9223372036854775808:::int8, but in both Postgres and Cockroach it is valid.
> ```

:grimacing:

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38784)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @mjibson)

___
*[pkg/sql/sem/tree/eval_test.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38784#-LjRdbLm8Cr1R5n0HKVy:-LjS0zsn7brXzBJwoclD:b-5202wg) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b6a6d23df8fdfb22c58881c02de5c83645236f/pkg/sql/sem/tree/eval_test.go#L53)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Don't we need to do something with the string that gets returned here to make sure the tests still fail on error? Or is that somehow handled by `datadriven.RunTest` already?
</blockquote></details>

That's handled by datadriven. It errors if the returned string doesn't match the expected string.
___
*[pkg/sql/sem/tree/eval_test.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38784#-LjPimiD6c3RnDvwPV84:-LjS1ZJcEnWRhQV_PMLH:b-rjee02) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b6a6d23df8fdfb22c58881c02de5c83645236f/pkg/sql/sem/tree/eval_test.go#L111)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Ok what's going on after this line -- why don't you simply do ``return res.String` here and be done with it?
</blockquote></details>

Added a comment explaining this. A SQL result is not printed the same as its datum is, which is SQL-parseable. For example, a bit array's res.String would be `1001` but as a datum it's `B'1001'`, so we have to parse the res.String back into a datum.
___
*[pkg/sql/sem/tree/main_test.go, line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38784#-LjRdrBU4gPYLVbKTPId:-LjS1jb-AqGWR8WY7FYR:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b6a6d23df8fdfb22c58881c02de5c83645236f/pkg/sql/sem/tree/main_test.go#L25)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

It doesn't like this but I'm not too sure why, maybe not enough ..?
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38784)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @mjibson)

___
*[pkg/sql/sem/tree/eval_test.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38784#-LjPimiD6c3RnDvwPV84:-LjUeteJ8RPCbFNgWqWG:ba05lzt) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b6a6d23df8fdfb22c58881c02de5c83645236f/pkg/sql/sem/tree/eval_test.go#L111)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary><blockquote>

Added a comment explaining this. A SQL result is not printed the same as its datum is, which is SQL-parseable. For example, a bit array's res.String would be `1001` but as a datum it's `B'1001'`, so we have to parse the res.String back into a datum.
</blockquote></details>

Yes yes your comment here is rephrasing what the code does, which I understand.

My question is *why* this is needed. what is wrong with using the SQL result in the datadriven reference output, instead of the datum representation.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38784)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @knz, and @mjibson)

___
*[pkg/sql/sem/tree/eval_test.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38784#-LjPimiD6c3RnDvwPV84:-LjUhmIVD4EbA9xly0jf:b-wd8xup) ([raw file](https://github.com/cockroachdb/cockroach/blob/79b6a6d23df8fdfb22c58881c02de5c83645236f/pkg/sql/sem/tree/eval_test.go#L111)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Yes yes your comment here is rephrasing what the code does, which I understand.

My question is *why* this is needed. what is wrong with using the SQL result in the datadriven reference output, instead of the datum representation.
</blockquote></details>

Ah. It's because the other two subtests in this function only produce datums, and skip the full SQL layer. We could rewrite those tests to also output SQL results, I suppose. It's still not exactly clear what TestEval is supposed to do and what TestLogic is supposed to do. Maybe we should think about that more.

**Comment by mjibson** [comment]
PTAL

**Review by jordanlewis — APPROVED** [review]
:lgtm: thanks for taking care of this.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38784#-:-LjrEsYL3hb7QaznaSOt:b-lm9myv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Pull request merged**
