### PR TITLE
WIP. ui: Statements extraction

### PR DESCRIPTION
**Pull request by koorosh**
Statements page and all related logic are extracted to `/modules/statements` which
can be seen as a independent package.

TODO: 
- [ ] Move all `statements` dependencies to `common` module

Screenshot 2020-04-08 at 17 28 26

Statements extraction

### CODE REVIEW

**Comment by dhartunian** [comment]
@koorosh do you see us publishing modules to NPM in this scenario?

**Comment by dhartunian** [comment]
Also as a related issue, I'll revive the storybook PR so we can test this out 😄

**Comment by dhartunian** [comment]
in general, I do like this pattern of organizing the src hierarchy by functionality.

**Comment by koorosh** [comment]
> @koorosh do you see us publishing modules to NPM in this scenario?

Yes, `Observability components` (as shown on diagram) is supposed to be NPM module. 
In this draft implementation I kept everything under the same module just for simplicity.

**Pull request closed without merging**
