### PR TITLE
build: correct documentation

### PR DESCRIPTION
**Pull request by yaojingguo**
1. ./deploy/build should be ./build/deploy
2. Add backtick characters

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3574)

### CODE REVIEW

**Comment by tamird** [comment]
lgtm

**Comment by tschottdorf** [comment]
while you're there, can you change the sentence:

> To build this image, run `./builder.sh init`.

to

> To build this image, run `./builder.sh init`. The resulting image `cockroachdb/builder` can be run conveniently via `./builder.sh`.

LGTM

**Comment by yaojingguo** [comment]
@tschottdorf, a new commit after adding your suggested change.

**Comment by tschottdorf** [comment]
LGTM

**Pull request merged**
