### PR TITLE
pgwire: include detail and hint in error tests

### PR DESCRIPTION
**Pull request by knz**
Needed for #103857.
Epic: CRDB-27642

### CODE REVIEW

**Review by ecwall — APPROVED** [review]

**Comment by knz** [comment]
thank you!

bors r=ecwall

**Review by rafiss — CHANGES_REQUESTED** [review]
have you run these against postgres to ensure that the test still pass? you can use `./dev test pkg/sql/pgwire -f=TestPGTest--test-args='-addr localhost:5432`

i'm thinking that we only want to include the hint and detail if `keepErrMessage` is true.

**Comment by knz** [comment]
>have you run these against postgres to ensure that the test still pass? you can use ./dev test pkg/sql/pgwire -f=TestPGTest--test-args='-addr localhost:5432'

I have checked that the tests I am touching have the same behavior on pg, yes.

**However** what you request is not possible -- the pg compat for this test had been broken already before my PR. For example the following. I don't believe it's in-scope for this PR to fix these problems.

```
            expected:
            {"Type":"ErrorResponse","Code":"34000","Message":"unknown portal \"\""}
            {"Type":"ReadyForQuery","TxStatus":"I"}

            found:
            {"Type":"ErrorResponse","Code":"34000","Message":"portal \"\" does not exist"}
            {"Type":"ReadyForQuery","TxStatus":"I"}

            expected:
            {"Type":"CommandComplete","CommandTag":"RESET"}
            {"Type":"ReadyForQuery","TxStatus":"I"}

            found:
            {"Type":"ParameterStatus","Name":"IntervalStyle","Value":"postgres"}
            {"Type":"CommandComplete","CommandTag":"RESET"}
            {"Type":"ReadyForQuery","TxStatus":"I"}

            {"Type":"ParseComplete"}
            {"Type":"ErrorResponse","Code":"42804","Message":"binary data has type 0 (-) instead of expected 16 (boolean) in record column 1"}
            {"Type":"ReadyForQuery","TxStatus":"I"}

            found:
            {"Type":"ParseComplete"}
            {"Type":"ErrorResponse","Code":"42804","Message":"wrong data type: 0, expected 16"}
            {"Type":"ReadyForQuery","TxStatus":"I"}
```

**Comment by knz** [comment]
ok well i can't merge this unless there's a new review disposition now

**Review by rafiss — APPROVED** [review]
i see, thanks for checking

**Comment by rafiss** [comment]
oh, well i still wonder what you think about this:

> i'm thinking that we only want to include the hint and detail if keepErrMessage is true.

is there a reason to unconditionally include detail and hint?

**Comment by knz** [comment]
cheers

bors r=ecwall,rafiss

**Comment by knz** [comment]
> is there a reason to unconditionally include detail and hint?

ok here I do not have an opinion.

Do you think it's better?

**Comment by knz** [comment]
i have done the keepErrMessage thing.

bors r=ecwall,rafiss

**Review by rafiss — COMMENTED** [review]
thank you, yes that feels more consistent to me.

**Comment by knz** [comment]
bors single on r=ecwall,rafiss

**Comment by healthy-pod** [comment]
bors single off

**Comment by knz** [comment]
bors r=ecwall,rafiss

**Comment by knz** [comment]
This was #105057 .

**Comment by knz** [comment]
bors r=ecwall,rafiss

**Pull request merged**
