### PR TITLE
ui: send request state to component, process data in components

### PR DESCRIPTION
**Pull request by xinhaoz**
We should not decouple the data from a fetch request and fields
describing the request/response like `inFlight`, `valid`,
`lastUpdated` which are stored in redux, when passing them as props
into the component.

In traditional redux apps we we would be able to select the request
state as a whole unit, getting fields like `isLoading`, `error` and
etc with the data portion of the payload.  Unfortunately, with the
our split redux stores in db-console and CC, we were not able to
select directly from the stores.  Instead, we have been following a
pattern of creating selectors for each required part of the request
field (e.g. `selectData`, `selectError`, `selectDataIsValid`) for
each cached request, having to create a copy of each selector in both
db-console and cluster-ui. These selectors are then used to pass each
field independently as a prop. One can see how this boilerplate code
can quickly multiply with the number of new requests being created.

This pattern was probably a mistake -- we use selectors to memoize
computations when we want to transform data from the redux store.
For modern React we have built-in utilities like `useMemo` that can
accomplish this within the component. For many fields currently using
`createSelector`, like `isLoading`, the logic is extremely simple, where
the field is directly read and returned with no computation. This means
caching with `createSelector`in most cases is unnecessary, so we have
a lot of boilerplate with no useful effects. In addition, the processing
of some of the data in each prop selectors (db-console and cluster-ui)
means we have code that gets duplicated.  This is hard to maintain and
can become confusing as the prop may even go through more processing
when inside the component.

We should adopt a pattern of sending the entire request state for cached
data fetches to the components reading them. This commit introduces the
`RequestState<T>>` type which going forward should be used as the redux
field type for all cached data fetches in cluster-ui, and be prop type
used by components that use the response.

This commit shows an example of what can be done with the statements page
and sql stats response when we adopt this pattern. Note that for class
components, where `useMemo` is not available, we can just use redux's
selectors/reselect to help memoize when necessary.

Release note: None

--------------------
DB-Console: https://www.loom.com/share/2dbc66751fce49aea25b5f341d26e76a
CC: https://www.loom.com/share/3cd57711da2441eaab9fbf593607c03d

Epic: CRDB-25476

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
Nice changes!
I would like to see a loom with the page working on DB and CC

> Reviewed 14 of 14 files at r1, 11 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-:-NSqwvJ_2GLjmI5WPlF0:bj9f8iw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/db-console/src/redux/apiReducers.ts` line 650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-NSqv73J404mJPwq7XtB:-NSqv73J404mJPwq7XtC:b86ngej) ([raw file](https://github.com/cockroachdb/cockroach/blob/44a67555eced6ff461824a5b7f2e2fd670f04f12/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L650)):*
> ```XML
> // This mapped type assigns keys in object type T where the key value
> // is of type V to the key value. Otherwise, it assigns it 'never'.
> // THis enables one to etract keys in an object T of type V.
> ```

nit: this
nit: extract?
___
*[`pkg/ui/workspaces/db-console/src/views/statements/statements.spec.tsx` line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-NSqwsCv02x6ODmr8WxU:-NSqwsCv02x6ODmr8WxV:blv8nrf) ([raw file](https://github.com/cockroachdb/cockroach/blob/99a4c74fbd4988b958229e8cbd50e4c8e31286fd/pkg/ui/workspaces/db-console/src/views/statements/statements.spec.tsx#L58)):*
> ```XML
>   fixedWindowEnd: moment(1646334815),
> };
> ```

why all these tests got removed?

**Review by j82w — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101188)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.tsx` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-NSqw386EQkbYWjS9gHh:-NSqw386EQkbYWjS9gHi:bvjxtus) ([raw file](https://github.com/cockroachdb/cockroach/blob/44a67555eced6ff461824a5b7f2e2fd670f04f12/pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.tsx#L47)):*
> ```XML
>   const regions = filters.regions?.length > 0 ? filters.regions.split(",") : [];
>   const nodes = filters.nodes?.length > 0 ? filters.nodes.split(",") : [];
>   const appNames = filters.app
> ```

I don't see this being used anywhere. Am I missing something?
___
*[`pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.tsx` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-NSqwtAH3OratWAaUC6F:-NSqwtAH3OratWAaUC6G:boexypv) ([raw file](https://github.com/cockroachdb/cockroach/blob/44a67555eced6ff461824a5b7f2e2fd670f04f12/pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.tsx#L144)):*
> ```XML
>       if (
>         data.internal_app_name_prefix &&
>         app.startsWith(data.internal_app_name_prefix)
> ```

Should there be a check if the app value exists? It checks below: ` apps.add(app ? app : unset);`

**Review by xinhaoz — COMMENTED** [review]
Loom added!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-:-NSr3E429M1f0iGrOIwO:b-p5umyt)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @maryliag)

___
*[`pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.tsx` line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-NSqw386EQkbYWjS9gHh:-NSqzimR2ADMme22OvPQ:b-hh5kex) ([raw file](https://github.com/cockroachdb/cockroach/blob/44a67555eced6ff461824a5b7f2e2fd670f04f12/pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.tsx#L47)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

I don't see this being used anywhere. Am I missing something?
</blockquote></details>

Ah I think that was deleted by a merge conflict by accident (it's used in the next commit) - put it back for this commit as well.
___
*[`pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.tsx` line 144 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-NSqwtAH3OratWAaUC6F:-NSr-fcb8aNyq2BMZ11G:bfz4huy) ([raw file](https://github.com/cockroachdb/cockroach/blob/44a67555eced6ff461824a5b7f2e2fd670f04f12/pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.tsx#L144)):*
<details><summary><i>Previously, j82w (Jake) wrote…</i></summary><blockquote>

Should there be a check if the app value exists? It checks below: ` apps.add(app ? app : unset);`
</blockquote></details>

Ah yes it might be a good idea to add that in. It's true we don't guarantee app is not null in key_data. I also added some tests for this case.
___
*[`pkg/ui/workspaces/db-console/src/redux/apiReducers.ts` line 650 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-NSqv73J404mJPwq7XtB:-NSr-EoN94UapdXG-gyf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/44a67555eced6ff461824a5b7f2e2fd670f04f12/pkg/ui/workspaces/db-console/src/redux/apiReducers.ts#L650)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

nit: this
nit: extract?
</blockquote></details>

Done.
___
*[`pkg/ui/workspaces/db-console/src/views/statements/statements.spec.tsx` line 58 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-NSqwsCv02x6ODmr8WxU:-NSqzFH-2NmPxTfxv0Mj:b-rgi1tc) ([raw file](https://github.com/cockroachdb/cockroach/blob/99a4c74fbd4988b958229e8cbd50e4c8e31286fd/pkg/ui/workspaces/db-console/src/views/statements/statements.spec.tsx#L58)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

why all these tests got removed?
</blockquote></details>

We don't use these selectors anymore. The selectors were just wrappers around the functions in `sqlActivity/util.tsx`, which are now being tested in the corresponding test file (and moved to cluster-ui).

**Review by maryliag — APPROVED** [review]
a few nits, otherwise
:lgtm: 

> Reviewed 12 of 12 files at r3, 12 of 12 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-:-NSv3TBw8JT2eaSMkLvU:b-9kwdlo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @j82w and @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.spec.tsx` line 231 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-NSv2XFr-z6p_v_3U6SF:-NSv2XFr-z6p_v_3U6SG:bfyzfnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/68cf71e350e6887cc8029fc84000d9c267fd8905/pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.spec.tsx#L231)):*
> ```XML
>     expect(
>       filteredStmts.map(stmt => Number(stmt.aggregatedFingerprintID)).sort(),
>     ).toEqual(expectedIDs);
> ```

all tests are using this very same code block (or some cases almost the same), so maybe you can create a function that receives: expectedCount, expectedIDs, stmtsRaw and the filters, so each test only have to call that function that will do all these checks



_Code quote:_
```XML
    const expectedCount = 3;
    const expectedIDs = [1, 2, 6];

    const statements = convertRawStmtsToAggregateStatistics(stmtsRaw);

    const filteredStmts = filteredStatementsData(
      filters,
      null,
      statements,
      false,
    );

    expect(filteredStmts.length).toEqual(expectedCount);

    expect(
      filteredStmts.map(stmt => Number(stmt.aggregatedFingerprintID)).sort(),
    ).toEqual(expectedIDs);
```
___
*[`pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.spec.tsx` line 291 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/101188#-NSv2yxH0G0Pebw-a4sr:-NSv2yxI-4xnJ09SnCvp:b-ysqztn) ([raw file](https://github.com/cockroachdb/cockroach/blob/68cf71e350e6887cc8029fc84000d9c267fd8905/pkg/ui/workspaces/cluster-ui/src/sqlActivity/util.spec.tsx#L291)):*
> ```XML
> 
>   it("should filter out statements with svc_lat less than filter time value", () => {
>     // Create stmts with ids matching service_lat in seceonds.
> ```

nit: seconds

**Comment by xinhaoz** [comment]
Addressed feedback! TFTR!!
bors r+

**Pull request merged**
