### PR TITLE
sql: Support CREATE DATABASE WITH OWNER

### LINKED ISSUE #67817: sql: Support CREATE DATABASE WITH OWNER
Support `CREATE DATABASE WITH OWNER`

```
CREATE DATABASE name
    [ [ WITH ] [ OWNER [=] user_name ]
```

See details at https://www.postgresql.org/docs/14/sql-createdatabase.html

Epic CRDB-8948

### PR DESCRIPTION
**Pull request by Fenil-P**
fixes https://github.com/cockroachdb/cockroach/issues/67817

Release note (sql change): Allow users to specify the owner when creating a database. 
			                      Similar to postgresql: CREATE DATABASE name [ [ WITH ] [ OWNER [=] user_name ]

### CODE REVIEW

**Review by RichardJCai — CHANGES_REQUESTED** [review]
Nice work, looks mostly good to me after minor comments are addressed.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-:-MtiRFdI4YHsI-ndNzJH:b-y5sqbl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Fenil-P and @RichardJCai)

___
*[pkg/sql/descriptor.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtiQTCdDzBxlqoQZMbz:-MtiQTCdDzBxlqoQZMc-:b-9v09vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/07937d91315628e4a4e9c765d5108b413bf44bf2/pkg/sql/descriptor.go#L147)):*
> ```Go
> 	// database-level zone configuration if there is a region config on the
> 	// descriptor.
> 	//p.setNewDatabaseOwner(ctx)
> ```

Remove this comment.
___
*[pkg/sql/descriptor.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtiQauM-ALRe8tpiqX5:-MtiQauM-ALRe8tpiqX6:b-tlokoa) ([raw file](https://github.com/cockroachdb/cockroach/blob/07937d91315628e4a4e9c765d5108b413bf44bf2/pkg/sql/descriptor.go#L148)):*
> ```Go
> 	// descriptor.
> 	//p.setNewDatabaseOwner(ctx)
> 	if database.Owner.Name != "" {
> ```

Use `Owner.IsUndefined()`
___
*[pkg/sql/descriptor.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtiQf2F-38hb5lahO5A:-MtiQf2F-38hb5lahO5B:b-e471xv) ([raw file](https://github.com/cockroachdb/cockroach/blob/07937d91315628e4a4e9c765d5108b413bf44bf2/pkg/sql/descriptor.go#L154)):*
> ```Go
> 		}
> 
> 		if err := p.checkCanAlterToNewOwner(ctx, desc, newOwner); err != nil {
> ```

Not 100% sure if we need this check if we're creating a new database here.
Can you double check with Postgres - you'll have to download PG and verify.

Namely, check if you can `CREATE DATABASE ... WITH OWNER ...` where the current user is not a member of the owner role.

Also please add a test for this if it turns out we do need this check (verify that we need to be a member of the owner role)
___
*[pkg/sql/descriptor.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtiQxKHEiPeFe4WBP0B:-MtiQxKHEiPeFe4WBP0C:bdubf0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/07937d91315628e4a4e9c765d5108b413bf44bf2/pkg/sql/descriptor.go#L161)):*
> ```Go
> 			return nil, true, err
> 		}
> 		if err := p.writeNonDropDatabaseChange(
> ```

Don't need this since the database descriptor gets written later in this function.

**Review by Fenil-P — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RichardJCai)

___
*[pkg/sql/descriptor.go, line 147 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtiQTCdDzBxlqoQZMbz:-MtnW14ABOktft8qKzkN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07937d91315628e4a4e9c765d5108b413bf44bf2/pkg/sql/descriptor.go#L147)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Remove this comment.
</blockquote></details>

Done.
___
*[pkg/sql/descriptor.go, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtiQauM-ALRe8tpiqX5:-MtnW0ifDAcXjzFT8eHC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07937d91315628e4a4e9c765d5108b413bf44bf2/pkg/sql/descriptor.go#L148)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Use `Owner.IsUndefined()`
</blockquote></details>

Done.
___
*[pkg/sql/descriptor.go, line 154 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtiQf2F-38hb5lahO5A:-MtnW-sJ2RV6g4sJP1RN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07937d91315628e4a4e9c765d5108b413bf44bf2/pkg/sql/descriptor.go#L154)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Not 100% sure if we need this check if we're creating a new database here.
Can you double check with Postgres - you'll have to download PG and verify.

Namely, check if you can `CREATE DATABASE ... WITH OWNER ...` where the current user is not a member of the owner role.

Also please add a test for this if it turns out we do need this check (verify that we need to be a member of the owner role)

</blockquote></details>

Done.
___
*[pkg/sql/descriptor.go, line 161 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtiQxKHEiPeFe4WBP0B:-MtnW-MeEdK_p5bgJ61R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/07937d91315628e4a4e9c765d5108b413bf44bf2/pkg/sql/descriptor.go#L161)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

Don't need this since the database descriptor gets written later in this function.
</blockquote></details>

Done.

**Review by RichardJCai — APPROVED** [review]
Great work! LGTM after addressing nit

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-:-MtobvjLBZU70lkDd2kw:bn5caa7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Fenil-P and @RichardJCai)

___
*[pkg/sql/descriptor.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtobjqV-9OHgFnFFP9Z:-MtobjqV-9OHgFnFFP9_:bivdi5q) ([raw file](https://github.com/cockroachdb/cockroach/blob/85e30e334ba8c76d23335c8a1962f412c2bc9d53/pkg/sql/descriptor.go#L140)):*
> ```Go
> 
> 	} else {
> 		owner = p.SessionData().User()
> ```

nit: we can just remove this else block and initially set owner to `p.SessionData.User()` and update it if the if cond is met

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Fenil-P, @rafiss, and @RichardJCai)

___
*[pkg/sql/descriptor.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtobjqV-9OHgFnFFP9Z:-Mtoi5dG-jq5s2VTzoxF:b-vh9fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/85e30e334ba8c76d23335c8a1962f412c2bc9d53/pkg/sql/descriptor.go#L140)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: we can just remove this else block and initially set owner to `p.SessionData.User()` and update it if the if cond is met
</blockquote></details>

+1 

actually when is database.Owner ever undefined?
___
*[pkg/sql/parser/sql.y, line 8923 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtoivEoBlVi0JsOIFh3:-MtoivEoBlVi0JsOIFh4:b-y5f52r) ([raw file](https://github.com/cockroachdb/cockroach/blob/85e30e334ba8c76d23335c8a1962f412c2bc9d53/pkg/sql/parser/sql.y#L8923)):*
> ```Yacc
>   OWNER opt_equal role_spec
>   {
>     $$ = $3
> ```

should this be `$$.val = $3.roleSpec()`

maybe it's the same thing?
___
*[pkg/sql/parser/sql.y, line 8928 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtoisCIE6hoUh_pEaVO:-MtoisCJ7Nv94g6CsNY2:b-vs0mer) ([raw file](https://github.com/cockroachdb/cockroach/blob/85e30e334ba8c76d23335c8a1962f412c2bc9d53/pkg/sql/parser/sql.y#L8928)):*
> ```Yacc
>    {
> 		 $$.val = tree.RoleSpec{
> 		   RoleSpecType: tree.SessionUser,
> ```

why SessionUser and not CurrentUser?

**Review by Fenil-P — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74867)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss and @RichardJCai)

___
*[pkg/sql/descriptor.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtobjqV-9OHgFnFFP9Z:-MtsWd7Z6n8WuFalhRn0:bu960b3) ([raw file](https://github.com/cockroachdb/cockroach/blob/85e30e334ba8c76d23335c8a1962f412c2bc9d53/pkg/sql/descriptor.go#L140)):*
> actually when is database.Owner ever undefined?
They're undefined when defaultdb and postgres are being created
___
*[pkg/sql/parser/sql.y, line 8923 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtoivEoBlVi0JsOIFh3:-MtsXO7C2-mm74F6P_0F:b-hu5ta1) ([raw file](https://github.com/cockroachdb/cockroach/blob/85e30e334ba8c76d23335c8a1962f412c2bc9d53/pkg/sql/parser/sql.y#L8923)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should this be `$$.val = $3.roleSpec()`

maybe it's the same thing?
</blockquote></details>

I kept the opt_owner_clause the same type as role_spec so its done later on in the create db statement.
___
*[pkg/sql/parser/sql.y, line 8928 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtoisCIE6hoUh_pEaVO:-MtsXcIG-VxsSyLvIa7W:b-bu91xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/85e30e334ba8c76d23335c8a1962f412c2bc9d53/pkg/sql/parser/sql.y#L8928)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why SessionUser and not CurrentUser?
</blockquote></details>

Updated

**Review by rafiss — APPROVED** [review]
nice!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-:-Mts_UuF8fUc3Mq7LP-s:b-7m74ox)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Fenil-P, @rafiss, and @RichardJCai)

___
*[pkg/sql/descriptor.go, line 140 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/74867#-MtobjqV-9OHgFnFFP9Z:-MtsZLFRAqAy3DpgT_3m:bn44e9y) ([raw file](https://github.com/cockroachdb/cockroach/blob/85e30e334ba8c76d23335c8a1962f412c2bc9d53/pkg/sql/descriptor.go#L140)):*
<details><summary><i>Previously, Fenil-P (Fenil Patel) wrote…</i></summary><blockquote>

> actually when is database.Owner ever undefined?
They're undefined when defaultdb and postgres are being created

</blockquote></details>

that happens in `createDefaultDbs` in startupmigrations with `CREATE DATABASE IF NOT EXISTS "%s"`

but based on how you added the new syntax, shouldn't an empty `owner` clause already default to using the current user?

anyway, this doesn't need to block the PR, i was just curious. having the undefined fallback case seems good regardless

**Comment by Fenil-P** [comment]
bors retry

**Pull request merged**
