### PR TITLE
distsqlrun: run cluster test in a transaction

### LINKED ISSUE #15284: sql/distsqlrun: TestClusterFlow failed under stress
SHA: https://github.com/cockroachdb/cockroach/commits/12277347aeaf2cf797141d05b1f1a72b7e22ea78

Parameters:
```
TAGS=
GOFLAGS=
```

Stress build found a failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=232145&tab=buildLog

```
W170424 06:41:26.601285 52 server/status/runtime.go:111  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
I170424 06:41:26.603924 52 server/config.go:413  1 storage engine initialized
I170424 06:41:26.604306 52 server/node.go:451  [n?] store [n0,s0] not bootstrapped
I170424 06:41:26.614908 52 server/node.go:386  [n?] **** cluster ac9e8a8c-9d69-405c-9c9d-189a6708e468 has been created
I170424 06:41:26.614934 52 server/node.go:387  [n?] **** add additional nodes by specifying --join=127.0.0.1:45596
I170424 06:41:26.615334 52 storage/store.go:1245  [n1] [n1,s1]: failed initial metrics computation: [n1,s1]: system config not yet available
I170424 06:41:26.615361 52 server/node.go:464  [n1] initialized store [n1,s1]: {Capacity:536870912 Available:536870912 RangeCount:1 LeaseCount:0}
I170424 06:41:26.615384 52 server/node.go:348  [n1] node ID 1 initialized
I170424 06:41:26.615472 52 gossip/gossip.go:297  [n1] NodeDescriptor set to node_id:1 address:<network_field:"tcp" address_field:"127.0.0.1:45596" > attrs:<> locality:<> 
I170424 06:41:26.615593 52 storage/stores.go:296  [n1] read 0 node addresses from persistent storage
I170424 06:41:26.615669 52 server/node.go:605  [n1] connecting to gossip network to verify cluster ID...
I170424 06:41:26.617265 52 server/node.go:630  [n1] node connected via gossip and verified as part of cluster "ac9e8a8c-9d69-405c-9c9d-189a6708e468"
I170424 06:41:26.617321 52 server/node.go:402  [n1] node=1: started with [[]=] engine(s) and attributes []
I170424 06:41:26.617589 52 sql/executor.go:326  [n1] creating distSQLPlanner with address {tcp 127.0.0.1:45596}
I170424 06:41:26.621031 52 server/server.go:730  [n1] starting https server at 127.0.0.1:52080
I170424 06:41:26.621053 52 server/server.go:731  [n1] starting grpc/postgres server at 127.0.0.1:45596
I170424 06:41:26.621068 52 server/server.go:732  [n1] advertising CockroachDB node at 127.0.0.1:45596
I170424 06:41:26.650472 52 sql/event_log.go:101  [n1] Event: "alter_table", target: 12, info: {TableName:eventlog Statement:ALTER TABLE system.eventlog ALTER COLUMN uniqueID SET DEFAULT uuid_v4() User:node MutationID:0 CascadeDroppedViews:[]}
I170424 06:41:26.653335 52 sql/lease.go:372  [n1] publish: descID=12 (eventlog) version=2 mtime=2017-04-24 06:41:26.653306232 +0000 UTC
I170424 06:41:26.662616 52 server/server.go:841  [n1] done ensuring all necessary migrations have run
I170424 06:41:26.662683 52 server/server.go:843  [n1] serving sql connections
I170424 06:41:26.664789 399 sql/event_log.go:101  [n1] Event: "node_join", target: 1, info: {Descriptor:{NodeID:1 Address:{NetworkField:tcp AddressField:127.0.0.1:45596} Attrs: Locality:} ClusterID:ac9e8a8c-9d69-405c-9c9d-189a6708e468 StartedAt:1493016086617278641 LastUp:1493016086617278641}
W170424 06:41:26.677598 52 server/status/runtime.go:111  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W170424 06:41:26.677822 52 gossip/gossip.go:1189  [n?] no incoming or outgoing connections
I170424 06:41:26.678817 52 server/config.go:413  1 storage engine initialized
I170424 06:41:26.679006 52 server/node.go:451  [n?] store [n0,s0] not bootstrapped
I170424 06:41:26.679030 52 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170424 06:41:26.679048 52 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170424 06:41:26.695858 422 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:45596
I170424 06:41:26.699502 436 gossip/server.go:234  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:51120}
I170424 06:41:26.699701 429 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170424 06:41:26.699767 52 server/node.go:630  [n?] node connected via gossip and verified as part of cluster "ac9e8a8c-9d69-405c-9c9d-189a6708e468"
I170424 06:41:26.700604 52 kv/dist_sender.go:367  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170424 06:41:26.701179 52 server/node.go:341  [n?] new node allocated ID 2
I170424 06:41:26.701220 52 gossip/gossip.go:297  [n2] NodeDescriptor set to node_id:2 address:<network_field:"tcp" address_field:"127.0.0.1:51120" > attrs:<> locality:<> 
I170424 06:41:26.701266 52 server/node.go:402  [n2] node=2: started with [[]=] engine(s) and attributes []
I170424 06:41:26.701313 52 sql/executor.go:326  [n2] creating distSQLPlanner with address {tcp 127.0.0.1:51120}
I170424 06:41:26.703162 52 server/server.go:730  [n2] starting https server at 127.0.0.1:45741
I170424 06:41:26.703179 52 server/server.go:731  [n2] starting grpc/postgres server at 127.0.0.1:51120
I170424 06:41:26.703190 52 server/server.go:732  [n2] advertising CockroachDB node at 127.0.0.1:51120
I170424 06:41:26.703824 411 storage/stores.go:312  [n1] wrote 1 node addresses to persistent storage
I170424 06:41:26.717391 52 server/server.go:841  [n2] done ensuring all necessary migrations have run
I170424 06:41:26.717413 52 server/server.go:843  [n2] serving sql connections
I170424 06:41:26.717970 469 server/node.go:586  [n2] bootstrapped store [n2,s2]
W170424 06:41:26.369471 175 util/hlc/hlc.go:146  backward time jump detected (-0.354257 seconds)
W170424 06:41:26.369752 512 util/hlc/hlc.go:146  backward time jump detected (-0.354080 seconds)
W170424 06:41:26.373282 52 server/status/runtime.go:111  Could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
W170424 06:41:26.373310 52 util/hlc/hlc.go:146  backward time jump detected (-0.346917 seconds)
W170424 06:41:26.373477 52 gossip/gossip.go:1189  [n?] no incoming or outgoing connections
I170424 06:41:26.376606 516 sql/event_log.go:101  [n2] Event: "node_join", target: 2, info: {Descriptor:{NodeID:2 Address:{NetworkField:tcp AddressField:127.0.0.1:51120} Attrs: Locality:} ClusterID:ac9e8a8c-9d69-405c-9c9d-189a6708e468 StartedAt:1493016086701253586 LastUp:1493016086701253586}
I170424 06:41:26.377249 52 server/config.go:413  1 storage engine initialized
I170424 06:41:26.377442 52 server/node.go:451  [n?] store [n0,s0] not bootstrapped
I170424 06:41:26.377460 52 storage/stores.go:296  [n?] read 0 node addresses from persistent storage
I170424 06:41:26.377477 52 server/node.go:605  [n?] connecting to gossip network to verify cluster ID...
I170424 06:41:26.396652 65 gossip/client.go:131  [n?] started gossip client to 127.0.0.1:45596
I170424 06:41:26.397108 655 gossip/server.go:234  [n1] received initial cluster-verification connection from {tcp 127.0.0.1:40026}
I170424 06:41:26.397394 52 server/node.go:630  [n?] node connected via gossip and verified as part of cluster "ac9e8a8c-9d69-405c-9c9d-189a6708e468"
I170424 06:41:26.397603 656 storage/stores.go:312  [n?] wrote 1 node addresses to persistent storage
I170424 06:41:26.397675 656 storage/stores.go:312  [n?] wrote 2 node addresses to persistent storage
I170424 06:41:26.398495 52 kv/dist_sender.go:367  [n?] unable to determine this node's attributes for replica selection; node is most likely bootstrapping
I170424 06:41:26.398987 52 server/node.go:341  [n?] new node allocated ID 3
I170424 06:41:26.399026 52 gossip/gossip.go:297  [n3] NodeDescriptor set to node_id:3 address:<network_field:"tcp" address_field:"127.0.0.1:40026" > attrs:<> locality:<> 
I170424 06:41:26.399065 52 server/node.go:402  [n3] node=3: started with [[]=] engine(s) and attributes []
I170424 06:41:26.399112 52 sql/executor.go:326  [n3] creating distSQLPlanner with address {tcp 127.0.0.1:40026}
I170424 06:41:26.422614 52 server/server.go:730  [n3] starting https server at 127.0.0.1:58780
I170424 06:41:26.422636 52 server/server.go:731  [n3] starting grpc/postgres server at 127.0.0.1:40026
I170424 06:41:26.422646 52 server/server.go:732  [n3] advertising CockroachDB node at 127.0.0.1:40026
I170424 06:41:26.439517 52 server/server.go:841  [n3] done ensuring all necessary migrations have run
I170424 06:41:26.439538 52 server/server.go:843  [n3] serving sql connections
I170424 06:41:26.439978 462 storage/stores.go:312  [n1] wrote 2 node addresses to persistent storage
I170424 06:41:26.440579 440 storage/stores.go:312  [n2] wrote 2 node addresses to persistent storage
I170424 06:41:26.444318 810 sql/event_log.go:101  [n3] Event: "node_join", target: 3, info: {Descriptor:{NodeID:3 Address:{NetworkField:tcp AddressField:127.0.0.1:40026} Attrs: Locality:} ClusterID:ac9e8a8c-9d69-405c-9c9d-189a6708e468 StartedAt:1493016086723710583 LastUp:1493016086723710583}
I170424 06:41:26.450575 691 server/node.go:586  [n3] bootstrapped store [n3,s3]
I170424 06:41:26.475092 464 sql/event_log.go:101  [client=127.0.0.1:45015,user=root,n1] Event: "create_database", target: 50, info: {DatabaseName:test Statement:CREATE DATABASE IF NOT EXISTS test User:root}
I170424 06:41:26.479017 464 sql/event_log.go:101  [client=127.0.0.1:45015,user=root,n1] Event: "create_table", target: 51, info: {TableName:test.t Statement:CREATE TABLE test.t (num INT PRIMARY KEY, digitsum INT, numstr STRING, INDEX s (digitsum)) User:root}
I170424 06:41:26.495257 52 sql/distsqlrun/cluster_test.go:199  Setting up flow on 0
W170424 06:41:26.495485 870 sql/distsqlrun/server.go:148  [n1] failed to join a remote trace: opentracing: SpanContext not found in Extract carrier
I170424 06:41:26.496001 52 sql/distsqlrun/cluster_test.go:206  Setting up flow on 1
W170424 06:41:26.496959 441 sql/distsqlrun/server.go:148  [n2] failed to join a remote trace: opentracing: SpanContext not found in Extract carrier
I170424 06:41:26.498424 52 sql/distsqlrun/cluster_test.go:213  Running flow on 2
W170424 06:41:26.498677 933 sql/distsqlrun/server.go:148  [n3] failed to join a remote trace: opentracing: SpanContext not found in Extract carrier
E170424 06:41:26.500651 935 sql/distsqlrun/tablereader.go:195  [n3,TableReader=51] scan error: read at time 1493016086.723710583,95 encountered previous write with future timestamp 1493016086.723710583,265 within uncertainty interval
I170424 06:41:26.513376 407 vendor/google.golang.org/grpc/transport/http2_server.go:323  transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:45596->127.0.0.1:45006: use of closed network connection
I170424 06:41:26.513469 287 vendor/google.golang.org/grpc/transport/http2_client.go:1231  transport: http2Client.notifyError got notified that the client transport was broken EOF.
	cluster_test.go:242: unexpected metadata (1): [{Ranges:[] Err:read at time 1493016086.723710583,95 encountered previous write with future timestamp 1493016086.723710583,265 within uncertainty interval}]
```

### PR DESCRIPTION
**Pull request by RaduBerinde**
We don't really care about transactionality in this test, but we could get
uncertainty errors which require retries.

Fixes #15284.

### CODE REVIEW

**Comment by tamird** [comment]
LGTM! Could you include a comment on the "kvDB.Txn" call that explains the reason for using a transaction (essentially the same string as the commit message).

Thanks for fixing this!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 84 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15558#-Kj4MCi19QK3p1iyAxw6:-Kj4MCi19QK3p1iyAxw7:b66vdfx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e500861a5e92e84d286c284e91bbd5c94d8b4400/pkg/sql/distsqlrun/cluster_test.go#L84)):*
> ```Go
> 	if err := kvDB.Txn(context.TODO(), func(ctx context.Context, txn *client.Txn) error {
> 		// Start a span (useful to look at spans using Lighstep).
> 		sp := tracing.NewTracer().StartSpan("cluster test")
> ```

Don't we want to do this outside the closure?

---

*[pkg/sql/distsqlrun/cluster_test.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15558#-Kj4M-yFfFdPMn4AYi58:-Kj4M-yFfFdPMn4AYi59:btobdvz) ([raw file](https://github.com/cockroachdb/cockroach/blob/e500861a5e92e84d286c284e91bbd5c94d8b4400/pkg/sql/distsqlrun/cluster_test.go#L88)):*
the other call to this method includes the comment:
> 	// DistSQL needs to initialize the Transaction proto before we put it in the
	// FlowRequest's below. This is because we might not have used the txn do to
	// anything else (we might not have sent any requests through the client.Txn,
	// which normally does this init).

Could you extract that comment such that it applies to both? The reason for this call wasn't obvious to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15558#-:-Kj4MI_NMQw5jINJezcH:bcbzuvq)*

**Comment by RaduBerinde** [comment]
I have reworked this. @andreimatei says that we shouldn't be seeing uncertainty errors if the transaction is properly initialized, so I changed the test to initialize the txn proto. If we see the failure again, we can revisit.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15558#-:-Kj4l8PXGjGB2EbQ0KxI:b-whck9s)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15558#-Kj4M-yFfFdPMn4AYi58:-Kj4nswMmuT0emU6DeGc:bve87y2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e500861a5e92e84d286c284e91bbd5c94d8b4400/pkg/sql/distsqlrun/cluster_test.go#L88)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

the other call to this method includes the comment:
> 	// DistSQL needs to initialize the Transaction proto before we put it in the
	// FlowRequest's below. This is because we might not have used the txn do to
	// anything else (we might not have sent any requests through the client.Txn,
	// which normally does this init).

Could you extract that comment such that it applies to both? The reason for this call wasn't obvious to me.
</blockquote></details>

Looks like our usage of this pattern (as opposed to the closure pattern) is very limited, appearing only in a handful of tests. I don't know all the background, but it seems like a justifying comment would be valuable. What do you think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15558)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15558#-Kj4M-yFfFdPMn4AYi58:-Kj4r9Aje_9yp8Ybr-HB:ba91jah) ([raw file](https://github.com/cockroachdb/cockroach/blob/e500861a5e92e84d286c284e91bbd5c94d8b4400/pkg/sql/distsqlrun/cluster_test.go#L88)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Looks like our usage of this pattern (as opposed to the closure pattern) is very limited, appearing only in a handful of tests. I don't know all the background, but it seems like a justifying comment would be valuable. What do you think?
</blockquote></details>

@andreimatei ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15558)*

**Comment by andreimatei** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/distsqlrun/cluster_test.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15558#-Kj4M-yFfFdPMn4AYi58:-Kj4uPYxJNSdx-mbpZfb:b-9z5kbe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e500861a5e92e84d286c284e91bbd5c94d8b4400/pkg/sql/distsqlrun/cluster_test.go#L88)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

@andreimatei ?
</blockquote></details>

My thought was that this test shouldn't need any retries. It wants to execute a flow, once. However, flows are only executed in kv transactions (courtesy of all SQL queries being executed in transactions), so it makes sense for this test to also execute it in a txn, to reflect the real world better.
If we add the `db.Txn()` call, then that'd be emulating something that the sql `Executor` does, so a whole different level. Which may prove necessary, but I hope it won't.

FWIW, I'm unclear as to why this test failed in the first place, and Radu failed to repro. It's also unclear if the change will solve the failure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15558#-:-Kj4ypSuXMtZBbGjrSSr:bnfp4nl)*

**Pull request merged**
