### PR TITLE
sql: show allocated memory in `SHOW SESSIONS`

### PR DESCRIPTION
**Pull request by jordanlewis**
Release note (sql change): `SHOW SESSIONS` now includes the number of
allocated bytes by the session.

### CODE REVIEW

**Comment by asubiotto** [comment]
Sorry for the delay in reviewing this!

The objective of this change is to offer operators the ability to observe memory usage per session at the current point in time but I don't think this change is enough to allow for this because according to my understanding

1) The monitor whose usage is reported does not take into account any distsql usage. The `distsql` monitor is hooked up directly to the `root` monitor, so bypassing this `session` monitor. That should be fixed for distsql execution local to the node where the session was created, although seems right for remote distsql execution on behalf of a session.
2) After fixing 1), this approach would only report memory usage of the session's gateway node so we would want some way to annotate remote monitors with a session ID and aggregate the usage.

I think this would be great to have, and some extensions could include showing the high watermark memory usage of a query (by using the same mechanism with statement monitors).

**Comment by jordanlewis** [comment]
Okay, PTAL. I added the high watermark of memory usage to the session. Also, I rebased this patch on top of #26108, which makes the query's txn memory monitor parent the flow memory monitor (for the gateway node only).

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/sql/crdb_internal.go, line 846 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25395#-LDgOO2aDksAQ8ggcKCd:-LDgOO2aDksAQ8ggcKCe:b-xvki08) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcf59f476a97c8b0dce86ddcd3cb78d1a592f4c9/pkg/sql/crdb_internal.go#L846)):*
> ```Go
> 			oldestStartDatum,
> 			kvTxnIDDatum,
> 			tree.NewDInt(tree.DInt(session.AllocBytes)),
> ```

This should default to zero in a mixed version cluster where it gets session information from a machine that has the old version, correct?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25395#-:-LDgODXt2G74I5yhuLMb:bnfp4nl)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/crdb_internal.go, line 846 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/25395#-LDgOO2aDksAQ8ggcKCd:-LDgbYVJ61ZmCbbQCIuY:btqqu5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/bcf59f476a97c8b0dce86ddcd3cb78d1a592f4c9/pkg/sql/crdb_internal.go#L846)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

This should default to zero in a mixed version cluster where it gets session information from a machine that has the old version, correct?
</blockquote></details>

Correct.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25395)*

**Comment by asubiotto** [comment]
:lgtm: Although maybe you should call out in the release note that memory usage of a session's remote execution is not included.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25395#-:-LDgkLARBt4yb02Ok21O:bctq1ae)*

**Comment by jordanlewis** [comment]
> Although maybe you should call out in the release note that memory usage of a session's remote execution is not included.

Done.

bors r+

**Pull request merged**
