### PR TITLE
sql: add 'distsql_workmem' session variable

### PR DESCRIPTION
**Pull request by yuzefovich**
This required putting the newly introduced parameters into the
serialized part of the session data (so that the remote nodes respected
it) and some plumbing.

Release note (sql change): New session variable `distsql_workmem` has
been introduced that determines how much RAM a single operation of
a single query can take before the operation must spill to disk. It is
the same thing as `sql.distsql.temp_storage.workmem` cluster setting but
has the session-level scope.

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 37 of 37 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63959#-:-MYlvZ2G6FFb0HapbhHf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/execinfra/server_config.go, line 260 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63959#-MYlufUc83VG7vcBet3N:-MYlufUc83VG7vcBet3O:bwmdgst) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ad9232f5aa1170b4c872c70033b452f4380b48/pkg/sql/execinfra/server_config.go#L260)):*
> ```Go
> // GetWorkMemLimit returns the number of bytes determining the amount of RAM
> // available to a single processor or operator.
> func GetWorkMemLimit(config *ServerConfig, sd *sessiondata.SessionData) int64 {
> ```

super nit: It's a little unfortunate that you need to add an extra param everywhere this function is called. Not a big deal, but it seems like in a lot of places you're passing two pieces of the same large object (e.g., flowCtx). Not sure if it's possible, but did you consider trying pass a single param instead of two? Ditto with another function you updated in this PR to add SessionData as a param.
___
*[pkg/sql/rowexec/windower.go, line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63959#-MYltQjC6ORO8RkIXnZ6:-MYltQjC6ORO8RkIXnZ7:b-carp3o) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ad9232f5aa1170b4c872c70033b452f4380b48/pkg/sql/rowexec/windower.go#L151)):*
> ```Go
> 			return nil, errors.Errorf(
> 				"window functions require %d bytes of RAM but only %d are in the budget. "+
> 					"Consider increasing sql.distsql.temp_storage.workmem setting or distsql_workmem variable",
> ```

nit: maybe say "cluster setting" and "session setting" instead of "setting" and "variable"

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63959#-:-MYpLQx-8JiLRyDGKT-u:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/execinfra/server_config.go, line 260 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63959#-MYlufUc83VG7vcBet3N:-MYpKPdq7qMnS4OBVDnF:b-xw7sda) ([raw file](https://github.com/cockroachdb/cockroach/blob/83ad9232f5aa1170b4c872c70033b452f4380b48/pkg/sql/execinfra/server_config.go#L260)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

super nit: It's a little unfortunate that you need to add an extra param everywhere this function is called. Not a big deal, but it seems like in a lot of places you're passing two pieces of the same large object (e.g., flowCtx). Not sure if it's possible, but did you consider trying pass a single param instead of two? Ditto with another function you updated in this PR to add SessionData as a param.
</blockquote></details>

I thought about it initially as well, but I was under the wrong impression that `FlowCtx` lived in `flowinfra` package - I was wrong, it is in the same `execinfra` package, so using that as a single parameter is easy. Done.

**Comment by andreimatei** [comment]
bors says
`cannot use distSQLCfg (type *execinfra.ServerConfig) as type *execinfra.FlowCtx in argument to execinfra.NewLimitedMonitor` 
sounds like it could be coming from this PR, so I'm canceling it. Sorry if I'm wrong.

bors r-

**Comment by yuzefovich** [comment]
Oh, it's a merge skew between my two PRs (second one is #63900) :) Thanks Andrei, I'll let the other one merge first.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63959)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/execinfra/processorsbase.go, line 987 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63959#-MYrAgiuDQlpw4lIUnxE:-MYrAgiuDQlpw4lIUnxF:bayzyzb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb0c5f29815a6d603673500fa66ca5c6f0b92f2/pkg/sql/execinfra/processorsbase.go#L987)):*
> ```Go
> // NewLimitedMonitorNoFlowCtx is the same as NewLimitedMonitor and should be
> // used when the caller doesn't have an access to *FlowCtx.
> func NewLimitedMonitorNoFlowCtx(
> ```

With the support for spilling in `bufferNode` PR I added a call to `NewLimitedMonitor` when the caller doesn't have access to `*FlowCtx` (which was always the case until that PR). I still think it is beneficial to simplify the signature of that method, so I added another helper method instead. @rytaft let me know what you think.

**Review by rytaft — APPROVED** [review]
> Reviewed 20 of 23 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63959)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft and @yuzefovich)

___
*[pkg/sql/execinfra/processorsbase.go, line 987 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/63959#-MYrAgiuDQlpw4lIUnxE:-MYtqrpr5NJWO64wVV4I:b-bk5ipd) ([raw file](https://github.com/cockroachdb/cockroach/blob/9fb0c5f29815a6d603673500fa66ca5c6f0b92f2/pkg/sql/execinfra/processorsbase.go#L987)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

With the support for spilling in `bufferNode` PR I added a call to `NewLimitedMonitor` when the caller doesn't have access to `*FlowCtx` (which was the case until then). I still think it is beneficial to simplify the signature of that method, so I added another helper method instead. @rytaft let me know what you think.
</blockquote></details>

Works for me!

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63959#-:-MYuQVf47IV5RTQC7mKR:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

**Pull request merged**
