### PR TITLE
storage: Re-propose pending commands when replicaID is changed

### PR DESCRIPTION
**Pull request by d4l3k**
Adds a check that re-proposes pending commands to the new raft group if the replicaID changes.

See #4474

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6651)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 359 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHaf-ECCLvJt-9RbLGQ:-KHaf-EDbkt2g6RsHazK:301097951) ([raw file](https://github.com/cockroachdb/cockroach/blob/845d38159a5fd18321a66b679e71ffa7fe0a149c/storage/replica.go#L359)):*
> ```Go
> 		return util.Errorf("replicaID cannot move backwards from %d to %d", r.mu.replicaID, replicaID)
> 	} else if r.mu.replicaID != 0 {
> 		// TODO(bdarnell): clean up previous raftGroup (cancel pending commands,
> ```

are we cancelling pending commands?

---

*[storage/replica_test.go, line 5561 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafZPw40Ik71bWOawb:-KHafZPw40Ik71bWOawc:1375710064) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5561)):*
> ```Go
> 		commandProposed = true
> 		if p != p2 {
> 			t.Fatalf("unknown pending command proposed: %v", p2)
> ```

nit: i'm not sure about this strictness, perhaps just
```
if p == p2 {
  ...
}
```

@bdarnell should weigh in

also consider a more verbose name than p2

---

*[storage/replica_test.go, line 5567 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafLGp1QIXik0khlr9:-KHafLGrSNxEV_BBUsar:-857580020) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5567)):*
> ```Go
> 	rng.mu.Unlock()
> 
> 	// Set the ReplicaID on the description and replica.
> ```

s/description/descriptor/

---

*[storage/replica_test.go, line 5568 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafS1YSqwmZ0ChLI-V:-KHafS1YSqwmZ0ChLI-W:150597153) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5568)):*
> ```Go
> 
> 	// Set the ReplicaID on the description and replica.
> 	rng.GetReplica().ReplicaID = 2
> ```

is this safe?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651)*

**Comment by d4l3k** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[storage/replica.go, line 359 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHaf-ECCLvJt-9RbLGQ:-KHagY1XEq8009W6ItjW:2014250641) ([raw file](https://github.com/cockroachdb/cockroach/blob/845d38159a5fd18321a66b679e71ffa7fe0a149c/storage/replica.go#L359)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> are we cancelling pending commands?</details>
Ben decided that instead of cancelling pending commands the best thing was to repropose them.

https://github.com/cockroachdb/cockroach/issues/4474

---

*[storage/replica_test.go, line 5567 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafLGp1QIXik0khlr9:-KHah3lKpGXi9rDVPYCB:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5567)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> s/description/descriptor/</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651)*

**Comment by d4l3k** [comment]
Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[storage/replica_test.go, line 5568 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafS1YSqwmZ0ChLI-V:-KHajF9eDzIYUrYkU1Bd:-136529346) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5568)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> is this safe?</details>
It is now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[storage/replica_test.go, line 5568 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafS1YSqwmZ0ChLI-V:-KHan--spLC2bCShw6z8:425084064) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5568)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> It is now.</details>
OK. This still looks fishy to me. In particular, why does setReplicaID not do this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651)*

**Comment by d4l3k** [comment]
*[storage/replica_test.go, line 5568 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafS1YSqwmZ0ChLI-V:-KHaoHLlBtpFrazhT2h3:1387303967) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5568)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> OK. This still looks fishy to me. In particular, why does setReplicaID not do this?</details>
Normally the entire ReplicaDescriptor is replaced at the same time the replicaID is changed.
This occurs when a replica is removed and immediately re-added for some reason. Instead of entirely destroying the old replica object it replaces the descriptor and replicaID.

I thought this was the cleanest way to keep the descriptor up to date (but is a bad idea in production code).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[storage/replica_test.go, line 5561 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafZPw40Ik71bWOawb:-KHaz5L8GYWyskvNh6fJ:778774003) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5561)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: i'm not sure about this strictness, perhaps just
> ```
> if p == p2 {
>   ...
> }
> ```
> 
> @bdarnell should weigh in
> 
> also consider a more verbose name than p2</details>
`LeaderLease` commands can be proposed at any time, so this shouldn't be so strict. Write to the channel when the expected command gets proposed but don't fail on others.

Also, `t.Fatalf` is not thread-safe and should only be called from the `Test` function's original goroutine. 

I would call the `func` argument `p` and the one in the outer scope something like `expectedCmd`

---

*[storage/replica_test.go, line 5568 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafS1YSqwmZ0ChLI-V:-KHb0bYcRvxkMx5vnodp:-1300954776) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5568)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Normally the entire ReplicaDescriptor is replaced at the same time the replicaID is changed.
> This occurs when a replica is removed and immediately re-added for some reason. Instead of entirely destroying the old replica object it replaces the descriptor and replicaID.
> 
> I thought this was the cleanest way to keep the descriptor up to date (but is a bad idea in production code).</details>
It's definitely strange. After `setReplicaIDLocked`, the replica's range descriptor is out of date. This fixes it, but in a way that's very different from production code (mutating the descriptor instead of replacing it with a modified copy).

Out of date descriptors are a fairly normal occurrence - I think it should generally be fine to leave the descriptor out of date until the replica catches up through the normal mechanisms. The one time where it matters, as far as I can tell, is in `setReplicaIDLocked` itself, when the replica says "if there is only one replica, and it is me, i should be leader". This panics if the replica ID doesn't match. I think this is actually a bug: the check for "am I the sole replica" should use ReplicaID, not StoreID. Try removing the assignment to ReplicaID here, and changing StoreID to ReplicaID in the campaign check.

---

*[storage/replica_test.go, line 5540 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHayp-cDJVhhSRmjNXa:-KHayp-d3ePeBA0DnukK:-251151831) ([raw file](https://github.com/cockroachdb/cockroach/blob/250e7c514779c0f3fabca1862ad7fca15bbb3e30/storage/replica_test.go#L5540)):*
> ```Go
> 	defer tc.Stop()
> 	rng := tc.rng
> 	descriptor := rng.GetReplica()
> ```

The word "descriptor" on its own more often refers to range descriptor here; I would call this `replicaDesc`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651)*

**Comment by d4l3k** [comment]
Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---

*[storage/replica_test.go, line 5561 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafZPw40Ik71bWOawb:-KHuVHV8Vjq5_eRGx12h:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5561)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> `LeaderLease` commands can be proposed at any time, so this shouldn't be so strict. Write to the channel when the expected command gets proposed but don't fail on others.
> 
> Also, `t.Fatalf` is not thread-safe and should only be called from the `Test` function's original goroutine. 
> 
> I would call the `func` argument `p` and the one in the outer scope something like `expectedCmd`</details>
Done.

---

*[storage/replica_test.go, line 5568 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafS1YSqwmZ0ChLI-V:-KHuXTAKNczLGamA33tM:-2099899377) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5568)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> It's definitely strange. After `setReplicaIDLocked`, the replica's range descriptor is out of date. This fixes it, but in a way that's very different from production code (mutating the descriptor instead of replacing it with a modified copy).
> 
> Out of date descriptors are a fairly normal occurrence - I think it should generally be fine to leave the descriptor out of date until the replica catches up through the normal mechanisms. The one time where it matters, as far as I can tell, is in `setReplicaIDLocked` itself, when the replica says "if there is only one replica, and it is me, i should be leader". This panics if the replica ID doesn't match. I think this is actually a bug: the check for "am I the sole replica" should use ReplicaID, not StoreID. Try removing the assignment to ReplicaID here, and changing StoreID to ReplicaID in the campaign check.</details>
Changing StoreID to ReplicaID seems to fix the problem. Though I'm not sure it's fixing it the right way. The new behavior is that if the descriptor is out of date it won't campaign even in cases where it's the only replica.

---

*[storage/replica_test.go, line 5540 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHayp-cDJVhhSRmjNXa:-KHuVUjYSDN7SB05zg2q:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/2b4c619b6f9f68d71576a74466777e015b8e8734/storage/replica_test.go#L5540)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> The word "descriptor" on its own more often refers to range descriptor here; I would call this `replicaDesc`</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651)*

**Comment by bdarnell** [comment]
:lgtm:

<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> #### storage: Re\-propose pending commands when replicaID is changed
> 
> Adds a check that re-proposes pending commands to the new raft group if the replicaID changes.
> 
> 
> 
> See #4474
> 
> 
> </details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/replica_test.go, line 5568 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafS1YSqwmZ0ChLI-V:-KHv6gBSmA3ldXq7DxLd:-976002803) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5568)):*
<details><summary><i>Previously, d4l3k (Tristan Rice) wrote…</i></summary>
> Changing StoreID to ReplicaID seems to fix the problem. Though I'm not sure it's fixing it the right way. The new behavior is that if the descriptor is out of date it won't campaign even in cases where it's the only replica.</details>
If the descriptor is out of date, how can it know that it's truly the only replica? In any case, the campaign here is just an optimization so it's fine if it doesn't fire in some rare situations. The normal time-based election mechanism will kick in in those cases. 

---

*[storage/replica_test.go, line 5566 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHv6TMTpYmwN0CjYp-q:-KHv6TMUV0zvK5aBM3fh:1325013844) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a78f80f47100ce95ca3c7ea79c9bf0ecefbc41/storage/replica_test.go#L5566)):*
> ```Go
> 	}
> 
> 	// Set the ReplicaID on the replicaDesc and replica.
> ```

replicaDesc no longer exists, so remove it from this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-:-KHv73NPOXCMepCpzZri:1417088721)*

**Comment by d4l3k** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/replica_test.go, line 5568 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHafS1YSqwmZ0ChLI-V:-KHvLE4e452k5GkL8cmF:2052356559) ([raw file](https://github.com/cockroachdb/cockroach/blob/4167c6c7844a8af27b080d5592f307c4ad40e3f2/storage/replica_test.go#L5568)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> If the descriptor is out of date, how can it know that it's truly the only replica? In any case, the campaign here is just an optimization so it's fine if it doesn't fire in some rare situations. The normal time-based election mechanism will kick in in those cases. </details>
That makes sense.

---

*[storage/replica_test.go, line 5566 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-KHv6TMTpYmwN0CjYp-q:-KHvLDdqdLaUks1czo3j:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/54a78f80f47100ce95ca3c7ea79c9bf0ecefbc41/storage/replica_test.go#L5566)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> replicaDesc no longer exists, so remove it from this comment.</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651)*

**Comment by tamird** [comment]
:lgtm:

<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6651#-:-KHvLkrwTmFXU8JqugnK:1417088721)*

**Pull request merged**
