### PR TITLE
ts: plumb contexts

### PR DESCRIPTION
**Pull request by RaduBerinde**
The batches ran by `ts` now get contexts; this fixes the lack of node tags on
these operations. In addition they are also marked with a `ts-srv` or
`ts-poll` tag.

Plus: Don't duplicate tags when using WithLogTagsFromCtx.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9275)

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ts/server.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9275#-KRQkykVbN_I4nqIvlFX:-KRQkykVbN_I4nqIvlFY:b-rjsnkq) ([raw file](https://github.com/cockroachdb/cockroach/blob/08687668d86a43cb0e42457ab8223bcbe877463a/ts/server.go#L67)):*
> ```Go
> }
> 
> // logContext applies the log tags from the Server's context to a GRPC context.
> ```

"to a GRPC" context doesn't make any sense. There's nothing GRPC about the involved contexts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9275#-:-KRQldXn0-ZXGnskx5M8:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ts/server.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9275#-KRQkykVbN_I4nqIvlFX:-KRQnF24-3-N8O9V8KJ8:b-2ym5lx) ([raw file](https://github.com/cockroachdb/cockroach/blob/08687668d86a43cb0e42457ab8223bcbe877463a/ts/server.go#L67)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> "to a GRPC" context doesn't make any sense. There's nothing GRPC about the involved contexts.
</details>
`Query` is part of the TimeSeries gRPC service

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9275)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ts/server.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9275#-KRQkykVbN_I4nqIvlFX:-KRQnxP5u4VwzzOug_WS:behclei) ([raw file](https://github.com/cockroachdb/cockroach/blob/08687668d86a43cb0e42457ab8223bcbe877463a/ts/server.go#L67)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> `Query` is part of the TimeSeries gRPC service
</details>
I should say "to a context passed from gRPC"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9275)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[ts/server.go, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9275#-KRQkykVbN_I4nqIvlFX:-KRQojLnq0_RQmZ0-cZl:b-vosx46) ([raw file](https://github.com/cockroachdb/cockroach/blob/08687668d86a43cb0e42457ab8223bcbe877463a/ts/server.go#L67)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I should say "to a context passed from gRPC"?
</details>
As far as this method is concerned, it doesn't seem like it restricts (or should restrict) where the context comes from. I would just drop the reference to GRPC, though feel free to keep it if you prefer that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9275)*

**Pull request merged**
