### PR TITLE
sql: populate `pg_proc.prokind`

### LINKED ISSUE #95288: sql: missing `prokind` in `pg_proc` for builtins
Found via #88061.
`pg_catalog.pg_proc` has a `prokind` column that describes the kind of function.
This is currently NULL for all builtins.

cc @rafiss for triage

Jira issue: CRDB-23448
Epic: CRDB-23454

### PR DESCRIPTION
**Pull request by knz**
Needed for #88061.

Fixes #95288.
Epic: CRDB-23454

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
thank you!

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95289#-:-NLyZ356CRcf_l9I-qy-:bsv417h)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

**Comment by knz** [comment]
Thank you :)

bors=rafiss

**Comment by knz** [comment]
bors=rafiss

**Comment by knz** [comment]
bors=rafiss

**Comment by knz** [comment]
bors=rafiss

**Comment by knz** [comment]
bors r=rafiss

**Pull request merged**
