### PR TITLE
roachtest: run TPCH vec benchmark only on 19.1.0 and after

### LINKED ISSUE #37965: roachtest: tpchbench/tpchVec/nodes=3/cpu=4/sf=1 failed
SHA: https://github.com/cockroachdb/cockroach/commits/24b7b441f56ce8d559380bd6a42bb8104c5cd68a

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=tpchbench/tpchVec/nodes=3/cpu=4/sf=1 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1318721&tab=buildLog

```
The test failed on branch=release-2.1, cloud=gce:
	tpchbench.go:114,cluster.go:1854,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1318721-tpchbench-tpchvec-nodes-3-cpu-4-sf-1:4 -- ./workload run querybench --db=tpch --concurrency=1 --query-file=tpchVec --num-runs=3 --max-ops=27 --vectorized=true {pgurl:1-3} --histograms=logs/stats.json returned:
		stderr:
		
		stdout:
		Error: pq: unrecognized configuration parameter "experimental_vectorize"
		Error:  ssh verbose log retained in /root/.roachprod/debug/ssh_34.73.224.171_2019-06-01T14:24:19Z: exit status 1
		: exit status 1
	cluster.go:1875,tpchbench.go:118,tpchbench.go:235,test.go:1251: Goexit() was called

```

### PR DESCRIPTION
**Pull request by yuzefovich**
Fixes: #37965. 

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/cmd/roachtest/tpchbench.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37976#-LgT5eTdCSwr2uittZq0:-LgT5eTdCSwr2uittZq1:b7otu5k) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef83e3f088fc7a4f6306c643b832699e22747c73/pkg/cmd/roachtest/tpchbench.go#L234)):*
> ```Go
> 		Name:       strings.Join(nameParts, "/"),
> 		Cluster:    makeClusterSpec(numNodes),
> 		MinVersion: b.minVersion,
> ```

Maybe have `minVersion` default to `maybeMinVersionForFixturesImport` if `b.minVersion` is an empty string? Might be better than having to respecify in each test spec.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37976)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchbench.go, line 234 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37976#-LgT5eTdCSwr2uittZq0:-LgT98nO2iLbGkKY6u8v:b-s2rc7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ef83e3f088fc7a4f6306c643b832699e22747c73/pkg/cmd/roachtest/tpchbench.go#L234)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe have `minVersion` default to `maybeMinVersionForFixturesImport` if `b.minVersion` is an empty string? Might be better than having to respecify in each test spec.
</blockquote></details>

Good point, thanks!

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37976#-:-LgTBw8J-FlvIo2JSfu0:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
