### PR TITLE
storage: recompute and adjust stats via consistency checker

### PR DESCRIPTION
**Pull request by tbg**
A number of bugs in our MVCCStats logic has been fixed recently (e.g. #20996)
and others are still present (#20554). For both, and also potentially for future
bugs or deliberate adjustments of the computations, we need a mechanism to
recompute the stats in order to purge incorrect numbers from the system over
time. Such a mechanism is introduced here.

It consists of two main components:

- A new RPC `AdjustStats`, which applies to a single Range and computes the
difference between the persisted stats and the recomputed ones; it can "inject"
a suitable delta into the stats (thus fixing the divergence) or do a "dry run".
- A trigger in the consistency checker that runs on the coordinating node (the
lease holder). The consistency checker already recomputes the stats, and it can
compare them against the persisted stats and judge whether there is a divergence.
If there is one, naively one may hope to just insert the newly computed diff into
the range, but this is not ideal due to concerns about double application and racing
consistency checks. Instead, use `AdjustStats` (which, of course, was introduced for
this purpose) which strikes a balance between efficiency and correctness.

Updates #20554.

Release note (general change): introduced a mechanism to recompute range stats
automatically over time to reflect changes in the underlying logic.

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1, 20 of 20 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/api.proto, line 397 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2R7hFjoRX8an55CTPb:-L2R7hFjoRX8an55CTPc:b-xkxfn5) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/roachpb/api.proto#L397)):*
> ```protobuf
> 
>   Span header = 1 [(gogoproto.nullable) = false, (gogoproto.embed) = true];
>   bytes computation_end_key = 2 [(gogoproto.casttype) = "Key"];
> ```

This looks unused.

---

*[pkg/roachpb/api.proto, line 400 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2R7p5WSaakn2WU18jp:-L2R7p5WSaakn2WU18jq:b-584oec) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/roachpb/api.proto#L400)):*
> ```protobuf
>   // When dry_run is true, the stats delta is computed, but no stats adjustment
>   // is performed.
>   bool dry_run = 3;
> ```

Do you expect to use this anywhere but tests? We're going to be issuing this command without dry_run in an automated fashion and it should be safe and idempotent, so I don't think a dry run flag is necessary.  (a dry run is not any cheaper than a full run since even a "dry run" goes through raft as a write)

---

*[pkg/storage/replica_consistency.go, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RAINenE3ORr7W5VyZ:-L2RAINenE3ORr7W5Vy_:b-l359tz) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/replica_consistency.go#L132)):*
> ```Go
> 		b.AddRawRequest(&req)
> 
> 		err := r.store.db.Run(ctx, &b)
> ```

If we've lost the lease, this request may go to another node, and during an upgrade it may not have the AdjustStats method. We should make sure that this doesn't log in a scary way. 

---

*[pkg/storage/batcheval/cmd_adjust_stats.go, line 40 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2R5LrMs3tb95C6f3br:-L2R5LrMs3tb95C6f3bs:b3u5qog) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/batcheval/cmd_adjust_stats.go#L40)):*
> ```Go
> 	// Declare only the target key, even though we're really iterating over a key range. This is OK
> 	// since all we're doing is computing a stats delta, and applying this delta commutes with other
> 	// operations on the same key space (except splits, which always touch the start key).
> ```

The start key is a real key, so this will interfere with at least some regular transactions. Maybe we should target this command to the range descriptor instead? 

---

*[pkg/storage/batcheval/cmd_adjust_stats.go, line 68 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2R91fyqKUEFTXhHHEX:-L2R91fyqKUEFTXhHHEY:bknc627) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/batcheval/cmd_adjust_stats.go#L68)):*
> ```Go
> 	}
> 
> 	if !descSpan.Equal(reqSpan) {
> ```

This could check `args.Key.Equal(desc.StartKey)` since the EndKey is set identically in both cases. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-:-L2RAutMvKXfSNjVH9Uy:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Reviewed 2 of 2 files at r1, 20 of 20 files at r2.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[pkg/roachpb/api.proto, line 386 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RTzk0cWQJzVA6PDJk:-L2RTzk0cWQJzVA6PDJl:boohe2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/roachpb/api.proto#L386)):*
> ```protobuf
> //
> // Since this request targets a specific Range, the start key must equal the
> // start key of the target Range.
> ```

or what?

---

*[pkg/roachpb/api.proto, line 393 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RUUUWPkU5Fzs76z1H:-L2RUUUWPkU5Fzs76z1I:b-3w48u6) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/roachpb/api.proto#L393)):*
> ```protobuf
> // it is safe to invoke at any time, including repeatedly, though it should be
> // used conservatively due to performing a full scan of the Range.
> message AdjustStatsRequest {
> ```

`AdjustStatsRequest` sounds a bit off to me. If this request took a stats delta to apply without scanning the entire range it would seem appropriate, but as is, I don't think this conveys the right information. `RecomputeStatsRequest` seems like a better name because it implies how expensive this might be.

---

*[pkg/storage/consistency_queue_test.go, line 37 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RVBdgYFYSy8v58rpO:-L2RVBdgYFYSy8v58rpP:b-2clmca) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/consistency_queue_test.go#L37)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/log"
> 	"github.com/cockroachdb/cockroach/pkg/util/retry"
> 	"github.com/pkg/errors"
> ```

Sorry, it just sticks out like a sore thumb :)

---

*[pkg/storage/consistency_queue_test.go, line 328 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RW2VmFPzb0F7WiEfI:-L2RW2VmFPzb0F7WiEfJ:b-qtlerh) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/consistency_queue_test.go#L328)):*
> ```Go
> 	// The stats should magically repair themselves. The high timeout is only
> 	// relevant in stress testing; it's usually quick.
> 	if err := retry.ForDuration(3*time.Minute, func() error {
> ```

Should we force a run of the `consistencyQueue`? 3 minutes seems like a long time.

---

*[pkg/storage/helpers_test.go, line 28 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RWEdMmZnXlwaZIHw3:-L2RWEdMmZnXlwaZIHw4:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/helpers_test.go#L28)):*
> ```Go
> 	"time"
> 
> 	"github.com/cockroachdb/cockroach/pkg/storage/rditer"
> ```

ditto

---

*[pkg/storage/replica_command.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RWJ3II0vYZ6RZ4Eah:-L2RWJ3II0vYZ6RZ4Eai:bpgu38j) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/replica_command.go#L26)):*
> ```Go
> 	"time"
> 
> 	"github.com/cockroachdb/cockroach/pkg/storage/rditer"
> ```

Is this a goland issue?

---

*[pkg/storage/replica_consistency.go, line 122 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RWemgeOUaRdl5khbQ:-L2RWemgeOUaRdl5khbR:b-robelj) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/replica_consistency.go#L122)):*
> ```Go
> 		// Note that this code runs only on the lease holder (at the time of initiating
> 		// the computation), so this work isn't duplicated. Also, we're essentially
> 		// paced by the consistency checker.
> ```

We should note that this doesn't mean that it will never be run twice at the same time.

---

*[pkg/storage/replica_consistency.go, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RAINenE3ORr7W5VyZ:-L2RWtqBGzqWF5Ct-cAw:bs3w5eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/replica_consistency.go#L132)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

If we've lost the lease, this request may go to another node, and during an upgrade it may not have the AdjustStats method. We should make sure that this doesn't log in a scary way. 
</blockquote></details>

I was also surprised that this didn't require a new cluster version.

---

*[pkg/storage/batcheval/cmd_adjust_stats.go, line 45 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RY2O0j8MPD4UA20u-:-L2RY2O0j8MPD4UA20u0:b-o7nifx) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/batcheval/cmd_adjust_stats.go#L45)):*
> ```Go
> 	// shorten the range, so our recomputation would be bogus), though declaring the start key
> 	// (above this comment) already has that effect.
> 	spans.Add(spanset.SpanReadOnly, roachpb.Span{Key: keys.RangeDescriptorKey(desc.StartKey)})
> ```

If we wanted to avoid concurrent adjustments, couldn't we just make one of these declared keys a write?

---

*[pkg/storage/batcheval/cmd_adjust_stats.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RYtluK60XE3oxoNB6:-L2RYtluK60XE3oxoNB7:b-ejor3z) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/batcheval/cmd_adjust_stats.go#L72)):*
> ```Go
> 	}
> 
> 	// If this is a SpanSetBatch, unwrap it. We're intentionally reading without
> ```

Could you expand the first sentence to explain why we need to unwrap it? Something like "unwrap it because we lied to it in declareKeysAdjustStats".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345)*

**Comment by tschottdorf** [comment]
I still have to figure out what happens when introducing new batch requests and sending them to a node that doesn't know them. I hope I addressed the rest.

---

Review status: 1 of 21 files reviewed at latest revision, 14 unresolved discussions.

---

*[pkg/roachpb/api.proto, line 386 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RTzk0cWQJzVA6PDJk:-L2g2VP6gLoPNwCDLPSi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/roachpb/api.proto#L386)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

or what?
</blockquote></details>

Done.

---

*[pkg/roachpb/api.proto, line 393 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RUUUWPkU5Fzs76z1H:-L2g2kCE2UF4x0x4fFqM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/roachpb/api.proto#L393)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`AdjustStatsRequest` sounds a bit off to me. If this request took a stats delta to apply without scanning the entire range it would seem appropriate, but as is, I don't think this conveys the right information. `RecomputeStatsRequest` seems like a better name because it implies how expensive this might be.
</blockquote></details>

Done.

---

*[pkg/roachpb/api.proto, line 397 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2R7hFjoRX8an55CTPb:-L2g2omzU2ytOdVkVwHe:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/roachpb/api.proto#L397)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This looks unused.
</blockquote></details>

Done.

---

*[pkg/roachpb/api.proto, line 400 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2R7p5WSaakn2WU18jp:-L2g2rldiG-5GKBpr9N6:banjwps) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/roachpb/api.proto#L400)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Do you expect to use this anywhere but tests? We're going to be issuing this command without dry_run in an automated fashion and it should be safe and idempotent, so I don't think a dry run flag is necessary.  (a dry run is not any cheaper than a full run since even a "dry run" goes through raft as a write)
</blockquote></details>

Yeah, only in tests.

---

*[pkg/storage/consistency_queue_test.go, line 37 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RVBdgYFYSy8v58rpO:-L2g38mxVmSDAJQEsQCq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/consistency_queue_test.go#L37)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Sorry, it just sticks out like a sore thumb :)
</blockquote></details>

Done.

---

*[pkg/storage/consistency_queue_test.go, line 328 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RW2VmFPzb0F7WiEfI:-L2g3WLoYUV4xN2gkk1X:b-5vbh6h) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/consistency_queue_test.go#L328)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we force a run of the `consistencyQueue`? 3 minutes seems like a long time.
</blockquote></details>

The queue is trying to run quickly. I think there's just a lot of stuff going on in `testrace` that slows it down. 3 minutes is just to catch the tail end of it.

---

*[pkg/storage/helpers_test.go, line 28 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RWEdMmZnXlwaZIHw3:-L2g3vF05Tt1VuORk56M:b-lymlmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/helpers_test.go#L28)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

I've checked 

---

*[pkg/storage/replica_command.go, line 26 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RWJ3II0vYZ6RZ4Eah:-L2g4pht9QiJAU2J_W0c:boyp7s1) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/replica_command.go#L26)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Is this a goland issue?
</blockquote></details>

https://youtrack.jetbrains.com/issue/GO-3092 :(

Interestingly, `goimports -local` doesn't completely fix this:

```diff
diff --git a/pkg/storage/replica_command.go b/pkg/storage/replica_command.go
index 9ede04f7c..16513f7a5 100644
--- a/pkg/storage/replica_command.go
+++ b/pkg/storage/replica_command.go
@@ -23,10 +23,11 @@ import (
 	"sync/atomic"
 	"time"

-	"github.com/cockroachdb/cockroach/pkg/storage/rditer"
 	"github.com/coreos/etcd/raft/raftpb"
 	"github.com/pkg/errors"

+	"github.com/cockroachdb/cockroach/pkg/storage/rditer"
+
 	"github.com/cockroachdb/cockroach/pkg/base"
 	"github.com/cockroachdb/cockroach/pkg/internal/client"
 	"github.com/cockroachdb/cockroach/pkg/keys"
```

I'll humor you in this PR, but generally I'm not super excited by these nits (though I can understand them).

---

*[pkg/storage/replica_consistency.go, line 122 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RWemgeOUaRdl5khbQ:-L2g9W9eR_fSVTfqUsvp:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/replica_consistency.go#L122)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We should note that this doesn't mean that it will never be run twice at the same time.
</blockquote></details>

Done.

---

*[pkg/storage/replica_consistency.go, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RAINenE3ORr7W5VyZ:-L2gFNVHxwmGDHyfE9ve:b-hqzhbg) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/replica_consistency.go#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I was also surprised that this didn't require a new cluster version.
</blockquote></details>

Hmm, that's a good point. I've tried to test this out, but probably didn't do this right. What I think will happen is that we send a `BatchRequest` with a length-one `Requests` that will look like a zero-length `Requests` at the receiver. That will either receive an error (empty batch) or an empty response. In the latter case we're likely going to shoot ourselves in the foot because we rely on there being a response in the `BatchResponse`.

`ClearRange` would have a similar problem. I've added a TODO, intending to look at this in this PR.

---

*[pkg/storage/batcheval/cmd_adjust_stats.go, line 40 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2R5LrMs3tb95C6f3br:-L2gHTulNY7m_1VVXB8-:b49hf2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/batcheval/cmd_adjust_stats.go#L40)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The start key is a real key, so this will interfere with at least some regular transactions. Maybe we should target this command to the range descriptor instead? 
</blockquote></details>

PTAL. I think declaring a read on the range descriptor (for splits) and a write on some key that only we use is the way to go.

---

*[pkg/storage/batcheval/cmd_adjust_stats.go, line 45 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RY2O0j8MPD4UA20u-:-L2gG5gapy1NJ_efWdlE:b-s1oacg) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/batcheval/cmd_adjust_stats.go#L45)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

If we wanted to avoid concurrent adjustments, couldn't we just make one of these declared keys a write?
</blockquote></details>

We could, but then we'd block a whole lot more. I did something though, see the comment thread above this one (and the updated code).

---

*[pkg/storage/batcheval/cmd_adjust_stats.go, line 68 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2R91fyqKUEFTXhHHEX:-L2gHRykLbgTG6fEUMZk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/batcheval/cmd_adjust_stats.go#L68)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This could check `args.Key.Equal(desc.StartKey)` since the EndKey is set identically in both cases. 
</blockquote></details>

Done.

---

*[pkg/storage/batcheval/cmd_adjust_stats.go, line 72 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RYtluK60XE3oxoNB6:-L2gH8UOuskMIZiJ5aWG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/batcheval/cmd_adjust_stats.go#L72)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Could you expand the first sentence to explain why we need to unwrap it? Something like "unwrap it because we lied to it in declareKeysAdjustStats".
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-:-L2gZxRxXHuo2tWDAFlS:bb1w6ln)*

**Comment by bdarnell** [comment]
LGTM aside from the question of migration. 

---

Reviewed 1 of 20 files at r2, 21 of 21 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica_consistency.go, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L2RAINenE3ORr7W5VyZ:-L2veLofB92JgYzXK4YR:b8140uh) ([raw file](https://github.com/cockroachdb/cockroach/blob/633d8f5d3ca38964cdb245bf8e9cf42d1ae9ad4b/pkg/storage/replica_consistency.go#L132)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Hmm, that's a good point. I've tried to test this out, but probably didn't do this right. What I think will happen is that we send a `BatchRequest` with a length-one `Requests` that will look like a zero-length `Requests` at the receiver. That will either receive an error (empty batch) or an empty response. In the latter case we're likely going to shoot ourselves in the foot because we rely on there being a response in the `BatchResponse`.

`ClearRange` would have a similar problem. I've added a TODO, intending to look at this in this PR.
</blockquote></details>

I think it'll be a non-empty `Requests` slice, but attempting to extract the request will result in nil, which I'm pretty sure will panic somewhere. If it makes it far enough, Replica.Send will treat it as read-only since it doesn't contain any requests with the write or admin flags, then `evaluateBatch` will panic in `RequestUnion.GetInner`. So I think we will need a migration for this case. Adding a check so that unknown commands return a clean error instead of a panic would make future cases like this easier since we could catch the error instead of killing the node. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-:-L2vfqkB1QnVgipqOvzW:b-shtp39)*

**Comment by tschottdorf** [comment]
Breaks as expected. I'll fix this regression, send a patch to the v1.1 series, and add migrations for `ClearRange` and `RecomputeStats`.

```
E180116 09:56:14.048458 1796 util/log/crash_reporting.go:83  [n1] a panic has occurred!
E180116 09:56:14.177092 1796 util/log/crash_reporting.go:176  [n1] Reported as error 4b753b8a92df46698d28f184860cbb08
panic: interface conversion: interface is nil, not roachpb.Request [recovered]
        panic: interface conversion: interface is nil, not roachpb.Request

goroutine 1796 [running]:
github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).Recover(0xc420568500, 0x6e6b9e8, 0xc420c2eb40)
        /go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:200 +0xb1
panic(0x533ed00, 0xc420db8180)
        /usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/cockroachdb/cockroach/pkg/roachpb.RequestUnion.GetInner(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/roachpb/api.go:367 +0x4f
github.com/cockroachdb/cockroach/pkg/keys.Range(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/pkg/keys/keys.go:637 +0x17f
github.com/cockroachdb/cockroach/pkg/storage.(*Stores).Send(0xc4202b4080, 0x6e6b9e8, 0xc420c2eba0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, .
..)
        /go/src/github.com/cockroachdb/cockroach/pkg/storage/stores.go:148 +0x66
github.com/cockroachdb/cockroach/pkg/server.(*Node).batchInternal.func1(0x6e6b9e8, 0xc420c2eba0, 0x0, 0x0)
```

---

Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-:-L2zTYUp0whVWHrnRbuH:b-wlfjii)*

**Comment by tschottdorf** [comment]
Ah, this panic actually doesn't apply to realistic requests (it's the test-only store-driven replica lookup path), but I'm sure it would break in other ways and should be prevented from getting into the system in the first place.

---

Review status: all files reviewed at latest revision, 12 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-:-L2zUmQ8J1JWMZa8YI-c:b-tek3hc)*

**Comment by tschottdorf** [comment]
Added the migration (`ClearRange` was OK already, I had overlooked the migration earlier).
Refusing unknown requests is in https://github.com/cockroachdb/cockroach/pull/21466.

Will merge on green, TFTRs!

**Comment by tschottdorf** [comment]
Fixing up that test was more interesting than I thought it was going to be, but now everything should be hunky dory. @nvanbenschoten could you give that a look?

---

Review status: 1 of 24 files reviewed at latest revision, 12 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-:-L33jf3B-3ViJ54uGOJ-:b-evu5hn)*

**Comment by nvanbenschoten** [comment]
:lgtm_strong: 

---

Reviewed 1 of 20 files at r2, 1 of 21 files at r4, 6 of 21 files at r5, 23 of 23 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[pkg/storage/batcheval/cmd_recompute_stats.go, line 49 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L33teUtVrYm379D-0hr:-L33teUtVrYm379D-0hs:b-5hojax) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa6acd7843ddd85f3117d95575f88124e017998/pkg/storage/batcheval/cmd_recompute_stats.go#L49)):*
> a write on a transaction anchored at the range descriptor key

Do any other commands declare this key? Or is it completely synthetic?

---

*[pkg/storage/batcheval/cmd_recompute_stats.go, line 79 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L33u6zIsg4rxf1GMZAg:-L33u6zIsg4rxf1GMZAh:b6npdzc) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa6acd7843ddd85f3117d95575f88124e017998/pkg/storage/batcheval/cmd_recompute_stats.go#L79)):*
> ```Go
> 	// we read from the range state if concurrent writes are inflight[1].
> 	//
> 	// Note that in doing so, we also circumvent the assertions (present in both
> ```

Nice, this actually makes things simpler!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-:-L33uJiHBjkETRipqb5A:b-uwkowd)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/storage/batcheval/cmd_recompute_stats.go, line 49 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345#-L33teUtVrYm379D-0hr:-L33yoA2ISILDuM22RGH:boicliv) ([raw file](https://github.com/cockroachdb/cockroach/blob/aaa6acd7843ddd85f3117d95575f88124e017998/pkg/storage/batcheval/cmd_recompute_stats.go#L49)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> a write on a transaction anchored at the range descriptor key

Do any other commands declare this key? Or is it completely synthetic?
</blockquote></details>

Synthetic, though I assume a split would use it, but very unlikely with a nil ID.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21345)*

**Pull request merged**
