### PR TITLE
deps: update errors and the sentry-go dependency

### LINKED ISSUE #76439: deps: evaluate a possible upgrade to the newest sentry-go
Currently CockroachDb files issues to Sentry.io using an outdated version of sentry-go (SDK 0.6.1).

The filing of issues happens automatically via the [errors library](https://github.com/cockroachdb/errors).
This week, an external contributor volunteered to upgrade the sentry-go dependency in `errors`: https://github.com/cockroachdb/errors/pull/92

Before we accept this PR, we need to **qualify this inside CockroachDB**:
1. create a build of CockroachDB with the proposed patch in `errors`.
2. point the build to our dev instance in Sentry.io
3. trigger a reportable error
4. check in the Sentry UI that the error report is 1) actually filed and 2) that the metadata is preserved just as well as in the previous SDK version.

### PR DESCRIPTION
**Pull request by knz**
Fixes #76439.

This updates the sentry SDK version from 0.6.1 to 0.12.0.

### CODE REVIEW

**Review by rail — CHANGES_REQUESTED** [review]
`cockroachdb/sentry-go` is still in `go.sum`,  probably this is why the test fails.

> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-:-Mvs7lgWE8Y2BpK3RpM8:b78gqwk)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[go.sum, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-Mvs8zRu0JZuuJ6rYn-b:-Mvs8zRu0JZuuJ6rYn-c:bhnynmz) ([raw file](https://github.com/cockroachdb/cockroach/blob/14cfcc55ef38ef376eae10cb8b12e2c5bea939c2/go.sum#L440)):*
> ```
> github.com/cockroachdb/returncheck v0.0.0-20200612231554-92cdbca611dd h1:KFOt5I9nEKZgCnOSmy8r4Oykh8BYQO8bFOTgHDS8YZA=
> github.com/cockroachdb/returncheck v0.0.0-20200612231554-92cdbca611dd/go.mod h1:AN708GD2FFeLgUHMbD58YPe4Nw8GG//3rwgyG4L9gR0=
> github.com/cockroachdb/sentry-go v0.6.1-cockroachdb.2/go.mod h1:8BT+cPK6xvFOcRlk0R8eg+OTkcqI6baNH4xAkpiYVvQ=
> ```

Looks like this line makes the linter unhappy.
___
*[pkg/cli/flags_test.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-Mvs847mDmbYd-J0NO95:-Mvs847mDmbYd-J0NO96:biry315) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb473c8f304ac20fec51ff0a0d04e128383bcf6/pkg/cli/flags_test.go#L74)):*
> ```Go
> 			"github.com/cockroachdb/cockroach/pkg/testutils", // meant for testing code only
> 		},
> 		// Sentry and the errors library use go/build to determine
> ```

Can you also update the comments here to mention only the errors library.



_Code quote (from pkg/util/log/logcrash/crash_reporting.go):_
```Go
cockroachdb/sentry-go
```

**Review by knz — COMMENTED** [review]
I don't see any test failure, other than the unrelated test flakes in #76501 and #76502.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-:-MvsNt6iDazUReWtpOcr:bw5h30)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[go.sum, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-Mvs8zRu0JZuuJ6rYn-b:-MvsNqgS7QO9sY7YIPHj:b-nydrl3) ([raw file](https://github.com/cockroachdb/cockroach/blob/14cfcc55ef38ef376eae10cb8b12e2c5bea939c2/go.sum#L440)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Looks like this line makes the linter unhappy.
</blockquote></details>

Done. But what is this "linter" you speak of?
___
*[pkg/cli/flags_test.go, line 74 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-Mvs847mDmbYd-J0NO95:-MvsNprECuCAt8UEVi2L:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbb473c8f304ac20fec51ff0a0d04e128383bcf6/pkg/cli/flags_test.go#L74)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

Can you also update the comments here to mention only the errors library.
</blockquote></details>

Done.

**Review by rail — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[go.sum, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-Mvs8zRu0JZuuJ6rYn-b:-Mvscs3MCrjbBe4tfss9:b8xr1qz) ([raw file](https://github.com/cockroachdb/cockroach/blob/14cfcc55ef38ef376eae10cb8b12e2c5bea939c2/go.sum#L440)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Done. But what is this "linter" you speak of?
</blockquote></details>

"check generated code", see https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_CheckGeneratedCode/4371077?showRootCauses=true&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true
It's more like a build system linter.

The error is still there :thinking:, maybe something special in https://github.com/cockroachdb/cockroach/blob/master/build/bazelutil/bazel-generate.sh

**Comment by knz** [comment]
I fixed the broken tests. RFAL

**Review by rail — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rail)

___
*[go.sum, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-Mvs8zRu0JZuuJ6rYn-b:-Mvsf24s6YdjAajx2VIg:b-1moavv) ([raw file](https://github.com/cockroachdb/cockroach/blob/14cfcc55ef38ef376eae10cb8b12e2c5bea939c2/go.sum#L440)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

"check generated code", see https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_CheckGeneratedCode/4371077?showRootCauses=true&expandBuildChangesSection=true&expandBuildDeploymentsSection=true&expandBuildProblemsSection=true
It's more like a build system linter.

The error is still there :thinking:, maybe something special in https://github.com/cockroachdb/cockroach/blob/master/build/bazelutil/bazel-generate.sh
</blockquote></details>

https://github.com/cockroachdb/cockroach/blob/bbb473c8f304ac20fec51ff0a0d04e128383bcf6/pkg/cmd/mirror/mirror.go#L177 calls `go list -mod=readonly -m all`. 
```
go list -m: github.com/cockroachdb/datadriven@v1.0.1-0.20211007161720-b558070c3be0 requires
	github.com/cockroachdb/errors@v1.6.1 requires
	github.com/cockroachdb/sentry-go@v0.6.1-cockroachdb.2: missing go.sum entry; to add it:
	go mod download github.com/cockroachdb/sentry-go
```

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rail)

___
*[go.sum, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-Mvs8zRu0JZuuJ6rYn-b:-MvsjZWe4Cydos3jVhLP:b-on1l89) ([raw file](https://github.com/cockroachdb/cockroach/blob/14cfcc55ef38ef376eae10cb8b12e2c5bea939c2/go.sum#L440)):*
<details><summary><i>Previously, rail (Rail Aliiev) wrote…</i></summary><blockquote>

https://github.com/cockroachdb/cockroach/blob/bbb473c8f304ac20fec51ff0a0d04e128383bcf6/pkg/cmd/mirror/mirror.go#L177 calls `go list -mod=readonly -m all`. 
```
go list -m: github.com/cockroachdb/datadriven@v1.0.1-0.20211007161720-b558070c3be0 requires
	github.com/cockroachdb/errors@v1.6.1 requires
	github.com/cockroachdb/sentry-go@v0.6.1-cockroachdb.2: missing go.sum entry; to add it:
	go mod download github.com/cockroachdb/sentry-go
```
</blockquote></details>

But this logic is broken, right? The dependency graph should smoothly upgrade the dependency of datadriven to errors 1.8.7 since it's compatible with 1.6.1, and drop the dependency to cockroachdb/sentry-go. We don't need it any more in the top level.

So it looks to me that `mirror.go` has incorrect logic.

Why does this use `go list -mod=readonly` and not `go list -mod=mod` btw?

**Review by rail — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76498)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[DEPS.bzl, line 1311 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-Mvsm3bY3wUoIFLDfAte:-Mvsm3bZ12K8wBkANIVU:b-pxo3yq) ([raw file](https://github.com/cockroachdb/cockroach/blob/09eedbe3a57491e8722258832a884c21b6500181/DEPS.bzl#L1311)):*
> ```Starlark
>         importpath = "github.com/cockroachdb/sentry-go",
>         sha256 = "fbb2207d02aecfdd411b1357efe1192dbb827959e36b7cab7491731ac55935c9",
>         strip_prefix = "github.com/cockroachdb/sentry-go@v0.6.1-cockroachdb.2",
> ```

hmmm, I'm not sure we want to keep it around just to make the test pass. :thinking: 
___
*[go.sum, line 440 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-Mvs8zRu0JZuuJ6rYn-b:-MvsliJV9zuu4rQM4dqO:bsd6q0n) ([raw file](https://github.com/cockroachdb/cockroach/blob/14cfcc55ef38ef376eae10cb8b12e2c5bea939c2/go.sum#L440)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

But this logic is broken, right? The dependency graph should smoothly upgrade the dependency of datadriven to errors 1.8.7 since it's compatible with 1.6.1, and drop the dependency to cockroachdb/sentry-go. We don't need it any more in the top level.

So it looks to me that `mirror.go` has incorrect logic.

Why does this use `go list -mod=readonly` and not `go list -mod=mod` btw?
</blockquote></details>

I think `go list` thinks they are different modules and this is why it's still there. `datadriven` still thinks that our fork is required. Probably we have to update datadriven's deps too.

**Comment by knz** [comment]
I have iterated back and forth between datadriven and errors, and was not able to get them to remove the offending package from go.sum. I suspect there's yet another 3rd party dependency, perhaps used indirectly, that depends on an older version of cockroachdb/errors.

I'm not sure what else we should do here?

**Comment by knz** [comment]
okay I've done my best here. I think this is good enough to say "we dropped the fork" since it's not copied into the vendor/ tree any more. I'm not too concerned by go.sum at this point - it doesn't seem to hurt.

**Review by rail — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r5, 2 of 3 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/76498#-:-MvxyZak7MZtqEzpwfnZ:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @knz)

**Pull request merged**
