### PR TITLE
Makefile: add some missing prereqs

### LINKED ISSUE #22808: *: `make build` fails the first time around
Looks like the submodules are not available during some invocation of `find` (`master` near https://github.com/cockroachdb/cockroach/commit/f9f3d43ca646b6b8a84c6d09b091936ac30bc1ae)

```
tschottdorf@gceworker-tstest:~/go/src/github.com/cockroachdb/cockroach$ make build
GOPATH set to /home/tschottdorf/go
find: ‘./vendor/github.com/coreos/etcd/raft’: No such file or directory
Running make with -j24
find: ‘./vendor/github.com/coreos/etcd/raft’: No such file or directory
Running make with -j24
git submodule update --init
Submodule 'c-deps/cryptopp' (https://github.com/cockroachdb/cryptopp.git) registered for path 'c-deps/cryptopp'
Submodule 'c-deps/googletest' (https://github.com/cockroachdb/googletest) registered for path 'c-deps/googletest'
Submodule 'c-deps/jemalloc' (https://github.com/cockroachdb/jemalloc.git) registered for path 'c-deps/jemalloc'
Submodule 'c-deps/protobuf' (https://github.com/cockroachdb/protobuf.git) registered for path 'c-deps/protobuf'
Submodule 'c-deps/rocksdb' (https://github.com/cockroachdb/rocksdb.git) registered for path 'c-deps/rocksdb'
Submodule 'c-deps/snappy' (https://github.com/cockroachdb/snappy.git) registered for path 'c-deps/snappy'
Submodule 'vendor' (https://github.com/cockroachdb/vendored) registered for path 'vendor'
build/node-run.sh -C ./pkg/ui yarn install
Cloning into 'c-deps/cryptopp'...
installing githooks/post-rewrite
installing githooks/commit-msg
installing githooks/post-checkout
installing githooks/prepare-commit-msg
```

### PR DESCRIPTION
**Pull request by benesch**
Fix #22808.

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 1182 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22830#-L5nNiRwerMqay_pco3j:-L5nNiRwerMqay_pco3k:b-j7rdi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b33b086574afda41ebe6f9462295ab8f5421edd/Makefile#L1182)):*
> ```Makefile
> 	gofmt -s -w $@
> 
> bin/.docgen_bnfs: $(SQLPARSER_ROOT)/sql.y pkg/cmd/docgen/diagrams.go pkg/cmd/docgen/main.go | $(SUBMODULES_TARGET)
> ```

My make is rusty: what does `|` do in a prereqs list?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22830)*

**Comment by benesch** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 1182 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/22830#-L5nNiRwerMqay_pco3j:-L5nZg4g4d--zGUmJQeT:bofudkh) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b33b086574afda41ebe6f9462295ab8f5421edd/Makefile#L1182)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

My make is rusty: what does `|` do in a prereqs list?
</blockquote></details>

It's an order-only prerequisite: https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html

Unlike a normal prerequisite, the target's mtime isn't checked, only its existence.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/22830)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Makefile, line 1182 at r2](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22830#-L5nNiRwerMqay_pco3j:-L5nd8Ht-udUpCKbJdDd:b2nhoia) ([raw file](https://github.com/cockroachdb/cockroach/blob/8b33b086574afda41ebe6f9462295ab8f5421edd/Makefile#L1182)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

It's an order-only prerequisite: https://www.gnu.org/software/make/manual/html_node/Prerequisite-Types.html

Unlike a normal prerequisite, the target's mtime isn't checked, only its existence.
</blockquote></details>

TIL

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/22830#-:-L5ndOHMDcTmegdnOpQ-:bnfp4nl)*

**Review by tbg — APPROVED** [review]
Thanks @benesch!

**Comment by benesch** [comment]
TFTRs!

**Pull request merged**
