### PR TITLE
sql: support collated strings within arrays

### PR DESCRIPTION
**Pull request by justinj**
The syntax for this is a little odd, given the collation goes on the
outside of the array, but it's the same as postgres (and I guess it
makes sense if you think of the collation as a property of the entire
type).

### CODE REVIEW

**Comment by knz** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17489#-:-KqyRFuOU95wsz1NioZ2:bnfp4nl)*

**Comment by jordanlewis** [comment]
:lgtm: but as we discussed offline I think you should add a bunch of new test cases for all of the collations stuff you're scared of. Array containing several collations should fail. Do operations to arrays with mismatched collations fail as well? Etc.

---

Reviewed 7 of 7 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17489#-:-KqyTdRMYes0c_5RuWvs:b-4i8ysp)*

**Comment by justinj** [comment]
Ok, PTAL! I added a handful of extra tests (and found a case I wasn't handling as a result)

**Comment by knz** [comment]
:+1:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17489#-:-Kr1XAPzDLbTbtYRzKSb:bb6mt9b)*

**Pull request merged**
