### PR TITLE
distsqlrun, opt: Add planNode and distsql planner case for zigzagjoin

### PR DESCRIPTION
**Pull request by itsbilal**
This change adds a planNode to represent zigzag joins, as well as
associated planning code in distsql_physical_planner to convert it to a
processor spec. It also makes minor changes to the spec and the zigzag
joiner itself for more efficient passing of fixed values from the
planner/opt node.

The change to actually plan zigzag joins in the optimizer will land in a
separate PR.

Release note: None

### CODE REVIEW

**Review by gautamgupta — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32431)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 1969 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRjBhf55SEhO61pZ2OC:-LRjBhf55SEhO61pZ2OD:b-jeal0g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1db12a0b026e860b443b7603b5f3d9e5a40f22/pkg/sql/distsql_physical_planner.go#L1969)):*
> ```Go
> 
> 	tables := make([]sqlbase.TableDescriptor, len(n.sides))
> 	indexids := make([]uint32, len(n.sides))
> ```

`indexIds`?
___
*[pkg/sql/distsql_physical_planner.go, line 2017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRjC8bd-C6Wgtz6ZFC_:-LRjC8bd-C6Wgtz6ZFCa:bgop668) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1db12a0b026e860b443b7603b5f3d9e5a40f22/pkg/sql/distsql_physical_planner.go#L2017)):*
> ```Go
> 	planToStreamColMap := makePlanToStreamColMap(numOutCols)
> 	colOffset := 0
> 	i := 0
> ```

Is `i` actually used / read again?
___
*[pkg/sql/distsql_physical_planner.go, line 2023 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRjCQqO0g6xe6Mfe3kM:-LRjCQqO0g6xe6Mfe3kN:bnem8ha) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1db12a0b026e860b443b7603b5f3d9e5a40f22/pkg/sql/distsql_physical_planner.go#L2023)):*
> ```Go
> 			ord := tableOrdinal(side.scan.desc, colID, side.scan.colCfg.visibility)
> 
> 			post.OutputColumns[colOffset+ord] = uint32(colOffset + ord)
> ```

Maybe we can extract `colOffset+ord` into a variable
___
*[pkg/sql/opt_exec_factory.go, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRjCfe77atYmuN5W39Z:-LRjCfe77atYmuN5W39_:b-j70lm3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1db12a0b026e860b443b7603b5f3d9e5a40f22/pkg/sql/opt_exec_factory.go#L631)):*
> ```Go
> ) (*scanNode, error) {
> 	colCount := len(indexDesc.ColumnIDs) + len(indexDesc.ExtraColumnIDs)
> 	colCount += len(indexDesc.StoreColumnIDs)
> ```

We can have this continue from the previous line?

**Comment by jordanlewis** [comment]
Going to review this today.

**Review by jordanlewis — COMMENTED** [review]
Generally looks good - @gautamgupta's comments also seem reasonable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-:-LRnJot82e_y4nxp77YS:b-1iauux)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2009 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRn88wE2bw-tWu4-IvC:-LRn88wE2bw-tWu4-IvD:buh07zh) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/distsql_physical_planner.go#L2009)):*
> ```Go
> 	//
> 	// The schema of the zigzagJoinNode is:
> 	//    <side 1 index columns> ... <side 2 index columns> ...
> ```

Is the second half of this comment redundant?
___
*[pkg/sql/distsql_physical_planner.go, line 2019 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRn8oyLAsYQpiQYgSfU:-LRn8oyLAsYQpiQYgSfV:brbx83s) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/distsql_physical_planner.go#L2019)):*
> ```Go
> 	i := 0
> 
> 	for _, side := range n.sides {
> ```

Add a comment above this loop, explaining what it's doing at a high level. Just something like "Populate post.OutputColumns with the internal schema" would be helpful.
___
*[pkg/sql/distsql_physical_planner.go, line 2058 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRnJI_l7mAvlZ-WZGrJ:-LRnJI_l7mAvlZ-WZGrK:bave1sm) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/distsql_physical_planner.go#L2058)):*
> ```Go
> 	stageID := plan.NewStageID()
> 	// Set the ON condition.
> 	if n.onCond != nil {
> ```

Just so I understand, this shouldn't ever get set today, right? When we're just doing 2-index searches.
___
*[pkg/sql/opt_exec_factory.go, line 648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRnJbx1ASiCybag-DKi:-LRnJbx1ASiCybag-DKj:bsonhgv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/opt_exec_factory.go#L648)):*
> ```Go
> 
> 	scan := ef.planner.Scan()
> 	if err := scan.initTable(context.TODO(), ef.planner, tableDesc, nil, colCfg); err != nil {
> ```

suspicious use of context.TODO - do we not have one to plumb in?
___
*[pkg/sql/opt_exec_factory.go, line 653 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRnJZCtCFuYbqDYIA_O:-LRnJZCtCFuYbqDYIA_P:be4wd4y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/opt_exec_factory.go#L653)):*
> ```Go
> 
> 	scan.index = indexDesc
> 	scan.run.isSecondaryIndex = (indexDesc != &tableDesc.PrimaryIndex)
> ```

This seems suspicious - compare the ids instead of the pointers.
___
*[pkg/sql/walk.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRn5adq8qMhpbUGxbYm:-LRn5adq8qMhpbUGxbYn:bohzsim) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/walk.go#L229)):*
> ```Go
> 			v.observer.attr(name, "type", joinTypeStr(n.joinType))
> 			for _, side := range n.sides {
> 				v.observer.attr(name, "table", fmt.Sprintf("%s@%s", side.scan.desc.Name, side.scan.index.Name))
> ```

Can you include the scan spans here? Actually, since the node seems to contain one scanNode per side, you should just recurse into those nodes - with `v.visitConcrete(side.scan)`. Actually, I think you could avoid this call to `attr` if you just recurse in the way I'm suggesting.

And you could consider adding the information produced by the "fixed values" to the explain output as well. I'm sure it would prove useful.
___
*[pkg/sql/zigzag_join.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRn5sCYCSMUkQTeoP3Z:-LRn5sCZ0V3_Lz_7WlM7:bg4515y) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/zigzag_join.go#L24)):*
> ```Go
> )
> 
> type zigzagJoinNode struct {
> ```

Please add a top-level struct comment explaining what zigzag join is. Since the main implementation lives in distsql, just put a one-sentence summary and a "link" to the real description.

**Review by itsbilal — COMMENTED** [review]
Thanks for the review @jordanlewis! I've addressed everything you mentioned. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-:-LRrQQx2DqqyHbSMcOPP:b-50fpk6)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 1969 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRjBhf55SEhO61pZ2OC:-LRr1v1mED6PdBgn8r4E:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1db12a0b026e860b443b7603b5f3d9e5a40f22/pkg/sql/distsql_physical_planner.go#L1969)):*
<details><summary><i>Previously, GautamGupta (Gautam Gupta) wrote…</i></summary><blockquote>

`indexIds`?
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 2017 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRjC8bd-C6Wgtz6ZFC_:-LRr2LGyEdu8RfZhAJgU:bv8ypvm) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1db12a0b026e860b443b7603b5f3d9e5a40f22/pkg/sql/distsql_physical_planner.go#L2017)):*
<details><summary><i>Previously, GautamGupta (Gautam Gupta) wrote…</i></summary><blockquote>

Is `i` actually used / read again?
</blockquote></details>

It needs to survive one iteration of `n.sides`, so yes it needs to live outside that scope.
___
*[pkg/sql/distsql_physical_planner.go, line 2009 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRn88wE2bw-tWu4-IvC:-LRr1vzA6uszjPQRQl9T:b-qb3qgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/distsql_physical_planner.go#L2009)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Is the second half of this comment redundant?
</blockquote></details>

The difference is `s/tables/index/`. I'll make that more obvious.
___
*[pkg/sql/distsql_physical_planner.go, line 2019 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRn8oyLAsYQpiQYgSfU:-LRr6KrCCykI3-vSKXk0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/distsql_physical_planner.go#L2019)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Add a comment above this loop, explaining what it's doing at a high level. Just something like "Populate post.OutputColumns with the internal schema" would be helpful.
</blockquote></details>

Done.
___
*[pkg/sql/distsql_physical_planner.go, line 2058 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRnJI_l7mAvlZ-WZGrJ:-LRr6NOr30biZ0EyGwsb:b7fsdbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/distsql_physical_planner.go#L2058)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Just so I understand, this shouldn't ever get set today, right? When we're just doing 2-index searches.
</blockquote></details>

It can be set - if there's a filter on one of the STORING columns. Currently (based on how the other PR is written), we still pass on `fixedCol` equality filters in the `onCond` for sanity / better pretty-printed output, but those can effectively be removed.
___
*[pkg/sql/opt_exec_factory.go, line 631 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRjCfe77atYmuN5W39Z:-LRr87LjEFxAhTco_g5B:bmed27n) ([raw file](https://github.com/cockroachdb/cockroach/blob/9a1db12a0b026e860b443b7603b5f3d9e5a40f22/pkg/sql/opt_exec_factory.go#L631)):*
<details><summary><i>Previously, GautamGupta (Gautam Gupta) wrote…</i></summary><blockquote>

We can have this continue from the previous line?
</blockquote></details>

Line would be too long
___
*[pkg/sql/opt_exec_factory.go, line 648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRnJbx1ASiCybag-DKi:-LRr8FRH1teX8HAzIVey:byx9d7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/opt_exec_factory.go#L648)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

suspicious use of context.TODO - do we not have one to plumb in?
</blockquote></details>

Seems like every other call to `initTable` in this file does the same thing, so it's probably fine?
___
*[pkg/sql/opt_exec_factory.go, line 653 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRnJZCtCFuYbqDYIA_O:-LRr9IXI7BI25LcUcx5j:b-aimxat) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/opt_exec_factory.go#L653)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This seems suspicious - compare the ids instead of the pointers.
</blockquote></details>

Done. Other instances of the same comparison in this file compare pointers though, but IDs make more sense.
___
*[pkg/sql/walk.go, line 229 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRn5adq8qMhpbUGxbYm:-LRrMyUp10YaTsFP08BJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/walk.go#L229)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you include the scan spans here? Actually, since the node seems to contain one scanNode per side, you should just recurse into those nodes - with `v.visitConcrete(side.scan)`. Actually, I think you could avoid this call to `attr` if you just recurse in the way I'm suggesting.

And you could consider adding the information produced by the "fixed values" to the explain output as well. I'm sure it would prove useful.
</blockquote></details>

Done.
___
*[pkg/sql/zigzag_join.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRn5sCYCSMUkQTeoP3Z:-LRrQNyu3GMeV4LigEyw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/zigzag_join.go#L24)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Please add a top-level struct comment explaining what zigzag join is. Since the main implementation lives in distsql, just put a one-sentence summary and a "link" to the real description.
</blockquote></details>

Done.

**Review by jordanlewis — APPROVED** [review]
:lgtm: - this is great! Though it doesn't make me happy that there aren't any tests, I imagine you're going to add those in the next PR since without the optimizer support the planNode is not usable.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-:-LSFAT5_BK_nurTH_3Ry:b-5ucmsb)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/sql/distsql_physical_planner.go, line 2058 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRnJI_l7mAvlZ-WZGrJ:-LSF9t227Cl4i0XoVWOO:b5o90rr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/distsql_physical_planner.go#L2058)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

It can be set - if there's a filter on one of the STORING columns. Currently (based on how the other PR is written), we still pass on `fixedCol` equality filters in the `onCond` for sanity / better pretty-printed output, but those can effectively be removed.
</blockquote></details>

I see, ok.
___
*[pkg/sql/opt_exec_factory.go, line 648 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRnJbx1ASiCybag-DKi:-LSF9yit3xpmrVMM41hD:be5d9wr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/opt_exec_factory.go#L648)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Seems like every other call to `initTable` in this file does the same thing, so it's probably fine?
</blockquote></details>

Oops, didn't see that. sounds good
___
*[pkg/sql/opt_exec_factory.go, line 653 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32431#-LRnJZCtCFuYbqDYIA_O:-LSFA1QS-wwwQoE-Hj8p:b13581r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ba99165f84eac5225d0e5fc83ea81bc39bcac9aa/pkg/sql/opt_exec_factory.go#L653)):*
<details><summary><i>Previously, itsbilal (Bilal Akhtar) wrote…</i></summary><blockquote>

Done. Other instances of the same comparison in this file compare pointers though, but IDs make more sense.
</blockquote></details>

Heh, didn't realize that. I would say you could have kept it then, but I do agree comparing by IDs seems better...

**Comment by itsbilal** [comment]
Thanks for the review! And yes - this is practically dead code unfortunately until #32512 lands. That one should land within this week though, so hopefully it'll be tested very soon.

bors r+

**Pull request merged**
