### PR TITLE
acceptance: use generated names

### PR DESCRIPTION
**Pull request by tbg**
Instead of timestamps, use generated names as a random component
of generated terraform resources.

Harmonize allocator test naming (some used `to`, others `To`, and while I was at it, I added some separation).
cc @jordanlewis wrt to possibly breaking nightly tests with the renames.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7530)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: 2 of 4 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530)*

**Comment by jordanlewis** [comment]
This won't break anything -- nothing looks at the instance names except for the tests themselves.

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[acceptance/allocator_test.go, line 322 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLSaA8je-9Meo_R0Gyg:-KLSaA8je-9Meo_R0Gyh:1923878945) ([raw file](https://github.com/cockroachdb/cockroach/blob/f642921af5d3aeea4c8f4a42ffe61020b1e37b0a/acceptance/allocator_test.go#L322)):*
> ```Go
> 		EndNodes:   3,
> 		StoreURL:   archivedStoreURL + "/1node-10g-262ranges",
> 		Prefix:     "u1to3s",
> ```

I'm not crazy about making these names super compact and hard to understand because they show up in the Google Cloud console. It's probably useful to know what tests are using what resources. That being said, this isn't a big deal and I could go either way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-:-KLSaMiGsmoL8LfDrkeh:-1748801249)*

**Comment by tschottdorf** [comment]
Updated: cribbing the name generation code from docker to avoid the (big) dependency. PTAL.

---

Review status: 2 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[acceptance/allocator_test.go, line 322 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLSaA8je-9Meo_R0Gyg:-KLSbG3vk5s5yMU0iGqN:-508135611) ([raw file](https://github.com/cockroachdb/cockroach/blob/f642921af5d3aeea4c8f4a42ffe61020b1e37b0a/acceptance/allocator_test.go#L322)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> I'm not crazy about making these names super compact and hard to understand because they show up in the Google Cloud console. It's probably useful to know what tests are using what resources. That being said, this isn't a big deal and I could go either way.
</details>
Is this too compact? I found `uprep-1to3-small` unnecessarily verbose (though the reason I made this change is that the terraform regex elsewhere suggests that there is a 45 character limit).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-:-KLScXuUIGnDR4cRygzl:-203187501)*

**Comment by jordanlewis** [comment]
Reviewable seems to be down for the moment, but my opinion is that the original name, although verbose, provides the right amount of detail for a name that will appear on the global GCE instance list. If this were just an in-code name I'd feel differently, but for something that gets shown on a website that is incredibly far removed from its source (this particular acceptance test) I think it's quite useful to have that extra detail.

**Comment by cuongdo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[acceptance/allocator_test.go, line 322 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLSaA8je-9Meo_R0Gyg:-KLSdlA6ajohozkUnXJA:-1708327244) ([raw file](https://github.com/cockroachdb/cockroach/blob/f642921af5d3aeea4c8f4a42ffe61020b1e37b0a/acceptance/allocator_test.go#L322)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary>
> Is this too compact? I found `uprep-1to3-small` unnecessarily verbose (though the reason I made this change is that the terraform regex elsewhere suggests that there is a 45 character limit).
</details>
maybe `uprep1to3s`? The 45 character limit is so that when such strings like `-block-writer-1` and `-cockroach-50` are appended, we're under Terraform's limit (which I think is 63). I think that with your change to using the generated name as part of the prefix, `u1to3s` is unnecessarily short.

---

*[acceptance/allocator_test.go, line 334 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLSeQjh57Gm5vVfSb0S:-KLSeQjh57Gm5vVfSb0T:2055546228) ([raw file](https://github.com/cockroachdb/cockroach/blob/29da7757d21dc99445b06dfda21c6dc38f08848e/acceptance/allocator_test.go#L334)):*
> ```Go
> 		EndNodes:   5,
> 		StoreURL:   archivedStoreURL + "/3nodes-10g-262ranges",
> 		Prefix:     "r3to5s",
> ```

maybe `rebal3to5s`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530)*

**Comment by cuongdo** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[acceptance/allocator_test.go, line 322 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLSaA8je-9Meo_R0Gyg:-KLSfZK-ePo3B2kj10IA:-1178568364) ([raw file](https://github.com/cockroachdb/cockroach/blob/f642921af5d3aeea4c8f4a42ffe61020b1e37b0a/acceptance/allocator_test.go#L322)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> maybe `uprep1to3s`? The 45 character limit is so that when such strings like `-block-writer-1` and `-cockroach-50` are appended, we're under Terraform's limit (which I think is 63). I think that with your change to using the generated name as part of the prefix, `u1to3s` is unnecessarily short.
</details>
I guess the generated names aren't *that* short. Still, I think a bit more verbosity would be helpful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[acceptance/util_test.go, line 118 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLSozXN-nf1O2iQ3T_O:-KLSozXOOTVMpEKHbQtX:-360054209) ([raw file](https://github.com/cockroachdb/cockroach/blob/29da7757d21dc99445b06dfda21c6dc38f08848e/acceptance/util_test.go#L118)):*
> ```Go
> 	prefix += getRandomName()
> 
> 	if !prefixRE.MatchString(prefix) {
> ```

i think you can do this before the random name stuff

also something something collisions here are gonna suck

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530)*

**Comment by tschottdorf** [comment]
Review status: 1 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[acceptance/allocator_test.go, line 322 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLSaA8je-9Meo_R0Gyg:-KLSuEDLkt-x9E_B9WSG:630910404) ([raw file](https://github.com/cockroachdb/cockroach/blob/f642921af5d3aeea4c8f4a42ffe61020b1e37b0a/acceptance/allocator_test.go#L322)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> I guess the generated names aren't *that* short. Still, I think a bit more verbosity would be helpful.
</details>
`uprep1to3s` sounds ok to me. If you're not worried about the length, that's fine.

---

*[acceptance/allocator_test.go, line 334 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLSeQjh57Gm5vVfSb0S:-KLSuILPJAY83rnydM5U:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/29da7757d21dc99445b06dfda21c6dc38f08848e/acceptance/allocator_test.go#L334)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary>
> maybe `rebal3to5s`?
</details>
Done.

---

*[acceptance/util_test.go, line 118 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLSozXN-nf1O2iQ3T_O:-KLT7UjBcdVUDnR6spDU:-1433499187) ([raw file](https://github.com/cockroachdb/cockroach/blob/29da7757d21dc99445b06dfda21c6dc38f08848e/acceptance/util_test.go#L118)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> i think you can do this before the random name stuff
> 
> also something something collisions here are gonna suck
</details>
I think this is mostly an assertion, so if it does fail, I'd rather have it print out the actual thing that it thinks is bad (and I do want to check the thing that terraform will see).

Collisions here are going to be fine (now).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[acceptance/namesgenerator.go, line 16 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLTM1vScoitI6oT1XbX:-KLTM1vScoitI6oT1XbY:1083729535) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a3a72524dba424f517df1bea2de7cf77fc00ef/acceptance/namesgenerator.go#L16)):*
> ```Go
> //
> // Author: Docker, Inc.
> ```

can you like to the source file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530)*

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[acceptance/util_test.go, line 118 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLWtlZpgnSsQZgfQVWx:-KLWtlZpgnSsQZgfQVWy:-1237087924) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a3a72524dba424f517df1bea2de7cf77fc00ef/acceptance/util_test.go#L118)):*
> ```Go
> 	prefix += getRandomName()
> 
> 	// Rudimentary collision control.
> ```

We don't purge `.tfstate` files after each run finishes, so in a test environment, we have to be careful to ensure that we clean the test directory regularly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-:-KLWu-t5HBB1y5qUKdFq:1417088721)*

**Comment by tschottdorf** [comment]
Review status: 1 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[acceptance/namesgenerator.go, line 16 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530#-KLTM1vScoitI6oT1XbX:-KLXJeH0FhiGj7-AJwg1:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/71a3a72524dba424f517df1bea2de7cf77fc00ef/acceptance/namesgenerator.go#L16)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> can you like to the source file?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7530)*

**Pull request merged**
