### PR TITLE
release-21.1: kvcoord: fix rangefeed retries on transport errors

### LINKED ISSUE #66636: changefeedccl: Rangefeeds might fail due to stale range cache
Customer observed changefeeds failing after some of the nodes were
decomissioned

```
ERROR: failed to connect to n4 at 172.31.91.238:26257: initial connection heartbeat failed: rpc error: code = PermissionDenied desc = n4 was permanently removed from the cluster at 2021-05-27 21:08:12.282567682 +0000 U…
```

In addition, error message
```
return args.Timestamp, newSendError(
				fmt.Sprintf("sending to all %d replicas failed", len(replicas)))
```

The hypothesis is that we might not be handling decomissioned nodes correctly.  In particular, perhaps we need to handle `InitialHeartbeatFailed` error in addition to the errors we already handle in `partialRangeFeed` 

1. We need to write tests around decomissioned nodes
2. We need to improve above error message in dist_sender_rangefeed -- we should print all replicas.
3. We need to handle decomissioned nodes

### PR DESCRIPTION
**Pull request by erikgrinaker**
Backport 2/2 commits from #66910.

Also pulls in gomock additions from #63616 and #65029, as well as `pkg/cmd/import-tools/stub.go` from #62560 to get around a `testrace` CI failure for that package (`build constraints exclude all Go files`).

/cc @cockroachdb/release

---

### rangecache: consider FailedPrecondition a retryable error

In #66199, the gRPC error `FailedPrecondition` (returned when contacting
a decommissioned node) was incorrectly considered a permanent error
during range descriptor lookups, via `IsRangeLookupErrorRetryable()`.
These lookups are all trying to reach a meta-range (addressed by key),
so when encountering a decommissioned node they should evict the cache
token and retry the lookup.

This patch reverses that change, making only authentication errors
permanent (i.e. when the local node is decommissioned or otherwise not
part of the cluster).

Release note: None

### kvcoord: fix rangefeed retries on transport errors

`DistSender.RangeFeed()` was meant to retry transport errors after
refreshing the range descriptor (invalidating the cached entry).
However, due to an incorrect error type check (`*sendError` vs
`sendError`), these errors failed the range feed without invalidating
the cached range descriptor.

This was particularly severe in cases where a large number of nodes had
been decommissioned, where some stale range descriptors on some nodes
contained only decommissioned nodes. Since change feeds set up range
feeds across many nodes and ranges in the cluster, they are likely to
encounter these decommissioned nodes and return an error -- and since
the descriptor cache wasn't invalidated they would keep erroring until
the nodes were restarted such that the caches were flushed (often
requiring a full cluster restart).

Resolves #66636, touches #66586.

Release note (bug fix): Change feeds now properly invalidate cached
range descriptors and retry when encountering decommissioned nodes.

/cc @cockroachdb/kv

### CODE REVIEW

**Review by aliher1911 — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67013#-:-MdN_rZlCmbQAscvS1UF:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by erikgrinaker** [comment]
@rickystewart I just pulled in some of the gomock/Bazel stuff directly into this PR (from the PRs mentioned in the description), let me know if you'd like me to do this differently.

**Review by rickystewart — CHANGES_REQUESTED** [review]
Looks good (actually, I don't really care about how the Bazel stuff looks on `release-21.1` -- the Bazel build isn't actually used for anything).

Looks like you need to `make bazel-generate` though, the lint job is going to fail.

**Comment by erikgrinaker** [comment]
Thanks @rickystewart, updated the Bazel build manifests.

**Comment by shermanCRL** [comment]
Addresses https://github.com/cockroachdb/cockroach/issues/66586

**Pull request merged**
