### PR TITLE
ui: rationalize GC Bytes Age on the range status page 

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, we were interpreting this gc score as a duration in
nanos which made no sense. This patch displays it as a raw number and
separately as an average age per dead byte.

Release note: None

### CODE REVIEW

**Comment by andreimatei** [comment]
@tbg I'm pretty confused about whether displaying this score in the UI makes sense because I can't really come up with a coherent story about how this age is "aged" in the copy of the stats stored in the database (as opposed to the on-demand computation performed by the GC queue).
I'm failing to answer the question about who, if anybody, updates it during normal operation. We update it when there's commands applying on the range, I think, but what if there aren't?

I've run some experiments and I do see it updated sometimes, but not reliably. 
And more surprisingly, I've seen it once go from 0 to non-zero and then to 0 again (although GC didn't actually collect anything).
Do you know what the story is?

**Comment by tbg** [comment]
^- I just sent PR #38287 to make sure you see a "recent" age in the range ui page.

I'm not aware of any reason why it would reset to zero. It shouldn't ever decrease unless there's been GC (or you're somehow seeing a stats object that's aged to less than a previous one).

**Review by tbg — CHANGES_REQUESTED** [review]
Post screenshot plz

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-:-LhizPBqDZWSjsXKRvcF:b-a36yyp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-Lhiz9e38dImvYCbTMAt:-Lhiz9e38dImvYCbTMAu:b-dgkuuk) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6f6ee557db84582dc0bd15b313dbc430889243/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L82)):*
> ```XML
>   { variable: "mvccLastUpdate", display: "MVCC Last Update", compareToLeader: true },
>   { variable: "mvccIntentAge", display: "MVCC Intent Age", compareToLeader: true },
>   { variable: "GCBytesAge", display: "GC Bytes Age (score)", compareToLeader: false},
> ```

Why `false`? Ditto below

If the info comes from the range, they should match (if the log position also matches, but that's the assumption for all the `true`s above). Or at least that would be my expectation.

**Review by andreimatei — COMMENTED** [review]
See the two new rows towards the bottom




> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-:-Lhkogos14GfXlN9e26l:b5kh8ud)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 82 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-Lhiz9e38dImvYCbTMAt:-Lhkoco75MtijvUb2ClO:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6f6ee557db84582dc0bd15b313dbc430889243/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L82)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Why `false`? Ditto below

If the info comes from the range, they should match (if the log position also matches, but that's the assumption for all the `true`s above). Or at least that would be my expectation.
</blockquote></details>

done

**Review by tbg — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38283)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 509 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-Lhl0d510uZR-yG1LpWt:-Lhl0d52DbQMlHIEQTDi:b-goihko) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e6f6ee557db84582dc0bd15b313dbc430889243/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L509)):*
> ```XML
>         mvccSystemBytesCount: this.contentMVCC(FixLong(mvcc.sys_bytes), FixLong(mvcc.sys_count)),
>         rangeMaxBytes: this.contentBytes(FixLong(info.state.range_max_bytes)),
>         mvccIntentAge: this.contentDuration(FixLong(mvcc.intent_age)),
> ```

btw this has similar semantics, not sure if you wanna pull on this thread too but if so now's the time to do it

**Review by andreimatei — COMMENTED** [review]
threw in the intents age too



> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-:-LhqXgQy3X7PwM8Rz-6E:b-h3l8s5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by tbg — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38283)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-LhqcZck0YwxQcKmz54Q:-LhqcZck0YwxQcKmz54R:b-2a343p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d175a6ba2c69eb4bcec9a87f0e09d9118a18a91/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L84)):*
> ```XML
>   { variable: "GCAvgAge", display: "Dead Value average age", compareToLeader: true},
>   { variable: "NumIntents", display: "Intents", compareToLeader: true},
>   { variable: "IntentAvgAge", display: "Intent Average Age", compareToLeader: true},
> ```

Nit: for bytes age you first show the number, then the average. Settle for one order and stick to it.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-:-Lhqguje1cpzOal4wtue:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/ui/src/views/reports/containers/range/rangeTable.tsx, line 84 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-LhqcZck0YwxQcKmz54Q:-Lhqgu7S781k-_c4BC5M:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1d175a6ba2c69eb4bcec9a87f0e09d9118a18a91/pkg/ui/src/views/reports/containers/range/rangeTable.tsx#L84)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Nit: for bytes age you first show the number, then the average. Settle for one order and stick to it.
</blockquote></details>

done

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-:-LiEv13IDziuO6J2IEpu:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Review by andreimatei — COMMENTED** [review]
the bors build looks successful, don't know why it's complaining

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38283#-:-LiKAmNGEFaVCPryDx5B:b-hcivvc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Pull request merged**
