### PR TITLE
sql: replace Filter from PostProcessSpec with a Filterer processor

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: add Filterer processor

This change adds a Filterer processor and switches planning code to
use that instead of PostProcessSpec.Filter (which will be removed in a
subsequent commit).

This makes plan diagrams easier to understand and makes it possible to
collect and present statistics separately for the filtering stage.

Note that the initial motivation for having the filter in the
PostProcessSpec was for efficiency, but that is no longer a big
concern thanks to the RowSource refactoring and vectorized execution.

Release note: None

#### sql: remove Filter from PostProcessSpec

Release notes: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Wow, this is the best news ever!

**Comment by RaduBerinde** [comment]
I'm just atoning for my sins haha

**Review by jordanlewis — COMMENTED** [review]
:lgtm_strong: hopefully Yahor can take a look next week too, thank you for doing this!

> Reviewed 23 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-:-MNHKCzP1DkQ5sfLwIqk:b-2buog2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors.proto, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNHHIB74vWUhj1ewjDQ:-MNHHIB74vWUhj1ewjDR:by8nod4) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff96265b99a0836da9686c99806b68f880b5dcf/pkg/sql/execinfrapb/processors.proto#L90)):*
> ```protobuf
>   optional NoopCoreSpec noop = 1;
>   optional TableReaderSpec tableReader = 2;
>   optional FiltererSpec filterer = 34;
> ```

Why not at the bottom after 33?
___
*[pkg/sql/rowexec/BUILD.bazel, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNHJcFb7MA1tL2_YY8Q:-MNHJcFb7MA1tL2_YY8R:bsu0zoc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a42042b425b427ba4156395f637cc71f56a625db/pkg/sql/rowexec/BUILD.bazel#L12)):*
> ```Starlark
>         "countrows.go",
>         "distinct.go",
>         "filterer.go",
> ```

I think these are in the wrong commit, maybe just squash the two?
___
*[pkg/sql/rowexec/filterer.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNHJ2Uy4tfKGPuOkpZc:-MNHJ2Uy4tfKGPuOkpZd:b-4jb18e) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff96265b99a0836da9686c99806b68f880b5dcf/pkg/sql/rowexec/filterer.go#L111)):*
> ```Go
> 		}
> 		if passes {
> 			if outRow := f.ProcessRowHelper(row); outRow != nil {
> ```

hmm, should we add a limiter and renderer too? :)

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57138)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/execinfrapb/processors.proto, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNHHIB74vWUhj1ewjDQ:-MNM3h8yCaGLGFCp6BD8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff96265b99a0836da9686c99806b68f880b5dcf/pkg/sql/execinfrapb/processors.proto#L90)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Why not at the bottom after 33?
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/BUILD.bazel, line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNHJcFb7MA1tL2_YY8Q:-MNM3hgx1S8Il8tti_zm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a42042b425b427ba4156395f637cc71f56a625db/pkg/sql/rowexec/BUILD.bazel#L12)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I think these are in the wrong commit, maybe just squash the two?
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/filterer.go, line 111 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNHJ2Uy4tfKGPuOkpZc:-MNM3ixB8NacNfc3Putp:b79z2fv) ([raw file](https://github.com/cockroachdb/cockroach/blob/eff96265b99a0836da9686c99806b68f880b5dcf/pkg/sql/rowexec/filterer.go#L111)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

hmm, should we add a limiter and renderer too? :)
</blockquote></details>

Not at this time :)

**Review by yuzefovich — COMMENTED** [review]
I agree, very nice cleanup! I have some nits and a question.

> Reviewed 1 of 21 files at r2, 22 of 22 files at r3, 20 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-:-MNP3bdl83xu4SP625up:b-o9y2wl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 418 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNP2IWDAr9sK6KOcwhZ:-MNP2IWDAr9sK6KOcwh_:bk48tj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ef0178501e512ec5cacef356e1bce99ac44096/pkg/sql/colexec/colbuilder/execplan.go#L418)):*
> ```Go
> 		)
> 	} else if post.Limit != 0 && post.Limit < math.MaxUint64-post.Offset {
> 		// There is a limit specified with no post-process filter, so we know
> ```

nit: the comment needs an update.
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1245 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNP2NuiB-MxA66RLPyh:-MNP2NuiB-MxA66RLPyi:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ef0178501e512ec5cacef356e1bce99ac44096/pkg/sql/colexec/colbuilder/execplan.go#L1245)):*
> ```Go
> 
> // planAndMaybeWrapFilter plans a filter. If the filter is unsupported, it is
> // planned as a wrapped noop processor with the filter as a post-processing
> ```

ditto
___
*[pkg/sql/execinfrapb/processors_base.proto, line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNP32SL2LZT2UmTpalX:-MNP32SL2LZT2UmTpalY:b9odhth) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ef0178501e512ec5cacef356e1bce99ac44096/pkg/sql/execinfrapb/processors_base.proto#L27)):*
> ```protobuf
> 
> // PostProcessSpec describes the processing required to obtain the output
> // (filtering, projection). It operates on the internal schema of the processor
> ```

"filtering"
___
*[pkg/sql/rowexec/filterer.go, line 1 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNP0mAP7nTq2lGuvLFA:-MNP0mAQ7Wnj5CXuIrPX:b-yelmx3) ([raw file](https://github.com/cockroachdb/cockroach/blob/419095ee627ea749c88a485af2c50e44c326494d/pkg/sql/rowexec/filterer.go#L1)):*
> ```Go
> // Copyright 2018 The Cockroach Authors.
> ```

nit: `s/2018/2020/`.
___
*[pkg/sql/rowexec/filterer.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNP0zWZ9Dn9aGopTsFM:-MNP0zW_4-zTCmwFt7FB:b-l166wc) ([raw file](https://github.com/cockroachdb/cockroach/blob/419095ee627ea749c88a485af2c50e44c326494d/pkg/sql/rowexec/filterer.go#L62)):*
> ```Go
> 
> 	// Hydrate all types used in the processor.
> 	resolver := flowCtx.TypeResolverFactory.NewTypeResolver(f.EvalCtx.Txn)
> ```

I think this hydration is redundant because we should be doing it in `f.Init` too. Or is it necessary because we're initializing the expr helper with a sema ctx below?
___
*[pkg/sql/rowexec/filterer.go, line 125 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNP23zr2Sy8dS0Suwnf:-MNP23zr2Sy8dS0Suwng:bg2oi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/419095ee627ea749c88a485af2c50e44c326494d/pkg/sql/rowexec/filterer.go#L125)):*
> ```Go
> }
> 
> // execStatsForTrace outputs the collected distinct stats to the trace. Will
> ```

nit: "distinct".
___
*[pkg/sql/rowexec/noop.go, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNP1z5-0mSLWkzwNo9P:-MNP1z5-0mSLWkzwNo9Q:bg2oi8) ([raw file](https://github.com/cockroachdb/cockroach/blob/419095ee627ea749c88a485af2c50e44c326494d/pkg/sql/rowexec/noop.go#L101)):*
> ```Go
> }
> 
> // execStatsForTrace outputs the collected distinct stats to the trace. Will
> ```

nit: "distinct".

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57138)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/sql/colexec/colbuilder/execplan.go, line 1245 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNP2NuiB-MxA66RLPyh:-MNPoNtpDA2N-N8rzV2J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ef0178501e512ec5cacef356e1bce99ac44096/pkg/sql/colexec/colbuilder/execplan.go#L1245)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[pkg/sql/execinfrapb/processors_base.proto, line 27 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNP32SL2LZT2UmTpalX:-MNPoTo65PXYzIqZ1AtN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/40ef0178501e512ec5cacef356e1bce99ac44096/pkg/sql/execinfrapb/processors_base.proto#L27)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

"filtering"
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/filterer.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-MNP0zWZ9Dn9aGopTsFM:-MNPpjyR5YE_X_S8IPA3:byj2j7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/419095ee627ea749c88a485af2c50e44c326494d/pkg/sql/rowexec/filterer.go#L62)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think this hydration is redundant because we should be doing it in `f.Init` too. Or is it necessary because we're initializing the expr helper with a sema ctx below?
</blockquote></details>

You're right, fixed by storing semaCtx in the processor, which @jordanlewis is also doing in another PR for allocation-saving purposes :)

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 25 of 25 files at r5, 5 of 5 files at r6, 20 of 20 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57138#-:-MNPyK93C8p-AUOJsWC4:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Pull request merged**
