### PR TITLE
changefeedccl: various tests

### PR DESCRIPTION
**Pull request by danhhz**
See individual commits for details

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27962#-:-LIWsuJg1SGwx48ao0XU:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 322 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27962#-LIWsEmT-lQMY5NurhuU:-LIWsEmU9hTGxFoF6OIO:bg7szrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0360a0f44b938a7170b523e64647726fee37214/pkg/ccl/changefeedccl/changefeed_test.go#L322)):*
> ```Go
> 	}
> 
> 	// Watching system.jobs would create a cycle, since the resolved timestamp
> ```

Maybe also test a time series table.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 317 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27962#-LIWsYX17dRb0vLDoyRK:-LIWsYX17dRb0vLDoyRL:bjirpm0) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b9cec3744ad5203226fcdf5d380e8021eff4861/pkg/ccl/changefeedccl/changefeed_test.go#L317)):*
> ```Go
> 	sqlDB.Exec(t, `CREATE DATABASE d`)
> 	sqlDB.Exec(t, `CREATE TABLE cc (
> 		a INT, b INT AS (a + 1) STORED, c INT AS (a + 2) STORED, PRIMARY KEY (b, a)
> ```

What if the column is not stored?

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27962)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 322 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27962#-LIWsEmT-lQMY5NurhuU:-LIfoCxVDqCzJ3qCNdLS:b-a55qpc) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0360a0f44b938a7170b523e64647726fee37214/pkg/ccl/changefeedccl/changefeed_test.go#L322)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Maybe also test a time series table.
</blockquote></details>

Hmm, can you elaborate? The time series data is stored outside the table data.
___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 317 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/27962#-LIWsYX17dRb0vLDoyRK:-LIfn6YtAX7OVOMXQwvd:bhns8o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b9cec3744ad5203226fcdf5d380e8021eff4861/pkg/ccl/changefeedccl/changefeed_test.go#L317)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

What if the column is not stored?
</blockquote></details>

We only support STORED ones at the moment. Added A TODO

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27962)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 322 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27962#-LIWsEmT-lQMY5NurhuU:-LIftjX78jvE86zHgTk4:ba5wbpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0360a0f44b938a7170b523e64647726fee37214/pkg/ccl/changefeedccl/changefeed_test.go#L322)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Hmm, can you elaborate? The time series data is stored outside the table data.
</blockquote></details>

Yeah, I'd just test that we can't create a changfeed on one of them either.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27962)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/ccl/changefeedccl/changefeed_test.go, line 322 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/27962#-LIWsEmT-lQMY5NurhuU:-LIfxNal-S7kL55MA4HM:b-45hi68) ([raw file](https://github.com/cockroachdb/cockroach/blob/f0360a0f44b938a7170b523e64647726fee37214/pkg/ccl/changefeedccl/changefeed_test.go#L322)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Yeah, I'd just test that we can't create a changfeed on one of them either.
</blockquote></details>

Sorry, what I meant was I don't think our timeseries data is addressable via any sort of table name

**Review by nvb — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27962)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by danhhz** [comment]
Thanks for the review!

bors r=nvanbenschoten

**Pull request merged**
