### PR TITLE
invertedexpr: add functions to convert geoindex.{UnionKeySpans, RPKey…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…Expr}

to SpanExpressionProto

Release note: None

### CODE REVIEW

**Review by rytaft — APPROVED** [review]
:lgtm: but do we eventually want the APIs to return a `SpanExpressionProto` directly? Needing to perform this conversion for every input row to a geo lookup join seems like it could add unnecessary overhead. If the main concern is the dependency on sqlbase for `sqlbase.EncodeTableKey`, we could always pass in the encode function as a parameter to the APIs or use an interface....

Either way, this definitely works for now as a way to unblock the optimizer work, but could be worth adding some TODOs somewhere...

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49603#-:-M8Mu3NZ6tqG1fetMfd_:b-gxjzdl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[pkg/sql/opt/invertedexpr/geo_expression.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49603#-M8Mqt2cAW6t6vlyjAzh:-M8Mqt2d3JN5H4sChFrI:b-ufz2ni) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1481493693d238f5a13bd938d0a139909a26bd/pkg/sql/opt/invertedexpr/geo_expression.go#L33)):*
> ```Go
> 	encoded, err := sqlbase.EncodeTableKey(nil, &dint, encoding.Ascending)
> 	if err != nil {
> 		panic(fmt.Sprintf("bug: can't encode %d", k))
> ```

use `panic(errors.AssertionFailedf(...))` for these kind of errors. Probably also worth printing the original error as part of the error message.

**Review by sumeerbhola — COMMENTED** [review]
TFTR!

> do we eventually want the APIs to return a SpanExpressionProto directly? Needing to perform this conversion for every input row to a geo lookup join seems like it could add unnecessary overhead. If the main concern is the dependency on sqlbase for sqlbase.EncodeTableKey, we could always pass in the encode function as a parameter to the APIs or use an interface....

I'm conflicted about the right approach. The conversion does seem wasteful (though I would be surprised if it showed up in end-to-end query cpu profiles). Having the `geo` specific expressions with `uint64` keys is nice in some ways since they directly correspond to cell ids. And the expression types are quite simple and efficient since they are effectively just slices (due to the reverse-polish notation). From a layering perspective, it seems to me that the `geoindex` package should be depended on by the optimizer but not the other way around, so we would need to move `SpanExpressionProto` out of the optimizer if we wanted `geoindex` to produce these protos -- any thoughts on where we would put it?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49603#-:-M8NHbLT1NmLmYmETaZO:bi3z73a)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49603)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/invertedexpr/geo_expression.go, line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/49603#-M8Mqt2cAW6t6vlyjAzh:-M8NLYyL6Gvr5syf-2KM:b-hyg0xd) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d1481493693d238f5a13bd938d0a139909a26bd/pkg/sql/opt/invertedexpr/geo_expression.go#L33)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

use `panic(errors.AssertionFailedf(...))` for these kind of errors. Probably also worth printing the original error as part of the error message.
</blockquote></details>

I switched to `errors.NewAssertionErrorWithWrappedErrf`

**Review by rytaft — APPROVED** [review]
I agree that `geoindex` should probably not depend on any packages in the optimizer, but I'm not sure of a better place to put `SpanExpressionProto`. Would be good to get the opinion of some other people... maybe @raduberinde has an idea?

One option is to just move `invertedexpr` out of `opt`...

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49603#-:-M8NLnhU-fJo5wCCsAfX:b5nkj69)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by andy-kimball** [comment]
Looking at the code, there's `RPExprElement`, `SpanExpressionProto`, and `SpanExpression`. This seems like at least 1 too many representations: I could see one meant to be used during planning/analysis and one highly optimized for execution. How come all 3 are needed?

**Review by sumeerbhola — COMMENTED** [review]
> One option is to just move invertedexpr out of opt...

Any thoughts on where we would put it?
Meanwhile I've added a TODO `TODO(sumeer): change geoindex to produce SpanExpressionProtos directly.` and will go ahead and merge this PR to unblock the optimizer work.

> Looking at the code, there's RPExprElement, SpanExpressionProto, and SpanExpression. This seems like at least 1 too many representations: I could see one meant to be used during planning/analysis and one highly optimized for execution. How come all 3 are needed?

There will be streamlining after we have things working end-to-end. The `SpanExpressionProto` and `SpanExpression` difference is because of the interface `InvertedExpression` that is meant to help with optimizer costing -- there is a TODO above the declaration of `SpanExpression` to revisit exactly this issue later.
`RPExprElement` and `RPExpr` are what `geoindex` started with -- these expressions use geospatial cellids -- they don't care about inverted indexes or their encoding. This is the duplication that Becca raised in this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49603#-:-M8Q1nT71xvmYohE1lNV:b-uztlrt)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — APPROVED** [review]
> Any thoughts on where we would put it?

`invertedexpr` could be just its own package under `sql`. Or we could move it under something like `sql/sem`. Or even put the proto stuff in `sql/execinfrapb` and leave the rest in `opt/invertedexpr`. Someone who has a better idea of the whole landscape of sql packages will probably have a stronger opinion here....

> ... will go ahead and merge this PR to unblock the optimizer work

sounds good.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49603#-:-M8QFxGh-ez3sOkfoc7Q:bqps6fn)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
