### PR TITLE
opt: push limit through index join

### PR DESCRIPTION
**Pull request by RaduBerinde**
Pushing limit through index joins. This is important for cases like
```
SELECT * FROM t ORDER BY w LIMIT 5
```
where it's much better to index-join 5 rows than to read the entire
table and sort.

Unfortunately this requires more acrobatics during exec build (we have
to move the limit above the indexJoinNode). This is the reason why I
haven't yet implemented the same rule for Offset; I'm hoping that case
is less important and can wait until we have a better lookup-join
execution path.

Release note: None

@rytaft - I realize this conflicts heavily with your outstanding PRs, I plan to wait for them to merge and rebase my changes.

### CODE REVIEW

**Comment by justinj** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 550 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LEjOepb32LNXaMG7s-e:-LEjOepb32LNXaMG7s-f:bbo3y2d) ([raw file](https://github.com/cockroachdb/cockroach/blob/84602811cd620e27899de900dc8d58347d11a4c8/pkg/sql/opt/exec/execbuilder/relational_builder.go#L550)):*
> ```Go
> func (b *Builder) buildLookupJoin(ev memo.ExprView) (execPlan, error) {
> 	var err error
> 	// If lookup join child is a limit and/sort operator then flip the order so
> ```

`and/or`?

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LEjOix56R8WQuNMoepz:-LEjOix56R8WQuNMoeq-:b-95h8nz) ([raw file](https://github.com/cockroachdb/cockroach/blob/84602811cd620e27899de900dc8d58347d11a4c8/pkg/sql/opt/exec/execbuilder/relational_builder.go#L564)):*
> ```Go
> 		child = child.Child(0)
> 	}
> 	if child.Operator() == opt.SortOp {
> ```

If both operators are present, will the limit always be on top of the sort in this situation?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-:-LEjPjsx0TBRbEOyH6wz:bnfp4nl)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LEjOix56R8WQuNMoepz:-LEjVu3jB0dVrGeQCzIR:b8zewp1) ([raw file](https://github.com/cockroachdb/cockroach/blob/84602811cd620e27899de900dc8d58347d11a4c8/pkg/sql/opt/exec/execbuilder/relational_builder.go#L564)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is a good question. In practice, I haven't seen the other ordering. If we have a limit under a sort, it can always be pushed down into the index scan. Also, we consider the sort above the index-join first, which usually means that we would choose that plan.

That said, this is all pretty fragile. We could have more complicated trees. For example:
```
query TTTTT
EXPLAIN (VERBOSE) SELECT k, w FROM (SELECT * FROM t WHERE v >= 1 AND v <= 100 ORDER BY k LIMIT 10) ORDER BY v
----
render                          ·         ·          (k, w)     ·
 │                              render 0  k          ·          ·
 │                              render 1  w          ·          ·
 └── sort                       ·         ·          (k, v, w)  +v
      │                         order     +v         ·          ·
      └── limit                 ·         ·          (k, v, w)  +k
           │                    count     10         ·          ·
           └── sort             ·         ·          (k, v, w)  +k
                │               order     +k         ·          ·
                └── index-join  ·         ·          (k, v, w)  ·
                     ├── scan   ·         ·          (k, v)     ·
                     │          table     t@t_v_idx  ·          ·
                     │          spans     /1-/101    ·          ·
                     └── scan   ·         ·          (k, v, w)  ·
·                               table     t@primary  ·          ·
```
This plan could just as well have the sort/limit/sort under the index-join (especially if we improve the costing for sorts so that we prefer to sort fewer columns; today it's the same cost, but even that is subject to floating point issues).

The real fix is to migrate to a more general lookup-join path and remove this code. If we can't do that in time, we could throw "unsupported" errors from the execbuilder too, and fallback. We can also make BestExpr only accept a new candidate if it's better than the old by some epsilon; that way the first explored plan of equivalent cost will always be preferred, and we first explore sorts on top (CC @andy-kimball).
</blockquote></details>

I like the epsilon idea as short-term fix.

---

*[pkg/sql/opt/xform/explorer.go, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LEjdqAVDHA9GIHI0i-c:-LEjdqAVDHA9GIHI0i-d:b-ipie6b) ([raw file](https://github.com/cockroachdb/cockroach/blob/84602811cd620e27899de900dc8d58347d11a4c8/pkg/sql/opt/xform/explorer.go#L482)):*
> ```Go
> 	// Check if this is an index join. For index joins, the input key column IDs
> 	// are the table PK column IDs.
> 	if lookupJoinDef.Index == opt.PrimaryIndex {
> ```

Maybe factor this out into a `isIndexJoin` helper function? It would increase clarity as well as making it reusable.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-:-LEjeFZQ1f83UpZG08xh:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LEjOix56R8WQuNMoepz:-LEkXJ_D3E3GnHaE9mp1:bimc8wz) ([raw file](https://github.com/cockroachdb/cockroach/blob/84602811cd620e27899de900dc8d58347d11a4c8/pkg/sql/opt/exec/execbuilder/relational_builder.go#L564)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

I like the epsilon idea as short-term fix.
</blockquote></details>

Added in this PR (separate commit).

---

*[pkg/sql/opt/xform/explorer.go, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LEjdqAVDHA9GIHI0i-c:-LEkXMjC2Ra5cQjlOa2M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84602811cd620e27899de900dc8d58347d11a4c8/pkg/sql/opt/xform/explorer.go#L482)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Maybe factor this out into a `isIndexJoin` helper function? It would increase clarity as well as making it reusable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26597)*

**Comment by andy-kimball** [comment]
:lgtm:

---

Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/xform/explorer.go, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LEjdqAVDHA9GIHI0i-c:-LEuiI1A5VIXmVDcMnku:b-d9lnnu) ([raw file](https://github.com/cockroachdb/cockroach/blob/84602811cd620e27899de900dc8d58347d11a4c8/pkg/sql/opt/xform/explorer.go#L482)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In my PR WIP, I added this code to `private_defs.go`:
```
// IsIndexJoin is true if the lookup join is an index join, meaning that the
// input columns are from the same table as the lookup columns. In this special
// case, there is always a 1:1 relationship between input and output rows.
func (l *LookupJoinDef) IsIndexJoin(md *opt.Metadata) bool {
	// The input and index key column sets will be the same if this is an index
	// join, or always disjoint if not.
	ord := md.Table(l.Table).Index(l.Index).Column(0).Ordinal
	return md.TableColumn(l.Table, ord) == l.KeyCols[0]
}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-:-LEwOYPY8aG5xaSOI_te:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

---

*[pkg/sql/opt/xform/explorer.go, line 482 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LEjdqAVDHA9GIHI0i-c:-LEy6McNCZs7VloukYdh:b-e7ikgn) ([raw file](https://github.com/cockroachdb/cockroach/blob/84602811cd620e27899de900dc8d58347d11a4c8/pkg/sql/opt/xform/explorer.go#L482)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

In my PR WIP, I added this code to `private_defs.go`:
```
// IsIndexJoin is true if the lookup join is an index join, meaning that the
// input columns are from the same table as the lookup columns. In this special
// case, there is always a 1:1 relationship between input and output rows.
func (l *LookupJoinDef) IsIndexJoin(md *opt.Metadata) bool {
	// The input and index key column sets will be the same if this is an index
	// join, or always disjoint if not.
	ord := md.Table(l.Table).Index(l.Index).Column(0).Ordinal
	return md.TableColumn(l.Table, ord) == l.KeyCols[0]
}
```
</blockquote></details>

Cool, I added that in this PR as well.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26597)*

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 3 of 7 files at r1, 7 of 7 files at r2, 4 of 4 files at r3.
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale)

---

*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 600 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LF0T0bH8EfqMhCN-T3p:-LF0T0bH8EfqMhCN-T3q:bmuw91w) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f9ff5baa10fc916b2f4dadebbe05539ee71025/pkg/sql/opt/exec/execbuilder/testdata/select_index#L600)):*
> ```
>  WHERE message LIKE 'fetched:%'
> ----
> fetched: /test2/test2_k_key/'001' -> /...PK...
> ```

Maybe add a TODO here to explain why the results don't match the above comment

---

*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 1275 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LF0WgVP-RUJeIaTb54l:-LF0WgVP-RUJeIaTb54m:bbhuvvx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4b05221927cb1bd715ba8c6e96d6d2f0f8af2f8/pkg/sql/opt/exec/execbuilder/testdata/select_index#L1275)):*
> ```
> )
> 
> # This test verifies the hack in execbuilder to move the sort above the
> ```

Is this test no longer relevant?

---

*[pkg/sql/opt/xform/custom_funcs.go, line 304 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LF0Tfgy3WJEqoCBSC-m:-LF0Tfgy3WJEqoCBSC-n:b-4j19y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f9ff5baa10fc916b2f4dadebbe05539ee71025/pkg/sql/opt/xform/custom_funcs.go#L304)):*
> ```Go
> // contain all columns in an ordering.
> func (c *CustomFuncs) HasOrderingCols(input memo.GroupID, ordering memo.PrivateID) bool {
> 	outCols := c.e.mem.GroupProperties(input).Relational.OutputCols
> ```

can use the `xfunc.OutputCols` helper function

---

*[pkg/sql/opt/xform/custom_funcs.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LF0ToEI7ypAjnVOtS4X:-LF0ToEI7ypAjnVOtS4Y:bucwdfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f9ff5baa10fc916b2f4dadebbe05539ee71025/pkg/sql/opt/xform/custom_funcs.go#L305)):*
> ```Go
> func (c *CustomFuncs) HasOrderingCols(input memo.GroupID, ordering memo.PrivateID) bool {
> 	outCols := c.e.mem.GroupProperties(input).Relational.OutputCols
> 	ord := c.e.mem.LookupPrivate(ordering).(props.Ordering)
> ```

can use `xfunc.ExtractOrdering` helper

---

*[pkg/sql/opt/xform/testdata/rules/limit, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LF0Uubu-_OaYgZVdwe1:-LF0Uubu-_OaYgZVdwe2:bictuig) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f9ff5baa10fc916b2f4dadebbe05539ee71025/pkg/sql/opt/xform/testdata/rules/limit#L150)):*
> ```
> 
> opt
> SELECT * FROM kuv ORDER BY u LIMIT 5
> ```

Can you add another test case where the limit can't be pushed down due to insufficient ordering cols in the input index?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-:-LF0WpbK6OyAwOf-syUJ:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale)

---

*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 600 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LF0T0bH8EfqMhCN-T3p:-LF2S5ujBgh0dgLDcQGZ:bi2ab0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f9ff5baa10fc916b2f4dadebbe05539ee71025/pkg/sql/opt/exec/execbuilder/testdata/select_index#L600)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Maybe add a TODO here to explain why the results don't match the above comment
</blockquote></details>

This is "paired" with the explain above which does have a TODO

---

*[pkg/sql/opt/exec/execbuilder/testdata/select_index, line 1275 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LF0WgVP-RUJeIaTb54l:-LF2Rf86-oQjaFPilCxq:bm0psky) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4b05221927cb1bd715ba8c6e96d6d2f0f8af2f8/pkg/sql/opt/exec/execbuilder/testdata/select_index#L1275)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Is this test no longer relevant?
</blockquote></details>

With the epsilon change this is no longer reproducible (we'll always prefer the sort on top).

---

*[pkg/sql/opt/xform/custom_funcs.go, line 304 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LF0Tfgy3WJEqoCBSC-m:-LF2SgcCCQiQkCpC3Oz8:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f9ff5baa10fc916b2f4dadebbe05539ee71025/pkg/sql/opt/xform/custom_funcs.go#L304)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

can use the `xfunc.OutputCols` helper function
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/custom_funcs.go, line 305 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LF0ToEI7ypAjnVOtS4X:-LF2Sh7S4siyraDshD2W:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f9ff5baa10fc916b2f4dadebbe05539ee71025/pkg/sql/opt/xform/custom_funcs.go#L305)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

can use `xfunc.ExtractOrdering` helper
</blockquote></details>

Done.

---

*[pkg/sql/opt/xform/testdata/rules/limit, line 150 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26597#-LF0Uubu-_OaYgZVdwe1:-LF2SkIH185NXt9gpv1Z:bqqbert) ([raw file](https://github.com/cockroachdb/cockroach/blob/45f9ff5baa10fc916b2f4dadebbe05539ee71025/pkg/sql/opt/xform/testdata/rules/limit#L150)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Can you add another test case where the limit can't be pushed down due to insufficient ordering cols in the input index?
</blockquote></details>

Great idea, done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26597)*

**Pull request merged**
