### PR TITLE
colexec: make sure that joiners output only the needed columns

### LINKED ISSUE #40732: sql: vec result difference: row count mismatch
```
CREATE TABLE IF NOT EXISTS tab_orig AS
    SELECT
        g::INT8 AS _int8,
        g::FLOAT8 AS _float8,
        '2001-01-01'::DATE + g AS _date,
        g % 2 = 1 AS _bool,
        g::DECIMAL AS _decimal,
        g::STRING AS _string,
        g::STRING::BYTES AS _bytes
    FROM
        generate_series(1, 5) AS g;

INSERT INTO tab_orig DEFAULT VALUES;
```

```
root@:26257/defaultdb> SELECT
        *
FROM
        (
                SELECT
                        tab_1541._int8 AS col_2976
                FROM
                        defaultdb.public.tab_orig AS tab_1538
                        JOIN defaultdb.public.tab_orig AS tab_1539
                                JOIN defaultdb.public.tab_orig AS tab_1540 ON (tab_1539._float8) = (tab_1540._float8)
                                JOIN defaultdb.public.tab_orig AS tab_1541 ON (tab_1540._int8) = (tab_1541._int8) ON
                                        (tab_1538._float8) = (tab_1540._float8),
                        defaultdb.public.tab_orig AS tab_1542
                WHERE
                        (tab_1542._bool > tab_1540._bool)
        )
ORDER BY
        col_2976;
  col_2976  
+----------+
         2  
         2  
         2  
         4  
         4  
         4  
(6 rows)

Time: 6.610212ms

root@:26257/defaultdb> set vectorize=experimental_on;

SET

Time: 530.166µs

root@:26257/defaultdb> SELECT
        *
FROM
        (
                SELECT
                        tab_1541._int8 AS col_2976
                FROM
                        defaultdb.public.tab_orig AS tab_1538
                        JOIN defaultdb.public.tab_orig AS tab_1539
                                JOIN defaultdb.public.tab_orig AS tab_1540 ON (tab_1539._float8) = (tab_1540._float8)
                                JOIN defaultdb.public.tab_orig AS tab_1541 ON (tab_1540._int8) = (tab_1541._int8) ON
                                        (tab_1538._float8) = (tab_1540._float8),
                        defaultdb.public.tab_orig AS tab_1542
                WHERE
                        (tab_1542._bool > tab_1540._bool)
        )
ORDER BY
        col_2976;
  col_2976  
+----------+
(0 rows)

```

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, the joiners would create an output batch with all
the input columns but would set the values only the requested
output columns. Now this is fixed, and both hash and merge joiners
output the batch only with the requested columns.

Additionally, this commit fixes a bug with ON expression planning
for joiners. Previously, the column types that the remapped ON
expression references were not remapped themselves.

Furthermore, the ON expression itself was modified in-place. This
is now fixed.

Also, post.Filter was handled incorrectly after a joiner if the
columns used by the filter were not a part of the projection. This
is now fixed.

Fixes: #40732.

Release justification: Category 3: Fixes for high-priority or
high-severity bugs in existing functionality.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
#40766 should go in first.

**Comment by yuzefovich** [comment]
Okay, it is now RFAL.

**Comment by yuzefovich** [comment]
Friendly ping.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40754#-:-Lp2y2vX5iXxH-Br9yM1:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/execplan.go, line 844 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40754#-Lp2xGW_4xNuf8r5v63Q:-Lp2xGW_4xNuf8r5v63R:b-7wzml3) ([raw file](https://github.com/cockroachdb/cockroach/blob/e408c17e5e9a5be2bcd29e4f3814ef8a3fada263/pkg/sql/colexec/execplan.go#L844)):*
> ```Go
> 	if p.indexVarMap == nil {
> 		// If p.indexVarMap is nil, then there is no remapping to do.
> 		return expr
> ```

Is it valid to return the argument or do we somehow need to make a copy? If we don't, maybe mention that in the method comment.

**Review by yuzefovich — COMMENTED** [review]
Thanks for the review!

bors r=asubiotto

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40754#-:-Lp40-AaCY7luvCf6RjI:b-k10nwi)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @jordanlewis)

___
*[pkg/sql/colexec/execplan.go, line 844 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40754#-Lp2xGW_4xNuf8r5v63Q:-Lp4-vWW8aZJGtT2qnZ-:b-kjbnlh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e408c17e5e9a5be2bcd29e4f3814ef8a3fada263/pkg/sql/colexec/execplan.go#L844)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is it valid to return the argument or do we somehow need to make a copy? If we don't, maybe mention that in the method comment.
</blockquote></details>

Updated the comment, thanks.

**Pull request merged**
