### PR TITLE
distsql: small fixes (debug logs, hash join encoding problem)

### PR DESCRIPTION
**Pull request by RaduBerinde**
See individual commits.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/12119)

### CODE REVIEW

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119#-:-KYOk1t08xlBRq1nf-Gn:bnfp4nl)*

**Comment by irfansharif** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/hashjoiner.go, line 245 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119#-KYOv-dP5sImk2X6FYL-:-KYOv-dP3EVWZN-L0ke0:by5frh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8675177a6cf88ea518e771646c7c75db1d6ed262/pkg/sql/distsql/hashjoiner.go#L245)):*
> ```Go
> 		// Note: we cannot compare VALUE encodings because they contain column IDs
> 		// which can vary.
> 		appendTo, err = row[colIdx].Encode(&h.datumAlloc, sqlbase.DatumEncoding_ASCENDING_KEY, appendTo)
> ```

wait I don't understand this.  if you look at what `Encode(...)` actually does when passed in `sqlbase.DatumEncoding_VALUE` [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/encoded_datum.go#L213-L214) it uses a default `encoding.NoColumnID` so the column ID doesn't really make a difference?

---

*[pkg/sql/distsql/hashjoiner.go, line 245 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119#-KYOwFqp0V1tmF2GfepD:-KYOwFqp73JpvywKc5x9:bczb5p7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8675177a6cf88ea518e771646c7c75db1d6ed262/pkg/sql/distsql/hashjoiner.go#L245)):*
> ```Go
> 		// Note: we cannot compare VALUE encodings because they contain column IDs
> 		// which can vary.
> 		appendTo, err = row[colIdx].Encode(&h.datumAlloc, sqlbase.DatumEncoding_ASCENDING_KEY, appendTo)
> ```

```
// TODO(irfansharif): Different rows may come with different encodings,
// e.g. if they come from different streams that were merged, in which
// case the encodings don't match (despite having the same underlying
// datums). We instead opt to always choose sqlbase.DatumEncoding_VALUE
// but we may want to check the first row for what encodings are already
// available.
```

this is from `distinct.go` and is applicable here as well, no?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/hashjoiner.go, line 245 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119#-KYOwFqp0V1tmF2GfepD:-KYP7m-S2awSurHYd8Yx:b-rzojkz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8675177a6cf88ea518e771646c7c75db1d6ed262/pkg/sql/distsql/hashjoiner.go#L245)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

```
// TODO(irfansharif): Different rows may come with different encodings,
// e.g. if they come from different streams that were merged, in which
// case the encodings don't match (despite having the same underlying
// datums). We instead opt to always choose sqlbase.DatumEncoding_VALUE
// but we may want to check the first row for what encodings are already
// available.
```

this is from `distinct.go` and is applicable here as well, no?
</blockquote></details>

Yeah. In the future, we can add a function that compares VALUE encodings ignoring any column difference (in most cases it would come down to just skipping the first byte or something like that).

---

*[pkg/sql/distsql/hashjoiner.go, line 245 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119#-KYOv-dP5sImk2X6FYL-:-KYP7tqo1WV7k2NR_cgL:b-e0b5kf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8675177a6cf88ea518e771646c7c75db1d6ed262/pkg/sql/distsql/hashjoiner.go#L245)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

wait I don't understand this.  if you look at what `Encode(...)` actually does when passed in `sqlbase.DatumEncoding_VALUE` [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/encoded_datum.go#L213-L214) it uses a default `encoding.NoColumnID` so the column ID doesn't really make a difference?
</blockquote></details>

You are assuming that this particular code always creates the encoding, but the whole point of `EncDatum` is that we could have the encoding given to us, either directly from what is stored in KV or from another host (we would return that [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/encoded_datum.go#L202)).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119)*

**Comment by irfansharif** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/hashjoiner.go, line 245 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119#-KYOv-dP5sImk2X6FYL-:-KYPBBre-UBwfnDJWuBx:b-w0yspi) ([raw file](https://github.com/cockroachdb/cockroach/blob/8675177a6cf88ea518e771646c7c75db1d6ed262/pkg/sql/distsql/hashjoiner.go#L245)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

You are assuming that this particular code always creates the encoding, but the whole point of `EncDatum` is that we could have the encoding given to us, either directly from what is stored in KV or from another host (we would return that [here](https://github.com/cockroachdb/cockroach/blob/master/pkg/sql/sqlbase/encoded_datum.go#L202)).
</blockquote></details>

got it.

---

*[pkg/sql/distsql/hashjoiner.go, line 245 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119#-KYOwFqp0V1tmF2GfepD:-KYPBqf6CVNWlAHnJssx:b-u7myg0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8675177a6cf88ea518e771646c7c75db1d6ed262/pkg/sql/distsql/hashjoiner.go#L245)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah. In the future, we can add a function that compares VALUE encodings ignoring any column difference (in most cases it would come down to just skipping the first byte or something like that).
</blockquote></details>

right, I think it's worth adding this as a TODO for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119#-:-KYPC4sL3pZFNQaqn-C_:bnfp4nl)*

**Comment by RaduBerinde** [comment]
Review status: 6 of 7 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/distsql/hashjoiner.go, line 245 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119#-KYOwFqp0V1tmF2GfepD:-KYPE39kEho9yslZKRJ_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8675177a6cf88ea518e771646c7c75db1d6ed262/pkg/sql/distsql/hashjoiner.go#L245)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary><blockquote>

right, I think it's worth adding this as a TODO for.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119)*

**Comment by irfansharif** [comment]
Reviewed 5 of 5 files at r1, 2 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/12119)*

**Pull request merged**
