### PR TITLE
ui: compute graph domains correctly for stacked graphs

### LINKED ISSUE #9414: ui: raft messages received graph broken/confusing
The "raft messages received" graph is either broken or confusing. The numbers are accurate, but much of the graph doesn't fit within the visible area.

screen shot 2016-09-15 at 5 07 23 pm

### PR DESCRIPTION
**Pull request by maxlang**
Fixes #9414 

cc @cockroachdb/stability

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9542)

### CODE REVIEW

**Comment by mrtracy** [comment]
:lgtm: with some suggestions

---

Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/app/components/graphs.tsx, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9542#-KSbWHBNHHP_rHuqfQRs:-KSbWHBNHHP_rHuqfQRt:bm12i05) ([raw file](https://github.com/cockroachdb/cockroach/blob/c65fc27109415c896bd63d6fcb12bd6f9ed9f44e/ui/app/components/graphs.tsx#L89)):*
> ```XML
>   // max/min respectively.
>   addStackedPoints(keyedValues: {key: number, value: number}[]) {
>     _.each(keyedValues, (v: {key: number, value: number}) => {
> ```

Can the type of `v` not be inferred here?

---

*[ui/app/components/graphs.tsx, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9542#-KSbVeuX-9PCLWFjt8j5:-KSbVeuYUWGt64h7BVS1:b-zg4153) ([raw file](https://github.com/cockroachdb/cockroach/blob/c65fc27109415c896bd63d6fcb12bd6f9ed9f44e/ui/app/components/graphs.tsx#L90)):*
> ```XML
>   addStackedPoints(keyedValues: {key: number, value: number}[]) {
>     _.each(keyedValues, (v: {key: number, value: number}) => {
>       this.stackedSum[v.key] = _.sum([this.stackedSum[v.key], v.value]);
> ```

This is just two values, you don't need to use sum, do you?  I would think just be `this.stackedSum[v.key] += v.value`

---

*[ui/app/components/graphs.tsx, line 93 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9542#-KSbWOj20-NREs5FNsm7:-KSbWOj20-NREs5FNsm8:b-bo4vyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c65fc27109415c896bd63d6fcb12bd6f9ed9f44e/ui/app/components/graphs.tsx#L93)):*
> ```XML
>     });
> 
>     this.min = _.min(_.values<number>(this.stackedSum));
> ```

Again, really surprised the type information is necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9542#-:-KSbX54WfkcVGOPNDa4K:b-c6twz6)*

**Comment by maxlang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/app/components/graphs.tsx, line 89 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9542#-KSbWHBNHHP_rHuqfQRs:-KSbY-A1m71GEMDtab2d:b-1kzpp0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c65fc27109415c896bd63d6fcb12bd6f9ed9f44e/ui/app/components/graphs.tsx#L89)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Can the type of `v` not be inferred here?
</details>
I can't really understand why, but it inferred the type of `v` as `{}` at first. Now it seems to work fine. Done.

---

*[ui/app/components/graphs.tsx, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9542#-KSbVeuX-9PCLWFjt8j5:-KSbYd3hvi1vwtBeLzA0:b1a02m7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c65fc27109415c896bd63d6fcb12bd6f9ed9f44e/ui/app/components/graphs.tsx#L90)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> This is just two values, you don't need to use sum, do you?  I would think just be `this.stackedSum[v.key] += v.value`
</details>
`_.sum` works with `undefined` whereas `+` does not. That said, I agree randomly using `_.sum` here feels a little awkward.

What are you thoughts on using more advanced `lodash` stuff? Eg this could just be a one liner:

```
    _.assignWith(this.stackedSum, keyedValues, (sum: number, keyedValue: {key: number, value: number}) => (sum || 0) + keyedValue.value);
```

---

*[ui/app/components/graphs.tsx, line 93 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9542#-KSbWOj20-NREs5FNsm7:-KSbrGFJ8BY8VMtd6jdc:btu4kqx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c65fc27109415c896bd63d6fcb12bd6f9ed9f44e/ui/app/components/graphs.tsx#L93)):*
<details><summary><i>Previously, mrtracy wrote…</i></summary>
> Again, really surprised the type information is necessary.
</details>
Yeah this is kind of weird.

In fact, if I rewrite it as 
```
  stackedSum: { [key: string]: number } = {};
...
    this.min = _.min(_.map(this.stackedSum, (v)=>v));
    this.max = _.max(_.map(this.stackedSum, (v)=>v));
```
it does work. `_.values` seems to be parameterized in all the lodash typings.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9542)*

**Comment by maxlang** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[ui/app/components/graphs.tsx, line 90 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9542#-KSbVeuX-9PCLWFjt8j5:-KSby6ksSyUSW4mBFcIj:bhlt9my) ([raw file](https://github.com/cockroachdb/cockroach/blob/c65fc27109415c896bd63d6fcb12bd6f9ed9f44e/ui/app/components/graphs.tsx#L90)):*
<details><summary><i>Previously, maxlang (Max Lang) wrote…</i></summary>
> `_.sum` works with `undefined` whereas `+` does not. That said, I agree randomly using `_.sum` here feels a little awkward.
> 
> What are you thoughts on using more advanced `lodash` stuff? Eg this could just be a one liner:
> 
> ```
>     _.assignWith(this.stackedSum, keyedValues, (sum: number, keyedValue: {key: number, value: number}) => (sum || 0) + keyedValue.value);
> ```
> 
> 
> 
</details>
Changed to just use a normal `undefined` guard to avoid people wondering about this in the future.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9542)*

**Comment by maxlang** [comment]
screen shot 2016-09-26 at 4 08 30 pm

**Comment by tschottdorf** [comment]
LGTM if @mrtracy is happy.

**Pull request merged**
