### PR TITLE
sql: rename columns in partial index predicates

### PR DESCRIPTION
**Pull request by mgartner**
This commit makes an `ALTER TABLE ... RENAME COLUMN ...` statment
replace the old column names in partial index predicates with the new
column name. For example:

    CREATE TABLE t (a INT, INDEX (a) WHERE a > 0)
    ALTER TABLE t RENAME COLUMN a TO b

The partial index predicate expression, `a > 0`, will now be replaced
with `b > 0`.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
cc @RichardJCai.

Marcus, I'm wondering if this is our chance to leap forward into a fresh new era where we stop storing column names in stringified exprs altogether, which is clearly a source of pain. One proposal is that we could store column ids instead. That would prevent issues like this. Richard was looking at changing some of this for view descriptors, but we're wary to do it because that requires a migration (since there are old view descriptors lying around that exist).

Index predicates are new and have never been stored before. Could now be the time that we set a better precedent? By now I might not mean this PR, but before 20.2. Just want to set the wheels turning in heads...

**Comment by RaduBerinde** [comment]
I think we'd still be storing them as strings as we don't have any other reliable serialization format, but we would use something like `@11` or some other syntax to refer to columns by name. This seems straightforward at a high level but there are likely a lot of details to sort out (e.g. we still want to be able to print them out with column names for the user's benefit).

I agree that given that this is a new field, it's a good time to explore this. Let's file an issue so we don't lose track of it and try to look at it for 20.2 (but like you say, we shouldn't block the partial index work on it).

**Comment by mgartner** [comment]
@RaduBerinde created an issue: https://github.com/cockroachdb/cockroach/issues/49766

**Comment by jordanlewis** [comment]
I'm in agreement that we can move forward with this without redoing the serialization. Thanks for filing the issue.

**Review by rytaft — APPROVED** [review]
Last commit :lgtm: 

> Reviewed 10 of 10 files at r1, 6 of 6 files at r2, 30 of 30 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49672#-:-M8p9Kom1vPNCFbF6XNi:b-wa82fk)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49672)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/schemaexpr/column.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49672#-M8zgVw-4WiImGnMEA2h:-M8zgVw0BGT1cYK_M75M:b-vqxwnk) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dcbf48a470fa2a1da82aa092c3c6c734ea5f801/pkg/sql/schemaexpr/column.go#L65)):*
> ```Go
> // RenameColumn replaces any occurrence of the column from in expr with to, and
> // returns a string representation of the new expression.
> func RenameColumn(expr string, from *tree.Name, to *tree.Name) (string, error) {
> ```

Why are we passing pointers to strings?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49672)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/schemaexpr/column.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49672#-M8zgVw-4WiImGnMEA2h:-M90XMD--PhyXF1Seuia:bs7hqtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dcbf48a470fa2a1da82aa092c3c6c734ea5f801/pkg/sql/schemaexpr/column.go#L65)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why are we passing pointers to strings?
</blockquote></details>

In `pkg/sql/rename_column.go` the `renameColumn` function takes `oldName, newName *tree.Name` as arguments, and I used the same types here. I can change this and deference `oldName` and `newName` when calling this function if that's preferred.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/schemaexpr/column.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49672#-M8zgVw-4WiImGnMEA2h:-M91b9sY6l8YfpKhar0Q:b9cmqmo) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dcbf48a470fa2a1da82aa092c3c6c734ea5f801/pkg/sql/schemaexpr/column.go#L65)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

In `pkg/sql/rename_column.go` the `renameColumn` function takes `oldName, newName *tree.Name` as arguments, and I used the same types here. I can change this and deference `oldName` and `newName` when calling this function if that's preferred.
</blockquote></details>

Yeah I would change it. I don't know why the existing code does that.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/49672)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @rytaft)

___
*[pkg/sql/schemaexpr/column.go, line 65 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/49672#-M8zgVw-4WiImGnMEA2h:-M9K8Am33ww4oOWSLp6r:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3dcbf48a470fa2a1da82aa092c3c6c734ea5f801/pkg/sql/schemaexpr/column.go#L65)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Yeah I would change it. I don't know why the existing code does that.
</blockquote></details>

Done.

**Pull request merged**
