### PR TITLE
geoindex,sql: use SRID bounds for a geometry inverted index

### PR DESCRIPTION
**Pull request by sumeerbhola**
Release note: None

### CODE REVIEW

**Review by otan — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @sumeerbhola)

___
*[pkg/geo/geoindex/s2_geometry_index.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51241#-MBp8o1q3RD0HdEsWoB3:-MBp8o1q3RD0HdEsWoB4:bg1e86j) ([raw file](https://github.com/cockroachdb/cockroach/blob/321d4fa165256add9ff089a1154db2aaf887dd13/pkg/geo/geoindex/s2_geometry_index.go#L71)):*
> ```Go
> 		S2Geometry: &S2GeometryConfig{
> 			// Arbitrary bounding box.
> 			MinX:     -10000,
> ```

given the numbers i've seen, i think we should use 10e7 and -10e7, heh.

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/51241)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geoindex/s2_geometry_index.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51241#-MBp8o1q3RD0HdEsWoB3:-MBsgD-C4sbAgfCGpIFW:b-yhxzbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/321d4fa165256add9ff089a1154db2aaf887dd13/pkg/geo/geoindex/s2_geometry_index.go#L71)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

given the numbers i've seen, i think we should use 10e7 and -10e7, heh.
</blockquote></details>

If the user has small coordinates, large bounds reduce fidelity of the index. Are you thinking there are earth projections for which our projections map will be incomplete, so the defaults will function ok?

btw, I'd rather not tweak these in this PR and cause all test output to change (including the EXPLAIN output from the logic tests).

**Comment by otan** [comment]
___
*[pkg/geo/geoindex/s2_geometry_index.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/51241#-MBp8o1q3RD0HdEsWoB3:-MBt0IlR3YA2Bp8gw2X5:b-d4irw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/321d4fa165256add9ff089a1154db2aaf887dd13/pkg/geo/geoindex/s2_geometry_index.go#L71)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

If the user has small coordinates, large bounds reduce fidelity of the index. Are you thinking there are earth projections for which our projections map will be incomplete, so the defaults will function ok?

btw, I'd rather not tweak these in this PR and cause all test output to change (including the EXPLAIN output from the logic tests).
</blockquote></details>

SG! feel free to merge.

**Comment by sumeerbhola** [comment]
TFTR!

**Pull request merged**
