### PR TITLE
sql/parser: parsing for interleaved tables/indexes

### PR DESCRIPTION
**Pull request by danhhz**
I ran doc generation locally and the SKIP DOC seems to work and keep this off
the diagrams.

For #2972.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7655)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655#-:-KM6WjFLYXvx-3s-RUm3:1417088721)*

**Comment by petermattis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[sql/parser/parse_test.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655#-KM6v9R5B--sRBPXbGVp:-KM6v9R67cAJJccJjD74:419269030) ([raw file](https://github.com/cockroachdb/cockroach/blob/834d7860230075cc1a2ad3ce9029b9d1581d2fa7/sql/parser/parse_test.go#L101)):*
> ```Go
> 		{`CREATE TABLE a (b INT, c TEXT, INDEX d (b, c))`},
> 		{`CREATE TABLE a (b INT, c TEXT, CONSTRAINT d UNIQUE (b, c))`},
> 		{`CREATE TABLE a (b INT, c TEXT, CONSTRAINT d UNIQUE (b, c) INTERLEAVE IN PARENT d (e, f))`},
> ```

When interleaving an index, I assume we're only going to allow interleaving the index in the table it is part of. So perhaps the parent name should be omitted in this case and the `CREATE INDEX` statement.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655)*

**Comment by petermattis** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parser/sql.y, line 1599 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655#-KM6vnFa96rW8qQOmxml:-KM6vnFa96rW8qQOmxmm:1165118016) ([raw file](https://github.com/cockroachdb/cockroach/blob/834d7860230075cc1a2ad3ce9029b9d1581d2fa7/sql/parser/sql.y#L1599)):*
> ```Yacc
> 
> index_def:
>   INDEX opt_name '(' index_params ')' opt_storing opt_interleave
> ```

Using `opt_interleave` here means that `opt_drop_behavior` also applies, but `CASCADE` is always the rule for indexes. I think you'll need different rules for index vs table interleave statements.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655)*

**Comment by paperstreet** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parser/parse_test.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655#-KM6v9R5B--sRBPXbGVp:-KM9xf-P1FSKIFigcLmB:-1409724019) ([raw file](https://github.com/cockroachdb/cockroach/blob/834d7860230075cc1a2ad3ce9029b9d1581d2fa7/sql/parser/parse_test.go#L101)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> When interleaving an index, I assume we're only going to allow interleaving the index in the table it is part of. So perhaps the parent name should be omitted in this case and the `CREATE INDEX` statement.
</details>
I don't see any reason not to allow interleaving an index for one table into the data for another. As far as I see, it doesn't complicate the implementation of interleaving and maybe it will be useful? It reduces an index join from hitting three ranges to two. 

---

*[sql/parser/sql.y, line 1599 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655#-KM6vnFa96rW8qQOmxml:-KMA0-A8OO0Dnj8VRyzt:1372400846) ([raw file](https://github.com/cockroachdb/cockroach/blob/834d7860230075cc1a2ad3ce9029b9d1581d2fa7/sql/parser/sql.y#L1599)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Using `opt_interleave` here means that `opt_drop_behavior` also applies, but `CASCADE` is always the rule for indexes. I think you'll need different rules for index vs table interleave statements.
</details>
If we allow interleaving an index into some other table as I suggest above, then I think the "CASCADE is always the rule" part doesn't apply.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/parser/parse_test.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655#-KM6v9R5B--sRBPXbGVp:-KMA2tHY6tX2MorS-SrX:-2053328431) ([raw file](https://github.com/cockroachdb/cockroach/blob/834d7860230075cc1a2ad3ce9029b9d1581d2fa7/sql/parser/parse_test.go#L101)):*
<details><summary><i>Previously, paperstreet (Daniel Harrison) wrote…</i></summary>
> I don't see any reason not to allow interleaving an index for one table into the data for another. As far as I see, it doesn't complicate the implementation of interleaving and maybe it will be useful? It reduces an index join from hitting three ranges to two. 
</details>
Ah, so this was intentional. It feels a bit odd. On the other hand, interleaving an index in the table it is associated with isn't terribly useful given that for any row in the table there will be only a single row in the index. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655#-:-KMA3TGmHhCHUE83DrxT:1417088721)*

**Comment by RaduBerinde** [comment]
*[sql/parser/parse_test.go, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655#-KM6v9R5B--sRBPXbGVp:-KMA3yF3c8hd_Iylcv34:-653012023) ([raw file](https://github.com/cockroachdb/cockroach/blob/834d7860230075cc1a2ad3ce9029b9d1581d2fa7/sql/parser/parse_test.go#L101)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Ah, so this was intentional. It feels a bit odd. On the other hand, interleaving an index in the table it is associated with isn't terribly useful given that for any row in the table there will be only a single row in the index. 
</details>
Yeah I don't see why you would ever interleave an index with that same table.

Interleaving with another table can be useful. Here's an example - we have a table of customers (`customerID` PK) and a table of orders (`orderID` PK, each order also includes the `customerID`). We could have a `(customerID, orderID, sum)` index on orders and interleave that into the customer table; this would speed up joining by `customerID` (e.g. for generating a report with customer names and how much each one spent).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7655)*

**Pull request merged**
