### PR TITLE
storage/engine: ignore sign-comparison warnings

### LINKED ISSUE #14429: storage: c++ warnings when compiling db.cc
using `cc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609`

```
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc: In function ‘bool SplitKey(rocksdb::Slice, rocksdb::Slice*, rocksdb::Slice*)’:
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc:248:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   if (ts_size >= buf.size()) {
               ^
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc: In member function ‘virtual bool {anonymous}::DBMergeOperator::FullMerge(const rocksdb::Slice&, co
nst rocksdb::Slice*, const std::deque<std::__cxx11::basic_string<char> >&, std::__cxx11::string*, rocksdb::Logger*) const’:
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc:782:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < operand_list.size(); i++) {
                       ^
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc: In member function ‘virtual bool {anonymous}::DBMergeOperator::PartialMergeMulti(const rocksdb::Sl
ice&, const std::deque<rocksdb::Slice>&, std::__cxx11::string*, rocksdb::Logger*) const’:
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc:802:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < operand_list.size(); i++) {
                       ^
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc: In member function ‘virtual void {anonymous}::DBLogger::Logv(const char*, __va_list_tag*)’:
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc:852:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     if ((result >= 0) && (result < sizeof(space))) {
                                  ^
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc: In member function ‘DBSSTable* DBEngine::GetSSTables(int*)’:
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc:1344:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < metadata.size(); i++) {
                     ^
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc:1354:65: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-alia
sing]
       tables[i].start_key.key = *reinterpret_cast<DBSlice*>(&str);
                                                                 ^
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc:1354:31: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-alia
sing]
       tables[i].start_key.key = *reinterpret_cast<DBSlice*>(&str);
                               ^
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc:1359:63: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-alia
sing]
       tables[i].end_key.key = *reinterpret_cast<DBSlice*>(&str);
                                                               ^
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc:1359:29: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-alia
sing]
       tables[i].end_key.key = *reinterpret_cast<DBSlice*>(&str);
                             ^
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc: In function ‘MVCCStatsResult MVCCComputeStatsInternal(rocksdb::Iterator*, DBKey, DBKey, int64_t)’:
/mnt/kena/go/src/github.com/cockroachdb/cockroach/pkg/storage/engine/db.cc:2230:30: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (meta.val_bytes() != value.size()) {
```

### PR DESCRIPTION
**Pull request by petermattis**
Fix strict-aliasing warning due to type-punning.

Fixes #14429

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14432)

### CODE REVIEW

**Comment by petermattis** [comment]
I could fix the `-Wsign-compare` warnings, but they are just annoying in my opinion. @knz Can you verify this fixes the compile for you.

**Comment by knz** [comment]
Build is successful, with no warnings remaining.

**Comment by petermattis** [comment]
> Build is successful, with no warnings remaining.

Great. Can I get an LGTM?

**Comment by knz** [comment]
LGTM, but perhaps you want to check with folks using clang / osx too

**Comment by petermattis** [comment]
> but perhaps you want to check with folks using clang / osx too

I'm using clang on OS X, so this seems to be good.

**Pull request merged**
