### PR TITLE
schemachanger: move event logging to scbuild and scrun

### LINKED ISSUE #95779: schemachanger: move event logging to build time
Presently, in the declarative schema changer we publish to the event log at execution time by planning and emitting operations to that effect. In the legacy schema changer, we do so at the end of startExec. Moving the declarative schema changer's event logging to scbuild will mimic existing behaviour in that respect, will make it easier to log wrong events by mistake, and will make the execution plans smaller. Furthermore, it appears that the declarative schema changer doesn't emit reverse_schema_change events at all, and is a bit weird about the finish_schema_change & finish_schema_change_rollback events it does emit.

Jira issue: CRDB-23736

### PR DESCRIPTION
**Pull request by postamar**
Previously, the declarative schema changer would write events to the event log by means of operations planned in a mutation stage. This commit makes it so that the following schema change events are written by the schema change job:
  - reverse_schema_change,
  - finish_schema_change,
  - finish_schema_change_rollback. 

The remaining schema change events are written at build-time, which is in line with the legacy schema changer which does this in the planNodes' startExec method.

This makes for simpler declarative schema changer operation generation logic and much simpler plans. This comes at the expense of some transactionality, but it appears that this behaviour was not expected in any case.

Fixes #95779.

Release note: None

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
I read through this and the ideas seem sound to me.

**Comment by postamar** [comment]
Thanks. Note: I noticed that nothing actually tests for `reverse_schema_change` events so I added some assertions in an existing and suitable unit test.

**Review by ajwerner — APPROVED** [review]
> Reviewed 48 of 342 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/95786)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @postamar)

___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95786#-NM_fRdzADeyjCCcQlG3:-NM_fRdzADeyjCCcQlG4:bujuh5w) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b8f1de682853c56b2f1fd774805bfd672845ba/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L86)):*
> ```Go
> 
> 	// WithLogEvent will ensure that any target matching the provided element
> 	// emits an entry in the event log. No-ops if no target is found.
> ```

I'm not sure I love this `No-ops if no target is found`. Why would we expect that to happen? Can we make that an assertion failure?
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go` line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/95786#-NM_hww9Cs5AqEvjjODF:-NM_hww9Cs5AqEvjjODG:b-unb9dw) ([raw file](https://github.com/cockroachdb/cockroach/blob/71b8f1de682853c56b2f1fd774805bfd672845ba/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/dependencies.go#L87)):*
> ```Go
> 	// WithLogEvent will ensure that any target matching the provided element
> 	// emits an entry in the event log. No-ops if no target is found.
> 	WithLogEvent(element scpb.Element)
> ```

Can you describe the principle here? The idea, as I understand it, is that some elements are important an worth logging about and some are not and it's up to the builder to decide which are worth logging about.

**Comment by postamar** [comment]
Thanks for the review!

> No-ops if no target is found

I just thought it wouldn't be worth throwing an error complaining about a missing target, I didn't think the event logging to be important enough to warrant that. I can do an assertion failure, not a problem at all.

**Pull request merged**
