### PR TITLE
storage: avoid acquiring raftMu in Replica.propose

### PR DESCRIPTION
**Pull request by nvb**
Related to #9827.

This addresses a TODO to avoid acquiring `Replica.raftMu` in `Replica.propose`
in the common case where the replica's internal raft group is not null.

This showed up in blocking profiles when running sysbench's `oltp_insert`
workload. Specifically, the locking of `raftMu` in `Replica.propose` was
responsible for **29.3%** of blocking in the profile:

before
_raftMu locking in Replica.propose is responsible for the second large pillar_

This change increases throughput of the sysbench workload by **11%** and reduces
the reported average latency by **10%**. This was averaged over a few runs.
Below is the output of a representative run before and after.

Before
```
SQL statistics:
    queries performed:
        read:                            0
        write:                           202253
        other:                           0
        total:                           202253
    transactions:                        202253 (3368.51 per sec.)
    queries:                             202253 (3368.51 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

Throughput:
    events/s (eps):                      3368.5102
    time elapsed:                        60.0423s
    total number of events:              202253

Latency (ms):
         min:                                    0.99
         avg:                                   37.98
         max:                                  141.98
         95th percentile:                       58.92
         sum:                              7681469.72

Threads fairness:
    events (avg/stddev):           1580.1016/4.11
    execution time (avg/stddev):   60.0115/0.01
```

After
```
SQL statistics:
    queries performed:
        read:                            0
        write:                           228630
        other:                           0
        total:                           228630
    transactions:                        228630 (3808.46 per sec.)
    queries:                             228630 (3808.46 per sec.)
    ignored errors:                      0      (0.00 per sec.)
    reconnects:                          0      (0.00 per sec.)

Throughput:
    events/s (eps):                      3808.4610
    time elapsed:                        60.0321s
    total number of events:              228630

Latency (ms):
         min:                                    3.59
         avg:                                   33.60
         max:                                  156.34
         95th percentile:                       51.02
         sum:                              7680843.03

Threads fairness:
    events (avg/stddev):           1786.1719/3.89
    execution time (avg/stddev):   60.0066/0.01
```

After this change, the blocking profile shows that `Replica.propose` is no longer
a problem:

after

Release note (performance improvement): Reduce lock contention in
Replica write path.

### CODE REVIEW

**Comment by jordanlewis** [comment]
This is sweet - can't wait to hear whether it affects TPCC.

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[pkg/storage/replica.go, line 564 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24990#-LAnTEtM0mLStnvLQkm6:-LAnTEtM0mLStnvLQkm7:b-ibrfzk) ([raw file](https://github.com/cockroachdb/cockroach/blob/100828020de775b596c1138a4bec2383c5e8f02e/pkg/storage/replica.go#L564)):*
> ```Go
> 		// creation if we gossiped our store descriptor more than the election
> 		// timeout in the past.
> 		canCampaign := r.store.canCampaignIdleReplica()
> ```

#24920 is getting rid of this logic. You and Ben will have to work out the sequencing of these PRs.

---

*[pkg/storage/replica.go, line 3209 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24990#-LAnUnwC6YKTcXn4AoJx:-LAnUnwC6YKTcXn4AoJy:bjh9uup) ([raw file](https://github.com/cockroachdb/cockroach/blob/925dd4f3f6461766e1e430042da220daf99c0a46/pkg/storage/replica.go#L3209)):*
> ```Go
> 	// optimize for the common case where Replica.mu.internalRaftGroup is
> 	// non-nil, but that doesn't currently seem worth it. Always locking raftMu
> 	// has a tiny (~1%) performance hit for single-node block_writer testing.
> ```

It's interesting that you are seeing a benefit. Perhaps the rest of the system has evolved enough to make this a bottleneck now when it wasn't previously.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24990)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24990#-:-LAnUzCW9hij96ZZGlcD:bnfp4nl)*

**Comment by petermattis** [comment]
Reminder, we're in the stabilization period before the next 2.1 alpha release. We should consider the risk vs reward for this change and consider merging next week (after the 2.1 alpha has been cut) instead of this week.

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24990#-:-LAnV-hu9Xxv73joQRZ2:b17sgj7)*

**Comment by nvanbenschoten** [comment]
TFTR. I'll hold off on merging this until next week and will coordinate with #24920.

**Comment by a-robinson** [comment]
This is also related to https://github.com/cockroachdb/cockroach/issues/19156. Thanks @nvanbenschoten!

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica.go, line 528 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24990#-LAnXGej4X3o-x3U88UT:-LAnXGej4X3o-x3U88UU:bovofde) ([raw file](https://github.com/cockroachdb/cockroach/blob/100828020de775b596c1138a4bec2383c5e8f02e/pkg/storage/replica.go#L528)):*
> ```Go
> // replicas.
> //
> // Requires that Replica.mu is held. Also requires that Replica.raftMu is held
> ```

This is a weird and subtle rule. I don't like introducing non-standard synchronization rules because they're hard to reason about. How confident are we that the old comment "It appears that we only need to hold Replica.raftMu when calling raft.NewRawNode. We could get fancier with the locking here to" is still true?  The race detector can't help us here because `raftMu` isn't protecting access to any particular piece of memory. 

---

*[pkg/storage/replica.go, line 3209 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24990#-LAnUnwC6YKTcXn4AoJx:-LAnV2Go2N7f8BhFXOma:b-8954w7) ([raw file](https://github.com/cockroachdb/cockroach/blob/925dd4f3f6461766e1e430042da220daf99c0a46/pkg/storage/replica.go#L3209)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

It's interesting that you are seeing a benefit. Perhaps the rest of the system has evolved enough to make this a bottleneck now when it wasn't previously.
</blockquote></details>

I bet that comment came before we were fsyncing all log writes.  `handleRaftReadyRaftMuLocked` writes to the log while holding `raftMu` but not `r.mu`; it is one of the few places where we hold `raftMu` by itself. 

I wonder if we could refactor `handleRaftReady` so we didn't have to hold `raftMu` over the sync.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24990)*

**Comment by a-robinson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/replica.go, line 3209 at r1](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24990#-LAnUnwC6YKTcXn4AoJx:-LAnxw3Y3j_keoe8acoM:bm5blta) ([raw file](https://github.com/cockroachdb/cockroach/blob/925dd4f3f6461766e1e430042da220daf99c0a46/pkg/storage/replica.go#L3209)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

@bdarnell Heh, the `TODO(peter)` comment was written in 7fb95438c073ddff82b3d8bd0c5ae6e1f051ea80 (Oct 5, 2016). That was a lifetime ago.

> I wonder if we could refactor handleRaftReady so we didn't have to hold raftMu over the sync.

I did an audit a long time ago about long holds of `raftMu`. Probably worthwhile to do that again.
</blockquote></details>

As called out in https://github.com/cockroachdb/cockroach/issues/19156, `handleRaftReadyRaftMuLocked` is a huge offender.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/24990)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/replica.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24990#-LAnXGej4X3o-x3U88UT:-LBSB2cQEmrLIaJWZCW5:b-9t3rtg) ([raw file](https://github.com/cockroachdb/cockroach/blob/100828020de775b596c1138a4bec2383c5e8f02e/pkg/storage/replica.go#L528)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This is a weird and subtle rule. I don't like introducing non-standard synchronization rules because they're hard to reason about. How confident are we that the old comment "It appears that we only need to hold Replica.raftMu when calling raft.NewRawNode. We could get fancier with the locking here to" is still true?  The race detector can't help us here because `raftMu` isn't protecting access to any particular piece of memory. 
</blockquote></details>

All external mutations to `r.mu.internalRaftGroup` are performed under `Replica.mu` lock, so it looks like your suspicion was correct that we never need to hold Replica.raftMu when calling `withRaftGroupLocked`. This allowed me to simplify things considerably. PTAL.

---

*[pkg/storage/replica.go, line 564 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24990#-LAnTEtM0mLStnvLQkm6:-LBSBuB195nalLX8PsHb:b-70cz18) ([raw file](https://github.com/cockroachdb/cockroach/blob/100828020de775b596c1138a4bec2383c5e8f02e/pkg/storage/replica.go#L564)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

#24920 is getting rid of this logic. You and Ben will have to work out the sequencing of these PRs.
</blockquote></details>

#24920 is a much larger change, so that should go in first. It looks like it will be merged tomorrow.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24990)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/storage/replica.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24990#-LAnXGej4X3o-x3U88UT:-LBafFOO5Ec1yVWwElQN:bkf5xce) ([raw file](https://github.com/cockroachdb/cockroach/blob/100828020de775b596c1138a4bec2383c5e8f02e/pkg/storage/replica.go#L528)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

All external mutations to `r.mu.internalRaftGroup` are performed under `Replica.mu` lock, so it looks like your suspicion was correct that we never need to hold Replica.raftMu when calling `withRaftGroupLocked`. This allowed me to simplify things considerably. PTAL.
</blockquote></details>

It's certainly simpler, but is it safe? I didn't mean to say that we never need to hold raftMu when calling withRaftGroupLocked; I was asking whether even the lesser claim from that old comment (that we could avoid holding raftMu while calling withRaftGroupLocked if the group already exists) still holds. 

I think we need a fresh analysis of what exactly raftMu is needed for so we can figure out whether it's safe to make this change. I can't remember all the subtleties here and I'm not confident that the tests we have are enough to expose any issues. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24990)*

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24990)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24990#-LAnXGej4X3o-x3U88UT:-LIUekBc4j-7pk7MtW9e:b-37put) ([raw file](https://github.com/cockroachdb/cockroach/blob/100828020de775b596c1138a4bec2383c5e8f02e/pkg/storage/replica.go#L528)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

It's certainly simpler, but is it safe? I didn't mean to say that we never need to hold raftMu when calling withRaftGroupLocked; I was asking whether even the lesser claim from that old comment (that we could avoid holding raftMu while calling withRaftGroupLocked if the group already exists) still holds. 

I think we need a fresh analysis of what exactly raftMu is needed for so we can figure out whether it's safe to make this change. I can't remember all the subtleties here and I'm not confident that the tests we have are enough to expose any issues. 
</blockquote></details>

I went back through and audited the use of `Replica.mu` and `Replica.raftMu`. I also audited all manipulation of `Replica.mu.internalRaftGroup`. I'm now pretty convinced that the original version of this change was correct. I've reverted the code to that. If the `internalRaftGroup` is non-nil and we hold `Replica.mu` then `withRaftGroupLocked` should be safe to call because anyone who resets it to nil (`initRaftMuLockedReplicaMuLocked`, `setReplicaIDRaftMuLockedMuLocked`, `removeReplicaImpl`) also holds `Replica.mu` and handles local proposals in the same critical section. Additionally, calling `Propose` on the raft group should be safe even without `Replica.raftMu` because it's fine if it ends up being concurrent with a call to `handleRaftReadyRaftMuLocked` - either the `raft.Ready` will contain the new proposals or it won't.

The only thing that looks fishy to me is that this will allow us to call `Replica.unquiesceLocked()` without the `raftMu`, but we seem to do that [elsewhere](https://github.com/cockroachdb/cockroach/blob/a149437eec20fe632d058aa146817b5f9614095b/pkg/storage/store.go#L3811) as well. Do you have any insight into this?

**Review by bdarnell — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/24990)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/storage/replica.go, line 528 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/24990#-LAnXGej4X3o-x3U88UT:-LIcv7kC9Y03Puu9--Es:bq3phb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/100828020de775b596c1138a4bec2383c5e8f02e/pkg/storage/replica.go#L528)):*
> Do you have any insight into this?

Not really. Unquiescing without raftMu seems about the same as Proposing without it.

**Comment by nvanbenschoten** [comment]
TFTR.

bors r+

**Pull request merged**
