### PR TITLE
util/log: refactor log validation

### PR DESCRIPTION
**Pull request by rauchenstein**
Previously, log validation had significant boilerplate relating to defaulting logic,
defaulting behavior was not as centrally located as it could be, and lots of code was
duplicated.  With only file and fluent log sinks this was managable, but with http sinks
and more on the way, and more scalable solution was justified.  A small utility function
was added using reflection to reduce the existing boilerplate.  If it proves helpful
here, I'd like to make it more widely available as a utility.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
Throughout: "propogate" -> "propagate"

I'll finish reviewing this after you fix the doc generator.

> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66439#-:-McAZIg58-hcUl688YVr:bcdul74)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[pkg/util/log/logconfig/config.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66439#-McAZ5dF-MPg3nN-cvnf:-McAZ5dF-MPg3nN-cvng:bav9bc0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fd5d54ecd7f95bc05194a4b6a4b94c247320fe/pkg/util/log/logconfig/config.go#L303)):*
> ```Go
> 	Address string `yaml:""`
> 
> 	FluentDefaults `yaml:",inline"`
> ```

You'll need a perfunctory comment in front of this to satisfy the go req that exported fields be documented.
___
*[pkg/util/log/logconfig/config.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66439#-McAZFaJBqy0WNMqHrgj:-McAZFaJBqy0WNMqHrgk:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fd5d54ecd7f95bc05194a4b6a4b94c247320fe/pkg/util/log/logconfig/config.go#L393)):*
> ```Go
> 	Channels ChannelList `yaml:",omitempty,flow"`
> 
> 	FileDefaults `yaml:",inline"`
> ```

ditto

**Review by rauchenstein — COMMENTED** [review]
Review guidance:  The core idea is the new "propagate(.*)Defaults" utility functions at the bottom of validate.go and the simplification of code within that file.  For this to work, types needed to match, so within config.go defaultable fields in *Config structs are now promoted from their *Defaults structs (which is a nice reduction in redundancy anyways).  The remaining changes are mostly fixing sites that created *Config structs to match the new structure and modifying gen.go, which previously assumed that all promoted fields were common.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66439#-:-McGbX8T6CwrJj8dXQ2i:bf073ok)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/util/log/logconfig/config.go, line 303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66439#-McAZ5dF-MPg3nN-cvnf:-McGbPWv5zvX5HLoaHpd:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fd5d54ecd7f95bc05194a4b6a4b94c247320fe/pkg/util/log/logconfig/config.go#L303)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

You'll need a perfunctory comment in front of this to satisfy the go req that exported fields be documented.
</blockquote></details>

Done.
___
*[pkg/util/log/logconfig/config.go, line 393 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66439#-McAZFaJBqy0WNMqHrgj:-McGbR454rmSLG34plP3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b2fd5d54ecd7f95bc05194a4b6a4b94c247320fe/pkg/util/log/logconfig/config.go#L393)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

**Review by knz — COMMENTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rauchenstein)

___
*[docs/generated/logsinks.md, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66439#-McJMPtkDbALDBnbm1bj:-McJMPtlBgkO-zUz1CUv:bpu4lf) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ac8bdaaccaf871deb5314be0dfeda51d5cb404/docs/generated/logsinks.md#L70)):*
> ```Markdown
> |--|--|
> | `channels` | the list of logging channels that use this sink. See the [channel selection configuration](#channel-format) section for details.  |
> | `dir` | specifies the output directory for files generated by this sink. Inherited from `file-defaults.dir` if not specified. |
> ```

This change is a regression. We need to preserve a comment about inheritance for all the fields that are, effectively, inherited.
You can fix this by altering the doc generator to explain inheritance for embedded "default" structs.

**Review by rauchenstein — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66439)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[docs/generated/logsinks.md, line 70 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/66439#-McJMPtkDbALDBnbm1bj:-McpBD5l-E32dJX9UftV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/63ac8bdaaccaf871deb5314be0dfeda51d5cb404/docs/generated/logsinks.md#L70)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This change is a regression. We need to preserve a comment about inheritance for all the fields that are, effectively, inherited.
You can fix this by altering the doc generator to explain inheritance for embedded "default" structs.
</blockquote></details>

Done.

**Review by knz — APPROVED** [review]
:lgtm: well done :100: 

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66439#-:-McrvtX-1LHCSmchPgDx:b-f4hj8o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rauchenstein)

**Comment by rauchenstein** [comment]
bors r=knz

**Pull request merged**
