### PR TITLE
opt: Add rules to simplify outer self-join to inner self-join

### PR DESCRIPTION
**Pull request by andy-kimball**
The last remaining Hibernate query contains a correlated subquery that
becomes an outer self-join. It is possible to map an outer self-join to
an inner self-join if certain conditions are met (see JoinPreservesLeftRows
for those conditions). Once that's done, then the query can be fully
decorrelated.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Very nice!

> Reviewed 1 of 3 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-:-LIMKPv162UZm3VIycbB:b-kerl87)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/join.go, line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMGRuj9KBVrYJstmaq:-LIMGRuj9KBVrYJstmar:b-7pdq00) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L243)):*
> ```Go
> }
> 
> // JoinPreservesLeftRows returns true when the given join is guaranteed to
> ```

[nit] As written, this is trivially true for a left join, maybe say that all rows from its left input will match at least one row from the right input. Maybe even rename to `OnConditionMatchesAllLeftRows`
___
*[pkg/sql/opt/norm/join.go, line 392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMJV8t92EA5xBggxe0:-LIMJV8t92EA5xBggxe1:bvjt9k3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L392)):*
> ```Go
> 			relational.Rule.UnfilteredCols.UnionWith(c.deriveUnfilteredCols(right))
> 		}
> 	}
> ```

There are more cases we could do here (e.g. a leftjoin can pass through the unfiltered cols from the left side; similar for Union). Maybe add a TODO or comment that we don't care about other cases.

**Review by rytaft — CHANGES_REQUESTED** [review]
:lgtm_strong: 

> Reviewed 3 of 3 files at r1, 6 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-:-LIMpO808VFG_srOxOh9:b-uwkowd)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/join.go, line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMlO887SmQ-mt-CY4K:-LIMlO899ndx_AdTADu6:b-8f7zrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L248)):*
> ```Go
> //
> //   1. Each conjunct in the join condition is an equality between not-null
> //      columns from the left input and a column from the right input.
> ```

[nit] should say "an equality between a not-null column from the left input and a column from the right input"
___
*[pkg/sql/opt/norm/join.go, line 251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMjutm6AuKYVxOkv9k:-LIMjutm6AuKYVxOkv9l:b-p7bt1t) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L251)):*
> ```Go
> //   2. All left input equality columns come from a single table, as do all
> //      right input equality columns (can be different table).
> //   3. The right input contains every row from its equality table. There may be
> ```

[nit] I'd change "its equality table" to "the table containing its equality columns"
___
*[pkg/sql/opt/norm/join.go, line 276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMlEZzCkMwVZ6FCaPo:-LIMlEZzCkMwVZ6FCaPp:b-btrpu0) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L276)):*
> ```Go
> 
> 	leftCols := c.LookupLogical(left).Relational.NotNullCols
> 	rightCols := c.LookupLogical(right).Relational.NotNullCols
> ```

According to rule #1 above, the rightCols don't need to be non-null
___
*[pkg/sql/opt/norm/join.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMl8H66pcIoA80J2JS:-LIMl8H66pcIoA80J2JT:b60fd1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L303)):*
> ```Go
> 		}
> 		if !leftCols.Contains(int(leftCol)) || !rightCols.Contains(int(rightCol)) {
> 			// Condition #1: columns don't come from both sides of join.
> ```

Could also be because leftCol or rightCol is nullable
___
*[pkg/sql/opt/norm/rules/join.opt, line 283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMnS1i846jO-qkIsGU:-LIMnS1i846jO-qkIsGV:b1ovpzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/rules/join.opt#L283)):*
> ```
> # SimplifyRightJoinWithFilters reduces a RightJoin operator to an InnerJoin
> # operator (or a FullJoin to a LeftJoin) when it's known that every row in the
> # join's right input will match at least one row in the right input. This rule
> ```

should be "at least one row in the left output"

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27948)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/norm/join.go, line 243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMGRuj9KBVrYJstmaq:-LINVFFf6TSr2XZXOzGe:b4y9cx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L243)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] As written, this is trivially true for a left join, maybe say that all rows from its left input will match at least one row from the right input. Maybe even rename to `OnConditionMatchesAllLeftRows`
</blockquote></details>

Renamed to `JoinFiltersMatchAllLeftRows`.
___
*[pkg/sql/opt/norm/join.go, line 248 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMlO887SmQ-mt-CY4K:-LINWAT2351KiLGzVohf:bzbjtz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L248)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] should say "an equality between a not-null column from the left input and a column from the right input"
</blockquote></details>

Done, though clarified that it needs to be not-null on both sides.
___
*[pkg/sql/opt/norm/join.go, line 251 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMjutm6AuKYVxOkv9k:-LINWbmk9Mz2fViGE7Nt:blm4617) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L251)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] I'd change "its equality table" to "the table containing its equality columns"
</blockquote></details>

I added a definition for `equality table` in #2, so I can use that term (it's nice and short, and I need to refer to it multiple times).
___
*[pkg/sql/opt/norm/join.go, line 276 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMlEZzCkMwVZ6FCaPo:-LINX0oND5NT52ge1v25:b24e39m) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L276)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

According to rule #1 above, the rightCols don't need to be non-null
</blockquote></details>

They do need to be non-null, so I fixed the comment.
___
*[pkg/sql/opt/norm/join.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMl8H66pcIoA80J2JS:-LINXXS82UK69KTg-2uC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L303)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Could also be because leftCol or rightCol is nullable
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/join.go, line 392 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMJV8t92EA5xBggxe0:-LINXZ5jEUoZkSfeDuxp:b-hukn99) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L392)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

There are more cases we could do here (e.g. a leftjoin can pass through the unfiltered cols from the left side; similar for Union). Maybe add a TODO or comment that we don't care about other cases.
</blockquote></details>

Added TODO.
___
*[pkg/sql/opt/norm/rules/join.opt, line 283 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMnS1i846jO-qkIsGU:-LINXpAb-No5kmByjgdA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/rules/join.opt#L283)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

should be "at least one row in the left output"
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 1 of 7 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27948)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/norm/join.go, line 303 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/27948#-LIMl8H66pcIoA80J2JS:-LINaS278nGe28xjXspN:bm2mknn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e1b472b42a589a035f4850e684bc12c9afe13ab/pkg/sql/opt/norm/join.go#L303)):*
<details><summary><i>Previously, andy-kimball (Andy Kimball) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

change "not null" to "nullable".

**Pull request merged**
