### PR TITLE
sql: allow for pre-19.2 foreign keys in table validation

### LINKED ISSUE #57032: release-20.2: sql: failure to upgrade FK representation during table validation produces spurious errors and makes table unavailable
I'm not sure if this is part of the upgrade to 20.2.0 or some other reason that correlates in time, but I seem to have suddenly lost all foreign key references on our production servers.

Please describe the issue you observed, and any steps we can take to reproduce it:

Make a database using an older version and upgrade. This was noticed some time after the upgrade.

What did you do? Describe in your own words.

If possible, provide steps to reproduce the behavior:

1. Set up CockroachDB 3-node cluster and initialize the database.
2. Use the following SQL to setup the database for the errors below:
----------------------------------
```sql
-- The various known types of machines.
CREATE TABLE IF NOT EXISTS machine_type (
    id INT NOT NULL PRIMARY KEY,
    name STRING NOT NULL UNIQUE
);

INSERT INTO machine_type (id, name) VALUES
    (0, 'unknown'),
    (1, 'known');

-- Machines and their associated information.
CREATE TABLE IF NOT EXISTS machine (
    id BYTES DEFAULT uuid_v4() PRIMARY KEY NOT NULL,
    machine_type INT NOT NULL,
    name STRING,
    FOREIGN KEY(machine_type) REFERENCES machine_type(id) ON UPDATE CASCADE ON DELETE CASCADE
);
```
----------------------------------
3. Add some data.
4. Upgrade to CockroachDB 20.2.0.
5. Sudd

**Expected behavior**
Return results from query like normal.

**Additional data / screenshots**
----------------------------------
root@:26257/fini> SELECT * from backup
               -> ;
ERROR: internal error: missing fk back reference "fk_machine_id_ref_machine" to "backup" from "machine"
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:1500: validateCrossReferences()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:1440: Validate()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:298: unwrapDescriptor()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:160: GetDescriptorByID()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:215: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:707: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:811: exec()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:706: Txn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:193: acquire()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:858: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128: doCall()
/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
root@:26257/fini> SELECT * FROM machine;
ERROR: internal error: missing fk back reference "fk_machine_type_ref_machine_type" to "machine" from "machine_type"
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:1500: validateCrossReferences()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:1440: Validate()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:298: unwrapDescriptor()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:160: GetDescriptorByID()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:215: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:707: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:811: exec()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:706: Txn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:193: acquire()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:858: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128: doCall()
/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
root@:26257/fini> SELECT * FROM machine_type;
ERROR: internal error: missing fk forward reference "fk_machine_type_ref_machine_type" to "machine_type" from "machine"
SQLSTATE: XX000
DETAIL: stack trace:
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:1519: validateCrossReferences()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/tabledesc/structured.go:1440: Validate()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:298: unwrapDescriptor()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/catalogkv/catalogkv.go:160: GetDescriptorByID()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:215: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:707: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/txn.go:811: exec()
/go/src/github.com/cockroachdb/cockroach/pkg/kv/db.go:706: Txn()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:193: acquire()
/go/src/github.com/cockroachdb/cockroach/pkg/sql/catalog/lease/lease.go:858: func1()
/go/src/github.com/cockroachdb/cockroach/pkg/util/syncutil/singleflight/singleflight.go:128: doCall()
/usr/local/go/src/runtime/asm_amd64.s:1357: goexit()

HINT: You have encountered an unexpected error.

Please check the public issue tracker to check whether this problem is
already tracked. If you cannot find it there, please report the error
with details by creating a new issue.

If you would rather not post publicly, please contact us directly
using the support form.

We appreciate your feedback.
----------------------------------

If a node in your cluster encountered a fatal error, supply the contents of the
log directories (at minimum of the affected node(s), but preferably all nodes).

Note that log files can contain confidential information. Please continue
creating this issue, but contact support@cockroachlabs.com to submit the log
files in private.

**Environment:**
 - CockroachDB version 20.2.0
 - Server OS: Ubuntu Bionic
 - Client app: `cockroach sql`

**Additional context**
What was the impact?

I'm unable to run queries against our production servers.

### PR DESCRIPTION
**Pull request by thoszhang**
sql: allow for pre-19.2 foreign keys in table validation

We introduced a bug in v20.2 where we failed to upgrade referenced
descriptors' FK representations from pre-19.2 descriptors when
validating cross-references for tables, leading to validation failures
that would make the table unusable. This PR gets rid of the validation
errors by having `Validate()` account for pre-19.2-style foreign keys on
referenced table descriptors.

Fixes #57032.

Release note (bug fix): Fixes a bug where tables and metadata were
unavailable due to spurious `missing fk back reference` validation
errors.

---

catalogkv: add testing of descriptor unwrapping and validation

This commit adds a framework to test that descriptors validate properly.
It also adds testdata and a bash script to generate that test data.

This test is to exercise a problematic path whereby tables constructed
in v19.1 would fail to validate in v20.2.

Release note: None

### CODE REVIEW

**Review by ajwerner — CHANGES_REQUESTED** [review]
:lgtm: 

I might extract some helpers and do some more line wrapping but that' extremely nitpicky. 

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-:-MMvlLTw4dbm1zStKsYA:bc5if6p)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, and @lucy-zhang)

___
*[pkg/sql/catalog/catalogkv/unwrap_validation_test.go, line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-MMvlk8g6tPZe6S3IIj-:-MMvlk8g6tPZe6S3IIj0:b-t7psfu) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd257395327bd7c1d47c6d0dcdd0683af5d093a/pkg/sql/catalog/catalogkv/unwrap_validation_test.go#L16)):*
> ```Go
> 	"context"
> 	"encoding/hex"
> 	"errors"
> ```

Is the linter going to complain about this?
___
*[pkg/sql/catalog/tabledesc/structured.go, line 1648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-MMvl7mV8_w2vNc2Peee:-MMvl7mW1RbJtENVk_Ii:bv30fk4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3d12dd52c0db5205bfdb7e2eb9c950fd650187/pkg/sql/catalog/tabledesc/structured.go#L1648)):*
> ```
> 
> 					"missing index %d on %q from pre-19.2 foreign key forward reference %q on %q",
> 					fk.Index, desc.Name, backref.Name, originTable.GetName(),
> ```
Would we be happier if these errors had the entire descriptor? The names are going to disappear in redaction. Same for all the other errors around here.

**Review by jordanlewis — APPROVED** [review]
Looks good. If it's not too much trouble, I would like to see a unit test in the first commit that validates a hand-constructed descriptor pair of this type as well, so it's as easy as possible to see the behavior of this commit, and so we don't accidentally "lose" this test if the datadriven approach changes over time.

If this is silly, feel free to push back.

Overall, I'm confident in the small footprint of this change.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-:-MMvoOFXA4v4nZ7i2CvG:bryy3u0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @lucy-zhang)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 1544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-MMvoE3LCuVNzxE7zRwd:-MMvoE3LCuVNzxE7zRwe:b-y9fhh) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3d12dd52c0db5205bfdb7e2eb9c950fd650187/pkg/sql/catalog/tabledesc/structured.go#L1544)):*
> ```Go
> 		// somewhat parallels the logic in maybeUpgradeForeignKeyRepOnIndex.
> 		unupgradedFKsPresent := false
> 		if err := referencedTable.ForeachIndex(catalog.IndexOpts{}, func(referencedIdx *descpb.IndexDescriptor, isPrimary bool) error {
> ```

Should we add a `if found == true` breakout from this section to, to parallel the one in the second section?

**Comment by lucy-zhang** [comment]
I added some testing for (1) auto-created referencing-side indexes in 19.2, (2) extra indexes on the referencing side that overlap with the one that's designated for the FK, and (3) the case where we switch out the referencing-side index from the original pre-19.2 one (just sort of a special case in the upgrade path which I don't expect to cause problems).

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57066)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @jordanlewis)

___
*[pkg/sql/catalog/catalogkv/unwrap_validation_test.go, line 16 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-MMvlk8g6tPZe6S3IIj-:-MMvqK_wCBQtetJa0LQo:b-l97i80) ([raw file](https://github.com/cockroachdb/cockroach/blob/fdd257395327bd7c1d47c6d0dcdd0683af5d093a/pkg/sql/catalog/catalogkv/unwrap_validation_test.go#L16)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Is the linter going to complain about this?
</blockquote></details>

Good point, fixed.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 1544 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-MMvoE3LCuVNzxE7zRwd:-MMvqx3KBLbU1xGZyM7z:b-g0xhj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3d12dd52c0db5205bfdb7e2eb9c950fd650187/pkg/sql/catalog/tabledesc/structured.go#L1544)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Should we add a `if found == true` breakout from this section to, to parallel the one in the second section?
</blockquote></details>

Oh yeah, done.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 1648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-MMvl7mV8_w2vNc2Peee:-MMvqzJi6QicNItKEvxY:b-jcr22h) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3d12dd52c0db5205bfdb7e2eb9c950fd650187/pkg/sql/catalog/tabledesc/structured.go#L1648)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

> ```
> 
> 					"missing index %d on %q from pre-19.2 foreign key forward reference %q on %q",
> 					fk.Index, desc.Name, backref.Name, originTable.GetName(),
> ```
Would we be happier if these errors had the entire descriptor? The names are going to disappear in redaction. Same for all the other errors around here. 
</blockquote></details>

Yeah, I think so. How do you think we should format this log line (given that the table descriptor is some large thing with newlines)?

**Comment by lucy-zhang** [comment]
> If it's not too much trouble, I would like to see a unit test in the first commit that validates a hand-constructed descriptor pair of this type as well, so it's as easy as possible to see the behavior of this commit, and so we don't accidentally "lose" this test if the datadriven approach changes over time.

I think that's reasonable. We can add it to `TestValidateCrossTableReferences`.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57066)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jordanlewis, and @lucy-zhang)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 1648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-MMvl7mV8_w2vNc2Peee:-MMvzt_iCIDt3SsxpM8s:brrred2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3d12dd52c0db5205bfdb7e2eb9c950fd650187/pkg/sql/catalog/tabledesc/structured.go#L1648)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Yeah, I think so. How do you think we should format this log line (given that the table descriptor is some large thing with newlines)?
</blockquote></details>

for better or for worse, it doesn't have newlines.

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57066)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @jordanlewis)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 1648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-MMvl7mV8_w2vNc2Peee:-MMw2ENzDAHXLDDbAQ_d:bfyrqu9) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3d12dd52c0db5205bfdb7e2eb9c950fd650187/pkg/sql/catalog/tabledesc/structured.go#L1648)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

for better or for worse, it doesn't have newlines. 
</blockquote></details>

Feel free to just do something reasonable here and push it.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57066)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jordanlewis, and @lucy-zhang)

___
*[pkg/sql/catalog/tabledesc/structured.go, line 1648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-MMvl7mV8_w2vNc2Peee:-MMw5NW6A51jfg4sKyZR:bk37tbb) ([raw file](https://github.com/cockroachdb/cockroach/blob/0b3d12dd52c0db5205bfdb7e2eb9c950fd650187/pkg/sql/catalog/tabledesc/structured.go#L1648)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

Feel free to just do something reasonable here and push it.
</blockquote></details>

I'm skipping for now because it breaks a bunch of tests because we don't actually have valid descriptors and the formatting assumes we do (maybe that's a mistake). Will deal with it later in a more generic way.

**Comment by lucy-zhang** [comment]
@jordanlewis do you want to take another look at the tests?

**Review by jordanlewis — APPROVED** [review]
Do we have a test that checks what happens if neither descriptor had been upgraded? I see 2, which I think are both the 1-side case: one of the descriptors was upgraded, but not the other.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57066#-:-MMwNvLH-z5J_N3EuT7l:bcbzu3w)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @jordanlewis, and @lucy-zhang)

**Comment by lucy-zhang** [comment]
We're assuming (both in code and in the tests) that once the descriptors make their way into `validateCrossReferences`, the descriptor whose descriptor is being validated is always upgraded. The problem is just with the referenced descriptors.

**Comment by ajwerner** [comment]
> Do we have a test that checks what happens if neither descriptor had been upgraded? I see 2, which I think are both the 1-side case: one of the descriptors was upgraded, but not the other.

We always upgrade the current descriptor before attempting to read the other side. This test just tests validating the other side. We do exercise the specific scenario you're bringing up in the datadriven test. I can try to finagle one that runs the whole validation logic on both but it's going to be annoying.

**Comment by jordanlewis** [comment]
No problem, I'm satisfied if you are.

**Pull request merged**
