### PR TITLE
Tolerate ntp in disable-hyperv-timesync.sh

### LINKED ISSUE #16999: acceptance: max clock offset exceeded in nightly photos test
* build: 6b48d06
* failed test: [continuous photos load, 4 hours 6 nodes ](https://teamcity.cockroachdb.com/viewLog.html?buildId=294155&buildTypeId=Cockroach_Nightlies_ContinuousPhotos4Nodes6hours)
* [logs for failing node](https://teamcity.cockroachdb.com/viewLog.html?buildId=294155&buildTypeId=Cockroach_Nightlies_ContinuousPhotos4Nodes6hours&tab=artifacts#!12njl7i)

The issues started right after node startup:

```
W170712 06:20:05.975087 13418 storage/replica.go:2561  [n4,s4,r1/4:/{Min-System/}] context cancellation after 0.0s of attempting command RequestLease [/Min,/Min)
I170712 06:20:08.875706 3559 vendor/google.golang.org/grpc/transport/http2_client.go:954  Client received GoAway with http2.ErrCodeEnhanceYourCalm.
```

About 19 minutes after node startup, a stream of these warnings occurs:

```
W170712 06:39:41.891737 3469 ts/db.go:114  [n4,ts-poll] error writing time series data: storage/store.go:2460: rejecting command with timestamp in the future: 1499841581846724547 (508.613846ms ahead)
```

25 minutes into the test, the node crashes:

```
W170712 06:45:21.896630 3469 ts/db.go:114  [n4,ts-poll] error writing time series data: storage/store.go:2460: rejecting command with timestamp in the future: 1499841921882653599 (549.905815ms ahead)
E170712 06:45:28.058467 3445 util/log/crash_reporting.go:183  [n4] Reported as error 8145a85be92040209c25cf967d00ecc5
F170712 06:45:28.058489 3445 server/server.go:178  [n4] clock synchronization error: this node is more than 500ms away from at least half of the known nodes (2 of 4 are within the offset)
```

This is the first time this error has occurred since I first setup the disabling of the HyperV time sync on Azure. So, I suspect that a579c27fbc4f8951cf2e18a939ff9dee33d97ef3 is the culprit.

cc @mberhault in case he has thoughts on this

### PR DESCRIPTION
**Pull request by RaduBerinde**
Fixes #16999.

### CODE REVIEW

**Review by mberhault — APPROVED** [review]

**Comment by RaduBerinde** [comment]
@cuongdo I know you are removing `ntp`, but it's still a good idea to make this script more tolerant.

**Comment by cuongdo** [comment]
*[build/disable-hyperv-timesync.sh, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17004#-KotcQNUplAo8Ev408Dp:-KotcQNUplAo8Ev408Dq:bpsbpj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0ca9341c9ab8fef56266b29a237a3bea7f9881/build/disable-hyperv-timesync.sh#L46)):*
> ```Shell
>   sudo service ntp start
> else
>   sudo ntpdate -b ntp.ubuntu.com
> ```

can this run when systemd-timesyncd` is enabled? (I don't know much about that process)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17004)*

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17004#-:-KotcYQqKqX7x3LDk7fs:bnfp4nl)*

**Comment by RaduBerinde** [comment]
*[build/disable-hyperv-timesync.sh, line 46 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17004#-KotcQNUplAo8Ev408Dp:-Kow7NFB1sxaOeFxqLWY:b-qexegc) ([raw file](https://github.com/cockroachdb/cockroach/blob/bf0ca9341c9ab8fef56266b29a237a3bea7f9881/build/disable-hyperv-timesync.sh#L46)):*
<details><summary><i>Previously, cuongdo (Cuong Do) wrote…</i></summary><blockquote>

can this run when systemd-timesyncd` is enabled? (I don't know much about that process)
</blockquote></details>

We just disabled it above (set-ntp false)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17004)*

**Pull request merged**
