### PR TITLE
backupccl: fix bug in failing backups

### PR DESCRIPTION
**Pull request by pbardea**
Fixes a bug where backups progress updating goroutine may continue
running even after the backup command itself fails. At worst, this results
in a panic inside Google Cloud Storage's SDK since we attempt to write
to a destination that was previously closed upon the backup failure.

Release note (bug fix): fix a bug that could cause a node to crash in rare
cases if a BACKUP writing to Google Cloud Storage failed

### CODE REVIEW

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
very minor nit: I'm not sure I follow the release note, specifically what `where backup would attempt to write to the
backup destination` means to a user. I might just go with something like `fix a bug that could cause a node to crash in rare cases if a BACKUP to writing Google Cloud failed` might be sufficient ?

**Comment by pbardea** [comment]
Thanks for catching, updated.

**Comment by pbardea** [comment]
TFTR!
bors r+

**Comment by dt** [comment]
@pbardea we never backported this to 20.2, right?

**Pull request merged**
