### PR TITLE
roachtest: disable scheduled backups for `point-tombstone`

### PR DESCRIPTION
**Pull request by erikgrinaker**
Touches #110304.
Epic: none
Release note: None

### CODE REVIEW

**Comment by renatolabs** [comment]
Can we document why we're disabling backups? I clicked the related issue linked and one of the comments say the following about backups:

> Not clear that it's related, but doesn't seem particularly useful here either

If a backup is not directly working against the test, I would lean on not disabling -- we never know when something that is not "particularly useful" might uncover something unexpected.

It's fine to disable if we have a good reason; it's just unclear to me.

Nit: we have `option.DefaultStartOptsNoBackups()` for this purpose.

**Comment by erikgrinaker** [comment]
We're writing 30 GB of data in this test, which it seems a bit iffy to be backing up with the associated network costs. I'm fine with keeping it in if we think it's valuable though, just figured we had sufficient coverage in less expensive tests.

**Comment by renatolabs** [comment]
Hrmm, I believe 30GB shouldn't be too costly (dollar-wise) especially since the data shouldn't be leaving the GCP region. Storage costs should be minimal as well -- the backup bucket has a 1-day TTL.

If it's getting in the way of an investigation, I'd understand temporarily disabling, but I do believe these backups could help uncover bugs when they run by default in roachtests.

**Comment by erikgrinaker** [comment]
Sure, let's leave it in then. Not a problem afaik.

**Pull request closed without merging**
