### PR TITLE
sql, opt: add telemetry for nulls reordering on ORDER BY

### PR DESCRIPTION
**Pull request by nehageorge**
Previously, there was no tracking of the usage of NULLS FIRST/LAST
modifiers for ORDER BY. Since we are adding this feature in the
next major release, we should track this. This will also help
determine the urgency/necessity of adding nulls reordering for indexes.

Fixes #71461.

Release note: None.

### CODE REVIEW

**Review by mgartner — APPROVED** [review]
nit: fix the commit message and PR desription typo in "we should add track this"

LGTM

**Review by RaduBerinde — COMMENTED** [review]
LGTM

There will be some interaction between this and https://github.com/cockroachdb/cockroach/pull/71429.  Do we want to track non-default (as in different from the current session setting value) or do we want to track specifically the case that's the "non-standard" choice in our system? (thinking the latter, but we'll need a better name for the telemetry counter)

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71471#-:-MlpQFFtCLlgnrMdc3tg:b-ulwat3)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Review by nehageorge — COMMENTED** [review]
What do you mean by "non-standard" choice? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71471#-:-MlpRxKT91zM5tySa7eS:be9dawi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Review by nehageorge — COMMENTED** [review]
Oh I see what you mean. I think we still want to add the increment line in the same place, but perhaps a different name could be better? `OrderByNullsNonStandard`?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71471#-:-MlpSu17BPmaGRlqzpsb:b-bhru26)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner)

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71471#-:-MlqGRdi6Qb0iR2w3aLf:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by nehageorge** [comment]
TFTRs!

bors r+

**Pull request merged**
