### PR TITLE
opt: change InterestingOrderings to use OrderingChoice

### PR DESCRIPTION
**Pull request by rytaft**
**opt: move `OrderingChoice` from `physical` to `props`**
This commit moves `OrderingChoice` from `pkg/sql/opt/props/physical` to
`pkg/sql/opt/props` in preparation for using it in `pkg/sql/opt/props`.
This will be necessary to avoid an import cycle.

**opt: change `InterestingOrderings` to use `OrderingChoice`**
This commit changes the `InterestingOrderings` logical property to
use a set of `OrderingChoice`s rather than a set of `Ordering`s. This
allows the optimizer to take advantage of a larger number of
interesting orderings when some columns are constant or there
are equalities between columns.

Informs #56201

Release note (performance improvement): increased the intelligence
of the optimizer around orderings that can be provided by certain
relational expressions when some columns are constant or there
are equalities between columns. This can allow the optimizer to
plan merge joins, streaming group bys, and streaming set operations
in more cases, resulting in improved performance.

### CODE REVIEW

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/xform/testdata/physprops/ordering, line 1495 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64501#-MZ_azj1BT041pnj_o8a:-MZ_azj1BT041pnj_o8b:b-v6taw2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbf037bb56624b2bf3066f029c230347fb80420d/pkg/sql/opt/xform/testdata/physprops/ordering#L1495)):*
> ```
>  ├── fd: (9)==(10), (10)==(9)
>  ├── ordering: +(9|10) [actual: +9]
>  ├── sort (segmented)
> ```

This is the one place where we have a worse plan. I think it has something to do with the interesting orderings not aligning with the provided ordering, but I'm having trouble figuring it out. We shouldn't need any sort here at all.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64501)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/testdata/physprops/ordering, line 1495 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64501#-MZ_azj1BT041pnj_o8a:-MZdJPU35TKfwRiWxmRn:b-4brgej) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbf037bb56624b2bf3066f029c230347fb80420d/pkg/sql/opt/xform/testdata/physprops/ordering#L1495)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

This is the one place where we have a worse plan. I think it has something to do with the interesting orderings not aligning with the provided ordering, but I'm having trouble figuring it out. We shouldn't need any sort here at all.
</blockquote></details>

Provided orderings (the `actual`) are born in a post-processing step after the final plan is chosen, they can't affect the plan. Not sure if you meant those though.

The only place where interesting orderings play a role in this query is when we try segmented sort. Something stopped working in that logic, probably because what used to be `+1,+2,+3` is now `+(1|2),+3`.

As for why we sort at all, it's the `+(1|2),+3` which can only get pushed down under the select as `+1,+3` or `+2,+3` (although `+1,+2,+3` would also be correct). This can be improved by using interesting orderings to choose what to push down; tracked by issue https://github.com/cockroachdb/cockroach/issues/33023

**Comment by rytaft** [comment]
___
*[pkg/sql/opt/xform/testdata/physprops/ordering, line 1495 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64501#-MZ_azj1BT041pnj_o8a:-MZhwGMI2UlMRHne2tgh:bb3fhs0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bbf037bb56624b2bf3066f029c230347fb80420d/pkg/sql/opt/xform/testdata/physprops/ordering#L1495)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Provided orderings (the `actual`) are born in a post-processing step after the final plan is chosen, they can't affect the plan. Not sure if you meant those though.

The only place where interesting orderings play a role in this query is when we try segmented sort. Something stopped working in that logic, probably because what used to be `+1,+2,+3` is now `+(1|2),+3`.

As for why we sort at all, it's the `+(1|2),+3` which can only get pushed down under the select as `+1,+3` or `+2,+3` (although `+1,+2,+3` would also be correct). This can be improved by using interesting orderings to choose what to push down; tracked by issue https://github.com/cockroachdb/cockroach/issues/33023
</blockquote></details>

Oh nice! Thanks for the hint. I've fixed this in #64593.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice improvement!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64501#-:-MZnpgsl8QQEe4D6hC0W:b-6f8vr5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/xform/join_funcs.go, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64501#-MZnoD6_4E3BfqXHuMpf:-MZnoD6_4E3BfqXHuMpg:beadw7x) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c6b2cb160fa8731f64817ee8b9ca97a86d6021/pkg/sql/opt/xform/join_funcs.go#L101)):*
> ```Go
> 
> 	for _, ord := range orders {
> 		o := ord.ToOrderingLong()
> ```

[nit] ToOrderingLong is a bit questionable as a general primitive. I wonder if we shouldn't do it "inline" and while addressing the TODO below as well. We'd do the loop below directly on the OrderingChoice and then loop through the remaining columns and add them as well.
___
*[pkg/sql/opt/props/ordering_choice.go, line 729 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64501#-MZnozG392ZTPeRqxKeF:-MZnozG392ZTPeRqxKeG:bfl35me) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c6b2cb160fa8731f64817ee8b9ca97a86d6021/pkg/sql/opt/props/ordering_choice.go#L729)):*
> ```Go
> // set. If a group does not contain any columns in the given set, it removes that
> // group and all following groups.
> func (oc *OrderingChoice) ProjectColsNoError(cols opt.ColSet) {
> ```

[nit] I'd name it `RestrictToCols`

**Review by rytaft — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64501#-:-MZoIIhHDOYPHLhywEkI:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner)

___
*[pkg/sql/opt/xform/join_funcs.go, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64501#-MZnoD6_4E3BfqXHuMpf:-MZoH0EpDbRSPQo4GH_E:bz5py0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c6b2cb160fa8731f64817ee8b9ca97a86d6021/pkg/sql/opt/xform/join_funcs.go#L101)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] ToOrderingLong is a bit questionable as a general primitive. I wonder if we shouldn't do it "inline" and while addressing the TODO below as well. We'd do the loop below directly on the OrderingChoice and then loop through the remaining columns and add them as well.
</blockquote></details>

Good idea! Done.
___
*[pkg/sql/opt/props/ordering_choice.go, line 729 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/64501#-MZnozG392ZTPeRqxKeF:-MZo3jaH5M2PzLtJG7Xx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/73c6b2cb160fa8731f64817ee8b9ca97a86d6021/pkg/sql/opt/props/ordering_choice.go#L729)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I'd name it `RestrictToCols`
</blockquote></details>

Done.

**Pull request merged**
