### PR TITLE
sql: implement SHOW CREATE SEQUENCE

### PR DESCRIPTION
**Pull request by vilterp**
...including adding sequences to `crdb_internal.create_statements`. (The impetus for this is adding sequences to `cockroach dump`, since the dump command queries this table to get its create statements).

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
Yep, good stuff. Minor nits remaining.

---

Reviewed 3 of 3 files at r1, 8 of 8 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/sql/show_create.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-L1yJXpJt1JfG0jYBY-C:-L1yJXpJt1JfG0jYBY-D:b61023z) ([raw file](https://github.com/cockroachdb/cockroach/blob/87f009e577861d74d1cdd08d3364c30dc7bc7e4d/pkg/sql/show_create.go#L134)):*
> ```Go
> 	var buf bytes.Buffer
> 	buf.WriteString("CREATE SEQUENCE ")
> 	tn.Format(&buf, tree.FmtSimple)
> ```

`tree.FormatNode(&buf, tree.FmtSimple, tn)`

---

*[pkg/sql/show_create.go, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-L1yJbAqRJWK8uTyJpdW:-L1yJbAqRJWK8uTyJpdX:b-eanug6) ([raw file](https://github.com/cockroachdb/cockroach/blob/87f009e577861d74d1cdd08d3364c30dc7bc7e4d/pkg/sql/show_create.go#L136)):*
> ```Go
> 	tn.Format(&buf, tree.FmtSimple)
> 	opts := desc.SequenceOpts
> 	buf.WriteString(fmt.Sprintf(" MINVALUE %d", opts.MinValue))
> ```

Wait no
`fmt.Fprintf(&buf, " MINVALUE %d", opts.MinValue)`
here and below

---

*[pkg/sql/show_test.go, line 410 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-L1yJlHgDoIMJq3LzLxD:-L1yJlHgDoIMJq3LzLxE:b7nv0z0) ([raw file](https://github.com/cockroachdb/cockroach/blob/426f7bb829bddefdcb4448eea2d49a98d90837a0/pkg/sql/show_test.go#L410)):*
> ```Go
> 			name := fmt.Sprintf("t%d", i)
> 			stmt := fmt.Sprintf(test.create, name)
> 			fmt.Println("XXXXXXXX", stmt)
> ```

XXXXXXXXX?

---

*[pkg/sql/parser/sql.y, line 2905 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-L1yJt0CtBxxWXAH3CAZ:-L1yJt0DbDIJYXcMlYDv:b-g6jp2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/426f7bb829bddefdcb4448eea2d49a98d90837a0/pkg/sql/parser/sql.y#L2905)):*
> ```Yacc
> // %Text: SHOW CREATE SEQUENCE <seqname>
> show_create_sequence_stmt:
> 	SHOW CREATE SEQUENCE var_name
> ```

tabs not spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-:-L1yJwZ35TSjCVedKxSY:bp5amwt)*

**Comment by vilterp** [comment]
Reviewed 8 of 8 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/sql/show_create.go, line 134 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-L1yJXpJt1JfG0jYBY-C:-L1yLZXK_KLIQObtUMZX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87f009e577861d74d1cdd08d3364c30dc7bc7e4d/pkg/sql/show_create.go#L134)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

`tree.FormatNode(&buf, tree.FmtSimple, tn)`
</blockquote></details>

Done.

---

*[pkg/sql/show_create.go, line 136 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-L1yJbAqRJWK8uTyJpdW:-L1yLadTKmADuhFG4vwG:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/87f009e577861d74d1cdd08d3364c30dc7bc7e4d/pkg/sql/show_create.go#L136)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Wait no
`fmt.Fprintf(&buf, " MINVALUE %d", opts.MinValue)`
here and below
</blockquote></details>

Done.

---

*[pkg/sql/show_test.go, line 410 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-L1yJlHgDoIMJq3LzLxD:-L1yLbFQ2vT60_MJ5k6q:bpc77xs) ([raw file](https://github.com/cockroachdb/cockroach/blob/426f7bb829bddefdcb4448eea2d49a98d90837a0/pkg/sql/show_test.go#L410)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

XXXXXXXXX?
</blockquote></details>

Done. Whoops, leftover debug statement.

---

*[pkg/sql/parser/sql.y, line 2905 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-L1yJt0CtBxxWXAH3CAZ:-L1yLehTqxXJ3A6Th68A:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/426f7bb829bddefdcb4448eea2d49a98d90837a0/pkg/sql/parser/sql.y#L2905)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

tabs not spaces
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 7 of 8 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-:-L1yRZrm5c3eEO5NTZgR:bnfp4nl)*

**Comment by knz** [comment]
some test needed in help_test.go

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21208#-:-L1yReLUr6X15rh2hGpO:b8rrmal)*

**Comment by vilterp** [comment]
TFTR. Added a test to `help_test` (always forget that), but I can't figure out how to generate the BNF s.t. the build doesn't fail with a [workspace not clean error](https://teamcity.cockroachdb.com/viewLog.html?tab=buildLog&logTab=tree&filter=debug&expand=all&buildId=466159&_focus=1782).

Tried `make generate`; didn't change the BNF.

**Comment by knz** [comment]
`make generate PKG=./docs/...`

**Pull request merged**
