### PR TITLE
Makefile: regen DEPS.bzl on vendor update

### LINKED ISSUE #56128: bazel: vendor bumps without corresponding DEPS.bzl updates not being picked up by CI
Looks like we managed to [bump datadriven](https://github.com/cockroachdb/cockroach/pull/55867/commits/97442a0ecf5e741c3f2c09fd10113c6d7119de3f) without CI shouting about a missing corresponding update to DEPS.bzl,  Yevgeniy ended up picking up [here](https://github.com/cockroachdb/cockroach/pull/56127/files#diff-4684e52b2f07cacef882d7349c4c93909074491cfb9594f27f8e7ebf717ca0a5). I’m not sure how. I’m guessing nobody else is running into it either since it isn’t blocking other PRs right now.

### PR DESCRIPTION
**Pull request by otan**
Resolves #56128

Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
Doh.

**Comment by otan** [comment]
bors r=irfansharif,jlinder

**Comment by otan** [comment]
bors r=irfansharif,jlinder

**Comment by otan** [comment]
wat

bors r-

**Comment by otan** [comment]
bors r=irfansharif,jlinder

oh woops!

**Pull request merged**
