### PR TITLE
sql: extend TestParse2 and fix parse-print-parse for EXTRACT.

### LINKED ISSUE #9705: sql: EXTRACT does not pretty-print to parsable syntax
the cycle parse -> prettyprint -> parse is broken for EXTRACT:

```
EXTRACT(SECOND FROM NOW())
-- prints to
EXTRACT('second', NOW())
-- parses to
syntax error
```

This breaks history normalization from d4df9a804211b92df089916004f04f0cc08a68f3.

I think the fix is simply to enable parsing `extract(string, expr)` as an expression in addition to / next to `extract(identifier from ...)`

cc @mjibson

### PR DESCRIPTION
**Pull request by knz**
Fixes #9705.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9715)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/sql.y, line 3773 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9715#-KTFwC4I4oti8KIk4JyH:-KTFwC4I4oti8KIk4JyI:bz1s4ww) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9fb69337e4b759711a7a4b7c129b408b2439d8/sql/parser/sql.y#L3773)):*
> ```Yacc
>     $$.val = &FuncExpr{Name: WrapQualifiedFunctionName($1), Exprs: $3.exprs()}
>   }
> | EXTRACT '(' a_expr ',' a_expr ')'
> ```

I'm surprised we need this at all. Why doesn't this syntax get picked up by `func_application`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9715)*

**Comment by knz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[sql/parser/sql.y, line 3773 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9715#-KTFwC4I4oti8KIk4JyH:-KTG1XClcqRG-yGAVLsQ:b-mob833) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9fb69337e4b759711a7a4b7c129b408b2439d8/sql/parser/sql.y#L3773)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> I'm surprised we need this at all. Why doesn't this syntax get picked up by `func_application`?
</details>
Because EXTRACT is a col_name_keyword. The comment says:
```
// The type names appearing here are not usable as function names because they
// can be followed by '(' in typename productions, which looks too much like a
// function call for an LR(1) parser. 
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9715)*

**Comment by mjibson** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[sql/parser/parse_test.go, line 742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9715#-KTG5_FgbpUAJ6pipipr:-KTG5_FgbpUAJ6pipips:b-dskzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9fb69337e4b759711a7a4b7c129b408b2439d8/sql/parser/parse_test.go#L742)):*
> ```Go
> 		// Special overlay syntax
> 		{`SELECT OVERLAY('w333333rce' PLACING 'resou' FROM 3)`,
> 			`SELECT OVERLAY('w333333rce' PLACING 'resou' FROM 3)`},
> ```

All of the other special functions convert these into normal function calls. Why is overlay special? Can we change its String() to do the normal thing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9715)*

**Comment by knz** [comment]
OverlayExpr is dead, long live FuncExpr.

PTAL

---

Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/parser/parse_test.go, line 742 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/9715#-KTG5_FgbpUAJ6pipipr:-KTGUSv9YgWo2iG-ca9B:bw6oa6t) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c9fb69337e4b759711a7a4b7c129b408b2439d8/sql/parser/parse_test.go#L742)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> All of the other special functions convert these into normal function calls. Why is overlay special? Can we change its String() to do the normal thing?
</details>
Indeed. I have killed OverlayExpr accordingly. Thanks for the suggestion.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9715#-:-KTGUY4lRk4LDgkFf80y:bdu8z6u)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/9715#-:-KTGYsTdLerw874stWpt:bnfp4nl)*

**Pull request merged**
