### PR TITLE
sql: add CREATE_TABLE to crdb_internal.tables

### PR DESCRIPTION
**Pull request by madelynnblue**
Make that and SHOW CREATE TABLE only print the table name (and not the
database name) in the CREATE TABLE statement. This is because these
statements are intended to use to create new tables in any database, so
we don't want to tie the output to a single database.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13795)

### CODE REVIEW

**Comment by a-robinson** [comment]
Should this affect views as well?

**Comment by mjibson** [comment]
@a-robinson I'm not sure what you mean. Could you explain more? Is there a test that needs to be added for views or something?

**Comment by a-robinson** [comment]
I mean should `SHOW CREATE VIEW` also only print the table name (and not the database name) in the `CREATE VIEW` statement?

**Comment by mjibson** [comment]
I didn't know that was a statement. Yes, I've made that change too.

**Comment by a-robinson** [comment]
Thanks! 👍

**Review by danhhz — APPROVED** [review]

**Pull request merged**
