### PR TITLE
storage: GC range keys by unsetting identical suffixes

### PR DESCRIPTION
**Pull request by jbowens**
In CockroachDB's key encoding some keys have multiple logically equivalent but physically distinct encodings. Most notably, in CockroachDB versions 23.2 and earlier keys written to global tables encoded MVCC timestamps with a 'synthetic bit.' In #101938 CockroachDB stopped encoding and decoding this synthetic bit, transparently ignoring it.

In #129592 we observed the existence of a bug in the CockroachDB comparator when comparing two MVCC timestamp suffixes, specifically outside the context of a full MVCC key. The comparator failed to consider a timestamp with the synthetic bit and a timestamp without the synthetic bit as logically equivalent. There are limited instances where Pebble uses the comparator to compare "bare suffixes," and all instances are constrained to the implementation of range keys.

In #129592 it was observed that the comparator bug could prevent the garbage collection of MVCC delete range tombstones (the single use of range keys within CockroachDB). A cluster running 23.2 or earlier may write a MVCC delete range tombstone with a timestamp encoding the synthetic bit. If the cluster subsequently upgraded to 24.1 or later, the code path to clear range keys stopped understanding synthetic bits and wrote range key unset tombstones without the synthetic bit set. Due to the comparator bug, Pebble did not consider these timestamp suffixes equal and the unset was ineffective.

We initially attempted to fix this issue by fixing the comparator, but inadvertently introduced the possibility of replica divergence #130533 by changing the semantics of LSM state below raft.

This commit works around this comparator bug by adapting ClearMVCCRangeKey to write range key unsets using the verbatim suffix that was read from the storage engine. To avoid reverting #101938 and re-introducing knowledge of the synthetic bit, the MVCCRangeKey data structures are adapted to retain a copy of the encoded timestamp suffix when reading range keys from storage engine iterators. If later an attempt is made to clear the range key through ClearMVCCRangeKey, this encoded timestamp suffix is used instead of re-encoding the timestamp. Through avoiding the decoding/encoding roundtrip, ClearMVCCRangeKey ensures that the suffixes it writes are identical to the range keys that exist on disk, even if they encode a synthetic bit.

Release note (bug fix): Fixes a bug that could result in the inability to garbage collect a MVCC range tombstone within a global table.
Epic: none
Informs #129592.

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
This looks very nice and clean!  I will take a second more detailed look later today.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-:-O6b8JZBCVxIniKRLfFc:bk9a21h)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @nvanbenschoten, and @sumeerbhola)

**Review by RaduBerinde — COMMENTED** [review]
`master` still has the comparator fix, so I'd expect the `range_keys_clear_synthetic_bit` test to pass regardless of the change (can you verify that?)  We should try the patch on `release-24.2`

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-:-O6b91YN3JIaMo_9yz47:b8vuq1c)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @nvanbenschoten, and @sumeerbhola)

**Review by jbowens — COMMENTED** [review]
Yeah, I confirmed that the tests pass on 24.2

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-:-O6bD2NS9whdwJA5qh_G:bcbacvv)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @nvanbenschoten, and @sumeerbhola)

**Review by nvb — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @jbowens, and @sumeerbhola)

___
*[`-- commits` line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6bWZDeE1_z_XAZ9CTJ):*
Nice writeup on the history of this issue!
___
*[`pkg/storage/pebble_iterator.go` line 750 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6bXb6gAbxAjr3FCqZg:-O6bXb6gAbxAjr3FCqZh:b-nyk1q7) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de835f14b156699ab066d69f47c36c13e1172b8/pkg/storage/pebble_iterator.go#L750)):*
> ```Go
> 			Timestamp:              timestamp,
> 			Value:                  rangeKey.Value,
> 			EncodedTimestampSuffix: rangeKey.Suffix,
> ```

Will this memory be invalidated when the iterator is advanced?

The reason I had suggested a `copySuffix` param in the doc was so that we could conditionally perform a memcpy here, but maybe that isn't needed.
___
*[`pkg/storage/mvcc_history_test.go` line 1939 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6bYFQc9M-NN6XZeYV6:-O6bYFQc9M-NN6XZeYV7:b-krzxob) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de835f14b156699ab066d69f47c36c13e1172b8/pkg/storage/mvcc_history_test.go#L1939)):*
> ```Go
> 	// range key writes will use and we want to exercise it. See #129592.
> 	if e.hasArg("syntheticBit") {
> 		suffix := storage.EncodeMVCCTimestampSuffixWithSyntheticBitForTesting(rangeKey.Timestamp)
> ```

nit: any reason this isn't inside the `withWriter` function with the `EncodeMVCCValue` call?
___
*[`pkg/storage/mvcc_test.go` line 5404 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6bYUVuEZ0kjO9cpdFQ:-O6bYUVuEZ0kjO9cpdFR:b-jinf27) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de835f14b156699ab066d69f47c36c13e1172b8/pkg/storage/mvcc_test.go#L5404)):*
> ```Go
> 		} else {
> 			rw := mvccRangeKeyEncodedTimestampReadWriter{engine}
> 			// rw := engine
> ```

nit: stale comment?
___
*[`pkg/storage/mvcc_test.go` line 5416 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6bYdqT1Q9IW28qzOJi:-O6bYdqT1Q9IW28qzOJj:bh259z1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de835f14b156699ab066d69f47c36c13e1172b8/pkg/storage/mvcc_test.go#L5416)):*
> ```Go
> // mvccRangeKeyEncodedTimestampReadWriter wraps a ReadWriter, overriding
> // PutMVCCRangeKey so that if MVCCRangeKey.EncodedTimestampSuffix is non-empty,
> // the resulting range key uses the encoded suffix varbatim. This is a bit of a
> ```

s/varbatim/verbatim/
___
*[`pkg/storage/mvcc_test.go` line 5423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6bZi2VDPOL562PGKpx:-O6bZi2VDPOL562PGKpy:b-18bsi3) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de835f14b156699ab066d69f47c36c13e1172b8/pkg/storage/mvcc_test.go#L5423)):*
> ```Go
> // TODO(jackson): Remove this when we've guaranteed that all range keys have
> // timestamps without the synthetic bit.
> type mvccRangeKeyEncodedTimestampReadWriter struct {
> ```

Consider mentioning somewhere in this comment that the production ReadWriter implementations only use `EncodedTimestampSuffix` in their `ClearMVCCRangeKey` methods, not in their `PutMVCCRangeKey` methods.

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @nvanbenschoten, @stevendanna, and @sumeerbhola)

___
*[`pkg/storage/pebble_iterator.go` line 750 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6bXb6gAbxAjr3FCqZg:-O6c2vRX82Btfva6LXTZ:btzq56g) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de835f14b156699ab066d69f47c36c13e1172b8/pkg/storage/pebble_iterator.go#L750)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Will this memory be invalidated when the iterator is advanced?

The reason I had suggested a `copySuffix` param in the doc was so that we could conditionally perform a memcpy here, but maybe that isn't needed.
</blockquote></details>

It may (whether it was invalidated is dependent on the value of RangeKeyChanged() after the next iterator operation) , but that's true of the entire `MVCCRangeKeyStack` structure we return. The bounds user keys will be invalidated, and we'll reuse the `p.mvccRangeKeyVersions` slice to hold `stack.Versions` too. We rely on the caller `Clone`/`CloneInto`-ing if necessary
___
*[`pkg/storage/mvcc_history_test.go` line 1939 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6bYFQc9M-NN6XZeYV6:-O6c46oGBmsXjX7m_gy3:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de835f14b156699ab066d69f47c36c13e1172b8/pkg/storage/mvcc_history_test.go#L1939)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: any reason this isn't inside the `withWriter` function with the `EncodeMVCCValue` call?
</blockquote></details>

Done
___
*[`pkg/storage/mvcc_test.go` line 5423 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6bZi2VDPOL562PGKpx:-O6c45rp3WKwuhRpInGG:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2de835f14b156699ab066d69f47c36c13e1172b8/pkg/storage/mvcc_test.go#L5423)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Consider mentioning somewhere in this comment that the production ReadWriter implementations only use `EncodedTimestampSuffix` in their `ClearMVCCRangeKey` methods, not in their `PutMVCCRangeKey` methods.
</blockquote></details>

Done

**Comment by RaduBerinde** [comment]
*[`pkg/storage/pebble_batch.go` line 762 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6cLsm87Cth6AurUJ90:-O6cLsm87Cth6AurUJ91:b-b0nwj3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2f157dbc642322dbd944242e48358d5cd2f6c8f/pkg/storage/pebble_batch.go#L762)):*
> ```Go
> 			for _, v := range rangeKeys.Versions {
> 				if err := p.batch.RangeKeyUnset(startRaw, endRaw,
> 					EncodeMVCCTimestampSuffix(v.Timestamp), nil); err != nil {
> ```

I think we need it here too? Is there a way to exercise this code in a test?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @nvanbenschoten, @RaduBerinde, @stevendanna, and @sumeerbhola)

___
*[`pkg/storage/pebble_batch.go` line 762 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6cLsm87Cth6AurUJ90:-O6cdPa0DRilnKfixKd8:b-mvabqg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2f157dbc642322dbd944242e48358d5cd2f6c8f/pkg/storage/pebble_batch.go#L762)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I think we need it here too? Is there a way to exercise this code in a test?
</blockquote></details>

Really good catch—I added a mvcc history test that exercises this code path metamorphically. I started to look at trying to add a GC unit test that could've exercised this code, but it's a bit tricky to get the synthetic bit set on the test data.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @jbowens, @nvanbenschoten, @stevendanna, and @sumeerbhola)

___
*[`pkg/storage/pebble_batch.go` line 762 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6cLsm87Cth6AurUJ90:-O6coPCO71dAWQ1Rw-I0:b8v0gb3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2f157dbc642322dbd944242e48358d5cd2f6c8f/pkg/storage/pebble_batch.go#L762)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Really good catch—I added a mvcc history test that exercises this code path metamorphically. I started to look at trying to add a GC unit test that could've exercised this code, but it's a bit tricky to get the synthetic bit set on the test data.
</blockquote></details>

Great! I audited all calls to EncodeMVCCTimestampSuffic and haven't found anything else.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 9 files at r1, 8 of 9 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-:-O6w9Kcm9F-mlZUdnXzX:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @jbowens, @nvanbenschoten, and @stevendanna)

___
*[`pkg/storage/pebble_batch.go` line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6w739t8N5NQ0bgBr5a:-O6w739t8N5NQ0bgBr5b:b-fc435a) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc0604e6d5b921b68ab63d3c7c339c709d8af18/pkg/storage/pebble_batch.go#L222)):*
> ```Go
> 	}
> 	return wb.PutEngineRangeKey(
> 		rangeKey.StartKey, rangeKey.EndKey, EncodeMVCCTimestampSuffix(rangeKey.Timestamp), value)
> ```

is this also a case where the encoded suffix, if present, could be used?
Was this deliberately omitted since it is used in AddSSTable and export, and we don't want to preserve the synthetic bit in those cases?

`SSTWriter` also has this method.
___
*[`pkg/storage/sst_writer.go` line 270 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6votpSB7M7zxefTDmE:-O6votpSB7M7zxefTDmF:b-63vf1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc0604e6d5b921b68ab63d3c7c339c709d8af18/pkg/storage/sst_writer.go#L270)):*
> ```Go
> 	// write the tombstone to clear it using the same encoding of the timestamp.
> 	// See #129592.
> 	if len(rangeKey.EncodedTimestampSuffix) > 0 {
> ```

just checking my understanding: is it accurate that we never actually unset rangekeys via writing to a sst?
___
*[`pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go` line 1269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6w8CPJ4oWarj0NfRgc:-O6w8CPJ4oWarj0NfRgd:bn5wgec) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc0604e6d5b921b68ab63d3c7c339c709d8af18/pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go#L1269)):*
> ```Go
> 								v.LocalTimestamp.WallTime *= 1e9
> 								kv.RangeKey.Timestamp.WallTime *= 1e9
> 								kv.RangeKey.EncodedTimestampSuffix = storage.EncodeMVCCTimestampSuffix(kv.RangeKey.Timestamp)
> ```

since this is optional, should it randomly choose between setting and not setting, so we don't end up with code that relies on it being set?
___
*[`pkg/kv/kvserver/batcheval/cmd_delete_range_test.go` line 210 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6w8K7BAuXutuXspZBP:-O6w8K7BAuXutuXspZBQ:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc0604e6d5b921b68ab63d3c7c339c709d8af18/pkg/kv/kvserver/batcheval/cmd_delete_range_test.go#L210)):*
> ```Go
> 						EndKey:                 roachpb.Key(tc.end),
> 						Timestamp:              ts,
> 						EncodedTimestampSuffix: storage.EncodeMVCCTimestampSuffix(ts),
> ```

ditto
___
*[`pkg/kv/kvserver/batcheval/knobs_use_range_tombstones_test.go` line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6w8SQhA81RIQ0eanQp:-O6w8SQhA81RIQ0eanQq:bbml9kg) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc0604e6d5b921b68ab63d3c7c339c709d8af18/pkg/kv/kvserver/batcheval/knobs_use_range_tombstones_test.go#L88)):*
> ```Go
> 		case storage.MVCCRangeKeyValue:
> 			kv.RangeKey.Timestamp = hlc.Timestamp{}
> 			kv.RangeKey.EncodedTimestampSuffix = nil
> ```

why explicitly setting it to nil?

**Review by jbowens — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @nvanbenschoten, @stevendanna, and @sumeerbhola)

___
*[`pkg/storage/pebble_batch.go` line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6w739t8N5NQ0bgBr5a:-O6wZnUE4HatbMu-wGyu:b-evh5p2) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc0604e6d5b921b68ab63d3c7c339c709d8af18/pkg/storage/pebble_batch.go#L222)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is this also a case where the encoded suffix, if present, could be used?
Was this deliberately omitted since it is used in AddSSTable and export, and we don't want to preserve the synthetic bit in those cases?

`SSTWriter` also has this method.
</blockquote></details>

Yeah, that's right. We deliberately omitted it so that we explicitly avoid propagating the synthetic bit
___
*[`pkg/storage/sst_writer.go` line 270 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6votpSB7M7zxefTDmE:-O6wZjpV09-FwdxH6YaP:b-890fet) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc0604e6d5b921b68ab63d3c7c339c709d8af18/pkg/storage/sst_writer.go#L270)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

just checking my understanding: is it accurate that we never actually unset rangekeys via writing to a sst?
</blockquote></details>

yeah, that's right
___
*[`pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go` line 1269 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6w8CPJ4oWarj0NfRgc:-O6wZUaICnZDn6S6qRDQ:bzia934) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc0604e6d5b921b68ab63d3c7c339c709d8af18/pkg/kv/kvserver/batcheval/cmd_add_sstable_test.go#L1269)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

since this is optional, should it randomly choose between setting and not setting, so we don't end up with code that relies on it being set?
</blockquote></details>

unfortunately almost all the tests rely on deep equality of the range key, so we need to maintain the suffix on the expectation or update all the tests
___
*[`pkg/kv/kvserver/batcheval/knobs_use_range_tombstones_test.go` line 88 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6w8SQhA81RIQ0eanQp:-O6wZCsm8JgsbyPVTV08:b9unpox) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc0604e6d5b921b68ab63d3c7c339c709d8af18/pkg/kv/kvserver/batcheval/knobs_use_range_tombstones_test.go#L88)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

why explicitly setting it to nil?
</blockquote></details>

To match the above explicit clearing of the `Timestamp` (this test does some wonky things)

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-:-O6wkl38B5y76qE2bU-3:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @aadityasondhi, @jbowens, @nvanbenschoten, and @stevendanna)

___
*[`pkg/storage/pebble_batch.go` line 222 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-O6w739t8N5NQ0bgBr5a:-O6wkbE43jl-axXJ6kOL:b-o726d4) ([raw file](https://github.com/cockroachdb/cockroach/blob/0cc0604e6d5b921b68ab63d3c7c339c709d8af18/pkg/storage/pebble_batch.go#L222)):*
<details><summary><i>Previously, jbowens (Jackson Owens) wrote…</i></summary><blockquote>

Yeah, that's right. We deliberately omitted it so that we explicitly avoid propagating the synthetic bit
</blockquote></details>

Could you add a code comment pointing this out, else someone might think it is an oversight.

**Review by RaduBerinde — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 9 files at r1, 8 of 9 files at r2, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/130572#-:-O733KS57RpUX4sM0VBS:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @aadityasondhi, @jbowens, @nvanbenschoten, @stevendanna, and @sumeerbhola)

**Comment by jbowens** [comment]
TFTRs!

bors r+

**Comment by rail** [comment]
blathers backport staging-v24.2.2

**Comment by jbowens** [comment]
blathers backport release-24.2.3-rc

**Pull request merged**
