### PR TITLE
storage: Include range IDs in stack traces inside withRaftGroupLocked

### PR DESCRIPTION
**Pull request by bdarnell**
withRaftGroup has the useful property of appearing on a lot of stack
traces that get logged (often due to panics in the raft code, but also
when sampling goroutine stacks of a running servers). Add a dummy
wrapper function with the range ID as an argument so that these stack
traces will include the range ID to assist in debugging.

Release note: None

### CODE REVIEW

**Review by petermattis — COMMENTED** [review]
:lgtm: Do we want to say this fixes https://github.com/cockroachdb/cockroach/issues/11684?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27297#-:-LH-ch879oPrBiLGbBuA:btfiznv)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by bdarnell** [comment]
Ah, I forgot we had an old issue for this. I'll refactor this a bit to apply it to r.Send too and then it'll definitely close that issue.

**Comment by bdarnell** [comment]
OK, applied it to Send too (although it turns out the value is already visible from the first bytes of the BatchRequest proto). I removed the ababab hack because it didn't seem to reliably appear, and just moved the argument to the first position instead.

**Review by tbg — APPROVED** [review]
:lgtm:
In your example, the rangeID is the fourth word passed into the function. Is my understanding correct:
First word: receiver, i.e. a pointer. Second and third word: the `ctx`, which is probably passed as a fat pointer that contains the type of the impl (0x64bfb80?). I think it would even be acceptable to move the `rangeID` ahead of the context.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/27297#-:-LH23TUj2xSjJmiwvNjP:btt0f9a)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale)

**Comment by bdarnell** [comment]
> In your example, the rangeID is the fourth word passed into the function. Is my understanding correct: First word: receiver, i.e. a pointer. Second and third word: the `ctx`, which is probably passed as a fat pointer that contains the type of the impl (0x64bfb80?).

Yes, that's my understanding too, although I sometimes see things that I can't explain in these argument lists. 

> I think it would even be acceptable to move the `rangeID` ahead of the context.

Golint doesn't.

**Pull request merged**
