### PR TITLE
sql: fix CREATE TABLE AS with subqueries, also cure major wart

### LINKED ISSUE #23002: sql: Cannot use subqueries when using select statements to create tables
```
root@:26257/t> create table test as select * from pg_catalog.pg_proc as pro where pro.pronamespace in (select "id" from namespace);
pq: programming error: subquery 2 ("(SELECT id FROM namespace)") not started prior to evaluation
```
The above create table statement fails, even though the query itself is valid:
```
root@:26257/t> select * from pg_catalog.pg_proc as pro where pro.pronamespace in (select "id" from namespace);
+-----+---------+--------------+----------+---------+---------+---------+-------------+--------------+----------+-------------+-----------+--------------+-------------+-----------+-------------+-------------+----------+-----------------+------------+-------------+----------------+-------------+-------------+----------------+-------------+--------+--------+-----------+--------+
| oid | proname | pronamespace | proowner | prolang | procost | prorows | provariadic | protransform | proisagg | proiswindow | prosecdef | proleakproof | proisstrict | proretset | provolatile | proparallel | pronargs | pronargdefaults | prorettype | proargtypes | proallargtypes | proargmodes | proargnames | proargdefaults | protrftypes | prosrc | probin | proconfig | proacl |
+-----+---------+--------------+----------+---------+---------+---------+-------------+--------------+----------+-------------+-----------+--------------+-------------+-----------+-------------+-------------+----------+-----------------+------------+-------------+----------------+-------------+-------------+----------------+-------------+--------+--------+-----------+--------+
+-----+---------+--------------+----------+---------+---------+---------+-------------+--------------+----------+-------------+-----------+--------------+-------------+-----------+-------------+-------------+----------+-----------------+------------+-------------+----------------+-------------+-------------+----------------+-------------+--------+--------+-----------+--------+
(0 rows)

Time: 4.41ms
```

### PR DESCRIPTION
**Pull request by knz**
Prior to this patch, CREATE TABLE AS would instantiate a logical plan
for its query operand once during the prepare phase, and then *again*
during execution so that it could use the same logic as the INSERT
statement.

This was done because it is not possible to instantiate the same logic
as the INSERT statement during the prepare phase, when the descriptor
for the newly created table doesn't exist yet.

Unfortunately, doing so created a problem at some point in the 2.0
development cycle, when the handling of subqueries was improved to
collect the subqueries in the top-level plan structure
(planner.curTop): if there are any subqueries in the CREATE TABLE AS
operand, the 2nd plan creation would fail to initialize their subquery
nodes properly!

This patch fixes this by keeping the logical plan created during the
prepare phase and using it to fetch the rows to insert in the execute
phase. This fixes the problem with subqueries and avoids duplicating
the logical planning work, which was a major wart ever since CREATE
TABLE AS was initially implemented.

This is achieved by avoiding to reuse the entirety of the INSERT logic
and using a simplified insert loop.

This also fixes an obscure bug where CREATE TABLE AS would incorrectly
autocommit when used as a data source (either in CTE or as an operand
of [SHOW TRACE ... ]).

Release note (bug fix): CREATE TABLE AS can now be used again with
scalar subqueries.

Fixes #23002.

### CODE REVIEW

**Comment by knz** [comment]
cc @rytaft

**Comment by knz** [comment]
ping

**Comment by jordanlewis** [comment]
Taking a look at this today, sorry for the delay

**Comment by jordanlewis** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/logictest/testdata/logic_test/create_as, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23017#-L6YRTwvh1s0E3kGIG71:-L6YRTwvh1s0E3kGIG72:bsd2c25) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d85b1d3b3e45717a820872997810b74b6f1387/pkg/sql/logictest/testdata/logic_test/create_as#L104)):*
> ```
> # Check that CREATE TABLE AS can use subqueries (#23002)
> query I
> CREATE TABLE foo4 (x) AS SELECT (SELECT 1); SELECT * FROM foo4
> ```

Can you please add a heavier-weight test? Making sure that it still works when the subquery actually has to read from another table, for example.

I understand that the logic you're adding might not be different in this case, however it strikes me as an important regression case.

---

*[pkg/sql/logictest/testdata/logic_test/show_trace, line 242 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23017#-L6YRK_z6alz5Wa5j2gG:-L6YRK_z6alz5Wa5j2gH:b-dnrg00) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d85b1d3b3e45717a820872997810b74b6f1387/pkg/sql/logictest/testdata/logic_test/show_trace#L242)):*
> ```
> 1   starting plan   fetched: /kv/primary/2/v -> /3
> 1   starting plan   CPut /Table/53/1/...PK.../0 -> /TUPLE/1:1:Int/2/1:2:Int/3
> 25  dist sender     querying next range at /Table/53/1/...PK.../0
> ```

I'm very confused by the change in this trace! Can you explain it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23017#-:-L6YRdqr-U4d0gaJ0JW8:bnfp4nl)*

**Comment by knz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/logictest/testdata/logic_test/create_as, line 104 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23017#-L6YRTwvh1s0E3kGIG71:-L6vcIEGMYYZ6-zg99CD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d85b1d3b3e45717a820872997810b74b6f1387/pkg/sql/logictest/testdata/logic_test/create_as#L104)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you please add a heavier-weight test? Making sure that it still works when the subquery actually has to read from another table, for example.

I understand that the logic you're adding might not be different in this case, however it strikes me as an important regression case.
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/show_trace, line 242 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/23017#-L6YRK_z6alz5Wa5j2gG:-L6vfMZ3FTuY3muZg856:b-8xhk89) ([raw file](https://github.com/cockroachdb/cockroach/blob/10d85b1d3b3e45717a820872997810b74b6f1387/pkg/sql/logictest/testdata/logic_test/show_trace#L242)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I'm very confused by the change in this trace! Can you explain it?
</blockquote></details>

This was an artifact of the different ordering of KV operations in the code for the INSERT statement and this new code. I have inserted a new intermediate commit that changes the way the trace tests are written, to hide this distinction. As you can see, once the trace test is done differently (1st commit), the main change in this PR does not cause any tracing changes any more.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23017)*

**Comment by knz** [comment]
TFYR!

**Pull request merged**
