### PR TITLE
rac2,replica_rac2: implement Processor.AdmitForEval

### LINKED ISSUE #129522: rac2: implement Processor.AdmitForEval
Epic [CRDB-37515](https://cockroachlabs.atlassian.net/browse/CRDB-37515)

Jira issue: CRDB-41572

### PR DESCRIPTION
**Pull request by sumeerbhola**
- RangeController.WaitForEval is changed to additionally return a waited
  bool, so that it conforms to the callers expectation that (false, nil)
  will be returned when the RangeController is closed during waiting.
  This allows the caller to wait on the local store (before eval) and
  not completely bypass all AC.
- Processor.AdmitForEval consults the existing
  kvadmission.flow_control.mode cluster setting to decide whether a
  request should be subject to replication AC, and if yes, forwards to
  the RangeController.

Fixes #129522

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
First commit is from https://github.com/cockroachdb/cockroach/pull/129521

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129573#-:-O5-KtBQBxLaM6GNquwt:bnvx596)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by kvoli — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129573#-:-O5EuaVXC3APVMsat26N:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv)

**Comment by sumeerbhola** [comment]
TFTR!

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
