### PR TITLE
storage: persist minimum transaction timestamps in intents

### LINKED ISSUE #36089: roachtest: kv/contention/nodes=4 failed
SHA: https://github.com/cockroachdb/cockroach/commits/c59f5347d5424edb90575fb0fd50bad677953752

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=kv/contention/nodes=4 PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1195732&tab=buildLog

```
The test failed on release-19.1:
	ts_util.go:89,kv.go:186,cluster.go:1605,errgroup.go:57: spent 5.263158% of time below target of 10.000000 txn/s, wanted no more than 5.000000%
	cluster.go:1626,kv.go:189,test.go:1214: Goexit() was called

```

### PR DESCRIPTION
**Pull request by nvb**
Fixes #36089.
Informs #37199.

This commit addresses the second concern from https://github.com/cockroachdb/cockroach/pull/37199#issuecomment-488283038 by implementing its suggestion #1.

It augments the TxnMeta struct to begin storing the transaction's minimum timestamp. This allows pushers to have perfect accuracy into whether an intent is part of a transaction that can eventually be committed or whether it has been aborted by any other pusher and uncommittable.

This allows us to get rid of the false positive cases where a pusher incorrectly detects that a transaction is still active and begins waiting on it. In this worst case, this could lead to transactions waiting for the entire transaction expiration for a contending txn.

@tbg I'm assigning you because you reviewed most of the lazy transaction record stuff (especially #33523), but let me know if you'd like me to find a different reviewer.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Here's some confirmation that this addresses the remaining txn stalls in `kv/contention/nodes=4`:

Screen Shot 2019-07-09 at 11 59 28 PM

_before on left, after on right_

**Review by tbg — APPROVED** [review]
:lgtm_strong: neat.

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, 6 of 6 files at r3, 3 of 3 files at r4, 22 of 22 files at r5, 7 of 7 files at r6, 27 of 27 files at r7, 3 of 3 files at r8, 22 of 22 files at r9, 7 of 7 files at r10, 2 of 2 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-:-LjRUIgtCcXSTrmORLqr:b-oxv5qn)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_tscache.go, line 297 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRRzNc1cdgKe0Joo3m:-LjRRzNc1cdgKe0Joo3n:bwpbtqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/replica_tscache.go#L297)):*
> ```Go
> 
> // CanCreateTxnRecord determines whether a transaction record can be created
> // for the provided transaction information. Callers should provide the
> ```

s/should/must/
___
*[pkg/storage/replica_tscache.go, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRS5f28T7teOVjZI3e:-LjRS5f28T7teOVjZI3f:b-thzqk1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/replica_tscache.go#L299)):*
> , that is, the epoch zero OrigTimestamp.
___
*[pkg/storage/replica_tscache.go, line 305 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRR6jU13sqZSwnCcAX:-LjRR6jV6DXyu4V1ZG2Y:b-td8pvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/replica_tscache.go#L305)):*
> ```Go
> // it returns the reason that transaction record was rejected. If the method
> // ever determines that a transaction record must be rejected, it will continue
> // to reject that transaction going forwards.
> ```

While you're here, you could also point out that if this method returns true, we may still fail to create the record because there's no locking here. Maybe this is clear already.
___
*[pkg/storage/replica_tscache.go, line 309 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRRc4S30Vrl_MSEJtc:-LjRRc4TAB9oef4k5VCJ:b-nlb61d) ([raw file](https://github.com/cockroachdb/cockroach/blob/813b0146e763e8f44c4cb45e498e68e6ace9bc2d/pkg/storage/replica_tscache.go#L309)):*
> ```Go
> // provisional commit timestamp because it may have moved forward over the
> // course of a single epoch and they can't provide their (current epoch's)
> // OrigTimestamp because it may have moved forward over a series of prior
> ```

Feel like I've asked this before, but wasn't `EpochZeroTimestamp` the thing folks wanted to pass here? Why not?
I also assume callers that had only seen an intent sometimes need this and could only provide something larger than optimal, but this isn't in the old comment.

Nice that this all simplifies with this PR.
___
*[pkg/storage/batcheval/transaction.go, line 165 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRS_0N3NV9bXvF5t0M:-LjRS_0N3NV9bXvF5t0N:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/batcheval/transaction.go#L165)):*
> ```Go
> 		// that we can remove it in v20.1 and replace it with:
> 		//
> 		//  synthTxnRecord.Status = roachpb.ABORTED
> ```

:thumbsup: 
___
*[pkg/storage/rangefeed/processor.go, line 272 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRT269-kAb_cGoVRBq:-LjRT269-kAb_cGoVRBr:blbj2ny) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/rangefeed/processor.go#L272)):*
> ```Go
> 							// harmless, especially because the txnPushAttempt performs a
> 							// high-priority push.
> 							MinTimestamp: txn.timestamp,
> ```

We can't have the real minTimestamp here?

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38782)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/replica_tscache.go, line 297 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRRzNc1cdgKe0Joo3m:-LjS4J4fEKvTsJqwqBcS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/replica_tscache.go#L297)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

s/should/must/
</blockquote></details>

Done.
___
*[pkg/storage/replica_tscache.go, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRS5f28T7teOVjZI3e:-LjS51ZP41nm-7ghHLvF:b-fldv64) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/replica_tscache.go#L299)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> , that is, the epoch zero OrigTimestamp.
</blockquote></details>

The notion of an "epoch zero OrigTimestamp" is part of what I'm trying to get rid of here. The contract we want from this timestamp is that it's the minimum timestamp that a transaction could have ever written. Mixing this up with epochs and the OrigTimestamp (which I'd like to rename to the read timestamp) just confuses all of this.
___
*[pkg/storage/replica_tscache.go, line 305 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRR6jU13sqZSwnCcAX:-LjS5Wl8B_cE4rrVSAXU:b-6j4nt0) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/replica_tscache.go#L305)):*
> because there's no locking here

Latching provides this locking. No request that would update the timestamp cache to prevent a txn record from being created could be evaluating concurrently.
___
*[pkg/storage/replica_tscache.go, line 309 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRRc4S30Vrl_MSEJtc:-LjS4Lm-3qmoafxS7A4m:b-9y9rcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/813b0146e763e8f44c4cb45e498e68e6ace9bc2d/pkg/storage/replica_tscache.go#L309)):*
> but wasn't EpochZeroTimestamp the thing folks wanted to pass here

Yes, but that field is only populated after a restart. We were passing the result of `InclusiveTimeBounds` here before, which accounted for this.

> I also assume callers that had only seen an intent sometimes need this and could only provide something larger than optimal

Yes, that's correct 

> but this isn't in the old comment.

The old comment discussed the false negatives that could occur if this timestamp wasn't the real min timestamp. The (now removed) comment in `cmd_push_txn.go` discussed the actual implications of this.
___
*[pkg/storage/rangefeed/processor.go, line 272 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRT269-kAb_cGoVRBq:-LjS0KMp39PtzDcs4k8Z:b5vs5j9) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/rangefeed/processor.go#L272)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

We can't have the real minTimestamp here?
</blockquote></details>

We'd need to ship in through the `LogicalOpLog` as an `MVCCLogicalOp`. That doesn't seem worth it and would also cause compatibility concerns.

**Review by tbg — COMMENTED** [review]
> Reviewed 28 of 28 files at r13, 1 of 1 files at r14, 8 of 8 files at r15, 3 of 3 files at r16, 22 of 22 files at r17, 7 of 7 files at r18, 2 of 2 files at r19, 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38782)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/replica_tscache.go, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRS5f28T7teOVjZI3e:-LjSJRVeEQmm5yx5oW2k:bpsbxvn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/replica_tscache.go#L299)):*
That sounds good, but then why not

> , that is, the epoch zero value of the `Timestamp` field (the epoch zero write timestamp).

Were you also planning to rename `Timestamp` to `WriteTimestamp`? That would make sense to me, the role of the two timestamps is confusing enough to those who haven't internalized it over the years.
___
*[pkg/storage/replica_tscache.go, line 305 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRR6jU13sqZSwnCcAX:-LjSJc-O6Bx2viFXs2Hu:b-8deqs4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/replica_tscache.go#L305)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> because there's no locking here

Latching provides this locking. No request that would update the timestamp cache to prevent a txn record from being created could be evaluating concurrently.
</blockquote></details>

But the low water mark could rise over due to unrelated requests rolling over the page and change the outcome?

Now that I looked up this method I'm seeing that it's really just part of the eval context, and there it makes more sense because that restricts who calls it (command evaluation), so latches are assumed. This reminds me that I was hoping to take off the eval context methods from the main replica, but it was a giant yak shave. I should get back to that at some point though.
___
*[pkg/storage/rangefeed/processor.go, line 272 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRT269-kAb_cGoVRBq:-LjSLbR62CpNFAFe2wqM:b62wp52) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/rangefeed/processor.go#L272)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We'd need to ship in through the `LogicalOpLog` as an `MVCCLogicalOp`. That doesn't seem worth it and would also cause compatibility concerns.
</blockquote></details>

That is unfortunate, but on the other hand this line keeps all of the magic in the comments that you removed alive, but in a more subtle way. It directly contradicts the contract of the `MinTimestamp` field. I feel that this is problematic enough to fix.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38782)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/replica_tscache.go, line 299 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRS5f28T7teOVjZI3e:-LjSOdPh2wN2txPAMcmW:b-efghgx) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/replica_tscache.go#L299)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

That sounds good, but then why not

> , that is, the epoch zero value of the `Timestamp` field (the epoch zero write timestamp).

Were you also planning to rename `Timestamp` to `WriteTimestamp`? That would make sense to me, the role of the two timestamps is confusing enough to those who haven't internalized it over the years.
</blockquote></details>

Yes, exactly. The goal is to get the long list of transaction timestamps down to `read_timestamp`, `write_timestamp`, `min_timestamp`, and `max_timestamp`, `last_heartbeat`.

`max_timestamp` might also be due for a rename though, as it's not quite clear from the name what it's actual meaning is. Perhaps `max_uncertain_timestamp`.

Also, hopefully, `last_heartbeat` can also go away when we stop heartbeating individual transactions.
___
*[pkg/storage/replica_tscache.go, line 305 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRR6jU13sqZSwnCcAX:-LjSP_XD6vNE5wTv_K2z:b-g7wsu5) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/replica_tscache.go#L305)):*
> But the low water mark could rise over due to unrelated requests rolling over the page and change the outcome?

Sure, but that wouldn't prevent the request from creating the transaction record. It's no different than any other write that only checks the timestamp cache once. Timestamp cache pressure could create artificial conflicts, but nothing real, so the "race" is immaterial.
___
*[pkg/storage/rangefeed/processor.go, line 272 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRT269-kAb_cGoVRBq:-LjSQfR06k0n9wG9qLdl:bss46j7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/rangefeed/processor.go#L272)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

That is unfortunate, but on the other hand this line keeps all of the magic in the comments that you removed alive, but in a more subtle way. It directly contradicts the contract of the `MinTimestamp` field. I feel that this is problematic enough to fix.
</blockquote></details>

I'm curious what your suggested fix is. It seems to me like it could go one of a few ways:
1. ship the transaction's min timestamp around through the `LogicalOpLog` with the rest of the transaction metadata. This would have compatibility issues with v19.1, so at some level we'll still need this, although I guess we can let the missing min timestamp case fall through to `SynthesizeTxnFromMeta`, which already needs to handle it. Interestingly, this is essentially what we'd get for free if the transaction ID included its minimum timestamp, which is the long term goal for this series of changes.
2. don't set any min timestamp here and formally support txn pushes without one specified by falling back to the old approach of using the write timestamp as the min timestamp when one is not specified, which essentially makes the current compatibility hack set in stone.
3. don't set any min timestamp here and formally support txn pushes without one specified by considering missing records to be aborted. I'm not sure if this works in practice, but we could probably make it work.
4. something else I haven't yet considered.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38782)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/storage/rangefeed/processor.go, line 272 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRT269-kAb_cGoVRBq:-LjT67M4DCsxRMNx8HJ1:b-ucqonv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/rangefeed/processor.go#L272)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I'm curious what your suggested fix is. It seems to me like it could go one of a few ways:
1. ship the transaction's min timestamp around through the `LogicalOpLog` with the rest of the transaction metadata. This would have compatibility issues with v19.1, so at some level we'll still need this, although I guess we can let the missing min timestamp case fall through to `SynthesizeTxnFromMeta`, which already needs to handle it. Interestingly, this is essentially what we'd get for free if the transaction ID included its minimum timestamp, which is the long term goal for this series of changes.
2. don't set any min timestamp here and formally support txn pushes without one specified by falling back to the old approach of using the write timestamp as the min timestamp when one is not specified, which essentially makes the current compatibility hack set in stone.
3. don't set any min timestamp here and formally support txn pushes without one specified by considering missing records to be aborted. I'm not sure if this works in practice, but we could probably make it work.
4. something else I haven't yet considered.
</blockquote></details>

I decided to go with the first option. The migration story ends up being almost the same as it is for normal PushTxn requests and the fact that this will come for free with a change to the transaction ID format was decently compelling. The new field also parallels the existing `TxnKey` field, which is nice. PTAL.

**Review by tbg — APPROVED** [review]
:lgtm_strong: 

> Reviewed 28 of 28 files at r21, 1 of 1 files at r22, 8 of 8 files at r23, 3 of 3 files at r24, 22 of 22 files at r25, 11 of 11 files at r26, 7 of 7 files at r27, 2 of 2 files at r28, 1 of 1 files at r29.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-:-LjUvcyN4vvL87QqnYlj:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/storage/rangefeed/processor.go, line 272 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38782#-LjRT269-kAb_cGoVRBq:-LjUvDXB7V5sVXsxaxSU:brbjvkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c868e1d2566b18a032a05aea641eaaca2fb15ab3/pkg/storage/rangefeed/processor.go#L272)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I decided to go with the first option. The migration story ends up being almost the same as it is for normal PushTxn requests and the fact that this will come for free with a change to the transaction ID format was decently compelling. The new field also parallels the existing `TxnKey` field, which is nice. PTAL.
</blockquote></details>

I was leaning towards option 1 as well when I skimmed this comment last night. Thanks for making the change.

**Pull request merged**
