### PR TITLE
sql: allow manipulating unqualified index names.

### LINKED ISSUE #8800: sql: investiage a PostgreSQL-compatible DROP INDEX syntax
Postgres supports dropping indices using the following syntax [1]:
`DROP INDEX my_index;`

CockroachDB doesn't support that syntax:
```
syntax error at or near "my_index"
drop my_index;
```
Instead it requires
`DROP INDEX my_index@my_table;`

It makes sense to have a syntax that can disambiguate indices by table name.  However, for compatibility with existing code, it also makes sense to drop a matching index without an explicit table name, if there is only one such index.

Is the incompatiblity intentional?

[1]: https://www.postgresql.org/docs/9.2/static/sql-dropindex.html

```
Build Tag:   beta-20160728
Build Time:  2016/07/28 17:02:34
Platform:    linux amd64
Go Version:  go1.6.3
C Compiler:  gcc 4.9.2
```

### PR DESCRIPTION
**Pull request by knz**
With this patch, one can use a simple index name "idxname" instead of
"tablename@idxname" with DROP INDEX and ALTER INDEX.

Fixes #8800.

cc @dt

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10091)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/split.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10091#-KUTYYbWVIe_MwoXghya:-KUTYYbWVIe_MwoXghyb:b-rip4oo) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18b5e7cf3617b641d27de16293cac6faef52fe2/pkg/sql/split.go#L53)):*
> ```Go
> 	}
> 
> 	if n.Index != nil && n.Index.SearchTable {
> ```

Why do we need the check for n.Index != nil here?

Also this if block is repeated almost verbatim (except for this n.Index check) in three places. Can we make a method on `n` to correctly set tn and n.Index?

---

*[pkg/sql/parser/sql.y, line 4391 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10091#-KUTXLbrQYmwnz8zWa_A:-KUTXLbsIoB7mZ_NMaKS:b1kzf6o) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18b5e7cf3617b641d27de16293cac6faef52fe2/pkg/sql/parser/sql.y#L4391)):*
> ```Yacc
>     $$.val = &TableNameWithIndex{Table: $1.normalizableTableName(), Index: Name($3)}
>   }
> | qualified_name
> ```

Why not `name`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10091)*

**Comment by knz** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/split.go, line 53 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10091#-KUTYYbWVIe_MwoXghya:-KUakkakA3Varwo28jN_:bfy3vxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18b5e7cf3617b641d27de16293cac6faef52fe2/pkg/sql/split.go#L53)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Why do we need the check for n.Index != nil here?
> 
> Also this if block is repeated almost verbatim (except for this n.Index check) in three places. Can we make a method on `n` to correctly set tn and n.Index?
</details>
The check for n.Index is because this node is used for both ALTER TABLE ... SPLIT AT and ALTER INDEX ... SPLIT AT.

But I refactored the code as suggested.

---

*[pkg/sql/parser/sql.y, line 4391 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10091#-KUTXLbrQYmwnz8zWa_A:-KUakp0fe4pLkHmI8-JQ:bctvdcg) ([raw file](https://github.com/cockroachdb/cockroach/blob/b18b5e7cf3617b641d27de16293cac6faef52fe2/pkg/sql/parser/sql.y#L4391)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> Why not `name`?
</details>
Because if I don't have a current database in the planner I still want to do e.g. "DROP INDEX mydb.myindex".

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10091)*

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10091#-:-KUxiGe4WV4gMaKcJMHI:bnfp4nl)*

**Comment by knz** [comment]
TFYR!

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10091#-:-KUxj0olHbswbV6qPo1N:b-814cj3)*

**Pull request merged**
