### PR TITLE
sql: track bytes and rows read unconditionally for every statement

### PR DESCRIPTION
**Pull request by yuzefovich**
In order to propagate metrics about bytes and rows read we use
the existing tracing infrastructure, but, instead of using recording
spans, we use recordable ones. All processors get a recordable span,
but only table readers propagate their stats when full tracing is
disabled.

Addresses: #37409.

In order to see the performance hit, I ran `kv` workload with read only queries (I guess it should have the largest hit) and saw a decrease of around 3%. Here is a representative output of 30 seconds of load:
```
With stats:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
   30.0s        0         128368         4278.2      0.2      0.3      0.4      0.6     10.0

Without stats:
_elapsed___errors_____ops(total)___ops/sec(cum)__avg(ms)__p50(ms)__p95(ms)__p99(ms)_pMax(ms)__result
   30.0s        0         131946         4398.1      0.2      0.3      0.4      0.6     10.0 
```

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
At the moment, these metrics are only exposed via storing them in `crdb_internal.node_statement_statistics` table. I think we should show them on the statement detail page, but probably that should be done in a separate PR.

I might not be fully understanding what I'm doing here, so please take a very critical look. Also cc @jordanlewis @andreimatei if you guys have time to take a look as well.

**Comment by ajwerner** [comment]
3% is sort of a bummer, I'm interested in digging in more to the perf implications

**Review by ajwerner — COMMENTED** [review]
```
name             old ops/s   new ops/s   delta
KV99-throughput  42.1k ± 3%  40.3k ± 3%  -4.17%  (p=0.032 n=5+5)

name             old ms/s    new ms/s    delta
KV99-P50          8.10 ± 0%   8.60 ± 3%  +6.17%  (p=0.016 n=4+5)
KV99-Avg          2.64 ± 6%   2.74 ± 6%    ~     (p=0.333 n=5+5)
```

This is with longer runs on your later revision. We're going to need to look at the source of inefficiency. Hopefully we can pre-allocate or pool some objects to mitigate the cost. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-:-LgZ4wkCD-6xmL2gai8Q:bvck2hb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @asubiotto)

**Review by asubiotto — CHANGES_REQUESTED** [review]
This looks good to me minus the performance cost. There are several things you could try out:
1) In the tableReader, tags are set on the span. This is something unnecessary and that we can avoid, although we don't go into `getSpans`, which would be the more expensive part.
2) There is no need to create any spans, this is probably expensive as well. I would just create a RecordedSpan with the `Stats` field set when the `tableReader` returns metadata.

> Reviewed 11 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-:-Lgbz3MnBICxcmA1N9S3:b-tjchbv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 542 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-Lgby73DEIq7y8xunvEb:-Lgby73E0YVcVD_9WKLu:b-1yusmg) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9c853d42ac6c3c3f1b6702d7c238107ca1e248/pkg/sql/distsql_running.go#L542)):*
> ```Go
> 						r.rowsRead += trs.InputStats.NumRows
> 					} else {
> 						// TODO(yuzefovich): what should we do here?
> ```

I think this is fine
___
*[pkg/util/tracing/tracer_span.go, line 250 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LgbyvLQ03a3YWEUxjja:-LgbyvLQ03a3YWEUxjjb:bwbw6a0) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9c853d42ac6c3c3f1b6702d7c238107ca1e248/pkg/util/tracing/tracer_span.go#L250)):*
> ```Go
> 		stats, err := types.MarshalAny(s.mu.stats)
> 		if err != nil {
> 			// TODO(yuzefovich): what should we do here?
> ```

`getSpans` panics as well.

**Comment by yuzefovich** [comment]
Okay, looks like the performance hit is very reasonable in my opinion, so this PR is ready for a look. 

Thanks guys for the help on figuring this out. As it turns out, that huge performance gap in some cases on kv99 workload was due to me not fully implementing the conversion of new metadata which was causing an error which, in turn, was affecting automatic stats collection. I still don't fully understand why the performance sometimes was good, and sometimes it wasn't, but oh well, now it seems consistently good.

Here are the numbers:
kv99 load was run 5 times for 5 minutes with 10 second ramp with 128 concurrency.

(this "new" one was before a minor fix to pass the tests, and the fix should have no performance impart)
```
aws
name             old ops/s   new ops/s   delta
KV99-throughput  27.2k ± 2%  27.0k ± 2%   ~     (p=0.841 n=5+5)

name             old ms/s    new ms/s    delta
KV99-P50          12.9 ± 2%   12.8 ± 2%   ~     (p=1.000 n=5+5)
KV99-Avg          4.02 ± 3%   4.10 ± 0%   ~     (p=0.556 n=5+4)
```
```
gcp
name             old ops/s   new ops/s   delta
KV99-throughput  19.3k ± 1%  19.0k ± 2%  -1.26%  (p=0.032 n=5+5)

name             old ms/s    new ms/s    delta
KV99-P50          17.2 ± 3%   17.4 ± 3%    ~     (p=1.000 n=5+5)
KV99-Avg          5.88 ± 2%   6.00 ± 0%    ~     (p=0.238 n=5+4)
```

(for this one, I used the old benchmark data for the base binary and exactly this PR for the new one, so they ran with some time apart)
```
aws
name             old ops/s   new ops/s   delta
KV99-throughput  27.2k ± 2%  27.5k ± 2%   ~     (p=0.310 n=5+5)

name             old ms/s    new ms/s    delta
KV99-P50          12.9 ± 2%   12.6 ± 0%   ~     (p=0.095 n=5+4)
KV99-Avg          4.02 ± 3%   3.90 ± 0%   ~     (p=0.167 n=5+5)
```
```
gcp
name             old ops/s   new ops/s   delta
KV99-throughput  19.3k ± 1%  18.6k ± 6%  -3.52%  (p=0.016 n=5+5)

name             old ms/s    new ms/s    delta
KV99-P50          17.2 ± 3%   17.8 ± 0%    ~     (p=0.238 n=5+4)
KV99-Avg          5.88 ± 2%   5.92 ± 2%    ~     (p=1.000 n=5+5)
```

And the microbenchmarks (these seem quite noisy and probably not too meaningful anyway for measuring the performance of this change):
```
name                       old time/op    new time/op    delta
TableReader/rows=16-12       39.1µs ± 2%    39.8µs ± 1%   +1.88%  (p=0.000 n=10+9)
TableReader/rows=256-12       131µs ± 3%     137µs ±19%     ~     (p=0.529 n=10+10)
TableReader/rows=4096-12     1.29ms ± 4%    1.50ms ± 5%  +16.33%  (p=0.000 n=10+8)
TableReader/rows=65536-12    20.6ms ± 8%    23.1ms ±26%     ~     (p=0.052 n=10+10)
```
```
name                         old time/op    new time/op    delta
KV/Insert/SQL/rows=10000-12     219ms ± 1%     229ms ± 7%     ~     (p=0.101 n=8+10)
KV/Scan/SQL/rows=1-12           184µs ±17%     163µs ±15%  -11.30%  (p=0.011 n=10+10)
KV/Scan/SQL/rows=10-12          214µs ± 6%     177µs ± 3%  -17.42%  (p=0.000 n=9+9)
KV/Scan/SQL/rows=100-12         284µs ± 6%     282µs ± 4%     ~     (p=0.666 n=9+9)
KV/Scan/SQL/rows=1000-12       1.17ms ± 2%    1.18ms ± 1%   +1.60%  (p=0.004 n=8+10)
KV/Scan/SQL/rows=10000-12      9.77ms ± 7%   10.20ms ± 4%   +4.39%  (p=0.022 n=10+9)
```

**Review by ajwerner — APPROVED** [review]
:lgtm: thanks for doing this!

> Reviewed 23 of 23 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-:-Lgmb7jG1xLMmlsM04fH:bw3kg2j)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsqlpb/data.go, line 216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LgmaHZU7v3z6l6LvAFX:-LgmaHZV9EqXeOWWONeO:b1f9ogz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec8d4e2ff05c2365e33bddb4b67c226819324e2a/pkg/sql/distsqlpb/data.go#L216)):*
> ```Go
> }
> 
> // MetricsMetaPool is a pool of metadata used to propagate metrics.
> ```

My preference would be that this pool not to be exported and instead have strongly typed functions.

**Comment by yuzefovich** [comment]
Friendly ping @asubiotto.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @yuzefovich)

___
*[pkg/sql/distsqlrun/tablereader.go, line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhaKUsa1CjESFzBuhtd:-LhaKUsa1CjESFzBuhte:bg90jt6) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75627361374c07c4fa77977947235e8db6c9035/pkg/sql/distsqlrun/tablereader.go#L363)):*
> ```Go
> 	if mc, ok := tr.input.(*metricsCollector); ok {
> 		meta := distsqlpb.GetMetricsMeta()
> 		meta.Metrics.BytesRead, meta.Metrics.RowsRead = tr.fetcher.GetBytesRead(), mc.rowsRead
> ```

Is it necessary to add a `Metrics` field to metadata instead of just doing something like `distsqlpb.ProducerMetadata{TraceData: []RecordedSpan{Stats: &TableReaderStats{BytesRead: bytes, RowsRead: rows}}}`. We can use a `RecordedSpan` pool. In any case, it would be good to make sure that these bytes are also added to the `EXPLAIN ANALYZE` plan in case of tracing.
___
*[pkg/sql/distsqlrun/tablereader.go, line 377 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhaKGl95SZgA3xjkT0x:-LhaKGl95SZgA3xjkT0y:bfpyttg) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75627361374c07c4fa77977947235e8db6c9035/pkg/sql/distsqlrun/tablereader.go#L377)):*
> ```Go
> // that it is a lightweight version of InputStatCollector - namely, tracking
> // stall time is omitted for performance reasons.
> type metricsCollector struct {
> ```

Why bother with a `metricsCollector`? Since this is unconditional, we could just have the `tableReader` keep track of the number of rows read.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @asubiotto)

___
*[pkg/sql/distsql_running.go, line 542 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-Lgby73DEIq7y8xunvEb:-LhaXzT-Dsm350JAvdLP:bypen0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9c853d42ac6c3c3f1b6702d7c238107ca1e248/pkg/sql/distsql_running.go#L542)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think this is fine
</blockquote></details>

Removed the changes.
___
*[pkg/sql/distsqlpb/data.go, line 216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LgmaHZU7v3z6l6LvAFX:-LhaY0QT30Tw0q-zZCtg:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec8d4e2ff05c2365e33bddb4b67c226819324e2a/pkg/sql/distsqlpb/data.go#L216)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

My preference would be that this pool not to be exported and instead have strongly typed functions. 
</blockquote></details>

Done.
___
*[pkg/sql/distsqlrun/tablereader.go, line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhaKUsa1CjESFzBuhtd:-Lhb4vnj-cyqLpVOKo-7:buo3u8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75627361374c07c4fa77977947235e8db6c9035/pkg/sql/distsqlrun/tablereader.go#L363)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Is it necessary to add a `Metrics` field to metadata instead of just doing something like `distsqlpb.ProducerMetadata{TraceData: []RecordedSpan{Stats: &TableReaderStats{BytesRead: bytes, RowsRead: rows}}}`. We can use a `RecordedSpan` pool. In any case, it would be good to make sure that these bytes are also added to the `EXPLAIN ANALYZE` plan in case of tracing.
</blockquote></details>

The reasoning for adding `Metrics` field was attempt at removing one marshaling/unmarshaling conversion, but the benchmarks do not show significant changes because of that, so I removed it as we discussed.

Bytes read do show up in the output of `EXPLAIN ANALYZE` since they are added to `TableReaderStats` in `outputStatsToTrace`.
___
*[pkg/sql/distsqlrun/tablereader.go, line 377 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhaKGl95SZgA3xjkT0x:-LhaXnPY1Y_Jmu8iex3K:b-586ybz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75627361374c07c4fa77977947235e8db6c9035/pkg/sql/distsqlrun/tablereader.go#L377)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why bother with a `metricsCollector`? Since this is unconditional, we could just have the `tableReader` keep track of the number of rows read.
</blockquote></details>

Indeed, I feel so silly :/
___
*[pkg/util/tracing/tracer_span.go, line 250 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LgbyvLQ03a3YWEUxjja:-LhaXwcyEo6gJLXPmmBs:bypen0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd9c853d42ac6c3c3f1b6702d7c238107ca1e248/pkg/util/tracing/tracer_span.go#L250)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`getSpans` panics as well.
</blockquote></details>

Removed the changes.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @asubiotto)

___
*[pkg/sql/distsqlrun/tablereader.go, line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhaKUsa1CjESFzBuhtd:-LhbrRDN6JG99YOcwc33:b-aerhy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75627361374c07c4fa77977947235e8db6c9035/pkg/sql/distsqlrun/tablereader.go#L363)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The reasoning for adding `Metrics` field was attempt at removing one marshaling/unmarshaling conversion, but the benchmarks do not show significant changes because of that, so I removed it as we discussed.

Bytes read do show up in the output of `EXPLAIN ANALYZE` since they are added to `TableReaderStats` in `outputStatsToTrace`.
</blockquote></details>

My initial change was incomplete - the tests were failing due to duplicate spans. My understanding is that when we leave `SpanID` field of `RecordedSpan` uninitialized, it has value of 0 which belongs to the root span which breaks some assumptions. I think now I have fixed the issue, but rerunning the benchmarks shows slight performance decrease (I believe due to marshaling/unmarshaling as I was thinking earlier). Here are the numbers on `kv99` ran 4 times for 4 minutes with 10 seconds ramp ("old" one is using `Metrics` field and "new" one is this PR at the moment):
```
gcp
name             old ops/s   new ops/s   delta
KV99-throughput  17.8k ± 2%  17.0k ± 3%  -4.39%  (p=0.029 n=4+4)

name             old ms/s    new ms/s    delta
KV99-P50          19.7 ± 7%   20.7 ± 4%    ~     (p=0.257 n=4+4)
KV99-Avg          6.00 ± 0%   6.38 ± 4%  +6.25%  (p=0.029 n=4+4)
```
```
aws
name             old ops/s   new ops/s   delta
KV99-throughput  29.8k ± 1%  29.1k ± 3%    ~     (p=0.200 n=4+4)

name             old ms/s    new ms/s    delta
KV99-P50          11.8 ± 3%   11.8 ± 7%    ~     (p=1.000 n=4+4)
KV99-Avg          3.70 ± 0%   3.80 ± 0%  +2.70%  (p=0.029 n=4+4)
```
The numbers look quite noisy, but it seems that there is a 2-3% performance hit (in addition to about 1% performance hit on `Metrics` binary), so now I'm leaning towards going back to using `Metrics` field again.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 1 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @asubiotto, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 621 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhemUQa1Qt_gm7kTJ9g:-LhemUQb7FwvtAo4sCvD:bokdrmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/75bf1750b91aac8d69c8e0f59e818f30c0b9ccf0/pkg/sql/distsql_running.go#L621)):*
> ```Go
> 		}
> 	}
> 	meta.Release()
> ```

Where is `meta` being acquired from the pool?
___
*[pkg/sql/distsqlrun/tablereader.go, line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhaKUsa1CjESFzBuhtd:-Lhen0ME7rU6mgf7XNIa:b-nbyo5y) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75627361374c07c4fa77977947235e8db6c9035/pkg/sql/distsqlrun/tablereader.go#L363)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

My initial change was incomplete - the tests were failing due to duplicate spans. My understanding is that when we leave `SpanID` field of `RecordedSpan` uninitialized, it has value of 0 which belongs to the root span which breaks some assumptions. I think now I have fixed the issue, but rerunning the benchmarks shows slight performance decrease (I believe due to marshaling/unmarshaling as I was thinking earlier). Here are the numbers on `kv99` ran 4 times for 4 minutes with 10 seconds ramp ("old" one is using `Metrics` field and "new" one is this PR at the moment):
```
gcp
name             old ops/s   new ops/s   delta
KV99-throughput  17.8k ± 2%  17.0k ± 3%  -4.39%  (p=0.029 n=4+4)

name             old ms/s    new ms/s    delta
KV99-P50          19.7 ± 7%   20.7 ± 4%    ~     (p=0.257 n=4+4)
KV99-Avg          6.00 ± 0%   6.38 ± 4%  +6.25%  (p=0.029 n=4+4)
```
```
aws
name             old ops/s   new ops/s   delta
KV99-throughput  29.8k ± 1%  29.1k ± 3%    ~     (p=0.200 n=4+4)

name             old ms/s    new ms/s    delta
KV99-P50          11.8 ± 3%   11.8 ± 7%    ~     (p=1.000 n=4+4)
KV99-Avg          3.70 ± 0%   3.80 ± 0%  +2.70%  (p=0.029 n=4+4)
```
The numbers look quite noisy, but it seems that there is a 2-3% performance hit (in addition to about 1% performance hit on `Metrics` binary), so now I'm leaning towards going back to using `Metrics` field again.
</blockquote></details>

Going back to using the `Metrics` field sounds like a good call

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @asubiotto)

___
*[pkg/sql/distsql_running.go, line 621 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhemUQa1Qt_gm7kTJ9g:-LhfI3kN0EEzMqvMvLsG:bw2uzz2) ([raw file](https://github.com/cockroachdb/cockroach/blob/75bf1750b91aac8d69c8e0f59e818f30c0b9ccf0/pkg/sql/distsql_running.go#L621)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Where is `meta` being acquired from the pool?
</blockquote></details>

Within `generateMeta` of `tableReader`.
___
*[pkg/sql/distsqlrun/tablereader.go, line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhaKUsa1CjESFzBuhtd:-LhfOmgp0_qMXSyh_jkZ:bxo75ih) ([raw file](https://github.com/cockroachdb/cockroach/blob/c75627361374c07c4fa77977947235e8db6c9035/pkg/sql/distsqlrun/tablereader.go#L363)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Going back to using the `Metrics` field sounds like a good call
</blockquote></details>

Ok, I restored that version. Please take - hopefully last - look.

**Review by asubiotto — COMMENTED** [review]
> Reviewed 3 of 12 files at r4, 9 of 9 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 621 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhemUQa1Qt_gm7kTJ9g:-LhfTle064G_Oy8Div_a:brlonjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/75bf1750b91aac8d69c8e0f59e818f30c0b9ccf0/pkg/sql/distsql_running.go#L621)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Within `generateMeta` of `tableReader`.
</blockquote></details>

But then you'd also want to acquire and release it in inbound streams and outboxes in the case of distributed flows, right?
___
*[pkg/sql/distsqlpb/data.go, line 226 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhfU6nPBMdYQZaj9X2a:-LhfU6nPBMdYQZaj9X2b:bna2kod) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9fb6ff2a6928488caf54ee0abd7ec770e7bc7e7/pkg/sql/distsqlpb/data.go#L226)):*
> ```Go
> 
> // Release is part of Releasable interface. Note that we do not explicitly
> // reset the values of the fields since those will be correctly assigned during
> ```

I think it's convention to reset them though (e.g. table reader specs)
___
*[pkg/sql/distsqlrun/tablereader.go, line 303 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhffC7l2hmMgIEQf9TZ:-LhffC7l2hmMgIEQf9T_:b-t80qud) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9fb6ff2a6928488caf54ee0abd7ec770e7bc7e7/pkg/sql/distsqlrun/tablereader.go#L303)):*
> ```Go
> 		}
> 
> 		tr.rowsRead++
> ```

I would add a comment that `rowsRead` are counted twice when tracing (I think). Once in the `InputStats`, then again here.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @asubiotto)

___
*[pkg/sql/distsql_running.go, line 621 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhemUQa1Qt_gm7kTJ9g:-Lhg9yRkBxepKqCTljNp:b-1a0z3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/75bf1750b91aac8d69c8e0f59e818f30c0b9ccf0/pkg/sql/distsql_running.go#L621)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

But then you'd also want to acquire and release it in inbound streams and outboxes in the case of distributed flows, right?
</blockquote></details>

Hm, nice catch. You're right - I think, as it was before, I would only release the meta to the pool on the gateway node, but I'd be getting it from the pool on all nodes. I added another acquisition/release in stream encoder/decoder which should be (?) sufficient.

The change seems a little dirty in `RemoteProducerMetaToLocalMeta` since we want to allocate a new `ProducerMetadata` object in all cases except for `Metrics` one. Let me know if you see a cleaner way to go about it (I could extract a separate type check for metrics to put before the type switch, but that seems inefficient and not cleaner).

Let's see what the build says about that change.
___
*[pkg/sql/distsqlpb/data.go, line 226 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhfU6nPBMdYQZaj9X2a:-Lhfi4xI8urwBJOh9EPq:bl1h72v) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9fb6ff2a6928488caf54ee0abd7ec770e7bc7e7/pkg/sql/distsqlpb/data.go#L226)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think it's convention to reset them though (e.g. table reader specs)
</blockquote></details>

Ok, done.
___
*[pkg/sql/distsqlrun/tablereader.go, line 303 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhffC7l2hmMgIEQf9TZ:-Lhfiqr_7FO8alohw4IH:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9fb6ff2a6928488caf54ee0abd7ec770e7bc7e7/pkg/sql/distsqlrun/tablereader.go#L303)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would add a comment that `rowsRead` are counted twice when tracing (I think). Once in the `InputStats`, then again here.
</blockquote></details>

Done.

**Review by asubiotto — APPROVED** [review]
:lgtm: minus consolidation of metrics release into meta release.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-:-Lhk-Vsj63ZgROIIF__E:b-n9ivwy)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @asubiotto, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 529 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhjzyrBB1TNawGd--Gl:-LhjzyrC6kn6t3M9ezRo:b-x2xvcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d374e8786a0ad1eb2fe713e99f45e5ac177a4e14/pkg/sql/distsql_running.go#L529)):*
> ```Go
> 			r.bytesRead += meta.Metrics.BytesRead
> 			r.rowsRead += meta.Metrics.RowsRead
> 			meta.Metrics.Release()
> ```

It might make sense to do something similar to `ReleaseSetupFlowRequest`, where that takes care of checking and releasing fields instead of having to remember to do so.

**Comment by yuzefovich** [comment]
As discussed with Alfonso, two objects have different lifetimes, so it is easier to keep two `Release` methods separate.

I kicked off another testing run, and the numbers look good (by mistake, both clusters were on GCP):
```
name             old ops/s   new ops/s   delta
KV99-throughput  19.7k ± 2%  19.5k ± 2%   ~     (p=0.886 n=4+4)

name             old ms/s    new ms/s    delta
KV99-P50          17.6 ± 8%   17.6 ± 4%   ~     (p=1.000 n=4+4)
KV99-Avg          5.57 ± 4%   5.57 ± 4%   ~     (p=1.000 n=4+4)
```
```
name             old ops/s   new ops/s   delta
KV99-throughput  19.0k ± 2%  19.5k ± 2%   ~     (p=0.114 n=4+4)

name             old ms/s    new ms/s    delta
KV99-P50          19.6 ± 4%   18.1 ± 5%   ~     (p=0.057 n=4+4)
KV99-Avg          5.35 ± 3%   5.50 ± 0%   ~     (p=0.429 n=4+4)
```
It sees like there is no noticeable performance hit (my explanation is that this commit improves things with pooling some allocations and gives a performance hit due to extra bookkeeping and metadata propagation which about cancel each other out).

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-:-LhklkPk3FEXAl1mLrSa:bctxt4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @ajwerner and @asubiotto)

___
*[pkg/sql/distsql_running.go, line 529 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/38002#-LhjzyrBB1TNawGd--Gl:-Lhkl1ISAgw2drpYidAi:b-nvz12s) ([raw file](https://github.com/cockroachdb/cockroach/blob/d374e8786a0ad1eb2fe713e99f45e5ac177a4e14/pkg/sql/distsql_running.go#L529)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It might make sense to do something similar to `ReleaseSetupFlowRequest`, where that takes care of checking and releasing fields instead of having to remember to do so.
</blockquote></details>

It seems to me that because of different lifetimes, it'd more complicated to do something similar. I'll look into doing some refactoring around usage of `ProducerMetadata` this Friday since it seems like we could benefit from pooling those, so I'll merge this as is for now.

**Pull request merged**
