### PR TITLE
storage: track `curAtIntent` in `intentInterleavingIter`

### LINKED ISSUE #82588: storage: optimize intent checks in `intentInterleavingIter`
`intentInterleavingIter` calls `isCurAtIntentIter()` (or specialized versions) when checking whether the iterator is currently positioned on an intent. These are called at least three times per step: positioning, `UnsafeKey()`, and `UnsafeValue()`. This has a measurable performance impact, as seen in https://github.com/cockroachdb/cockroach/pull/77417#issuecomment-1145831133. We should instead calculate this once whenever we position the iterator (possibly in `computePos()`)

### PR DESCRIPTION
**Pull request by erikgrinaker**
@sumeerbhola Thoughts on this before I update the comments and such?

---

This patch stores `curAtIntent` as a struct field, computing it once per
step rather than recomputing it via `isCurAtIntentIter()`.

Even though `intentCmp` is no longer strictly needed for correctness, it
is retained to allow cheap checks for missing provisional values.

```
MVCCScan_Pebble/rows=1/versions=1/valueSize=64-24               5.60µs ± 1%    5.53µs ± 1%  -1.17%  (p=0.000 n=10+9)
MVCCScan_Pebble/rows=100/versions=1/valueSize=64-24             39.8µs ± 1%    39.2µs ± 1%  -1.59%  (p=0.000 n=10+10)
MVCCScan_Pebble/rows=10000/versions=1/valueSize=64-24           2.84ms ± 1%    2.84ms ± 1%    ~     (p=0.740 n=10+7)
MVCCReverseScan_Pebble/rows=1/versions=1/valueSize=64-24        6.01µs ± 1%    5.90µs ± 1%  -1.71%  (p=0.000 n=10+10)
MVCCReverseScan_Pebble/rows=100/versions=1/valueSize=64-24      52.2µs ± 1%    51.7µs ± 1%  -0.99%  (p=0.003 n=10+10)
MVCCReverseScan_Pebble/rows=10000/versions=1/valueSize=64-24    4.02ms ± 1%    4.00ms ± 1%    ~     (p=0.218 n=10+10)
```

Resolves #82588.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85385)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/storage/intent_interleaving_iter.go` line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85385#-N8Pq_FZ-cXsufB6WLJH:-N8Pq_FZ-cXsufB6WLJI:b-pqln58) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fe052748de0406d7cb2c8a1e9230143f54f7534/pkg/storage/intent_interleaving_iter.go#L815)):*
> ```Go
> }
> 
> // TODO(erikgrinaker): Consider computing this once and storing it as a struct
> ```

were these not getting inlined?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85385)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @sumeerbhola)

___
*[`pkg/storage/intent_interleaving_iter.go` line 815 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85385#-N8Pq_FZ-cXsufB6WLJH:-N8PrVcJ-i3hIZFWhBOJ:bxmsy6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/5fe052748de0406d7cb2c8a1e9230143f54f7534/pkg/storage/intent_interleaving_iter.go#L815)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

were these not getting inlined?
</blockquote></details>

They're inlined, but the comparisons are apparently expensive enough to matter.

I noticed this during the initial range key implementation here, where adding a couple of extra comparisons was expensive enough that I had to split out separate methods for the forward and reverse direction.

**Review by sumeerbhola — CHANGES_REQUESTED** [review]
code changes look good

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85385#-:-N8Zs9v78ccApF_RDvNH:b-ed4hpp)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @sumeerbhola)

___
*[`pkg/storage/intent_interleaving_iter.go` line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85385#-N8ZoCxv-RmJNI1OAPgQ:-N8ZoCxx5nNfTmczrM2r:b45te5b) ([raw file](https://github.com/cockroachdb/cockroach/blob/998669b86a4c3487f2a978dca469cc9be5600357/pkg/storage/intent_interleaving_iter.go#L491)):*
> ```Go
> 
> // Assumes that i.err != nil. And i.iterValid and i.iterKey are up to date.
> func (i *intentInterleavingIter) computePos() {
> ```

We are running a risk of overlooking some case where `computePos` is not called and we forget to update `i.curAtIntent`, and then we work with a stale value. I am wondering if there are some creative ways we can reduce that risk beyond code inspection. Say under race increment a counter whenever `curAtIntent` is updated, and check at the end of various step and seek calls that counter was incremented.

We should at least put big warning comments wher `curAtIntent` is declared that every code path that moves any of the 2 iterators and doesn't end with an error must update `curAtIntent`.
 
___
*[`pkg/storage/intent_interleaving_iter.go` line 674 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85385#-N8Zqw4C5q2KSNOI4JE3:-N8Zqw4D4OkUZ1NLQFkT:b-lxjdez) ([raw file](https://github.com/cockroachdb/cockroach/blob/998669b86a4c3487f2a978dca469cc9be5600357/pkg/storage/intent_interleaving_iter.go#L674)):*
> ```Go
> 					return
> 				}
> 			}
> ```

worth a code comment that `i.curAtIntent` stays true.
___
*[`pkg/storage/intent_interleaving_iter.go` line 692 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85385#-N8Zr14A0-liyqtWTc9W:-N8Zr14A0-liyqtWTc9X:bn69nz5) ([raw file](https://github.com/cockroachdb/cockroach/blob/998669b86a4c3487f2a978dca469cc9be5600357/pkg/storage/intent_interleaving_iter.go#L692)):*
> ```Go
> 			// NB: doesn't need maybeSkipIntentRangeKey() as intentCmp > 0.
> 			i.intentCmp = +1
> 			i.curAtIntent = false
> ```

It is already false. Worth replacing this with a code comment and an assertion.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85385)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @sumeerbhola)

___
*[`pkg/storage/intent_interleaving_iter.go` line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85385#-N8ZoCxv-RmJNI1OAPgQ:-N93Mw6eAjIfQ5aRAPGa:b46j9gg) ([raw file](https://github.com/cockroachdb/cockroach/blob/998669b86a4c3487f2a978dca469cc9be5600357/pkg/storage/intent_interleaving_iter.go#L491)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

We are running a risk of overlooking some case where `computePos` is not called and we forget to update `i.curAtIntent`, and then we work with a stale value. I am wondering if there are some creative ways we can reduce that risk beyond code inspection. Say under race increment a counter whenever `curAtIntent` is updated, and check at the end of various step and seek calls that counter was incremented.

We should at least put big warning comments wher `curAtIntent` is declared that every code path that moves any of the 2 iterators and doesn't end with an error must update `curAtIntent`.
 
</blockquote></details>

Over on `pointSynthesizingIter`, I assert all iterator invariants on every call to `Valid` under race (which will be called following every position change). We could do something like that here too, where we check the actual iterator positions against `intentCmp`, `curAtIntent`, and others. Wdyt?
___
*[`pkg/storage/intent_interleaving_iter.go` line 674 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85385#-N8Zqw4C5q2KSNOI4JE3:-N93NVkXEnN_qu3uXBKt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/998669b86a4c3487f2a978dca469cc9be5600357/pkg/storage/intent_interleaving_iter.go#L674)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

worth a code comment that `i.curAtIntent` stays true.
</blockquote></details>

Done.
___
*[`pkg/storage/intent_interleaving_iter.go` line 692 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85385#-N8Zr14A0-liyqtWTc9W:-N93NgJYBa2bdTl8Miy4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/998669b86a4c3487f2a978dca469cc9be5600357/pkg/storage/intent_interleaving_iter.go#L692)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

It is already false. Worth replacing this with a code comment and an assertion.
</blockquote></details>

Done.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85385)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @sumeerbhola)

___
*[`pkg/storage/intent_interleaving_iter.go` line 491 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85385#-N8ZoCxv-RmJNI1OAPgQ:-N93O9DoDlk1W1MC-mcr:b-fmmtl8) ([raw file](https://github.com/cockroachdb/cockroach/blob/998669b86a4c3487f2a978dca469cc9be5600357/pkg/storage/intent_interleaving_iter.go#L491)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Over on `pointSynthesizingIter`, I assert all iterator invariants on every call to `Valid` under race (which will be called following every position change). We could do something like that here too, where we check the actual iterator positions against `intentCmp`, `curAtIntent`, and others. Wdyt?
</blockquote></details>

Forgot the link: https://github.com/cockroachdb/cockroach/blob/ce222fe883089fdaedb7cfb3c36c30f4a4a68ece/pkg/storage/point_synthesizing_iter.go#L553-L558

**Comment by erikgrinaker** [comment]
I'm going to drop this for now. The gains are marginal, and we've already taken on enough complexity here.

**Pull request closed without merging**
