### PR TITLE
kvserver/rangefeed: remove future package

### PR DESCRIPTION
**Pull request by wenyihu6**
Previously, to reduce O(ranges) goroutines and avoid blocking on rangefeed
completion, we introduced the future package to manage rangefeed completion by
invoking a future callback when an error occurred. The future package makes it
difficult to justify which goroutine the callback runs on and which locks are
being held. This patch introduces a new approach, replacing the future usage.
Each registration now uses the embedded StreamMuxer.DisconnectStreamWithError
method to signal rangefeed completion. StreamMuxer will manage the shutdown
logic and additional stream cleanup.

Part of: https://github.com/cockroachdb/cockroach/issues/126561
Release note: none

### CODE REVIEW

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126490)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)
 
___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1Y1t7I-tepwCgYfZB4:-O1Y1t7I-tepwCgYfZB5:b-qnw76d) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f5f6b8e43fe025b29d6585d6c1a3d93872fa09/pkg/kv/kvserver/replica_rangefeed.go#L516)):*
> ```Go
> 		scanner, err := rangefeed.NewSeparatedIntentScanner(ctx, r.store.TODOEngine(), desc.RSpan())
> 		if err != nil {
> 			stream.Disconnect(kvpb.NewError(err))
> ```

I attempted to change this to construct the `IntentScanner` earlier during `registerWithRangefeedRaftMuLocked` to avoid using stream.Disconnect. But I got the same test failure as seen in https://github.com/cockroachdb/cockroach/pull/52844 which is why the callback was initially implemented.
___
*[`pkg/kv/kvclient/rangefeed/rangefeed_external_test.go` line 1630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1Y3aD7AwFN2kdawyZJ:-O1Y3aD7AwFN2kdawyZK:b-bdt2vd) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f5f6b8e43fe025b29d6585d6c1a3d93872fa09/pkg/kv/kvclient/rangefeed/rangefeed_external_test.go#L1630)):*
> ```Go
> 	ctx  context.Context
> 	ch   chan<- *kvpb.RangeFeedEvent
> 	done chan *kvpb.Error
> ```

Instead of using a channel for all sink types, we could embed the real `StreamMuxer` and check for disconnect errors in `StreamMuxer.ServerStreamSender`. I chose this approach because it aligns more closely with our approach prior to https://github.com/cockroachdb/cockroach/pull/96756 and also seems much easier. And I plan to change tests in `processor_test.go` to use a real StreamMuxer in the next PR to expand our test coverage on StreamMuxer. What’s your preference?

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-:-O1cTqM09t143xJNrh2w:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1Y1t7I-tepwCgYfZB4:-O1cUF_A7TtG22Dj0eTw:bkhrd2s) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f5f6b8e43fe025b29d6585d6c1a3d93872fa09/pkg/kv/kvserver/replica_rangefeed.go#L516)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

I attempted to change this to construct the `IntentScanner` earlier during `registerWithRangefeedRaftMuLocked` to avoid using stream.Disconnect. But I got the same test failure as seen in https://github.com/cockroachdb/cockroach/pull/52844 which is why the callback was initially implemented.
</blockquote></details>

It's kind of strange that a processor-wide (multiple rangefeeds can attach to the same rangefeed processor) dependency is in charge of sending an error signal to a single stream. What would it look like to add an error return value to `IntentScannerConstructor` and handle the error case inside of the processor?
___
*[`pkg/server/node.go` line 1867 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1cS3Bh0a9ZfKAVEgDN:-O1cS3Bi96c9xxcFydru:biqpgg2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a818e9b455345a458e920e2c07388b671fe04800/pkg/server/node.go#L1867)):*
> ```Go
> // Disconnect implements the rangefeed.Stream interface. It disconnects the
> // stream from the StreamMuxer. The StreamMuxer is then responsible for
> // disconnecting the stream and cleaning up.
> ```

This comment says that the function " disconnects the stream from the StreamMuxer" and that "The StreamMuxer is then responsible for disconnecting the stream". These two sound contradictory. Are both true? Can the responsibility of each be clarified?
___
*[`pkg/server/node.go` line 1938 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1cSYks-nn_P30FfGNT:-O1cSYks-nn_P30FfGNU:bzekp5d) ([raw file](https://github.com/cockroachdb/cockroach/blob/a818e9b455345a458e920e2c07388b671fe04800/pkg/server/node.go#L1938)):*
> ```Go
> 			streamMuxer.AddStream(req.StreamID, cancel)
> 
> 			if err := n.stores.RangeFeed(req, streamSink); err != nil {
> ```

Can we add a comment here that this call registers a RangeFeed and returns an error if registration fails, but that it returns without blocking and without an error if the registration succeeds?
___
*[`pkg/kv/kvclient/rangefeed/rangefeed_external_test.go` line 1630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1Y3aD7AwFN2kdawyZJ:-O1cSzg_2LWWkyshKfTj:b-nlz83z) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f5f6b8e43fe025b29d6585d6c1a3d93872fa09/pkg/kv/kvclient/rangefeed/rangefeed_external_test.go#L1630)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

Instead of using a channel for all sink types, we could embed the real `StreamMuxer` and check for disconnect errors in `StreamMuxer.ServerStreamSender`. I chose this approach because it aligns more closely with our approach prior to https://github.com/cockroachdb/cockroach/pull/96756. And I plan to change tests in `processor_test.go` to use a real StreamMuxer in the next PR to expand our test coverage on StreamMuxer. What’s your preference?
</blockquote></details>

This approach seems fine to me. It's nice to avoid the dependency on `StreamMuxer`.
___
*[`pkg/kv/kvserver/rangefeed/processor_test.go` line 1812 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1cTVZu36LbM9grPBth:-O1cTVZu36LbM9grPBti:bjpur4r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a818e9b455345a458e920e2c07388b671fe04800/pkg/kv/kvserver/rangefeed/processor_test.go#L1812)):*
> ```Go
> 	case err := <-c.done:
> 		return err.GoError()
> 	case <-time.After(30 * time.Second):
> ```

Let's replace all of these `30 * time.Second` with `testutils.DefaultSucceedsSoonDuration`.

**Review by wenyihu6 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126490)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[`pkg/kv/kvserver/replica_rangefeed.go` line 516 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1Y1t7I-tepwCgYfZB4:-O20yWly0wVEviKPHLFi:b-roci15) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f5f6b8e43fe025b29d6585d6c1a3d93872fa09/pkg/kv/kvserver/replica_rangefeed.go#L516)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

It's kind of strange that a processor-wide (multiple rangefeeds can attach to the same rangefeed processor) dependency is in charge of sending an error signal to a single stream. What would it look like to add an error return value to `IntentScannerConstructor` and handle the error case inside of the processor?
</blockquote></details>

Thanks for raising this! I looked into this more. There are two things that I'm not quite understanding. 

This comment says https://github.com/cockroachdb/cockroach/blob/04a6ba0578480482eb20bf447f1820d0a1e5e24b/pkg/kv/kvserver/rangefeed/processor.go#L166-L167. 

However, the nil check is performed on the intent scanner constructor but not on the intent scanner itself https://github.com/cockroachdb/cockroach/blob/04a6ba0578480482eb20bf447f1820d0a1e5e24b/pkg/kv/kvserver/rangefeed/scheduled_processor.go#L118. It seems that it could lead to panic here https://github.com/cockroachdb/cockroach/blob/91f53eae420edbb40cddfd2559bcb4406f7a4c93/pkg/kv/kvserver/rangefeed/task.go#L135.

I'm trying to distinguish when the intent scanner constructor returns nil without an error V.S. returns nil with an error. The first case seems only possible in tests. Based on the code here https://github.com/cockroachdb/cockroach/blob/91f53eae420edbb40cddfd2559bcb4406f7a4c93/pkg/kv/kvserver/rangefeed/task.go#L110, the constructor should never return a nil intent scanner without an error. Is that correct?

2. Additionally, we only disconnect the first registration here during `IntentScannerConstructor` . I think this is currently true because we make sure to call the intent scanner constructor under the same lock as the first registration (It just happens that we need this to avoid missing events). No other `p.Register` could happen before `IntentScannerConstructor` is called but it feels like a brittle assumption. Should we call `p.StopProcessor()` when `IntentScannerConstructor` returns an error? 

I'm trying to fix these in https://github.com/cockroachdb/cockroach/pull/127204 if the concerns look right to you. 
___
*[`pkg/server/node.go` line 1867 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1cS3Bh0a9ZfKAVEgDN:-O20yXrnDpLfZif2SKBE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a818e9b455345a458e920e2c07388b671fe04800/pkg/server/node.go#L1867)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This comment says that the function " disconnects the stream from the StreamMuxer" and that "The StreamMuxer is then responsible for disconnecting the stream". These two sound contradictory. Are both true? Can the responsibility of each be clarified?
</blockquote></details>

Done.
___
*[`pkg/server/node.go` line 1938 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1cSYks-nn_P30FfGNT:-O20yZNK3ZsCSEwO_R3w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a818e9b455345a458e920e2c07388b671fe04800/pkg/server/node.go#L1938)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we add a comment here that this call registers a RangeFeed and returns an error if registration fails, but that it returns without blocking and without an error if the registration succeeds?
</blockquote></details>

Done.
___
*[`pkg/kv/kvclient/rangefeed/rangefeed_external_test.go` line 1630 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1Y3aD7AwFN2kdawyZJ:-O20ybViBYMjLouMBQWL:b-frh4mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/35f5f6b8e43fe025b29d6585d6c1a3d93872fa09/pkg/kv/kvclient/rangefeed/rangefeed_external_test.go#L1630)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This approach seems fine to me. It's nice to avoid the dependency on `StreamMuxer`.
</blockquote></details>

Ack, cool.
___
*[`pkg/kv/kvserver/rangefeed/processor_test.go` line 1812 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O1cTVZu36LbM9grPBth:-O20ygMP0VHVJjCQ7TjV:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a818e9b455345a458e920e2c07388b671fe04800/pkg/kv/kvserver/rangefeed/processor_test.go#L1812)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's replace all of these `30 * time.Second` with `testutils.DefaultSucceedsSoonDuration`.
</blockquote></details>

Done.

**Review by wenyihu6 — COMMENTED** [review]
Sorry for the delayed turnaround. I was looking into a support issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-:-O20yiS53Jl03k4KRZNx:bmlm5bm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-:-O21HrBj4L1cSVtsUpcB:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @wenyihu6)

___
*[`pkg/server/node.go` line 1961 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/126490#-O21HfMq55iQQ6m-lt_k:-O21HfMq55iQQ6m-lt_l:bmsg98z) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd537f936f3c5d9bdd4e0d8a0581caff036f3ed7/pkg/server/node.go#L1961)):*
> ```Go
> // StreamMuxer to detach the stream. The StreamMuxer is then responsible for
> // handling the actual disconnection and additional cleanup. Note that Caller
> // should not rely on immediate disconnection as cleanup take place async.
> ```

"takes"

**Comment by wenyihu6** [comment]
TFTR! 

bors r=nvanbenschoten

**Pull request merged**
