### PR TITLE
storageccl: count rows imported/exported

### PR DESCRIPTION
**Pull request by dt**
also surface said counts in BACKUP and RESTORE

### CODE REVIEW

**Comment by dt** [comment]
We'll want to document the current known limitations:
- BACKUP counts may, e.g. for incremental, include the number of rows deleted because it include the tombstone record
- rows in interleaved tables aren't currently counted.

**Comment by danhhz** [comment]
pretty sure you could address both of these limitations. deleted rows are easy, skip over any keys with a value length of 0 before you even do the SafeSplitKey. interleaved tables can be done if the rowCounter has access to table descriptors

the former should be addressed before this is merged. the latter should probably be fixed by 1.1, but i'm okay if it's a followup

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/storageccl/export.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-Kn5T4yla_JWwlhoza2A:-Kn5T4yla_JWwlhoza2B:byts1t2) ([raw file](https://github.com/cockroachdb/cockroach/blob/213e7c9eda21df2583ca59fa0a47c4feb036ee3f/pkg/ccl/storageccl/export.go#L62)):*
> ```Go
> 
> func (r *rowCounter) count(key roachpb.Key) error {
> 	row, err := keys.EnsureSafeSplitKey(key)
> ```

this wants a comment

---

*[pkg/roachpb/api.proto, line 808 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-Kn5SsiWzMFx-QTuSf_J:-Kn5SsiWzMFx-QTuSf_K:b-al8xut) ([raw file](https://github.com/cockroachdb/cockroach/blob/213e7c9eda21df2583ca59fa0a47c4feb036ee3f/pkg/roachpb/api.proto#L808)):*
> ```protobuf
>     optional Span span = 1 [(gogoproto.nullable) = false];
>     optional string path = 2 [(gogoproto.nullable) = false];
>     reserved 3;
> ```

oof, this will throw off counts for a backup or restore during a rolling upgrade. not the end of the world i guess, but it definitely need to be called out in docs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-:-Kn5T9bqfnx0euiTm65U:baa0naq)*

**Comment by dt** [comment]
Huh, actually, I think maybe interleaved already just works? Added a test that suggests it's working.

Added skipping len(0) values in export and made the tests check strict == -- that was easy, thanks!

---

Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/storageccl/export.go, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-Kn5T4yla_JWwlhoza2A:-Kn5bEw5ww74M4s2wT-g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/213e7c9eda21df2583ca59fa0a47c4feb036ee3f/pkg/ccl/storageccl/export.go#L62)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this wants a comment
</blockquote></details>

Done.

---

*[pkg/roachpb/api.proto, line 808 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-Kn5SsiWzMFx-QTuSf_J:-Kn5bGEyh14b_ndfemxl:bm3mpll) ([raw file](https://github.com/cockroachdb/cockroach/blob/213e7c9eda21df2583ca59fa0a47c4feb036ee3f/pkg/roachpb/api.proto#L808)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

oof, this will throw off counts for a backup or restore during a rolling upgrade. not the end of the world i guess, but it definitely need to be called out in docs
</blockquote></details>

Yeah, I thought about keeping the old field and filling both, but decided incuring the cruft and cleanup debt wasn't worth it, since it a) only matters in a rare edge case b) doesn't affect actual data correctness.

We've advised before that some things may have slightly odd (but never correctness-compromising) behavior if used on mixed version clusters -- e.g. we say not to change settings during upgrades -- so I'm not super worried about adding another doc caveat.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-:-Kn5b5is1dpHwAtFpYiC:b-szseig)*

**Comment by danhhz** [comment]
Oh yes, of course interleaved works. :lgtm:

---

Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/sqlccl/backup.go, line 446 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-Kn5hg8rSCMzqJOJgsEI:-Kn5hg8rSCMzqJOJgsEJ:bbbc7w2) ([raw file](https://github.com/cockroachdb/cockroach/blob/64baa3aa0e5ed2f478e2454027da8e99bc890f28/pkg/ccl/sqlccl/backup.go#L446)):*
> ```Go
> 		Spans:         spans,
> 		Files:         files,
> 		DataSize:      summary.DataSize,
> ```

double check this, but I think this is only used in tests. should be safe to remove it

---

*[pkg/ccl/storageccl/export.go, line 157 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-Kn5gJfz6SevUFc5bUgS:-Kn5gJg-Fsb7fOcL7WJ9:bf2mjko) ([raw file](https://github.com/cockroachdb/cockroach/blob/64baa3aa0e5ed2f478e2454027da8e99bc890f28/pkg/ccl/storageccl/export.go#L157)):*
> ```Go
> 			log.Infof(ctx, "Export %s %s", iter.UnsafeKey(), v.PrettyPrint())
> 		}
> 		if len(iter.UnsafeValue()) != 0 {
> ```

comment plz

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-:-Kn5fV3dAyPEG2xhOkjo:bo6mehg)*

**Comment by dt** [comment]
Review status: 0 of 11 files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/ccl/sqlccl/backup.go, line 446 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-Kn5hg8rSCMzqJOJgsEI:-Kn5jbxr-MKJ2l1dOtYN:bl9pj95) ([raw file](https://github.com/cockroachdb/cockroach/blob/64baa3aa0e5ed2f478e2454027da8e99bc890f28/pkg/ccl/sqlccl/backup.go#L446)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

double check this, but I think this is only used in tests. should be safe to remove it
</blockquote></details>

well, it's used right here to pass the info on to the SQL stmt handler, but even aside from plumbing, I think it's nice to have?

---

*[pkg/ccl/storageccl/export.go, line 157 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623#-Kn5gJfz6SevUFc5bUgS:-Kn5kN-aJlTPtPsaPgT1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/64baa3aa0e5ed2f478e2454027da8e99bc890f28/pkg/ccl/storageccl/export.go#L157)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

comment plz
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16623)*

**Pull request merged**
