### PR TITLE
execinfrapb: print input types one per line in EXPLAIN (DISTSQL, TYPES)

### PR DESCRIPTION
**Pull request by yuzefovich**
Previously, input types were printed in a single line within the input
synchronizer box on the flow diagram. However, when we have a processor
with two inputs and when each input has several columns, the boxes would
collide and make the types unreadable. This commit changes it to print
each type one per line, so there is no collision between different boxes
of input synchronizer. Separately, cockroachdb.github.io has been
adjusted so that the boxes for the input synchronizers could be
displayed well in such scenario.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Screen Shot 2019-12-20 at 9 08 14 AM
changes to
Screen Shot 2019-12-20 at 9 08 57 AM
Both options seem bad :/

**Comment by RaduBerinde** [comment]
Ha, maybe spend a bit of time playing with https://github.com/cockroachdb/cockroachdb.github.io/blob/master/distsqlplan/flow_diagram.js to adjust the positioning of those things. I think [this](https://github.com/cockroachdb/cockroachdb.github.io/blob/master/distsqlplan/flow_diagram.js#L86) is where the "bounding box" is defined, the height should probably be proportional to the number of lines.

**Comment by yuzefovich** [comment]
Here is an example of what the plan looks like now (with the change to constraints):
Screen Shot 2020-01-14 at 10 16 37 AM
I think this PR should be good to go in.

**Comment by RaduBerinde** [comment]
:lgtm:  Consider adding a release note, someone might find it useful.

**Comment by yuzefovich** [comment]
There was a release note in #43193, and I think it is sufficient (in a sense this PR is fixing what that PR started :) ).

TFTR!

bors r+

**Pull request merged**
