### PR TITLE
sql: reduce allocations in rowContainerIterator

### PR DESCRIPTION
**Pull request by mgartner**
In #111318 a shallow copy of rows was added to
`rowContainerIterator.Next`. This copy is only necessary for one usage
of the iterator within `plpgsqlCursorHelper`. This commit moves the copy
to the cursor helper which reduces allocations for all other usages of
the iterator.

Informs #117546

Release note: None

### CODE REVIEW

**Review by DrewKimball — APPROVED** [review]
:lgtm: Thanks for the fix!

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118923#-:-Nq4cmUFCnL2cgD_y2L6:b-72sm86)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
Had to make a slight tweak, PTAL.

**Comment by mgartner** [comment]
I think this should probably be backported to v23.2.

**Review by DrewKimball — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/118923#-:-Nq4thFv67sATWWq578V:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
