### PR TITLE
backupccl: idempotently restore system tables in cluster restore

### PR DESCRIPTION
**Pull request by pbardea**
Previously, if a cluster restore were to restart (e.g. in the case of
the coordinator crashing) after restoring the system tables, but before
completing, the job would attempt to restore the system table data again
and potentially fail on non-idempotent system table restoration
functions (e.g. restoring jobs).

This commit, adds a new SystemTablesRestored field to the restore
details to keep track of each system table that it has restored and
maintains progress. This is required, since not all system tables may
need to be restored atomically in the future.

Release note (bug fix): Fix a bug where cluster restore would sometimes
(very rarely) fail after retrying.

Release justification: bug fix

### CODE REVIEW

**Comment by pbardea** [comment]
After trying a few approaches, I think this is the most flexible to restoring system tables individually (e.g. when restoring the zone config table first, the progress of that table can be tracked separately). The drawback here is the fragility introduced by persisting a dynamic value to keep track of progress rather than using a protobuf field, which would make it easier to maintain cross-compatibility across versions (in mixed-version cluster scenarios).

An alternative here is to restore the system tables in a single txn and keep one progress update to track that, which would mean that we wouldn't be able to keep track of specific system tables restored in a mixed-binary cluster (e.g. 21.1 cluster has restored `zones`, but the job gets resumed on a 20.2 node). In practice, this is actually safe because restoring the zones table is an idempotent operation (wipe all rows, insert new rows) -- but would not be generally true if we want to restore some system tables in a different phase in a non-idempotent way.

**Review by dt — APPROVED** [review]

**Comment by pbardea** [comment]
TFTR!
bors r=dt

**Comment by pbardea** [comment]
Skipping the test it flaked on and will bors again when that's in.

**Comment by pbardea** [comment]
Flaked on a race fixed by https://github.com/cockroachdb/cockroach/pull/60958. Waiting for that to merge and will rebase.

**Comment by pbardea** [comment]
bors r=dt

**Pull request merged**
