### PR TITLE
storage/engine: split some pure MVCC logic out into storage/mvcc

### PR DESCRIPTION
**Pull request by dt**
More work on #30001.

This splits some pure-go MVCC encoding/decodeing logic out of
`stroage/engine` into a new package `storage/mvcc` so it no longer
shares a package any of the rocksdb interfacing code that lives in
`storage/engine`. This is so that callers can import and use these functions
without introducing our c-deps code to their dependency closure, which
is an issue if callers might end up being used outside of the cockroach build
environment or share packages with code that is.

This is just a mechanical code move with a following rename to avoid
repeating the package name in func/var prefixes, eg. `MVCCKey` ->
`mvcc.Key`, and only includes `MVCCKey` as well as those functions that were
in-use within sqlbase. Significant MVCC encoding/decoding code reamins that can
be moved later as needed.

Release note: none.

sqlbase: unskip c-deps dependency linter.

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
This is a noble effort and I'm 100% in support of it, but in its current state, this isn't mergeable. If we're going to create a new `storage/mvcc` package, we should move all MVCC logic into it. This includes just about everything in `engine/mvcc.go` and the `mvcc.proto` files currently in `engine/enginepb`. Right now the split is arbitrary and will make this code even harder to understand than it currently is.

I've actually considered this before but didn't have a good enough reason to justify the code movement at the time. Here's what I propose:
- create a new `storage/mvcc` package to house files like `mvcc.go`, `mvcc_logical_ops.go`, etc.
- move most of the interfaces from `engine/engine.go` into this new package. Specifically, any interface that interacts with MVCC types should be moved.
- create a new `storage/mvcc/mvccpb` package to house files like `mvcc.proto` and `mvcc3.proto`
- create a dependency from `storage/engine` to `storage/mvcc`
- most current imports of `storage/engine` could move to `storage/mvcc`
- as usual, strip all type names that now stutter

How does that sound?


Also, I don't think we should make this change until after the stability period.

> Reviewed 57 of 57 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30043#-:-LM8Mmy382wPriBZb0HH:b-po9fzm)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/engine/mvcc.go, line 41 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30043#-LM8MP9A2TQw3IhURCQw:-LM8MP9A2TQw3IhURCQx:b-a4qoed) ([raw file](https://github.com/cockroachdb/cockroach/blob/926b3ec74d850c694d17cfbf17e3844b415f1198/pkg/storage/engine/mvcc.go#L41)):*
> ```Go
> )
> 
> // MVCCKey is an alias to mvcc.Key to ease refactoring.
> ```

I don't think we should merge anything with this type alias.

**Comment by dt** [comment]
I started by trying to move `mvcc.go` wholesale, but the actual read/write methods (MVCCGet/Put/Scan/etc) all use `engine` types so that left an edge to engine, rather than the other way around.

I can look for a short-term fix instead. Maybe just copy pasta `MVCCScanDecodeKeyValue` into sqlbase and change it to return `(key []byte, ts int64)` instead of `MVCCKey`?

**Comment by dt** [comment]
hm, so I guess I'd rather not duplicate `DecodeKey`, `SplitKey`, etc in `sqlbase`.

Alternative idea: leave mvcc.go alone except for moving three functions to something like `engine/encoding` and switching them to return primitive `[]byte` and `int` instead of `MVCCKey`. Keep the API in `engine` the same, e.g. switching implementation of `engine.DecodeKey` to be call `encoding.DecodeKey` and just wrap the field back to the expected `MVCCKey`.

I can still cut the edge from `sql` to engine that way, but with much less code moving in `engine`.

**Comment by nvanbenschoten** [comment]
>I started by trying to move mvcc.go wholesale, but the actual read/write methods (MVCCGet/Put/Scan/etc) all use engine types so that left an edge to engine, rather than the other way around.

What do they use other than the interfaces from `engine/engine.go` which I proposed we could move to the new package?

**Comment by dt** [comment]
Ah, whoops, yeah, I missed that part -- yeah, it was those interfaces that I was looking at.

I think that would work, but yeah, it's a big code move to merge right now, so I think I need to look for a more narrow fix for now to break the sqlbase -> engine edge.

**Comment by nvanbenschoten** [comment]
> so I think I need to look for a more narrow fix for now to break the sqlbase -> engine edge.

Is this urgent?

**Comment by dt** [comment]
Yeah, we can't currently update the vendored cockroach code in telemetry recording server, to pick up new fields in 2.1 telemetry, because of the introduction of edges from sql to c-deps.

**Comment by dt** [comment]
I tried a much more targeting fix in #30082

**Pull request closed without merging**
