### PR TITLE
base,server: better UX for server addrs and cert mis-configurations

### LINKED ISSUE #28500: cli/start: server accepts to start with conflicting cert and --listen-addr
If a node certificate only contains the name "localhost" and a server is started with `--listen-addr=other`, where `other` is the canonical host name, but maps with  /etc/hosts to 127.0.0.1, then

- `cockroach start` will appear to start a node successfully without error message
- any client command will fail with an obscure error message ("transient failure, last error \<nil\>")
- the logs will report:

```
W180812 07:21:19.208860 614 vendor/google.golang.org/grpc/clientconn.go:1293  grpc: addrConn.createTransport failed to connect to {afaa39c93f7c:26257 0  <nil>}. Err :connection error: desc = "transport: authentication handshake failed: x509: certificate is valid for localhost, not afaa39c93f7c". Reconnecting...
```

(I had been fighting with this bug for ages without knowing where to look, I finally figured it out with a CI failure on something entirely unrelated.)

cc @mberhault

### PR DESCRIPTION
**Pull request by knz**
Fixes #28500.

###  base,server: perform address validation and normalization upfront

Prior to this patch, the listen and advertise addresses were resolved
late in the server initialization, down to the point where the
`net.Listen()` call was made. 

This patch extracts address normalization earlier into a separate
method `(*Config).ValidateAddrs()` and removes this responsibility
from the `Server` code. The only thing that remains to be done
after `net.Listen()` is to update the port numbers if they were
automatically allocated.

This patch also adds proper support and validation for named ports.

Release note (cli change): CockroachDB now supports configuring port
numbers with `--listen-addr`/`--http-addr`/`--advertise-addr` using
service names in addition to numeric values.

### server,base: verify upfront that the addresses are listed in certs

Prior to this patch, CockroachDB made no attempt upfront at
verifying/validating that the addresses configured with
`--listen`/`--advertise` were present in the provided certificate
files. Instead, the validation was delayed upon the first received
client connection, which could occur much later than start-up and
would only be reported in the log file.

This led to poor UX, where an invalid certificate configuration
would *appear* to work (`cockroach start` reporting no error) but
client connections would fail (with more or less clear x509 errors).

To improve UX, this patch validates the configured addresses upfront
while the connections are being set up. If a discrepancy is detected,
it is logged immediately with a `log.Shout` so that it is more likely
to be seen by the human operator.

Also in any case the configured addresses inside the certificates are
logged, to aid troubleshooting.

For example:

```
$ cockroach cert create-node --certs-dir=certs localhost

$ ./cockroach start --certs-dir=certs --listen-addr=kenax
*
* WARNING: [n?] listen address "192.168.2.10" and advertise address "kenax" not in node certificate (dnsNames: localhost; commonName: node)
* Secure node-node and SQL connections are likely to fail.
* Consider extending the node certificate or use different server flags.
*
```

Release note (cli change): CockroachDB now attempts to inform the
operator if the names and IP addresses listed in the configured
certificates do not match the server configuration.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28502)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/base/addr_validation.go, line 238 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJhiQc2axlxHuzu5nCW-r2-238:-LJiob5s-fpmRC5qjmpy:b-i21bbo) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3709ecad33ba0a12ec3e8e1f0da58083419fbc/pkg/base/addr_validation.go#L238)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

You need to check `certInfo.Error` before using it. See function docs for details: https://github.com/cockroachdb/cockroach/blob/master/pkg/security/certificate_manager.go#L282
</blockquote></details>

Thanks. Done.
___
*[pkg/base/addr_validation.go, line 252 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJhiQc2axlxHuzu5nCW-r2-252:-LJioc5316i5n4d73Y1J:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3709ecad33ba0a12ec3e8e1f0da58083419fbc/pkg/base/addr_validation.go#L252)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

ditto. check `certInfo.Error`
</blockquote></details>

Done.
___
*[pkg/base/addr_validation.go, line 267 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJhiQc2axlxHuzu5nCW-r2-267:-LJiocjX-wbnEkct0r21:bcvjgzp) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3709ecad33ba0a12ec3e8e1f0da58083419fbc/pkg/base/addr_validation.go#L267)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

HTTP not being in the UI certificate is not as much of a problem. It's not unreasonable to only stick a load balancer address in the UI certificate rather than the node's listen and advertise addresses. For example: `cyan`'s listen address (and advertise address since they're the same) are **not** in the certificate. Only the publicly resolvable fully-qualified DNS names. I'm fine keeping the shout, but toning down the language for it may be nice. At the very least a warning should a future contributor change the shout to a failure.
</blockquote></details>

Good idea. Done.
___
*[pkg/base/addr_validation.go, line 286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJhiQc2axlxHuzu5nCW-r2-286:-LJis11p58xBoRtcLa8o:b-rzp0ys) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3709ecad33ba0a12ec3e8e1f0da58083419fbc/pkg/base/addr_validation.go#L286)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

A simple slice of IP address strings and DNS names with a final `strings.Join(..., ',')` will be much simpler, it's not like we need to worry about the tiny efficiency gain of using a buffer. I also don't think we need the IP address vs DNS name breakdown.
</blockquote></details>

My rationale is that if the user created the cert themselves and mistakenly put the IP addresses in the DNS names, that would fail validation and this message here would reveal that. What do you think?

**Review by mberhault — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28502)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/base/addr_validation.go, line 286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJhiQc2axlxHuzu5nCW-r2-286:-LJkAKPbAZ2jdbE4b0FK:b-i35d7q) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3709ecad33ba0a12ec3e8e1f0da58083419fbc/pkg/base/addr_validation.go#L286)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

My rationale is that if the user created the cert themselves and mistakenly put the IP addresses in the DNS names, that would fail validation and this message here would reveal that. What do you think?
</blockquote></details>

It's an incredibly rare case but sure, it can happen. I should have added "nit" to my comment above. I'll leave it up to you.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28502)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/base/addr_validation.go, line 286 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJhiQc2axlxHuzu5nCW-r2-286:-LJmaJsd8nWjBZ7a5CuO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5f3709ecad33ba0a12ec3e8e1f0da58083419fbc/pkg/base/addr_validation.go#L286)):*
<details><summary><i>Previously, mberhault (marc) wrote…</i></summary><blockquote>

It's an incredibly rare case but sure, it can happen. I should have added "nit" to my comment above. I'll leave it up to you.
</blockquote></details>

Done.

**Review by bdarnell — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28502)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/base/addr_validation.go, line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoA_8s69VDTtJfNDUb:-LJoA_8s69VDTtJfNDUc:b1py2ov) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L92)):*
> ```Go
> 	}
> 	if (desiredHost != "" && lnHost != desiredHost) ||
> 		(desiredHost == "" && lnHost != "::" /* ipv6 all */) {
> ```

Some  people disable ipv6 on their servers (I've seen this a lot among Tornado users), so we should also allow `desiredHost == "" && lnHost == '0.0.0.0'`. 
___
*[pkg/base/addr_validation.go, line 121 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoBAHL2UVNBs7Fw4fh:-LJoBAHL2UVNBs7Fw4fi:bxmxjdv) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L121)):*
> ```Go
> 		// We want SplitHostPort to complete successfully, so the port
> 		// number must be filled in already.
> 		listenAddr = listenAddr + ":"
> ```

What if `listenAddr == "::1"` (or `[::1]`)? That contains a colon but no port number, so won't it need a colon (and maybe brackets) added for SplitHostPort to work?
___
*[pkg/base/addr_validation.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoCODGBJcKB1IqRTDT:-LJoCODGBJcKB1IqRTDU:b1s63gd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L181)):*
> ```Go
> // on all interfaces" and resolves host names to IP addresses.
> func validateListenAddr(ctx context.Context, addr, defaultHost string) (string, string, error) {
> 	host, port, err := net.SplitHostPort(addr)
> ```

Why doesn't this do the "append a colon" thing that validateAdvertiseAddr does? Can `validateAdvertiseAddr` use a listen address that's been validated by this function instead of doing its own similar-but-not-identical logic?
___
*[pkg/base/addr_validation.go, line 294 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoG74-4VKJwoMbdqg3:-LJoG74-4VKJwoMbdqg4:b-xhiowd) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L294)):*
> ```Go
> 		// been called already.
> 		//
> 		// We are less stringent here than for the node certificate
> ```

This looks like the same logic. Is the "less stringent" part just that the shout is "info" rather than "warning"?

**Comment by knz** [comment]
rebased to pick up the latest builder update. rfal

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28502)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/base/addr_validation.go, line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoA_8s69VDTtJfNDUb:-LJoJwqp6LLQn4nQUADF:b77eoyx) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L92)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Some  people disable ipv6 on their servers (I've seen this a lot among Tornado users), so we should also allow `desiredHost == "" && lnHost == '0.0.0.0'`. 
</blockquote></details>

that's included here. if the listen call gets 0.0.0.0 as an input spec, the lnHost here will be the empty string.
___
*[pkg/base/addr_validation.go, line 121 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoBAHL2UVNBs7Fw4fh:-LJoK9r8-VUezDYUD025:bajm45f) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L121)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

What if `listenAddr == "::1"` (or `[::1]`)? That contains a colon but no port number, so won't it need a colon (and maybe brackets) added for SplitHostPort to work?
</blockquote></details>

This logic was bogus, thanks for picking on it. The caller of this code already ensures the entire string is either empty or contains a host/port delimiting colon. There is no need for adding a missing colon, instead just check the addr is non-empty. I was mistaken -- corrected by removing this and adding a clarifying comment about the contract at the top.
___
*[pkg/base/addr_validation.go, line 181 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoCODGBJcKB1IqRTDT:-LJoM0PP-F2E8hwIrS2r:bg1btza) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L181)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Why doesn't this do the "append a colon" thing that validateAdvertiseAddr does? Can `validateAdvertiseAddr` use a listen address that's been validated by this function instead of doing its own similar-but-not-identical logic?
</blockquote></details>

Correct, I had forgotten a case here. Fixed and added the corresponding tests.
___
*[pkg/base/addr_validation.go, line 294 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoG74-4VKJwoMbdqg3:-LJoKUjR4UDu8gkXQ1IB:bm1jmxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L294)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

This looks like the same logic. Is the "less stringent" part just that the shout is "info" rather than "warning"?
</blockquote></details>

not the same logic indeed:

1) the wording of the message is different.
2) the certInfo defaults to that of the node if nil

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28502)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/base/addr_validation.go, line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoA_8s69VDTtJfNDUb:-LJoOkX17Xw0H6wJ8Mx9:bsaioic) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L92)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

that's included here. if the listen call gets 0.0.0.0 as an input spec, the lnHost here will be the empty string.
</blockquote></details>

oh I think we have the opposite case: if the user requests 0.0.0.0 then lnHost is empty but desiredHost isn't. Will check.

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28502)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/base/addr_validation.go, line 92 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoA_8s69VDTtJfNDUb:-LJoPQlE39QfTATgtRmL:b-lwx1vo) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L92)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

oh I think we have the opposite case: if the user requests 0.0.0.0 then lnHost is empty but desiredHost isn't. Will check.
</blockquote></details>

So I found the following

- if the flag requests empty the lnHost is either 0.0.0.0, empty or :: 
- if the flag requests 0.0.0.0 the lnHost is either 0.0.0.0, empty or ::
- if the flag requests :: the lnHost is either empty or ::

I made a conditional that's very generous about all these. RFAL.

**Review by bdarnell — APPROVED** [review]
> Reviewed 1 of 3 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28502)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/base/addr_validation.go, line 294 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoG74-4VKJwoMbdqg3:-LJtYghzDtmOMDltD-Y4:bysr776) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L294)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

not the same logic indeed:

1) the wording of the message is different.
2) the certInfo defaults to that of the node if nil


</blockquote></details>

The wording is different, but they both look just as shouty/scary to the user (and for clusters like cyan that are intentionally not using the per-node hostname in the UI certs (that's not an option for letsencrypt), there's no way to suppress the message so it will just be a persistent false positive). This message is also not as critical because users will see the browser warning if they get this wrong (as opposed to the mostly-hidden node-to-node connections).  I don't think this warning is worth including given the chance of false positives and the fact that most users will either get both certs right or both wrong. 
___
*[pkg/base/addr_validation.go, line 200 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJtYXVyEi833zr_sHpp:-LJtYXVyEi833zr_sHpq:b-i4pd09) ([raw file](https://github.com/cockroachdb/cockroach/blob/c569dd5c9e6fd9b452f0f07d8e167dbd57b936f8/pkg/base/addr_validation.go#L200)):*
> ```Go
> 	}
> 	if port == "" {
> 		port = "0"
> ```

When does the default port 26257 get applied?

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28502)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/base/addr_validation.go, line 294 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJoG74-4VKJwoMbdqg3:-LJtatv36zm8lV2u4fCc:b7k4l95) ([raw file](https://github.com/cockroachdb/cockroach/blob/4e98559f4df5978cd155a8f29b847a14d08c80b4/pkg/base/addr_validation.go#L294)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The wording is different, but they both look just as shouty/scary to the user (and for clusters like cyan that are intentionally not using the per-node hostname in the UI certs (that's not an option for letsencrypt), there's no way to suppress the message so it will just be a persistent false positive). This message is also not as critical because users will see the browser warning if they get this wrong (as opposed to the mostly-hidden node-to-node connections).  I don't think this warning is worth including given the chance of false positives and the fact that most users will either get both certs right or both wrong. 
</blockquote></details>

Ok, removed the Shout.
___
*[pkg/base/addr_validation.go, line 200 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/28502#-LJtYXVyEi833zr_sHpp:-LJtapsp4vpPXA8GIUw1:bej1p8g) ([raw file](https://github.com/cockroachdb/cockroach/blob/c569dd5c9e6fd9b452f0f07d8e167dbd57b936f8/pkg/base/addr_validation.go#L200)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

When does the default port 26257 get applied?
</blockquote></details>

The caller does, it's the default value of the string in `cli/flags.go`.

**Comment by knz** [comment]
Thanks for all the feedback. I'll take suggestions for improvements if anything needs tweaking.

bors r+

**Pull request merged**
