### PR TITLE
cli/demo: Deflake Example_demo

### LINKED ISSUE #56846: cli: Example_demo failed
[(cli).Example_demo failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=2453878&tab=buildLog) on [master@06944cb1996ed9ccfa036118b810e46673fe0ff4](https://github.com/cockroachdb/cockroach/commits/06944cb1996ed9ccfa036118b810e46673fe0ff4):

Fatal error:
```
panic: interface conversion: interface {} is *withstack.withStack, not *server.TestServer [recovered]
	panic: interface conversion: interface {} is *withstack.withStack, not *server.TestServer

```

Stack:
```
goroutine 1 [running]:
testing.(*InternalExample).processRunResult(0xc004a85ca0, 0xc0044a8700, 0xef, 0x4925bcd2, 0x410b3e0, 0xc0055ee750, 0x432b54)
	/usr/local/go/src/testing/example.go:89 +0x648
testing.runExample.func2(0xbfe54d6cdc75a887, 0x1d3cea0884, 0x7678880, 0xc000466528, 0xc000126008, 0xc003a4e900, 0xc004a85ca0, 0xc004a85cd0)
	/usr/local/go/src/testing/run_example.go:58 +0x10d
panic(0x410b3e0, 0xc0055ee750)
	/usr/local/go/src/runtime/panic.go:969 +0x1b9
github.com/cockroachdb/cockroach/pkg/cli.(*transientCluster).start(0xc00755cc80, 0x53d0200, 0xc000124010, 0x734f820, 0x0, 0x0, 0xc004a852c0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo_cluster.go:162 +0x11ce
github.com/cockroachdb/cockroach/pkg/cli.runDemo(0x734f820, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:279 +0x38c
github.com/cockroachdb/cockroach/pkg/cli.glob..func8(0x734f820, 0xc0052cf9e0, 0x0, 0x3, 0xc0038b6cf0, 0xd)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/demo.go:52 +0x33
github.com/cockroachdb/cockroach/pkg/cli.MaybeDecorateGRPCError.func1(0x734f820, 0xc0052cf9e0, 0x0, 0x3, 0x0, 0x0)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/error.go:193 +0x79
github.com/spf13/cobra.(*Command).execute(0x734f820, 0xc0052cf8f0, 0x3, 0x3, 0x734f820, 0xc0052cf8f0)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:826 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0x73469a0, 0xc000466528, 0xc004a858d0, 0x1)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/cockroachdb/cockroach/vendor/github.com/spf13/cobra/command.go:864
github.com/cockroachdb/cockroach/pkg/cli.Run(...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli.go:226
github.com/cockroachdb/cockroach/pkg/cli.cliTest.RunWithArgs.func1(0xc0034ee6c0, 0x4, 0x4, 0x0, 0xc00105c4b0, 0x44, 0x4d7e578, 0xc000126690, 0x0, 0x0, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli_test.go:359 +0x2ab
github.com/cockroachdb/cockroach/pkg/cli.cliTest.RunWithArgs(0x0, 0xc00105c4b0, 0x44, 0x4d7e578, 0xc000126690, 0x0, 0x0, 0x0, 0xc0034ee6c0, 0x4, ...)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli_test.go:360 +0x85
github.com/cockroachdb/cockroach/pkg/cli.Example_demo()
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/cli_test.go:448 +0x7f3
testing.runExample(0x46d3356, 0xc, 0x4d7dfc0, 0x4c4cfcc, 0x45e, 0x0, 0x0)
	/usr/local/go/src/testing/run_example.go:62 +0x209
testing.runExamples(0xc004a85e48, 0x7358fe0, 0x18, 0x18, 0xbfe54fa579c21700)
	/usr/local/go/src/testing/example.go:44 +0x1af
testing.(*M).Run(0xc000d1bd00, 0x0)
	/usr/local/go/src/testing/testing.go:1346 +0x273
github.com/cockroachdb/cockroach/pkg/cli_test.TestMain(0xc000d1bd00)
	/go/src/github.com/cockroachdb/cockroach/pkg/cli/main_test.go:34 +0x8e
main.main()
	_testmain.go:235 +0x165

```

<details><summary>Log preceding fatal error</summary><p>

```
=== RUN   Example_demo
[demo -e show database]
W201118 06:24:52.199831 1 server/status/runtime.go:311  [n?] could not parse build timestamp: parsing time "" as "2006/01/02 15:04:05": cannot parse "" as "2006"
E201118 06:24:52.207400 1 cli/error.go:398  listen tcp 127.0.0.1:8080: bind: address already in use
[demo -e show database --empty]
--- FAIL: Example_demo (1.23s)

```

</p></details>

<details><summary>More</summary><p>
Parameters:

- TAGS=
- GOFLAGS=-parallel=4

```
make stressrace TESTS=Example_demo PKG=./pkg/cli TESTTIMEOUT=5m STRESSFLAGS='-timeout 5m' 2>&1
```

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2AExample_demo.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by knz**
Fixes #56846.

See individual commits for details.

### CODE REVIEW

**Review by otan — APPROVED** [review]
> Reviewed 5 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56865)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]
lgtm!

looks like bazel deps need to be updated

**Comment by knz** [comment]
@tbg could you have a cursory look at my TestServer changes? CI is failing repeatedly but I am not getting a clear message (test process terminates with exit 1 or 2 but without logs / errors).

**Comment by knz** [comment]
oh hm the problems disappeared after a rebase. Oh well :shrug: 

bors r=rafiss,otan

**Pull request merged**
