### PR TITLE
sql/parser: support nullable arguments in builtin functions

### LINKED ISSUE #9754: sql: more specific error message when there are too many overloads
If there is more than one overload eligible for selection even after all the heuristics have attempted to unambiguously pick one, the current error message suggests that there is no such method, which is slightly misleading when in fact there are actually _too many_ such methods.

### LINKED ISSUE #9920: sql: type error on ABS(NULL)
```
root@:26257> SELECT ABS(NULL);
pq: unknown signature for ABS: ABS(NULL)
root@:26257> SELECT ABS(NULL :: FLOAT);
+------------------+
| ABS(NULL::FLOAT) |
+------------------+
| NULL             |
+------------------+
(1 row)
```

I would expect `NULL` in the first case as well.

### LINKED ISSUE #12968: sql: nullable arguments in builtin functions are unsupported
It is currently impossible to define a builtin function that accepts an optionally-null argument because of the way the overload resolver deals with `NULL`.

There's at least one builtin function that requires a nullable argument: see the discussion of `format_type()` in #12967.

This issue tracks the work necessary to enhance the overload resolver to deal with nullable arguments.

### PR DESCRIPTION
**Pull request by nvb**
Fixes #12968.
Fixes #9920.
Fixes #9754.

This change reworks how NULL arguments are handled during type checking
for `FuncExprs`, `UnaryOps`, `CmpOps`, and `BinOps`. In doing so, it
also fixes a latent bug we had where the latter two expressions would
return NULL when given a NULL argument even when no candidate overload
would be possible. For instance: `'hello' + NULL` returned NULL, even
though we had no `<string> + <T>` operator. We were actually testing
this behavior in `TestTypeCheck`, so those tests had to change.

It does addresses this by returning all compatible candidate functions from
`typeCheckOverloadedExprs`. This improvement to the function's interface
allows us to distinguish impossible overload resolution from ambiguous
resolution. We then return NULL if **1 or more** candidates are possible
and there is a NULL argument.

To compliment this, we add a `nullableArgs` flag on the `Builtin` struct
so that the few implementations that want a chance to see the NULL
values can. This means that we can selectively disable the NULL
fast-path for certain builtins.

Please note that I'm not currently satisfied with the structure of
`typeCheckOverloadedExprs` or its conflation of the terms `overload` and
`candidate`. I plan to address these in a later change though that will
pull the operations of `typeCheckOverloadedExprs` into an
`overloadResolver` type.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/13031)

### CODE REVIEW

**Comment by knz** [comment]
Before I review this let me state that I think the commit message (and the PR descr) is not sufficiently informative.

For one built-in functions *already* accept "nullable" arguments -- passing a NULL value of the suitable type to any built-in currently works perfectly fine (and returns NULL as expected), so the current commit message is misleading.

Then this change is not really about "accepting nullable arguments" but rather **selectively disable the previous type checking and evaluation fast path in presence of a null argument value** so that the computation code of the built-in function is given a chance to see the null value.

Also as usual I will ask you to re-state or summarize the problem being solved in the commit message :)

**Comment by jordanlewis** [comment]
@knz, I think you are only partially correct in the statement that built-ins already accept "nullable" arguments. In the case of the `col_description` function that spawned this issue, the overload resolver actually fails to find a match when passing NULL as the second argument to the function:

```
root@:26257> select format_type(3,null);
pq: unknown signature: pg_catalog.format_type(int, NULL)
````

**Comment by knz** [comment]
It works just fine to me: `select format_type(3, null::int)` just returns NULL currently.

What is this PR trying to fix exactly?
It seems to me that it's trying to do two things at the same time (that may need to be separated):

- properly handle the NULL *type* during overload resolution (I may want to suggest that we could instead change the implicit typing rules to type a dangling NULL literal using the type demanded by its context, including the argument position type during overload resolution)

- make NULL *values* visible to built-in functions instead of an evaluation short-circuit to a null result.

**Comment by jordanlewis** [comment]
The suggestion in your first point (typing `null` in a position based on the type of the argument in that position) would resolve the issue I have with your example. We should not have to explicitly provide the type of `null` to get the overload resolver to work correctly in this case.

**Comment by knz** [comment]
Could you rebase this on top of #13896? I'd be interested to see the effects.

**Comment by nvanbenschoten** [comment]
I completely reworked this to address both related issues and I think the result is a lot more sound. PTAL.

**Comment by tamird** [comment]
Reviewed 1 of 8 files at r1.
Review status: 1 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/builtins.go, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kgyn8aJRxC7rTXac5Hh:-Kgyn8aJRxC7rTXac5Hi:bduwpcx) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c98a7535a6df9d62150e19348204320398985c7/pkg/sql/parser/builtins.go#L105)):*
> When
> 	// set, the function will be given the chance to see NULL values instead of
> 	// evaluating directly to NULL in the presence of any NULL values.

This is written in such a way that it assumes the reader already knows that otherwise functions called with NULL arguments evaluate immediately to NULL. Perhaps spell it out, if it's true, rather than assuming.

---

*[pkg/sql/parser/builtins.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgynJDuQ6FZ55o9UCS6:-KgynJDuQ6FZ55o9UCS7:brv8sla) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c98a7535a6df9d62150e19348204320398985c7/pkg/sql/parser/builtins.go#L108)):*
> ```Go
> 	// evaluating directly to NULL in the presence of any NULL values.
> 	//
> 	// NOTE: when set, a function should be prepared for any of its arguments to
> ```

Looks like all functions that have this set are variadic. Perhaps this can be encoded in the Types field, rather than having a separate flag?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/parser/builtins.go, line 105 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kgyn8aJRxC7rTXac5Hh:-KgzBM1SIBJ77Wf2wifl:b-qu6n94) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c98a7535a6df9d62150e19348204320398985c7/pkg/sql/parser/builtins.go#L105)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

> When
> 	// set, the function will be given the chance to see NULL values instead of
> 	// evaluating directly to NULL in the presence of any NULL values.

This is written in such a way that it assumes the reader already knows that otherwise functions called with NULL arguments evaluate immediately to NULL. Perhaps spell it out, if it's true, rather than assuming.
</blockquote></details>

Good point. Done.

---

*[pkg/sql/parser/builtins.go, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgynJDuQ6FZ55o9UCS6:-KgzAlfzIV0cax1uyCFK:bqdntoy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c98a7535a6df9d62150e19348204320398985c7/pkg/sql/parser/builtins.go#L108)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Looks like all functions that have this set are variadic. Perhaps this can be encoded in the Types field, rather than having a separate flag?
</blockquote></details>

`format_type` is the function that prompted part of this change, and it's not variadic. What you're suggesting is actually what we used to do, and confusing those ideas is what got us in trouble. Better to keep the concepts orthogonal

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031)*

**Comment by eisenstatdavid** [comment]
Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 110 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgztpecRm-I_SVwndrR:-KgztpecRm-I_SVwndrS:baiiimt) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/builtins.go#L110)):*
> ```Go
> 	//
> 	// NOTE: when set, a function should be prepared for any of its arguments to
> 	// be NULL and should act accordinly.
> ```

nit: accordingly

---

*[pkg/sql/parser/overload.go, line 176 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kgzv2tuKvRMNgLAoZzt:-Kgzv2tuKvRMNgLAoZzu:b-gnqp31) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/overload.go#L176)):*
> ```Go
> 
> func (v VariadicType) matchAt(typ Type, i int) bool {
> 	return typ == TypeNull || v.Typ.Equivalent(typ)
> ```

What is this change for?

---

*[pkg/sql/parser/overload.go, line 529 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kgzx4TlDWxQrCsnims_:-Kgzx4Tmz-u6cVtnR0YM:b-ycujwp) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/overload.go#L529)):*
> ```Go
> 	}
> 
> 	// The final heuristic is to defer to preferred candidates, if available.
> ```

Why did this block move?

---

*[pkg/sql/parser/type_check.go, line 1034 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgzwSa9QLOkOSSjgBAB:-KgzwSa9QLOkOSSjgBAC:bae45jl) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/type_check.go#L1034)):*
> ```Go
> 
> 	// Throw a typing error if overload resolution found either no compatible candidates
> 	// or if it found an ambiguity.
> ```

Can we give different error messages in these cases?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031)*

**Comment by knz** [comment]
I like the new implementation much better, but like eisen I have a couple questions.

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 12 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/eval.go, line 2383 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgzyBCC611wyDBnJM8K:-KgzyBCDyZtPEtkeNRs-:b75h45y) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/eval.go#L2383)):*
> ```Go
> 			return nil, err
> 		}
> 		if arg == DNull && !expr.fn.nullableArgs {
> ```

Many elegance, such conciseness. Wow, amaze. :dog: :100: 

---

*[pkg/sql/parser/overload.go, line 85 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgzyeG6jX4B2Sgw78DL:-KgzyeG76zOVHdwXjjB8:b-kqe0nf) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/overload.go#L85)):*
> ```Go
> 		typ = TypeTuple
> 	}
> 	return i < len(a) && (typ == TypeNull || a[i].Typ.Equivalent(typ))
> ```

This change is qualitatively different from the rest: instead of merely providing NULL *values* to calls, it also makes the NULL *type* blindly a valid argument to any call. Is that what we want? 
If so please justify this in a comment here.

I think it also should change the error messages in some cases, from a "function with this signature was not found" to "this call is ambiguous" (e.g. `abs(null)`, because now `null` matches both for the `decimal` and `float` impls). I am confused why your test suggests otherwise.

---

*[pkg/sql/parser/overload_test.go, line 179 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kh--O2ExC6fahov8063:-Kh--O2FeFkGaGC-CxTp:bfquwpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/overload_test.go#L179)):*
> ```Go
> 		if len(fns) == 1 {
> 			fn = fns[0]
> 		}
> ```

Since you're here you could add an `else` branch here and adopt #10955 into it.

---

*[pkg/sql/parser/type_check.go, line 127 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kh--erJdLr4_2zNpFK4:-Kh--erLaUtj7l7ZKoij:b-kisnky) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/type_check.go#L127)):*
> ```Go
> 	// Return NULL if at least one overload is possible and NULL is an argument.
> 	if len(fns) > 0 {
> 		if leftReturn == TypeNull || rightReturn == TypeNull {
> ```

Don't you also need to check here that none of the overloads accepts null arguments, like you do below in TypeCheck. If any does, it still would need to be called.

---

*[pkg/sql/parser/type_check.go, line 134 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kh--rVG3i9_CUMqNw_m:-Kh--rVHAU5v8GfluXzh:b-xwfkgw) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/type_check.go#L134)):*
> ```Go
> 	// Throw a typing error if overload resolution found either no compatible candidates
> 	// or if it found an ambiguity.
> 	if len(fns) != 1 {
> ```

ditto here re overlap with #10955

---

*[pkg/sql/parser/type_check.go, line 1018 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kh-0l5dXx-X2XDRlh83:-Kh-0l5f09eCYnmDupYQ:b5u05vg) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/type_check.go#L1018)):*
> ```Go
> 	rightReturn := rightExpr.ResolvedType()
> 
> 	// Return NULL if at least one overload is possible and NULL is an argument.
> ```

I don't understand how this comment matches the code below it. Please clarify.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-:-Kh-1ICjTFQzlX9t2K2i:b-zfbzm)*

**Comment by nvanbenschoten** [comment]
Thanks for taking a look! I improved the `TestTypeCheckOverloadedExprs` to test error cases to a greater extent and adopted the changes proposed in #10955 to work with the new `typeCheckOverloadedExprs` interface.

---

Review status: 1 of 8 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[pkg/sql/parser/builtins.go, line 110 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgztpecRm-I_SVwndrR:-KhPdXFNuru5unP9HRVB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/builtins.go#L110)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

nit: accordingly
</blockquote></details>

Done.

---

*[pkg/sql/parser/overload.go, line 85 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgzyeG6jX4B2Sgw78DL:-KhR0S7W1lDGEk3VsWUR:b-h2x6yk) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/overload.go#L85)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

This change is qualitatively different from the rest: instead of merely providing NULL *values* to calls, it also makes the NULL *type* blindly a valid argument to any call. Is that what we want? 
If so please justify this in a comment here.

I think it also should change the error messages in some cases, from a "function with this signature was not found" to "this call is ambiguous" (e.g. `abs(null)`, because now `null` matches both for the `decimal` and `float` impls). I am confused why your test suggests otherwise.
</blockquote></details>

I think the issue here comes down to our lack of distinction between typed and untyped NULL values. We should be accepting untyped NULL values here, but typed NULL values should undergo the same type checking as all other typed values. An example that demonstrates this issue is `1+(1+NULL)` vs. `1+('str'||NULL)`. Clearly, we should be accepting the first expression but throwing an error for the second expression. The most straightforward way to approach this would be to remove all NULL short circuits during type checking and propagate up the resolved expressions even in the presence of NULL arguments. This would provide us with access to the type of the expression when typing parent expressions, even when we know it will later be simplified to NULL.

However, this approach is somewhat at odds with the proposal made in #9920. There, we would return an expression during type checking even when we found an ambiguity during overload resolution as long as some of the arguments were NULL. This means that the expression could have multiple types and upper levels would need to be able to handle them all. I'm not exactly sure how we want to approach this situation.

Per your second comment: Improved error messages in the third commit.

---

*[pkg/sql/parser/overload.go, line 176 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kgzv2tuKvRMNgLAoZzt:-KhR0h7xAQrRNiQTbTOA:b-f8sf1p) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/overload.go#L176)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

What is this change for?
</blockquote></details>

Added a comment.

---

*[pkg/sql/parser/overload.go, line 529 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kgzx4TlDWxQrCsnims_:-KhR0uZWAFCXqlJ0cIKm:b-fdir9v) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/overload.go#L529)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Why did this block move?
</blockquote></details>

It was in the wrong place. We shoudn't have performed the `defaultTypeCheck` until after all candidate filtering had completed and resulted in an ambiguity.

---

*[pkg/sql/parser/overload_test.go, line 179 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kh--O2ExC6fahov8063:-KhPwQQR-lk0-pObaylY:bna7hc) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/overload_test.go#L179)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Since you're here you could add an `else` branch here and adopt #10955 into it.
</blockquote></details>

Improved this test by distinguishing ambiguous resolution results from unsupported resolution results.

---

*[pkg/sql/parser/type_check.go, line 127 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kh--erJdLr4_2zNpFK4:-KhPwJybf2M8VMeZ1IM8:b-re0pzj) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/type_check.go#L127)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Don't you also need to check here that none of the overloads accepts null arguments, like you do below in TypeCheck. If any does, it still would need to be called.
</blockquote></details>

That's only an option for `Builtin` functions.

---

*[pkg/sql/parser/type_check.go, line 134 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kh--rVG3i9_CUMqNw_m:-KhPvy39SSb1Fv6btZF4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/type_check.go#L134)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

ditto here re overlap with #10955
</blockquote></details>

Done.

---

*[pkg/sql/parser/type_check.go, line 1018 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-Kh-0l5dXx-X2XDRlh83:-KhR-AGWuC7kG7QhVf2v:b-2wn92b) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/type_check.go#L1018)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I don't understand how this comment matches the code below it. Please clarify.
</blockquote></details>

It looks like we have never been simplifying `ComparisonExpr` to NULL during type checking like we do for other function-like expressions. Fixed. Thanks for catching that.

---

*[pkg/sql/parser/type_check.go, line 1034 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgzwSa9QLOkOSSjgBAB:-KhPvF2NWdlAbXvJt3Sa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/type_check.go#L1034)):*
<details><summary><i>Previously, eisenstatdavid (David Eisenstat) wrote…</i></summary><blockquote>

Can we give different error messages in these cases?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-:-KhR1YLnrGtNbqZSqXpL:b-lo2ybs)*

**Comment by knz** [comment]
:lgtm: but I really want to pursue the question of typed NULLs; please see my comment underneath, and either follow up here or file a separate issue. The short circuiting of NULL is important for performance (it is silly to mandate a separate traversal to fold NULLs when we could just use one) but we also need to clear out typing problems properly.

---

Reviewed 4 of 6 files at r3, 1 of 1 files at r4, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/overload.go, line 85 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgzyeG6jX4B2Sgw78DL:-KhRKAlHPjEwLXBFl8UN:bo4mgi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/overload.go#L85)):*
> I think the issue here comes down to our lack of distinction between typed and untyped NULL values. We should be accepting untyped NULL values here, but typed NULL values should undergo the same type checking as all other typed values.

I do not understand the distinction between "typed and untyped" null values. To me every NULL value is typed, by its context; if there is insufficient information to decide typing, that qualifies as ambiguous typing to me.

> An example that demonstrates this issue is 1+(1+NULL) vs. 1+('str'||NULL). Clearly, we should be accepting the first expression but throwing an error for the second expression.

Yes; the way to do that in the second case is to fold `'str'||NULL` as a NULL value typed with `TypeString`.

> The most straightforward way to approach this would be to remove all NULL short circuits during type checking and propagate up the resolved expressions even in the presence of NULL arguments. This would provide us with access to the type of the expression when typing parent expressions, even when we know it will later be simplified to NULL.

Why "later"? Why not simply introducing typed NULL constants? Like "DNullString", "DNullInt", etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-:-KhRK92cm_zv4AcYBQ9I:bgwworx)*

**Comment by eisenstatdavid** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/parser/overload.go, line 85 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-KgzyeG6jX4B2Sgw78DL:-KhSGFhnFNADqOQd11Nk:b579jjc) ([raw file](https://github.com/cockroachdb/cockroach/blob/baa7750d470b7893015dad1d0b03ff24c1f3c8c4/pkg/sql/parser/overload.go#L85)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

> I think the issue here comes down to our lack of distinction between typed and untyped NULL values. We should be accepting untyped NULL values here, but typed NULL values should undergo the same type checking as all other typed values.

I do not understand the distinction between "typed and untyped" null values. To me every NULL value is typed, by its context; if there is insufficient information to decide typing, that qualifies as ambiguous typing to me.

> An example that demonstrates this issue is 1+(1+NULL) vs. 1+('str'||NULL). Clearly, we should be accepting the first expression but throwing an error for the second expression.

Yes; the way to do that in the second case is to fold `'str'||NULL` as a NULL value typed with `TypeString`.

> The most straightforward way to approach this would be to remove all NULL short circuits during type checking and propagate up the resolved expressions even in the presence of NULL arguments. This would provide us with access to the type of the expression when typing parent expressions, even when we know it will later be simplified to NULL.

Why "later"? Why not simply introducing typed NULL constants? Like "DNullString", "DNullInt", etc.


</blockquote></details>

Can we just treat NULL as a new constant literal with every single type in its resolvable set?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/13031#-:-KhSGoN9W5-bukIb4Kld:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
Superseded by #17264.

**Pull request closed without merging**
