### PR TITLE
sql: integrate support bundle with diagnostics

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### sql: statement diagnostics cleanup

Minor cleanup of the statement diagnostics infrastructure:
 - use a custom type `stmtDiagRequestID` instead of int
 - use maps instead of slices
 - `InsertRequest` no longer returns an ID (it wasn't useful for an external
   caller).

Release note: None

#### sql: integrate support bundle with diagnostics

This change integrates the logic of getting a support bundle with statement
diagnostics. When diagnostics are requested for a fingerprint, the bundle is now
created along with the trace.

EXPLAIN BUNDLE now shares the same logic and it now generates a bundle even if
the query hits an error (in which case the bundle information is added to the
error as a DETAIL.

To make the code easier to follow, we replace the func returned by
`shouldCollectDiagnostics` with a helper type that stores the necessary
information.

Release note: None

Release justification: Category 2 (fixes/updates to new functionality).

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45997)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/conn_executor_exec.go, line 206 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45997#-M2FJCogD_tTDwsxCBmz:-M2FJCogD_tTDwsxCBn-:b5xdghn) ([raw file](https://github.com/cockroachdb/cockroach/blob/8460b94dcebe61cc1628365a7df7bd0222fbb23d/pkg/sql/conn_executor_exec.go#L206)):*
> ```Go
> 	}()
> 
> 	// stmtDiagPlan is set below.
> ```

nit: unnecessary comment
___
*[pkg/sql/statement_diagnostics.go, line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45997#-M2FJ-dK-MnRw4_U2i9A:-M2FJ-dK-MnRw4_U2i9B:ben6xyb) ([raw file](https://github.com/cockroachdb/cockroach/blob/8460b94dcebe61cc1628365a7df7bd0222fbb23d/pkg/sql/statement_diagnostics.go#L201)):*
> ```Go
> 	if explainBundle, ok := ast.(*tree.ExplainBundle); ok {
> 		// Always collect diagnostics for EXPLAIN BUNDLE.
> 		fingerprint := tree.AsStringWithFlags(explainBundle.Statement, tree.FmtHideConstants)
> ```

How hard would it be to keep the handling of `explain bundle` out of here? Which would mean that a `stmtDiagHelper` with an id of 0 would also go away.
I think exposing `insertDiagnostics` to the SQL package is cool, though.
___
*[pkg/sql/statement_diagnostics.go, line 501 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45997#-M2FKSdZ4FG73qRTahgA:-M2FKSdZ4FG73qRTahgB:b-6u32cv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8460b94dcebe61cc1628365a7df7bd0222fbb23d/pkg/sql/statement_diagnostics.go#L501)):*
> ```Go
> // traceToJSON converts a trace to a JSON datum suitable for the
> // system.statement_diagnostics.trace column. In case of error, the returned
> // datum is DNull. Also returns the string representation of the trace.
> ```

Do we really need the string if we return that datum?

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/statement_diagnostics.go, line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45997#-M2FJ-dK-MnRw4_U2i9A:-M2FhYPt8mrJqmZ_MqLc:bb6mlse) ([raw file](https://github.com/cockroachdb/cockroach/blob/8460b94dcebe61cc1628365a7df7bd0222fbb23d/pkg/sql/statement_diagnostics.go#L201)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

How hard would it be to keep the handling of `explain bundle` out of here? Which would mean that a `stmtDiagHelper` with an id of 0 would also go away.
I think exposing `insertDiagnostics` to the SQL package is cool, though.

</blockquote></details>

I'll give that a shot.

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45997)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

___
*[pkg/sql/statement_diagnostics.go, line 201 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45997#-M2FJ-dK-MnRw4_U2i9A:-M2KTHzC-KtOmK32TWrS:b-3wcv3p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8460b94dcebe61cc1628365a7df7bd0222fbb23d/pkg/sql/statement_diagnostics.go#L201)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'll give that a shot.
</blockquote></details>

Updated PR with the version we looked at offline.
___
*[pkg/sql/statement_diagnostics.go, line 501 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45997#-M2FKSdZ4FG73qRTahgA:-M2KTL7G-gUdpOn7IOfI:b-7ll2ec) ([raw file](https://github.com/cockroachdb/cockroach/blob/8460b94dcebe61cc1628365a7df7bd0222fbb23d/pkg/sql/statement_diagnostics.go#L501)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Do we really need the string if we return that datum?
</blockquote></details>

It's nicely formatted so I'm using it to put the trace in the bundle as a .json text file.

**Comment by andreimatei** [comment]
LGTM

**Pull request merged**
