### PR TITLE
 opt: return struct from index rec library instead of formatted string

### LINKED ISSUE #85955: create index recommendation []string on instrumentation
Currently the value on `instrumentation.indexRecommendations` returns the format
```
{
"index recommendations: 2",
"   1. type: index replacement",
"   SQL commands: CREATE UNIQUE INDEX ON t1 (i) STORING (k); DROP INDEX t1@existing_t1_i;",
"   2. type: index creation",
"   SQL command: CREATE INDEX ON t2 (i) STORING (k);",
}
```

When being stored on `statement_statistics` this needs to be parsed, increasing the chances of errors if this format changes.
We need a list of just the recommendations, for example by having `IndexRecommendationSet.Output` returning a []string consisting of just the SQL statements, like `[]string{"CREATE INDEX ON t (a)"}`, and store this on instrumentation.

Jira issue: CRDB-18501

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: simplify the IndexRecommendationSet type

Release justification: This is a low-risk change to existing
functionality.

Release note: None

#### opt: rename some index recommendation functions

Some of the methods of `indexrec.IndexRecommendationSet` have been
renamed to be less redundant.

Release justification: This is a very minor change.

Release note: None

#### opt: return struct from index rec library instead of formatted string

Previously, the `indexrec` package returned a formatted string as the
final recommendation result. The string was formatted specificaly for
the output of `EXPLAIN`. This had limited utility. To create index
recommendations in the `statement_statistics` table, we were parsing the
string output.

This commit updates the `indexrec` package to return a slice of structs
rather than a slice of strings that are formatted for `EXPLAIN` output.
The recommendations can now be consumed in different contexts without
having to parse a string.

Fixes #85955

Release justification: This is a minor change to new functionality.

Release note: None

#### opt: simplify filenames in indexrec

Release justification: This is a non-code change.

Release note: None

### CODE REVIEW

**Review by maryliag — CHANGES_REQUESTED** [review]
Thank you for working on this! Awesome improvement! Just a minor change you will need to do

> Reviewed 13 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86754#-:-NAF6uiF0jfntnct29eI:blguag5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @mgartner, and @wenyihu6)

___
*[`pkg/sql/idxrecommendations/idx_recommendations.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86754#-NAF6N3L7Nr6L2igInvN:-NAF6N3L7Nr6L2igInvO:b2l73hj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbcb3eab0a6b6ac0b71088ec24fd6deecae2ce78/pkg/sql/idxrecommendations/idx_recommendations.go#L51)):*
> ```Go
> 	recommendations := make([]string, len(recs))
> 	for i := range recs {
> 		recType := "index creation"
> ```

you can remove the "index" and have just "creation" and just "replacement" below, to match the description of what this function does. Also your tests will probably fail with the extra word that are not expected on the final result
(on the UI we're also not expecting to see the "index" word)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86754)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @maryliag, and @wenyihu6)

___
*[`pkg/sql/idxrecommendations/idx_recommendations.go` line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/86754#-NAF6N3L7Nr6L2igInvN:-NAF9Ilk-dXfoIuBfMY5:bxiq7pj) ([raw file](https://github.com/cockroachdb/cockroach/blob/dbcb3eab0a6b6ac0b71088ec24fd6deecae2ce78/pkg/sql/idxrecommendations/idx_recommendations.go#L51)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

you can remove the "index" and have just "creation" and just "replacement" below, to match the description of what this function does. Also your tests will probably fail with the extra word that are not expected on the final result
(on the UI we're also not expecting to see the "index" word)
</blockquote></details>

Thanks for catching this! Fixed.

**Review by maryliag — APPROVED** [review]
Changes related to how is being used/saved for statement statistics :lgtm: 

> Reviewed 15 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86754#-:-NAFJO2GA2pTwfbOLBrs:b-9136pb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @wenyihu6)

**Comment by wenyihu6** [comment]
It's possible I'm biased; do you think it's worth changing this [struct]( https://github.com/cockroachdb/cockroach/blob/8f6923b5ec401eaa2b523486e718a5cd523328fe/pkg/sql/opt/indexrec/rec.go#L26-L32) to an interface? And we can create three types of structs that implement this interface.

```
type Rec interface {
    sqlString() // return "CREATE INDEX ..."
    recType() // return "index creation"
}

type CreateIndex struct {
     SQL string
     retType string
}

type IndexReplacement struct {
     SQL string
     retType string
}

type AlterIndexVisible struct {
     SQL string
     retType string
}
```

When you constructed the struct Rec, you know the type of index recommendation, what sql string you want to output already. Every time when you use Rec instances, instead of using if statements to check, and printing out different things, having an interface that returns what string to print out for different index rec type seems to be cleaner. We are only introducing three types of index rec now (create index, replacement, alter index visibility). But it's possible that we want to introduce more types of index rec in the future, and the if statement can become really long. This would make these two parts of the code easier. 
https://github.com/cockroachdb/cockroach/blob/8f6923b5ec401eaa2b523486e718a5cd523328fe/pkg/sql/idxrecommendations/idx_recommendations.go#L50-L54
https://github.com/cockroachdb/cockroach/blob/8f6923b5ec401eaa2b523486e718a5cd523328fe/pkg/sql/explain_plan.go#L145-L152

Also, we are adding these printing statements in pkg/sql/explain_plan.go and pkg/sql/idxrecommendations/idx_recommendations.go which are outside of the pkg/sql/opt/indexrec folder. It's easy to forget updating them when someone is updating indexrec.

If we don't want to introduce an interface, adding struct methods inside index rec folder that does if statement check and return is also sufficient.

```
type Rec struct {
	// SQL is the statement(s) to run that will apply the recommendation.
	SQL string
	// Replacement is true if SQL replaces an existing index, i.e., it contains
	// both a CREATE INDEX and DROP INDEX statement.
	Replacement bool
}

func (rec Rec) retType() string {
 if Replacement{ return "index replacement"}
else {return "index creation"}
}

func (rec Rec) sqlStmt() string {
 if Replacement{ return "SQL commands: ...."}
else ...
}
```

**Comment by mgartner** [comment]
In Go, interfaces are primarily used to describe a set of _actions_ or _verbs_ that a type can perform, not a _thing_ itself. As opposed to classes in object-oriented languages, they are generally not used to create hierarchies or groups of types, like in the example you provided. While we don't explicitly mention avoiding this pattern in our [coding guidelines](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/181371303/Go+Golang+coding+guidelines), I (and I think most others) would consider it non-idiomatic Go.

Instead of abstract type hierarchies, we should think about the concrete representation of the _data_ (e.g., the recommendations) that we are working with. The different types of recommendations are all physically (their in-memory structure) very similar - they are all SQL strings. An interface doesn't provide any benefit from what I can tell. And there are downsides to using an interface including a possible heap allocation (an interface is a pointer to data and a type; in many cases the data will be allocated on the heap), obfuscating the nature of the _data_ we are working with, and more lines of code.

Your concern with many `if` statements for generating rec type strings is more idiomatically handled by defining a `String` method for the enum representing the type of the recommendation. For example:

```go
// Rec represents an index recommendation in the form of a SQL statement(s)
// that can be executed to apply the recommendation.
type Rec struct {
	// SQL is the statement(s) to run that will apply the recommendation.
	SQL string
	// Type is the type of the recommendation.
	Type Type
}

type Type uint8

const (
	TypeCreate Type = iota
	TypeReplace
	TypeAlter
)

func (t Type) String() string {
	switch t {
	case TypeCreate:
		return "index creation"
	case TypeReplace:
		return "index replacement"
	case TypeAlter:
		return "index alter"
	default:
		return "invalid"
	}
}

func formatRec(r Rec) string {
	// No if's necessary!
	return fmt.Sprintf("SQL: %s, Type: %s", r.SQL, r.Type.String())
}
```

If we need to add a new type of recommendation, it's as simple as:

```diff
 const (
 	TypeCreate Type = iota
 	TypeReplace
 	TypeAlter
+	TypeMyNewType
 )
 
 func (t Type) String() string {
 	switch t {
 	case TypeCreate:
 		return "index creation"
 	case TypeReplace:
 		return "index replacement"
 	case TypeAlter:
 		return "index alter"
+	case TypeMyNewType:
+		return "a new type"
 	default:
 		return "invalid"
 	}
 }
```

**Comment by wenyihu6** [comment]
> 

I see. That makes sense. Thanks for explaining to me!

**Comment by mgartner** [comment]
> If we don't want to introduce an interface, adding struct methods inside index rec folder that does if statement check and return is also sufficient.

That's a possibility - but I'd argue that if the formatting of a `Rec` is context-dependent (which it appears to be), then the implementation of `Rec` shouldn't be concerned with providing methods for all the different ways it can be formatted. For example, if the index rec type formatting changes depending on context, then my `String` suggestion won't work, but I don't think the conclusion is that we should define multiple `XXXString()` methods. We can define helpers to format the type in the context that the `Rec` is used.

**Comment by wenyihu6** [comment]
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 2209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86754#-NAGTwJm9GtE9QDh4K35:-NAGTwJm9GtE9QDh4K36:bhnsmns) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f6923b5ec401eaa2b523486e718a5cd523328fe/pkg/sql/opt/testutils/opttester/opt_tester.go#L2209)):*
> ```Go
> 	md = optExpr.(memo.RelExpr).Memo().Metadata()
> 	indexRecommendations := indexrec.FindRecs(optExpr, md)
> 	result := indexRecommendations.Output()
> ```

```
--- a/pkg/sql/opt/testutils/opttester/opt_tester.go
+++ b/pkg/sql/opt/testutils/opttester/opt_tester.go
@@ -2206,12 +2206,23 @@ func (ot *OptTester) IndexRecommendations() (string, error) {
        }
        md = optExpr.(memo.RelExpr).Memo().Metadata()
        indexRecommendations := indexrec.FindRecs(optExpr, md)
-       result := indexRecommendations.Output()
+       var rows []string
+       rows = append(rows, fmt.Sprintf("index recommendations: %d", len(indexRecommendations)))
+       for i := range indexRecommendations {
+               plural := ""
+               recType := "index creation"
+               if indexRecommendations[i].Replacement {
+                       recType = "index replacement"
+                       plural = "s"
+               }
+               rows = append(rows, fmt.Sprintf("%d. type: %s", i+1, recType))
+               rows = append(rows, fmt.Sprintf("   SQL command%s: %s", plural, indexRecommendations[i].SQL))
+       }
 
-       if result == nil {
+       if indexRecommendations == nil {
                return fmt.Sprintf("No index recommendations.\n--\nOptimal Plan.\n%s", ot.FormatExpr(optExpr)), nil
        }
-       return fmt.Sprintf("%s\n--\nOptimal Plan.\n%s", strings.Join(result, "\n"), ot.FormatExpr(optExpr)), nil
+       return fmt.Sprintf("%s\n--\nOptimal Plan.\n%s", strings.Join(rows, "\n"), ot.FormatExpr(optExpr)), nil
 }
```

I think you need something like this here as well.

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86754)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball, @maryliag, and @wenyihu6)

___
*[`pkg/sql/opt/testutils/opttester/opt_tester.go` line 2209 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/86754#-NAGTwJm9GtE9QDh4K35:-NAGkgspCOif4OWS4Ih9:b-mz76ap) ([raw file](https://github.com/cockroachdb/cockroach/blob/8f6923b5ec401eaa2b523486e718a5cd523328fe/pkg/sql/opt/testutils/opttester/opt_tester.go#L2209)):*
<details><summary><i>Previously, wenyihu6 (Wenyi Hu) wrote…</i></summary><blockquote>

```
--- a/pkg/sql/opt/testutils/opttester/opt_tester.go
+++ b/pkg/sql/opt/testutils/opttester/opt_tester.go
@@ -2206,12 +2206,23 @@ func (ot *OptTester) IndexRecommendations() (string, error) {
        }
        md = optExpr.(memo.RelExpr).Memo().Metadata()
        indexRecommendations := indexrec.FindRecs(optExpr, md)
-       result := indexRecommendations.Output()
+       var rows []string
+       rows = append(rows, fmt.Sprintf("index recommendations: %d", len(indexRecommendations)))
+       for i := range indexRecommendations {
+               plural := ""
+               recType := "index creation"
+               if indexRecommendations[i].Replacement {
+                       recType = "index replacement"
+                       plural = "s"
+               }
+               rows = append(rows, fmt.Sprintf("%d. type: %s", i+1, recType))
+               rows = append(rows, fmt.Sprintf("   SQL command%s: %s", plural, indexRecommendations[i].SQL))
+       }
 
-       if result == nil {
+       if indexRecommendations == nil {
                return fmt.Sprintf("No index recommendations.\n--\nOptimal Plan.\n%s", ot.FormatExpr(optExpr)), nil
        }
-       return fmt.Sprintf("%s\n--\nOptimal Plan.\n%s", strings.Join(result, "\n"), ot.FormatExpr(optExpr)), nil
+       return fmt.Sprintf("%s\n--\nOptimal Plan.\n%s", strings.Join(rows, "\n"), ot.FormatExpr(optExpr)), nil
 }
```

I think you need something like this here as well. 
</blockquote></details>

Nice catch, thanks!

Fixed. I also added another commit that simplifies the output of the tests - they don't need to mimic the EXPLAIN output anymore.

**Review by wenyihu6 — APPROVED** [review]
:lgtm: 

Sorry for taking so long! The rest looks good to me!

> Reviewed 8 of 15 files at r3, 3 of 6 files at r5, 3 of 3 files at r6, 1 of 15 files at r7, 8 of 10 files at r9, 4 of 6 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/86754#-:-NAJuU7I00MJLuXJU8dW:bhpoidm)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball)

**Comment by mgartner** [comment]
TFTRs!

The failure caused by #86838, which is unrelated.

bors r+

**Pull request merged**
