### PR TITLE
sql: allow rollback to savepoint regardless of txn state

### LINKED ISSUE #6850: sql: Allow `ROLLBACK TO SAVEPOINT` when nothing has happened
If a transaction function fails before issuing its first SQL query, the rollback operation fails: 

```
root@:26257> begin;
BEGIN
root@:26257> savepoint cockroach_restart;
OK
root@:26257> rollback to savepoint cockroach_restart;
pq: the transaction is not in a retriable state
```

The transaction should be retryable as soon as the savepoint statement is issued.

### PR DESCRIPTION
**Pull request by spencerkimball**
Removes one of @andreimatei's TODOs.

Fixes #6850

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14538)

### CODE REVIEW

**Comment by andreimatei** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/internal/client/txn.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-KgkGdQG4xj3nrTdQ_oE:-KgkGdQG4xj3nrTdQ_oF:b-dlx45i) ([raw file](https://github.com/cockroachdb/cockroach/blob/37b861c9b8c2af292504fc4ff6d5035638352848/pkg/internal/client/txn.go#L74)):*
> ```Go
> 		// stmtCount indicates how many statements have been sent through
> 		// this transaction. Reset on retryable txn errors.
> 		stmtCount int
> ```

mmm I think we should avoid putting this field in the `client.Txn`. It's sql-specific; let's try to track it at the sql level, if at all possible.
I could be convinced if you tell me that sql is already doing hacky things by looking at the txn's proto... I don't remember the issue around what youre fixing here very well but I'll look more if you think what you're doing is right.

---

*[pkg/sql/executor.go, line 1188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-KgkGOR45AQHoxFpvCsf:-KgkGOR45AQHoxFpvCsg:bxvyhw5) ([raw file](https://github.com/cockroachdb/cockroach/blob/37b861c9b8c2af292504fc4ff6d5035638352848/pkg/sql/executor.go#L1188)):*
> ```Go
> 	case *parser.RollbackToSavepoint:
> 		err := parser.ValidateRestartCheckpoint(s.Savepoint)
> 		// Return a not retriable error if the transaction is underway but
> ```

if we allow rollback-to-sp for a virgin txn, why not allow it for a non-virgin one regardless of its state?

---

*[pkg/sql/executor.go, line 1191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-KgkFuA4Blz78U_SbZw8:-KgkFuA4Blz78U_SbZw9:b-hb7uqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/37b861c9b8c2af292504fc4ff6d5035638352848/pkg/sql/executor.go#L1191)):*
> ```Go
> 		// not awaiting a restart. Rollback to the savepoint is legal for
> 		// a still-virgin transaction, where "virgin" includes the state of
> 		// a transaction which at the start of retrying.
> ```

something's off with the comment

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538)*

**Comment by spencerkimball** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/internal/client/txn.go, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-KgkGdQG4xj3nrTdQ_oE:-KgkMqr9Gq5OwLSWPpRi:b-cvyx8p) ([raw file](https://github.com/cockroachdb/cockroach/blob/37b861c9b8c2af292504fc4ff6d5035638352848/pkg/internal/client/txn.go#L74)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

mmm I think we should avoid putting this field in the `client.Txn`. It's sql-specific; let's try to track it at the sql level, if at all possible.
I could be convinced if you tell me that sql is already doing hacky things by looking at the txn's proto... I don't remember the issue around what youre fixing here very well but I'll look more if you think what you're doing is right.
</blockquote></details>

This has nothing to do with SQL. This is the number of commands sent via the kv transaction. I'm going to rename this as "commandCount" instead of "stmtCount" to eliminate confusion.

I tried at first to track this at the SQL level but it's very fragile there due to optimizations to batch, pipelining, etc. I think this is the right place to 

---

*[pkg/sql/executor.go, line 1188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-KgkGOR45AQHoxFpvCsf:-KgkNmTw0c9nbuGz3Hbd:bwi0bmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/37b861c9b8c2af292504fc4ff6d5035638352848/pkg/sql/executor.go#L1188)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

if we allow rollback-to-sp for a virgin txn, why not allow it for a non-virgin one regardless of its state?
</blockquote></details>

That's outside the scope of this PR, and would require a lot more careful thought.

---

*[pkg/sql/executor.go, line 1191 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-KgkFuA4Blz78U_SbZw8:-KgkNkhe-ydLxiDpgW7o:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/37b861c9b8c2af292504fc4ff6d5035638352848/pkg/sql/executor.go#L1191)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

something's off with the comment
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538)*

**Comment by andreimatei** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-KgkGOR45AQHoxFpvCsf:-KgoHW_wl2H67yvO59mG:b-1u47t6) ([raw file](https://github.com/cockroachdb/cockroach/blob/37b861c9b8c2af292504fc4ff6d5035638352848/pkg/sql/executor.go#L1188)):*
<details><summary><i>Previously, spencerkimball (Spencer Kimball) wrote…</i></summary><blockquote>

That's outside the scope of this PR, and would require a lot more careful thought.
</blockquote></details>

well but what is the scope of this PR exactly? Why do we need to special-case the virgin txns and allow `ROLLBACK TO SAVEPOINT` in them if we don't allow that afterwards? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538)*

**Comment by bdarnell** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-KgkGOR45AQHoxFpvCsf:-KgohGIOZKA-ojQmHaV4:b-x4zuus) ([raw file](https://github.com/cockroachdb/cockroach/blob/37b861c9b8c2af292504fc4ff6d5035638352848/pkg/sql/executor.go#L1188)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

well but what is the scope of this PR exactly? Why do we need to special-case the virgin txns and allow `ROLLBACK TO SAVEPOINT` in them if we don't allow that afterwards? 
</blockquote></details>

As far as I can remember, I filed #6850 because I was surprised that `ROLLBACK TO SAVEPOINT` would ever be rejected. I wasn't thinking that empty transactions should be a special case. I think I assumed that the problem was that the Transaction hadn't been initialized yet and didn't try it with a command that succeeded.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538)*

**Comment by spencerkimball** [comment]
I've changed things so the rollback to savepoint is always accepted. PTAL.

**Comment by andreimatei** [comment]
LGTM

commit message is now stale :)

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/txn_restart_test.go, line 950 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-Kgtedl2eCkRjemzXCkp:-Kgtedl2eCkRjemzXCkq:b-pfgnql) ([raw file](https://github.com/cockroachdb/cockroach/blob/350ace7f937f19503fae07de8c1a061569f97ba5/pkg/sql/txn_restart_test.go#L950)):*
> ```Go
> 		t.Fatal(err)
> 	}
> 	// ROLLBACK TO SAVEPOINT without an "empty" transaction.
> ```

I'm not sure what an empty transaction is, but this seems empty to me... I don't think you want this comment at all, as empty or not shouldn't matter.
In fact I don't think you want this test here at all; the logic one seems like a better place to me.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-:-Kgtdq-BgthT_en9WFgj:blnro0d)*

**Comment by spencerkimball** [comment]
Updated commit message.

---

Review status: 0 of 6 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/executor.go, line 1188 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-KgkGOR45AQHoxFpvCsf:-Kgu-RqVliH4xQLSVMW_:b-oqy86m) ([raw file](https://github.com/cockroachdb/cockroach/blob/37b861c9b8c2af292504fc4ff6d5035638352848/pkg/sql/executor.go#L1188)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

As far as I can remember, I filed #6850 because I was surprised that `ROLLBACK TO SAVEPOINT` would ever be rejected. I wasn't thinking that empty transactions should be a special case. I think I assumed that the problem was that the Transaction hadn't been initialized yet and didn't try it with a command that succeeded.
</blockquote></details>

I've changed it to allow rollback to savepoint at any arbitrary point in the transaction.

---

*[pkg/sql/txn_restart_test.go, line 950 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-Kgtedl2eCkRjemzXCkp:-Kgu0_FTYVw5NA99I_kk:bp9gk0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/350ace7f937f19503fae07de8c1a061569f97ba5/pkg/sql/txn_restart_test.go#L950)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I'm not sure what an empty transaction is, but this seems empty to me... I don't think you want this comment at all, as empty or not shouldn't matter.
In fact I don't think you want this test here at all; the logic one seems like a better place to me.
</blockquote></details>

Mis-commented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14538#-:-Kgu-O1ZS8RLya06PcOo:bqtp7za)*

**Pull request merged**
