### PR TITLE
sql: add test for DrainingNames jobs status

### PR DESCRIPTION
**Pull request by vivekmenezes**
Release note: None

### CODE REVIEW

**Review by eriktrinh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30643)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/drop_test.go, line 978 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30643#-LNLidiyEgvuwf_6c0-J:-LNLidiyEgvuwf_6c0-K:bx64gd4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ff22cbb8d1d607ff306b1c1fab5960a7bc26d3c/pkg/sql/drop_test.go#L978)):*
> ```Go
> 	// Job still running, waiting for draining names.
> 	sqlRun := sqlutils.MakeSQLRunner(sqlDB)
> 	if err := jobutils.VerifyRunningSystemJob(
> ```

could this check be a little flakey? how do we know that the schema changer hasn't already completed the draining names stage?

**Review by vivekmenezes — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30643)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/drop_test.go, line 978 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30643#-LNLidiyEgvuwf_6c0-J:-LNLne4n6nuF1xp6cH8v:b-wihfpx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ff22cbb8d1d607ff306b1c1fab5960a7bc26d3c/pkg/sql/drop_test.go#L978)):*
<details><summary><i>Previously, eriktrinh (Erik Trinh) wrote…</i></summary><blockquote>

could this check be a little flakey? how do we know that the schema changer hasn't already completed the draining names stage?
</blockquote></details>

good questions. We've turned off schema change execution via the testing knobs above. Both the synchronous and asynchronous path have been disabled.

**Review by eriktrinh — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30643#-:-LNLy1T2EcliBeDvyFQa:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/drop_test.go, line 978 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/30643#-LNLidiyEgvuwf_6c0-J:-LNLy-Kx35YRWToa7pM9:b-q8ilnv) ([raw file](https://github.com/cockroachdb/cockroach/blob/6ff22cbb8d1d607ff306b1c1fab5960a7bc26d3c/pkg/sql/drop_test.go#L978)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

good questions. We've turned off schema change execution via the testing knobs above. Both the synchronous and asynchronous path have been disabled.
</blockquote></details>

gotcha

**Pull request merged**
