### PR TITLE
sqlsmith: refactor samplers to use a generic template

### PR DESCRIPTION
**Pull request by madelynnblue**
Use https://github.com/cheekybits/genny to templatize the sampler
code. This gives us some benefits:

- No more manual code duplication.
- We still get type safety.
- All sampling is identical. Previously there were special (statement and
table expr) and non special (everything else) samplers, and porting the
non-special ones was annoying and so not done.

This new way allows us to, using Options, very easily modify what kinds
of things we want in different parts of the system.

A makefile is included because we don't want to use a go:generate rule
that will run every time, since it requires genny to be installed. This
is similar to the hba ragel code where the author is responsible for
re-running the codegen if it changes, which is rare.

Release note: None

### CODE REVIEW

**Comment by mjibson** [comment]
All commits will be squashed before merge. Sending the PR like this for easier review.

**Review by yuzefovich — APPROVED** [review]
Hm, pretty cool! :lgtm:

> Reviewed 5 of 5 files at r1, 3 of 3 files at r2, 4 of 4 files at r3, 4 of 4 files at r4, 4 of 4 files at r5, 7 of 7 files at r6, 3 of 3 files at r7, 3 of 4 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43329#-:-LwUQI4-Dgp_5MmnyiU8:b-ujsgao)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/internal/sqlsmith/sqlsmith.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43329#-LwUMjVX7bzFxvkhl6vn:-LwUMjVX7bzFxvkhl6vo:bqr15zx) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf41ee6be6c4fa4d1dcd1178c8245d67010a3fb/pkg/internal/sqlsmith/sqlsmith.go#L206)):*
> ```Go
> // mutate any on-disk data.
> var DisableMutations = simpleOption("disable mutations", func(s *Smither) {
> 	s.stmtWeights = nonMutatingStatements
> ```

[nit]: assigning `Statements` to `stmtWeights` is slightly confusing. Maybe `s/nonMutatingStatements/nonMutatingStmtsWeights/g`? But that seems too long :/
___
*[pkg/internal/sqlsmith/sqlsmith_test.go, line 154 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/43329#-LwUQCpfEHHxHd07G1Xv:-LwUQCpfEHHxHd07G1Xw:b36zptq) ([raw file](https://github.com/cockroachdb/cockroach/blob/277e28b2ea78929563e85cb1c9efc573f37408a4/pkg/internal/sqlsmith/sqlsmith_test.go#L154)):*
> ```Go
> }
> 
> func TestWeightedSampler(t *testing.T) {
> ```

Is this test not useful anymore?
___
*[pkg/internal/sqlsmith/gen-sampler-gen.go, line 72 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43329#-LwUOX3L14kYaadL-kYw:-LwUOX3L14kYaadL-kYx:b-t1t356) ([raw file](https://github.com/cockroachdb/cockroach/blob/709ab942171492d7c99ec2f66cc762cd513eb432/pkg/internal/sqlsmith/gen-sampler-gen.go#L72)):*
> ```Go
> }
> 
> // Copyright 2019 The Cockroach Authors.
> ```

I'm slight confused by the repeated header - I'd expect it to not be regenerated and only structs/functions that have `Element` in it to be generated.

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43329)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/internal/sqlsmith/sqlsmith.go, line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43329#-LwUMjVX7bzFxvkhl6vn:-LwUQmtb17ETpYYdOOWh:b76ccr5) ([raw file](https://github.com/cockroachdb/cockroach/blob/6bf41ee6be6c4fa4d1dcd1178c8245d67010a3fb/pkg/internal/sqlsmith/sqlsmith.go#L206)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: assigning `Statements` to `stmtWeights` is slightly confusing. Maybe `s/nonMutatingStatements/nonMutatingStmtsWeights/g`? But that seems too long :/
</blockquote></details>

I think it's fine like it is.
___
*[pkg/internal/sqlsmith/sqlsmith_test.go, line 154 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/43329#-LwUQCpfEHHxHd07G1Xv:-LwUQs-K5EJFS6b2mLiU:btpxx5o) ([raw file](https://github.com/cockroachdb/cockroach/blob/277e28b2ea78929563e85cb1c9efc573f37408a4/pkg/internal/sqlsmith/sqlsmith_test.go#L154)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Is this test not useful anymore?
</blockquote></details>

Not really. It was more useful when I used a different sampling method.
___
*[pkg/internal/sqlsmith/gen-sampler-gen.go, line 72 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/43329#-LwUOX3L14kYaadL-kYw:-LwUQh8GEopvOWPTuCMk:b-xpksrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/709ab942171492d7c99ec2f66cc762cd513eb432/pkg/internal/sqlsmith/gen-sampler-gen.go#L72)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'm slight confused by the repeated header - I'd expect it to not be regenerated and only structs/functions that have `Element` in it to be generated.
</blockquote></details>

It's repeated because genny isn't super sophisticated. It's mostly text replacement.

**Pull request merged**
