### PR TITLE
server,kvserver,rac2: make ongoing WaitForEvals respond to settings c…

### PR DESCRIPTION
**Pull request by sumeerbhola**
…hange

The current config is encapsulated in WaitForEvalConfig, which is passed to rangeController. There are now two "refresh" channels in WaitForEval, (a) the existing one for replica changes, (b) the new one for when the config changes in a manner that narrows the set of work that needs to WaitForEval.

The existing code in processorImpl to look at cluster settings is removed. This means the fast path that returns when work does not need to WaitForEval is not as fast as before -- it needs to lookup the rangeController and the rangeController needs to call into WaitForEvalConfig, but it is better not to prematurely optimize by introducing duplicate code.

Some additional tracing is added in rangeController.WaitForEval.

Epic: CRDB-37515

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
The existing tests won't build and I haven't added tests for the new functionality. I'd like a quick opinion on this change before doing those.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-:-O9I1WvV-NUuIodvpSLu:bnvnirj)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

**Review by kvoli — COMMENTED** [review]
Approach :lgtm: -- I'll re-review asap once the tests are in.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-:-O9Ko6p19f-BySIRQOU0:bq7tif2)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Kl7Ib2WvfUma5nA7X:-O9Kl7Ib2WvfUma5nA7Y:b1oqmd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L646)):*
> ```Go
> 	if bypass {
> 		if expensiveLoggingEnabled {
> 			log.VEventf(ctx, 2, "r%v/%v bypassed request (pri=%v)",
> ```

nit: below the log message is "request bypassed" and here it is "bypassed request", consider adopting the same phrasing for both.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 649 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9KlbBr4lSF1HPoGfJl:-O9KlbBr4lSF1HPoGfJm:b-o79b38) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L649)):*
> ```Go
> 				rc.opts.RangeID, rc.opts.LocalReplicaID, pri)
> 		}
> 		rc.opts.EvalWaitMetrics.OnWaiting(wc)
> ```

nit: consider moving this out of the conditional and removing the other (general case) `OnWaiting` call below.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 757 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Klub71n18hInBInRh:-O9Klub71n18hInBInRi:bfxpq4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L757)):*
> ```Go
> 				continue
> 			case ContextCanceled:
> 				waitDuration := rc.opts.Clock.PhysicalTime().Sub(start)
> ```

nit: consider declaring now just above the switch statement or just calculating the wait duration there (although not applicable to the retry case).
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 759 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Km7Au8bGzRiX7mcab:-O9Km7Au8bGzRiX7mcac:b-lwljdt) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L759)):*
> ```Go
> 				waitDuration := rc.opts.Clock.PhysicalTime().Sub(start)
> 				if expensiveLoggingEnabled {
> 					log.VEventf(ctx, 2, "r%v/%v cancelled (pri=%v wait-duration=%s)",
> ```

:england:  --  not important or relevant, but we probably haven't been consistent with English/American spelling, just came to mind seeing this. 
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 771 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Kmenz2DTVRFzW48gw:-O9Kmenz2DTVRFzW48gx:b-r54by) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L771)):*
> ```Go
> 					if expensiveLoggingEnabled {
> 						log.VEventf(ctx, 2,
> 							"r%v/%v request bypassed as settings changed (pri=%v wait-duration=%s)",
> ```

nit: use %v instead of %s unless the value is a string constant -- this makes no difference afaik, just consistency.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Kn7hd4aDWAZiwmQQY:-O9Kn7he32O74oGbPa5I:b-nk34rk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L451)):*
> ```Go
> 	case RefreshWait1Signaled:
> 		w.Print("refresh_wait1_signaled")
> 	case RefreshWait2Signaled:
> ```

Any reason not to name these channel wait end states specifically e.g., something like `RefreshWaitReplicaSignaled` and `RefreshWaitConfigSignaled`
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/wait_for_eval_config.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9KnUxw6efMaOpqwx_g:-O9KnUxw6efMaOpqwx_h:bu8q4v5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/wait_for_eval_config.go#L28)):*
> ```Go
> // Bypass returns true iff the given WorkClass does not need to wait for
> // tokens in WaitForEval.
> func (waitCat WaitForEvalCategory) Bypass(wc admissionpb.WorkClass) bool {
> ```

nit: why the longer name instead of `wec` or some abbreviation?
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/wait_for_eval_config.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9KnnAP4gL2QkMq-48C:-O9KnnAP4gL2QkMq-48D:b-bdapqq) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/wait_for_eval_config.go#L57)):*
> ```Go
> 	w.mu.Lock()
> 	defer w.mu.Unlock()
> 	if w.mu.waitCategory > waitCategory {
> ```

nit: consider adding a comment about why we only need to check the increase case, something about any request that would have been affected by the change would have already bypassed wait for eval (if that is correct).

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

I'll ping when the tests are ready.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-:-O9LXZRq336AS3GXlvWj:bli4jvg)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 646 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Kl7Ib2WvfUma5nA7X:-O9LO3k44z882-jK6fxp:b-kpoqjb) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L646)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: below the log message is "request bypassed" and here it is "bypassed request", consider adopting the same phrasing for both.
</blockquote></details>

Done. The original trace statement in this method said "admitted request", so everything is now standardized to "<something> request".
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 649 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9KlbBr4lSF1HPoGfJl:-O9LQ5l25fzdMDxAmAQv:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L649)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider moving this out of the conditional and removing the other (general case) `OnWaiting` call below.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 757 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Klub71n18hInBInRh:-O9LQOJaDeXQxFXZ2lXl:bs1kkuh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L757)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider declaring now just above the switch statement or just calculating the wait duration there (although not applicable to the retry case).
</blockquote></details>

I've left it as-is for readability, since we don't use now in multiple of these cases.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 759 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Km7Au8bGzRiX7mcab:-O9LQY0s6nXkKNeviGpf:b-ohjb7t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L759)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

:england:  --  not important or relevant, but we probably haven't been consistent with English/American spelling, just came to mind seeing this.
</blockquote></details>

Everyone knows it is cancelled :)

Changed to conform to the American Way.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 771 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Kmenz2DTVRFzW48gw:-O9LRDte-9yDbRmLnFam:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L771)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: use %v instead of %s unless the value is a string constant -- this makes no difference afaik, just consistency.
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Kn7hd4aDWAZiwmQQY:-O9LRMSV9XrYti8ZerET:b-6kewv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L451)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Any reason not to name these channel wait end states specifically e.g., something like `RefreshWaitReplicaSignaled` and `RefreshWaitConfigSignaled`
</blockquote></details>

The callee did not care about the semantics. But that's not a good reason, so I've made these meaningful.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/wait_for_eval_config.go` line 28 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9KnUxw6efMaOpqwx_g:-O9LRZWx6OTl-ysDfGh0:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/wait_for_eval_config.go#L28)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: why the longer name instead of `wec` or some abbreviation?
</blockquote></details>

Done
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/wait_for_eval_config.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9KnnAP4gL2QkMq-48C:-O9LSQXdDcY8v0TI0oh3:b-l4396t) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/wait_for_eval_config.go#L57)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

nit: consider adding a comment about why we only need to check the increase case, something about any request that would have been affected by the change would have already bypassed wait for eval (if that is correct).
</blockquote></details>

Added a comment

**Review by sumeerbhola — COMMENTED** [review]
Tests are ready. PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-:-O9LrWQ75NEeootlVLaq:bwffwj8)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @pav-kv)

**Review by kvoli — APPROVED** [review]
:lgtm: Feel free to defer adopting any nit comments to a later PR, to unblock merging.

> Reviewed 3 of 5 files at r2, 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-:-O9MUUsY5eKEVB7e-Q9P:bvtell5)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @pav-kv and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 757 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Klub71n18hInBInRh:-O9MSY2M7FCgxISvaIVF:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L757)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I've left it as-is for readability, since we don't use now in multiple of these cases.
</blockquote></details>

sgtm
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go` line 759 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Km7Au8bGzRiX7mcab:-O9MSYvKADxfM90k8e1u:b32vhw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller.go#L759)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

Everyone knows it is cancelled :)

Changed to conform to the American Way.
</blockquote></details>

:)
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 451 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9Kn7hd4aDWAZiwmQQY:-O9MSsHK0yhzG2hCaQNC:b-wmnbb1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7615daa8f7bb63afb56002b340356e19943e56f3/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L451)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

The callee did not care about the semantics. But that's not a good reason, so I've made these meaningful.
</blockquote></details>

Nice -- looks good.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go` line 463 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9MSxRi-5eFNnd3bJZT:-O9MSxRj2voawzWHB2w0:b-uj5d2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d19bfdd5a09c816d5c36186748bbd33e26b12e4/pkg/kv/kvserver/kvflowcontrol/rac2/token_counter.go#L463)):*
> ```Go
> // available, including all the required wait handles. The caller provides two
> // refresh channels, which when signaled will cause the function to return
> // RefreshWait{1,2}Signaled, allowing the caller to retry waiting with updated
> ```

This comment is stale now that these are named -- feel free to merge and fix in a follow up given CI is green.
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_config_change` line 117 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9MUKqC4pInj0A0Ka91:-O9MUKqC4pInj0A0Ka92:buk2djn) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d19bfdd5a09c816d5c36186748bbd33e26b12e4/pkg/kv/kvserver/kvflowcontrol/rac2/testdata/range_controller/wait_for_eval_config_change#L117)):*
> ```
> set-flow-control-config enabled=true
> ----
> enabled: true mode: apply_to_all
> ```

Nice test, rather concise!
___
*[`pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go` line 1405 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132724#-O9MTcP25xwXhB_pZ4sF:-O9MTcP25xwXhB_pZ4sG:b-5oqtfa) ([raw file](https://github.com/cockroachdb/cockroach/blob/9d19bfdd5a09c816d5c36186748bbd33e26b12e4/pkg/kv/kvserver/kvflowcontrol/rac2/range_controller_test.go#L1405)):*
> ```Go
> 				return buf.String()
> 
> 			case "set-flow-control-config":
> ```

nit: also no need to make the change now, the other `TestRangeController` datadriven commands use `_` rather than `-` for concatenating words.

**Comment by sumeerbhola** [comment]
bors r=kvoli

**Pull request merged**
