### PR TITLE
server: remove the setting `server.remote_debugging.mode`

### LINKED ISSUE #24992: ui: gracefully handle remote_debugging setting
In #24071, which was made as part of the emergency changes to fix #23555, I added a band-aid fix to the Node Logs page and the Range Simulated Allocator component.  The fix has this TODO above:

> TODO(couchand): This is a really myopic way to check for this particular
> case, but making major changes to the CachedDataReducer or util.api seems
> fraught at this point.  We should revisit this soon.

Let's get rid of that TODO.  Broadly, I can see two potential strategies:

1.  Explicitly check for the setting and don't bother making a request to an endpoint that will fail.
2.  Implement #6307 and consider that to be sufficient protection, so just remove the changes made to address #23555.

### LINKED ISSUE #26283: ui: debug pages <-> login interaction
Original post below. As @a-robinson pointed out, it doesn't seem that we currently expose sensitive data to users unless `remote_debugging` is set appropriately.

This issue serves to clarify what we can expose once a user is logged in.

----

The `#/debug` page can be used to show the cluster settings. I *think* it shows all of them which seems dangerous.

We could block it, but I'd prefer if we sanitized it. That could take the form of marking the setting as private at creation time. For private settings, we show the string <redacted> unless the setting is at default value. 

@couchand for triage -- apologies if this isn't the right team.

### LINKED ISSUE #57072: server: Remove remote_debugging setting
Following analysis in https://github.com/cockroachdb/cockroach/issues/50472#issuecomment-721907671, the `server.remote_debugging.mode` is a relic of the time before we had proper authentication. Now that everything affected by this setting has real authentication, this setting is just an unnecessary restriction and should be removed.

### PR DESCRIPTION
**Pull request by knz**
Fixes  #57072.
Fixes #26283
Fixes #24992

As suggested/requested by @bdarnell.

Release note (security update): Certain HTTP debug endpoints reserved
to `admin` users now return more details about range start/end keys,
such as the "hot ranges" report.

Release note (security update): The cluster setting
`server.remote_debugging.mode` has been removed. The debug endpoints
are now available to every client with access to the HTTP port.
All the HTTP URLs previously affected by this setting already have
user authentication and require a user to be logged in that's member
of the `admin` group, so there was no need for an additional layer of
security.

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63748)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz)

___
*[pkg/cmd/roachprod/install/cockroach.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63748#-MYeanswAWfV-qE0fcqB:-MYeanswAWfV-qE0fcqC:b-4jc1it) ([raw file](https://github.com/cockroachdb/cockroach/blob/5794a976be83ae75fd1e925169e506ff550732d9/pkg/cmd/roachprod/install/cockroach.go#L585)):*
> ```Go
> 	url := h.r.NodeURL(h.c, "localhost", h.r.NodePort(h.c, 1))
> 
> 	// We ignore failures to set remote_debugging.mode, which was
> ```

Users may also have scripts that do this. In order to minimize disruption, it may be better to leave the setting in place but make it an error to set it to anything but "any".

**Comment by knz** [comment]
> In order to minimize disruption, it may be better to leave the setting in place but make it an error to set it to anything but "any".

I simply marked the setting as retired - we have logic to do this already. Setting it becomes a no-op, and SHOW CLUSTER SETTINGS hides it.

**Review by bdarnell — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/63748)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell and @knz)

___
*[pkg/cmd/roachprod/install/cockroach.go, line 585 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/63748#-MYeanswAWfV-qE0fcqB:-MYjkMcC-V8trdVkqV3_:bbwh166) ([raw file](https://github.com/cockroachdb/cockroach/blob/5794a976be83ae75fd1e925169e506ff550732d9/pkg/cmd/roachprod/install/cockroach.go#L585)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Users may also have scripts that do this. In order to minimize disruption, it may be better to leave the setting in place but make it an error to set it to anything but "any". 
</blockquote></details>

I'd undo this change now that the setting is marked as retired. 
___
*[pkg/server/debug/server.go, line 55 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/63748#-MYjkTpe1oIT4KXL9l62:-MYjkTpe1oIT4KXL9l63:b-6z8xx7) ([raw file](https://github.com/cockroachdb/cockroach/blob/5896578e83027560436af4cf3e3ac789b3a76108/pkg/server/debug/server.go#L55)):*
> ```Go
> 	// This setting definition still exists so as to not break
> 	// deployment scripts that set it unconditionally.
> 	v := settings.RegisterStringSetting("server.remote_debugging.mode", "unused", "local")
> ```

The default should now say "any" instead of "local" (or maybe just an empty string if the default of a retired setting is never visible anywhere).

**Comment by knz** [comment]
TFYR!

bors r=bdarnell

**Comment by RaduBerinde** [comment]
@knz what do you think about backporting this change to 21.1? I'm asking because I'm trying to make roachprod as close as possible between 21.1 and 21.2.

**Comment by knz** [comment]
it's not too hard to backport, but @bdarnell's opinion is that we shouldn't pull functionality from under the feet of users in patch releases, so I don't know?

Probably with sufficient PM approval and @bdarnell 's we could make it happen.

**Comment by RaduBerinde** [comment]
Thanks - I don't think it's worth the work if there are no other good reasons. I think I can backport just the roachprod change and things would still work.

**Comment by bdarnell** [comment]
I don't think this is appropriate for a backport - removing this control was safe because of other work we did to improve access control. Backporting it runs the risk of a security regression if we failed to backport any of those other improvements. (and whether there's an actual security regression, it would look like one to anyone watching closely, which would raise eyebrows about the safety of our patches)

**Pull request merged**
