### PR TITLE
backupccl: add multi-region test to TestRestoreOldVersions

### LINKED ISSUE #67650: backupccl: add multi-region tests to RestoreAllVersions
[quote @ajwerner](https://github.com/cockroachdb/cockroach/pull/67581#pullrequestreview-706484620)

> How do you feel about adding some tests to RestoreOldVersions tests which include backups from the current branch as well as the previous branch with multiregion databases? Perhaps including backups and restores of individual tables, databases, and whole clusters? I think those tests are invaluable to make sure we don't break support for restoring old backups.

Seems like a good idea.

### PR DESCRIPTION
**Pull request by otan**
Release justification: test-only change

Release note: None

Resolves #67650

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> Reviewed 1 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69725)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @shermanCRL)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-MiabCNW2t6mkUQbJzHn:-MiabCNW2t6mkUQbJzHo:bx86xgf) ([raw file](https://github.com/cockroachdb/cockroach/blob/49fdbb60a33e45eaf481bfc2ff282de407021e97/pkg/ccl/backupccl/restore_old_versions_test.go#L294)):*
> ```Go
> }
> 
> func runOldVersionMultiRegionTest(exportDir string) func(t *testing.T) {
> ```

This LGTM, but I'm wondering if we need to test a few more permutations.  For example, what about table level restore?  We currently don't support it for MR tables into MR databases (which we should validate), but we do support non-MR tables into MR databases. 
___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-MiacL8C01d_UqpXm_TL:-MiacL8C01d_UqpXm_TM:b-ywnph7) ([raw file](https://github.com/cockroachdb/cockroach/blob/49fdbb60a33e45eaf481bfc2ff282de407021e97/pkg/ccl/backupccl/restore_old_versions_test.go#L326)):*
> ```Go
> 		})
> 		defer tc.Stopper().Stop(ctx)
> 		require.NoError(t, os.Symlink(exportDir, filepath.Join(dir, "foo")))
> ```

Nit: why "foo"?  Does it make sense to give this a more descriptive name?  Something like "localBackupDir"?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69725)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @shermanCRL)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-MiabCNW2t6mkUQbJzHn:-MiadTyu2WSpGEteu0j2:b-oce2tj) ([raw file](https://github.com/cockroachdb/cockroach/blob/49fdbb60a33e45eaf481bfc2ff282de407021e97/pkg/ccl/backupccl/restore_old_versions_test.go#L294)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

This LGTM, but I'm wondering if we need to test a few more permutations.  For example, what about table level restore?  We currently don't support it for MR tables into MR databases (which we should validate), but we do support non-MR tables into MR databases. 
</blockquote></details>

eh there's other tests that already do this no? 
___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-MiacL8C01d_UqpXm_TL:-MiadPqE-M9gA5g-Qu_6:b3crc5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/49fdbb60a33e45eaf481bfc2ff282de407021e97/pkg/ccl/backupccl/restore_old_versions_test.go#L326)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Nit: why "foo"?  Does it make sense to give this a more descriptive name?  Something like "localBackupDir"?
</blockquote></details>

Copy paste. All the other tests do this.

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69725)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @shermanCRL)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-MiabCNW2t6mkUQbJzHn:-Mib-nQPDO6T7VN2Opl0:b-526o53) ([raw file](https://github.com/cockroachdb/cockroach/blob/49fdbb60a33e45eaf481bfc2ff282de407021e97/pkg/ccl/backupccl/restore_old_versions_test.go#L294)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

eh there's other tests that already do this no? 
</blockquote></details>

Yes, but not for older versions.  When we relax the restrictions, I'd think we'd want to ensure that they work on older versions.  Not suggesting we do it here (although maybe we should), but another issue/PR could be warranted. 
___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-MiacL8C01d_UqpXm_TL:-Mib04ry3nqZQ3pLJ2cc:b8llupm) ([raw file](https://github.com/cockroachdb/cockroach/blob/49fdbb60a33e45eaf481bfc2ff282de407021e97/pkg/ccl/backupccl/restore_old_versions_test.go#L326)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Copy paste. All the other tests do this. 
</blockquote></details>

Why be like everyone else?

**Comment by otan** [comment]
___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-MiabCNW2t6mkUQbJzHn:-Mic53CE2OYLEvviKl6s:b-ijjefh) ([raw file](https://github.com/cockroachdb/cockroach/blob/49fdbb60a33e45eaf481bfc2ff282de407021e97/pkg/ccl/backupccl/restore_old_versions_test.go#L294)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Yes, but not for older versions.  When we relax the restrictions, I'd think we'd want to ensure that they work on older versions.  Not suggesting we do it here (although maybe we should), but another issue/PR could be warranted. 
</blockquote></details>

Yeah I'd think there's a million cases to test in theory, I don't buy its too much more exciting. In general I'd rather a randomised backup restore test.

**Comment by otan** [comment]
___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 326 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-MiacL8C01d_UqpXm_TL:-Mic5HFv2Mck76ZT26kX:b-15fxl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/49fdbb60a33e45eaf481bfc2ff282de407021e97/pkg/ccl/backupccl/restore_old_versions_test.go#L326)):*
<details><summary><i>Previously, ajstorm (Adam Storm) wrote…</i></summary><blockquote>

Why be like everyone else?
</blockquote></details>

Just want to fit in

**Review by ajstorm — COMMENTED** [review]
:lgtm: We can debate the value of the table-level test offline.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-:-MicZ_LuA_mL1aSKdGg4:bj3jp6o)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @shermanCRL)

___
*[pkg/ccl/backupccl/restore_old_versions_test.go, line 294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-MiabCNW2t6mkUQbJzHn:-MicZ2XKEgqQ-EQFIIlb:b-iyjl97) ([raw file](https://github.com/cockroachdb/cockroach/blob/49fdbb60a33e45eaf481bfc2ff282de407021e97/pkg/ccl/backupccl/restore_old_versions_test.go#L294)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Yeah I'd think there's a million cases to test in theory, I don't buy its too much more exciting. In general I'd rather a randomised backup restore test. 
</blockquote></details>

The fact that the enum isn't coming along for the ride makes things more interesting IMO.  Doesn't have to be this PR, but I do think that we should open an issue.

**Review by ajstorm — APPROVED** [review]
:lgtm: with feeling this time.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69725#-:-MicZgmJ7qFTWLG2I0I7:b-fhf0k2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm and @shermanCRL)

**Comment by otan** [comment]
bors r=ajstorm

**Pull request merged**
