### PR TITLE
sql: implement pg_has_role

### PR DESCRIPTION
**Pull request by nvb**
Needed for #69010.
Related to #22734.

This commit implements the `pg_has_role` builtin function. `pg_has_role`
returns whether the user has privileges for a specified role or not.
Allowable privilege types are MEMBER and USAGE. MEMBER denotes direct or
indirect membership in the role (that is, the right to do SET ROLE),
while USAGE denotes whether the privileges of the role are immediately
available without doing SET ROLE.

`pg_has_role` was the last remaining unimplemented "access privilege
inquiry functions", and was omitted from 94c25be because our role-based
access control system was not mature enough to support it at the time.

The commit also makes a small modification to `pg_catalog.pg_roles` and
`pg_catalog.pg_authid` to reflect that fact that all users and roles
inherit the privileges of roles they are members of.

Release note (sql change): The pg_has_role builtin function is now
supported, which returns whether a given user has privileges for a
specified role or not.

Release justification: None, waiting for v22.1.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
I've added one more commit here resolving an incompatibility in CockroachDB's handling of the privilege string accepted by each of these Access Privilege Inquiry Functions. The intention was for the functions to return whether _any_ of the comma-separated privileges were held. However, since their introduction, they were returning whether _all_ of the privileges were held.

The intended behavior is mentioned in https://www.postgresql.org/docs/current/functions-info.html.

> Also, multiple privilege types can be listed separated by commas, in which case the result will be true if any of the listed privileges is held.

I'm also happy to pull this into a follow-on PR if that's easier for reviewers.

**Review by rafiss — CHANGES_REQUESTED** [review]
thanks for these improvements!

could you also add the null-handling change in the first commit to a release note

overall this looks good, but i think this would benefit from @richardjcai reviewing the last 2 or 3 commits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-:-MjV6ccmD5BDe6UpNN_O:b-t4n9xd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @nvanbenschoten, and @RichardJCai)

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1812 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-MjV5dG55vgOFepGTrfo:-MjV5dG7AaDRVDtclcN2:b-a1k3ow) ([raw file](https://github.com/cockroachdb/cockroach/blob/e13f038787432ca0c18cd865666ee693841b46fb/pkg/sql/sem/builtins/pg_builtins.go#L1812)):*
> ```Go
> 						"role %s does not exist", roleArg)
> 				case *tree.DOid:
> 					// Postgres returns NULL if no matching tablespace is found when given
> ```

nit: should be "no matching role"
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2199 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-MjV5zls2yQqDOI28ofV:-MjV5zls2yQqDOI28ofW:boruac0) ([raw file](https://github.com/cockroachdb/cockroach/blob/e13f038787432ca0c18cd865666ee693841b46fb/pkg/sql/sem/builtins/pg_builtins.go#L2199)):*
> ```Go
> 
> // isSuperuser returns whether the specified user has superuser privileges.
> // This is defined to match the pg_roles.rolsuper field.
> ```

heads up: we are fixing the rolsuper field so that it determines superuser status based on admin membership:  https://github.com/cockroachdb/cockroach/issues/69943
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 503 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-MjV72RG8bScw78_q4Uc:-MjV72RG8bScw78_q4Ud:bvu5eqy) ([raw file](https://github.com/cockroachdb/cockroach/blob/d419c8a3bef5c7434ffeea8085771537208f272d/pkg/sql/sem/builtins/pg_builtins.go#L503)):*
> ```Go
> // on an object to others if it is the owner of the object or if it itself
> // holds both (1) that privilege on the object and (2) the GRANT privilege
> // on the object.
> ```

nit: might want to link the tracking issue https://github.com/cockroachdb/cockroach/issues/67410

**Review by RichardJCai — CHANGES_REQUESTED** [review]
Mostly looks good to me as well modulo the part on with grant opt.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-:-MjWXhBbAXw5R5eHHIHL:bl9fk4f)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @nvanbenschoten)

___
*[pkg/sql/resolver.go, line 327 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-MjWXLHg9KHSRonz30aO:-MjWXLHg9KHSRonz30aP:bh77a7k) ([raw file](https://github.com/cockroachdb/cockroach/blob/478a4d8ca49b194fbe72334fbf41f134810dfe3e/pkg/sql/resolver.go#L327)):*
> ```Go
> 		return true, nil
> 	}
> 	// For WITH GRANT OPTION, check the roles also has the GRANT privilege.
> ```

I'm not sure if we should remove this or not. On one hand we technically don't support with grant opt, but having GRANT privilege is needed to actually grant a privilege. For correctness it actually does make sense to check GRANT privilege to substitute for WITH GRANT OPTION right now.

**Review by nvb — COMMENTED** [review]
> could you also add the null-handling change in the first commit to a release note

Done.

TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-:-Mjbe18S4_AiyTXus59G:bp4qmo5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @rafiss, and @RichardJCai)

___
*[pkg/sql/resolver.go, line 327 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-MjWXLHg9KHSRonz30aO:-Mjbhha01YNMG7TaPWqJ:b3e3kvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/478a4d8ca49b194fbe72334fbf41f134810dfe3e/pkg/sql/resolver.go#L327)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I'm not sure if we should remove this or not. On one hand we technically don't support with grant opt, but having GRANT privilege is needed to actually grant a privilege. For correctness it actually does make sense to check GRANT privilege to substitute for WITH GRANT OPTION right now.
</blockquote></details>

This isn't quite being removed. Rather, the change is removing the `withGrantOption` from this interface and calling `HasPrivilege` twice, one as before and once with `privilege.GRANT` when `WITH GRANT OPTION` is provided. An analogous change was made to `evalPrivilegeCheck`. This is explained in some new commentary in `pg_builtin.go`.

I thought this was a nice simplification to these interfaces at first because it allowed us to consolidate the WITH GRANT OPTION handling to a single place (`runSinglePrivilegeCheck`). But with the addition of the last commit here, I'm less sure now. I think it depends on how we intend to address https://github.com/cockroachdb/cockroach/issues/67410 and how we intend to represent a "privilege with grant option" in the code.

What do you think?
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1812 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-MjV5dG55vgOFepGTrfo:-MjbbszS-x7ZWHvJ4gpc:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e13f038787432ca0c18cd865666ee693841b46fb/pkg/sql/sem/builtins/pg_builtins.go#L1812)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: should be "no matching role"
</blockquote></details>

Done.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2199 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-MjV5zls2yQqDOI28ofV:-MjbhWl-0kH95FAXmVAn:bm3ui2h) ([raw file](https://github.com/cockroachdb/cockroach/blob/e13f038787432ca0c18cd865666ee693841b46fb/pkg/sql/sem/builtins/pg_builtins.go#L2199)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

heads up: we are fixing the rolsuper field so that it determines superuser status based on admin membership:  https://github.com/cockroachdb/cockroach/issues/69943
</blockquote></details>

Thanks for the heads up! Fixed.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 503 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-MjV72RG8bScw78_q4Uc:-MjbeShq8m0Ava6JDjY5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d419c8a3bef5c7434ffeea8085771537208f272d/pkg/sql/sem/builtins/pg_builtins.go#L503)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: might want to link the tracking issue https://github.com/cockroachdb/cockroach/issues/67410
</blockquote></details>

Done.

**Review by RichardJCai — APPROVED** [review]
LGTM modulo nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-:-Mje7ypu3fpHK6rAKA-N:b-zi7er)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @nvanbenschoten, and @rafiss)

___
*[pkg/sql/resolver.go, line 327 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-MjWXLHg9KHSRonz30aO:-Mje2xLo0HfXJh1VICM0:b-n0j70b) ([raw file](https://github.com/cockroachdb/cockroach/blob/478a4d8ca49b194fbe72334fbf41f134810dfe3e/pkg/sql/resolver.go#L327)):*
Ah oops, I missed it. 
>how we intend to represent a "privilege with grant option" in the code.
Fair, I don't think we have a concrete idea of how this will look right now.

This sounds good to me.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1962 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-Mje7OGjEyc1YoJ3r4gA:-Mje7OGjEyc1YoJ3r4gB:b-sblnsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/e579c5eaaa9629e8f814c282dc142c49ac627aed/pkg/sql/sem/builtins/pg_builtins.go#L1962)):*
> ```Go
> 				return tree.DNull, nil
> 			}
> 			// All users have USAGE privileges to all types.
> ```

I think we can remove this hardcoded case and rely on the privilege check (the Public role is explicitly granted USAGE on new types).
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2462 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-Mje50U33OWIpRzH9fud:-Mje50U33OWIpRzH9fue:bkuc6g7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e579c5eaaa9629e8f814c282dc142c49ac627aed/pkg/sql/sem/builtins/pg_builtins.go#L2462)):*
> ```Go
> 	}
> 
> 	// Superusers have every privilege, so are part of every role.
> ```

nit: `so are part of every role`

I think this shit be and are part of every role.

**Review by nvb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69939)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru, @rafiss, and @RichardJCai)

___
*[pkg/sql/sem/builtins/pg_builtins.go, line 1962 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-Mje7OGjEyc1YoJ3r4gA:-Mjevcwj4PMer0NHpHqu:b-tkkdhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/e579c5eaaa9629e8f814c282dc142c49ac627aed/pkg/sql/sem/builtins/pg_builtins.go#L1962)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

I think we can remove this hardcoded case and rely on the privilege check (the Public role is explicitly granted USAGE on new types).
</blockquote></details>

Good point. I'll do this in a separate PR.
___
*[pkg/sql/sem/builtins/pg_builtins.go, line 2462 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/69939#-Mje50U33OWIpRzH9fud:-Mjevc0-3uoR8CWBIg2x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e579c5eaaa9629e8f814c282dc142c49ac627aed/pkg/sql/sem/builtins/pg_builtins.go#L2462)):*
<details><summary><i>Previously, RichardJCai (Richard Cai) wrote…</i></summary><blockquote>

nit: `so are part of every role`

I think this shit be and are part of every role.
</blockquote></details>

Done.

**Pull request merged**
