### PR TITLE
backupccl: immediately process resume spans during backup

### PR DESCRIPTION
**Pull request by stevendanna**
Previously, we put resume spans returned from an export request back
on the queue for processing. In a large cluster with a lot of work to
do, this might result in the resume span being processed much later.
This isn't great because (1) it means we don't get to take advantage
of disk and block caching and (2) it means that the resume span has a
smaller chance of ending up in the same SST as the original span.

Release justification: Low risk performance improvement.

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
This is really just a few line change.  If you look at the whitespace-ignored diff it is clearer.

**Review by dt — APPROVED** [review]

**Comment by stevendanna** [comment]
bors r=dt

**Comment by stevendanna** [comment]
bors r=dt

**Comment by shermanCRL** [comment]
Backportable?

**Comment by shermanCRL** [comment]
(Ping on whether we think this is a good backport candidate for v22.1. OK if not or if we already talked about it.)

**Pull request merged**
