### PR TITLE
cli: don't interleave warnings with statement timings

### LINKED ISSUE #61516: cli: unexpected interaction between PG notices and result rows
**Context** 
We want to send a pg notice from the coordinator node running a RESTORE statement if it is unable to find the table stats file in the backup location since this could impact query performance after RESTORE until the stats are recomputed.

**Approach**
We use the `BufferClientNotice` helper on the planner to buffer this notice as other statements like `CREATE INDEX CONCURRENTLY` appear to do.

**Issue**
The notice is getting flushed at a point that causes it to appear interleaved with the statement execution times.
Screen Shot 2021-03-04 at 9 31 34 AM

**Potential Root Cause**
RESTORE sends back a row with a summary of stats about the restore job. During the planning phase it also buffers a notice using the `BufferClientNotice` helper. Some debugging has led me to believe that the row with the completed jobs statistics is processed first, which we print as an asciiTable and set `delayNotices` to true - https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/sql_util.go#L629

The next row we process results in `handleNotice` being invoked, but since `delayNotices` is true, we don't flush it - https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/sql_util.go#L130

Once we have processed the rows, we invoke `maybeShowTimes` https://github.com/cockroachdb/cockroach/blob/master/pkg/cli/sql_util.go#L940 that leads us to `getLastQueryStatistics`. This method notably calls `rows.Close()` on the internal query it issues - https://github.com/cockroachdb/cockroach/blob/a5a59be87d690ea28394a7213c20190d9c6616a0/pkg/cli/sql_util.go#L389 which triggers a flush of the notice we have buffered. I _think_ this explains the interleaved nature of the notice in the screenshot above,  when coming from restore.

### PR DESCRIPTION
**Pull request by knz**
Fixes #61516 

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
(this PR intentionally does not contain unit tests as this will be refactored in #67229)

**Review by arulajmani — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/67265#-:-MdwEoRo3he03Zlq-d6y:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

**Comment by knz** [comment]
thank you! 

bors r=arulajmani

**Comment by adityamaru** [comment]
Thank you for picking this up @knz!!

**Pull request merged**
