### PR TITLE
 WIP: sql: use node liveness epochs for table leases

### PR DESCRIPTION
**Pull request by vivekmenezes**
ignore the first two commits

This is only a prototype to prompt discussion and feedback

The basic idea is:
1. Start creating leases with the liveness epoch of the node.
2. Set the expiration time of such leases to infinity for backwards
compatibility reasons. Older nodes can see the infinite expiration
time and will assume the lease is legit.
3. whenever the epoch changes, refresh all the leases, and purge
old leases.
4. Keep track of liveness epoches of all other nodes in the cluster
and purge infinite time leases at older epoches after a set timeout.

The only remaining part here is to to create a reliabe way to be notified
of changes to system config (this uses gossip) to be reliably notified
of changes in table versios so that leases can be renewed.

My plan is to split this into a few PR:
1. Introduce node liveness epoch into the lease table and add a migration
to ALTER TABLE ADD COLUMN epoch. Start writing leases with epoch but retain
the expiration time.
2. When the epoch changes or table versions change refresh all leases.
3. Set the expiration time to infinity only after the cluster upgrade has
been accepted by the user, start following node liveness and delete old
leases from other nodes.

### CODE REVIEW

**Review by andreimatei — CHANGES_REQUESTED** [review]
> 2. Set the expiration time of such leases to infinity for backwards
> compatibility reasons. Older nodes can see the infinite expiration
> time and will assume the lease is legit.
> ...
> 3. Set the expiration time to infinity only after the cluster upgrade has
> been accepted by the user, start following node liveness and delete old
> leases from other nodes.

These two items seem to contradict each other?
If I read 2 alone, I'm not sure I understand. Say you have a new node create one of these "infinite" leases and then the node goes away and there's no other new nodes. Won't that lease leave forever and block schema changes?
As the other bullet is suggesting, I think it'd be cleaner if we started used epoch leases only after a cluster version change.

Another thing that seems sketchy is how leases for old epochs are cleaned up. Rather than having all nodes race to do it, can't this process be centralized? Like, for example, can't the owner of a schema change lease do it for that respective table?

And then a big thing that I don't see in the PR is how does a gateway assert that it's epoch is still the one for which it has leases before doing KV ops (in particular, before committing a txn)? Similarly, I don't quite follow how the txn deadline now works - don't we need to set the deadline only when we're about to commit, not when we acquire a lease?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-:-LJZzaTy8FO6kgqfeCyM:bojwqgz)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 153 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZy0QqDwJbAFJs_COA:-LJZy0QqDwJbAFJs_COB:b7a2ppm) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L153)):*
> ```Go
> 
> // The deadline a txn using this table version should use.
> func (s LeaseStore) txnDeadline(tvs *tableVersionState, timestamp hlc.Timestamp) hlc.Timestamp {
> ```

what is the timestamp argument?
___
*[pkg/sql/lease.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZy3eR9rwesR6ISc4Z:-LJZy3eR9rwesR6ISc4_:bbqg23f) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L155)):*
> ```Go
> func (s LeaseStore) txnDeadline(tvs *tableVersionState, timestamp hlc.Timestamp) hlc.Timestamp {
> 	if tvs.expiration == hlc.MaxTimestamp {
> 		timestamp.Add(int64(s.leaseDuration), 0)
> ```

I don't understand what's going on here... We modify a local variable but then not use it again? Are we returning the right thing?
___
*[pkg/sql/lease.go, line 170 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZyIn8AxEarVKJmafa:-LJZyIn8AxEarVKJmafb:b-h8dmwv) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L170)):*
> ```Go
> // If the lease cannot be obtained because the descriptor is in the process of
> // being dropped, the error will be errTableDropped.
> func (s LeaseStore) acquire(ctx context.Context, epoch int64, tableID sqlbase.ID) (*tableVersionState, error) {
> ```

wouldn't it make more sense for the `LeaseStore` to figure out the node's epoch itself instead of taking one in?
___
*[pkg/sql/lease.go, line 244 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZyhXV-f73o_2bobW0:-LJZyhXV-f73o_2bobW1:b-xnlbk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L244)):*
> ```Go
> 		}
> 		const deleteLease = `DELETE FROM system.lease ` +
> 			`WHERE ("descID", version, "nodeID", expiration, epoch) = ($1, $2, $3, $4, $5)`
> ```

let's please add an id to these leases since we're doing a migration so we won't have to run statements like this for ever
___
*[pkg/sql/lease.go, line 1729 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZz-iL7co2NFYLWmcs:-LJZz-iL7co2NFYLWmct:b-6a68ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L1729)):*
> ```Go
> 				for nodeID, es := range epochs {
> 					if !es.released && es.duration > 2*m.leaseDuration {
> 						// Release stability epoch. This is a rather aggressive strategy
> ```

what's a "stability epoch"?

**Review by vivekmenezes — COMMENTED** [review]
The contradiction was not intended. The lease expiration will be set to infinity only after the cluster has been upgraded.

It is my intention to centralize it somehow using perhaps the node with the lowest nodeid that is live.

in this PR the deadline is still set to the 5 minute interval under the assumption that other nodes can withdraw the lease only after they have seen a new epoch for the 2 * 5 minute interval.

The shortlived frequently extension lease is not for 2.1 . Perhaps to ultimately get rid of the expiration one will have to pass the epoch in the end transaction. But that is not the intention for 2.1

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-:-LJ_5ShNADBUoAI2liFr:boeswit)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZy3eR9rwesR6ISc4Z:-LJ_78Qb89a0YRlwjDBf:bjf1w4m) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L155)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I don't understand what's going on here... We modify a local variable but then not use it again? Are we returning the right thing?
</blockquote></details>

when we have an infinite lease we return an expiration of 5 minutes as the deadline for the txn
___
*[pkg/sql/lease.go, line 244 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZyhXV-f73o_2bobW0:-LJ_7eCq4PcHyQpAQKva:b-wqqm5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L244)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

let's please add an id to these leases since we're doing a migration so we won't have to run statements like this for ever
</blockquote></details>

Do you have some efficiency idea in mind?
___
*[pkg/sql/lease.go, line 1729 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZz-iL7co2NFYLWmcs:-LJ_7pCF9I2-Ow_BOaxc:b-bvxois) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L1729)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

what's a "stability epoch"?
</blockquote></details>

because the epochs can keep moving forward this method can keep getting starved. The stability epoch is the one that is eventually used in the call to release(). Its the one that was last seen 2 * 5 minutes ago

**Review by vivekmenezes — COMMENTED** [review]
The main idea here is given a leaseDuration = 5m, a lease at a particular epoch is valid until infinity or (observation_time + leaseDuration + some delta), where observation_time = time when epoch+1 was observed by the cluster. Therefore a transaction using such a lease must use a deadline of txn.origTimestamp() + leaseDuration.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-:-LJ_CgEZ3SWxd0GAu9hi:b-s4ud01)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by vivekmenezes — COMMENTED** [review]
As far as the consistency of the data is concerned the only guarantee we want to have is that the txn deadline is before the withdrawal time (deletion time) of the lease. The issue of how much time epoch +1 takes to propagate through the cluster only affects the wait time for a schema change in the ungraceful shutdown scenario.

The main danger here is a node moving along using leases at epoch while it itself has transitioned to epoch + 1 and for that we have to use a "delta" that makes sense.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-:-LJ_HsYM-a4ZlgtjfIHV:b-f7v859)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — COMMENTED** [review]
I'm confused, sorry :)
Can you please explain again the envisioned deal before (if any changes here) and after the cluster version bump? What is a txn's deadline and when does a new lease need to be acquired?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-:-LJ_IPYLDWxbwB0bsDb8:bcuz99e)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Review by andreimatei — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28458)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/sql/lease.go, line 155 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZy3eR9rwesR6ISc4Z:-LJ_JrKB1ooXkDXGezTC:bfcycqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L155)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

when we have an infinite lease we return an expiration of 5 minutes as the deadline for the txn
</blockquote></details>

but we're returning the unchanged `tvs.expiration`, which is `hlc.MaxTimestamp`, aren't we?
___
*[pkg/sql/lease.go, line 244 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZyhXV-f73o_2bobW0:-LJ_K7Sz1PxKFh6AJ4ex:bf5ze0c) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L244)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

Do you have some efficiency idea in mind?
</blockquote></details>

I just want to identify a lease by something else other then the totality of its columns. I guess after your change we can identify a lease uniquely by nodeid+epoch+version?
___
*[pkg/sql/lease.go, line 1729 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-LJZz-iL7co2NFYLWmcs:-LJ_Kl121FMc8L0aG3QL:b-u0mncx) ([raw file](https://github.com/cockroachdb/cockroach/blob/913ef4bde0f7541f361b4d271f29bd126ffca96e/pkg/sql/lease.go#L1729)):*
<details><summary><i>Previously, vivekmenezes wrote…</i></summary><blockquote>

because the epochs can keep moving forward this method can keep getting starved. The stability epoch is the one that is eventually used in the call to release(). Its the one that was last seen 2 * 5 minutes ago
</blockquote></details>

I haven't looked at this method carefully yet and so I don't know if I understand what's going on, but the `stabilityEpoch` field definitely needs some comment

**Comment by vivekmenezes** [comment]
FYI, I'm moving forward with this idea in separate PRs. Thanks for all your comments.

**Review by vivekmenezes — COMMENTED** [review]
The node will continue to have its old epoch but won't NodeLiveness.Self() return an error? As long as it returns an error the expiration on the epoch will occur after 5 minutes and the node will not be able to use its leases.

The main motivations for this change are fixing issues https://github.com/cockroachdb/cockroach/issues/23510 and  https://github.com/cockroachdb/cockroach/issues/18684 . I'd originally built a periodic polling mechanism to fix them but after talking to robert about his need to support 10,000 tables (100 databases with 100 tables each) to prototype a multi-tenant system, I realized the polling implementation was not going to scale (approximately 40 lease renews a second per node).

Additionally after building this prototype I felt the implementation was not as complex as I had imagined. Thanks

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28458#-:-LJpSPqK1hPpuSTZ_lI1:b-z6dds2)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by petermattis** [comment]
I'm a bit worried about making a significant change to the table lease system at this point in the release cycle. This is an area of the system which has the potential to affect all queries. The risk seems high. 

Refreshing 10k table leases every 5min translates into 33 table leases / sec. That doesn't sound unreasonable if spread relatively evenly over that time period. I'd worry more if there is any part of the system which invalidates all of the leases simultaneously.

**Comment by vivekmenezes** [comment]
Peter,

FYI the periodic refresh to leases also comes with risk because it's not
yet reviewed. That's another reason I didn't want to go that way.

I feel this change can be turned on with a flag which we can turn off if
its resulting in instability.
We still have two months until ga

Vivek

**Comment by vivekmenezes** [comment]
It occurred to me that the polling mechanism will hit the same range for
the lease table. So a 10 node cluster would get the equivalent traffic of
40*10 = 400 writes per second hitting the same range.

Since we're still not at code freeze I think we should be bold and move
forward with the changes under flag as long as the changes are well
understood and well tested.

Vivek

**Comment by bdarnell** [comment]
> The node will continue to have its old epoch but won't NodeLiveness.Self() return an error?

No, it won't. NodeLiveness.Self() only returns an error when we have not yet made our first contact with the liveness data. Once we have something, we'll continue using it until it is replaced by something else. The epoch number alone is not very meaningful except when combined with its expiration time. 

400 writes per second to the lease range is a lot, so when we support 10k tables we'll probably need to do something about it. But we need to think about what that is (this is subtle enough to need at least a mini-rfc), and not just adopt new requirements at the end of a development cycle (we haven't created the release branch yet, but we still should be working towards stability and not adding new capabilities). If someone does need to support 10k tables before we can implement something like this for 2.2 or later, they can increase the lease duration (the only thing this hurts is the ability to do schema changes shortly after a node restarts uncleanly). 

It's also not at all clear that this is the only change that would be needed to support 10k tables. When we build support for this use case we'll need to budget enough time to test it and ensure that we can fix any issues that may be necessary beyond lease maintenance overhead.

**Comment by vivekmenezes** [comment]
closing this discussion in favor of an update to the RFC: https://github.com/cockroachdb/cockroach/pull/28628

I'm still trying to get this into 2.1 only because we haven't branched yet :-)

**Pull request closed without merging**
