### PR TITLE
ui, server: move node diagnostic page to the admin ui

### PR DESCRIPTION
**Pull request by BramGruneir**
No filter (ignore the weird tool tip in the top left):
screen shot 2017-06-12 at 14 41 43

With a locality regex filter:
screen shot 2017-06-12 at 14 41 36

With a locality regex filter and a node id filter:
screen shot 2017-06-12 at 14 41 27

Future work to be done after this is merged is to start to abstract out the common parts used by all debug pages and rename problemRanges to debugProblemRanges (and move the status to under /debug/).

### CODE REVIEW

**Comment by BramGruneir** [comment]
@mrtracy's notes from the wrong PR:

---

*[pkg/server/debug_nodes.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16494#-KmXOFGDv4oUP8mdOSYw:-KmXOFGDv4oUP8mdOSYx:b-llwm3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/33036d05f69df84c3f626b13a8c407d7791287ae/pkg/server/debug_nodes.go#L192)):*
> ```Go
> 			Title:   header.title,
> 			Values:  []string{header.title},
> 			Classes: []string{debugClassCellLeftHeader, debugClassCellShort},
> ```

Hmm... This essentially abandons the separation of concerns. The backend should produce the data, and your frontend should present that data to the user.  Here, you are having the backend directly instruct the frontend how to present the data very directly; in terms of CSS classes, even. The backend here is expecting to know exactly what this CSS styling this class will apply on the frontend; that *might* be acceptable *as a hack* if we had absolutely no control over the front-end, but here we have full control over the frontend.

If necessary, give the data some semantic information that describes it; for example, marking it as a "warning" is fine.

---

*[pkg/ui/src/views/devtools/containers/debugNodes/index.tsx, line 124 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16494#-KmXSU6jgU9LA0WTlBvR:-KmXSU6jgU9LA0WTlBvS:b-b9fa71) ([raw file](https://github.com/cockroachdb/cockroach/blob/33036d05f69df84c3f626b13a8c407d7791287ae/pkg/ui/src/views/devtools/containers/debugNodes/index.tsx#L124)):*
> ```XML
>                             <span key={k}>
>                               {value}
>                               <br/>
> ```

Just use divs if you are putting line breaks here, it's not a span anymore at that point.  Spans are specifically inline - like italic or bold text, for example.

Actually, the most semantically correct element may be an unordered list.

---

*[pkg/ui/src/views/devtools/containers/debugNodes/index.tsx, line 142 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16494#-KmXU6RJoRUbWrLNkVKz:-KmXU6RJoRUbWrLNkVL-:b-2p1xz3) ([raw file](https://github.com/cockroachdb/cockroach/blob/33036d05f69df84c3f626b13a8c407d7791287ae/pkg/ui/src/views/devtools/containers/debugNodes/index.tsx#L142)):*
> ```XML
>       <div className="section">
>         <h1>Node Diagnostics Page</h1>
>         {failuresTable(debugNodes.failures)}
> ```

These should be components instead of inline functions.  Basically:

1. Move these functions (i.e. "failuresTable") outside of the render() scope and to the top level of the file. This is good from a performance perspective, because we no longer need to create the closures inside of the render scope.  It also makes the "render" method shorter.
2. Change the signature of these methods to accept a single variable "props", which is an interface that accepts the existing props.  For example, the signature of failuresTable would be:
`function FailuresTable(props: { failures: protos.cockroach.server.serverpb.DebugFailure$Properties[] })`.  Note that you need the uppercase name for it to be a react component (you might have to add a ts-lint rule for this, for some reason it doesn't understand the JSX casing rules.)
3. write these as components instead of function calls:
`<FailuresTable failures={debugNodes.failures} />`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16494)*

**Comment by BramGruneir** [comment]
Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/server/debug_nodes.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-KmXlVW6koDr_2ARmilR:-KmXlVW6koDr_2ARmilS:bkrt6bn) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea19ac11b7dcf06aba4bae900e9a4e3b55174353/pkg/server/debug_nodes.go#L192)):*
> ```Go
> 			Title:   header.title,
> 			Values:  []string{header.title},
> 			Classes: []string{debugClassCellLeftHeader, debugClassCellShort},
> ```

@mrtracy said

Hmm... This essentially abandons the separation of concerns. The backend should produce the data, and your frontend should present that data to the user. Here, you are having the backend directly instruct the frontend how to present the data very directly; in terms of CSS classes, even. The backend here is expecting to know exactly what this CSS styling this class will apply on the frontend; that might be acceptable as a hack if we had absolutely no control over the front-end, but here we have full control over the frontend.

If necessary, give the data some semantic information that describes it; for example, marking it as a "warning" is fine.

---

*[pkg/ui/src/views/devtools/containers/debugNodes/index.tsx, line 119 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-KmXlmzg055ImIgRJLQM:-KmXlmzg055ImIgRJLQN:bm377tv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea19ac11b7dcf06aba4bae900e9a4e3b55174353/pkg/ui/src/views/devtools/containers/debugNodes/index.tsx#L119)):*
> ```XML
>                           <span key={k}>
>                             {value}
>                             <br/>
> ```

@mrtracy says
Just use divs if you are putting line breaks here, it's not a span anymore at that point. Spans are specifically inline - like italic or bold text, for example.

Actually, the most semantically correct element may be an unordered list.

---

*[pkg/ui/src/views/devtools/containers/debugNodes/index.tsx, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-KmXlwZ0a-1ZPVLrjJN-:-KmXlwZ0a-1ZPVLrjJN0:b-fruuzv) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea19ac11b7dcf06aba4bae900e9a4e3b55174353/pkg/ui/src/views/devtools/containers/debugNodes/index.tsx#L137)):*
> ```XML
>         <h1>Node Diagnostics Page</h1>
>         {failuresTable(debugNodes.failures)}
>         {filtersOutput(debugNodes.filters)}
> ```

@mrtracy says
These should be components instead of inline functions. Basically:

1. Move these functions (i.e. "failuresTable") outside of the render() scope and to the top level of the file. This is good from a performance perspective, because we no longer need to create the closures inside of the render scope. It also makes the "render" method shorter.
2. Change the signature of these methods to accept a single variable "props", which is an interface that accepts the existing props. For example, the signature of failuresTable would be:
function FailuresTable(props: { failures: protos.cockroach.server.serverpb.DebugFailure$Properties[] }). Note that you need the uppercase name for it to be a react component (you might have to add a ts-lint rule for this, for some reason it doesn't understand the JSX casing rules.)
3. write these as components instead of function calls:
<FailuresTable failures={debugNodes.failures} />

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475)*

**Comment by BramGruneir** [comment]
Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/server/debug_nodes.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-KmXlVW6koDr_2ARmilR:-KmXmASpOEMYOL6vc9-s:b-cnubl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea19ac11b7dcf06aba4bae900e9a4e3b55174353/pkg/server/debug_nodes.go#L192)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

@mrtracy said

Hmm... This essentially abandons the separation of concerns. The backend should produce the data, and your frontend should present that data to the user. Here, you are having the backend directly instruct the frontend how to present the data very directly; in terms of CSS classes, even. The backend here is expecting to know exactly what this CSS styling this class will apply on the frontend; that might be acceptable as a hack if we had absolutely no control over the front-end, but here we have full control over the frontend.

If necessary, give the data some semantic information that describes it; for example, marking it as a "warning" is fine.
</blockquote></details>

It does break the separation of concerns, in part, by design.

My goal here is to try to make some reusable table structure for all debug pages.  All of which have a matrix style 

Calling it a class is a misnomer here.  It really is more of a style.

So far, we have
* leftheader
* warning
* short

The actual styling is entirely up to the frontend, but what I'm trying to avoid is having a collection of highly specialized outputs and contains for each page.  The simpler the better. 

The one that doesn't fit there would be the "short" one.  I can see removing it.  
Perhaps changing this to a collection of flags would be better?  Would an enum from the protobuf work for you?

---

*[pkg/ui/src/views/devtools/containers/debugNodes/index.tsx, line 119 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-KmXlmzg055ImIgRJLQM:-KmXwfjdE1qmCy99LyR5:bba7pc6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea19ac11b7dcf06aba4bae900e9a4e3b55174353/pkg/ui/src/views/devtools/containers/debugNodes/index.tsx#L119)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

@mrtracy says
Just use divs if you are putting line breaks here, it's not a span anymore at that point. Spans are specifically inline - like italic or bold text, for example.

Actually, the most semantically correct element may be an unordered list.
</blockquote></details>

Done.  It's not an unordered list.  I also converted filtersOutput as well.

---

*[pkg/ui/src/views/devtools/containers/debugNodes/index.tsx, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-KmXlwZ0a-1ZPVLrjJN-:-KmXwxry5PRW4p7XM-rs:b-npyz8n) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea19ac11b7dcf06aba4bae900e9a4e3b55174353/pkg/ui/src/views/devtools/containers/debugNodes/index.tsx#L137)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

@mrtracy says
These should be components instead of inline functions. Basically:

1. Move these functions (i.e. "failuresTable") outside of the render() scope and to the top level of the file. This is good from a performance perspective, because we no longer need to create the closures inside of the render scope. It also makes the "render" method shorter.
2. Change the signature of these methods to accept a single variable "props", which is an interface that accepts the existing props. For example, the signature of failuresTable would be:
function FailuresTable(props: { failures: protos.cockroach.server.serverpb.DebugFailure$Properties[] }). Note that you need the uppercase name for it to be a react component (you might have to add a ts-lint rule for this, for some reason it doesn't understand the JSX casing rules.)
3. write these as components instead of function calls:
<FailuresTable failures={debugNodes.failures} />
</blockquote></details>

I'll be moving most of these to components.  But what I don't want to do is needless over-optimization.  So as soon as one is used in more than one location I will.  For example, that failures is moved in the my follow up PR #16501.

I expect all 3 of these will be full fledged components shortly.

For now, I've done step 1. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475)*

**Comment by mrtracy** [comment]
Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[pkg/server/debug_nodes.go, line 192 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-KmXlVW6koDr_2ARmilR:-KmY4OHqYJUy8qj7eL_l:b3amm8o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ea19ac11b7dcf06aba4bae900e9a4e3b55174353/pkg/server/debug_nodes.go#L192)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

It does break the separation of concerns, in part, by design.

My goal here is to try to make some reusable table structure for all debug pages.  All of which have a matrix style 

Calling it a class is a misnomer here.  It really is more of a style.

So far, we have
* leftheader
* warning
* short

The actual styling is entirely up to the frontend, but what I'm trying to avoid is having a collection of highly specialized outputs and contains for each page.  The simpler the better. 

The one that doesn't fit there would be the "short" one.  I can see removing it.  
Perhaps changing this to a collection of flags would be better?  Would an enum from the protobuf work for you?


</blockquote></details>

"It breaks the separation of concerns by design", I mean, why design it that way?  Why is the backend giving such explicit instructions for visual styling?  I really fail to see the benefit, in my mind you've just made this harder to understand for the next person who has to make a change to this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475)*

**Comment by mrtracy** [comment]
We have talked about this in person, and have been ruminating on this for the last day or so.  I think there are problems with the approach here, and we need to go in one of two directions.

1. If we are committed to these pages being first-class members of the Admin UI, then we need to *move most of the logic involved in computing these diagnostic report to the front-end*.  In this code review, the backend is still processing all of the data down into a report, and is inescapably sending rendering instructions to the Admin UI; in this design, the Admin UI basically becomes a "report renderer" for some bizarre, proprietary tabular data format expressed in protobuffers.  I dislike this intensely.

If we are concerned about network traffic, perhaps there are some individual computations that the backend can compute, but this should be more elemental; from the Admin UIs perspective, it should be querying informational data endpoints with strong, clear schemas.  From an architectural perspective, this provides a much better layering of responsibility, and should help third-party tools have a more flexible interaction with the backend.

2. If solution 1 is considered too expensive in terms of development time, then I see no reason to move these pages into the Admin UI at all; these report pages already exist, they're already displaying renderable HTML content, and we can even put them behind the upcoming user login.  Heck, if we really need the navigation bar we could use an iframe and still render the content inside of the Admin UI.

The "halfway" solution, presented in this PR, in my opinion is convoluted and adds needless complexity while providing no architectural benefits.

---

Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-:-KmcEf17tmH8iw36aueW:bz72atu)*

**Comment by petermattis** [comment]
> If we are committed to these pages being first-class members of the Admin UI, then we need to move most of the logic involved in computing these diagnostic report to the front-end. 

We're committed, but that doesn't mean we can't change our minds. I thought we were moving logic to compute the diagnostic page to the front-end. Certainly, some bits of data will necessarily be computed on the back-end because moving it to the front-end is too onerous or expensive, but most of the logic seems to belong in the front-end. 

Looking at the code, I imagine you're objecting to the inclusion of "layout" information in the `DebugNodes` endpoint. I agree, that seems awkward. Is there something else to the offline conversation? Is there an objection to moving the layout logic fully to the front-end? 

---

Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-:-KmcThyrrIgLriE8QA6w:b-iapi0u)*

**Comment by vivekmenezes** [comment]
I believe the objection stems from the use of the generic protobuf to
represent all of the pages. I believe the model we
want to use is a specific protobuf/schema per page. The generic protobuf
was a convenience built for the previous
implementation.

I think if this were being built the first time around we would certainly
use a specific schema per page, but given that we are
moving some stuff over in this PR I think we ought to be more flexible. I'd
suggest focusing on the problem and opportunity cost
rather than the violation of a principal. i see the PR getting rid of our
dependency on html/template

**Comment by BramGruneir** [comment]
Some of this was discussed offline, and I wanted to re-iterate the reasons behind the design decisions I made while working on this PR (and the rest of the work of moving these pages over).

What were our goals for this project:
* move the pages over to the admin ui
* do this quickly
* enable other engineers to quickly add to and edit the debug pages
* remove any reliance on go templates

Some non-goals:
* support some 3rd party frontend

I'm not going to go into the merits of moving the pages to the admin ui, suffice to say that we can expect that our users will indeed see the pages, most likely as some sort of advanced reports menu.  So they should look like they are indeed integrated and share common styles with the rest of the admin ui.

When formulating the design for moving these pages over, what I was looking at was the content of all the debug pages and latched onto the fact that they are all a collection of tables.  Each one has a failure table and either one or more amorphous tables with some minimal styling.  And by that, I mean that the tables will vary in the number of rows and columns based on data, sometimes between refreshes.  The way that most of them are currently rendered using the go templates is to assign the classes, titles, and values to a 2d matrix of cells and rely on some ad hoc css to render them properly.  However, each page did use a slightly different version of this.

For these pages, in order to quickly move them into the admin ui, I was trying to minimize the amount of code-rewriting/refactoring that was needed.  To that end, I opted to avoid doing any of the following if possible:
* Moving all of the sorting/matching/collating logic into javascript - this is a large task that would provide no clear benefit if rewritten in javascript
* Creating highly detailed explicit protobuf schemas for each page - since the logic was remaining on the go side, all that is needed for each page is a fairly simple protobuf with one or more generic 2d matrices (tables) with some basic rendering instructions and pre-formatted data to fill in the table
* Creating complex pages in javascript/jsx - by using this common definition for all the tables, it would allow a single component to use the rendering instructions to display the different tables on the javascript side with minimal intervention

What I did want to work on was getting rid of the ad hoc styles and leveraging the frontend's css system to ensure that not only did the new pages mesh well with the admin ui but also be able to restyle them all fairly quickly.

One clear advantage of this approach is that it also allows us to quickly make additions to these pages without having to touch protobufs or even the admin ui's code.  Say for example, if you wanted to add a new field to the range debug page (with a warning when the value on a replica is different than the leader).  With this style, all that needs to be added would be some copy-pasted code within the debug-range.go file and the rest would be taken care of automatically.  If we instead went with the logic in the javascript style, there are a number of places in which code would need to change:  on the go side; an update to the protobuf; updates to the logic in the javascript; and updates to the display logic to show the new row.  This is where, in my view, the unneeded complexity exists.  Furthermore, we are a shop of mostly golang developers, and I can see having to touch so many parts being a real barrier to entry for many.  

It's great to stand by the purity of the philosophy behind the code, but I felt that this was a more pragmatic solution.  I could also estimate the time it would take to move all the existing pages over to be around 2 weeks worth of work.  If each page needs to be entirely split into data fetching/filtering, sending and then display, I think this will be a larger task, and it also feels like a task that I've already completed once already.  

All that being said, if we decide to go in the opposite direction and use the "correct" way of doing things in the admin ui, I'll proceed in that direction instead of this one.  But I will have to re-estimate how long that's going to take.

---

Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-:-KmdqR8J_0K-hf1IYN_b:bpwdgz6)*

**Comment by petermattis** [comment]
Sounds like there were incompatible assumptions made by the various parties. I was assuming the move to the admin UI infrastructure would involve providing UI independent status endpoints. I too have no interest in supporting a 3rd party frontend, but I do want to keep a reasonable separation between the backend and frontend. This isn't a purity argument in my mind. We should be providing this separation so that we can easily support the CLI as well.

> Furthermore, we are a shop of mostly golang developers, and I can see having to touch so many parts being a real barrier to entry for many.

We'll soon have a number of people comfortable in typescript as well.

---

Review status: 0 of 19 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-:-Kmg1Mjkgn2Ci8ynSKMI:bowrtvv)*

**Comment by BramGruneir** [comment]
So as discussed, let's put this change on ice for a bit.  

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16475#-:-Kmn93622ECT7SU54YDv:b-l4gdv3)*

**Comment by BramGruneir** [comment]
Closed in favour of #17120.

**Pull request closed without merging**
