### PR TITLE
rangecache: fix a span use-after-Finish

### PR DESCRIPTION
**Pull request by andreimatei**
Lookups of range descriptors use a form of pretty unusual unstructured
concurrency: a request spawns a goroutine that might outlive it (in case
the request is canceled), but at the same time the goroutine wants to be
part of the same trace as the request. Before this patch, the goroutine
was responsible for forking the request's span asynchronously. This was
pretty broken because the request's span might be finished by the time
it's forked. This is a use-after-Finish, and I'm trying to stop
tolerating such uses. This patch fixes it by forking the span
synchronously.

Release note: None

### CODE REVIEW

**Review by aayushshah15 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73478)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15 and @andreimatei)

___
*[pkg/kv/kvclient/rangecache/range_cache.go, line 649 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73478#-MqCanKs1Q5ThUeZ9zHj:-MqCanKs1Q5ThUeZ9zHk:b-ep3o0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/fff5ca0ec692be32dc57fcdbd36cd13cc973643e/pkg/kv/kvclient/rangecache/range_cache.go#L649)):*
> ```Go
> 	}
> 	requestKey := makeLookupRequestKey(key, prevDesc, useReverseScan)
> 	reqCtx, reqSpan := tracing.EnsureChildSpan(ctx, rc.tracer, "range lookup")
> ```

Could you say why we don't just fork synchronously inside the `DoChan` callback?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73478)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aayushshah15)

___
*[pkg/kv/kvclient/rangecache/range_cache.go, line 649 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/73478#-MqCanKs1Q5ThUeZ9zHj:-MqFIetU6K1ADjKp2qOA:b-x9ba83) ([raw file](https://github.com/cockroachdb/cockroach/blob/fff5ca0ec692be32dc57fcdbd36cd13cc973643e/pkg/kv/kvclient/rangecache/range_cache.go#L649)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

Could you say why we don't just fork synchronously inside the `DoChan` callback?
</blockquote></details>

Like this?

**Review by aayushshah15 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73478#-:-MqFkZ1q-4paDz4OJy_r:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Review by andreimatei — COMMENTED** [review]
TFTR

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/73478#-:-MqFmd1S5R_llKWLnGiy:b-4as1hm)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @aayushshah15)

**Pull request merged**
