### PR TITLE
compose/compare: add tables to comparison tests

### PR DESCRIPTION
**Pull request by madelynnblue**
This involves quite a lot of mutation code to coerce tables created with
RandCreateTable into something that 1) postgres can executed and 2)
will execute identically between cockroach and postgres while keeping
the cockroach-specific features in the tables. Some of these features
don't affect query output, but should still be tested in cockroach (i.e.,
column families, interleave).

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/cmd/smithcmp/cmpconn/conn.go, line 115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44364#-LzO7aTb2fPAFsYdV5db:-LzO7aTb2fPAFsYdV5dc:b-q4b6h2) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad45e25738930f518de59070fe5798af93a7549/pkg/cmd/smithcmp/cmpconn/conn.go#L115)):*
> ```Go
> 	}
> 	mutated, _ = mutations.ApplyString(c.rng, exec, c.sqlMutators...)
> 	rows, err = c.PGX.QueryEx(ctx, exec, simpleProtocol)
> ```

The previous code was executing mutated `exec`.
___
*[pkg/compose/compare/compare/compare_test.go, line 129 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44364#-LzO8pLl6ea21AaWJ9-N:-LzO8pLl6ea21AaWJ9-O:bhbp8tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71408bbb1a6bed584f3d80e356196dc6b78475f/pkg/compose/compare/compare/compare_test.go#L129)):*
> ```Go
> 				connSetup, _ := mutations.ApplyString(rng, setup, testCn.mutators...)
> 				if err := conn.Exec(ctx, connSetup); err != nil {
> 					t.Log(setup)
> ```

Should we log `connSetup` here instead since that's the query that is actually executed?
___
*[pkg/sql/mutations/mutations.go, line 559 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44364#-LzO9V_I2tsE7a9B9nqH:-LzO9V_J1UwVJmKMwJFD:b-xoi4q9) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71408bbb1a6bed584f3d80e356196dc6b78475f/pkg/sql/mutations/mutations.go#L559)):*
> ```Go
> 					continue
> 				}
> 				stmt.Defs = append(stmt.Defs[:i], stmt.Defs[i+1:]...)
> ```

If I understand correctly, these "removal" statements are only reached when we have family table definition. I'd move it up in there and get rid off all `continue` statements. I would find that easier to read.
___
*[pkg/sql/mutations/mutations.go, line 569 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44364#-LzOAB-JBUB5auA-IVWH:-LzOAB-JBUB5auA-IVWI:bd2ocgj) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71408bbb1a6bed584f3d80e356196dc6b78475f/pkg/sql/mutations/mutations.go#L569)):*
> ```Go
> 					continue
> 				}
> 				stmt.Cmds = append(stmt.Cmds[:i], stmt.Cmds[i+1:]...)
> ```

ditto for moving it inside the `if` block and removing the negation on `ok`. My mental model is something like "check whether we support this statement, if we don't, then remove it, if we do, then proceed to the next statement".

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44364)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/smithcmp/cmpconn/conn.go, line 115 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/44364#-LzO7aTb2fPAFsYdV5db:-LzOWCmmBm5smDQElrwc:b52jums) ([raw file](https://github.com/cockroachdb/cockroach/blob/bad45e25738930f518de59070fe5798af93a7549/pkg/cmd/smithcmp/cmpconn/conn.go#L115)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The previous code was executing mutated `exec`.
</blockquote></details>

yikes good catch
___
*[pkg/compose/compare/compare/compare_test.go, line 129 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44364#-LzO8pLl6ea21AaWJ9-N:-LzOWKuI42ePVf1ipujH:b2nign6) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71408bbb1a6bed584f3d80e356196dc6b78475f/pkg/compose/compare/compare/compare_test.go#L129)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Should we log `connSetup` here instead since that's the query that is actually executed?
</blockquote></details>

yes
___
*[pkg/sql/mutations/mutations.go, line 559 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44364#-LzO9V_I2tsE7a9B9nqH:-LzOZsCgDPHhhA4bc7rl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71408bbb1a6bed584f3d80e356196dc6b78475f/pkg/sql/mutations/mutations.go#L559)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

If I understand correctly, these "removal" statements are only reached when we have family table definition. I'd move it up in there and get rid off all `continue` statements. I would find that easier to read.
</blockquote></details>

Done.
___
*[pkg/sql/mutations/mutations.go, line 569 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/44364#-LzOAB-JBUB5auA-IVWH:-LzO_2Zm4VR90ypYixB5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/b71408bbb1a6bed584f3d80e356196dc6b78475f/pkg/sql/mutations/mutations.go#L569)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

ditto for moving it inside the `if` block and removing the negation on `ok`. My mental model is something like "check whether we support this statement, if we don't, then remove it, if we do, then proceed to the next statement".
</blockquote></details>

Done.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

I just had a random thought: in `CompareVals` do we need to have special case when comparing floats to make sure that their are within "closeness"? I guess not because floats fall under `pgtype.Numeric` and we converts those to a decimal, right?

> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, 2 of 3 files at r10, 3 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44364#-:-LzOyLkZBZKQAsKXe3fA:bovu2h3)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

**Comment by mjibson** [comment]
cmpconn already has both of those. for floats:

https://github.com/cockroachdb/cockroach/blob/7d63e8eab5fa3be71e9f8fe55998646ab2f03f3e/pkg/cmd/smithcmp/cmpconn/compare.go#L126

and decimals:

https://github.com/cockroachdb/cockroach/blob/7d63e8eab5fa3be71e9f8fe55998646ab2f03f3e/pkg/cmd/smithcmp/cmpconn/compare.go#L130

**Pull request merged**
