### PR TITLE
sql: update the `SHOW RANGE FOR ROW` command to just take index cols

### LINKED ISSUE #41421: sql: allow SHOW RANGE FROM TABLE foo FOR ROW to only apply for fields in PK
Using the new SQL SHOW RANGE FROM TABLE foo FOR ROW command is a bit difficult as it requires the user to input some values for all of the columns in the table and not just the PK:
Consider the vehicles table in MovR:
```SQL
show create table vehicles;
  table_name |                                       create_statement
+------------+-----------------------------------------------------------------------------------------------+
  vehicles   | CREATE TABLE vehicles (
             |     id UUID NOT NULL,
             |     city VARCHAR NOT NULL,
             |     type VARCHAR NULL,
             |     owner_id UUID NULL,
             |     creation_time TIMESTAMP NULL,
             |     status VARCHAR NULL,
             |     current_location VARCHAR NULL,
             |     ext JSONB NULL,
             |     CONSTRAINT "primary" PRIMARY KEY (city ASC, id ASC),
             |     CONSTRAINT fk_city_ref_users FOREIGN KEY (city, owner_id) REFERENCES users(city, id),
             |     INDEX vehicles_auto_index_fk_city_ref_users (city ASC, owner_id ASC),
             |     FAMILY "primary" (id, city, type, owner_id, creation_time, status, current_location, ext)
             | )
(1 row)

Time: 46.349ms
```
To use the new command you must provide values for every entry and not just those in the PK:
```SQL
show range from table vehicles for row ('acde070d-8c4c-4f0d-9d8a-162843c10333','san francisco','',Null,Null,'','',Null);
  start_key | end_key | range_id | lease_holder | lease_holder_locality | replicas |                           replica_localities
+-----------+---------+----------+--------------+-----------------------+----------+------------------------------------------------------------------------+
  NULL      | NULL    |       26 |            4 | region=us-east,az=1   | {3,4,8}  | {"region=us-west,az=2","region=us-east,az=1","region=us-central,az=1"}
(1 row)

Time: 7.347ms
```
PK only:
```SQL
root@127.0.0.1:49818/movr> show range from table vehicles for row ('acde070d-8c4c-4f0d-9d8a-162843c10333','san francisco');
pq: number of values in row must equal number of columns in the requested table
```
You must provide values for everything in a secondary index which means, in effect, you must provide values for all columns in order to specify which columns apply.

### PR DESCRIPTION
**Pull request by rohany**
Fixes #41421.

The SHOW RANGE FOR ROW command was difficult to use because it required
the user to input all of the columns in a particular row. This PR
changes the command to only require inputting the index columns now.

Release note (backward-incompatible change): The SHOW RANGE FOR ROW
command has been changed to take in a tuple of the row's index columns,
rather than the full column set of the row.

### CODE REVIEW

**Comment by rohany** [comment]
cc @awoods187, mind playing around with this once it lands?

**Review by solongordon — APPROVED** [review]
LGTM though let's give the user more help in the weird implicit columns case.

> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50479#-:-MAS9o_vCu7j8070L7l7:b-9njvl1)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rohany and @solongordon)

___
*[pkg/sql/sem/builtins/builtins.go, line 3332 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50479#-MAS9NInCrFgSmPzXm40:-MAS9NIo2qfHfLGwm1BM:bd51pd6) ([raw file](https://github.com/cockroachdb/cockroach/blob/06fb35c1d4e56479cccead4bcf05db024e5db104/pkg/sql/sem/builtins/builtins.go#L3332)):*
> ```Go
> 						return nil, errors.WithHintf(
> 							err,
> 							"columns %v are implicitly part of index %q's key and must be included",
> ```

I wonder if we can make this message clearer. It's not clear what order the columns should be provided in. Maybe it would be more helpful to provide a complete list of the columns which should be specified.

**Comment by rohany** [comment]
Updated the message, PTAL

**Review by solongordon — APPROVED** [review]

**Comment by rohany** [comment]
bors r=solongordon

**Pull request merged**
