### PR TITLE
raft: enable store liveness in raft unit tests phase 2

### PR DESCRIPTION
**Pull request by iskettaneh**
This commit modifies the following tests to allow them to run in both
store liveness enabled/disabled configurations:

1) TestPreVoteMigrationCanCompleteElection
2) TestPreVoteMigrationWithFreeStuckPreCandidate
3) TestAddNodeCheckQuorum
4) TestCandidateResetTermMsgHeartbeat
5) TestCandidateResetTermMsgApp

Note that these tests create their own Raft instances instead of relying
on the network te create ones.

References: https://github.com/cockroachdb/cockroach/issues/132241

Release note: None

### CODE REVIEW

**Review by arulajmani — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133971)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh)

___
*[`pkg/raft/raft_test.go` line 4367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133971#-OAcO2Qj9X14aA-6oIQe:-OAcO2Qj9X14aA-6oIQf:b-gtzzxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/3283e59158e5c26df57f0770aaceaf1303f66e18/pkg/raft/raft_test.go#L4367)):*
> ```Go
> 	for j, p := range peers {
> 		id := peerAddrs[j]
> 		// If we are not creating a liveness fabric from scratch, it's the caller's
> ```

Instead of having this logic in this for loop, conditional on `createNewFabric`, let's add another for loop that simply calls `fabric.AddPeer(id)` above. Then, you don't need this awkward comment about responsibilities here and don't need to track the `createNewFabric` variable. 
___
*[`pkg/raft/raft_test.go` line 1694 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133971#-OAcOhJx-OmQAWaL1U6n:-OAcOhJyD6PhH36JpvhI:bur1i1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/ede91fcc099913d4192dc2e39fba3762233da379/pkg/raft/raft_test.go#L1694)):*
> ```Go
> 
> 	if storeLivenessEnabled {
> 		// We need to withdraw support of the current leader to allow the new peer
> ```

nit: these comments would read better if they talked about peerIDs instead of current leader. So, something like:

``` 
// We need to withdraw support from 1 before 2 can campaign and get elected
```

Here, and elsewhere.
___
*[`pkg/raft/raft_test.go` line 1703 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133971#-OAcOv2yEurl585kv3tj:-OAcOv2yEurl585kv3tk:b-k4lilk) ([raw file](https://github.com/cockroachdb/cockroach/blob/ede91fcc099913d4192dc2e39fba3762233da379/pkg/raft/raft_test.go#L1703)):*
> ```Go
> 	if storeLivenessEnabled {
> 		// We need to withdraw support of the current leader to allow the new peer
> 		// to campaign and get elected.
> ```

We're also granting support to 1 because we withdrew support from it above; otherwise 1 can't be elected again.
___
*[`pkg/raft/raft_test.go` line 1734 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133971#-OAcPtRK6ZmmMCIjHIC8:-OAcPtRK6ZmmMCIjHIC9:b-fyftl1) ([raw file](https://github.com/cockroachdb/cockroach/blob/ede91fcc099913d4192dc2e39fba3762233da379/pkg/raft/raft_test.go#L1734)):*
> ```Go
> 	nt.recover()
> 	if storeLivenessEnabled {
> 		// Restore the liveness support state.
> ```

nit: adding context about why would improve this comment. Here, and elsewhere the comment was copy pasted.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133971)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft_test.go` line 4367 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/133971#-OAcO2Qj9X14aA-6oIQe:-OAdSQud58jHTVhivWM7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3283e59158e5c26df57f0770aaceaf1303f66e18/pkg/raft/raft_test.go#L4367)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of having this logic in this for loop, conditional on `createNewFabric`, let's add another for loop that simply calls `fabric.AddPeer(id)` above. Then, you don't need this awkward comment about responsibilities here and don't need to track the `createNewFabric` variable.
</blockquote></details>

Done.
___
*[`pkg/raft/raft_test.go` line 1703 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/133971#-OAcOv2yEurl585kv3tj:-OAdQEQmDUXD1pPJjKQs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ede91fcc099913d4192dc2e39fba3762233da379/pkg/raft/raft_test.go#L1703)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

We're also granting support to 1 because we withdrew support from it above; otherwise 1 can't be elected again.
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133971#-:-OAsQ6le5dY9xTI0bAGp:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @iskettaneh)

___
*[`pkg/raft/raft_test.go` line 3986 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/133971#-OAsPrV09LyAud9SZLnk:-OAsPrV09LyAud9SZLnl:bdnj0mw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a5ea86755e9ab17b3be09fa33eb48bd2ed4bd5e/pkg/raft/raft_test.go#L3986)):*
> ```Go
> 
> 	if storeLivenessEnabled {
> 		// We need to withdraw support from 1 before 2 can campaign and get elected.
> ```

nit: should this say "before 3 can campaign and get elected"?

**Comment by iskettaneh** [comment]
TFTR!

bors r+

**Pull request merged**
