### PR TITLE
perf: re-use evaluation Batch on proposer in proposer-evaluated KV

### LINKED ISSUE #10415: perf: re-use evaluation Batch on proposer in proposer-evaluated KV
Proposer-evaluated KV currently opens a Batch, writes to it, and serializes to a WriteBatch when a command is proposed. Subsequently, at apply time, all nodes create a Batch from the serialized WriteBatch and commit that.

That is unnecessary on the proposer itself; we should keep the evaluation Batch open and simply commit that when the Raft command applies.

This shouldn't be a hard change: keep the evaluation Batch in `LocalProposalData` and make sure to commit it appropriately instead of using the `WriteBatch`.
A wrinkle of complexity is that when the command does *not* apply, we must not leak the evaluation `Batch`. No intrinsic complexity there though; just have to make sure that whenever we delete a proposal, we close the contained Batch.

Since the proposer always has the waiting client, this should measurably reduce the commit latency and should show in benchmarks. It's also easy enough to hack together if preliminary results are desired.

### PR DESCRIPTION
**Pull request by yznming**
fix #10415  @tschottdorf 
btw, how to verify it improves the performance? any reference would be appreciate.

### CODE REVIEW

**Comment by petermattis** [comment]
Thanks for the PR, @yzming. I've been running some performance load tests recently. I'll try this out soon.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/replica.go, line 4331 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16951#-KogbSykKlNucHbRRiR2:-KogbSykKlNucHbRRiR3:b-itl3pj) ([raw file](https://github.com/cockroachdb/cockroach/blob/65eab308f71a4ae19218de48438094c0aadb0291/pkg/storage/replica.go#L4331)):*
> ```Go
> 
> 	if batch == nil {
> 		batch = r.store.Engine().NewWriteOnlyBatch()
> ```

This PR might be a performance regression because the proposer batch is a read-write batch and normally we're committing a write-only batch. I'm specifically thinking of the code in `rocksDBBatch.Commit` which performs batch grouping, but only for write-only batches. I don't recall the exact reason grouping is not done for read-write batches.

---

*[pkg/storage/replica.go, line 4336 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16951#-Kogc5d1U0kxsMPfo-8G:-Kogc5d1U0kxsMPfo-8H:bhg38jj) ([raw file](https://github.com/cockroachdb/cockroach/blob/65eab308f71a4ae19218de48438094c0aadb0291/pkg/storage/replica.go#L4336)):*
> ```Go
> 
> 	if writeBatch != nil {
> 		if err := batch.ApplyBatchRepr(writeBatch.Data, false); err != nil {
> ```

All this PR is saving is this call to `ApplyBatchRepr`, but for a write-only batch this is very fast. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16951#-:-KogcD0F8AZyIrn09DrF:bvinaur)*

**Comment by petermattis** [comment]
Running `ycsb --workload F` on a 6-node cluster showed a 9.4% performance decline from this change. My suspicion is that the handling of read-write batches in `rocksDBBatch.Commit` is the cause. I'll see if there is anything that can be done. 

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16951#-:-KohN4OxpcT0xniHwQ20:bag9ow7)*

**Comment by yznming** [comment]
@petermattis what's difference between read-write batch and write-only batch in `Commit` stage?

**Comment by petermattis** [comment]
@yznming See https://github.com/cockroachdb/cockroach/pull/16976.

**Comment by petermattis** [comment]
After merging #16976 and rebasing on top of that PR, I can't measure a performance benefit to this change. My recommendation would be to close it, or perhaps change it to replace the `TODO(tschottdorf)` with a small comment indicating why using the reusing the proposer batch for application is not a performance win. I'm happy to write that comment.

@tschottdorf Thoughts?

**Comment by tschottdorf** [comment]
Yep, I agree. Sorry for sending you down a path that ultimately didn't result in a win, @yznming!

**Comment by yznming** [comment]
@tschottdorf it's OK. We can try other ways to improve the performance.

**Comment by irfansharif** [comment]
Though I suspect it's not going to make much difference on the proposer, downstream of raft, we can skip [`batch.ApplyBatchRepr`](https://github.com/yznming/cockroach/blob/65eab308f71a4ae19218de48438094c0aadb0291/pkg/storage/replica.go#L4336) as the batch already has these writes. I'm pretty sure this also applies to [`setAppliedIndex`](https://github.com/yznming/cockroach/blob/65eab308f71a4ae19218de48438094c0aadb0291/pkg/storage/replica.go#L4351),  though this makes MVCCStats computation for the delta unclear. Basically skip everything and commit directly.

**Comment by petermattis** [comment]
> Though I suspect it's not going to make much difference on the proposer, downstream of raft, we can skip batch.ApplyBatchRepr as the batch already has these writes. I'm pretty sure this also applies to setAppliedIndex, though this makes MVCCStats computation for the delta unclear. Basically skip everything and commit directly.

Which `ApplyBatchRepr` can be skipped? The one in `Replica.applyRaftCommand`?

**Comment by irfansharif** [comment]
> Which `ApplyBatchRepr` can be skipped? The one in `Replica.applyRaftCommand`?

Yes, on the proposer. If I'm not mistaken.

**Comment by petermattis** [comment]
> > Which ApplyBatchRepr can be skipped? The one in Replica.applyRaftCommand?
>
> Yes, on the proposer. If I'm not mistaken.

That's exactly what this PR got rid of. But that call is very fast because applying a batch repr to a write-only batch is more or less a memory copy. I was unable to measure a performance benefit to getting rid of it.

**Comment by irfansharif** [comment]
doh, missed [this](https://github.com/yznming/cockroach/blob/65eab308f71a4ae19218de48438094c0aadb0291/pkg/storage/replica.go#L4142). nm.

**Pull request closed without merging**
