### PR TITLE
multitenant: make {EXPERIMENTAL_}RELOCATE compatible with secondary tenants

### PR DESCRIPTION
**Pull request by ecwall**
Informs #93452

Use the RangeDescIterator in {EXPERIMENTAL_}RELOCATE so that secondary tenants can use these commands.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
LGTM modulo request.
Please also take a review from Arul.

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94063#-:-NJpKUt38U9ssOCVUGYR:bi9f3xn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @ecwall, @michae2, and @rafiss)

___
*[`pkg/sql/opt_exec_factory.go` line 2026 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94063#-NJpJghs80on4UucLEYU:-NJpJghtAC1L2w_z_GQF:bxgefqd) ([raw file](https://github.com/cockroachdb/cockroach/blob/e965687bbed61cc1e4e8874973eafa34608d30e1/pkg/sql/opt_exec_factory.go#L2026)):*
> ```Go
> 	fromStoreID tree.TypedExpr,
> ) (exec.Node, error) {
> ```

nit: remove empty line.
___
*[`pkg/sql/relocate.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94063#-NJpKEwT1p_5zP2nuACb:-NJpKEwT1p_5zP2nuACc:b-e97ai7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e965687bbed61cc1e4e8874973eafa34608d30e1/pkg/sql/relocate.go#L117)):*
> ```Go
> 		EndKey: rKey.PrefixEnd().AsRawKey(),
> 	}
> 	rangeDescIterator, err := execCfg.RangeDescIteratorFactory.NewIterator(params.ctx, span)
> ```

Since this lookup is also used in another place, please put it in a separate function used in both places. Perhaps this new function could be called `lookupRangeDescriptor` too?
___
*[`pkg/sql/relocate_range.go` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94063#-NJpKMtd06VIhdASPZX-:-NJpKMtd06VIhdASPZX0:b-bfjan4) ([raw file](https://github.com/cockroachdb/cockroach/blob/e965687bbed61cc1e4e8874973eafa34608d30e1/pkg/sql/relocate_range.go#L127)):*
> ```Go
> ) (*roachpb.RangeDescriptor, error) {
> 	execCfg := params.ExecCfg()
> 	rangeDescIterator, err := execCfg.RangeDescIteratorFactory.NewIterator(params.ctx, execCfg.Codec.TenantSpan())
> ```

shared function.

**Review by ecwall — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94063)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani, @knz, @michae2, and @rafiss)

___
*[`pkg/sql/opt_exec_factory.go` line 2026 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94063#-NJpJghs80on4UucLEYU:-NJq0VwuEkZyMpj9QgYN:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/e965687bbed61cc1e4e8874973eafa34608d30e1/pkg/sql/opt_exec_factory.go#L2026)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

nit: remove empty line.
</blockquote></details>

Fixed.
___
*[`pkg/sql/relocate.go` line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94063#-NJpKEwT1p_5zP2nuACb:-NJq0XW7CTBN0db02Ibh:b-vujdl2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e965687bbed61cc1e4e8874973eafa34608d30e1/pkg/sql/relocate.go#L117)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Since this lookup is also used in another place, please put it in a separate function used in both places. Perhaps this new function could be called `lookupRangeDescriptor` too?
</blockquote></details>

They are actually different since the other place gets ranges by ID and this place just uses the first range. I updated the code here to make that more obvious.
___
*[`pkg/sql/relocate_range.go` line 127 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/94063#-NJpKMtd06VIhdASPZX-:-NJq0jLF7v-TJg2Ht944:b-otilcs) ([raw file](https://github.com/cockroachdb/cockroach/blob/e965687bbed61cc1e4e8874973eafa34608d30e1/pkg/sql/relocate_range.go#L127)):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

shared function.
</blockquote></details>

See comment above.

**Review by michae2 — APPROVED** [review]
:lgtm: on behalf of sql queries

> Reviewed 1 of 6 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94063#-:-NJrByoM81vxQUcZDsWG:bsl2bhf)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani, @knz, and @rafiss)

**Review by knz — APPROVED** [review]
Thanks for the changes. Let's merge this, and if Arul would like to improve this further we'll make a followup PR in the new year.

> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94063#-:-NKIioo81XVqjswJtuL8:b-cfumti)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @arulajmani and @rafiss)

**Comment by ecwall** [comment]
bors r=knz,michae2

**Pull request merged**
