### PR TITLE
roachtest: adjust tpchvec test

### LINKED ISSUE #43259: roachtest: randomize workmem setting on tpchvec test
While debugging #43217, I ran into a few internal errors when I lowered `sql.distsql.temp_storage.workmem` to `6MiB` and `1MiB`. Once we have disk spilling, we should enhance `tpchvec` test to do some randomization with that setting. This issue is just a reminder to do so.

### LINKED ISSUE #45281: roachtest: tpchvec failed
[(roachtest).tpchvec failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=1759645&tab=buildLog) on [master@b797cad6d130714748983bc53d4611ddc6151153](https://github.com/cockroachdb/cockroach/commits/b797cad6d130714748983bc53d4611ddc6151153):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/tpchvec/run_1
	test_runner.go:756: test timed out (10h0m0s)

```

<details><summary>More</summary><p>

Artifacts: [/tpchvec](https://teamcity.cockroachdb.com/viewLog.html?buildId=1759645&tab=artifacts#/tpchvec)

[See this test on roachdash](https://roachdash.crdb.dev/?filter=status%3Aopen+t%3A.%2Atpchvec.%2A&sort=title&restgroup=false&display=lastcommented+project)
<sub>powered by [pkg/cmd/internal/issues](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)</sub></p></details>

### PR DESCRIPTION
**Pull request by yuzefovich**
This commit changes the way we run TPCH queries: previously, we would
run all of them in a round-robin fashion first with vec ON and then with
vec OFF, now we will run them one query at a time with both
configurations. Query 9 is now (temporarily) skipped. We now inject
statistics so that we don't have to wait for automatic statistics to be
collected.

Additionally, workmem is now randomized in [1, 64] MiB range
(previously, it was set to 1GiB).

We also set `vmodule=bytes_usage=1` on all nodes in the test cluster.

Fixes: #45281.
Fixes: #43259.

Release note: None

### CODE REVIEW

**Review by asubiotto — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45308)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/tpchvec.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shQCO3CRQeKQJW7s9:-M0shQCO3CRQeKQJW7sA:bkq9cux) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L54)):*
> ```Go
> 	}
> 	queriesToSkipByVersionPrefix["v20.1"] = map[int]string{
> 		// TODO(yuzefovich): remove this once disk spilling is in place.
> ```

Did the other queries run into the memory error due to the hashRouter accounting bug?
___
*[pkg/cmd/roachtest/tpchvec.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shkW_B9ugk4vdOnGY:-M0shkW_B9ugk4vdOnGZ:b27lfww) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L99)):*
> ```Go
> 		t.Status("waiting for full replication")
> 		waitForFullReplication(t, conn)
> 		numMinutesToSleep := 3
> ```

Why 3 minutes? Seems like a long time. If necessary, is there a way to force earlier stats collection?
___
*[pkg/cmd/roachtest/tpchvec.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shvty1IFjXAPtVs2Q:-M0shvty1IFjXAPtVs2R:bat5ji7) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L117)):*
> ```Go
> 			}
> 		}
> 		t.Status("setting vmodule=bytes_usage=1 on all nodes")
> ```

Are we sure we want to do this? This will skew the performance numbers a bit if we rely on these tests to get tpch numbers. Should we at least provide a way to disable it?
___
*[pkg/cmd/roachtest/tpchvec.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0siOoLCAoqxybrSugx:-M0siOoLCAoqxybrSugy:bar6tpj) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f79943d18e2494eed0816ae25375138d7a4d3f2/pkg/cmd/roachtest/tpchvec.go#L121)):*
> ```Go
> 			t.Status("reading all tables to populate the caches")
> 			for _, table := range TPCHTables {
> 				count := fmt.Sprintf("SELECT count(*) FROM %s;", table)
> ```

Do we not have to do this anymore?
___
*[pkg/cmd/roachtest/tpchvec.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0siYZs1U5vb70PlkD3:-M0siYZs1U5vb70PlkD4:b-6jfuiy) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L142)):*
> ```Go
> 				if err != nil {
> 					// Note: if you see an error like "exit status 1", it is likely caused
> 					// by the erroneous output of the query.
> ```

Should we call `t.Status` regardless of the error if it provides more clarity?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45308)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shQCO3CRQeKQJW7s9:-M0tBuRNAo1inTYthyQu:b-2cgm0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L54)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Did the other queries run into the memory error due to the hashRouter accounting bug?
</blockquote></details>

I don't think so, query 9 seems to operate on the biggest amount of data.
___
*[pkg/cmd/roachtest/tpchvec.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shkW_B9ugk4vdOnGY:-M0tCK0D3vXrUQcEq5E3:bxqlw1d) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L99)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why 3 minutes? Seems like a long time. If necessary, is there a way to force earlier stats collection?
</blockquote></details>

I believe that automatic statistics collection job is kicked off right after the TPCH backup is restored, and the population of stats on `lineitem` takes about 2 minutes, so 3 minutes just to be safe.

Initially, I tried an approach with checking whether there are any stats on all of the tables (via `SHOW STATISTICS FOR TABLE %s`), but I ran into an error that `region` table didn't exist. I don't know how that could have happened, but I thought that just sleeping is safer.
___
*[pkg/cmd/roachtest/tpchvec.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shvty1IFjXAPtVs2Q:-M0tDA3r8tY0FIGks7zv:b4sn5dl) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L117)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Are we sure we want to do this? This will skew the performance numbers a bit if we rely on these tests to get tpch numbers. Should we at least provide a way to disable it?
</blockquote></details>

I think that absolute runtime numbers are not that important (might be wrong though), and we're mostly interested in the comparison between vec ON and OFF, so both engines should be impacted - hopefully - to about the same degree.

At least for the some time I would like to have this logging on always so that in case similar fatal OOM crash occurs, at least there would be some data to debug with. If it doesn't occur within a couple of weeks, we can remove this.
___
*[pkg/cmd/roachtest/tpchvec.go, line 121 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0siOoLCAoqxybrSugx:-M0tDoFvCzvf9W9jHVzI:b-rtzp4q) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f79943d18e2494eed0816ae25375138d7a4d3f2/pkg/cmd/roachtest/tpchvec.go#L121)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we not have to do this anymore?
</blockquote></details>

I don't think it actually ever worked, and now that we have increased the number of runs per query, I don't think this would give us any benefit.
___
*[pkg/cmd/roachtest/tpchvec.go, line 142 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0siYZs1U5vb70PlkD3:-M0tECMB4EqkRxq9UgZk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L142)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should we call `t.Status` regardless of the error if it provides more clarity?
</blockquote></details>

Done.

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45308)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/roachtest/tpchvec.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shQCO3CRQeKQJW7s9:-M0wbkDW1ly6IVqOOSlb:b-mt4fhj) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L54)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I don't think so, query 9 seems to operate on the biggest amount of data.
</blockquote></details>

I mean previously, because a lot of them are listed as "can cause OOM", which made us bump the limit up to 1GiB, so reducing it to 64MiB at most means that something changed. I know for sure that query 5 had this issue, wondering if the rest of the queries ran into it too.
___
*[pkg/cmd/roachtest/tpchvec.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shkW_B9ugk4vdOnGY:-M0wbzuB37co2Up64EVh:b-nplubu) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L99)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I believe that automatic statistics collection job is kicked off right after the TPCH backup is restored, and the population of stats on `lineitem` takes about 2 minutes, so 3 minutes just to be safe.

Initially, I tried an approach with checking whether there are any stats on all of the tables (via `SHOW STATISTICS FOR TABLE %s`), but I ran into an error that `region` table didn't exist. I don't know how that could have happened, but I thought that just sleeping is safer.
</blockquote></details>

Maybe region is a reserved keyword or something? Alternatively, would it be possible to inject statistics since the dataset doesn't change?
___
*[pkg/cmd/roachtest/tpchvec.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shvty1IFjXAPtVs2Q:-M0wcCfO3gVr7PaWxROn:b4qekzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L117)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I think that absolute runtime numbers are not that important (might be wrong though), and we're mostly interested in the comparison between vec ON and OFF, so both engines should be impacted - hopefully - to about the same degree.

At least for the some time I would like to have this logging on always so that in case similar fatal OOM crash occurs, at least there would be some data to debug with. If it doesn't occur within a couple of weeks, we can remove this.
</blockquote></details>

I think absolute runtimes are important, because we'll probably use this as a tool to get some numbers between versions. We definitely at least want a flag to disable this.
___
*[pkg/cmd/roachtest/tpchvec.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0wci2h1LyudGQnQt0M:-M0wci2h1LyudGQnQt0N:b-812xn1) ([raw file](https://github.com/cockroachdb/cockroach/blob/15b2d1f666334a905ee14d82596c1ea74af13318/pkg/cmd/roachtest/tpchvec.go#L146)):*
> ```Go
> 					// TODO(yuzefovich): remove the condition once disk spilling is in
> 					// place.
> 					if !strings.Contains(string(workloadOutput), "memory budget exceeded") {
> ```

Shouldn't this be handled by the fact that we skip certain queries that we know run into this error? If we're doing this explicitly to give us some breathing room until disk spilling is enabled, we should probably add a comment.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45308)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/cmd/roachtest/tpchvec.go, line 54 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shQCO3CRQeKQJW7s9:-M0xBs9C8-Gi-Y6hu8Bx:bhsssbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L54)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I mean previously, because a lot of them are listed as "can cause OOM", which made us bump the limit up to 1GiB, so reducing it to 64MiB at most means that something changed. I know for sure that query 5 had this issue, wondering if the rest of the queries ran into it too.
</blockquote></details>

So in `19.2` there is no memory accounting, and that's why it's not safe to run that subset of queries.

In `20.1` we have memory account and external algorithms, so we don't expect to be hitting memory limits (maybe for `hash-aggregator`). What changed is that we added the external algorithms that use dummy queues (which still do memory accounting), so we "spill to memory".
___
*[pkg/cmd/roachtest/tpchvec.go, line 99 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shkW_B9ugk4vdOnGY:-M0xDfue0Izd2y5KuPOi:b5lcx9d) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L99)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe region is a reserved keyword or something? Alternatively, would it be possible to inject statistics since the dataset doesn't change?
</blockquote></details>

I tried restoring the backup locally and then running `SHOW STATISTICS FOR TABLE region`, and it worked like a charm, so I'm very puzzled by how that error could have occurred.

I also thought that injecting stats might be a way to go but brushed off that thought because of thinking that statistics are per node and we scatter all the tables. But I just looked into the comments for sample aggregator spec, and it seems that statistics are "global" (i.e. shared between all nodes), so injecting should work. Done.
___
*[pkg/cmd/roachtest/tpchvec.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shvty1IFjXAPtVs2Q:-M0xIcJc1kFQxETteh27:bewqudn) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L117)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think absolute runtimes are important, because we'll probably use this as a tool to get some numbers between versions. We definitely at least want a flag to disable this.
</blockquote></details>

Do `roachtest`s support custom flags? I don't think that I've seen an example of this.

I think that right now the stability is a lot more important than absolute numbers (I don't think that we have ever looked at absolute numbers in this test before). If some time later we do need the absolute numbers, then we can just remove this `vmodule` part then, but I'd like to have the verbose logging for the next few weeks.
___
*[pkg/cmd/roachtest/tpchvec.go, line 146 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0wci2h1LyudGQnQt0M:-M0xXsX1-GnJ7JoJJXbS:b-cu489x) ([raw file](https://github.com/cockroachdb/cockroach/blob/15b2d1f666334a905ee14d82596c1ea74af13318/pkg/cmd/roachtest/tpchvec.go#L146)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Shouldn't this be handled by the fact that we skip certain queries that we know run into this error? If we're doing this explicitly to give us some breathing room until disk spilling is enabled, we should probably add a comment.
</blockquote></details>

We skip queries in `19.2` release, and in `20.1` we don't.

For example, query 1 hits a limit on hash aggregator: `Error: [q1]: pq: hash-aggregator-limited: memory budget exceeded: 4669440 bytes requested, 24268800 currently allocated, 25165824 bytes in budget`. The goal for this change is that I'd like to run `tpchvec` roachtest a few times with different memory limits, and see what the errors are.

**Review by asubiotto — APPROVED** [review]
:lgtm: How does the variance look?

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-:-M116UQ51cvbNksGSCgX:bi0yui0)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/roachtest/tpchvec.go, line 117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-M0shvty1IFjXAPtVs2Q:-M116P8GAEGkB1EM8bRC:b2nhktp) ([raw file](https://github.com/cockroachdb/cockroach/blob/163f4281e4bfb992041bb72052a2cb3782883c82/pkg/cmd/roachtest/tpchvec.go#L117)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Do `roachtest`s support custom flags? I don't think that I've seen an example of this.

I think that right now the stability is a lot more important than absolute numbers (I don't think that we have ever looked at absolute numbers in this test before). If some time later we do need the absolute numbers, then we can just remove this `vmodule` part then, but I'd like to have the verbose logging for the next few weeks.
</blockquote></details>

OK.

**Review by yuzefovich — COMMENTED** [review]
With the stats injected the numbers were reasonable in the test run I did yesterday (like a few percent difference). Previously, it could be on the order of 100% difference on the first couple of queries (I assume while the stats were not yet collected, so we were running a suboptimal plan).

TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45308#-:-M1182KU0fWNJmo1C3TF:blpbjnx)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
