### PR TITLE
kvclient: stop reads on followers

### LINKED ISSUE #112351: kvclient: don't send follower reads to unhealthy nodes
**Describe the problem**

A draining node is likely to shut down soon. By moving the leaseholders off we stop all non-follower reads to that node, but we don't prevent follower reads from using it. SInce we already know that it is draining, we should either exclude or prioritize last the draining or suspect nodes. This could be enhanced to also exclude nodes with IO overload or generally take the health of the node into account when deciding which node to send a follower read to.

**To Reproduce**

1. Create a CRDB cluster with 6 nodes.
2. Run a workload of only follower reads at a low rate.
3. Drain and then stop one of the nodes.
4. Notice the P99.99 ~3s latency at the time the node is stopped due to read attempts waiting for an RPC timeout.

**Expected behavior**

From a client perspective, draining a node should allow clean shutdown without a performance impact. Follower reads break this model because while all the leases are moved, so normal reads and writes do not require this node, follower reads don't take this into account.

**Additional context**
This was noticed in a customer investigation where they had a 500ms client timeout on read requests and saw an elevated number of failures when they were cycling nodes. 

Jira issue: CRDB-32365

### PR DESCRIPTION
**Pull request by andrewbaptist**
Stop follower reads on draining, decommissioning or unhealthy nodes.

Epic: none
Fixes: #112351

Release note (performance improvement): This change prevents failed requests from being issued on followers that are draining, decommissioning or unhealthy which prevents latency spikes if those nodes later go offline.

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114205)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andrewbaptist and @mgartner)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114205#-NitsmDVEoCsN-Z3uv6Q:-NitsmDVEoCsN-Z3uv6R:b-z9bek9) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3bdff2074ab59c90d02a1e3446b5f65aca051f2/pkg/kv/kvclient/kvcoord/dist_sender.go#L278)):*
> ```Go
> 	"kv.dist_sender.follower_reads_unhealthy.enabled",
> 	"send follower reads to unhealthy nodes",
> 	true,
> ```

We want to start with this set to false, right? Until we've mitigated the performance impact. We can then set it to true in the tests which want to exercise it.

I guess the downside of that is that we get less passive testing of the logic. We don't want certain customers running with logic that we only test in rare cases.

Ok, I guess it seems ok to keep this set to true on master to ensure it gets full test coverage, and then set it to false in the backport.

----

EDIT: I was actually misinterpreting this setting. I thought "true" meant "opt into the new behavior". Landing this on master defaulted to off (true) seems like the right approach. I think we may still want to get it turned on by default on master before backporting the off-by-default version to the release branch, so we know that it's at least getting full test coverage on some branch.

Does that seem like a reasonable plan?
___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go` line 1184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114205#-NitvQyjDpCIpXsd9cTb:-NitvQyk6Riyy4-8nH0k:b-2oqps1) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3bdff2074ab59c90d02a1e3446b5f65aca051f2/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L1184)):*
> ```Go
> 			Settings:          settings,
> 			Locality:          localities[i],
> 			DefaultTestTenant: base.TestIsSpecificToStorageLayerAndNeedsASystemTenant,
> ```

When we backport, we'll just not include this, right? Are there any downsides to that, other than the test taking a little longer?

**Review by andrewbaptist — COMMENTED** [review]
TFTR - Running one more time with the removal of the TestArgs so it can be an "exact" backport. It should finish shortly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114205#-:-NiuCaGk3rLROTUVocb4:b-i7dsrr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender.go` line 278 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114205#-NitsmDVEoCsN-Z3uv6Q:-NiuC8T73MpBqnHSBGKT:bwugj0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3bdff2074ab59c90d02a1e3446b5f65aca051f2/pkg/kv/kvclient/kvcoord/dist_sender.go#L278)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We want to start with this set to false, right? Until we've mitigated the performance impact. We can then set it to true in the tests which want to exercise it.

I guess the downside of that is that we get less passive testing of the logic. We don't want certain customers running with logic that we only test in rare cases.

Ok, I guess it seems ok to keep this set to true on master to ensure it gets full test coverage, and then set it to false in the backport.

----

EDIT: I was actually misinterpreting this setting. I thought "true" meant "opt into the new behavior". Landing this on master defaulted to off (true) seems like the right approach. I think we may still want to get it turned on by default on master before backporting the off-by-default version to the release branch, so we know that it's at least getting full test coverage on some branch.

Does that seem like a reasonable plan?
</blockquote></details>

Yes - this is exactly what I was thinking. Leaving this as "disabled" (reading from unhealthy) no both 23.2 and master and then enabling once the other PRs land.
___
*[`pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go` line 1184 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114205#-NitvQyjDpCIpXsd9cTb:-NiuCIG98cT-KEtc8wW-:b317isk) ([raw file](https://github.com/cockroachdb/cockroach/blob/e3bdff2074ab59c90d02a1e3446b5f65aca051f2/pkg/ccl/kvccl/kvfollowerreadsccl/followerreads_test.go#L1184)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

When we backport, we'll just not include this, right? Are there any downsides to that, other than the test taking a little longer?
</blockquote></details>

I'm removing these settings so I don't need to wait for the other PR. I'll reenable these later on master in a different PR. It does just take a little longer, although I've seen tests flake on stress+race without these. 

We have a somewhat annoying situation that tests only run StressRace after a change has been made to them, and I believe a number of tests (maybe a majority) will fail the first time any change is made. We probably should figure out a better way to handle this.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114205#-:-NiuJ_gi0SIHFKtl0l-9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

**Comment by andrewbaptist** [comment]
bors r=nvanbenschoten

**Comment by andrewbaptist** [comment]
blathers backport 23.2

**Pull request merged**
