### PR TITLE
client: Don't log frequent, expected abort errors

### LINKED ISSUE #10490: client: `Txn.CleanupOnError` logs if transaction is already aborted
`Txn.CleanupOnError` doesn't return an error, but it calls `log.Errorf` if an error occurs during rollback, which will happen if the transaction is already known to be aborted (this error comes from the client package; no request is sent to the server in this case). 

We should at least handle the case of an already-aborted transaction silently, and for other kinds of errors `log.Error` is probably not the right way to handle it - this should probably go into the trace and not the server's log.

### PR DESCRIPTION
**Pull request by a-robinson**
Just send them to the event trace instead.

Fixes #10490

### CODE REVIEW

**Comment by bdarnell** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/internal/client/txn.go, line 442 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15326#-Ki_mNMQDNYZl2o_mHd9:-Ki_mNMQDNYZl2o_mHdA:bhzr0b4) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e2b5415a8e55ecbad62b55dc2c33e7eabe1216c/pkg/internal/client/txn.go#L442)):*
> ```Go
> 	if txn.status() == roachpb.PENDING {
> 		if replyErr := txn.Rollback(ctx); replyErr != nil {
> 			if replyErr.Error() == "does not exist" || replyErr.Error() == "already committed" ||
> ```

These are both `TransactionStatusError`. I think we should make all `TransactionStatusErrors` quiet instead of looking at specific messages. (If we do want to distinguish subtypes of `TransactionStatusError`, we should add an explicit enum to the proto instead of doing string matching in non-test code. That "does not exist" error message really needs to be updated since it appears to be leaking out to users)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15326)*

**Comment by a-robinson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/internal/client/txn.go, line 442 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15326#-Ki_mNMQDNYZl2o_mHd9:-Ki_t9ac1l63K-1jzLMQ:be1grhp) ([raw file](https://github.com/cockroachdb/cockroach/blob/6e2b5415a8e55ecbad62b55dc2c33e7eabe1216c/pkg/internal/client/txn.go#L442)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

These are both `TransactionStatusError`. I think we should make all `TransactionStatusErrors` quiet instead of looking at specific messages. (If we do want to distinguish subtypes of `TransactionStatusError`, we should add an explicit enum to the proto instead of doing string matching in non-test code. That "does not exist" error message really needs to be updated since it appears to be leaking out to users)
</blockquote></details>

Done. I wasn't sure that it was reasonable to ignore all `TransactionStatusError`s.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15326)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica_test.go, line 3379 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15326#-Ki_tXb2Cu5As-91q0zC:-Ki_tXb39LTSX49XFYC-:b-9v09vq) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f44c053a8ecac16b4a20381099b180b76e50990/pkg/storage/replica_test.go#L3379)):*
> ```Go
> 		expErrRegexp string
> 	}{
> 		// NB: If the "does not exist" or "already committed" error messages change,
> ```

Remove this comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15326#-:-Ki_tZAIbr4fRJJxLX1j:bnfp4nl)*

**Comment by a-robinson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/replica_test.go, line 3379 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15326#-Ki_tXb2Cu5As-91q0zC:-Ki_uCNG1v2TFs3G31Cy:burzyzg) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f44c053a8ecac16b4a20381099b180b76e50990/pkg/storage/replica_test.go#L3379)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

Remove this comment.
</blockquote></details>

Ugh, thanks. That's what I get for running crlfmt on the entire repo and manually cleaning up afterward, losing my other changes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15326)*

**Pull request merged**
