### PR TITLE
storage/engine: fix Pebble bloom filters

### LINKED ISSUE #42351: cli: Pebble test failures
The failures here can be reproduced with:

```
~ COCKROACH_STORAGE_ENGINE=pebble make test PKG=./cli TESTS=...
```

`TestRemoveDeadReplicas` times out and never completes. Note that the `removeDeadReplicas` command currently hard codes usage of RocksDB for the surgery performed on the store. This might be indicative of an incompatibility between RocksDB and Pebble.

### PR DESCRIPTION
**Pull request by petermattis**
The Pebble `Comparer.Split` function was returning a different key
prefix than the prefix extractor we are using with RocksDB. The Pebble
version was omitting the trailing NUL byte the RocksDB one was including
it. This meant that Pebble generated bloom filters were incompatible
with RocksDB generated ones.

This fixes `TestRemoveDeadReplicas` which opens a store using Pebble,
repairs the store using RocksDB, then re-opens the store using
Pebble. This final step was failing to find the `storeIdent` key to the
bloom filter problem.

Add support for using Pebble in `cli.OpenExistingStore`, though note
that TODO that this currently causes a test failure.

Fixes #42351

Release note: None

### CODE REVIEW

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, @petermattis, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42405#-LtVQ3Iu5i4ff0n0Ains:-LtVQ3Iu5i4ff0n0Aint:b-93s045) ([raw file](https://github.com/cockroachdb/cockroach/blob/85cf8d7f002d919a57646c77ef9bdcd6a71523fd/pkg/storage/engine/pebble.go#L73)):*
> ```Go
> 		// This matches the behavior of libroach/KeyPrefix. RocksDB requires that
> 		// keys generated via a SliceTransform be comparable with normal encoded
> 		// MVCC keys. Encoded MVCC keys have a suffix indicating the number of
> ```

is there a reason for this RocksDB requirement?

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42405#-LtVQ3Iu5i4ff0n0Ains:-LtVQSJC75bDKeum7amH:b-z8r3fu) ([raw file](https://github.com/cockroachdb/cockroach/blob/85cf8d7f002d919a57646c77ef9bdcd6a71523fd/pkg/storage/engine/pebble.go#L73)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

is there a reason for this RocksDB requirement?
</blockquote></details>

I'm pretty sure that somewhere in the bowels of RocksDB it compares transformed keys vs untransformed keys. I'm pretty sure Pebble doesn't do this. I couldn't point to the specific line of code in RocksDB that is problematic, though. It could also be that this comment is FUD (I copied it from `c-deps/libroach/encoding.cc`).  Regardless, we can't change the behavior of how which portion of the key we create a bloom filter on.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajkr, @itsbilal, and @sumeerbhola)

___
*[pkg/cli/debug.go, line 143 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/42405#-LtW16XLBI2G112QgjOF:-LtW16XM6TFLbpXOJyEc:byztzh) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0c5cfaed3d18884990ee8c6b6682d5506ccf815/pkg/cli/debug.go#L143)):*
> ```Go
> 	// TODO(peter): Using Pebble here causes TestRemoveDeadReplicas to fail with:
> 	//
> 	// debug_test.go:292: pebble: internal error: L0 flushed file 000004 overlaps with the largest seqnum of a preceding flushed file: 0-2278 vs 414
> ```

This is fixed by https://github.com/cockroachdb/pebble/pull/392.

**Review by ajkr — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42405#-:-LtW6Eoq0K5XW5Nf32Qm:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42405#-LtVQ3Iu5i4ff0n0Ains:-LtW1Wzx5dFdpWpN_oDw:b-m9k5bf) ([raw file](https://github.com/cockroachdb/cockroach/blob/85cf8d7f002d919a57646c77ef9bdcd6a71523fd/pkg/storage/engine/pebble.go#L73)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

I'm pretty sure that somewhere in the bowels of RocksDB it compares transformed keys vs untransformed keys. I'm pretty sure Pebble doesn't do this. I couldn't point to the specific line of code in RocksDB that is problematic, though. It could also be that this comment is FUD (I copied it from `c-deps/libroach/encoding.cc`).  Regardless, we can't change the behavior of how which portion of the key we create a bloom filter on.
</blockquote></details>

The `Options::prefix_extractor` API doc suggests it makes these comparisons although I don't know why it would / where it does.

**Review by petermattis — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42405#-:-LtW6lsGDFiWv3q6wE4p:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @itsbilal and @sumeerbhola)

___
*[pkg/storage/engine/pebble.go, line 73 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/42405#-LtVQ3Iu5i4ff0n0Ains:-LtW6TOx-tVSZIIkEDB7:b6ain19) ([raw file](https://github.com/cockroachdb/cockroach/blob/85cf8d7f002d919a57646c77ef9bdcd6a71523fd/pkg/storage/engine/pebble.go#L73)):*
<details><summary><i>Previously, ajkr (Andrew Kryczka) wrote…</i></summary><blockquote>

The `Options::prefix_extractor` API doc suggests it makes these comparisons although I don't know why it would / where it does.
</blockquote></details>

I think the problem might be that we pass the transformed string from `prefix_extractor` into the comparator. So we're not comparing transformed vs untransformed strings, but comparing transformed strings against each other. The transformed string needs to be compatible with the comparator.

**Pull request merged**
