### PR TITLE
sql: add plan gist to sampled query telemetry log

### LINKED ISSUE #71328: Enrich the existing query log format for cloud telemetry
This builds on top of this [issue](https://github.com/cockroachdb/cockroach/issues/70553) to capture additional workload insights and details in our telemetry pipeline. The previous format for query events is outlined in the following [spreadsheet](https://docs.google.com/spreadsheets/d/15IAXvF5UWJ_nK42D1NwxwnoTy4Hm_9hzMtOyT26OC0Q/edit#gid=0).

Additional information to capture:

- [x] HasIndexJoin (we have HasFullTableScan today) (not available)
- - `index_join_count` field
- [x] Contention (wait time) (not available)
- [x] Statement Fingerprint ID (measuring uniqueness of a workload) (not available)
- [ ] Database ID (not available)
- - complications with adding Database ID, documented in: https://github.com/cockroachdb/cockroach/pull/84195
- [x] Database name
- [x] Session ID
- [x] Transaction ID (measure how large/conversational transactions are)
- [x] Statement ID (Avoid having to filter based on the query text)
- [x] Plan from the plan gist (determine the complexity and how optimal the workload is)
- [ ] Whether the query touched all cluster nodes ([related issue](https://github.com/cockroachdb/cockroach/issues/81922)) (not available)
- [x] [Index recommendation](https://github.com/cockroachdb/cockroach/issues/83782) (not available)

Jira issue: CRDB-10514

Epic CRDB-13538

### PR DESCRIPTION
**Pull request by THardy98**
Partially resolves: #71328

This change adds a plan gist field to the sampled query telemetry log.
The plan gist is written as a base64 encoded string.

Release note (sql change): The sampled query telemetry log now includes
a plan gist field. The plan gist field provides a compact representation
of a logical plan for the sampled query, the field is written as a
base64 encoded string.

### CODE REVIEW

**Comment by THardy98** [comment]
@vy-ton currently added the `plan_gist` in its base64 encoded string form. Is this the form that we wanted, or the decoded plan gist rows?

**Comment by cucaroach** [comment]
I don’t know what a telemetry log is but just writing the gist sounds fine,  the plan can be decoded with decode_plan_gist.  The gist is just integer ids there's no PII in there.   What's the use case/context for where we might want to decode the gist?

**Comment by THardy98** [comment]
> I don’t know what a telemetry log is but just writing the gist sounds fine, the plan can be decoded with decode_plan_gist. The gist is just integer ids there's no PII in there. What's the use case/context for where we might want to decode the gist?

I imagine for debugging/investigation purposes

**Review by maryliag — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83027)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[`docs/generated/eventlog.md` line 2461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83027#-N5fNuQM-PlGRDi2fJ6P:-N5fNuQM-PlGRDi2fJ6Q:bdtn4ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a6b198cc12f4f24683d3e980f7ab3a2a3f177aa/docs/generated/eventlog.md#L2461)):*
> ```Markdown
> | `CostEstimate` | Cost of the query as estimated by the optimizer. | no |
> | `Distribution` | The distribution of the DistSQL query plan (local, full, or partial). | no |
> | `PlanGist` | The query's plan gist bytes as a base64 encoded string. | yes |
> ```

plan gist is not sensitive
___
*[`pkg/util/log/eventpb/json_encode_generated.go` line 3294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83027#-N5fO1e7A6seRaDJdeUg:-N5fO1e7A6seRaDJdeUh:b28sy30) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a6b198cc12f4f24683d3e980f7ab3a2a3f177aa/pkg/util/log/eventpb/json_encode_generated.go#L3294)):*
> ```Go
> 		printComma = true
> 		b = append(b, "\"PlanGist\":\""...)
> 		b = append(b, redact.StartMarker()...)
> ```

there is no need to redact the gist
___
*[`pkg/sql/telemetry_logging_test.go` line 235 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83027#-N5fO4U95KMY3R7xa67W:-N5fO4U95KMY3R7xa67X:b-4swzju) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a6b198cc12f4f24683d3e980f7ab3a2a3f177aa/pkg/sql/telemetry_logging_test.go#L235)):*
> ```Go
> 				}
> 				// Match plan gist on any non-empty string value.
> 				planGist := regexp.MustCompile("\"PlanGist\":(\"\\S+\")")
> ```

when this test is executed? we have cases where we don't have a plan gist, so we might not send this, which will fail your test

**Comment by THardy98** [comment]
> when this test is executed? we have cases where we don't have a plan gist, so we might not send this, which will fail your test

Only executes for the test cases above which produce plan gists.

**Review by THardy98 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83027)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

___
*[`docs/generated/eventlog.md` line 2461 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83027#-N5fNuQM-PlGRDi2fJ6P:-N5fV362ArSEhcpsj3Xx:bizlmrb) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a6b198cc12f4f24683d3e980f7ab3a2a3f177aa/docs/generated/eventlog.md#L2461)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

plan gist is not sensitive
</blockquote></details>

Tagged as non-sensitive.
___
*[`pkg/util/log/eventpb/json_encode_generated.go` line 3294 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/83027#-N5fO1e7A6seRaDJdeUg:-N5fV5AKA8bicRe5oX1e:b-siolcm) ([raw file](https://github.com/cockroachdb/cockroach/blob/5a6b198cc12f4f24683d3e980f7ab3a2a3f177aa/pkg/util/log/eventpb/json_encode_generated.go#L3294)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

there is no need to redact the gist
</blockquote></details>

Ditto :)

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 5 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83027#-:-N5fscNLBwfgOADwhKL8:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag and @THardy98)

**Comment by THardy98** [comment]
TYFR :)

**Comment by kevin-v-ngo** [comment]
@THardy98, can this be backported?

**Pull request merged**
