### PR TITLE
storage: deflake TestStoreRangeMergeTimestampCacheCausality

### PR DESCRIPTION
**Pull request by benesch**
TestStoreRangeMergeTimestampCacheCausality could time out if the merge
transaction retried, which occured about one out of every two hundred
runs, because it would try to send multiple values over a channel whose
buffer had room for only one value. Deflake the test by remembering in a
variable the value from the last merge transaction to execute rather
than using channels.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
FYI this hasn't appeared to fail on master or a release branch yet, but it failed in an unrelated PR build of mine.

**Review by nvb — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28928)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/client_merge_test.go, line 507 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28928#-LKXrPATE0sr0yuWjCWW:-LKXrPATE0sr0yuWjCWX:b-tuc101) ([raw file](https://github.com/cockroachdb/cockroach/blob/668f252db527ba47c095e18861b5f09ae67423d1/pkg/storage/client_merge_test.go#L507)):*
> ```Go
> 	storeCfg := storage.TestStoreConfig(nil /* clock */)
> 	mtc := &multiTestContext{storeConfig: &storeCfg}
> 	var readTS hlc.Timestamp
> ```

We don't need to access this atomically because `ba.IsSingleSubsumeRequest()` will only ever be `true` for requests that are performed on the main testing goroutine, right?

**Review by benesch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28928)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/storage/client_merge_test.go, line 507 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/28928#-LKXrPATE0sr0yuWjCWW:-LKXrwW4DN98bp8kfuKR:b-7g6egz) ([raw file](https://github.com/cockroachdb/cockroach/blob/668f252db527ba47c095e18861b5f09ae67423d1/pkg/storage/client_merge_test.go#L507)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

We don't need to access this atomically because `ba.IsSingleSubsumeRequest()` will only ever be `true` for requests that are performed on the main testing goroutine, right?
</blockquote></details>

I think there's still concurrency somewhere, actually. But it's safe because there can only be one Subsume request executing at a time and the main goroutine won't look at the value until the merge has completed at which point there cannot be any Subsume requests executing.

**Review by nvb — APPROVED** [review]

**Comment by benesch** [comment]
bors r=nvanbenschoten

**Pull request merged**
