### PR TITLE
physicalplan: debugging for segfault in fakeSpanResolverIterator.Seek

### PR DESCRIPTION
**Pull request by michae2**
Break up a line that is segfaulting into several lines, so that we can tell which part is to blame if it happens again.

Informs: #100051
Informs: #100108

Epic: None

Release note: None

### CODE REVIEW

**Review by rharding6373 — APPROVED** [review]
:lgtm: Thanks!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100204#-:-NRoN-Kh-HvKHWXd5nwS:b-g2a5fb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach)

**Review by rharding6373 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100204)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @michae2)

___
*[`pkg/sql/physicalplan/fake_span_resolver.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100204#-NRoN8eE7UWmo1zDAWJ_:-NRoN8eE7UWmo1zDAWJa:b-ukyiyd) ([raw file](https://github.com/cockroachdb/cockroach/blob/3985b7ba91cf457fd8bb928422eaeb5317d3b2f8/pkg/sql/physicalplan/fake_span_resolver.go#L171)):*
> ```Go
> 	fit.ranges = make([]fakeRange, len(splits)-1)
> 	for i := range fit.ranges {
> 		nodes := fit.fsr.nodes
> ```

minor nit: maybe there should be a comment here so that a reasonable person doesn't clean this up in the near future.

**Review by cucaroach — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100204)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @rharding6373)

___
*[`pkg/sql/physicalplan/fake_span_resolver.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100204#-NRoRYc_CrTOhFktwoRt:-NRoRYc_CrTOhFktwoRu:b-6jjfhr) ([raw file](https://github.com/cockroachdb/cockroach/blob/3985b7ba91cf457fd8bb928422eaeb5317d3b2f8/pkg/sql/physicalplan/fake_span_resolver.go#L172)):*
> ```Go
> 	for i := range fit.ranges {
> 		nodes := fit.fsr.nodes
> 		n := len(nodes)
> ```

It looks weird (to me) that n and nodes aren't hoisted outside the loop.

**Review by michae2 — COMMENTED** [review]
TFTRs!

bors r=rharding6373,cucaroach

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/100204#-:-NRoT6YODed0T2K0SqR9:b-6qhezf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach and @rharding6373)

___
*[`pkg/sql/physicalplan/fake_span_resolver.go` line 171 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100204#-NRoN8eE7UWmo1zDAWJ_:-NRoT4cF83c2_MqN3rHr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3985b7ba91cf457fd8bb928422eaeb5317d3b2f8/pkg/sql/physicalplan/fake_span_resolver.go#L171)):*
<details><summary><i>Previously, rharding6373 (Rachael Harding) wrote…</i></summary><blockquote>

minor nit: maybe there should be a comment here so that a reasonable person doesn't clean this up in the near future.
</blockquote></details>

Done.
___
*[`pkg/sql/physicalplan/fake_span_resolver.go` line 172 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/100204#-NRoRYc_CrTOhFktwoRt:-NRoT5JUBYZ0tOUjJT40:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/3985b7ba91cf457fd8bb928422eaeb5317d3b2f8/pkg/sql/physicalplan/fake_span_resolver.go#L172)):*
<details><summary><i>Previously, cucaroach (Tommy Reilly) wrote…</i></summary><blockquote>

It looks weird (to me) that n and nodes aren't hoisted outside the loop.
</blockquote></details>

Done.

**Comment by knz** [comment]
might be worth backporting? in case this happens to 23.1 deployments

**Comment by michae2** [comment]
> might be worth backporting? in case this happens to 23.1 deployments

blathers backport 23.1

**Pull request merged**
