### PR TITLE
rfc: CockroachDB-specific query cancel protocol

### PR DESCRIPTION
**Pull request by knz**
Rendered text of the RFC:
https://github.com/knz/cockroach/blob/20220122-cancel-rfc/docs/RFCS/20220122_cancel_rfc.md

MVP implementation: #75211

**note: this RFC was rejected, because we've found another way. It is recorded in the repository for reference in future discussions.**

### CODE REVIEW

**Review by kpatron-cockroachlabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75307)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @petermattis, and @rafiss)

___
*[docs/RFCS/20220122_cancel_rfc.md, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuBrSb944qSClVEJQdI:-MuBrSb944qSClVEJQdJ:b-x4qjjh) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L349)):*
> ```Markdown
> 
> Note that if there is any error encountered during the steps 1-6, we
> hide this error from the client by sending a standardized payload back
> ```

As currently implemented I think this would be an issue because the query might not be cancelled by the customer if someone else consumes the nonce before them. I guess the user could detect this by seeing if the returned is more than one more than the one they provided.

If we make nonces only increment on successful cancels this would be prevented but an attacker could determine if their cancel message succeeded, which I think is fine. It is far more efficient for the attacker to capture a legitimate signed packet and guess the secret offline rather than sending it to us to validate each time.
___
*[docs/RFCS/20220122_cancel_rfc.md, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuBsNnd2oUhzb_NPGBm:-MuBsNneB4E0yVnFEBUA:b2c7dif) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L351)):*
> ```Markdown
> hide this error from the client by sending a standardized payload back
> in any case. This ensures that a malicious attacker (or legit
> pentester) cannot learn details about the infrastructure by blasting
> ```

If the nonces for invalid sessionIDs are always 1/2 they still might be able to infer some things from the response (or by sending multiple requests and seeing if it increments).

I don't think we should put too much effort into locking down this path.
___
*[docs/RFCS/20220122_cancel_rfc.md, line 454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuBtNTY-zm8kerzP1Je:-MuBtNTY-zm8kerzP1Jf:b-5dcfkf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L454)):*
> ```Markdown
> 
> In this protocol, the server maintains an integer counter alongside
> the shared secret. The counter is incremented at every authentication
> ```

see comment in the other PR. I would argue this should be incremented after every successful attempt.
___
*[docs/RFCS/20220122_cancel_rfc.md, line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuBtXWNCUqmDm2G2cOD:-MuBtXWNCUqmDm2G2cOE:b8rzd5r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L457)):*
> ```Markdown
> attempt and serves as nonce.
> 
> A cancel request is then computed as a HMAC of the shared secret
> ```

Nit: of the nonce using the shared secret. It's a little odd because in practice we are just hashing the shared secret and nonce but still.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75307)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @petermattis, and @rafiss)

___
*[docs/RFCS/20220122_cancel_rfc.md, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuCIki_AHvq1UsIW1-M:-MuCIki_AHvq1UsIW1-N:b-l8j8z8) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L148)):*
> ```Markdown
> However, in practice, a custom CockroachDB-specific SQL driver may
> remain elusive even if Cockroach Labs provides custom SDKs to
> end-users. More likely than not, CRL SDKs will be wrappers around
> ```

I do not agree with this - I anticipate that we will fork existing drivers rather than wrap them, and we will be able to make more extensive modifications. It's nice that we have an approach that can work through existing drivers in the short term, but in the long run I expect we'll be better off publishing our own drivers that encapsulate this protocol than asking developers of shells and gui tools to implement it at the application layer. 
___
*[docs/RFCS/20220122_cancel_rfc.md, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuCJQJnEryfBQ4zwtN_:-MuCJQJnEryfBQ4zwtNa:b-3sx6s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L280)):*
> ```Markdown
> The advantage is that it makes it extremely lightweight to
> process. The liability is that it makes cancellation messages
> vulnerable to *replayability*: a malicious user observing the network
> ```

The problem is that from the user perspective, they're cancelling a query (and this is logically an idempotent operation). But because the protocol targets a *session* instead of a query, we have the problem that an attempt to cancel on query can be abused to cancel other queries on the session. 

This RFC proposes a sequence number for cancellation attempts, but it would be ideal to tie the sequencer to the number of attempted queries. That may not be feasible with a light-touch wrapper around existing drivers, but it at least deserves a mention as an alternative. (and if we were making deeper protocol changes there are various ways we could include a per-query cancellation token for free). 
___
*[docs/RFCS/20220122_cancel_rfc.md, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuCXYtz9m8iloXbUC3C:-MuCXYtz9m8iloXbUC3D:b-7jj7hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L284)):*
> ```Markdown
> message and use it to cancel subsequent queries on the same session.
> 
> If at all possible, we could aim to preserve the advantage (low-cost
> ```

I question the goal of avoiding TLS (and note that this would be one-way TLS, not mTLS). Using TLS would let us use the "simple protocol" and we wouldn't need to implement the more complex "hmac protocol". I do not believe the cancellation operation is frequent or latency-sensitive enough that we need to avoid the cost of a TLS handshake. (and to the extent that we do care about this latency, TLS 1.3 reduced the handshake from 3 round trips to 1. There's also a 0-RTT "session resumption" mode but it comes with caveats so I'm not sure whether it is safe to use here or not). 
___
*[docs/RFCS/20220122_cancel_rfc.md, line 325 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuCV0_P-HVoX3EqYdOA:-MuCV0_P-HVoX3EqYdOB:b-nsf3hs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L325)):*
> ```Markdown
> needed. Also, because the `StartupMessage` remains standardized, it
> will be forwarded perfectly by off-the-shelf pg connection pools and
> forwarders.
> ```

One potential caveat here is that in TLS-required deployments, StartupMessage is never sent in the clear and it may be rejected by proxies. (Case in point: the proxy we built for CC serverless would need to be modified to pass this message along)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75307)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @kpatron-cockroachlabs, @petermattis, and @rafiss)

___
*[docs/RFCS/20220122_cancel_rfc.md, line 148 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuCIki_AHvq1UsIW1-M:-MuCl5iaAMVgENVJSvDf:b-grt4tp) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L148)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I do not agree with this - I anticipate that we will fork existing drivers rather than wrap them, and we will be able to make more extensive modifications. It's nice that we have an approach that can work through existing drivers in the short term, but in the long run I expect we'll be better off publishing our own drivers that encapsulate this protocol than asking developers of shells and gui tools to implement it at the application layer. 
</blockquote></details>

This is not contradicting the point being made here IMHO. I was highlighting that the first next action taken by CRL on this will be to wrap existing drivers, and we're likely not going to simultaneously push our users to use a SDK and also switch drivers (moving two pieces at the same time will make us blind to understanding what's up if the combination fails).
___
*[docs/RFCS/20220122_cancel_rfc.md, line 280 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuCJQJnEryfBQ4zwtN_:-MuClJxE-kj0Xpm_Nx61:b9qf047) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L280)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

The problem is that from the user perspective, they're cancelling a query (and this is logically an idempotent operation). But because the protocol targets a *session* instead of a query, we have the problem that an attempt to cancel on query can be abused to cancel other queries on the session. 

This RFC proposes a sequence number for cancellation attempts, but it would be ideal to tie the sequencer to the number of attempted queries. That may not be feasible with a light-touch wrapper around existing drivers, but it at least deserves a mention as an alternative. (and if we were making deeper protocol changes there are various ways we could include a per-query cancellation token for free). 

</blockquote></details>

Good point. Will mention in the text.
___
*[docs/RFCS/20220122_cancel_rfc.md, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuCXYtz9m8iloXbUC3C:-MuClOAT4u7a9JlBSqRi:b-yhyuvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L284)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

I question the goal of avoiding TLS (and note that this would be one-way TLS, not mTLS). Using TLS would let us use the "simple protocol" and we wouldn't need to implement the more complex "hmac protocol". I do not believe the cancellation operation is frequent or latency-sensitive enough that we need to avoid the cost of a TLS handshake. (and to the extent that we do care about this latency, TLS 1.3 reduced the handshake from 3 round trips to 1. There's also a 0-RTT "session resumption" mode but it comes with caveats so I'm not sure whether it is safe to use here or not). 
</blockquote></details>

As long as we continue to use off-the-shelf drivers, we can't force them to do one-way TLS...

But point taken, I'll add your argument. Notice how the current RFC does not preclude deploying this in either direction.
___
*[docs/RFCS/20220122_cancel_rfc.md, line 325 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuCV0_P-HVoX3EqYdOA:-MuClb-q8bt_9hN46IHe:b-g34wc9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L325)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary><blockquote>

One potential caveat here is that in TLS-required deployments, StartupMessage is never sent in the clear and it may be rejected by proxies. (Case in point: the proxy we built for CC serverless would need to be modified to pass this message along)
</blockquote></details>

I'll add a note for this. As mentioned above, the proposal does not preclude TLS, it just makes it optional.
___
*[docs/RFCS/20220122_cancel_rfc.md, line 349 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuBrSb944qSClVEJQdI:-MuClgKo1lzX7ck0TBIj:b-ry14hk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L349)):*
> the query might not be cancelled by the customer if someone else consumes the nonce before them

The impl takes care of that by informing the client their nonce is not valid any more and they have to retry.

> If we make nonces only increment on successful cancels this would be prevented but an attacker could determine if their cancel message succeeded, which I think is fine

Ok thanks for this, I wasn't sure. I'll try it the way you say.
___
*[docs/RFCS/20220122_cancel_rfc.md, line 351 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuBsNnd2oUhzb_NPGBm:-MuClnvB3WO-S-WGxGGo:b-yasbr9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L351)):*
<details><summary><i>Previously, kpatron-cockroachlabs wrote…</i></summary><blockquote>

If the nonces for invalid sessionIDs are always 1/2 they still might be able to infer some things from the response (or by sending multiple requests and seeing if it increments).

I don't think we should put too much effort into locking down this path.
</blockquote></details>

If we only increment upon successful authn, then they wouldn't learn any more, is that right?
___
*[docs/RFCS/20220122_cancel_rfc.md, line 454 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuBtNTY-zm8kerzP1Je:-MuCm2tbA8H35WUKk0Gc:bhz47kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L454)):*
<details><summary><i>Previously, kpatron-cockroachlabs wrote…</i></summary><blockquote>

see comment in the other PR. I would argue this should be incremented after every successful attempt.
</blockquote></details>

see discussion above
___
*[docs/RFCS/20220122_cancel_rfc.md, line 457 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuBtXWNCUqmDm2G2cOD:-MuCm4X352sotzO6D3OT:b-xd4d4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L457)):*
<details><summary><i>Previously, kpatron-cockroachlabs wrote…</i></summary><blockquote>

Nit: of the nonce using the shared secret. It's a little odd because in practice we are just hashing the shared secret and nonce but still.
</blockquote></details>

thanks - we can hash the session ID too, I don't think it matters much.

**Review by bdarnell — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75307)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @knz, @kpatron-cockroachlabs, @petermattis, and @rafiss)

___
*[docs/RFCS/20220122_cancel_rfc.md, line 284 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-MuCXYtz9m8iloXbUC3C:-MuCoxUiBgsesNJ84LUh:bd0n77q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a97c2b1b33a9dfb5eeaccaefeabeeed931275db5/docs/RFCS/20220122_cancel_rfc.md#L284)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

As long as we continue to use off-the-shelf drivers, we can't force them to do one-way TLS...

But point taken, I'll add your argument. Notice how the current RFC does not preclude deploying this in either direction.
</blockquote></details>

What I called "one-way TLS" is just normal TLS without a client certificate (as opposed to mTLS or mutual TLS with client certs). That's definitely doable with standard drivers.

**Review by knz — COMMENTED** [review]
I've made the recommended changes, RFAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/75307#-:-MuH3Bbx2VTb8IEYJcqY:b-6pm88r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @bdarnell, @knz, @kpatron-cockroachlabs, @petermattis, and @rafiss)

**Comment by knz** [comment]
@rafiss based on recent discussions, I will mark this RFC as "rejected' and merge the PR. Then you can refer to it from the other/new one.

**Pull request merged**
