### PR TITLE
sql: make deadline errors retryable

### LINKED ISSUE #96336: bench: BenchmarkOrderBy fails with liveness session expired
```
BenchmarkOrderBy/SharedProcessTenantCockroach/count=100000/limit=10
BenchmarkOrderBy/SharedProcessTenantCockroach/count=100000/limit=10/distinct=false
    bench_test.go:849: error executing 'DROP TABLE IF EXISTS bench.sort': pq: liveness session expired 1m48.770406s before transaction
--- FAIL: BenchmarkOrderBy/SharedProcessTenantCockroach/count=100000/limit=10/distinct=false
BenchmarkOrderBy/SharedProcessTenantCockroach/count=100000/limit=10/distinct=true
    bench_test.go:852: error executing 'CREATE TABLE bench.sort (k INT PRIMARY KEY, v INT, w INT)': pq: liveness session expired 1m48.814375s before transaction
    bench_test.go:849: error executing 'DROP TABLE IF EXISTS bench.sort': pq: liveness session expired 1m48.81459s before transaction
--- FAIL: BenchmarkOrderBy/SharedProcessTenantCockroach/count=100000/limit=10/distinct=true
--- FAIL: BenchmarkOrderBy/SharedProcessTenantCockroach/count=100000/limit=10
--- FAIL: BenchmarkOrderBy/SharedProcessTenantCockroach/count=100000
--- FAIL: BenchmarkOrderBy/SharedProcessTenantCockroach
```

Error: 
```
bench_test.go:849: error executing 'DROP TABLE IF EXISTS bench.sort': pq: liveness session expired 1m48.81459s before transaction
```

**Notes**:
The benchmark only fails when running with a low cpu count (or I presume on a slow machine as well), I set it to `-test.cpu 1`.

To Reproduce:
```
./dev bench pkg/bench -f=BenchmarkOrderBy --ignore-cache --bench-time=1s --verbose --stream-output --timeout 10m --test-args="-test.failfast -test.cpu 1"
```

Jira issue: CRDB-24075

### PR DESCRIPTION
**Pull request by ajwerner**
If a transaction gets finds itself with a deadline before its current timestamp, something that can happen when there are schema changes or when the sqlliveness subsystem is unavailable, we ought to retry the transaction. Today, an assertion failure is sent. This is the wrong behavior.

In order to achieve the desired goal, we detect the scenario in MaybeUpdateDeadline and we return an error which implements the appropriate interface to be interpreted as a retry error in the pgwire and sql layers.

This change does a few other little things:

1) It simplies the logic to check whether an error is retriable so that
   all errors which pgwire will treat as client-visible retries are treated
   as retriable internally. In addition, we retain certain additional checks
   for retriable errors the sql layer handles explicitly.
2) It makes sure to reset the sqlliveness session in the descs.Collection
   when restarting transactions. Not doing this, on the one hand, was an
   oversight that meant that if the session turned over internally, then
   restarts wouldn't see it. However, it's not actually a bug today because
   only secondary tenants set the session, and they never acquire a new
   session.

The test utilizes sessions rather than descriptors because the testing knob infrastructure is easier to manipulate.

Fixes: #96336

Backports will deal with #76727

Release note (bug fix): In rare cases involving overload and schema changes, users could sometimes, transiently, see errors of the form "deadline below read timestamp is nonsensical; txn has would have no chance to commit". These errors carried and internal pgcode and could not be retried. This form of error is now classified as a retriable error and will be retried automatically either by the client or internally.

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm_strong:  pretty straightforward and clean

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99760#-:-NRcHIxQ2tGfviSqXa-m:b-e13s4y)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @DrewKimball)

___
*[`pkg/sql/catalog/descs/txn_external_test.go` line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99760#-NRcGzPU5JAAtlGxgOrT:-NRcGzPU5JAAtlGxgOrU:batnq1g) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b90e16bacdbf801a642f168fd4d9d5608969ccc/pkg/sql/catalog/descs/txn_external_test.go#L166)):*
> ```Go
> }
> 
> type fakeSession struct{ exp hlc.Timestamp }
> ```

Would it make sense to lift this into a common package, since we have another fake session implementation inside sql_test

**Review by ajwerner — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99760#-:-NRcZT9uCUvrZXTdQodb:b-814g8k)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball and @fqazi)

___
*[`pkg/sql/catalog/descs/txn_external_test.go` line 166 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/99760#-NRcGzPU5JAAtlGxgOrT:-NRcZQvwBYAyaJOKsm5c:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4b90e16bacdbf801a642f168fd4d9d5608969ccc/pkg/sql/catalog/descs/txn_external_test.go#L166)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Would it make sense to lift this into a common package, since we have another fake session implementation inside sql_test
</blockquote></details>

Done.

**Comment by ajwerner** [comment]
TFTR!

bors r+

**Review by yuzefovich — COMMENTED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99760)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @DrewKimball, and @fqazi)

___
*[`pkg/sql/conn_executor.go` line 3110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99760#-NRdEzAw3qgJgruWi2Zq:-NRdEzAw3qgJgruWi2Zr:b-17crd) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8dc0db45364be087236d4b512448d71a49eca2e/pkg/sql/conn_executor.go#L3110)):*
> ```Go
> 		errors.Is(err, retriableMinTimestampBoundUnsatisfiableError) ||
> 		errors.Is(err, descidgen.ErrDescIDSequenceMigrationInProgress) ||
> 		execinfra.IsDynamicQueryHasNoHomeRegionError(err) ||
> ```

nit: add `pgerror.ClientVisibleRetryError` interface assertions to the errors that are no longer explicitly mentioned in this method.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/99760)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @DrewKimball, @fqazi, and @yuzefovich)

___
*[`pkg/sql/conn_executor.go` line 3110 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/99760#-NRdEzAw3qgJgruWi2Zq:-NRdGAI803AJV2Uy-vLy:bn7ze57) ([raw file](https://github.com/cockroachdb/cockroach/blob/f8dc0db45364be087236d4b512448d71a49eca2e/pkg/sql/conn_executor.go#L3110)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: add `pgerror.ClientVisibleRetryError` interface assertions to the errors that are no longer explicitly mentioned in this method.
</blockquote></details>

https://github.com/cockroachdb/cockroach/blob/736a67e0d36cc545bf74d65db069ee895ff9bea0/pkg/kv/kvpb/errors.go#L701
and then otherwise done.

**Pull request merged**
