### PR TITLE
sql/randgen: disable crazy names in most randomized tests

### PR DESCRIPTION
**Pull request by mgartner**
#### sql/randgen: unify table options

Options for generating random tables have been unified into the
`TableOpt` type. Prior to this commit, options were specified with a
mixture of boolean arguments and the `tableGenerationOptions` type.

Release note: None

#### sql/randgen: add TableOptCrazyNames

The `randgen.TableOptCrazyNames` option has been added, which instructs
`randgen` functions to use the `randident` package to generate table,
column, and partition names with special and interesting characters.

This setting is only used for sqlsmith tests where it is most likely to
catch problems. It not used for other forms of randomized tests because
it makes it more difficult to reduce those test failures.

Epic: None

Release note: None

### CODE REVIEW

**Review by mw5h — APPROVED** [review]
Totally worth it just for the cleanup alone.

> Reviewed 12 of 12 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132106#-:-O8ceQu29_7O9CeYP0K5:btdwmxm)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @azhu-crl, @srosenberg, and @vidit-bhat)

**Review by michae2 — APPROVED** [review]
:lgtm: Thank you!!

> Reviewed 12 of 12 files at r1, 2 of 2 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132106#-:-O8cgVWq4h5YpBqqnxIq:bwy8rtm)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @azhu-crl, @mgartner, @srosenberg, and @vidit-bhat)

___
*[`pkg/sql/randgen/schema.go` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132106#-O8ceuwh8uatB7pei2JR:-O8ceuwh8uatB7pei2JS:bfnisvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/16948e675be2018c0732db05ca536e9b7f64d078/pkg/sql/randgen/schema.go#L115)):*
> ```Go
> 
> func (t TableOpt) IsSet(o TableOpt) bool {
> 	return t&o != 0
> ```

nit: Channeling my [inner Marcus](https://github.com/cockroachdb/cockroach/pull/118931#pullrequestreview-1870386752), I think this would be safer as `t&o == o`. (Which reminds me, I need to merge https://github.com/cockroachdb/cockroach/pull/119035.)

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132106)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @azhu-crl, @michae2, @srosenberg, and @vidit-bhat)

___
*[`pkg/sql/randgen/schema.go` line 115 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132106#-O8ceuwh8uatB7pei2JR:-O8chEr79mKb37A-i2Wt:b-almebs) ([raw file](https://github.com/cockroachdb/cockroach/blob/16948e675be2018c0732db05ca536e9b7f64d078/pkg/sql/randgen/schema.go#L115)):*
<details><summary><i>Previously, michae2 (Michael Erickson) wrote…</i></summary><blockquote>

nit: Channeling my [inner Marcus](https://github.com/cockroachdb/cockroach/pull/118931#pullrequestreview-1870386752), I think this would be safer as `t&o == o`. (Which reminds me, I need to merge https://github.com/cockroachdb/cockroach/pull/119035.)
</blockquote></details>

Ha... While I was writing this I was reminded of that conversation, but had forgotten exacttly what we settled on and couldn't find it. Fixed!

**Pull request merged**
