### PR TITLE
[dnm] [prototype] copy: implement with bulk adder

### PR DESCRIPTION
**Pull request by jordanlewis**
This (very much a not-finished prototype) commit changes the mechanism of COPY to pass the parsed data into
the bulk adder, rather than using batched ordinary inserts. This should
be more efficient than th e current implementation.

It's marked [dnm] because I believe this is unsafe - I think to use the
bulk adder the table must be taken offline.

Perhaps this, plus taking the table offline properly, could be a mode of
operation for COPY, but it probably couldn't be the default unless
Postgres COPY does the same thing, which I cannot quite figure out at
the moment.

### CODE REVIEW

**Comment by dt** [comment]
how does COPY handle collisions / duplicates?

**Comment by jordanlewis** [comment]
In Postgres, COPY seems to fail if an input violates any constraints. I suppose that means this strategy will not even work a little bit, right? :)

**Comment by dt** [comment]
well, you could run checks on every row before sending them to the adder, and take the table offline, and check for an invalidate any FKs, and then do post-ingest validation, which probably means you'd need to make it a job (e.g. if your coordinator dies you want your table to come back online). But that is just IMPORT at that point.

**Comment by otan** [comment]
thanks for writing this up! was less crazy than i thought it'd be (i was going to write something that basically just runs the import command instead)

that said, the offline thing is probably a killer. at the very least, we'd want to define a "OFFLINE" syntax for COPY or a session variable. maybe we'll decide to use it for DMS though. we'll see!

**Pull request closed without merging**
