### PR TITLE
distsql: DISTINCT optimizations, partial orderings

### PR DESCRIPTION
**Pull request by irfansharif**
Ordered columns, the columns the input is already sorted by, can be optionally
specified for possible partial ordering optimizations. If we are processing
`DISTINCT(x, y)` and the input stream is ordered by `x`, we are using `x` as our
group key and our `seen` set at any given time is _only_ the set of all rows with 
the same group key. The `seen` set is reset whenever we find consecutive rows 
differing on a `prefix` comprised of the ordered columns thus avoiding the need 
to store encodings of _all_ rows.

open to suggestions for some of the variable names used here.

Part of #7587, extension to #10034.
cc @RaduBerinde, @andreimatei

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10090)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM

---

Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/distinct.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUTLwrbKwOUQ1l3gUjA:-KUTLwrbKwOUQ1l3gUjB:bfjlka5) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb26c072cdf7fdce49e0d0731e5dd61c25314143/pkg/sql/distsql/distinct.go#L88)):*
> ```Go
> 		}
> 
> 		prefix, suffix, err := d.encode(scratch[0], scratch[1], row)
> ```

i would call it `groupKey` or similar, `prefix` is a bit misleading

---

*[pkg/sql/distsql/distinct.go, line 128 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUTKRnwNDYnFjDsxEi1:-KUTKRnxqv3AQxOf6GJe:b-xncn0s) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb26c072cdf7fdce49e0d0731e5dd61c25314143/pkg/sql/distsql/distinct.go#L128)):*
> ```Go
> }
> 
> func (d *distinct) encode(prefix, encoding []byte, row sqlbase.EncDatumRow) ([]byte, []byte, error) {
> ```

need comments explaining the arguments and return values. you can also name the return values as a documentation thing. Sometimes we use `appendTo` as arg names if that's what we're using them for.

---

*[pkg/sql/distsql/distinct.go, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUTLlfnqqsYYNr4gCYm:-KUTLlfnqqsYYNr4gCYn:b-3u0jq3) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb26c072cdf7fdce49e0d0731e5dd61c25314143/pkg/sql/distsql/distinct.go#L133)):*
> ```Go
> 	// processing DISTINCT(x, y) and the input stream is ordered by x, we are
> 	// using x as our group key (our 'seen' set at any given time is the set of
> 	// all rows with the same group key). This alleviates the need to use x in
> ```

you mean that we could just compare the `EncDatum` values on the `orderedCols` against the last row instead of generating any encoding for `x` right? That would be more efficient and the code might actually be simpler. It would also easily allow us to verify that we are indeed getting the ordering we were promised.

---

*[pkg/sql/distsql/processors.proto, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUTJoVBZl9q9vT2NXtz:-KUTJoVBZl9q9vT2NXu-:b-wo5odo) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb26c072cdf7fdce49e0d0731e5dd61c25314143/pkg/sql/distsql/processors.proto#L137)):*
> ```protobuf
>   // optionally specified for possible optimizations taking advantage of the
>   // partial orderings.
>   repeated uint32 ordered_cols = 2;
> ```

I realize the implementation doesn't care about the actual ordering, but it will always be known when where planning so we should probably just put in an `Ordering`.

The advantage would be that we will be able to add code that asserts that the ordering is as expected, which would be very useful to catch planning bugs.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-:-KUTL4dD2c-jrEeLxsLA:bb6ywmx)*

**Comment by irfansharif** [comment]
Review status: 0 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/distinct.go, line 88 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUTLwrbKwOUQ1l3gUjA:-KUTg6UHOOe27fAUfzRr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb26c072cdf7fdce49e0d0731e5dd61c25314143/pkg/sql/distsql/distinct.go#L88)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> i would call it `groupKey` or similar, `prefix` is a bit misleading
</details>
Done.

---

*[pkg/sql/distsql/distinct.go, line 128 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUTKRnwNDYnFjDsxEi1:-KUTg8_otiEczHysrg4w:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb26c072cdf7fdce49e0d0731e5dd61c25314143/pkg/sql/distsql/distinct.go#L128)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> need comments explaining the arguments and return values. you can also name the return values as a documentation thing. Sometimes we use `appendTo` as arg names if that's what we're using them for.
</details>
Done.

---

*[pkg/sql/distsql/distinct.go, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUTLlfnqqsYYNr4gCYm:-KUTmbSVUf0Te0tNE3BB:bxcqavu) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb26c072cdf7fdce49e0d0731e5dd61c25314143/pkg/sql/distsql/distinct.go#L133)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> you mean that we could just compare the `EncDatum` values on the `orderedCols` against the last row instead of generating any encoding for `x` right? That would be more efficient and the code might actually be simpler. It would also easily allow us to verify that we are indeed getting the ordering we were promised.
</details>
haha, actually i meant *another* optimization where given the we've encoded `x` within our `prefix|groupKey` we don't really need to encode it *again* in our `suffix|encoding` because everything in the current `seen` set will by design share the same `x`.
but to your point about direct comparisons on `EncDatum` values, i see how direct comparisons instead of encoded `[] byte` comparisons is simpler.  Will add this in the next revision.

---

*[pkg/sql/distsql/processors.proto, line 137 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUTJoVBZl9q9vT2NXtz:-KUTmG3sNxn973YEtOrJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb26c072cdf7fdce49e0d0731e5dd61c25314143/pkg/sql/distsql/processors.proto#L137)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I realize the implementation doesn't care about the actual ordering, but it will always be known when where planning so we should probably just put in an `Ordering`.
> 
> The advantage would be that we will be able to add code that asserts that the ordering is as expected, which would be very useful to catch planning bugs.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/distinct.go, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUTLlfnqqsYYNr4gCYm:-KUU9FMyjyvRPp98mNFC:b-5vqysi) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb26c072cdf7fdce49e0d0731e5dd61c25314143/pkg/sql/distsql/distinct.go#L133)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> haha, actually i meant *another* optimization where given the we've encoded `x` within our `prefix|groupKey` we don't really need to encode it *again* in our `suffix|encoding` because everything in the current `seen` set will by design share the same `x`.
> but to your point about direct comparisons on `EncDatum` values, i see how direct comparisons instead of encoded `[] byte` comparisons is simpler.  Will add this in the next revision.
</details>
Ah, I assumed we already did that (by removing the "group key" columns from `d.distinctCols`.

---

*[pkg/sql/distsql/distinct.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUU9zLaif8AhGEaS3X9:-KUU9zLbSIqlGpk9-QUo:b-1pj84u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c59d7805b92828d0ac799eca24e111b2599dc501/pkg/sql/distsql/distinct.go#L118)):*
> ```Go
> 			d.seen[key] = struct{}{}
> 			outRow := d.rowAlloc.AllocRow(len(d.distinctCols))
> 			for i, colIdx := range d.distinctCols {
> ```

we rearrange the columns? why?

---

*[pkg/sql/distsql/processors.proto, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUU9U-Yc-2Cf_CmGV_e:-KUU9U-Yc-2Cf_CmGV_f:bmc707f) ([raw file](https://github.com/cockroachdb/cockroach/blob/c59d7805b92828d0ac799eca24e111b2599dc501/pkg/sql/distsql/processors.proto#L132)):*
> ```protobuf
> 
> message DistinctSpec {
>   repeated uint32 cols = 1;
> ```

What is this? It should be explained. If it's just a list of all the input columns, why do we need it? (we at most need a single number, the number of columns; but we can just read the first row to get that).

If we support doing "distinct" just on a subset of columns, that should be documented (though I don't know if we need that).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090)*

**Comment by irfansharif** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql/distinct.go, line 133 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUTLlfnqqsYYNr4gCYm:-KUXpG5MG7KIEupoDlC5:b-n3gy6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb26c072cdf7fdce49e0d0731e5dd61c25314143/pkg/sql/distsql/distinct.go#L133)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> Ah, I assumed we already did that (by removing the "group key" columns from `d.distinctCols`.
</details>
No we didn't, we 'render' based on `d.distinctCols` which is standard SQL behavior (`DISTINCT(a, b)` returns `a, b` tuples) instead of maintaining a separate `render` list. The new revision contains the optimization I described, waiting for comments on the other discussion first before implementing the direct `EncDatum` comparisons.

---

*[pkg/sql/distsql/distinct.go, line 118 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUU9zLaif8AhGEaS3X9:-KUY7fpQhvStn9N7-U7W:bc8x7hz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c59d7805b92828d0ac799eca24e111b2599dc501/pkg/sql/distsql/distinct.go#L118)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> we rearrange the columns? why?
</details>
We are not. See the other comment below for how `distinctCols` in the current implementation covers only a subset of the columns.

---

*[pkg/sql/distsql/processors.proto, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUU9U-Yc-2Cf_CmGV_e:-KUY6CVgFKnXz4rAI5Wr:bzfs6z7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c59d7805b92828d0ac799eca24e111b2599dc501/pkg/sql/distsql/processors.proto#L132)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> What is this? It should be explained. If it's just a list of all the input columns, why do we need it? (we at most need a single number, the number of columns; but we can just read the first row to get that).
> 
> If we support doing "distinct" just on a subset of columns, that should be documented (though I don't know if we need that).
</details>
The current implementation here is doing `DISTINCT` on a set of columns, see `distinct_test.go` where the input stream rows are comprised of more columns than `DISTINCT` operates on. I made this decision partly because the intermediary step to filter out the remaining columns seemed redundant, though I see in hindsight this is partly what `PROGRAM`/`EVALUATOR` was intended for. no strong opinions here, will remove if thought better to remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/processors.proto, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUU9U-Yc-2Cf_CmGV_e:-KUYDx0WezmyJzI6GU_1:b-n9na11) ([raw file](https://github.com/cockroachdb/cockroach/blob/c59d7805b92828d0ac799eca24e111b2599dc501/pkg/sql/distsql/processors.proto#L132)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> The current implementation here is doing `DISTINCT` on a set of columns, see `distinct_test.go` where the input stream rows are comprised of more columns than `DISTINCT` operates on. I made this decision partly because the intermediary step to filter out the remaining columns seemed redundant, though I see in hindsight this is partly what `PROGRAM`/`EVALUATOR` was intended for. no strong opinions here, will remove if thought better to remove.
</details>
I see. As a general rule, we want to cut out unneded columns as soon as possible to avoid sending them through streams unnecessarily. Most processors already support specifying `output_columns`, and indeed we can also cut them with `Evaluator` (though it shouldn't be necessary, at least not usually). So maybe we want to support `output_columns` (and perhaps a filter expression).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090)*

**Comment by irfansharif** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/processors.proto, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUU9U-Yc-2Cf_CmGV_e:-KUYGPkHYQtdwjubeTwV:b-vsann2) ([raw file](https://github.com/cockroachdb/cockroach/blob/c59d7805b92828d0ac799eca24e111b2599dc501/pkg/sql/distsql/processors.proto#L132)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> I see. As a general rule, we want to cut out unneded columns as soon as possible to avoid sending them through streams unnecessarily. Most processors already support specifying `output_columns`, and indeed we can also cut them with `Evaluator` (though it shouldn't be necessary, at least not usually). So maybe we want to support `output_columns` (and perhaps a filter expression).
</details>
I think I like the 'the processor will get no more than it needs' idea better, certainly makes implementation of `DISTINCT` here cleaner. I've seen the `output_filter` mentioned in passing in the RFC to be applied per row, perhaps explicit mention/implementation of the `output_columns` will be a good idea. Changing this now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090)*

**Comment by irfansharif** [comment]
Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[pkg/sql/distsql/processors.proto, line 132 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUU9U-Yc-2Cf_CmGV_e:-KUYlu9cwffo1GEyhHBU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c59d7805b92828d0ac799eca24e111b2599dc501/pkg/sql/distsql/processors.proto#L132)):*
<details><summary><i>Previously, irfansharif (irfan sharif) wrote…</i></summary>
> I think I like the 'the processor will get no more than it needs' idea better, certainly makes implementation of `DISTINCT` here cleaner. I've seen the `output_filter` mentioned in passing in the RFC to be applied per row, perhaps explicit mention/implementation of the `output_columns` will be a good idea. Changing this now.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090)*

**Comment by RaduBerinde** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/distsql/distinct.go, line 127 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUrGRXXgR7LFX63XWcd:-KUrGRXXgR7LFX63XWce:bn3msx1) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d7202bcac2f2783332fd2ef8b0f14b0f51e4c56/pkg/sql/distsql/distinct.go#L127)):*
> ```Go
> }
> 
> // encode returns the encoding of the row, this is then is the key we use in our
> ```

appends the encoding of non-ordered columns, which we use as a key in our `seen` set.

---

*[pkg/sql/distsql/distinct.go, line 129 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUrGm0BbgpacQm1Ztbe:-KUrGm0BbgpacQm1Ztbf:ba0gcwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d7202bcac2f2783332fd2ef8b0f14b0f51e4c56/pkg/sql/distsql/distinct.go#L129)):*
> ```Go
> // encode returns the encoding of the row, this is then is the key we use in our
> // 'seen' set.
> func (d *distinct) encode(encoding []byte, row sqlbase.EncDatumRow) ([]byte, error) {
> ```

rename `encoding` to `appendTo`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-:-KUrH-KCCwd_1ehRdKVI:bnfp4nl)*

**Comment by irfansharif** [comment]
TFTR, pulling in now.

---

Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/distsql/distinct.go, line 127 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUrGRXXgR7LFX63XWcd:-KUrIgPdtJ1dGmXUXUhD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d7202bcac2f2783332fd2ef8b0f14b0f51e4c56/pkg/sql/distsql/distinct.go#L127)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> appends the encoding of non-ordered columns, which we use as a key in our `seen` set.
</details>
Done.

---

*[pkg/sql/distsql/distinct.go, line 129 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-KUrGm0BbgpacQm1Ztbe:-KUrIi33XhY2WH_wTycF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6d7202bcac2f2783332fd2ef8b0f14b0f51e4c56/pkg/sql/distsql/distinct.go#L129)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> rename `encoding` to `appendTo`
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10090#-:-KUrIkKF2HfDEc8rZZWO:b6z6o1z)*

**Pull request merged**
