### PR TITLE
Run each transaction correctness test 15 times

### PR DESCRIPTION
**Pull request by tamird**
@spencerkimball this causes the failures to reproduce very reliably. We probably don't want to merge this, but this change should be helpful in debugging the `TestTxnDBLostUpdateAnomaly` failure. On my machine, it almost always fails with the invocation `make test PKG=./kv TESTTIMEOUT=5m CPUS=4,4`.

### CODE REVIEW

**Comment by tschottdorf** [comment]
FWIW, I can't reproduce this on my machine (at least haven't been able so far). I think sporadic failures are expected when limiting to three retries arbitrarily and on slow machines, though.

**Comment by tamird** [comment]
I think your machine might be faster than mine, so you'll need to ratchet these changes so the concurrency is even higher. Also helps to increase the number of runs e.g. `make test PKG=./kv TESTTIMEOUT=5m CPUS=4,4,4,4 TESTS=TestTxnDBLostUpdateAnomaly`

**Comment by tamird** [comment]
Actually you probably want `CPUS=8,8,...` on your machine.

**Comment by tschottdorf** [comment]
I've seen it on CircleCI, and as discussed there's every reason that we should be seeing these. The retry limit in those tests is arbitrary.

**Comment by tamird** [comment]
It doesn't seem like any of these failing transactions should ever need more than 2 attempts; if the hypothesis is that they are encountering old write intents, I would expect the first attempt to synchronously resolve them, and the second attempt to go through. What am I missing?

**Comment by tschottdorf** [comment]
I don't see where we would try to resolve them synchronously, the relevant callsite is `store.go:~1259`:
`err = s.resolveWriteIntentError(ctx, wiErr, rng, args, pushType, false /* wait */)`
and then, later
`waitForResolve := wait && i == len(wiErr.Intents)-1`
(not sure what the second part is for, but basically we don't resolve intents synchronously).

**Comment by tschottdorf** [comment]
should probably loop in @spencerkimball because doing that synchronously sometimes seems to make sense.

**Comment by tamird** [comment]
discussion has moved to #1555

**Pull request closed without merging**
