### PR TITLE
sql: enable auto-rehoming of REGIONAL BY ROW tables

### PR DESCRIPTION
**Pull request by pawalt**
Previously, REGIONAL BY ROW tables never had their rows rehomed unless
the user manually specified to do so. This PR adds a cluster setting,
`sql.defaults.auto_rehoming.enabled` and a session setting,
`enable_auto_rehoming` that will rehoming rows to the user's gateway
region on UPDATE.

Release justification: low-risk change on existing feature, hidden
behind a cluster setting.
Release note (sql change): The cluster setting
`sql.defaults.auto_rehoming.enabled` and session setting
`enable_auto_rehoming` were added to enable auto-rehoming on UPDATE for
REGIONAL BY ROW tables.

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
My reading of this session variable/setting is that it enables or disables whether or not the table picks up this `ON UPDATE` expression at creation time. My sense is that that is not quite the knob folks want, or, at least, not quite the only knob folks want. My sense is that the knob that folks will often want is the ability to turn off rehoming for tables which currently have it active. That would mean that the execution of the expression should take this setting into account. What do you think?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-:-Mi1h-M804IpKdlv-HBF:b-ltmni0)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

**Review by arulajmani — CHANGES_REQUESTED** [review]
> My sense is that that is not quite the knob folks want, or, at least, not quite the only knob folks want. 

I agree this isn't the final incarnation of auto-rehoming and this "all or nothing decide at creation time" might not be the behavior most folks want. Something I've heard mentioned before, as a north star, is that we only want to rehome rows if some % of new updates are coming from a different (non-home) region within a time window. That seems like a much harder problem, which is why we decided to scope it down to what you see here (and hide it behind a cluster setting). 
 
> My sense is that the knob that folks will often want is the ability to turn off rehoming for tables which currently have it active. That would mean that the execution of the expression should take this setting into account.

In Peyton's first WIP implementation of this feature he had something similar to this. We wanted to refrain from having to special case regional by row tables in the optimizer and keep it as general as possible. This is what motivated the whole `ON UPDATE` RFC! Here's the link to the original discussion: https://github.com/cockroachdb/cockroach/pull/66604#pullrequestreview-688564136

When you say make execution aware of this session setting did you have something similar to Peyton's WIP PR in mind? Or is there a way to generate an expression here that is setting aware? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-:-Mi1oz1x3zIzy2-IcBdH:bvnhq0z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi1nVFtEyx5mwxf2tbs:-Mi1nVFtEyx5mwxf2tbt:bgjz8qt) ([raw file](https://github.com/cockroachdb/cockroach/blob/d416cd18a20b8b16c28004380ac04b0999cef4cc/pkg/ccl/multiregionccl/auto_rehoming_test.go#L8)):*
> ```Go
> //
> //     https://github.com/cockroachdb/cockroach/blob/master/licenses/CCL.txt
> ```

Let's add UPSERT tests for this as well? 
___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi1ko8n6KvHIR5UFTyJ:-Mi1ko8n6KvHIR5UFTyK:bwuqnxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d416cd18a20b8b16c28004380ac04b0999cef4cc/pkg/ccl/multiregionccl/auto_rehoming_test.go#L81)):*
> ```Go
> }
> 
> func TestAutoHomingWithAlteredTable(t *testing.T) {
> ```

This test looks awfully similar to the one above. The only thing that is different is the setup. Let's make this a single "test table style" test? 

Something like: 

testCases := []struct{
name string
setup string
} {
...
}

Edit: I think you can collapse all 4 tests into a single one. Just add a `rehomedRegion` field to your struct and assert on that. 
___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi1mMBDAEdTnuOzxfb_:-Mi1mMBDAEdTnuOzxfba:bvjd07z) ([raw file](https://github.com/cockroachdb/cockroach/blob/d416cd18a20b8b16c28004380ac04b0999cef4cc/pkg/ccl/multiregionccl/auto_rehoming_test.go#L226)):*
> ```Go
> 
> 	sql0.Exec(t, `
> CREATE DATABASE test PRIMARY REGION "us-east1" REGIONS "us-east2";
> ```

When you change this into a test table test, you might want to make the primary region "us-east2" here in the setup instead. That way, when updating from "us-east3" fails, you'll be able to assert that the row is instead homed in "us-east2" (as opposed to "us-east1", where it starts off). 
___
*[pkg/sql/create_table.go, line 2799 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi1oG8tEaSwm2cL25AR:-Mi1oG8tEaSwm2cL25AS:b-1gg9t9) ([raw file](https://github.com/cockroachdb/cockroach/blob/d416cd18a20b8b16c28004380ac04b0999cef4cc/pkg/sql/create_table.go#L2799)):*
> ```Go
> }
> 
> func regionalByRowOnUpdateExpr(evalCtx *tree.EvalContext, enumOid oid.Oid) tree.Expr {
> ```

nit: s/regionalByRowOnUpdateExpr/maybeRegionalByRowOnUpdateExpr/g 

This could use a comment explaining the nature of "maybe" -- it'll only return one if the cluster version for `ON UPDATE` has been finalized and the session variable dictates as such. 

Speaking of version gating, let's add tests to ensure ALTER/CREATE tables with the cluster setting turned on but the version not finalized don't create this `ON UPDATE` expression. You should be able to check this by looking at the `SHOW CREATE` statements.

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pawalt)

___
*[pkg/sql/create_table.go, line 2790 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi1tnI72Ix8088UXwGd:-Mi1tnI72Ix8088UXwGe:b-8553wb) ([raw file](https://github.com/cockroachdb/cockroach/blob/d416cd18a20b8b16c28004380ac04b0999cef4cc/pkg/sql/create_table.go#L2790)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 
> 			Func: tree.WrapFunction(builtins.DefaultToDatabasePrimaryRegionBuiltinName),
> 			Exprs: []tree.Expr{
> 				&tree.FuncExpr{
> 					Func: tree.WrapFunction(builtins.GatewayRegionBuiltinName),
> 				},
> 			},
> ```
</details>

My suggestion is that we add a new builtin that takes the current value and then can look at the setting and decide whether it wants to return gateway region or the existing region. It also gives us flexibility to improve the behavior over time at very little cost.

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 8 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi1nVFtEyx5mwxf2tbs:-Mi2WSzF8DndkjHNSBbf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d416cd18a20b8b16c28004380ac04b0999cef4cc/pkg/ccl/multiregionccl/auto_rehoming_test.go#L8)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's add UPSERT tests for this as well? 
</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 81 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi1ko8n6KvHIR5UFTyJ:-Mi2LKa-BL7nX2lIb3nE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/d416cd18a20b8b16c28004380ac04b0999cef4cc/pkg/ccl/multiregionccl/auto_rehoming_test.go#L81)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This test looks awfully similar to the one above. The only thing that is different is the setup. Let's make this a single "test table style" test? 

Something like: 

testCases := []struct{
name string
setup string
} {
...
}

Edit: I think you can collapse all 4 tests into a single one. Just add a `rehomedRegion` field to your struct and assert on that. 

</blockquote></details>

Done.
___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 226 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi1mMBDAEdTnuOzxfb_:-Mi2LUN-A5CMermyrT-t:bngpynu) ([raw file](https://github.com/cockroachdb/cockroach/blob/d416cd18a20b8b16c28004380ac04b0999cef4cc/pkg/ccl/multiregionccl/auto_rehoming_test.go#L226)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

When you change this into a test table test, you might want to make the primary region "us-east2" here in the setup instead. That way, when updating from "us-east3" fails, you'll be able to assert that the row is instead homed in "us-east2" (as opposed to "us-east1", where it starts off). 
</blockquote></details>

I think `us-east1` makes more sense since we want to rehome to us-east2 and then see that if we update again, it gets sent to us-east1. If the primary region was `us-east2`, we'd see no change in the final update.
___
*[pkg/sql/create_table.go, line 2799 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi1oG8tEaSwm2cL25AR:-Mi2WN607hAyVkQTzVmX:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/d416cd18a20b8b16c28004380ac04b0999cef4cc/pkg/sql/create_table.go#L2799)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: s/regionalByRowOnUpdateExpr/maybeRegionalByRowOnUpdateExpr/g 

This could use a comment explaining the nature of "maybe" -- it'll only return one if the cluster version for `ON UPDATE` has been finalized and the session variable dictates as such. 

Speaking of version gating, let's add tests to ensure ALTER/CREATE tables with the cluster setting turned on but the version not finalized don't create this `ON UPDATE` expression. You should be able to check this by looking at the `SHOW CREATE` statements. 
</blockquote></details>

Done

**Review by arulajmani — CHANGES_REQUESTED** [review]
Mostly looks good to me now. Few comments around your tests. 

Separately, can we file that issue to add a new session/cluster setting pair, consult it, and return a sentinel error if the session setting dictates that we shouldn't be rehoming? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-:-Mi2plkP0tRwX1x4wduk:bh50e2y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 31 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi2mJIT6_VAe4Lu1JXu:-Mi2mJIT6_VAe4Lu1JXv:b-qd3oth) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a30820e3fda666e51d3ae48ff363f75f96ddac6/pkg/ccl/multiregionccl/auto_rehoming_test.go#L31)):*
> ```Go
> 	}{
> 		{
> 			"auto homing",
> ```

nit: here, and below, add the field name before the value?
___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi2mqbpDNBs2u2vQehI:-Mi2mqbpDNBs2u2vQehJ:b7hrzsy) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a30820e3fda666e51d3ae48ff363f75f96ddac6/pkg/ccl/multiregionccl/auto_rehoming_test.go#L98)):*
> ```Go
> 
> 			row := sql0.QueryRow(t, `
> SELECT p, s, crdb_region FROM rbr WHERE p = 1`)
> ```

nit: here, and below, you can just select the `crdb_region` column. You're not using `p` and `s`, are you?
___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi2pDng4wZC-9ZwFEpj:-Mi2pDng4wZC-9ZwFEpk:b-rqmx61) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a30820e3fda666e51d3ae48ff363f75f96ddac6/pkg/ccl/multiregionccl/auto_rehoming_test.go#L101)):*
> ```Go
> 			row.Scan(&p, &s, &crdbRegion)
> 
> 			if crdbRegion != test.expectedLocalities[0] {
> ```

I don't completely follow why we have this expectedLocalities array which queries from 3 different SQL gateways. Does it buy us anything interesting in some case? If not, can we just pick one gateway and express our expected localities that way? 
___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi2m1Zs6CW91dYmLlwD:-Mi2m1Zs6CW91dYmLlwE:b1wsii8) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a30820e3fda666e51d3ae48ff363f75f96ddac6/pkg/ccl/multiregionccl/auto_rehoming_test.go#L157)):*
> ```Go
> }
> 
> func TestRehomingVersionGating(t *testing.T) {
> ```

Can we put this test in `pkg/ccl/logictestccl/testdata/logic_test/as_of_mixed` instead? It'll make the whole `SHOW CREATE TABLE` assert much easier!

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 101 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi2pDng4wZC-9ZwFEpj:-Mi35oSG0T_b34jdd3BS:b8xluct) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a30820e3fda666e51d3ae48ff363f75f96ddac6/pkg/ccl/multiregionccl/auto_rehoming_test.go#L101)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't completely follow why we have this expectedLocalities array which queries from 3 different SQL gateways. Does it buy us anything interesting in some case? If not, can we just pick one gateway and express our expected localities that way? 
</blockquote></details>

Nope. Moved to one gateway,
___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 157 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi2m1Zs6CW91dYmLlwD:-Mi34p9M-rHkVY8GpsJ5:b-5br3rn) ([raw file](https://github.com/cockroachdb/cockroach/blob/0a30820e3fda666e51d3ae48ff363f75f96ddac6/pkg/ccl/multiregionccl/auto_rehoming_test.go#L157)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Can we put this test in `pkg/ccl/logictestccl/testdata/logic_test/as_of_mixed` instead? It'll make the whole `SHOW CREATE TABLE` assert much easier! 
</blockquote></details>

Added TODO for a later PR.

**Review by ajwerner — COMMENTED** [review]
My immediate request with this change is to throw the word `experimental` into `sql.defaults.auto_rehoming.enabled` and `enable_auto_rehoming`. It doesn't cost us much and it is going to save us a lot of explaining. I think this change is amazingly cool, rehoming has long been a dream and now it's a reality! However, this implementation isn't the end of the road for this functionality. I don't think we're ready to give this feature a big press push that the end state of this work deserves. While people might clamor for `experimental` features to have that label removed, they do tend to approach such features with caution.

I hope we can do some fast follow-on work to give the user even more control, but I don't think that that needs to block this from going in. 

> Reviewed 1 of 13 files at r1, 1 of 4 files at r3, 2 of 9 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-:-Mi3JFiM3axmljYavYRw:bqbqrmm)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

**Review by arulajmani — COMMENTED** [review]
The test changes look good to me. Let's put in the `experimental` in both the session and cluster setting and merge this in after @pawalt? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-:-Mi3GspO3Ocp5rJ2Nbmo:b-uxo4ro)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 136 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3EJhC8e0-3a-QdizR:-Mi3EJhC8e0-3a-QdizS:b-xhhrrt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c921bd1c0cf77810b29f25d40cbd538d6882149/pkg/ccl/multiregionccl/auto_rehoming_test.go#L136)):*
> ```Go
> }
> 
> // TODO(arulajmani): move this to a multiregion logictest
> ```

nit: full stop

**Review by arulajmani — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @pawalt)

___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 137 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3YuLMCk4T3LpCtGkJ:-Mi3YuLMCk4T3LpCtGkK:b-ekeyfk) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c921bd1c0cf77810b29f25d40cbd538d6882149/pkg/ccl/multiregionccl/auto_rehoming_test.go#L137)):*
> ```Go
> 
> // TODO(arulajmani): move this to a multiregion logictest
> func TestRehomingVersionGating(t *testing.T) {
> ```

CI is complaining that you don't have a `defer leaktest.AfterTest` here.

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @pawalt)

___
*[pkg/ccl/multiregionccl/auto_rehoming_test.go, line 137 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3YuLMCk4T3LpCtGkJ:-Mi3doLR2UBWcCfXt8mC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c921bd1c0cf77810b29f25d40cbd538d6882149/pkg/ccl/multiregionccl/auto_rehoming_test.go#L137)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

CI is complaining that you don't have a `defer leaktest.AfterTest` here. 
</blockquote></details>

Done.

**Review by arulajmani — APPROVED** [review]
Looks like you need to regenerate some files and rewrite a couple of logic tests, but otherwise this is good to go. Great job tying together the work you did previously into this feature! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-:-Mi3iOIS2Cru2VcGB0vw:bp2mfk)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner, @arulajmani, and @pawalt)

___
*[-- commits, line 6 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3j52R5a7o0mjVamHN):*
Update with the new name (here, and below)
___
*[docs/generated/settings/settings.html, line 82 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3hq0HC2aSlnzbhsCh:-Mi3hq0HC2aSlnzbhsCi:b-b7kjtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fd90eb0a53cd5d38b0e337836e083a9eeff27c1/docs/generated/settings/settings.html#L82)):*
> ```HTML
> <tr><td><code>sql.cross_db_sequence_owners.enabled</code></td><td>boolean</td><td><code>false</code></td><td>if true, creating sequences owned by tables from other databases is allowed</td></tr>
> <tr><td><code>sql.cross_db_views.enabled</code></td><td>boolean</td><td><code>false</code></td><td>if true, creating views that refer to other databases is allowed</td></tr>
> <tr><td><code>sql.defaults.auto_rehoming.enabled</code></td><td>boolean</td><td><code>false</code></td><td>default value for enable_auto_rehoming; allows for rows in REGIONAL BY ROW tables to be auto-rehomed on UPDATE</td></tr>
> ```

This'll need to be regenerated. 
___
*[docs/generated/settings/settings-for-tenants.txt, line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3hxqMAFdRdtAWm_Zz:-Mi3hxqMAFdRdtAWm__-:b-p2h929) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fd90eb0a53cd5d38b0e337836e083a9eeff27c1/docs/generated/settings/settings-for-tenants.txt#L78)):*
> ```help
> sql.cross_db_sequence_owners.enabled	boolean	false	if true, creating sequences owned by tables from other databases is allowed
> sql.cross_db_views.enabled	boolean	false	if true, creating views that refer to other databases is allowed
> sql.defaults.auto_rehoming.enabled	boolean	false	default value for enable_auto_rehoming; allows for rows in REGIONAL BY ROW tables to be auto-rehomed on UPDATE
> ```

regenerate. 
___
*[pkg/sql/logictest/testdata/logic_test/information_schema, line 4578 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3iA-g-fbiOcrrYR56:-Mi3iA-g-fbiOcrrYR57:b-ych3rm) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fd90eb0a53cd5d38b0e337836e083a9eeff27c1/pkg/sql/logictest/testdata/logic_test/information_schema#L4578)):*
> ```
> disallow_full_table_scans                              off
> distsql_workmem                                        64 MiB
> enable_auto_rehoming                                   off
> ```

This needs a rewrite? 
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 4059 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3iBSY2Hh9r6wd2e-r:-Mi3iBSY2Hh9r6wd2e-s:bbvl78r) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fd90eb0a53cd5d38b0e337836e083a9eeff27c1/pkg/sql/logictest/testdata/logic_test/pg_catalog#L4059)):*
> ```
> distsql                                                NULL    NULL     NULL     NULL        NULL
> distsql_workmem                                        NULL    NULL     NULL     NULL        NULL
> enable_auto_rehoming                                   NULL    NULL     NULL     NULL        NULL
> ```

Same here, this needs a rewrite too

**Review by pawalt — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69381)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner, @arulajmani, and @pawalt)

___
*[-- commits, line 6 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3j52R5a7o0mjVamHN):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Update with the new name (here, and below)
</blockquote></details>

Done.
___
*[docs/generated/settings/settings.html, line 82 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3hq0HC2aSlnzbhsCh:-Mi4IC0fA2DtvA4W_ltE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fd90eb0a53cd5d38b0e337836e083a9eeff27c1/docs/generated/settings/settings.html#L82)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This'll need to be regenerated. 
</blockquote></details>

Done.
___
*[docs/generated/settings/settings-for-tenants.txt, line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3hxqMAFdRdtAWm_Zz:-Mi4ICes6g1Y7i4PfzoZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fd90eb0a53cd5d38b0e337836e083a9eeff27c1/docs/generated/settings/settings-for-tenants.txt#L78)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

regenerate. 
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/information_schema, line 4578 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3iA-g-fbiOcrrYR56:-Mi4Hvds7zlPkmPrb9Ec:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fd90eb0a53cd5d38b0e337836e083a9eeff27c1/pkg/sql/logictest/testdata/logic_test/information_schema#L4578)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This needs a rewrite? 
</blockquote></details>

Done.
___
*[pkg/sql/logictest/testdata/logic_test/pg_catalog, line 4059 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/69381#-Mi3iBSY2Hh9r6wd2e-r:-Mi4Hw_ODVF2pHK-jWfN:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/6fd90eb0a53cd5d38b0e337836e083a9eeff27c1/pkg/sql/logictest/testdata/logic_test/pg_catalog#L4059)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Same here, this needs a rewrite too 
</blockquote></details>

Done.

**Pull request merged**
