### PR TITLE
roachprod: support --secure flag for start-tenant

### PR DESCRIPTION
**Pull request by stevendanna**
The in-development tenant streaming features require a secure tenant
to test them properly.

This change adds support for the --secure flag when starting a
tenant. When passed, we use the host cluster to generate tenant-client
certificates and distribute them to the tenant cluster, along with the
CA and previously created client certificates.

For simplicity, we've stuck with using a single CA for all certificate
creation.

Release note: None

### CODE REVIEW

**Review by rimadeodhar — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82248)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @stevendanna)

___
*[`pkg/roachprod/install/cluster_synced.go` line 1124 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82248#-N3eiDaQEjoxuTrWCkfT:-N3eiDaQEjoxuTrWCkfU:b5o4rre) ([raw file](https://github.com/cockroachdb/cockroach/blob/f50a04a92bf74b0088cc6baf113a96fa5a5d67db/pkg/roachprod/install/cluster_synced.go#L1124)):*
> ```Go
> mkdir -p tenant-certs/certs
> cp certs/ca.crt tenant-certs/certs/
> cp certs/client.* tenant-certs/certs/
> ```

This will not work as expected with the new incoming code around tenant scoped certificates i.e. after this PR - https://github.com/cockroachdb/cockroach/pull/79065 merges. 
Instead of copying the client certificates as is, you will need to recreate these certificates by adding a tenant scope with the specific tenant IDs. The CLI changes to add tenant scopes have already been merged so you should be able to update your PR to add a tenant scope along the lines of what is already being done for roachtests: https://github.com/cockroachdb/cockroach/blob/fd26d19fe0d2cf7e1bbd1655873e6047eb11d7eb/pkg/cmd/roachtest/tests/multitenant_utils.go#L72.

**Comment by stevendanna** [comment]
@rimadeodhar Thanks, updated with the version check. PTAL.

**Review by knz — APPROVED** [review]
:lgtm: but also let's get a look from test-eng.

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82248#-:-N4gpBjI36h2FA_DJgik:bd41f2h)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @srosenberg and @stevendanna)

**Review by rimadeodhar — APPROVED** [review]
The certs code :lgtm: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82248#-:-N4hGRvR1LJcAevDsaY0:bmwp5vq)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @srosenberg)

**Pull request merged**
