### PR TITLE
sql: disallow SELECT with no targets

### LINKED ISSUE #5833: sql: bad query puts connection in invalid state
`master` at time of writing, with standard `(id, balance)` bank table.

```
root@:26257> set database = bank;
SET
root@:26257> select * from (select balance from accounts where id = 3 union values(0)) as f;
+---------+
| balance |
+---------+
|       0 |
+---------+
root@:26257> select from (select balance from accounts where id = 3 union values(0)) as f;
pq: unexpected DataRow in simple query execution
root@:26257> select * from (select balance from accounts where id = 3 union values(0)) as f;
driver: bad connection
root@:26257>
```

I just checked and `select from accounts` already causes the same behavior. Continuing after `bad connection` works again, but the connection loses its database setting.

### PR DESCRIPTION
**Pull request by RaduBerinde**
We currently allow select statements with no targets (`SELECT FROM t`) but the
result throws off the pg client. This is an invalid statement (I verified via
http://sqlzoo.net that popular engines error out on it).

Updating the sql syntax to always require SELECT targets.

Fixes #5833

Note: this diff is on top of PR #5838

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5842)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/testdata/select, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5842#-KEWqRunEWrhEXTAgz6r:-KEWqRuoZIplym0EERj1:221029165) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c510d70d93116d9deb3e68de0be21c5fe0b90d3/sql/testdata/select#L20)):*
Seems reasonable to require at least one target, and yet postgres doesn't:

```
pmattis=# select from (values (1)) as foo;
--
(1 row)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5842)*

**Comment by RaduBerinde** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/testdata/select, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5842#-KEWqRunEWrhEXTAgz6r:-KEWshJFerJh3JRKAWmh:1953442679) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c510d70d93116d9deb3e68de0be21c5fe0b90d3/sql/testdata/select#L20)):*
For me that query behaves very weird (psql opens up a pager with the result, unlike other queries). When I tried it via sqlzoo.net (PostgreSQL engine), I got `ERROR: syntax error at or near "FROM" LINE 1: SELECT FROM world ^`
Maybe it depends on the version?
The other engines I tried through that site (MySQL, Oracle, SQL Server) all errored out.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5842)*

**Comment by petermattis** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/testdata/select, line 20 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5842#-KEWqRunEWrhEXTAgz6r:-KEWzCqU_SgpyEfyh0_J:-2073289843) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c510d70d93116d9deb3e68de0be21c5fe0b90d3/sql/testdata/select#L20)):*
I'm running postgres 9.4.5. Guess I'm fine with removing this regardless. Anyone else have opinions about this? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/5842)*

**Comment by bdarnell** [comment]
I'm fine with removing this, although I have a vague memory of running into this somehow when I was first working on pgwire. (I was looking for a way to generate a zero-column result set for some reason).

**Comment by petermattis** [comment]
LGTM. We can always add this support back if necessary.

**Comment by RaduBerinde** [comment]
Merged in PR #5859

**Pull request closed without merging**
