### PR TITLE
sql: any "not-null" filters should be trimmed according to non-null…

### LINKED ISSUE #20237: sql: There should not be a "NOT NULL" filter on "NOT NULL" columns in optimized plan
**BUG REPORT**

1. 
```sql
create table t2 (id int not null, num int);
```
2.
```sql
explain(exprs,metadata) select * from t2 where id is not null;
```
```
+-------+--------+----------+----------------+----------------------------------+-----------------------------------+
| Level |  Type  |  Field   |  Description   |             Columns              |             Ordering              |
+-------+--------+----------+----------------+----------------------------------+-----------------------------------+
|     0 | render |          |                | (id, num)                        | id!=NULL                          |
|     0 |        | render 0 | id             |                                  |                                   |
|     0 |        | render 1 | num            |                                  |                                   |
|     1 | scan   |          |                | (id, num, rowid[hidden,omitted]) | id!=NULL; rowid!=NULL; key(rowid) |
|     1 |        | table    | t2@primary     |                                  |                                   |
|     1 |        | spans    | ALL            |                                  |                                   |
|     1 |        | filter   | id IS NOT NULL |                                  |                                   |
+-------+--------+----------+----------------+----------------------------------+-----------------------------------+
```

I don't think the filter should be here because "id" has been defined "NOT NULL".

### PR DESCRIPTION
**Pull request by sydnever**
Fixes #20237 
Sorry, I deleted my remote branch carelessly. So I have to make a new pull request. I wrote other infomation in my comment of codes.

### CODE REVIEW

**Comment by knz** [comment]
Thanks @sydnever for following up.

@RaduBerinde please have a look and suggest how this code can be best improved. the iterative call to `mergeConj` looks suspicious.

**Comment by knz** [comment]
@sydnever 

1) the PR description should be more clearly formatted -- use "Fixes #NNNN." not just "#NNNN". Also indicate in the PR message what the change is doing.

2) extend the commit message with an indication of the release notes (see `CONTRIBUTING.md` for information about how to format release notes)

**Comment by RaduBerinde** [comment]
Looks good, modulo some comments.

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/opt_index_selection.go, line 132 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20436#-L-Y_imh9uIf_ZmR5pf_:-L-Y_imh9uIf_ZmR5pfa:b-x6xzkm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c181ae0b47ac7ae4a21debda17531d360d90f094/pkg/sql/opt_index_selection.go#L132)):*
> ```Go
> 		// possibly overlapping ranges.
> 
> 		// issue#20237
> ```

Don't leave issue numbers in the code if they're about to be closed.

---

*[pkg/sql/opt_index_selection.go, line 275 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20436#-L-Y_n1pRLkMBKqQpXaM:-L-Y_n1pRLkMBKqQpXaN:bzgp074) ([raw file](https://github.com/cockroachdb/cockroach/blob/c181ae0b47ac7ae4a21debda17531d360d90f094/pkg/sql/opt_index_selection.go#L275)):*
> ```Go
> 
> // #20237
> // any "not-null" filters should be trimmed according to non-nullable columns
> ```

// Removes any unnecessary IS NOT NULL filters on non-nullable columns.

This function could be implemented as a method on scanNode and it could set s.filter directly.

---

*[pkg/sql/opt_index_selection.go, line 283 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20436#-L-Y_uKi98_rEjYaRbWp:-L-Y_uKi98_rEjYaRbWq:b-1luu56) ([raw file](https://github.com/cockroachdb/cockroach/blob/c181ae0b47ac7ae4a21debda17531d360d90f094/pkg/sql/opt_index_selection.go#L283)):*
> ```Go
> 			c.Operator == tree.IsNot && c.Right == tree.DNull {
> 			if ok, idx := getColVarIdx(c.Left); ok {
> 				// The reason I(@sydnever) don't use s.props.notNullCols here
> ```

// TODO(radu): we don't use props.notNullCols because those get initialized later.
// We should compute them earlier and generalize this optimization to work on
// any filterNode.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20436#-:-L-YaVuAbub3_uWhz2UH:b-x3un62)*

**Comment by knz** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20436)*

**Comment by knz** [comment]
@sydnever thank you!

**Pull request merged**
