### PR TITLE
storage: update output for allocator_test's Example_rebalancing

### PR DESCRIPTION
**Pull request by BramGruneir**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10333)

### CODE REVIEW

**Comment by tamird** [comment]
I know you're just kicking @d4l3k's changes forward, but can we make this use tabwriter or "github.com/olekukonko/tablewriter" (already used in CR) so it has headings and is generally more legible?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10333#-:-KVR5Px9J53pMwsdmbQs:bitxuyo)*

**Comment by BramGruneir** [comment]
Sure, I can play around with it, but it's already a win past the original output.  No rush on merging this.

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10333#-:-KVR6JCXPSA6cYxczx89:b-yb64wg)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10333#-:-KVRFXWqt3uHaYgf0inT:bnfp4nl)*

**Comment by BramGruneir** [comment]
@tamird Updated to use tablewriter.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10333#-:-KVVpvxvoFmC-6dYBsVC:bs53sfw)*

**Comment by tamird** [comment]
:lgtm: :heart_eyes: 

Still kinda hard to figure out that the display is `<range count> <capacity %>`, but certainly this is better than the old.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10333#-:-KVVr1xSj-ZlQf14ADDR:b-yd74ox)*

**Pull request merged**
