### PR TITLE
storage: chunk gcqueue's requests

### LINKED ISSUE #15989: storage: chunk gcqueue's requests
The GC queue may generate large proposals, especially now that proposer-evaluated KV is in place. Though it hasn't been observed in practice, it should be easy to trigger that by deleting everything in a full range at around the same time (and we should start doing that on our test clusters).

The GC Queue should simply dispatch its `GCRequest` batches in chunks. Since it scans the complete key range before, it can even be more intelligent about these chunks than just capping them at X keys (which may still incur a large proposal; think of the case in which one key is continuously overwritten - that would generate a huge proposal just out of the evaluation of the GCRequest affecting only that key).

### PR DESCRIPTION
**Pull request by a6802739**
Fixes #15989. @tschottdorf

### CODE REVIEW

**Comment by tschottdorf** [comment]
Looks good, thanks songhao! Could you make `batches` a top-level function and write a small unit test? Just to check that the chunking works. Other than that, LGTM!

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/gc_queue.go, line 578 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Kls9-UmPlVu8mglp34U:-Kls9-UmPlVu8mglp34V:b-z765uz) ([raw file](https://github.com/cockroachdb/cockroach/blob/d00ab5a2088e1be0235624ebaccee2052f2e700c/pkg/storage/gc_queue.go#L578)):*
> ```Go
> 		for i, key := range gcKeys {
> 			size += len(key.Key)
> 			if size >= 256*1000 {
> ```

can you extract this into a `const` that lives at the top of the file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-:-Kls9HMBGqS6OBtgnrcr:brwno90)*

**Comment by a6802739** [comment]
@tschottdorf, what do you mean `make batches a top-level function`, and How could I check the chunking works, any reference would be appreciate?

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/storage/gc_queue.go, line 578 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Kls9-UmPlVu8mglp34U:-KlvIa4loSMppfR915OS:b-4hvi0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/d00ab5a2088e1be0235624ebaccee2052f2e700c/pkg/storage/gc_queue.go#L578)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

can you extract this into a `const` that lives at the top of the file?
</blockquote></details>

Got it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-:-KlvHzW3J9YSy6Duci0S:b-hlajr4)*

**Comment by tschottdorf** [comment]
from `batches := func(...)` to `func batches(...)` and then you can write a unit test that calls `batches`.

**Comment by a6802739** [comment]
@tschottdorf, Thank you for your reference, please have a look again.

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---

*[pkg/storage/gc_queue.go, line 78 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km1kuxYppGTL3378i35:-Km1kuxYppGTL3378i36:bj9gyyc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4993e4e8d95d6b2184ceab572493a6096e30f1ee/pkg/storage/gc_queue.go#L78)):*
> ```Go
> 	gcTaskLimit = 25
> 
> 	// gcChunkKeySize is the defalut size(256KB) for GCRequst's batch key size.
> ```

just drop the `(256KB)`. Typo in `GCRequest`. Typo in `default`.

---

*[pkg/storage/gc_queue.go, line 534 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km1kzLi-_2kJ_9laFqj:-Km1kzLi-_2kJ_9laFqk:b-ktwrxc) ([raw file](https://github.com/cockroachdb/cockroach/blob/4993e4e8d95d6b2184ceab572493a6096e30f1ee/pkg/storage/gc_queue.go#L534)):*
> // chunkGCRequest chunks the supplied gcKeys (which are consumed by this method) into multiple batches which must be executed in order by the caller.

---

*[pkg/storage/gc_queue_test.go, line 905 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km1lRNi-Lz3l25RlFHE:-Km1lRNi-Lz3l25RlFHF:b569u6a) ([raw file](https://github.com/cockroachdb/cockroach/blob/4993e4e8d95d6b2184ceab572493a6096e30f1ee/pkg/storage/gc_queue_test.go#L905)):*
> ```Go
> 	}
> 	batches := chunkGCRequest(desc, info, gcKeys)
> 	for _, batche := range batches[1:] {
> ```

rename `batche` to `batch`. Assert that there is more than one batch (if there isn't make the number of keys larger until the batching actually kicks in). Assert that the total number of keys in all batches equals what you started with.

---

*[pkg/storage/gc_queue_test.go, line 906 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km1leF9T-Kk2QKy6g5D:-Km1leF9T-Kk2QKy6g5E:b-iyaf2c) ([raw file](https://github.com/cockroachdb/cockroach/blob/4993e4e8d95d6b2184ceab572493a6096e30f1ee/pkg/storage/gc_queue_test.go#L906)):*
> ```Go
> 	batches := chunkGCRequest(desc, info, gcKeys)
> 	for _, batche := range batches[1:] {
> 		size := len(batche.Keys)
> ```

This isn't the right check - you want to check that the sum of the lengths of the keys in the batch is `<= gcChunkKeySize`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299)*

**Comment by a6802739** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/storage/gc_queue.go, line 78 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km1kuxYppGTL3378i35:-Km5ioJtoodnMgAiwFhZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4993e4e8d95d6b2184ceab572493a6096e30f1ee/pkg/storage/gc_queue.go#L78)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

just drop the `(256KB)`. Typo in `GCRequest`. Typo in `default`.
</blockquote></details>

Done.

---

*[pkg/storage/gc_queue.go, line 534 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km1kzLi-_2kJ_9laFqj:-Km5iprXM1YVzSARB500:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4993e4e8d95d6b2184ceab572493a6096e30f1ee/pkg/storage/gc_queue.go#L534)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> // chunkGCRequest chunks the supplied gcKeys (which are consumed by this method) into multiple batches which must be executed in order by the caller.
</blockquote></details>

Done.

---

*[pkg/storage/gc_queue_test.go, line 905 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km1lRNi-Lz3l25RlFHE:-Km5iy9XWWK3-1eVnHt1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4993e4e8d95d6b2184ceab572493a6096e30f1ee/pkg/storage/gc_queue_test.go#L905)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

rename `batche` to `batch`. Assert that there is more than one batch (if there isn't make the number of keys larger until the batching actually kicks in). Assert that the total number of keys in all batches equals what you started with.
</blockquote></details>

Done.

---

*[pkg/storage/gc_queue_test.go, line 906 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km1leF9T-Kk2QKy6g5D:-Km5j-gQLxXLXowjsf9p:bh7ksxg) ([raw file](https://github.com/cockroachdb/cockroach/blob/4993e4e8d95d6b2184ceab572493a6096e30f1ee/pkg/storage/gc_queue_test.go#L906)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This isn't the right check - you want to check that the sum of the lengths of the keys in the batch is `<= gcChunkKeySize`.
</blockquote></details>

Yes, My mistake. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299)*

**Comment by tschottdorf** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/storage/gc_queue_test.go, line 899 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7buuzyiawdvBFq40r:-Km7buuzyiawdvBFq40s:b-qlvvwj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L899)):*
> ```Go
> 	info := &GCInfo{}
> 	var gcKeys1 []roachpb.GCRequest_GCKey
> 	for i := 0; i < 256; i++ {
> ```

make `256` a function of `gcChunkKeySize`.

---

*[pkg/storage/gc_queue_test.go, line 905 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7b_-UvI-z1S3M2WSD:-Km7b_-UvI-z1S3M2WSE:bshgqsj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L905)):*
> ```Go
> 	}
> 	batches := chunkGCRequest(desc, info, gcKeys1)
> 	if len(batches)-1 != 1 {
> ```

```go
// We expect two batches: The initial state-adjusting batch that is always emitted, and an unbroken batch of our keys.
if act, exp := len(batches), 2; act != exp {
  t.Fatalf("expected %d batches, but got %d", exp, act)
}
```

---

*[pkg/storage/gc_queue_test.go, line 908 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7bmpAc-M0broIKmGG:-Km7bmpAc-M0broIKmGH:b4onvzz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L908)):*
> ```Go
> 		t.Fatalf("expected GC Request's chunked batches' length is one, but got %v", len(batches)-1)
> 	}
> 	size := 0
> ```

nit: we prefer `var size int`.

---

*[pkg/storage/gc_queue_test.go, line 913 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7bk_yPtdWCL7rhwCV:-Km7bk_yPtdWCL7rhwCW:b-lhdstf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L913)):*
> ```Go
> 	}
> 	if size > gcChunkKeySize {
> 		t.Fatalf("expected GC Request's batch size is smaller than %v, but got %v", gcChunkKeySize, size)
> ```

you can drop "is".

---

*[pkg/storage/gc_queue_test.go, line 924 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7brbhjKcdh0XHllNA:-Km7brbhjKcdh0XHllNB:b-mv9185) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L924)):*
> ```Go
> 
> 	batches = chunkGCRequest(desc, info, gcKeys2)
> 	if len(batches)-1 <= 1 {
> ```

Same as above.
// Now we expect there to be at least three batches since our key batch should have split.

---

*[pkg/storage/gc_queue_test.go, line 936 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7ca0SZIZVsULCNYks:-Km7ca0TkFWupxr-TA-D:b-x5gjot) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L936)):*
> ```Go
> 			base = size
> 		}
> 		if i > 0 && i < len(batches[1:])-1 {
> ```

This check is a little specific. You're testing that they all have the same size, but that's only true because you've set up the data that way. It's fine by me, though.

---

*[pkg/storage/gc_queue_test.go, line 937 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7cq23h1SFDESyN6pa:-Km7cq23h1SFDESyN6pb:b-h3uy29) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L937)):*
> ```Go
> 		}
> 		if i > 0 && i < len(batches[1:])-1 {
> 			cur = size
> ```

You can eliminate the variable `cur`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299)*

**Comment by tschottdorf** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/storage/gc_queue_test.go, line 946 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7d1c1bcMpk8G9logR:-Km7d1c1bcMpk8G9logS:bfpamna) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L946)):*
> ```Go
> 		}
> 		size = 0
> 	}
> ```

Also check that you didn't lose any requests. I.e. the `sum len(batch.Keys)` is equal to the initial number of keys you put in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299)*

**Comment by a6802739** [comment]
@tschottdorf, Thanks for you review.

---

Review status: 1 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[pkg/storage/gc_queue_test.go, line 899 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7buuzyiawdvBFq40r:-KmAQrBfLOW_nvLNGUv9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L899)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

make `256` a function of `gcChunkKeySize`.
</blockquote></details>

Done.

---

*[pkg/storage/gc_queue_test.go, line 905 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7b_-UvI-z1S3M2WSD:-KmAQsn46K3JtZcbTQdw:b-82fzpm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L905)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

```go
// We expect two batches: The initial state-adjusting batch that is always emitted, and an unbroken batch of our keys.
if act, exp := len(batches), 2; act != exp {
  t.Fatalf("expected %d batches, but got %d", exp, act)
}
```
</blockquote></details>

Thank you. Done.

---

*[pkg/storage/gc_queue_test.go, line 908 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7bmpAc-M0broIKmGG:-KmAQxXuOVsgNz1mmDDo:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L908)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

nit: we prefer `var size int`.
</blockquote></details>

Done.

---

*[pkg/storage/gc_queue_test.go, line 913 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7bk_yPtdWCL7rhwCV:-KmAR0pvvpngg_Vyc6_F:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L913)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

you can drop "is".
</blockquote></details>

Done.

---

*[pkg/storage/gc_queue_test.go, line 924 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7brbhjKcdh0XHllNA:-KmAR3cT0fJsicxNsmpm:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L924)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Same as above.
// Now we expect there to be at least three batches since our key batch should have split.
</blockquote></details>

Done.

---

*[pkg/storage/gc_queue_test.go, line 936 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7ca0SZIZVsULCNYks:-KmAR51KSIUNh2hREFBR:b-yqc93u) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L936)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

This check is a little specific. You're testing that they all have the same size, but that's only true because you've set up the data that way. It's fine by me, though.
</blockquote></details>

Yes. It is a little specific.

---

*[pkg/storage/gc_queue_test.go, line 937 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7cq23h1SFDESyN6pa:-KmARCFfJq2-v9uu5y5q:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L937)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

You can eliminate the variable `cur`.
</blockquote></details>

Done.

---

*[pkg/storage/gc_queue_test.go, line 946 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-Km7d1c1bcMpk8G9logR:-KmAREG4OIJJ6hThL-Hl:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c86d74fdb3f599a07309e09f19fc1fbd22c18911/pkg/storage/gc_queue_test.go#L946)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Also check that you didn't lose any requests. I.e. the `sum len(batch.Keys)` is equal to the initial number of keys you put in.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-:-KmA-z0rgYA7eDLeOSAZ:b-vf8rjq)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/storage/gc_queue_test.go, line 920 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-KmC4FJBDgSZvGAV1-Zf:-KmC4FJBDgSZvGAV1-Zg:bmwtgmy) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0d423ee6ae89a36da311626271327cb9a246a0/pkg/storage/gc_queue_test.go#L920)):*
> ```Go
> 
> 	var gcKeys2 []roachpb.GCRequest_GCKey
> 	for i := 0; i < gcChunkKeySize; i++ {
> ```

make this, for example, `5*gcChunkKeySize` (or you end up with 3 batches and your check below really only sees one "full" batch and tests less).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-:-KmC4TEw8q0L3dEpdw75:bnfp4nl)*

**Comment by a6802739** [comment]
@tschottdorf, Thank you very much.

---

Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/storage/gc_queue_test.go, line 920 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-KmC4FJBDgSZvGAV1-Zf:-KmQOryHQGyxX_EpP8OD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2a0d423ee6ae89a36da311626271327cb9a246a0/pkg/storage/gc_queue_test.go#L920)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

make this, for example, `5*gcChunkKeySize` (or you end up with 3 batches and your check below really only sees one "full" batch and tests less).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-:-KmQOtP54R9pOTC1I0jR:bimrd01)*

**Comment by tschottdorf** [comment]
:lgtm: Thanks!

---

Reviewed 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16299#-:-KmRfzRCxASR88JOe_Db:b-g2a5fb)*

**Pull request merged**
