### PR TITLE
sql: make snowball tracing work with distsql

### PR DESCRIPTION
**Pull request by RaduBerinde**
We add trace data as a new type of metadata that can circulate through distsql
streams. Each processor that is part of a recording sends out its traces before
exiting.

To implement this we need to add a special mode to `StartChildSpan` which
disconnects the child span recording from the parent span (otherwise each
processor would send out not just its traces but everything that runs on that
node; and processors running on the gateway would be recorded twice).

Note that `SHOW TRACE FOR` still does not run queries with distsql. This is
because the distsql planner doesn't know what to do with a `traceNode`.

### CODE REVIEW

**Comment by andreimatei** [comment]
:lgtm: woot!

---

Reviewed 15 of 21 files at r1.
Review status: 15 of 21 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_running.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-KnBBRjnav6pnrkYs8og:-KnBBRjnav6pnrkYs8oh:blcoh8x) ([raw file](https://github.com/cockroachdb/cockroach/blob/04af531bd73558bfa27ae373597842a9d7fae6a7/pkg/sql/distsql_running.go#L32)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/log"
> 	"github.com/cockroachdb/cockroach/pkg/util/tracing"
> 	opentracing "github.com/opentracing/opentracing-go"
> ```

nit: put these imports above the cockroach ones. I'm surprised no linter is yelling.

---

*[pkg/sql/distsqlrun/base.go, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-KnBFqxxHQUyDZwV1ZJi:-KnBFqxytfS6blxxsFAq:b8cpzfw) ([raw file](https://github.com/cockroachdb/cockroach/blob/04af531bd73558bfa27ae373597842a9d7fae6a7/pkg/sql/distsqlrun/base.go#L33)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/util/syncutil"
> 	"github.com/cockroachdb/cockroach/pkg/util/tracing"
> 	opentracing "github.com/opentracing/opentracing-go"
> ```

move import up

---

*[pkg/sql/distsqlrun/data.proto, line 202 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-KnBDJzL1XjRi5gnFEwH:-KnBDJzM2gkPyUHzDWIr:bx6udns) ([raw file](https://github.com/cockroachdb/cockroach/blob/04af531bd73558bfa27ae373597842a9d7fae6a7/pkg/sql/distsqlrun/data.proto#L202)):*
> ```protobuf
>   }
>   message TraceData {
>     repeated util.tracing.RecordedSpan collected_spans = 1 [(gogoproto.nullable) = false];
> ```

please check if `make proto` shows a warning saying `nullable` on a `repeated` field is nonsense. I feel like I've seen this recently (and this applies to the RangeInfo above too).

---

*[pkg/sql/distsqlrun/stream_decoder.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-KnBEQSTsPUb0WOlHjms:-KnBEQSUuKRgrh329f7I:b-prqp6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/04af531bd73558bfa27ae373597842a9d7fae6a7/pkg/sql/distsqlrun/stream_decoder.go#L117)):*
> ```Go
> 
> 			default:
> 				// Unknown metadata, ignore.
> ```

I think we should `continue` here, to avoid appending an empty meta.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-:-KnBGKo6QlGUj1Vihmva:b-7twlcb)*

**Comment by RaduBerinde** [comment]
TFTR!

---

Review status: 12 of 21 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/distsql_running.go, line 32 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-KnBBRjnav6pnrkYs8og:-KnBczfDQpmpluSRtAyk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04af531bd73558bfa27ae373597842a9d7fae6a7/pkg/sql/distsql_running.go#L32)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

nit: put these imports above the cockroach ones. I'm surprised no linter is yelling.
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/base.go, line 33 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-KnBFqxxHQUyDZwV1ZJi:-KnBd45h6KOnT9VH3eoW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04af531bd73558bfa27ae373597842a9d7fae6a7/pkg/sql/distsqlrun/base.go#L33)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

move import up
</blockquote></details>

Done.

---

*[pkg/sql/distsqlrun/data.proto, line 202 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-KnBDJzL1XjRi5gnFEwH:-KnBd5nVDQ7daXcL7x__:bzfp47q) ([raw file](https://github.com/cockroachdb/cockroach/blob/04af531bd73558bfa27ae373597842a9d7fae6a7/pkg/sql/distsqlrun/data.proto#L202)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please check if `make proto` shows a warning saying `nullable` on a `repeated` field is nonsense. I feel like I've seen this recently (and this applies to the RangeInfo above too).
</blockquote></details>

No, that only applies to basic types. There is a difference when you're using a repeated "message".

---

*[pkg/sql/distsqlrun/stream_decoder.go, line 117 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-KnBEQSTsPUb0WOlHjms:-KnBdYVCph8qt5259ZRb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/04af531bd73558bfa27ae373597842a9d7fae6a7/pkg/sql/distsqlrun/stream_decoder.go#L117)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think we should `continue` here, to avoid appending an empty meta.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-:-KnBdwvcqb3PC_tGrDqj:b-814g8k)*

**Comment by knz** [comment]
:lgtm: :beers: 

---

Reviewed 18 of 21 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/16655#-:-KnE_uVlt5srICOv1kiM:bfx5672)*

**Comment by spencerkimball** [comment]
Awesome! Have you given any thought to returning trace data in a streaming fashion?

**Comment by knz** [comment]
I was asking the same yesterday. Here's the answer from Radu:

> It's not supposed to contain a high volume of stuff, modulo the KV stuff. Note that there is a limit on the events in each span.
> I'm not sure I understand your proposal, if you send things through a channel and they're not being retrieved, isn't that still accumulating them in memory?
> We could also put a hard limit on the number of messages in a recording if need be
> we actually have that more or less, it's maxLogsPerSpan (1000) times the number of spans in the operation

**Comment by RaduBerinde** [comment]
I think Spencer is asking more from the perspective of knowing what happened during a long running or stuck query (not from a memory usage concern). It shouldn't be hard to do, we can improve the interfaces to get recording "diffs". We just have to come up with the right facility to extract/present these in-progress traces.

**Pull request merged**
