### PR TITLE
sql: show column directions in SHOW INDEX

### LINKED ISSUE #3414: The index direction is not part of the SHOW INDEX data
One idea is to show it with `+/-` on the column name vs introducing a dedicated output column. But what if we support collations later on?

### PR DESCRIPTION
**Pull request by andreimatei**
closes #3414

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3437)

### CODE REVIEW

**Comment by petermattis** [comment]
LGTM

---

Review status: 0 of 10 files reviewed at latest revision, 3 unresolved discussions.

---

*[sql/show.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XBDhANcVrAuJdxxv5:-K5XBDhANcVrAuJdxxv6:-62404455) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f53304cf72bf9780ec0a240a4dfa0988a9ef20f/sql/show.go#L206)):*
I wonder if `"-"` would be better than an empty string. 

---

*[sql/structured.go, line 79 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XBTv-_cwioqeCwYre:-K5XBTv-_cwioqeCwYrf:1364238413) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f53304cf72bf9780ec0a240a4dfa0988a9ef20f/sql/structured.go#L79)):*
This should be a method on `IndexDescriptor_Direction`, not on `IndexDescriptor`. An no need for the named return values here. You're not using them anyways.

---

*[sql/structured.go, line 84 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XBmj3kq2IoApXQhim:-K5XBmj3kq2IoApXQhin:782079664) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f53304cf72bf9780ec0a240a4dfa0988a9ef20f/sql/structured.go#L84)):*
I wonder if `"asc"` and `"desc"` would be better, to match the SQL tokens.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-:-K5XC1Pmcg2KAbqx3Yl9:676834233)*

**Comment by tamird** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/show.go, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XCDFvDqlVNt0Xaita:-K5XCDFvDqlVNt0Xaitb:-300167391) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f53304cf72bf9780ec0a240a4dfa0988a9ef20f/sql/show.go#L197)):*
since you have different treatment for `index.ColumnNames` and `index.StoreColumnNames`, perhaps it's time to to not use a single loop for the two.

You can use a closure to capture the common code below.

---

*[sql/structured.go, line 86 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XC_MtStjcklPut6QV:-K5XC_MtStjcklPut6QW:1628533622) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f53304cf72bf9780ec0a240a4dfa0988a9ef20f/sql/structured.go#L86)):*
nit: this should be `util.Errorf` because it is a programming error, not a user error.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Comment by andreimatei** [comment]
Review status: 0 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/show.go, line 197 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XCDFvDqlVNt0Xaita:-K5XRBwqhi2EuZy-2ARK:148850956) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f53304cf72bf9780ec0a240a4dfa0988a9ef20f/sql/show.go#L197)):*
Should have known this isn't going to fly. FWIW, we were always treating the 2 column types differently :)

---

*[sql/show.go, line 206 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XBDhANcVrAuJdxxv5:-K5XLXKzHKXYRiL0fg9N:1731470435) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f53304cf72bf9780ec0a240a4dfa0988a9ef20f/sql/show.go#L206)):*
switched to `N/A`

---

*[sql/structured.go, line 79 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XBTv-_cwioqeCwYre:-K5XSD4jFQKzpoQFumLV:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f53304cf72bf9780ec0a240a4dfa0988a9ef20f/sql/structured.go#L79)):*
Done.

---

*[sql/structured.go, line 84 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XBmj3kq2IoApXQhim:-K5XSHL-lXIBqxhnchkx:-35364532) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f53304cf72bf9780ec0a240a4dfa0988a9ef20f/sql/structured.go#L84)):*
switched to `ASC`/`DESC`

---

*[sql/structured.go, line 86 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XC_MtStjcklPut6QV:-K5XSGyUIkFDvfA4q8CW:304186811) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f53304cf72bf9780ec0a240a4dfa0988a9ef20f/sql/structured.go#L86)):*
Done. Googled util errorf, got cockroach github. Nice.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Comment by tamird** [comment]
Reviewed 10 of 10 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/show.go, line 191 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XW7s80Kc6wjhDViVI:-K5XW7s9L5H1VBnLWBwP:-281208776) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd21a979b2cfab360e09906ed3663fdc8ef20b63/sql/show.go#L191)):*
you may want to hoist this out of the loop; this possibly allocates many closures.

---

*[sql/structured.go, line 79 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XWSaiwaa9sXI1NUf8:-K5XWSaiwaa9sXI1NUf9:1221015484) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd21a979b2cfab360e09906ed3663fdc8ef20b63/sql/structured.go#L79)):*
make this a value receiver.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Comment by andreimatei** [comment]
Review status: 8 of 10 files reviewed at latest revision, 5 unresolved discussions.

---

*[sql/show.go, line 191 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XW7s80Kc6wjhDViVI:-K5Xagmi0JRQCwZKAC8_:-760058350) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd21a979b2cfab360e09906ed3663fdc8ef20b63/sql/show.go#L191)):*
Done. I put it inside to capture `index`, but you're probably right

---

*[sql/structured.go, line 79 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5XWSaiwaa9sXI1NUf8:-K5Xafp29J7MMoLblV5b:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd21a979b2cfab360e09906ed3663fdc8ef20b63/sql/structured.go#L79)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/structured.go, line 86 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5YINKMZpzPZrG91fAJ:-K5YINKMZpzPZrG91fAK:1657508850) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c9c01600d70c8266229ca4fad5ff0b55dd82d82/sql/structured.go#L86)):*
Rather than return an error here, it might be better to return `fmt.Sprint(int(dir))`. That way the user can see the invalid direction in the output rather than trying to figure out what part of the descriptor is problematic from the error message (which currently doesn't provide enough detail).

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/structured.go, line 86 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5YINKMZpzPZrG91fAJ:-K5aP8UwV38BXQZU2dNP:-985628000) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c9c01600d70c8266229ca4fad5ff0b55dd82d82/sql/structured.go#L86)):*
well bad user input should not actually make it to this place. The parser should bail before, right. So this error represents a bug. I'm guessing you'll still see the invalid value in the log (although I got lost trying to trace the call path).
Do you still think  we should just return a string? In the context of this particular function, I have no opinion really.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/structured.go, line 86 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5YINKMZpzPZrG91fAJ:-K5aSKbOqzRW2K4yKPow:-694146333) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c9c01600d70c8266229ca4fad5ff0b55dd82d82/sql/structured.go#L86)):*
In fact, I was surprised that the proto code even allows out of range values for enums.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/structured.go, line 86 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5YINKMZpzPZrG91fAJ:-K5aSnqdoimaAuXjwgYN:861314671) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c9c01600d70c8266229ca4fad5ff0b55dd82d82/sql/structured.go#L86)):*
Can't not allow out of range values; that would break forward-compatibility. I'd be very surprised if you found the invalid value in the log.

I don't feel strongly about string vs error but the value should definitely be reported in the function's output.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/structured.go, line 86 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5YINKMZpzPZrG91fAJ:-K5aSpLeM3qfvvHgScfl:-951653306) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c9c01600d70c8266229ca4fad5ff0b55dd82d82/sql/structured.go#L86)):*
I think you should just return a string. An invalid proto enum value here is possible, but extremely unlikely.  I think you can actually remove this method name and use `IndexDescriptor_Direction.String()`.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/structured.go, line 86 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437#-K5YINKMZpzPZrG91fAJ:-K5awmvVSd6Wq19WKaa8:-2116617490) ([raw file](https://github.com/cockroachdb/cockroach/blob/4c9c01600d70c8266229ca4fad5ff0b55dd82d82/sql/structured.go#L86)):*
well out of range values could probably be disallowed, at least for setting.
Anyway, ok, I'm removing this function all-together in a new PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/3437)*

**Pull request merged**
