### PR TITLE
storage: introduce LeaseInfoRequest

### PR DESCRIPTION
**Pull request by andreimatei**
LeaseInfoRequest is a read command for getting the current lease holder
for a range.
It will be used to proactively refresh the LeaseHolderCache when SQL
planning needs to figure out some lease holders.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8752)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1, 9 of 11 files at r2.
Review status: 9 of 11 files reviewed at latest revision, 6 unresolved discussions, all commit checks successful.

---

*[roachpb/api.proto, line 724 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp4QjIkgdLpuYDa3Rb:-KPp4QjIkgdLpuYDa3Rc:b2ngywj) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/roachpb/api.proto#L724)):*
> ```protobuf
>   optional ChangeFrozenRequest change_frozen = 27;
>   optional TransferLeaseRequest transfer_lease = 28;
>   optional LeaseInfoRequest lease_info = 30;
> ```

29?

---

*[roachpb/api.proto, line 761 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp4NQmS4wObaNQDuYe:-KPp4NQmS4wObaNQDuYf:b-rgrihv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/roachpb/api.proto#L761)):*
> ```protobuf
>   optional ChangeFrozenResponse change_frozen = 27;
>   reserved 28; // TransferLease and RequestLease both use RequestLeaseResponse
>   optional LeaseInfoResponse lease_info = 30;
> ```

where did 29 go?

---

*[roachpb/method.go, line 110 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp4mETg0gDaUNCwTT5:-KPp4mETg0gDaUNCwTT6:b-48x9f1) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/roachpb/method.go#L110)):*
> ```Go
> 	// TransferLease transfers the range lease from a lease holder to a new one.
> 	TransferLease
> 	// LeaseInfo returns information about a range's lease.
> ```

doesn't it return information about a lease holder's lease? in other words, the RPC addresses a replica, not a range.

---

*[storage/replica.go, line 948 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp55w4jx3BP6wgsjSj:-KPp55w5LjkPC5x0w0jN:b6jr36) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/storage/replica.go#L948)):*
> ```Go
> 	}
> 	if pErr != nil {
> 		log.Tracef(ctx, "replica.Send got error: %s", pErr)
> ```

won't this be redundant when @raduberinde's context plumbing goes in?

---

*[testutils/testcluster/testcluster.go, line 426 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp5Ki4hcMEQPtFySBG:-KPp5Ki4hcMEQPtFySBH:b-4mub3b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/testutils/testcluster/testcluster.go#L426)):*
> ```Go
> 	}
> 	if hintServer == nil {
> 		return ReplicationTarget{}, errors.Errorf("bad hint: no such node")
> ```

include the hint? ditto above in the call to `GetReplicaDescriptor` while you're here.

---

*[testutils/testcluster/testcluster.go, line 441 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp5c64vnlpfHk6J2HH:-KPp5c64vnlpfHk6J2HI:bu9abjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/testutils/testcluster/testcluster.go#L441)):*
> ```Go
> 	}
> 	replicaDesc := leaseResp.(*roachpb.LeaseInfoResponse).Replica
> 	rt := ReplicationTarget{
> ```

nit: avoid this local?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752)*

**Comment by RaduBerinde** [comment]
Great stuff! A question - what happens if we query a span that spans ranges? Does the result reflect whatever range corresponds to the beginning of the span? Should a "cutoff" key be returned in that case? (this should be documented in the .proto files)

---

Review status: 9 of 11 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[storage/replica.go, line 948 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp55w4jx3BP6wgsjSj:-KPsR-vCCUOE9cZO7TxY:b-s309ub) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/storage/replica.go#L948)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> won't this be redundant when @raduberinde's context plumbing goes in?
</details>
Since the file and line are not part of traces at this point (there was some debate about changing that), "error: x" might be too vague even with the proper replica/store context.

---

*[storage/replica_command.go, line 3187 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPsRZtWhWI1ku-xo953:-KPsRZtWhWI1ku-xo954:bjtc3rm) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f599298e474ea4a6f509c9bd51355ec1d8011f/storage/replica_command.go#L3187)):*
> ```Go
> // one), the replica tries to acquire the lease.
> func (r *Replica) LeaseInfo(
> 	ctx context.Context,
> ```

[nit] the args fit on one line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-:-KPsRl74uYbAhPaTu-5-:b-q48cn9)*

**Comment by bdarnell** [comment]
LeaseInfo doesn't have the `isRange` flag in `api.go`, so it's a point request and should never have an EndKey. Maybe it should be a range request, though, so you don't have to know the range bounds in advance. 

LGTM

---

Reviewed 10 of 11 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[roachpb/api.proto, line 636 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPsl_LL2NVB2HtL4_Jk:-KPsl_LM7URl_1JoQkua:b-4tg5hl) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f599298e474ea4a6f509c9bd51355ec1d8011f/roachpb/api.proto#L636)):*
> ```protobuf
>   // for the range, but it can be the tentative future lease holder, if a lease
>   // transfer is in progress.
>   optional ReplicaDescriptor replica = 2 [(gogoproto.nullable) = false];
> ```

This should probably be a Lease instead of just the ReplicaDescriptor. Even if we don't need it today, it can't hurt to make the timing information available. 

---

*[storage/client_replica_test.go, line 763 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPslv1i8VsqiD_fU1XS:-KPslv1jtg_LEBRgx7sZ:b2qduhs) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f599298e474ea4a6f509c9bd51355ec1d8011f/storage/client_replica_test.go#L763)):*
> ```Go
> 
> 	tableStartKey := keys.MakeRowSentinelKey(keys.MakeTablePrefix(uint32(tableDesc.ID)))
> 	_, tableRangeDesc, err := tc.SplitRange(tableStartKey)
> ```

Doesn't this split happen automatically as a result of the table creation? We shouldn't be doing it manually here. 

Do you even need a table and a split? You should be able to do all of this on range 1.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-:-KPsji0tIb0ePb_tnKA4:bnmcj6y)*

**Comment by andreimatei** [comment]
TFTR!
There'll be a higher level that splits by range (other than the `DistSender`), because we might want to hint different lease holders for different ranges (think load balancing for the upcoming operation).

@bdarnell I've changed the response of `LeaseInfoRequest` to be a `Lease` so I had to also change `NotLeaseHolderError` to include a `Lease` too. PTAL at r5 and r6 when you can.

Also I've added some clarifying comments to what the guarantees of `TestCluster.TransferRangeLease()` are.

---

Review status: 0 of 16 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[roachpb/api.proto, line 724 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp4QjIkgdLpuYDa3Rb:-KPyh0zhKtasrpeLvZ9h:b3rkwy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/roachpb/api.proto#L724)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> 29?
</details>
AdminTransferLeaseRequest

---

*[roachpb/api.proto, line 761 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp4NQmS4wObaNQDuYe:-KPyh4GwL7g5tvOgyf5x:b3rkwy2) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/roachpb/api.proto#L761)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> where did 29 go?
</details>
AdminTransferLeaseRequest

---

*[roachpb/api.proto, line 636 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPsl_LL2NVB2HtL4_Jk:-KPxGl5vsIh29ZTlB2uU:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f599298e474ea4a6f509c9bd51355ec1d8011f/roachpb/api.proto#L636)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> This should probably be a Lease instead of just the ReplicaDescriptor. Even if we don't need it today, it can't hurt to make the timing information available. 
</details>
done

---

*[roachpb/method.go, line 110 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp4mETg0gDaUNCwTT5:-KPyhERqC8xAM7wwVOrg:byij0c3) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/roachpb/method.go#L110)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> doesn't it return information about a lease holder's lease? in other words, the RPC addresses a replica, not a range.
</details>
Not sure I understand what you're driving at. The request addresses a range, just like all (most?) of the others, in the same way that any read is addressed to a range. Except this read is supposed to be done usually as an `INCONSISTENT` one, so even more so you can address it to any replica.

Maybe the confusion is terminological - I think it's correct to say that a range has a lease - it's part of the replicate range state (even though it crowns one particular replica).

---

*[storage/client_replica_test.go, line 763 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPslv1i8VsqiD_fU1XS:-KQ1p4v8yXpQdhukIuYX:b-7nse9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f599298e474ea4a6f509c9bd51355ec1d8011f/storage/client_replica_test.go#L763)):*
<details><summary><i>Previously, bdarnell (Ben Darnell) wrote…</i></summary>
> Doesn't this split happen automatically as a result of the table creation? We shouldn't be doing it manually here. 
> 
> Do you even need a table and a split? You should be able to do all of this on range 1.
</details>
Done. I don't know why I was scared of using range 1.

---

*[storage/replica_command.go, line 3187 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPsRZtWhWI1ku-xo953:-KPyiTWrM9B-t2t_vcGY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/88f599298e474ea4a6f509c9bd51355ec1d8011f/storage/replica_command.go#L3187)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> [nit] the args fit on one line
</details>
Done.

---

*[testutils/testcluster/testcluster.go, line 426 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp5Ki4hcMEQPtFySBG:-KQ1pf35FEtU6U_KM0Mi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/testutils/testcluster/testcluster.go#L426)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> include the hint? ditto above in the call to `GetReplicaDescriptor` while you're here.
</details>
Done.

---

*[testutils/testcluster/testcluster.go, line 441 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-KPp5c64vnlpfHk6J2HH:-KQ1pm3MASePR1XSOe3x:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8948800db2b0743dad12b8f93c9a3df334f65034/testutils/testcluster/testcluster.go#L441)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: avoid this local?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8752#-:-KPyi_d1WKYDYguUu1lJ:b7zon4l)*

**Pull request merged**
