### PR TITLE
optional: add Duration

### PR DESCRIPTION
**Pull request by asubiotto**
This commit adds a TimeValue protobuf that is used to represent time.Duration
statistics in the ComponentStats proto. Similar to the IntValue struct, this
protobuf allows differentiating between set and unset values.

These stats were previously stored as time.Durations but EXPLAIN ANALYZE logic
test flakiness on recent PRs have shown that it is valid for a time.Duration to
be set to 0 in some cases (when recording less than a ns of time). The
ComponentStats formatting code assumes a time of 0 is unset, so this would
cause some time labels to be elided from the diagram non-deterministically.

Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
Nice! I was initially thinking that we'd make sure any kind of timer returns at least 1ns. But that is more error prone, and this is more consistent with the int stats.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56951#-:-MMaDkg25GMB4a-_pdum:bvuudus)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @RaduBerinde)

___
*[pkg/sql/execinfrapb/component_stats.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56951#-MMaGaau4UpIpxlecZNb:-MMaGaau4UpIpxlecZNc:b-2vz27x) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89099dfa52ab8437d30a89145139075c4342b81/pkg/sql/execinfrapb/component_stats.go#L143)):*
> ```Go
> 	timeVal := func(v *TimeValue) {
> 		if v.HasValue() {
> 			v.Set(1)
> ```

[nit] time.Nanosecond instead of 1
___
*[pkg/sql/execinfrapb/component_stats.proto, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56951#-MMaFOMzCweRUoWg8CYu:-MMaFOMzCweRUoWg8CYv:b-ybkixa) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89099dfa52ab8437d30a89145139075c4342b81/pkg/sql/execinfrapb/component_stats.proto#L116)):*
> ```protobuf
> // The underlying value is the logical value plus 1, so that zero remains the
> // special case of having no value.
> message TimeValue {
> ```

This is a better design than IntValue: we can't inadvertently set or compare to literal constants, or print with '%d'. It causes an extra byte in the encoded data but that's unlikely to matter.
I will switch IntValue to this design too, and move them both to a separate `util/optional` package (because I  would already use them in other places).
___
*[pkg/sql/execinfrapb/component_stats.proto, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56951#-MMaFs2r9fSKa9tL1I3z:-MMaFs2r9fSKa9tL1I4-:bdp39c1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89099dfa52ab8437d30a89145139075c4342b81/pkg/sql/execinfrapb/component_stats.proto#L120)):*
> ```protobuf
>   // RawValue is the TimeValue's underlying value.
>   // DO NOT ACCESS THIS DIRECTLY. Use HasValue and Value instead.
>   optional google.protobuf.Duration raw_value = 1 [(gogoproto.nullable) = false,
> ```

[nit] could be `value_plus_one` so it's more clear and less likely that someone will use it without realizing that

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56951)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @RaduBerinde)

___
*[pkg/sql/execinfrapb/component_stats.proto, line 116 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56951#-MMaFOMzCweRUoWg8CYu:-MMovV8cE5pS485zz4Zs:b-mdy29o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89099dfa52ab8437d30a89145139075c4342b81/pkg/sql/execinfrapb/component_stats.proto#L116)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This is a better design than IntValue: we can't inadvertently set or compare to literal constants, or print with '%d'. It causes an extra byte in the encoded data but that's unlikely to matter.
I will switch IntValue to this design too, and move them both to a separate `util/optional` package (because I  would already use them in other places).
</blockquote></details>

:+1: I'll wait for your `optional` PR to go in before moving it and merging this PR.
___
*[pkg/sql/execinfrapb/component_stats.proto, line 120 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56951#-MMaFs2r9fSKa9tL1I3z:-MMovdRO0R8mrO6zYNPv:b-ovwaw7) ([raw file](https://github.com/cockroachdb/cockroach/blob/c89099dfa52ab8437d30a89145139075c4342b81/pkg/sql/execinfrapb/component_stats.proto#L120)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] could be `value_plus_one` so it's more clear and less likely that someone will use it without realizing that
</blockquote></details>

Good idea.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56951#-:-MN-ev5U0Efch3CLpxJA:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by asubiotto** [comment]
TFTR

bors r=RaduBerinde

**Comment by asubiotto** [comment]
Looks like an unrelated `TestTrace` failure/timeout.

bors r=RaduBerinde

**Pull request merged**
