### PR TITLE
sql: add NOSQLLOGIN role which restricts SQL CLI only

### LINKED ISSUE #74482: Create a new role option NOSQLLOGIN to allow DB Console access and restrict SQL shell access
**Describe the solution you'd like**
We want to create a new role option called `NOSQLLOGIN` so that any DB user with this role option can access the DB Console but not be able to get SQL shell access. This will give customers more granular control over how to manage what access their users have within a cluster

`CREATE ROLE app_developers WITH NOSQLLOGIN;`

Epic: CRDB-12102

### PR DESCRIPTION
**Pull request by dhartunian**
Previously, in order to restrict user login ability, the `LOGIN` and
`NOLOGIN` role options were available which would restrict both SQL and
DB Console login ability.

This change adds the `NOSQLLOGIN` (and its inverse: `SQLLOGIN`) role
option in order to provide the ability to disable SQL CLI logins from
users while retaining DB Console login ability.

Resolves cockroachdb#74482

Release note (sql change): A new role option is now available,
`NOSQLLOGIN` (and its inverse `SQLLOGIN`), which restricts SQL CLI login
ability for a user while retaining their ability to login to the DB
Console (as opposed to `NOLOGIN` which restricts both SQL and DB
Console). Without any role options all login behavior remains permitted
as it does today. OIDC logins to the DB Console continue to be permitted
with `NOSQLLOGIN` set.

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74706)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian and @maryliag)

___
*[pkg/sql/roleoption/role_option.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74706#-MtEogW1EkQ5zc6vVrXb:-MtEogW2-wmtXOVbPCIl:b-8my88w) ([raw file](https://github.com/cockroachdb/cockroach/blob/434af3b6d612fc0c19b3a5d0fe96215f3a4a2f38/pkg/sql/roleoption/role_option.go#L222)):*
> ```Go
> 			roleOptionBits&NOCANCELQUERY.Mask() != 0) ||
> 		(roleOptionBits&MODIFYCLUSTERSETTING.Mask() != 0 &&
> 			roleOptionBits&NOMODIFYCLUSTERSETTING.Mask() != 0) {
> ```

should you add the check here for the `SQLLOGIN` and `NOSQLLOGIN` ?

**Review by kpatron-cockroachlabs — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74706)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dhartunian, @kpatron-cockroachlabs, and @maryliag)

___
*[pkg/server/authentication.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74706#-MtEwDTABNun4Q20GUbH:-MtEwDTABNun4Q20GUbI:b-2yeo5u) ([raw file](https://github.com/cockroachdb/cockroach/blob/434af3b6d612fc0c19b3a5d0fe96215f3a4a2f38/pkg/server/authentication.go#L417)):*
> ```Go
> // The caller is responsible for ensuring that the username is normalized.
> // (CockroachDB has case-insensitive usernames, unlike PostgreSQL.)
> func (s *authenticationServer) verifyPassword(
> ```

Should we rename this function to something to make sure people don't accidentally use it in the DBConsole context?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74706)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kpatron-cockroachlabs, @maryliag, and @rafiss)

___
*[pkg/server/authentication.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74706#-MtEwDTABNun4Q20GUbH:-MtJACSlDTYbEY_67XFq:b-c9hzcr) ([raw file](https://github.com/cockroachdb/cockroach/blob/434af3b6d612fc0c19b3a5d0fe96215f3a4a2f38/pkg/server/authentication.go#L417)):*
<details><summary><i>Previously, kpatron-cockroachlabs wrote…</i></summary><blockquote>

Should we rename this function to something to make sure people don't accidentally use it in the DBConsole context?
</blockquote></details>

actually, this function can be removed entirely (and just keep the `verifyPasswordDBConsole` one). the SQL login password is verified in a different way. see: https://github.com/cockroachdb/cockroach/blob/fded4b03b28f9ce8941c6cd54ab45049c14ebbb2/pkg/security/auth.go#L175
___
*[pkg/sql/roleoption/role_option.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74706#-MtEogW1EkQ5zc6vVrXb:-MtJBhsx5tHF0yg9m3zO:b2ngthx) ([raw file](https://github.com/cockroachdb/cockroach/blob/434af3b6d612fc0c19b3a5d0fe96215f3a4a2f38/pkg/sql/roleoption/role_option.go#L222)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

should you add the check here for the `SQLLOGIN` and `NOSQLLOGIN` ?
</blockquote></details>

+1

**Review by dhartunian — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74706)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kpatron-cockroachlabs, @maryliag, and @rafiss)

___
*[pkg/server/authentication.go, line 417 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74706#-MtEwDTABNun4Q20GUbH:-MtP1H_Y1TlWTPisMCpy:b-yd5kvq) ([raw file](https://github.com/cockroachdb/cockroach/blob/434af3b6d612fc0c19b3a5d0fe96215f3a4a2f38/pkg/server/authentication.go#L417)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

actually, this function can be removed entirely (and just keep the `verifyPasswordDBConsole` one). the SQL login password is verified in a different way. see: https://github.com/cockroachdb/cockroach/blob/fded4b03b28f9ce8941c6cd54ab45049c14ebbb2/pkg/security/auth.go#L175
</blockquote></details>

Ah thx for the tip @rafiss.

The places where `verifyPassword` is used are:
- `pkg/server/authentication.go#demoLogin` to facilitate easy login for demo DB Console (this use case can be changed)
- ``pkg/server/api_v2_auth.go#login` for logging into another HTTP server

I'll just keep one `verifyPasswordDBConsole` to cover all these cases.
___
*[pkg/sql/roleoption/role_option.go, line 222 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/74706#-MtEogW1EkQ5zc6vVrXb:-MtP1syC5CC2bS9d7-x_:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/434af3b6d612fc0c19b3a5d0fe96215f3a4a2f38/pkg/sql/roleoption/role_option.go#L222)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

+1 
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

cc @knz this refactors some code you're working on

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74706#-:-MtcyeAD6q6oXr3iL79Z:b-p8bw2c)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kpatron-cockroachlabs, @maryliag, and @rafiss)

**Review by knz — COMMENTED** [review]
thanks, that works

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74706#-:-MtczZUqEIcfMIq2XKUG:b-7jz99x)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kpatron-cockroachlabs, @maryliag, and @rafiss)

**Comment by dhartunian** [comment]
@kpatron-cockroachlabs any further concerns?

**Review by kpatron-cockroachlabs — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/74706#-:-MtmjO4G9TRS5naOO_1x:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kpatron-cockroachlabs, @liamgillies, and @maryliag)

**Comment by dhartunian** [comment]
bors r=rafiss,kylepatron-cockroachlabs

**Pull request merged**
