### PR TITLE
sql: add builtins to construct and scan spans

### PR DESCRIPTION
**Pull request by stevendanna**
This adds crdb_internal.scan, a generating functions that returns the
raw keys and values contained in a span.

Additionally, it adds the following utility functions:

- crdb_internal.tenant_span
- crdb_internal.table_span
- crdb_internal.index_span
- crdb_internal.trim_tenant_prefix

These can be combined to create basic "tenant fingerprinting" queries:

    SELECT xor_agg(fnv64(key, value)) AS fingerprint
    FROM crdb_internal.scan(crdb_internal.tenant_span(2))

The current implementation of crdb_internal.scan is naive. It is a
small wrapper around txn.Scan. However, it still seems like a useful
first step and is likely good enough for use in medium scale tests and
it has already found a few small bugs.

Possible future work includes:

    - using ExportRequest instead of scan so we can also get all keys
      for some time range.

    - plumbing this further into the sql table reader or some new
      processor such that it can easily be distributed.

Release note: None

### CODE REVIEW

**Comment by stevendanna** [comment]
The implementation of `crdb_internal.scal` is dumb, but I've already caught a couple of bugs with this so perhaps it is good enough to start.

**Review by ajwerner — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83934)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy and @stevendanna)

___
*[`pkg/sql/sem/builtins/builtins.go` line 5244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnNpT96lODlJsU0LQ:-N6NnNpT96lODlJsU0LR:b-5yy5bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5244)):*
> ```Go
> 			},
> 			Info:       "This function assumes the given bytes are a CockroachDB key and trims any tenant prefix from the key.",
> 			Volatility: volatility.Immutable,
> ```

Call this LeakProof?
___
*[`pkg/sql/sem/builtins/builtins.go` line 5268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnNKP2IGp802Mhf-F:-N6NnNKP2IGp802Mhf-G:b-5yy5bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5268)):*
> ```Go
> 			},
> 			Info:       "This function assumes the given bytes are a CockroachDB key and trims any tenant prefix from the key.",
> 			Volatility: volatility.Immutable,
> ```

Call this LeakProof?
___
*[`pkg/sql/sem/builtins/builtins.go` line 5300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnMoT2tb6E0zVFpjT:-N6NnMoT2tb6E0zVFpjU:b-5yy5bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5300)):*
> ```Go
> 			},
> 			Info:       "This function returns the span that contains the keys for the given tenant.",
> 			Volatility: volatility.Immutable,
> ```

Call this LeakProof?
___
*[`pkg/sql/sem/builtins/builtins.go` line 5303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NmzFP1UoNApkZoRnJ:-N6NmzFP1UoNApkZoRnK:bjvbran) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5303)):*
> ```Go
> 		},
> 	),
> 	// TODO(ssd): Would this be more useful it it returned the primary index span?
> ```

:shrug: it's easy enough to look up the primary index. It'd change the volatility of this from LeakProof to Stable
___
*[`pkg/sql/sem/builtins/builtins.go` line 5331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnE0t6zx0-APdnafN:-N6NnE0t6zx0-APdnafO:b-5yy5bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5331)):*
> ```Go
> 			},
> 			Info:       "This function returns the span that contains the keys for the given table.",
> 			Volatility: volatility.Immutable,
> ```

Call this LeakProof?
___
*[`pkg/sql/sem/builtins/builtins.go` line 5365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnLkHCcdjAk6aPka1:-N6NnLkHCcdjAk6aPka2:b-5yy5bx) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5365)):*
> ```Go
> 			},
> 			Info:       "This function returns the span that contains the keys for the given index.",
> 			Volatility: volatility.Immutable,
> ```

Call this LeakProof?
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnQ7e00xg6-Z_tCYK:-N6NnQ7e00xg6-Z_tCYL:b-yxk5tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/generator_builtins.go#L138)):*
> ```Go
> 			},
> 			"Returns the raw keys and values from the specified span",
> 			volatility.Volatile,
> ```

I think this is Stable, no?
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnStX2uazpDXxthqZ:-N6NnStX2uazpDXxthq_:b-yxk5tb) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/generator_builtins.go#L167)):*
> ```Go
> 			},
> 			"Returns the raw keys and values from the specified span",
> 			volatility.Volatile,
> ```

I think this is Stable, no?
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1780 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnWNDDij52nHoP8JO:-N6NnWNDDij52nHoP8JP:b-iukzzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/generator_builtins.go#L1780)):*
> ```Go
> const rangeKeyIteratorChunkSize = 256
> 
> // const rangeKeyIteratorChunkSizeMB = 16 << 20 // 16MB
> ```

What's this about?
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1818 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnkJJAM60ZHIraVxO:-N6NnkJJAM60ZHIraVxP:b-mnjper) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/generator_builtins.go#L1818)):*
> ```Go
> func (sp *spanKeyIterator) Start(ctx context.Context, txn *kv.Txn) error {
> 	sp.txn = txn
> 	kvs, err := txn.Scan(ctx, sp.span.Key, sp.span.EndKey, rangeKeyIteratorChunkSize)
> ```

It'd be great if you could use the size limiting features we've added in terms of bytes and memory monitor this thing.

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83934)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @stevendanna)

___
*[`pkg/sql/sem/builtins/builtins.go` line 5244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnNpT96lODlJsU0LQ:-N6NtJVjEhyqHiFjF1zR:b-e4d51x) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5244)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Call this LeakProof?
</blockquote></details>

Ah, I wasn't sure of this for the trim_tenant_prefix and tenant_span functions because of this comment:


```
Any function that might throw an error depending on the values of its arguments is not leak-proof.
```
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnQ7e00xg6-Z_tCYK:-N6Nu3k35KBy_DgwQcTF:b-wbs4hr) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/generator_builtins.go#L138)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this is Stable, no?
</blockquote></details>

I think so. I think I copy/pasta'd this from the `crdb_internal.list_sql_keys_in_range`, which can probably also be listed as stable?

**Review by ajwerner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83934)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @stevendanna)

___
*[`pkg/sql/sem/builtins/builtins.go` line 5244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnNpT96lODlJsU0LQ:-N6OJ0sE-uY04YaYXtql:b-z8nk9n) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5244)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

Ah, I wasn't sure of this for the trim_tenant_prefix and tenant_span functions because of this comment:


```
Any function that might throw an error depending on the values of its arguments is not leak-proof.
```


</blockquote></details>

whoops, yeah, you're right, though I don't know how `Append` fails.

**Review by stevendanna — COMMENTED** [review]
> Do you think it's possible to add to e.g. pkg/sql/logictest/testdata/logic_test/builtin_function to add some test coverage for those?

Gah, yes, already written but I failed to git-add. Thank you!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-:-N6OJUWo-k55LL5CE8UJ:bq6ulwr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @miretskiy, and @stevendanna)

**Review by stevendanna — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83934)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

*[a discussion](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6qn9lQ4gfNdma9Gljy:-N6qn9lQ4gfNdma9Gljz:b-78cdvi) (no related file):*
Apologies for the delay. The updates to the logictests have been pushed and basic memory monitoring added.

___
___
*[`pkg/sql/sem/builtins/builtins.go` line 5244 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnNpT96lODlJsU0LQ:-N6qlsTKAB3AzA4IKpz-:b-wf06jn) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5244)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

whoops, yeah, you're right, though I don't know how `Append` fails. 
</blockquote></details>

Kept this Immutable, but moves those that only fail because of Append to Leakproof.  Append seems to  only fail for problems related to the size or type of the input, which we control.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5268 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnNKP2IGp802Mhf-F:-N6qm9872WC7q1MZooEm:bt2nr48) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5268)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Call this LeakProof?
</blockquote></details>

Not marking as LeakProof because it can error based on the arguments.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5300 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnMoT2tb6E0zVFpjT:-N6qmJED8TE35DucIqVs:b-6g4bjr) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5300)):*
> Not marking as LeakProof because it can error based on the arguments.
Not marking as LeakProof because it can error based on the arguments.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5303 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NmzFP1UoNApkZoRnJ:-N6qmZpy47moOQXkDT7P:b-qzngbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5303)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

:shrug: it's easy enough to look up the primary index. It'd change the volatility of this from LeakProof to Stable
</blockquote></details>

I think it's fine as is.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5331 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnE0t6zx0-APdnafN:-N6qmcmx7erfHU8O1NPZ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5331)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Call this LeakProof?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/builtins.go` line 5365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnLkHCcdjAk6aPka1:-N6qmdHs1eHa4GMISLFS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/builtins.go#L5365)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Call this LeakProof?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 138 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnQ7e00xg6-Z_tCYK:-N6qmeZr8wMrhRyJCnh-:b-ylixj) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/generator_builtins.go#L138)):*
<details><summary><i>Previously, stevendanna (Steven Danna) wrote…</i></summary><blockquote>

I think so. I think I copy/pasta'd this from the `crdb_internal.list_sql_keys_in_range`, which can probably also be listed as stable?
</blockquote></details>

Marked these as stable but didn't change list_sql_keys_in_range because the fact that the range bounds could change made me suspect it was Stable.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 167 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnStX2uazpDXxthqZ:-N6qmqL46tuNqS-7PsdD:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/generator_builtins.go#L167)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think this is Stable, no?
</blockquote></details>

Done.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1780 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnWNDDij52nHoP8JO:-N6qmrk63pnxSjwmr46G:b-8soxwn) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/generator_builtins.go#L1780)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

What's this about?
</blockquote></details>

This is now used to set the size limit for the scan.
___
*[`pkg/sql/sem/builtins/generator_builtins.go` line 1818 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-N6NnkJJAM60ZHIraVxO:-N6qmy-w8oxeuPEkzN46:bs08o6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/944b866f6aa7def9e39d0586915255126e6e1a87/pkg/sql/sem/builtins/generator_builtins.go#L1818)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

It'd be great if you could use the size limiting features we've added in terms of bytes and memory monitor this thing. 
</blockquote></details>

Done. Well, we now reserve some memory up front and set the TargetBytes on the request.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/83934#-:-N6s-QXs-8QxNO7QsPrE:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner and @miretskiy)

**Comment by stevendanna** [comment]
bors r=ajwerner

**Pull request merged**
