### PR TITLE
sqlmigrations: prevent schema change noise upon cluster creation

### PR DESCRIPTION
**Pull request by knz**
First commit from  #46829.
Informs #46757.

The system.comments is now created without write permission to
public. No need to re-do that change on every new cluster.

Release note: None

### CODE REVIEW

**Review by thoszhang — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46832)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

**Comment by knz** [comment]
bors r=lucy-zhang

**Comment by knz** [comment]
bors r=lucy-zhang

**Comment by knz** [comment]
lemme take this out of the queue until its CI finishes

bors r-

**Comment by knz** [comment]
bors r=lucy-zhang

**Comment by lucy-zhang** [comment]
@knz did you intend for that first commit to be included?

**Comment by knz** [comment]
yes - it didn't pass CI otherwise. But that first commit is currently being merged by bors so it will be in the master branch by the time bors gets to this.

**Comment by lucy-zhang** [comment]
I figured that was the reason. It looks like they're queued up in the same batch, though, and I was wondering if bors handles that correctly (I guess I'll find out shortly).

**Comment by knz** [comment]
it does (I have used this before). In the occasional case where they don't fit in the same batch, it still all works out because git is clever at reusing commits when the SHAs are identical.

**Pull request merged**
