### PR TITLE
Revert "TxnCoordSender's heartbeat uses Context cancellation when available"

### LINKED ISSUE #5559: timeout in sql TestLogic, txn:197
https://circleci.com/gh/cockroachdb/cockroach/15215

https://circle-artifacts.com/gh/cockroachdb/cockroach/15215/artifacts/0/tmp/circle-artifacts.EVY4hXL/test.log
Delays in this test: https://github.com/cockroachdb/cockroach/blob/master/sql/testdata/txn

We have a transaction that apparently gets stuck due to an earlier, aborted txn.
```
BEGIN TRANSACTION
UPDATE kv SET v = 'b' WHERE k in ('a')
BEGIN TRANSACTION    <-- error here as expected
...
ROLLBACK TRANSACTION
... some unrelated stuff ...

BEGIN TRANSACTION
UPDATE kv SET v = 'b' WHERE k in ('a')      <--- this gets stuck until the test times out some 40 seconds later
```

```
testdata/txn:197 root: UPDATE kv SET v = 'b' WHERE k in ('a')
I160324 22:11:13.051400 storage/replica_command.go:1086  failed to push "sql/executor.go:380 sql txn" id=c82252c9 key=/Table/51/1/"a"/2/1 rw=true pri=0.03126385 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.046150991,0 orig=1458857473.046150991,0 max=1458857473.046150991,0 wto=false
W160324 22:11:13.051738 kv/dist_sender.go:676  failed to invoke PushTxn [/Table/51/1/"a"/2/1,/Min): txn "sql/executor.go:380 sql txn" id=e4cfa1bb key=/Min rw=false pri=0.02541374 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.050232167,0 orig=1458857473.050232167,0 max=1458857473.050232167,0 wto=false failed to push "sql/executor.go:380 sql txn" id=c82252c9 key=/Table/51/1/"a"/2/1 rw=true pri=0.03126385 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.046150991,0 orig=1458857473.046150991,0 max=1458857473.046150991,0 wto=false
I160324 22:11:13.051869 client/db.go:457  failed batch: txn "sql/executor.go:380 sql txn" id=e4cfa1bb key=/Min rw=false pri=0.08630948 iso=SERIALIZABLE stat=PENDING epo=1 ts=1458857473.050232167,0 orig=1458857473.050232167,0 max=1458857473.050232167,0 wto=false failed to push "sql/executor.go:380 sql txn" id=c82252c9 key=/Table/51/1/"a"/2/1 rw=true pri=0.03126385 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.046150991,0 orig=1458857473.046150991,0 max=1458857473.046150991,0 wto=false
I160324 22:11:13.051924 storage/intent_resolver.go:99  [node=1,store=1,range=1] on Scan: txn "sql/executor.go:380 sql txn" id=e4cfa1bb key=/Min rw=false pri=0.08630948 iso=SERIALIZABLE stat=PENDING epo=1 ts=1458857473.050232167,0 orig=1458857473.050232167,0 max=1458857473.050232167,0 wto=false failed to push "sql/executor.go:380 sql txn" id=c82252c9 key=/Table/51/1/"a"/2/1 rw=true pri=0.03126385 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.046150991,0 orig=1458857473.046150991,0 max=1458857473.046150991,0 wto=false
W160324 22:11:13.051983 storage/store.go:1671  conflicting intents on [/Table/51/1/"a"/2/1]: resolved? false
I160324 22:11:13.102662 storage/replica_command.go:1086  failed to push "sql/executor.go:380 sql txn" id=c82252c9 key=/Table/51/1/"a"/2/1 rw=true pri=0.03126385 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.046150991,0 orig=1458857473.046150991,0 max=1458857473.046150991,0 wto=false
W160324 22:11:13.103171 kv/dist_sender.go:676  failed to invoke PushTxn [/Table/51/1/"a"/2/1,/Min): txn "sql/executor.go:380 sql txn" id=e4cfa1bb key=/Min rw=false pri=0.02541374 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.050232167,0 orig=1458857473.050232167,0 max=1458857473.050232167,0 wto=false failed to push "sql/executor.go:380 sql txn" id=c82252c9 key=/Table/51/1/"a"/2/1 rw=true pri=0.03126385 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.046150991,0 orig=1458857473.046150991,0 max=1458857473.046150991,0 wto=false
I160324 22:11:13.103354 client/db.go:457  failed batch: txn "sql/executor.go:380 sql txn" id=e4cfa1bb key=/Min rw=false pri=0.03228220 iso=SERIALIZABLE stat=PENDING epo=1 ts=1458857473.050232167,0 orig=1458857473.050232167,0 max=1458857473.050232167,0 wto=false failed to push "sql/executor.go:380 sql txn" id=c82252c9 key=/Table/51/1/"a"/2/1 rw=true pri=0.03126385 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.046150991,0 orig=1458857473.046150991,0 max=1458857473.046150991,0 wto=false
I160324 22:11:13.103453 storage/intent_resolver.go:99  [node=1,store=1,range=1] on Scan: txn "sql/executor.go:380 sql txn" id=e4cfa1bb key=/Min rw=false pri=0.03228220 iso=SERIALIZABLE stat=PENDING epo=1 ts=1458857473.050232167,0 orig=1458857473.050232167,0 max=1458857473.050232167,0 wto=false failed to push "sql/executor.go:380 sql txn" id=c82252c9 key=/Table/51/1/"a"/2/1 rw=true pri=0.03126385 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.046150991,0 orig=1458857473.046150991,0 max=1458857473.046150991,0 wto=false
W160324 22:11:13.103514 storage/store.go:1671  conflicting intents on [/Table/51/1/"a"/2/1]: resolved? false
I160324 22:11:13.210310 storage/replica_command.go:1086  failed to push "sql/executor.go:380 sql txn" id=c82252c9 key=/Table/51/1/"a"/2/1 rw=true pri=0.03126385 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.046150991,0 orig=1458857473.046150991,0 max=1458857473.046150991,0 wto=false
W160324 22:11:13.210829 kv/dist_sender.go:676  failed to invoke PushTxn [/Table/51/1/"a"/2/1,/Min): txn "sql/executor.go:380 sql txn" id=e4cfa1bb key=/Min rw=false pri=0.02541374 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.050232167,0 orig=1458857473.050232167,0 max=1458857473.050232167,0 wto=false failed to push "sql/executor.go:380 sql txn" id=c82252c9 key=/Table/51/1/"a"/2/1 rw=true pri=0.03126385 iso=SERIALIZABLE stat=PENDING epo=0 ts=1458857473.046150991,0 orig=1458857473.046150991,0 max=1458857473.046150991,0 wto=false
```

This is the same issue noticed in https://github.com/cockroachdb/cockroach/issues/5376#issuecomment-198805820

### PR DESCRIPTION
**Pull request by vivekmenezes**
Reverts cockroachdb/cockroach#5447

causing frequent test failures

closes #5559

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5568)

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM. For reference, this is issue #5559

**Comment by tamird** [comment]
This doesn't fix the underlying issue. It's really pretty frustrating to
see PRs like this get merged win less than 20 minutes, when few people have
had a chance to comment.

There were 4 of us in gitter looking at this last night, and none of us
felt it was urgent to revert this. What was the impetus for doing this so
expediently?

**Comment by bdarnell** [comment]
It's important to keep the build green; I think it's good to be aggressive about reverting changes that cause test flakiness. If we leave them in then that's a drain on the whole team as people have to retry builds and it reduces confidence in the tests.

**Comment by RaduBerinde** [comment]
It doesn't fix the issue (which is why the issue itself is still open) but it avoids others running into the same failure. Not only does that cause headache for others but when tests fail already, new failures tend to slip through more easily.

This was not new code, it was a revert, making things equivalent to Dan simply having not merged his PR yet. I don't understand the frustration, what was there to comment? Did you need the change in master for some reason?

**Pull request merged**
