### PR TITLE
coldata: use flat bytes implementation instead of [][]byte

### LINKED ISSUE #40244: exec: issues with flat bytes implementation
There are some bugs with and concerns about the current flat bytes implementation, so I will be reverting to using `[][]byte` in the vectorized engine. Here are the problems I observed:
- [x] `Slice` method modifies the receiver in-place instead of creating a shallow sliced copy. This doesn't follow what happens to regular slices. I think the fix is quite simple, something along these lines:
```
func (b *Bytes) Slice(start, end int) *Bytes {
	if start < 0 || start > end || end > b.Len() {
		panic(fmt.Sprintf("invalid slice arguments: start=%d end=%d when Bytes.Len()=%d", start, end, b.Len()))
	}
	maxSetIndex := end - start - 1
	if start == end {
		maxSetIndex = 0
	}
	if maxSetIndex > b.maxSetIndex {
		maxSetIndex = b.maxSetIndex
	}
	return &Bytes{
		data:        b.data,
		offsets:     b.offsets[start:end],
		lengths:     b.lengths[start:end],
		maxSetIndex: maxSetIndex,
	}
}
```
- [x] `CopySlice` incorrectly overwrites data when `destIdx > b.maxSetIndex`. I've seen cases when `b.data` was overwritten because `b.offsets[destIdx] == 0` because we're not doing the check.
~- [ ] the fact that we’re not checking in `Get()` whether `i <= b.maxSetIndex` is suspicious~
~- [ ] overall, I think there should be more explicit bounds checks because we're allocating `offsets` and `lengths` of 1024 length, so what should be an out of bounds access succeeds when accessing those two which can then lead to an incorrect behavior (without a panic though).~
- [x] the interaction with nulls is also concerning. If we do start checking the value of `b.maxSetIndex`, then whenever a null value is set in a Bytes column, an empty byte slice will probably need to be appended in order to have the correct indices.

### PR DESCRIPTION
**Pull request by yuzefovich**
**coldata: use flat bytes implementation instead of [][]byte**

This commit reverts the revert of using []byte + offsets implementation
of two-dimensional byte slice. The original revert was done due to
several issues which will be addressed in the follow-up commits.

**coldata: fix a couple of issues with flat bytes implementation**

This commit fixes the following:
- Slice method no longer modifies the receiver in-place and returns
  a shallow copy instead (as regular slices do)
- in CopySlice, srcEndIdx has been updated to be "trimmed" so that
  offsets and lengths are not overwritten past the copied values.

**coldata: remove lengths slice from flat bytes implementation**

Previously, we would use offsets and lengths to store the
information about each of the []byte in the flat bytes.
However, that information was quite redundant since
b.lengths[i] = b.offsets[i+1] - b.offsets[i], and this commit
removes that redundancy.

Also, this commit fixes a problem with how NULLs are treated.
Previously, it was possible for offsets of flat bytes to get into
an "inconsistent" state - we assume that the offsets are
non-decreasing, but when a NULL value is set on the colexec.Vec,
then Bytes will not be notified of this. As a result, there were
"gaps" of unset zero values in offsets. Now we're actively
backfilling the offsets to maintain the invariant.

Fixes: #40244.

**colexec: add invariants checker during logic tests**

This commit adds an ability to plan vectorized invariants
checkers while running the logic tests (in all configs except
for when the vectorized engine is disabled). The only invariants
that are currently being checked are that the batches are of correct
width and that all byte slices (up to the length of the batch) can be
retrieved from the flat bytes implementation.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
I added an invariants checker during logic tests run.

**Review by asubiotto — DISMISSED** [review]
Will take a closer look at the new `bytes.go` in another pass.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, 6 of 6 files at r3, 6 of 6 files at r4, 2 of 2 files at r5, 6 of 6 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-:-LryskpT4xXAA6Ss2Khe:bnel87y)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LrtlRyh8Ksosx0sdMfk:-LrtlRyh8Ksosx0sdMfl:bcbjw7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e29c0b589fc813fb0260dd86cd641e2f1336d7/pkg/col/coldata/bytes.go#L97)):*
> ```Go
> 		maxSetIndex = 0
> 	}
> 	if maxSetIndex > b.maxSetIndex-start {
> ```

Do we need to backfill up to the new max set index in this case? This seems to imply that `end > b.maxSetIndex`, meaning that if we don't backfill, we might get an empty `data` below because we'll access an uninitialized offset. You might have done this in a later commit, but I'll just keep this comment here
___
*[pkg/col/coldata/bytes.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrtvc5z462g-PSZ3FgW:-Lrtvc5z462g-PSZ3FgX:bwdhj08) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e29c0b589fc813fb0260dd86cd641e2f1336d7/pkg/col/coldata/bytes.go#L183)):*
> ```Go
> 	// number of bytes.
> 	if destIdx != 0 {
> 		b.data = append(b.data[:b.offsets[destIdx-1]+b.lengths[destIdx-1]], srcDataToCopy...)
> ```

Why is this `destIdx-1`? won't this append overwrite more than we want:
```
func main() {
	a := []int{0,1}
	fmt.Println("Hello, playground", append(a[:1], 2))
}
---
Hello, playground [0 2]
```
___
*[pkg/col/coldata/bytes.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LruDI6f6QkivdF4tXiX:-LruDI6f6QkivdF4tXiY:b-xchdb) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f0b696073847ccbadf042bb1156c1d9036d608e/pkg/col/coldata/bytes.go#L56)):*
> ```Go
> 	prev := int32(0)
> 	for j := uint64(0); j <= n; j++ {
> 		if b.offsets[j] == 0 {
> ```

It might be less error prone to actually check that the offsets are non-decreasing, not just 0.
___
*[pkg/col/coldata/bytes_test.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrtxr3H9--gZpBLi6P4:-Lrtxr3H9--gZpBLi6P5:b-n8ua29) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e29c0b589fc813fb0260dd86cd641e2f1336d7/pkg/col/coldata/bytes_test.go#L101)):*
> ```Go
> 			// Generate a length-inclusive destIdx.
> 			destIdx := rng.Intn(n + 1)
> 			// Make a pair of sources to copy/append from.
> ```

We're not testing self-referencing sources anymore? I think it's important to still do so.
___
*[pkg/sql/colexec/columnarizer.go, line 116 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LrtyUja-RNyJ5r14WY8:-LrtyUja-RNyJ5r14WY9:b5m35sn) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f0b696073847ccbadf042bb1156c1d9036d608e/pkg/sql/colexec/columnarizer.go#L116)):*
> ```Go
> 		}
> 	}
> 	c.batch.SetLength(nRows)
> ```

Hmm, having to `SetLength` after setting the elements is an interesting and unfortunate case, not sure what to immediately do about it though.
___
*[pkg/sql/colexec/invariants_checker.go, line 49 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lryr5Bu1JdEf6ufghRf:-Lryr5Bu1JdEf6ufghRg:b-z3mgdy) ([raw file](https://github.com/cockroachdb/cockroach/blob/51caab9149caee7170a1338789679d926ec1c2a1/pkg/sql/colexec/invariants_checker.go#L49)):*
> ```Go
> 			// For flat bytes implementation we want to make sure that offsets are
> 			// non-decreasing. We can check that by retrieving all []byte slices up
> 			// to the length of the batch.
> ```

Let's consider an example: ["hello", NULL]. Let's say the offsets are in violation of this invariant, so the NULL offset is uninitialized: [0, 5, 0]. Would we just expect it to panic with an invalid slice index? I think it might be clearer to delegate to some helper function in `bytes.go` that explicitly checks for this invariant rather than implicitly assuming we'll get a panic.
___
*[pkg/sql/colexec/mergejoiner.go, line 447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lru9wDy8MubsVTo6JL3:-Lru9wDy8MubsVTo6JL4:bx8d9a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f0b696073847ccbadf042bb1156c1d9036d608e/pkg/sql/colexec/mergejoiner.go#L447)):*
> ```Go
> 	// adjust its length.
> 	bufferedGroup.length += uint64(groupLength)
> 	for _, v := range bufferedGroup.colVecs {
> ```

Can we avoid doing this explicitly? Maybe by calling `bufferedGroup.SetLength` somewhere?
___
*[pkg/workload/bench_test.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LruAYvl0sFycVIKmNws:-LruAYvl0sFycVIKmNwt:bk94uva) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f0b696073847ccbadf042bb1156c1d9036d608e/pkg/workload/bench_test.go#L34)):*
> ```Go
> 		var bytes int64
> 		colBytes := col.Bytes()
> 		colBytes.EnforceNonDecreasingOffsets(uint64(colBytes.Len()))
> ```

I would try to avoid having any code that isn't `SetLength` worry about non decreasing offsets. Can we avoid calling `EnforceNonDecreasingOffsets` here?

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/col/coldata/bytes.go, line 97 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LrtlRyh8Ksosx0sdMfk:-Lrz2ph86YpEdRvOmGCC:bbzp04v) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e29c0b589fc813fb0260dd86cd641e2f1336d7/pkg/col/coldata/bytes.go#L97)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we need to backfill up to the new max set index in this case? This seems to imply that `end > b.maxSetIndex`, meaning that if we don't backfill, we might get an empty `data` below because we'll access an uninitialized offset. You might have done this in a later commit, but I'll just keep this comment here
</blockquote></details>

We are backfilling in the beginning of this method, and then we're making sure that `maxSetIndex` does not exceed `b.maxSetIndex`, so all offsets in `b.offsets[start:end+1]` should all be set.
___
*[pkg/col/coldata/bytes.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrtvc5z462g-PSZ3FgW:-Lrz3oSV-r1Rq4wSsLHK:bwzv8it) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e29c0b589fc813fb0260dd86cd641e2f1336d7/pkg/col/coldata/bytes.go#L183)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is this `destIdx-1`? won't this append overwrite more than we want:
```
func main() {
	a := []int{0,1}
	fmt.Println("Hello, playground", append(a[:1], 2))
}
---
Hello, playground [0 2]
```
</blockquote></details>

I think this is addressed in the later commits. The intermediate commits probably have bugs (I saw some logic tests failures), but I decided not to figure them out, and, instead, do the offsets-only implementation and debug that right away.
___
*[pkg/col/coldata/bytes.go, line 56 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LruDI6f6QkivdF4tXiX:-Lrz1R8rBjNp95uegTkd:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f0b696073847ccbadf042bb1156c1d9036d608e/pkg/col/coldata/bytes.go#L56)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It might be less error prone to actually check that the offsets are non-decreasing, not just 0.
</blockquote></details>

Good point, done.
___
*[pkg/col/coldata/bytes_test.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrtxr3H9--gZpBLi6P4:-LrzQ5zp4qbXUEKrXVmF:b-523dg9) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e29c0b589fc813fb0260dd86cd641e2f1336d7/pkg/col/coldata/bytes_test.go#L101)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We're not testing self-referencing sources anymore? I think it's important to still do so.
</blockquote></details>

I'll look into it.
___
*[pkg/sql/colexec/columnarizer.go, line 116 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LrtyUja-RNyJ5r14WY8:-Lrz5qex25q7sBc8uln6:b-ltglip) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f0b696073847ccbadf042bb1156c1d9036d608e/pkg/sql/colexec/columnarizer.go#L116)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Hmm, having to `SetLength` after setting the elements is an interesting and unfortunate case, not sure what to immediately do about it though.
</blockquote></details>

I have the same feelings :/
___
*[pkg/sql/colexec/invariants_checker.go, line 49 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lryr5Bu1JdEf6ufghRf:-Lrz63qmE1kr1URvC7e2:b8cnlm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/51caab9149caee7170a1338789679d926ec1c2a1/pkg/sql/colexec/invariants_checker.go#L49)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Let's consider an example: ["hello", NULL]. Let's say the offsets are in violation of this invariant, so the NULL offset is uninitialized: [0, 5, 0]. Would we just expect it to panic with an invalid slice index? I think it might be clearer to delegate to some helper function in `bytes.go` that explicitly checks for this invariant rather than implicitly assuming we'll get a panic.
</blockquote></details>

Yes, it would panic on `bytes.Get(1)` because it would do `b.data[b.offsets[1] : b.offsets[2]]` equivalent to `b.data[5:0]`, but I agree with your point. I moved the logic into `bytes.go`.
___
*[pkg/sql/colexec/mergejoiner.go, line 447 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lru9wDy8MubsVTo6JL3:-Lrz6Wh1DAswSx0Zly4x:b5ohhjl) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f0b696073847ccbadf042bb1156c1d9036d608e/pkg/sql/colexec/mergejoiner.go#L447)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Can we avoid doing this explicitly? Maybe by calling `bufferedGroup.SetLength` somewhere?
</blockquote></details>

The problem is that we have `uint64`, but `batch.SetLength` takes in`uint16`, so we would need to modify the interface. I'm not sure whether it would be better than this option. What do you think?
___
*[pkg/workload/bench_test.go, line 34 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LruAYvl0sFycVIKmNws:-LrzO6kn3haJFWFRog27:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4f0b696073847ccbadf042bb1156c1d9036d608e/pkg/workload/bench_test.go#L34)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I would try to avoid having any code that isn't `SetLength` worry about non decreasing offsets. Can we avoid calling `EnforceNonDecreasingOffsets` here?
</blockquote></details>

Done.

**Review by asubiotto — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, and @yuzefovich)

___
*[pkg/col/coldata/bytes.go, line 30 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrz2_c0EASKh3scdN0U:-Lrz2_c0EASKh3scdN0V:bx76dqi) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5a6170496b41cc112ebd2a73bde9d6e0e550b2/pkg/col/coldata/bytes.go#L30)):*
> ```Go
> 	// maxSetIndex specifies the last index set by the user of this struct. This
> 	// enables us to disallow unordered sets (which would require data movement).
> 	// Also, this helps us in maintains the assumption of non-decreasing offsets.
> ```

`s/this helps us in maintains/this helps us maintain`
___
*[pkg/col/coldata/bytes.go, line 66 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrz5Qsq9E5nhxiinx1Y:-Lrz5Qsq9E5nhxiinx1Z:b-kck4le) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5a6170496b41cc112ebd2a73bde9d6e0e550b2/pkg/col/coldata/bytes.go#L66)):*
> ```Go
> // maybeBackfillOffsets is an optimized version of EnforceNonDecreasingOffsets
> // that assumes that all offsets up to b.maxSetIndex+1 are non-decreasing.
> func (b *Bytes) maybeBackfillOffsets(i int) {
> ```

We should probably remove `maybe` from the method name, since there is no condition.
___
*[pkg/col/coldata/bytes.go, line 66 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LrzRBnH48u5hh3tM4Z4:-LrzRBnH48u5hh3tM4Z5:b-bj8u45) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5a6170496b41cc112ebd2a73bde9d6e0e550b2/pkg/col/coldata/bytes.go#L66)):*
> ```Go
> // maybeBackfillOffsets is an optimized version of EnforceNonDecreasingOffsets
> // that assumes that all offsets up to b.maxSetIndex+1 are non-decreasing.
> func (b *Bytes) maybeBackfillOffsets(i int) {
> ```

Also, is there some check we could add to the reference implementation test as well to double check this invariant? The reference test uses flat bytes in a novel way due to its randomness. We should also make sure to run `make stress` on the reference test for a bit before merging this PR.
___
*[pkg/col/coldata/bytes.go, line 68 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LrzQfGZ63cJ-lCSHNzX:-LrzQfGZ63cJ-lCSHNzY:bzbw03v) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5a6170496b41cc112ebd2a73bde9d6e0e550b2/pkg/col/coldata/bytes.go#L68)):*
> ```Go
> func (b *Bytes) maybeBackfillOffsets(i int) {
> 	for j := b.maxSetIndex + 2; j <= i; j++ {
> 		b.offsets[j] = b.offsets[b.maxSetIndex+1]
> ```

Do we need to update the `maxSetIndex` in this case?
___
*[pkg/col/coldata/bytes.go, line 82 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrz2t_pEpcsF7herTIU:-Lrz2t_pEpcsF7herTIV:b-f2pr52) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5a6170496b41cc112ebd2a73bde9d6e0e550b2/pkg/col/coldata/bytes.go#L82)):*
> ```Go
> // away necessary space in the flat buffer. Note that a nil value will be
> // "converted" into an empty byte slice.
> func (b *Bytes) Set(i int, v []byte) {
> ```

Could we maybe add some small unit tests that check the offsets invariant? I'm thinking
1) `Set(0, val)`, `Slice(0, 2)` to check offsets past the end of the known element
2) `Set(0, val)`, `Set(2, val)`, `Slice(0, 4)` to check offsets between two valid values and past the last known element.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41724)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

___
*[pkg/col/coldata/bytes.go, line 30 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrz2_c0EASKh3scdN0U:-LsJ03Sx10PseM-JEnPz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5a6170496b41cc112ebd2a73bde9d6e0e550b2/pkg/col/coldata/bytes.go#L30)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

`s/this helps us in maintains/this helps us maintain`
</blockquote></details>

Done.
___
*[pkg/col/coldata/bytes.go, line 66 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrz5Qsq9E5nhxiinx1Y:-LsJ04n1-JNpZyHu2Gsh:b-pkfw0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5a6170496b41cc112ebd2a73bde9d6e0e550b2/pkg/col/coldata/bytes.go#L66)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

We should probably remove `maybe` from the method name, since there is no condition.
</blockquote></details>

There is an implicit condition `if b.maxSetIndex + 1 < i`, so it is possible that this method will be a noop.
___
*[pkg/col/coldata/bytes.go, line 66 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LrzRBnH48u5hh3tM4Z4:-LsJ2fiE3mFbJIAgHuZ8:be4dkec) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5a6170496b41cc112ebd2a73bde9d6e0e550b2/pkg/col/coldata/bytes.go#L66)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Also, is there some check we could add to the reference implementation test as well to double check this invariant? The reference test uses flat bytes in a novel way due to its randomness. We should also make sure to run `make stress` on the reference test for a bit before merging this PR.
</blockquote></details>

I added the assertion that checks the invariant after each method is applied and ran the stress test for a couple of minutes with no failures.
___
*[pkg/col/coldata/bytes.go, line 68 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-LrzQfGZ63cJ-lCSHNzX:-LsJ10Q_D_9d35AaXBj2:b-kwtf99) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5a6170496b41cc112ebd2a73bde9d6e0e550b2/pkg/col/coldata/bytes.go#L68)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Do we need to update the `maxSetIndex` in this case?
</blockquote></details>

I think it is a responsibility of the caller to do so depending on the context. And in all places where we call `maybeBackfillOffsets` we do update `maxSetIndex` afterwards.
___
*[pkg/col/coldata/bytes.go, line 82 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrz2t_pEpcsF7herTIU:-LsJ4DsIE0OTS5qeFobi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df5a6170496b41cc112ebd2a73bde9d6e0e550b2/pkg/col/coldata/bytes.go#L82)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Could we maybe add some small unit tests that check the offsets invariant? I'm thinking
1) `Set(0, val)`, `Slice(0, 2)` to check offsets past the end of the known element
2) `Set(0, val)`, `Set(2, val)`, `Slice(0, 4)` to check offsets between two valid values and past the last known element.
</blockquote></details>

Done.
___
*[pkg/col/coldata/bytes_test.go, line 101 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-Lrtxr3H9--gZpBLi6P4:-LsJ-lmpEG996RdUYcBg:b-cayga1) ([raw file](https://github.com/cockroachdb/cockroach/blob/16e29c0b589fc813fb0260dd86cd641e2f1336d7/pkg/col/coldata/bytes_test.go#L101)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I'll look into it.
</blockquote></details>

Done. Bringing back self-referencing sources in the test actually uncovered a bug (updating `maxSetIndex` too early in case of self referencing source).

**Review by asubiotto — COMMENTED** [review]
:lgtm_strong: thanks for all your hard work in getting this in

> Reviewed 1 of 6 files at r8, 8 of 8 files at r11.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41724#-:-LsNMmSGCG5puPWvL7BO:b7v7onx)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @jordanlewis)

**Comment by yuzefovich** [comment]
Thanks for the reviews!

bors r+

**Pull request merged**
