### PR TITLE
colexec: refactor dynamic batching to pay attention to memory footprint

### LINKED ISSUE #68008: sql: unexpectedly high memory usage when sorting/joining wide rows
When sorting/joining wide rows (especially when spilling to disk) memory usage can get way higher than workmem, up to gigabytes per single query.

# To Reproduce

## sort

```sql
create table t (id primary key, t, v)
as
select gen_random_uuid(), now(), '{"value": "' || repeat('hi', 4 * 64 * 1024) || '"}'
from generate_series(1,1000) g(g);

analyze t;

explain analyze (distsql)
select * from t order by t desc;
```

This results in `max memory allocated: 1.5 GiB`. Notice that scratch disk usage is very low compared to that (24 MiB). Interestingly, if you query before statistics get calculated, the query is slower, but also uses less memory. (This is why we do `analyze t` in the repro)

The memory usage seems to scale linearly with the row width. With `repeat('hi', 64 * 1024 * 20)` you can even get `ERROR: internal error: unexpected error from the vectorized engine: runtime error: slice bounds out of range [:-2145375836]` (we're not interested in _that_ wide rows tho.)

## join

```sql
create table t1 (id primary key, n, v)
as
select gen_random_uuid(), 1, '{"value": "' || repeat('hi', 4 * 64 * 1024) || '"}'
from generate_series(1,1000) g(g);

create table t2 (n) as values (1);

analyze t1;

explain analyze (distsql)
select * from t1 inner join t2 on t1.n = t2.n;
```

This results in 518 MiB sql memory used.

# Expected behavior
We'd like memory usage to stay on the order of workmem.

# Environment
 - CockroachDB version 21.1.6
 - Server OS: linux/macOS
 - Client app `cockroach sql`

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: refactor dynamic batching to pay attention to memory footprint**

We use `Allocator.ResetMaybeReallocate` method in order to get the
"dynamic batch" behavior - meaning that the batches are of "dynamic"
size. Previously, the capacity argument to the method was the most
important - the contract of the method guaranteed that the batch will
have the requested capacity. This commit changes the contract so that if
we see that the old batch has already exceeded the specified maximum
memory footprint, then that batch will be reused, even if the desired
capacity is not satisfied.

This commit then updates the code in several places (all sorters and the
cross joiner) to take advantage of the new contract. In some places
I believe we don't want/need to use the limiting. A couple of other
places (the hash aggregator and the ordered synchronizer) will be
refactored in a follow-up commit.

Release note: None

**colexec: use SetAccountingHelper in the ordered sync and hash aggregator**

This commit refactors the ordered synchronizer and the hash aggregator
to take advantage of the recently introduced `SetAccountingHelper` in
order to have precise control on the output batch capacity based on the
memory footprint.

Release note: None

**colexec: improve partitioning logic in external sort**

Previously, `inputPartitioningOperator` - which decides when to start
a new partition for the external sort - operated on a batch granularity.
That meant that if the input batch significantly exceeded the target
memory limit, the operator would do nothing about it and return the
batch as is. This is suboptimal, and this commit changes the behavior so
that operator creates "windows" into an input batch if it notices that
returning the input batch as is would overshoot the target.

Release note: None

Fixes: #68008.

### CODE REVIEW

**Comment by yuzefovich** [comment]
The sort query in #68008 went down from 480MiB to 368MiB and the hash joiner one didn't change for the first commit, then the second commit brought down the sort query to 215MiB.

**Comment by yuzefovich** [comment]
Benchmarks of both commits are [here](https://gist.github.com/yuzefovich/ad30e86b6d929b5d31ace886c5fcc40f).

**Comment by yuzefovich** [comment]
Note to myself: for some reason `TestExternalDistinct` is failing non-deterministically.

**Comment by yuzefovich** [comment]
Miscellaneous microbenchmarks are [here](https://gist.github.com/yuzefovich/8dc48c94e1fd199e91ff435a0584c61a).

**Comment by yuzefovich** [comment]
Note that in the microbenchmarks we see a noticeable regression on the external hash aggregator benchmarks when spilling is forced and group sizes are small. This is expected due to the way we're forcing the spilling (by giving a memory limit of 1 byte) and is explained by the change in the second commit (now the in-memory hash aggregator will be returning batches of size 1). This is an artificial scenario and is safe to be ignored.

**Review by DrewKimball — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68092#-:-Mfu47vXBL4c_AsEkckl:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @yuzefovich)

___
*[pkg/sql/colexec/external_sort.go, line 709 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68092#-Mfu3cWe0rTfCOAEPVTa:-Mfu3cWe0rTfCOAEPVTb:b-p46j11) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e54b9abbfa729ff33c1f84d62d8cf108c4dddf8/pkg/sql/colexec/external_sort.go#L709)):*
> ```Go
> 		// batch is non-nil only if there are more rows to be emitted from the
> 		// last read batch.
> 		batch coldata.Batch
> ```

[nit] We should be nilling out this batch and the windowed batch in `Close`
___
*[pkg/sql/colexec/external_sort.go, line 782 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68092#-Mfu3jj81vGg4jRr36Ll:-Mfu3jj81vGg4jRr36Lm:b-88v4ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e54b9abbfa729ff33c1f84d62d8cf108c4dddf8/pkg/sql/colexec/external_sort.go#L782)):*
> ```Go
> // not nil and not all rows have been emitted from it.
> func (o *inputPartitioningOperator) emitWindowIntoLastBatch() coldata.Batch {
> 	// We use plus one so that this windowed batch reached the memory limit if
> ```

[nit] reached -> reaches
___
*[pkg/sql/colexec/colexecutils/utils.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68092#-Mfu3qT7DPbTp7pSFJVF:-Mfu3qT7DPbTp7pSFJVG:b-jv7yjf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e54b9abbfa729ff33c1f84d62d8cf108c4dddf8/pkg/sql/colexec/colexecutils/utils.go#L39)):*
> ```Go
> 		copy(windowedBatch.Selection(), windowIntoSel)
> 		maxSelIdx := 0
> 		for _, selIdx := range windowIntoSel {
> ```

[nit] Why are we iterating through the entire selection vector when it should be sorted in ascending order?

**Review by yuzefovich — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68092#-:-MfuFDKU5cXZjakoDvi-:b-oduykh)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @DrewKimball and @jordanlewis)

___
*[pkg/sql/colexec/external_sort.go, line 709 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68092#-Mfu3cWe0rTfCOAEPVTa:-MfuAU9UD5RHOZzCB-uf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e54b9abbfa729ff33c1f84d62d8cf108c4dddf8/pkg/sql/colexec/external_sort.go#L709)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] We should be nilling out this batch and the windowed batch in `Close`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/external_sort.go, line 782 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68092#-Mfu3jj81vGg4jRr36Ll:-MfuCHrp7Nakpd2qMjYB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e54b9abbfa729ff33c1f84d62d8cf108c4dddf8/pkg/sql/colexec/external_sort.go#L782)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] reached -> reaches
</blockquote></details>

Done.
___
*[pkg/sql/colexec/colexecutils/utils.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/68092#-Mfu3qT7DPbTp7pSFJVF:-MfuDsKM7M9Ito4GdKC1:b-ruuj2g) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e54b9abbfa729ff33c1f84d62d8cf108c4dddf8/pkg/sql/colexec/colexecutils/utils.go#L39)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Why are we iterating through the entire selection vector when it should be sorted in ascending order?
</blockquote></details>

Good point, refactored. I think this code was written before began relying on the invariant and was never updated.

**Pull request merged**
