### PR TITLE
[WIP] migrations: introduce new system which supports long-running migrations

### LINKED ISSUE #39182: *: long-running migrations
Backward compatibility is a necessary part of storage infrastructure, but we'd like to minimize the associated technical debt. Initially our migrations were one-off, required complicated reasoning, and under tested (example: the format version stuff that was added for column families and interleaved tables). Over time, we've added frameworks to help with this, but there's one notable gap in our story: long-running data migrations.

An example that's come up a number of times is rewriting all table descriptors in kv. An extreme example that we may have to do one day might be rewriting all data on disk.

Note that the format versions mentioned above do a mini-migration on each table descriptor as it enters the node (from kv, gossip, etc). Nothing guarantees that all table descriptors eventually get rewritten. So even though this has been around since before 1.0, the format version migrations have to stay around as permanent technical debt. The FK migration currently underway will have a similar problem.

The format version code is a small amount of debt, but it'd be nice to get rid of it. Other examples are not so simple. The learner replicas work in 19.2 replaces preemptive snapshots, but after we stop using preemptive snapshots, we need to completely flush them out of the system before the code can be deleted. One of these places is an interim state between when a preemptive snapshot has been written to rocksdb and when raft has caught up enough to make it into a real replica. To flush these out, after we stop sending preemptive snapshots, we'll need to iterate each range descriptor in kv and ensure that it is finished being added or is removed.

More examples from @tbg:
- GenerationComparable (make sure that 20.1 can assume that there are no legacy generations out there) - not yet sure how exactly this is achieved but should be doable
- the various Raft migrations (RangeAppliedState, unreplicated truncated state, etc) which all boil down to "run something through Raft until they're all active on all ranges but 99.99% sure they're all active already anyway"

We currently have two main frameworks for migrations. They go by different names in various places, but I'll call them startup migrations and cluster versions.

## Startup Migrations

Startup migrations (in package pkg/sqlmigrations and called "Cluster Upgrade Tool" by the RFC) are used to ensure that some backwards-compatible hook is run before the code that needs it. An example of this is adding a new system table. A node that doesn't know about a system table simply doesn't use it, so it's safe to add one in a mixed version cluster.

When the first node of the new version starts up and tries to join the cluster, it notices that the migration hasn't run, runs it, and saves the result durably in kv. Any nodes that start after see that the migration has been run and skip it.

If a second node of the new version tries to join the cluster before the migration has completed, it blocks until the migration finishes. This means that startup migrations need to be relatively quick. In an ideal world, every user would do version upgrades with a rolling restart, waiting for each node to be healthy and settled before moving on. But it's not Making Data Easy if a non-rolling restart blocks every node on some extremely long startup migration, causing a total outage.

On the other hand, by running at startup, all code in the new version can assume that startup migrations have been run. This means there doesn't need to be a fallback path and that any old code can be deleted immediately.

## Cluster Versions

Cluster versions are a special case of our gossip-based configuration settings. They allow for backward-incompatible behaviors to be gated by a promise from the user that they'll never downgrade. An example of this is adding a field to an existing rpc request protobuf. A node doesn't want to send such a request until it is sure that it will be handled correctly on the other end. Because of protobuf semantics, if it went to an old node, the field would be silently ignored.

Cluster versions tie together two concepts. First, a promise to the user that we don't have to worry about rpc or disk compatibility with old versions anymore. Second, a feature gate that is unlocked by that promise. There is an ordered list of these, one for each feature being gated.

Because the feature gate is initially off when a new version is rolled onto, each check of the gate needs to have a fallback. New features can return an error informing the user to finish the upgrade and bump the version, but other uses need to keep old code around for a release cycle.

Aside: To make it easier for users that don't want the control, the cluster version is automatically bumped some period of time after all nodes have been upgraded. A setting is available to disable this for users that want to keep the option to roll back until they've manually signed off on the new version.

# Data Migrations

Summary: I propose a partial unification of these two systems. To avoid having three migration frameworks, they will be based on and replace Cluster Versions. Separate the two ClusterVersion concepts described above so that we can execute potentially long-running hooks in between.

The interface presented to the user is essentially the same, but slightly expanded. After rolling onto a new version of cockroach, some features are not available until the cluster version is bumped. Either the user does this manually or the auto-upgrade does. Instead of the version bump finishing immediately, a system job is created to do the upgrade, enabling the feature gates as it progresses. This is modeled as a system job both to make sure only one coordinator is running as well as exposing progress to the user. Once the job finishes (technically as each step finishes) the gated features become available to the user.

The interface presented to CockroachDB developers is also mostly the same. Each version in the list is now given the option of including a hook, which is allowed to take a while (TODO be more specific) to finish.

Details: 
- The hook, if given, runs _after_ the feature gate is enabled. This simple building block can be used to build more complex migrations by using multiple gate+hook features.
- To make it simpler to reason about the code that goes in the hook, the system guarantees that the gate has been pushed to every node in the system. That is, every `IsActive(feature)` check will _always_ return true on every node from now on. This was not previously guaranteed and the implementation is mostly tricky around handling nodes that are unavailable when the gate is pushed.
- Like startup migrations, the hook must be idempotent.
- Complications such as flushing caches, etc are left to the hooks. If any compelling patterns emerge, they could be baked into the framework in the future.
- Startup migrations then conceptually become very similar to this. They currently implement their own coordinator leasing system and there is an opportunity for code unification by moving them to this new system job type.

Side node: This is all very nearly the long-term vision laid out in https://github.com/cockroachdb/cockroach/blob/master/docs/RFCS/20161024_cluster_upgrade_tool.md

Note to self: https://reviewable.io/reviews/cockroachdb/cockroach/38932#-LlaULyp9sd2JS_tyaKi:-LlaULyp9sd2JS_tyaKj:bfh2kib

### PR DESCRIPTION
**Pull request by danhhz**
This subsumes the cluster version cluster setting. There is a large
overlap with pkg/sqlmigrations, which should be cleaned up in the
future.

Closes #39182

Release note (<category, see below>): <what> <show> <why>

### CODE REVIEW

**Comment by danhhz** [comment]
@tbg this is a very early draft and mostly unfinished, but I wanted to get it out in time to get your initial feedback tomorrow

**Review by tbg — COMMENTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44249)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz)

___
*[pkg/migration/migration.go, line 52 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM6cMz0DpS-NMchPHt:-LzM6cMz0DpS-NMchPHu:b-hb9dh7) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/migration/migration.go#L52)):*
> ```Go
> }
> 
> func init() {
> ```

We've amassed a larger list of migrations that fit this bill, right? For me personally I think the most useful thing would be to see them all stubbed out here, to have a good sample of the kinds of things we're expecting the migrations to need to do. The separate raft log engine migration for example, or some migration that uses https://github.com/cockroachdb/cockroach/pull/42822, and whatever other ones we've mentioned.
___
*[pkg/migration/connect/connect.go, line 30 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM01Ro-INQzyhncfWJ:-LzM01Ro-INQzyhncfWK:b-6x9mq5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/migration/connect/connect.go#L30)):*
> ```Go
> 	// (filtering out self, etc). On one hand it'd be nice to keep this from
> 	// depending on gossip (so the response could be _used_ by gossip), but it
> 	// would be unfortuante to duplicate this initial work.
> ```

Yeah the joining process is quite complex (think about resolvers, etc), that was also my main worry over in https://github.com/cockroachdb/cockroach/issues/32574
It's worth figuring out whether we're allowed to simplify the semantics. Such as: a node that starts up must be able to reach another initialized (or soon to be initialized) node via its join flags. For example it would be illegal to start a new node with only bogus join flags and to rely on it being mentioned in other nodes' join flags (who could then reach out to it).
___
*[pkg/migration/everynode/everynode.go, line 72 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM2YPC0m7J_qbpg3IE:-LzM2YPC0m7J_qbpg3IF:bprralg) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/migration/everynode/everynode.go#L72)):*
> ```Go
> // RunHookOnEveryNode executes the requested hook closure on each node in the
> // cluster and each node added to the cluster in the future. If no error is
> // returned, the caller is guaranteed that no node will ever again serve SQL or
> ```

Make this stronger: connect to the cluster

Lots of stuff happens before "serving SQL or KV traffic". We want to preempt all of the moving parts here.
___
*[pkg/migration/everynode/everynode.go, line 79 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM2gya9dg2eTh7LYG7:-LzM2gya9dg2eTh7LYG8:b-nnjn9s) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/migration/everynode/everynode.go#L79)):*
> ```Go
> // RPC and returned a successful response.
> //
> // WIP how do we communicate to the user if this is blocking while a node is
> ```

I was hoping the job could have a good description of where it's at, but maybe that's not enough
___
*[pkg/migration/everynode/everynode.go, line 82 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM2qjW9i6Z-XvfnIsx:-LzM2qjW9i6Z-XvfnIsy:b-623ln1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/migration/everynode/everynode.go#L82)):*
> ```Go
> // down?
> //
> // WIP what about nodes that are decommissioned and later re-added? Is this even
> ```

It's "legal" today but won't be legal in the future. If we wanted to prevent this, we add a NodeID graveyard against which the incoming `Connect` calls are checked (init'ed nodes will put their NodeID into the RPC). As is, we'd be relying on the operator to just not bring decommissioned nodes back, which I agree we'll ultimately have to fix.
___
*[pkg/migration/fflag/fflag.go, line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM3KGeDWcYIpVXhOld:-LzM3KGeDWcYIpVXhOle:bupohmk) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/migration/fflag/fflag.go#L39)):*
> ```Go
> //
> // WIP how does this work for cluster init? separate method in this package?
> func GetHandle(bootVersion ClusterVersion) *Handle {
> ```

NewHandle?
___
*[pkg/migration/fflag/fflag.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM3NY361RALAoEnLb9:-LzM3NY361RALAoEnLbA:b-o5d0s2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/migration/fflag/fflag.go#L47)):*
> However, a feature that is active once is guaranteed to be active for eternity.

Still true, right? Regarding the "feature flag" framing, are feature flags generally thought of as reversible? Because here they aren't. In general, as we release new functionality, as long as it's a true feature flag, this means we'd keep it out of.. these feature flags (but use a cluster setting or such instead)? I wonder if that could be confusing - the only feature flags that we have in the migrations are the non-reversible ones, but I'm not so sure I'd think of them as "feature flags" any more... it's more of a multi-frontier migration, where you can migrate into features individually.

I read https://martinfowler.com/articles/feature-toggles.html to gut-check my intuition and there it seems that a "feature flag" should be a simple switch that goes both ways. So maybe we should reconsider the naming here and stick to "migrations" naming while perhaps in the future adding a separate mechanism for true feature flags once we feel that is something we need (not today).
___
*[pkg/migration/fflag/fflag.go, line 97 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM4bMB7BX8DxRNBp1K:-LzM4bMB7BX8DxRNBp1L:ba447jz) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/migration/fflag/fflag.go#L97)):*
> ```Go
> 		Version: roachpb.Version{Major: 19, Minor: 2, Unstable: 3},
> 	},
> 	{
> ```

Since we're here, it has always bothered me that this was growing the wrong direction. It'd be easier if wereversed this, then the VersionKey and the new version are next to each other in code.
___
*[pkg/server/server.go, line 213 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM5Owy9kLWWUl7t5K6:-LzM5Owy9kLWWUl7t5K7:b-mun4zw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/server/server.go#L213)):*
> ```Go
> func NewServer(cfg Config, stopper *stop.Stopper) (*Server, error) {
> 	// WIP do we know way up here whether this node is bootstrapping the cluster
> 	// or not?
> ```

No, that happens only way down, when we `.start` the `Node`:

https://github.com/cockroachdb/cockroach/blob/46a38c9c9d4d7314b9ca5e22358668caea7da07c/pkg/server/server.go#L1341-L1368

There's no reason this couldn't be lifted, though. Note also that the logic will simplify after https://github.com/cockroachdb/cockroach/pull/44112: if we have no initialized engines, we go into init mode (i.e. wait for a bootstrap cmd or for one of our peers to become initialized). If there are init'ed engines, we're already set up. So no need to look at the join flags, though it raises the question of what it means to start a node without a join flag.

The natural sequencing here is to let Raphael's PR merge (quite a bit of work involved in that one, too). Then, pull out the determination of whether to bootstrap out into something we can query before the call to `Connect`. If we're bootstrapped, send NodeID in connect (otherwise don't and let Connect alloc a NodeID and StoreIDs for you). This actually boils down cleanly to "do https://github.com/cockroachdb/cockroach/issues/32574"? Adding the migration stuff you need should be straightforward after that.

By the way, I would be quite excited to have that happen. That work item has always gotten in the way of seriously thinking about cleaning up our server startup code.
___
*[pkg/server/server.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM4uY_-x3RiXnez1iF:-LzM4uY_-x3RiXnez1iG:b-9o84b5) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/server/server.go#L556)):*
> ```Go
> 		txnMetrics, nil /* execCfg */, &s.rpcContext.ClusterID)
> 
> 	// WIP is this too late in the boot process?
> ```

Yeah definitely, but also what can be in a hook? You want to run this early (to avoid setting up all of those moving parts), so all you'll have is the slice of `engine.Engine`s, you can't do KV, you don't have your `*Node` or even your `*Server` set up.

**Review by danhhz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/44249)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @danhhz and @tbg)

___
*[pkg/migration/fflag/fflag.go, line 47 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM3NY361RALAoEnLb9:-LznzQX6CzPLcRxM45--:bncfm1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/migration/fflag/fflag.go#L47)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

> However, a feature that is active once is guaranteed to be active for eternity.

Still true, right? Regarding the "feature flag" framing, are feature flags generally thought of as reversible? Because here they aren't. In general, as we release new functionality, as long as it's a true feature flag, this means we'd keep it out of.. these feature flags (but use a cluster setting or such instead)? I wonder if that could be confusing - the only feature flags that we have in the migrations are the non-reversible ones, but I'm not so sure I'd think of them as "feature flags" any more... it's more of a multi-frontier migration, where you can migrate into features individually.

I read https://martinfowler.com/articles/feature-toggles.html to gut-check my intuition and there it seems that a "feature flag" should be a simple switch that goes both ways. So maybe we should reconsider the naming here and stick to "migrations" naming while perhaps in the future adding a separate mechanism for true feature flags once we feel that is something we need (not today).
</blockquote></details>

Makes sense, I just needed a new package name for dep reasons. Does something like feature gate feel less flip-floppy or should I stay away from "feature" in the name entirely?
___
*[pkg/server/server.go, line 556 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/44249#-LzM4uY_-x3RiXnez1iF:-Lzo-fJz1rxptHtUhnvY:b7ot0ho) ([raw file](https://github.com/cockroachdb/cockroach/blob/7381c2ac94fb1060e46f34269797ec0dc3ac6f3e/pkg/server/server.go#L556)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Yeah definitely, but also what can be in a hook? You want to run this early (to avoid setting up all of those moving parts), so all you'll have is the slice of `engine.Engine`s, you can't do KV, you don't have your `*Node` or even your `*Server` set up.
</blockquote></details>

yeah, I think this should just be a slice of engine.Engines

**Comment by danhhz** [comment]
Don't think this is useful anymore. Closing

**Pull request closed without merging**
