### PR TITLE
builtins: add trunc(decimal, int) builtin

### LINKED ISSUE #85620: sql: support trunc(decimal,int)
The 'trunc' function (which I think has been part of postgres since at least version 11)  appears to be missing

Postgres 14:
```
C:\Development\YADAMU>psql -Upostgres -hyadamu-db2  -d yadamu
Password for user postgres:
psql (13.3, server 14.4 (Debian 14.4-1.pgdg110+1))
WARNING: psql major version 13, server major version 14.
         Some psql features might not work.
WARNING: Console code page (437) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
Type "help" for help.

yadamu=# select version() ;
                                                           version
-----------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 14.4 (Debian 14.4-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
(1 row)


yadamu=# select trunc(123.4567,2);
 trunc
--------
 123.45
(1 row)


yadamu=# exit
```

Cockroach 22.1.5

```
C:\Development\YADAMU>psql -Uroot -hyadamu-db2  -d yadamu -p 26257
psql (13.3, server 13.0.0)
WARNING: Console code page (437) differs from Windows code page (1252)
         8-bit characters might not work correctly. See psql reference
         page "Notes for Windows users" for details.
Type "help" for help.

yadamu=> select version() ;
                                       version
-------------------------------------------------------------------------------------
 CockroachDB CCL v22.1.5 (x86_64-pc-linux-gnu, built 2022/07/28 14:58:04, go1.17.11)
(1 row)


yadamu=> select trunc(123.4567,2);
ERROR:  unknown signature: trunc(decimal, int)
yadamu=>

```

Jira issue: CRDB-18347
Epic CRDB-14049

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/85620

Release note (sql change): Added the trunc(decimal, int) builtin
function, which truncates the given decimal value to the specified
number of decimal places. A negative value can be used for the scale
parameter, which will truncate to the left of the decimal point.

Example:
```
> select trunc(541.234, 2), trunc(541.234, 0), trunc(541.234, -1);

  trunc  | trunc | trunc
---------+-------+---------
  541.23 |   541 | 5.4E+2
```

### CODE REVIEW

**Comment by ZhouXing19** [comment]
The latest CI is still failing with 
```
client_merge_test.go:4753: ranges unexpectedly unmerged expected startKey /Table/106/1/1, but got /Table/106/1/2
```
Could this be related to the oid changes?

**Comment by rafiss** [comment]
Where did you see those failures? I just see a data race for `TestAdminAuditLogBasic` which is caused by https://github.com/cockroachdb/cockroach/issues/85988

**Comment by ZhouXing19** [comment]
I saw it from [here](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Test/6061955?showRootCauses=true&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildDeploymentsSection=true&expandBuildTestsSection=true), in `TestMergeQueueWithSlowNonVoterSnaps`. But I just test this commit locally and it passed, so I'm guessing it was just a flake...

Other than the CI failures everything LGTM!

**Review by ZhouXing19 — APPROVED** [review]

**Comment by rafiss** [comment]
tftr!

bors r=ZhouXing19

**Comment by rafiss** [comment]
bors r=ZhouXing19

**Pull request merged**
