### PR TITLE
sql: disallow some schema changes in transactions

### PR DESCRIPTION
**Pull request by vivekmenezes**
@bdarnell for the change to return error from SetSystemConfigTrigger()

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14368)

### CODE REVIEW

**Comment by knz** [comment]
From a UX perspective it seems to me that we can do slightly better than disallowing every statement after a schema change: probably any SELECT/INSERT/UPDATE/DELETE that uses *other* tables than those being updated are fine; and probably we can allow INSERT/SELECT on newly created table/indices.

What about making the various getDescriptor() functions return an error if there are pending schema changes on that table/index instead of rejecting subsequent statements directly in the executor? That will make independent statements able to proceed normally.

Also cc @nvanbenschoten to look at how this should interact with #14188.

Also cc @andreimatei to look at the change to `txnClosure` in `execRequest`. 

---

Reviewed 11 of 12 files at r1, 4 of 5 files at r2.
Review status: 15 of 16 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14368#-:-Kg9mS18bYBVeJhNMFeL:bgofgyc)*

**Comment by vivekmenezes** [comment]
I happy to add a data dependency analysis module to this change if you think it would be useful. Are they any use cases you imagine that can benefit from this? It wouldn't surprise me that eventually someone will need more complexity here, but one thought it to leave it with this heavier stick for now and see who complains and cares about it.

---

Review status: 15 of 16 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14368#-:-KgEyHWAlbiAZhcjQfdu:b-13whj1)*

**Comment by dt** [comment]
@knz from a UX perspective it might also be easier / simpler to understand if it is a simple rule -- e.g. "schema change must be last statement in txn" -- rather than the minimal technically correct limitation computed from the dependencies of the particular schema in use? also certainly easier for us to ensure correctness.

**Comment by bdarnell** [comment]
LGTM for the changes outside the `sql` package.

I also prefer the simple rule of "no other statements after a schema change" instead of a more complex analysis.

---

Reviewed 11 of 12 files at r1, 5 of 5 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14368#-:-KgFOqMSX3mhHqC_2pQ_:b-gwd1ly)*

**Comment by dt** [comment]
@vivekmenezes while discussion of behavior added in second commit continues, can we pull the first commit, the txn anchor panic -> error, into a standalone PR that we can merge now?

**Comment by vivekmenezes** [comment]
okay let me do that today

**Review by dt — APPROVED** [review]

**Comment by dt** [comment]
I'm strongly in favor of the stricter rule at least until we can carefully consider all the subtleties of the more permissive but more complex behavior. Starting restrictive and then loosening is much easier than figuring out we need to be more restrictive later.

**Comment by bdarnell** [comment]
How does `CREATE TABLE AS SELECT` (which is effectively a `CREATE TABLE` followed by an `INSERT`) work?

**Comment by vivekmenezes** [comment]
@bdarnell this change doesn't affect the behavior of ```CREATE TABLE AS SELECT``` . It is tested in sql/testdata/logic_test/create_as

**Comment by bdarnell** [comment]
I wasn't suggesting that this would break `CREATE TABLE AS SELECT`, I was curious about how it works and why this is safe while other inserts after a CREATE TABLE are not.

**Comment by vivekmenezes** [comment]
@bdarnell we still permit an INSERT following a CREATE TABLE as long as the table doesn't reference FKs or is an interleaved table (both needing post transaction processing). I was mistaken in my understanding of this. I've added a test for this case in #14619

**Comment by eldos-dl** [comment]
This point should be mentioned in Transactions Docs.

**Comment by vivekmenezes** [comment]
@eldos-dl This PR has been rolled back? Did you have anything specific in mind?

**Comment by eldos-dl** [comment]
@vivekmenezes I assumed that schema changes are not allowed inside transactions as I was unable to perform this type of transactions.
```
CREATE TABLE a (id SERIAL NOT NULL PRIMARY KEY);
CREATE TABLE b (id SERIAL NOT NULL PRIMARY KEY);
BEGIN; DROP TABLE a; SHOW TABLES; ALTER TABLE b RENAME TO a;  COMMIT;
```

**Comment by vivekmenezes** [comment]
@eldos-al thanks for clarifying

We do support schema changes within transactions, but cannot perform specific ones within
a transaction. We do not support dropping and recreating a table using the same name in the same transaction as described above and in #12123

Unfortunately this is not going to be easy for us to fix.

**Comment by eldos-dl** [comment]
@vivekmenezes I think this should be clarified in documentation. Also [Table Migrations to Add or Change Immutable Constraints](https://www.cockroachlabs.com/docs/constraints.html#table-migrations-to-add-or-change-immutable-constraints) suggests to 
> 3. Issue a transaction that drops the old table, and then renames the new table to the old name.

which is not possible.

**Comment by vivekmenezes** [comment]
@eldos-dl we really appreciating this! I do appreciate you taking the time to report this. I've updated the docs. Thanks!

**Pull request merged**
