### PR TITLE
workload/ycsb: support workload D, E and fix key selection for insertion and reading

### PR DESCRIPTION
**Pull request by jeffrey-xiao**
This PR does the following items:

1. Support workload D (95% reads skewed to newer keys, 5% writes) by adding a latest generator
2. Support workload E (95% scans, 5% writes) by implementing scans
3. Fix key selection for insertion by having a separate index for next row to insert rather than using the `iMaxHead` in the zipfian generator
4. Fix key selection for reading by having a separate counter for number of rows instead of using the number of initial rows. I didn't fully understand the method proposed in the ycsb paper in section 5.3, so if this isn't the best way, I'm open to changes.
5. Improve key selection by hashing before modding. This follows the logic proposed in the ycsb paper. Originally we were hashing after applying a modulo, but that always causes the first inserted key to be the hotspot rather than distribute the hotspot around.
6. Change API for generators to be more consistent. All generators now take in a lower bound and upper bound and generate an inclusive range between the lower and upper bound (I.E. [lower, upper]).

### CODE REVIEW

**Review by ajwerner — COMMENTED** [review]
Very cool! Have you tried running them on a roachprod cluster? Consider adding these workloads to the set of ycsb roachtests and then running them and seeing what you see. Both of these are useful and realistic workloads. 

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-:-LffJGss-1FXSeeSgMj2:benz6lq)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jeffrey-xiao and @nvanbenschoten)

___
*[pkg/workload/ycsb/ycsb.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LffH_tw5FpxDmEanaBX:-LffH_tw5FpxDmEanaBY:bicpo0v) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6f94e16455565ed454a840520be69bd0ff63336/pkg/workload/ycsb/ycsb.go#L338)):*
> ```Go
> 	updateStmts []*gosql.Stmt
> 
> 	// The next row index to insert.
> ```

Seems like you never want these to be nil pointers when you interact with them below. How about avoiding the allocations above and just taking the address of the field for use with the atomics?
___
*[pkg/workload/ycsb/ycsb.go, line 126 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LffIAUO8tE2c3ShHt57:-LffIAUO8tE2c3ShHt58:b3fh88i) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f1a6f19b46d16e07b2a4985d4cf73bef5d63948/pkg/workload/ycsb/ycsb.go#L126)):*
> ```Go
> 		g.flags.StringVar(&g.workload, `workload`, `B`, `Workload type. Choose from A-F.`)
> 		g.flags.StringVar(&g.requestDistribution, `request-distribution`, `zipfian`, `Distribution for request key generation [zipfian, uniform, latest].`)
> 		g.flags.StringVar(&g.scanLengthDistribution, `scan-length-distribution`, `uniform`, `Distribution for scan length generation [zipfian, uniform].`)
> ```

nit: can you augment the help text for these 3 flags to mention that this is for workload E.
___
*[pkg/workload/ycsb/ycsb.go, line 510 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LffIj0nDajj5voUG0cH:-LffIj0oCdkywd0TrDht:b6hz5ze) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f1a6f19b46d16e07b2a4985d4cf73bef5d63948/pkg/workload/ycsb/ycsb.go#L510)):*
> ```Go
> 	defer res.Close()
> 	for res.Next() {
> ```

nit: no need for this blank line. I guess if you feel like it's visually important you can add a comment inside the loop.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37804)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @nvanbenschoten)

___
*[pkg/workload/ycsb/ycsb.go, line 338 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LffH_tw5FpxDmEanaBX:-LffKLr5Bh_BXXhqyrO_:b-bbl9et) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6f94e16455565ed454a840520be69bd0ff63336/pkg/workload/ycsb/ycsb.go#L338)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

Seems like you never want these to be nil pointers when you interact with them below. How about avoiding the allocations above and just taking the address of the field for use with the atomics?
</blockquote></details>

The row indexes and counters are shared between workers, so they have to be allocated.

**Review by ajwerner — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-:-LffYgDH7KvRPvRRZCpN:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by nvb — COMMENTED** [review]
Very nice!

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, 4 of 4 files at r6, 2 of 2 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-:-LffcewL4roAHJz76ugI:b-j7qk9t)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jeffrey-xiao)

___
*[pkg/workload/ycsb/latest_generator.go, line 24 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LffaOoK7AGBVdRdMvSI:-LffaOoK7AGBVdRdMvSJ:bjnyxpv) ([raw file](https://github.com/cockroachdb/cockroach/blob/993bb9c43c427f3c99be0f0075bcac0191b983af/pkg/workload/ycsb/latest_generator.go#L24)):*
> ```Go
> )
> 
> // LatestGenerator is a random number generator that generates draws from a
> ```

The official YCSB benchmark seems to [use a skewed latest generator](https://github.com/brianfrankcooper/YCSB/blob/e5f436cfb3dded3e63fb2ca71168d728b3d8a24f/core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java#L488) for workload D. Why did you decide to go with a uniform distribution here?

EDIT: never mind, looks like you realized this already. Want to call this `SkewedLatestGenerator` to mirror their implementation?
___
*[pkg/workload/ycsb/uniform_generator.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LffbiFmBZEHcvsk7T1c:-LffbiFmBZEHcvsk7T1d:b10209g) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f1a6f19b46d16e07b2a4985d4cf73bef5d63948/pkg/workload/ycsb/uniform_generator.go#L62)):*
> ```Go
> }
> 
> // Uint64 returns a random Uint64 between iMin and iMax, drawn from a uniform
> ```

How does this ensure that the value is above `iMin`?
___
*[pkg/workload/ycsb/ycsb.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-Lff_ErxDPr6qa6MJcef:-Lff_ErxDPr6qa6MJceg:b-daschh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6f94e16455565ed454a840520be69bd0ff63336/pkg/workload/ycsb/ycsb.go#L406)):*
> ```Go
> // See YCSB paper section 5.3 for a complete description of how keys are chosen.
> func (yw *ycsbWorker) nextReadKey() string {
> 	rowCount := atomic.LoadUint64(yw.rowCount)
> ```

Do we ever modify `rowCount`? Do we need this atomic load?
___
*[pkg/workload/ycsb/ycsb.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LffbLyE7J1ySkS8UDES:-LffbLyE7J1ySkS8UDET:bexk2d8) ([raw file](https://github.com/cockroachdb/cockroach/blob/993bb9c43c427f3c99be0f0075bcac0191b983af/pkg/workload/ycsb/ycsb.go#L144)):*
> ```Go
> 	return workload.Hooks{
> 		Validate: func() error {
> 			switch g.workload {
> ```

Do you think we should be defaulting the request distribution differently depending on the workload?
___
*[pkg/workload/ycsb/ycsb.go, line 307 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-Lffc0L4517OfTbEBhpu:-Lffc0L4517OfTbEBhpv:b-73m6vw) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f1a6f19b46d16e07b2a4985d4cf73bef5d63948/pkg/workload/ycsb/ycsb.go#L307)):*
> ```Go
> 		return workload.QueryLoad{}, errors.Errorf("Unknown request distribution: %s", g.requestDistribution)
> 	}
> 	if err != nil {
> ```

Nice catch!

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37804)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/workload/ycsb/uniform_generator.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LffbiFmBZEHcvsk7T1c:-LffduvSCamonNo3Mqsq:b-9b4gt2) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f1a6f19b46d16e07b2a4985d4cf73bef5d63948/pkg/workload/ycsb/uniform_generator.go#L62)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

How does this ensure that the value is above `iMin`?
</blockquote></details>

Oops, forgot to make this change.
___
*[pkg/workload/ycsb/ycsb.go, line 406 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-Lff_ErxDPr6qa6MJcef:-Lffdxdn5ouZi6rlkghx:b-qi3cxd) ([raw file](https://github.com/cockroachdb/cockroach/blob/d6f94e16455565ed454a840520be69bd0ff63336/pkg/workload/ycsb/ycsb.go#L406)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do we ever modify `rowCount`? Do we need this atomic load?
</blockquote></details>

Also forgot to increment this when iMax gets incremented.
___
*[pkg/workload/ycsb/ycsb.go, line 144 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LffbLyE7J1ySkS8UDES:-Lffe7SQEY2OVsoXGKeC:b26w9em) ([raw file](https://github.com/cockroachdb/cockroach/blob/993bb9c43c427f3c99be0f0075bcac0191b983af/pkg/workload/ycsb/ycsb.go#L144)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you think we should be defaulting the request distribution differently depending on the workload?
</blockquote></details>

I think that's a reasonable change.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37804)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jeffrey-xiao and @nvanbenschoten)

___
*[pkg/workload/ycsb/uniform_generator.go, line 67 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-Lftv_pL4nhnXICrfKjv:-Lftv_pL4nhnXICrfKjw:b-95jv2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b98e9a05eebf8a39c110c387920d3d884e95dc/pkg/workload/ycsb/uniform_generator.go#L67)):*
> ```Go
> 	z.mu.Lock()
> 	defer z.mu.Unlock()
> 	return rand.Uint64()%(z.mu.iMax-z.iMin+1) + z.iMin
> ```

This should be using `z.mu.r.Uint64()`, not the global `rand.Uint64()`.

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37804)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jeffrey-xiao and @nvanbenschoten)

___
*[pkg/workload/ycsb/uniform_generator.go, line 67 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-Lftv_pL4nhnXICrfKjv:-Lfvjz9K2gvUkPTQbj6U:b-u36x51) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b98e9a05eebf8a39c110c387920d3d884e95dc/pkg/workload/ycsb/uniform_generator.go#L67)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This should be using `z.mu.r.Uint64()`, not the global `rand.Uint64()`.
</blockquote></details>

Also, using mod to get integers within a range is slightly biased. This code should probably be using `math/rand.Rand.Int63n`. I realize this wasn't changed in this PR, but as long as you're in here...

**Review by petermattis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37804)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @jeffrey-xiao and @nvanbenschoten)

___
*[pkg/workload/ycsb/ycsb.go, line 409 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LfyWY6C-Dwx96CtM3dW:-LfyWY6C-Dwx96CtM3dX:b-fk6e8m) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66295eb55024d7d59a0c3d1bd767940ed4ed89f/pkg/workload/ycsb/ycsb.go#L409)):*
> ```Go
> 	// distribution and modding the samples. To properly support INSERTS, we need
> 	// to maintain a separate rownum counter.
> 	rownum := yw.randGen.IMaxHead()
> ```

This was the only call to `IMaxHead`. I think we can remove that method now, which was a bit of an oddity in the random generators.
___
*[pkg/workload/ycsb/ycsb.go, line 438 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LfyWFqq2Xv1ozvRVdMo:-LfyWFqq2Xv1ozvRVdMp:bal27qk) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b98e9a05eebf8a39c110c387920d3d884e95dc/pkg/workload/ycsb/ycsb.go#L438)):*
> ```Go
> func (yw *ycsbWorker) nextReadKey() string {
> 	rowCount := atomic.LoadUint64(yw.rowCount)
> 	rowIndex := yw.hashKey(yw.requestGen.Uint64()) % rowCount
> ```

`buildKeyName` also calls `hashKey`, so this will cause us to call `hashKey` twice for each read key. Is that expected?
___
*[pkg/workload/ycsb/ycsb.go, line 472 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LfyWjRJ8cK74SUhbHdv:-LfyWjRJ8cK74SUhbHdw:bx46v4a) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b98e9a05eebf8a39c110c387920d3d884e95dc/pkg/workload/ycsb/ycsb.go#L472)):*
> ```Go
> 			return err
> 		}
> 		atomic.AddUint64(yw.rowCount, 1)
> ```

Can you confirm that this is what the official YCSB implementation does? I ask because it is still possible to generate a read key which hasn't been inserted yet due to concurrency in the inserts.

**Review by jeffrey-xiao — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37804)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten and @petermattis)

___
*[pkg/workload/ycsb/uniform_generator.go, line 67 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-Lftv_pL4nhnXICrfKjv:-LfyiaLB7Nz9bpLS-a8c:b1gafge) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b98e9a05eebf8a39c110c387920d3d884e95dc/pkg/workload/ycsb/uniform_generator.go#L67)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Also, using mod to get integers within a range is slightly biased. This code should probably be using `math/rand.Rand.Int63n`. I realize this wasn't changed in this PR, but as long as you're in here...
</blockquote></details>

Done. Unfortunate that there is no `Uint64n`.
___
*[pkg/workload/ycsb/ycsb.go, line 409 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LfyWY6C-Dwx96CtM3dW:-LfykA-CBSW_wOtxR7KI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e66295eb55024d7d59a0c3d1bd767940ed4ed89f/pkg/workload/ycsb/ycsb.go#L409)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

This was the only call to `IMaxHead`. I think we can remove that method now, which was a bit of an oddity in the random generators.
</blockquote></details>

Done.
___
*[pkg/workload/ycsb/ycsb.go, line 438 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LfyWFqq2Xv1ozvRVdMo:-LfyilJw83hqxGMQebM_:b-o5t4f0) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b98e9a05eebf8a39c110c387920d3d884e95dc/pkg/workload/ycsb/ycsb.go#L438)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

`buildKeyName` also calls `hashKey`, so this will cause us to call `hashKey` twice for each read key. Is that expected?
</blockquote></details>

The issue with the previous implementation is that it gets hashed after the mod which always causes the hotspot to be the first key. The yscb paper suggests to hash then mod. Hashing twice for each read key is also consistent with the official ycsb implementation. When the request distribution is `zipfian`, the official yscb implementation uses a `ScrambledZipfianGenerator` which hashes the output of a `ZipfianGenerator`. Then they hash the generated key num to obtain the key name. 
___
*[pkg/workload/ycsb/ycsb.go, line 472 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-LfyWjRJ8cK74SUhbHdv:-Lfz6eMX1-aRht4YOqQD:b-5b3tk5) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b98e9a05eebf8a39c110c387920d3d884e95dc/pkg/workload/ycsb/ycsb.go#L472)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary><blockquote>

Can you confirm that this is what the official YCSB implementation does? I ask because it is still possible to generate a read key which hasn't been inserted yet due to concurrency in the inserts. 
</blockquote></details>

Thanks for the catch. The official implementation uses an `AcknowledgedCounterGenerator` which I've now added.

**Review by petermattis — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-:-Lg-0rUt3RZWj4t0wHj8:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jeffrey-xiao and @nvanbenschoten)

___
*[pkg/workload/ycsb/acknowledged_counter.go, line 45 at r16](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-Lg-0NDz-EccN2C0lVaU:-Lg-0NDz-EccN2C0lVaV:b-cssqv7) ([raw file](https://github.com/cockroachdb/cockroach/blob/e5e1116b181d9ed3110b1f8090745990d78c8b54/pkg/workload/ycsb/acknowledged_counter.go#L45)):*
> ```Go
> 	c := &AcknowledgedCounter{}
> 	c.mu.count = initialCount
> 	c.mu.window = make([]bool, windowSize)
> ```

I believe this will use `windowSize` bytes. You could reduce that by a factor of 8 by using a bitmap. Not sure if that is worth it as we're only talking about 1MB of memory and the current code is clear and concise.
___
*[pkg/workload/ycsb/uniform_generator.go, line 67 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/37804#-Lftv_pL4nhnXICrfKjv:-Lg--FiQ-HTsVUi5tprr:b-2t0a8z) ([raw file](https://github.com/cockroachdb/cockroach/blob/b3b98e9a05eebf8a39c110c387920d3d884e95dc/pkg/workload/ycsb/uniform_generator.go#L67)):*
<details><summary><i>Previously, jeffrey-xiao (Jeffrey Xiao) wrote…</i></summary><blockquote>

Done. Unfortunate that there is no `Uint64n`.
</blockquote></details>

Someday (not today) we may upgrade to `golang.org/x/exp/rand` which does have `Uint64n`.

**Pull request merged**
