### PR TITLE
idalloc: assert against counter regressions

### PR DESCRIPTION
**Pull request by tbg**
Touches #48485.

Release note: None

### CODE REVIEW

**Review by irfansharif — APPROVED** [review]
LGTM.

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48526#-:-M6jhuh71uTc3SwF1tG9:b-85i63v)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/idalloc/id_alloc.go, line 43 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/48526#-M6jfw6S4cMvhVU46dMq:-M6jfw6S4cMvhVU46dMr:b-dex3u3) ([raw file](https://github.com/cockroachdb/cockroach/blob/20392313df2c78323cb5b0cdd30ef3282931d586/pkg/kv/kvserver/idalloc/id_alloc.go#L43)):*
> ```Go
> 
> // Incrementer abstracts over the database which holds the key counter.
> type Incrementer func(_ context.Context, _ roachpb.Key, inc int64) (new int64, _ error)
> ```

[nit] Define this above its first use. Also s/new/res? (new is a keyword)

**Comment by irfansharif** [comment]
(do remember to backport as needed, I'm not sure how far back we should get backported to.)

**Review by neeral — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/idalloc/id_alloc.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48526#-M6lItsUC1ryoAFxDio8:-M6lItsUC1ryoAFxDio9:brlwfe3) ([raw file](https://github.com/cockroachdb/cockroach/blob/524de32a2eb6dc0ca0ef592aca2338313bcfa9eb/pkg/kv/kvserver/idalloc/id_alloc.go#L105)):*
> ```Go
> 		defer close(ia.ids)
> 
> 		var prevValue int64 // for assertions
> ```

Dumb question and please feel free to ignore. `newValue` and `prevValue` are of type int64 but IDs are uint32. `newValue` is cast to a uint32 on line 152. What's the reason for this? The only thing I thought of is integer overflow but that would affect this code when a value is cast to a uint32.

**Comment by tbg** [comment]
TFTR!

bors r=irfansharif

**Comment by tbg** [comment]
bors r=irfansharif

```
*roachpb.InternalTimeSeriesData: not observed below raft!
*enginepb.MVCCMetadataSubsetForMergeSerialization: not observed below raft!
```

I added an exception for those two. Sometimes timeseries don't get written as part of the `kvserver` test suite and then this check wants us to remove them from the below-raft list, but they belong on it.

**Comment by tbg** [comment]
Hadn't pushed yet.

bors r=irfansharif

**Review by irfansharif — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/48526)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif, @neeral, and @tbg)

___
*[pkg/kv/kvserver/idalloc/id_alloc.go, line 105 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/48526#-M6lItsUC1ryoAFxDio8:-M78_t9z17jOAqnKYhmP:b6jh0ch) ([raw file](https://github.com/cockroachdb/cockroach/blob/524de32a2eb6dc0ca0ef592aca2338313bcfa9eb/pkg/kv/kvserver/idalloc/id_alloc.go#L105)):*
<details><summary><i>Previously, neeral (Neeral Dodhia) wrote…</i></summary><blockquote>

Dumb question and please feel free to ignore. `newValue` and `prevValue` are of type int64 but IDs are uint32. `newValue` is cast to a uint32 on line 152. What's the reason for this? The only thing I thought of is integer overflow but that would affect this code when a value is cast to a uint32.
</blockquote></details>

Not a dumb question! Tobi changed IDs out to 64 to make this less janky, but the original 64 bit allocations came the increment API, but I'm guessing we really didn't expect range ID allocations to ever hit the 32 bit threshold.

**Pull request merged**
