### PR TITLE
storage: misc tiny cleanups

### PR DESCRIPTION
**Pull request by sumeerbhola**
Release note: None

### CODE REVIEW

**Review by nicktrav — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81058#-:-N1Kqnel85_DVvm-XeHt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola)

___
*[`pkg/storage/mvcc_incremental_iterator_test.go` line 1463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81058#-N1KqK2F5b30qOdq4QKV:-N1KqK2F5b30qOdq4QKW:b-tlvu7n) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e93d5884adfe5a86ff6581ecba38e4036c4e1bb/pkg/storage/mvcc_incremental_iterator_test.go#L1463)):*
> ```Go
> 	}
> 
> 	put("a", "b value", 2, &roachpb.Transaction{
> ```

nit: a -> "a value", b -> "b value" instead?

**Review by jbowens — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81058#-:-N1OoG-UE9Yvv84iS4mv:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/81058#-:-N1cpJ1b-yCSFjMM_T76:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @jbowens and @nicktrav)

___
*[`pkg/storage/mvcc_incremental_iterator_test.go` line 1463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/81058#-N1KqK2F5b30qOdq4QKV:-N1QGvCBD1rg1bjc9gyw:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e93d5884adfe5a86ff6581ecba38e4036c4e1bb/pkg/storage/mvcc_incremental_iterator_test.go#L1463)):*
<details><summary><i>Previously, nicktrav (Nick Travers) wrote…</i></summary><blockquote>

nit: a -> "a value", b -> "b value" instead?
</blockquote></details>

Done

**Comment by sumeerbhola** [comment]
bors r=nicktrav,jbowens

**Pull request merged**
