### PR TITLE
sql,schemachanger: disallow concurrent execution for new schema changes

### PR DESCRIPTION
**Pull request by postamar**
This PR prevents new-style schema changes from running concurrently with
any other schema changes, in two ways:

1. If there are mutations in progress (from either new or old schema
   changes) when attempting to plan a new-style schema change, we wait
   and poll until there are no mutations, and then restart the
   transaction.
2. If we try to write an old-style schema change job while there is a
   new-style schema change on the table, which is detected via a new
   field on the table descriptor for the new-style schema change job ID,
   an error is returned. This effectively prevents all schema changes,
   even the ones without mutations.

Most of this commit consists of testing. Testing knobs for the new
schema changer are introduced. We also now accumulate the statements
involved in the schema change, as strings, in the schema changer state
in `extraTxnState`. The executor now takes an argument to inject more
relevant state into the testing knobs, including the aforementioned
statements.

Release note: None

### CODE REVIEW

**Comment by postamar** [comment]
This is https://github.com/cockroachdb/cockroach/pull/61042 but rebased.

**Review by ajwerner — APPROVED** [review]
:lgtm:

There's going to be more work to refine this as time goes on but this is a good start. 

> Reviewed 7 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64291#-:-MZUZTJFCTwYlw4e7CQ_:bfcikkw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi and @postamar)

___
*[pkg/sql/schema_change_plan_node.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64291#-MZUYcR3EX6l6kxmLgEs:-MZUYcR3EX6l6kxmLgEt:b-ur1dwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/491a56d765e14f9a111bbc762a29f051abea88bf/pkg/sql/schema_change_plan_node.go#L71)):*
> ```Go
> 	}
> 
> 	for r := retry.StartWithCtx(ctx, base.DefaultRetryOptions()); r.Next(); {
> ```

how do you feel about a `log.Every` and then logging in this loop?
___
*[pkg/sql/schemachanger/scjob/job.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64291#-MZUZ4RL6_RhoVHyW7ZY:-MZUZ4RL6_RhoVHyW7ZZ:b-c7qnh1) ([raw file](https://github.com/cockroachdb/cockroach/blob/491a56d765e14f9a111bbc762a29f051abea88bf/pkg/sql/schemachanger/scjob/job.go#L186)):*
> ```Go
> 	// This is a hack to get individual statements back out of the concatenated
> 	// statements.
> 	return strings.Split(j.Payload().Statement, "; ")
> ```

I think it'd be better to use `parser.Parse` and then to use the `SQL` field of the parsed `Statement`. A downside there is that it potentially exposes risks to errors I don't really want to see.

Maybe better would be to update this proto. I *think* you can turn non-repeated fields into repeated fields in a backwards compatible way. Also we don't have compatibility concerns for now.

**Review by postamar — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64291)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @fqazi)

___
*[pkg/sql/schema_change_plan_node.go, line 71 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64291#-MZUYcR3EX6l6kxmLgEs:-MZXpXi05UXCs_6QDnlY:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/491a56d765e14f9a111bbc762a29f051abea88bf/pkg/sql/schema_change_plan_node.go#L71)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

how do you feel about a `log.Every` and then logging in this loop?
</blockquote></details>

Done.
___
*[pkg/sql/schemachanger/scjob/job.go, line 186 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64291#-MZUZ4RL6_RhoVHyW7ZY:-MZXpZJh-ELmb9BseOvD:b-xpr29t) ([raw file](https://github.com/cockroachdb/cockroach/blob/491a56d765e14f9a111bbc762a29f051abea88bf/pkg/sql/schemachanger/scjob/job.go#L186)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

I think it'd be better to use `parser.Parse` and then to use the `SQL` field of the parsed `Statement`. A downside there is that it potentially exposes risks to errors I don't really want to see.

Maybe better would be to update this proto. I *think* you can turn non-repeated fields into repeated fields in a backwards compatible way. Also we don't have compatibility concerns for now. 
</blockquote></details>

I was going to say you were wrong about the proto, but I since found out that you were right. I'll push a new change shortly.

**Pull request merged**
