### PR TITLE
raft: enable store liveness in raft unit tests phase 1

### PR DESCRIPTION
**Pull request by iskettaneh**
This commit modifies the following tests to allow them to run in both store liveness enabled/disabled configurations:

1) TestCommitWithoutNewTermEntry
2) TestConfChangeCheckBeforeCampaign
3) TestConfChangeV2CheckBeforeCampaign
4) TestLeaderCycle
5) TestLeaderCyclePreVote
6) TestLeaderTransferReceiveHigherTermVote
7) TestLogReplication
8) TestOldMessages

References: #132241

Release note: None

### CODE REVIEW

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/133670#-:-OAcMmki1Pys8_EK1Z9u:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @iskettaneh)

**Comment by rickystewart** [comment]
https://github.com/cockroachdb/cockroach/pull/134074 to correct that. Also your PR is failing the lints as you can see [here](https://mesolite.cluster.engflow.com/invocations/default/0084e9c3-8f30-4ef2-97d9-6da356f59f90).

**Pull request merged**
