### PR TITLE
Integrate CRDB with stackdriver profiling

### PR DESCRIPTION
**Pull request by joshimhoff**
This integrates CRDB with stackdriver profiling: https://cloud.google.com/profiler. Stackdriver profiling provides continuous profiling as a service. GCP currently doesn't charge anything for this service.

Once this PR is merged, if you start CRDB like this:

```
cockroach start --logtostderr --insecure --stackdriver-profiler-enabled --stackdriver-profiler-project-id 'cockroach-managed-staging`
```

Then cockroach will send CPU/heap/goroutine profiles to stackdriver in the "cockroach-managed-staging" project. Then you can view profiles with the below UI:

image

Profiles are stored for 30 days, which is really great!

The stackdriver profiler API must be enabled in the project for this to work correctly. If you leave off the `--stackdriver-profiler-project-id` flag, CRDB will send profiles to the project in which CRDB is running. This will be useful for GCP CC clusters.

The profiler takes a sampling-based approach, in order to be safe to use in prod. With that said, I remember there were some funny postmortems from when Google first rolled this out to their own prod. If I understand the docs correctly, around one profile for each profile type will be taken a minute, **per service**. Given that service is set to cockroach + cluster ID in this PR, this means one profile per minute **across all nodes**, NOT one profile per minute per node.

@petermattis has mentioned that this would be useful for root causing roachprod failures. This PR might need tweaks to make it useful.

I didn't write tests yet. Want to get eyes on the PR before writing tests.

### CODE REVIEW

**Comment by joshimhoff** [comment]
Will get tests passing.

**Comment by joshimhoff** [comment]
Hmm. I see this error in teamcity:

```
```

**Comment by joshimhoff** [comment]
I see this error in teamcity:

```
      pkg/server/server.go:31:2: cannot find package "cloud.google.com/go/profiler" in any of:
19:20:15
      	/go/src/github.com/cockroachdb/cockroach/vendor/cloud.google.com/go/profiler (vendor tree)
19:20:15
      	/usr/local/go/src/cloud.google.com/go/profiler (from $GOROOT)
19:20:15
      	/go/src/cloud.google.com/go/profiler (from $GOPATH)
```

Code change is working locally, tests are passing locally, and `Gopkg.lock` is updated.
I see that `vendor` is untracked according to git:

```
~/g/s/g/c/cockroach [integrate_with_stackdriver_profiling] $ git status                                                            17:47:55
On branch integrate_with_stackdriver_profiling
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

	modified:   vendor (untracked content)

no changes added to commit (use "git add" and/or "git commit -a")
```

I am guessing that either I am not using `dep` correctly or there is some CRDB-related edge with which I'm unfamiliar.

**Comment by joshimhoff** [comment]
As this is my first CRDB PR, can I get a sanity check before I add tests?

**Review by ajwerner — COMMENTED** [review]
See the docs here to upgrade the dependency inside the vendor submodule: https://github.com/cockroachdb/cockroach/tree/master/build#updating-dependencies

I might consider using a cluster setting rather than a flag to set up the strackdriver project ID. See `trace.zipkin` in https://www.cockroachlabs.com/docs/stable/cluster-settings.html. Are there cases where you want different nodes to have different stackdriver profiling project IDs?

In general this seems pretty much okay. It does need testing but moreover it is in serious need of documentation. 
You're going to need to document what these settings/flags mean in terms of behavior changes, how to connect the profiler to the backend, etc. It's probably also worthy of a docs page on how to connect to stackdriver. Additionally it'll be important to document how the service name is generated. Perhaps you'll also want to allow that to be controlled. 

I think that the release note is a general change not just a CLI change, you added support to the server for stackdriver profiling in addition to the flags for cockroach start. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45177#-:-M0zx8I62lH79jaqWwoW:b-v8hw7r)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @dt)

**Pull request closed without merging**
