### PR TITLE
roachtest: move schemachange/secondary-index-multi-version to new framework

### LINKED ISSUE #110534: roachtest: port schemachange/secondary-index-multi-version to new mixed-version framework
See the parent issue https://github.com/cockroachdb/cockroach/issues/110528 for details.

An example is here: https://github.com/cockroachdb/cockroach/pull/108802

Jira issue: CRDB-31484

### PR DESCRIPTION
**Pull request by rafiss**
The new framework has better testing and is the only one being maintained now.

fixes https://github.com/cockroachdb/cockroach/issues/110534
Release note: None

### CODE REVIEW

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113696)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @annrpom, @renatolabs, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/secondary_indexes.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113696#-NiGORZS8CN89ewxoq63:-NiGORZS8CN89ewxoq64:b16loa1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f515f7051d88079a07a31c86d2b13263d68c4b25/pkg/cmd/roachtest/tests/secondary_indexes.go#L57)):*
> ```Go
> 
> 		// Modify index data from that node.
> 		modifyData(1,
> ```

the old code took care to run this command on the node whose binary was upgraded. i don't think the new framework offers us that control. is that correct @renatolabs?  it may be sufficient to just rely on randomization here.

**Comment by renatolabs** [comment]
Hrm, I'm trying to run this test on my gceworker but I'm seeing some schema mismatches, does it run successfully on your end? It seems to have passed in the CI build so it might be my environment.

**Comment by rafiss** [comment]
yeah I got a successful run from running from my laptop

**Comment by renatolabs** [comment]
Sorry, comment was meant for #113643 (I have since deleted it).

**Review by renatolabs — APPROVED** [review]
:lgtm:, but in the theme of efficiency, this is another test that I wish didn't spin up real VMs.

Nothing for this test to do right now, I think the better course of action is to set up a nightly "Local roachtest" run for tests like this and the validate-schema one recently ported.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/113696#-:-NiaGX7a1KomGUXUE5T2:bryttr8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @annrpom, @rafiss, and @srosenberg)

___
*[`pkg/cmd/roachtest/tests/secondary_indexes.go` line 57 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/113696#-NiGORZS8CN89ewxoq63:-NiLsVu49-2nDNy0B34-:b-pd3b3j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f515f7051d88079a07a31c86d2b13263d68c4b25/pkg/cmd/roachtest/tests/secondary_indexes.go#L57)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the old code took care to run this command on the node whose binary was upgraded. i don't think the new framework offers us that control. is that correct @renatolabs?  it may be sufficient to just rely on randomization here.
</blockquote></details>

You can achieve the same goal with in the new test with:

```go
upgradeContext := h.Context()
nextVersionDB := func() *gosql.DB {
    upgrading := upgradeContext.ToVersion.Compare(upgradeContext.FromVersion) > 0
    var node int
    var db *gosql.DB
    if upgrading {
        node, db = h.RandomDB(rng, upgradeContext.ToVersion)
    } else {
        node, db = h.RandomDB(rng, upgradeContext.FromVersion) // downgrading
    }

    l.Printf("connecting to n%d", node)
    return db
}

nextVersionDB().ExecContext(/* ... */)
```

There's a recent higher level API being introduced in a WIP PR, but the above should achieve that goal with what exists today. I'll add a note to update this test once that's ready.

**Comment by rafiss** [comment]
tftr!

bors r+

**Comment by rafiss** [comment]
blathers backport 23.1

**Pull request merged**
