### PR TITLE
rfc: update partitioning to match implementation

### PR DESCRIPTION
**Pull request by danhhz**
The major change here is that a table or index that has been partitioned
previously required that all its data was in one of the partitions, but
it no longer does. This was originally added for two reasons: (1) to
make it possible to treat a list partitioning without a DEFAULT like an
enum during query planning and (2) to aid users in maintaining this
invariant about their data (esp both INSERT/UPDATE and repartitionings).

After reflection and discussion, it was decided that there were better
ways to solve both of these. (1) is better served by `SELECT ... FROM
... PARTITION(...)` with all partitions specified or a true enum type
once we have it. For (2), users are already used to using CHECK
constraints for invariants and we can better prevent mistakes during
repartitioning with a dry run mode both for repartitioning and zone
config changes.

This commit also updates the RFC text to match some changes that were
decided during code reviews of the implemenation.

Release note: None

### CODE REVIEW

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20933#-:-L0uYv5iSsJLn4NO2lY1:bnfp4nl)*

**Comment by jordanlewis** [comment]
Changes :lgtm:.

I'd like to request some additional clarity on the `SELECT ... FROM ... PARTITION (...)` syntax based on our offline conversation. Specifically, I'd like to see a paragraph that explains that it's currently purely syntactic sugar that's translated to a `WHERE` clause. You give an example of that, but I think it also needs to live where the syntax is introduced.

I think you should also explain why that syntax is very important, by reminding the reader that it's much less of a burden to have to write the partition names you're looking for than the primary key prefixes that you're looking for, because there's a one-to-many relationship between partition names and primary key prefixes.

You could also mention the other important reason why this syntax is being introduced, which is the potential future data sovereignty requirement that a query be constrained to only touching data in specified partitions.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/20170921_sql_partitioning.md, line 819 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20933#-L1OQqqUZvR7Id1_YLzI:-L1OQqqUZvR7Id1_YLzJ:b459fgz) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e70fc22dec7a7fd4e375a2bc23c458e5a01f5/docs/RFCS/20170921_sql_partitioning.md#L819)):*
> ```Markdown
> 
> 3. A list partitioning without a `DEFAULT` is an enum. The user can use the
>    `SELECT ... FROM roachmart.users PARTITION (north_america, ...)` with all
> ```

something's up with the grammar in this sentence. can use the `...` *syntax*, or something?

---

*[docs/RFCS/20170921_sql_partitioning.md, line 820 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20933#-L1OWJO8ctCXGwQZ1B1l:-L1OWJO8ctCXGwQZ1B1m:b-xmbl9c) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e70fc22dec7a7fd4e375a2bc23c458e5a01f5/docs/RFCS/20170921_sql_partitioning.md#L820)):*
> ```Markdown
> 3. A list partitioning without a `DEFAULT` is an enum. The user can use the
>    `SELECT ... FROM roachmart.users PARTITION (north_america, ...)` with all
>    partitions specified. Internally, the planner will turn this into an `AND
> ```

This is good detail. I think it belongs up above where this syntax is introduced.

---

*[docs/RFCS/20170921_sql_partitioning.md, line 858 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20933#-L1ORMWEFnrdAV_cc_UL:-L1ORMWEFnrdAV_cc_UM:b-4m0syu) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e70fc22dec7a7fd4e375a2bc23c458e5a01f5/docs/RFCS/20170921_sql_partitioning.md#L858)):*
> ```Markdown
> that user (orders, etc) near it. A geographically partitioned user can be moved
> with one `UPDATE`, and the user’s orders (plus the rest of the interleave
> heirarchy) can be moved with `ON UPDATE CASCADE`.
> ```

hierarchy*

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20933#-:-L1OSvrSnavsLreldE0a:b-9zs1r)*

**Comment by danhhz** [comment]
Did everything but mention the sovereignty stuff since my guess is that's likely to cause more confusion than good, given how little we've figured out about it.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[docs/RFCS/20170921_sql_partitioning.md, line 819 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20933#-L1OQqqUZvR7Id1_YLzI:-L1O_sChRu-EJMhtxYAt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e70fc22dec7a7fd4e375a2bc23c458e5a01f5/docs/RFCS/20170921_sql_partitioning.md#L819)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

something's up with the grammar in this sentence. can use the `...` *syntax*, or something?
</blockquote></details>

Done.

---

*[docs/RFCS/20170921_sql_partitioning.md, line 820 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20933#-L1OWJO8ctCXGwQZ1B1l:-L1O_lVXUL2Bh51y9NZB:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e70fc22dec7a7fd4e375a2bc23c458e5a01f5/docs/RFCS/20170921_sql_partitioning.md#L820)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is good detail. I think it belongs up above where this syntax is introduced.
</blockquote></details>

Done.

---

*[docs/RFCS/20170921_sql_partitioning.md, line 858 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/20933#-L1ORMWEFnrdAV_cc_UL:-L1O_w9ERoHMjzG_jaS2:b-gv2ztg) ([raw file](https://github.com/cockroachdb/cockroach/blob/fa6e70fc22dec7a7fd4e375a2bc23c458e5a01f5/docs/RFCS/20170921_sql_partitioning.md#L858)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

hierarchy*
</blockquote></details>

heh, can't even tell you how many times i spelled this wrong while working on interleaved tables

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20933#-:-L1ObGQroiwLgBDWhkYB:b4skb6w)*

**Comment by jordanlewis** [comment]
Thanks! LGTM

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20933#-:-L1Ofuxe6rf4034lZZ9h:b70hlkx)*

**Comment by danhhz** [comment]
Thanks for the reviews!

**Pull request merged**
