### PR TITLE
tests: write allocs for sysbench microbenchmark with -test.benchmem

### PR DESCRIPTION
**Pull request by tbg**
The default Go flag -test.benchmem isn't that useful: it just dumps a
mem profile at the very end. The test setup can allocate significantly,
so for example for BenchmarkSysbench they're not useful.

This commit refines the behavior:

If -test.benchmem is passed, the sysbench tests will write their
individual post-less-pre alloc delta profiles, which captures
exactly the allocations done during the actual benchmark work.

This functionality could also, at some point, help us track the
change in such profiles over time, but for now my motivation to
add this is because (an earlier form of) it has been useful in https://github.com/cockroachdb/cockroach/pull/135146
and I'd like to use the same process for follow-up work.

Epic: none
Release note: None

### CODE REVIEW

**Comment by RaduBerinde** [comment]
Could the same be achieved by moving the non-setup part to a sub-benchmark?

**Comment by tbg** [comment]
> Could the same be achieved by moving the non-setup part to a sub-benchmark?

I don't think so. Sadly `-test.benchmem` is quite basic, it saves exactly one profile at the very end of everything it has run.

**Review by RaduBerinde — APPROVED** [review]
This is great!!

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135560#-:-OBzjLylD0rcYy5WHQ5L:b-6m563k)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @tbg)

___
*[`pkg/sql/tests/sysbench_test.go` line 708 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135560#-OBzhs03EhsnRUSf0S71:-OBzhs047Mp6I6iUNfB0:b-yygta0) ([raw file](https://github.com/cockroachdb/cockroach/blob/addfc16dda6966937a007dc4bfbecc60cb979b61/pkg/sql/tests/sysbench_test.go#L708)):*
> ```Go
> 	var benchMemFile string
> 	pf := pflag.NewFlagSet("test", pflag.ContinueOnError)
> 	pf.StringVar(&benchMemFile, "test.memprofile", "", "")
> ```

[nit Why do we use pflag if we have to manually look for `-test.memprofile` anyway? Can't we just look for it (or the two dash version) and get the next arg?
___
*[`pkg/sql/tests/sysbench_test.go` line 722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135560#-OBziCMJ7cbzdxcXbTvz:-OBziCMJ7cbzdxcXbTw-:bya1uq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/addfc16dda6966937a007dc4bfbecc60cb979b61/pkg/sql/tests/sysbench_test.go#L722)):*
> ```Go
> 	saniRE := regexp.MustCompile(`\W+`)
> 	saniName := saniRE.ReplaceAllString(b.Name(), "_")
> 	dest := strings.ReplaceAll(benchMemFile, ".pb.gz", "") + "_"
> ```

[nit] I don't think using `.pb.gz` is universal. I've seen`.prof`, `.out`, and no extension being used. Maybe separate at the first `'.'`?

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/135560)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[`pkg/sql/tests/sysbench_test.go` line 708 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135560#-OBzhs03EhsnRUSf0S71:-OCJTqUG9R-BT3NsD76N:bicnbjw) ([raw file](https://github.com/cockroachdb/cockroach/blob/addfc16dda6966937a007dc4bfbecc60cb979b61/pkg/sql/tests/sysbench_test.go#L708)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit Why do we use pflag if we have to manually look for `-test.memprofile` anyway? Can't we just look for it (or the two dash version) and get the next arg?
</blockquote></details>

I think of args handling as something that's best left to the professionals. It's unfortunately that I have to add the extra dash here, but at least other than that I don't have to do stuff like making it such that if the flag is passed multiple times the last one wins, et cetera. There are two flags to parse now, so I think `pflag` has amortized :-)
___
*[`pkg/sql/tests/sysbench_test.go` line 722 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/135560#-OBziCMJ7cbzdxcXbTvz:-OCJU1fS2mzKShTjSA3t:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/addfc16dda6966937a007dc4bfbecc60cb979b61/pkg/sql/tests/sysbench_test.go#L722)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] I don't think using `.pb.gz` is universal. I've seen`.prof`, `.out`, and no extension being used. Maybe separate at the first `'.'`?
</blockquote></details>

Done.

**Comment by tbg** [comment]
TFTR!
bors r+

**Pull request merged**
