### PR TITLE
sql: add tsvector and tsquery types to SQL

### PR DESCRIPTION
**Pull request by jordanlewis**
Updates https://github.com/cockroachdb/cockroach/issues/41288.

Broken off from https://github.com/cockroachdb/cockroach/pull/83736

This PR adds the tsvector and tsquery types and pgwire encodings to sql, and makes them available for use using the string::tsvector and string::tsquery casts. It also implements the in-memory evaluation of @@ (the tsquery match operator) by delegating to the tsearch.eval package.

Release note (sql change): implement in memory handling for the tsquery and tsvector Postgres datatypes, which provide text search capabilities. See https://www.postgresql.org/docs/current/datatype-textsearch.html for more details.

Epic: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
this is looking good! is there already a cluster version gate on being able to use these new types?

> Reviewed 16 of 63 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-:-NH1Co-Z5d6lFZPv53yK:b-ldh137)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @renatolabs, and @srosenberg)

___
*[`pkg/sql/pgwire/types.go` line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1DCltBwJQ-TsCxXTq:-NH1DCltBwJQ-TsCxXTr:bn6txim) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/pgwire/types.go#L244)):*
> ```Go
> 
> 	case *tree.DTSQuery:
> 		b.writeLengthPrefixedString(v.String())
> ```

does this take care of "tree written in infix notation. Example: ( 'abc':*B | 'def' ) & !'ghi'". 
___
*[`pkg/sql/pgwire/types.go` line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1D2hY8IjbNjeoyUtK:-NH1D2hY8IjbNjeoyUtL:b1lqc0e) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/pgwire/types.go#L247)):*
> ```Go
> 
> 	case *tree.DTSVector:
> 		b.writeLengthPrefixedString(v.String())
> ```

does this take care of " As seen above. ' is escaped with '' and \ is escaped with \\." consider adding a separate function for the pgwire text encodings to make this more explicit.
___
*[`pkg/sql/rowenc/valueside/array.go` line 322 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1Det8D_2Jo3a7YFeJ:-NH1Det8D_2Jo3a7YFeK:b-1d4c3x) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/rowenc/valueside/array.go#L322)):*
> ```Go
> 		return encoding.EncodeUntaggedBytesValue(b, encoded), nil
> 	case *tree.DTSVector:
> 		encoded := tsearch.EncodeTSVector(nil, t.TSVector)
> ```

why do you use the `PGBinary` version for tsquery, but not for tsvector?
___
*[`pkg/sql/rowenc/valueside/encode.go` line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1DtVbEHG39tddZ-lx:-NH1DtVbEHG39tddZ-ly:b-nmezja) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/rowenc/valueside/encode.go#L88)):*
> ```Go
> 		return encoding.EncodeTSQueryValue(appendTo, uint32(colID), encoded), nil
> 	case *tree.DTSVector:
> 		encoded := tsearch.EncodeTSVector(scratch, t.TSVector)
> ```

ditto question about `PGBinary`
___
*[`pkg/sql/sem/cast/cast_map_gen.sh` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1ESM88h6MNl3MPzc4:-NH1ESM88h6MNl3MPzc5:bmuuh2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1c3e7777b28a30ebe41428fb173f0156e8968c/pkg/sql/sem/cast/cast_map_gen.sh#L12)):*
> ```Shell
> DATABASE="${1-postgres}"
> 
> psql $DATABASE -Xqtc "SELECT postgis_full_version()" &> /dev/null
> ```

why was this removed?
___
*[`pkg/util/tsearch/encoding.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1ALUg5DLVp5Z_InVM:-NH1ALUh8w2ldM5RSpj0:b8y4u9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L22)):*
> ```Go
> )
> 
> // EncodeTSVector encodes a tsvector into a serialized representation.
> ```

can you say when you would use this, versus `EncodeTSVectorPGBinary`?
___
*[`pkg/util/tsearch/encoding.go` line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1AV6R5LRSzuxwRglv:-NH1AV6R5LRSzuxwRglw:b-cb7kys) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L87)):*
> ```Go
> //	The words are sorted when parsed, and only written once. Positions are also sorted and only written once.
> //	For some reason, the unique check does not seem to be made for binary input, only text input...
> //	text: As seen above. ' is escaped with '' and \ is escaped with \\.
> ```

what is "as seen above" referencing? if this is copied from https://www.npgsql.org/dev/types.html we should link to it

also, this is the "text" encoding, which i don't think we need in this comment
___
*[`pkg/util/tsearch/encoding.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1BD-GB1l9w7-sAbst:-NH1BD-GB1l9w7-sAbsu:b4yi9a1) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L101)):*
> ```Go
> 		appendTo = append(appendTo, []byte(l)...)
> 		appendTo = append(appendTo, byte(0))
> 		appendTo = encoding.EncodeUint16Ascending(appendTo, uint16(len(term.positions)))
> ```

should it error if `len(positions)` is greater than `MaxUint16`?
___
*[`pkg/util/tsearch/encoding.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1A5a8DkJHh7-oXkxD:-NH1A5a8DkJHh7-oXkxE:b-bmqks8) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L108)):*
> ```Go
> 				return nil, err
> 			}
> 			// TODO(jordan): do we need to clear the top 2 bits first?
> ```

how can we find out how to answer this?
___
*[`pkg/util/tsearch/encoding.go` line 160 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1BMUR9aTPkzTgliYW:-NH1BMUR9aTPkzTgliYX:b-866d4n) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L160)):*
> ```Go
> // A tree with operands and operators (&, |, !). Operands are strings,
> // with optional weight (bitmask of ABCD) and prefix search (yes/no, written with *).
> // text: the tree written in infix notation. Example: ( 'abc':*B | 'def' ) & !'ghi'
> ```

nit: don't need the `text` encoding in this comment
___
*[`pkg/util/tsearch/encoding.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1BqB78utwnKvdTeeX:-NH1BqB78utwnKvdTeeY:b-3svja) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L164)):*
> ```Go
> // First the number of tokens (a token is an operand or an operator).
> // For each token:
> // UInt8 type (1 = val, 2 = oper) followed by
> ```

https://www.npgsql.org/dev/types.html had some indentation here that made it easier to read
___
*[`pkg/util/tsearch/random.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1CMQv39Y5U5tUR3-R:-NH1CMQv39Y5U5tUR3-S:b4i772) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/random.go#L21)):*
> ```Go
> var alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
> 
> // RandomTSVector returns a random TSVector for testing.
> ```

can these go into a test file?

**Review by jordanlewis — COMMENTED** [review]
TFTR!

Added gates for the casts, which should be enough since we don't have disk-storage yet in this PR.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-:-NH2cRnpB09pPUqL8IbS:b-bujb1p)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rafiss, @renatolabs, and @srosenberg)

___
*[`pkg/sql/pgwire/types.go` line 244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1DCltBwJQ-TsCxXTq:-NH1wo_hDblWv_8MEsMX:bc8u3et) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/pgwire/types.go#L244)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this take care of "tree written in infix notation. Example: ( 'abc':*B | 'def' ) & !'ghi'". 
</blockquote></details>

Yes, this is how the String method works.
___
*[`pkg/sql/pgwire/types.go` line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1D2hY8IjbNjeoyUtK:-NH1wq1T-QOlfaPYpb2M:b-q5igo1) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/pgwire/types.go#L247)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

does this take care of " As seen above. ' is escaped with '' and \ is escaped with \\." consider adding a separate function for the pgwire text encodings to make this more explicit.
</blockquote></details>

Yes, also just how the string function works. I guess I could make it more explicit, but I think it's typical that we have the .String() method produce the same output that you'd see on the commandline, which is the same as the text serialization format usually, right?

I'm just looking at how the JSON case above works as prior art here.
___
*[`pkg/sql/rowenc/valueside/array.go` line 322 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1Det8D_2Jo3a7YFeJ:-NH1x9NZ8YdhzIh3Z2Fk:bd0sepl) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/rowenc/valueside/array.go#L322)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why do you use the `PGBinary` version for tsquery, but not for tsvector?
</blockquote></details>

I created a hand-rolled TSVector storage format while implementing TSVector, but re-used the PGBinary one for TSQuery. There's no real rhyme or reason to this, just how the implementation started.

Thinking it over, I think the main reason to have different functions is if the PG wire protocol evolves in a new version - in that case, we would need to copy the function and only change the wire protocol one.

I went ahead and made a new version for TSQuery. It's identical to the PGBinary one, except it uses the Cockroach-style length-prefixed strings instead of the Postgres-style 0-byte terminated strings.
___
*[`pkg/sql/rowenc/valueside/encode.go` line 88 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1DtVbEHG39tddZ-lx:-NH3-zBx98RZw7-1yFd1:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/rowenc/valueside/encode.go#L88)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

ditto question about `PGBinary`
</blockquote></details>

Done.
___
*[`pkg/sql/sem/cast/cast_map_gen.sh` line 12 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1ESM88h6MNl3MPzc4:-NH1xvF9CdQBm4gDk8tn:b-kcy50i) ([raw file](https://github.com/cockroachdb/cockroach/blob/0c1c3e7777b28a30ebe41428fb173f0156e8968c/pkg/sql/sem/cast/cast_map_gen.sh#L12)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why was this removed?
</blockquote></details>

Oops, thanks for catching this - I deleted it temporarily because I couldn't figure out how to install postgis locally to run this script.
___
*[`pkg/util/tsearch/encoding.go` line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1ALUg5DLVp5Z_InVM:-NH2jqnp814jd2A2lqME:bgkbmrc) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L22)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can you say when you would use this, versus `EncodeTSVectorPGBinary`?
</blockquote></details>

This one is for on-disk storage, and the other one is for pg binary wire protocol.
___
*[`pkg/util/tsearch/encoding.go` line 87 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1AV6R5LRSzuxwRglv:-NH1yWxQ0bndhsUj3Tvz:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L87)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what is "as seen above" referencing? if this is copied from https://www.npgsql.org/dev/types.html we should link to it

also, this is the "text" encoding, which i don't think we need in this comment
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/encoding.go` line 101 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1BD-GB1l9w7-sAbst:-NH2-6NV9PJ9DHygQvzH:b-iq3doz) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L101)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

should it error if `len(positions)` is greater than `MaxUint16`?
</blockquote></details>

Yes, it should. I am missing a bunch of max length checks, I've added them and tests.
___
*[`pkg/util/tsearch/encoding.go` line 108 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1A5a8DkJHh7-oXkxD:-NH1yXd8Dtqrmmv20U0t:bfvo66) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L108)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

how can we find out how to answer this?
</blockquote></details>

It was leftover when writing this code, it's not necessary.
___
*[`pkg/util/tsearch/encoding.go` line 164 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1BqB78utwnKvdTeeX:-NH2Tge5AVVMraxHJF4g:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/encoding.go#L164)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

https://www.npgsql.org/dev/types.html had some indentation here that made it easier to read
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/random.go` line 21 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1CMQv39Y5U5tUR3-R:-NH2ThjfCgulApb2GONJ:bktq7jc) ([raw file](https://github.com/cockroachdb/cockroach/blob/16094d20a4e28763e35cf4d633009c485295f924/pkg/util/tsearch/random.go#L21)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

can these go into a test file?
</blockquote></details>

They cannot, because of the way randgen is set up (it's a non-test package).

**Review by rafiss — CHANGES_REQUESTED** [review]
one more request for tests: can you add encoding tests for the new types to `pgwire.TestEncodings`?

1. Add examples to pkg/cmd/generate-binary/main.go
2. Start PG server
3. `cd pkg/cmd/generate-binary; go run main.go > ../../sql/pgwire/testdata/encodings.json`
4. I think there might be some tech debt so that some of the float encodings are incorrectly adjusted. undo that part of the diff

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-:-NHaWhK4EJ8bZo0Bt8rS:b-2u2soy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @jordanlewis, @renatolabs, and @srosenberg)

___
*[`pkg/sql/pgwire/types.go` line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1D2hY8IjbNjeoyUtK:-NHaV4URBqWi6I8tN6Nu:b56szbn) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/pgwire/types.go#L247)):*
> .String() method produce the same output that you'd see on the commandline, which is the same as the text serialization format usually

i don't think there is a standard one way or another about `String`. the reliable way to get the pgwire text format is to use the `FmtPgwireText` flag, but as you say, not all types need that. for example, arrays and tuples do need it. might as well use it here too
___
*[`pkg/sql/rowenc/valueside/array.go` line 322 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1Det8D_2Jo3a7YFeJ:-NHaXWwG1FYi3wd8C5gx:bb7ohn6) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/rowenc/valueside/array.go#L322)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I created a hand-rolled TSVector storage format while implementing TSVector, but re-used the PGBinary one for TSQuery. There's no real rhyme or reason to this, just how the implementation started.

Thinking it over, I think the main reason to have different functions is if the PG wire protocol evolves in a new version - in that case, we would need to copy the function and only change the wire protocol one.

I went ahead and made a new version for TSQuery. It's identical to the PGBinary one, except it uses the Cockroach-style length-prefixed strings instead of the Postgres-style 0-byte terminated strings.
</blockquote></details>

sgtm

**Review by jordanlewis — COMMENTED** [review]
I forgot about this test - good suggestion, it turned up 2 bugs in the pgwire encoding. It would be nice if we didn't have to hand-generate these but I guess I don't see a better way given that you need a running pg server to make it happen.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-:-NHfIk8HEyeyadFx8M_r:buatj80)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @rafiss, @renatolabs, and @srosenberg)

___
*[`pkg/sql/pgwire/types.go` line 247 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1D2hY8IjbNjeoyUtK:-NHfIiqt8HPPWNJUYkfE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/pgwire/types.go#L247)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

> .String() method produce the same output that you'd see on the commandline, which is the same as the text serialization format usually

i don't think there is a standard one way or another about `String`. the reliable way to get the pgwire text format is to use the `FmtPgwireText` flag, but as you say, not all types need that. for example, arrays and tuples do need it. might as well use it here too
</blockquote></details>

Done.
___
*[`pkg/sql/rowenc/valueside/array.go` line 322 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-NH1Det8D_2Jo3a7YFeJ:-NHfIjY4AkWBqa8A8rVE:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fb8a80dcb5028ccc34307f968181158c5201dc11/pkg/sql/rowenc/valueside/array.go#L322)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

sgtm
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
lgtm!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/90842#-:-NIIwT3S2x2_eRdIw8Zi:b-7nbn20)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner, @renatolabs, and @srosenberg)

**Comment by jordanlewis** [comment]
TFTR!

bors r+

**Comment by rafiss** [comment]
@jordanlewis somehow this passed CI even though benchmarks fail with
```
10:47:17       --- FAIL: BenchmarkAsJSON/tsquery
10:47:17           json_test.go:56: unexpected type *tree.DTSQuery for AsJSON
10:47:17       --- FAIL: BenchmarkAsJSON/tsvector
10:47:17           json_test.go:56: unexpected type *tree.DTSVector for AsJSON
```
https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelEssentialCi/7844044?

**Comment by srosenberg** [comment]
It failed on Bazel Extended CI [1] during the original run. Note that microbenches are _not_ executed by `bors`. The latter runs only Bazel Essential CI. @herkolategan FYI as we were discussing something related earlier today.

[1] https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_BazelExtendedCi/7708653

**Pull request merged**
