### PR TITLE
colexec: track more memory via the Allocator

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: add Copy method to Allocator**

This commit adds Copy method to Allocator and updates all previous
usages of coldata.Vec.Copy to go through it.

Release note: None

**colexec: make sure that execgen.SETs are accounted for**

This commit make sure that all memory that is allocated during
execgen.SETs is tracked by the allocator. In order to do that
Allocator's performOperation primitive is used. In some cases, we have
a special casing for Bytes type so that the accounting doesn't impact
the fast path for other types (for which the memory account will not be
updated during SET).

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
First three commits are a part of a separate PR.

**Review by asubiotto — DISMISSED** [review]
This perform operation thing is really cool, I like how you did it. Could you also run a couple of benchmarks to check the performance hit? I think it should be ok given it's per-batch but might be worth checking. If that looks good consider this a :lgtm: since I'll be away from my computer

> Reviewed 9 of 9 files at r4, 16 of 16 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42684#-:-LuI0e7J65YR3zKUZ1p9:b6epu3w)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colexec/allocator.go, line 102 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42684#-LuI0DdNAJIWciHs66sX:-LuI0DdNAJIWciHs66sY:b-dhw62d) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcc3b9ae78a59f4e85851dab928545ff3b0aad7d/pkg/sql/colexec/allocator.go#L102)):*
> ```Go
> 			after += int64(dest.Bytes().Size())
> 		} else {
> 			after += int64(estimateBatchSizeBytes([]coltypes.T{dest.Type()}, dest.Length()))
> ```

Why did this have to change to `+=`?
___
*[pkg/sql/colexec/allocator.go, line 161 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42684#-LuI0HHB4N_mQN1Gv3gc:-LuI0HHB4N_mQN1Gv3gd:b-ndmz9) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcc3b9ae78a59f4e85851dab928545ff3b0aad7d/pkg/sql/colexec/allocator.go#L161)):*
> ```Go
> 		case coltypes.Bytes:
> 			// Bytes type is estimated to take up no actual space because its memory
> 			// footprint is tracked separately.
> ```

Might be worth it to add an extra explanation about how.

**Review by yuzefovich — COMMENTED** [review]
I ran benchmarks (all existing ones that are touched by the changes) and found one performance hit (in merge joiner) which I addressed (more or less).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/42684#-:-LuJ80_o-wIZJcGIWSBf:bp89dnd)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto)

___
*[pkg/sql/colexec/allocator.go, line 102 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42684#-LuI0DdNAJIWciHs66sX:-LuIzclBCIGC-B3umqha:bmk8kvy) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcc3b9ae78a59f4e85851dab928545ff3b0aad7d/pkg/sql/colexec/allocator.go#L102)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why did this have to change to `+=`?
</blockquote></details>

We now perform the operation on multiple `coldata.Vec`s, so we're iterating over all `Vec`s that are passed in and aggregating the memory usages.
___
*[pkg/sql/colexec/allocator.go, line 161 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/42684#-LuI0HHB4N_mQN1Gv3gc:-LuJ7jiw1ZQjqlvFkP3t:b6pgvi4) ([raw file](https://github.com/cockroachdb/cockroach/blob/fcc3b9ae78a59f4e85851dab928545ff3b0aad7d/pkg/sql/colexec/allocator.go#L161)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Might be worth it to add an extra explanation about how.
</blockquote></details>

Actually your comment made me realize that I wasn't correct - we do allocate some memory when creating a new `Bytes` object. I updated the code and the comment.

**Comment by yuzefovich** [comment]
I'll go ahead and merge this since the performance impact is negligible (only noticeable with merge joiner on "both side repeat" sub-benchmark).

TFTR!

bors r+

**Comment by yuzefovich** [comment]
Seems like a flake.

bors r+

**Pull request merged**
