### PR TITLE
util/tracing: make some span options in singletons 

### PR DESCRIPTION
**Pull request by andreimatei**
A couple of span creation options are empty structs implementing the
SpanOption interface. Being an empty struct, putting it in an interface
doesn't allocate as the compiler optimizes small types in interfaces.
Still, the output of `gcflags=-m` lists the value as escaping to the
heap, very confusingly. This patch introduces singletons for the structs
to make it clear that there's no allocation.

Release note: None

### CODE REVIEW

**Review by nvb — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/util/tracing/span_options.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71056#-MlL2P_m1MxHgukKk-Rw:-MlL2P_m1MxHgukKk-Rx:b-aazyut) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ceee6ab098c39719985074dd2c954549effede/pkg/util/tracing/span_options.go#L191)):*
> ```
> // Allocating this option as a singleton avoids allocating anew in every call to
> // WithFollowsFrom.
> ```

This isn't true, for the reason you listed in the commit message. Stuffing an empty struct into an interface does not allocate. Given that, is this change worth the added complexity and reduction in code clarity?

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71056)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[pkg/util/tracing/span_options.go, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/71056#-MlL2P_m1MxHgukKk-Rw:-MlLBYqYBH78zO0kGYbG:b-h9hfkx) ([raw file](https://github.com/cockroachdb/cockroach/blob/24ceee6ab098c39719985074dd2c954549effede/pkg/util/tracing/span_options.go#L191)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> ```
> // Allocating this option as a singleton avoids allocating anew in every call to
> // WithFollowsFrom.
> ```

This isn't true, for the reason you listed in the commit message. Stuffing an empty struct into an interface does not allocate. Given that, is this change worth the added complexity and reduction in code clarity?
</blockquote></details>

I've removed the comment.

If you'll agree, I think this is worth merging. You say "added complexity", but I don't see it; if anything, it's complexity reduction: what's simpler than returning a global? So I don't think any commentary is even needed.
The code around tracing is, and will continue to be, heavily scrutinized for allocations, so the fact that the compiler's output suggests an allocation for these options is quite obnoxious. I'd like to avoid others going through the rabbit hole I went in.
WDYT?

**Comment by nvanbenschoten** [comment]
> The code around tracing is, and will continue to be, heavily scrutinized for allocations, so the fact that the compiler's output suggests an allocation for these options is quite obnoxious.

The compiler's output does not suggest an allocation. A value escaping to the heap is different from a value being moved to the heap. If you're searching for allocations, you should be looking for `moved to heap` in the compiler output.

**Review by nvb — APPROVED** [review]
Talked in person. I'm fine with this now that the comments are gone.

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/71056#-:-MlQVq1yEXZaWi-sRAGp:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Pull request merged**
