### PR TITLE
pgwire improvements

### PR DESCRIPTION
**Pull request by madelynnblue**

### CODE REVIEW

**Comment by knz** [comment]
I'm sorry it's unlikely I can review this today. It may have to wait next week (and thus later if you are on vacation).

Please defer to Bob and I would recommend @BramGruneir too.

**Review by bobvawter — CHANGES_REQUESTED** [review]
:lgtm: Just needs some comments for folks not already intimately familiar with the code.

> Reviewed 2 of 2 files at r1, 16 of 16 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-:-LQETtqq12CgjWUlxio0:b-7r5ozm)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/cmp-protocol/main.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQEQVaJAWntVKgPnDeQ:-LQEQVaJAWntVKgPnDeR:brsz0c0) ([raw file](https://github.com/cockroachdb/cockroach/blob/27f6da8efb3262bb25917bd29ac98ea71ac46aec/pkg/cmd/cmp-protocol/main.go#L58)):*
> ```Go
> 	} else {
> 		go func() {
> 			rng := rand.New(rand.NewSource(0)) // time.Now().Unix()))
> ```

Dangling comment.  Maybe make the seed a flag?
___
*[pkg/cmd/cmp-protocol/main.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQESUpxD6aqkycc4Jee:-LQESUpxD6aqkycc4Jef:b-44jz33) ([raw file](https://github.com/cockroachdb/cockroach/blob/4615c6a0fcc1fa8654d6f638086a8f249031d38d/pkg/cmd/cmp-protocol/main.go#L98)):*
> ```Go
> }
> 
> func compare(w io.Writer, input, pg, cr, pgUser, crUser string) error {
> ```

pgAddr, crAddr for clarity?
___
*[pkg/sql/pgwire/encoding_test.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQETEd30UHD5sx28jOu:-LQETEd30UHD5sx28jOv:b-h0bq5c) ([raw file](https://github.com/cockroachdb/cockroach/blob/712ce6de1f361cc3419e94fa101dc8e6b841b250/pkg/sql/pgwire/encoding_test.go#L78)):*
> ```Go
> 			}
> 
> 			{
> ```

Why a block here?
___
*[pkg/sql/pgwire/encoding_test.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQETJcIDphEavF3rLtS:-LQETJcIDphEavF3rLtT:b15mgbh) ([raw file](https://github.com/cockroachdb/cockroach/blob/712ce6de1f361cc3419e94fa101dc8e6b841b250/pkg/sql/pgwire/encoding_test.go#L84)):*
> ```Go
> 					t.Fatal(buf.err)
> 				}
> 				got := buf.wrapped.Bytes()[4:]
> ```

Comment to explain the magic constant 4?
___
*[pkg/sql/pgwire/encoding_test.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQEU6dE4_Pnm9mRis2Z:-LQEU6dE4_Pnm9mRis2_:bp1bwp8) ([raw file](https://github.com/cockroachdb/cockroach/blob/4615c6a0fcc1fa8654d6f638086a8f249031d38d/pkg/sql/pgwire/encoding_test.go#L33)):*
> ```Go
> )
> 
> func TestEncodings(t *testing.T) {
> ```

Add a comment for a future engineer to point at how they can regenerate `encodings.json` if this test breaks due to future work.
___
*[pkg/sql/pgwire/types.go, line 197 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQEUWMa7oh06WNV4OiV:-LQEUWMa7oh06WNV4OiW:b-8kw5m3) ([raw file](https://github.com/cockroachdb/cockroach/blob/4615c6a0fcc1fa8654d6f638086a8f249031d38d/pkg/sql/pgwire/types.go#L197)):*
> ```Go
> 	case *tree.DBitArray:
> 		words, lastBitsUsed := v.EncodingParts()
> 		b.putInt32(4 + int32(8*(len(words)-1)) + int32((lastBitsUsed+7)/8))
> ```

What magic is this?

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32091)* status: :shipit: complete! 1 of 0 LGTMs obtained

___
*[pkg/cmd/cmp-protocol/main.go, line 58 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQEQVaJAWntVKgPnDeQ:-LQFchBw4qB7x8DP-BcC:bsw1l3d) ([raw file](https://github.com/cockroachdb/cockroach/blob/27f6da8efb3262bb25917bd29ac98ea71ac46aec/pkg/cmd/cmp-protocol/main.go#L58)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Dangling comment.  Maybe make the seed a flag?
</blockquote></details>

changed to use our internal randutil
___
*[pkg/cmd/cmp-protocol/main.go, line 98 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQESUpxD6aqkycc4Jee:-LQFcmfg7Gr61plcKjKX:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4615c6a0fcc1fa8654d6f638086a8f249031d38d/pkg/cmd/cmp-protocol/main.go#L98)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

pgAddr, crAddr for clarity?
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/encoding_test.go, line 78 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQETEd30UHD5sx28jOu:-LQFdR_740sUzJU6m93x:b-r8pl3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/712ce6de1f361cc3419e94fa101dc8e6b841b250/pkg/sql/pgwire/encoding_test.go#L78)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Why a block here?
</blockquote></details>

Because text encoding is coming and these will be turned into subtests.
___
*[pkg/sql/pgwire/encoding_test.go, line 84 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQETJcIDphEavF3rLtS:-LQFdbxR9jVyU-YNN4aK:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/712ce6de1f361cc3419e94fa101dc8e6b841b250/pkg/sql/pgwire/encoding_test.go#L84)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Comment to explain the magic constant 4?
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/encoding_test.go, line 33 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQEU6dE4_Pnm9mRis2Z:-LQFdQyN9MkaoVNQ_CPI:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/4615c6a0fcc1fa8654d6f638086a8f249031d38d/pkg/sql/pgwire/encoding_test.go#L33)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

Add a comment for a future engineer to point at how they can regenerate `encodings.json` if this test breaks due to future work.
</blockquote></details>

Done.
___
*[pkg/sql/pgwire/types.go, line 197 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LQEUWMa7oh06WNV4OiV:-LQFfJzE5O-51gRQXUl2:b-va3jmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/4615c6a0fcc1fa8654d6f638086a8f249031d38d/pkg/sql/pgwire/types.go#L197)):*
<details><summary><i>Previously, bobvawter (Bob Vawter) wrote…</i></summary><blockquote>

What magic is this?
</blockquote></details>

Add a comment to explain.

**Review by bobvawter — APPROVED** [review]

**Review by knz — COMMENTED** [review]
:lgtm: but I have a few suggestions for readability improvements, see below

> Reviewed 1 of 2 files at r1, 18 of 18 files at r4, 14 of 16 files at r5, 3 of 3 files at r7, 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-:-LRSSDta5-Au0ZS4ZZPn:bvoyqpx)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/cmd/cmp-protocol/main.go, line 64 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LRSRTA7B3Vm7Vgho6IL:-LRSRTA7B3Vm7Vgho6IM:bfep06h) ([raw file](https://github.com/cockroachdb/cockroach/blob/403827ff1b20e27a888d6679d04383d978eede27/pkg/cmd/cmp-protocol/main.go#L64)):*
> ```Go
> 				switch sem {
> 				case sqlbase.ColumnType_DECIMAL, // trailing zeros differ, ok
> 					sqlbase.ColumnType_COLLATEDSTRING, // pg complains about utf8
> ```

you might be able to resolve the problem with collated strings by specifying the `client_encoding` in the connection parameters.
___
*[pkg/cmd/cmp-protocol/pgconnect/pgconnect.go, line 55 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LRSRJFIEDZL64oVuM6B:-LRSRJFJBb2SUWGyiq0W:b-qoz1a2) ([raw file](https://github.com/cockroachdb/cockroach/blob/403827ff1b20e27a888d6679d04383d978eede27/pkg/cmd/cmp-protocol/pgconnect/pgconnect.go#L55)):*
> ```Go
> 	var res []byte
> 	g := ctxgroup.WithContext(ctx)
> 	g.GoCtx(func(ctx context.Context) error {
> ```

could you perhaps enhance this code with comments that describe the role of each goroutine.
___
*[pkg/cmd/cmp-protocol/pgconnect/pgconnect.go, line 94 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/32091#-LRSRN7aAHEfX22L01kZ:-LRSRN7aAHEfX22L01k_:bbg6zaf) ([raw file](https://github.com/cockroachdb/cockroach/blob/403827ff1b20e27a888d6679d04383d978eede27/pkg/cmd/cmp-protocol/pgconnect/pgconnect.go#L94)):*
> ```Go
> 	g.GoCtx(func(ctx context.Context) error {
> 		send <- &pgproto3.StartupMessage{
> 			ProtocolVersion: 196608,
> ```

A comment which explains the magic number here would be welcome.

**Comment by knz** [comment]
(also my apologies for not reviewing this earlier)

**Pull request merged**
