### PR TITLE
sql: pass stopper.ShouldQuiesce() to retryFunc for TemporaryObjectCleaner

### LINKED ISSUE #47047: sql: temporary schema code causes slowdown in tests
I noticed various simple tests (like `TestChartCatalogGen`) occasionally taking ~15 seconds. The logs suggest that we are waiting to stop the server and the temporary schema code keeps retrying:
```
I200405 00:49:55.632477 3931 util/stop/stopper.go:539  quiescing
W200405 00:49:55.632530 6061 kv/kvserver/intentresolver/intent_resolver.go:745  failed to gc transaction record: could not GC completed transaction anchored at /Table/SystemConfigSpan/Start: node unavailable; try another peer
E200405 00:49:55.632533 5034 kv/kvserver/queue.go:1089  [n1,raftlog,s1,r3/1:/System/{NodeLive…-tsd}] node unavailable; try another peer
W200405 00:49:55.632553 5404 sql/temporary_schema.go:430  [n1] error during schema cleanup, retrying: failed to send RPC: sending to all 1 replicas failed; last error: (err: [NotLeaseHolderError] r26: replica (n1,s1):1 not lease holder; lease holder unknown) <nil>
W200405 00:49:56.604126 5404 sql/temporary_schema.go:430  [n1] error during schema cleanup, retrying: node unavailable; try another peer
W200405 00:49:58.822833 5404 sql/temporary_schema.go:430  [n1] error during schema cleanup, retrying: node unavailable; try another peer
W200405 00:50:02.607569 5404 sql/temporary_schema.go:430  [n1] error during schema cleanup, retrying: node unavailable; try another peer
W200405 00:50:10.180665 5404 sql/temporary_schema.go:430  [n1] error during schema cleanup, retrying: node unavailable; try another peer
W200405 00:50:10.180735 5404 sql/temporary_schema.go:551  [n1] failed to clean temp objects: node unavailable; try another peer
I200405 00:50:10.180765 5404 sql/temporary_schema.go:562  [n1] temporary object cleaner next scheduled to run at 2020-04-05 01:19:55.595077005 +0000 UTC
```

This happens frequently enough that when running tests for a big package, a handful of tests hit this, with a big impact in the overall test time.

Perhaps we should be checking `stopper.ShouldQuiesce()` before retrying.

### PR DESCRIPTION
**Pull request by otan**
Resolves https://github.com/cockroachdb/cockroach/issues/47047.

This fixes a bug where the temporary object cleaner can hang during
object shutdown by not obeying stopper.ShouldQuiesce(). I've run
`TestChartCatalogGen` 10 times and confirmed it all takes the same
amount of time.

Release note: None

### CODE REVIEW

**Comment by otan** [comment]
(the bot will ping for external contributors and me, for testing reasons)

**Review by RaduBerinde — COMMENTED** [review]
Thanks for the quick fix! :lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47048#-:-M47ODR6CjFX2DCtD99k:b-w3daj9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan and @RaduBerinde)

___
*[pkg/sql/temporary_schema.go, line 429 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47048#-M47O0M01IJJI8f7MFIR:-M47O0M14e-dlrbL2TaS:b-vanesw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9c587675aa5ccd2257ec55cb4e843e53f0355c5/pkg/sql/temporary_schema.go#L429)):*
> ```Go
> 			retry.Options{
> 				InitialBackoff: 1 * time.Second,
> 				MaxBackoff:     1 * time.Minute, Multiplier: 2,
> ```

[nit] newline before Multiplier

**Comment by otan** [comment]
bors r=RaduBerinde

**Comment by otan** [comment]
flakes

bors r=RaduBerinde

**Comment by otan** [comment]
flakes

bors r=RaduBerinde

**Comment by andreimatei** [comment]
Thanks Oliver! Are you gonna backport this?
Btw, any idea why bisecting #47011 seemed to indicate #46832 as the culprit? Had I fooled myself?

**Comment by otan** [comment]
> Thanks Oliver! Are you gonna backport this?
yes, along with https://github.com/cockroachdb/cockroach/pull/47063

> Btw, any idea why bisecting #47011 seemed to indicate #46832 as the culprit? Had I fooled myself?
nope. maybe your computer doesn't like you? haha!

**Pull request merged**
