### PR TITLE
sql: simplify+generalize control statements

### LINKED ISSUE #22907: sql: enable cancelling multiple queries in a single statement
`CANCEL QUERY` only takes a single query id. It would be good to be able to cancel multiple queries at once.

Bikeshed, something like `CANCEL QUERIES WHERE...` ?

### PR DESCRIPTION
**Pull request by knz**
The following statements gain the ability to operate on multiple entries at once:

- `CANCEL SESSIONS`
- `CANCEL QUERIES`
- `CANCEL JOBS`
- `RESUME JOBS`
- `PAUSE JOBS`

See individual commits for details.

Fixes #22907.

cc @cockroachdb/sql

### CODE REVIEW

**Comment by RaduBerinde** [comment]
I have never looked at any of this code before, not sure why I'm the reviewer. CC @jordanlewis @andreimatei

**Comment by justinj** [comment]
:lgtm:

We should make sure the semantics here are clearly documented, for example, that if an error occurs at row `n`, rows `1` to `n-1` will be cancelled and any after `n` won't be (right?)

---

Review status: 0 of 26 files reviewed at latest revision, all discussions resolved.

---

*[pkg/sql/cancel_queries.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25157#-LBLuVjhAGiGR6lBtUTn:-LBLuVjhAGiGR6lBtUTo:bxqvv27) ([raw file](https://github.com/cockroachdb/cockroach/blob/decd03410716b0179e24beedd116a71465735966/pkg/sql/cancel_queries.go#L1)):*
> ```Go
> // Copyright 2017 The Cockroach Authors.
> ```

nit: 2018

---

*[pkg/sql/cancel_queries.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25157#-LBLvrPj51hqIh6OVrcs:-LBLvrPj51hqIh6OVrct:b9ofp1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50d6d5e783a2030d805c10b3c34158c1823cbde/pkg/sql/cancel_queries.go#L89)):*
> ```Go
> 	}
> 
> 	if !response.Canceled && !n.ifExists {
> ```

When can this happen? What if a query happened to finish in between starting the cancellation and now or something? I would think we might still want to finish out the batch instead of erroring fast?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25157#-:-LBLrha42wNokGxQvYwX:bexpmi1)*

**Comment by andreimatei** [comment]
Reviewed 6 of 19 files at r1.
Review status: 0 of 26 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/sql/cancel_queries.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25157#-LBLvrPj51hqIh6OVrcs:-LBMJsWFCk-hKZH0ac6B:bwqjdfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50d6d5e783a2030d805c10b3c34158c1823cbde/pkg/sql/cancel_queries.go#L89)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

When can this happen? What if a query happened to finish in between starting the cancellation and now or something? I would think we might still want to finish out the batch instead of erroring fast?
</blockquote></details>

I also think we should continue canceling the others and reporting all the errors at the end. And I think implementing `Next()` like this doesn't make much sense - what does it mean to iterate throught this CancelQueries node if `values()` doesn't return anything? I'd just make it perform all the work on the first `Next()` call.

---

*[pkg/sql/executor.go, line 1254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25157#-LBMG-yX0Ia9Ug8dxKQJ:-LBMG-yX0Ia9Ug8dxKQK:bdij9qb) ([raw file](https://github.com/cockroachdb/cockroach/blob/decd03410716b0179e24beedd116a71465735966/pkg/sql/executor.go#L1254)):*
> ```Go
> 
> 	// Ignore statements that spawn jobs from SHOW QUERIES and from being cancellable
> 	// using CANCEL QUERIES. Jobs have their own run control statements (CANCEL JOB,
> ```

please dont change this file :)

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25157)*

**Comment by mjibson** [comment]
`CANCEL JOBS` uses a txn to do the canceling (i.e., it doesn't have side effects outside of a KV put). So if we do document the behavior of an error in the middle, JOBS isn't like the others.

**Comment by knz** [comment]
> We should make sure the semantics here are clearly documented, for example, that if an error occurs at row n, rows 1 to n-1 will be cancelled and any after n won't be (right?)

Agreed. I have added an explanation to this effect in the commit messages. This is to preserve symmetry with the JOB commands, like Matt explained.

---

Review status: 0 of 25 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/cancel_queries.go, line 1 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25157#-LBLuVjhAGiGR6lBtUTn:-LBOWOJoA5n_vxihqNyO:b-4f29dk) ([raw file](https://github.com/cockroachdb/cockroach/blob/decd03410716b0179e24beedd116a71465735966/pkg/sql/cancel_queries.go#L1)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: 2018
</blockquote></details>

Despite what reviewable thinks, this is a rename from `cancel_query.go`. 

---

*[pkg/sql/cancel_queries.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25157#-LBLvrPj51hqIh6OVrcs:-LBOY9ZZAIGFOybz5s97:b-fmqqww) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50d6d5e783a2030d805c10b3c34158c1823cbde/pkg/sql/cancel_queries.go#L89)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I also think we should continue canceling the others and reporting all the errors at the end. And I think implementing `Next()` like this doesn't make much sense - what does it mean to iterate throught this CancelQueries node if `values()` doesn't return anything? I'd just make it perform all the work on the first `Next()` call.
</blockquote></details>

@justinj like Andrei said, a cancellation can fail because the query doesn't exist any more. Or perhaps the ID was invalid (no query with that ID exists on that node). If  IF EXISTS is specified, this is not an error and the processing continues; otherwise it is an error and the processing stops.

Andrei: I changed this logic so that the statement result count now reflects the number of items processed. Remember, SQL statements with pgwire can have a result type of "RowsAffected", for example INSERT and CREATE TABLE AS have that. I am leveraging this here.

---

*[pkg/sql/executor.go, line 1254 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/25157#-LBMG-yX0Ia9Ug8dxKQJ:-LBOWbTT4XJBOr78iI03:b-aw8owz) ([raw file](https://github.com/cockroachdb/cockroach/blob/decd03410716b0179e24beedd116a71465735966/pkg/sql/executor.go#L1254)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

please dont change this file :)
</blockquote></details>

this was a mechanical rename. Reverted.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25157#-:-LBOXyJcBZhsCREoCXWU:b4w5h95)*

**Comment by knz** [comment]
@robert-s-lee @awoods187  if you need this back-ported into 2.0, please reach out to the release team and ping me when there's agreement, I'll do the rest.

**Comment by mjibson** [comment]
Code for the jobs commit LGTM. But the commit message is wrong. It says:

>  If a job's state cannot be updated, an error occurs and no further job commands are attempted.

But should read something like:

> If a job's state cannot be updated, an error occurs and none of the specified jobs are modified.

**Comment by knz** [comment]
Thanks Matt for clarifying. I have updated the commit message.
Also since the processing for jobs is atomic and local, there is no point in incremental behavior (there's not much concurrency to be gained) so I moved the code back to `startExec`.

**Review by madelynnblue — APPROVED** [review]

**Comment by andreimatei** [comment]
Review status: 0 of 25 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/cancel_queries.go, line 89 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25157#-LBLvrPj51hqIh6OVrcs:-LBRLaqK1fD0km9dSWMH:bsiows4) ([raw file](https://github.com/cockroachdb/cockroach/blob/a50d6d5e783a2030d805c10b3c34158c1823cbde/pkg/sql/cancel_queries.go#L89)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

@justinj like Andrei said, a cancellation can fail because the query doesn't exist any more. Or perhaps the ID was invalid (no query with that ID exists on that node). If  IF EXISTS is specified, this is not an error and the processing continues; otherwise it is an error and the processing stops.

Andrei: I changed this logic so that the statement result count now reflects the number of items processed. Remember, SQL statements with pgwire can have a result type of "RowsAffected", for example INSERT and CREATE TABLE AS have that. I am leveraging this here.
</blockquote></details>

I still maintain that this `Next()` implementation doesn't make sense. I think the node could implement `FastPathResults()` and return the count explicitly, if you care about the count.
And I also think that the behavior that one would want is to cancel all the queries from the list that are still running. If I want to cancel 100 queries and the 59th had just finished, I think it's pretty clear I want to cancel the other 99 (regardless of whether `if exists` was specified).

Also, the behavior of `if exists` here seems funky - we swallow any error if it is specified?

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25157)*

**Pull request merged**
