### PR TITLE
followerreadsccl,storage: consider MaxClockOffset and MaxTimestamp

### LINKED ISSUE #36220: storage: follower reads should respect transaction uncertainty window
Forked from #36022.

Currently, a follower read is allowed for a transaction as long as the transaction's read timestamp (`orig.forward(refresh)`) is closed out. This is insufficient to ensure that a transaction will see all writes in its uncertainty window. We should fix this in both `followerreadsccl. canSendToFollower` and `Replica.canServeFollowerRead`.

@bdarnell mentioned in the other issue:

> I think follower reads can only be safe if the entire uncertainty window is less than the closed timestamp. I'm not sure whether we can use ObservedTimestamps for this at all or if we have to use the worst-case MaxTimestamp for the transaction.

@bdarnell could you expand on this? I was thinking that we could use the ObservedTimestamp of the current leaseholder to enforce an upper bound on this uncertainty window. The logic would be similar to what we have in [`Replica.limitTxnMaxTimestamp`](https://github.com/cockroachdb/cockroach/blob/3dc90223414590b110985f29a8c469afb2b63b5d/pkg/storage/replica.go#L1290).

The determination of which observed timestamp is relevant is complicated though (especially on the client-side of this) so it's probably not worth being tricky here. Forwarding the minimum acceptable closed timestamp to the transaction's MaxTimestamp should be sufficient, so we should probably go with that to start.

### PR DESCRIPTION
**Pull request by ajwerner**
This PR ensures that we forward the timestamp used for consideration for
follower reads by the MaxTimestamp and that we ensure that a full
MaxClockOffset beyond the known max closed timestamp has passed.

Fixes #36220.

Release note: None

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Why are we adding a `base.DefaultMaxClockOffset` in both cases? Shouldn't this already be captured in the `MaxTimestamp`?

**Comment by ajwerner** [comment]
> Why are we adding a `base.DefaultMaxClockOffset` in both cases? Shouldn't this already be captured in the `MaxTimestamp`?

Should have gone and read what MaxTimestamp was first. Now I know.

**Review by nvb — APPROVED** [review]
Nice, this looks good now. What do you think is the best way to test it?

**Comment by ajwerner** [comment]
> Nice, this looks good now. What do you think is the best way to test it?

Added some unit tests, PTAL.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/36247#-:-Lb9UTRyBEmlUOC7w56S:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Pull request merged**
