### PR TITLE
opt: prune columns in With and WithScan

### PR DESCRIPTION
**Pull request by justinj**
Will wait for 19.2.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41209#-:-Lq2xG4n2tV37bC9tW-o:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/opt/norm/rules/with.opt, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41209#-Lq2upq63NI_6TEH5NCk:-Lq2upq63NI_6TEH5NCl:b-krod2u) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe5a61ca27813e578a7e343ad1f46bdf8462419f/pkg/sql/opt/norm/rules/with.opt#L23)):*
> ```
> # effect of pruning columns, but since the With passes through all its columns,
> # no logic to test prunability is needed.
> [PushProjectIntoWith, Normalize]
> ```

Should this be named `PruneWithCols` and moved to `rules/prune_cols.opt`? Also, maybe extend the comment to discuss why it's ok to not check prune cols, and why it's ok for this to not be "in sync" with the `PruneCols` advertised by `With`. It took me a while to remember that the goal of the prune cols is to not litter the tree with projects, so we only want to create a new project on top of `With` if we know it can get pushed down. But otherwise if we already have a project, we might as well push it down in all cases.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 2021 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41209#-Lq2tSk18NfZlt8V-QPP:-Lq2tSk18NfZlt8V-QPQ:bdttypu) ([raw file](https://github.com/cockroachdb/cockroach/blob/88cfc71c8e7a70153209d1bacdfa233bbfd80b16/pkg/sql/opt/norm/testdata/rules/decorrelate#L2021)):*
> ```
> ----
> 
> # opt expect=TryDecorrelateGroupBy
> ```

Why is this commented out? If it's intentional, please add a comment.

**Review by justinj — COMMENTED** [review]
TFTR!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41209#-:-Lq72o3C8MXKwgpJCi7n:b-814g8k)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/norm/rules/with.opt, line 23 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/41209#-Lq2upq63NI_6TEH5NCk:-Lq72a9t7syiZLSEyLnW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fe5a61ca27813e578a7e343ad1f46bdf8462419f/pkg/sql/opt/norm/rules/with.opt#L23)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Should this be named `PruneWithCols` and moved to `rules/prune_cols.opt`? Also, maybe extend the comment to discuss why it's ok to not check prune cols, and why it's ok for this to not be "in sync" with the `PruneCols` advertised by `With`. It took me a while to remember that the goal of the prune cols is to not litter the tree with projects, so we only want to create a new project on top of `With` if we know it can get pushed down. But otherwise if we already have a project, we might as well push it down in all cases.
</blockquote></details>

Done.
___
*[pkg/sql/opt/norm/testdata/rules/decorrelate, line 2021 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/41209#-Lq2tSk18NfZlt8V-QPP:-Lq72WHb1CSmQfZc49lQ:b-o28nt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/88cfc71c8e7a70153209d1bacdfa233bbfd80b16/pkg/sql/opt/norm/testdata/rules/decorrelate#L2021)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Why is this commented out? If it's intentional, please add a comment.
</blockquote></details>

Meant to fix it to still work—fixed.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41209#-:-Lq7p3q89_Bb7wLEkFLj:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @justinj, @RaduBerinde, and @rytaft)

___
*[pkg/sql/logictest/testdata/logic_test/apply_join, line 294 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41209#-Lq7osaq1WYZfT_x2kDe:-Lq7osaq1WYZfT_x2kDf:b1rjg1s) ([raw file](https://github.com/cockroachdb/cockroach/blob/e0b915957e20be8a3998efc4491509169eab77ff/pkg/sql/logictest/testdata/logic_test/apply_join#L294)):*
> ```
> statement error could not decorrelate subquery
> SELECT
>     NULL
> ```

why this change? we seem to be using indent of 2 in most cases

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 4 of 9 files at r1, 7 of 7 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41209#-:-Lq8NQl5CWfQvlWQCMcg:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @RaduBerinde)

**Pull request merged**
