### PR TITLE
internal/client: remove Txn.Context

### PR DESCRIPTION
**Pull request by tamird**
client.Txn.Context is the star of this show.

This may have been a bit heavy-handed, so a thorough review would be appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14051)

### CODE REVIEW

**Comment by benesch** [comment]
Queued a TC build for this. @jordanlewis TC seems to be failing to pick up GH PR builds with some frequency lately.

**Comment by andreimatei** [comment]
Keep the fight up Tamir. See comments in executor.go, I think that guy can be improved with this occasion.

---

Reviewed 7 of 97 files at r1.
Review status: 7 of 97 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/online_schema_change.md, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetTqXZXc-OJCkjihGQ:-KetTqX_5fcis9kEezi1:b-on4dh) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/docs/RFCS/online_schema_change.md#L108)):*
> ```Markdown
>       lastKey = getLastKeyOfFullRowInScan(scan)
>       b := makeIndexKeysBatch(scan)
>       return txn.CommitInBatch(ctx, b)
> ```

looool
But then put a `ctx` above too

---

*[pkg/internal/client/db.go, line 467 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetT5thYkTtSuoiSuVX:-KetT5thYkTtSuoiSuVY:bs9cby5) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/internal/client/db.go#L467)):*
> ```Go
> 	// to use the correct tracer).
> 
> 	ctx, cancel := context.WithCancel(ctx)
> ```

leave a TODO to revisit when the TxnCS goes away

---

*[pkg/internal/client/doc.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetU9asIs0tMdY4EH-6:-KetU9asIs0tMdY4EH-7:brm0ogz) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/internal/client/doc.go#L112)):*
> ```Go
> 		// returns success (i.e. nil). Calling CommitInBatch explicitly can
> 		// sometimes reduce the number of RPCs.
> 		return txn.CommitInBatch(ctx, b)
> ```

put a ctx above too

---

*[pkg/kv/txn_coord_sender.go, line 980 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetTMe3UyQqpELKP2uh:-KetTMe3UyQqpELKP2ui:bc7vre7) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/kv/txn_coord_sender.go#L980)):*
> ```Go
> // run the whole thing for them, or any restart will still end up at the client
> // which will not be prepared to be handed a Txn.
> func (tc *TxnCoordSender) resendWithTxn(
> ```

perhaps a ctx can be plumbed to this method now?

---

*[pkg/sql/executor.go, line 548 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetUiWuwWLTFAyw9o3t:-KetUiWuwWLTFAyw9o3u:b-y0jepz) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/sql/executor.go#L548)):*
> ```Go
> 	var err error
> 
> 	ctx := session.Ctx()
> ```

I think this method should continue to use `session.Ctx()` everywhere. Otherwise you have to update this `ctx` variable after a statement has been run (in the loop below). But see other comments below.

---

*[pkg/sql/executor.go, line 877 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetVDEFKilr5TQnuj2S:-KetVDEFKilr5TQnuj2T:bu3omif) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/sql/executor.go#L877)):*
> ```Go
> 
> 	for i, stmt := range stmts {
> 		ctx := planMaker.session.Ctx()
> ```

capturing the context here, even though it's done anew after every statement, and passing it into `execStmtInOpenTxn` and friends, changes behavior compared to the current state of affairs. Before, we were switching to using the session's ctx immediately after committing or rolling back a sql txn (so immediately after `commitSQLTransaction/rollbackSQLTransaction` were called). Now, we'd only switch once control comes back to this loop. It's not a big deal, it might be completely inconsequential. However I find it a bit hard to think about, and I suspect new readers will be quite confused - why exactly do I need to capture the ctx at this level and not above or below? Does it need to be in the loop?

I think using `session.Ctx()` everywhere was clearer (although not cleaner) - didn't have to think about anything. But if you want to be more structured, here's what I think would be the cleanest - I think we should make it so that `execStmtInCurrentTxn` can take in a context for its entire operation. After all, it's supposed to only execute statements belonging to one transaction - so it could use the transaction's context for the entirety of the methods life. I believe you can do that change right now - pass the txn's context into this method - without any bad consequences. This would exacerbate the behaviour change that I was talking about in the previous paragraph - a txn's ctx would potentially be used even longer after `commitSQLTransaction/rollbackSQLTransaction` have been called. But that's cool; the txn's context can technically be used just fine after commit/rollback up until the point where we finish the txn's span - which is done above this level, in `execRequest`, by `txnState.finishSQLTxn()`. Btw this is a wart of the current code (with and without your changes) - execution goes back to using the session's ctx even though the txn's span hasn't been closed yet.

To make the code better structured and the story clear, I think we can get rid of the `session.Ctx()`method completely. If this method starts taking in a (transaction's) ctx, then the biggest use of that method goes away.
We should also make it very clear where sql transactions begin and end, and solve the inconsistency with the span's finish mentioned above, by a refactoring. Right now, the sql txn state (`Open` vs `NoTxn` vs ..., done by `resetStateAndTxn(<new state>)`) is done in a bunch of places - in some cases it's done at the `execRequest` level, in other cases it's done way deeper down by `commit/rollbackSQLTransaction()`. I'd suggest we move all calls to `resetStateAndTxn` to the `execRequest` level (to match the txn's span) and we pipe information about the required state transition from the commit/rollback calls to `execRequest` level through a fatter return value.

Some of the things that would need to change:
- `execStmtsInCurrentTxn` won't be able to inspect `txnState.State` after executing each statement to see if the txn is done. Instead it'd have to look at some return value.
- our friend the `EvalCtx` uses `session.Ctx()` for expression evaluation. We should either:
a) do whatever it takes to pipe a ctx to all expression evaluations and remove the context from EvalCtx. I know this is your preference, but I've thought about it some more and I don't think there's good reason to do exactly that. Instead:
b) sql function calls and `TypedExpr.Eval` should continue to take just an `EvalCtx` with a ctx in it, but `EvalCtx.Ctx` should be set explicitly every time just before one of these function that takes a `EvalCtx` is called.
c) you can be lazy and reset `planner.EvalCtx.Ctx` to either a session's or a txn's context at the `execRequest` level, whenever we get in and out of a transaction.

Makes sense?

---

*[pkg/sql/executor.go, line 1203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetVp8GC6P8sPTgTHs3:-KetVp8GC6P8sPTgTHs4:bgkbbh3) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/sql/executor.go#L1203)):*
> ```Go
> 		log.Eventf(ctx, "%s done", tResult)
> 	}
> 	log.Eventf(session.context, "%s done", tResult)
> ```

I would remove this line with this occasion. Not sure exactly why we log separately to the session and to the txn context, but I don't think it's useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-:-KetksfUaBRduf671Srb:bmwiyn3)*

**Comment by knz** [comment]
Reviewed 94 of 97 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[pkg/sql/executor.go, line 1203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetVp8GC6P8sPTgTHs3:-KeuLdB2-Fox0AvARLO4:b-f2py5m) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/sql/executor.go#L1203)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I would remove this line with this occasion. Not sure exactly why we log separately to the session and to the txn context, but I don't think it's useful.
</blockquote></details>

huh I agree the first argument should be `ctx` but the log should be there: even if `traceSQL` is not set, we still want to know when the result is complete.n

---

*[pkg/storage/addressing_test.go, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KeuNJCVhCgt_saCxwb0:-KeuNJCVhCgt_saCxwb1:b2qwy0u) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/storage/addressing_test.go#L158)):*
> ```Go
> 		db := client.NewDB(tcs)
> 		txn := client.NewTxn(db)
> 		if err := txn.Run(context.TODO(), b); err != nil {
> ```

In the other tests you have changed you have created a single `ctx` variable and passed that to the various functions. Any reason to do it differently here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/online_schema_change.md, line 108 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetTqXZXc-OJCkjihGQ:-KetmdPsenzdz70JOevC:b-6slrip) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/docs/RFCS/online_schema_change.md#L108)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

looool
But then put a `ctx` above too
</blockquote></details>

Ha! Done.

---

*[pkg/internal/client/db.go, line 467 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetT5thYkTtSuoiSuVX:-KetojK2P5AuPTvKoRXJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/internal/client/db.go#L467)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

leave a TODO to revisit when the TxnCS goes away
</blockquote></details>

Done.

---

*[pkg/internal/client/doc.go, line 112 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetU9asIs0tMdY4EH-6:-KetmlQRUI4_A_pxyYCT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/internal/client/doc.go#L112)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

put a ctx above too
</blockquote></details>

Done.

---

*[pkg/kv/txn_coord_sender.go, line 980 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetTMe3UyQqpELKP2uh:-KetnH4IMIIWBiTMOu3c:bjb06eu) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/kv/txn_coord_sender.go#L980)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

perhaps a ctx can be plumbed to this method now?
</blockquote></details>

Easily. Done.

---

*[pkg/sql/executor.go, line 548 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetUiWuwWLTFAyw9o3t:-KfJBf7ktlFnWwdB-ZQY:b1e0j50) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/sql/executor.go#L548)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I think this method should continue to use `session.Ctx()` everywhere. Otherwise you have to update this `ctx` variable after a statement has been run (in the loop below). But see other comments below.
</blockquote></details>

I've rolled back these changes and focused only on what was required to remove client.Txn.Context. PTAL.

---

*[pkg/sql/executor.go, line 877 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetVDEFKilr5TQnuj2S:-KfJBjsrzwkc005ESBYg:bxh3s69) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/sql/executor.go#L877)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

capturing the context here, even though it's done anew after every statement, and passing it into `execStmtInOpenTxn` and friends, changes behavior compared to the current state of affairs. Before, we were switching to using the session's ctx immediately after committing or rolling back a sql txn (so immediately after `commitSQLTransaction/rollbackSQLTransaction` were called). Now, we'd only switch once control comes back to this loop. It's not a big deal, it might be completely inconsequential. However I find it a bit hard to think about, and I suspect new readers will be quite confused - why exactly do I need to capture the ctx at this level and not above or below? Does it need to be in the loop?

I think using `session.Ctx()` everywhere was clearer (although not cleaner) - didn't have to think about anything. But if you want to be more structured, here's what I think would be the cleanest - I think we should make it so that `execStmtInCurrentTxn` can take in a context for its entire operation. After all, it's supposed to only execute statements belonging to one transaction - so it could use the transaction's context for the entirety of the methods life. I believe you can do that change right now - pass the txn's context into this method - without any bad consequences. This would exacerbate the behaviour change that I was talking about in the previous paragraph - a txn's ctx would potentially be used even longer after `commitSQLTransaction/rollbackSQLTransaction` have been called. But that's cool; the txn's context can technically be used just fine after commit/rollback up until the point where we finish the txn's span - which is done above this level, in `execRequest`, by `txnState.finishSQLTxn()`. Btw this is a wart of the current code (with and without your changes) - execution goes back to using the session's ctx even though the txn's span hasn't been closed yet.

To make the code better structured and the story clear, I think we can get rid of the `session.Ctx()`method completely. If this method starts taking in a (transaction's) ctx, then the biggest use of that method goes away.
We should also make it very clear where sql transactions begin and end, and solve the inconsistency with the span's finish mentioned above, by a refactoring. Right now, the sql txn state (`Open` vs `NoTxn` vs ..., done by `resetStateAndTxn(<new state>)`) is done in a bunch of places - in some cases it's done at the `execRequest` level, in other cases it's done way deeper down by `commit/rollbackSQLTransaction()`. I'd suggest we move all calls to `resetStateAndTxn` to the `execRequest` level (to match the txn's span) and we pipe information about the required state transition from the commit/rollback calls to `execRequest` level through a fatter return value.

Some of the things that would need to change:
- `execStmtsInCurrentTxn` won't be able to inspect `txnState.State` after executing each statement to see if the txn is done. Instead it'd have to look at some return value.
- our friend the `EvalCtx` uses `session.Ctx()` for expression evaluation. We should either:
a) do whatever it takes to pipe a ctx to all expression evaluations and remove the context from EvalCtx. I know this is your preference, but I've thought about it some more and I don't think there's good reason to do exactly that. Instead:
b) sql function calls and `TypedExpr.Eval` should continue to take just an `EvalCtx` with a ctx in it, but `EvalCtx.Ctx` should be set explicitly every time just before one of these function that takes a `EvalCtx` is called.
c) you can be lazy and reset `planner.EvalCtx.Ctx` to either a session's or a txn's context at the `execRequest` level, whenever we get in and out of a transaction.

Makes sense?
</blockquote></details>

I've rolled back these changes and focused only on what was required to remove client.Txn.Context. PTAL.

I'll pull on this thread in a follow-up PR.

---

*[pkg/sql/executor.go, line 1203 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KetVp8GC6P8sPTgTHs3:-KfJBnHRUSyjDaNmJk9D:bwwta4t) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/sql/executor.go#L1203)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

huh I agree the first argument should be `ctx` but the log should be there: even if `traceSQL` is not set, we still want to know when the result is complete.n
</blockquote></details>

Replaced with session.Ctx().

---

*[pkg/storage/addressing_test.go, line 158 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KeuNJCVhCgt_saCxwb0:-KfDiCN2c9gNdWejPtMj:b-z0ua7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/df8c9384ca3e46f3d5f81fa934f6f56a306bda2e/pkg/storage/addressing_test.go#L158)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

In the other tests you have changed you have created a single `ctx` variable and passed that to the various functions. Any reason to do it differently here?
</blockquote></details>

no reason; there are a *ton* of cases where context.TODO() is peppered throughout the test. I'm happy to change any cases you point out, but you're gonna have to point them all out :P

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051)*

**Comment by knz** [comment]
:lgtm:

---

Reviewed 60 of 60 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-:-KfNNbdzTrqUT1DfCs83:bnfp4nl)*

**Comment by nvanbenschoten** [comment]
:lgtm:

---

Reviewed 38 of 97 files at r1, 53 of 60 files at r2, 10 of 10 files at r3, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[pkg/internal/client/client_test.go, line 234 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KfMhkcQdT1RKy_UKaV6:-KfMhkcQdT1RKy_UKaV7:b-r67myh) ([raw file](https://github.com/cockroachdb/cockroach/blob/030ce97c3e27224dbf526d6c9401f0702535bc0f/pkg/internal/client/client_test.go#L234)):*
> ```Go
> 			// On the first iteration, send the non-txn put or get.
> 			if count == 1 {
> 				ctx := context.TODO()
> ```

consider renaming to make it clear that this is the context of the non-txn

---

*[pkg/migrations/migrations.go, line 97 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KfNfpbRv_6lEqD8xrjM:-KfNfpbRv_6lEqD8xrjN:bmxplp3) ([raw file](https://github.com/cockroachdb/cockroach/blob/57bd19acc27165d1147b8061464a525e6c56ca8d/pkg/migrations/migrations.go#L97)):*
> ```Go
> // db is defined just to allow us to use a fake client.DB when testing this
> // package.
> type db interface {
> ```

might want to add a `var _ db = &client.DB{}`

---

*[pkg/sql/set.go, line 26 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KfNiQzp-kVZlv9Y1NEG:-KfNiQzp-kVZlv9Y1NEH:b-kmledn) ([raw file](https://github.com/cockroachdb/cockroach/blob/57bd19acc27165d1147b8061464a525e6c56ca8d/pkg/sql/set.go#L26)):*
> ```Go
> 
> 	"golang.org/x/net/context"
> ```

nit: we've grouped apd with other (non-cockroach) libs elsewhere in this PR. Which convention do you want?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-:-KfNksO_v59InZo19kTE:bnfp4nl)*

**Comment by tamird** [comment]
Review status: 93 of 112 files reviewed at latest revision, 10 unresolved discussions.

---

*[pkg/internal/client/client_test.go, line 234 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KfMhkcQdT1RKy_UKaV6:-KfNmKkM10l2YnuTXMsh:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/030ce97c3e27224dbf526d6c9401f0702535bc0f/pkg/internal/client/client_test.go#L234)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

consider renaming to make it clear that this is the context of the non-txn
</blockquote></details>

Done.

---

*[pkg/migrations/migrations.go, line 97 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KfNfpbRv_6lEqD8xrjM:-KfNlPpGJ2yDmBteHwxb:bdzrwyv) ([raw file](https://github.com/cockroachdb/cockroach/blob/57bd19acc27165d1147b8061464a525e6c56ca8d/pkg/migrations/migrations.go#L97)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

might want to add a `var _ db = &client.DB{}`
</blockquote></details>

I think you accidentally reviewed @benesch's code here :)

---

*[pkg/sql/set.go, line 26 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051#-KfNiQzp-kVZlv9Y1NEG:-KfNlUAwSTcJZmpFP7fn:bsturw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/57bd19acc27165d1147b8061464a525e6c56ca8d/pkg/sql/set.go#L26)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: we've grouped apd with other (non-cockroach) libs elsewhere in this PR. Which convention do you want?
</blockquote></details>

Fixed throughout.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14051)*

**Pull request merged**
