### PR TITLE
roachtest: add version gate for statement in schemachange/mixed/tpcc

### LINKED ISSUE #39622: roachtest: schemachange/mixed/tpcc failed
SHA: https://github.com/cockroachdb/cockroach/commits/51a6fdedf0ce1d1329d40d801a7deaf8206b6b07

Parameters:

To repro, try:

```
# Don't forget to check out a clean suitable branch and experiment with the
# stress invocation until the desired results present themselves. For example,
# using stress instead of stressrace and passing the '-p' stressflag which
# controls concurrency.
./scripts/gceworker.sh start && ./scripts/gceworker.sh mosh
cd ~/go/src/github.com/cockroachdb/cockroach && \
stdbuf -oL -eL \
make stressrace TESTS=schemachange/mixed/tpcc PKG=roachtest TESTTIMEOUT=5m STRESSFLAGS='-maxtime 20m -timeout 10m' 2>&1 | tee /tmp/stress.log
```

Failed test: https://teamcity.cockroachdb.com/viewLog.html?buildId=1436116&tab=buildLog

```
The test failed on branch=provisional_201908060405_v19.1.4, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/20190812-1436116/schemachange/mixed/tpcc/run_1
	schemachange.go:452,schemachange.go:414,cluster.go:2078,errgroup.go:57: pq: syntax error at or near "primary"
	cluster.go:1735,tpcc.go:183,cluster.go:2078,errgroup.go:57: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/bin/roachprod run teamcity-1565651234-57-n5cpu16:5 -- ./workload run tpcc --warehouses=1000 --histograms=perf/stats.json --wait=false --tolerate-errors --ramp=5m0s --duration=3h0m0s {pgurl:1-4} returned:
		stderr:
		
		stdout:
		       0           26.0           28.9    184.5  38654.7  45097.2  45097.2 stockLevel
		  14m27s        0           35.9           28.8   1543.5  12884.9  16106.1  16106.1 delivery
		  14m27s        0          349.6          288.0   3623.9  38654.7  68719.5  73014.4 newOrder
		  14m27s        0           44.8           29.0     83.9   6442.5  40802.2  40802.2 orderStatus
		  14m27s        0          410.3          282.8   6442.5  81604.4 103079.2 103079.2 payment
		  14m27s        0           37.8           28.9    218.1   6442.5  42949.7  42949.7 stockLevel
		  14m28s        0           29.1           28.8   1610.6  16643.0  24696.1  24696.1 delivery
		  14m28s        0          169.3          287.9   3355.4  22548.6  73014.4  98784.2 newOrder
		  14m28s        0           15.0           29.0     46.1   9126.8  18253.6  18253.6 orderStatus
		  14m28s        0          278.5          282.8   9663.7 103079.2 103079.2 103079.2 payment
		  14m28s        0           16.0           28.9    419.4   6442.5  12348.0  12348.0 stockLevel
		: signal: killed
	cluster.go:2099,tpcc.go:193,schemachange.go:410,test_runner.go:691: Goexit() was called

```

### PR DESCRIPTION
**Pull request by thoszhang**
`schemachange/mixed/tpcc` was failing on 19.1 because `CREATE TABLE AS` with a
specified primary key was only added in 19.2. This PR adds a version gate in
the test for that statement.

Fixes #39622.

Release justification: Fixes a broken test.

Release note: None

### CODE REVIEW

**Review by pbardea — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40912)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang and @pbardea)

___
*[pkg/cmd/roachtest/schemachange.go, line 414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40912#-Lp9SoDc2rgz5Paprgv1:-Lp9SoDd6sh-holUiByw:b-j6x866) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef83c38b5cf3c07a40ebf621030f4832c710c0a/pkg/cmd/roachtest/schemachange.go#L414)):*
> ```Go
> 				Extra:      "--wait=false --tolerate-errors",
> 				During: func(ctx context.Context) error {
> 					if t.IsBuildVersion(`v19.2.0`) {
> ```

Do we want this to check if it is version 19.2 or later? (Rather than exactly 19.2.0?)

**Review by thoszhang — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40912)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @pbardea)

___
*[pkg/cmd/roachtest/schemachange.go, line 414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40912#-Lp9SoDc2rgz5Paprgv1:-Lp9TmFm3tktTG5K87Sp:b-utngy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef83c38b5cf3c07a40ebf621030f4832c710c0a/pkg/cmd/roachtest/schemachange.go#L414)):*
<details><summary><i>Previously, pbardea (Paul Bardea) wrote…</i></summary><blockquote>

Do we want this to check if it is version 19.2 or later? (Rather than exactly 19.2.0?)
</blockquote></details>

This method has a misleading name. It actually checks whether the version is at least `19.2.0`.

**Review by pbardea — APPROVED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40912#-:-Lp9UXn_48Za8_HgaxOM:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @lucy-zhang)

___
*[pkg/cmd/roachtest/schemachange.go, line 414 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/40912#-Lp9SoDc2rgz5Paprgv1:-Lp9USom8FWkQogK681s:b-jrim5z) ([raw file](https://github.com/cockroachdb/cockroach/blob/7ef83c38b5cf3c07a40ebf621030f4832c710c0a/pkg/cmd/roachtest/schemachange.go#L414)):*
<details><summary><i>Previously, lucy-zhang (Lucy Zhang) wrote…</i></summary><blockquote>

This method has a misleading name. It actually checks whether the version is at least `19.2.0`.
</blockquote></details>

Haha nice. Good to know.

**Pull request merged**
