### PR TITLE
Use gulp to allow livereload

### PR DESCRIPTION
**Pull request by maxlang**

### CODE REVIEW

**Comment by petermattis** [comment]
That is an incredible number of commits batched up into a single PR. And all of them so tiny. I can almost reverse-engineer your development process. :)

It is generally our style to have a small number of commits per PR and not to make a separate commit for every step of the development process. And I would encourage separate PRs for logically separate changes (I'm not saying any of the above should be broken into separate PRs...I only glanced briefly at the changes). I suppose we should write up some documentation about our expectations for pull-requests and how we handle the pull-request process.

**Comment by maxlang** [comment]
That all sounds good. I'm happy to conform to the team's preferred style. I actually thought it wouldn't matter because they'd all get squashed in the end, but I can also see how it makes a PR easier to read.

**Comment by tschottdorf** [comment]
If you're squashing before merging anyways, it's fine to leave the commits as you create them in your work. Whatever you do, at the end there should be a few well-defined commits (so no merges, intermediate stages with broken tests/functionality, ...).

**Comment by tamird** [comment]
There's a lot going on here; dividing this PR into several logic commits would make review much easier. Having said that, I have some immediate concerns:
- What does this PR achieve? How do I use livereload? This needs to be documented.
- Can we avoid vendoring all the bower dependencies?
- Looks like embedded.go lost the TS source map; did embedded_debug keep it?
- Why are we doing global `npm` installs?
- I see you checked in a "special" mithril.d.ts; what's the plan for upstreaming that?

**Comment by maxlang** [comment]
I think I opened this PR prematurely so I'll close and restructure it a bit.

@tschottdorf Thanks I forgot to set up auto-rebasing.

@tamird 
1) I'll add a bunch of documentation on how to use live-reload/add new dependencies.
2) What do you mean by vendoring? I checked in the bower/tsd dependencies based on a conversation with @petermattis that it's faster to just check in all the files than have to bower/tsd install.
3) I wasn't generating source maps because I noticed our tsconfig.json had ```    "sourceMap": false``` but  honestly that should get set up regardless so I'll add that in.
4) Global installs are needed to run things from the command line. In particular we need to install ```gulp``` globally. I could drop bower and tsd because those dependencies are checked in currently.
5) I'll make a PR against https://github.com/borisyankov/DefinitelyTyped once these changes are in. We were already using a special mithril.d.ts, it's more that I've moved all the other dependencies to be the standard bower/tsd ones, but the mithril.d.ts file was special. Another option would be to fork https://github.com/borisyankov/DefinitelyTyped but that seems like a bad idea.

**Comment by tamird** [comment]
> 4) Global installs are needed to run things from the command line. In particular we need to install gulp globally. I could drop bower and tsd because those dependencies are checked in currently.

Why? the current setup runs things from the command line by using the binstub inside `node_modules/`

**Comment by maxlang** [comment]
I think I haven't fully internalized the "as little footprint as possible" mentality. I'll add a note to install them globally if you want to use them from the command line.

**Comment by petermattis** [comment]
@maxlang Perhaps there was confusion in our discussion yesterday. We should check-in generated code that would be necessary to run "go build". We don't need to check-in/vendor tools/libraries that are necessary for development but will not affect "go build". My understanding of the current setup is that the node_modules are necessary to regenerate `ui/js/app.js` but not to use it. Hence, `ui/js/app.js` is checked in, but not the node_modules. Looking at this just now, we don't even need to check-in `ui/js/app.js` since it is `ui/embedded.go` which is important. Might be worth simplifying that, though I wouldn't worry about it unless it is actively causing a problem.

**Comment by maxlang** [comment]
@petermattis Ah yeah I think I was confused. I thought we wanted to check in enough to run go generate reasonably quickly. Otherwise embedded.go is sufficient.

**Comment by petermattis** [comment]
We do want `go generate` to run reasonably quickly, but that doesn't necessitate vendoring. We can bake tools into our `cockroachdb/builder` if installing them during CI is too slow.

**Comment by maxlang** [comment]
Cool, that's what I was doing originally. I'll .gitignore the vendor/generated files but keep embedded.go.

**Pull request closed without merging**
