### PR TITLE
colrpc: some more logging around errors in inbox and outbox

### PR DESCRIPTION
**Pull request by yuzefovich**
Release note: None

### CODE REVIEW

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @michae2, and @yuzefovich)

___
*[pkg/sql/colflow/colrpc/outbox.go, line 229 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64295#-MZKM5ic5asSEP1RA4HZ:-MZKM5idDSPaO98tDj88:bru7b3s) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d6beca9ffe0ebedf7b45b8427f3766f82519f6c/pkg/sql/colflow/colrpc/outbox.go#L229)):*
> ```Go
> func (o *Outbox) moveToDraining(ctx context.Context, reason string) {
> 	if atomic.CompareAndSwapUint32(&o.draining, 0, 1) {
> 		log.VEventf(ctx, 2, "Outbox moved to draining because of %s", reason)
> ```

[nit] "because of terminated gracefully" , I'd just do `moved to draining (%s)`
___
*[pkg/sql/colflow/colrpc/outbox.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64295#-MZKMGFO6StBfiQKj44a:-MZKMGFO6StBfiQKj44b:b-jj0q6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d6beca9ffe0ebedf7b45b8427f3766f82519f6c/pkg/sql/colflow/colrpc/outbox.go#L305)):*
> ```Go
> 	msg := &execinfrapb.ProducerMessage{}
> 	if errToSend != nil {
> 		log.Warningf(ctx, "Outbox sending error as metadata: %+v", errToSend)
> ```

Is this appropriate as a Warning? (if yes, add a comment explaining why)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @michae2, and @RaduBerinde)

___
*[pkg/sql/colflow/colrpc/outbox.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64295#-MZKMGFO6StBfiQKj44a:-MZKeq6PBcbkyP4b2wtl:brymlsx) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d6beca9ffe0ebedf7b45b8427f3766f82519f6c/pkg/sql/colflow/colrpc/outbox.go#L305)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Is this appropriate as a Warning? (if yes, add a comment explaining why)
</blockquote></details>

Good point - I confused myself. I thought this was an error from `stream.Send`, so I deemed it important. However, `errToSend` is only from the "producing" part of the outbox (like its input returned an error or the outbox failed to serialize data), so I lowered it to `VEvent(1)`.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64295)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @michae2, and @RaduBerinde)

___
*[pkg/sql/colflow/colrpc/outbox.go, line 305 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/64295#-MZKMGFO6StBfiQKj44a:-MZKff-i63hXseRwoVll:b257gmh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2d6beca9ffe0ebedf7b45b8427f3766f82519f6c/pkg/sql/colflow/colrpc/outbox.go#L305)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Good point - I confused myself. I thought this was an error from `stream.Send`, so I deemed it important. However, `errToSend` is only from the "producing" part of the outbox (like its input returned an error or the outbox failed to serialize data), so I lowered it to `VEvent(1)`.
</blockquote></details>

Ditto for the inbox.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/64295#-:-MZL7Eea75eYsMoSslrt:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach and @michae2)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
