### PR TITLE
opt: Make some perf-related changes

### PR DESCRIPTION
**Pull request by andy-kimball**
Enable the cost-based optimizer in the SQL bench test. Enhance
the opt benchmark test to allow execution and easy CPU profiling.
Speed up star projections in optbuilder.

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28778#-:-LK9Rsft08mQr5PzRseP:bnfp4nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28778#-:-LKDL3mk14Ay9lE6Wsrx:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale)

___
*[pkg/sql/opt/bench/bench_test.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28778#-LKDJCqfDw2qfZ2vnwR4:-LKDJCqfDw2qfZ2vnwR5:b-g6s12n) ([raw file](https://github.com/cockroachdb/cockroach/blob/20414540c4fa0cfb9b5870ba61516ef949bc65c6/pkg/sql/opt/bench/bench_test.go#L59)):*
> ```Go
> 
> 	// Explore constructs the Memo from the AST and enables all normalization
> 	// and Explore rules. The Memo is fully optimized. Explore includes the time
> ```

[nit] normalization and exploration

**Review by andy-kimball — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28778)* status: :shipit: complete! 2 of 0 LGTMs obtained

___
*[pkg/sql/opt/bench/bench_test.go, line 59 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/28778#-LKDJCqfDw2qfZ2vnwR4:-LKEEbB37RYt8PuyOCrJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20414540c4fa0cfb9b5870ba61516ef949bc65c6/pkg/sql/opt/bench/bench_test.go#L59)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] normalization and exploration
</blockquote></details>

Done.

**Pull request merged**
