### PR TITLE
sqlccl: retry azure block and blocklist upload 3 times

### PR DESCRIPTION
**Pull request by dt**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/14109)

### CODE REVIEW

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/util/retry/retry.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-Kf7CdI_4n8Y1WqlokWH:-Kf7CdI_4n8Y1WqlokWI:b-7iyku0) ([raw file](https://github.com/cockroachdb/cockroach/blob/411187394aba9688aa7ec83e688753978d80c3a6/pkg/util/retry/retry.go#L147)):*
> ```Go
> 
> // WithMaxAttempts is a helper that runs fn N times and collects the last err.
> func WithMaxAttempts(ctx context.Context, opts Options, n int, fn func() error) error {
> ```

test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-:-Kf7Cp05nNzOVm7BA8G-:bnfp4nl)*

**Comment by danhhz** [comment]
On second thought, I've come around on your thought to put this in the implementation of Export. How do you feel about instead moving `retry.WithMaxAttempts` to wrap the call to Finish? https://github.com/cockroachdb/cockroach/blob/master/pkg/ccl/storageccl/export.go#L138

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/export_storage.go, line 656 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-Kf7KcE9PFtEbbfskJIA:-Kf7KcE9PFtEbbfskJIB:b-8w97u6) ([raw file](https://github.com/cockroachdb/cockroach/blob/411187394aba9688aa7ec83e688753978d80c3a6/pkg/ccl/storageccl/export_storage.go#L656)):*
> (s.ctx, base.DefaultRetryOptions(), maxAttempts, func() error {

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-:-Kf7KUCDjs-E-SLdTkog:byxru6j)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/ccl/storageccl/export_storage.go, line 656 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-Kf7KcE9PFtEbbfskJIA:-Kf7M7rxVvOqc1oN3CJm:btladui) ([raw file](https://github.com/cockroachdb/cockroach/blob/411187394aba9688aa7ec83e688753978d80c3a6/pkg/ccl/storageccl/export_storage.go#L656)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

> (s.ctx, base.DefaultRetryOptions(), maxAttempts, func() error {
</blockquote></details>

what's this quote?

---

*[pkg/util/retry/retry.go, line 147 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-Kf7CdI_4n8Y1WqlokWH:-Kf7MDKLjnkL9w4Feg_i:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/411187394aba9688aa7ec83e688753978d80c3a6/pkg/util/retry/retry.go#L147)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

test?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109)*

**Comment by danhhz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/export_storage.go, line 656 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-Kf7KcE9PFtEbbfskJIA:-Kf7YHvA0OV4aGBfzvJI:b-nvz0tl) ([raw file](https://github.com/cockroachdb/cockroach/blob/411187394aba9688aa7ec83e688753978d80c3a6/pkg/ccl/storageccl/export_storage.go#L656)):*
<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary><blockquote>

what's this quote?
</blockquote></details>

no clue. ignore

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109)*

**Comment by dt** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ccl/storageccl/export_storage.go, line 656 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-Kf7KcE9PFtEbbfskJIA:-Kf7YnsDH498RzIXD8xy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/411187394aba9688aa7ec83e688753978d80c3a6/pkg/ccl/storageccl/export_storage.go#L656)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

no clue. ignore
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109)*

**Comment by dt** [comment]
Eh, I've also come around on *your* thoughts: _until_ we add streaming, we might as well do some granular retries where we are able to -- we likely still need a top-level retry, but this one can't hurt.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-:-Kf7YqUSwgf-7MLVmWRj:b-cs5jcg)*

**Comment by mjibson** [comment]
:lgtm:

I'm ok with the whack-a-mole approach until we know we need higher level retries.

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-:-Kf7wj4624qk4eOiJrpH:b-xlmkwz)*

**Comment by danhhz** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/14109#-:-Kf8-ht4uudmhTWYKg3f:bnfp4nl)*

**Comment by dt** [comment]
to recap, we'll keep applying whack-a-mole from the bottle up for now -- so we know where errors are actually coming from -- before adding a higher level (e.g. around Finish) retry potentially in the future.

**Pull request merged**
