### PR TITLE
builtins: fix incorrect sqrdiff evaluation due to reuse of the results from previous iterations when used as a window function

### LINKED ISSUE #55944: sql: windowed aggregate functions for decimals return unexpected results
Consider the following sql:

```
CREATE TABLE t
(
    yf float,
    yd decimal
);

INSERT INTO t (yf,yd)
VALUES (1.0, 1.0),
       (20.0, 20.0),
       (25.0, 25.0),
       (41.0, 41.0),
       (55.5, 55.5),
       (60.9, 60.9),
       (72.0, 72.0),
       (88.0, 88.0),
       (88.0, 88.0),
       (89.0, 89.0);

select sqrdiff(yf)     as sqrdiff_float,
       sqrdiff(yd)     as sqrdiff_decimal,
       var_pop(yf)     as var_pop_float,
       var_pop(yd)     as var_pop_decimal,
       var_samp(yf)    as var_samp_float,
       var_samp(yd)    as var_samp_decimal,
       stddev_pop(yf)  as stddev_pop_float,
       stddev_pop(yd)  as stddev_pop_decimal,
       stddev_samp(yf) as stddev_samp_float,
       stddev_samp(yd) as stddev_samp_decimal
from t;

-- returns

    sqrdiff_float   | sqrdiff_decimal |   var_pop_float   | var_pop_decimal |  var_samp_float   | var_samp_decimal | stddev_pop_float  |  stddev_pop_decimal   | stddev_samp_float |  stddev_samp_decimal
--------------------+-----------------+-------------------+-----------------+-------------------+------------------+-------------------+-----------------------+-------------------+------------------------
  8885.844000000001 |        8885.844 | 888.5844000000001 |        888.5844 | 987.3160000000001 |          987.316 | 29.80913282871543 | 29.809132828715430446 | 31.42158493774622 | 31.421584937746218024
(1 row)

-- Note that the results for floats and decimals are the same and these values correspond to what PG returns.

select sqrdiff(yf) over (order by yf)     as sqrdiff_float,
       sqrdiff(yd) over (order by yd)     as sqrdiff_decimal,
       var_pop(yf) over (order by yf)     as var_pop_float,
       var_pop(yd) over (order by yd)     as var_pop_decimal,
       var_samp(yf) over (order by yf)    as var_samp_float,
       var_samp(yd) over (order by yd)    as var_samp_decimal,
       stddev_pop(yf) over (order by yf)  as stddev_pop_float,
       stddev_pop(yd) over (order by yd)  as stddev_pop_decimal,
       stddev_samp(yf) over (order by yf) as stddev_samp_float,
       stddev_samp(yd) over (order by yd) as stddev_samp_decimal
from t;

-- returns:

sqrdiff_float    |       sqrdiff_decimal       |   var_pop_float   |    var_pop_decimal    |   var_samp_float   |   var_samp_decimal    |  stddev_pop_float  |  stddev_pop_decimal   | stddev_samp_float  |  stddev_samp_decimal
---------------------+-----------------------------+-------------------+-----------------------+--------------------+-----------------------+--------------------+-----------------------+--------------------+------------------------
                   0 |                           0 |                 0 |                     0 | NULL               | NULL                  |                  0 |                     0 | NULL               | NULL
               180.5 |                       180.5 |             90.25 |                 90.25 |              180.5 |                 180.5 |                9.5 |                   9.5 | 13.435028842544403 | 13.435028842544402964
   320.6666666666667 | 1563.5500000000000000000001 | 106.8888888888889 | 52.738888888888888889 | 160.33333333333334 | 79.108333333333333333 | 10.338708279513883 | 7.2621545624483157849 | 12.662279942148386 | 8.8942865556116041596
              814.75 | 1563.5500000000000000000001 |          203.6875 |               163.075 |  271.5833333333333 | 217.43333333333333333 | 14.271912976192084 | 12.770082223697700217 | 16.479785597310826 | 14.745620818851043999
                1726 |        57131586605212041.25 |             345.2 |                312.71 |              431.5 |              390.8875 | 18.579558659989747 | 17.683608229091708760 |  20.77257807784099 | 19.770875043861867471
              2600.8 | 13317.319002524018247997853 | 433.4666666666667 | 145.82459565876494609 |  520.1600000000001 | 174.98951479051793531 | 20.819862311424316 | 12.075785508974765907 | 22.807016464237492 | 13.228360245718965727
  3845.0371428571434 |  1859.455475739525896765693 | 549.2910204081634 | 190.24741432177168926 |  640.8395238095239 | 221.95531670873363747 | 23.436958429117105 | 13.793020493052697892 | 25.314808389745398 | 14.898164877216711669
   7527.842222222223 |  18594.55475739525896765693 | 836.4269135802471 | 557.17077551305346554 |  940.9802777777779 | 626.81712245218514873 | 28.921046204801222 | 23.604465160495661304 |  30.67540183563661 | 25.036316071902134954
   7527.842222222223 |  18594.55475739525896765693 | 836.4269135802471 | 557.17077551305346554 |  940.9802777777779 | 626.81712245218514873 | 28.921046204801222 | 23.604465160495661304 |  30.67540183563661 | 25.036316071902134954
   8885.844000000001 |  1859.455475739525896765693 | 888.5844000000001 | 185.94554757395258968 |  987.3160000000001 | 206.60616397105843297 |  29.80913282871543 | 13.636185228059663963 |  31.42158493774622 | 14.373801305537044085
(10 rows)
```

The results for windowed aggregate functions with ordering for decimals differ from the results for the same functions without using `over`. The results for floats are the same.

I reproduced this on master branch, commit 7fa301fe1879b8af0249238e3dfd97502a1c694d.

### PR DESCRIPTION
**Pull request by mneverov**
builtins: fix incorrect sqrdiff evaluation due to reuse of the results from previous iterations when used as a window function

fixes #55944

Release note (bug fix): CockroachDB previously could incorrectly evaluate sqrdiff function when used as a window function in some cases, and now it is fixed.

### CODE REVIEW

**Comment by mneverov** [comment]
@yuzefovich could you please take a look?
The root cause was that the result of the sqrdiff function was reused: `tree.DDecimal{Decimal: a.sqrDiff}` copies the pointer to the underlying slice of the `a.sqrDiff`.
Order within windowed aggregate functions does not affect order of the output when run on several nodes, i.e. the order of rows when running `select sqrdiff(x) OVER (ORDER BY x) from t` is unpredictable. As I understand from the other tests in this file this works as intended so I added the column `x` as well as `order by x` to the sql statement.

**Review by yuzefovich — APPROVED** [review]
Thanks for finding the bug and fixing it! I only have some nits, but it :lgtm:

Re: ordering: yeah, `ORDER BY` within `OVER()` clause doesn't guarantee the ordering of the results, we need to have a query level `ORDER BY` clause for that.

nit: it'd be nice to include a short description of the bug into the commit message, and we also should add a release note (it'll be something like `Release note (bug fix): CockroachDB previously could incorrectly evaluate sqrdiff function when used as a window function in some cases, and now it is fixed.`).

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55957#-:-MK_UwLA5U_0WZrYEfMi:b-tep2vd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mneverov)

___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 2862 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55957#-MK_VW96BTBuVYM3MnQV:-MK_VW96BTBuVYM3MnQW:b19x7ik) ([raw file](https://github.com/cockroachdb/cockroach/blob/afc91f7ea9a0911d950fb68163957a24fb4bc02e/pkg/sql/logictest/testdata/logic_test/aggregate#L2862)):*
> ```
> 0.522232967867094 3
> 
> # Regression test for window aggregate functions for decimals reuse the results
> ```

nit: this test should go into `window` logic test file.

nit: I'd slightly reword the comment to be a bit more specific - `Regression test for window aggregate functions not making a deep copy of decimals on each iteration (#55944).`

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55957)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/aggregate, line 2862 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/55957#-MK_VW96BTBuVYM3MnQV:-MK_pJjq461rTs-5mt7N:b8inxp) ([raw file](https://github.com/cockroachdb/cockroach/blob/afc91f7ea9a0911d950fb68163957a24fb4bc02e/pkg/sql/logictest/testdata/logic_test/aggregate#L2862)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: this test should go into `window` logic test file.

nit: I'd slightly reword the comment to be a bit more specific - `Regression test for window aggregate functions not making a deep copy of decimals on each iteration (#55944).`
</blockquote></details>

moved to `window`, replaced the comment, thanks!

**Comment by mneverov** [comment]
@yuzefovich thanks for the review. 
Could you please check if the commit message contains enough / proper info?

**Review by yuzefovich — COMMENTED** [review]
Thanks, one last nit.

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55957#-:-MK_rD0B93s0hzbeeNHK:bsm7jhf)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mneverov)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 3866 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55957#-MK_r5Zq34UPzahd373X:-MK_r5Zq34UPzahd373Y:b-1d3p9g) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6eefbe7efaf3950dc91b45693dfa1db1528e012/pkg/sql/logictest/testdata/logic_test/window#L3866)):*
> ```
> {"1": "1", "2": "2", "3": "3", "4": "4", "5": "5"}
> 
> Regression test for window aggregate functions not making a deep copy of decimals on each iteration (#55944)
> ```

nit: missing `#` in the beginning and a period in the end.

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55957)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/window, line 3866 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/55957#-MK_r5Zq34UPzahd373X:-MK_s5M45gWMNVlmgoue:b-265ea5) ([raw file](https://github.com/cockroachdb/cockroach/blob/f6eefbe7efaf3950dc91b45693dfa1db1528e012/pkg/sql/logictest/testdata/logic_test/window#L3866)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

nit: missing `#` in the beginning and a period in the end.
</blockquote></details>

fixed thx

**Review by yuzefovich — COMMENTED** [review]
Thanks!

bors r=yuzefovich

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/55957#-:-MK_sI9Z2TL6aUyxZChO:b6az1yq)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Pull request merged**
