### PR TITLE
colflow: more minor optimizations and pooling on the read path

### PR DESCRIPTION
**Pull request by yuzefovich**
**colflow: evaluate temp storage path lazily**

This commit makes the evaluation of the temp storage path in the
vectorized flow lazy which allows us to not create a uuid in case of
a local flow when the spilling to disk doesn't occur. This shows about
1% improvement on the micro benchmark of the flow setup. Additionally,
the directory creation is now done when its path is requested for the
first time which allows us to remove one callback from the config.

Release note: None

**colflow: more pooling of objects during the flow setup**

This commit keeps the references to several slices and a map that are
used during the flow setup which allows us to remove several
allocations.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Microbenchmarks:
- first commit
```
name                                          old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24     19.3µs ± 4%    19.1µs ± 5%    ~     (p=0.174 n=19+19)
FlowSetup/vectorize=true/distribute=false-24    16.9µs ± 3%    16.8µs ± 2%  -0.90%  (p=0.044 n=20+20)

name                                          old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24     33.3kB ± 0%    33.2kB ± 0%  -0.35%  (p=0.000 n=19+18)
FlowSetup/vectorize=true/distribute=false-24    29.9kB ± 0%    29.7kB ± 0%  -0.37%  (p=0.000 n=16+16)

name                                          old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24        324 ± 0%       321 ± 0%  -0.93%  (p=0.000 n=19+20)
FlowSetup/vectorize=true/distribute=false-24       293 ± 0%       290 ± 0%  -1.02%  (p=0.000 n=17+17)
```
- second commit
```
name                                          old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24     19.4µs ± 6%    19.0µs ± 4%    ~     (p=0.051 n=20+19)
FlowSetup/vectorize=true/distribute=false-24    16.8µs ± 3%    16.8µs ± 4%    ~     (p=0.851 n=19+17)

name                                          old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24     33.2kB ± 0%    33.2kB ± 0%  -0.27%  (p=0.000 n=18+16)
FlowSetup/vectorize=true/distribute=false-24    29.8kB ± 0%    29.7kB ± 1%  -0.20%  (p=0.003 n=18+19)

name                                          old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24        322 ± 0%       318 ± 0%  -1.24%  (p=0.000 n=19+20)
FlowSetup/vectorize=true/distribute=false-24       291 ± 0%       287 ± 0%  -1.33%  (p=0.000 n=17+17)
```
- third commit
```
name                                          old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24     19.0µs ± 5%    19.0µs ± 4%    ~     (p=0.940 n=19+18)
FlowSetup/vectorize=true/distribute=false-24    16.7µs ± 3%    16.7µs ± 3%    ~     (p=0.763 n=20+20)

name                                          old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24     33.2kB ± 0%    33.1kB ± 0%  -0.06%  (p=0.000 n=16+16)
FlowSetup/vectorize=true/distribute=false-24    29.7kB ± 1%    29.7kB ± 0%  -0.17%  (p=0.000 n=19+16)

name                                          old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24        318 ± 0%       317 ± 0%  -0.31%  (p=0.000 n=20+19)
FlowSetup/vectorize=true/distribute=false-24       287 ± 0%       286 ± 0%  -0.39%  (p=0.000 n=17+17)
```
All commits together:
```
name                                           old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24      18.9µs ± 3%    18.8µs ± 4%    ~     (p=0.422 n=18+20)
FlowSetup/vectorize=true/distribute=false-24     16.7µs ± 3%    16.7µs ± 2%    ~     (p=0.971 n=19+19)
FlowSetup/vectorize=false/distribute=true-24     18.0µs ± 2%    18.1µs ± 5%    ~     (p=0.664 n=20+20)
FlowSetup/vectorize=false/distribute=false-24    16.1µs ± 3%    16.1µs ± 2%    ~     (p=0.862 n=19+20)

name                                           old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24      33.3kB ± 0%    33.2kB ± 0%  -0.49%  (p=0.000 n=19+20)
FlowSetup/vectorize=true/distribute=false-24     29.9kB ± 0%    29.7kB ± 0%  -0.48%  (p=0.000 n=16+19)
FlowSetup/vectorize=false/distribute=true-24     33.8kB ± 0%    33.8kB ± 0%  -0.05%  (p=0.000 n=17+18)
FlowSetup/vectorize=false/distribute=false-24    30.4kB ± 0%    30.3kB ± 0%  -0.06%  (p=0.000 n=18+18)

name                                           old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24         324 ± 0%       318 ± 0%  -1.85%  (p=0.000 n=19+19)
FlowSetup/vectorize=true/distribute=false-24        293 ± 0%       287 ± 0%  -2.05%  (p=0.000 n=17+17)
FlowSetup/vectorize=false/distribute=true-24        289 ± 0%       288 ± 0%  -0.35%  (p=0.000 n=20+20)
FlowSetup/vectorize=false/distribute=false-24       258 ± 0%       257 ± 0%  -0.39%  (p=0.000 n=20+20)
```

**Comment by yuzefovich** [comment]
I personally don't like the third commit - it doesn't give us much improvement but complicates the flow setup story a bit.

**Review by asubiotto — CHANGES_REQUESTED** [review]
Agreed on the last commit, doesn't seem worth it.

> Reviewed 9 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-:-MLlcbyu1aFgd8mr50gm:b59ebch)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto and @yuzefovich)

___
*[pkg/sql/colflow/vectorized_flow.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-MLlbhsw2fItr9ndN7M5:-MLlbhsw2fItr9ndN7M6:b4l46og) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e64351be6e5d51b4ba6a22a4c626934e5848ab6/pkg/sql/colflow/vectorized_flow.go#L104)):*
> ```Go
> 
> 	tempStorage struct {
> 		pathStateMu struct {
> ```

I think we can merge this with `createdStateMu` below somehow by even getting rid of the `created` boolean (i.e.  path has been created if `path != ""`)
___
*[pkg/sql/colflow/vectorized_flow.go, line 256 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-MLlb6TyDbhCZrH9ntQl:-MLlb6TyDbhCZrH9ntQm:b-r7uk2a) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e64351be6e5d51b4ba6a22a4c626934e5848ab6/pkg/sql/colflow/vectorized_flow.go#L256)):*
> ```Go
> 	f.tempStorage.pathStateMu.Lock()
> 	defer f.tempStorage.pathStateMu.Unlock()
> 	if f.tempStorage.pathStateMu.path == "" {
> ```

nit: I would flip the if to keep most of the code unindented:
```
if f.tempStorage.pathStateMu.path != "" {
    return f.tempStorage.pathStateMu.path
}
// Compute path
```
___
*[pkg/sql/colflow/vectorized_flow.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-MLlcvsV1vfbAIVzgF3j:-MLlcvsV1vfbAIVzgF3k:bpzz2yg) ([raw file](https://github.com/cockroachdb/cockroach/blob/09cd5f33f7fae664fbc99734cdbec6dcd3ae33ea/pkg/sql/colflow/vectorized_flow.go#L107)):*
> ```Go
> // execinfra.Releasable interface, but that would lead to conflict with
> // semaphore.Semaphore.Release method.
> func (s *countingSemaphore) ReleaseToPool() {
> ```

Should this assert that `s.count` is 0?
___
*[pkg/sql/colflow/vectorized_flow.go, line 622 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-MLldDPq9WAq84ySVrw_:-MLldDPq9WAq84ySVrwa:b8ursir) ([raw file](https://github.com/cockroachdb/cockroach/blob/09cd5f33f7fae664fbc99734cdbec6dcd3ae33ea/pkg/sql/colflow/vectorized_flow.go#L622)):*
> ```Go
> 		releasables:                    s.releasables[:0],
> 		scratch: struct {
> 			inputs               []colexecbase.Operator
> ```

another way you could do this is just assign the fields below to avoid having to redefine the anonymous struct
___
*[pkg/sql/distsql/columnar_utils_test.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-MLlcH1C72SmAwSVtgNk:-MLlcH1C72SmAwSVtgNl:b8d34hd) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e64351be6e5d51b4ba6a22a4c626934e5848ab6/pkg/sql/distsql/columnar_utils_test.go#L91)):*
> ```Go
> 	}
> 	defer tempEngine.Close()
> 	queueCfg, cleanup := colcontainerutils.NewTestingDiskQueueCfg(t, true /* inMem */)
> ```

Why do we need to make the testing disk queue cfg here? Since the cfg didn't have a path before wouldn't the equivalent be to populate the disk queue cfg with a callback that returns an empty string?

**Review by yuzefovich — COMMENTED** [review]
Ok, removed the third commit.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-:-MLnPERw0vCYnlfVVa_w:b1oa2ze)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colflow/vectorized_flow.go, line 104 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-MLlbhsw2fItr9ndN7M5:-MLnTPeFBunX3ZieB5qM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e64351be6e5d51b4ba6a22a4c626934e5848ab6/pkg/sql/colflow/vectorized_flow.go#L104)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I think we can merge this with `createdStateMu` below somehow by even getting rid of the `created` boolean (i.e.  path has been created if `path != ""`)
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 107 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-MLlcvsV1vfbAIVzgF3j:-MLnYiY44bt97Aacx8Dk:b-fap6s5) ([raw file](https://github.com/cockroachdb/cockroach/blob/09cd5f33f7fae664fbc99734cdbec6dcd3ae33ea/pkg/sql/colflow/vectorized_flow.go#L107)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Should this assert that `s.count` is 0?
</blockquote></details>

I'm not sure how useful that is - we're releasing all of the leftover FDs in `vectorizedFlow.Cleanup`, so it must be zero and it might make sense to assert it just in case. However, we don't have a way to propagate the error from `Release` method, so it must be panic that will not be caught and will lead to a crash.

That said, I think if it does crash, then something has gone really wrong, so I added the assertion.
___
*[pkg/sql/colflow/vectorized_flow.go, line 622 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-MLldDPq9WAq84ySVrw_:-MLn_C6z72C-IuIj71ag:boqybmq) ([raw file](https://github.com/cockroachdb/cockroach/blob/09cd5f33f7fae664fbc99734cdbec6dcd3ae33ea/pkg/sql/colflow/vectorized_flow.go#L622)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

another way you could do this is just assign the fields below to avoid having to redefine the anonymous struct
</blockquote></details>

Yeah, we could have this diff
```
@@ -592,6 +595,7 @@ func (s *vectorizedFlowCreator) Release() {
        for _, r := range s.releasables {
                r.Release()
        }
+       scratch := s.scratch
        *s = vectorizedFlowCreator{
                streamIDToInputOp:              s.streamIDToInputOp,
                streamIDToSpecIdx:              s.streamIDToSpecIdx,
@@ -602,16 +606,10 @@ func (s *vectorizedFlowCreator) Release() {
                monitors:                       s.monitors[:0],
                accounts:                       s.accounts[:0],
                releasables:                    s.releasables[:0],
-               scratch: struct {
-                       inputs               []colexecbase.Operator
-                       metadataSourcesQueue []execinfrapb.MetadataSource
-                       toClose              []colexecbase.Closer
-               }{
-                       inputs:               s.scratch.inputs[:0],
-                       metadataSourcesQueue: s.scratch.metadataSourcesQueue[:0],
-                       toClose:              s.scratch.toClose[:0],
-               },
        }
+       s.scratch.inputs = scratch.inputs[:0]
+       s.scratch.metadataSourcesQueue = scratch.metadataSourcesQueue[:0]
+       s.scratch.toClose = scratch.toClose[:0]
```
but I like the idea of having to declare the anonymous struct because if we later add another field to `scratch`, then the compiler will complain and it'll be a reminder to update `Release` method accordingly. Do you think there is a performance impact of declaring an anonymous struct on every `Release` call?

I guess I can try both options with microbenchmarks.

They showed no difference, so I'm leaning towards keeping the anonymous struct:
```
name                                          old time/op    new time/op    delta
FlowSetup/vectorize=true/distribute=true-24     18.8µs ± 6%    18.6µs ± 4%    ~     (p=0.206 n=44+45)
FlowSetup/vectorize=true/distribute=false-24    16.9µs ± 3%    16.9µs ± 4%    ~     (p=0.982 n=50+45)

name                                          old alloc/op   new alloc/op   delta
FlowSetup/vectorize=true/distribute=true-24     33.7kB ± 0%    33.7kB ± 0%  +0.06%  (p=0.003 n=47+47)
FlowSetup/vectorize=true/distribute=false-24    30.3kB ± 0%    30.3kB ± 0%  +0.06%  (p=0.000 n=44+35)

name                                          old allocs/op  new allocs/op  delta
FlowSetup/vectorize=true/distribute=true-24        317 ± 1%       318 ± 1%  +0.32%  (p=0.000 n=50+50)
FlowSetup/vectorize=true/distribute=false-24       288 ± 0%       289 ± 0%  +0.35%  (p=0.000 n=50+40)
```
___
*[pkg/sql/distsql/columnar_utils_test.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-MLlcH1C72SmAwSVtgNk:-MLnX9otDQ-JHkmzLoz9:b-ewxth6) ([raw file](https://github.com/cockroachdb/cockroach/blob/5e64351be6e5d51b4ba6a22a4c626934e5848ab6/pkg/sql/distsql/columnar_utils_test.go#L91)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why do we need to make the testing disk queue cfg here? Since the cfg didn't have a path before wouldn't the equivalent be to populate the disk queue cfg with a callback that returns an empty string?
</blockquote></details>

Yeah, fixed.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 8 of 8 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/56464#-:-MLqslyf-QihNEmMIb2n:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
