### PR TITLE
[DNM] sql: use the correct type for inverted key columns during planning

### LINKED ISSUE #50695: opt: change the key column of inverted indexes to use a new column id and type
Currently, the inverted key column of an inverted index uses the same column ID and type as the original table column it indexes. This is a problem if the column needs to be passed between several operators, because the execution engine expects a column with a certain type (e.g., Geometry), but receives a different type (e.g., int). It also makes several things awkward in the optimizer, and requires special handling of the inverted key column.

The solution is to create a new column for the inverted key column, with a new column ID and type corresponding to the real type stored in the inverted index. This issue tracks the work to make that change in the optimizer.

### PR DESCRIPTION
**Pull request by rytaft**
This commit changes the column type for inverted key columns when constructing
`scanNode`s and `TableReaderSpec`s so that the type matches the data type actually
stored in the index. Prior to this commit, the type corresponded to the column
being indexed (e.g., `geometry`), rather than the actual type of the key column
(e.g., `int`). This is needed in order to enable vectorized execution with the
`invertedFilterer` processor.

Fixes #50695

Release note (performance improvement): Queries that use a geospatial inverted
index can now take advantage of vectorized execution for some parts of the
query plan, resulting in improved performance.

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
One place that needs to be updated is removal of disabling of inverted filterer in `colbuilder/execplan.go:579`. I'd also try running some queries manually with `SET vectorize=experimental_always` to make sure that the vectorized flow does get planned.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53202#-:-MFGbCbR-vFAxsumgXmd:b-4ho1nl)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola and @yuzefovich)

**Review by sumeerbhola — COMMENTED** [review]
and even geospatial may become its own custom encoding and not `DInt` -- ongoing discussion at https://cockroachlabs.slack.com/archives/CPBH0NZHQ/p1598027962010700

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53202#-:-MFGzW4H7i_2AOMIE7mj:b-ktwdxe)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @sumeerbhola)

**Comment by rytaft** [comment]
So I finally got this working, but it required a lot more changes than I expected. I had to thread the types of the virtual columns through many different functions, and I had to modify the `invertedFilterer` to encode the key columns (since the vectorized engine only returned decoded columns). This all feels pretty ugly and feels like it's probably not the best way to fix this issue.

I'm not sure how much of a difference this will make in terms of performance and whether or not it's worth the added complexity and ugliness. Is there a particular benchmark we want to test here?

Let me know if people have suggestions or if I should just close this PR.

**Review by sumeerbhola — COMMENTED** [review]
> I'm not sure how much of a difference this will make in terms of performance and whether or not it's worth the added complexity and ugliness. Is there a particular benchmark we want to test here?

Thanks for working through this! 
Can you try with https://github.com/cockroachlabs/sqlcmp and see if this helps -- I am very curious about the result.

The encoding of the inverted geo column will change in https://github.com/cockroachdb/cockroach/pull/53215 and no longer be the `DInt` encoding, so I think we'll need to figure out how to use `DBytes` for everything.

> Reviewed 2 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/53202#-:-MFVOsUW9uj8EV04b7tp:b-dwzo99)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/rowexec/inverted_joiner.go, line 263 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/53202#-MFVOZOI9LwVt3VVKpR6:-MFVOZOI9LwVt3VVKpR7:bz8x4qn) ([raw file](https://github.com/cockroachdb/cockroach/blob/47449fd2bb37d222d597a89a94dd51ac00be6af2/pkg/sql/rowexec/inverted_joiner.go#L263)):*
> ```Go
> 		descpb.ScanLockingStrength_FOR_NONE, descpb.ScanLockingWaitPolicy_BLOCK,
> 		nil /* systemColumns */, nil, /* virtualColumns */
> 	)
> ```

Did the scan done by the `invertedJoiner` not return a decoded inverted column? I would have expected we would need to encode it before passing to the `batchedInvertedExprEvaluator`.

**Comment by rytaft** [comment]
I ran the benchmark, and for these queries, vectorization doesn't seem to help (I've only included the queries that use invertedFilterer):
```
name                                   old ms     new ms     delta
Test/postgis_geography_tutorial/11.2b  3.61 ±41%  3.25 ±50%  -10.10%  (p=0.209 n=24+18)
Test/postgis_geography_tutorial/11.6   8.40 ±40%  8.72 ±23%   +3.82%  (p=0.578 n=16+14)
Test/postgis_geometry_tutorial/11.2b   4.87 ±28%  5.00 ±31%   +2.77%  (p=0.428 n=21+17)
Test/postgis_geometry_tutorial/11.6    5.92 ±45%  6.13 ±40%   +3.64%  (p=0.606 n=25+20)
Test/postgis_geometry_tutorial/12.1.2  3.85 ±33%  3.77 ±33%   -1.99%  (p=0.679 n=24+20)
Test/postgis_geometry_tutorial/12.2.3  5.95 ±66%  6.19 ±60%   +4.05%  (p=0.622 n=25+20)
Test/postgis_geometry_tutorial/12.2.4  6.86 ±36%  7.48 ±28%   +9.01%  (p=0.252 n=24+19)
```
This doesn't really surprise me, since the only thing these queries are using the vectorized execution engine for is the scan. If anything, vectorization is probably a bit worse here since there is probably some overhead to convert back and forth between the two data formats.

I bet that vectorization will be helpful for more complex queries, but given the complexity of this change and the lack of a compelling use case, seems like we should close this PR.

Any objections?

**Comment by yuzefovich** [comment]
I agree with your assessment about probably not getting much benefit (if any) from the vectorization on spatial queries and am in favor of closing this PR. Thanks for trying this out!

**Comment by rytaft** [comment]
Closing - thanks!

**Pull request closed without merging**
