### PR TITLE
workload/schemachange: put ADD REGION/PRIMARY REGION into operation_generator

### PR DESCRIPTION
**Pull request by otan**
see individual commits for details

### CODE REVIEW

**Comment by ajstorm** [comment]
Nit: Can we change the description on the commit record for the 4th commit?  It took me a few minutes to realize that you're not actually putting ADD REGION and ADD PRIMARY REGION into the schema changer (!!!) but instead, into the schema changer test harness (operation_generator).

**Review by ajwerner — APPROVED** [review]
I find `workload/schemachange` as a prefix to be clearer. 

:lgtm: 

> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62238#-:-MWPLSJP9CTqHEwphk-Z:b-dtolsb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/ccl/testccl/workload/schemachange/main_test.go, line 32 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/62238#-MWPLfET6tI66bTA64Bx:-MWPLfET6tI66bTA64By:b8h94fb) ([raw file](https://github.com/cockroachdb/cockroach/blob/2dd513b1029c024965011ffbd053768aeccc94e7/pkg/ccl/testccl/workload/schemachange/main_test.go#L32)):*
> ```Go
> }
> 
> //go:generate ../../util/leaktest/add-leaktest.sh *_test.go
> ```

this now needs another `../../`

**Comment by otan** [comment]
bors r=ajwerner

**Comment by otan** [comment]
oops, letting this pass first 

bors r-

**Comment by otan** [comment]
bors r=ajwerner

**Comment by otan** [comment]
bors r-

great, stressrace

**Comment by otan** [comment]
should be good, missing an `if rows.Err() != nil` check (that is not obvious :\)

bors r=ajwerner

**Review by ajwerner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/62238)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @ajwerner and @otan)

___
*[pkg/workload/schemachange/operation_generator.go, line 445 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/62238#-MWS04cC6E3H-AhE5jCu:-MWS04cDCY_wxe7J1V4W:b-56tb1r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ce69d70d627a9dab5e034c378081a6988d04085b/pkg/workload/schemachange/operation_generator.go#L445)):*
> ```Go
> 		regionNames = append(regionNames, regionName)
> 	}
> 	if rows.Err() != nil {
> ```

I feel like there should be a linter for this

**Pull request merged**
