### PR TITLE
sql: Fix commit count for txns in CommitWait state

### LINKED ISSUE #5644: ui: count of transaction graph not showing commits when retrying
the photos app running against the beta cluster was just upgraded to a version that uses https://github.com/cockroachdb/cockroach-go/blob/master/crdb/tx.go to retry transactions.

As soon as that happened, the SQL transaction graph dropped to zero for Commits:
https://beta.cockroachdb.com:8080/#/nodes/graphs 

The KV transactions graph looks ok though.

### PR DESCRIPTION
**Pull request by andreimatei**
Fixes #5644

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/5674)

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm: mod first commit

---

Reviewed 2 of 2 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[testutils/sqlutils/metric_utils.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2TOLbJQqNuABd-hVL:-KE2TOLbJQqNuABd-hVM:-1135789303) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfce115739fe2513a1b0e914788df146ca411720/testutils/sqlutils/metric_utils.go#L26)):*
this is not the right place for these. Put them in a _test file in the sql package (but leave them exported). This will make them accessible from packages sql and sql_test, which is enough for what you need in this PR.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-:-KE2TfRwl9pTpRSaD2Nx:-1015774604)*

**Comment by andreimatei** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[testutils/sqlutils/metric_utils.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2TOLbJQqNuABd-hVL:-KE2Y-WM8x7QDXUaftMK:-1194167449) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfce115739fe2513a1b0e914788df146ca411720/testutils/sqlutils/metric_utils.go#L26)):*
why is this not the right place? Here's where I'd look for utility functions, as opposed to troll other tests. And tests importing from other tests seems not ideal. When I refactor something in one test file I probably wouldn't think to look around for other users.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674)*

**Comment by tamird** [comment]
Well, sqlutils is not test-only, AFAIK.

**Comment by andreimatei** [comment]
but this is `testutils/sqlutils`

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-:-KE2b1wQV79uhaAYPyMW:-1493735931)*

**Comment by tamird** [comment]
Ok, it seems to me that this is not used outside of SQL, so it shouldn't be
exported more broadly. As for the file naming concern: don't put it in an
existing file; make a new file called metrics_utils_test.go. It's the same,
just smaller in scope.

**Comment by cuongdo** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[testutils/sqlutils/metric_utils.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2TOLbJQqNuABd-hVL:-KE2iBkuDnoZg4z7AaEE:-933204114) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfce115739fe2513a1b0e914788df146ca411720/testutils/sqlutils/metric_utils.go#L26)):*
I don't feel strongly either way, but I don't think it's worth moving this to a new file in the `sql` directory.  This doesn't do any harm here, and I agree with @andreimatei that I don't generally look in other test files for helper functions, except for test setup functions..

---

*[testutils/sqlutils/metric_utils.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2hDtpQCn6lu2tlrTL:-KE2hDtqH9IhR67W1Jn4:2053865747) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2cfcc35d83f1a327870db4f97f9955a8616c35/testutils/sqlutils/metric_utils.go#L27)):*
why `!(a == e)`? seems clearer to write `a != e`

---

*[testutils/sqlutils/metric_utils.go, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2hKXi1VKmkE1GFDWG:-KE2hKXi1VKmkE1GFDWH:-1299925971) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2cfcc35d83f1a327870db4f97f9955a8616c35/testutils/sqlutils/metric_utils.go#L33)):*
same here, why not write `(a < e)`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 4 unresolved discussions.

---

*[sql/metric_util_test.go, line 26 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2TOLbJQqNuABd-hVL:-KE2jq2cPGj2HEt6aQkm:-385753690) ([raw file](https://github.com/cockroachdb/cockroach/blob/bfce115739fe2513a1b0e914788df146ca411720/sql/metric_util_test.go#L26)):*
the argument I kinda bought is that we haven't really figured out what `testutils` is supposed to be... utilities used in tests, or in prod code that facilitates testing.
I've moved it to an `_test` file.

---

*[sql/metric_util_test.go, line 27 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2hDtpQCn6lu2tlrTL:-KE2k8psKlRgLpQu-_12:806872343) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2cfcc35d83f1a327870db4f97f9955a8616c35/sql/metric_util_test.go#L27)):*
I guess the idea was to mimic the condition in the function name. Changed.

---

*[sql/metric_util_test.go, line 33 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2hKXi1VKmkE1GFDWG:-KE2kD_QO6RSss7EBlTJ:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/6c2cfcc35d83f1a327870db4f97f9955a8616c35/sql/metric_util_test.go#L33)):*
Done.

---

*[sql/metric_util_test.go, line 19 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2jcNt-WAnQQOoEr7E:-KE2jcNuJMRxPL5lIH2s:1596031878) ([raw file](https://github.com/cockroachdb/cockroach/blob/99fc9dfeaac6a33e88aaa31c39467009e4be3027/sql/metric_util_test.go#L19)):*
i had to put it in the `_test` package because `sql` can't import `server` :(  

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674)*

**Comment by cuongdo** [comment]
:lgtm:

---

Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-:-KE2l6VGDdIqbeSTnEcl:1417088721)*

**Comment by tamird** [comment]
Reviewed 3 of 3 files at r3, 5 of 5 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/metric_util_test.go, line 19 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2jcNt-WAnQQOoEr7E:-KE2kvuyq8zQrC2h7ZiD:1730223963) ([raw file](https://github.com/cockroachdb/cockroach/blob/99fc9dfeaac6a33e88aaa31c39467009e4be3027/sql/metric_util_test.go#L19)):*
Ah, makes sense. FWIW, these functions don't need to be exported now, since they aren't shared between `sql` and `sql_test`. In fact, they could happily stay where they started.

Anyway, your call.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674)*

**Comment by andreimatei** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/metric_util_test.go, line 19 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674#-KE2jcNt-WAnQQOoEr7E:-KE2nO4msrhNE7gHCKGk:-1823687759) ([raw file](https://github.com/cockroachdb/cockroach/blob/99fc9dfeaac6a33e88aaa31c39467009e4be3027/sql/metric_util_test.go#L19)):*
unexported

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/5674)*

**Pull request merged**
