### PR TITLE
geo: add ability to convert from Geography to S2 regions

### PR DESCRIPTION
**Pull request by otan**
This PR adds the ability to convert from Geography to S2. We currently
do this via the geom library, to avoid having to parse any EWKB
ourselves. This will be different in future, but is a good stop gap to
unblock feature development.

Release note: None

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46945#-:-M4-rhwQ0DPgzclw8elZ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @otan)

___
*[pkg/geo/geo_test.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46945#-M4-r9M4-v76xkW9jkYY:-M4-r9M4-v76xkW9jkYZ:b-9rsiy0) ([raw file](https://github.com/cockroachdb/cockroach/blob/462537977e43f9af0b42009d70c63f050fb0ac99/pkg/geo/geo_test.go#L22)):*
> ```Go
> )
> 
> func TestGeographyAsS2(t *testing.T) {
> ```

`s2.Region` doesn't seem to have a `String()` function. If it had one, this would be less code as a datadriven test.

**Comment by otan** [comment]
___
*[pkg/geo/geo_test.go, line 22 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46945#-M4-r9M4-v76xkW9jkYY:-M402FDl2L1iQXW1rTnv:b2nh4dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/462537977e43f9af0b42009d70c63f050fb0ac99/pkg/geo/geo_test.go#L22)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

`s2.Region` doesn't seem to have a `String()` function. If it had one, this would be less code as a datadriven test.
</blockquote></details>

:'(

**Comment by otan** [comment]
bors r=sumeerbhola

**Comment by knz** [comment]
this PR has a CI failure

bors r-

**Comment by otan** [comment]
urgh, GithubCI didn't trigger. sorry about that.

image

**Comment by otan** [comment]
bors r=sumeerbhola

**Pull request merged**
