### PR TITLE
sql/catalog/tabledesc: relaxed validation for virtual col in SUFFIX cols

### PR DESCRIPTION
**Pull request by Xiang-Gu**
One of the validation rule says that "we don't allow virtual columns to
be in the SUFFIX columns of a secondary index", except for one case:
`ALTER PRIMARY KYE USING HASH`, where the implicitly created virtual,
shard column, will need to appear in the SUFFIX columns of the
implicitly created unique, secondary index of the old PK key columns (
which btw is a CRDB unique feature).

The validation has logic to exempt us from this special case but it's
written specifically to the legacy schema changer. Namely, it uses the
canonical `PrimaryKeySwap` mutation type as the signal but we don't have
that in the declarative schema changer. This PR addresses this issue and
allows the validation logic to also exempt the exact same case but
in the declarative schema changer.

Release note: None

### CODE REVIEW

**Review by ajwerner — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85849)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner and @Xiang-Gu)

___
*[`pkg/sql/catalog/tabledesc/validate.go` line 1295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85849#-N93MPFb0tvNFkgAUHKp:-N93MPFb0tvNFkgAUHKq:b7709cz) ([raw file](https://github.com/cockroachdb/cockroach/blob/6004b1ff29a06d06a6d39db111323984ddcbb53a/pkg/sql/catalog/tabledesc/validate.go#L1295)):*
> ```Go
> 			// sadly, if the `ALTER PRIMARY KEY USING HASH` is from declarative schema changer,
> 			// we won't find the `PrimaryKeySwap` mutation. In that case, we will attempt to
> 			// find a mutation of adding a primary index and use that
> ```

nit: start with a capital letter and maybe end the sentence with `and allow its key columns to be used`?

**Review by Xiang-Gu — COMMENTED** [review]
RFAL!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85849#-:-N978lp4-dBEs6EhFaZU:b-828fnn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajwerner)

___
*[`pkg/sql/catalog/tabledesc/validate.go` line 1295 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85849#-N93MPFb0tvNFkgAUHKp:-N978kmNCIMhbMvN0b2w:b-896fja) ([raw file](https://github.com/cockroachdb/cockroach/blob/6004b1ff29a06d06a6d39db111323984ddcbb53a/pkg/sql/catalog/tabledesc/validate.go#L1295)):*
<details><summary><i>Previously, ajwerner wrote…</i></summary><blockquote>

nit: start with a capital letter and maybe end the sentence with `and allow its key columns to be used`? 
</blockquote></details>

Done!

**Review by ajwerner — APPROVED** [review]
:lgtm:

If you've got an approval and my comments are just nits, feel free to bors it without my taking another look. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85849#-:-N97973z2uDWDoLCAnqi:b-uxrsbo)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajwerner)

**Comment by Xiang-Gu** [comment]
TFTR!

bors r+

**Pull request merged**
