### PR TITLE
.github: add CODEOWNERS

### PR DESCRIPTION
**Pull request by knz**

### CODE REVIEW

**Comment by knz** [comment]
cc @danhhz @RaduBerinde

**Comment by tschottdorf** [comment]
pkg/storage/** belongs to core.

**Comment by jordanlewis** [comment]
@knz I am mildly concerned - will this automatically request reviews from every member of each team that owns a modified file in a PR? If so, that will hurt usability in my opinion.

**Comment by knz** [comment]
@jordanlewis please elaborate.

**Comment by petermattis** [comment]
I'll be curious to see how helpful or irritating this is. Willing to experiment.

**Comment by knz** [comment]
The problem I am trying to solve is that I do not want to be subscribed to all github notifications yet I would like to receive a notifications for exactly those PRs that touch at least some of the files I am interested in.

If there is another solution to solve that problem, I'll take it.

**Comment by jordanlewis** [comment]
Also willing to try, but my concern is just that adding every team member as an auto reviewer will leave most PRs with 5 or more reviewers. Perhaps that's okay! But we'll need to establish clearer guidelines at that point for how to designate the primary reviewer. For example, we could use the assignee field.

**Comment by knz** [comment]
@jordanlewis AFAICS there is a single reviewer entry for the entire team invited to review by the codeowners file. See the example in https://github.com/blog/2392-introducing-code-owners.

**Comment by jordanlewis** [comment]
Ah, cool! I think that's great then. I was fooled because you can't manually add a team as a reviewer.

**Comment by benesch** [comment]
:tada: agreed, this sounds great.

FWIW, if we start ascribing more meaning to the assignee field, I'd prefer that we do what GitHub intends, and use it to mean "the person who will press the big green merge button." This essentially means every PR an employee opens will be assigned to him/herself, but for external contributors it'll designate whoever's shepherding the PR.

**Comment by benesch** [comment]
`pkg/storage/*     @cockroachdb/core`?

**Comment by knz** [comment]
yes toby already mentioned that. will do in a moment.

**Comment by benesch** [comment]
Whoops, sorry, didn't read. Also would be in favor of a build team:

```
build/*          @cockroachdb/build
c-deps/*         @cockroachdb/build
githooks/*       @cockroachdb/build
scripts/*        @cockroachdb/build
**/Makefile      @cockroachdb/build
```

**Comment by knz** [comment]
can you edit the PR to your liking? (Don't forget to create the team first)

**Comment by benesch** [comment]
You bet. Done!

**Comment by knz** [comment]
LGTM

**Comment by knz** [comment]
Another data point for understanding: it is actually important that the team ID gets bound as reviewer and not the members. This way a person can join the team after the PR was created, and see the PR appear in their "list of PRs awaiting review" list automatically.

**Comment by andreimatei** [comment]
Can you please explain what this will do? Will we still be able to assign individual reviewers somehow (besides the whole team being otherwise CCed?). Cause that's important IMO.

**Comment by benesch** [comment]
Yeah, AIUI, the team gets auto-review-requested, but a primary reviewer can
still be explicitly listed. We can always revert if that turns out not to
work properly.

**Comment by knz** [comment]
No opinions were voiced, assuming all good. Merging.

**Pull request merged**
