### PR TITLE
release-22.1: ci: add scripting to generate declarative schema changer corpus 

### PR DESCRIPTION
**Pull request by fqazi**
These changes do the following:

Informs: https://github.com/cockroachdb/cockroach/issues/82643

* Move test case for validating schema changer corpuses into the corpus package (done to stay in sync with master)
* More importantly for the dev-infra team an initial approach to collect declarative schema changer states from logictest during nightly builds. The scripts included here will generate a corpus and upload them to GCS storage for a nightly build.

Release justification: low-risk changes to add scripting for nightly artifacts to allow us to do mixed version testing for the declarative schema changer

### CODE REVIEW

**Comment by fqazi** [comment]
Wrong branch stupid mistake on my part, used the wrong tag

**Comment by fqazi** [comment]
Needs some tweaks will re-open after

**Review by rickystewart — APPROVED** [review]

**Comment by fqazi** [comment]
@rickystewart TFTR!

bors r+

**Comment by yuzefovich** [comment]
No need to use bors on older branches, just click the merge button once it becomes green.

**Pull request merged**
