### PR TITLE
spanconfig: add Record constructor and validation

### PR DESCRIPTION
**Pull request by adityamaru**
This change adds a constructor method that returns
a new `spanconfig.Record` and conditionally performs
some validation if the target is a SystemTarget.

Informs: https://github.com/cockroachdb/cockroach/issues/73727

Release note: None

Release justification: low-risk updates to new functionality

### CODE REVIEW

**Comment by adityamaru** [comment]
Will rebase once #77338 is in.

**Review by arulajmani — COMMENTED** [review]
Thanks for doing this! Looks good modulo couple minor comments/suggestions. 

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-:-MxPvkeREc9nRDTZVf7T:b-ysyrdd)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/roachpb/span_config.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPql3N3h2WNB5RKgS2:-MxPql3N3h2WNB5RKgS3:b-byfpg5) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/roachpb/span_config.go#L89)):*
> ```Go
> 		return errors.AssertionFailedf("LeasePreferences set on system span config")
> 	}
> 	if s.RangefeedEnabled == true {
> ```

The linter is complaining about simplifying this to just `if s.RangefeedEnabled {`
___
*[pkg/roachpb/span_config.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPw3x4Aa2fZOHNLjgr:-MxPw3x4Aa2fZOHNLjgs:b-83jxvi) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/roachpb/span_config.go#L91)):*
> ```Go
> 	if s.RangefeedEnabled == true {
> 		return errors.AssertionFailedf("RangefeedEnabled set on system span config")
> 	}
> ```

Do we want to check `ExcludeFromBackup` here as well? 
___
*[pkg/roachpb/span_config.proto, line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPtoko2SOjpz4En8ET:-MxPtoko2SOjpz4En8EU:ba864k1) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/roachpb/span_config.proto#L189)):*
> ```protobuf
>   // Next ID: 12
>   //
>   // When adding a field, also add a check a to `ValidateSystemTargetSpanConfig`
> ```

nit: you could add a test that codifies this, something similar in essence to what we do in `TestValidateCoversAllDescriptorFields`.
___
*[pkg/spanconfig/spanconfig.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPr7eL231oGm80F76-:-MxPr7eL231oGm80F760:b-sr3frq) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfig.go#L277)):*
> ```Go
> // Record ties a target to its corresponding config.
> //
> // Use `MakeRecord` to construct a new Record instead of directly reaching for
> ```

Instead of this comment, how about enforcing this in code by making `Target` and `Config` private fields and adding getters? 
___
*[pkg/spanconfig/spanconfig.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPsW4mCRPXbmaDvNZ8:-MxPsW4mCRPXbmaDvNZ9:bel58y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfig.go#L279)):*
> ```Go
> // Use `MakeRecord` to construct a new Record instead of directly reaching for
> // this struct to ensure proper validation.
> type Record struct {
> ```

super nit: should we pull this struct, its getters, and constructors into its own file? 
___
*[pkg/spanconfig/spanconfig.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPsBhJ6GEh7AqM93ui:-MxPsBhJ6GEh7AqM93uj:b8kkxoo) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfig.go#L289)):*
> ```Go
> // MakeRecord returns a Record with the specified Target and SpanConfig. If the
> // Record targets a SystemTarget, we also validate the SpanConfig.
> func MakeRecord(target Target, cfg roachpb.SpanConfig) (Record, error) {
> ```

Let's add a basic test that ensures we return validation errors correctly? 
___
*[pkg/spanconfig/spanconfig.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPuj2u87CfeO4rB116:-MxPuj2u87CfeO4rB117:b-3wnzpn) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfig.go#L293)):*
> ```Go
> 		if err := cfg.ValidateSystemTargetSpanConfig(); err != nil {
> 			return Record{},
> 				errors.AssertionFailedf("failed to validate SystemTarget SpanConfig: %+v", err.Error())
> ```

nit: we could panic here, like we do in `MakeTargetFromSpan` and a few other places in `target.go` where we know for sure it is a programming mistake if this ever happens. 
___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPtR1lBYwnq7dCdiK9:-MxPtR1lBYwnq7dCdiKA:b-xpa4) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L180)):*
> ```Go
> 			}
> 		}
> 		clusterSystemRecord, err := spanconfig.MakeRecord(
> ```

nit: missing error check

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77349)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @adityamaru and @arulajmani)

___
*[pkg/roachpb/span_config.go, line 89 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPql3N3h2WNB5RKgS2:-MxW9TtkB4NyBggNP7rS:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/roachpb/span_config.go#L89)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

The linter is complaining about simplifying this to just `if s.RangefeedEnabled {`
</blockquote></details>

Done.
___
*[pkg/roachpb/span_config.go, line 91 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPw3x4Aa2fZOHNLjgr:-MxW9ULy8L5h5q7UEwPU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/roachpb/span_config.go#L91)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Do we want to check `ExcludeFromBackup` here as well? 
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfig.go, line 277 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPr7eL231oGm80F76-:-MxW9Wqh47lMCNEy8xbT:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfig.go#L277)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Instead of this comment, how about enforcing this in code by making `Target` and `Config` private fields and adding getters? 
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfig.go, line 279 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPsW4mCRPXbmaDvNZ8:-MxW9XRo0zWZyyrsxl4-:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfig.go#L279)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

super nit: should we pull this struct, its getters, and constructors into its own file? 
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfig.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPuj2u87CfeO4rB116:-MxW9YhC0BwXj9aoUQqT:b-gl8efz) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfig.go#L293)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: we could panic here, like we do in `MakeTargetFromSpan` and a few other places in `target.go` where we know for sure it is a programming mistake if this ever happens. 
</blockquote></details>

meh I'm generally panic averse. Most of the places already had proper error handling so it wasn't too painful. In light of issues like https://github.com/cockroachdb/cockroach/issues/76734 and having being bitten by panics in bulk code I prefer to return an error.
___
*[pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go, line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPtR1lBYwnq7dCdiK9:-MxW9nO52OmwwcDr8Qj4:b4g0byo) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfigsqltranslator/sqltranslator.go#L180)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: missing error check 
</blockquote></details>

oops, done.

**Comment by adityamaru** [comment]
I want CI to shake out any tests I might have forgotten to update so I'd hold off reviewing for a bit. I also need to add a simple validation test still but addressed other comments.

**Review by arulajmani — COMMENTED** [review]
:lgtm: modulo a couple minor comments. 

> Reviewed 18 of 20 files at r2, 1 of 1 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-:-MxjiOdL0bSg06Y4xJQX:blib45z)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @adityamaru)

___
*[pkg/spanconfig/spanconfig.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPsBhJ6GEh7AqM93ui:-MxjiGpJ2p9_hyt4bBmR:b-k4i083) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfig.go#L289)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Let's add a basic test that ensures we return validation errors correctly? 
</blockquote></details>

The line this comment was referencing has moved, but were hoping to do this? 
___
*[pkg/spanconfig/spanconfig.go, line 293 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPuj2u87CfeO4rB116:-Mxjgdoh2iS-HbUExyK5:bx5xt6s) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfig.go#L293)):*
<details><summary><i>Previously, adityamaru (Aditya Maru) wrote…</i></summary><blockquote>

meh I'm generally panic averse. Most of the places already had proper error handling so it wasn't too painful. In light of issues like https://github.com/cockroachdb/cockroach/issues/76734 and having being bitten by panics in bulk code I prefer to return an error.
</blockquote></details>

Okay, no strong preference. 
___
*[pkg/spanconfig/spanconfig.go, line 369 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxjgmCy3sADTrzx58DR:-MxjgmCy3sADTrzx58DS:bhxepl4) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d6c270c79efd53f7d91dd1b6e2ef11d9e3c7867/pkg/spanconfig/spanconfig.go#L369)):*
> ```Go
> 	record, err := MakeRecord(target, roachpb.SpanConfig{}) // delete
> 	if err != nil {
> 		log.Fatalf(context.Background(), "%+v", err)
> ```

I don't think `context.Background()` is correct here is it? We should either thread in the context or panic here, it's pretty much the same effect. Alternatively, you could bubble up the error. 

We should be a consistent in how we handle these `MakeRecord` errors though -- if we're okay crashing the node here, then let's just do it in the constructor to `MakeRecord` as well. If we're not, then let's bubble up the error here as well.

**Review by adityamaru — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77349)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru and @arulajmani)

___
*[pkg/spanconfig/spanconfig.go, line 289 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxPsBhJ6GEh7AqM93ui:-MxoqADiBubm5ZOzA0Hi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/adbe7ba95bdebb19829845ed2262b2e876ad1d51/pkg/spanconfig/spanconfig.go#L289)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

The line this comment was referencing has moved, but were hoping to do this? 
</blockquote></details>

Done.
___
*[pkg/spanconfig/spanconfig.go, line 369 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-MxjgmCy3sADTrzx58DR:-MxnqpKp-V5JGTTwXvkj:b-mtt45t) ([raw file](https://github.com/cockroachdb/cockroach/blob/5d6c270c79efd53f7d91dd1b6e2ef11d9e3c7867/pkg/spanconfig/spanconfig.go#L369)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

I don't think `context.Background()` is correct here is it? We should either thread in the context or panic here, it's pretty much the same effect. Alternatively, you could bubble up the error. 

We should be a consistent in how we handle these `MakeRecord` errors though -- if we're okay crashing the node here, then let's just do it in the constructor to `MakeRecord` as well. If we're not, then let's bubble up the error here as well. 
</blockquote></details>

agreed, switched to bubble up the error.

**Review by arulajmani — APPROVED** [review]
:shipit: 

> Reviewed 9 of 10 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77349#-:-MxpNFhF9kGLUcWAQZYB:bizlbj6)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @adityamaru)

**Comment by adityamaru** [comment]
Looks like a bazel flake. 

TFTR!

bors r=arulajmani

**Comment by adityamaru** [comment]
bors r=arulajmani

**Comment by adityamaru** [comment]
bors r=arulajmani

**Comment by adityamaru** [comment]
🤷 unsure whatsup, will try to bors in a bit.

**Comment by adityamaru** [comment]
bors r=arulajmani

**Comment by adityamaru** [comment]
bors r=arulajmani

**Pull request merged**
