### PR TITLE
retry.{Abort,Succeed}

### PR DESCRIPTION
**Pull request by tamird**
Builds on #1359.

### CODE REVIEW

**Comment by BramGruneir** [comment]
Why *flunk* and not *fail*, which is a proper antonym of Succeed?

**Comment by tamird** [comment]
I opted for the greater greppability, but I'd be ok with changing it before merging.

**Comment by BramGruneir** [comment]
I'd prefer fail.  Seems more accurate and it won't confuse people who don't understand english very well.

**Comment by bdarnell** [comment]
I also prefer `Fail` to `Flunk`. I'd also be OK with `Abort` to make it sound more "final" (since `Continue` and `Reset` are failures of a sort).

LGTM

**Comment by tamird** [comment]
Changed to `Abort`.

**Comment by petermattis** [comment]
I find the `retry.WithBackoff` structure difficult to read regardless the naming of the `retry.Status` return values. I've wanted to try reworking the retry stuff so that it can be used in a normal for-loop:

```
  for r := retry.Init(retryOpts); !r.Done(); r.Next() {
    // If the retryable operation succeeds you can use a normal "break" or "return" 
    // to exit the loop. A r.Reset() method could reset the backoff.
  }
```

**Comment by tamird** [comment]
I like that. Let me see about implementing it.

**Comment by tamird** [comment]
How about https://github.com/cenkalti/backoff?

**Comment by petermattis** [comment]
`ExponentialBackoff` looks interesting. The `backoff.Retry` function looks similar to `retry.WithBackoff` with all my existing reservations about readability.

**Comment by tamird** [comment]
Yeah, I think probably https://godoc.org/github.com/cenkalti/backoff#Ticker is the more useful facility.

**Comment by petermattis** [comment]
This doesn't sound good:

```
Ticks will continue to arrive when the previous operation is still running, so operations that take a while to fail could run in quick succession.
```

**Comment by tamird** [comment]
Ergh. OK, I'm going to see about wrapping their `Backoff` interface with some custom stuff.

**Comment by tamird** [comment]
Seems like we've excluded this approach.

**Pull request closed without merging**
