### PR TITLE
develop->master (end of split)

### PR DESCRIPTION
**Pull request by tbg**
Only two conflicts in GLOCKFILE (runc and x/tools); resolved by preferring
master's version.

`git diff origin/master -- GLOCKFILE` (does not contain the conflict resolution since that was taken off of master).

``` diff
diff --git a/GLOCKFILE b/GLOCKFILE
index 6a1851a..6c0d2c7 100644
--- a/GLOCKFILE
+++ b/GLOCKFILE
@@ -21,20 +21,20 @@ cmd golang.org/x/tools/cmd/stringer
 cmd honnef.co/go/simple/cmd/gosimple
 cmd honnef.co/go/staticcheck/cmd/staticcheck
 cmd honnef.co/go/unused/cmd/unused
-cloud.google.com/go 9696460acdaa8a7b2505fa6230ac54b4e97a9961
+cloud.google.com/go b6b89b673b4cb9a472803466ee4ccd1fee6acfbd
 github.com/Azure/go-ansiterm fa152c58bc15761d0200cb75fe958b89a9d4888e
 github.com/Microsoft/go-winio ce2922f643c8fd76b46cadc7f404a06282678b34
 github.com/Sirupsen/logrus 08a8a7c27e3d058a8989316a850daad1c10bf4ab
-github.com/StackExchange/wmi 771c736650b4aabf956d9103ba5bf439414f79f9
+github.com/StackExchange/wmi e54cbda6595d7293a7a468ccf9525f6bc8887f99
 github.com/VividCortex/ewma 8b9f1311551e712ea8a06b494238b8a2351e1c33
 github.com/agtorre/gocolorize f42b554bf7f006936130c9bb4f971afd2d87f671
-github.com/backtrace-labs/go-bcd c5383e2df7004f8b2fb2f10a33167d757bb0fbfb
+github.com/backtrace-labs/go-bcd 84eadf5656a924e6d2e1851ee22dd7d21a01cc4b
 github.com/biogo/store 913427a1d5e89604e50ea1db0f28f34966d61602
 github.com/cenk/backoff cdf48bbc1eb78d1349cbda326a4a037f7ba565c6
 github.com/chzyer/logex 96a4d311aa9ba1c5f9f2abda8039671de20f6aa5
-github.com/chzyer/readline a193146c91dea4b6cf30f355e99fb85f73d20f07
+github.com/chzyer/readline 283f5429f7723ac628cb68a44a11097c11a7a9c1
 github.com/chzyer/test bea8f082b6fd8382588bf6fdc6af9217078af151
-github.com/client9/misspell dcb75ecbeec8f85e28b639c3a2f5b4c8a7b8a888
+github.com/client9/misspell 88a1370162d5afbe6e2f40f8f0172e0ebd9cda40
 github.com/cockroachdb/c-jemalloc 42e6a32cd7a4dff9c70d80323681d46d046181ef
 github.com/cockroachdb/c-protobuf 951f3e665896e7ba939fd1f2db9aeaae6ca988f8
 github.com/cockroachdb/c-rocksdb b5ca031b93fde49bfa2ba99aba423136aebf3c06
@@ -47,27 +47,26 @@ github.com/cockroachdb/yacc 7c99dfd2164a5d23c3f495ffc2e0b72b6379d066
 github.com/codahale/hdrhistogram f8ad88b59a584afeee9d334eff879b104439117b
 github.com/coreos/etcd 143e2f27fc20f0cf5c29ad432b7526ef5adc9899
 github.com/cpuguy83/go-md2man 2724a9c9051aa62e9cca11304e7dd518e9e41599
-github.com/davecgh/go-spew 5215b55f46b2b919f50a1df0eaa5886afe4e3b3d
-github.com/docker/distribution c9fd26e9efe2c7405d7072ad181844275977b5e3
+github.com/davecgh/go-spew 6cf5744a041a0022271cefed95ba843f6d87fd51
+github.com/docker/distribution c810308d1bf3051521dd63cc1cdda03be9f11327
 github.com/docker/docker 7baa09faa02ad93dcb0e103abde3c45862fc903c
 github.com/docker/go-connections 0bad1a3951398f88ef4dd75fdb42af374430be89
 github.com/docker/go-units eb879ae3e2b84e2a142af415b679ddeda47ec71c
 github.com/dustin/go-humanize 2fcb5204cdc65b4bec9fd0a87606bb0d0e3c54e8
 github.com/elastic/gosigar 7c0ce0d4814c8d4950d7e7f40ed3b6359e757875
-github.com/elazarl/go-bindata-assetfs e1a2a7ec64b07d04ac9ebb072404fe8b7b60de1b
+github.com/elazarl/go-bindata-assetfs 9a6736ed45b44bf3835afeebb3034b57ed329f3e
 github.com/facebookgo/clock 600d898af40aa09a7a93ecb9265d87b0504b6f03
 github.com/go-ole/go-ole 7dfdcf409020452e29b4babcbb22f984d2aa308a
 github.com/go-sql-driver/mysql 0b58b37b664c21f3010e836f1b931e1d0b0b0685
 github.com/gogo/protobuf a4cceea7a401a73fefafd1a21fedbd4694124a82
 github.com/golang/glog 23def4e6c14b4da8ac2ed8007337bc5eb5007998
 github.com/golang/lint c7bacac2b21ca01afa1dee0acf64df3ce047c28f
-github.com/golang/protobuf 2c1988e8c18d14b142c0b472624f71647cf39adb
+github.com/golang/protobuf 7390af9dcd3c33042ebaf2474a1724a83cf1a7e6
 github.com/google/btree 7d79101e329e5a3adf994758c578dab82b90c017
 github.com/gordonklaus/ineffassign cb7fbaf18166b1f12a02c381e89ab5ce538a02ec
-github.com/grpc-ecosystem/grpc-gateway ccd4e6b091a44f9f6b32848ffc63b3e8f8e26092
+github.com/grpc-ecosystem/grpc-gateway 5e0e028ba0a015710eaebf6e47af18812c9f2767
 github.com/inconshreveable/mousetrap 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75
 github.com/jteeuwen/go-bindata a0ff2567cfb70903282db057e799fd826784d41d
-github.com/julienschmidt/httprouter d8ff598a019f2c7bad0980917a588193cf26666e
 github.com/kisielk/errcheck 50ffcb6f3595daac70aff9e63afe8b8b277b1a1a
 github.com/kisielk/gotool 94d5dba705240ba73ce5d65d83ce44adc749b440
 github.com/kkaneda/returncheck bf081fa7155e3a27df1f056a49d50685edfa5b1b
@@ -101,12 +100,12 @@ github.com/sasha-s/go-deadlock 09aefc0ac06ad74d91ca31acdb11fc981c159149
 github.com/satori/go.uuid 0aa62d5ddceb50dbcb909d790b5345affd3669b6
 github.com/shurcooL/sanitized_anchor_name 10ef21a441db47d8b13ebcc5fd2310f636973c77
 github.com/spf13/cobra 7c674d9e72017ed25f6d2b5e497a1368086b6a6f
-github.com/spf13/pflag f676131e2660dc8cd88de99f7486d34aa8172635
+github.com/spf13/pflag 4f9190456aed1c2113ca51ea9b89219747458dc1
 github.com/stretchr/testify d77da356e56a7428ad25149ca77381849a6a5232
 github.com/tebeka/go2xunit cb8eb3dedfac9cf4cb1f2d8988f3390f2d0cf2e7
 github.com/termie/go-shutil bcacb06fecaeec8dc42af03c87c6949f4a05c74c
 github.com/wadey/gocovmerge b5bfa59ec0adc420475f97f89b58045c721d761c
-golang.org/x/crypto a548aac93ed489257b9d959b40fe1e8c1e20778c
+golang.org/x/crypto 1ce41b6ca7dccc03377edf55652ffa334b6c06ce
 golang.org/x/net 07b51741c1d6423d4a6abab1c49940ec09cb1aaf
 golang.org/x/oauth2 4784bb855e56a530f1ce5d788959359ed6cb4a16
 golang.org/x/sys a646d33e2ee3172a661fc09bca23bb4889a41bc8
@@ -116,7 +115,7 @@ google.golang.org/appengine e951d3868b377b14f4e60efa3a301532ee3c1ebf
 google.golang.org/grpc 79b7c349179cdd6efd8bac4a1ce7f01b98c16e9b
 gopkg.in/check.v1 4f90aeace3a26ad7021961c297b22c42160c7b25
 gopkg.in/inf.v0 3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4
-gopkg.in/yaml.v1 9f9df34309c04878acc86042b16630b0f696e1de
+gopkg.in/yaml.v2 e4d366fc3c7938e2958e662b4258c7a89e1f0e3e
 honnef.co/go/lint a730e73f0085f274d67b586a1d587fd6e42e6708
 honnef.co/go/simple aa6f9e72ec86009fdfc110b52e2c769d48d5a904
 honnef.co/go/staticcheck 02337b3080e043d43781e1a0d129df14848f9507
```

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9672)

### CODE REVIEW

**Comment by tamird** [comment]
LGTM and praise the lord

**Comment by tschottdorf** [comment]
👍 

for posterity, here is the actual conflict:

```diff
diff --git a/GLOCKFILE b/GLOCKFILE
index 6a1851a..f2d1077 100644
--- a/GLOCKFILE
+++ b/GLOCKFILE
@@ -21,20 +21,20 @@ cmd golang.org/x/tools/cmd/stringer
 cmd honnef.co/go/simple/cmd/gosimple
 cmd honnef.co/go/staticcheck/cmd/staticcheck
 cmd honnef.co/go/unused/cmd/unused
-cloud.google.com/go 9696460acdaa8a7b2505fa6230ac54b4e97a9961
+cloud.google.com/go b6b89b673b4cb9a472803466ee4ccd1fee6acfbd
 github.com/Azure/go-ansiterm fa152c58bc15761d0200cb75fe958b89a9d4888e
 github.com/Microsoft/go-winio ce2922f643c8fd76b46cadc7f404a06282678b34
 github.com/Sirupsen/logrus 08a8a7c27e3d058a8989316a850daad1c10bf4ab
-github.com/StackExchange/wmi 771c736650b4aabf956d9103ba5bf439414f79f9
+github.com/StackExchange/wmi e54cbda6595d7293a7a468ccf9525f6bc8887f99
 github.com/VividCortex/ewma 8b9f1311551e712ea8a06b494238b8a2351e1c33
 github.com/agtorre/gocolorize f42b554bf7f006936130c9bb4f971afd2d87f671
-github.com/backtrace-labs/go-bcd c5383e2df7004f8b2fb2f10a33167d757bb0fbfb
+github.com/backtrace-labs/go-bcd 84eadf5656a924e6d2e1851ee22dd7d21a01cc4b
 github.com/biogo/store 913427a1d5e89604e50ea1db0f28f34966d61602
 github.com/cenk/backoff cdf48bbc1eb78d1349cbda326a4a037f7ba565c6
 github.com/chzyer/logex 96a4d311aa9ba1c5f9f2abda8039671de20f6aa5
-github.com/chzyer/readline a193146c91dea4b6cf30f355e99fb85f73d20f07
+github.com/chzyer/readline 283f5429f7723ac628cb68a44a11097c11a7a9c1
 github.com/chzyer/test bea8f082b6fd8382588bf6fdc6af9217078af151
-github.com/client9/misspell dcb75ecbeec8f85e28b639c3a2f5b4c8a7b8a888
+github.com/client9/misspell 88a1370162d5afbe6e2f40f8f0172e0ebd9cda40
 github.com/cockroachdb/c-jemalloc 42e6a32cd7a4dff9c70d80323681d46d046181ef
 github.com/cockroachdb/c-protobuf 951f3e665896e7ba939fd1f2db9aeaae6ca988f8
 github.com/cockroachdb/c-rocksdb b5ca031b93fde49bfa2ba99aba423136aebf3c06
@@ -47,27 +47,26 @@ github.com/cockroachdb/yacc 7c99dfd2164a5d23c3f495ffc2e0b72b6379d066
 github.com/codahale/hdrhistogram f8ad88b59a584afeee9d334eff879b104439117b
 github.com/coreos/etcd 143e2f27fc20f0cf5c29ad432b7526ef5adc9899
 github.com/cpuguy83/go-md2man 2724a9c9051aa62e9cca11304e7dd518e9e41599
-github.com/davecgh/go-spew 5215b55f46b2b919f50a1df0eaa5886afe4e3b3d
-github.com/docker/distribution c9fd26e9efe2c7405d7072ad181844275977b5e3
+github.com/davecgh/go-spew 6cf5744a041a0022271cefed95ba843f6d87fd51
+github.com/docker/distribution c810308d1bf3051521dd63cc1cdda03be9f11327
 github.com/docker/docker 7baa09faa02ad93dcb0e103abde3c45862fc903c
 github.com/docker/go-connections 0bad1a3951398f88ef4dd75fdb42af374430be89
 github.com/docker/go-units eb879ae3e2b84e2a142af415b679ddeda47ec71c
 github.com/dustin/go-humanize 2fcb5204cdc65b4bec9fd0a87606bb0d0e3c54e8
 github.com/elastic/gosigar 7c0ce0d4814c8d4950d7e7f40ed3b6359e757875
-github.com/elazarl/go-bindata-assetfs e1a2a7ec64b07d04ac9ebb072404fe8b7b60de1b
+github.com/elazarl/go-bindata-assetfs 9a6736ed45b44bf3835afeebb3034b57ed329f3e
 github.com/facebookgo/clock 600d898af40aa09a7a93ecb9265d87b0504b6f03
 github.com/go-ole/go-ole 7dfdcf409020452e29b4babcbb22f984d2aa308a
 github.com/go-sql-driver/mysql 0b58b37b664c21f3010e836f1b931e1d0b0b0685
 github.com/gogo/protobuf a4cceea7a401a73fefafd1a21fedbd4694124a82
 github.com/golang/glog 23def4e6c14b4da8ac2ed8007337bc5eb5007998
 github.com/golang/lint c7bacac2b21ca01afa1dee0acf64df3ce047c28f
-github.com/golang/protobuf 2c1988e8c18d14b142c0b472624f71647cf39adb
+github.com/golang/protobuf 7390af9dcd3c33042ebaf2474a1724a83cf1a7e6
 github.com/google/btree 7d79101e329e5a3adf994758c578dab82b90c017
 github.com/gordonklaus/ineffassign cb7fbaf18166b1f12a02c381e89ab5ce538a02ec
-github.com/grpc-ecosystem/grpc-gateway ccd4e6b091a44f9f6b32848ffc63b3e8f8e26092
+github.com/grpc-ecosystem/grpc-gateway 5e0e028ba0a015710eaebf6e47af18812c9f2767
 github.com/inconshreveable/mousetrap 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75
 github.com/jteeuwen/go-bindata a0ff2567cfb70903282db057e799fd826784d41d
-github.com/julienschmidt/httprouter d8ff598a019f2c7bad0980917a588193cf26666e
 github.com/kisielk/errcheck 50ffcb6f3595daac70aff9e63afe8b8b277b1a1a
 github.com/kisielk/gotool 94d5dba705240ba73ce5d65d83ce44adc749b440
 github.com/kkaneda/returncheck bf081fa7155e3a27df1f056a49d50685edfa5b1b
@@ -83,7 +82,7 @@ github.com/mdempsky/unconvert beb68d938016d2dec1d1b078054f4d3db25f97be
 github.com/mibk/dupl 415e882ea21ca7012cc49906cb338f34d2d4b4d6
 github.com/montanaflynn/stats 60dcacf48f43d6dd654d0ed94120ff5806c5ca5c
 github.com/olekukonko/tablewriter daf2955e742cf123959884fdff4685aa79b63135
-github.com/opencontainers/runc ae7a92e352116f38bce3f7cb3aa2bc590a7e3f65
+github.com/opencontainers/runc 12c3d17017f5e50baed65aa4543d7a2771e6afc8
 github.com/opennota/check 5b00aacd5639507d2b039245a278ec9f5505509f
 github.com/opentracing/basictracer-go 1b32af207119a14b1b231d451df3ed04a72efebf
 github.com/opentracing/opentracing-go 30dda9350627161ff15581c0bdc504e32ec9a536
@@ -101,22 +100,30 @@ github.com/sasha-s/go-deadlock 09aefc0ac06ad74d91ca31acdb11fc981c159149
 github.com/satori/go.uuid 0aa62d5ddceb50dbcb909d790b5345affd3669b6
 github.com/shurcooL/sanitized_anchor_name 10ef21a441db47d8b13ebcc5fd2310f636973c77
 github.com/spf13/cobra 7c674d9e72017ed25f6d2b5e497a1368086b6a6f
-github.com/spf13/pflag f676131e2660dc8cd88de99f7486d34aa8172635
+github.com/spf13/pflag 4f9190456aed1c2113ca51ea9b89219747458dc1
 github.com/stretchr/testify d77da356e56a7428ad25149ca77381849a6a5232
 github.com/tebeka/go2xunit cb8eb3dedfac9cf4cb1f2d8988f3390f2d0cf2e7
 github.com/termie/go-shutil bcacb06fecaeec8dc42af03c87c6949f4a05c74c
 github.com/wadey/gocovmerge b5bfa59ec0adc420475f97f89b58045c721d761c
-golang.org/x/crypto a548aac93ed489257b9d959b40fe1e8c1e20778c
+golang.org/x/crypto 1ce41b6ca7dccc03377edf55652ffa334b6c06ce
 golang.org/x/net 07b51741c1d6423d4a6abab1c49940ec09cb1aaf
 golang.org/x/oauth2 4784bb855e56a530f1ce5d788959359ed6cb4a16
 golang.org/x/sys a646d33e2ee3172a661fc09bca23bb4889a41bc8
+<<<<<<< HEAD
 golang.org/x/text 2910a502d2bf9e43193af9d68ca516529614eed3
 golang.org/x/tools fc2b74b64ef08c618146ebc92062f6499db5314c
+||||||| merged common ancestors
+golang.org/x/text 2910a502d2bf9e43193af9d68ca516529614eed3
+golang.org/x/tools 0e9f43fcb67267967af8c15d7dc54b373e341d20
+=======
+golang.org/x/text d69c40b4be55797923cec7457fac7a244d91a9b6
+golang.org/x/tools 08b1e0510c4cfc628a52f0ce641d027b4b2cebe0
+>>>>>>> origin/develop
 google.golang.org/appengine e951d3868b377b14f4e60efa3a301532ee3c1ebf
 google.golang.org/grpc 79b7c349179cdd6efd8bac4a1ce7f01b98c16e9b
 gopkg.in/check.v1 4f90aeace3a26ad7021961c297b22c42160c7b25
 gopkg.in/inf.v0 3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4
-gopkg.in/yaml.v1 9f9df34309c04878acc86042b16630b0f696e1de
+gopkg.in/yaml.v2 e4d366fc3c7938e2958e662b4258c7a89e1f0e3e
 honnef.co/go/lint a730e73f0085f274d67b586a1d587fd6e42e6708
 honnef.co/go/simple aa6f9e72ec86009fdfc110b52e2c769d48d5a904
 honnef.co/go/staticcheck 02337b3080e043d43781e1a0d129df14848f9507
```

**Comment by tschottdorf** [comment]
Checklist:

- [ ] audit dependencies - @tamird
- [ ] change default branch - @tschottdorf 
- [ ] compile merge queue for waiting PRs - @petermattis 

Teamcity should work out of the box.

**Comment by tamird** [comment]
Should also turn on branch protection for `develop` -- it should no longer be possible to merge to it at all.

**Pull request merged**
