### PR TITLE
release-24.2: sql: SHOW CREATE now uses two-part names for composite types

### PR DESCRIPTION
**Pull request by spilchen**
Backport 1/1 commits from #127158.

/cc @cockroachdb/release

---

This change formats composite types as two- or three-part names, depending on the context, in places that output the name, such as SHOW CREATE TABLES. Previously, composite types were only displayed with a one-part name, which could cause ambiguity, especially if a table had two types with the same name but in different schemas. The new rules for formatting composite types are the same as those implemented for enum types.

Closes: #125934
Release note (bug fix): Fixed a bug related to displaying the names of composite types in the SHOW CREATE TABLES command. The names are now shown as two-part names, which disambiguates the output and makes it more portable to other databases.

### CODE REVIEW

**Comment by spilchen** [comment]
Closing this off. I won't include in 24.2 because they are only accepting release blockers.

**Comment by michae2** [comment]
> Closing this off. I won't include in 24.2 because they are only accepting release blockers.

@spilchen now that we're out of stability period for 24.2, would it be worth re-opening this backport?

**Comment by spilchen** [comment]
Yes, I think we can try this again. Let me open a fresh PR.

**Comment by spilchen** [comment]
New PR for this is #137768

**Pull request closed without merging**
