### PR TITLE
storage: remove the limit on processing the same replica

### PR DESCRIPTION
**Pull request by darinpp**
There is currently a limit of processing the same replica three times
before the replication queue moves to processing the next replica.
This removes the limit so each replica is processed as many times
as needed before moving to the next one in the queue.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/37577#-:-LfQSb9Q0l2E9N6q-MWD:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

**Comment by tbg** [comment]
@darinpp could you do me a favor and, on a flake, take a look at what flaked and file an issue if appropriate? In this case it's `TestPlannerLogic/5node-dist/distsql_interleaved_join` which doesn't have an issue. I filed at https://github.com/cockroachdb/cockroach/issues/37698

**Comment by darinpp** [comment]
> @darinpp could you do me a favor and, on a flake, take a look at what flaked and file an issue if appropriate? In this case it's `TestPlannerLogic/5node-dist/distsql_interleaved_join` which doesn't have an issue. I filed at #37698

Yes. Will do.

**Pull request merged**
