### PR TITLE
stats,opt: performance improvements for histograms

### PR DESCRIPTION
**Pull request by rytaft**
**stats,opt: move histogram bucket distinct count estimation code**
    
This commit moves the code to estimate the number of distinct values
per histogram bucket out of the optimizer and into the stats package.
The purpose of doing this is to remove the overhead of calculating the
number of distinct values per bucket from the critical path of query
planning, and instead perform the calculation offline when initially
generating the histogram.

**opt: performance improvements for histograms**
    
This commit improves the performance of histograms in the optimizer
by avoiding allocating and copying the full histogram unless strictly
necessary. Additionally, it changes the code for filtering histograms
to use binary search instead of performing a linear scan.

----

As a result of both of these commits, the overhead of histograms is reduced. Prior to these changes, the overhead of histograms caused 14% lower throughput and 29% higher latency when running kv with 95% reads. After, it caused only 4.6% lower throughput and 11% higher latency. (Clearly there is still work to do, but this is some progress...)

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Nice changes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-:-Ll8HsRN74bV7naGg_ou:b-2hquxa)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 558 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll8GekN0PRpe4xJhpzV:-Ll8GekN0PRpe4xJhpzW:btiic8r) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/memo/statistics_builder.go#L558)):*
> ```Go
> 	colStat := sb.copyColStat(colSet, s, inputColStat)
> 	if inputColStat.Histogram != nil {
> 		if s.Selectivity != 1 || scan.HardLimit.IsSet() {
> ```

In the HardLimit case, we're not modifying the histogram AFAICT
___
*[pkg/sql/opt/memo/statistics_builder.go, line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll8GTSkEN4OaJd8y8NZ:-Ll8GTSkEN4OaJd8y8N_:b-w0xjy4) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/memo/statistics_builder.go#L567)):*
> ```Go
> 	}
> 
> 	if s.Selectivity != 1 {
> ```

[nit] would be a bit more clear if we moved these two inside the block above

**Review by justinj — COMMENTED** [review]
:lgtm: Do you have any benchmarks showing the improvement this PR gives?

> Reviewed 19 of 19 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-:-Ll85zn82CXOXvLLajk3:b8opprm)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/props/histogram.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll7yEqMEYxuMxaMTs-1:-Ll7yEqN3KeYN6EE3sFu:bd6x9en) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/props/histogram.go#L159)):*
> ```Go
> 		return 0, false
> 
> 	default:
> ```

would it ever be relevant to return `1` if `lowerBound=upperBound` or is this function never called like that?
___
*[pkg/sql/stats/histogram.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll7V8SD4bRR9TJqhzft:-Ll7V8SD4bRR9TJqhzfu:b3d79ym) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e29ebe7c2b0eab104894a603623bd7c23505532/pkg/sql/stats/histogram.go#L90)):*
> ```Go
> 				break
> 			} else if c > 0 {
> 				panic("samples not sorted")
> ```

nit/not actually a part of this change, but should this be an `AssertionFailedf`?
___
*[pkg/sql/stats/histogram.proto, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll7Wk4V7RQcR49SOg5y:-Ll7Wk4W96HJHfD8CEex:bpory1h) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e29ebe7c2b0eab104894a603623bd7c23505532/pkg/sql/stats/histogram.proto#L42)):*
> ```protobuf
>     // value because it is estimated by distributing the known distinct
>     // count for the column among the buckets, in proportion to the number
>     // of rows in each bucket.
> ```

nit: consider mentioning that this value is in fact derived from the rest of the data, but is included to avoid re-computing it later?

**Review by rytaft — COMMENTED** [review]
TFTRs!

> Do you have any benchmarks showing the improvement this PR gives?

The PR message has some perf numbers - is that not what you had in mind?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-:-Ll8Rtum8lhDlPS5oJh2:b-cj87ms)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 558 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll8GekN0PRpe4xJhpzV:-Ll8OOpaESJNV7xa4_8-:bzd82xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/memo/statistics_builder.go#L558)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

In the HardLimit case, we're not modifying the histogram AFAICT
</blockquote></details>

We actually might be, in `finalizeFromRowCount`. But I realized that we already account for the limit with cardinality, so I removed the check for the hard limit below -- all will be updated if needed in `finalizeFromRowCount`. 
___
*[pkg/sql/opt/memo/statistics_builder.go, line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll8GTSkEN4OaJd8y8NZ:-Ll8L50U1aX3ewebKVPe:b5ke5uc) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/memo/statistics_builder.go#L567)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] would be a bit more clear if we moved these two inside the block above
</blockquote></details>

How? We still want to execute this block even if the histogram is nil.
___
*[pkg/sql/opt/props/histogram.go, line 159 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll7yEqMEYxuMxaMTs-1:-Ll8OyxyAhxIu-2ND7q0:b-9stvsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/props/histogram.go#L159)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

would it ever be relevant to return `1` if `lowerBound=upperBound` or is this function never called like that?
</blockquote></details>

No, because the `upperBound` is exclusive. So in that case we still want to return 0.
___
*[pkg/sql/stats/histogram.go, line 90 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll7V8SD4bRR9TJqhzft:-Ll8PFFr27VcNgAYTtoU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e29ebe7c2b0eab104894a603623bd7c23505532/pkg/sql/stats/histogram.go#L90)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit/not actually a part of this change, but should this be an `AssertionFailedf`?
</blockquote></details>

Done.
___
*[pkg/sql/stats/histogram.proto, line 42 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll7Wk4V7RQcR49SOg5y:-Ll8QMXA7BgZzVeGEGJ2:bs7wumb) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e29ebe7c2b0eab104894a603623bd7c23505532/pkg/sql/stats/histogram.proto#L42)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

nit: consider mentioning that this value is in fact derived from the rest of the data, but is included to avoid re-computing it later?
</blockquote></details>

Done.

**Comment by justinj** [comment]
Ah nice! I missed that—I only looked at the commit messages in reviewable

**Review by RaduBerinde — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 558 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll8GekN0PRpe4xJhpzV:-Ll8XqJO1PlXDz-QbK3B:b1pn2ga) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/memo/statistics_builder.go#L558)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

We actually might be, in `finalizeFromRowCount`. But I realized that we already account for the limit with cardinality, so I removed the check for the hard limit below -- all will be updated if needed in `finalizeFromRowCount`. 
</blockquote></details>

I see. This seems fragile; the condition here has to match what `finalizeFromRowCount` is doing. I don't have a good solution though.. perhaps move the condition inside a `canFinalizeFromRowCountModifyHistogram` helper (and put that next to `finalizeFromRowCount`), and assert that it returns true when we modify the histogram (inside `finalizeFromRowCount`).
___
*[pkg/sql/opt/memo/statistics_builder.go, line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll8GTSkEN4OaJd8y8NZ:-Ll8YnXGBl_m4y4DkFdx:bo8yt0m) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/memo/statistics_builder.go#L567)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

How? We still want to execute this block even if the histogram is nil.
</blockquote></details>

The block could be
```
colStat.Histogram = inputColStat.Histogram
if <need copy> {
  colStat.Histogram = colStat.Histogram.Copy()
  ...
}
```
But I didn't realize `finalizeFromRowCount` plays a role, so this doesn't help much.

**Review by rytaft — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39178)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj and @RaduBerinde)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 558 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll8GekN0PRpe4xJhpzV:-LlCMNp568OVkaKUJDP5:b-9sm4vd) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/memo/statistics_builder.go#L558)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I see. This seems fragile; the condition here has to match what `finalizeFromRowCount` is doing. I don't have a good solution though.. perhaps move the condition inside a `canFinalizeFromRowCountModifyHistogram` helper (and put that next to `finalizeFromRowCount`), and assert that it returns true when we modify the histogram (inside `finalizeFromRowCount`).
</blockquote></details>

Thinking about this more, I think it would be much cleaner if histograms are immutable. `Histogram.Filter` already returns a new histogram without changing the original, so I changed `Histogram.ApplySelectivity` to do the same thing. There are cases where this may cause a histogram to get copied twice (e.g., a scan that is both constrained and limited), but in the general case I think this makes everything much cleaner and more efficient, and will save us a lot of headaches down the road. Let me know what you think.
___
*[pkg/sql/opt/memo/statistics_builder.go, line 567 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll8GTSkEN4OaJd8y8NZ:-LlCNMW-3B_tIuJGi4-0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/memo/statistics_builder.go#L567)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

The block could be
```
colStat.Histogram = inputColStat.Histogram
if <need copy> {
  colStat.Histogram = colStat.Histogram.Copy()
  ...
}
```
But I didn't realize `finalizeFromRowCount` plays a role, so this doesn't help much.
</blockquote></details>

Done.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-:-LlCQICX3cMJhS8rUbye:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @justinj and @rytaft)

___
*[pkg/sql/opt/memo/statistics_builder.go, line 558 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-Ll8GekN0PRpe4xJhpzV:-LlCQARg0HBPz_W9iMez:b-wv63gy) ([raw file](https://github.com/cockroachdb/cockroach/blob/80b804d5b621a1b4b967832032860e5ee0019d07/pkg/sql/opt/memo/statistics_builder.go#L558)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Thinking about this more, I think it would be much cleaner if histograms are immutable. `Histogram.Filter` already returns a new histogram without changing the original, so I changed `Histogram.ApplySelectivity` to do the same thing. There are cases where this may cause a histogram to get copied twice (e.g., a scan that is both constrained and limited), but in the general case I think this makes everything much cleaner and more efficient, and will save us a lot of headaches down the road. Let me know what you think.
</blockquote></details>

Awesome, sounds great to me.

**Review by rytaft — COMMENTED** [review]
Thanks!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39178#-:-LlCelNv7VRFzIiEgDSR:b-voiyyw)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @justinj)

**Pull request merged**
