### PR TITLE
sql: use IndexFetchSpec for zigzag join

### PR DESCRIPTION
**Pull request by RaduBerinde**
#### rowexec: follow-up cleanup for EncodedKey in zigzagjoiner

The zig-zag joiner code still uses `Bytes` instead of `EncodedKey` for
the encoded key. This works because the fixed values are encoded using
VALUE encoding, and the value encodings are the same for `DBytes` and
`DEncodedKey`.

This commit updates the zigzag joiner to use the correct `EncodedKey`
type.  The code no longer needs to special case inverted indexes -
with the addition of support for `EncodedKey` in `keyside.Encode`, the
general code path can now be used.

Release note: None

#### sql: clean up ZigZagJoinerSpec

This change cleans up the zig-zag joiner spec: we move the per-side
information into a Side sub-message and use a list of Sides instead of
many parallel lists. Other misc cleanup in the zigzag joiner code is
included.

Release note: None

#### sql: use IndexFetchSpec for zigzag join

This commit changes the zigzag joiner to use IndexFetchSpec for the
two sides instead of table and index descriptors. The internal schema
of the zigzag joiner is changed to match the fetched columns,
simplifying the execution code.

This change necessitates fixes on the planning side - we weren't
determining the necessary scan columns correctly (this wasn't a
problem when the internal schema had all table columns and we were
relying on the execution layer to figure out what is needed).

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
Very nice cleanup! :lgtm:

> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 27 of 27 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78295#-:-MyocTYE3q0ugeRL6AKI:b-g85lzj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @RaduBerinde)

___
*[pkg/sql/rowexec/zigzagjoiner_test.go, line 232 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78295#-MyobtWVAUcxHQABqL4K:-MyobtWW3Av9NsCBUrBU:b-nbqvdl) ([raw file](https://github.com/cockroachdb/cockroach/blob/772e76cd368435883ee35ba7a3751132fbf9dfa7/pkg/sql/rowexec/zigzagjoiner_test.go#L232)):*
> ```Go
> 					},
> 					{
> 						FetchSpec: makeFetchSpec(t, empty, "d", "a,b,d"),
> ```

This should be `highRangeDesc`.
___
*[pkg/sql/rowexec/zigzagjoiner_test.go, line 248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78295#-Myobwif4BAAAiJIpFtt:-Myobwif4BAAAiJIpFtu:b-xscho) ([raw file](https://github.com/cockroachdb/cockroach/blob/772e76cd368435883ee35ba7a3751132fbf9dfa7/pkg/sql/rowexec/zigzagjoiner_test.go#L248)):*
> ```Go
> 				Sides: []execinfrapb.ZigzagJoinerSpec_Side{
> 					{
> 						FetchSpec: makeFetchSpec(t, empty, "c", "a,b,c"),
> ```

Here the order of `empty` and `highRangeDesc` is switched.

**Review by mgartner — APPROVED** [review]
:star_struck: :lgtm: 

> Reviewed 2 of 2 files at r1, 5 of 5 files at r2, 27 of 27 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78295#-:-Myr56Ff3kVKHEwtSP0V:bgpwjey)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by RaduBerinde — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/78295#-:-MysVNgR4EKsJZkXHr6V:bz5mair)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/rowexec/zigzagjoiner_test.go, line 232 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78295#-MyobtWVAUcxHQABqL4K:-MysTlYPCZPV6Er-ORzO:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/772e76cd368435883ee35ba7a3751132fbf9dfa7/pkg/sql/rowexec/zigzagjoiner_test.go#L232)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

This should be `highRangeDesc`.
</blockquote></details>

Done.
___
*[pkg/sql/rowexec/zigzagjoiner_test.go, line 248 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/78295#-Myobwif4BAAAiJIpFtt:-MysVHNLAT62VnrmD8GC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/772e76cd368435883ee35ba7a3751132fbf9dfa7/pkg/sql/rowexec/zigzagjoiner_test.go#L248)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Here the order of `empty` and `highRangeDesc` is switched.
</blockquote></details>

Done.

**Pull request merged**
