### PR TITLE
Fail more gracefully if gossiping fails to initialize due to lack of peers.

### PR DESCRIPTION
**Pull request by knz**
Proposed fix for issue #3963

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/3964)

### CODE REVIEW

**Comment by bdarnell** [comment]
I don't think we should add a new logging type; among other things it is handled inconsistently from other similar errors like the one you get if you pass an empty value for `--stores` (I'm not saying that behavior is ideal, but we should have it all in one place). 

We should instead move towards returning an error back up the stack so the `cli` package can handle it.

**Comment by knz** [comment]
Ok I have adapted the fix, no need for a new error interface.

**Comment by bdarnell** [comment]
LGTM, although the error message could be more human-friendly. We generally prefer `fmt.Errorf` to `util.Errorf` for errors that we expect to be exposed to end users (so it doesn't include a filename/line number), and mentioning "gossip persistence" is confusing.

**Comment by knz** [comment]
Ok changed the message to "gossip interface" and dropped the file/lineno references.

**Comment by bdarnell** [comment]
LGTM

**Pull request merged**
