### PR TITLE
rowexec: improve mem accounting in the join reader

### PR DESCRIPTION
**Pull request by jordanlewis**
This commit separates out three memory usages in the join reader code
(the processor itself, the join reader strategy, and the span generator)
by introducing additional memory accounts. This allows us to use
`ResizeTo` method and get the memory usage once, instead of twice.

Additionally, it refactors the way the memory accounting is done in the
join reader - we now update the memory account before each row is copied
rather than in bulk, after all rows have been copied. It also deeply
resets the scratch rows space as well as nils out some things eagerly.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
@yuzefovich I'm going to close this in a bit as I'm losing context. I was hoping you could take a brief look to see if there is anything that is worth preserving.

**Comment by yuzefovich** [comment]
I also removed most changes to the memory accounting logic in the join reader because I think they were incorrect - `jr.memAcc` is shared between the join reader itself and the span generator, so we cannot use `ResizeTo` when working with the memory account. I kept the changes about nilling some things out eagerly which seem good.

**Review by yuzefovich — COMMENTED** [review]
Alright, I think I extracted all of the ideas from Jordan's work and expanded them a bit, and it is RFAL.

> Reviewed 1 of 5 files at r1, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68044#-:-MllzDu_CPY676Js6Gd1:b-ba3r2b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @cucaroach, @rytaft, and @yuzefovich)

**Review by cucaroach — APPROVED** [review]
:LGTM:

> Reviewed 1 of 5 files at r1, 4 of 5 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/68044#-:-Mloixfn7AXG5bD9225b:bmxilld)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rytaft)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Pull request merged**
