### PR TITLE
migrations: add long-running migration for namespace table 

### LINKED ISSUE #60488: sql: implement the system.namespace migration as a long-running migration

### PR DESCRIPTION
**Pull request by thoszhang**
This PR adds a migration to copy all namespace entries from the old
namespace table (ID 2) to the new namespace table (ID 30). This
migration was previously implemented as an async task (see #49099 for
history and context) in 20.1, so there was no guarantee of it actually
being complete before any subsequent version upgrade.

This PR copies the preexisting implementation as much as possible into
the new migration framework. It also modifies the roachtest originally
written for that async "migration," which only ran in 20.1, to start a
cluster in 19.2 and upgrade all the way to 21.1. Finally, it removes the
async migration.

Closes #60488.

Release note: None

### CODE REVIEW

**Comment by lucy-zhang** [comment]
I preserved the existing checks where we skip the migration if the cluster was bootstrapped in 20.1 or later, or if the key indicating completion of the migration had been written to. But we could just skip these checks for simplicity.

I also debated including some test other than a roachtest (e.g., we could create a bunch of tables and then manually move some namespace entries to the old table), but I'm not sure if it's worth it.

**Comment by lucy-zhang** [comment]
I added a test. I also got rid of the checks for state indicating the migration would be unnecessary, so now we run it unconditionally. I reread our discussion from last year, and we'd sort of planned on doing it this way, to guarantee that we would always run this on the upgrade and not have to worry about whatever state we were previously in.

**Comment by lucy-zhang** [comment]
I don't know what to make of this:

```
I210219 05:25:49.423603 44596 migration/migrations/namespace_migration.go:60  [n1,job=634525939811549185,migration=20.2-36] 783  migrating system.namespace chunk
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784  MIGRATION job 634525939811549185: stepping through state reverting with error: running migration for 20.2-36: txn already encountered an error; cannot be used anymore (previous err: concurrent txn use detected. ba: Scan [/Table/2/1/0/"db0016"/3/1,/Table/2/2), [txn: 30a406bc])
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +(1) attached stack trace
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  -- stack trace:
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | github.com/cockroachdb/cockroach/pkg/migration/migrationjob.resumer.Resume
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/migration/migrationjob/migration_job.go:95
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine.func1
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1171
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).stepThroughStateMachine
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/registry.go:1172
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).runJob
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:250
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | github.com/cockroachdb/cockroach/pkg/jobs.(*Registry).resumeJob.func1
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/jobs/adopt.go:209
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | github.com/cockroachdb/cockroach/pkg/util/stop.(*Stopper).RunAsyncTask.func1
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | 	/go/src/github.com/cockroachdb/cockroach/pkg/util/stop/stopper.go:351
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | runtime.goexit
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +  | 	/usr/local/go/src/runtime/asm_amd64.s:1374
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +Wraps: (2) running migration for 20.2-36
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +Wraps: (3) txn already encountered an error; cannot be used anymore (previous err: concurrent txn use detected. ba: Scan [/Table/2/1/0/"db0016"/3/1,/Table/2/2), [txn: 30a406bc])
I210219 05:25:49.460239 44596 jobs/registry.go:1153  [n1] 784 +Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *roachpb.TxnAlreadyEncounteredErrorError
```

(https://teamcity.cockroachdb.com/viewLog.html?buildId=2693159&tab=buildResultsDiv&buildTypeId=Cockroach_UnitTests_Test)

The txn usage in the migration is not very interesting so I have no idea how we'd get a `concurrent txn use detected` error. Based on the scan it seems like it's probably coming from the internal executor query.

**Comment by lucy-zhang** [comment]
Oh, I guess it's unsafe to update the namespace tables while concurrently streaming result rows from that join. I'll fix it.

**Comment by lucy-zhang** [comment]
This should be ready for review.

**Review by ajwerner — APPROVED** [review]
:lgtm_strong: 

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60647#-:-MU9TRi08cnL4fuPreHS:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

**Comment by lucy-zhang** [comment]
I guess I should actually be using `QueryBufferedEx` from #60693, which would have required no changes to the existing implementation. But I'm not sure what the status of that is.

**Review by jordanlewis — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60647#-:-MUA8KG3AX37GG-sCsrC:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained

**Comment by lucy-zhang** [comment]
TFTRs

bors r+

**Pull request merged**
