### PR TITLE
roachtest: ignore unrelated tags when looking for build version

### PR DESCRIPTION
**Pull request by danhhz**
Release note: None

### CODE REVIEW

**Review by bdarnell — APPROVED** [review]
There's also a `git describe` command in the Makefile that we should fix at the same time.

**Review by benesch — APPROVED** [review]
Can you make the same changes here? 

* https://github.com/cockroachdb/cockroach/blob/94516a112c550fb6f2f531d83fe85dc2fc44a6a5/Makefile#L1007
* https://github.com/cockroachdb/cockroach/blob/94516a112c550fb6f2f531d83fe85dc2fc44a6a5/pkg/cmd/internal/issues/issues.go#L143
* https://github.com/cockroachdb/cockroach/blob/94516a112c550fb6f2f531d83fe85dc2fc44a6a5/scripts/release-notes.py#L722-L723
* https://github.com/cockroachdb/cockroach/blob/94516a112c550fb6f2f531d83fe85dc2fc44a6a5/build/teamcity-post-failures.py#L66

🙈

**Comment by danhhz** [comment]
Done. That's some nice grepping

**Review by benesch — APPROVED** [review]

**Comment by danhhz** [comment]
Thanks for the reviews!

bors r=bdarnell,benesch

**Pull request merged**
