### PR TITLE
security: disable permission checks on windows

### LINKED ISSUE #15058: security,cli: failing tests on Windows
These failures are fallout from the recent certificate work.

[cli.test.txt](https://github.com/cockroachdb/cockroach/files/930911/cli.test.txt)
[security.test.txt](https://github.com/cockroachdb/cockroach/files/930912/security.test.txt)

### PR DESCRIPTION
**Pull request by mberhault**
Fixes #15058

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/security/certificate_loader.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101#-Ki4TlzRnTvYQq9I-VHG:-Ki4TlzRnTvYQq9I-VHH:bcu8a0y) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f4ce3831568f75032c93131ee4fd243c2b33895/pkg/security/certificate_loader.go#L34)):*
> ```Go
> 
> func init() {
> 	if runtime.GOOS == "windows" {
> ```

Do we need to file an issue upstream? There is no justification AFAICT, and the behaviour has been the same since https://github.com/golang/go/commit/b07e4d95116.

Meanwhile, 0444 seems perfectly valid on my Windows VM:
```
tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ touch foobar

tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ ls -lah foobar
-rw-r--r-- 1 tamird None 0 Apr 19 09:11 foobar

tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ chmod 0444 foobar

tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ ls -lah foobar
-r--r--r-- 1 tamird None 0 Apr 19 09:11 foobar

tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ chmod 0666 foobar

tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ ls -lah foobar
-rw-r--r-- 1 tamird None 0 Apr 19 09:11 foobar
```

---

*[pkg/security/certificate_loader.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101#-Ki4UIbZ8JXE0PVrQHhQ:-Ki4UIbZ8JXE0PVrQHhR:bl45zt1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f4ce3831568f75032c93131ee4fd243c2b33895/pkg/security/certificate_loader.go#L40)):*
> ```Go
> 		skipPermissionChecks = true
> 	} else {
> 		skipPermissionChecks = envutil.EnvOrDefaultBool("COCKROACH_SKIP_KEY_PERMISSION_CHECK", true)
> ```

I don't think you meant to change this from `false` to `true`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101)*

**Comment by mberhault** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/security/certificate_loader.go, line 34 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101#-Ki4TlzRnTvYQq9I-VHG:-Ki4XVlwoEXPH2Vqg_id:b-w3wkje) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f4ce3831568f75032c93131ee4fd243c2b33895/pkg/security/certificate_loader.go#L34)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

Do we need to file an issue upstream? There is no justification AFAICT, and the behaviour has been the same since https://github.com/golang/go/commit/b07e4d95116.

Meanwhile, 0444 seems perfectly valid on my Windows VM:
```
tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ touch foobar

tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ ls -lah foobar
-rw-r--r-- 1 tamird None 0 Apr 19 09:11 foobar

tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ chmod 0444 foobar

tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ ls -lah foobar
-r--r--r-- 1 tamird None 0 Apr 19 09:11 foobar

tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ chmod 0666 foobar

tamird@tamird-build MINGW64 /c/Users/tamird/go/src/github.com/cockroachdb/cockroach
$ ls -lah foobar
-rw-r--r-- 1 tamird None 0 Apr 19 09:11 foobar
```
</blockquote></details>

my understanding of this stuff is that they're interpreting windows ACLs into ugo-type permissions, but there's still no equivalent unless you add extra data (I believe cygwin used to, but mingw doesn't). Either way, this is trivial to disable on our end, and deep inside the standard library. I can dig further and see if it makes sense to even file an issue upstream.

---

*[pkg/security/certificate_loader.go, line 40 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101#-Ki4UIbZ8JXE0PVrQHhQ:-Ki4W8rnmOgz-k0u_TcT:b-7z3m4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/7f4ce3831568f75032c93131ee4fd243c2b33895/pkg/security/certificate_loader.go#L40)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

I don't think you meant to change this from `false` to `true`.
</blockquote></details>

indeed I did not. Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101)*

**Comment by tamird** [comment]
:lgtm: modulo comment changes.

Tested this on Windows; security and cli tests pass.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/security/certificate_loader.go, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101#-Ki4ai4cnfJaCwhWcawF:-Ki4ai4cnfJaCwhWcawG:bkeuenk) ([raw file](https://github.com/cockroachdb/cockroach/blob/69eac11276d7b6c3114c85121f258790dd479416/pkg/security/certificate_loader.go#L35)):*
> ```Go
> func init() {
> 	if runtime.GOOS == "windows" {
> 		// File modes are not implemented on windows and default to 0666 for r/w files:
> ```

This comment isn't quite correct; they're implemented, just incomplete. I tested the following:
```
package main

import (
	"fmt"
	"os"
)

func main() {
	f, err := os.OpenFile("foo", os.O_CREATE, 0664) // <-- Note "664"
	if err != nil {
		panic(err)
	}
	info, err := f.Stat()
	if err != nil{
		panic(err)
	}
	fmt.Println(info.Mode().Perm())
}

```
```
$ go run main.go && ls -lah foo
-rw-rw-rw-
-rw-r--r-- 1 tamird None 0 Apr 19 09:51 foo
```
So what I saw in my previous comment was just a different default - msys defaults to 644 for r/w, and go defaults to 666. TL;DR is that ugo permissions don't transit through (go on) windows correctly. I think this comment should reflect that.

It's very strange that this isn't documented in standard library.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101#-:-Ki4crv8jLZDQdApE7xR:b-xjhua2)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[pkg/security/certificate_loader_test.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101#-Ki4dfy3-EXOQLdSWvcl:-Ki4dfy3-EXOQLdSWvcm:b-krckep) ([raw file](https://github.com/cockroachdb/cockroach/blob/b79509871db21abbd70082207221b169ac287d8b/pkg/security/certificate_loader_test.go#L73)):*
> ```Go
> 
> 	if runtime.GOOS == "windows" {
> 		t.Skip("file permissions do not exist on windows")
> ```

On second thought, isn't this too broad? Can't we disable a narrower part of the test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101)*

**Comment by mberhault** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/security/certificate_loader.go, line 35 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101#-Ki4ai4cnfJaCwhWcawF:-Ki5QTI5u9NtMq4X24Ja:b-hlgthz) ([raw file](https://github.com/cockroachdb/cockroach/blob/b79509871db21abbd70082207221b169ac287d8b/pkg/security/certificate_loader.go#L35)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

This comment isn't quite correct; they're implemented, just incomplete. I tested the following:
```
package main

import (
	"fmt"
	"os"
)

func main() {
	f, err := os.OpenFile("foo", os.O_CREATE, 0664) // <-- Note "664"
	if err != nil {
		panic(err)
	}
	info, err := f.Stat()
	if err != nil{
		panic(err)
	}
	fmt.Println(info.Mode().Perm())
}

```
```
$ go run main.go && ls -lah foo
-rw-rw-rw-
-rw-r--r-- 1 tamird None 0 Apr 19 09:51 foo
```
So what I saw in my previous comment was just a different default - msys defaults to 644 for r/w, and go defaults to 666. TL;DR is that ugo permissions don't transit through (go on) windows correctly. I think this comment should reflect that.

It's very strange that this isn't documented in standard library.
</blockquote></details>

tweaked comment.

---

*[pkg/security/certificate_loader_test.go, line 73 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101#-Ki4dfy3-EXOQLdSWvcl:-Ki5QAaUSMzJ4VQTnGUZ:bbccxzr) ([raw file](https://github.com/cockroachdb/cockroach/blob/b79509871db21abbd70082207221b169ac287d8b/pkg/security/certificate_loader_test.go#L73)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

On second thought, isn't this too broad? Can't we disable a narrower part of the test?
</blockquote></details>

Done. Only skip a single test case on windows.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101)*

**Comment by tamird** [comment]
Reviewed 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15101)*

**Pull request merged**
