### PR TITLE
kvserver: fix race in TestSchedulerBuffering

### LINKED ISSUE #94303: kv/kvserver: TestSchedulerBuffering failed
kv/kvserver.TestSchedulerBuffering [failed](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8108933?buildTab=log) with [artifacts](https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_Nightlies_StressBazel/8108933?buildTab=artifacts#/) on master @ [9c5375f6a7375724cdbcbaa0029ed97a230d7abe](https://github.com/cockroachdb/cockroach/commits/9c5375f6a7375724cdbcbaa0029ed97a230d7abe):

```
=== RUN   TestSchedulerBuffering
    test_log_scope.go:161: test logs captured to: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestSchedulerBuffering2749501448
    test_log_scope.go:79: use -show-logs to present logs inline
    scheduler_test.go:296: condition failed to evaluate within 45s: expected ready=[1:2] request=[1:2] tick=[1:20], but got ready=[1:2] request=[1:2] tick=[1:24]
    panic.go:522: -- test log scope end --
test logs left over in: /artifacts/tmp/_tmp/33e1d369c27b9c01b2b6009c561815a3/logTestSchedulerBuffering2749501448
--- FAIL: TestSchedulerBuffering (45.13s)
```
<p>Parameters: <code>TAGS=bazel,gss,deadlock</code>
</p>
<details><summary>Help</summary>
<p>

See also: [How To Investigate a Go Test Failure \(internal\)](https://cockroachlabs.atlassian.net/l/c/HgfXfJgM)
</p>
</details>
/cc @cockroachdb/kv
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*TestSchedulerBuffering.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

Jira issue: CRDB-22813

### PR DESCRIPTION
**Pull request by pav-kv**
In TestSchedulerBuffering there is a race between adding a new event to the
queue and finishing the processing of the previous event. The scheduler
processes this correctly, but when the ticks need to be dropped, the number of
processed ticks is non-deterministic.

This commit fixes the flake. It introduces a Raft ready interceptor which
effectively allows blocking the processing loop while ticks are being added.
This imitates the real world scenario.

Fixes #94303
Epic: none

### CODE REVIEW

**Review by erikgrinaker — APPROVED** [review]

**Comment by pavelkalinnikov** [comment]
Still catching it:
```
scheduler_test.go:307: condition failed to evaluate within 45s: expected ready=[1:2] request=[1:2] tick=[1:19,2:5], but got ready=[1:2] request=[1:2] tick=[1:19,2:6]
```

**Comment by pavelkalinnikov** [comment]
Probably this isn't due to this branch:
https://github.com/cockroachdb/cockroach/blob/a826248c13b5caaca2df0c4e292911f7494a0446/pkg/kv/kvserver/scheduler.go#L342-L365

It's enough that the enqueue is racing with the processing, regardless of the range ID.

**Comment by pavelkalinnikov** [comment]
Made a stable repro, fixing.

**Comment by pavelkalinnikov** [comment]
@erikgrinaker This should be fixed now. Feel free to take another look.

**Review by erikgrinaker — APPROVED** [review]
LGTM, thanks!

**Comment by pavelkalinnikov** [comment]
bors r=erikgrinaker

**Pull request merged**
