### PR TITLE
sql: introduce PurposelyUnimplemented for REINDEX syntax

### LINKED ISSUE #46653: sql: add unimplemented errors for REINDEX
[Postgres REINDEX](https://www.postgresql.org/docs/12/sql-reindex.html) rebuilds an index using the data stored in the index's table, replacing the old copy of the index. There are several scenarios in which Postgres recommends using REINDEX:

- An index has become corrupted, and no longer contains valid data. Although in theory this should never happen, in practice indexes can become corrupted due to software bugs or hardware failures. REINDEX provides a recovery method.
- An index has become "bloated", that is it contains many empty or nearly-empty pages. This can occur with B-tree indexes in PostgreSQL under certain uncommon access patterns. REINDEX provides a way to reduce the space consumption of the index by writing a new version of the index without the dead pages. See Section 23.2 for more information.
- You have altered a storage parameter (such as fillfactor) for an index, and wish to ensure that the change has taken full effect.
- An index build with the CONCURRENTLY option failed, leaving an "invalid" index. Such indexes are useless but it can be convenient to use REINDEX to rebuild them. Note that REINDEX will not perform a concurrent build. To build the index without interfering with production you should drop the index and reissue the CREATE INDEX CONCURRENTLY command.

CockroachDB does not need the reindex command because of how we built our indexing and schema change tooling. If you attempt to use them, you will see these errors:
```SQL
root@127.0.0.1:65504/movr> REINDEX INDEX rides_id;
invalid syntax: statement ignored: at or near "reindex": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
REINDEX INDEX rides_id
^
root@127.0.0.1:65504/movr> REINDEX TABLE rides;
invalid syntax: statement ignored: at or near "reindex": syntax error
SQLSTATE: 42601
DETAIL: source SQL:
REINDEX TABLE rides
^
```

We should turn these into unimplemented errors that contain notices/hints that this command is not needed in CockroachDB and link to the documentation.

### PR DESCRIPTION
**Pull request by otan**
Resolves https://github.com/cockroachdb/cockroach/issues/46653.

In addition to the release note, we introduce a
`PurposelyUnimplemented` helper for sql.y, which does not inherit
the unimp wrappers that add a bunch of details to check GitHub
for an existing issue or to create one.

Release note (sql change): Added support for parsing the REINDEX
syntax, which results in an unimplemented error that explains that
REINDEXing is not required in CRDB.

### CODE REVIEW

**Review by knz — COMMENTED** [review]
nice!

I'll let rohan review for correctness

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46850#-:-M3qCrm-74KAnzIAY6FG:b-sue9ji)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rohany)

___
*[pkg/sql/parser/sql.y, line 3419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46850#-M3qCmWS-W9f7AeeDTqW:-M3qCmWS-W9f7AeeDTqX:bwa5gr) ([raw file](https://github.com/cockroachdb/cockroach/blob/20a2d943e8413235b16dcf830eddad54d598c046/pkg/sql/parser/sql.y#L3419)):*
> ```Yacc
> 	DECLARE { return unimplementedWithIssue(sqllex, 41412) }
> 
> reindex_stmt:
> ```

Not 100% sure but this may need `/* SKIP DOC */`?

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/46850)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @rohany)

___
*[pkg/sql/parser/sql.y, line 3419 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/46850#-M3qCmWS-W9f7AeeDTqW:-M3qDW38-aJe0ysu_NIr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/20a2d943e8413235b16dcf830eddad54d598c046/pkg/sql/parser/sql.y#L3419)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Not 100% sure but this may need `/* SKIP DOC */`?
</blockquote></details>

Done.

**Review by rohany — APPROVED** [review]

**Comment by otan** [comment]
bors r=rohany

**Comment by otan** [comment]
bors r=rohany

**Pull request merged**
