### PR TITLE
cmd/skiperrs: add small cmd to skip erroring SQL

### PR DESCRIPTION
**Pull request by madelynnblue**
I have wanted this program many times. We can reuse the sql stream code
and most of the hard work is already done.

Release note: None

### CODE REVIEW

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43013#-:-LvNhmmM56p7fV6AdchC:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mjibson)

___
*[pkg/cmd/cr2pg/sqlstream/stream.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43013#-LvNhAu_4IMExD9rMosi:-LvNhAu_4IMExD9rMosj:b-ibcgox) ([raw file](https://github.com/cockroachdb/cockroach/blob/febc01689c29f23477148fd9ee1a9565e930fbed/pkg/cmd/cr2pg/sqlstream/stream.go#L20)):*
> ```Go
> 	"github.com/cockroachdb/cockroach/pkg/sql/parser"
> 	// Include this because the parser assumes builtin functions exist.
> 	_ "github.com/cockroachdb/cockroach/pkg/sql/sem/builtins"
> ```

[question]: does this not actually import `sem/builtins` package and lies to make `sql/parser` happy?
___
*[pkg/cmd/skiperrs/main.go, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43013#-LvNgiDL38c2KRZ_biAF:-LvNgiDL38c2KRZ_biAG:b-ra1fst) ([raw file](https://github.com/cockroachdb/cockroach/blob/febc01689c29f23477148fd9ee1a9565e930fbed/pkg/cmd/skiperrs/main.go#L2)):*
> ```Go
> // skiperrs connects to a postgres-compatible server with its URL specified
> // as the first argument. It then streams splits stdin into SQL statements and
> ```

[nit]: something feels off in "streams splits".

**Review by madelynnblue — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43013)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/cmd/cr2pg/sqlstream/stream.go, line 20 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43013#-LvNhAu_4IMExD9rMosi:-LwF1IG41XyeF4Givya5:b-ws5fph) ([raw file](https://github.com/cockroachdb/cockroach/blob/febc01689c29f23477148fd9ee1a9565e930fbed/pkg/cmd/cr2pg/sqlstream/stream.go#L20)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[question]: does this not actually import `sem/builtins` package and lies to make `sql/parser` happy?
</blockquote></details>

no, it actually imports it. importing it has a side effect during init that sets up some variables or something. i'm not sure of the details but this is common if you grep for it in our code.
___
*[pkg/cmd/skiperrs/main.go, line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/43013#-LvNgiDL38c2KRZ_biAF:-LwF274G-ivVU-IVgT41:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/febc01689c29f23477148fd9ee1a9565e930fbed/pkg/cmd/skiperrs/main.go#L2)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: something feels off in "streams splits".
</blockquote></details>

fixed

**Pull request merged**
