### PR TITLE
kvserver: de-flake TestStoreRangeMergeRHSLeaseExpiration

### LINKED ISSUE #47503: kv: TestStoreRangeMergeRHSLeaseExpiration timeout under testrace
Something got stuck for 45 minutes.

The log only has periodic `StorePool missing descriptor for local store`.

https://teamcity.cockroachdb.com/viewLog.html?buildId=1876754&buildTypeId=Cockroach_MergeToMaster

Attaching the logs
[TestStoreRangeMergeRHSLeaseExpiration.txt](https://github.com/cockroachdb/cockroach/files/4479067/TestStoreRangeMergeRHSLeaseExpiration.txt)

@tbg any chance you can look at this one?

### PR DESCRIPTION
**Pull request by tbg**
The test is setting up a race where a RHS leaseholder which is about to
get merged away loses the lease, while serving reads and writes.

The test set up these reads and writes so that they would all get to at
least the span acquisition stage. However, requests could bounce early
on the leaseholder check, which would deadlock the test.

Looking at the test, it's a little surprising that the replica sometimes
does not realize it is supposed to get a lease, but this is one of the
wonkier multiTestContext plus manual clock setup plus a maze of
interceptors, so it's not too surprising and, as I decided, not
worth looking into. Instead, the fix is to tolerate that not all
requests will make it to the latch, which seems like a sane assumption;
the test does not rely on it, it would just like it to happen so that
the intended regression test takes place.

Before this commit,

> make stress PKG=./pkg/kv/kvserver/ TESTS=TestStoreRangeMergeRHSLeaseExpiration TESTTIMEOUT=1m 2>&1 | tee log

failed in ~1-2 minutes. Runs just fine for 10+ minutes now.

Closes #47503.

Release note: None

### CODE REVIEW

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47508)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/kv/kvserver/client_merge_test.go, line 1489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47508#-M5-CX0s1zBLOkbKMZuu:-M5-CX0s1zBLOkbKMZuv:bah1y4b) ([raw file](https://github.com/cockroachdb/cockroach/blob/2332b9c0133f7d67d566f73f5609e724254f26ec/pkg/kv/kvserver/client_merge_test.go#L1489)):*
> ```Go
> 			// Latch acquired.
> 		case <-time.After(time.Second):
> 			// Requests may never make it to the latch acquisition if s1 has not
> ```

(if I understand correctly) Instead of this timeout, could we wait for a channel piping through the `NotLeaseholderErrors` that these requests are rejected with before getting to the latching?
___
*[pkg/kv/kvserver/client_merge_test.go, line 1506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47508#-M5-DGQxCJTSf1u50dhK:-M5-DGQy138I8VHGgWuW:bzhmqxh) ([raw file](https://github.com/cockroachdb/cockroach/blob/2332b9c0133f7d67d566f73f5609e724254f26ec/pkg/kv/kvserver/client_merge_test.go#L1506)):*
> ```Go
> 
> 	// Because the merge completed successfully, r2 has ceased to exist. We
> 	// therefore *must* see either a RangeNotFound or a NotLeaseHolderError
> ```

Can you please add some words here to explain how it is that either of these errors is expected?

**Review by tbg — COMMENTED** [review]
@nvanbenschoten do I remember correctly that we (you) changed something about when we check the lease? I'm starting to think that this made this flaky, but I couldn't remember/find the PR that made that change.
Reason I think that is because the test seems to expect to get latches before leaseholder error.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47508#-:-M52puYfEhO9N9O_njgZ:bwe4ubv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

**Comment by nvanbenschoten** [comment]
> do I remember correctly that we (you) changed something about when we check the lease? I'm starting to think that this made this flaky, but I couldn't remember/find the PR that made that change.

Yes, that's correct. I wonder that's also the cause of https://github.com/cockroachdb/cockroach/issues/47231. I'll look into that one.

**Review by tbg — COMMENTED** [review]
PTAL

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47508#-:-M5LytH466uGrO3d9-IQ:bb71pro)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/kv/kvserver/client_merge_test.go, line 1489 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47508#-M5-CX0s1zBLOkbKMZuu:-M5LwLGPEel7xSAGintS:b-h23rtk) ([raw file](https://github.com/cockroachdb/cockroach/blob/2332b9c0133f7d67d566f73f5609e724254f26ec/pkg/kv/kvserver/client_merge_test.go#L1489)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

(if I understand correctly) Instead of this timeout, could we wait for a channel piping through the `NotLeaseholderErrors` that these requests are rejected with before getting to the latching?
</blockquote></details>

Done, thanks for the suggestion.
___
*[pkg/kv/kvserver/client_merge_test.go, line 1506 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/47508#-M5-DGQxCJTSf1u50dhK:-M5LynIY358i0n18wEdl:b-83cjmw) ([raw file](https://github.com/cockroachdb/cockroach/blob/2332b9c0133f7d67d566f73f5609e724254f26ec/pkg/kv/kvserver/client_merge_test.go#L1506)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Can you please add some words here to explain how it is that either of these errors is expected?
</blockquote></details>

Done. Only RangeNotFound is expected (since not leaseholder is caught before latches).

**Review by andreimatei — COMMENTED** [review]
LGTM

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/47508#-:-M5NvOSACrr90QRSNbC2:bb6ywmx)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @tbg)

___
*[pkg/kv/kvserver/client_merge_test.go, line 1514 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/47508#-M5NvGPT2gGRA4jgUbOy:-M5NvGPUEVBKkB28vuyz:bsd7ia1) ([raw file](https://github.com/cockroachdb/cockroach/blob/9aad0482cf766b56962d8e6d1b129ff4d29600d5/pkg/kv/kvserver/client_merge_test.go#L1514)):*
> ```Go
> 	for pErr := range reqErrs {
> 		_, ok := pErr.GetDetail().(*roachpb.RangeNotFoundError)
> 		require.True(t, ok, "unxpected error %v", pErr)
> ```

require.IsType(*roachpb.RangeNotFoundErr)

**Comment by tbg** [comment]
Done, TFTR

bors r=andreimatei

**Pull request merged**
