### PR TITLE
release-21.1: ui: fix custom chart initial no load

### PR DESCRIPTION
**Pull request by Santamaura**
**What was there before:** The original logic for drawing the custom chart.
**What was the issue:** On initial load the function to create the options returns an array with 1 object but the uplot lib expects 2 objects with the second object having an attribute 'scale'.
**How it was resolved:** Added a check on the functions return to see if the numbers of elements is < 2 and if so return a 'filler' object with a scale value of 1.

Release note (ui): fix custom chart bug where it does not load on initial
[Github issue](https://github.com/cockroachdb/cockroach/issues/66890)
[Jira](https://cockroachlabs.atlassian.net/browse/CRDB-8278)

### CODE REVIEW

**Review by nathanstilwell — APPROVED** [review]
LGTM.

**Comment by nvanbenschoten** [comment]
HI @Santamaura, thanks for the quick fix! Will this be backported to release-21.1?

**Comment by nathanstilwell** [comment]
@nvanbenschoten this PR was merged to release-21.1 directly. I assumed that the equivalent to a backport. Are there other actions we need to take to get this into release 21.1.4?

**Comment by nvanbenschoten** [comment]
Ah, I did not notice that. No further action needed then if this was never an issue on `master`. Thanks @nathanstilwell.

**Comment by andreimatei** [comment]
Any chance we can get some type of test that would have caught this?

**Comment by nkodali** [comment]
Yes @andreimatei, we're planning to do this. @Santamaura after you make them, can you link the relevant issues here for tracking?

**Comment by Santamaura** [comment]
Relevant issues: https://github.com/cockroachdb/cockroach/issues/67132, https://github.com/cockroachdb/cockroach/issues/67134, https://github.com/cockroachdb/cockroach/issues/67136

**Pull request merged**
