### PR TITLE
kvserver: scale Raft entry cache size with system memory

### LINKED ISSUE #98666: kvserver: investigate raft entry cache sizing
The raft entry cache is sized to 16mb per store. This seems very small:

https://github.com/cockroachdb/cockroach/blob/e005c0f90ccc3b5462b9ff132020f1257d7ea53d/pkg/kv/kvserver/store.go#L103-L105

The `raft.entrycache.{accesses,hits}` metrics can be used to arrive at a cache hit rate. This is something we should be paying attention to when optimizing write performance.

x-ref https://github.com/cockroachdb/cockroach/pull/98576 where this was noticed.

Jira issue: CRDB-25431

### PR DESCRIPTION
**Pull request by erikgrinaker**
The Raft entry cache size defaulted to 16 MB, which is rather small. This has been seen to cause tail latency and throughput degradation with high write volume on large nodes, correlating with a reduction in the entry cache hit rate.

This patch linearly scales the Raft entry cache size as 1/256 of total system/cgroup memory, shared evenly between all stores, with a minimum 32 MB. For example, a 32 GB 8-vCPU node will have a 128 MB entry cache.

This is a conservative default, since this memory is not accounted for in existing memory budgets nor by the `--cache` flag. We rarely see cache misses in production clusters anyway, and have seen significantly improved hit rates with this scaling (e.g. a 64 KB kv0 workload on 8-vCPU nodes increased from 87% to 99% hit rate).

Resolves #98666.
Epic: none

Release note (performance improvement): The default Raft entry cache size has been increased from 16 MB to 1/256 of system memory with a minimum of 32 MB, divided evenly between all stores. This can be configured via `COCKROACH_RAFT_ENTRY_CACHE_SIZE`.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
I could be convinced to increase the scaling here to e.g. 1/128 with 64 MB minimum, but I decided to err on the side of caution here, and I haven't seen compelling evidence that this scaling is insufficient for the majority of workloads.

@nvanbenschoten Do you have any further workloads or experiments you'd like to calibrate this on? I'm currently rerunning https://github.com/cockroachdb/cockroach/issues/98666#issuecomment-1612502955 and will post results in #98666, but after 1 hour I'm seeing ~100% hit rate with the new setting while the old default is at 98.9%.

**Review by nvb — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107424#-:-NaEJg86B-_5gVpZA5qO:b-uwkowd)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker and @pavelkalinnikov)

___
*[`pkg/kv/kvserver/store.go` line 1294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107424#-NaEJ_De3_w_8ED5I8cV:-NaEJ_De3_w_8ED5I8cW:b-gj3j9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1dac6a2c350ec48cf737bc82426c8cf9dea4953/pkg/kv/kvserver/store.go#L1294)):*
> ```Go
> 	}
> 	if sc.RaftEntryCacheSize == 0 {
> 		sc.RaftEntryCacheSize = uint64(defaultRaftEntryCacheSize)
> ```

nit: should this just be `sc.RaftEntryCacheSize = uint64(defaultRaftEntryCacheSize) / uint64(numStores)`?

**Review by erikgrinaker — COMMENTED** [review]
TFTR!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/107424#-:-NaGJYBVE1Rcbhc2ATOT:b-oduykh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @pavelkalinnikov)

___
*[`pkg/kv/kvserver/store.go` line 1294 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/107424#-NaEJ_De3_w_8ED5I8cV:-NaGIsH3CoM18H2hKnVS:bq2gwxf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f1dac6a2c350ec48cf737bc82426c8cf9dea4953/pkg/kv/kvserver/store.go#L1294)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: should this just be `sc.RaftEntryCacheSize = uint64(defaultRaftEntryCacheSize) / uint64(numStores)`?
</blockquote></details>

Figured I'd guard against division by zero. This is called unconditionally on the server startup path, and I don't know if there are cases where we can end up running without a store (e.g. SQL pods).

**Pull request merged**
