### PR TITLE
sql: minor cleanup of RSG tests

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10596)

### CODE REVIEW

**Comment by mjibson** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/rsg_test.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10596#-KWEPLhXw3RXHdrxcLE0:-KWEPLhYWdzoeg1DbfML:b8mz20n) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cccf69ebc2ea9fdf2b071fb4e25c11b836cc48e/pkg/sql/rsg_test.go#L66)):*
> ```Go
> 		_, err := db.Exec(`CREATE DATABASE IF NOT EXISTS ident`)
> 		if err != nil {
> 			panic(err)
> ```

These have to be panics because this function is run in a goroutine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10596)*

**Comment by tamird** [comment]
The main goroutine never exits before this one does, so this is safe..?

**Comment by mjibson** [comment]
"FailNow must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test."

https://golang.org/pkg/testing/#T.FailNow (which is called by t.Fatal)

**Comment by mjibson** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10596#-:-KWEqkA1Ieaulsjhxdd6:bnfp4nl)*

**Comment by andreimatei** [comment]
Wait, how did you decide that `t.Fatal()` call is OK?

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10596#-:-KWErHmacEMBRfpYnjW2:byjpgg3)*

**Comment by tamird** [comment]
What t.Fatal call? I backed them all out.

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/rsg_test.go, line 66 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10596#-KWEPLhXw3RXHdrxcLE0:-KWErjyJwM4UFIfI0uu7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/5cccf69ebc2ea9fdf2b071fb4e25c11b836cc48e/pkg/sql/rsg_test.go#L66)):*
<details><summary><i>Previously, mjibson (Matt Jibson) wrote…</i></summary>
> These have to be panics because this function is run in a goroutine.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10596#-:-KWErdPiOddzeMRCjjfL:bawfj7w)*

**Pull request merged**
