### PR TITLE
sql: Add Size() method to EncDatum and EncDatumRow.

### PR DESCRIPTION
**Pull request by yuzefovich**
Adds Size() method to EncDatum and EncDatumRow structs
along with corresponding unit test.

Release note: None

### CODE REVIEW

**Comment by asubiotto** [comment]
Review status: :shipit: complete! 0 of 0 LGTMs obtained

---

*[pkg/sql/sqlbase/encoded_datum.go, line 77 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-LFxFJLJBX9QPHqxftVq:-LFxFJLJBX9QPHqxftVr:b6wn7s) ([raw file](https://github.com/cockroachdb/cockroach/blob/86d9fe63a11f5206f26ab69282df2dd6153ab6a9/pkg/sql/sqlbase/encoded_datum.go#L77)):*
> ```Go
> // Size returns a lower bound on the total size of the receiver in bytes,
> // including memory referenced by the receiver.
> func (ed *EncDatum) Size() uintptr {
> ```

I think this is better off as a value receiver

---

*[pkg/sql/sqlbase/encoded_datum.go, line 105 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-LFxF0vR8kV7KeCqjsr5:-LFxF0vR8kV7KeCqjsr6:bdm1cuj) ([raw file](https://github.com/cockroachdb/cockroach/blob/86d9fe63a11f5206f26ab69282df2dd6153ab6a9/pkg/sql/sqlbase/encoded_datum.go#L105)):*
> ```Go
> // encDatumFromEncodedAndDatum initializes an EncDatum with the given encoded
> // value and datum to be used for testing purposes.
> func encDatumFromEncodedAndDatum(enc DatumEncoding, encoded []byte, datum tree.Datum) EncDatum {
> ```

I don't think you need this function. I would just create an `EncDatum{}` in your tests. If you do want to keep this though, it would be better to put it in `sql/sqlbase/testutils.go`

---

*[pkg/sql/sqlbase/encoded_datum.go, line 388 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-LFxG9-b-Hyl6q9xACec:-LFxG9-b-Hyl6q9xACed:b-gzzth7) ([raw file](https://github.com/cockroachdb/cockroach/blob/86d9fe63a11f5206f26ab69282df2dd6153ab6a9/pkg/sql/sqlbase/encoded_datum.go#L388)):*
> ```Go
> 
> // Size returns a lower bound on the total size all EncDatum in the receiver
> // without accounting for the overhead.
> ```

Why not take the overhead into account? It's a good idea to not have to call `Sizeof` every time if the value never changes though. We should probably have the `EncDatum` size implementation just use a const `EncDatumSize` as its default starting size. Maybe do the same thing here for the overhead? Otherwise I can see callers having to individually calculate what that overhead is. What do you think?

---

*[pkg/sql/sqlbase/encoded_datum_test.go, line 543 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-LFxDPdl-X0wjuP8fsBh:-LFxDPdl-X0wjuP8fsBi:b-gog8vy) ([raw file](https://github.com/cockroachdb/cockroach/blob/86d9fe63a11f5206f26ab69282df2dd6153ab6a9/pkg/sql/sqlbase/encoded_datum_test.go#L543)):*
> ```Go
> }
> 
> const EncDatumStructSize = unsafe.Sizeof(EncDatum{})
> ```

I would declare these consts inside the test. Note that you can also use the:
```
const (
    EncDatumStructSize = ...
    DIntSize = ...
)
```
syntax

---

*[pkg/sql/sqlbase/encoded_datum_test.go, line 552 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-LFxDc-F72cV4hr1G1NH:-LFxDc-F72cV4hr1G1NI:bpd7tja) ([raw file](https://github.com/cockroachdb/cockroach/blob/86d9fe63a11f5206f26ab69282df2dd6153ab6a9/pkg/sql/sqlbase/encoded_datum_test.go#L552)):*
> ```Go
> 	defer leaktest.AfterTest(t)()
> 
> 	asc := DatumEncoding_ASCENDING_KEY
> ```

Declare these as consts

---

*[pkg/sql/sqlbase/encoded_datum_test.go, line 560 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-LFxDyTHC8n6090WU62U:-LFxDyTHC8n6090WU62V:b5s0i8a) ([raw file](https://github.com/cockroachdb/cockroach/blob/86d9fe63a11f5206f26ab69282df2dd6153ab6a9/pkg/sql/sqlbase/encoded_datum_test.go#L560)):*
> ```Go
> 	}{
> 		{
> 			encDatum:     EncDatumFromEncoded(asc, encoding.EncodeVarintAscending(nil, int64(0))),
> ```

The casts shouldn't be necessary

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26985)*

**Comment by asubiotto** [comment]
:lgtm_strong: 

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/sqlbase/encoded_datum.go, line 388 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-LFxG9-b-Hyl6q9xACec:-LG1FmbB-o8MSZYh0iKV:b6i8oes) ([raw file](https://github.com/cockroachdb/cockroach/blob/86d9fe63a11f5206f26ab69282df2dd6153ab6a9/pkg/sql/sqlbase/encoded_datum.go#L388)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

I saw a comment somewhere in the code like "without accounting for the overhead", so I thought it is a common approach. However, I totally agree with your point - accounting for as much memory as possible is the most intuitive (at least to me) approach.

I placed those two constants right above `Size()` methods. Is there a better place for them?
</blockquote></details>

Where you put them looks good to me.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-:-LG1Fwsm4mXN2LTcMi5Z:b-uwkowd)*

**Comment by yuzefovich** [comment]
TFTR.

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained

---

*[pkg/sql/sqlbase/encoded_datum.go, line 388 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-LFxG9-b-Hyl6q9xACec:-LG1HYPd6ZbnkrOxli0X:b-54avio) ([raw file](https://github.com/cockroachdb/cockroach/blob/86d9fe63a11f5206f26ab69282df2dd6153ab6a9/pkg/sql/sqlbase/encoded_datum.go#L388)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Where you put them looks good to me.
</blockquote></details>

Ok, thanks.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-:-LG1H_hM3WoSsRDj5yXE:b-814g87)*

**Comment by yuzefovich** [comment]
bors r+

---

Review status: :shipit: complete! 1 of 0 LGTMs obtained

---



*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26985#-:-LG1QQsgBaMGEHXtuN7K:b-ydi9ay)*

**Pull request merged**
