### PR TITLE
build: prune unused lint

### PR DESCRIPTION
**Pull request by tamird**
Whitelist util/interval/interval.go internally.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/9740)

### CODE REVIEW

**Comment by tamird** [comment]
It's pretty cheap to add it back when it's needed.

**Comment by tamird** [comment]
Upstream has generated code detection. https://github.com/dominikh/go-unused/commit/a4e2753c996cf34068d446d74f47f365ee694bc2

**Comment by RaduBerinde** [comment]
Ah that's cool. LGTM

**Comment by tamird** [comment]
Added a commit that removes `varcheck` while I'm here.

**Comment by RaduBerinde** [comment]
LGTM

**Pull request merged**
