### PR TITLE
ui: sort system database last on databases page

### LINKED ISSUE #25453: ui: system should sort after all other databases
This is not the case today, as can be seen by creating a database named `z`.
@couchand for triage.

### PR DESCRIPTION
**Pull request by couchand**
This sorts the system databases last, so that user databases are together
and the system tables are next to the non-table system data on this page.
Specifically `system`, `defaultdb`, and `postgres` sort to the end.

screen shot 2018-05-23 at 2 17 07 pm
(notice `test` above `defaultdb` here with the horizontal rule between)

Fixes #25453
Release note (admin ui change): List the system databases after all user
databases on the Databases page, instead of mixed in with them.

### CODE REVIEW

**Comment by bdarnell** [comment]
Can we put in some sort of divider here? It's confusing if the list is almost-but-not-quite-alphabetical without any indication that that's what's going on.

**Review by vilterp — APPROVED** [review]
LGTM; works when I tested locally. A wee unit test plz before merging?

**Comment by couchand** [comment]
@josueeee Could I get a design review on this change?  Thanks!

**Comment by couchand** [comment]
Unit test added.  Design feedback will be addressed in followup work.

bors r+

**Comment by couchand** [comment]
missing a file
bors r-

**Pull request merged**
