### PR TITLE
raft: persist Lead into the HardState

### LINKED ISSUE #124421: raft: persist Lead in HardState
`raft.lead` is currently volatile state which is lost on restart. We should add this to `HardState` and make it durable. This will pair with the `LeadEpoch` field that we plan to add to `HardState` as part of the leader-lease project.

Related to https://github.com/cockroachdb/cockroach/issues/122446.

Jira issue: CRDB-38884

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by arulajmani**
Previously, leader information for a given term was stored as volatile state in raft. This change persists it durably by moving it to HardState. This is done in service of leader leases, where we want to ensure a follower doesn't violate its promise of support to the leader even after a restart.

Fixes https://github.com/cockroachdb/cockroach/issues/124421

Release note: None

### CODE REVIEW

**Review by nvb — COMMENTED** [review]
> Reviewed 39 of 39 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126898)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1O8NuPECJf2kVXZyvC:-O1O8NuPECJf2kVXZyvD:beh5amh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94161a49c8099c1a63039828ac0ecf11c6f79d7/pkg/raft/raft.go#L478)):*
> ```Go
> 		raftlog.appliedTo(c.Applied, 0 /* size */)
> 	}
> 	r.becomeFollower(r.Term, r.lead)
> ```

One of the interesting parts about this change is that a follower can now know that it was the leader before it restarted. It would be nice to have a test that creates this scenario and demonstrates that the old leader (who can no longer serve as the leader due to a restart) campaigns at the next term.
___
*[`pkg/raft/raft.go` line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1O9BFNEulvONgBMWJb:-O1O9BFNEulvONgBMWJc:bzfp2se) ([raw file](https://github.com/cockroachdb/cockroach/blob/311900448e08e2919d932e2dbec6c7a57e0ee204/pkg/raft/raft.go#L773)):*
> ```Go
> 		r.Term = term
> 		r.Vote = None
> 	}
> ```

This is a subtle change. Was it needed? Or is this just an extra layer of protection against forgetting the leader.
___
*[`pkg/raft/rawnode.go` line 180 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1O9WLC45yl8XrSZpxY:-O1O9WLC45yl8XrSZpxZ:b-xcq4vh) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94161a49c8099c1a63039828ac0ecf11c6f79d7/pkg/raft/rawnode.go#L180)):*
> ```Go
> // that a synchronous write to persistent storage is required.
> func MustSync(st, prevst pb.HardState, entsnum int) bool {
> 	// Persistent state on all servers:
> ```

This comment needs an update.
___
*[`pkg/raft/raftpb/raft.proto` line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1O7L6gE3Be_ln5p4m0:-O1O7L6gE3Be_ln5p4m1:bh9nkcw) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94161a49c8099c1a63039828ac0ecf11c6f79d7/pkg/raft/raftpb/raft.proto#L125)):*
> ```proto
>   optional uint64 match = 15 [(gogoproto.nullable) = false];
> 
>   optional uint64 lead   = 16 [(gogoproto.nullable) = false, (gogoproto.casttype) = "PeerID"];
> ```

Let's give this a comment and explain when it is set.
___
*[`pkg/raft/raftpb/raft.proto` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1O7QS6Dpl8DApf_Jx_:-O1O7QS6Dpl8DApf_Jxa:bhppy94) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94161a49c8099c1a63039828ac0ecf11c6f79d7/pkg/raft/raftpb/raft.proto#L132)):*
> ```proto
> 	optional uint64 vote   = 2 [(gogoproto.nullable) = false, (gogoproto.casttype) = "PeerID"];
> 	optional uint64 commit = 3 [(gogoproto.nullable) = false];
>   optional uint64 lead   = 4 [(gogoproto.nullable) = false, (gogoproto.casttype) = "PeerID"];
> ```

Reviewable is indicating that the alignment with the other three fields is off here, because they use tabs while this line uses spaces.

**Review by arulajmani — COMMENTED** [review]
Resolved comments, PTAL. 

I've added a bunch of TODOs in the latest revision. I don't think any of these are in the critical path of this patch, however, we should talk about these as they'll guide the design for a few upcoming things. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-:-O1cf15d2-C8DxyQbH0q:b-lomlr4)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 478 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1O8NuPECJf2kVXZyvC:-O1Zpo_2BXFd2iMRU4ta:b-owaysd) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94161a49c8099c1a63039828ac0ecf11c6f79d7/pkg/raft/raft.go#L478)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

One of the interesting parts about this change is that a follower can now know that it was the leader before it restarted. It would be nice to have a test that creates this scenario and demonstrates that the old leader (who can no longer serve as the leader due to a restart) campaigns at the next term.
</blockquote></details>

I extended `TestRawNodeRestart` to demonstrate this.
___
*[`pkg/raft/raft.go` line 773 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1O9BFNEulvONgBMWJb:-O1ZphvL-oPFQVvpZzZm:b-xd1bfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/311900448e08e2919d932e2dbec6c7a57e0ee204/pkg/raft/raft.go#L773)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

This is a subtle change. Was it needed? Or is this just an extra layer of protection against forgetting the leader.
</blockquote></details>

Reverted this, like we spoke about offline. I've added a TODO to make this change in a separate PR. 
___
*[`pkg/raft/raftpb/raft.proto` line 125 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1O7L6gE3Be_ln5p4m0:-O1cd5OP3K_ScHhkuU7n:b-5hkuyp) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94161a49c8099c1a63039828ac0ecf11c6f79d7/pkg/raft/raftpb/raft.proto#L125)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Let's give this a comment and explain when it is set.
</blockquote></details>

I moved this up and updated the comment on `vote` that was talking about `MsgStorageAppends` (re)constructing a `HardState`. 
___
*[`pkg/raft/raftpb/raft.proto` line 132 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1O7QS6Dpl8DApf_Jx_:-O1ccq2U2Ga5bOAuvRVz:b-gg3rxi) ([raw file](https://github.com/cockroachdb/cockroach/blob/b94161a49c8099c1a63039828ac0ecf11c6f79d7/pkg/raft/raftpb/raft.proto#L132)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Reviewable is indicating that the alignment with the other three fields is off here, because they use tabs while this line uses spaces.
</blockquote></details>

Done. I converted the entire file to tabs, so it picked up another field (match) that was recently introduced. I'll (lazily) let it be part of this commit unless you prefer otherwise.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-:-O1relcz63udDLlieuZR:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 1243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1rb-yG8-gIq0rcq6ic:-O1rb-yG8-gIq0rcq6id:brg6r7l) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/raft/raft.go#L1243)):*
> Technically, it could win this election before the previous QSE expires.

The plan is to only even enter this CheckQuorum step down case if the QSE has already expired, right? So I'm not sure that this is possible on this specific step down case, but it is possible in the more general step down case.
___
*[`pkg/raft/raft.go` line 1244 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1ray3vB1c4oEpbTb98:-O1ray3vB1c4oEpbTb99:bipjso9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/raft/raft.go#L1244)):*
> ```Go
> 			// election. Technically, it could win this election before the previous
> 			// QSE expires.
> 			// TODO(arul): update the tense of this once laeder leases are implemented.
> ```

s/leader/laeder/
___
*[`pkg/raft/raft.go` line 1253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1rb_XJ2sLpKGxVCws8:-O1rb_XJ2sLpKGxVCws9:b-5ph52q) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/raft/raft.go#L1253)):*
> ```Go
> 			// store liveness for itself), it's safe for leader leases.
> 			//
> 			// TODO(arul,nvanbenschoten): One thing special about this case is that if
> ```

+1 on this being a special case. We probably don't want to pass `None` and forget the leader though. Better to have the condition for this step down and the result of the step down (i.e. immediately call an election) remain loosely coupled.
___
*[`pkg/raft/raft.go` line 1993 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1rcbcQDkRWIS1hJw6I:-O1rcbcQDkRWIS1hJw6J:bez9lou) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/raft/raft.go#L1993)):*
> ```Go
> 			// NB: Similar to the CheckQuorum step down case, we must remember our
> 			// prior stint as leader, lest we regress the QSE.
> 			r.becomeFollower(r.Term, r.lead)
> ```

Now that we're often passing `r.lead` to `r.becomeFollower`, should we remove the `lead` argument from the function? We can then package `assignLead` as a separate method with some safety checks to replace the `r.lead = m.From` and `r.becomeFollower(m.Term, m.From)` calls. Doesn't need to be this PR.
___
*[`pkg/raft/raftpb/raft.proto` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1rdbKZ8S5i47LRNXz5:-O1rdbKZ8S5i47LRNXz6:btqnbal) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/raft/raftpb/raft.proto#L91)):*
> ```proto
> 	repeated Entry       entries     = 7  [(gogoproto.nullable) = false];
> 	optional uint64      commit      = 8  [(gogoproto.nullable) = false];
> 	optional uint64 lead   = 16 [(gogoproto.nullable) = false, (gogoproto.casttype) = "PeerID"];
> ```

nit: this alignment with the previous fields looks off.
___
*[`pkg/kv/kvserver/below_raft_protos_test.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1reZ718vEFxtJMSU3p:-O1reZ718vEFxtJMSU3q:bcwgcj0) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/kv/kvserver/below_raft_protos_test.go#L67)):*
> ```Go
> 				Term:   n % 3,
> 				Vote:   raftpb.PeerID(n % 7),
> 				Commit: n % 11,
> ```

Want to add `Lead` here?

**Review by arulajmani — COMMENTED** [review]
TFTR!

bors r=nvanbenschoten

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-:-O20BedqCNmnqMxdhqDK:b-l0r5kv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 1243 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1rb-yG8-gIq0rcq6ic:-O206J42DUvvVNjfjtmI:ba6prvr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/raft/raft.go#L1243)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

> Technically, it could win this election before the previous QSE expires.

The plan is to only even enter this CheckQuorum step down case if the QSE has already expired, right? So I'm not sure that this is possible on this specific step down case, but it is possible in the more general step down case.
</blockquote></details>

Yeah. Cleaned up the commentary here. 
___
*[`pkg/raft/raft.go` line 1253 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1rb_XJ2sLpKGxVCws8:-O2063Be4J-5lAO5yzou:b84p2y3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/raft/raft.go#L1253)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

+1 on this being a special case. We probably don't want to pass `None` and forget the leader though. Better to have the condition for this step down and the result of the step down (i.e. immediately call an election) remain loosely coupled.
</blockquote></details>

Agreed. As we discussed over the last week, we don't want to treat this any different. I've just removed this stream of thought and cleaned up the commentary to call out the special case.
___
*[`pkg/raft/raft.go` line 1993 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1rcbcQDkRWIS1hJw6I:-O20AesKDg0HQG51HcnV:b-my9oq2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/raft/raft.go#L1993)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Now that we're often passing `r.lead` to `r.becomeFollower`, should we remove the `lead` argument from the function? We can then package `assignLead` as a separate method with some safety checks to replace the `r.lead = m.From` and `r.becomeFollower(m.Term, m.From)` calls. Doesn't need to be this PR.
</blockquote></details>

I've added a TODO for this, for now. I'll address it in a followup. 
___
*[`pkg/raft/raftpb/raft.proto` line 91 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1rdbKZ8S5i47LRNXz5:-O203W5eCnBvcEjA7FiG:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/raft/raftpb/raft.proto#L91)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

nit: this alignment with the previous fields looks off.
</blockquote></details>

Fixed.
___
*[`pkg/kv/kvserver/below_raft_protos_test.go` line 67 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/126898#-O1reZ718vEFxtJMSU3p:-O20AawpCcqAJtgtykMb:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a6f85774ef85a376a45d9aa19b0947b620c4bdc9/pkg/kv/kvserver/below_raft_protos_test.go#L67)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Want to add `Lead` here?
</blockquote></details>

Done.

**Pull request merged**
