### PR TITLE
rac2,kvflowcontrol: fix redaction safety for a few types

### PR DESCRIPTION
**Pull request by pav-kv**
Part of #136526

### CODE REVIEW

**Comment by pav-kv** [comment]
First 3 commits are from #137699.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, 2 of 2 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137766#-:-OEUIuM9DMbetYPB2y5E:bg7igkv)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @kvoli and @pav-kv)

___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontrolpb/kvflowcontrol.go` line 56 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/137766#-OEUH7iyCLPiEXZbAUcN:-OEUH7iyCLPiEXZbAUcO:bo908ao) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed169e7836188b0cc4a8df191d50aefa63116e3/pkg/kv/kvserver/kvflowcontrol/kvflowcontrolpb/kvflowcontrol.go#L56)):*
> ```Go
> }
> 
> func (a AdmittedResponseForRange) SafeFormat(w redact.SafePrinter, _ rune) {
> ```

I think `AdmittedResponseForRange` is not used. There is a todo to remove it in kvflowcontrol.proto. May as well do it now.
___
*[`pkg/raft/raftpb/raft.go` line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/137766#-OEUIRgh7BwDT5W-BXQ-:-OEUIRgh7BwDT5W-BXQ0:b7dsz4o) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed169e7836188b0cc4a8df191d50aefa63116e3/pkg/raft/raftpb/raft.go#L78)):*
> ```Go
> 	switch p {
> 	case LowPri:
> 		w.SafeString("LowPri")
> ```

just confirming that this was an optional change, yes? Given that the format argument is considered safe.
___
*[`pkg/util/admission/admissionpb/admissionpb.go` line 235 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/137766#-OEUIozJA-FHrCcZ7Ii2:-OEUIozJA-FHrCcZ7Ii3:bxv5dra) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed169e7836188b0cc4a8df191d50aefa63116e3/pkg/util/admission/admissionpb/admissionpb.go#L235)):*
> ```Go
> 	switch w {
> 	case RegularWorkClass:
> 		p.SafeString("regular")
> ```

same question about this being an optional change.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137766)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/raft/raftpb/raft.go` line 78 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/137766#-OEUIRgh7BwDT5W-BXQ-:-OEUXa2_E048wKutMg7n:b-mfb0dy) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed169e7836188b0cc4a8df191d50aefa63116e3/pkg/raft/raftpb/raft.go#L78)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

just confirming that this was an optional change, yes? Given that the format argument is considered safe.
</blockquote></details>

Yes, totally optional. I just thought it might be slightly cheaper, since `SafeString()` is straightforward, while `Printf` is variadic and allows arbitrary things in.
___
*[`pkg/util/admission/admissionpb/admissionpb.go` line 235 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/137766#-OEUIozJA-FHrCcZ7Ii2:-OEUYAyLD07m3-1bGfQX:b-redf51) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed169e7836188b0cc4a8df191d50aefa63116e3/pkg/util/admission/admissionpb/admissionpb.go#L235)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

same question about this being an optional change.
</blockquote></details>

Same answer.

**Review by pav-kv — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/137766)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @kvoli and @sumeerbhola)

___
*[`pkg/kv/kvserver/kvflowcontrol/kvflowcontrolpb/kvflowcontrol.go` line 56 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/137766#-OEUH7iyCLPiEXZbAUcN:-OEUcHKT8pwXFuF_6d5x:btkaeyw) ([raw file](https://github.com/cockroachdb/cockroach/blob/eed169e7836188b0cc4a8df191d50aefa63116e3/pkg/kv/kvserver/kvflowcontrol/kvflowcontrolpb/kvflowcontrol.go#L56)):*
<details><summary><i>Previously, sumeerbhola wrote…</i></summary><blockquote>

I think `AdmittedResponseForRange` is not used. There is a todo to remove it in kvflowcontrol.proto. May as well do it now.
</blockquote></details>

Good one. Removed.

**Comment by pav-kv** [comment]
bors r=sumeerbhola

**Pull request merged**
