### PR TITLE
raft: consult store liveness before campaigning

### LINKED ISSUE #132755: raft: consult store liveness before campaigning
**Describe the problem**

Currently, a raft peer doesn't consult StoreLiveness to determine whether it has support from a majority of peers before campaigning. We should perform this check and only call an election if we have sufficient StoreLiveness support. 

Given we don't attempt to seek StoreLiveness support from a store until `SupportFrom` is called for the very first time, this change would mean that raft elections would be delayed until StoreLiveness support has been established. We'll want to make sure this doesn't meaningfully impact how long tests take to run[1].

[1] One possible way is to ensure we don't wait out an entire election interval if the StoreLiveness support check fails, while ensuring elections are still called at random.

Jira issue: CRDB-43263

Epic CRDB-37522

### PR DESCRIPTION
**Pull request by iskettaneh**
This commit makes followers to make sure they are supported by a quorum before campaigning.

Fixes: #132755

Release note: None

### CODE REVIEW

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani)

___
*[`pkg/raft/raft.go` line 1296 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-O9WvyDmBPVQnV8yE5LJ:-O9WvyDmBPVQnV8yE5LK:b-kdv0po) ([raw file](https://github.com/cockroachdb/cockroach/blob/f96dad10fdd0248ecaad48f2e96c4cda3a0136f9/pkg/raft/raft.go#L1296)):*
> ```Go
> 	// become a pre-candidate, we forget the leader. This allows us to vote to
> 	// another candidate even if the electionElapsed is less than electionTimeout.
> 	if !r.supportedByQuorum() && t == campaignElection {
> ```

By structuring it like that, we will end up calling SupportFrom the first time on the Prevote Hup() (which might return false the very first time it's called, but it's okay because we don't stop becoming pre-candidate based on the support status)

**Review by nvb — COMMENTED** [review]
> Reviewed 5 of 5 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @iskettaneh)

___
*[`pkg/raft/raft.go` line 1362 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAOMenZ-gQoQElTfPB7:-OAOMenZ-gQoQElTfPB8:buhqxlf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e928a24d802a9b06d7dafa0c83598d5ac88d676/pkg/raft/raft.go#L1362)):*
> ```Go
> 
> 	// We shouldn't campaign if we don't have quorum support in store liveness.
> 	if r.fortificationTracker.FortificationEnabledForTerm() &&
> ```

`FortificationEnabledForTerm()` is stateful and tied to a leadership term. Do we want to expose a new method (`RequireQuorumSupportOnCampaign`?) which has no memory?
___
*[`pkg/raft/raft.go` line 1365 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAOMvBa5bQzEPDBLqrp:-OAOMvBa5bQzEPDBLqrq:bhgt9k9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e928a24d802a9b06d7dafa0c83598d5ac88d676/pkg/raft/raft.go#L1365)):*
> ```Go
> 		!r.fortificationTracker.QuorumSupported() {
> 		r.logger.Debugf("%x cannot campaign since it's not supported by a quorum in store liveness",
> 			r.id)
> ```

nit: don't wrap the `r.id`, just include it on the previous line. There are longer log lines below.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAOLnGA8LBe_J1fC9pI:-OAOLnGA8LBe_J1fC9pJ:bz5kss1) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6654aae1005e551cfd42adf08290b18fb65ffe/pkg/raft/tracker/fortificationtracker.go#L326)):*
> ```Go
> // or not.
> func (st *FortificationTracker) QuorumSupported() bool {
> 	votes := map[pb.PeerID]bool{}
> ```

Can we hang this map off of the `FortificationTracker` so that we don't need to allocate it on each call to this function? Unlike `computeLeadSupportUntil`, we don't need to support concurrent callers to this function.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 327 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAOLuWoE8UOp3CicnUc:-OAOLuWpCuOB9S1VTRos:b-itta34) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6654aae1005e551cfd42adf08290b18fb65ffe/pkg/raft/tracker/fortificationtracker.go#L327)):*
> ```Go
> func (st *FortificationTracker) QuorumSupported() bool {
> 	votes := map[pb.PeerID]bool{}
> 	for _, cfg := range st.config.Voters {
> ```

We can use `st.config.Voters.Visit` to avoid duplicate calls for peers in both halves of a joint configuration.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/raft/raft.go` line 1362 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAOMenZ-gQoQElTfPB7:-OAOYWo3A0TgrRSivCuJ:b9si1wf) ([raw file](https://github.com/cockroachdb/cockroach/blob/9e928a24d802a9b06d7dafa0c83598d5ac88d676/pkg/raft/raft.go#L1362)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

`FortificationEnabledForTerm()` is stateful and tied to a leadership term. Do we want to expose a new method (`RequireQuorumSupportOnCampaign`?) which has no memory?
</blockquote></details>

And basically the function `RequireQuorumSupportOnCampaign` would return ft.storeLiveness.SupportFromEnabled()?  I added that method and made QuorumSupported call it
___
*[`pkg/raft/tracker/fortificationtracker.go` line 326 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAOLnGA8LBe_J1fC9pI:-OAOYyiO89fcdbkEMcVR:b207neh) ([raw file](https://github.com/cockroachdb/cockroach/blob/7a6654aae1005e551cfd42adf08290b18fb65ffe/pkg/raft/tracker/fortificationtracker.go#L326)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Can we hang this map off of the `FortificationTracker` so that we don't need to allocate it on each call to this function? Unlike `computeLeadSupportUntil`, we don't need to support concurrent callers to this function.
</blockquote></details>

I was following the same code as in QuorumActive(), but I agree that we shouldn't allocate the map every time we call this function. I didn't completely understand your suggestion though. I added a map to the fortificationTracker, and for now I am resetting it before counting the votes. We can probably clear it when we become a follower for a given term, but I think that optimization needs a bit more thinking

**Review by arulajmani — COMMENTED** [review]
Mostly looks good. Some minor comments/nits.

> Reviewed 1 of 5 files at r2, 6 of 6 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-:-OAPUAlCEYrgG5J8ZubU:b-1qorjq)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @iskettaneh and @nvanbenschoten)

___
*[`pkg/raft/tracker/fortificationtracker.go` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAPSJAC20qVt3kteK6z:-OAPSJAC20qVt3kteK7-:b3exh7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e3285c9a3533a7843235e2737d24460f01fd93/pkg/raft/tracker/fortificationtracker.go#L54)):*
> ```Go
> 	fortification map[pb.PeerID]pb.Epoch
> 
> 	// votersSupport is a map that gets populated before campaigning to make sure
> ```

The "populated before campaigning" bit seems off -- we shouldn't be making assumptions about the caller of `QuorumSupported` (esp given the general name of the method) here. We should rewrite this comment in the context of the `fortificationTracker` instead -- something like:
```
votersSupported is a map that hangs off the fortificationTracker to prevent allocations on every call to QuorumSupported.
```
___
*[`pkg/raft/tracker/fortificationtracker.go` line 330 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAPRqBL13FfIWd49iSB:-OAPRqBM4qQcdbrMgNJ2:bs71i3u) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e3285c9a3533a7843235e2737d24460f01fd93/pkg/raft/tracker/fortificationtracker.go#L330)):*
> ```Go
> // requireQuorumSupportOnCampaign returns true if quorum support before
> // campaigning is required.
> func (ft *FortificationTracker) requireQuorumSupportOnCampaign() bool {
> ```

Should this be a public method that's called in `raft.go` instead of being called from `QuorumSupported` instead? The name would suggest it should.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 342 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAPT3oUAcegAtfKfmdv:-OAPT3oVE-w7C1zguNJ2:b-qnuppz) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e3285c9a3533a7843235e2737d24460f01fd93/pkg/raft/tracker/fortificationtracker.go#L342)):*
> ```Go
> 
> 	// TODO(ibrahim): If this is expensive, we can try to clear the map when we
> 	// become a follower for a given term.
> ```

Would that mean that we can only call `QuorumSupported` once per term?
___
*[`pkg/raft/tracker/fortificationtracker.go` line 346 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAPTGvo3qtNpIreYkwX:-OAPTGvo3qtNpIreYkwY:bjc966t) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e3285c9a3533a7843235e2737d24460f01fd93/pkg/raft/tracker/fortificationtracker.go#L346)):*
> ```Go
> 
> 	ft.config.Voters.Visit(func(id pb.PeerID) {
> 		_, ft.votersSupport[id] = ft.IsFortifiedBy(id)
> ```

nit: it might be clearer to say something like:

```golang
		_, isSupported := ft.IsFortifiedBy(id)
		ft.votersSupport[id] = isSupported
```
___
*[`pkg/raft/tracker/fortificationtracker_test.go` line 402 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAPRaxbANocydoP86xo:-OAPRaxbANocydoP86xp:b6ao51p) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e3285c9a3533a7843235e2737d24460f01fd93/pkg/raft/tracker/fortificationtracker_test.go#L402)):*
> ```Go
> }
> 
> // TestQuorumActive ensures that we correctly determine whether a leader's
> ```

nit: "TestQuorumSupported"

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/raft/tracker/fortificationtracker.go` line 54 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAPSJAC20qVt3kteK6z:-OAPeIq4BZHIqZwMQJT1:b3f9abz) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e3285c9a3533a7843235e2737d24460f01fd93/pkg/raft/tracker/fortificationtracker.go#L54)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

The "populated before campaigning" bit seems off -- we shouldn't be making assumptions about the caller of `QuorumSupported` (esp given the general name of the method) here. We should rewrite this comment in the context of the `fortificationTracker` instead -- something like:
```
votersSupported is a map that hangs off the fortificationTracker to prevent allocations on every call to QuorumSupported.
```
</blockquote></details>

Makes sense! Done
___
*[`pkg/raft/tracker/fortificationtracker.go` line 330 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAPRqBL13FfIWd49iSB:-OAPffKL8zuQQzheJ8Oa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e3285c9a3533a7843235e2737d24460f01fd93/pkg/raft/tracker/fortificationtracker.go#L330)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should this be a public method that's called in `raft.go` instead of being called from `QuorumSupported` instead? The name would suggest it should.
</blockquote></details>

Done.
___
*[`pkg/raft/tracker/fortificationtracker.go` line 342 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAPT3oUAcegAtfKfmdv:-OAPdnymEh7oeEFn1re4:bgy19fz) ([raw file](https://github.com/cockroachdb/cockroach/blob/82e3285c9a3533a7843235e2737d24460f01fd93/pkg/raft/tracker/fortificationtracker.go#L342)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Would that mean that we can only call `QuorumSupported` once per term?
</blockquote></details>

I removed the TODO since it doesn't make much sense

**Review by arulajmani — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r6, 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-:-OAPgRKPEEa8ybi-bc_V:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @iskettaneh and @nvanbenschoten)

___
*[`pkg/raft/tracker/fortificationtracker.go` line 54 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAPg8TP7pCaLRc_v8g5:-OAPg8TP7pCaLRc_v8g6:b-mho7w4) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b600413c85c659b62c08364ad3e4dab19911c6/pkg/raft/tracker/fortificationtracker.go#L54)):*
> ```Go
> 	fortification map[pb.PeerID]pb.Epoch
> 
> 	// votersSupported is a map that hangs off the fortificationTracker to prevent
> ```

nit: my bad, I was reading the field name wrong. s/votersSupported/votersSupport/g

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/raft/tracker/fortificationtracker.go` line 54 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAPg8TP7pCaLRc_v8g5:-OASb_L99P8iON_cnlYw:b-4adu6u) ([raw file](https://github.com/cockroachdb/cockroach/blob/25b600413c85c659b62c08364ad3e4dab19911c6/pkg/raft/tracker/fortificationtracker.go#L54)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: my bad, I was reading the field name wrong. s/votersSupported/votersSupport/g
</blockquote></details>

Hahaha I also didn't catch the typo

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_server_test.go` line 4781 at r10](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OATYSg5CISYhxl6pePE:-OATYSg5CISYhxl6pePF:b4lnf9p) ([raw file](https://github.com/cockroachdb/cockroach/blob/315e3b079eea540d1db17ef890d5ce0b1e86670a/pkg/kv/kvclient/kvcoord/dist_sender_server_test.go#L4781)):*
> ```Go
> 				// this block once #118943 is fixed.
> 				testutils.SucceedsSoon(t, func() error {
> 					if leaseType == roachpb.LeaseLeader {
> ```

Thoughts about this?

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/client_raft_test.go` line 1244 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAV5OlcEsXctFaJn93q:-OAV5OlcEsXctFaJn93r:by1l5v0) ([raw file](https://github.com/cockroachdb/cockroach/blob/467998ed5d9bfa956c4515283f0a4c28ef2ebd50/pkg/kv/kvserver/client_raft_test.go#L1244)):*
> ```Go
> 		require.ErrorAs(t, pErr.GetDetail(), &nlhe, pErr)
> 
> 		// In symmetric=true, we expect that the partitioned replica can't know
> ```

@arulajmani The test worked fine under stress

**Review by arulajmani — COMMENTED** [review]
> Reviewed 6 of 6 files at r9, 7 of 7 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @iskettaneh and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_server_test.go` line 4787 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAYUBPIA8Fzsc1rxEd1:-OAYUBPIA8Fzsc1rxEd2:b-n1xzok) ([raw file](https://github.com/cockroachdb/cockroach/blob/467998ed5d9bfa956c4515283f0a4c28ef2ebd50/pkg/kv/kvclient/kvcoord/dist_sender_server_test.go#L4787)):*
> ```Go
> 						// support from a majority. We need to keep trying to transfer the
> 						// lease until the new leader is elected.
> 						tc.TransferRangeLeaseOrFatal(t, desc, tc.Target(1))
> ```

This wouldn't retry, right? It'll just fatal if it can't transfer the lease. Did you mean to use `TransferRangeLease` here which returns an error instead? 

Separately, slightly surprised that this didn't fatal under stress.
___
*[`pkg/kv/kvserver/client_raft_test.go` line 1139 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAYUPncBX9miAqjYmWi:-OAYUPncBX9miAqjYmWj:b2vlow8) ([raw file](https://github.com/cockroachdb/cockroach/blob/467998ed5d9bfa956c4515283f0a4c28ef2ebd50/pkg/kv/kvserver/client_raft_test.go#L1139)):*
> ```Go
> 		//          ^  ^		                x   x
> 		//         /    \		               /     \
> 		//        x      x		            x       x
> ```

nit: the diagram for the symmetric case is a bit skewed.
___
*[`pkg/kv/kvserver/client_raft_test.go` line 1166 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAYUXme-z2h1CZED5VU:-OAYUXme-z2h1CZED5VV:b-5g84sd) ([raw file](https://github.com/cockroachdb/cockroach/blob/467998ed5d9bfa956c4515283f0a4c28ef2ebd50/pkg/kv/kvserver/client_raft_test.go#L1166)):*
> ```Go
> 		testutils.SucceedsSoon(t, func() error {
> 			if partRepl.RaftStatus().RaftState == raftpb.StateLeader {
> 				return errors.New("partitioned replica should stepped down")
> ```

nit:  While here, "should step down" or "should have stepped down"
___
*[`pkg/kv/kvserver/client_raft_test.go` line 1244 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAV5OlcEsXctFaJn93q:-OAYUe1A5TSrOqJ2FU5D:balonrr) ([raw file](https://github.com/cockroachdb/cockroach/blob/467998ed5d9bfa956c4515283f0a4c28ef2ebd50/pkg/kv/kvserver/client_raft_test.go#L1244)):*
<details><summary><i>Previously, iskettaneh wrote…</i></summary><blockquote>

@arulajmani The test worked fine under stress
</blockquote></details>

nit: "the partitioned replica to not know about the leader. As a result, it returns a NotLeaseHolderError without a speculative lease"

Separately, we should add an else branch for the asymmetric case -- in this case, we always expect the speculative lease to point to the leader replica.
___
*[`pkg/kv/kvserver/client_raft_test.go` line 1281 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAYV-TQ5o7dibIoAcyt:-OAYV-TQ5o7dibIoAcyu:b-ionjvv) ([raw file](https://github.com/cockroachdb/cockroach/blob/467998ed5d9bfa956c4515283f0a4c28ef2ebd50/pkg/kv/kvserver/client_raft_test.go#L1281)):*
> ```Go
> 			store.Transport().ListenIncomingRaftMessages(store.Ident.StoreID, store)
> 			store.StoreLivenessTransport().ListenMessages(
> 				store.Ident.StoreID, store.TestingStoreLivenessMessageHandler(),
> ```

nit: consider reverting this and changing the line above instead.

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvclient/kvcoord/dist_sender_server_test.go` line 4787 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAYUBPIA8Fzsc1rxEd1:-OAYYaLu7MWJcjcYjjhx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/467998ed5d9bfa956c4515283f0a4c28ef2ebd50/pkg/kv/kvclient/kvcoord/dist_sender_server_test.go#L4787)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

This wouldn't retry, right? It'll just fatal if it can't transfer the lease. Did you mean to use `TransferRangeLease` here which returns an error instead? 

Separately, slightly surprised that this didn't fatal under stress.
</blockquote></details>

Done.
___
*[`pkg/kv/kvserver/client_raft_test.go` line 1139 at r11](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAYUPncBX9miAqjYmWi:-OAYZ7jQE1P5BCKL05zi:bi9hzj9) ([raw file](https://github.com/cockroachdb/cockroach/blob/467998ed5d9bfa956c4515283f0a4c28ef2ebd50/pkg/kv/kvserver/client_raft_test.go#L1139)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

nit: the diagram for the symmetric case is a bit skewed.
</blockquote></details>

Tabs vs spaces. Now they all should be spaces

**Review by arulajmani — COMMENTED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @iskettaneh and @nvanbenschoten)

___
*[`pkg/kv/kvserver/client_raft_test.go` line 1246 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAYnqOT4y4PAe14yjWz:-OAYnqOT4y4PAe14yjX-:b-2bvmzs) ([raw file](https://github.com/cockroachdb/cockroach/blob/868559f9d95ae323256e666845ce20d19e929af6/pkg/kv/kvserver/client_raft_test.go#L1246)):*
> ```Go
> 		// In symmetric=true, we expect that the partitioned replica to not know
> 		// about the leader. As a result, it returns a NotLeaseHolderError without
> 		// a speculative lease
> ```

nit: missing period. Separately, let's move this inside the if block. 
___
*[`pkg/kv/kvserver/client_raft_test.go` line 1252 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAYnvQYABqeZ7YwjByj:-OAYnvQZ0UWqZlmfiIsd:b-nvnb8k) ([raw file](https://github.com/cockroachdb/cockroach/blob/868559f9d95ae323256e666845ce20d19e929af6/pkg/kv/kvserver/client_raft_test.go#L1252)):*
> ```Go
> 			require.False(t, nlhe.Lease.Empty())
> 			require.False(t,
> 				nlhe.Lease.OwnedBy(partitionStore.StoreID()),
> ```

Should we also assert that it's `leaderReplicaID`?

**Review by iskettaneh — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/132915)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @arulajmani and @nvanbenschoten)

___
*[`pkg/kv/kvserver/client_raft_test.go` line 1252 at r12](https://reviewable.io/reviews/cockroachdb/cockroach/132915#-OAYnvQYABqeZ7YwjByj:-OAZ00174wi-Jdz7oyXf:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/868559f9d95ae323256e666845ce20d19e929af6/pkg/kv/kvserver/client_raft_test.go#L1252)):*
<details><summary><i>Previously, arulajmani (Arul Ajmani) wrote…</i></summary><blockquote>

Should we also assert that it's `leaderReplicaID`?
</blockquote></details>

Done.

**Comment by iskettaneh** [comment]
TFTR!

bors r+

**Pull request merged**
