### PR TITLE
sql: support qualified name resolution and search path for function names

### LINKED ISSUE #10417: sql: support qualified function names
We may have to support qualified function names to support Hibernate.

Repro:
Run @nvanbenschoten's example Hibernate app (cockroachdb/examples-orms#2) twice. (The first time currently fails because of the currently being addressed lack of `pg_catalog.pg_settings`.)

Output:
```
ERROR: ERROR: unknown function: pg_catalog.pg_get_expr
Exception in thread "main" org.hibernate.exception.GenericJDBCException: Error accessing column metadata: company.customers
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:47)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:111)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:97)
        at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.convertSQLException(InformationExtractorJdbcDatabaseMetaDataImpl.java:97)
        at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.getColumn(InformationExtractorJdbcDatabaseMetaDataImpl.java:485)
        at org.hibernate.tool.schema.extract.internal.TableInformationImpl.getColumn(TableInformationImpl.java:68)
        at org.hibernate.mapping.Table.sqlAlterStrings(Table.java:456)
        at org.hibernate.tool.schema.internal.SchemaMigratorImpl.migrateTable(SchemaMigratorImpl.java:367)
        at org.hibernate.tool.schema.internal.SchemaMigratorImpl.performMigration(SchemaMigratorImpl.java:260)
        at org.hibernate.tool.schema.internal.SchemaMigratorImpl.doMigration(SchemaMigratorImpl.java:137)
        at org.hibernate.tool.schema.internal.SchemaMigratorImpl.doMigration(SchemaMigratorImpl.java:110)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:176)
        at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:65)
        at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:308)
        at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:476)
        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:707)
        at com.cockroachlabs.Application.buildSessionFactory(Application.java:45)
        at com.cockroachlabs.Application.main(Application.java:17)
Caused by: org.postgresql.util.PSQLException: ERROR: unknown function: pg_catalog.pg_get_expr
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2284)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2003)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:200)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:424)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:321)
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:284)
        at org.postgresql.jdbc.PgDatabaseMetaData.getColumns(PgDatabaseMetaData.java:1703)
        at org.postgresql.jdbc.PgDatabaseMetaData.getColumns(PgDatabaseMetaData.java:1802)
        at org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl.getColumn(InformationExtractorJdbcDatabaseMetaDataImpl.java:458)
```

I tried adding `pg_catalog.pg_expr` as an identity function:

```
diff --git a/pkg/sql/parser/builtins.go b/pkg/sql/parser/builtins.go
index 2f74848..9fac249 100644
--- a/pkg/sql/parser/builtins.go
+++ b/pkg/sql/parser/builtins.go
@@ -1142,6 +1142,15 @@ var Builtins = map[string][]Builtin{
                        },
                },
        },
+       "pg_catalog.pg_get_expr": {
+               Builtin{
+                       Types:      VariadicType{TypeString},
+                       ReturnType: TypeString,
+                       fn: func(_ *EvalContext, args DTuple) (Datum, error) {
+                               return args[0], nil
+                       },
+               },
+       },
 }

 func init() {
```

However, this didn't resolve the issue. I suspect that we're not parsing function names with `.` correctly.

@knz any thoughts here?

### PR DESCRIPTION
**Pull request by knz**
This patch introduces support for:
- built-in functions with a long name, for example "foo.bar()";
- automatically searching an unqualified function name, for example
  in "bar()" if "bar" does not exist but "foo" is in the current
  search path, "foo.bar()" can be found.

Besides achieving this, the patch also refactors the handling of
function resolution: instead of a 2-step process, the first from
UnresolvedName to QualifiedFunctionName in Normalize() then another in
TypeCheck() from QualifiedFunctionName to builtin, now a single
function Resolve() substitutes an UnresolvedName with a
FunctionDefinition in the FuncExpr node.

FunctionDefinition objects are pre-allocated and carry the normalized
name of the function. This means that pretty-printing a call
expression now always reports the function name upper cased.
Fixes  #10417.
cc @cuongdo.

---
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/10595)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Nice! Just a few comments.

---

Review status: 0 of 4 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/sql/select_name_resolution.go, line 143 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWFMdx84sIjXrmB9zDx:-KWFMdx84sIjXrmB9zDy:b-65u6mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/f346d8022f42ea1e3fe5d4273222abcc1930434f/pkg/sql/select_name_resolution.go#L143)):*
> ```Go
> ) error {
> 	var buf bytes.Buffer
> 	for _, part := range fn.Context {
> ```

This seems like it should be a method on either `QualifiedFunctionName` or `NameParts`

---

*[pkg/sql/select_name_resolution.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWFNA0kKxcwVNtwhSOR:-KWFNA0kKxcwVNtwhSOS:b492a4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/f346d8022f42ea1e3fe5d4273222abcc1930434f/pkg/sql/select_name_resolution.go#L152)):*
> ```Go
> 		}
> 	}
> 	prefix := buf.String()
> ```

A lot of this can (should) be optimized for the common case where a function has no Context.

---

*[pkg/sql/select_name_resolution.go, line 173 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWFNg4jAlodYEZS_22p:-KWFNg4jAlodYEZS_22q:b71iujg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f346d8022f42ea1e3fe5d4273222abcc1930434f/pkg/sql/select_name_resolution.go#L173)):*
> ```Go
> 	}
> 
> 	fn.Context = nil
> ```

Do you think we should replace the entire `FuncExpr` in the visitor in the rare cases that the `QualifiedFunctionName` changes (and not change anything in place when we're just making an unqualified name lower-case)? I think that would fix the user-visible change problem.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-:-KWFOsfh3Xupx1f9Th-V:b-41hb28)*

**Comment by knz** [comment]
Turned into a larger refactoring; I figured we don't really need QualifiedFunctionName at all.

---

Review status: 0 of 16 files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/sql/select_name_resolution.go, line 143 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWFMdx84sIjXrmB9zDx:-KWIrx1KJvyFbjugICUU:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f346d8022f42ea1e3fe5d4273222abcc1930434f/pkg/sql/select_name_resolution.go#L143)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> This seems like it should be a method on either `QualifiedFunctionName` or `NameParts`
</details>
Done.

---

*[pkg/sql/select_name_resolution.go, line 152 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWFNA0kKxcwVNtwhSOR:-KWIrwKmwBABhlWrgkiA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f346d8022f42ea1e3fe5d4273222abcc1930434f/pkg/sql/select_name_resolution.go#L152)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> A lot of this can (should) be optimized for the common case where a function has no Context.
</details>
Done.

---

*[pkg/sql/select_name_resolution.go, line 173 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWFNg4jAlodYEZS_22p:-KWIrxlmmMiJRxVF0TNP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f346d8022f42ea1e3fe5d4273222abcc1930434f/pkg/sql/select_name_resolution.go#L173)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Do you think we should replace the entire `FuncExpr` in the visitor in the rare cases that the `QualifiedFunctionName` changes (and not change anything in place when we're just making an unqualified name lower-case)? I think that would fix the user-visible change problem.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-:-KWIrzmPOyUKLEEdoNvk:b-ssifnv)*

**Comment by nvanbenschoten** [comment]
It doesn't look like the commit message or PR message discusses this new refactoring at all. I really like where this is headed though.

---

Reviewed 16 of 17 files at r2.
Review status: 15 of 16 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/function_name.go, line 70 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWMOSUwr-nxmlmTQ2-W:-KWMOSUwr-nxmlmTQ2-X:bsir7bi) ([raw file](https://github.com/cockroachdb/cockroach/blob/31594ec5e5a9280a2dc73c5b73b7b5e28da710c8/pkg/sql/parser/function_name.go#L70)):*
> ```Go
> // holding a pre-resolved function. Helper for grammar rules.
> func WrapFunction(n string) ResolvableFunctionReference {
> 	fd := Builtins[n]
> ```

`fd, ok :=` and panic on `!ok`

---

*[pkg/sql/parser/function_name.go, line 93 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWMPBFunIpF2pEQsJaN:-KWMPBFunIpF2pEQsJaO:bwi4576) ([raw file](https://github.com/cockroachdb/cockroach/blob/31594ec5e5a9280a2dc73c5b73b7b5e28da710c8/pkg/sql/parser/function_name.go#L93)):*
> ```Go
> }
> 
> // NormalizeFunctionName transforms an UnresolvedName to a QualifiedFunctionName.
> ```

Not anymore!

---

*[pkg/sql/parser/function_name.go, line 140 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWMQin5SRt6z09Fo-nb:-KWMQin5SRt6z09Fo-nc:b-56jcia) ([raw file](https://github.com/cockroachdb/cockroach/blob/31594ec5e5a9280a2dc73c5b73b7b5e28da710c8/pkg/sql/parser/function_name.go#L140)):*
> ```Go
> }
> 
> // FunctionDefinition implements a reference to one or more function
> ```

All of this information is already stored in `Builtins`, right? Now we're going to start allocating these object at runtime whenever we resolve builtin functions? Seems like restructuring `Builtins` or providing an init-time mapping from Builtins to a `name`->`FunctionDefinition` map would be an easy win.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-:-KWMMzVp6tkqOnlrksP2:b-n6sn3r)*

**Comment by knz** [comment]
Thanks for the suggestions!

---

Review status: 15 of 16 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/function_name.go, line 70 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWMOSUwr-nxmlmTQ2-W:-KWMirPZB80OGchoG2el:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31594ec5e5a9280a2dc73c5b73b7b5e28da710c8/pkg/sql/parser/function_name.go#L70)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> `fd, ok :=` and panic on `!ok`
</details>
Done.

---

*[pkg/sql/parser/function_name.go, line 93 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWMPBFunIpF2pEQsJaN:-KWMjHXxFyML8-x6EqAw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31594ec5e5a9280a2dc73c5b73b7b5e28da710c8/pkg/sql/parser/function_name.go#L93)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Not anymore!
</details>
Done.

---

*[pkg/sql/parser/function_name.go, line 140 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWMQin5SRt6z09Fo-nb:-KWMpL9UfCN1eFTwI7KF:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/31594ec5e5a9280a2dc73c5b73b7b5e28da710c8/pkg/sql/parser/function_name.go#L140)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> All of this information is already stored in `Builtins`, right? Now we're going to start allocating these object at runtime whenever we resolve builtin functions? Seems like restructuring `Builtins` or providing an init-time mapping from Builtins to a `name`->`FunctionDefinition` map would be an easy win.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-:-KWMqW4Ozm4lt1TFS6f9:b-yr7a7q)*

**Comment by nvanbenschoten** [comment]
A lot of this change is now dealing with the error reporting with 

---

Reviewed 6 of 19 files at r3.
Review status: 16 of 29 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/reference_test.go, line 70 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWNHKsYfQ7dgNv4ssx:-KWWNHKsYfQ7dgNv4ssy:bf1u6xt) ([raw file](https://github.com/cockroachdb/cockroach/blob/2257842790704ae55ecbf41ba2b9768198f00365/pkg/acceptance/reference_test.go#L70)):*
> ```Go
> $bin sql -d old -e "INSERT INTO testing_old values (1, true, 'hello', decimal '3.14159', 3.14159, NOW(), interval '1h')"
> $bin sql -d old -e "INSERT INTO testing_old values (2, false, 'world', decimal '0.14159', 0.14159, NOW(), interval '234h45m2s234ms')"
> $bin sql -d old -e "SELECT i, b, s, d, f, v, extract(epoch FROM t) FROM testing_old" > old.everything
> ```

What's up with this?

---

*[pkg/sql/parser/aggregate_builtins.go, line 74 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWNNpJYa_wOL4Xo3fd:-KWWNNpJYa_wOL4Xo3fe:bhi4bcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/aggregate_builtins.go#L74)):*
> ```Go
> var Aggregates map[string][]Builtin
> 
> var _ = setupBuiltins(map[string][]Builtin{
> ```

I'm confused why we're assigning things to `var _`. If we want static initilization, the idiomatic way to do that is to have an `init` method.

---

*[pkg/sql/parser/builtins.go, line 186 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWOWCJsQfFVxB04bzO:-KWWOWCJsQfFVxB04bzP:b-ktezek) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/builtins.go#L186)):*
> ```Go
> 			Aggregates[uname] = def
> 		}
> 		fdef := &FunctionDefinition{Name: uname, Definition: def}
> ```

I'd strongly lean towards storing `name` here and having the lower case name be the one in the error. That's what PG does, and that's what makes more sense in light of issues like #8862. (sorry if that means changing a bunch of tests)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-:-KWWM8Wa6CYG36ZfCk1L:b-uxc00j)*

**Comment by nvanbenschoten** [comment]
EDIT: Please ignore the message above, I thought I removed that. It's touched upon below with the upper case vs. lower case error reporting.

---

Review status: 16 of 29 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-:-KWWPCVxp5UX06eY8Xel:b-mjuqg3)*

**Comment by knz** [comment]
Review status: 16 of 29 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/reference_test.go, line 70 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWNHKsYfQ7dgNv4ssx:-KWXjtJZLTb-QaYnwhVH:b-r5r96z) ([raw file](https://github.com/cockroachdb/cockroach/blob/2257842790704ae55ecbf41ba2b9768198f00365/pkg/acceptance/reference_test.go#L70)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> What's up with this?
</details>
The test compares the results of the SELECT; however the SELECT also prints out column headers. Since the columns are named after the expressions, a function call is normalized to uppercase (or lowercase after your suggested change). I surmise we want to avoid that and define a stable column name in all cases.

---

*[pkg/sql/parser/aggregate_builtins.go, line 74 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWNNpJYa_wOL4Xo3fd:-KWXk8-vpRLi5A-jkALJ:b-iippa7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/aggregate_builtins.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I'm confused why we're assigning things to `var _`. If we want static initilization, the idiomatic way to do that is to have an `init` method.
</details>
Yes but the order init functions is run is not deterministic! 
Prior to this change we're writing to the Builtins array both here and in builtins.go, in both their init() functions (plus the array definition in window.go). I wanted a way to ensure the funDefs initializion code was guaranteed to run after the Builtins array is stable, and I could find one. This new way is the next best thing I found. Let me know if you have a better idea.

---

*[pkg/sql/parser/builtins.go, line 186 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWOWCJsQfFVxB04bzO:-KWXkdvSmyaAwNz4egsP:bvcnwpi) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/builtins.go#L186)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> I'd strongly lean towards storing `name` here and having the lower case name be the one in the error. That's what PG does, and that's what makes more sense in light of issues like #8862. (sorry if that means changing a bunch of tests)
</details>
I'm ok with changing the test (a simple revert is easy enough) but I found some messages are more difficult to read with every word in lowercase.

Would you be ok with adding parentheses after lowercase function names in error messages? Like e.g. "cannot use OVER with min()" instead of "OVER with min"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595)*

**Comment by nvanbenschoten** [comment]
Review status: 13 of 29 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/aggregate_builtins.go, line 74 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWNNpJYa_wOL4Xo3fd:-KWdxmuL-cdfLyH1HLXw:b40vmnt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/aggregate_builtins.go#L74)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Yes but the order init functions is run is not deterministic! 
> Prior to this change we're writing to the Builtins array both here and in builtins.go, in both their init() functions (plus the array definition in window.go). I wanted a way to ensure the funDefs initializion code was guaranteed to run after the Builtins array is stable, and I could find one. This new way is the next best thing I found. Let me know if you have a better idea.
</details>
What funDefs initialization code? And why does it need to be run before the Builtins array is stable?

---

*[pkg/sql/parser/builtins.go, line 186 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWOWCJsQfFVxB04bzO:-KWdy2JLNy5uYVsxC7Hj:b-7myast) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/builtins.go#L186)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I'm ok with changing the test (a simple revert is easy enough) but I found some messages are more difficult to read with every word in lowercase.
> 
> Would you be ok with adding parentheses after lowercase function names in error messages? Like e.g. "cannot use OVER with min()" instead of "OVER with min"?
</details>
Yeah I like the lower case with parentheses the best.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595)*

**Comment by knz** [comment]
Review status: 13 of 29 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/aggregate_builtins.go, line 74 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWNNpJYa_wOL4Xo3fd:-KWiFA4I1OJBWo-WYblk:b-7vl9yn) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/aggregate_builtins.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> What funDefs initialization code? And why does it need to be run before the Builtins array is stable?
</details>
I'm sorry I did not express myself properly.
The problem is that the following 3 things need to happen:
1) the aggregate and window builtins must migrate to the Builtins array
2) all the Builtins entries must be aliased to uppercase
3) the `funDefs` array must be populated.

The question from there is: Where do you place the code that does 2 and 3? 

If I choose to preserve the previous structure (separate init functions for aggregates.go, builtins.go and window_builtins.go) then there will be duplicate code.

With the proposed structure, each invocation of `setupBuiltins` performs all 3 steps for that subset of the builtins that is given to it as parameter.

---

*[pkg/sql/parser/builtins.go, line 186 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWOWCJsQfFVxB04bzO:-KWiFtkWkBEHU3JBSiCq:bim2pwq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/builtins.go#L186)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Yeah I like the lower case with parentheses the best.
</details>
Ok, will do.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595)*

**Comment by knz** [comment]
Review status: 13 of 29 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/sql/parser/builtins.go, line 186 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWOWCJsQfFVxB04bzO:-KWiWnAkcvjH3GY5lsIP:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/builtins.go#L186)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Ok, will do.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595)*

**Comment by nvanbenschoten** [comment]
Reviewed 29 of 29 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/parser/aggregate_builtins.go, line 74 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWNNpJYa_wOL4Xo3fd:-KWnzxkhFRX6_MS9r4e5:b-ic4si1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/aggregate_builtins.go#L74)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> I'm sorry I did not express myself properly.
> The problem is that the following 3 things need to happen:
> 1) the aggregate and window builtins must migrate to the Builtins array
> 2) all the Builtins entries must be aliased to uppercase
> 3) the `funDefs` array must be populated.
> 
> The question from there is: Where do you place the code that does 2 and 3? 
> 
> If I choose to preserve the previous structure (separate init functions for aggregates.go, builtins.go and window_builtins.go) then there will be duplicate code.
> 
> With the proposed structure, each invocation of `setupBuiltins` performs all 3 steps for that subset of the builtins that is given to it as parameter.
> 
> 
</details>
How about turning the `init` functions in `aggregate_builtins.go` and `window_builtins.go` into regular functions (eg. `initAggregateBuiltins()`) and having a single `init` method here that calls both of those before performing the `funDefs` population on the `Builtins` map? That way there will be little to no duplication, and the order of initialization will be deterministic.

Also, it looks like `Builtins` population wasn't removed from `window_builtins.go`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595)*

**Comment by knz** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/parser/aggregate_builtins.go, line 74 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWWNNpJYa_wOL4Xo3fd:-KWoC517z7vmh8KbHZne:b57vytc) ([raw file](https://github.com/cockroachdb/cockroach/blob/1ddca9a30b6a3c8ea418306eb38d6fdac2a3edeb/pkg/sql/parser/aggregate_builtins.go#L74)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> How about turning the `init` functions in `aggregate_builtins.go` and `window_builtins.go` into regular functions (eg. `initAggregateBuiltins()`) and having a single `init` method here that calls both of those before performing the `funDefs` population on the `Builtins` map? That way there will be little to no duplication, and the order of initialization will be deterministic.
> 
> Also, it looks like `Builtins` population wasn't removed from `window_builtins.go`.
</details>
Done.
Thanks for the hint!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595)*

**Comment by nvanbenschoten** [comment]
:lgtm_strong: 

---

Reviewed 5 of 14 files at r5.
Review status: 23 of 32 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[pkg/sql/parser/builtins.go, line 179 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWoKWN5A1w39lqGYY7s:-KWoKWN5A1w39lqGYY7t:bk35os4) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd60481f78936098cb23c0081a0403af561b00ba/pkg/sql/parser/builtins.go#L179)):*
> ```Go
> 		uname := strings.ToUpper(name)
> 		Builtins[uname] = def
> 		if def[0].class == AggregateClass {
> ```

This seems out of place. Why not perform this in `initAggregateBuiltins` (if it's even needed).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-:-KWoLpIk3a3WdnGzwe1l:b-uwkowd)*

**Comment by knz** [comment]
TFYR

---

Review status: 23 of 32 files reviewed at latest revision, 1 unresolved discussion.

---

*[pkg/sql/parser/builtins.go, line 179 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWoKWN5A1w39lqGYY7s:-KWoSRmsSR2wnPoO_82b:b-2mksln) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd60481f78936098cb23c0081a0403af561b00ba/pkg/sql/parser/builtins.go#L179)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> This seems out of place. Why not perform this in `initAggregateBuiltins` (if it's even needed).
</details>
Well because I wouldn't find a way to edit the Aggregates array in-place, also this way the upcasing only happens in one place for everything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-:-KWoSaBv1ZDWoTvziy8J:bb73zww)*

**Comment by nvanbenschoten** [comment]
Review status: 23 of 32 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/builtins.go, line 179 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWoKWN5A1w39lqGYY7s:-KWoSs9OE7SwzhnDDh6k:b-xg9wwy) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd60481f78936098cb23c0081a0403af561b00ba/pkg/sql/parser/builtins.go#L179)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> Well because I wouldn't find a way to edit the Aggregates array in-place, also this way the upcasing only happens in one place for everything.
</details>
Does it need to be uppercased? It didn't before.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595)*

**Comment by knz** [comment]
Review status: 23 of 32 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/sql/parser/builtins.go, line 179 at r6](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595#-KWoKWN5A1w39lqGYY7s:-KWs9YlrpHizO_Dm2smc:bjb2e2l) ([raw file](https://github.com/cockroachdb/cockroach/blob/cd60481f78936098cb23c0081a0403af561b00ba/pkg/sql/parser/builtins.go#L179)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Does it need to be uppercased? It didn't before.
</details>
Ah not any more that we are normalizing to lower case. Thanks for pushing me to investigate.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/10595)*

**Pull request merged**
