### PR TITLE
ui: fix statements page

### PR DESCRIPTION
**Pull request by vladlos**
fix typo, that breaks statements page loading

Release note (ui): fix typo, that breaks statements page loading

### CODE REVIEW

**Review by kscurtis — APPROVED** [review]

**Comment by vilterp** [comment]
An easy mistake to make. Seems like this should be a type error, though. Why didn't this fail typechecking in CI? 🤔 Any ideas @nathanstilwell?

**Comment by elkmaster** [comment]
current version of typescript does not understand connected props with such syntax. this approach https://github.com/DefinitelyTyped/DefinitelyTyped/issues/29759 may help, but it also has lack of strictness in some edge cases.

**Comment by nathanstilwell** [comment]
bors merge

**Comment by nathanstilwell** [comment]
@vilterp - @elkmaster is right, I don't think we have (clearly we don't) type checking for redux `connect`. I'll look into what Vlad posted on DefinitelyTyped, but off the top of my head I'm not very familiar with Redux types.

**Pull request merged**
