### PR TITLE
sql: Remove printing qualified name expressions twice

### PR DESCRIPTION
**Pull request by nvb**
```
name                old time/op    new time/op   delta
Scan1_Cockroach-4     267µs ± 2%     265µs ± 1%    ~      (p=0.297 n=9+9)

name               old alloc/op   new alloc/op   delta
Scan1_Cockroach-4    11.1kB ± 1%    10.8kB ± 1%   -2.10%  (p=0.000 n=10+10)

name               old allocs/op  new allocs/op  delta
Scan1_Cockroach-4       222 ± 1%       214 ± 0%   -3.55%  (p=0.000 n=10+10)
```

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4307)

### CODE REVIEW

**Comment by dt** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/select.go, line 381 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307#-KACLWZx6hri2y7Gm1Lx:-KACLWZx6hri2y7Gm1Ly:435550952) ([raw file](https://github.com/cockroachdb/cockroach/blob/0649eff60b3c2c323f2ca695f2fa7584bfd8b959/sql/select.go#L381)):*
Any particular advantage of the `switch` here over an `if`?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/select.go, line 381 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307#-KACLWZx6hri2y7Gm1Lx:-KACS0izemkXos6Un8UW:-1534736514) ([raw file](https://github.com/cockroachdb/cockroach/blob/0649eff60b3c2c323f2ca695f2fa7584bfd8b959/sql/select.go#L381)):*
No, I just usually find them easier to read for switching on types. Plus they're easier to grow later on.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/select.go, line 381 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307#-KACLWZx6hri2y7Gm1Lx:-KACSb37YhnMh8b18Swb:27045516) ([raw file](https://github.com/cockroachdb/cockroach/blob/0649eff60b3c2c323f2ca695f2fa7584bfd8b959/sql/select.go#L381)):*
+1 on using the type switch.

However, it's kind of odd to read this comment, since I can't tell where I should look to validate its claim.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/select.go, line 381 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307#-KACLWZx6hri2y7Gm1Lx:-KACZMGErDJWs5_MDaDw:616095428) ([raw file](https://github.com/cockroachdb/cockroach/blob/0649eff60b3c2c323f2ca695f2fa7584bfd8b959/sql/select.go#L381)):*
The qualified name resolution is what the rest of this function is doing, and is why this case is handled at the end.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/select.go, line 381 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307#-KACLWZx6hri2y7Gm1Lx:-KAC_TNs6YME2S1qGA0C:-1846904550) ([raw file](https://github.com/cockroachdb/cockroach/blob/0649eff60b3c2c323f2ca695f2fa7584bfd8b959/sql/select.go#L381)):*
Oh, so this could just be an `else` on the immediately following `if`? Doesn't that seem cleaner?

```go
if qname, ok := target.Expr.(*parser.QualifiedName); !ok {
  outputName = target.Expr.String()
} else {
<existing code>
}
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307)*

**Comment by nvanbenschoten** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[sql/select.go, line 381 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307#-KACLWZx6hri2y7Gm1Lx:-KACdkd5xloH2lgrSjEv:1580188073) ([raw file](https://github.com/cockroachdb/cockroach/blob/0649eff60b3c2c323f2ca695f2fa7584bfd8b959/sql/select.go#L381)):*
Not exactly. This code was surprisingly subtle but the `target.As != ""` needs precedence over the type check.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307)*

**Comment by tamird** [comment]
LGTM

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307#-:-KACfTywUA6ylyPHCgWX:676834233)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/select.go, line 377 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307#-KACi04RHCM7MVos0K9x:-KACi04RHCM7MVos0K9y:-1987118526) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c303bdd41247c94abce57d4eaf2502c34856e66/sql/select.go#L377)):*
I think this comment is referring to the code in the `else` branch?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307)*

**Comment by nvanbenschoten** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/select.go, line 377 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307#-KACi04RHCM7MVos0K9x:-KACuefsQnK3m9OXDmF4:1156309391) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c303bdd41247c94abce57d4eaf2502c34856e66/sql/select.go#L377)):*
How's that?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[sql/select.go, line 377 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307#-KACi04RHCM7MVos0K9x:-KACwblg6p4SEJeu7-yJ:-1868698381) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c303bdd41247c94abce57d4eaf2502c34856e66/sql/select.go#L377)):*
:lgtm_strong: 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4307)*

**Pull request merged**
