### PR TITLE
changefeedccl: Add jitter to aggregator flushes

### PR DESCRIPTION
**Pull request by miretskiy**
Add jitter, controlled by the `changefeed.aggregator.flush_jitter`
setting (default 10%) to the aggregator flush logic.
This helps mitigate the load place on the changefeed coordinator
by spreading out the time aggregators decide to flush.

Informs https://github.com/cockroachdb/cockroach/issues/114133

Release note: None

### CODE REVIEW

**Comment by sean-** [comment]
Fixes https://github.com/cockroachdb/cockroach/issues/114133

**Review by jayshrivastava — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114161)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @miretskiy)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 594 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114161#-Nity7V9DYrzP53JSI6h:-Nity7V9DYrzP53JSI6i:b-5kn77o) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3d4c677b54d7d737cc0071b5bc1ffab96ae8004/pkg/ccl/changefeedccl/changefeed_processors.go#L594)):*
> ```Go
> 	"add the following jitter as a fraction of min_checkpoint_frequency",
> 	0.1, /* 10% */
> 	settings.NonNegativeFloat,
> ```

Should disallow > 1.
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114161#-Nity33J5Okwlinzp7_b:-Nity33J5Okwlinzp7_c:b-wjhybu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3d4c677b54d7d737cc0071b5bc1ffab96ae8004/pkg/ccl/changefeedccl/changefeed_processors.go#L602)):*
> ```Go
> 		return d
> 	}
> 	return time.Duration(float64(d) * (1 + j))
> ```

If the flush frequency is 1 minute, this value will always be 1.1 minutes for all aggregators, so there's no jitter. We need rng.
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 780 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114161#-NityKuQ8s6hzzlN2OE_:-NityKuQ8s6hzzlN2OEa:blj1cyj) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3d4c677b54d7d737cc0071b5bc1ffab96ae8004/pkg/ccl/changefeedccl/changefeed_processors.go#L780)):*
> ```Go
> 		}()
> 		return ca.flushFrontier()
> 	}
> ```

A small test would be nice. We can add a callback knob which is called every time the aggregator flushes.

**Review by miretskiy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/114161)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jayshrivastava)

___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 594 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114161#-Nity7V9DYrzP53JSI6h:-NiyTyV_5eveP5EZ54a5:b3lj2hn) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3d4c677b54d7d737cc0071b5bc1ffab96ae8004/pkg/ccl/changefeedccl/changefeed_processors.go#L594)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

Should disallow > 1.
</blockquote></details>

ahh.. who am I to judge if you decide to have 2-3 or even 100x jitter?
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 602 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114161#-Nity33J5Okwlinzp7_b:-NiyU4c08iH9InZtHzP7:b-lemvbl) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3d4c677b54d7d737cc0071b5bc1ffab96ae8004/pkg/ccl/changefeedccl/changefeed_processors.go#L602)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

If the flush frequency is 1 minute, this value will always be 1.1 minutes for all aggregators, so there's no jitter. We need rng.
</blockquote></details>

that's because I had a brain malfunction.  Fixed.
___
*[`pkg/ccl/changefeedccl/changefeed_processors.go` line 780 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/114161#-NityKuQ8s6hzzlN2OE_:-NiyU98qAjClr_aSWR99:bny2xov) ([raw file](https://github.com/cockroachdb/cockroach/blob/c3d4c677b54d7d737cc0071b5bc1ffab96ae8004/pkg/ccl/changefeedccl/changefeed_processors.go#L780)):*
<details><summary><i>Previously, jayshrivastava (Jayant) wrote…</i></summary><blockquote>

A small test would be nice. We can add a callback knob which is called every time the aggregator flushes.
</blockquote></details>

Of course.

**Comment by miretskiy** [comment]
@jayshrivastava  -- ptal.

**Review by jayshrivastava — APPROVED** [review]

**Pull request merged**
