### PR TITLE
sqlsmith: make order-dependent aggregation functions deterministic

### LINKED ISSUE #83024: costfuzz failure: difference in concat_agg window function results
Reduced form of [this costfuzz failure](https://github.com/cockroachdb/cockroach/issues/81717#issuecomment-1147147668) is:

```sql
SET CLUSTER SETTING sql.stats.automatic_collection.enabled = false;

CREATE TABLE table1 (
  col1_0 INT8 NULL,
  col1_1 REGROLE NOT NULL,
  col1_2 BOOL NULL,
  col1_3 INT2 NULL,
  col1_4 STRING NOT NULL,
  col1_5 BIT(17) NOT NULL,
  col1_6 INT4 NOT NULL,
  col1_7 TIMESTAMP NOT NULL,
  col1_8 INT2 NULL,
  PRIMARY KEY (col1_4, col1_7 ASC, col1_1 DESC, col1_5 ASC, col1_6),
  UNIQUE (col1_3, col1_2 DESC),
  INDEX (col1_1 ASC, col1_8) WHERE (
                                    (
                                      (
                                        (table1.col1_8 = (-1) AND table1.col1_2)
                                        AND table1.col1_3 <= 0
                                      )
                                      AND table1.col1_6 = (-1)
                                    )
                                    AND table1.col1_7 > '-4713-11-24 00:00:00'
                                   )
                               AND table1.col1_0 > 2147483647,
  INDEX (col1_0 DESC, col1_8 DESC) WHERE table1.col1_0 >= 32767,
  UNIQUE (
    col1_5 DESC,
    col1_3 ASC,
    lower(col1_4) ASC,
    col1_6 DESC,
    col1_0 DESC,
    col1_2 ASC,
    col1_4 DESC,
    col1_8 DESC
  ) WHERE (
            (
              (((NOT table1.col1_2) OR table1.col1_8 < (-1)) OR table1.col1_6 >= 0)
              AND table1.col1_7 < '-4713-11-24 00:00:00'
            )
            OR table1.col1_4 <= e'\''
          )
      AND table1.col1_3 <= 1,
  INDEX (col1_8, col1_2 DESC, col1_4 ASC, col1_3 DESC, col1_7 DESC, col1_0 DESC, col1_6 DESC),
  FAMILY (col1_2),
  FAMILY (col1_8),
  FAMILY (col1_6),
  FAMILY (col1_5, col1_1, col1_0),
  FAMILY (col1_7)
);

ALTER TABLE table1
  INJECT STATISTICS '[{"avg_size": 0, "columns": ["col1_3"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 2835645428332221785, "histo_col_type": "INT2", "name": "__auto__", "null_count": 144904359820128795, "row_count": 8792450473244410607}, {"avg_size": 0, "columns": ["col1_6"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 6775706651097429889, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 8792450473244410607}, {"avg_size": 0, "columns": ["col1_8"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 8185713498755366596, "histo_buckets": [{"distinct_range": 0, "num_eq": 30000, "num_range": 0, "upper_bound": "-8530"}, {"distinct_range": 200, "num_eq": 6451778158798508932, "num_range": 200, "upper_bound": "-1"}, {"distinct_range": 7620426664667765000, "num_eq": 3008667158896670253, "num_range": 7620426664667764521, "upper_bound": "14452"}, {"distinct_range": 1412448057122352600, "num_eq": 7000, "num_range": 1967875260130639116, "upper_bound": "26012"}, {"distinct_range": 792117820960871600, "num_eq": 3153923422725146976, "num_range": 8179254772406641980, "upper_bound": "26215"}, {"distinct_range": 44329256.522211604, "num_eq": 40, "num_range": 1000000000, "upper_bound": "32024"}], "histo_col_type": "INT2", "name": "__auto__", "null_count": 2609007360056319673, "row_count": 8792450473244410607}, {"avg_size": 0, "columns": ["col1_4"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 7512423249709915011, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 8792450473244410607}, {"avg_size": 0, "columns": ["col1_5"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 2183739228962088931, "histo_buckets": [{"distinct_range": 0, "num_eq": 4894663348510381996, "num_range": 0, "upper_bound": "00000001011101111"}, {"distinct_range": 80000000000, "num_eq": 100000, "num_range": 80000000000, "upper_bound": "00011110100111110"}, {"distinct_range": 0, "num_eq": 7191341377154946226, "num_range": 4000000, "upper_bound": "00100110000011110"}, {"distinct_range": 1745675273088934700, "num_eq": 50000000000, "num_range": 5016738168423573353, "upper_bound": "01000111001010110"}, {"distinct_range": 0, "num_eq": 8813881930904719834, "num_range": 200000000, "upper_bound": "01011101011001110"}, {"distinct_range": 2295432160576390400, "num_eq": 9207893403340054467, "num_range": 4481459699953256512, "upper_bound": "01110000000001000"}, {"distinct_range": 440070998.40185046, "num_eq": 70000000000, "num_range": 700000000, "upper_bound": "11001110010101001"}, {"distinct_range": 0, "num_eq": 500000, "num_range": 0, "upper_bound": "11100111101010011"}], "histo_col_type": "BIT(17)", "name": "__auto__", "null_count": 0, "row_count": 8792450473244410607}, {"avg_size": 0, "columns": ["col1_7"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 6879920997147781222, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 8792450473244410607}, {"avg_size": 0, "columns": ["col1_0"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 7770400146463795814, "histo_buckets": [{"distinct_range": 0, "num_eq": 800000000, "num_range": 0, "upper_bound": "-8205128782161458636"}, {"distinct_range": 0, "num_eq": 2042697633031396187, "num_range": 5000000, "upper_bound": "-7812936227256431183"}, {"distinct_range": 9000000000, "num_eq": 40000, "num_range": 9000000000, "upper_bound": "-6612122703009741158"}], "histo_col_type": "INT8", "name": "__auto__", "null_count": 1494558236833540481, "row_count": 8792450473244410607}, {"avg_size": 0, "columns": ["col1_1"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 4430898258945554397, "histo_col_type": "", "name": "__auto__", "null_count": 0, "row_count": 8792450473244410607}, {"avg_size": 0, "columns": ["col1_2"], "created_at": "2000-01-01 00:00:00+00:00", "distinct_count": 780658195341626202, "histo_col_type": "", "name": "__auto__", "null_count": 2983023298723053532, "row_count": 8792450473244410607}]';

INSERT
  INTO table1 (col1_1, col1_2, col1_4, col1_5, col1_6, col1_7)
VALUES (
        847310153,
        true,
        e'\x10',
        B'11100111110000010',
        1122356067,
        '2010-05-30 14:42:42.000552'
       );

INSERT
  INTO table1
SELECT 7283603077408099527,
       0,
       true,
       (-17400),
       e'\U00002603',
       B'00100101010011010',
       (-620483107),
       '2025-11-02 04:23:12.000808'
 LIMIT 74;

INSERT
  INTO table1
SELECT 8400041801024410953,
       1888605199,
       true,
       (-29547),
       e'\'',
       B'00000000000000000',
       1113534463,
       '0001-01-01 00:00:00'
 LIMIT 73;

INSERT
  INTO table1 (
                                            col1_0,
                                            col1_1,
                                            col1_2,
                                            col1_3,
                                            col1_4,
                                            col1_5,
                                            col1_6,
                                            col1_7
                                           )
VALUES (
        4473668024872695533,
        0,
        true,
        (-19531),
        'D.U&WO`',
        B'11010001101111111',
        1119067721,
        '1971-02-02 04:53:49.000657'
       );

INSERT
  INTO table1 (col1_0, col1_1, col1_2, col1_4, col1_5, col1_6, col1_7)
VALUES (
        1694385328552230223,
        1328022167,
        NULL,
        e'#_\x01b\x07\b',
        B'10001000010010111',
        (-93810042),
        '2011-08-05 15:29:46.000115'
       );

UPDATE table1 AS tab_8550
   SET col1_1 = tab_8550.col1_1
 WHERE tab_8550.col1_2
 LIMIT 60;

  SELECT concat_agg(tab_77577.col1_4::STRING) OVER (
          PARTITION BY tab_77575.tableoid, tab_77575.col1_1 ORDER BY tab_77575.col1_6 ASC
         )::STRING AS col_161779,
         (-1737169242):::INT8 AS col_161780,
         2037724374:::OID AS col_161781,
         1513653682:::OID AS col_161782
    FROM defaultdb.public.table1 AS tab_77573
    JOIN defaultdb.public.table1 AS tab_77574 ON tab_77573.col1_0 = tab_77574.col1_0
    JOIN defaultdb.public.table1@table1_col1_3_col1_2_key AS tab_77575 ON tab_77573.col1_0
                                                                          = tab_77575.col1_0
    JOIN defaultdb.public.table1@[0] AS tab_77576
    JOIN defaultdb.public.table1@[0] AS tab_77577 ON tab_77576.crdb_internal_mvcc_timestamp
                                                     = tab_77577.crdb_internal_mvcc_timestamp ON
          tab_77575.tableoid = tab_77577.tableoid
          AND tab_77575.col1_0 = tab_77576.col1_0
          AND tab_77573.col1_0 = tab_77576.col1_0
   WHERE tab_77577.col1_2
GROUP BY tab_77577.col1_4, tab_77575.col1_1, tab_77575.col1_6, tab_77575.tableoid
  HAVING bool_and(tab_77576.col1_2::BOOL)::BOOL
ORDER BY tab_77575.col1_6 DESC;

SET testing_optimizer_random_cost_seed = 4516411882398307454;

  SELECT concat_agg(tab_77577.col1_4::STRING) OVER (
          PARTITION BY tab_77575.tableoid, tab_77575.col1_1 ORDER BY tab_77575.col1_6 ASC
         )::STRING AS col_161779,
         (-1737169242):::INT8 AS col_161780,
         2037724374:::OID AS col_161781,
         1513653682:::OID AS col_161782
    FROM defaultdb.public.table1 AS tab_77573
    JOIN defaultdb.public.table1 AS tab_77574 ON tab_77573.col1_0 = tab_77574.col1_0
    JOIN defaultdb.public.table1@table1_col1_3_col1_2_key AS tab_77575 ON tab_77573.col1_0
                                                                          = tab_77575.col1_0
    JOIN defaultdb.public.table1@[0] AS tab_77576
    JOIN defaultdb.public.table1@[0] AS tab_77577 ON tab_77576.crdb_internal_mvcc_timestamp
                                                     = tab_77577.crdb_internal_mvcc_timestamp ON
          tab_77575.tableoid = tab_77577.tableoid
          AND tab_77575.col1_0 = tab_77576.col1_0
          AND tab_77573.col1_0 = tab_77576.col1_0
   WHERE tab_77577.col1_2
GROUP BY tab_77577.col1_4, tab_77575.col1_1, tab_77575.col1_6, tab_77575.tableoid
  HAVING bool_and(tab_77576.col1_2::BOOL)::BOOL
ORDER BY tab_77575.col1_6 DESC;
```

The difference in results:

```
      col_161779     | col_161780  | col_161781 | col_161782
---------------------+-------------+------------+-------------
  '☃D.U&WO`'☃D.U&WO` | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`'☃D.U&WO` | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`'☃D.U&WO` | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
(9 rows)


Time: 14ms total (execution 13ms / network 0ms)
```

vs

```
      col_161779     | col_161780  | col_161781 | col_161782
---------------------+-------------+------------+-------------
  '☃D.U&WO`D.U&WO`'☃ | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`D.U&WO`'☃ | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`D.U&WO`'☃ | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
  '☃D.U&WO`          | -1737169242 | 2037724374 | 1513653682
(9 rows)


Time: 8ms total (execution 8ms / network 0ms)
```

Jira issue: CRDB-16801

Epic: CRDB-14914

### PR DESCRIPTION
**Pull request by michae2**
**cmd: add smith command**

Add a new top-level command `smith` which dumps randomly-generated
sqlsmith queries. This is useful for testing modifications to sqlsmith.

Assists: #83024

Release note: None

**sqlsmith: make order-dependent aggregation functions deterministic**

Some aggregation functions (e.g. string_agg) have results that depend
on the order of input rows. To make sqlsmith more deterministic, add
ORDER BY clauses to these aggregation functions whenever their argument
is a column reference. (When their argument is a constant, ordering
doesn't matter.)

Fixes: #83024

Release note: None

### CODE REVIEW

**Review by msirek — APPROVED** [review]
Thanks for making the new `smith` command!  The fix looks good.

> Reviewed 6 of 6 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84324#-:-N6s9-ho9gzgO3kikPkg:bhyej9z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @michae2)

___
*[`pkg/cmd/smith/main.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84324#-N6s8erQCjHgvdgbTlLt:-N6s8erQCjHgvdgbTlLu:b-jbqtsc) ([raw file](https://github.com/cockroachdb/cockroach/blob/91f1efe48b1e13affc7e7a8fcc374e7da6c2d576/pkg/cmd/smith/main.go#L35)):*
> ```Go
> 
> 	for {
> 		fmt.Print("\n", smither.Generate(), ";\n")
> ```

Maybe in the future we can add a command-line option to print a set number of statements.

**Review by michae2 — COMMENTED** [review]
TFYR!

bors r=msirek

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84324#-:-N6s_eSo5somgfmnW4Ov:bw8tmsh)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/cmd/smith/main.go` line 35 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/84324#-N6s8erQCjHgvdgbTlLt:-N6s_UOn0eT1jcUbSt3d:baab3e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/91f1efe48b1e13affc7e7a8fcc374e7da6c2d576/pkg/cmd/smith/main.go#L35)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Maybe in the future we can add a command-line option to print a set number of statements.
</blockquote></details>

Done. Also added some help text.

**Review by mgartner — APPROVED** [review]
:lgtm: The new `smith` command will be very useful!

I am slightly worried that the second commit (along with other recent changes) are reducing the efficacy of sqlsmith's in achieving its original goal - to find tests cases that cause panics. The more we constrain the output of sqlsmith to better support randomized correctness testing, the less effective it will become at randomized panic testing. Maybe should consider implementing two SQLSmith modes - one with almost no restrictions that can be used to catch panics, and one that is as restrictive as necessary to get deterministic results in randomized correctness tests.

> Reviewed 4 of 6 files at r1, 3 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84324#-:-N6slZ8R3osMlQLbALVR:b-hz8dfp)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @msirek)

**Review by msirek — COMMENTED** [review]
Maybe we can set a flag when running any of the tests which compare results, and only use the `ORDER BY` if that flag is `true`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84324#-:-N6snErZBy-90hGn6tA9:b-ad41ao)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @michae2 and @msirek)

**Review by michae2 — COMMENTED** [review]
Good point!

bors r-

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84324#-:-N6sq3t84SReDw-f2sJ7:boukkv2)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

___
*[`pkg/cmd/smith/main.go` line 65 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/84324#-N6skjxX1UfC3B6VTcZ9:-N6sq9T19TdtlDJKLmDC:b-lw4jma) ([raw file](https://github.com/cockroachdb/cockroach/blob/bd298385eab421557e1afa4322e2c247938dfc87/pkg/cmd/smith/main.go#L65)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

IIRC sqlsmith looks at the existing table schema to generate queries. What schema is used ins this case?
</blockquote></details>

public

**Comment by michae2** [comment]
@mgartner @msirek how would you feel if I extended `DisableImpureFns()` to also cover this?

**Comment by mgartner** [comment]
> public

Sorry, my question was not specific. I'm curious what tables SQLSmith is generating statements for when running this command. It doesn't seem like any tables would exist, unless they are being created somewhere here that I'm missing.

> @mgartner @msirek how would you feel if I extended DisableImpureFns() to also cover this?

Sounds good to me. Maybe rename it to reflect it's increase influence? `DisableNonDeterminism`?

**Review by msirek — COMMENTED** [review]
+1

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84324#-:-N6szv_01mf7JWVbrX1b:b32v57)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @msirek)

**Review by michae2 — COMMENTED** [review]
Ok, I went hog-wild and added to `smith`:
- passthrough of simple sqlsmith options
- option to connect to a database for schema info
- new `MutatingMode` for sqlsmith based on mutating smither from TLP / costfuzz / unoptimized-query-oracle
- ability to generate expressions instead of statements

To answer your question, @mgartner, without a db connection sqlsmith can only generate expressions, `SELECT` statements (over `VALUES` tables), `CREATE TABLE` statements, and probably a few other things. But no mutations.

As for the original issue, I extended `DisableImpureFns` to cover adding the `ORDER BY` and renamed it to `DisableNondeterministicFns`.

Since I changed so much, I'll wait for another look whenever you have time (no rush).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/84324#-:-N6tiiwFCOV93mULS3-V:b-8a7z5f)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner and @msirek)

**Review by msirek — APPROVED** [review]
Updates look good

**Comment by michae2** [comment]
Thanks!

bors r=msirek,mgartner

**Pull request merged**
