### PR TITLE
build: add bors.toml

### PR DESCRIPTION
**Pull request by couchand**
Teaches Bors to wait for a successful build on TeamCity before merging approved PRs to master.

Contributes to #22499
Release note (build change): Begin using Bors to automate merging PRs to master.

### CODE REVIEW

**Comment by couchand** [comment]
bors try

**Comment by knz** [comment]
Ok so Andrew please teach me a bit more about what I am supposed to see here and how you think I should evaluate this to do my review.

What does this toml file do?
Why is this 3-line, new file PR sufficient to make bors do things for us?
How does bors process this config file? When does it process it?
When bors "does something", is there a log of what has been done somewhere?

Also please accompany this PR with a wiki page on our github repo that explains what bors is, how it works, how it helps us, and what we should expect from it when it works properly. This last item is of particular importance because it also teaches us to detect when bors doesn't work properly.

**Comment by knz** [comment]
(I do want to complement my previous comment by saying I am positively excited about this and I really want us to try it out to see if it indeed reduces merge skews. Thanks Andrew for taking the lead.)

**Comment by benesch** [comment]
I think we should hold off on writing any docs until we're actually sure we want to move forward with Bors.

@knz, a bors.toml functions much like a .travis.yml/.circle.yml in that you can install a GitHub application, in this case https://github.com/organizations/cockroachdb/settings/installations/115054, that does magic when the file is present.

We should discuss whether we want to host our own Bors. Do we trust the folks running the public Bors not to abuse their commit bit? There's also an ominous warning at the bottom of app.bors.tech:

> This service is provided for free on a best-effort basis.

Anyway, the code here (obviously) LGTM, but I'd like at least @bdarnell to weigh in on the self-hosting question before we merge.

**Comment by bdarnell** [comment]
> Do we trust the folks running the public Bors not to abuse their commit bit?

Who are those people? There's not even an "about" page there. I had been assuming we'd have to self-host this.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/24100#-:-L881j2cmzVyaRLQxfQB:by9kglp)*

**Comment by benesch** [comment]
Agreed, it’s weird.

**Comment by couchand** [comment]
@knz sorry for the lack of context.  @benesch you're right we shouldn't "merge" docs until we're ready to move forward, but it probably makes sense to start writing them to at least add some context to this PR.  I'll add a first draft here this afternoon, and I've added docs to the todo list on #22499.

@benesch @bdarnell I had thought that using the public instance would be the quickest way to get started, and we could move to self-hosted in the future.  But after reconsidering it, the best course of action seems to be just to self-host from the start.  I've removed the public instance access and updated #22499 to reflect the new plan.

> Who are those people?

As far as I can tell it's basically just Michael Howell himself (he commented on the issue btw) running the public instance to support open-source development.

> Do we trust the folks running the public Bors not to abuse their commit bit?

FWIW there are some not insignificant projects that trust the public instance: intellij-rust/intellij-rust, nix-rust/nix, gfx-rs/gfx to name a few recent examples from the newsletter.

**Comment by couchand** [comment]
bors try

**Comment by couchand** [comment]
this should fail due to the label `do-not-merge`

bors r+

**Comment by couchand** [comment]
bors r=benesch

**Pull request merged**
