### PR TITLE
opt: fix INSERT ON CONFLICT for partial index predicates with virtual columns

### PR DESCRIPTION
**Pull request by mgartner**
#### optbuilder: move partial index tests to new file

This commit aggregates all optbuilder tests related to partial indexes
into a single test file. This eliminates duplication of CREATE TABLE
statements across files and slows the growth of the insert, delete,
update, and upsert test files.

Release note: None

#### optbuilder: rename table in partial index tests

Release note: None

#### optbuilder: eliminate redundant table in partial index tests

Release note: None

#### optbuilder: eliminate redundant computed column table in partial index tests

Release note: None

#### opt: fix INSERT ON CONFLICT for partial index predicates with virtual columns

The `Builder.buildPartialIndexPredicate` function assumes that the input
`tableScope.expr`, which is built by `Builder.buildScan`, is always a
Scan. The introduction of virtual computed columns breaks this
assumption because `buildScan` creates a Project on top of a Scan if the
underlying table has virtual columns.

The manifestation of this bug is that the following INSERT succeeds. The
correct behavior is for the INSERT to error because an arbiter predicate
is not supplied in the ON CONFLICT clause, and no arbiter index on b can
be chosen.

    CREATE TABLE t (
      a INT PRIMARY KEY,
      b INT,
      v INT AS (b + 1) VIRTUAL,
      UNIQUE INDEX (b) WHERE v > 0
    )

    INSERT INTO t VALUES (1, 1) ON CONFLICT (b) DO NOTHING

There is no release note because this bug is only present with virtual
computed columns which are still gated behind an experimental session
setting.

Release note: None

#### opt: add prune column tests for partial index predicates with virtual columns

Release note: None

### CODE REVIEW

**Comment by mgartner** [comment]
Apologies for the large diff — it's mostly from the first four housekeeping commits.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59816#-:-MSibDzEET16ah-ma5TV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/optbuilder/insert.go, line 1352 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59816#-MSiZumBAusvo2oTtir6:-MSiZumBAusvo2oTtir7:bbg64e6) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f45425f2c4780e7f58ce190de8618ce9b7bcfa9/pkg/sql/opt/optbuilder/insert.go#L1352)):*
> ```Go
> 			// constructs a Project on top of the Scan. This is problematic when
> 			// building arbiter predicates because it relies on tableScope.expr
> 			// being a Scan in order to normalize the arbiter predicate. So, if
> ```

It's a little strange what we're doing here. We are going to build the Select on top of a Scan which does not produce the virtual columns. I guess any virtual columns in the predicate are going to be treated as "outer" columns?
___
*[pkg/sql/opt/optbuilder/testdata/partial-indexes, line 1034 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59816#-MSi_aKd8oms6d5L25Hy:-MSi_aKd8oms6d5L25Hz:bi2r6a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f45425f2c4780e7f58ce190de8618ce9b7bcfa9/pkg/sql/opt/optbuilder/testdata/partial-indexes#L1034)):*
> ```
>            └── column3:7 = 'bar' [as=partial_index_put2:19]
> 
> # Error when no arbiter is found because a the arbiter predicate in the query
> ```

[nit] because the
___
*[pkg/sql/opt/optbuilder/testdata/partial-indexes, line 1527 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59816#-MSi_U_388c7p33mOW9S:-MSi_U_388c7p33mOW9T:bi2r6a9) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f45425f2c4780e7f58ce190de8618ce9b7bcfa9/pkg/sql/opt/optbuilder/testdata/partial-indexes#L1527)):*
> ```
>            └── column11:11 = 'bar' [as=partial_index_put4:28]
> 
> # Error when no arbiter is found because a the arbiter predicate in the query
> ```

[nit] because the

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/59816)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde and @rytaft)

___
*[pkg/sql/opt/optbuilder/insert.go, line 1352 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59816#-MSiZumBAusvo2oTtir6:-MSiqshQ5CUXAADt-Jtc:b-a2dl68) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f45425f2c4780e7f58ce190de8618ce9b7bcfa9/pkg/sql/opt/optbuilder/insert.go#L1352)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

It's a little strange what we're doing here. We are going to build the Select on top of a Scan which does not produce the virtual columns. I guess any virtual columns in the predicate are going to be treated as "outer" columns?
</blockquote></details>

Ya I don't love it. I'd like to try your `(Select (FakeRel))` suggestion in a future PR, but for now I think this is a good temporary solution. I'll point out that we're already doing this in [`buildScan` by calling `addPartialIndexPredicatesForTable` before constructing the Project for virtual columns](https://github.com/cockroachdb/cockroach/blob/21439d49f284e21323da4a0a8fa424b69df029a1/pkg/sql/opt/optbuilder/select.go#L542). I assume things work ok because the normalization rules we need to run involve just the Select and its filters, not its input.
___
*[pkg/sql/opt/optbuilder/testdata/partial-indexes, line 1034 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59816#-MSi_aKd8oms6d5L25Hy:-MSirXatEh0OY3boiUb0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f45425f2c4780e7f58ce190de8618ce9b7bcfa9/pkg/sql/opt/optbuilder/testdata/partial-indexes#L1034)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] because the
</blockquote></details>

Done.
___
*[pkg/sql/opt/optbuilder/testdata/partial-indexes, line 1527 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59816#-MSi_U_388c7p33mOW9S:-MSirYACBuWguBR8Umob:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f45425f2c4780e7f58ce190de8618ce9b7bcfa9/pkg/sql/opt/optbuilder/testdata/partial-indexes#L1527)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] because the
</blockquote></details>

Done.

**Comment by RaduBerinde** [comment]
___
*[pkg/sql/opt/optbuilder/insert.go, line 1352 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/59816#-MSiZumBAusvo2oTtir6:-MSiwnmE6NY3PNaMK2i9:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/9f45425f2c4780e7f58ce190de8618ce9b7bcfa9/pkg/sql/opt/optbuilder/insert.go#L1352)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Ya I don't love it. I'd like to try your `(Select (FakeRel))` suggestion in a future PR, but for now I think this is a good temporary solution. I'll point out that we're already doing this in [`buildScan` by calling `addPartialIndexPredicatesForTable` before constructing the Project for virtual columns](https://github.com/cockroachdb/cockroach/blob/21439d49f284e21323da4a0a8fa424b69df029a1/pkg/sql/opt/optbuilder/select.go#L542). I assume things work ok because the normalization rules we need to run involve just the Select and its filters, not its input.
</blockquote></details>

:thumbsup:

**Comment by mgartner** [comment]
TFTR!

bors r+

**Pull request merged**
