### PR TITLE
sql: fix EXPLAIN(TRACE).

### LINKED ISSUE #7082: stability: crash on explain (trace)
Seen on the registration cluster when trying to diagnose a slow query.
Query worked fine without `explain` entirely, and with a bare `explain`, but failed on `explain (trace)` 

built sha: `5f666c8`

query run:
```
explain (trace) SELECT * FROM registration.clusters LIMIT 10;
```

trace:
```
panic: runtime error: index out of range

goroutine 17911480 [running]:
panic(0x182ca00, 0xc82000e040)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/cockroachdb/cockroach/sql.(*valuesNode).ValuesLess(0xc878766000, 0xc83e847560, 0x6, 0x6, 0xc83e846f60, 0x6, 0x6, 0x18500000000)
        /go/src/github.com/cockroachdb/cockroach/sql/values.go:208 +0x1ba
github.com/cockroachdb/cockroach/sql.(*valuesNode).Less(0xc878766000, 0x6, 0x0, 0x19a06d0)
        /go/src/github.com/cockroachdb/cockroach/sql/values.go:199 +0xfe
sort.quickSort(0x7f71483a05d0, 0xc878766000, 0x0, 0xa, 0x8)
        /usr/local/go/src/sort/sort.go:210 +0x18d
sort.Sort(0x7f71483a05d0, 0xc878766000)
        /usr/local/go/src/sort/sort.go:229 +0x74
github.com/cockroachdb/cockroach/sql.(*valuesNode).SortAll(0xc878766000)
        /go/src/github.com/cockroachdb/cockroach/sql/values.go:265 +0x51
github.com/cockroachdb/cockroach/sql.(*sortAllStrategy).Finish(0xc8c9d71ed8)
        /go/src/github.com/cockroachdb/cockroach/sql/sort.go:409 +0x24
github.com/cockroachdb/cockroach/sql.(*sortNode).Next(0xc8ad810be0, 0xc82e2877a0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/sort.go:328 +0x5e7
github.com/cockroachdb/cockroach/sql.(*explainTraceNode).Next(0xc8758b68a0, 0xc844a5d7a0, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/trace.go:75 +0x144
github.com/cockroachdb/cockroach/sql.(*Executor).execStmt(0xc8202cf7a0, 0x7f71483a0118, 0xc83d538840, 0xc82ac3d090, 0xc83d538801, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/sql/executor.go:958 +0x736
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtInOpenTxn(0xc8202cf7a0, 0x7f71483a0118, 0xc83d538840, 0xc82ac3d090, 0x101, 0xc82ac3d028, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/sql/executor.go:826 +0x545
github.com/cockroachdb/cockroach/sql.(*Executor).execStmtsInCurrentTxn(0xc8202cf7a0, 0xc8253a5c90, 0x1, 0x1, 0xc82ac3d090, 0xc82ac3d028, 0x2160101, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/sql/executor.go:605 +0x5da
github.com/cockroachdb/cockroach/sql.runTxnAttempt(0xc8202cf7a0, 0xc82ac3d090, 0x1, 0xc82ac3d028, 0xc8b4bdca40, 0xc8253a5c90, 0x1, 0x1, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/sql/executor.go:535 +0x18d
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest.func1(0xc8c9356000, 0xc8b4bdca40, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/executor.go:444 +0x34a
github.com/cockroachdb/cockroach/client.(*Txn).Exec(0xc8c9356000, 0xc8a6710101, 0x1455dba8e7f3bbaf, 0x0, 0xc8a6716280, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/client/txn.go:527 +0x2eb
github.com/cockroachdb/cockroach/sql.(*Executor).execRequest(0xc8202cf7a0, 0x7f732ce23178, 0xc8afa0e2c0, 0xc82ac3d000, 0xc8230cf092, 0x3d, 0x0, 0x0, 0x0, 0x7f732ce6ce00)
        /go/src/github.com/cockroachdb/cockroach/sql/executor.go:449 +0x962
github.com/cockroachdb/cockroach/sql.(*Executor).ExecuteStatements(0xc8202cf7a0, 0x7f732ce23178, 0xc8afa0e2c0, 0xc82ac3d000, 0xc8230cf092, 0x3d, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/sql/executor.go:338 +0xe5
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).executeStatements(0xc8b4707e00, 0x7f732ce23178, 0xc8afa0e2c0, 0xc8230cf092, 0x3d, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:648 +0xb2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).handleSimpleQuery(0xc8b4707e00, 0x7f732ce23178, 0xc8afa0e2c0, 0xc8b4707e28, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:325 +0xf2
github.com/cockroachdb/cockroach/sql/pgwire.(*v3Conn).serve(0xc8b4707e00, 0xc848f35460, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/v3.go:281 +0x1095
github.com/cockroachdb/cockroach/sql/pgwire.(*Server).ServeConn(0xc82036cfc0, 0x7f732ce73a68, 0xc8232af200, 0x0, 0x0)
        /go/src/github.com/cockroachdb/cockroach/sql/pgwire/server.go:224 +0x99b
github.com/cockroachdb/cockroach/server.(*Server).Start.func8.1(0x7f732ce51e20, 0xc9351e0840)
        /go/src/github.com/cockroachdb/cockroach/server/server.go:361 +0x42
github.com/cockroachdb/cockroach/util.(*Server).ServeWith.func1(0xc820116148, 0x7f732ce51e20, 0xc9351e0840, 0xc820336010)
        /go/src/github.com/cockroachdb/cockroach/util/net.go:131 +0x62
created by github.com/cockroachdb/cockroach/util.(*Server).ServeWith
        /go/src/github.com/cockroachdb/cockroach/util/net.go:133 +0x333
```

### PR DESCRIPTION
**Pull request by knz**
Fixes #7082.

Summary:
- EXPLAIN(TRACE)'s queryPlan was incorrect; is now fixed.
- EXPLAIN can now be EXPLAINed (`EXPLAIN EXPLAIN(TRACE) ...`) so as to enable a test for the fix above.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/7088)

### CODE REVIEW

**Comment by knz** [comment]
cc @dt @tschottdorf

**Comment by tamird** [comment]
> 778cea1: sql: Fix EXPLAIN(TRACE).
> 
> The changes pertaining to #6735 have inverter the logical order of
> explainTraceNode and sortNode. This caused a panic because the
> sortNode was instructed to sort using a column that did not exist in
> its child node.

s/inverter/inverted/

Also can you reference a commit rather than a PR? I can't `git show #6735` :(.

> This patch addresses the issue by restoring the correct logical order
> between the two nodes.
> 
> Additionally, the patch changes the rendering of "cumulative time"
> that was incorrect: since the "earliestTime" may change between
> different batches of debugValues provided by the child node, the
> computation of cumulative time was incorrect. Instead this patch
> restores a useful cumulative time displays that uses a common single
> timestamp computed during the explainTraceNode's initialization.

s/displays/display/


> This patch is a follow-up to the previous one, adding a test to check
that EXPLAIN(TRACE) runs as intended.

I think this paragraph can simply be deleted.

:lgtm:



---

Reviewed 3 of 3 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/trace.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088#-KJgZ_TeGr9eUWg612jS:-KJgZ_TfMTeDRPqs1-Sg:-1714498287) ([raw file](https://github.com/cockroachdb/cockroach/blob/778cea140d7e1872559fe9cb77a380c124014d59/sql/trace.go#L50)):*
> ```Go
> 	{Name: "Event", Typ: parser.TypeString},
> }, debugColumns...)
> var traceOrdering = []columnOrderInfo{
> ```

newline before this?

---

*[sql/trace.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088#-KJgZWitZAYrtcxpKFv2:-KJgZWitZAYrtcxpKFv3:-1720259999) ([raw file](https://github.com/cockroachdb/cockroach/blob/778cea140d7e1872559fe9cb77a380c124014d59/sql/trace.go#L56)):*
> ```Go
> 
> func makeTraceNode(plan planNode, txn *client.Txn) planNode {
> 	explain := &explainTraceNode{
> ```

nit: I think you can get rid of these intermediates

---

*[sql/parser/sql.y, line 953 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088#-KJg_OhMHdCV7D72u6S5:-KJg_OhMHdCV7D72u6S6:1116589365) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85124b8c43ed424eb91912dece47c5a1fbf7a0b/sql/parser/sql.y#L953)):*
> ```Yacc
> | update_stmt
> | delete_stmt
> | explain_stmt
> ```

does this need a parser test?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088#-:-KJgYdP71YaM0wNPwPRk:2026328620)*

**Comment by knz** [comment]
The commit text was modified as requested.

<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> > 778cea1: sql: Fix EXPLAIN(TRACE).
> > 
> > The changes pertaining to #6735 have inverter the logical order of
> > explainTraceNode and sortNode. This caused a panic because the
> > sortNode was instructed to sort using a column that did not exist in
> > its child node.
> 
> s/inverter/inverted/
> 
> Also can you reference a commit rather than a PR? I can't `git show #6735` :(.
> 
> > This patch addresses the issue by restoring the correct logical order
> > between the two nodes.
> > 
> > Additionally, the patch changes the rendering of "cumulative time"
> > that was incorrect: since the "earliestTime" may change between
> > different batches of debugValues provided by the child node, the
> > computation of cumulative time was incorrect. Instead this patch
> > restores a useful cumulative time displays that uses a common single
> > timestamp computed during the explainTraceNode's initialization.
> 
> s/displays/display/
> 
> 
> > This patch is a follow-up to the previous one, adding a test to check
> that EXPLAIN(TRACE) runs as intended.
> 
> I think this paragraph can simply be deleted.
> 
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks pending.

---

*[sql/trace.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088#-KJgZ_TeGr9eUWg612jS:-KJg_xeMwbsgOzQI8fo3:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/778cea140d7e1872559fe9cb77a380c124014d59/sql/trace.go#L50)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> newline before this?
</details>
Done.

---

*[sql/trace.go, line 56 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088#-KJgZWitZAYrtcxpKFv2:-KJg_yPnq5CS2KjAkTgO:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/778cea140d7e1872559fe9cb77a380c124014d59/sql/trace.go#L56)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> nit: I think you can get rid of these intermediates
</details>
Done.

---

*[sql/parser/sql.y, line 953 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088#-KJg_OhMHdCV7D72u6S5:-KJgauVQEOvg4u7yw-aR:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c85124b8c43ed424eb91912dece47c5a1fbf7a0b/sql/parser/sql.y#L953)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> does this need a parser test?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088#-:-KJgaP5n6aCiVqa_b2fn:148051596)*

**Comment by tamird** [comment]
Reviewed 6 of 6 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088)*

**Comment by dt** [comment]
:lgtm:

<details><summary><i>Previously, knz (kena) wrote…</i></summary>
> The commit text was modified as requested.
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088#-:-KJgciMll-mcu8Nt42Va:1417088721)*

**Comment by tschottdorf** [comment]
Reviewed 3 of 3 files at r1, 6 of 6 files at r2, 6 of 6 files at r3, 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088)*

**Comment by RaduBerinde** [comment]
:lgtm:

<details><summary><i>Previously, dt (David Taylor) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: 6 of 7 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/7088#-:-KJgxoIWUu1RXgLcmu70:1417088721)*

**Pull request merged**
