### PR TITLE
sql: better memory accounting in windower

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, the size of the bucket key wasn't taken into account. Also,
now nil out the partition map when closing the windower to ensure memory
is freed in a timely manner.

Might help with #30617.

Release note: None

### CODE REVIEW

**Comment by jordanlewis** [comment]
Ping @asubiotto, PTAL.

**Review by asubiotto — APPROVED** [review]
Woops, missed this. LGTM though I doubt the key accounting per partition is to blame for the associated issue.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30776#-:-LNl7Bqq6qbarH1q8kbJ:b-txne2z)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by jordanlewis** [comment]
Yeah, I'm pretty sure it's not related, but might as well fix it.

**Comment by knz** [comment]
wouldn't hurt to backport this

**Pull request merged**
