### PR TITLE
catalog: improve role validation for descriptors.

### PR DESCRIPTION
**Pull request by rafiss**
Make it so the node user is always assumed to exist.

Also, add a check for the owner of the descriptor.

informs https://github.com/cockroachdb/cockroach/issues/122552
Release note: None

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
Just one minor comment

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124772#-:-Nz-xzSwAlzR6J7Fi2BS:bsjsx63)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 6183 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124772#-Nz-xpGG3o4vTe8IrTOR:-Nz-xpGG3o4vTe8IrTOS:b855xex) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eac8b3640df05fe63135c4076e4afe39a16b60d/pkg/sql/crdb_internal.go#L6183)):*
> ```Go
> 				if username.IsRootUser() ||
> 					username.IsAdminRole() ||
> 					username.IsNodeUser() ||
> ```

Aah, good find.
___
*[`pkg/sql/catalog/validate.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124772#-Nz-xprV4b7F_gPHnXDr:-Nz-xprV4b7F_gPHnXDs:b-9we4ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eac8b3640df05fe63135c4076e4afe39a16b60d/pkg/sql/catalog/validate.go#L206)):*
> ```Go
> ) error {
> 	// Validate the owner.
> 	exists, err := RoleExists(descriptor.GetPrivileges().Owner())
> ```

We probably should add a validation test for this

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124772)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/validate.go` line 206 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124772#-Nz-xprV4b7F_gPHnXDr:-Nz58V89-jWBmgWjV4hh:b-tbcb6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/3eac8b3640df05fe63135c4076e4afe39a16b60d/pkg/sql/catalog/validate.go#L206)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

We probably should add a validation test for this
</blockquote></details>

good call; i added a test

**Review by fqazi — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124772)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/catalog/schemadesc/schema_desc_builder.go` line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124772#-NzEX2OBCqjG1e7oShQV:-NzEX2OBCqjG1e7oShQW:b-vmj76l) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d6c1c9094e6929d23d9348d2eac4dfc0a0abe0/pkg/sql/catalog/schemadesc/schema_desc_builder.go#L147)):*
> ```Go
> ) error {
> 	// If the owner doesn't exist, change the owner to admin.
> 	if !roleExists(sdb.maybeModified.GetPrivileges().Owner()) {
> ```

Just curiosity what kind of badness happens if we have existing descriptors like this? I'm guessing no one can access them but the root / node users?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124772)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi)

___
*[`pkg/sql/catalog/schemadesc/schema_desc_builder.go` line 147 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/124772#-NzEX2OBCqjG1e7oShQV:-NzUhuNz27O9QrInd5Ls:b-p4832m) ([raw file](https://github.com/cockroachdb/cockroach/blob/34d6c1c9094e6929d23d9348d2eac4dfc0a0abe0/pkg/sql/catalog/schemadesc/schema_desc_builder.go#L147)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Just curiosity what kind of badness happens if we have existing descriptors like this? I'm guessing no one can access them but the root / node users?
</blockquote></details>

the non-owner grants would still let other users access it. but the only users who would be able to drop the descriptor is anyone with the `admin` role. also, i think it would mess with `SHOW` statements.

**Comment by rafiss** [comment]
tftr!

bors r=fqazi

**Pull request merged**
