### PR TITLE
build: add missing plpgsql build rules

### LINKED ISSUE #101544: build: github-CI is currently broken due to missing plpgsql build rules
**Describe the problem**

The "Github CI" / "Lint" target in TC is currently failing on `master` with the following error:

```
[15:47:57] :			 [run] # github.com/cockroachdb/cockroach/pkg/sql/scanner
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:35:23: undefined: lexbase.SCONST
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:43:23: undefined: lexbase.IDENT
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:50:23: undefined: lexbase.SCONST
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:60:24: undefined: lexbase.BCONST
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:71:23: undefined: lexbase.DOT_DOT
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:83:23: undefined: lexbase.NOT_EQUALS
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:92:23: undefined: lexbase.LESS_LESS
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:96:23: undefined: lexbase.LESS_EQUALS
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:105:23: undefined: lexbase.GREATER_GREATER
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:109:23: undefined: lexbase.GREATER_EQUALS
[15:47:57] :			 [run] pkg/sql/scanner/plpgsql_scan.go:109:23: too many errors
```

**To Reproduce**

Example here: https://teamcity.cockroachdb.com/buildConfiguration/Cockroach_UnitTests_Check/9610026?showRootCauses=false&expandBuildChangesSection=true&expandBuildProblemsSection=true

**Expected behavior**

No error

Jira issue: CRDB-27002

### PR DESCRIPTION
**Pull request by e-mbrown**
Resolve: #101544

The "Github CI"/ "Lint" target in TC was failing due to missing plpgsql build rules. This commit should add the rules.

Release note: None

### CODE REVIEW

**Comment by knz** [comment]
The main issue I'm seeing here is that the new plpgsql depends on the sql/parser package; and so the source code for the latter needs to be ready before the source code for the former is processed. I'll show what I mean in a separate commit.

**Comment by knz** [comment]
Ok we're out of the woods - i seems the package dependency doesn't matter for file generation.

**Review by e-mbrown — COMMENTED** [review]
Hm, we are getting this error still `undefined: lexbase`, previously the error was `undefined: lexbase.DOT_DOT` or other keyword. Ricky thinks that goimports might not be getting called, or maybe it is returning an incorrect result for some reason.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/101930#-:-NToluoJ4m2DxfCCq8t-:b9z4s1j)* status: :shipit: complete! 0 of 0 LGTMs obtained

**Comment by knz** [comment]
drat, it failed again. I'm looking further now

**Comment by knz** [comment]
This is the failure:
```
[21:30:53] :			 [run] # github.com/cockroachdb/cockroach/pkg/sql/plpgsql/parser
[21:30:53] :			 [run] plpgsql-gen.y:260: undefined: lexbase
[21:30:53] :			 [run] plpgsql-gen.y:261: undefined: lexbase
[21:30:53] :			 [run] plpgsql-gen.y:262: undefined: lexbase
[21:30:53] :			 [run] plpgsql-gen.y:263: undefined: lexbase
[21:30:53] :			 [run] plpgsql-gen.y:264: undefined: lexbase
[21:30:53] :			 [run] plpgsql-gen.y:265: undefined: lexbase
[21:30:53] :			 [run] plpgsql-gen.y:266: undefined: lexbase
[21:30:53] :			 [run] plpgsql-gen.y:268: undefined: lexbase
[21:30:53] :			 [run] plpgsql-gen.y:269: undefined: lexbase
[21:30:53] :			 [run] plpgsql-gen.y:270: undefined: lexbase
[21:30:53] :			 [run] plpgsql-gen.y:270: too many errors
```

I think i know what's up. i'll try something.

**Comment by knz** [comment]
Here's how to repro locally:
```
rm pkg/sql/plpgsql/parser/lexbase/tokens.go
rm pkg/sql/plpgsql/parser/lexbase/keywords.go
rm pkg/sql/plpgsql/parser/plpgsql.go
make pkg/sql/plpgsql/parser/plpgsql.go
```

The issue is because the code needs to import `lexbase`, but `goimports` doesn't know how to add it unless the lexbase files have been generated already.

there are 2 fixes possible:

- add a dependency to only generate plpgsql.go after the other files have been generated already; OR
- add the import manually to plpgsql.y

I think the latter is easier. I'll try this next.

**Comment by knz** [comment]
Next hurdle below . @rickystewart why did the Bazel CI target not find this already? Is this linter not running in bazel? It's a super important linter.

```
    lint_test.go:95:
        pkg/sql/plpgsql/parser/plpgsql-gen.y:692: Parse(): message argument is not a constant expression
        Tip: use YourFuncf("descriptive prefix %s", ...) or list new formatting wrappers in pkg/testutils/lint/passes/fmtsafe/functions.go.
        N.B. additional entry is required functions in the main package. See functions.go#requireConstFmt
```

**Comment by rickystewart** [comment]
Generally we don't have lints on for generated code.

**Comment by knz** [comment]
> This is a problem: the "generated code" for all files is generated from templates that do not have the .go extension, but are written by humans. If these templates contain code that violates our lint rules and bazel doesn't detect that, it's bad.

Filed this separate issue for that:  #102191.

**Comment by rickystewart** [comment]
> This is a problem: the "generated code" for all files is generated from templates that do not have the .go extension, but are written by humans. If these templates contain code that violates our lint rules and bazel doesn't detect that, it's bad.

If we can find a list of which "generated code" files should and should not be linted, then it'll be easy to apply it. I suspect that we have not fully thought through which "generated code" files are and are not lint-worthy.

**Comment by knz** [comment]
Let's move the lint discussion to #102191.

**Comment by knz** [comment]
I'm cautiously optimistic that my latest amend has fixed the remaining CI issues.

I'll disconnect from the computer now. If CI is indeed happy in the end feel free to squash and merge.

**Review by knz — APPROVED** [review]
LGTM modulo squashing the commits together.

NB: you'll need to `git fetch` (or `pull`) my last commit locally from your remote branch before you can squash.

**Comment by knz** [comment]
i'm going to go ahead and merge this so that the remainder of the team doesn't continue to worry something is amiss.

bors r+

**Comment by e-mbrown** [comment]
blathers backport 23.1 22.2

**Pull request merged**
