### PR TITLE
rfc: update the RFC process

### PR DESCRIPTION
**Pull request by knz**
Following a discussion with Ben yesterday.

Main changes:
- new section in template: "how do we teach this?" - mirrors the same in the Rust RFCs, known-good addition
- each template section explains what belongs in the section
- RFC file name prefixed by date of PR merge (intendedly different from date *in* RFC which is date of first authorship)

### CODE REVIEW

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: 0 of 74 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-:-KrBUt1peYxMxKcfND21:bnfp4nl)*

**Review by a-robinson — APPROVED** [review]

**Comment by couchand** [comment]
Was just thinking about writing something up like this (particularly trying to get some useful ordering to the merged RFCs).  Looks great, thanks!

The other alternative would be to title the RFC with the PR number (like Rust does), but since we include that in the text anyway, the date seems more useful.

---

Reviewed 2 of 145 files at r1.
Review status: 2 of 74 files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/00000000_template.md, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBmP9rhV9SprsCfkrD:-KrBmP9rhV9SprsCfkrE:b-8c5zap) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L10)):*
> ```Markdown
> # Summary
> 
> One para explanation of the proposed change.
> ```

s/para/paragraph/

---

*[docs/RFCS/00000000_template.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBmtBY_CF3R6qQvOZ3:-KrBmtBY_CF3R6qQvOZ4:b-4reuvt) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L22)):*
> ```Markdown
> Why are we doing this? What use cases does it support? What is the expected outcome?
> 
> # Guide-level explanation
> ```

I don't think it's clear which headings are literal template headings and which are meta/descriptive headings.

---

*[docs/RFCS/00000000_template.md, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBojenLAWoZKt9cMIb:-KrBojenLAWoZKt9cMIc:b-t1e7ia) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L60)):*
> ```Markdown
> What / how.
> 
> Outline both "how it works" and "what needs to be changed and in which order to get there."
> ```

maybe add something like "Describe the overview of the design, and then explain each part of the implementation in enough detail that reviewers will be able to identify any missing pieces.  Make sure to call out interactions with other active RFCs."

---

*[docs/RFCS/00000000_template.md, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBnf_O6ScRhAyRoh75:-KrBnf_O6ScRhAyRoh76:b-82ovfd) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L64)):*
> ```Markdown
> ## Drawbacks
> 
> Why should we *not* do this?
> ```

Maybe also mitigating factors that make each drawback acceptable?

---

*[docs/RFCS/00000000_template.md, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBnkH6uhhlMHW60Wp0:-KrBnkH6uhhlMHW60Wp1:b5etumw) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L68)):*
> ```Markdown
> ## Rationale and Alternatives
> 
> - Why is this design the best in the space of possible designs?
> ```

In the RFCs I've read this is often the weakest section, which is unfortunate, since it's important to understand why the solution chosen was right.  I would guess that stems from the solution being determined first and the RFC written to support that, without much consideration being given to the alternatives.

I'm not sure exactly what the form of it would be, but it might be a good idea to add guidance here that this section is vital.

---

*[docs/RFCS/00000000_template.md, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBoded8DNTGQHmAK3D:-KrBodeecT-GTMC8W9RI:b9nh8wp) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L74)):*
> ```Markdown
> ## Unresolved questions
> ```

Extra blank line.

---

*[docs/RFCS/README.md, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBq5Umnd_I1cWG4ds5:-KrBq5Umnd_I1cWG4ds6:b80t6u9) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/README.md#L8)):*
> ```Markdown
> # RFC process
> 
> Before making major changes, consider sending an RFC for discussion.
> ```

Maybe add some guidance about what constitutes a "major change"?

---

*[docs/RFCS/README.md, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBpywmnF74dgzCosKJ:-KrBpywnwar7LxIxc-ij:b-l4smt5) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/README.md#L62)):*
> ```Markdown
>   A newly minted RFC has this status, until either the proposal is
>   accepted (next possible status: in-progress) or that it is DOA (next
>   possible status: rejected).
> ```

Maybe also document the "rejected" status here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-:-KrBmKJLBu2p3wfKV1cE:b-7bzm8m)*

**Comment by arjunravinarayan** [comment]
Review status: 2 of 74 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/00000000_template.md, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrDrGeNU9xK2L1JmpX5:-KrDrGeNU9xK2L1JmpX6:bfy41ni) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L26)):*
> ```Markdown
> How do we teach this?
> 
> Explain the proposal as if it was already included in the project and
> ```

I'm not sure this ask can be satisfied in every RFC. Oftentimes the way to teach a thing in a pedagogically sound fashion is not apparent until after building the thing itself. You could add a caveat that this section could probably be written last.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568)*

**Comment by knz** [comment]
Review status: 2 of 74 files reviewed at latest revision, 9 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/00000000_template.md, line 10 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBmP9rhV9SprsCfkrD:-KrFmsGakvHAJ0z6t5o5:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L10)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

s/para/paragraph/
</blockquote></details>

Done.

---

*[docs/RFCS/00000000_template.md, line 22 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBmtBY_CF3R6qQvOZ3:-KrFnxSjMt1CxjWXYF2h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L22)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

I don't think it's clear which headings are literal template headings and which are meta/descriptive headings.
</blockquote></details>

Done.

---

*[docs/RFCS/00000000_template.md, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrDrGeNU9xK2L1JmpX5:-KrFo1wNCezEKydzuZy5:bclt24w) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L26)):*
<details><summary><i>Previously, arjunravinarayan (Arjun Narayan) wrote…</i></summary><blockquote>

I'm not sure this ask can be satisfied in every RFC. Oftentimes the way to teach a thing in a pedagogically sound fashion is not apparent until after building the thing itself. You could add a caveat that this section could probably be written last.
</blockquote></details>

I actually do not agree with this in general. 

1) I think it is true that some RFC sections are harder to write than others and therefore the process of writing the RFC can be iterative and the PR can be submitted for discussion / iteration before the RFC is complete. I added a note to this effect in the README file. 

2) I think that depending on the topic you could say of any RFC section "it is not apparent until after building the thing itself". It is not clear to me that this section is special in that regard. For example "Alternatives" also come up during implementation, and so do "Unresolved questions"

3) I honestly think that an idea that you can't explain in simple terms is not yet ready to be implemented.

---

*[docs/RFCS/00000000_template.md, line 60 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBojenLAWoZKt9cMIb:-KrFp6UkPWUI-G70TYri:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L60)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

maybe add something like "Describe the overview of the design, and then explain each part of the implementation in enough detail that reviewers will be able to identify any missing pieces.  Make sure to call out interactions with other active RFCs."
</blockquote></details>

Done.

---

*[docs/RFCS/00000000_template.md, line 64 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBnf_O6ScRhAyRoh75:-KrFpCtBRgnxtOq_CQY3:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L64)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Maybe also mitigating factors that make each drawback acceptable?
</blockquote></details>

Done.

---

*[docs/RFCS/00000000_template.md, line 68 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBnkH6uhhlMHW60Wp0:-KrFpoxDn0nzMpH4A7jj:bxgk5ii) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L68)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

In the RFCs I've read this is often the weakest section, which is unfortunate, since it's important to understand why the solution chosen was right.  I would guess that stems from the solution being determined first and the RFC written to support that, without much consideration being given to the alternatives.

I'm not sure exactly what the form of it would be, but it might be a good idea to add guidance here that this section is vital.
</blockquote></details>

Added a note in the README file and a reminder here.

---

*[docs/RFCS/00000000_template.md, line 74 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBoded8DNTGQHmAK3D:-KrFpx0uBHylz_hGCScm:bt2vr1b) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L74)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Extra blank line.
</blockquote></details>

Fixed.

---

*[docs/RFCS/README.md, line 8 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBq5Umnd_I1cWG4ds5:-KrFrdjKc0iOPYT3q-UJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/README.md#L8)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Maybe add some guidance about what constitutes a "major change"?
</blockquote></details>

Done.

---

*[docs/RFCS/README.md, line 62 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrBpywmnF74dgzCosKJ:-KrFrokOsDuohCBZesJC:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/README.md#L62)):*
<details><summary><i>Previously, couchand (Andrew Couch) wrote…</i></summary><blockquote>

Maybe also document the "rejected" status here?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568)*

**Comment by knz** [comment]
Review status: 0 of 75 files reviewed at latest revision, 9 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/00000000_template.md, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrDrGeNU9xK2L1JmpX5:-KrFs9GyZx6KIZSer2js:b-jt341g) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L26)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I actually do not agree with this in general. 

1) I think it is true that some RFC sections are harder to write than others and therefore the process of writing the RFC can be iterative and the PR can be submitted for discussion / iteration before the RFC is complete. I added a note to this effect in the README file. 

2) I think that depending on the topic you could say of any RFC section "it is not apparent until after building the thing itself". It is not clear to me that this section is special in that regard. For example "Alternatives" also come up during implementation, and so do "Unresolved questions"

3) I honestly think that an idea that you can't explain in simple terms is not yet ready to be implemented.
</blockquote></details>

Also the process of explaining the thing often helps shaping up the detailed design. I can see cases in the past where this was true.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568)*

**Comment by knz** [comment]
Entering final comment period.

**Comment by knz** [comment]
@danhhz did you also have comments on this one?

**Comment by danhhz** [comment]
very nice. the rust rfc process really seems to be working well for them, so i'm in favor of cribbing it even more directly than we have been

---

Review status: 0 of 75 files reviewed at latest revision, 13 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/00000000_template.md, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrDrGeNU9xK2L1JmpX5:-Ks9cu6jkueQ1_eqSA4C:b-lkwn65) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L26)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Also the process of explaining the thing often helps shaping up the detailed design. I can see cases in the past where this was true.
</blockquote></details>

+1 to arjun's concern. Some people are able to work through every detail ahead of time, but some (including myself) need to work more iteratively. I think it'd be nice if it was explicitly called out that's it's completely fine to start with only some of the sections filled out and they all need to be present for the final merge

---

*[docs/RFCS/00000000_template.md, line 10 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-Ks9b8WPgO5DSnQnROjZ:-Ks9b8WPgO5DSnQnROj_:bxbu6tw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f731b1f4e4c3bf354764e53cbc182ec2f0da461/docs/RFCS/00000000_template.md#L10)):*
> ```Markdown
> Replace the text between angle brakets below (‹...›) by your own content.
> 
> Preferred style through the text:
> ```

this seems overly prescriptive to me

I, for one, greatly prefer spencer's tense in rfcs, which is to document the feature as if it's already been implemented

---

*[docs/RFCS/00000000_template.md, line 20 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-Ks9eN_uDipD653G3XFz:-Ks9eN_uDipD653G3XG-:b-atxnb7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f731b1f4e4c3bf354764e53cbc182ec2f0da461/docs/RFCS/00000000_template.md#L20)):*
> ```Markdown
> # Summary
> 
> ‹One paragraph explanation of the proposed change.
> ```

nit: What are these < and > ? They're distracting in both the raw text and the rendered view

---

*[docs/RFCS/00000000_template.md, line 84 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-Ks9cL7XH_dfFz0jIpeN:-Ks9cL7XH_dfFz0jIpeO:b-3xxgz1) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f731b1f4e4c3bf354764e53cbc182ec2f0da461/docs/RFCS/00000000_template.md#L84)):*
> ```Markdown
> ‹What / how.
> 
> (You may replace the section title if the intent stays clear.)
> ```

nit: repeating this is distracting. either remove it entirely or have it somewhere once

---

*[docs/RFCS/00000000_template.md, line 103 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-Ks9emcYCVH4Kx49d1xk:-Ks9emcZV44eGI8gMa7H:blzmkeo) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f731b1f4e4c3bf354764e53cbc182ec2f0da461/docs/RFCS/00000000_template.md#L103)):*
> ```Markdown
> ‹
> 
> This section is extremely important. See the README file for details.
> ```

nit: link here to the header containing what you're referencing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-:-Ks9_k4M5RMNeOgRqpKs:bvr4szd)*

**Comment by knz** [comment]
Review status: 0 of 75 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/00000000_template.md, line 26 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KrDrGeNU9xK2L1JmpX5:-KsExL-o10zqhMeWxHwN:bz6fupg) ([raw file](https://github.com/cockroachdb/cockroach/blob/58ee0f7ab1c1bc05e5facd54d05a4d1011390a85/docs/RFCS/00000000_template.md#L26)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

+1 to arjun's concern. Some people are able to work through every detail ahead of time, but some (including myself) need to work more iteratively. I think it'd be nice if it was explicitly called out that's it's completely fine to start with only some of the sections filled out and they all need to be present for the final merge
</blockquote></details>

I added a reminder at the top that the PR can be created before all sections have been filled. Does this satisfy?

---

*[docs/RFCS/00000000_template.md, line 10 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-Ks9b8WPgO5DSnQnROjZ:-KsEvvMq_LkB3iOttRQb:bsm863y) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f731b1f4e4c3bf354764e53cbc182ec2f0da461/docs/RFCS/00000000_template.md#L10)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

this seems overly prescriptive to me

I, for one, greatly prefer spencer's tense in rfcs, which is to document the feature as if it's already been implemented
</blockquote></details>

Reworded to clarify intent.

---

*[docs/RFCS/00000000_template.md, line 20 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-Ks9eN_uDipD653G3XFz:-KsEwSk3THR5VrNEztGM:b-6uncoj) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f731b1f4e4c3bf354764e53cbc182ec2f0da461/docs/RFCS/00000000_template.md#L20)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: What are these < and > ? They're distracting in both the raw text and the rendered view
</blockquote></details>

It's explained at the top: this is the part you can replace by your own content.

---

*[docs/RFCS/00000000_template.md, line 84 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-Ks9cL7XH_dfFz0jIpeN:-KsEwfV2pKhIDsOv4gt9:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f731b1f4e4c3bf354764e53cbc182ec2f0da461/docs/RFCS/00000000_template.md#L84)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: repeating this is distracting. either remove it entirely or have it somewhere once
</blockquote></details>

Done.

---

*[docs/RFCS/00000000_template.md, line 103 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-Ks9emcYCVH4Kx49d1xk:-KsEwvv5Jv0EfWh7Rnqj:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f731b1f4e4c3bf354764e53cbc182ec2f0da461/docs/RFCS/00000000_template.md#L103)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

nit: link here to the header containing what you're referencing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568)*

**Comment by danhhz** [comment]
:lgtm:

even considering our apparently difference of opinion on one remaining point, this is a huge net win from where we were before. thanks for picking this up!

---

Review status: 0 of 75 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/00000000_template.md, line 20 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-Ks9eN_uDipD653G3XFz:-KsF9wvYbNS1IeCeDIfN:b-aqapr7) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f731b1f4e4c3bf354764e53cbc182ec2f0da461/docs/RFCS/00000000_template.md#L20)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

It's explained at the top: this is the part you can replace by your own content.
</blockquote></details>

I think this causes more confusion than it eliminates. Let's remove

---

*[docs/RFCS/00000000_template.md, line 13 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KsFA4l8rfQABwvFuEWX:-KsFA4l8rfQABwvFuEWY:b9lxxpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/903af6867cecc41c2b4d6016658ea3526c804ee7/docs/RFCS/00000000_template.md#L13)):*
> ```Markdown
> complete. Refer to the [README](README.md#rfc-process) for details.**
> 
> While writing, be careful about your style. In particular, avoid "We
> ```

I think this is overly prescriptive and the inclusion of it has not been justified. IMO the tense of the rfc should be optimized for documentation after it's been merged. In this case the discussion already _has_ taken place (and there's certainly some lesser space for discussion after it's gone through final comment period and implementation has begun).

Is your concern that an rfc written in one of these tenses indicates that the author is going to give more push back on the reviewers? I don't believe that those are dependent. Or if that's not it, what is your concern?

Preference for removing this entirely. Failing that, the motivation definitely needs to be justified in the document text.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-:-KsFBrOKJMWERtyB7K-P:bxzwhv4)*

**Comment by knz** [comment]
Review status: 0 of 75 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/00000000_template.md, line 20 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-Ks9eN_uDipD653G3XFz:-KsPK7aU94O7VsRDJluA:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1f731b1f4e4c3bf354764e53cbc182ec2f0da461/docs/RFCS/00000000_template.md#L20)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I think this causes more confusion than it eliminates. Let's remove
</blockquote></details>

Done.

---

*[docs/RFCS/00000000_template.md, line 13 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KsFA4l8rfQABwvFuEWX:-KsPJsUoXKWYHa4r3RV5:bqmfpnw) ([raw file](https://github.com/cockroachdb/cockroach/blob/903af6867cecc41c2b4d6016658ea3526c804ee7/docs/RFCS/00000000_template.md#L13)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I think this is overly prescriptive and the inclusion of it has not been justified. IMO the tense of the rfc should be optimized for documentation after it's been merged. In this case the discussion already _has_ taken place (and there's certainly some lesser space for discussion after it's gone through final comment period and implementation has begun).

Is your concern that an rfc written in one of these tenses indicates that the author is going to give more push back on the reviewers? I don't believe that those are dependent. Or if that's not it, what is your concern?

Preference for removing this entirely. Failing that, the motivation definitely needs to be justified in the document text.
</blockquote></details>

@tschottdorf  you were the one who expressed interest in having the template clarify this point. Can you restate your perspective / point of view here please?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568)*

**Comment by tschottdorf** [comment]
Review status: 0 of 75 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/00000000_template.md, line 13 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KsFA4l8rfQABwvFuEWX:-KsPZYgWvb7drNu1hGhX:b5zrq47) ([raw file](https://github.com/cockroachdb/cockroach/blob/903af6867cecc41c2b4d6016658ea3526c804ee7/docs/RFCS/00000000_template.md#L13)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

@tschottdorf  you were the one who expressed interest in having the template clarify this point. Can you restate your perspective / point of view here please?
</blockquote></details>

I'm fine leaving this out. Thanks for checking in.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568)*

**Comment by tschottdorf** [comment]
Reviewed 142 of 145 files at r1, 3 of 4 files at r2, 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568)*

**Comment by knz** [comment]
Review status: 74 of 75 files reviewed at latest revision, 14 unresolved discussions.

---

*[docs/RFCS/00000000_template.md, line 13 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568#-KsFA4l8rfQABwvFuEWX:-KsPaJ_gXuXdUUZooeRJ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/903af6867cecc41c2b4d6016658ea3526c804ee7/docs/RFCS/00000000_template.md#L13)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I'm fine leaving this out. Thanks for checking in.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/17568)*

**Comment by knz** [comment]
TFYRs!

**Pull request merged**
