### PR TITLE
opt: Enable additional logic tests for opt configs

### PR DESCRIPTION
**Pull request by andy-kimball**
Enable most logic tests from crdb_internal -> inverted_index.

Fix several issues that were preventing these tests from working
with the cost-based optimizer.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
LGTM. You are moving really fast :)

**Comment by rytaft** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r1, 4 of 4 files at r2, 2 of 2 files at r3, 49 of 50 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[pkg/sql/logictest/testdata/logic_test/inet, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26058#-LDNMDJcDVRf71z1NdSt:-LDNMDJcDVRf71z1NdSu:bdv6cj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/743cb132d205764065067d0722312306eea97fe0/pkg/sql/logictest/testdata/logic_test/inet#L1)):*
> ```
> # LogicTest: default opt parallel-stmts distsql distsql-metadata
> ```

Does this not work yet with opt-distsql?

---

*[pkg/sql/logictest/testdata/logic_test/optimizer, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26058#-LDNCOfXB4t2_Yxsx0tB:-LDNCOfY0Jo9Y8-JIAkg:b-2psoqs) ([raw file](https://github.com/cockroachdb/cockroach/blob/2491c0c28020392aeaa6f41163fad2b0981e9a03/pkg/sql/logictest/testdata/logic_test/optimizer#L92)):*
> ```
> SELECT COUNT(*) FILTER (WHERE v>10) FROM t
> 
> query error pq: views and sequences are not supported
> ```

Could you also add this same test above to make sure we fall back to the existing planner?

---

*[pkg/sql/logictest/testdata/logic_test/optimizer, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26058#-LDNNts_5MKtCCzDz_oC:-LDNNtsa5loZUIJZKlQI:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/743cb132d205764065067d0722312306eea97fe0/pkg/sql/logictest/testdata/logic_test/optimizer#L95)):*
> ```
> SELECT * FROM tview
> 
> query error pq: virtual tables are not supported
> ```

ditto

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26058#-LDLmz2nDCZWQ-32uq-w:-LDLmz2oD3kuOKPvlRG-:bq7yfww) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd330aeeae54b5d4a50112181e3a9dc4030cdc6e/pkg/sql/opt/exec/execbuilder/relational_builder.go#L474)):*
> ```Go
> 	}
> 	// LIMIT/OFFSET expression should never need buildScalarContext, because it
> 	// can't refer to input expression.
> ```

[nit] refer to input -> refer to the input

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26058#-:-LDNRRd18i56-OPUEr0j:bnfp4nl)*

**Comment by RaduBerinde** [comment]
*[pkg/sql/logictest/testdata/logic_test/inet, line 1 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26058#-LDNMDJcDVRf71z1NdSt:-LDNh3Mp-tJ3v1RCnSNr:b6ipgdr) ([raw file](https://github.com/cockroachdb/cockroach/blob/743cb132d205764065067d0722312306eea97fe0/pkg/sql/logictest/testdata/logic_test/inet#L1)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Does this not work yet with opt-distsql?
</blockquote></details>

There as an issue, fixed in #26086

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26058)*

**Comment by andy-kimball** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[pkg/sql/logictest/testdata/logic_test/optimizer, line 92 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/26058#-LDNCOfXB4t2_Yxsx0tB:-LDNmINo3T_7DAf87C3R:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2491c0c28020392aeaa6f41163fad2b0981e9a03/pkg/sql/logictest/testdata/logic_test/optimizer#L92)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

Could you also add this same test above to make sure we fall back to the existing planner?
</blockquote></details>

Done.

---

*[pkg/sql/logictest/testdata/logic_test/optimizer, line 95 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/26058#-LDNNts_5MKtCCzDz_oC:-LDNmIfx2E3fW1KF-XIs:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/743cb132d205764065067d0722312306eea97fe0/pkg/sql/logictest/testdata/logic_test/optimizer#L95)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.

---

*[pkg/sql/opt/exec/execbuilder/relational_builder.go, line 474 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/26058#-LDLmz2nDCZWQ-32uq-w:-LDNmShtDwZAb71bSYQ6:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/fd330aeeae54b5d4a50112181e3a9dc4030cdc6e/pkg/sql/opt/exec/execbuilder/relational_builder.go#L474)):*
<details><summary><i>Previously, rytaft wrote…</i></summary><blockquote>

[nit] refer to input -> refer to the input
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/26058)*

**Pull request merged**
