### PR TITLE
ui/cluster-ui: fix routing to statement details page

### PR DESCRIPTION
**Pull request by xinhaoz**
Partially addresses #68843

Previously, we used two different bases for the statement details page, which
depended on which route parameters were included. `/statements/` was used when
the app name was included in the path, and otherwise `/statement/` was used.
The database name was also optionally included in the path name, further
complicating routing to the statement details page as these optional route
params lead to the need to include all combinations of route parameters for
statement detail paths,

This commit turns all optional route parameters into query string parameters,
removing the necessity for different base paths and route param combinations.

Release note (ui change): For statement detail URLs, the app name and database
name are now query string parameters. The route to statement details is
now definitively `/statement/:implicitTxn/:statement?{queryStringParams}`.

e.g.
`statement/true/SELECT%20city%2C%20id%20FROM%20vehicles%20WHERE%20city%20%3D%20%241?database=movr&app=movr`

### CODE REVIEW

**Comment by xinhaoz** [comment]
Note that I pulled relevant changes from https://github.com/cockroachdb/cockroach/pull/70282, and have rebased that branch on top of this one, since it makes more sense to include those changes relevant to the routing here.

**Review by maryliag — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70600)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag and @xinhaoz)

___
*[pkg/ui/workspaces/db-console/src/app.tsx, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70600#-MkEcehGCS9ZGzhw1T3r:-MkEcehGCS9ZGzhw1T3s:b-1xsvob) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa0e1e68ef72aaaba86752e9fb26598d6d16b99/pkg/ui/workspaces/db-console/src/app.tsx#L191)):*
> ```XML
>                   component={StatementDetails}
>                 />
>                 <Route
> ```

Instead of getting rid of the old routes, we should do a reroute, at least for now, in case users bookmark a statement they frequently check or something like that

**Review by xinhaoz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70600)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[pkg/ui/workspaces/db-console/src/app.tsx, line 191 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/70600#-MkEcehGCS9ZGzhw1T3r:-MkIMb1y7jfop57Qz8B4:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/2aa0e1e68ef72aaaba86752e9fb26598d6d16b99/pkg/ui/workspaces/db-console/src/app.tsx#L191)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

Instead of getting rid of the old routes, we should do a reroute, at least for now, in case users bookmark a statement they frequently check or something like that
</blockquote></details>

Done.

**Review by maryliag — CHANGES_REQUESTED** [review]
When there is no App selected on the filter, you're passing the value `All` as a parameters, and on the details page is not returning anything because it can find an app called `All`. Make sure that you're only passing parameters on the url if a value was selected

> Reviewed 9 of 14 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70600#-:-MkNNiJ_C-0YuR9PLNZX:b-u9v2jz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Review by maryliag — COMMENTED** [review]
I notice the issue I mentioned above only happens when any of the other filters was selected (database, SQL type, etc). If no filter is selected the App is empty on the url and it works, so make sure that when any of the filters is selected, the App name is being handled properly

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70600#-:-MkNOQpS5oojPYZt_0Nb:b-e6if35)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

**Comment by xinhaoz** [comment]
@maryliag Done. Nice catch -- I was erroneously pulling the app name from the query string in the statements page, when that page still uses the route param.

**Review by maryliag — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 14 files at r1, 2 of 4 files at r2, 4 of 6 files at r3, 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70600#-:-MkcLOPLDedBGUzywd7d:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @maryliag)

**Review by Azhng — COMMENTED** [review]
Hmm, is there anything special about `implicitTxn` that we want to make it part of the path instead of also turning it into query param ?

> Reviewed 3 of 14 files at r1, 1 of 4 files at r2, 3 of 6 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/70600#-:-Mkd4Dc5ChlR-11Vtgzo:b-4dpxa5)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @Azhng and @maryliag)

**Comment by xinhaoz** [comment]
bors r=maryliag

**Pull request merged**
