### PR TITLE
exec: use streaming merge joiner with 'auto' setting

### LINKED ISSUE #39066: exec: plan merge joiner in some cases with "streaming" on
In general case, merge joiner is not a streaming operator because it can do unbounded buffering when there are rows that are the same on the equality columns. However, when both of the inputs are unique, it becomes a streaming operator and should be planned accordingly once #38620 is closed.

### PR DESCRIPTION
**Pull request by yuzefovich**
Merge joiner is a streaming operator when equality columns form a key
for both of the inputs. This information is now added to the spec and
is populated by the optimizer.

However, if we encounter a hash router in the flow spec, we will not
be using the vectorized engine when vectorize=auto because the hash
router can do unlimited buffering.

Fixes: #39066.

Release note: None

### CODE REVIEW

**Review by jordanlewis — COMMENTED** [review]
:lgtm: from exec point of view.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-:-LlUioAb0MSHHM4JVLAf:boixymw)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis and @RaduBerinde)

**Comment by yuzefovich** [comment]
On `fakedist-opt`, this logic test:
```
statement ok
CREATE TABLE l (a INT PRIMARY KEY)

statement ok
CREATE TABLE r (a INT PRIMARY KEY)

statement ok
INSERT INTO l VALUES (1), (2), (3)

statement ok
INSERT INTO r VALUES (2), (3), (4)

query I
SELECT * FROM l LEFT OUTER JOIN r USING(a) WHERE a = 1
----
1
```
produces this plan
Screen Shot 2019-08-04 at 8 51 37 PM
Doesn't it seem weird?

**Comment by yuzefovich** [comment]
Filed #39317.

**Comment by yuzefovich** [comment]
I implemented Alfonso's suggestion to not use the vectorized engine when there is a hash router in the flow spec. RFAL.

**Review by asubiotto — CHANGES_REQUESTED** [review]
I think @RaduBerinde is OOO, @rytaft, could you take a look at the OPT changes? They're additions to plumb down whether join columns form a key.

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-:-LmAHgNx1XhiBHkc9KuL:b-4ljiy)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @yuzefovich)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1462 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-LmAFz8CCYuae072KF1w:-LmAFz8DDGAv5CqM7q-I:b1fhwkv) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fe1becd25c54b34b844d2312b9cc6172cbf742a/pkg/sql/distsqlrun/column_exec_setup.go#L1462)):*
> ```Go
> 		}
> 
> 		if flowCtx.EvalCtx.SessionData.VectorizeMode == sessiondata.VectorizeAuto &&
> ```

Maybe `!=` `On` might be a stronger check.
___
*[pkg/sql/exec/mergejoiner.go, line 325 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-LmAGbM61P7trTJZNiUn:-LmAGbM61P7trTJZNiUo:b-96np4p) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fe1becd25c54b34b844d2312b9cc6172cbf742a/pkg/sql/exec/mergejoiner.go#L325)):*
> ```Go
> 	builderState mjBuilderState
> 
> 	estimatedStaticMemoryUsage int
> ```

Why is this a field? Isn't it sufficient to define `EstimateStaticMemoryUsage` and use that result in `column_exec_setup.go`? I would rather template this function for the different join types.
___
*[pkg/sql/exec/mergejoiner.go, line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-LmAGVMc6_yix7kOrOYB:-LmAGVMc6_yix7kOrOYC:bc9xg8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fe1becd25c54b34b844d2312b9cc6172cbf742a/pkg/sql/exec/mergejoiner.go#L333)):*
> ```Go
> 	rightDistincter := o.right.distincter.(StaticMemoryOperator)
> 	o.estimatedStaticMemoryUsage =
> 		// TODO(yuzefovich): the first addendum is an overestimation in case of
> ```

Resolved by #39294?

**Review by rytaft — APPROVED** [review]
Opt changes :lgtm: 

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-:-LmATkTl2WuspGfR8vGx:b-e0eosb)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde and @yuzefovich)

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39301)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto, @RaduBerinde, and @rytaft)

___
*[pkg/sql/distsqlrun/column_exec_setup.go, line 1462 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-LmAFz8CCYuae072KF1w:-LmKfrUMDZe9XZ5mSRxO:b-oqshtw) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fe1becd25c54b34b844d2312b9cc6172cbf742a/pkg/sql/distsqlrun/column_exec_setup.go#L1462)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe `!=` `On` might be a stronger check.
</blockquote></details>

But I think that we want to have vectorized flows with `experimental_on` and `experimental_always` if we support them, regardless of the presence of hash routers, right? We only care about "non-streamingness" of a component only with `auto` setting.
___
*[pkg/sql/exec/mergejoiner.go, line 325 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-LmAGbM61P7trTJZNiUn:-LmKit0E3OEQcojZBjVI:byg433c) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fe1becd25c54b34b844d2312b9cc6172cbf742a/pkg/sql/exec/mergejoiner.go#L325)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Why is this a field? Isn't it sufficient to define `EstimateStaticMemoryUsage` and use that result in `column_exec_setup.go`? I would rather template this function for the different join types.
</blockquote></details>

Refactored.
___
*[pkg/sql/exec/mergejoiner.go, line 333 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-LmAGVMc6_yix7kOrOYB:-LmKipGP-1sBBU0Zqc8F:bsa1vsq) ([raw file](https://github.com/cockroachdb/cockroach/blob/1fe1becd25c54b34b844d2312b9cc6172cbf742a/pkg/sql/exec/mergejoiner.go#L333)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Resolved by #39294?
</blockquote></details>

Yes, that's why I left this TODO as a reminder.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-:-LmeQihI08a9VBCg6Ay5:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 2 stale) (waiting on @asubiotto and @RaduBerinde)

**Review by yuzefovich — COMMENTED** [review]
Thanks for the reviews!

bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/39301#-:-LmeebJH0Ak1vVomY72D:bctxt4d)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 3 stale) (waiting on @asubiotto, @RaduBerinde, and @rytaft)

**Pull request merged**
