### PR TITLE
sql: fully consume statement sources despite outer limits

### LINKED ISSUE #20732: sql: DMLs in statement sources don't work properly with limits
```
root@:26257/test> create table a (a int);
CREATE TABLE
root@:26257/test> insert into a values(1),(2);
INSERT 2
root@:26257/test> select * from [delete from a returning a] limit 1;
+---+
| a |
+---+
| 1 |
+---+
(1 row)
root@:26257/test> select * from [delete from a returning a] limit 2;
+---+
| a |
+---+
| 1 |
| 2 |
+---+
(2 rows)
root@:26257/test> select * from a;
+---+
| a |
+---+
| 1 |
| 2 |
+---+
(2 rows)
```

As you can see, the inner `delete` never gets executed.

Without a `limit`, or with an `offset`, this seems to work properly:

```
root@:26257/test> select * from [delete from a returning a] offset 1;
+---+
| a |
+---+
| 2 |
+---+
(1 row)
root@:26257/test> select * from a;
+---+
| a |
+---+
+---+
(0 rows)
```

Same problem exists with insert:

```
root@:26257/test> select * from [insert into a values(1) returning a] limit 1;
+---+
| a |
+---+
| 1 |
+---+
(1 row)
root@:26257/test> select * from a;
+---+
| a |
+---+
+---+
(0 rows)
```

cc @knz

### LINKED ISSUE #20970: sql: statement sources without RETURNING clauses should not be allowed
Statement sources that don't return any data are malformed and should be prevented at planning time.

Postgres has a similar concept with CTEs:

```
jordan=# with x as (insert into a values (1)) select 1 from x;
ERROR:  WITH query "x" does not have a RETURNING clause
LINE 1: with x as (insert into a values (1)) select 1 from x;
                                                           ^
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Previously, DMLs within the `[]` statement source syntax wouldn't always
be fully consumed. For example, the query

```
SELECT * FROM [INSERT INTO t VALUES (1), (2)] LIMIT 1
```

would not insert any values into `t` because the insertNode didn't get
flushed. Additionally, even if the insertNode was flushed, only `1`
would be inserted, not both `1` and `2`.

Now, the inner DML statement is drained completely upon starting the plan.

Fixes #20732.
Fixes #20970.

### CODE REVIEW

**Comment by jordanlewis** [comment]
PTAL - I changed this so that DMLs within statement sources get completely executed upon `startExec`, saving their results into a `RowContainer`.

**Comment by andreimatei** [comment]
I'm now thinking that insertNode & friends should always execute fully. I started a discussion in 
https://groups.google.com/a/cockroachlabs.com/forum/#!topic/eng/kdkPpLfYFZI

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-:-L0pw_q5aFDHoPkWdZ1x:bxqcee6)*

**Comment by knz** [comment]
:-1: on the 2nd commit -- tables with zero columns are valid in SQL, there is no reason to single out the [...] syntax.

:-1: on the 4th commit -- 1) I'm not sure we should be draining *at all* (see my other argument on eng@) and 2) the draining behavior should not be set by getDataSource but instead optimizePlan -- set drain to true by default, and then set it to false in optimizePlan if the top-level node is insert/delete/update. 3) Also the giant accumulation of rows in memory for drains is highly problematic.

The other changes LGTM.

---

Reviewed 1 of 1 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[pkg/sql/data_source.go, line 415 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-L0s_m_dHzkRMjZ1HHwO:-L0s_m_eeXP7H4QbhNQN:b-61y83y) ([raw file](https://github.com/cockroachdb/cockroach/blob/193dd4cfe6f8c63033736139a9d17cacb6f68401/pkg/sql/data_source.go#L415)):*
> ```Go
> 				"statement source \"%v\" does not return any columns", t.Statement)
> 		}
> 		switch n := plan.(type) {
> ```

If we end up keeping this, it needs an extensive motivating comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-:-L0s_BvErEkw5x2Sxn4f:b-daibrx)*

**Comment by knz** [comment]
In line with our previous discussion, I am remaining of the opinion that the DML statements should be triggered to commit by their consumer (when the consumer is done with them), not during start(). 

Also I'd like to request that you step out of the code for a minute and look at this at a high level. The entire point of the volcano model (and to some extent, the distsql engine) is to utilize dataflow scheduling, and perform the computation in a streaming fashion -- this ensures both relatively constant memory usage, and avoids doing more work than necessary if a client abandons the request in-flight. Any change that pushes for eager computation (like this PR) is completely decimating all the reasons to use a dataflow approach. If that's the new "party line" we might as well execute each statement in turn with a giant for loop and a memory (possibly disk-backed) buffer.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-:-L0sahzy2sEAhw9tU2DD:b-70wxq7)*

**Comment by jordanlewis** [comment]
TFTR!

> 👎 on the 2nd commit -- tables with zero columns are valid in SQL, there is no reason to single out the [...] syntax.

I'm just doing this for consistency. It doesn't make semantic sense to treat a DML that has no `RETURNING` clause as a statement source, and in fact it's banned in other databases for this same reason.

Additionally, we're already inconsistent here because of the delete fast path. The test we added to respond to #19805 wasn't actually testing the delete fast path - it was testing the delete slow path. Doing `SELECT 1 FROM [slow path]` returns one row, doing `SELECT 1 FROM [fast path]` returns 0 rows. This is inconsistent and confusing - it's better to just prevent the semantic problems in the first place by sensibly banning DMLs without `RETURNING` in sources.

> In line with our previous discussion, I am remaining of the opinion that the DML statements should be triggered to commit by their consumer (when the consumer is done with them), not during start().

I am not sure how to avoid the eager computation in `startExec`. Consider the following statement:

```
SELECT * FROM [DELETE FROM t RETURNING col] LIMIT 0
```

While silly, even this `DELETE` must conform to our guiding principle for DMLs in statement sources and thus be fully drained. The `deleteNode` will never be `Next()`'d because of the outer limit. How do you propose to notify the `deleteNode` that it's time to drain? We briefly discussed adding a new `finalize` phase in plan execution, but I think we all agree that adding such a thing increases complexity without too much gain. Unless you're proposing to bring that back?

As far as memory usage, yes, this is not great. However, I argue that until we lift the transaction size limits in core, it doesn't matter. Also, since the memory is accounted, it's not like we're going to blow up from doing this.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-:-L0t75bazB592o7ximP_:b-7vu18g)*

**Comment by knz** [comment]
OK you changed my mind on the 2nd commit - thanks to #20970.
For the other thing I'm still not buying the argument. The main issue I have is that *currently* (i.e. before this PR), a DML statement that produces a lot of data and is used as data source will be processed in a streaming fashion without any error, and without incorrect behavior. This PR will actually *break* several use cases that *currently work*. We don't usually do that.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-:-L0tjGXuUhFiLc0mb2Xq:bxob9r)*

**Comment by knz** [comment]
What of the other solution we discussed? Refuse to build the plan if there's a limit applied in the surrounding query?

**Comment by knz** [comment]
Or alternatively, only drain early if a limit is applied.

**Comment by jordanlewis** [comment]
> Or alternatively, only drain early if a limit is applied.

Great idea. I should have done that from the start. Coming right up.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-:-L0tnxhzten-6-jySKVj:bau8pmh)*

**Comment by andreimatei** [comment]
Guys, can we please agree on the mailing thread before doing more stuff here?
The one and only comment there from Jordan was " in the general case, we need to fully drain DML plan nodes before returning data from them"  - and yet work here seems to be proceeding in a different direction.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-:-L0tqM8ofILd2xHN953V:b3zowr)*

**Comment by jordanlewis** [comment]
@andreimatei, I consider this work to be orthogonal to the question on the mailing list thread. That is a large design decision. This patch is fundamentally a bugfix, and work toward unblocking finishing the implementation of CTEs.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-:-L0tqtdxXw_flqusPitT:b3tlytf)*

**Comment by andreimatei** [comment]
Sorry, I disagree. It's not orthogonal. Let's build to last :p
Also you have more code in here already than what it would take to do something at the insert level

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-:-L0tsLxpIQo4CFAybxhm:b-ci1rl8)*

**Comment by knz** [comment]
"do something at the insert level" makes no sense because you need to know whether there's a surrounding query to make the choice. As I explained eager computation "by default" / "in general" just doesn't cut it.

**Comment by knz** [comment]
Andrei if you want to introduce semantic changes please also consider the RFC process instead of unstructured back-and-forths between multiple communication media.

**Comment by jordanlewis** [comment]
Okay I've updated this patch to only consume fully when there's outer limits, but given the preferences here I'm going to 1. split this PR up so the first half can get merged and 2. hold off on pushing on the second half until we've resolved our discussion about DML-returning plan consumption in general.

---

Review status: 3 of 9 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/20919#-:-L0uIg9UB4scdoJjN8eg:b-jqo8tj)*

**Comment by jordanlewis** [comment]
Superseded by #23824 and others.

**Pull request closed without merging**
