### PR TITLE
execbuilder: clean up non-metamorphic tests

### PR DESCRIPTION
**Pull request by yuzefovich**
**execbuilder: clean up non-metamorphic tests**

This commit audits all opt logic tests that cannot be run under the
metamorphic build and splits up the files into two wherever it makes
sense. All files that cannot be run under the metamorphic build now
have `_nonmetamorphic` suffix in the name.

As a reminder, the metamorphic build randomizes some of the magic
constants (e.g. `coldata.BatchSize`, `mutations.MaxBatchSize`), and
randomization of the mutations max batch size makes the output of
tracing non-deterministic. That's why we moved all tests that use
tracing to non-metamorphic build (which will occur 25% of the time if
`crdb_test_off` build tag is not specified).

Release note: None

**execbuilder: unskip and rewrite show_trace logic test**

The test was skipped because it is being flaky; however, with only
a couple of queries currently skipped I didn't hit a single flake during
5 minutes of stress on my laptop.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
First commit is in a separate PR.

**Review by mgartner — APPROVED** [review]
:LGTM:

Why can't these tests be run in metamorphic mode? It might be helpful to explain that in the commit message & PR description.

> Reviewed 1 of 1 files at r1, 12 of 12 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58160#-:-MP752wa7hx_bJacALti:b-d37bc8)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Review by RaduBerinde — APPROVED** [review]
Wow, this is great! Thanks for taking the time to do this! :lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58160#-:-MP7k4zzC3o1i2HmzGpq:bd6vkcn)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @RaduBerinde)

**Comment by yuzefovich** [comment]
Updated the first commit message and the PR description.

TFTRs!

bors r+

**Comment by yuzefovich** [comment]
bors crashed

bors r+

**Comment by yuzefovich** [comment]
Apparently another query needs to be skipped.

bors r-

**Comment by yuzefovich** [comment]
Should be good now.

bors r+

**Pull request merged**
