### PR TITLE
roachtest: add test for authentication under network partition

### PR DESCRIPTION
**Pull request by rafiss**
Customers have raised major complaints about this situation. If a node
disappears under a network partition (or the host is hard-killed), then
it is possible that no connections can be established to any other node.
Specifically, if the system.users leaseholder is the node that
disappears, authentication can fail. We expect on the order of ~10
seconds of authentication unavailability, but customers have showed us
an outage period of up to 40 seconds.

This test tries to repro what our customers have shown us so that we can
iterate on the root cause more quickly.

Release note: None

### CODE REVIEW

**Review by knz — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66550)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz, @otan, and @rafiss)

___
*[pkg/cmd/roachtest/network.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66550#-McO6toaDLPUkLji8XT8:-McO6toaDLPUkLji8XT9:b-5rvzwf) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cb5e23861a829b2bc2320342f61145e718f7d10/pkg/cmd/roachtest/network.go#L143)):*
> ```Go
> 	waitForFullReplication(t, db)
> 
> 	if err := c.RunE(ctx, c.Node(1),
> ```

I am confused  - why not `db.Exec` here too?
___
*[pkg/cmd/roachtest/network.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66550#-McO79r69Dzq-RDfuxZD:-McO79r69Dzq-RDfuxZE:b-87hg6p) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cb5e23861a829b2bc2320342f61145e718f7d10/pkg/cmd/roachtest/network.go#L182)):*
> ```Go
> 
> 	m := newMonitor(ctx, c, c.All())
> 	m.Go(func(ctx context.Context) error {
> ```

I would suggest starting the goroutine above,
and let it run for 20 seconds (not 10 iterations), with 1 iteration per 250ms or 500ms

then do the iptables dance 5 seconds later

this ensures that the connection attempts straddle the iptables reconfiguration on both sides (in time)
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 752 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66550#-McO7REh3L6hWX9oIHvH:-McO7REh3L6hWX9oIHvI:b354p86) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cb5e23861a829b2bc2320342f61145e718f7d10/pkg/kv/kvclient/kvcoord/dist_sender.go#L752)):*
> ```Go
> 		var rpl *roachpb.BatchResponse
> 		var pErr *roachpb.Error
> 		// todo here
> ```

what's this?
___
*[pkg/rpc/nodedialer/nodedialer.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66550#-McO7T0g5-bK1Evtsrlr:-McO7T0g5-bK1Evtsrls:ba4q4ku) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cb5e23861a829b2bc2320342f61145e718f7d10/pkg/rpc/nodedialer/nodedialer.go#L168)):*
> ```Go
> 		// If we were canceled during the dial, don't trip the breaker.
> 		if ctxErr := ctx.Err(); ctxErr != nil {
> 			fmt.Printf("canceled during the dial\n")
> ```

if you care about this, make it `log.Errorf`? this way you get it in artifacts

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/66550)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @knz and @otan)

___
*[pkg/cmd/roachtest/network.go, line 143 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66550#-McO6toaDLPUkLji8XT8:-McPjzby1KRgPVm1ecnB:bs1k8xq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cb5e23861a829b2bc2320342f61145e718f7d10/pkg/cmd/roachtest/network.go#L143)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I am confused  - why not `db.Exec` here too?
</blockquote></details>

yes, much better. i'd done some copy+paste from another test and forgot to clean this up
___
*[pkg/cmd/roachtest/network.go, line 182 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66550#-McO79r69Dzq-RDfuxZD:-McPjrk62OyzzP-Brv5a:b-4fwim9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cb5e23861a829b2bc2320342f61145e718f7d10/pkg/cmd/roachtest/network.go#L182)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

I would suggest starting the goroutine above,
and let it run for 20 seconds (not 10 iterations), with 1 iteration per 250ms or 500ms

then do the iptables dance 5 seconds later

this ensures that the connection attempts straddle the iptables reconfiguration on both sides (in time)
</blockquote></details>

good suggestion!
___
*[pkg/kv/kvclient/kvcoord/dist_sender.go, line 752 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66550#-McO7REh3L6hWX9oIHvH:-McPjjde6kWgi8a-y1ov:bgp0iy6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cb5e23861a829b2bc2320342f61145e718f7d10/pkg/kv/kvclient/kvcoord/dist_sender.go#L752)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

what's this?
</blockquote></details>

this was an accident
___
*[pkg/rpc/nodedialer/nodedialer.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/66550#-McO7T0g5-bK1Evtsrlr:-McPjmL0DZCdW1dyatuh:bg2oklv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8cb5e23861a829b2bc2320342f61145e718f7d10/pkg/rpc/nodedialer/nodedialer.go#L168)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

if you care about this, make it `log.Errorf`? this way you get it in artifacts
</blockquote></details>

whoops another accident

**Comment by rafiss** [comment]
hm, i'm noticing that my attempt to pin the liveness and system leaseholders don't actually seem to work.

the test does:
```
ALTER RANGE liveness CONFIGURE ZONE USING lease_preferences = '[[+node=1]]';
ALTER RANGE system CONFIGURE ZONE USING lease_preferences = '[[+node=1]]';
```

but using `testutils.SucceedsSoon` to confirm that `SELECT lease_holder FROM [SHOW RANGES FROM TABLE system.public.users]` returns `1` does not reliably work.

**Comment by knz** [comment]
@andreimatei  comments:
image

**Comment by rafiss** [comment]
I'd expect there to be a replica on the preferred node -- it's a 3 node cluster and the `num_replicas` for `liveness` and `system` is 5. But I'll try setting the constraint too and see what happens.

**Comment by andreimatei** [comment]
If there's a replica on the preferred node, the constraints are not gonna help. I'd try running the range through the replication queue manually and see if you get any useful explanation about the inaction - the "Manual enqueue range" page under Advanced Debug.

**Comment by nvanbenschoten** [comment]
I've found that this needs two more changes to demonstrate the slow connection time, as opposed to hitting errors earlier and masking the full delay.

First, it should set the `server.user_login.timeout` cluster setting to something larger, like 2m. This ensures that `system.public.users` query in `retrieveUserAndPassword` doesn't get canceled after 10 seconds, before it completes.

Second, it should pass a larger value for the `COCKROACH_CONNECT_TIMEOUT` environment variable. Otherwise, the SQL client can hit an `i/o timeout` after 15 seconds, before the SQL connection is established.

A diff like this does the trick:
```
diff --git a/pkg/cmd/roachtest/network.go b/pkg/cmd/roachtest/network.go
index d65b9cf..5402421 100644
--- a/pkg/cmd/roachtest/network.go
+++ b/pkg/cmd/roachtest/network.go
@@ -154,6 +154,9 @@ func runNetworkAuthentication(ctx context.Context, t *test, c Cluster) {
        if _, err := db.Exec(`ALTER RANGE system CONFIGURE ZONE USING lease_preferences = '[[+node=1]]', constraints = '{"+node=1": 1}'`); err != nil {
                t.Fatal(err)
        }
+       if _, err := db.Exec(`SET CLUSTER SETTING server.user_login.timeout = '2m'`); err != nil {
+               t.Fatal(err)
+       }

        const expectedLeaseholder = 1
        testutils.SucceedsSoon(t, func() error {
@@ -206,7 +209,7 @@ WHERE start_pretty = '/System/NodeLiveness' AND end_pretty = '/System/NodeLivene
                                }

                                url := "postgres://testuser:password@localhost:26257/defaultdb?sslmode=require"
-                               b, err := c.RunWithBuffer(ctx, t.l, c.Node(i), "time", "-p", "./cockroach", "sql",
+                               b, err := c.RunWithBuffer(ctx, t.l, c.Node(i), "COCKROACH_CONNECT_TIMEOUT=120", "time", "-p", "./cockroach", "sql",
                                        "--url", url, "--certs-dir", certsDir, "-e", "'SELECT 1'")
                                t.l.Printf("%s\n", b)
                                if err != nil {
```

I'm getting pulled into another escalation, so I won't be able to dig any further for now.

**Comment by rafiss** [comment]
Thanks Nathan, it makes sense that this diff would result in a longer delay. However, the customer was seeing that even with the default values for both of those settings, that their attempts to log in would fail for ~40 seconds. In other words, the first attempt to connect would fail after the 10 second time out, then the second attempt would fail, then the third attempt, and so on until it finally worked. 

So whether it's one very long connection failure or a few ~10 second connection failures, it seems like the internal problem of a slow liveness heartbeat could still happen.

Later today I'll also put up another test for another situation that has been reported: when an entire AZ (with 5 nodes) is network black-holed, then all the nodes in the cluster (of 15 nodes) were failing liveness checks for several minutes.

**Comment by knz** [comment]
> the first attempt to connect would fail after the 10 second time out, then the second attempt would fail, then the third attempt, and so on until it finally worked.

This is new information to me, and that's interesting. This means that they are seeing multiple cancellations due to `server.user_login.timeout` one after the other. In that case, I agree you don't need to change the cluster setting in your test.

Meanwhile, nathan is right to suggest to set `COCKROACH_CONNECT_TIMEOUT`. This is because I believe the customer is not using crdb's own `sql` client in their test, they use a different Java client with no such timeout. Therefore, it's useful to bring the test closer to the customer's environment by avoiding a client-side timeout with the env var.

**Comment by rafiss** [comment]
Actually, the customer was using the `cockroach` CLI in their testing. Here are the steps they used to run their test: https://github.com/cockroachlabs/support/issues/1022#issuecomment-860158102

**Comment by knz** [comment]
heads up that I'm going to try a couple of things today:

1. rebase this on top of the 20.2 branch. I want to see this repro on a 20.2 server regardless of whether we may have accidentally fixed the issue in 21.1 or later already.
2. disable TLS for clients (`--accept-sql-without-tls`) to simplify the test and enable network snooping of pgwire if we ever need this later in the investigation. The problem is not related to TLS anyway.
3. give the test user some non-standard roles and role options (LOGIN / VALIDUNTIL), to give the server some extra work to do upon login. I know the customer does this too.
4. add extra logging in the server code:
   - log the time needed between the point KV sends out a RPC request and the point where the circuitbreaker lets it through
   - log the time between receipt/ingress of a RPC call by a server and completion of the call (response sent)
   - log the time needed for a rpc.Dial call
   - modify the gRPC dependency to log the time needed for a net.Connect call

The point of the logging is to confirm that the network configuration thing with iptables is effective. Regardless of whether we observe the same symptoms as the customer, it's pretty important to demonstrate that the test reproduces something similar, which is a long connect timeout. If we are not able to see this with the logging, we'll need to work on that first.

**Comment by knz** [comment]
> using testutils.SucceedsSoon to confirm that SELECT lease_holder FROM [SHOW RANGES FROM TABLE system.public.users] returns 1 does not reliably work.

fixing that: the zone config for `DATABASE system` and `RANGE system` are two different things. The test needs both.

**Comment by knz** [comment]
ok I found something else, the `--secure` flag for `c.Start` does not work properly.
It causes the cluster to become partitioned already from the start.

Now trying to tweak the test properly.

**Comment by rafiss** [comment]
Thanks for your work on this @knz ! 

> fixing that: the zone config for DATABASE system and RANGE system are two different things. The test needs both.

I just discovered this last night as well. 

Also, I updated this PR with one more test -- one that simulates an entire AZ black-hole. This is to test the scenario described in another issue raised by the same customer, here: https://github.com/cockroachlabs/support/issues/1037

**Comment by knz** [comment]
running my patches in #66768. I'll comment my findings further there.
(If we let the two PRs diverge in implementation, we can't interleave the discussion on findings, as they will pertain to different scenarios)

**Comment by nvanbenschoten** [comment]
Thank you for all the help here @knz!

> This is new information to me, and that's interesting. This means that they are seeing multiple cancellations due to server.user_login.timeout one after the other. In that case, I agree you don't need to change the cluster setting in your test.

> Meanwhile, nathan is right to suggest to set COCKROACH_CONNECT_TIMEOUT. This is because I believe the customer is not using crdb's own sql client in their test, they use a different Java client with no such timeout. Therefore, it's useful to bring the test closer to the customer's environment by avoiding a client-side timeout with the env var.

I think you raise a good point about keeping these settings as close as possible to what the customer is seeing. I was mainly suggesting these settings to assist the debugging process. A series of 10s queries that get cancelled is a little harder to investigate than a 40s long query that succeeds.

**Comment by rafiss** [comment]
replaced by https://github.com/cockroachdb/cockroach/pull/66768

**Pull request closed without merging**
