### PR TITLE
sql: disallow specifying both FORCE_INDEX and NO_INDEX_JOIN

### PR DESCRIPTION
**Pull request by RaduBerinde**
The current code allows both `FORCE_INDEX` and `NO_INDEX_JOIN`
"hints", and the query fails if the index we force requires
index-join.

This semantic would be tricky to support with the optimizer (it would
be a "no-plans" condition during exploration).

This commit changes the behavior to disallow setting both hints at the
same time. The code to combine and validate `IndexHints` is moved in a
method; the code is kept general even though with this change it's
never valid to have more than one parameter.

Release note (sql change): It is now an error to specify both
FORCE_INDEX and NO_INDEX_JOIN hints at the same time.

### CODE REVIEW

**Comment by RaduBerinde** [comment]
CC @andy-kimball

**Review by knz — APPROVED** [review]
:lgtm: but while you're looking at this it would be nice to rename them from "hint" to "constraint". There is nothing hint-y about this code.

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/28411#-:-LJV4uvXCNx_HrDfVHzE:b-i40eqo)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale)

**Comment by RaduBerinde** [comment]
I like "index flags". Done.

**Pull request merged**
