### PR TITLE
sql: fix various problematic uses of the txn in DistSQL flows

### PR DESCRIPTION
**Pull request by andreimatei**
see individual commits

Release justification: Fixes bad bugs.

### CODE REVIEW

**Comment by andreimatei** [comment]
I haven't made the vectorized `UnorderedSync` serial yet. Working on that now.

**Comment by andreimatei** [comment]
handled the vectorized synchronizer

**Review by RaduBerinde — COMMENTED** [review]
This looks good to me, I'm comfortable with this going into 19.2.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-:-LqLwxkG7E_JjRl-YVEQ:b-m669zi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, and @RaduBerinde)

___
*[pkg/sql/distsql_running.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLsOW0C-lN_1OCe5K4:-LqLsOW0C-lN_1OCe5K5:b-7dz576) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/distsql_running.go#L156)):*
> ```Go
> 			for nodeID, spec := range flows {
> 				fuseOpt := flowinfra.Normal
> 				if nodeID == thisNodeID && localState.IsLocal {
> ```

[nit] Doesn't the latter imply the former? Perhaps we should set this outside of the loop and assert that there is a single flow. There are a few similar instances below. Maybe we should move this into a helper function that gets the list of flows and the localstate.
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLs3GGCsLV9HhrmUXt:-LqLs3GGCsLV9HhrmUXu:b-89spdi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colexec/serial_unordered_synchronizer.go#L23)):*
> ```Go
> // SerialUnorderedSynchronizer is an Operator that combines multiple Operator
> // streams into one. It reads its inputs one by one until each one is exhausted,
> // at which point it moves to the next input.
> ```

[nit] Add some context as to why it exists, maybe point at the relevant issue #s.
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLrutT68FVUw256tq5:-LqLrutT68FVUw256tq6:b10v22d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colexec/serial_unordered_synchronizer.go#L30)):*
> ```Go
> 	curSerialInputIdx int
> 	zeroBatch         coldata.Batch
> }
> ```

[nit] add type assertions so it's clear what interface(s) it's supposed to implement
___
*[pkg/sql/colflow/vectorized_flow.go, line 407 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLsEK97RTcX8cyh47B:-LqLsEK97RTcX8cyh47C:b-8q2yst) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colflow/vectorized_flow.go#L407)):*
> ```Go
> 			memUsed += op.(colexec.StaticMemoryOperator).EstimateStaticMemoryUsage()
> 		} else {
> 			if opt == flowinfra.FuseAggressively {
> ```

Add a comment here, maybe point to the issue #s.
___
*[pkg/sql/distsql/server.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLwlOV7jqu45lq6CC5:-LqLwlOV7jqu45lq6CC6:be1nn0t) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/distsql/server.go#L361)):*
> ```Go
> 		return nil, nil, err
> 	}
> 	if meta := req.TxnCoordMeta; meta != nil {
> ```

This block is used 3 times, should be a helper
___
*[pkg/sql/rowflow/input_sync.go, line 368 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLtEw_94dID1DY7cPM:-LqLtEw_94dID1DY7cPN:b-5zcv7d) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/input_sync.go#L368)):*
> ```Go
> // makeOrderedSync creates an orderedSynchronizer. ordering dictates how rows
> // are to be compared. Use sqlbase.NoOrdering to indicate that the row ordering
> // doesn't matter and sources should be consumed in index order.
> ```

Add more context as to why you would want that, maybe refer to FuseAggressively.
___
*[pkg/sql/rowflow/row_based_flow.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLuHpR5mdNI-1C8XJQ:-LqLuHpR5mdNI-1C8XJR:brlx29i) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/row_based_flow.go#L129)):*
> ```Go
> 							return true
> 						}
> 					} else {
> ```

[nit] Would be more readable if we put this first under a `if len(in.Streams) == 1` check (we won't need the `else`).
___
*[pkg/sql/rowflow/row_based_flow.go, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLv-PT5OYstoJzcg4X:-LqLv-PT5OYstoJzcg4Y:b-ggo1aj) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/row_based_flow.go#L154)):*
> ```Go
> 	spec *execinfrapb.FlowSpec, streamID execinfrapb.StreamID,
> ) *execinfrapb.ProcessorSpec {
> 	for _, pspec := range spec.Processors {
> ```

[nit] don't copy each spec,  do `pspec := &spec.Processors[i]`
___
*[pkg/sql/rowflow/row_based_flow.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLunBFAtF20vnRuGBl:-LqLunBFAtF20vnRuGBm:b-1kvjnq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/row_based_flow.go#L156)):*
> ```Go
> 	for _, pspec := range spec.Processors {
> 		if len(pspec.Output) > 1 {
> 			return nil
> ```

Shouldn't this be `continue` ? (same below)
___
*[pkg/sql/rowflow/row_based_flow.go, line 276 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLw0e5AyMzsF9EPi9D:-LqLw0e61MNUOeZKbPuJ:bbptzty) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/row_based_flow.go#L276)):*
> ```Go
> 				// dropped).
> 				streams := make([]execinfra.RowSource, len(is.Streams))
> 				numLocal := 0
> ```

what's numLocal for?
___
*[pkg/sql/rowflow/row_based_flow.go, line 289 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLvpSM9CqujxaR3rl0:-LqLvpSM9CqujxaR3rl1:b7x7wpt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/row_based_flow.go#L289)):*
> ```Go
> 				}
> 				var err error
> 				var ordering sqlbase.ColumnOrdering
> ```

[nit] you can do `ordering := sqlbase.NoOrdering` and flip the`if`

**Review by jordanlewis — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 4 of 4 files at r2, 13 of 13 files at r3, 6 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41307)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/distsql_running.go, line 353 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqMy0gj3dAXX-y2GrfK:-LqMy0gkD1Uy-d9iS_kG:b-2e16a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/distsql_running.go#L353)):*
> ```Go
> 	// For such flows, we were supposed to have fused everything.
> 	if txn != nil && planCtx.isLocal && flow.ConcurrentExecution() {
> 		recv.SetError(errors.Errorf(
> ```

Can you make this an "internal error"? use AssertionErrorf.
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqMZFq7Dg-xP_vFSMd4:-LqMZFq7Dg-xP_vFSMd5:bdtwn6j) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colexec/serial_unordered_synchronizer.go#L62)):*
> ```Go
> // Next is part of the Operator interface.
> func (s *SerialUnorderedSynchronizer) Next(ctx context.Context) coldata.Batch {
> 	if ctx.Err() != nil {
> ```

This is unnecessary (I think and hope) - it's handled by the `CancelChecker` which is always instantiated below the scan operators.
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqMZzYX0Z0gBYfTFIMt:-LqMZzYX0Z0gBYfTFIMu:bb6hmi) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colexec/serial_unordered_synchronizer.go#L71)):*
> ```Go
> 		b := s.inputs[s.curSerialInputIdx].Next(ctx)
> 		if b.Length() == 0 {
> 			s.curSerialInputIdx++
> ```

I won't make a stink about it but you could consider removing inputs when they're exhausted right? But I won't make a stink about it.
___
*[pkg/sql/rowflow/input_sync.go, line 114 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqM_PcX3WFDxeBWytJ-:-LqM_PcX3WFDxeBWytJ0:b-fezkoq) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/input_sync.go#L114)):*
> ```Go
> func (s *orderedSynchronizer) Less(i, j int) bool {
> 	// If we're not enforcing any ordering between rows, let's consume sources in
> 	// their index order.
> ```

nit: extra conditional on every row is kinda sadface - can we instead swap out the Less implementation at constructor time? or just make another copy of the synchronizer like you did for the col one?

**Review by yuzefovich — COMMENTED** [review]
Looks good to me as well. You will also add the tests for the bugs that are being fixed, right?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-:-LqNLsGH3jepqOYjvyAB:b-6ap2sy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @jordanlewis)

___
*[pkg/sql/distsql_running.go, line 352 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNLLGP4dI8c8eI-3Ek:-LqNLLGP4dI8c8eI-3El:blralix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/distsql_running.go#L352)):*
> ```Go
> 	// since they might have mutations), and the RootTxn does not permit concurrency.
> 	// For such flows, we were supposed to have fused everything.
> 	if txn != nil && planCtx.isLocal && flow.ConcurrentExecution() {
> ```

[nit]: it is unusual to see a single opening parenthesis at the end of the line (several lines above).
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqMZFq7Dg-xP_vFSMd4:-LqN7Z9rAw3NoRsrXeSG:b-hkctww) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colexec/serial_unordered_synchronizer.go#L62)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

This is unnecessary (I think and hope) - it's handled by the `CancelChecker` which is always instantiated below the scan operators.
</blockquote></details>

Yeah, I also think this is unnecessary.
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNLj5D8-o3oYBPGzVq:-LqNLj5D8-o3oYBPGzVr:bv0wacb) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/colexec/serial_unordered_synchronizer.go#L28)):*
> ```Go
> 	// curSerialInputIdx is used if parallel is false. It indicates the index of
> 	// the current input being consumed.
> 	curSerialInputIdx int
> ```

[nit]: the comment above seems to be out-of-date.
___
*[pkg/sql/colflow/vectorized_flow.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNHfsW5owNM9n8_DJB:-LqNHfsW5owNM9n8_DJC:bhlqqhe) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/colflow/vectorized_flow.go#L85)):*
> ```Go
> // ConcurrentExecution is part of the Flow interface.
> func (f *vectorizedFlow) ConcurrentExecution() bool {
> 	return f.operatorConcurrency || f.FlowBase.ConcurrentExecution()
> ```

The second part of this conditional is always (at least right now) false for the vectorized flows, but I guess it doesn't matter.
___
*[pkg/sql/distsql/server.go, line 393 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNLakZ4yhh-oWj3I92:-LqNLakZ4yhh-oWj3I93:bym2usm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/distsql/server.go#L393)):*
> ```Go
> 	// This will directly by the flow if the flow has no concurrency. If there is
> 	// concurrency, a LeafTxn will be created.
> 	Txn *client.Txn
> ```

[nit]: a few words are missing, maybe "This will be used directly ..." (above)
___
*[pkg/sql/physicalplan/physical_plan.go, line 1132 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNJ8xb2DWtS74KbHsX:-LqNJ8xb2DWtS74KbHsY:b9w5cv1) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/physicalplan/physical_plan.go#L1132)):*
> ```Go
> 	for i := 0; i < len(p.ResultRouters); i++ {
> 		pIdx := p.ResultRouters[i]
> 		node := p.Processors[p.ResultRouters[i]].Node
> ```

[nit]: `s/p.ResultRouters[i]/pIdx/`.
___
*[pkg/sql/rowflow/row_based_flow.go, line 111 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNLenk0LJ5qinrRNOx:-LqNLenk0LJ5qinrRNOy:bkjgomm) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/rowflow/row_based_flow.go#L111)):*
> ```Go
> 						// If it's an orderedSynchronizer, the we look inside it to see if
> 						// the processor we're trying to fuse feeds into it.
> 						orderedSync, ok := inputSyncs[pIdx][inIdx].(*orderedSynchronizer)
> ```

[nit]: `s/the we/then we/` (above).

**Review by andreimatei — COMMENTED** [review]
I've isolated a commit (r6) for clarifying the various `isLocal` fields and for unifying the handling of queries that were forced to be planned locally with ones that happened to not have any remote flows (for whatever reason).
I've reworded the commit message on r9 to remove any references to remote flows. That was FUD; I had failed to read the code properly.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-:-LqNPhIe7fUaIzMiSH2N:b7bmr9i)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/distsql_running.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLsOW0C-lN_1OCe5K4:-LqNMGkL26VGbJaVd4pC:bq9epq1) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/distsql_running.go#L156)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Doesn't the latter imply the former? Perhaps we should set this outside of the loop and assert that there is a single flow. There are a few similar instances below. Maybe we should move this into a helper function that gets the list of flows and the localstate.
</blockquote></details>

done
I didn't add a helper. The other guys besides this one are randos that don't really matter, and also not completely analogous to this case.
___
*[pkg/sql/distsql_running.go, line 352 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNLLGP4dI8c8eI-3Ek:-LqNNeNrEKiBJYZKdz7O:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/distsql_running.go#L352)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: it is unusual to see a single opening parenthesis at the end of the line (several lines above).
</blockquote></details>

Done.
___
*[pkg/sql/distsql_running.go, line 353 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqMy0gj3dAXX-y2GrfK:-LqNNjxJ540o7FTzDPNr:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/distsql_running.go#L353)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

Can you make this an "internal error"? use AssertionErrorf.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 23 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLs3GGCsLV9HhrmUXt:-LqMlx5y9sHtn1fiU_lR:brwd9r6) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colexec/serial_unordered_synchronizer.go#L23)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Add some context as to why it exists, maybe point at the relevant issue #s.
</blockquote></details>

added some words
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 30 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLrutT68FVUw256tq5:-LqMmJcKCta0qHI3Z-91:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colexec/serial_unordered_synchronizer.go#L30)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] add type assertions so it's clear what interface(s) it's supposed to implement
</blockquote></details>

done
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 62 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqMZFq7Dg-xP_vFSMd4:-LqNO1oe3dKtt9r4h_Js:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colexec/serial_unordered_synchronizer.go#L62)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Yeah, I also think this is unnecessary.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 71 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqMZzYX0Z0gBYfTFIMt:-LqNMkrF-qlH7PhdRJzL:bn3xdlk) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colexec/serial_unordered_synchronizer.go#L71)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I won't make a stink about it but you could consider removing inputs when they're exhausted right? But I won't make a stink about it.
</blockquote></details>

meh, I like it more this way (with immutable `inputs`)
___
*[pkg/sql/colexec/serial_unordered_synchronizer.go, line 28 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNLj5D8-o3oYBPGzVq:-LqNNy5C5DPvZ0cDOq_y:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/colexec/serial_unordered_synchronizer.go#L28)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: the comment above seems to be out-of-date.
</blockquote></details>

Done.
___
*[pkg/sql/colflow/vectorized_flow.go, line 407 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLsEK97RTcX8cyh47B:-LqMlbgw4B9noaU5PCw0:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/colflow/vectorized_flow.go#L407)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Add a comment here, maybe point to the issue #s.
</blockquote></details>

done
___
*[pkg/sql/colflow/vectorized_flow.go, line 85 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNHfsW5owNM9n8_DJB:-LqNMttwB21C_akx-kET:b-pw8l6c) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/colflow/vectorized_flow.go#L85)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

The second part of this conditional is always (at least right now) false for the vectorized flows, but I guess it doesn't matter.
</blockquote></details>

yeah, I went back and forth, but I'd leave it like this
___
*[pkg/sql/distsql/server.go, line 361 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLwlOV7jqu45lq6CC5:-LqNFI7_BSHsWqXXdq6p:b-6bh6a8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/distsql/server.go#L361)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

This block is used 3 times, should be a helper
</blockquote></details>

I've moved this stuff back to `Server.setupFlow()`.
___
*[pkg/sql/distsql/server.go, line 393 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNLakZ4yhh-oWj3I92:-LqNOQHR6946AtBLFWc-:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/distsql/server.go#L393)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: a few words are missing, maybe "This will be used directly ..." (above)
</blockquote></details>

done
___
*[pkg/sql/rowflow/input_sync.go, line 368 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLtEw_94dID1DY7cPM:-LqMkkqA62R6dIzictSK:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/input_sync.go#L368)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Add more context as to why you would want that, maybe refer to FuseAggressively.
</blockquote></details>

done
___
*[pkg/sql/rowflow/row_based_flow.go, line 129 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLuHpR5mdNI-1C8XJQ:-LqMkXCK988lxfUTfBIv:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/row_based_flow.go#L129)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] Would be more readable if we put this first under a `if len(in.Streams) == 1` check (we won't need the `else`).
</blockquote></details>

done
___
*[pkg/sql/rowflow/row_based_flow.go, line 154 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLv-PT5OYstoJzcg4X:-LqMXkil4a1Fn2Xcfnvt:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/row_based_flow.go#L154)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] don't copy each spec,  do `pspec := &spec.Processors[i]`
</blockquote></details>

done
___
*[pkg/sql/rowflow/row_based_flow.go, line 156 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLunBFAtF20vnRuGBl:-LqMYDYI0XOfIa3wajMf:b6ksgcn) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/row_based_flow.go#L156)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

Shouldn't this be `continue` ? (same below)
</blockquote></details>

well this should never happen (cause we don't have procs with multiple outputs, right?). But changed.
___
*[pkg/sql/rowflow/row_based_flow.go, line 276 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLw0e5AyMzsF9EPi9D:-LqMYTX-2EpVd_Uiw1ul:b-d1keyg) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/row_based_flow.go#L276)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

what's numLocal for?
</blockquote></details>

nothing; leftover. removed.
___
*[pkg/sql/rowflow/row_based_flow.go, line 289 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqLvpSM9CqujxaR3rl0:-LqMYpVb9xTVXv0aHtnF:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/row_based_flow.go#L289)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] you can do `ordering := sqlbase.NoOrdering` and flip the`if`
</blockquote></details>

done
___
*[pkg/sql/rowflow/row_based_flow.go, line 162 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqMYJ58-OB7lQ4J-5Pp:-LqMYJ58-OB7lQ4J-5Pq:bq3zpw) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/rowflow/row_based_flow.go#L162)):*
> ```Go
> 			// The output is not pass-through and thus is being sent through a
> 			// router.
> 			return nil
> ```

this one should be a continue, yeah

**Review by andreimatei — COMMENTED** [review]
> You will also add the tests for the bugs that are being fixed, right?

I wasn't planning to. The only test that makes sense is the test that there's no concurrency on a RootTxn, and that's what we have with the assertion in `DistSQLPlanner.Run()`.
Since we've eliminated this concurrency, there's no timings I can play with any more to force a bad scenario. So the type of test I would have written below to demonstrate problems (e.g. have a union and block one side until the other one encounters a retriable error) would now be fairly non-sensical to write.

What's generally needed is an extension of Jepsen to more complex SQL queries, but that's big ask :)
So I'm thinking about it, but not sure what to do about it. Other than talk to Radu about stressing by hand the FK checks that showed problems initially, but I'm unsure about the current status of the FK checks.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-:-LqNV74mB8rugUP8R0pj:b-zfbbrc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @RaduBerinde, and @yuzefovich)

**Review by andreimatei — COMMENTED** [review]
merging so @knz can start a beta in the morning
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-:-LqOnx4IAIJFZC-n45OT:b-f9epj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/rowflow/input_sync.go, line 114 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqM_PcX3WFDxeBWytJ-:-LqOboJv38AbAuSQ7JZi:bcevojt) ([raw file](https://github.com/cockroachdb/cockroach/blob/f438061b1643fe750c127c99c96460dce81fc6b4/pkg/sql/rowflow/input_sync.go#L114)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

nit: extra conditional on every row is kinda sadface - can we instead swap out the Less implementation at constructor time? or just make another copy of the synchronizer like you did for the col one?
</blockquote></details>

I don't think that's worth it... This input sync is a fat cat anyway, this extra comparison will be lost in the noise. In the lean and mean vectorized world, that's a separate story...

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/41307)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @jordanlewis, @RaduBerinde, and @yuzefovich)

___
*[pkg/sql/rowflow/row_based_flow.go, line 111 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/41307#-LqNLenk0LJ5qinrRNOx:-LqOoDjL44b2Com2rHE3:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c07ebc4db59a72d60d94298ec91d895f971d1b54/pkg/sql/rowflow/row_based_flow.go#L111)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

[nit]: `s/the we/then we/` (above).
</blockquote></details>

done

**Pull request merged**
