### PR TITLE
rfc: upsert

### PR DESCRIPTION
**Pull request by danhhz**
[ci skip]

Rendered version at https://github.com/paperstreet/cockroach/blob/rfc_upsert/docs/RFCS/upsert.md

For #1962.

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6331)

### CODE REVIEW

**Comment by petermattis** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/upsert.md, line 41 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJDPhpVCLtgnDLsl24:-KGJDPhpVCLtgnDLsl25:-1975039026) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L41)):*
When a conflict is detected are there ever cases when we'll have to read the old row data? I'm not sure that the `ConditionFailedError` will have enough info, but I haven't thought through all of the cases yet. A few examples might be useful.

---

*[docs/RFCS/upsert.md, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJD0nU05oeB_tP6X0h:-KGJD0nU05oeB_tP6X0i:639659048) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L47)):*
Can you give an example of this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by bdarnell** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/upsert.md, line 11 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJPb-Yh17VjKl2VDfp:-KGJPb-ZKzjMGxDbyrvf:-1100710802) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L11)):*
Are our semantics close enough to MySQL's `REPLACE` that we'd be comfortable naming this `REPLACE` instead of `UPSERT`? "Replace" has the advantage of being a real word. 

---

*[docs/RFCS/upsert.md, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJMB8qFbCxRnF4qRuJ:-KGJMB8qFbCxRnF4qRuK:1055815209) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L34)):*
That's surprising, and different from mysql and postgres.

In [mysql](https://dev.mysql.com/doc/refman/5.7/en/insert-on-duplicate.html), if there are multiple unique indexes one row will be chosen arbitrarily for update: "If column b is also unique, the INSERT is equivalent to this UPDATE statement instead:

UPDATE table SET c=c+1 WHERE a=1 OR b=2 LIMIT 1;
If a=1 OR b=2 matches several rows, only one row is updated. In general, you should try to avoid using an ON DUPLICATE KEY UPDATE clause on tables with multiple unique indexes."

In [postgres](http://www.postgresql.org/docs/9.5/static/sql-insert.html), the `ON CONFLICT` clause takes an index specifier which is syntactically optional but "For ON CONFLICT DO UPDATE, a conflict_target must be provided.".  So the example above is not legal in postgres. 

I don't think we should allow for a single upsert to affect more than one row. I'd prefer the postgres approach of requiring a single index to be identified (and the short form should always use the primary key), instead of the mysql approach of choosing one arbitrarily on a row-by-row basis.

---

*[docs/RFCS/upsert.md, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJNWrmoIYmlSakI6dY:-KGJNWrmoIYmlSakI6dZ:-302326232) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L38)):*
The KV batch currently aborts at the first ConditionFailedError and discards all work that's already done in that batch. This will require work at the KV level to allow the CPuts that match to proceed while reporting on the mismatches. I'd like to see a detailed walkthrough of the KV execution of an upsert (maybe two, one for a primary key collision and one for a secondary unique index), because I think it gets complicated when you get a CPut when writing to the unique index but you're doing regular Puts to insert the data rows. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by paperstreet** [comment]
Thanks for the review! RFAL

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/upsert.md, line 11 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJPb-Yh17VjKl2VDfp:-KGNLErBBNcEFTYe6YF9:-600344965) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L11)):*
I started out calling it REPLACE, but became increasingly uncomfortable with that. The differences in unspecified fields (overwrite with field default vs leave it alone) and constraint behavior are significant and I think would be confusing.

FWIW, UPSERT seems to be what this is generally called (see https://wiki.postgresql.org/wiki/UPSERT).

---

*[docs/RFCS/upsert.md, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJMB8qFbCxRnF4qRuJ:-KGNMTQ7Qqn3lsKL4IdN:-890269336) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L34)):*
Ah, this behavior was inspired by REPLACE which can alter multiple rows (http://dev.mysql.com/doc/refman/5.7/en/replace.html).

Your proposal sounds great. I'll update.

---

*[docs/RFCS/upsert.md, line 38 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJNWrmoIYmlSakI6dY:-KGNSib1tDdibAGrt6vV:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L38)):*
Done.

---

*[docs/RFCS/upsert.md, line 41 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJDPhpVCLtgnDLsl24:-KGO60e3VU11N8D59ixW:1718519682) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L41)):*
In expanding on this, I realized it's a lot more complicated than I was thinking. Put together with the CPut thing Ben mentioned, I'm going to switch which strategy I'd like to use for this.

---

*[docs/RFCS/upsert.md, line 47 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJD0nU05oeB_tP6X0h:-KGNSJvZW-T21GZoWdTM:723211579) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L47)):*
I think this is no longer true after Ben's suggestion to avoid updating multiple table rows with one upsert row. Removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-:-KGOFkA4YZR9DeAwL39s:-411374130)*

**Comment by tschottdorf** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/upsert.md, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJMB8qFbCxRnF4qRuJ:-KGRvC6pGbNNZgxiMa_H:762662810) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L34)):*
s/(the short form uses the primary index)// (with the edit suggested above).

---

*[docs/RFCS/upsert.md, line 41 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJDPhpVCLtgnDLsl24:-KGRwZhhJNPfkWEW1yqS:74043899) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L41)):*
It wouldn't be so difficult if you had a smarter `CPut` which wouldn't error out (but instead return whether the write was carried out). The casual observer will notice the similarity in the discussion which led to the (so far unused) `InitPut` command. You want something like `InitPut` too, but its current form doesn't quite do what you want. Maybe it can be changed in a way that satisfies both use cases. cc @vivekmenezes

---

*[docs/RFCS/upsert.md, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRuuRZF1j40IpUQS7I:-KGRuuRZF1j40IpUQS7J:-1973014106) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L28)):*
Why even introduce UPSERT?

---

*[docs/RFCS/upsert.md, line 30 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRv3_DFqbji0Dz_BsX:-KGRv3_DFqbji0Dz_BsY:1396564461) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L30)):*
s/for the long form/for the long form for the primary index/

---

*[docs/RFCS/upsert.md, line 67 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRwFG5jB17mFKjjpBf:-KGRwFG5jB17mFKjjpBg:1333296465) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L67)):*
talking about committing first and then conditional puts is unintuitive - switch the order.

---

*[docs/RFCS/upsert.md, line 92 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRxtb7JqUICVbYQVy6:-KGRxtb7JqUICVbYQVy7:-163167742) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L92)):*
As noted above, I think changing `InitPut` might be what you want.

---

*[docs/RFCS/upsert.md, line 95 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRxya_r9DIK8zIBHt7:-KGRxya_r9DIK8zIBHt8:537063455) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L95)):*
+1. Easy to introduce later, hard to remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/upsert.md, line 41 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJDPhpVCLtgnDLsl24:-KGSB3l92QlIX19efQuP:955554981) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L41)):*
Yes please explore the use of a new command and perhaps include InitPut in those requirements. On reading this RFC, and with the expectation that users will expect high performance from UPSERT, we should support this at the KV layer if that's possible.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by vivekmenezes** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/upsert.md, line 41 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJDPhpVCLtgnDLsl24:-KGSBXJ_0XQ9ouaJnxuv:855999247) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L41)):*
Ah ha when you do detect a conflict you need some feedback to trigger updating the secondary indexes, so I suppose this operation will always run in two phases and adding in KV support for this might not pan out to be valuable. I'd optimize for the INSERT case FWIW because I believe folks use UPSERT for the rare conflict scenario.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, all commit checks successful.

---

*[docs/RFCS/upsert.md, line 28 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRuuRZF1j40IpUQS7I:-KGSCJi8iCxYEagJpCSF:790055750) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L28)):*
The short form is usually what is desired and mildly simpler to implement that the full generality of Postgres' `ON CONFLICT`. 

---

*[docs/RFCS/upsert.md, line 67 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRwFG5jB17mFKjjpBf:-KGSC4sXhcboVJ0KZRMS:-1740298510) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L67)):*
I think `s/committed/executed/g` would alleviate the confusion. Perhaps also `s/transaction batch/batch/g`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by bdarnell** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 8 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-:-KGScFAzB0MJwmtVsczK:1417088721)*

**Comment by paperstreet** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, some commit checks pending.

---

*[docs/RFCS/upsert.md, line 34 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJMB8qFbCxRnF4qRuJ:-KGSOCWLOUrCDlZPzbvU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L34)):*
Done.

---

*[docs/RFCS/upsert.md, line 41 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGJDPhpVCLtgnDLsl24:-KGSgyWNIJx6MO9zG-fU:739877766) ([raw file](https://github.com/cockroachdb/cockroach/blob/00423e9d6399a852361604f238a7d42f85c32566/docs/RFCS/upsert.md#L41)):*
Added a reference to InitPut.

@vivekmenezes In addition to the secondary indexes, the ON CONFLICT version can update completely different fields. Plus the primary key could be changing. It complicates the kv layer quite a bit.

Fwiw, I think the real-world uses of UPSERT are usually skewed toward mostly conflicts or mostly non-conflicts. It's tough to say which bucket our users will fall into.

---

*[docs/RFCS/upsert.md, line 30 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRv3_DFqbji0Dz_BsX:-KGSOA_Re9_zeDFJGHDh:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L30)):*
Done.

---

*[docs/RFCS/upsert.md, line 67 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRwFG5jB17mFKjjpBf:-KGSOQT3SI9eVHGQgJPU:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L67)):*
Done.

---

*[docs/RFCS/upsert.md, line 92 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRxtb7JqUICVbYQVy6:-KGSQEOqXE6NRUXKu2HY:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L92)):*
Done.

---

*[docs/RFCS/upsert.md, line 95 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGRxya_r9DIK8zIBHt7:-KGSMrSEFhPvBRHV4s9P:1777607599) ([raw file](https://github.com/cockroachdb/cockroach/blob/3c7c2e6538f2965b0bfbd43f95d57b5b257fdfbf/docs/RFCS/upsert.md#L95)):*
Ditto what Pete said above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by tschottdorf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-:-KGSl1ZoExe4Z61tCPIE:1417088721)*

**Comment by RaduBerinde** [comment]
LGTM

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/upsert.md, line 42 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGSo5Kp3XKcnIldxvkb:-KGSo5KqPE4ZaviXG4wY:-1825557428) ([raw file](https://github.com/cockroachdb/cockroach/blob/57fbf2cd70c6de88055515c874f77c70955fa310/docs/RFCS/upsert.md#L42)):*
If we really want to optimize for updates, we would get everything we need in the initial fetch..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-:-KGSojPvmXNjRXxv5pzC:676834233)*

**Comment by paperstreet** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/upsert.md, line 42 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGSo5Kp3XKcnIldxvkb:-KGSpRyGiJMu6n4bOgYI:-269257608) ([raw file](https://github.com/cockroachdb/cockroach/blob/57fbf2cd70c6de88055515c874f77c70955fa310/docs/RFCS/upsert.md#L42)):*
For the primary index yes. You need two if the conflict index is a secondary index.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by RaduBerinde** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/upsert.md, line 42 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGSo5Kp3XKcnIldxvkb:-KGSq5VLhbdF033FzVj2:-729164355) ([raw file](https://github.com/cockroachdb/cockroach/blob/57fbf2cd70c6de88055515c874f77c70955fa310/docs/RFCS/upsert.md#L42)):*
Why? If we e.g. fetch the entire row, don't we have everything we need to do the update, regardless where the conflict is?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by paperstreet** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/upsert.md, line 42 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGSo5Kp3XKcnIldxvkb:-KGSrMe6V_9ozvuasOpl:-1627255489) ([raw file](https://github.com/cockroachdb/cockroach/blob/57fbf2cd70c6de88055515c874f77c70955fa310/docs/RFCS/upsert.md#L42)):*
You don't (necessarily) know the fields in the primary key during the first read

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by paperstreet** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/upsert.md, line 42 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGSo5Kp3XKcnIldxvkb:-KGSreRdPaVjrzdu7DNx:1720913737) ([raw file](https://github.com/cockroachdb/cockroach/blob/57fbf2cd70c6de88055515c874f77c70955fa310/docs/RFCS/upsert.md#L42)):*
*the value of the fields in the primary key

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331)*

**Comment by RaduBerinde** [comment]
One thing - the RFC mentions the (legitimate) complaint that we tell people to use a table if they just want a KV API, and yet we don't provide them with a way to do `Put`s.

Unfortunately neither of the two options fixes that. We should implement this optimization when it is possible - e.g. if we try to UPSERT a row which has values for all the columns in the table and there are no indexes, we should simply use `Put`s.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/upsert.md, line 42 \[r3\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-KGSo5Kp3XKcnIldxvkb:-KGSrxujA6PMCtSKowY9:-1544537236) ([raw file](https://github.com/cockroachdb/cockroach/blob/57fbf2cd70c6de88055515c874f77c70955fa310/docs/RFCS/upsert.md#L42)):*
Ah, my bad, I was thinking of the "short form" (primary key) case, and read over the key "if .. the index is a secondary index" part.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-:-KGStEQWt7DEQx4Ft-uw:-1300765187)*

**Comment by paperstreet** [comment]
Good point about the optimization. Added a bit about that.

---

Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6331#-:-KGnRgr2uF4ZeSqg-Ot5:1094525107)*

**Pull request merged**
