### PR TITLE
ui: a number of small debug page fixes

### LINKED ISSUE #21238: ui/debug: CommandQueue viz page should display errors
Errors on the `/reports/range/<rangeID>/cmdqueue` page are not displayed to the user. Instead, the page will continuously say "loading..." (see attached image). These errors can occur for a number of reasons, including that we're talking to a node that does not contain a replica in the range. We should display these errors prominently.

screen shot 2018-01-04 at 2 45 44 pm 2

### PR DESCRIPTION
**Pull request by BramGruneir**
This is a follow up to the post merge comments left on #20828 and some fixes
that clean up how the keyed caches are used.

The biggest change is that is it a bad idea to create keys in two different
places. This fixes that for all debug page KeyedCachedDataReducers.

Also, in the command queue page, this adds a loading spinner and an error page.

Also this addresses some of the more egregious formatting changes from the PR
that were caused by prettier.

It would be nice to use prettier, but the defaults are clearly just wrong for
us.

Release note (ui): The command queue debug page now displays errors correctly.

Fixes #21238.

### CODE REVIEW

**Comment by vilterp** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ui/src/views/reports/containers/commandQueue/index.tsx, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21529#-L35AaeeJ_pfLqIcRuQj:-L35AaeeJ_pfLqIcRuQk:boy8uux) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f2944fbd5bc30cc6549e1404469d67b3d684357/pkg/ui/src/views/reports/containers/commandQueue/index.tsx#L67)):*
> ```XML
>     }
> 
>     const snapshot = commandQueue.data.snapshot;
> ```

any way to make the preceding lines (up to 45) common to the `Loading` component? Seems like practically every page needs this logic on its CachedDataReducer.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21529)*

**Comment by BramGruneir** [comment]
As requested, I have split this into a collection of smaller commits to make it easier to review.

---

Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[pkg/ui/src/views/reports/containers/commandQueue/index.tsx, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21529#-L35AaeeJ_pfLqIcRuQj:-L39AI9tOWj2ke6FjtIK:bjjqwqa) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f2944fbd5bc30cc6549e1404469d67b3d684357/pkg/ui/src/views/reports/containers/commandQueue/index.tsx#L67)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

any way to make the preceding lines (up to 45) common to the `Loading` component? Seems like practically every page needs this logic on its CachedDataReducer.
</blockquote></details>

I'd love to.  But not in this PR.  I think a combined loading/error component would be amazing and greatly simplify all of these pages. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21529#-:-L39AASacmNkL36aSdww:bi4ztu4)*

**Comment by vilterp** [comment]
:lgtm: Thanks for splitting out into commits. Nice to have these bugs fixed, but it still takes way to much code to just load some data and render it, with a spinner and error message. Not sure how to factor this better; maybe will take a whack at it tomorrow.

---

Reviewed 8 of 8 files at r1, 6 of 6 files at r2, 1 of 1 files at r3, 4 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ui/src/redux/apiReducers.ts, line 157 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21529#-L39a--L7QrZySZpklMU:-L39a--L7QrZySZpklMV:b-u8q9be) ([raw file](https://github.com/cockroachdb/cockroach/blob/512c170ddbc83b6d9eb36cf915356140236bfcd2/pkg/ui/src/redux/apiReducers.ts#L157)):*
> ```XML
> 
> export const certificatesRequestKey = (req: api.CertificatesRequestMessage): string =>
>   _.isEmpty(req.node_id) ? "none" : req.node_id;
> ```

Why do they keep getting called with an empty argument? Maybe a change for another PR, but would like to see that check done at some level above each of these key functions, if possible.

---

*[pkg/ui/src/views/reports/containers/commandQueue/index.tsx, line 67 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/21529#-L35AaeeJ_pfLqIcRuQj:-L39cBncUof759oAO_R5:b-88bvjv) ([raw file](https://github.com/cockroachdb/cockroach/blob/3f2944fbd5bc30cc6549e1404469d67b3d684357/pkg/ui/src/views/reports/containers/commandQueue/index.tsx#L67)):*
<details><summary><i>Previously, BramGruneir (Bram Gruneir) wrote…</i></summary><blockquote>

I'd love to.  But not in this PR.  I think a combined loading/error component would be amazing and greatly simplify all of these pages. 
</blockquote></details>

Fair.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21529#-:-L39dVfzlAGri2vIKJdp:b-rzl0wu)*

**Comment by BramGruneir** [comment]
I do have an inkling on how to clean this up by adding another component, but it will have to wait for a free Friday for me.  Feel free to give it a go.

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[pkg/ui/src/redux/apiReducers.ts, line 157 at r4](https://reviewable.io:443/reviews/cockroachdb/cockroach/21529#-L39a--L7QrZySZpklMU:-L39iWwM14HrRN1jPQ2d:b-xos20h) ([raw file](https://github.com/cockroachdb/cockroach/blob/512c170ddbc83b6d9eb36cf915356140236bfcd2/pkg/ui/src/redux/apiReducers.ts#L157)):*
<details><summary><i>Previously, vilterp (Pete Vilter) wrote…</i></summary><blockquote>

Why do they keep getting called with an empty argument? Maybe a change for another PR, but would like to see that check done at some level above each of these key functions, if possible.
</blockquote></details>

I'm not 100% certain the it can, but this does at least give it a key in case we get there.  This might not be needed at all but I feel a bit safer with it in there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/21529#-:-L39iIObWbDINSa2yVs-:beqes04)*

**Pull request merged**
