### PR TITLE
sql: verify errors are propagated through DistSQL sorting

### LINKED ISSUE #23519: stability: "missing stock row"
While running against the tpcc-10k dataset, I'm periodically seeing a "missing stock row" error. This occurs when the `newOrder` txn doesn't get all of the rows it expects.

Some additional logging provides more context:

```
5: missing stock row
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_05
FROM stock
WHERE (s_i_id, s_w_id) IN ((6879, 2615), (8447, 5535), (15502, 2615), (15567, 2615), (94436, 2615), (98429, 2615))
ORDER BY s_i_id
```

The `5` indicates that this was the last row (0-based index). Curiously, all 6 rows appear to be present:

```
root@localhost:26257/tpcc> SELECT COUNT(*) FROM stock 
WHERE (s_i_id, s_w_id) IN ((6879, 2615), (8447, 5535), (15502, 2615), (15567, 2615), (94436, 2615), (98429, 2615)); 
+-------+
| count |
+-------+
|     6 |
+-------+
```

Here's another instance:

```
0: missing stock row
SELECT s_quantity, s_ytd, s_order_cnt, s_remote_cnt, s_data, s_dist_06
FROM stock
WHERE (s_i_id, s_w_id) IN ((16641, 3428), (49897, 3137), (61754, 3137), (73026, 3137), (74538, 3137), (82097, 3137), (97858, 3137))
ORDER BY s_i_id
```

Running that query by hand produces:

```
+------------+-------+-------------+--------------+---------------------------------------------------+--------------------------+
| s_quantity | s_ytd | s_order_cnt | s_remote_cnt |                      s_data                       |        s_dist_06         |
+------------+-------+-------------+--------------+---------------------------------------------------+--------------------------+
|         21 |     1 |           1 |            0 | d9cxNWM9cGi1PisNhsHswUv55LfT0woDO                 | LJoNY1EJ8oUBmx4ZrEv03nwl |
|         31 |     0 |           0 |            0 | hmYBZchJ2XkTroMNw7zlz0rMgJZ4HEZS1jVPQL3Ws9m47gxL  | RFCsCgypns8ETW4DSmEyPcxP |
|         51 |     0 |           0 |            0 | TPto84xxOGIhMpxgwZnhCBwfERaQgDMQnRiuHK3ANXUfLplw2 | JIvxyM98pQLZepqz9BDJSgRj |
|         69 |     0 |           0 |            0 | fctCjgUrCp6mZPYA1Mp5ebwY7L5hMydEarjsLq            | 59IA2mTPIjpTDDFrX5MymvhU |
|         77 |     0 |           0 |            0 | L1sp2o1mODnXuB6EhvISmsGLDDCUa9rnabMjavcgCtE       | Am0cqZRCQYTQdflwZcQT120T |
|         32 |     7 |           1 |            0 | hrGkBMswDZxd22eRSZEJdN7QuVqkSmo9fL58              | MxTH7pI2Sx3EpKkoX7PhxbDJ |
|         75 |     0 |           0 |            0 | y2UVk0zm7VMaYqBLXM3bUMPZm7F9Jjp7DEdKgH77w         | ows1MwMR9lMjGXOlgm3Adx1J |
+------------+-------+-------------+--------------+---------------------------------------------------+--------------------------+
```

This is running `cockroach-v2.0-beta.20180305-143-gf95187e` (the current release-2.0 head).

### PR DESCRIPTION
**Pull request by petermattis**
Extend TestDistSQLRetryableError to verify that errors are propagated
properly through `sortAllProcessor`.

Closes #23519

Release note: None

### CODE REVIEW

**Comment by petermattis** [comment]
This test fails without #23541 and succeeds with it.

**Comment by arjunravinarayan** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23603#-:-L76AbZ-QnYP-TESFdEc:bnfp4nl)*

**Comment by andreimatei** [comment]
I think this test is too random to have been merged... Write a metadata propagation test for the sorter, since that has given us so much trouble.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23603#-:-L775yXvM9R516HF6oZV:bjs25vs)*

**Comment by petermattis** [comment]
> I think this test is too random to have been merged... Write a metadata propagation test for the sorter, since that has given us so much trouble.

More random than the existing `TestDistSQLRetryableError` checks? I think it is useful to have a specific regression test for any serious bug that is found and this issue certainly classifies as serious. FYI, @abhimadan is working on a set of holistic tests for metadata propagation of all processors. I'm not sure what the current state of that work is, but I know he has found a few more problems. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23603#-:-L77XpCrIj2QNFeH0Fxe:b-5ps8wu)*

**Comment by andreimatei** [comment]
> More random than the existing TestDistSQLRetryableError checks?

Yup, more random. `TestDistSQLRetryableError` used to be an integration test between DistSQL and KV. What you've added is, in my opinion, a test for the sorter done at the wrong level - it's neither specific enough to be a unit test for the sorter, nor general enough to convince that metadata propagation works more generally across more processors.


> I think it is useful to have a specific regression test for any serious bug that is found and this issue certainly classifies as serious.

Of course, the question is what's the right test.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23603#-:-L7AIES_tOQIA1mLQsnb:bh18bqg)*

**Comment by petermattis** [comment]
> nor general enough to convince that metadata propagation works more generally across more processors.

Definitely not, nor was I claiming it to be. It does reproduce the specified bug. Would you prefer if the test were in the `sql/distsqlrun` package?

> Of course, the question is what's the right test.

Do you mind giving me something actionable here? 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23603#-:-L7AKR9oIheZCgEAb-sX:b-pwww7y)*

**Comment by andreimatei** [comment]
What I had in mind was a test in sorter_test.go, using a mocked input for a sorter (a la `RowBuffer` or `RepeatableRowSource`, but you'd augment it with metadata) where you directly control what goes into the sorter and assert what comes out.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23603#-:-L7AR00EwpNlOJG8mqy_:bpj1dev)*

**Comment by abhimadan** [comment]
It's been alluded to twice here, so I'll give a brief description of what I'm working on. Essentially, "source" processors (tablereaders and values) will send metadata for each row they emit, and a "count" message once they are done emitting rows. If all of these metadata don't make it to the `distSQLReceiver`, the query will error out. This is fairly expensive to do all the time, so it would be gated (maybe with a cluster setting?). To run this on a large corpus of queries, we can enable this behaviour for all the logic tests with a flag. I'm still trying to polish up what I have before sending it out for review, but that's the gist of it.

Running logic tests won't produce `TxnMeta`s that have been associated with the serious bugs we've been seeing, but if these row metas are dropped, then other metadata (including `TxnMeta`) can also be dropped, which can indicate a more serious problem. Processors are agnostic to most upstream metadata and should just pass it along, so this test should make us fairly confident about the robustness of the processors (given the robustness of the logic tests in both success and failure cases).

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/cockroachdb/cockroach/23603#-:-L7AURO_-t5NKQstOYFh:b-cqp9k8)*

**Pull request merged**
