### PR TITLE
uuid: use cryptographically random ChaCha8 algorithm from math/rand/v2

### LINKED ISSUE #109397: performance of UUID generation is slow – implementation uses `getrandom` syscall
UUID (`gen_random_uuid()` and `uuid_v4()`) [1] are currently implemented using `crypto/rand`. While this provides a strong guarantee wrt security, it's highly inefficient. UUID v4 is a _randomly_ generated 128-bit value; nothing in the spec. [2] dictates that the implementation must use a cryptographically secure PRNG.

The current implementation effectively requires a system call (`getrandom`) for every new value of `gen_random_uuid()`.  This was originally observed in [3]. I have independently stumbled upon it while `strace`ing an execution of,

```
./workload fixtures import tpcc  --warehouses=100
```

which induced ~6 million syscalls to `getrandom`! The reason is we use `gen_random_uuid()` for automatically generating the `rowid` column in the `history` table [4].

### Microbenchmarks

Using the existing microbenchmarks `BenchmarkMakeV4` and `BenchmarkFastMakeV4` on `c5.9xlarge` (with PMU), we can see that the performance is > 10x slower; cf. ~811 ns/op vs. 54 ns/op.

```
 perf stat -r 3 -C2 taskset -c 2 uuid_test -test.v --test.benchtime=10000000x -test.bench 'BenchmarkMakeV4' -test.run '^$'
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
BenchmarkMakeV4
BenchmarkMakeV4 	10000000	       811.3 ns/op
PASS
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
BenchmarkMakeV4
BenchmarkMakeV4 	10000000	       812.2 ns/op
PASS
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
BenchmarkMakeV4
BenchmarkMakeV4 	10000000	       812.3 ns/op
PASS

 Performance counter stats for 'CPU(s) 2' (3 runs):

           8128.12 msec cpu-clock                 #    1.000 CPUs utilized            ( +-  0.09% )
             48426      context-switches          #    5.953 K/sec                    ( +-  2.29% )
                 2      cpu-migrations            #    0.246 /sec
              1976      page-faults               #  242.898 /sec                     ( +- 19.25% )
       27698246183      cycles                    #    3.405 GHz                      ( +-  0.02% )
       32737716985      instructions              #    1.18  insn per cycle           ( +-  0.03% )
        3791218261      branches                  #  466.032 M/sec                    ( +-  0.06% )
          14589289      branch-misses             #    0.38% of all branches          ( +-  0.23% )

           8.12496 +- 0.00284 seconds time elapsed  ( +-  0.03% )
```

```
perf stat -r 3 -C2 taskset -c 2 uuid_test -test.v --test.benchtime=10000000x -test.bench 'BenchmarkFastMakeV4' -test.run '^$'
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
BenchmarkFastMakeV4
BenchmarkFastMakeV4 	10000000	        53.98 ns/op
PASS
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
BenchmarkFastMakeV4
BenchmarkFastMakeV4 	10000000	        53.98 ns/op
PASS
goos: linux
goarch: amd64
cpu: Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz
BenchmarkFastMakeV4
BenchmarkFastMakeV4 	10000000	        53.97 ns/op
PASS

 Performance counter stats for 'CPU(s) 2' (3 runs):

            544.35 msec cpu-clock                 #    0.999 CPUs utilized            ( +-  2.10% )
               254      context-switches          #  456.941 /sec                     ( +-  0.73% )
                 2      cpu-migrations            #    3.598 /sec
               798      page-faults               #    1.436 K/sec                    ( +-  0.11% )
        1875740389      cycles                    #    3.374 GHz                      ( +-  0.03% )
        4910290809      instructions              #    2.62  insn per cycle           ( +-  0.00% )
        1013553042      branches                  #    1.823 G/sec                    ( +-  0.00% )
            168504      branch-misses             #    0.02% of all branches          ( +-  0.91% )

          0.544744 +- 0.000349 seconds time elapsed  ( +-  0.06% )
```

[1] https://www.cockroachlabs.com/docs/stable/uuid
[2] https://www.ietf.org/rfc/rfc4122.txt
[3] https://github.com/cockroachdb/cockroach/issues/30236#issuecomment-434588162
[4]

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/109397

###  uuid: add parallel benchmark

This lets us test the effect of sharing a global random source
between multiple threads.

### uuid: use mathRandReader instead of crypto/rand

go1.22 uses a new random number generator called ChaCha8, and it is
cryptographically random. We can use this instead of the slower
crypto/rand random source to ensure UUID uniqueness.

https://go.dev/blog/chacha8rand

### *: rename FastMakeV4 to MakeV4

There's no need for a separate FastMakeV4 function now; it's the same as
MakeV4.

###  uuid: use math/rand/v2

This new rand package is an improvement since it makes it impossible to
accidentally set a global seed for the shared RNG, which would make
UUIDs become entirely predictable and collision-prone.

It also appears to be faster. I think it's because now the global RNG
does not need to be guarded by a mutex.

```
Removing the top-level Seed also let us hard-code the use of scalable,
per-thread generators by the top-level methods, avoiding a GODEBUG check
at each use.
```

See:
- https://go.dev/blog/randv2
- golang/go@0b9974d

### uuid: remove impossible error cases; reduce branching

This consolidates some conditional branches so that the Uint64()
function is always used to generate random numbers rather than using
(io.Reader).Read(). This change makes it so some functions can no longer
return errors, so some tests were removed.

---

### Diff between `crypto/rand` and `math/rand/v1`
```
goos: darwin
goarch: arm64
                       │ bench-crypto-rand.txt │    bench-math-rand-v1-trial1.txt    │
                       │        sec/op         │   sec/op     vs base                │
FastMakeV4-8                       29.49n ± 1%   29.68n ± 1%   +0.63% (p=0.011 n=10)
MakeV4-8                          519.50n ± 0%   29.52n ± 0%  -94.32% (p=0.000 n=10)
ConcurrentFastMakeV4-8             133.2n ± 0%   133.0n ± 0%   -0.19% (p=0.048 n=10)
ConcurrentMakeV4-8                 464.6n ± 1%   133.0n ± 0%  -71.36% (p=0.000 n=10)
geomean                            175.5n        62.75n       -64.24%

                       │ bench-crypto-rand.txt │      bench-math-rand-v1-trial1.txt      │
                       │         B/op          │    B/op     vs base                     │
FastMakeV4-8                      0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
MakeV4-8                          16.00 ± 0%      0.00 ± 0%  -100.00% (p=0.000 n=10)
ConcurrentFastMakeV4-8            0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
ConcurrentMakeV4-8                16.00 ± 0%      0.00 ± 0%  -100.00% (p=0.000 n=10)
geomean                                      ²               ?                       ² ³
¹ all samples are equal
² summaries must be >0 to compute geomean
³ ratios must be >0 to compute geomean

                       │ bench-crypto-rand.txt │      bench-math-rand-v1-trial1.txt      │
                       │       allocs/op       │ allocs/op   vs base                     │
FastMakeV4-8                      0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
MakeV4-8                          1.000 ± 0%     0.000 ± 0%  -100.00% (p=0.000 n=10)
ConcurrentFastMakeV4-8            0.000 ± 0%     0.000 ± 0%         ~ (p=1.000 n=10) ¹
ConcurrentMakeV4-8                1.000 ± 0%     0.000 ± 0%  -100.00% (p=0.000 n=10)
geomean                                      ²               ?                       ² ³
¹ all samples are equal
² summaries must be >0 to compute geomean
³ ratios must be >0 to compute geomean
```

### Diff between `math/rand/v1` and `math/rand/v2`
```
goos: darwin
goarch: arm64
                   │ bench-math-rand-v1-trial2.txt │       bench-math-rand-v2.txt        │
                   │            sec/op             │   sec/op     vs base                │
MakeV4-8                               29.44n ± 1%   12.18n ± 1%  -58.61% (p=0.000 n=10)
ConcurrentMakeV4-8                   133.100n ± 0%   1.642n ± 2%  -98.77% (p=0.000 n=10)
geomean                                62.60n        4.472n       -92.86%

                   │ bench-math-rand-v1-trial2.txt │       bench-math-rand-v2.txt        │
                   │             B/op              │    B/op     vs base                 │
MakeV4-8                              0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ConcurrentMakeV4-8                    0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
geomean                                          ²               +0.00%                ²
¹ all samples are equal
² summaries must be >0 to compute geomean

                   │ bench-math-rand-v1-trial2.txt │       bench-math-rand-v2.txt        │
                   │           allocs/op           │ allocs/op   vs base                 │
MakeV4-8                              0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
ConcurrentMakeV4-8                    0.000 ± 0%     0.000 ± 0%       ~ (p=1.000 n=10) ¹
geomean                                          ²               +0.00%                ²
¹ all samples are equal
² summaries must be >0 to compute geomean
```

### Overall improvement from this PR
```
goos: darwin
goarch: arm64
                       │ bench-crypto-rand.txt │        bench-math-rand-v2.txt         │
                       │        sec/op         │   sec/op     vs base                  │
FastMakeV4-8                       29.49n ± 1%
MakeV4-8                          519.50n ± 0%   12.18n ± 1%  -97.65% (p=0.000 n=10)
ConcurrentFastMakeV4-8             133.2n ± 0%
ConcurrentMakeV4-8               464.600n ± 1%   1.642n ± 2%  -99.65% (p=0.000 n=10)
geomean                            175.5n        4.472n       -99.09%                ¹
¹ benchmark set differs from baseline; geomeans may not be comparable

                       │ bench-crypto-rand.txt │          bench-math-rand-v2.txt          │
                       │         B/op          │   B/op     vs base                       │
FastMakeV4-8                      0.000 ± 0%
MakeV4-8                          16.00 ± 0%     0.00 ± 0%  -100.00% (p=0.000 n=10)
ConcurrentFastMakeV4-8            0.000 ± 0%
ConcurrentMakeV4-8                16.00 ± 0%     0.00 ± 0%  -100.00% (p=0.000 n=10)
geomean                                      ¹              ?                       ² ¹ ³
¹ summaries must be >0 to compute geomean
² benchmark set differs from baseline; geomeans may not be comparable
³ ratios must be >0 to compute geomean

                       │ bench-crypto-rand.txt │          bench-math-rand-v2.txt           │
                       │       allocs/op       │ allocs/op   vs base                       │
FastMakeV4-8                      0.000 ± 0%
MakeV4-8                          1.000 ± 0%     0.000 ± 0%  -100.00% (p=0.000 n=10)
ConcurrentFastMakeV4-8            0.000 ± 0%
ConcurrentMakeV4-8                1.000 ± 0%     0.000 ± 0%  -100.00% (p=0.000 n=10)
geomean                                      ¹               ?                       ² ¹ ³
¹ summaries must be >0 to compute geomean
² benchmark set differs from baseline; geomeans may not be comparable
³ ratios must be >0 to compute geomean
```

### CODE REVIEW

**Review by yuzefovich — COMMENTED** [review]
Very nice! I have some minor comments.

Should we audit all usages of `crypto/rand` in CRDB codebase? For example, we use it in `raft/raft.go`, but on a quick glance to a person not familiar with it, even non-crypto RNG would work there (it was added in https://github.com/etcd-io/raft/pull/50 in the upstream repo). Perhaps worth filing an issue to do the audit?

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 39 of 39 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-:-NyMPwaU8H9bilnE6ixc:b-xvaus1)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @mgartner, @rafiss, and @srosenberg)

___
*[`pkg/util/uuid/generator.go` line 293 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMSoW2AUH4NHSZOPk1:-NyMSoW2AUH4NHSZOPk2:b7oqbi6) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8215eb7cd6652598205cc88dfb5e50577e46dbd/pkg/util/uuid/generator.go#L293)):*
> ```Go
> func RandomHardwareAddrFunc() (net.HardwareAddr, error) {
> 	var hardwareAddr = make(net.HardwareAddr, 6)
> 	binary.BigEndian.PutUint32(hardwareAddr[:4], math_rand.Uint32())
> ```

nit: I'm a bit confused about what's going on here. It seems like we want to generate 6 random bytes, so we generate 4 bytes twice while losing 2 bytes from the first generation? Perhaps a quick comment explaining and justifying this would be helpful (like we don't have `Uint16`).
___
*[`pkg/util/uuid/generator.go` line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMTpKHAfXGh2f3DS7i:-NyMTpKHAfXGh2f3DS7j:b1r8nup) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e61ecaa2f47f6ed2a86e1ce748caff481744a68/pkg/util/uuid/generator.go#L94)):*
> ```Go
> 	storageMutex      syncutil.Mutex
> 
> 	rand interface {
> ```

Should we store the function directly? I.e.:
```
randUint64 func() uint64
```
IIUC whenever we're storing an interface, Go needs to perform interface dispatch on each `interface.Uint64()` invocation whereas if we just store the function directly that overhead can be avoided.
___
*[`pkg/util/uuid/uuid_wrapper.go` line 103 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMUM890KPE7UiBfm-Q:-NyMUM890KPE7UiBfm-R:b-mlc8fw) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e61ecaa2f47f6ed2a86e1ce748caff481744a68/pkg/util/uuid/uuid_wrapper.go#L103)):*
> ```Go
> 
> // mathRandReader is an RNG that calls through to "math/rand".Uint64
> // which is safe for concurrent use. As of go1.20, the math/rand (and
> ```

nit: go1.22 right?
___
*[`scripts/bench` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMP3XICxZ2avIHRtSX:-NyMP3XICxZ2avIHRtSY:by13rmb) ([raw file](https://github.com/cockroachdb/cockroach/blob/b36bc6c654ea0edaf3bd9a043f6a56449822562c/scripts/bench#L55)):*
> ```
>   echo "Switching to $name"
>   git checkout -q "$sha"
>   (set -x; ./dev bench ${PKG} --timeout=${BENCHTIMEOUT:-5m} --filter=${BENCHES} --count=${N:-10} $benchtime --bench-mem -v --stream-output --ignore-cache --test-args='-test.cpu 8' | tee "${dest}/bench.${name}" 2> "${dest}/log.txt")
> ```

What prompted this change?
___
*[`pkg/util/uuid/generator_test.go` line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMRx_G5Xhz43S5_eYE:-NyMRx_G5Xhz43S5_eYF:bou8k73) ([raw file](https://github.com/cockroachdb/cockroach/blob/76226deae669826feab6fdb6c529bff958a731b2/pkg/util/uuid/generator_test.go#L363)):*
> ```Go
> 	b.Run("V4", func(b *testing.B) {
> 		for i := 0; i < b.N; i++ {
> 			Must(NewV4())
> ```

nit: we could replace this with `MakeV4`.
___
*[`pkg/util/uuid/generator_test.go` line 366 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMRty69oDHxvs-deM7:-NyMRty69oDHxvs-deM8:b-ey1g68) ([raw file](https://github.com/cockroachdb/cockroach/blob/76226deae669826feab6fdb6c529bff958a731b2/pkg/util/uuid/generator_test.go#L366)):*
> ```Go
> 		}
> 	})
> 	b.Run("FastV4", func(b *testing.B) {
> ```

nit: this case is now redundant with `V4` above and should probably be removed.

**Review by mgartner — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 39 of 39 files at r3, 2 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-:-NyMrZLB9Lcakxkx7VEp:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @rafiss, @srosenberg, and @yuzefovich)

___
*[`pkg/util/uuid/generator.go` line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMpDwlB4PkoBu1TEp6:-NyMpDwlB4PkoBu1TEp7:bebmz2e) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8215eb7cd6652598205cc88dfb5e50577e46dbd/pkg/util/uuid/generator.go#L26)):*
> ```Go
> 	"hash"
> 	"io"
> 	math_rand "math/rand/v2"
> ```

nit: we typically avoid underscores in package names/aliases, don't we? Maybe `randv2` or just `rand`?
___
*[`pkg/util/uuid/generator.go` line 293 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMSoW2AUH4NHSZOPk1:-NyMpmGIDYO9K8k0oDhc:b-gu9xtc) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8215eb7cd6652598205cc88dfb5e50577e46dbd/pkg/util/uuid/generator.go#L293)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'm a bit confused about what's going on here. It seems like we want to generate 6 random bytes, so we generate 4 bytes twice while losing 2 bytes from the first generation? Perhaps a quick comment explaining and justifying this would be helpful (like we don't have `Uint16`).
</blockquote></details>

Why can't we generate one 64-bit integer and use 6 bytes from it?
___
*[`pkg/util/uuid/generator.go` line 119 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMrDWe4T5fRKfpot-N:-NyMrDWe4T5fRKfpot-O:b30drky) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e61ecaa2f47f6ed2a86e1ce748caff481744a68/pkg/util/uuid/generator.go#L119)):*
> ```Go
> func NewGenWithReader(r interface {
> 	Uint64() uint64
> }) *Gen {
> ```

did you mean to use the `rand` interface here? disregard if you remove the interface entirely based on Yahor's suggestion.
___
*[`pkg/util/uuid/uuid_wrapper.go` line 17 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMpvh3629j5ntlDe-n:-NyMpvh3629j5ntlDe-o:b3d5ifa) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8215eb7cd6652598205cc88dfb5e50577e46dbd/pkg/util/uuid/uuid_wrapper.go#L17)):*
> ```Go
> 	"encoding/json"
> 	"fmt"
> 	math_rand "math/rand/v2"
> ```

nit: `randv2`?

**Review by rafiss — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124271)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (waiting on @mgartner, @srosenberg, and @yuzefovich)

___
*[`pkg/util/uuid/generator.go` line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMpDwlB4PkoBu1TEp6:-NyWfYhX7kOeEWY2cArb:bpeo76i) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8215eb7cd6652598205cc88dfb5e50577e46dbd/pkg/util/uuid/generator.go#L26)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: we typically avoid underscores in package names/aliases, don't we? Maybe `randv2` or just `rand`?
</blockquote></details>

i'm not aware of that convention. there are existing examples with underscores:
```
io_prometheus_client "github.com/prometheus/client_model/go"

otel_pb "github.com/cockroachdb/cockroach/pkg/obsservice/obspb/opentelemetry-proto/common/v1"
```
___
*[`pkg/util/uuid/generator.go` line 293 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMSoW2AUH4NHSZOPk1:-NyWilFo7XwHUOW7pvkP:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8215eb7cd6652598205cc88dfb5e50577e46dbd/pkg/util/uuid/generator.go#L293)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Why can't we generate one 64-bit integer and use 6 bytes from it?
</blockquote></details>

done
___
*[`pkg/util/uuid/generator.go` line 94 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMTpKHAfXGh2f3DS7i:-NyWfmpDBczJsNHoEfiM:bxnhsst) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e61ecaa2f47f6ed2a86e1ce748caff481744a68/pkg/util/uuid/generator.go#L94)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

Should we store the function directly? I.e.:
```
randUint64 func() uint64
```
IIUC whenever we're storing an interface, Go needs to perform interface dispatch on each `interface.Uint64()` invocation whereas if we just store the function directly that overhead can be avoided.
</blockquote></details>

yeah, that is correct, nice catch
___
*[`pkg/util/uuid/generator.go` line 119 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMrDWe4T5fRKfpot-N:-NyWhjLT1MojZACXXjJf:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e61ecaa2f47f6ed2a86e1ce748caff481744a68/pkg/util/uuid/generator.go#L119)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

did you mean to use the `rand` interface here? disregard if you remove the interface entirely based on Yahor's suggestion.
</blockquote></details>

done
___
*[`pkg/util/uuid/uuid_wrapper.go` line 17 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMpvh3629j5ntlDe-n:-NyWimi1A2PWJZBUnW1f:b8053mr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a8215eb7cd6652598205cc88dfb5e50577e46dbd/pkg/util/uuid/uuid_wrapper.go#L17)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

nit: `randv2`?
</blockquote></details>

i think the relevant distinction with the alias is to differentiate `crypto/rand` usages from `math/rand`, so i'd prefer to keep this.
___
*[`pkg/util/uuid/uuid_wrapper.go` line 103 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMUM890KPE7UiBfm-Q:-NyWj5SU3kIedpJKfeaU:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/0e61ecaa2f47f6ed2a86e1ce748caff481744a68/pkg/util/uuid/uuid_wrapper.go#L103)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: go1.22 right?
</blockquote></details>

done
___
*[`scripts/bench` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMP3XICxZ2avIHRtSX:-NyWjg2h2Cr9JtcoKXXA:b-47en0d) ([raw file](https://github.com/cockroachdb/cockroach/blob/b36bc6c654ea0edaf3bd9a043f6a56449822562c/scripts/bench#L55)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

What prompted this change?
</blockquote></details>

the new benchmark i added is a parallel benchmark, which is important, since the old implementation was worse under concurrency. before this change, only 1 CPU would ever be used by the test, so there never was actually any parallelism.
___
*[`pkg/util/uuid/generator_test.go` line 363 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMRx_G5Xhz43S5_eYE:-NyWkMAp15DZjyJ_y4Yj:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/76226deae669826feab6fdb6c529bff958a731b2/pkg/util/uuid/generator_test.go#L363)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: we could replace this with `MakeV4`.
</blockquote></details>

done
___
*[`pkg/util/uuid/generator_test.go` line 366 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMRty69oDHxvs-deM7:-NyWkM_428MYYE-H-4v4:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/76226deae669826feab6fdb6c529bff958a731b2/pkg/util/uuid/generator_test.go#L366)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: this case is now redundant with `V4` above and should probably be removed.
</blockquote></details>

done

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 40 of 40 files at r6, 39 of 39 files at r7, 2 of 2 files at r8, 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-:-NyWubMc0-bajbzjeWgD:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mgartner, @rafiss, and @srosenberg)

___
*[`pkg/util/uuid/generator.go` line 116 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyWuBCg51cO0Ss14oUr:-NyWuBCg51cO0Ss14oUs:byboogg) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd1cfbe4e8a7024176e19ed8fea66b46e27c2ade/pkg/util/uuid/generator.go#L116)):*
> ```Go
> 
> // NewGenWithRand returns a new instance of gen which uses randUint64 as its
> // source of  randomness.
> ```

nit: double space "of  randomness".
___
*[`pkg/util/uuid/generator.go` line 177 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyWuRz40u1Em91ScVa2:-NyWuRz40u1Em91ScVa3:b8q1wa5) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd1cfbe4e8a7024176e19ed8fea66b46e27c2ade/pkg/util/uuid/generator.go#L177)):*
> ```Go
> 
> // NewV4 returns a randomly generated UUID.
> func (g *Gen) NewV4() (UUID, error) {
> ```

nit: perhaps worth removing `error` return parameter too.
___
*[`scripts/bench` line 55 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyMP3XICxZ2avIHRtSX:-NyWt2qpAZWpxpHeKzoB:b-uk6ot8) ([raw file](https://github.com/cockroachdb/cockroach/blob/b36bc6c654ea0edaf3bd9a043f6a56449822562c/scripts/bench#L55)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

the new benchmark i added is a parallel benchmark, which is important, since the old implementation was worse under concurrency. before this change, only 1 CPU would ever be used by the test, so there never was actually any parallelism.
</blockquote></details>

Ack, thanks for the context.

**Comment by rafiss** [comment]
tftr!

bors r+

**Review by rafiss — COMMENTED** [review]
> Dismissed @yuzefovich from a discussion.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/124271)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner, @srosenberg, and @yuzefovich)

___
*[`pkg/util/uuid/generator.go` line 116 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyWuBCg51cO0Ss14oUr:-NyWztfY0Nevi5puVpXN:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd1cfbe4e8a7024176e19ed8fea66b46e27c2ade/pkg/util/uuid/generator.go#L116)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: double space "of  randomness".
</blockquote></details>

done
___
*[`pkg/util/uuid/generator.go` line 177 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/124271#-NyWuRz40u1Em91ScVa2:-NyX1TlU7o35CcZuCBxq:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/dd1cfbe4e8a7024176e19ed8fea66b46e27c2ade/pkg/util/uuid/generator.go#L177)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: perhaps worth removing `error` return parameter too.
</blockquote></details>

done

**Comment by rafiss** [comment]
tftr!

bors r+

**Pull request merged**
