### PR TITLE
sql: implement ON CONFLICT DO NOTHING

### PR DESCRIPTION
**Pull request by danhhz**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/6633)

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
:lgtm:

<details><summary><i>Previously, paperstreet (Dan Harrison) wrote…</i></summary>
> #### sql: implement ON CONFLICT DO NOTHING
> 
> 
> 
> 
> </details>


---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[sql/insert.go, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633#-KHVnJxM2m27l_TF_jv6:-KHVnJxM2m27l_TF_jv7:-67339131) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7809fba029d088aa12d28405ba9c7752693a6c6/sql/insert.go#L212)):*
> ```Go
> 
> 		if n.OnConflict.DoNothing {
> 			// TODO(dan): Postgres allows ON CONFLICT DO NOTHING without specifying a
> ```

Could you open an issue so we can track this on Github as well?

---

*[sql/tablewriter.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633#-KHVnY4pCbrTvyiwvYOC:-KHVnY4pCbrTvyiwvYOD:-889418953) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7809fba029d088aa12d28405ba9c7752693a6c6/sql/tablewriter.go#L178)):*
> ```Go
> 	var err error
> 	var fetchCols []sqlbase.ColumnDescriptor
> 	if tu.updateCols == nil {
> ```

Would `len(tu.updateCols) == 0` (and below) be a bit more expressive?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633#-:-KHVnmN5k2gB_aPIuoED:1417088721)*

**Comment by RaduBerinde** [comment]
:lgtm:

<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> :lgtm:</details>


---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633#-:-KHW8cAjcIPljzAY5aKv:1417088721)*

**Comment by paperstreet** [comment]
TFTR!

<details><summary><i>Previously, RaduBerinde wrote…</i></summary>
> :lgtm:</details>


---

Review status: 4 of 7 files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[sql/insert.go, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633#-KHVnJxM2m27l_TF_jv6:-KHWNPCI-Tn0vUCSDz-A:-258643302) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7809fba029d088aa12d28405ba9c7752693a6c6/sql/insert.go#L212)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Could you open an issue so we can track this on Github as well?</details>
Great idea. https://github.com/cockroachdb/cockroach/issues/6637

---

*[sql/tablewriter.go, line 178 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633#-KHVnY4pCbrTvyiwvYOC:-KHWNNncCqjHYxHtEr28:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7809fba029d088aa12d28405ba9c7752693a6c6/sql/tablewriter.go#L178)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Would `len(tu.updateCols) == 0` (and below) be a bit more expressive?</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633#-:-KHWNZIwIIWFEg7PSkR9:-485616692)*

**Comment by nvanbenschoten** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/insert.go, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633#-KHVnJxM2m27l_TF_jv6:-KHWOSbQBQFoB5tK-_GP:50431225) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7809fba029d088aa12d28405ba9c7752693a6c6/sql/insert.go#L212)):*
<details><summary><i>Previously, paperstreet (Dan Harrison) wrote…</i></summary>
> Great idea. https://github.com/cockroachdb/cockroach/issues/6637</details>
Seems like a different issue :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633)*

**Comment by paperstreet** [comment]
Review status: 4 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[sql/insert.go, line 212 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633#-KHVnJxM2m27l_TF_jv6:-KHWPMzoa3Ii0ZZUu2kE:2040388250) ([raw file](https://github.com/cockroachdb/cockroach/blob/c7809fba029d088aa12d28405ba9c7752693a6c6/sql/insert.go#L212)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary>
> Seems like a different issue :)</details>
Whoops: https://github.com/cockroachdb/cockroach/issues/6639

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/6633)*

**Comment by jseldess** [comment]
Docs updated with https://github.com/cockroachdb/docs/pull/308

**Pull request merged**
