### PR TITLE
colexec: add the disk-spilling to the hash aggregator

### LINKED ISSUE #42485: rowexec: spill hashAggregator buckets to disk
It seems like a `hashAggregator` moves to draining if there is not enough memory to allocate a new bucket:
```
func (ag *aggregatorBase) createAggregateFuncs() (aggregateFuncs, error) {
	if err := ag.bucketsAcc.Grow(ag.Ctx, sizeOfAggregateFunc*int64(len(ag.funcs))); err != nil {
		return nil, err
	}
	bucket := make(aggregateFuncs, len(ag.funcs))
	for i, f := range ag.funcs {
		agg := f.create(ag.FlowCtx.EvalCtx, f.arguments)
		if err := ag.bucketsAcc.Grow(ag.Ctx, agg.Size()); err != nil {
			return nil, err
		}
		bucket[i] = agg
	}
	return bucket, nil
}
```

We should have a strategy to spill to disk. It seems like this case is very rare (we haven't gotten any complaints about an aggregation running out of memory).

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: mechanical changes for the external hash aggregator**

This commit performs several mechanical changes prompted by the
follow up work on the external hash aggregator:
- extract the arguments to `newSpillingQueue` into a struct
- add `context.Context` as the first argument to `ExportBuffered`
method
- extract aggregator tests into global variables.

It also fixes a couple of cosmetic issues with the memory account
names for the external operators.

Release note: None

**colexec: add the disk-spilling to the hash aggregator**

This commit introduces the external hash aggregator that uses the
hash-based partitioner with the in-memory hash aggregator as the "main"
strategy and the external sort + the ordered aggregator as the
"fallback". This approach was benchmarked against simply using the
external sort + the ordered aggregator, and on larger datasets the
chosen approach is noticably faster.

In order for the in-memory hash aggregator to be able to actually
fallback we need to keep track of all of the input tuples since it is
very hard to spill the intermediate results of computation. This
required the usage of a spilling queue and enqueuing the copies of all
input batches into it. The benchmarks show that the performance overhead
of this is relatively small while the spilling queue doesn't have to
spill to disk (on the order of 15-20% hit in micro-benchmarks), however,
when the spilling queue needs to use the disk, the hit can be 2-3x in
case when the hash aggregator itself doesn't have spill.

One notable change is that because the ordered aggregator doesn't
support filtering aggregation, we cannot support it in the external hash
aggregator, and as a result the hash aggregation is currently not
planned if filtering aggregation is requested.

Another notable change is the addition of unwrapping datum when
converting it to JSON using `AsJSON` - for some reason, the row engine
was panicking on `TestAggregatorAgainstProcessor` test with `json_agg`
function, yet I couldn't reproduce it outside of the unit test, still
I believe this addition doesn't make things worse.

Fixes: #42485.

Release note (sql change): Hash aggregation can now spill to disk when
it exhausts its memory limit when executed via the vectorized engine.

### CODE REVIEW

**Comment by yuzefovich** [comment]
I think it is RFAL.

The impact of the input tuples tracking is [here](https://gist.github.com/yuzefovich/3e1ba73b436e4658be7434f4056dd769) and the current benchmarks of the external hash aggregator:
```
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=1/numInputRows=1024-24         	    2211	    476218 ns/op	  17.20 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=2/numInputRows=1024-24         	    3430	    329819 ns/op	  24.84 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=32/numInputRows=1024-24        	    7532	    156059 ns/op	  52.49 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=128/numInputRows=1024-24       	   10000	    125719 ns/op	  65.16 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=1024/numInputRows=1024-24      	   10000	    122276 ns/op	  67.00 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=1/numInputRows=65536-24        	      38	  28239566 ns/op	  18.57 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=2/numInputRows=65536-24        	      82	  16028462 ns/op	  32.71 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=32/numInputRows=65536-24       	     322	   3729441 ns/op	 140.58 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=128/numInputRows=65536-24      	     378	   3194185 ns/op	 164.14 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=1024/numInputRows=65536-24     	     498	   2432773 ns/op	 215.51 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=1/numInputRows=4194304-24      	       1	2391378590 ns/op	  14.03 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=2/numInputRows=4194304-24      	       1	1389531760 ns/op	  24.15 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=32/numInputRows=4194304-24     	       4	 277958127 ns/op	 120.72 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=128/numInputRows=4194304-24    	       5	 239955596 ns/op	 139.84 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=false/int/groupSize=1024/numInputRows=4194304-24   	       5	 227793235 ns/op	 147.30 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=1/numInputRows=1024-24          	     162	   7933115 ns/op	   1.03 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=2/numInputRows=1024-24          	     152	   7966516 ns/op	   1.03 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=32/numInputRows=1024-24         	     100	  10126651 ns/op	   0.81 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=128/numInputRows=1024-24        	     147	   7766586 ns/op	   1.05 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=1024/numInputRows=1024-24       	     364	   3184790 ns/op	   2.57 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=1/numInputRows=65536-24         	      32	  40267586 ns/op	  13.02 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=2/numInputRows=65536-24         	      42	  30498486 ns/op	  17.19 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=32/numInputRows=65536-24        	      66	  18191805 ns/op	  28.82 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=128/numInputRows=65536-24       	      70	  17272921 ns/op	  30.35 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=1024/numInputRows=65536-24      	      78	  15805293 ns/op	  33.17 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=1/numInputRows=4194304-24       	       1	1933313547 ns/op	  17.36 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=2/numInputRows=4194304-24       	       1	1271602762 ns/op	  26.39 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=32/numInputRows=4194304-24      	       2	 534373176 ns/op	  62.79 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=128/numInputRows=4194304-24     	       2	 506018692 ns/op	  66.31 MB/s
BenchmarkExternalHashAggregator/MIN/spilled=true/int/groupSize=1024/numInputRows=4194304-24    	       3	 455339178 ns/op	  73.69 MB/s
```
The worst case for the input tuples tracking approach is when the group sizes are huge (i.e. we have 100 million of input tuples yet only 10 groups) in which the hash aggregator doesn't have to spill, yet the spilling queue will need to use disk. Still I think this approach is reasonable as the first cut, and we could look into another fall-over strategy that wouldn't require the tracking (I might look into it on one of the Fridays).

**Review by asubiotto — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, 14 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/colexec/hash_aggregator.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57817#-MQRvSFF978Y7MOEGB7s:-MQRvSFF978Y7MOEGB7t:bx38i0f) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ea2e0315697071286b54e26a4d376511e9a496/pkg/sql/colexec/hash_aggregator.go#L213)):*
> ```Go
> 				if n > 0 {
> 					// We cannot simply enqueue the pending batch because at the
> 					// moment the spilling queue doesn't deep copy batches when
> ```

This can be removed once your spilling queue PR is in, right?
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 846 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57817#-MQS-ozJ0r2JMKVtIb9B:-MQS-ozJ0r2JMKVtIb9C:b-pvc7t4) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ea2e0315697071286b54e26a4d376511e9a496/pkg/sql/colexec/colbuilder/execplan.go#L846)):*
> ```Go
> 						UnlimitedAllocator: colmem.NewAllocator(ctx, spillingQueueMemAccount, factory),
> 						Types:              inputTypes,
> 						// TODO(yuzefovich): at the moment, it is possible that
> ```

In other cases (e.g. hashjoiner) don't we subdivide the work memory limit? I'd prefer not to merge this without that behavior.

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57817)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto)

___
*[pkg/sql/colexec/hash_aggregator.go, line 213 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57817#-MQRvSFF978Y7MOEGB7s:-MQoRbZy23Vk6khmi1gz:byl2p0w) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ea2e0315697071286b54e26a4d376511e9a496/pkg/sql/colexec/hash_aggregator.go#L213)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

This can be removed once your spilling queue PR is in, right?
</blockquote></details>

Yes (actually this code block was what prompted me to fix the spilling queue).

Rebased on top of the spilling queue PR since that is very close to be merged and updated this PR.
___
*[pkg/sql/colexec/colbuilder/execplan.go, line 846 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57817#-MQS-ozJ0r2JMKVtIb9B:-MQoWDxK9YfpBMgMMolx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/36ea2e0315697071286b54e26a4d376511e9a496/pkg/sql/colexec/colbuilder/execplan.go#L846)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

In other cases (e.g. hashjoiner) don't we subdivide the work memory limit? I'd prefer not to merge this without that behavior.
</blockquote></details>

Done.

**Comment by yuzefovich** [comment]
Rebased on top of the spilling queue fix, RFAL.

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 19 of 19 files at r3, 9 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57817#-:-MQvNoxP5XvCiIotzwbN:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto)

**Comment by yuzefovich** [comment]
TFTR!

bors r+

**Comment by yuzefovich** [comment]
Merge conflict with a concurrent PR.

bors r-

**Comment by yuzefovich** [comment]
Okay, fixed another merge conflict.

bors r+

**Pull request merged**
