### PR TITLE
go.mod: import etcd/raft at the new path

### LINKED ISSUE #93174: go.mod: use new etcd/raft import path
Recently `etcd/raft` has migrated to a separate repository: https://github.com/etcd-io/raft. We should import the new `raft` module under the new path.

Jira issue: CRDB-22204

### PR DESCRIPTION
**Pull request by pav-kv**
The etcd/raft package has moved to a separate repository, and was renamed to go.etcd.io/raft. This commit imports the new path.

Fixes #93174
Epic: none

### CODE REVIEW

**Comment by pavelkalinnikov** [comment]
I'm not sure how compatibility will work between nodes with the new and old protos.

**Comment by erikgrinaker** [comment]
I think the name only matters if we're using `Any` fields.

**Review by tbg — APPROVED** [review]
Looking good, thanks!

I checked upstream what we're bumping to here and it looks like it's basically "latest of our changes" and then there are some fixups that don't affect the raft code.

image

**Comment by tbg** [comment]
`fmtsave` has some issue it seems:

```
Failed
=== RUN   Test
src/a/a.go:18:2: cannot find package "go.etcd.io/raft/v3" in any of:
	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/10248/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/testutils/lint/passes/fmtsafe/fmtsafe_test_/fmtsafe_test.runfiles/go_sdk/src/go.etcd.io/raft/v3 (from $GOROOT)
	/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/10248/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/testutils/lint/passes/fmtsafe/fmtsafe_test_/fmtsafe_test.runfiles/com_github_cockroachdb_cockroach/pkg/testutils/lint/passes/fmtsafe/testdata/src/go.etcd.io/raft/v3 (from $GOPATH)
/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/10248/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/testutils/lint/passes/fmtsafe/fmtsafe_test_/fmtsafe_test.runfiles/com_github_cockroachdb_cockroach/pkg/testutils/lint/passes/fmtsafe/testdata/src/a/a.go:18:2: could not import go.etcd.io/raft/v3 (invalid package name: "")
/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/10248/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/testutils/lint/passes/fmtsafe/fmtsafe_test_/fmtsafe_test.runfiles/com_github_cockroachdb_cockroach/pkg/testutils/lint/passes/fmtsafe/testdata/src/a/a.go:55:8: undeclared name: raft
/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/10248/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/testutils/lint/passes/fmtsafe/fmtsafe_test_/fmtsafe_test.runfiles/com_github_cockroachdb_cockroach/pkg/testutils/lint/passes/fmtsafe/testdata/src/a/a.go:18:2: could not import go.etcd.io/raft/v3 (invalid package name: "")
/home/roach/.cache/bazel/_bazel_roach/c5a4e7d36696d9cd970af2045211a7df/sandbox/processwrapper-sandbox/10248/execroot/com_github_cockroachdb_cockroach/bazel-out/k8-fastbuild/bin/pkg/testutils/lint/passes/fmtsafe/fmtsafe_test_/fmtsafe_test.runfiles/com_github_cockroachdb_cockroach/pkg/testutils/lint/passes/fmtsafe/testdata/src/a/a.go:55:8: undeclared name: raft
    analysistest.go:298: error analyzing fmtsafe@a: analysis skipped due to errors in package
    analysistest.go:298: error analyzing fmtsafe@a: analysis skipped due to errors in package
    analysistest.go:298: error analyzing fmtsafe@a.test: analysis skipped due to errors in package
--- FAIL: Test (3.16s)

```

**Comment by tbg** [comment]
Still LGTM but looks like you need to re-do vendor because someone beat you to it. Pro tip, if you do it be ready to bors it soon thereafter or you get starved :-)

**Comment by pavelkalinnikov** [comment]
There are some obscure lint failures in one of the targets that I'm still decoding.

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 97 of 121 files at r1, 25 of 25 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93190#-:-NJ8Nhy20EkuPa23Kbha:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @erikgrinaker)

**Comment by pavelkalinnikov** [comment]
`make lint` still fails with:

```
pkg/server/serverpb/status.proto:39:8:etcd/raft/v3/raftpb/raft.proto: does not exist
make: *** [Makefile:1373: bin/.gw_protobuf_sources] Error 100
make: *** Waiting for unfinished jobs....
pkg/kv/kvserver/kvserverpb/raft.proto:21:8:etcd/raft/v3/raftpb/raft.proto: does not exist
make: *** [Makefile:1365: bin/.go_protobuf_sources] Error 100
```

... even though the `./dev` / bazel builds are happy.

It also says that the makefile is deprecated, so I don't know how much effort should be put into fixing this. @tbg any ideas?

**Comment by pavelkalinnikov** [comment]
Now for some reason `make` generates this import path:
```
raftpb "github.com/cockroachdb/cockroach/pkg/raft/v3/raftpb"
```
instead of etcd raft

**Comment by pavelkalinnikov** [comment]
bors r=tbg,nvanbenschoten

**Pull request merged**
