### PR TITLE
sql: various COPY improvements

### PR DESCRIPTION
**Pull request by otan**
refs  https://github.com/cockroachdb/cockroach/issues/41608

Release note: None

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82457)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[`pkg/sql/copy.go` line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43w5ob3KHniGLyhQyV:-N43w5ob3KHniGLyhQyW:b-x2u1vn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L160)):*
> ```Go
> 		if c.format == tree.CopyFormatBinary {
> 			return nil, pgerror.Newf(
> 				pgcode.FeatureNotSupported,
> ```

PG says "This option is not allowed when using binary format." does PG return FeatureNotSupported here too? i'm thinking InvalidParameter may make more sense
___
*[`pkg/sql/copy.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43wEcg52lkbJaPWEP-:-N43wEcg52lkbJaPWEP0:bmkf4zr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L174)):*
> ```Go
> 		if len(delim) != 1 || !utf8.ValidString(delim) {
> 			return nil, pgerror.Newf(
> 				pgcode.FeatureNotSupported,
> ```

i think PG also doesn't allow this, so ditto
___
*[`pkg/sql/copy.go` line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43wGwX3azJQrNZgBz0:-N43wGwX3azJQrNZgBz1:b-7ropln) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L183)):*
> ```Go
> 		if c.format == tree.CopyFormatBinary {
> 			return nil, pgerror.Newf(
> 				pgcode.FeatureNotSupported,
> ```

ditto

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82457)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/copy.go` line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43w5ob3KHniGLyhQyV:-N440jDB5j_ktg_Cfz4x:b-qczufs) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L160)):*
```
otan=# \set VERBOSITY verbose
otan=# copy t from stdin delimiter ',';
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> COPY 0
```

totally an us problem
___
*[`pkg/sql/copy.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43wEcg52lkbJaPWEP-:-N440sJoBkid0x2E_B16:b-kfq2ab) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L174)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think PG also doesn't allow this, so ditto
</blockquote></details>

```
otan=# copy t from stdin delimiter 'xx';
ERROR:  0A000: COPY delimiter must be a single one-byte character
LOCATION:  ProcessCopyOptions, copy.c:561
```


this is correct
___
*[`pkg/sql/copy.go` line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43wGwX3azJQrNZgBz0:-N441-NSDkVvBzeUqgzz:b-djgz5f) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L183)):*
```
otan=# copy t from stdin null 'xxx';
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> COPY 0
```

totally an us problem

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82457)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[`pkg/sql/copy.go` line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43w5ob3KHniGLyhQyV:-N44cYvMApPZwv6QSmv8:b-qjsjk9) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L160)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

```
otan=# \set VERBOSITY verbose
otan=# copy t from stdin delimiter ',';
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> COPY 0
```

totally an us problem
</blockquote></details>

but you'd need to test with `copy t from stdin binary delimiter ',';`
___
*[`pkg/sql/copy.go` line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43wGwX3azJQrNZgBz0:-N44cfTAAkWRVEO9VqFi:b-anmkyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L183)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

```
otan=# copy t from stdin null 'xxx';
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> COPY 0
```

totally an us problem
</blockquote></details>

but what does PG say when you try with binary format?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82457)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @otan and @rafiss)

___
*[`pkg/sql/copy.go` line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43w5ob3KHniGLyhQyV:-N44d1b01oE8rWARGjyO:bqw73zg) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L160)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

but you'd need to test with `copy t from stdin binary delimiter ',';`
</blockquote></details>

just checked -- it's 42601 `syntax_error`
___
*[`pkg/sql/copy.go` line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43wEcg52lkbJaPWEP-:-N44dFFw9-gyOpMV-tUn:bpp65kn) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L174)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

```
otan=# copy t from stdin delimiter 'xx';
ERROR:  0A000: COPY delimiter must be a single one-byte character
LOCATION:  ProcessCopyOptions, copy.c:561
```


this is correct
</blockquote></details>

you're right PG does use 0A000 for this one
___
*[`pkg/sql/copy.go` line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43wGwX3azJQrNZgBz0:-N44d8uf0dhfCJJJFaZV:bhlxwkk) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L183)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

but what does PG say when you try with binary format?
</blockquote></details>

this is also it's 42601 `syntax_error`

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/82457)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/copy.go` line 160 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43w5ob3KHniGLyhQyV:-N44k7VK0onazIycrgLk:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L160)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

just checked -- it's 42601 `syntax_error`
</blockquote></details>

Done.
___
*[`pkg/sql/copy.go` line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/82457#-N43wGwX3azJQrNZgBz0:-N44k5132WCid0K8sY0i:bssw6e2) ([raw file](https://github.com/cockroachdb/cockroach/blob/a33fef785bc2ac7fae9ead01b06368d52935fac3/pkg/sql/copy.go#L183)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

this is also it's 42601 `syntax_error`
</blockquote></details>

ah they must do this at the parser layer. ok

**Review by rafiss — APPROVED** [review]

**Comment by otan** [comment]
bors r=rafiss

**Pull request merged**
