### PR TITLE
schemachanger: Implement `ADD UNIQUE WITHOUT INDEX`

### PR DESCRIPTION
**Pull request by Xiang-Gu**
This PR implements `ADD UNIQUE WITHOUT INDEX` in the declarative schema changer.
In general, it follows the same recipe for `ADD CHECK`.

Epic: None

### CODE REVIEW

**Comment by Xiang-Gu** [comment]
This is ready for a round of looks!

**Comment by postamar** [comment]
This looks good, I did a first pass and have no comments besides what I already shared in the PR this is based on, which might apply here also.

**Review by rytaft — COMMENTED** [review]
Nice! Most of this code is out of my area of expertise, but from what I can tell it looks good!

With this PR have you added support for all aspects of `UNIQUE WITHOUT INDEX` or just some? e.g., does this cover adding `NOT VALID` constraints and/or running `VALIDATE` on an existing constraint? How about adding them as part of a `CREATE TABLE` statement or dropping them?

Also seems like the change to include `indexIDForValidation` is mixed in with this change but should probably be its own separate change. It doesn't seem related to this.

I left a bunch of nits about long comment lines. Comments should be <= 80 characters wide.

> Reviewed 5 of 5 files at r18, 9 of 9 files at r19, 3 of 3 files at r20, 3 of 3 files at r21, 17 of 17 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-:-NJv8na5-AT7HheeSZyb:b-631z64)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @Xiang-Gu)

___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 176 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJukK2O33CkwTNuH2bm:-NJukK2O33CkwTNuH2bn:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/96a8d3eaa683b07f7785c741d83e4bca1ac1ef98/pkg/sql/catalog/rewrite/rewrite.go#L176)):*
> ```Go
> 		}
> 
> 		// Rewrite unique_without_index in both `UniqueWithoutIndexConstraints` and `Mutations` slice.
> ```

nit: long line
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go` line 439 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJujnJG5L5umQKPmREg:-NJujnJG5L5umQKPmREh:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f3a11eae416d1e068790477bbffaf7b0054a65/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go#L439)):*
> ```Go
> }
> 
> // getIndexIDForValidationForConstraint returns the index ID this check constraint is supposed to
> ```

nit: long line
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/constraint.go` line 346 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJug0VTCkBytXYOKIpb:-NJug0VTCkBytXYOKIpc:blb4wof) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scexec/scmutationexec/constraint.go#L346)):*
> ```Go
> 	}
> 	if op.ConstraintID >= tbl.NextConstraintID {
> 		tbl.NextConstraintID = op.ConstraintID + 1
> ```

why are you doing this in this function but not the others?
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/constraint.go` line 352 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJugI-I9mxiTl5fbQo_:-NJugI-I9mxiTl5fbQoa:b-cjokkd) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scexec/scmutationexec/constraint.go#L352)):*
> ```Go
> 		TableID:      op.TableID,
> 		ColumnIDs:    op.ColumnIDs,
> 		Name:         tabledesc.ConstraintNamePlaceholder(op.ConstraintID),
> ```

why not use the constraint name?
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/constraint.go` line 385 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJugdrb4H2CHEHG371P:-NJugdrb4H2CHEHG371Q:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scexec/scmutationexec/constraint.go#L385)):*
> ```Go
> 			// Remove the mutation from the mutation slice. The `MakeMutationComplete`
> 			// call will also mark the above added unique_without_index as VALIDATED.
> 			// If this is a rollback of a drop, we are trying to add the unique_without_index constraint
> ```

nit: long line
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/constraint.go` line 410 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJugzuC5LN1NlRZ0YbX:-NJugzuC5LN1NlRZ0YbY:b-ogdlrw) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scexec/scmutationexec/constraint.go#L410)):*
> ```Go
> }
> 
> func (m *visitor) MakePublicUniqueWithoutIndexConstraintValidated(
> ```

The name of this function doesn't seem to match what it's doing
___
*[`pkg/sql/schemachanger/scop/mutation.go` line 369 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJuhJKy9KpDqBsCKnMT:-NJuhJKy9KpDqBsCKnMU:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scop/mutation.go#L369)):*
> ```Go
> }
> 
> // MakeAbsentUniqueWithoutIndexConstraintWriteOnly adds a non-existent unique_without_index constraint
> ```

nit: long line
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 325 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJuhZh81Ov6ee3TgzCC:-NJuhZh81Ov6ee3TgzCD:bsrp4qm) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scpb/elements.proto#L325)):*
> ```protobuf
>   // Predicate, if non-nil, means a partial uniqueness constraint.
>   Expression predicate = 4 [(gogoproto.customname) = "Predicate"];
>   // IndexIDForValidation is the index id to hint to the unique_without_index constraint validation SQL query about which index
> ```

nit: long line
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_unique_without_index_constraint.go` line 19 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJuiOyaBbeQb-dRVn6M:-NJuiOyaBbeQb-dRVn6N:befmmg4) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scplan/internal/opgen/opgen_unique_without_index_constraint.go#L19)):*
> ```Go
> 
> func init() {
> 	opRegistry.register((*scpb.UniqueWithoutIndexConstraint)(nil),
> ```

I'm not familiar enough with how this works to review this part
___
*[`pkg/sql/schemachanger/scplan/internal/rules/testdata/deprules` line 1447 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJv7n826F4ugRe_Hdz-:-NJv7n838yr6hJSAB2I4:brz9glx) ([raw file](https://github.com/cockroachdb/cockroach/blob/03d3059ea13a4c686285e448884982bf8d7496e1/pkg/sql/schemachanger/scplan/internal/rules/testdata/deprules#L1447)):*
> ```
>     - $next-node[CurrentStatus] = TRANSIENT_DELETE_ONLY
>     - descriptorIsNotBeingDropped($prev)
>     - joinTargetNode($prev, $prev-target, $prev-node)
> ```

I don't know enough about this to review

**Comment by Xiang-Gu** [comment]
> With this PR have you added support for all aspects of UNIQUE WITHOUT INDEX or just some? e.g., does this cover adding NOT VALID constraints and/or running VALIDATE on an existing constraint? How about adding them as part of a CREATE TABLE statement or dropping them?

@rytaft Thank you first of all for taking a look at this PR. To answer your question:
1. This PR does not support NOT VALID. This is a to-do for the team for all kinds of constraints.
2. We don't support CREATE TABLE in the declarative schema changer yet, so we cannot yet add them as part of a CREATE TABLE.
3. We don't support DROP CONSTRAINT in the declarative schema changer yet, so we cannot yet drop them in the declarative schema changer. We should (?) be able to drop them in the legacy schema changer though.
4. Another aspect is `ADD COLUMN UNIQUE WITHOUT INDEX`. We already support `ADD COLUMN` in the declarative schema changer. With this PR, I think we can easily add a bit to `ADD COLUMN` logic to support `ADD COLUMN UNIQUE WITHOUT INDEX`, which is currently unsupported with the following workaround
```
ERROR: adding a column marked as UNIQUE WITHOUT INDEX is unsupported
SQLSTATE: 0A000
HINT: add the column first, then run ALTER TABLE ... ADD CONSTRAINT to add a UNIQUE WITHOUT INDEX constraint on the column
```

> Also seems like the change to include indexIDForValidation is mixed in with this change but should probably be its own separate change. It doesn't seem related to this.
This will be the key ingredient to support `ADD COLUMN UNIQUE WITHOUT INDEX` in the declarative schema changer. Btw, this is something required for (almost all) another constraint. 

I will address your code review feedback shortly!

**Review by Xiang-Gu — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93824)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rytaft)

___
*[`pkg/sql/catalog/rewrite/rewrite.go` line 176 at r21](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJukK2O33CkwTNuH2bm:-NLSUto3A3RCJH3td-PE:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/96a8d3eaa683b07f7785c741d83e4bca1ac1ef98/pkg/sql/catalog/rewrite/rewrite.go#L176)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: long line
</blockquote></details>

done



_Code quote:_
```Go
WithoutIndexConstraints` and `Mutations` slice.
```
___
*[`pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go` line 439 at r20](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJujnJG5L5umQKPmREg:-NLSVHHhBeuSDoOX3N9n:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/21f3a11eae416d1e068790477bbffaf7b0054a65/pkg/sql/schemachanger/scbuild/internal/scbuildstmt/alter_table_add_constraint.go#L439)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: long line
</blockquote></details>

done
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/constraint.go` line 346 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJug0VTCkBytXYOKIpb:-NLSVW8l374w_c6BIZKt:bzgrxy1) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scexec/scmutationexec/constraint.go#L346)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why are you doing this in this function but not the others?
</blockquote></details>

I in fact did: This is only required in the "first" operation, which usually has the name of `MakeAbsentXxxWriteOnly`. I confirmed that we did this for all three constraints we currently support: check, fk, and uwi
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/constraint.go` line 352 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJugI-I9mxiTl5fbQo_:-NLSVtk1EmM-aLtbkU5R:bya9i4j) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scexec/scmutationexec/constraint.go#L352)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why not use the constraint name?
</blockquote></details>

The constraint name itself is modeled as a separate "element" and we will update the name to the right on during the lifecycle of that name element.



_Code quote:_
```Go
	uwi := &descpb.UniqueWithoutIndexConstraint{
		TableID:      op.TableID,
```
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/constraint.go` line 385 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJugdrb4H2CHEHG371P:-NLSWBSg6BiqvAM7qJUc:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scexec/scmutationexec/constraint.go#L385)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: long line
</blockquote></details>

done



_Code quote:_
```Go
drop, we are trying to add the unique_without_inde
```
___
*[`pkg/sql/schemachanger/scexec/scmutationexec/constraint.go` line 410 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJugzuC5LN1NlRZ0YbX:-NLSWYu16A5_Q8drjLh4:b91a718) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scexec/scmutationexec/constraint.go#L410)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

The name of this function doesn't seem to match what it's doing
</blockquote></details>

You are right. We used to have a more-free-formed naming for those operations/functions. We (the schema team) then decided to make them conform to a certain naming convention. We chose the convention that makes it clear of the affected element's before and after status -- the element status as shown in a new schema changer plan. This operation, in the new schema changer plan's worlds and terminologies, transitioned the UniqueWIthoutIndex element from Public status to Validated status, so I gave this function this name.

What the function actually does, i.e. what a transition in the new schema changer plan's world translates to modifications to the descriptor, is considered a layer below and thus we don't want it to show in the function/operation names. That's my understanding of the rationale behind such a naming convention.
___
*[`pkg/sql/schemachanger/scop/mutation.go` line 369 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJuhJKy9KpDqBsCKnMT:-NLSYR5K56r5ZfccGgF0:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scop/mutation.go#L369)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: long line
</blockquote></details>

done



_Code quote:_
```Go
ds a non-existent unique_without_index constraint
```
___
*[`pkg/sql/schemachanger/scpb/elements.proto` line 325 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJuhZh81Ov6ee3TgzCC:-NLSYXo00tqnJ1gy4-6T:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scpb/elements.proto#L325)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: long line
</blockquote></details>

done



_Code quote:_
```protobuf
index id to hint to the unique_without_index cons
```
___
*[`pkg/sql/schemachanger/scplan/internal/opgen/opgen_unique_without_index_constraint.go` line 19 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJuiOyaBbeQb-dRVn6M:-NLSYZRf3wNQyJlJrTBe:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scplan/internal/opgen/opgen_unique_without_index_constraint.go#L19)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I'm not familiar enough with how this works to review this part
</blockquote></details>

ack
___
*[`pkg/sql/schemachanger/scplan/internal/rules/testdata/deprules` line 1447 at r22](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJv7n826F4ugRe_Hdz-:-NLSYai1EvH7kenRWNJA:b2nhysk) ([raw file](https://github.com/cockroachdb/cockroach/blob/03d3059ea13a4c686285e448884982bf8d7496e1/pkg/sql/schemachanger/scplan/internal/rules/testdata/deprules#L1447)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I don't know enough about this to review
</blockquote></details>

ack

**Review by rytaft — COMMENTED** [review]
Thanks for the info! I will let someone from the schema team sign off on this since I'm not familiar with most of this code.

> Reviewed 2 of 7 files at r30, 1 of 1 files at r31, 1 of 1 files at r32.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-:-NLXnMyF9eU7sJIKpfOY:b-zg7h35)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[`pkg/sql/schemachanger/scexec/scmutationexec/constraint.go` line 410 at r19](https://reviewable.io/reviews/cockroachdb/cockroach/93824#-NJugzuC5LN1NlRZ0YbX:-NLXmy5x5ROjJbG6m83p:b-a81j6n) ([raw file](https://github.com/cockroachdb/cockroach/blob/45bf44a7b1ac22e2d18772275ff84b6f3b940c3b/pkg/sql/schemachanger/scexec/scmutationexec/constraint.go#L410)):*
<details><summary><i>Previously, Xiang-Gu (Xiang Gu) wrote…</i></summary><blockquote>

You are right. We used to have a more-free-formed naming for those operations/functions. We (the schema team) then decided to make them conform to a certain naming convention. We chose the convention that makes it clear of the affected element's before and after status -- the element status as shown in a new schema changer plan. This operation, in the new schema changer plan's worlds and terminologies, transitioned the UniqueWIthoutIndex element from Public status to Validated status, so I gave this function this name.

What the function actually does, i.e. what a transition in the new schema changer plan's world translates to modifications to the descriptor, is considered a layer below and thus we don't want it to show in the function/operation names. That's my understanding of the rationale behind such a naming convention.
</blockquote></details>

Thanks for the explanation

**Review by postamar — APPROVED** [review]
LGTM but please address my comments in  https://github.com/cockroachdb/cockroach/pull/93068 first before merging. Nicely done!

**Pull request merged**
