### PR TITLE
opt: do not build cross-joins on inputs of lookup joins

### PR DESCRIPTION
**Pull request by mgartner**
#### opt: do not build cross-joins on inputs of lookup joins

Rules that generate lookup joins no longer build cross-joins on the
input of the lookup join to constrain an index column to a set of
constant values. Instead, a lookup expression is used which generates
multiple lookup spans during execution.

Building a cross-join added extra complexity to the optimizer logic and
has been shown to be error prone (see #78681 and #79384). Also, a
cross-join could significantly increase the number of input rows, so it
was likely less efficient than using a lookup expression.

If an index column is constrained to a single constant value, we still
project the value in the input of the lookup join so that it can be used
as an equality column. This is more performant than using a lookup
expression with an equality condition (see #66726).

This commit has some other notable changes to the lookup join generation
logic:

  1. The logic has been reordered. The case when a single constant value
     is projected is handled before the multiple constant value or range
     cases.
  2. An unnecessary projection is no longer added for single constant
     values when we revert to using a lookup expression. An explicit
     test was added for this.
  3. Fix `isCanonicalLookupJoinFilter` so that expressions with
     inequalities and either an equality or `IN` are not used as lookup
     expressions. The `multiSpanGenerator` does not support these types
     of expressions, and would panic if it encountered them. This bug has
     existed for a while, but has been hidden because of the preference
     for the cross-join strategy. Note that there are several cases
     where a lookup join contains filters in the `ON` expression that
     are redundant with the lookup expression. I'm planning on
     addressing this in a future commit.

Note that this commit does not affect inverted joins. Cross-joins can
still be generated on inverted join inputs.

Release note: None

### CODE REVIEW

**Review by msirek — APPROVED** [review]
Nice fix!  This gets rid of problematic cross joins while not giving up any optimizations.

nit: `This commit the` -> `This commit has`
> This commit the some other notable changes to the lookup join generation
logic:

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-:-N-5_kf44r9OjqmBhYEF:b2lvmii)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/exec/explain/testdata/gists_tpce, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-5YI1u9GsN04j9PZib:-N-5YI1u9GsN04j9PZic:bwxkwg3) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4862de957d243901e6a23bf420d53aac82c1810/pkg/sql/opt/exec/explain/testdata/gists_tpce#L40)):*
> ```
>                 │ table: broker@broker_b_name_idx
>                 │ equality cols are key
>                 │ lookup condition: (tr_b_id = b_id) AND (b_name IN _)
> ```

Maybe not related to this PR, but I wonder what's going on with costing.  An IN list lookup with 30 items on a non-unique index shouldn't beat out a PK lookup, which the old plan used.  `b_id` is the PK column, but the index key here is `b_name`.

**Review by mgartner — COMMENTED** [review]
Looks like this uncovered a bug in lookup join expressions that was hidden previously because of the preference for the cross-join approach. No need to review further until I can fix it.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-:-N-5pAsV0jsWlyE97rPU:beczoq5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @msirek and @rytaft)

___
*[pkg/sql/opt/exec/explain/testdata/gists_tpce, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-5YI1u9GsN04j9PZib:-N-5m8xT6A1lWBeL5Y4K:b-9ghwqc) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4862de957d243901e6a23bf420d53aac82c1810/pkg/sql/opt/exec/explain/testdata/gists_tpce#L40)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Maybe not related to this PR, but I wonder what's going on with costing.  An IN list lookup with 30 items on a non-unique index shouldn't beat out a PK lookup, which the old plan used.  `b_id` is an FK and unique, but the index key is `b_name`.
</blockquote></details>

Great catch! I'll look into this before merging.

I think this might be due to an under-costing of lookup joins with lookup expressions. When costing a lookup join with a lookup expression, we [add only a marginal cost overhead](https://github.com/cockroachdb/cockroach/blob/b01d6c7e57c3e2dafb4194d3788253ad3b988610/pkg/sql/opt/xform/coster.go#L1675-L1685) that is a multiple of `cpuCostFactor` and the length of the lookup expression. Ideally, this overhead should take into consideration the number of lookup spans that will be generated for each input row. And the overhead should probably be a multiple of `randIOCostFactor`, rather than `cpuCostFactor`.

For example, the lookup join in this test will generate 30 lookup spans for each input row, so the cost should be something like `num_input_rows * (30 * randIOCostFactor)`.

**Comment by mgartner** [comment]
> Looks like this uncovered a bug in lookup join expressions that was hidden previously because of the preference for the cross-join approach. No need to review further until I can fix it.

This should now be fixed. See (4) in the commit message which describes the bug that was previously unreachable.

**Review by msirek — APPROVED** [review]
Looks good. The Github PR summary still needs an update:
> nit: `This commit the` -> `This commit has`

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-:-N-9PgAo9gPiizcKOTWt:b-bfn496)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/join_funcs.go, line 837 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-9R8GJBrNEvBZBD315:-N-9R8GJBrNEvBZBD316:bxqqdps) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs.go#L837)):*
> ```Go
> 	}
> 	var isInequality func(expr opt.Expr) bool
> 	isInequality = func(expr opt.Expr) bool {
> ```

nit: This is checking not just for inequalities, but inequalities in a certain form, so maybe a better name is `isCanonicalInequality`.
___
*[pkg/sql/opt/exec/explain/testdata/gists_tpce, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-5YI1u9GsN04j9PZib:-N-5eelS9z7HIbeMJvka:b-qsqdj1) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4862de957d243901e6a23bf420d53aac82c1810/pkg/sql/opt/exec/explain/testdata/gists_tpce#L40)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

Great catch! I'll look into this before merging.

I think this might be due to an under-costing of lookup joins with lookup expressions. When costing a lookup join with a lookup expression, we [add only a marginal cost overhead](https://github.com/cockroachdb/cockroach/blob/b01d6c7e57c3e2dafb4194d3788253ad3b988610/pkg/sql/opt/xform/coster.go#L1675-L1685) that is a multiple of `cpuCostFactor` and the length of the lookup expression. Ideally, this overhead should take into consideration the number of lookup spans that will be generated for each input row. And the overhead should probably be a multiple of `randIOCostFactor`, rather than `cpuCostFactor`.

For example, the lookup join in this test will generate 30 lookup spans for each input row, so the cost should be something like `num_input_rows * (30 * randIOCostFactor)`. 
</blockquote></details>

Did there turn out to be a costing issue?  Maybe we need to open a Github issue for it.



_Code quote:_
```
equality cols are key
```

**Review by rytaft — COMMENTED** [review]
Nice!

> Reviewed 9 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-:-N-OawoQC63r5IyH8zdp:b-83sjoh)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mgartner)

___
*[pkg/sql/opt/xform/join_funcs.go, line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-OXjcwCVeknqBs-Ubh:-N-OXjcwCVeknqBs-Ubi:b-8cdtao) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs.go#L440)):*
> ```Go
> 				if inputProjections == nil {
> 					inputProjections = make(memo.ProjectionsExpr, 0, numIndexKeyCols-j)
> 				}
> ```

nit: Is this necessary? Seems like overkill (here and a couple places below)

Seems like you're avoiding a small number of possible allocations at the expense of additional code complexity and branching (but maybe I'm confused)
___
*[pkg/sql/opt/xform/join_funcs.go, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-OZUVq2aeAp-a0Ky2B:-N-OZUVq2aeAp-a0Ky2C:b-1fbrxx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs.go#L543)):*
> ```Go
> 		// A multi-join lookup span will include equality filters to constant values
> 		// in its LookupExpr, so projections are not required.
> 		if !shouldBuildMultiSpanLookupJoin && len(inputProjections) > 0 {
> ```

nit: would it be easier to just set `inputProjections` to `nil` inside the block for `shouldBuildMultiSpanLookupJoin`?
___
*[pkg/sql/opt/xform/join_funcs.go, line 1369 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-O_9Sf35oZAjbfHICC:-N-O_9Sf35oZAjbfHICD:buhsp1f) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40c144415fa70a753cd6abadb117a90cbcb260c/pkg/sql/opt/xform/join_funcs.go#L1369)):*
> ```Go
> 			if constraintCol != col ||
> 				constraint.Spans.Count() != 1 ||
> 				!c.isCanonicalLookupJoinFilter(filters[filterIdx]) {
> ```

Are you sure you don't need to check this anymore?
___
*[pkg/sql/opt/xform/join_funcs_test.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-Oab3e7-vXB-E-btfz:-N-Oab3e7-vXB-E-btg-:b-ndbju2) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs_test.go#L174)):*
> ```Go
> 		{name: "and-eq-lt",
> 			filter: "i = 10 AND i < 10",
> 			want:   false,
> ```

why did this change? Do we need another test case?

**Review by mgartner — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79586)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @cucaroach, @msirek, and @rytaft)

___
*[pkg/sql/opt/xform/join_funcs.go, line 440 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-OXjcwCVeknqBs-Ubh:-N-OrdUO6hNkBfsuClUL:b99j5mx) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs.go#L440)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: Is this necessary? Seems like overkill (here and a couple places below)

Seems like you're avoiding a small number of possible allocations at the expense of additional code complexity and branching (but maybe I'm confused)
</blockquote></details>

They're probably not necessary. I've removed them.
___
*[pkg/sql/opt/xform/join_funcs.go, line 543 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-OZUVq2aeAp-a0Ky2B:-N-Os4RKBY5002uYotJD:bkulqb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs.go#L543)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: would it be easier to just set `inputProjections` to `nil` inside the block for `shouldBuildMultiSpanLookupJoin`?
</blockquote></details>

Done. Note that this is all error prone because of the mixing of determining the lookup join cols and expression at the same time as building the lookup join and its input. I'm working on cleaning up a lot of this in a follow-up PR.
___
*[pkg/sql/opt/xform/join_funcs.go, line 837 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-9R8GJBrNEvBZBD315:-N-OsZPJBW4XtpzuxKSy:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs.go#L837)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

nit: This is checking not just for inequalities, but inequalities in a certain form, so maybe a better name is `isCanonicalInequality`.
</blockquote></details>

Done.
___
*[pkg/sql/opt/xform/join_funcs.go, line 1369 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-O_9Sf35oZAjbfHICC:-N-OsduM11RihW7A9LJI:bmplaau) ([raw file](https://github.com/cockroachdb/cockroach/blob/d40c144415fa70a753cd6abadb117a90cbcb260c/pkg/sql/opt/xform/join_funcs.go#L1369)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Are you sure you don't need to check this anymore?
</blockquote></details>

I'm fairly certain. If we find a non-canonical filter that constrains a column to a tight constraint with a single span, we will build a canonical filter here: https://github.com/cockroachdb/cockroach/blob/cbbfe24950b43213d9e63d54431d537c2c0d25e9/pkg/sql/opt/xform/join_funcs.go#L816

So I don't see a reason for this check here. Maybe @cucaroach remembers a specific case that requires this?

Maybe we should ensure that the constraint contains only a single column? Though I don't have any specific reason why that would be required, it just seems safer.
___
*[pkg/sql/opt/exec/explain/testdata/gists_tpce, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-5YI1u9GsN04j9PZib:-N-PAjHC6_0z4YkHvrKC:b-hvnu0x) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4862de957d243901e6a23bf420d53aac82c1810/pkg/sql/opt/exec/explain/testdata/gists_tpce#L40)):*
<details><summary><i>Previously, msirek (Mark Sirek) wrote…</i></summary><blockquote>

Did there turn out to be a costing issue?  Maybe we need to open a Github issue for it.
</blockquote></details>

It does look like a costing issue. I created an issue here: #79797.
___
*[pkg/sql/opt/xform/join_funcs_test.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-Oab3e7-vXB-E-btfz:-N-OuszL3Lqv__cRwitd:bbtvjjt) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs_test.go#L174)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why did this change? Do we need another test case?
</blockquote></details>

The execution engine would panic if it saw an expression with an equaity and an inequality. In practice, however, normalization rules make it impossible for this to occur. This example normalizes to `false`, and `i = 10 AND i >= 10` is normalizes to `i = 10`. 

In a future PR I'd like to get rid of the canonical filter checker, and instead ensure that a lookup expression is canonical by always constructing the expression, and not reusing one. Doing so should be less error prone.

**Review by msirek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79586)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @mgartner, and @rytaft)

___
*[pkg/sql/opt/exec/explain/testdata/gists_tpce, line 40 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-5YI1u9GsN04j9PZib:-N-PKw_Q5BMHjTNwOT29:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/d4862de957d243901e6a23bf420d53aac82c1810/pkg/sql/opt/exec/explain/testdata/gists_tpce#L40)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

It does look like a costing issue. I created an issue here: #79797.
</blockquote></details>

Thanks!

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-:-N-PMh0D7y4zW7K4XC10:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @cucaroach, @mgartner, and @rytaft)

___
*[pkg/sql/opt/xform/join_funcs_test.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-Oab3e7-vXB-E-btfz:-N-PMVH_1oemol9pPUVM:bcvma9i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs_test.go#L174)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

The execution engine would panic if it saw an expression with an equaity and an inequality. In practice, however, normalization rules make it impossible for this to occur. This example normalizes to `false`, and `i = 10 AND i >= 10` is normalizes to `i = 10`. 

In a future PR I'd like to get rid of the canonical filter checker, and instead ensure that a lookup expression is canonical by always constructing the expression, and not reusing one. Doing so should be less error prone.
</blockquote></details>

Then should we add a test case for something like `i = 10 AND j < 10` (i.e. two different variables)?

**Comment by mgartner** [comment]
*[pkg/sql/opt/xform/join_funcs_test.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-Oab3e7-vXB-E-btfz:-N-T5IFpBZK2Fx1JHzGJ:bv8ah51) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs_test.go#L174)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Then should we add a test case for something like `i = 10 AND j < 10` (i.e. two different variables)?
</blockquote></details>

This is test is testing individual FiltersItems, and `i = 10 AND j < 10` is split up into two filters items, so I don't think this test case is necessary.

**Review by rytaft — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/79586)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @mgartner and @rytaft)

___
*[pkg/sql/opt/xform/join_funcs_test.go, line 174 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/79586#-N-Oab3e7-vXB-E-btfz:-N-UuCNcBHOpBviMkGpF:b-whtlmm) ([raw file](https://github.com/cockroachdb/cockroach/blob/e2277350105e995d83e081f0a305c7d8e37e194e/pkg/sql/opt/xform/join_funcs_test.go#L174)):*
<details><summary><i>Previously, mgartner (Marcus Gartner) wrote…</i></summary><blockquote>

This is test is testing individual FiltersItems, and `i = 10 AND j < 10` is split up into two filters items, so I don't think this test case is necessary.
</blockquote></details>

Oh ok! Then never mind.

**Comment by mgartner** [comment]
TFTRs!

bors r+

**Pull request merged**
