### PR TITLE
roachtest: update version map and create fixtures

### PR DESCRIPTION
**Pull request by asubiotto**
This commit adds the recently released 19.1.10, 19.2.8, and 20.1.3 to the
version map in PredecessorVersion.

Release note: None (testing change)

### CODE REVIEW

**Review by jlinder — COMMENTED** [review]
Why are all the checkpoint fixtures updated in this PR? Is this something that should be happening every time the version map gets changed?

**Comment by asubiotto** [comment]
Yes, according to this comment:
```
	// NB: you can update the values in this map to point at newer patch
	// releases. You will need to run acceptance/version-upgrade with the
	// checkpoint option enabled to create the missing store directory fixture
	// (see runVersionUpgrade). The same is true for adding a new key to this
	// map.
```

**Review by jlinder — APPROVED** [review]
LGTM

**Comment by asubiotto** [comment]
bors r=jlinder

**Comment by asubiotto** [comment]
If anyone is reading this PR after the fact and wondering how I did it, a crucial step is to run the roachtest using the `--local` flag.

**Pull request merged**
