### PR TITLE
admission: eliminate WorkQueue.admitMu

### PR DESCRIPTION
**Pull request by sumeerbhola**
This was probably a misguided attempt to be very fair by ensuring that while one work item was doing a tryGet, a different one did not race ahead and succeed in a tryGet. If these tryGets fail, the WorkQueue will use (tenant-id, priority, creation-time) to order these requests, so this attempt at fairness seems worthless.

We have seen an instance where admitMu is causing high mutex contention. This change may help, or it may shift the contention to WorkQueue.mu. WorkQueue.mu is slightly narrower, and we are ok with small gains.

Relates to https://github.com/cockroachlabs/support/issues/3035

Epic: none

Release note: None

### CODE REVIEW

**Review by aadityasondhi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/129757#-:-O5KjP1hAf1jNGPiJj4R:bnfp4nl)* status: <span>:shipit:</span> complete! 1 of 0 LGTMs obtained

**Comment by aadityasondhi** [comment]
I am assuming we want this backported to a few releases, right?

**Comment by sumeerbhola** [comment]
TFTR!

> I am assuming we want this backported to a few releases, right?

I added a few labels, all the way back to 23.1.

**Comment by sumeerbhola** [comment]
bors r=aadityasondhi

**Pull request merged**
