### PR TITLE
ui: txn insights details fixes

### PR DESCRIPTION
**Pull request by xinhaoz**
See individual commits.

image
image

### CODE REVIEW

**Review by maryliag — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96832)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @xinhaoz)

___
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetails.tsx` line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96832#-NNqEbzp4y2y3hwXCQL8:-NNqEbzp4y2y3hwXCQL9:b9bhuze) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b83bde555f243d69a7ae5a39153c921bfeb1070/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetails.tsx#L151)):*
> ```XML
>           <Tabs.TabPane tab="Overview" key={TabKeysEnum.OVERVIEW}>
>             <TransactionInsightDetailsOverviewTab
>               isLoading={txnDetails == null && fetches.current === 0}
> ```

if you're trying 3 times, should this be `txnDetails == null && fetches.current < MAX_REQ_ATTEMPTS` ?

**Comment by xinhaoz** [comment]
*[`pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetails.tsx` line 151 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/96832#-NNqEbzp4y2y3hwXCQL8:-NNr-Ia4C0_3HYV-LmcA:bmmhif2) ([raw file](https://github.com/cockroachdb/cockroach/blob/5b83bde555f243d69a7ae5a39153c921bfeb1070/pkg/ui/workspaces/cluster-ui/src/insights/workloadInsightDetails/transactionInsightDetails.tsx#L151)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

if you're trying 3 times, should this be `txnDetails == null && fetches.current < MAX_REQ_ATTEMPTS` ?
</blockquote></details>

Ah yes, nice catch. Fixed!

**Review by maryliag — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/96832#-:-NNr6rar1AGlCIG1uFOV:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @xinhaoz)

**Comment by xinhaoz** [comment]
TFTR!
bors r=maryliag

**Pull request merged**
