### PR TITLE
sql: don't panic when PREPARING a PREPARE

### LINKED ISSUE #77061: sql: running SQL PREPARE and EXECUTE via the extended protocol panics the server
If you run a SQL-level PREPARE statement (e.g. `PREPARE x AS SELECT `) via the extended protocol, the server panics with the following stack trace:

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x70 pc=0x2fb7ad4]

goroutine 903 [running]:
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).closeWrapper(0xc00150c600, {0x523ecf0, 0xc0028bf6c0}, {0x3b14260, 0x756e3d0})
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1043 +0x1a5
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1()
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:744 +0x53
panic({0x3b14260, 0x756e3d0})
        GOROOT/src/runtime/panic.go:1038 +0x215
github.com/cockroachdb/cockroach/pkg/sql/types.(*T).Oid(...)
        github.com/cockroachdb/cockroach/pkg/sql/types/pkg/sql/types/types.go:1169
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).addPreparedStmt(0xc00150c600, {0x523ed98, 0xc002c476b0}, {0xc000fd9eba, 0x0}, {{{0x526c278, 0xc002082380}, {0xc000fd9ebd, 0x4d}, 0x2, ...}, ...}, ...)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:127 +0x514
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPrepare(0xc00150c600, {0x523ed98, 0xc002c47680}, {{0xc000fd9eba, 0x2}, {{0x526c278, 0xc002082380}, {0xc000fd9ebd, 0x4d}, 0x2, ...}, ...})
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor_prepare.go:63 +0x3b8
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd(0xc00150c600)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1948 +0x10c6
github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run(0xc00150c600, {0x523ecf0, 0xc0028bf6c0}, 0xc00223d920, {0xc00045b110, 0xc00343bdf8, 0xc002047550, 0x0}, 0xc00070bb30)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1779 +0x245
github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn(0xc001c66000, {0x523ecf0, 0xc0028bf6c0}, {0xc0003dd100}, {0x3, 0xc000a39190, 0xc002047550, 0x0}, 0xc0028bf640)
        github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:746 +0xa8
github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1()
        github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:723 +0x3b0
created by github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync
        github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:642 +0x272
```

There's a similar crash that's possible with a SQL-level `EXECUTE` on a SQL-level prepared statement with type hints if you try to run that via the extended protocol:

```
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +runtime error: index out of range [1] with length 1
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +(1) attached stack trace
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  -- stack trace:
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:744
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | [...repeated from below...]
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +Wraps: (2) while executing: EXECUTE _ ('_', '_')
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +Wraps: (3) attached stack trace
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  -- stack trace:
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn.func1
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:744
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | runtime.gopanic
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  GOROOT/src/runtime/panic.go:1038
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | runtime.goPanicIndex
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  GOROOT/src/runtime/panic.go:90
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).bufferBatch
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:1379
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*commandResult).AddBatch.func1
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/pgwire/command_result.go:235
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*commandResult).addInternal
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/pgwire/command_result.go:212
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*commandResult).AddBatch
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/pgwire/command_result.go:233
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLReceiver).PushBatch
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1155
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*BatchFlowCoordinator).Run
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/colflow/flow_coordinator.go:299
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql/colflow.(*vectorizedFlow).Run
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/colflow/vectorized_flow.go:259
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).Run
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:587
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*DistSQLPlanner).PlanAndRun
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/distsql_running.go:1423
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execWithDistSQLEngine
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1431
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).dispatchToExecutionEngine
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:1108
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmtInOpenState
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:683
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execStmt
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:141
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execPortal
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor_exec.go:229
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd.func2
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1924
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).execCmd
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1926
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*connExecutor).run
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:1779
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql.(*Server).ServeConn
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/conn_executor.go:746
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | github.com/cockroachdb/cockroach/pkg/sql/pgwire.(*conn).processCommandsAsync.func1
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  |  github.com/cockroachdb/cockroach/pkg/sql/pgwire/conn.go:723
E220225 22:28:09.574864 906 1@util/log/logcrash/crash_reporting.go:174  [n1,client=127.0.0.1:40780,user=root] 325 +  | runtime.goexit
```

### PR DESCRIPTION
**Pull request by jordanlewis**
Depends on #77059

Closes #77061

Previously, trying to run a PREPARE statement via the extended protocol
would panic the server. This is no longer the case.

Release note (bug fix): the database no longer crashes when running a
SQL PREPARE via the Postgres extended protocol.
Release justification: Bug fixes and low-risk updates to new functionality

### CODE REVIEW

**Review by rafiss — APPROVED** [review]
nice find! left a few nits, but lgtm

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77063#-:-Mwn50AlCWPWMv1KmrpM:b90xzcb)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/sql_prepare_test.go, line 35 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77063#-Mwn4bkD991dBKKA7Hy9:-Mwn4bkD991dBKKA7HyA:b-hztn8h) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ceeba3121f6473710a65e2c756f0ae198b0e1f0/pkg/sql/sql_prepare_test.go#L35)):*
> ```Go
> 
> 	foo, err := db.Prepare("PREPARE x AS SELECT $1::int")
> 	if err != nil {
> ```

nit: could simplify to `require.NoError(t, err)`

(ditto below)
___
*[pkg/sql/sql_prepare_test.go, line 51 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77063#-Mwn4qNmEXf-VEbrWIvs:-Mwn4qNmEXf-VEbrWIvt:b-7467hh) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ceeba3121f6473710a65e2c756f0ae198b0e1f0/pkg/sql/sql_prepare_test.go#L51)):*
> ```Go
> 	if err := r.Scan(&output); err != nil {
> 		t.Fatal(err)
> 	}
> ```

nit: simplify to 
```
var output int
err = foo.QueryRow().Scan(&output)
require.NoError(t, err)
```



_Code quote:_
```Go
	r := foo.QueryRow()
	var output int
	if err := r.Scan(&output); err != nil {
		t.Fatal(err)
	}
```
___
*[pkg/sql/sql_prepare_test.go, line 53 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/77063#-Mwn4gTS8zyvHU9A_cpW:-Mwn4gTS8zyvHU9A_cpX:b-dzxmba) ([raw file](https://github.com/cockroachdb/cockroach/blob/4ceeba3121f6473710a65e2c756f0ae198b0e1f0/pkg/sql/sql_prepare_test.go#L53)):*
> ```Go
> 	}
> 
> 	assert.Equal(t, 4, output)
> ```

nit: maybe use `require.Equal(t, 4, output)`

**Review by jordanlewis — COMMENTED** [review]
PTAL, I added a second commit that fixed a similar problem that occurred when executing a prepared EXECUTE :/

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77063#-:-MwnRMd76CSqzk05Uz0s:b-vib8cv)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Review by rafiss — APPROVED** [review]
nice! left optional comment

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77063#-:-MwwG_Kb1MgapPrQELLh:b-8ccsax)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis and @rafiss)

___
*[pkg/sql/sql_prepare_test.go, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77063#-MwwGEfQ8cK3Js6FQir4:-MwwGEfQ8cK3Js6FQir5:b-ue2jw4) ([raw file](https://github.com/cockroachdb/cockroach/blob/48a9a57438b763a4c27c7c051d3dbfb0967f140f/pkg/sql/sql_prepare_test.go#L26)):*
> ```Go
> // Make sure that running a wire-protocol-level PREPARE of a SQL-level PREPARE
> // doesn't cause any problems.
> func TestPreparePrepare(t *testing.T) {
> ```

nit: maybe rename the test since it also covers EXECUTE. also, could be good to use `t.Run` subtests to make it clear what all the different parts are testing.

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77063)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/sql_prepare_test.go, line 26 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/77063#-MwwGEfQ8cK3Js6FQir4:-MwyzGhV3bNEO9eS5K2n:b-6k18up) ([raw file](https://github.com/cockroachdb/cockroach/blob/48a9a57438b763a4c27c7c051d3dbfb0967f140f/pkg/sql/sql_prepare_test.go#L26)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: maybe rename the test since it also covers EXECUTE. also, could be good to use `t.Run` subtests to make it clear what all the different parts are testing.
</blockquote></details>

Done. I don't like using subtests here because they would not be independent - for subtests to make sense they really should be runnable individually, since they're designed to be individually triggered with TestFoo/subtest-name. So I added comments instead.

**Review by jordanlewis — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/77063#-:-Mx07x371UYQcj-iC2mX:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

**Pull request merged**
