### PR TITLE
Fix data race in node_test TestNodeJoinSelf.

### LINKED ISSUE #4264: Failed tests (12550):
The following test appears to have failed:

[#12550](https://circleci.com/gh/cockroachdb/cockroach/12550):

```
=== RUN   TestNodeJoinSelf
I0209 19:30:47.903459 437 server/node.go:323  store store=0:0 ([]=) not bootstrapped
I0209 19:30:47.903797 437 stopper.go:273  draining; tasks left:
1      gossip/gossip.go:767
==================
WARNING: DATA RACE
Write by goroutine 142:
  github.com/cockroachdb/cockroach/gossip/resolver.(*socketResolver).GetAddress()
      /go/src/github.com/cockroachdb/cockroach/gossip/resolver/socket.go:57 +0x1fc
  github.com/cockroachdb/cockroach/gossip.(*Gossip).getNextBootstrapAddress()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:727 +0x286
  github.com/cockroachdb/cockroach/gossip.(*Gossip).bootstrap.func1.1()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:763 +0x1a4
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunTask()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:125 +0xeb
  github.com/cockroachdb/cockroach/gossip.(*Gossip).bootstrap.func1()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:767 +0xac
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker.func1()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:98 +0x5f

Previous write by goroutine 48:
  github.com/cockroachdb/cockroach/gossip/resolver.(*socketResolver).GetAddress()
      /go/src/github.com/cockroachdb/cockroach/gossip/resolver/socket.go:57 +0x1fc
  github.com/cockroachdb/cockroach/server.(*Node).initStores()
      /go/src/github.com/cockroachdb/cockroach/server/node.go:349 +0x591
  github.com/cockroachdb/cockroach/server.(*Node).start()
      /go/src/github.com/cockroachdb/cockroach/server/node.go:258 +0x151
  github.com/cockroachdb/cockroach/server.TestNodeJoinSelf()
      /go/src/github.com/cockroachdb/cockroach/server/node_test.go:274 +0x659
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Goroutine 142 (running) created at:
  github.com/cockroachdb/cockroach/util/stop.(*Stopper).RunWorker()
      /go/src/github.com/cockroachdb/cockroach/util/stop/stopper.go:99 +0x6f
  github.com/cockroachdb/cockroach/gossip.(*Gossip).bootstrap()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:784 +0x103
  github.com/cockroachdb/cockroach/gossip.(*Gossip).Start()
      /go/src/github.com/cockroachdb/cockroach/gossip/gossip.go:688 +0x71
  github.com/cockroachdb/cockroach/server.createTestNode()
      /go/src/github.com/cockroachdb/cockroach/server/node_test.go:81 +0xf79
  github.com/cockroachdb/cockroach/server.TestNodeJoinSelf()
      /go/src/github.com/cockroachdb/cockroach/server/node_test.go:272 +0x572
  testing.tRunner()
      /tmp/workdir/go/src/testing/testing.go:456 +0xdc

Goroutine 48 (running) created at:
  testing.RunTests()
      /tmp/workdir/go/src/testing/testing.go:561 +0xaa3
  testing.(*M).Run()
      /tmp/workdir/go/src/testing/testing.go:494 +0xe4
  github.com/cockroachdb/cockroach/util/leaktest.TestMainWithLeakCheck()
      /go/src/github.com/cockroachdb/cockroach/util/leaktest/leaktest.go:37 +0x2e
  github.com/cockroachdb/cockroach/server_test.TestMain()
      /go/src/github.com/cockroachdb/cockroach/server/main_test.go:34 +0x2e
  main.main()
      github.com/cockroachdb/cockroach/server/_test/_testmain.go:118 +0x209
--
1      ts/db.go:98
I0209 19:31:03.966526 437 storage/engine/rocksdb.go:137  closing in-memory rocksdb instance
--- PASS: TestMetricsRecording (1.37s)
PASS
Found 1 data race(s)
FAIL	github.com/cockroachdb/cockroach/server	26.896s
=== RUN   TestNodeStatusMonitor
--- PASS: TestNodeStatusMonitor (0.01s)
=== RUN   TestNodeStatusRecorder
--- PASS: TestNodeStatusRecorder (0.03s)
=== RUN   TestRuntimeStatRecorder
I0209 19:30:59.406887 468 server/status/runtime.go:137  runtime stats: 11 goroutines, 3.11MiB active, 50000000.00cgo/sec, 629240.00/387220.00 %(u/s)time, 25119.11 %gc (2x)
--- PASS: TestRuntimeStatRecorder (0.01s)
=== RUN   TestNodeEventFeed
--- PASS: TestNodeEventFeed (0.01s)
=== RUN   TestServerNodeEventFeed

```
Please assign, take a look and update the issue accordingly.

### PR DESCRIPTION
**Pull request by spencerkimball**
Fixes #4264

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4273)

### CODE REVIEW

**Comment by tamird** [comment]
Fix LGTM but please break out the unrelated changes.

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gossip/resolver/socket.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4273#-KA6jJ4u6cfolfnbX05p:-KA6jJ4u6cfolfnbX05q:-583233240) ([raw file](https://github.com/cockroachdb/cockroach/blob/d30c12a8c2dfd5b6c90da3ca89eac08318947678/gossip/resolver/socket.go#L50)):*
This looks unrelated to the race fix. Can you put it in a separate commit that explains what it's doing?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4273#-:-KA6j_C6C1hFT7V-or8r:-1230077226)*

**Comment by spencerkimball** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gossip/resolver/socket.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4273#-KA6jJ4u6cfolfnbX05p:-KA71fpk6GFwA2DIK1ob:970517911) ([raw file](https://github.com/cockroachdb/cockroach/blob/d30c12a8c2dfd5b6c90da3ca89eac08318947678/gossip/resolver/socket.go#L50)):*
Type "lb" was phased out a while ago and this is just a small cleanup.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4273)*

**Comment by bdarnell** [comment]
How does this fix the race? I think you need a mutex in `socketResolver` to guard the `exhausted` field.

**Comment by spencerkimball** [comment]
Because I'm not longer calling `GetAddress()`

**Comment by bdarnell** [comment]
And the code that does call GetAddress and IsExhausted is guaranteed to do so from only a single thread? If so this should be documented on the Resolver interface.

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gossip/resolver/socket.go, line 50 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4273#-KA6jJ4u6cfolfnbX05p:-KA74IPla88uTlgP8be3:105118780) ([raw file](https://github.com/cockroachdb/cockroach/blob/d30c12a8c2dfd5b6c90da3ca89eac08318947678/gossip/resolver/socket.go#L50)):*
I understand; still, it deserves a separate commit.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4273)*

**Comment by spencerkimball** [comment]
@tamird we routinely clean up old comments and cruft during unrelated code reviews. This is dead code, not a functional change.

**Comment by spencerkimball** [comment]
I added a comment.

**Comment by bdarnell** [comment]
LGTM

**Comment by tamird** [comment]
> @tamird we routinely clean up old comments and cruft during unrelated code reviews. This is dead code, not a functional change.

I agree. I'm not asking for another PR, just another commit. Doesn't matter at this point, I just wanted to clarify.

**Comment by spencerkimball** [comment]
Do you normally merge both commits?

**Comment by tamird** [comment]
Yeah, if they're orthogonal (and in this case they were).

**Pull request merged**
