### PR TITLE
colexec: use Get methods on native type slices

### PR DESCRIPTION
**Pull request by jordanlewis**
Also, add //gcassert:inline assertions on all Get methods but the
DatumVec ones and the gcassert linter, to prove that all of these Get
methods are inlined.

Here are some benchmarks. I didn't run them all, because I believe that
the guaranteed inlining proven by gcassert implies that any benchmark
differences must be due to "binary layout" or other ghosts.

```
Distinct/Ordered/hasNulls=false/newTupleProbability=0.010/rows=65536/cols=2/ordCols=2-24     468µs ± 0%     462µs ± 0%  -1.26%  (p=0.000 n=10+10)

name                                                                                      old speed      new speed      delta
Distinct/Ordered/hasNulls=false/newTupleProbability=0.010/rows=65536/cols=2/ordCols=2-24  2.24GB/s ± 0%  2.27GB/s ± 0%  +1.28%  (p=0.000 n=10+10)

CastOp/useSel=true/hasNulls=true/int_to_float-24      5.18µs ± 2%    4.60µs ± 1%  -11.21%  (p=0.000 n=9+9)
CastOp/useSel=true/hasNulls=false/int_to_float-24     1.06µs ± 7%    1.03µs ± 5%     ~     (p=0.101 n=10+10)
CastOp/useSel=false/hasNulls=true/int_to_float-24     5.33µs ± 1%    5.47µs ± 2%   +2.53%  (p=0.000 n=9+10)
CastOp/useSel=false/hasNulls=false/int_to_float-24    1.08µs ± 0%    1.08µs ± 0%     ~     (p=0.136 n=10+10)

name                                                old speed      new speed      delta
CastOp/useSel=true/hasNulls=true/int_to_float-24    1.58GB/s ± 2%  1.78GB/s ± 1%  +12.62%  (p=0.000 n=9+9)
CastOp/useSel=true/hasNulls=false/int_to_float-24   7.73GB/s ± 7%  7.93GB/s ± 5%     ~     (p=0.089 n=10+10)
CastOp/useSel=false/hasNulls=true/int_to_float-24   1.54GB/s ± 1%  1.50GB/s ± 2%   -2.46%  (p=0.000 n=9+10)
CastOp/useSel=false/hasNulls=false/int_to_float-24  7.60GB/s ± 0%  7.59GB/s ± 0%     ~     (p=0.143 n=10+10)
```

Release note: None

### CODE REVIEW

**Comment by asubiotto** [comment]
I like this change 👍  should we wait for your bounds check linter before merging?

**Comment by jordanlewis** [comment]
I've un-dnm'd this, added `gcassert` assertions and the linter, and ran some benchmarks.

**Review by yuzefovich — APPROVED** [review]
:lgtm:

> Reviewed 38 of 38 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/50768#-:-MB4iwGo7Rg2Lir8c1Uq:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis)

___
*[pkg/sql/colexec/execgen/cmd/execgen/overloads_base.go, line 455 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/50768#-MB4imST08BgKh_2xFJz:-MB4imST08BgKh_2xFK-:b-pl3fe4) ([raw file](https://github.com/cockroachdb/cockroach/blob/12cd242d6c7ee99d46e19735bfad48eedb568e96/pkg/sql/colexec/execgen/cmd/execgen/overloads_base.go#L455)):*
> ```Go
> func get(family types.Family, target, i string) string {
> 	// Assert that the .Get call is inlined by Go, except in the case
> 	// of the DatumVec .Get which isn't inlinable.
> ```

nit: should it be `s/DatumVec .Get/DatumVec.Get/`?

**Comment by yuzefovich** [comment]
I think my commit from #50650 was merged for the second time in this PR :)

**Comment by jordanlewis** [comment]
I don't think so - git doesn't let you do that if the commits are the same. Check the log!

**Comment by yuzefovich** [comment]
Hm, indeed, it doesn't appear to be in the git log. What prompted me to look into this is that daily digest mentioned that this PR removed 27k lines of code, and I was like "what?!", so I checked the commits on master on the github, and I saw my face on the merge commit for this PR:
Screen Shot 2020-07-01 at 7 17 06 AM
I guess github treats things differently from git 🤷‍♂️

**Comment by jordanlewis** [comment]
Weird, that's annoying. GitHub is so frustrating. There should be no point to me rebasing a PR onto master if it contains a dependent commit on someone else's branch, since of course git itself won't care.

**Pull request merged**
