### PR TITLE
log: misc logging fixes

### LINKED ISSUE #23219: sql: exec log does not automatically flushed
The exec log enabled via the cluster setting `sql.trace.log_statement_execute` currently only gets flushed on rotations (default: every 10MB) or process shutdown. The automatic flush daemon is not running for it.

Spotted by @BramGruneir

### PR DESCRIPTION
**Pull request by knz**
Fixes #23219.

### CODE REVIEW

**Comment by knz** [comment]
I'm not married to the 3rd commit in the series. Please chime in with opinions.

**Comment by BramGruneir** [comment]
:lgtm: and I'm ok with 10s.  Probably best to get @bdarnell 's opinion on it.

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/23221#-:-L6S_H8H2PyURoh1dNNU:bgvzwuf)*

**Comment by knz** [comment]
On @bdarnell's suggestion, working on an additional commit to split flush from sync.

**Comment by knz** [comment]
I removed the last commit that changes the period and will merge this PR as-is. I will make a separate PR to split flush from sync.

**Comment by BramGruneir** [comment]
SGTM

**Pull request merged**
