### PR TITLE
changefeedccl: uri sinks, fill in record key, WITH envelope

### PR DESCRIPTION
**Pull request by danhhz**
See commit messages for details

### CODE REVIEW

**Comment by tschottdorf** [comment]
:lgtm: mod nits

---

Reviewed 8 of 8 files at r1, 2 of 2 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[pkg/ccl/changefeedccl/changefeed.go, line 224 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChWmke17hiktJMQTP4:-LChWmkf5X9lKFy-jO5G:b-3s4t3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed.go#L224)):*
> ```Go
> 		colIdxMap := make(map[sqlbase.ColumnID]int)
> 		var valNeededForCol util.FastIntSet
> 		if cf.envelope == optEnvelopeKeyOnly {
> ```

nit:

```go
var colIDs []sometype
if cf.envelope == optEnvelopeKeyOnly {
  colIDs = tableDesc.PrimaryIndex.ColumnIDs
} else {
  colIDs = tableDesc.Columns
}
for ...
```

---

*[pkg/ccl/changefeedccl/changefeed.go, line 365 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChX8uO2k0VXmkGZmwM:-LChX8uO2k0VXmkGZmwN:b-6mc7me) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed.go#L365)):*
> ```Go
> 		jsonKey.Format(&key)
> 		var value bytes.Buffer
> 		if cf.envelope == optEnvelopeNone {
> ```

I'm not quite sure what the "envelope" stands for, but is it intuitive that "none" corresponds to "both"? Should it just be `optEnvelopeBoth`?

---

*[pkg/ccl/changefeedccl/changefeed_test.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChXKP39geEdUn9dYzC:-LChXKP39geEdUn9dYzD:b7bo7pu) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed_test.go#L80)):*
> ```Go
> 	const testPollingInterval = 10 * time.Millisecond
> 	defer func(oldInterval time.Duration) {
> 		jobs.DefaultAdoptInterval = oldInterval
> ```

Since this is new code, can we do the Right Thing™ and pass this as a testing knob instead of futzing with a global?

---

*[pkg/ccl/changefeedccl/changefeed_test.go, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChXfqEEMhN0Y3666kS:-LChXfqEEMhN0Y3666kT:b-d9px00) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed_test.go#L97)):*
> ```
> testProducersHook
> ```

Another candidate to move into a knob.

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-:-LChXpr31AeKC2YAUg8b:b-tkmfg9)*

**Comment by danhhz** [comment]
Review status: 6 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

*[pkg/ccl/changefeedccl/changefeed.go, line 224 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChWmke17hiktJMQTP4:-LCik-Vq2HgIuCUeD1SO:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed.go#L224)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

nit:

```go
var colIDs []sometype
if cf.envelope == optEnvelopeKeyOnly {
  colIDs = tableDesc.PrimaryIndex.ColumnIDs
} else {
  colIDs = tableDesc.Columns
}
for ...
```
</blockquote></details>

Done

---

*[pkg/ccl/changefeedccl/changefeed.go, line 365 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChX8uO2k0VXmkGZmwM:-LCikCnb7es1ANHKSyVQ:bnldndp) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed.go#L365)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

I'm not quite sure what the "envelope" stands for, but is it intuitive that "none" corresponds to "both"? Should it just be `optEnvelopeBoth`?
</blockquote></details>

yeah. "envelope" make more sense when the third value gets introduced, which is both the new and old row values. how about `optEnvelopeRow` for this?

---

*[pkg/ccl/changefeedccl/changefeed_test.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChXKP39geEdUn9dYzC:-LCizv8-51aD7Y18xpro:b-dbmmtz) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed_test.go#L80)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

Since this is new code, can we do the Right Thing™ and pass this as a testing knob instead of futzing with a global?
</blockquote></details>

Sure, though I'd like to do it on another PR if that's alright. There's a bunch of other references to this that should also get updated. https://github.com/cockroachdb/cockroach/issues/25622

---

*[pkg/ccl/changefeedccl/changefeed_test.go, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChXfqEEMhN0Y3666kS:-LCj-TKoDjwP-rXQfkQT:beyxrqf) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed_test.go#L97)):*
<details><summary><i>Previously, tschottdorf (Tobias Schottdorf) wrote…</i></summary><blockquote>

> ```
> testProducersHook
> ```

Another candidate to move into a knob.
</blockquote></details>

I think the plan is to replace this with the sql table sink that ben suggested in the rfc

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25542)*

**Comment by tschottdorf** [comment]
Still LGTM.

---

Reviewed 2 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[pkg/ccl/changefeedccl/changefeed.go, line 365 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChX8uO2k0VXmkGZmwM:-LCj3eXEAaGew4cLIlhK:b-v0paw8) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed.go#L365)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

yeah. "envelope" make more sense when the third value gets introduced, which is both the new and old row values. how about `optEnvelopeRow` for this?
</blockquote></details>

I'm not really in the know here, but `optEnvelopeRow`  SGTM.

---

*[pkg/ccl/changefeedccl/changefeed_test.go, line 80 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChXKP39geEdUn9dYzC:-LCj3lEHDfukKPkfkOZJ:bkf6n0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed_test.go#L80)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

Sure, though I'd like to do it on another PR if that's alright. There's a bunch of other references to this that should also get updated. https://github.com/cockroachdb/cockroach/issues/25622
</blockquote></details>

Sure, thanks!

---

*[pkg/ccl/changefeedccl/changefeed_test.go, line 97 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-LChXfqEEMhN0Y3666kS:-LCj3lwm2EjEQK_9YL1X:bpbeaqk) ([raw file](https://github.com/cockroachdb/cockroach/blob/c29bfac695d26abc7ae56535b0501c4677283130/pkg/ccl/changefeedccl/changefeed_test.go#L97)):*
<details><summary><i>Previously, danhhz (Daniel Harrison) wrote…</i></summary><blockquote>

I think the plan is to replace this with the sql table sink that ben suggested in the rfc
</blockquote></details>

:thumbsup: that's even better

---


*Comments from [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/25542#-:-LCj3ueA5qKofCsk92qH:b-8zvpdv)*

**Comment by danhhz** [comment]
bors r=tschottdorf

**Comment by tschottdorf** [comment]
Could you triage the build failure? See https://github.com/cockroachdb/cockroach/pull/25616#issuecomment-389959482

**Comment by danhhz** [comment]
flake in TestReplicaLeaseRejectUnknownRaftNodeID

```
replica_test.go:1206: unexpected error obtaining lease for invalid store: cannot replace lease repl=(n1,s1):1 seq=1 start=0.000000000,0 exp=1.800000124,3 pro=0.900000124,4 with repl=(n2,s2):2 seq=0 start=0.900000124,0 exp=0.900000134,0: requested lease overlaps previous lease
```

**Comment by nvanbenschoten** [comment]
Looks like the flake is #25568. I'll help @a-robinson investigate.

**Comment by nvanbenschoten** [comment]
Never mind, he already has a fix out https://github.com/cockroachdb/cockroach/pull/25625.

**Comment by tschottdorf** [comment]
> I looked at it before rerunning, but the test timed out and failed most of the logic tests. Are we really posting that for every flake now? I haven't heard it announced anywhere

This is just a favor I ask, since it helps me keep track of what's urgent. Most of our builds are on PR branches, not master. Also, the authors already look at the failed build anyway (or how could they be sure that they didn't introduce the problem) so it's just a small step to let the rest of the world know what went wrong as well.

Ideally, of course, the bors message would contain the snippet from bors.. filed https://github.com/cockroachdb/cockroach/issues/25632.

**Pull request merged**
