### PR TITLE
tracing: add package-level documentation for tracing concepts

### PR DESCRIPTION
**Pull request by irfansharif**
First two commits are from #58509, and can be ignored here.

Release note: None

### CODE REVIEW

**Review by tbg — APPROVED** [review]
Thank you!

> Reviewed 7 of 7 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 8 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/58516#-:-MQQxbc0D72goCnrc2ib:b-9755fn)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @knz)

___
*[pkg/util/tracing/doc.go, line 53 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/58516#-MQQx7R37iobKfBbTVQw:-MQQx7R37iobKfBbTVQx:b-610zc) ([raw file](https://github.com/cockroachdb/cockroach/blob/36fb923ae7e6c23cb6e20a7d6e3d7ed9e5152e63/pkg/util/tracing/doc.go#L53)):*
> ```Go
> //                          way depend on the result of the second (think of a
> //                          goroutine that spins off another that outlives it).
> //                          Somewhat confusingly, we still refer to the "first"
> ```

It's not that confusing when you consider that even with a parent-child relation, you can still have the child outlive the parent (you shouldn't - but there's nothing stopping you). The relation type, as far as I can tell, is really more of a hint than something that materially effects how the span works.

**Comment by irfansharif** [comment]
#58211, sigh.

bors r+

**Comment by irfansharif** [comment]
This has to be my unluckiest PR to date, [now](https://teamcity.cockroachdb.com/viewLog.html?buildId=2568109&buildTypeId=Cockroach_UnitTests) with:

```
BenchmarkPgCopyConvertRecord
panic: runtime error: slice bounds out of range [1:0]
```

bors r+

**Pull request merged**
