### PR TITLE
sql: add default_value and origin to show cluster settings

### PR DESCRIPTION
**Pull request by maryliag**
Fixes https://cockroachlabs.atlassian.net/browse/CRDB-28519

**Commit 1**
This adds an API to the settings package to track the origin of the current value of each setting, such as whether it is set by the the default value, an explicit override or an external override.

**Commit 2**
Previously, there was no easy way to see default values for
cluster settings. This commit add the column for `default_value`
and `origin` to `crdb_internal.cluster_settings` and
the `show cluster settings` command.

Release note (sql change): Add columns `default_value` and
`origin` (default, override, external-override) to the
`show cluster settings` command.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
nice, this is a great improvement! just small nits

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-:-NXHdvB2EcBaxf3K5dRA:bh7b08e)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NXHdou28QGvMBPSX6E8):*
nit: let's avoid mentioning the crdb_internal table in the release note. it's good for the commit message though.
___
*[`pkg/sql/crdb_internal.go` line 2117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NXHdgQK0xjRI-dSujT4:-NXHdgQK0xjRI-dSujT5:b-fybq6m) ([raw file](https://github.com/cockroachdb/cockroach/blob/706e0a996f51dfc713f2a1a7a7093d57afb0542a/pkg/sql/crdb_internal.go#L2117)):*
> ```Go
> 			defaultVal, err := setting.DecodeToString(setting.EncodedDefault())
> 			if err != nil {
> 				defaultVal = setting.EncodedDefault()
> ```

why should we ignore the error here? i don't think this is ever expected to happen. if it is expected for some reason, that deserves a comment in the code

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104449)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 2117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NXHdgQK0xjRI-dSujT4:-NXHefx_47QjWepAqbFH:blfcjm8) ([raw file](https://github.com/cockroachdb/cockroach/blob/706e0a996f51dfc713f2a1a7a7093d57afb0542a/pkg/sql/crdb_internal.go#L2117)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

why should we ignore the error here? i don't think this is ever expected to happen. if it is expected for some reason, that deserves a comment in the code
</blockquote></details>

do you think this is a "panic" level or just "log this error" type of thing here?

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104449)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/crdb_internal.go` line 2117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NXHdgQK0xjRI-dSujT4:-NXHgFqME9qSZIHKcMlR:bhkjwax) ([raw file](https://github.com/cockroachdb/cockroach/blob/706e0a996f51dfc713f2a1a7a7093d57afb0542a/pkg/sql/crdb_internal.go#L2117)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

do you think this is a "panic" level or just "log this error" type of thing here?
</blockquote></details>

i'd say neither, it should just be a:
```
if err != nil {
  return err
}
```

**Comment by knz** [comment]
Maybe this would benefit from https://github.com/cockroachdb/cockroach/pull/104487

**Comment by maryliag** [comment]
Made changes to the column be `origin` instead of `is_overridden`. Right now is just comparing with the default, but once https://github.com/cockroachdb/cockroach/pull/104487 gets merged, this PR can be updated to use the value from there

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104449)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`-- commits` line 12 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NXHdou28QGvMBPSX6E8):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: let's avoid mentioning the crdb_internal table in the release note. it's good for the commit message though.
</blockquote></details>

Done
___
*[`pkg/sql/crdb_internal.go` line 2117 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NXHdgQK0xjRI-dSujT4:-NXLDroB1ojfQFXP93bh:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/706e0a996f51dfc713f2a1a7a7093d57afb0542a/pkg/sql/crdb_internal.go#L2117)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i'd say neither, it should just be a:
```
if err != nil {
  return err
}
```
</blockquote></details>

Done

**Review by rafiss — APPROVED** [review]
lgtm, but had a question

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-:-NXWl5u78wO73BNfTVnl:b-mnrkuy)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @maryliag)

___
*[`pkg/sql/crdb_internal.go` line 2123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NXWkxiPBorO-azGTkde:-NXWkxiPBorO-azGTkdf:b-x78w5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/73a3bed75ef1181738a7e16797b9e72a40110b47/pkg/sql/crdb_internal.go#L2123)):*
> ```Go
> 			// TODO(dt): make this reflect overrides for tenants
> 			if strVal != defaultVal {
> 				origin = "override"
> ```

what would "external-override" mean? i saw it in the comment, but doesn't look like we ever use it.

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104449)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/crdb_internal.go` line 2123 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NXWkxiPBorO-azGTkde:-NXWm1ag8Mv9J-EDuiJj:b-ct723l) ([raw file](https://github.com/cockroachdb/cockroach/blob/73a3bed75ef1181738a7e16797b9e72a40110b47/pkg/sql/crdb_internal.go#L2123)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

what would "external-override" mean? i saw it in the comment, but doesn't look like we ever use it.
</blockquote></details>

Currently not using because I'm waiting for https://github.com/cockroachdb/cockroach/pull/104487 to get merged, so I can use the flag from there on this PR as I mentioned on this [comment](https://github.com/cockroachdb/cockroach/pull/104449#issuecomment-1580914448).
The difference:
default: the default
ExplicitlySet: the user was the one who made the change
ExternallySet: someone set up for the entire cluster, so if a tenant is looking it will see the value has changed, but they were not the ones who did it

**Review by maryliag — COMMENTED** [review]
Commit from #104487 was added to this PR. PTAL
thank you @dt for the changes!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-:-NYYzRWiBzBzkhGLY796:b-2fzh0z)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @rafiss)

___
*[`pkg/sql/logictest/testdata/logic_test/cluster_settings` line 95 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NYYzfxc1tapOF-enOly:-NYYzfxc1tapOF-enOlz:ba34qsg) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a807fcabb3ce5989a9ad4842b188793e95e77f/pkg/sql/logictest/testdata/logic_test/cluster_settings#L95)):*
> ```
> ----
> sql.index_recommendation.drop_unused_duration  10s 168h0m0s override
> ```

@dt do you have any suggestions on how to test the external-override ?

**Review by rafiss — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104449)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @maryliag)

___
*[`pkg/settings/setting.go` line 164 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NYcZYUq1r7pByMT382P:-NYcZYUq1r7pByMT382Q:b630gdg) ([raw file](https://github.com/cockroachdb/cockroach/blob/2060b92634a766e6c4d568efac12d2e9bb92b2ba/pkg/settings/setting.go#L164)):*
> ```Go
> 
> func (v ValueOrigin) String() string {
> 	return [...]string{"default", "override", "external-override"}[v]
> ```

nit: this has a risk of an index out of bounds. can we add:

```
if v > OriginExternallySet {
  return fmt.Sprintf("invalid (%d)", m)
}
```
___
*[`pkg/sql/logictest/testdata/logic_test/cluster_settings` line 95 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NYYzfxc1tapOF-enOly:-NYcaIDw8ObJILXjLdE2:bn4d7ie) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a807fcabb3ce5989a9ad4842b188793e95e77f/pkg/sql/logictest/testdata/logic_test/cluster_settings#L95)):*
<details><summary><i>Previously, maryliag (Marylia Gutierrez) wrote…</i></summary><blockquote>

@dt do you have any suggestions on how to test the external-override ?
</blockquote></details>

i think it would be something like this:

```
user host-cluster-root

statement ok
ALTER TENANT ALL SET CLUSTER SETTING some.setting = 'value'

user root

query TTTT
SELECT variable, value, default_value, origin FROM [SHOW ALL CLUSTER SETTINGS]
WHERE variable IN ('some.setting')

```

**Review by maryliag — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/104449)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @dt and @rafiss)

___
*[`pkg/settings/setting.go` line 164 at r7](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NYcZYUq1r7pByMT382P:-NYcfT1R6IMYZB1zUcih:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/2060b92634a766e6c4d568efac12d2e9bb92b2ba/pkg/settings/setting.go#L164)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

nit: this has a risk of an index out of bounds. can we add:

```
if v > OriginExternallySet {
  return fmt.Sprintf("invalid (%d)", m)
}
```
</blockquote></details>

Done
___
*[`pkg/sql/logictest/testdata/logic_test/cluster_settings` line 95 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/104449#-NYYzfxc1tapOF-enOly:-NYcg93W5BhzljPR0o6l:b-w7ivhl) ([raw file](https://github.com/cockroachdb/cockroach/blob/d2a807fcabb3ce5989a9ad4842b188793e95e77f/pkg/sql/logictest/testdata/logic_test/cluster_settings#L95)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i think it would be something like this:

```
user host-cluster-root

statement ok
ALTER TENANT ALL SET CLUSTER SETTING some.setting = 'value'

user root

query TTTT
SELECT variable, value, default_value, origin FROM [SHOW ALL CLUSTER SETTINGS]
WHERE variable IN ('some.setting')

```
</blockquote></details>

Nice! Thanks! Added

**Review by dt — APPROVED** [review]

**Comment by maryliag** [comment]
TFTRs!
bors r+

**Pull request merged**
