### PR TITLE
build: enable required release justifications for stability period

### PR DESCRIPTION
**Pull request by jlinder**
To begin stability period for the 21.1 release.

Release justification: non-production code change
Release note: None

### CODE REVIEW

**Review by otan — APPROVED** [review]

**Comment by otan** [comment]
(worth sending an email out to eng when this merges)

**Comment by jlinder** [comment]
TFTR!

bors r=otan

**Comment by otan** [comment]
bors r-

this is going to block everything else in the queue, i'm going to merge this late at night if that's ok

**Pull request merged**
