### PR TITLE
storage: deflake TestReplicaAddAndRemove

### PR DESCRIPTION
**Pull request by tamird**
This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8964)

### CODE REVIEW

**Comment by petermattis** [comment]
:lgtm: modulo the change to use `inc[12]`

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/client_raft_test.go, line 1288 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-KQS96Utw3q42rWx_n1_:-KQS96Utw3q42rWx_n1a:b-92zszx) ([raw file](https://github.com/cockroachdb/cockroach/blob/828442ad960ab787d8a673f05325c69ed908380b/storage/client_raft_test.go#L1288)):*
> ```Go
> 		0,
> 		inc1,
> 	}))
> ```

I liked seeing the explicit constants in the code and the checks. I find this more difficult to follow now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-:-KQS9OdodNyd-NfnCAgf:bt000tl)*

**Comment by tamird** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[storage/client_raft_test.go, line 1288 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-KQS96Utw3q42rWx_n1_:-KQS9c6aWZVX_xZ8v2mP:boul92) ([raw file](https://github.com/cockroachdb/cockroach/blob/828442ad960ab787d8a673f05325c69ed908380b/storage/client_raft_test.go#L1288)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> I liked seeing the explicit constants in the code and the checks. I find this more difficult to follow now.
</details>
The error messages are better now (they'll actually point to the correct line), so it's really not that big a deal.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964)*

**Comment by jordanlewis** [comment]
Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1248 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-KQS9t-n1v4uKQmnz4lV:-KQS9t-n1v4uKQmnz4lW:b4sjv5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/828442ad960ab787d8a673f05325c69ed908380b/storage/client_raft_test.go#L1248)):*
> ```Go
> }
> 
> func testReplicaAddRemove(t *testing.T, addFirst bool) {
> ```

Might be worth adding a quick summary comment explaining what this test does, especially because the new test entry points aren't documented.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1248 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-KQS9t-n1v4uKQmnz4lV:-KQSAQidbnZmDxNdOgVO:b-eeigsw) ([raw file](https://github.com/cockroachdb/cockroach/blob/828442ad960ab787d8a673f05325c69ed908380b/storage/client_raft_test.go#L1248)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> Might be worth adding a quick summary comment explaining what this test does, especially because the new test entry points aren't documented.
</details>
I'm actually not sure how to summarize what this test does. From memory, I believe it was added to ensure that things don't panic when a replica is removed and then re-added without an intervening run of the replica GC queue. Would that be helpful? I'm hesitant because it'd be speculative.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1288 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-KQS96Utw3q42rWx_n1_:-KQSAGbu1bPRpFinygPQ:bdpa68x) ([raw file](https://github.com/cockroachdb/cockroach/blob/828442ad960ab787d8a673f05325c69ed908380b/storage/client_raft_test.go#L1288)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> The error messages are better now (they'll actually point to the correct line), so it's really not that big a deal.
</details>
Eh? I'm saying the code is less readable when using `inc{1,2}` and `inc1 + inc2`. So no, not a big deal, but this doesn't seem useful either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1248 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-KQS9t-n1v4uKQmnz4lV:-KQSAyy3knKfKXbpDOaC:bq7fp3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/828442ad960ab787d8a673f05325c69ed908380b/storage/client_raft_test.go#L1248)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm actually not sure how to summarize what this test does. From memory, I believe it was added to ensure that things don't panic when a replica is removed and then re-added without an intervening run of the replica GC queue. Would that be helpful? I'm hesitant because it'd be speculative.
</details>
To me, the fact that it's so complicated makes it even more important that it get documented. Having the intent of a test documented (when it's not obvious from the name) improves code understandability and discourages duplicate test writing. I agree that you shouldn't add a speculative explanation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964)*

**Comment by tamird** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks pending.

---

*[storage/client_raft_test.go, line 1248 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-KQS9t-n1v4uKQmnz4lV:-KQSBzV29v09b8KL5-Nj:b9v50zt) ([raw file](https://github.com/cockroachdb/cockroach/blob/828442ad960ab787d8a673f05325c69ed908380b/storage/client_raft_test.go#L1248)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary>
> To me, the fact that it's so complicated makes it even more important that it get documented. Having the intent of a test documented (when it's not obvious from the name) improves code understandability and discourages duplicate test writing. I agree that you shouldn't add a speculative explanation.
</details>
I'm not sure what you mean about complication - the test isn't that complicated; I just happen not to be the owner of the intent.

If my speculation is correct, then the name really is quite descriptive.

---

*[storage/client_raft_test.go, line 1288 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-KQS96Utw3q42rWx_n1_:-KQSBcvTR5gCSoAaVwuM:bl1a8ke) ([raw file](https://github.com/cockroachdb/cockroach/blob/828442ad960ab787d8a673f05325c69ed908380b/storage/client_raft_test.go#L1288)):*
<details><summary><i>Previously, petermattis (Peter Mattis) wrote…</i></summary>
> Eh? I'm saying the code is less readable when using `inc{1,2}` and `inc1 + inc2`. So no, not a big deal, but this doesn't seem useful either.
</details>
Previously, the only way to match a test failure to a line in the test was to look for the matching call to `verify` - the line number in the error message was that of the `util.SucceedsSoon` call inside `verify`. This is no longer the case, and thus it is less important that the numbers are obvious constants.

I kind of disagree regarding readability - this makes it clearer (to me) which updates are expected to be visible at each stage in the test.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964)*

**Comment by jordanlewis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_raft_test.go, line 1248 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-KQS9t-n1v4uKQmnz4lV:-KQSD-E0lw-NLXVV44Ah:b-5jfovr) ([raw file](https://github.com/cockroachdb/cockroach/blob/828442ad960ab787d8a673f05325c69ed908380b/storage/client_raft_test.go#L1248)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> I'm not sure what you mean about complication - the test isn't that complicated; I just happen not to be the owner of the intent.
> 
> If my speculation is correct, then the name really is quite descriptive.
</details>
Oh, I figured that you didn't understand how to summarize it because it was complicated. If it's not complicated then can't you just summarize it? I don't mean to belabor the point. If not that's okay.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-:-KQSDC_S52ITC4zhxLP6:bnfp4nl)*

**Comment by petermattis** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

*[storage/client_raft_test.go, line 1288 \[r2\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964#-KQS96Utw3q42rWx_n1_:-KQSCs31Hz2vG45kQi8m:b-9phap8) ([raw file](https://github.com/cockroachdb/cockroach/blob/828442ad960ab787d8a673f05325c69ed908380b/storage/client_raft_test.go#L1288)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Previously, the only way to match a test failure to a line in the test was to look for the matching call to `verify` - the line number in the error message was that of the `util.SucceedsSoon` call inside `verify`. This is no longer the case, and thus it is less important that the numbers are obvious constants.
> 
> I kind of disagree regarding readability - this makes it clearer (to me) which updates are expected to be visible at each stage in the test.
</details>
Yes, I get that the failure message has improved. I disagree about the readability. You've taken 1 line of concise expectation and changed it into 4 and now I have to refer to another part of the code (and below, perform some math) in order to figure out what the values should be. Using `inc{1,2}` has made it easier to change the increment values, but I don't see it aiding readability of the test.

Feel free to disregard. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8964)*

**Pull request merged**
