### PR TITLE
kvserver: remove extraneous circuit breaker check in Raft transport

### PR DESCRIPTION
**Pull request by tbg**
See https://github.com/cockroachdb/cockroach/issues/68419. We now use
`DialNoBreaker` for the raft transport, taking into account the previous
`Ready()` check.

`DialNoBreaker` was previously bypassing the breaker as it ought to but
was also *not reporting to the breaker* the result of the operation;
this is not ideal and was caught by the tests. This commit changes
`DialNoBreaker` to report the result (i.e. fail or success).

Release justification: bug fix
Release note (bug fix): Previously, after a temporary node outage, other
nodes in the cluster could fail to connect to the restarted node due to
their circuit breakers not resetting. This would manifest in the logs
via messages "unable to dial nXX: breaker open", where `XX` is the ID
of the restarted node. (Note that such errors are expected for nodes
that are truly unreachable, and may still occur around the time of
the restart, but for no longer than a few seconds).

### CODE REVIEW

**Review by erikgrinaker — COMMENTED** [review]
This is going to result in the queue filling up when a node is unavailable, and all of those thousands of queued messages getting sent when it comes back up. Do we need some additional TTL logic or queue draining or something to prevent this, or do we already have safeguards for this?

**Review by erikgrinaker — APPROVED** [review]

**Review by erikgrinaker — DISMISSED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/kv/kvserver/raft_transport.go, line 620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69405#-Mi12dmEErt4XOAwObMl:-Mi12dmEErt4XOAwObMm:bhsqurs) ([raw file](https://github.com/cockroachdb/cockroach/blob/c963f23e1f30a84c19f2448dc9cd0edc0b19ff71/pkg/kv/kvserver/raft_transport.go#L620)):*
> ```Go
> 		// checked the breaker. Checking it again can cause livelock, see:
> 		// https://github.com/cockroachdb/cockroach/issues/68419
> 		conn, err := t.dialer.DialNoBreaker(ctx, toNodeID, class)
> ```

This will bypass some internal health logging, which seems unfortunate. We may want to add some corresponding logging here.

https://github.com/cockroachdb/cockroach/blob/f72206dd391e709e2738b2098121aeded139016b/pkg/rpc/nodedialer/nodedialer.go#L159-L162
___
*[pkg/kv/kvserver/raft_transport.go, line 624 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69405#-Mi12OiI6pQ4wqYhfryf:-Mi12OiI6pQ4wqYhfryg:bcmwkfv) ([raw file](https://github.com/cockroachdb/cockroach/blob/c963f23e1f30a84c19f2448dc9cd0edc0b19ff71/pkg/kv/kvserver/raft_transport.go#L624)):*
> ```Go
> 		breaker := t.dialer.GetCircuitBreaker(toNodeID, class)
> 		if err != nil {
> 			breaker.Fail(err)
> ```

We need to check `ctx.Err()` here, otherwise context cancellation will trip the breaker.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69405)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @tbg)

___
*[pkg/rpc/nodedialer/nodedialer.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69405#-Mi1EVRb7p9rvCVubD0b:-Mi1EVRb7p9rvCVubD0c:b-fe70ev) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ba3c7f18371b58c0b0e11a51430f141ddcd172/pkg/rpc/nodedialer/nodedialer.go#L94)):*
> ```Go
> }
> 
> // DialNoBreaker ignores the breaker if there is an error dialing. This function
> ```

This comment should be updated to say it ignores the breaker state and always tries to dial, but reports the result.

**Review by tbg — COMMENTED** [review]
Almost there...

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69405#-:-Mi1RvZfE5IHs_eaontd:b-iufkp5)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[pkg/kv/kvserver/raft_transport.go, line 620 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69405#-Mi12dmEErt4XOAwObMl:-Mi1Qmd-4Q39YrayMujY:b-9rit3w) ([raw file](https://github.com/cockroachdb/cockroach/blob/c963f23e1f30a84c19f2448dc9cd0edc0b19ff71/pkg/kv/kvserver/raft_transport.go#L620)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This will bypass some internal health logging, which seems unfortunate. We may want to add some corresponding logging here.

https://github.com/cockroachdb/cockroach/blob/f72206dd391e709e2738b2098121aeded139016b/pkg/rpc/nodedialer/nodedialer.go#L159-L162
</blockquote></details>

I updated DialNoBreaker to notify the breaker instead. This makes everything work as expected. I needed to update DialNoBreaker to also break on resolver errors. The only other caller is the distSQL outbox, which doesn't care much about this, and https://github.com/cockroachdb/cockroach/pull/40691 didn't offer any explanation. I think it was just flat-out trying to touch the breaker at all, which in hindsight was not ideal. Now we do what should be the right thing: notify the breaker just like `Dial` would, but avoid failing fast.
___
*[pkg/kv/kvserver/raft_transport.go, line 624 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/69405#-Mi12OiI6pQ4wqYhfryf:-Mi1QldW56L_05Nvr12z:b-b3jbv4) ([raw file](https://github.com/cockroachdb/cockroach/blob/c963f23e1f30a84c19f2448dc9cd0edc0b19ff71/pkg/kv/kvserver/raft_transport.go#L624)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

We need to check `ctx.Err()` here, otherwise context cancellation will trip the breaker.
</blockquote></details>

Obsolete.
___
*[pkg/rpc/nodedialer/nodedialer.go, line 94 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/69405#-Mi1EVRb7p9rvCVubD0b:-Mi1R9i3BNXujYU5jA-g:b-r4p8y7) ([raw file](https://github.com/cockroachdb/cockroach/blob/81ba3c7f18371b58c0b0e11a51430f141ddcd172/pkg/rpc/nodedialer/nodedialer.go#L94)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

This comment should be updated to say it ignores the breaker state and always tries to dial, but reports the result.
</blockquote></details>

Rewrote the comment.

**Review by erikgrinaker — APPROVED** [review]
:lgtm:

Maybe consider rewording the commit message, although I suppose it's accurate as is too.

> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/69405#-:-Mi1VSqw6sbAVfwrlB9V:b-3ii2kj)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @tbg)

**Comment by tbg** [comment]
blathers backport 21.1

**Comment by erikgrinaker** [comment]
Can we get a backport to 20.2 as well? The original incident was with 20.2.13, so it applies.

**Comment by tbg** [comment]
blathers backport 20.2

**Comment by tbg** [comment]
Ok, time to build RocksDB again then :-)

**Pull request merged**
