### PR TITLE
cli/sql: new command `\info` to reproduce server details

### LINKED ISSUE #94417: cli/demo: connection URLs are hard to discover
**Describe the problem**

Reported by @bdarnell .
When starting `cockroach demo`, it appears as if the connection URLs are only printed one on the screen.
The command to print them (`\demo ls`) is not easy to discover.

**Expected behavior**

The help text should be more forthcoming about how to reproduce the connection URLs.

Epic: CRDB-22814

Jira issue: CRDB-22884

### PR DESCRIPTION
**Pull request by knz**
Fixes #94417.
Epic: CRDB-22182.
Requested by @bdarnell 

Prior to this change, the server details and connection information
printed when `cockroach sql` or `cockroach demo` were only printed
once, during startup. It was difficult to re-discover them after that.

This commit adds a new `\info` command to print them again.

Example (`cockroach sql`):
```
root@127.0.0.1:26257/defaultdb> \info
Server version: CockroachDB CCL v23.1.0-alpha....
Cluster ID: 3ab7efff-b9ff-4e01-4d56-02eafe9e6cfe
Organization: Cockroach Demo

Connection string: postgresql://demo:~~~~~~@127.0.0.1:26257/defaultdb?application_name=...
You are connected to database "defaultdb" as user "demo".
```

Example (`cockroach demo`):
```
demo@127.0.0.1:26257/defaultdb> \info
Server version: CockroachDB CCL v23.1.0-alpha....
Cluster ID: 3ab7efff-b9ff-4e01-4d56-02eafe9e6cfe
Organization: Cockroach Demo

You are connected to database "defaultdb" as user "demo".

You are connected to a demo cluster with 1 node(s).
Connection parameters (simplified):
   (webui)    http://127.0.0.1:8080/demologin?password=demo73734&username=demo
   (sql)      postgresql://demo:demo73734@127.0.0.1:26257/defaultdb?sslmode=require&sslrootcert=%2Ftmp%2Fdemo2535355557%2Fca-client-tenant.crt

Use the command '\demo ls' to list nodes and detailed connection parameters to each.
```

The output of `\demo ls` is unchanged and gives access to the detailed
connection parameters; for example:
```
demo@127.0.0.1:26257/defaultdb> \demo ls
node 1:
  Application tenant:
   (webui)    http://127.0.0.1:8080/demologin?password=demo73734&username=demo
   (sql)      postgresql://demo:demo73734@127.0.0.1:26257/defaultdb?sslmode=require&...
   (sql/jdbc) jdbc:postgresql://127.0.0.1:26257/defaultdb?password=demo73734&sslmode=require&...
   (rpc)      127.0.0.1:26257

  System tenant:
   (webui)    http://127.0.0.1:8081/demologin?password=demo73734&username=demo
   (sql)      postgresql://demo:demo73734@127.0.0.1:26258/defaultdb?sslmode=require&...
   (sql/jdbc) jdbc:postgresql://127.0.0.1:26258/defaultdb?password=demo73734&sslmode=require&...
   (sql/unix) postgresql://demo:demo73734@/defaultdb?host=%2Ftmp%2Fdemo2535355557&port=26258
   (rpc)      127.0.0.1:54621
```

Release note (cli change): `cockroach sql` and `cockroach demo` now
support an `\info` client-side command to print the server details
again.

### CODE REVIEW

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @knz, @renatolabs, and @smg260)

___
*[`-- commits` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94421#-NKTmFlV-GYYxOyYcQRk):*
hm, kind of funny that we redact the password here, but then show it anyway 5 lines below. i guess for demo purposes, we don't want redaction? but for any other cluster, all the passwords should be redacted

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @rafiss, @renatolabs, and @smg260)

___
*[`-- commits` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94421#-NKTmFlV-GYYxOyYcQRk):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

hm, kind of funny that we redact the password here, but then show it anyway 5 lines below. i guess for demo purposes, we don't want redaction? but for any other cluster, all the passwords should be redacted
</blockquote></details>

What are you suggesting? the password is already not redacted in the strings below.

**Review by rafiss — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @knz, @renatolabs, and @smg260)

___
*[`-- commits` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94421#-NKTmFlV-GYYxOyYcQRk):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

What are you suggesting? the password is already not redacted in the strings below.
</blockquote></details>

i am suggesting that we have consistent behavior. as a user, if i saw a password redacted here, but not 5 lines below, i would be alarmed that i am being shown something i shouldn't be seeing

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @rafiss, @renatolabs, and @smg260)

___
*[`-- commits` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94421#-NKTmFlV-GYYxOyYcQRk):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

i am suggesting that we have consistent behavior. as a user, if i saw a password redacted here, but not 5 lines below, i would be alarmed that i am being shown something i shouldn't be seeing
</blockquote></details>

Gotcha, thanks. will do

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @rafiss, @renatolabs, and @smg260)

___
*[`-- commits` line 65 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/94421#-NKTmFlV-GYYxOyYcQRk):*
<details><summary><i>Previously, knz (Raphael 'kena' Poss) wrote…</i></summary><blockquote>

Gotcha, thanks. will do
</blockquote></details>

Done.

**Review by rafiss — APPROVED** [review]
> Reviewed 2 of 5 files at r1, 4 of 6 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/94421)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aadityasondhi, @renatolabs, and @smg260)

**Comment by knz** [comment]
TFYR!

bors r=rafiss

**Comment by knz** [comment]
bors r=rafiss

**Comment by knz** [comment]
bors r=rafiss

**Comment by knz** [comment]
flaked on #93601.

bors r=rafiss

**Pull request merged**
