### PR TITLE
storage/concurrency: clean up lockTable datadriven tests

### PR DESCRIPTION
**Pull request by nvb**
This PR contains three small improvements that were suggested in #45062 by @tbg:
- prefix creation directives with "new-"
- rename `done` directive to `dequeue`
- rename `guard-start-waiting` directive to `should-wait`

@sumeerbhola I'll let you decide how you'd like to sequence this with #45124.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Rebased on #45124, so this should be ready for a look now.

**Review by sumeerbhola — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45147#-:-M0PCNJT0EvVsWOhPWLk:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @sumeerbhola and @tbg)

**Comment by nvanbenschoten** [comment]
Bors was canceled even though CI passed...

bors r+

**Pull request merged**
