### PR TITLE
sql: fix cleanup on connection close

### PR DESCRIPTION
**Pull request by andreimatei**
Before this patch, if a pgwire connection was closed while in the
Aborted state, we weren't rolling back the underlying KV txn. Its locks
were never getting released.
I think until recently we only had this bug in the RetryWait state, but
it got worse when we merged the RetryWait and Aborted states.

This patch fixes it by properly handling the case of the connection
closing in the Aborted state by handling the
NonRetriableError(IsCommit:True) event.

Release note: None

### CODE REVIEW

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45835#-:-M2-dzoJ-d58_rEf7i-9:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @andreimatei)

___
*[pkg/sql/conn_fsm.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45835#-M2-dG3H1_-W0IJY-CNb:-M2-dG3H1_-W0IJY-CNc:bnlro13) ([raw file](https://github.com/cockroachdb/cockroach/blob/223ebe9577d0c7f6acc71835ec1e964531c5f260/pkg/sql/conn_fsm.go#L365)):*
> ```Go
> 		},
> 		// ConnExecutor closing.
> 		eventNonRetriableErr{IsCommit: fsm.True}: {
> ```

Do you need to regenerate the FSM diagram? Did it not change?
___
*[pkg/sql/pgwire/conn_test.go, line 648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45835#-M2-dqi8Cb6cWk4lr9mm:-M2-dqi8Cb6cWk4lr9mn:b-gdg3xm) ([raw file](https://github.com/cockroachdb/cockroach/blob/223ebe9577d0c7f6acc71835ec1e964531c5f260/pkg/sql/pgwire/conn_test.go#L648)):*
> ```Go
> 	// We're going to test closing the connection in both the Open and Aborted
> 	// state.
> 	testutils.RunTrueAndFalse(t, "open state", func(t *testing.T, open bool) {
> ```

So before your change, this only succeeded in the `open_state=true` case?
___
*[pkg/sql/pgwire/conn_test.go, line 657 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45835#-M2-e5sR9dsclvD9abph:-M2-e5sR9dsclvD9abpi:b-hw524x) ([raw file](https://github.com/cockroachdb/cockroach/blob/223ebe9577d0c7f6acc71835ec1e964531c5f260/pkg/sql/pgwire/conn_test.go#L657)):*
> ```Go
> 		)
> 		defer cleanupFunc()
> 		db, err := gosql.Open("postgres", pgURL.String())
> ```

Lint is complaining that you have two `db`s in scope.

**Comment by bobvawter** [comment]
[CLA assistant check](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=45835) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.crdb.dev/cockroachdb/cockroach?pullRequest=45835) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.crdb.dev/check/cockroachdb/cockroach?pullRequest=45835) it.</sub>

**Review by andreimatei — COMMENTED** [review]
bors r+

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/45835#-:-M24_w6T8A7PlkzS_2ao:b-ydi9ay)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @nvanbenschoten)

___
*[pkg/sql/conn_fsm.go, line 365 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45835#-M2-dG3H1_-W0IJY-CNb:-M24_PN7-2m8fKSz0OnJ:bocvdjq) ([raw file](https://github.com/cockroachdb/cockroach/blob/223ebe9577d0c7f6acc71835ec1e964531c5f260/pkg/sql/conn_fsm.go#L365)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do you need to regenerate the FSM diagram? Did it not change?
</blockquote></details>

it hadn't but now I've changed the label on this event, and regenerated the diagram. I'm also adding the generated png; we didn't have it before.
___
*[pkg/sql/pgwire/conn_test.go, line 648 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45835#-M2-dqi8Cb6cWk4lr9mm:-M24ZC6HCmmXyvOrk2fF:b-jp377f) ([raw file](https://github.com/cockroachdb/cockroach/blob/223ebe9577d0c7f6acc71835ec1e964531c5f260/pkg/sql/pgwire/conn_test.go#L648)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

So before your change, this only succeeded in the `open_state=true` case?
</blockquote></details>

correct
___
*[pkg/sql/pgwire/conn_test.go, line 657 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/45835#-M2-e5sR9dsclvD9abph:-M24ZL-m8qan5-DRRCB8:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/223ebe9577d0c7f6acc71835ec1e964531c5f260/pkg/sql/pgwire/conn_test.go#L657)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Lint is complaining that you have two `db`s in scope.
</blockquote></details>

done

**Comment by knz** [comment]
@andreimatei this needs to get backported, right?

**Comment by andreimatei** [comment]
No; it looks like I was wrong about what I said in the commit message; we did not use to have this problem in 19.2 in the `RestartWait` wait. The state used to handle the event correctly.
So all the problems were new.

**Pull request merged**
