### PR TITLE
sql: introduce preliminary support for savepoints

### PR DESCRIPTION
**Pull request by knz**
Informs #10735
This implementation corresponds to [compatibility level L1 in the RFC](https://github.com/knz/cockroach/blob/20191014-rfc-savepoints/docs/RFCS/20191014_savepoints.md#layering-of-work).

This PR defines:

- the savepoint name stack-like scoping to implement nesting
- the savepoint lookup and rewind logic
- the separation of logic between restart and "regular" savepoints
- working logic to release and roll back regular savepoints **when no errors have occurred**

What is not supported:

- defining restart savepoints "under" regular savepoints (out of scope according to RFC)
- rolling back to a regular savepoint over an error (this is planned for a later PR)

### CODE REVIEW

**Comment by knz** [comment]
Some experiment about the current DDL behavior:

GOOD:

```
> begin;
  savepoint foo;
  create table t(x int);
  insert into t(x) values (1);
  rollback to savepoint foo;
  commit;
COMMIT

> select * from t;
ERROR: relation "t" does not exist
SQLSTATE: 42P01
```

BAD:

```
> begin; 
  savepoint foo; 
  create table t(x int); 
  rollback to savepoint foo;
ROLLBACK
> insert into t(x) values (1);
INSERT
```

(Bad because the create is rolled back so insert should fail to see the table)

But then:

```
> commit;
COMMIT

> select * from t;
ERROR: relation "t" does not exist
SQLSTATE: 42P01
```

So at least the creation gets eventually rolled back.

**Comment by knz** [comment]
This PR is ready for initial review.

Here are the pieces missing before it can merge:
- PR #44697 with fix needs to be merged
- I need to add a check in the code that there was no DDL "under" a savepoint being rolled back.

However I think the general structure of the code is ready for review and I'd appreciate the early feedback.

**Comment by knz** [comment]
The failed tests show that the restart savepoint is erroneously dropped and becomes unusable after a first `RELEASE SAVEPOINT cockroach_restart` encounters a retry error.

This is is because COMMIT implicitly drops all savepoints, and `RELEASE SAVEPOINT cockroach_restart` reuses the COMMIT code.

I'll split the commit code in two to fix.

**Review by andreimatei — CHANGES_REQUESTED** [review]
There's a lot of distinction in this PR between "restart" and non-restart savepoints. I wonder if there's a reason for this distinction. The only reason I can think of is that in the case of rolling back to `cockroach_restart`, we definitely don't want to clean up intents, whereas for everything else we might want to clean them up. Except with the current implementation, we never clean up any intents (right)? So I wonder if we really need the distinction. Because if we don't, it looks to me like a lot of code would be simpler.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43051#-:-M-k2N_G8FKLB-XWhlX0:b-orzoam)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @nvanbenschoten)

___
*[pkg/sql/conn_executor_savepoints.go, line 260 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43051#-M-k2FyzCXZRJCiPEFyA:-M-k2FyzCXZRJCiPEFyB:bxmf0kz) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fed1bd772a959032c1b4dec837548ff4bcd5b7/pkg/sql/conn_executor_savepoints.go#L260)):*
> ```Go
> // special "restart" semantics.
> func (ex *connExecutor) isRestartSavepoint(savepoint tree.Name) bool {
> 	if ex.sessionData.ForceSavepointRestart {
> ```

Does this `ForceSavepointRestart` session var still serve a purpose?
___
*[pkg/sql/conn_executor_savepoints.go, line 261 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43051#-M-k1o9dBWyLwpkMEq-m:-M-k1o9dBWyLwpkMEq-n:b-ngev5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fed1bd772a959032c1b4dec837548ff4bcd5b7/pkg/sql/conn_executor_savepoints.go#L261)):*
> ```Go
> func (ex *connExecutor) isRestartSavepoint(savepoint tree.Name) bool {
> 	if ex.sessionData.ForceSavepointRestart {
> 		// The session sxetting force_savepoint_restart implies that all
> ```

sxetting

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/sql/conn_executor_savepoints.go, line 260 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43051#-M-k2FyzCXZRJCiPEFyA:-M-vOu8CEkgD-X1AbsrZ:b-dlkpx5) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fed1bd772a959032c1b4dec837548ff4bcd5b7/pkg/sql/conn_executor_savepoints.go#L260)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

Does this `ForceSavepointRestart` session var still serve a purpose?
</blockquote></details>

Unfortunately, yes. There's some ORM out there (presumably, Spring?) where the app cannot customize the identifiers generated for savepoints. With that ORM the only way to implement a retry loop is to make all savepoints retry savepoints.

I did push back against it with Jordan and andy but they would like to decouple the development of a specific adapter for that ORM from the savepoint work. That sounded reasonable to me, so I want to keep that logic here until the separate AppRel work makes progress.
___
*[pkg/sql/conn_executor_savepoints.go, line 261 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43051#-M-k1o9dBWyLwpkMEq-m:-M-vOtrJAK-owxk6b6Me:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fed1bd772a959032c1b4dec837548ff4bcd5b7/pkg/sql/conn_executor_savepoints.go#L261)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

sxetting
</blockquote></details>

Done.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @knz, and @nvanbenschoten)

___
*[pkg/sql/conn_executor_savepoints.go, line 260 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43051#-M-k2FyzCXZRJCiPEFyA:-M-vQ5PABS38130qVldN:bs1npj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fed1bd772a959032c1b4dec837548ff4bcd5b7/pkg/sql/conn_executor_savepoints.go#L260)):*
<details><summary><i>Previously, knz (kena) wrote…</i></summary><blockquote>

Unfortunately, yes. There's some ORM out there (presumably, Spring?) where the app cannot customize the identifiers generated for savepoints. With that ORM the only way to implement a retry loop is to make all savepoints retry savepoints.

I did push back against it with Jordan and andy but they would like to decouple the development of a specific adapter for that ORM from the savepoint work. That sounded reasonable to me, so I want to keep that logic here until the separate AppRel work makes progress.
</blockquote></details>

I understand but I'm still hoping that the special treatment of `cockroach_restart` can also go away :)

**Review by knz — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43051)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

___
*[pkg/sql/conn_executor_savepoints.go, line 260 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/43051#-M-k2FyzCXZRJCiPEFyA:-M-vQejoApul-i2lI_r4:b-w18ypq) ([raw file](https://github.com/cockroachdb/cockroach/blob/84fed1bd772a959032c1b4dec837548ff4bcd5b7/pkg/sql/conn_executor_savepoints.go#L260)):*
<details><summary><i>Previously, andreimatei (Andrei Matei) wrote…</i></summary><blockquote>

I understand but I'm still hoping that the special treatment of `cockroach_restart` can also go away :)
</blockquote></details>

I hope so too. But baby steps. I want to get to that L1 step in the RFC then also L2 (error recovery) and then we'll talk about this again.

**Comment by knz** [comment]
The DDL blocking logic is now ready.
I have added numerous tests and transferred a few thing from logic tests to the new datadriven-based TestSavepoints.

RFAL. Note that I plan to implement error recovery in a subsequent PR.

**Review by andreimatei — COMMENTED** [review]
Only if you're curious, I've  been trying my hand over here: https://github.com/andreimatei/cockroach/commits/pr/43051
I think the code is getting there, but it's not ready - I seem to have broken something in one of the new tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/43051#-:-M1DBOKQCxtNC7kp1AlI:ba9koty)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei and @nvanbenschoten)

**Comment by knz** [comment]
subsumed by #45566

**Pull request closed without merging**
