### PR TITLE
build: remove uses of `bindata`

### LINKED ISSUE #111520: build: remove references to `bindata`
This is deprecated in `rules_go` and there's no need for it anyway since `go:embed` supports the same stuff.

Epic: CRDB-8308

Jira issue: CRDB-31944

### PR DESCRIPTION
**Pull request by rickystewart**
This is deprecated in `rules_go`, and `go:embed` has the same functionality.

Closes #111520.
Epic: CRDB-8308
Release note: None

### CODE REVIEW

**Review by rail — APPROVED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111588)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @herkolategan and @smg260)

**Review by srosenberg — APPROVED** [review]

**Comment by rickystewart** [comment]
bors r=rail,srosenberg

**Comment by yuzefovich** [comment]
After pulling in this change, GoLand refuses to compile for me
```
# github.com/cockroachdb/cockroach/pkg/security/securitytest
../../../../security/securitytest/securitytest.go:133:6: Asset redeclared in this block
	../../../../security/securitytest/embedded.go:662:6: other declaration of Asset
```
I did `./dev gen go` and cleared the GoLand cache to no help. I'm using Go 1.20.8 and GoLand 2023.2.2.

**Comment by rickystewart** [comment]
@yuzefovich `rm pkg/security/securitytest/embedded.go`

`git clean pkg` would get it but you'd have to re-generate code.

**Comment by yuzefovich** [comment]
Oh, ok, thanks. I was surprised that this file didn't show up us untracked in `git status`.

**Pull request merged**
