### PR TITLE
cherrypic: build: disable RocksDB assertions, except on race builds

### LINKED ISSUE #15604: engine: TestConcurrentBatch is flaky (locally)
`TestConcurrentBatch` has recently (in the last couple of weeks, I think) become flaky on my laptop. There are a bunch of slow batches, each taking longer than the last (this is a partial log):

```
W170502 12:50:40.391933 293 storage/engine/rocksdb.go:1220  batch [355017/4194314/0] commit took 12.411354136s (>500ms):
goroutine 293 [running]:
runtime/debug.Stack(0x4abc360, 0x4ff5a40, 0xc420014e80)
	/opt/local/lib/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc4203e0480, 0x4030300, 0x4be0868, 0xc42002cc00)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1220 +0x14d
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc4203e0480, 0xc406591100, 0x4670001, 0xc42041bfc8)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1189 +0x704
github.com/cockroachdb/cockroach/pkg/storage/engine.TestConcurrentBatch.func2(0xc420346300, 0x4ffa7a0, 0xc4203e0480)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb_test.go:391 +0x36
created by github.com/cockroachdb/cockroach/pkg/storage/engine.TestConcurrentBatch
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb_test.go:392 +0x75c
W170502 12:50:41.449260 305 storage/engine/rocksdb.go:1220  batch [355017/4194314/0] commit took 13.480834217s (>500ms):
goroutine 305 [running]:
runtime/debug.Stack(0x4abc360, 0x4ff5a40, 0xc420014e80)
	/opt/local/lib/go/src/runtime/debug/stack.go:24 +0x79
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).commitInternal(0xc4200b8900, 0x0, 0x0, 0x0)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1220 +0x14d
github.com/cockroachdb/cockroach/pkg/storage/engine.(*rocksDBBatch).Commit(0xc4200b8900, 0x0, 0x0, 0x0)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb.go:1189 +0x704
github.com/cockroachdb/cockroach/pkg/storage/engine.TestConcurrentBatch.func2(0xc420346300, 0x4ffa7a0, 0xc4200b8900)
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb_test.go:391 +0x36
created by github.com/cockroachdb/cockroach/pkg/storage/engine.TestConcurrentBatch
	/Users/bdarnell/work/cockroach/src/github.com/cockroachdb/cockroach/pkg/storage/engine/rocksdb_test.go:392 +0x75c
I170502 12:50:41.449954 211 storage/engine/rocksdb.go:447  closing rocksdb instance at "/var/folders/xw/y575gcfd7wx30kskwzd6p2qr0000gn/T/TestConcurrentBatch351385987"
--- FAIL: TestConcurrentBatch (16.33s)
	rocksdb_test.go:416: write took 13.4s
```

When the test passes, it takes about 4 seconds on this laptop (a macbook pro, with filevault enabled). 

I think this is probably a matter of other stuff going on on the machine. It fails a large fraction of the time when I run `make test` and there is stuff to rebuild, but it passes reliably when run in isolation or when there is no rebuilding going on. So it's not really a problem with the test per se, but I'd like to see it be more robust against concurrent activity (or for us to figure out a way for `make test` to not cause so much concurrent I/O)

### PR DESCRIPTION
**Pull request by mberhault**
In the transition to the new Make-based build system for C dependencies
(4d72e12), RocksDB assertions were inadvertently enabled for all builds.
Restore the old behavior, which only enabled assertions for race builds
(cockroachdb/c-rocksdb#27).

Fixes #15604.

### CODE REVIEW

**Review by benesch — APPROVED** [review]
LGTM! Sorry you had to take care of this—hope the conflicts weren't too hairy.

**Comment by mberhault** [comment]
nah, just had to drop the stdmalloc stuff. no biggie.
I'll merge this, which will break the bleeding edge `release-1.0` builds, but I'll cherrypick Tamir's fix right after.

**Comment by tamird** [comment]
I would slightly prefer that you add my fix into this PR, but your call.

**Comment by mberhault** [comment]
I thought about it but I prefer to keep the cherry-picks as PR-related as possible. I don't think we need to worry too much about people jumping to this sha either.

**Pull request merged**
