### PR TITLE
docs/tech-notes: update "Statement Execution" and "Building execution plans"  sections of "Life of a query"

### PR DESCRIPTION
**Pull request by mneverov**
docs/tech-notes: update "Statement Execution" and "Building execution plans"  sections of "Life of a query"

Release note: None

### CODE REVIEW

**Review by RaduBerinde — APPROVED** [review]
:lgtm: Thanks for the updates!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-:-MTYrNnV2lW50cbCb194:bi6r1b9)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mneverov)

___
*[docs/tech-notes/life_of_a_query.md, line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTYqdEnD0Jk0Gt6l9fn:-MTYqdEoB_xwlIpWyAAP:b3ufrza) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad79684a896d5ad42325a4395b01edbe1d582552/docs/tech-notes/life_of_a_query.md#L189)):*
> ```Markdown
> children whose data it consumes).
>                                 
> SQL query planning and optimizations are described in details in the 
> ```

[nit] in detail
___
*[docs/tech-notes/life_of_a_query.md, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTYqhVtA6iJemWPR39w:-MTYqhVtA6iJemWPR39x:b35sarw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad79684a896d5ad42325a4395b01edbe1d582552/docs/tech-notes/life_of_a_query.md#L192)):*
> ```Markdown
> documentation for the [`opt` package](https://github.com/cockroachdb/cockroach/blob/9969862335cf501c1aa67a4aaf018ad5dc8e85e8/pkg/sql/opt/doc.go). 
> 
> In the meantime, the plan `Builder` [looks at the type of the
> ```

remove "in the meantime"
say the `optbuilder` instead of `Builder` (we have an execbuilder.Builder too)
___
*[docs/tech-notes/life_of_a_query.md, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTYr-4AB9hIm7poI0UZ:-MTYr-4AB9hIm7poI0U_:b-5k0j7w) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad79684a896d5ad42325a4395b01edbe1d582552/docs/tech-notes/life_of_a_query.md#L202)):*
> ```Markdown
> [`builder.buildScan()`](https://github.com/cockroachdb/cockroach/blob/9969862335cf501c1aa67a4aaf018ad5dc8e85e8/pkg/sql/opt/optbuilder/select.go#L114))
> to scan a table, a `WHERE` clause is transformed into an [`memo.FilterExpr`](https://github.com/cockroachdb/cockroach/blob/9969862335cf501c1aa67a4aaf018ad5dc8e85e8/pkg/sql/opt/optbuilder/select.go#L1126),
> an `ORDER BY` clause is [ordering physical property](https://github.com/cockroachdb/cockroach/blob/9969862335cf501c1aa67a4aaf018ad5dc8e85e8/pkg/sql/opt/optbuilder/orderby.go#L65),
> ```

[nit] is turned into
___
*[docs/tech-notes/life_of_a_query.md, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTYr4Qg5TbPjDZnIfcH:-MTYr4Qg5TbPjDZnIfcI:bqs6yvo) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad79684a896d5ad42325a4395b01edbe1d582552/docs/tech-notes/life_of_a_query.md#L208)):*
> ```Markdown
> 
> Finally, the execution plan is simplified, [optimized](https://github.com/cockroachdb/cockroach/blob/5ee1f52f0eef1eeceddde16aad5002dc31ca08cb/pkg/sql/opt/xform/optimizer.go#L198), and
> a physical plan is built.
> ```

I'd add a bit more detail about how the physical plan is built: the `execbuilder` generates execution operators through an `exec.Factory` (implemented by `sql/opt_factory.go`)

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60568)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @RaduBerinde)

___
*[docs/tech-notes/life_of_a_query.md, line 189 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTYqdEnD0Jk0Gt6l9fn:-MTZZZruDx5lX_AqNk2Y:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad79684a896d5ad42325a4395b01edbe1d582552/docs/tech-notes/life_of_a_query.md#L189)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] in detail
</blockquote></details>

done
___
*[docs/tech-notes/life_of_a_query.md, line 192 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTYqhVtA6iJemWPR39w:-MTZZ_aU5blHmVZk1Rkx:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad79684a896d5ad42325a4395b01edbe1d582552/docs/tech-notes/life_of_a_query.md#L192)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

remove "in the meantime"
say the `optbuilder` instead of `Builder` (we have an execbuilder.Builder too)

</blockquote></details>

done
___
*[docs/tech-notes/life_of_a_query.md, line 202 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTYr-4AB9hIm7poI0UZ:-MTZZaeMBXSfG0Qq2Ctp:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad79684a896d5ad42325a4395b01edbe1d582552/docs/tech-notes/life_of_a_query.md#L202)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

[nit] is turned into
</blockquote></details>

done
___
*[docs/tech-notes/life_of_a_query.md, line 208 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTYr4Qg5TbPjDZnIfcH:-MTbO3O2C0L6gQ0jrZk_:bddqwq6) ([raw file](https://github.com/cockroachdb/cockroach/blob/ad79684a896d5ad42325a4395b01edbe1d582552/docs/tech-notes/life_of_a_query.md#L208)):*
<details><summary><i>Previously, RaduBerinde wrote…</i></summary><blockquote>

I'd add a bit more detail about how the physical plan is built: the `execbuilder` generates execution operators through an `exec.Factory` (implemented by `sql/opt_factory.go`)
</blockquote></details>

Added some info about physical plan building.

**Review by RaduBerinde — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-:-MTfjNJ17MZkvmQ1yW8l:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by yuzefovich — COMMENTED** [review]
Thanks a lot for the update! I have a couple of nits.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-:-MTidsrY0ppTxs01EgSV:byphjp5)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @mneverov)

___
*[docs/tech-notes/life_of_a_query.md, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTicnRaEFhW1iJFFPB8:-MTicnRaEFhW1iJFFPB9:b-a7amrj) ([raw file](https://github.com/cockroachdb/cockroach/blob/669beedd2e0d183ede2a5b33f4ca8942024afd4a/docs/tech-notes/life_of_a_query.md#L157)):*
> ```Markdown
> documentation](https://www.cockroachlabs.com/docs/stable/transactions.html#client-side-intervention).
> The statement execution code path continues inside the 
> [`callback`](https://github.com/cockroachdb/cockroach/blob/9969862335cf501c1aa67a4aaf018ad5dc8e85e8/pkg/sql/conn_executor_prepare.go#L201), 
> ```

nit: I'm confused about this sentence and the link only adds to my confusion. I think I'd remove the sentence entirely.

Probably, originally "callback" referred to https://github.com/cockroachdb/cockroach/blob/33c18ad1bcdb37ed6ed428b7527148977a8c566a/pkg/sql/executor.go#L604, and I'm not sure what the equivalent to it now is, possibly it became obsolete / was refactored.
___
*[docs/tech-notes/life_of_a_query.md, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTicQKv6BCdpM65Kcxp:-MTicQKv6BCdpM65Kcxq:b-ei81wv) ([raw file](https://github.com/cockroachdb/cockroach/blob/669beedd2e0d183ede2a5b33f4ca8942024afd4a/docs/tech-notes/life_of_a_query.md#L188)):*
> ```Markdown
> right`](https://github.com/cockroachdb/cockroach/blob/33c18ad1bcdb37ed6ed428b7527148977a8c566a/pkg/sql/join.go#L125)
> children whose data it consumes).
>                                 
> ```

super nit: something is off here (as viewing from Reviewable), seems like unnecessary space characters?

**Review by mneverov — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60568)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[docs/tech-notes/life_of_a_query.md, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTicnRaEFhW1iJFFPB8:-MTkx_9tAt3EiNgI24kl:bivkzoe) ([raw file](https://github.com/cockroachdb/cockroach/blob/669beedd2e0d183ede2a5b33f4ca8942024afd4a/docs/tech-notes/life_of_a_query.md#L157)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: I'm confused about this sentence and the link only adds to my confusion. I think I'd remove the sentence entirely.

Probably, originally "callback" referred to https://github.com/cockroachdb/cockroach/blob/33c18ad1bcdb37ed6ed428b7527148977a8c566a/pkg/sql/executor.go#L604, and I'm not sure what the equivalent to it now is, possibly it became obsolete / was refactored.
</blockquote></details>

yes, you're right. The previous statement related to `runTxnAttempt(...)` in the callback that did run the statement. The closure I mentioned just creates a memo for a prepared statement, but actual execution is don in `dispatchToExecutionEngine()`.
Updated the PR.
___
*[docs/tech-notes/life_of_a_query.md, line 188 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTicQKv6BCdpM65Kcxp:-MTkyga52dcYnHeSO9Np:b3vkw2p) ([raw file](https://github.com/cockroachdb/cockroach/blob/669beedd2e0d183ede2a5b33f4ca8942024afd4a/docs/tech-notes/life_of_a_query.md#L188)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

super nit: something is off here (as viewing from Reviewable), seems like unnecessary space characters?
</blockquote></details>

fixed, thx

**Review by yuzefovich — APPROVED** [review]
Awesome, thanks! :lgtm:

bors r=raduberinde,yuzefovich

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-:-MTlJa598Ur3GqNn8Eaz:b1z1t1y)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @mneverov)

___
*[docs/tech-notes/life_of_a_query.md, line 157 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/60568#-MTicnRaEFhW1iJFFPB8:-MTlJZHIEH16wr0zMLLJ:b-ucfknh) ([raw file](https://github.com/cockroachdb/cockroach/blob/669beedd2e0d183ede2a5b33f4ca8942024afd4a/docs/tech-notes/life_of_a_query.md#L157)):*
<details><summary><i>Previously, mneverov (Max Neverov) wrote…</i></summary><blockquote>

yes, you're right. The previous statement related to `runTxnAttempt(...)` in the callback that did run the statement. The closure I mentioned just creates a memo for a prepared statement, but actual execution is don in `dispatchToExecutionEngine()`.
Updated the PR.
</blockquote></details>

Thanks!

**Pull request merged**
