### PR TITLE
sql: panic with assertion errors, not raw strings

### PR DESCRIPTION
**Pull request by jordanlewis**
Panicking with raw strings will cause the strings to be redacted.

Release note: None

### CODE REVIEW

**Review by knz — APPROVED** [review]
yay :tada: 

thanks

**Comment by RaduBerinde** [comment]
Are the changes in optgen necessary? They're not really assertion errors, more like "compile failed" errors.

**Comment by jordanlewis** [comment]
Up to you, I just did a search and replace. I can roll them back

**Comment by RaduBerinde** [comment]
I just tried it and it's not much of a difference in the output, ok with me either way.

**Comment by jordanlewis** [comment]
I rolled back before your comment, I'll just merge as is. Thanks!

bors r+

**Pull request merged**
