### PR TITLE
util/log: disable usage of proto-format logs

### LINKED ISSUE #4449: util/log: remove proto-encoded logs
Use normal textual logs instead. We're not displaying debug logs in the admin UI anymore, nor do I think we want to in the future. The proto-encoded logs add a hurdle to debugging since they must be viewed with `cockroach log`.

@spencerkimball I imagine you have an opinion about this.

### PR DESCRIPTION
**Pull request by petermattis**
The code to output proto-format logs is still present, but the
logging.protoFormat field defaults to false and there is no means provided
to change it.

Fixes #4449.

[Review on Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/4545)

### CODE REVIEW

**Comment by petermattis** [comment]
I could be convinced to keep around some of the stuff removed in the second commit, though hide the functionality when text-logs are being used. My preference is to remove all of this code and the code in `util/log` for proto-format logs. Structured logs are an unobtainable holy grail. I think it would be better to invest effort in making sure our logs our easily ingestible by logstash/spunk/other-log-analysis-tool.

**Comment by tschottdorf** [comment]
Generally in favor of removing everything that isn't needed.
We don't want to keep the UI functionality to look at the logs in some way?

**Comment by petermattis** [comment]
Oh yeah, forgot to CC @maxlang that we should remove/disable the UI functionality as well. It isn't hooked up to the primary UI at this point anyways (you need to manually type in URLs to reach it).

**Comment by tschottdorf** [comment]
Sorry, my real question was: Don't we want to keep some way for users to glance over logs from the UI? I remember not really being strongly in favor when we made that decision, but whoever was in favor then should probably speak out now. And at the end of the day, it could be a useful feature.

**Comment by bdarnell** [comment]
The question of whether we expose logs in the UI is orthogonal to whether those logs are structured or plain text. Dropping the proto output format is fine with me but I think that exposing the logs in the UI could still be a good idea - if we don't, it's very unlikely that anyone but us will ever look at the logs. Maybe that's OK; we shouldn't be relying on users looking at the logs for anything routine, but during beta it seems likely that logs will contain helpful information and if users have to go outside the system and scp logs manually that's a big barrier. Since we already have this written I'd be in favor of keeping the status server code to make logs accessible.

**Comment by petermattis** [comment]
The admin UI has code for displaying logs from individual servers, but it is not currently hooked up. You have to manually construct the URLs. Additionally, I believe this part of the UI is unfinished (i.e. not polished). The `/_status/log*` endpoints currently rely on the proto log format. [`FetchEntriesFromFiles`](https://github.com/cockroachdb/cockroach/blob/master/util/log/file.go#L310) fetches log entries within a date range. We could certainly implement this on top of the text logs, though doing so is work I'd rather not do right now. 

I don't think retrieving logs from servers will be too onerous for beta users. Perhaps I'm wrong about that. In my opinion, the current half-finished state of this functionality argues for disabling it in the short term.

**Comment by maxlang** [comment]
You can get to the logs from the nodes page, but some of the styles are messed up. Currently you can only view it for one node at a time, and while it's possible to filter/search the results, it'd probably be easier/faster to just pull everything into a log analysis tool as mentioned.

Here's a screenshot (with one offending line of CSS changed)
screen shot 2016-02-22 at 2 54 28 pm

I'm fine stripping out the UI code for now, as I don't think it's very useful as is - you're limited to searching for log lines that match a regex, but can't see any context, easily copy/paste, etc,

To address Ben's concern we could provide a way to download log files through the UI.

**Comment by petermattis** [comment]
@maxlang Where is that accessible from the UI?!? I looked and looked and didn't see anything.

**Comment by maxlang** [comment]
@petermattis it's there if you scroll alll the way to the right in the nodes table. Honestly, not very discoverable and we already had someone complain about horizontal scrolling.
screen shot 2016-02-22 at 3 31 36 pm

**Comment by petermattis** [comment]
This is ready for another look. I've completed removed support for proto-format logs and reworked how the structured logs operate. On the plus side, I fixed `EntryDecoder` to parse text logs into separate log entries enabling the existing logs UI on the admin dashboard to continue working. I need to fix the `TestEntryDecoder` failure on circleci (timezone issue), but other than that I think this is good to go.

@maxlang The `log.Entry` structure has changed and certain fields will no longer be populated. Once this goes in we can simplify the logs UI to remove the `{Node,Store,Range}ID`, `Key` and `Method` columns.

**Comment by maxlang** [comment]
Sweet!

**Comment by bdarnell** [comment]
LGTM

---

Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[util/log/clog.go, line 530 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4545#-KBKFxeJnJsbtUtU43rY:-KBKFxeJnJsbtUtU43rZ:-1337870284) ([raw file](https://github.com/cockroachdb/cockroach/blob/723805f0743e4f7276a09d07b3ae045e8b0e6214/util/log/clog.go#L530)):*
I liked the extra space here; it made the logs more scannable when color was not enabled (which is going to be the norm now that we're logging to files instead of stderr by default). 

If this space is going away the comment a few lines up should also be removed (I'm not sure why the color-reset code was placed in between these two spaces).

---

*[util/log/clog.go, line 923 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4545#-KBKFh2fSFxdWOg17SF6:-KBKFh2fSFxdWOg17SF7:-319425951) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63d1bca62bd32eccac626f85411b20205e6c858/util/log/clog.go#L923)):*
s/mmdd/yymmdd/

---

*[util/log/clog_test.go, line 137 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4545#-KBKCVolh_RyieRZrbEB:-KBKCVolh_RyieRZrbEC:-1641251175) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63d1bca62bd32eccac626f85411b20205e6c858/util/log/clog_test.go#L137)):*
Can we also have a test that calls `formatHeader` directly and verifies its output is parseable in addition to these hard-coded examples?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4545#-:-KBKJPqOOUe69NVnmOd5:676834233)*

**Comment by petermattis** [comment]
Review status: 0 of 15 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[util/log/clog.go, line 530 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4545#-KBKFxeJnJsbtUtU43rY:-KBKMDabjPoAzfcO46MO:-735589680) ([raw file](https://github.com/cockroachdb/cockroach/blob/723805f0743e4f7276a09d07b3ae045e8b0e6214/util/log/clog.go#L530)):*
I didn't know the space was intentional. I'll re-add it.

---

*[util/log/clog.go, line 923 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4545#-KBKFh2fSFxdWOg17SF6:-KBKMGhE2UDQCuR1u_Uc:-499146009) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63d1bca62bd32eccac626f85411b20205e6c858/util/log/clog.go#L923)):*
Done.

---

*[util/log/clog_test.go, line 137 \[r4\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/4545#-KBKCVolh_RyieRZrbEB:-KBKMUlutIcKZ-FHynEO:-979730768) ([raw file](https://github.com/cockroachdb/cockroach/blob/d63d1bca62bd32eccac626f85411b20205e6c858/util/log/clog_test.go#L137)):*
I'm going to change this test so that it uses `formatHeader`. Seems a better approach than manually constructing a set of log messages

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/cockroachdb/cockroach/4545)*

**Comment by petermattis** [comment]
@tschottdorf Care to add anything?

**Pull request merged**
