### PR TITLE
server: remove unnecessary log message

### LINKED ISSUE #118500: multitenant: noisy log message when tenant is not available
When draining nodes on the DRT cluster we see this message in the logs printed hundreds of times:

```
E240130 16:45:26.420936 1374946742 1@server/server_sql.go:1927 ⋮ [T1,Vsystem,n1,client=‹10.142.1.104:53634›] 1353899  serving SQL client conn: no server for tenant ‹"application"›
W240130 16:45:26.421426 1374946688 server/server_controller_sql.go:79 ⋮ [T1,Vsystem,n1,client=‹10.142.1.104:53612›] 1353900  unable to find server for tenant ‹"application"›: no server for tenant ‹"application"›
```

Can we put this behind a `log.everyN`?

Jira issue: CRDB-35762

### PR DESCRIPTION
**Pull request by stevendanna**
This error is returned to the connecting client so additionally logging it server side is likely unnecessary.

Fixes #118500

Release note: None

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
This change looks good.  Do we also want to remove [this](https://github.com/cockroachdb/cockroach/blob/master/pkg/server/server_sql.go#L1927) log entry?

**Comment by stevendanna** [comment]
Sorry I lost track of this one. This should eliminate both entries that you see in the logs when the tenant doesn't exist.

**Review by ajstorm — APPROVED** [review]
LGTM

**Comment by stevendanna** [comment]
bors r=ajstorm

**Pull request merged**
