### PR TITLE
*: fix tests when DisallowSeparatedIntents=false

### PR DESCRIPTION
**Pull request by sumeerbhola**
- storage: fix all storage tests
- storage: prevent intentIter from stepping out of the lock table.
  It was throwing an error on finding /Local/Store/clusterVersion
  because callers were iterating forward without an upper bound.
- storage: fix engine iter bounds bug in pebbleBatch
- kv: fix TestRangeStatsComputation to account for TxnDidNotUpdateMeta
- keys: pretty print lock table keys
- rditer: fix lock table ranges to be non-overlapping
- kvserver: fix TestStoreRangeMergeRaftSnapshot to handle separated
  locks. The SST counts are different when we have separated locks.

We are leaving DisallowSeparatedIntents=true for now. This
is just preparatory work before we can test with both settings.

Release note: None

### CODE REVIEW

**Comment by sumeerbhola** [comment]
@nvanbenschoten Ignore this. The CI was not running tests, so seeing if adding a reviewer changes that.

**Review by sumeerbhola — COMMENTED** [review]
@nvanbenschoten All the tests now pass when `DisallowSeparatedIntents=false`, so I've removed that one commit and kept only the fixes. This is ready for a real review.

After this PR I will try with `DisallowSeparatedIntents=false` and `enabledSeparatedIntents=true`.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57264#-:-MNeBq2L5gW9ZfTYXBfE:b-19e99b)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @nvanbenschoten)

**Review by itsbilal — APPROVED** [review]
:lgtm: 

> Reviewed 15 of 15 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57264#-:-MO3UkeO-rQmeuhPMwnN:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nvanbenschoten and @petermattis)

**Review by nvb — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, 3 of 3 files at r2, 1 of 1 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, 2 of 2 files at r6, 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57264#-:-MO8GyNmAoaLBpwFpcSS:bnfp4nl)* status: :shipit: complete! 2 of 0 LGTMs obtained (waiting on @petermattis and @sumeerbhola)

___
*[pkg/keys/keys.go, line 411 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57264#-MO8Ee_d-JcII84M1wDu:-MO8Ee_e455F9A8TsuJe:b37eqjj) ([raw file](https://github.com/cockroachdb/cockroach/blob/09f21755fb4f589614b861f487b010dc83e284ea/pkg/keys/keys.go#L411)):*
> ```Go
> }
> 
> // LockTableSingleKeyStart is the inclusive start key of the key range
> ```

Do these belong in `constants.go`?
___
*[pkg/keys/printer.go, line 545 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57264#-MO8FoI88DEa-yBNVN3J:-MO8FoI88DEa-yBNVN3K:b-g4qrpy) ([raw file](https://github.com/cockroachdb/cockroach/blob/674cbc36ccbb17605279c97e11f17bcba9d4a8cd/pkg/keys/printer.go#L545)):*
> ```Go
> 		return buf.String()
> 	}
> 	buf.WriteString(lockTablePrintLockedKey(valDirs, lockedKey, true))
> ```

I believe some of the other nested keys use `fmt.Sprintf` to pass through the `roachpb.Key.String` instead of calling `prettyPrintInternal`, but this also seems fine.
___
*[pkg/storage/intent_reader_writer.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57264#-MO8CinABeltmXREH6Qq:-MO8CinABeltmXREH6Qr:ba4kant) ([raw file](https://github.com/cockroachdb/cockroach/blob/578761bf2f8ab396f1ead7d6bbfe52a2572310e5/pkg/storage/intent_reader_writer.go#L224)):*
> ```Go
> 	if iterKind == MVCCKeyIterKind || !opts.MinTimestampHint.IsEmpty() ||
> 		!opts.MaxTimestampHint.IsEmpty() {
> 		// This iterator does not need to see separated intents (see the interface
> ```

Should we allow `iterKind != MVCCKeyIterKind` when either of the timestamp hints are provided? This seems kind of subtle.

**Review by sumeerbhola — COMMENTED** [review]
TFTRs!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57264#-:-MO9X4JhBh7DASmXthek:bz5mair)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @itsbilal, @nvanbenschoten, and @petermattis)

___
*[pkg/keys/keys.go, line 411 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57264#-MO8Ee_d-JcII84M1wDu:-MO9TqSX8MVEJE5fY-sU:bb6un1j) ([raw file](https://github.com/cockroachdb/cockroach/blob/09f21755fb4f589614b861f487b010dc83e284ea/pkg/keys/keys.go#L411)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Do these belong in `constants.go`?
</blockquote></details>

Done
___
*[pkg/keys/printer.go, line 545 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/57264#-MO8FoI88DEa-yBNVN3J:-MO9Uses1GdUgxby9O8h:bl6tp3n) ([raw file](https://github.com/cockroachdb/cockroach/blob/674cbc36ccbb17605279c97e11f17bcba9d4a8cd/pkg/keys/printer.go#L545)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

I believe some of the other nested keys use `fmt.Sprintf` to pass through the `roachpb.Key.String` instead of calling `prettyPrintInternal`, but this also seems fine.
</blockquote></details>

The ones in this file seem to be using `[]byte`. I tried your suggestion and it does work for the test. I've left this for now, in case `valDirs` is useful.
___
*[pkg/storage/intent_reader_writer.go, line 224 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/57264#-MO8CinABeltmXREH6Qq:-MO9W5pz23S_ln6HBo0J:b-b5s3k2) ([raw file](https://github.com/cockroachdb/cockroach/blob/578761bf2f8ab396f1ead7d6bbfe52a2572310e5/pkg/storage/intent_reader_writer.go#L224)):*
<details><summary><i>Previously, nvanbenschoten (Nathan VanBenschoten) wrote…</i></summary><blockquote>

Should we allow `iterKind != MVCCKeyIterKind` when either of the timestamp hints are provided? This seems kind of subtle.
</blockquote></details>

Good point. I've tightened the error checking so that asking for `MVCCKeyAndIntentsIterKind` when specifying timestamp hints causes a `panic`.

**Pull request merged**
