### PR TITLE
kvserver: slow_replication_threshold := 1m

### LINKED ISSUE #74705: kvserver: default replica circuit breakers to on
Touches #33007.

As of #71806, per-replica circuit breakers are off by default. Once they are in
a state suitable for production use, the default should be flipped to "on", and
this must happen before the 22.1 release branch is cut.

This should be accommodated by additional testing and by a review of all issues
linked to #33007 to determine which one are required before the flip.

The commit that defaults breakers to on should also add the release note, which has intentionally been held back.

Jira issue: CRDB-12220

### PR DESCRIPTION
**Pull request by tbg**
Fixes #74705.

Release note: None

### CODE REVIEW

**Comment by tbg** [comment]
Running roachtest nightly off this branch to see if anything obvious transpires. https://teamcity.cockroachdb.com/viewQueued.html?itemId=4338356&tab=queuedBuildOverviewTab

**Comment by tbg** [comment]
There's definitely some fallout. Even if I remove all of the `(lost quorum: true)` hits (where some nodes are non-live, so the breakers firing has to be fair game), I'm left with quite a bit of fallout across multiple tests:

https://gist.github.com/tbg/e122a96d29aa6cf91adaeadcbffebab7

It makes sense for there to be some fallout. We tend to quite overload clusters in some of the more heavyweight tests, and now any proposal that takes >15s to replicate can trigger the breaker. The clients at the other end of the error are not going to retry the breaker errors, so jobs and workloads fail that would previously just have waited for a long time.

Without having investigated some of these failures in more depth (which I'll do) I wonder if perhaps outright tripping the breaker on a slow request is to aggressive. Perhaps instead we should "tickle" the breaker, letting the probe run. And the probe then determines whether to trip the breaker. I don't expect that to solve the problems here (as replication serializes all commands, if a command is slow then a probe on top of it will also be slow) but it is perhaps the "right" way to set things up to give fewer false positives in general, especially when we're looking to add triggers as discussed in https://github.com/cockroachdb/cockroach/issues/74712.

In the interim I'll experiment with a 2 or even 5 minute breaker timeout. I'd rather get them turned on in some capacity than to get sucked into an endless string of investigations into why proposals are taking longer than X in situation Y. It looks like I was way too optimistic with the initial choice of 15s.

**Comment by tbg** [comment]
5m timeout run just kicked off here: https://teamcity.cockroachdb.com/viewLog.html?buildId=4346831&

**Comment by tbg** [comment]
Doing another run, this time again with the aggressive 15s timeout, and #76673 cherry-picked, just to see what shakes out.
I'm only running import/tpcc/warehouses=4000/geo and tpcc/multiregion/survive=region/chaos=true, each three times.

**Comment by tbg** [comment]
Ok that didn't work, https://github.com/cockroachdb/cockroach/pull/76881. Need to try this again but for now rebasing and holding off.

**Comment by erikgrinaker** [comment]
What's with the CI failure, looks like the run timed out after 90 minutes? Should probably look into that.

**Comment by tbg** [comment]
Good question. From the artifacts I can see that the last output was this:

> ?       github.com/cockroachdb/cockroach/pkg/sql/lexbase/allkeywords    [no test files]

at 19:56:19, then nothing until the test gets killed 40 minutes later. But we can see that what's running is TestLogic:

image

(see the `logTestLogic` directory) and its last timestamps match up with when the test was killed:

image

Unfortunately there's nothing else in these logs. It's just lots of under-replicated ranges. No slow requests (and thus also circuit breakers shouldn't be involved at all). The log file starts at 19:48:07.

So it looks like TestLogic timed out, albeit without leaving any trace as to what it was even doing at the time. 😢 
Maybe something for @cockroachdb/sql-queries to look into improving.

I'm going to restart CI and see what I get.

**Comment by tbg** [comment]
Passed now. @erikgrinaker going to wait for your sign-off.

**Review by erikgrinaker — APPROVED** [review]

**Comment by tbg** [comment]
bors r=erikgrinaker

**Comment by tbg** [comment]
bors r=erikgrinaker

The LogicTest timeouts were discussed [here](https://cockroachlabs.slack.com/archives/C01RX2G8LT1/p1647893271114979?thread_ts=1647876496.669969&cid=C01RX2G8LT1) and seem to be a general problem right now.

**Pull request merged**
