### PR TITLE
RFC: optimize the handling of row Datums in memory.

### PR DESCRIPTION
**Pull request by knz**
This is a dump of notes form a brainstorming session with Radu last weekend.

@RaduBerinde can you check I didn't miss anything

[ci skip]

---

This change is [Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/8015)

### CODE REVIEW

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/row_mem.md, line 63 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015#-KNku-hF3gA0dAkvXGw2:-KNku-hF3gA0dAkvXGw3:-1754913749) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fe0dad3a49dafee3a6d0f36b8cbd5ba7e252ab/docs/RFCS/row_mem.md#L63)):*
> ```Markdown
> ```
> 
> Saving: 30% reduction in memory usage, possibly also from fewer allocations.
> ```

s/from//

---

*[docs/RFCS/row_mem.md, line 65 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015#-KNku3ZRu2EG2cXtDYek:-KNku3ZRu2EG2cXtDYel:2073015313) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fe0dad3a49dafee3a6d0f36b8cbd5ba7e252ab/docs/RFCS/row_mem.md#L65)):*
> ```Markdown
> Saving: 30% reduction in memory usage, possibly also from fewer allocations.
> 
> # Idea 2: fixed with columns next to each other
> ```

s/with/width/

---

*[docs/RFCS/row_mem.md, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015#-KNku9JJv-R2ONGpwtLW:-KNku9JJv-R2ONGpwtLX:-610028105) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fe0dad3a49dafee3a6d0f36b8cbd5ba7e252ab/docs/RFCS/row_mem.md#L67)):*
> ```Markdown
> # Idea 2: fixed with columns next to each other
> 
> (Best combined with idea 1): have a n array of bytes to hold
> ```

Is this actually possible in Go?

---

*[docs/RFCS/row_mem.md, line 79 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015#-KNkuKNB4BqokwanJ8zw:-KNkuKNB4BqokwanJ8zx:658574301) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fe0dad3a49dafee3a6d0f36b8cbd5ba7e252ab/docs/RFCS/row_mem.md#L79)):*
> ```Markdown
> it's needed as Datum. For every column that is not involved in SQL
> expressions this is beneficial, as we then can decode these columns
> directly from db format to pgwire, without going to Datum encoding at all.
> ```

s/going to/going through/

---

*[docs/RFCS/row_mem.md, line 92 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015#-KNkuSNe09Ye_DOuWPri:-KNkuSNe09Ye_DOuWPrj:655329948) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fe0dad3a49dafee3a6d0f36b8cbd5ba7e252ab/docs/RFCS/row_mem.md#L92)):*
> ```Markdown
> # Idea 4: lazy decode
> 
> Most useful in combination with distsql.  With distsql the data is
> ```

possibly throughout: double space

---

*[docs/RFCS/row_mem.md, line 101 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015#-KNkuYihr75OLS9iCd64:-KNkuYihr75OLS9iCd65:-572460664) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fe0dad3a49dafee3a6d0f36b8cbd5ba7e252ab/docs/RFCS/row_mem.md#L101)):*
> ```Markdown
> states whether the data is decoded in memory or not. Accessor would
> decode on the fly; and the re-encode stage to pass the data to another
> node could bypass reencoding if the original encoding is still there
> ```

re-encoding

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015)*

**Comment by RaduBerinde** [comment]
Thanks for writing this down!

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/row_mem.md, line 67 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015#-KNku9JJv-R2ONGpwtLW:-KNm0efj4KTbCuX_wZS3:-1244475260) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fe0dad3a49dafee3a6d0f36b8cbd5ba7e252ab/docs/RFCS/row_mem.md#L67)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary>
> Is this actually possible in Go?
</details>
If nothing else it should be possible to get the address of the interface structure (e.g. `reflect.Value.UnsafeAddr()`) and then cast to `(*uint64)(unsafe.Pointer(addr)` to muck with the pointer. I haven't tried it though. And it is kind of pushing the limits of what is safe (we think it will work with the current go GC but it's not impossible to conceive a potential future implementation where it doesn't).

---

*[docs/RFCS/row_mem.md, line 90 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015#-KNm2pXfuMjI--bkk9Ci:-KNm2pXfuMjI--bkk9Cj:-1893137851) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fe0dad3a49dafee3a6d0f36b8cbd5ba7e252ab/docs/RFCS/row_mem.md#L90)):*
> ```Markdown
> compression for many types).
> 
> # Idea 4: lazy decode
> ```

We can remove this idea - this is already what we do in distsql - see `EncDatum`. Though there are interesting open questions if we want to combine this with some of the other ideas.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015#-:-KNm3TNYeA4KJuwvY37d:-1628188054)*

**Comment by bdarnell** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[docs/RFCS/row_mem.md, line 45 \[r1\]](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015#-KNmc0sre02uGgzMC3Sx:-KNmc0sre02uGgzMC3Sy:-182158244) ([raw file](https://github.com/cockroachdb/cockroach/blob/b4fe0dad3a49dafee3a6d0f36b8cbd5ba7e252ab/docs/RFCS/row_mem.md#L45)):*
> ```Markdown
> 
> So the idea here is that we replace `DTuple` as the type to represent a row
> by something else; for example an array of unsafe pointers to the actual values;
> ```

FYI this is what `atomic.Value` does: https://github.com/golang/go/blob/be915159073ed93fa511ceef7256bc8ee396d1c7/src/sync/atomic/value.go (this is motivated not by space savings but because you can do atomic operations on a single 64-bit pointer but not a 128-bit interface struct)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/8015)*

**Comment by knz** [comment]
@jordanlewis can you scan this briefly and see if there's still anything useful in there? I think most of this has already been accomplished, with the exception perhaps of the first item. Once you've scanned this I could close the PR.

**Comment by jordanlewis** [comment]
Yes, you can close this, though it's a great summary of the issues with the row at a time execution engine's memory representation. Thanks!

**Pull request closed without merging**
