### PR TITLE
kv: limit replicate queue logging of traces to once per 10s

### PR DESCRIPTION
**Pull request by nvb**
This commit limits the frequency of replicate queue traces that will end up in the KV_DISTRIBUTION channel to once every 10s.

In a support issue, we saw that a cluster with full disks will spin in the replicate queue, rapidly processing replicas and failing, with attempts ever ~500µs. The replicate queue was putting each of the offending 14k ranges into its purgatory, but still attempting to process each once a second. As a result, these logs were too noisy. Over a 9s period, they filled up 6 6MB log files and caused the logs to rollover.

Release justification: low risk change that avoids losing information during support escalations due to log rollover.

Release note: None.

Epic: none.

### CODE REVIEW

**Comment by nvanbenschoten** [comment]
Gentle ping @AlexTalks.

**Comment by AlexTalks** [comment]
I'm open to this but might prefer the option of logging all replica errors/traces at a lower verbosity as in #92682...

**Comment by AlexTalks** [comment]
Since https://github.com/cockroachdb/cockroach/pull/92967 was merged, do you think this still may be necessary @nvanbenschoten ?

**Comment by nvanbenschoten** [comment]
No, I don't think so. I'll close.

**Pull request closed without merging**
