### PR TITLE
sql: type VALUES smarter to handle tuple arrays

### LINKED ISSUE #70767: roachtest/sqlsmith: error decoding 10 bytes: empty array
Extracted from https://github.com/cockroachdb/cockroach/issues/70666#issuecomment-927242723.

roachtest.sqlsmith/setup=empty/setting=no-ddl [failed](https://teamcity.cockroachdb.com/viewLog.html?buildId=3498637&tab=buildLog) with [artifacts](https://teamcity.cockroachdb.com/viewLog.html?buildId=3498637&tab=artifacts#/sqlsmith/setup=empty/setting=no-ddl) on master @ [ecaa4920192549af1418923648769ede3de1c9c8](https://github.com/cockroachdb/cockroach/commits/ecaa4920192549af1418923648769ede3de1c9c8):

```
The test failed on branch=master, cloud=gce:
test artifacts and logs in: /home/agent/work/.go/src/github.com/cockroachdb/cockroach/artifacts/sqlsmith/setup=empty/setting=no-ddl/run_1
	sqlsmith.go:223,sqlsmith.go:256,test_runner.go:777: error: pq: internal error: unexpected error from the vectorized engine: error decoding 10 bytes: empty array
		stmt:
SELECT
  col
FROM
  (VALUES ((ARRAY[]:::RECORD[],)), ((ARRAY[()],)))
    AS t(col)
ORDER BY
  col ASC;
```
<details><summary>Reproduce</summary>
<p>

See: [roachtest README](https://github.com/cockroachdb/cockroach/blob/master/pkg/cmd/roachtest/README.md)

</p>
<sub>

[This test on roachdash](https://roachdash.crdb.dev/?filter=status:open%20t:.*sqlsmith/setup=empty/setting=no-ddl.*&sort=title+created&display=lastcommented+project) | [Improve this report!](https://github.com/cockroachdb/cockroach/tree/master/pkg/cmd/internal/issues)
</sub>

### PR DESCRIPTION
**Pull request by rafiss**
fixes https://github.com/cockroachdb/cockroach/issues/70767

The VALUES clause previously would take the type of the first non-null element. Now it also searches for the first type that is not an array containing AnyTuple typed elements. This fixes a bug that was causing internal errors with some queries.

Release note: None

### CODE REVIEW

**Comment by rafiss** [comment]
i guess the other fakedist configs are fine because we already have this in `distSQLExprCheckVisitor`
```
	case *tree.DArray:
		if t.ResolvedType().ArrayContents() == types.AnyTuple {
			v.err = newQueryNotSupportedErrorf("array %s cannot be executed with distsql", t)
			return false, expr
		}
```

**Comment by RaduBerinde** [comment]
> There's just confusing behavior where if you use`TESTFLAGS='-rewrite'`, then the test will say pass even if it failed under `fakedist` configuration, as long as it passed some other configuration. Running without `-rewrite` still fails.

The test gets rewritten multiple times.. If there is a "hard" failure (eg unexpected error) then it shouldn't pass. I usually restrict it to one config when rewriting, then run under all configs.

**Review by yuzefovich — APPROVED** [review]
`fakedist-disk` config should not be handled differently from other `fakedist` configs because of `distSQLExprCheckVisitor` - that visitor is purely about the distributed execution and has nothing to do about the spilling to disk.

Looks like the tests pass though, thanks for the fix! :lgtm:

> Reviewed 3 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72243#-:-MnRZqPa4FBtIS3w6PAa:b-qhak3t)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @rafiss)

___
*[pkg/sql/distsql_physical_planner.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72243#-MnR_A9QDgYgJyB3wVPP:-MnR_A9QDgYgJyB3wVPQ:b-sjpb0o) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b6e24aec0c4cada9c4531077c364fc7cc4edce7/pkg/sql/distsql_physical_planner.go#L252)):*
> ```Go
> 		// We need to check for arrays of untyped tuples here since constant-folding
> 		// on builtin functions sometimes produces this. DecodeUntaggedDatum
> 		// requires that all the types of the tuple ocntents are known.
> ```

nit: `s/ocntents/contents/`.
___
*[pkg/sql/opt/optbuilder/values.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72243#-MnRa2e-7871oJRbHMUn:-MnRa2e-7871oJRbHMUo:b-x323p3) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b6e24aec0c4cada9c4531077c364fc7cc4edce7/pkg/sql/opt/optbuilder/values.go#L86)):*
> ```Go
> 					typ.ArrayContents().Family() == types.TupleFamily &&
> 					typ.ArrayContents() != types.AnyTuple {
> 					colTypes[colIdx] = typ
> ```

nit: maybe add a quick comment with an example here since the condition is quite long.

**Review by rafiss — COMMENTED** [review]
tftr!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72243#-:-MnRgl_L0g-yG15Buqpw:b-7ixx6c)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @yuzefovich)

___
*[pkg/sql/distsql_physical_planner.go, line 252 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72243#-MnR_A9QDgYgJyB3wVPP:-MnRgmQ537q3GZKdehXo:b-7ql1td) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b6e24aec0c4cada9c4531077c364fc7cc4edce7/pkg/sql/distsql_physical_planner.go#L252)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: `s/ocntents/contents/`.
</blockquote></details>

fixed
___
*[pkg/sql/opt/optbuilder/values.go, line 86 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/72243#-MnRa2e-7871oJRbHMUn:-MnRgnAw6-iZBoISm9DP:bb7f2mf) ([raw file](https://github.com/cockroachdb/cockroach/blob/1b6e24aec0c4cada9c4531077c364fc7cc4edce7/pkg/sql/opt/optbuilder/values.go#L86)):*
<details><summary><i>Previously, yuzefovich (Yahor Yuzefovich) wrote…</i></summary><blockquote>

nit: maybe add a quick comment with an example here since the condition is quite long.
</blockquote></details>

done

**Comment by rafiss** [comment]
bors r=yuzefovich

**Pull request merged**
