### PR TITLE
server/license: Limit enterprise trial license usage to once per cluster

### PR DESCRIPTION
**Pull request by spilchen**
Previously, clusters could install a second enterprise trial license. To prevent misuse, we are now restricting the use of this license type to only once per cluster. This update adds the necessary tracking mechanism.

A new key has been introduced in the KV system key range to record the number of enterprise trial licenses used, ensuring the data persists across restarts.

This change will be backported to versions 24.2, 24.1, 23.2, and 23.1.

Epic: CRDB-39988
Closes: CRDB-40416
Release note (general change): Attempting to install a second enterprise trial license on the same cluster will now fail.

### CODE REVIEW

**Review by fqazi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131422)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/server/license/enforcer.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131422#-O872hf21cERlj2VqCBB:-O872hf305N0ZVK_o99B:b-mzkdpd) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7b44340f2921f129c131f74cbbafe9887685ca/pkg/server/license/enforcer.go#L463)):*
> ```Go
> 
> 	var sb strings.Builder
> 	sb.WriteString(fmt.Sprintf("enforcer license updated: type is %d, ", licType))
> ```

Nit: Do we want to have human readable types with stringer? Probably something to poke at later.
___
*[`pkg/server/license/enforcer.go` line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131422#-O873eOM0b3007jt6wJF:-O873eOM0b3007jt6wJG:b-pmq41u) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7b44340f2921f129c131f74cbbafe9887685ca/pkg/server/license/enforcer.go#L513)):*
> ```Go
> 			}
> 			if oldVal.Value == nil && e.trialUsageCount.Load() != 0 {
> 				e.trialUsageCount.Store(0)
> ```

Could we use conditional put here instead? I believe it will return the old value if the CPut fails inside the ConditionFailedError.

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131422)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/server/license/enforcer.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131422#-O872hf21cERlj2VqCBB:-O87d3LW99yJxt3qxoZ0:b-nvf0ou) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7b44340f2921f129c131f74cbbafe9887685ca/pkg/server/license/enforcer.go#L463)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Nit: Do we want to have human readable types with stringer? Probably something to poke at later.
</blockquote></details>

Very cool. I wasn't aware of stringer. It seemed easy to hook up, so I added it to this PR.
___
*[`pkg/server/license/enforcer.go` line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131422#-O873eOM0b3007jt6wJF:-O87dIR7DXgmNABD93I0:by4rif3) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7b44340f2921f129c131f74cbbafe9887685ca/pkg/server/license/enforcer.go#L513)):*
<details><summary><i>Previously, fqazi (Faizan Qazi) wrote…</i></summary><blockquote>

Could we use conditional put here instead? I believe it will return the old value if the CPut fails inside the ConditionFailedError.
</blockquote></details>

We could implement that, and it would save a KV call. However, the logic to extract the actual value is a bit complex, and given how rarely this is expected to happen, it might not be worth optimizing for.

Instead of this:
```
			oldVal, err := txn.KV().Get(ctx, keys.TrialLicenseUsageCount)
			if err != nil {
				return err
			}
			if oldVal.Value == nil && e.trialUsageCount.Load() != 0 {
				e.trialUsageCount.Store(0)
				return nil
			} else if oldVal.Value != nil && oldVal.ValueInt() != e.trialUsageCount.Load() {
				e.trialUsageCount.Store(oldVal.ValueInt())
				return nil
			}
```

You would have this:
```
			if err := txn.KV().CPut(ctx, keys.TrialLicenseUsageCount,
				newCount, kvclientutils.StrToCPutExistingValue(fmt.Sprintf("%d", e.trialUsageCount.Load()))); err != nil {
				if detail := (*kvpb.ConditionFailedError)(nil); errors.As(err, &detail) {
					if detail.ActualValue == nil {
						e.trialUsageCount.Store(0)
						return nil
					}
					cur, err := detail.ActualValue.GetInt()
					if err != nil {
						return err
					}
					e.trialUsageCount.Store(cur)
					return nil
				}
				return err
			} else {
				e.trialUsageCount.Store(newCount)
				return nil
			}
```

**Review by fqazi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131422)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @spilchen)

___
*[`pkg/server/license/enforcer.go` line 513 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131422#-O873eOM0b3007jt6wJF:-O880AL2-TmuwvHU6jbC:b-vqgx68) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7b44340f2921f129c131f74cbbafe9887685ca/pkg/server/license/enforcer.go#L513)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

We could implement that, and it would save a KV call. However, the logic to extract the actual value is a bit complex, and given how rarely this is expected to happen, it might not be worth optimizing for.

Instead of this:
```
			oldVal, err := txn.KV().Get(ctx, keys.TrialLicenseUsageCount)
			if err != nil {
				return err
			}
			if oldVal.Value == nil && e.trialUsageCount.Load() != 0 {
				e.trialUsageCount.Store(0)
				return nil
			} else if oldVal.Value != nil && oldVal.ValueInt() != e.trialUsageCount.Load() {
				e.trialUsageCount.Store(oldVal.ValueInt())
				return nil
			}
```

You would have this:
```
			if err := txn.KV().CPut(ctx, keys.TrialLicenseUsageCount,
				newCount, kvclientutils.StrToCPutExistingValue(fmt.Sprintf("%d", e.trialUsageCount.Load()))); err != nil {
				if detail := (*kvpb.ConditionFailedError)(nil); errors.As(err, &detail) {
					if detail.ActualValue == nil {
						e.trialUsageCount.Store(0)
						return nil
					}
					cur, err := detail.ActualValue.GetInt()
					if err != nil {
						return err
					}
					e.trialUsageCount.Store(cur)
					return nil
				}
				return err
			} else {
				e.trialUsageCount.Store(newCount)
				return nil
			}
```
</blockquote></details>

True, not worth the complexity if its rare

**Review by rafiss — APPROVED** [review]
nice work!

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131422#-:-O88bQH02OHsgzIJ3Q8m:b-j4xmku)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @spilchen)

___
*[`pkg/server/license/enforcer.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131422#-O872hf21cERlj2VqCBB:-O88aNj4-1v58sQegOKu:b-8wz9wv) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7b44340f2921f129c131f74cbbafe9887685ca/pkg/server/license/enforcer.go#L463)):*
<details><summary><i>Previously, spilchen wrote…</i></summary><blockquote>

Very cool. I wasn't aware of stringer. It seemed easy to hook up, so I added it to this PR.
</blockquote></details>

`stringer` also lets you define custom string representations, in case you wanted to make the strings be different than the variable name. the `-linecomment` option lets you define the string representation in an inline comment. see: https://github.com/cockroachdb/cockroach/blob/5d46feeb33134e405fe7ff192467cbf485e1008d/pkg/ccl/backupccl/backup_telemetry.go#L34-L42

**Review by spilchen — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/131422)* status: <span>:shipit:</span> complete! 0 of 0 LGTMs obtained (waiting on @fqazi and @rafiss)

___
*[`pkg/server/license/enforcer.go` line 463 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/131422#-O872hf21cERlj2VqCBB:-O88kkDh2PjTB1lzPYeY:b-a5pw9b) ([raw file](https://github.com/cockroachdb/cockroach/blob/0d7b44340f2921f129c131f74cbbafe9887685ca/pkg/server/license/enforcer.go#L463)):*
<details><summary><i>Previously, rafiss (Rafi Shamim) wrote…</i></summary><blockquote>

`stringer` also lets you define custom string representations, in case you wanted to make the strings be different than the variable name. the `-linecomment` option lets you define the string representation in an inline comment. see: https://github.com/cockroachdb/cockroach/blob/5d46feeb33134e405fe7ff192467cbf485e1008d/pkg/ccl/backupccl/backup_telemetry.go#L34-L42
</blockquote></details>

Thanks for bringing that up. I used the linecomment option so that we don't include the type prefix `LicTyp`.

**Comment by spilchen** [comment]
TFTR!

bors r=fqazi,rafiss

**Pull request merged**
