### PR TITLE
build: allow directories for acceptance tests

### PR DESCRIPTION
**Pull request by justinj**
🔬🐶, this commit lets acceptance tests specify a directory which should
be mounted.

Included is a test of jdbc which translates the old string literal test
into one which has a directory structure and can be opened in IntelliJ.

@jordanlewis could you also check that you can open the `java_test` directory in IntelliJ and have it load properly and stuff (you still have to use `make acceptance TESTS=TestDockerJava` to run it)?

### CODE REVIEW

**Comment by benesch** [comment]
:tada: this is such an improvement. I didn't review the actual Java, FYI.

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/java_test.go, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwfa3wFt1gUHDegZr_H:-Kwfa3wFt1gUHDegZr_I:bxr8xsa) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test.go#L31)):*
> ```Go
> 
> 	ctx := context.Background()
> 	classPath := ".:lib/junit.jar:lib/hamcrest.jar:lib/postgres.jar:src/main/java"
> ```

(I mentioned this below, but I'd be a very happy camper if these were instead baked into the postgres-test image at the appropriate classpath.)

---

*[pkg/acceptance/java_test.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfaANuKbImiksQ5Mmh:-KwfaANuKbImiksQ5Mmi:b-kfkyry) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test.go#L42)):*
> ```Go
> 		cmd:   []string{"/bin/sh", "-c", strings.Replace(java, "%v", ``, 2)},
> 		binds: []string{"java_test"},
> 	})
> ```

I recommend dropping this test; every Docker test is so slow + flaky that we want each one to count.

---

*[pkg/acceptance/util_docker.go, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwf_RAekNL7tfbm6ZLt:-Kwf_RAekNL7tfbm6ZLu:bkqwa3m) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/util_docker.go#L51)):*
> ```Go
> 	// name within the docker container as outside of it (see java_test.go which
> 	// mounts the java_test directory).
> 	binds []string
> ```

I would drop this from the struct, and just always bind `testdata`. Binds are cheap provided you don't read/write them.

---

*[pkg/acceptance/util_docker.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfaeAjqSQcL4rNYDHm:-KwfaeAjqSQcL4rNYDHn:b-lqairw) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/util_docker.go#L99)):*
> ```Go
> 		pwd, err = os.Getwd()
> 		if err != nil {
> 			return
> ```

eek! return `err`

also why predeclare `pwd`?

---

*[pkg/acceptance/java_test/.gitignore, line 5 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwf_2h4RjUGTn2kdwmZ:-Kwf_2h5lHGQnO8h2Ja8:bua8gii) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test/.gitignore#L5)):*
> ```
> .DS_Store
> key.pk8
> .idea
> ```

On principle, we don't store os- or editor-specific entries in our .gitignores. (See one of the other .gitignores for rationale.) That means .DS_Store and .idea should go, but *.class and target should stay. Is key.pk8 necessary to ignore, or just part of an auto-generated .gitignore?

---

*[pkg/acceptance/java_test/lib/hamcrest.jar, line 0 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfZuvjAIlp54ie3tVp:-KwfZuvjAIlp54ie3tVq:b-rflh7i) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test/lib/hamcrest.jar#L0)):*
Ahhh, I'd really prefer not to check more binary blobs into the repo. I know it's a pain, but could you bake these into the `postgres-test` image?

---

*[pkg/acceptance/java_test/src/main/java/main.java, line 1 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfZSpQHlHT_d6cfFyL:-KwfZSpQHlHT_d6cfFyM:b-6hzhzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test/src/main/java/main.java#L1)):*
> ```Java
> import org.junit.*;
> ```

Convention is to put files like this in a folder named `testdata` so that Go doesn't think it's a package if it contains `.go` files, etc. I'd advocate for `testdata/java`, and then always mount `testdata`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-:-KwfaZxW0bGmBipj6nD_:b-njo4xr)*

**Comment by justinj** [comment]
Just responded to a couple things with clarification/questions - still working on the others

---

Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/java_test.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfaANuKbImiksQ5Mmh:-KwffDy6DIdmfob6DXjq:b-uo425o) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test.go#L42)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I recommend dropping this test; every Docker test is so slow + flaky that we want each one to count.
</blockquote></details>

We actually have a bunch of tests like this that mess with their input to intentionally fail (I think Tamir told me it's because there was a time when they were failing but we weren't detecting said failures appropriately). Perhaps we could even get away with deleting all but one of them at this point? I think *every* acceptance test has two versions in this way.

---

*[pkg/acceptance/util_docker.go, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwf_RAekNL7tfbm6ZLt:-KwfdehpaaTD_mIetHml:b8d8crx) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/util_docker.go#L51)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

I would drop this from the struct, and just always bind `testdata`. Binds are cheap provided you don't read/write them.
</blockquote></details>

:thumbsup: good point, I can just get rid of this struct and go back to the old function signatures then.

---

*[pkg/acceptance/util_docker.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfaeAjqSQcL4rNYDHm:-KwfdpYqxWtv1j0f3SjK:b-dh9orj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/util_docker.go#L99)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

eek! return `err`

also why predeclare `pwd`?
</blockquote></details>

The structure of this function is odd, the entire function predeclares `err` and returns it at the end due to the anonymous function passed to `RunDocker` (there's no explicit return at the end because the function ends there). Perhaps there's a nicer way to structure it given this change though, I'll investigate.

---

*[pkg/acceptance/java_test/.gitignore, line 5 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwf_2h4RjUGTn2kdwmZ:-Kwfe4baftyV0WTtJDFp:b-ohcm9q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test/.gitignore#L5)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

On principle, we don't store os- or editor-specific entries in our .gitignores. (See one of the other .gitignores for rationale.) That means .DS_Store and .idea should go, but *.class and target should stay. Is key.pk8 necessary to ignore, or just part of an auto-generated .gitignore?
</blockquote></details>

`key.pk8` is generated by the test, it could conceivably delete it afterwards but then you'd have it sitting around if the test failed somehow I think, I think it's easier if it's just ignored.

I'll remove the other stuff, I sort of feel like `.idea` is a different case since you might not want use your main editor for Java stuff (and just use IntelliJ and then get out), but I don't feel strongly.

---

*[pkg/acceptance/java_test/lib/hamcrest.jar, line  at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfZuvjAIlp54ie3tVp:-KwfeDOJmmjMhWepePvE:b-ybycqj) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test/lib/hamcrest.jar#L)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Ahhh, I'd really prefer not to check more binary blobs into the repo. I know it's a pain, but could you bake these into the `postgres-test` image?
</blockquote></details>

It's nicer to work with them in an IDE if the IDE has access to them for autocomplete and stuff (which is why I put them in here), but I agree that their inclusion is unfortunate, I wonder if there's a way to get IntelliJ to download them and put them in an ignored directory... I'll look into that.

Would it be [overly] weird to `.gitignore` them and then
a. have the docker container place them in there when it runs or
b. include a script that can be run manually to download them if you want the IDE support? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-:-KwfhnBc4-zynwIaVU9g:bsqf0at)*

**Comment by benesch** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/java_test.go, line 42 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfaANuKbImiksQ5Mmh:-KwfpooklPHFfd1uzIsf:b1gqgjz) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test.go#L42)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

We actually have a bunch of tests like this that mess with their input to intentionally fail (I think Tamir told me it's because there was a time when they were failing but we weren't detecting said failures appropriately). Perhaps we could even get away with deleting all but one of them at this point? I think *every* acceptance test has two versions in this way.
</blockquote></details>

Heh, you're totally right. I'm not sold on this being useful, but no point in breaking with convention.

---

*[pkg/acceptance/util_docker.go, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwf_RAekNL7tfbm6ZLt:-Kwfmik1oTXJpzDMRVj6:b4c9lyr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/util_docker.go#L51)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

:thumbsup: good point, I can just get rid of this struct and go back to the old function signatures then.
</blockquote></details>

:thumbsup: 

---

*[pkg/acceptance/util_docker.go, line 99 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfaeAjqSQcL4rNYDHm:-KwfmcGio5bf5OevJvsD:bhz5qbu) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/util_docker.go#L99)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

The structure of this function is odd, the entire function predeclares `err` and returns it at the end due to the anonymous function passed to `RunDocker` (there's no explicit return at the end because the function ends there). Perhaps there's a nicer way to structure it given this change though, I'll investigate.
</blockquote></details>

Oh, wow, I entirely misread. Carry on. Seems fine enough.

---

*[pkg/acceptance/java_test/.gitignore, line 5 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwf_2h4RjUGTn2kdwmZ:-Kwfl_R4ExH5UmisY171:b-1k2wqt) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test/.gitignore#L5)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

`key.pk8` is generated by the test, it could conceivably delete it afterwards but then you'd have it sitting around if the test failed somehow I think, I think it's easier if it's just ignored.

I'll remove the other stuff, I sort of feel like `.idea` is a different case since you might not want use your main editor for Java stuff (and just use IntelliJ and then get out), but I don't feel strongly.
</blockquote></details>

Yeah, I know what you mean, but I have a moderately-strong preference for forcing people to put crap like that into their global gitignore. This has served me so well:

```
$ cat ~/.config/git/ignore
.DS_Store
.vscode
.idea
.terraform
```

(E.g., what if someone else working on Java prefers Eclipse or NetBeans or whatever?)

---

*[pkg/acceptance/java_test/lib/hamcrest.jar, line  at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfZuvjAIlp54ie3tVp:-Kwfkk5rFSESHwtDMT14:b-n1hn0q) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test/lib/hamcrest.jar#L)):*
<details><summary><i>Previously, justinj (Justin Jaffray) wrote…</i></summary><blockquote>

It's nicer to work with them in an IDE if the IDE has access to them for autocomplete and stuff (which is why I put them in here), but I agree that their inclusion is unfortunate, I wonder if there's a way to get IntelliJ to download them and put them in an ignored directory... I'll look into that.

Would it be [overly] weird to `.gitignore` them and then
a. have the docker container place them in there when it runs or
b. include a script that can be run manually to download them if you want the IDE support? 
</blockquote></details>

Yeah, option b sounds perfect. I'd ignore all JAR files or `lib` entirely. Can you check in whatever `mvn install` needs, and then direct people to run `mvn install`? Does IntelliJ integrate with Maven?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321)*

**Comment by jordanlewis** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/java_test/.gitignore, line 5 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwf_2h4RjUGTn2kdwmZ:-KwfrIiiO7ldiwZFgD29:b-y52ygr) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test/.gitignore#L5)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, I know what you mean, but I have a moderately-strong preference for forcing people to put crap like that into their global gitignore. This has served me so well:

```
$ cat ~/.config/git/ignore
.DS_Store
.vscode
.idea
.terraform
```

(E.g., what if someone else working on Java prefers Eclipse or NetBeans or whatever?)
</blockquote></details>

-1 on including any intellij stuff in here at all. just use pom.xml. intellij (and every java ide) can import those

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321)*

**Comment by tschottdorf** [comment]
+1 on the approach, looking good!

---

Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-:-Kwg2yK6OSFTJBVPseWc:b-xwnj00)*

**Comment by justinj** [comment]
Review status: 0 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/java_test.go, line 31 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwfa3wFt1gUHDegZr_H:-Kwg4xl3SfImZYDhoJ9n:bfcl02r) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test.go#L31)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

(I mentioned this below, but I'd be a very happy camper if these were instead baked into the postgres-test image at the appropriate classpath.)
</blockquote></details>

https://github.com/cockroachdb/postgres-test/pull/25

---

*[pkg/acceptance/util_docker.go, line 51 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwf_RAekNL7tfbm6ZLt:-Kwg2Yj4gMTFv_kQUjou:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/util_docker.go#L51)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

:thumbsup: 
</blockquote></details>

Done.

---

*[pkg/acceptance/java_test/lib/hamcrest.jar, line  at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-KwfZuvjAIlp54ie3tVp:-Kwg2iZXEYTrUlmyypfV:bwcxwf3) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test/lib/hamcrest.jar#L)):*
<details><summary><i>Previously, benesch (Nikhil Benesch) wrote…</i></summary><blockquote>

Yeah, option b sounds perfect. I'd ignore all JAR files or `lib` entirely. Can you check in whatever `mvn install` needs, and then direct people to run `mvn install`? Does IntelliJ integrate with Maven?
</blockquote></details>

Ok, `mvn install` should work now! I added a README instructing the reader to do that.

---

*[pkg/acceptance/java_test/.gitignore, line 5 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwf_2h4RjUGTn2kdwmZ:-Kwg2bOaCra-wd2PWj26:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/ec04ccdf62a341232989b98bcd8ffa9b1452eac4/pkg/acceptance/java_test/.gitignore#L5)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

-1 on including any intellij stuff in here at all. just use pom.xml. intellij (and every java ide) can import those
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321)*

**Comment by jordanlewis** [comment]
:lgtm_strong:  I'm pretty convinced that you should just make `mvn test` work. You're so close! Then you can get rid of any kind of weird `javac` invocations. 

---

Review status: 0 of 8 files reviewed at latest revision, 10 unresolved discussions, some commit checks pending.

---

*[pkg/acceptance/java_test.go, line 44 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwg6JpCUMoQXaQPKO0H:-Kwg6JpCUMoQXaQPKO0I:b-ytuuoz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f41a9c9d03f9bbe3cabcbaec1607af5f931c9f3a/pkg/acceptance/java_test.go#L44)):*
> ```Go
> export PATH=$PATH:/usr/lib/jvm/java-1.8-openjdk/bin
> javac -cp %v src/main/java/main.java
> java -cp %v org.junit.runner.JUnitCore main
> ```

yay. fwiw this *is* kind of weird - normally you'd just run `mvn test` and have that all hooked up. I think this is fine - but just as a possibility if things get more complicated we can do that.

---

*[pkg/acceptance/testdata/java/java.iml, line 2 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwg6XMO9tEkFgqReph5:-Kwg6XMO9tEkFgqReph6:b-xvr2gz) ([raw file](https://github.com/cockroachdb/cockroach/blob/f41a9c9d03f9bbe3cabcbaec1607af5f931c9f3a/pkg/acceptance/testdata/java/java.iml#L2)):*
> ```XML
> <?xml version="1.0" encoding="UTF-8"?>
> <module org.jetbrains.idea.maven.project.MavenProjectsManager.isMavenModule="true" type="JAVA_MODULE" version="4">
> ```

this is an intellj file right? kill it with :fire: :)

---

*[pkg/acceptance/testdata/java/pom.xml, line 25 at r2](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwg6adThFMcj4hFq3vR:-Kwg6adThFMcj4hFq3vS:b-slf5df) ([raw file](https://github.com/cockroachdb/cockroach/blob/f41a9c9d03f9bbe3cabcbaec1607af5f931c9f3a/pkg/acceptance/testdata/java/pom.xml#L25)):*
> ```XML
>       </dependency>
>     </dependencies>
> </project>
> ```

sweet! like i said above you can set this up so that `mvn test` actually runs all the JUnit tests. It might be nice...!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-:-Kwg6sFBPHB08WKPthCZ:b-qvudt0)*

**Comment by tamird** [comment]
Does this close #4591?

**Comment by justinj** [comment]
It does, thanks for the heads up @tamird.

@jordanlewis good call, I didn't realize we would be able to do that - it uses `mvn test` now!

**Comment by benesch** [comment]
:lgtm:

---

Reviewed 6 of 27 files at r2, 6 of 6 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[pkg/acceptance/java_test.go, line 41 at r3](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-Kwk4vW4ebL8OhszG5sE:-Kwk4vW4ebL8OhszG5sF:bcz1pxy) ([raw file](https://github.com/cockroachdb/cockroach/blob/7703963d7887e566e74fa617b9a0b4a8c6413d41/pkg/acceptance/java_test.go#L41)):*
> ```Go
> openssl pkcs8 -topk8 -inform PEM -outform DER -in /certs/node.key -out key.pk8 -nocrypt
> 
> mvn %v
> ```

:thumbsup: this is short and sweet. Nice!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/19321#-:-Kwk5Gie9XZGYM6-iZLV:bnfp4nl)*

**Comment by benesch** [comment]
I think you just need to tag and push your postgres-test image and update util_docker.go accordingly in this PR?

**Comment by tschottdorf** [comment]
BTW, re: the negative tests -- I think it's good not to have rot there, but it's not worth the CI time in the "hot path". I don't think I would trust a separate "sentinel test", but we could just run the negatives nightly-only and would find out pretty quickly if something did regress.

**Comment by justinj** [comment]
Thanks for the reviews!

**Pull request merged**
