### PR TITLE
Tiny fixes to comments in range.go and queue.go

### PR DESCRIPTION
**Pull request by kkaneda**
- s/process/processLoop/
- Remove the comment on mutex from ContainsKey()

### CODE REVIEW

**Comment by BramGruneir** [comment]
LGTM

**Comment by tschottdorf** [comment]
You don't want to fix the vet error like that. Pass the leases as pointers so that the Stringer interface is implemented.

**Comment by kkaneda** [comment]
I see. Reverted the changed to the formatting.

**Comment by tschottdorf** [comment]
LGTM. `go vet` behaves weirdly sometimes unfortunately. Thanks @kkaneda

**Comment by tschottdorf** [comment]
the test failure should go away if you rebase on current master.

**Comment by kkaneda** [comment]
Thanks, @tschottdorf ! These things are very good to know. Will rebase and merge after the test passes.

**Pull request merged**
