### PR TITLE
kvserver: transfer lease when acquiring lease outside preferences

### LINKED ISSUE #106100: kvserver: eagerly move leases to preferred regions
When a leaseholder is lost, any surviving replica may acquire the lease, even if it violates lease preferences. There are two main reasons for this: we need to elect a new Raft leader who will acquire the lease, which is agnostic to lease preferences, and there may not even be any surviving replicas that satisfy the lease preferences at all.

However, after acquiring a lease, we rely on the replicate queue to transfer the lease back to a replica that conforms with the preferences, which can take several minutes in some cases. In multi-region clusters, this can cause severe latency degradation if the lease is acquired in a remote region.

We should eagerly move leases back to preferred regions when acquiring them outside of the preferred regions.

To reproduce:

```
$ roachprod create local -n 5
$ roachprod start local --racks 3

> create database kv;
> alter database kv configure zone using num_replicas=5, constraints='{"+rack=0": 2, "+rack=1": 2, "+rack=2": 1}', lease_preferences='[[+rack=0]]';

$ ./cockroach workload init kv --splits 1000

# Wait for all leases to move to rack=0 nodes.
> select range_id, start_key, end_key, lease_holder, lease_holder_locality from [show ranges from database kv with details] where lease_holder_locality not like '%rack=0';

# Alternatively, mass-relocate all violating leases to n4:
> alter range relocate lease to 4 for select range_id from [show ranges from database kv with details] where lease_holder_locality not like '%rack=0';

$ roachprod stop local:4

# In this case, we actually see leases move back to rack=0 quite soon. In a production cluster, we saw leases linger for 10 minutes. Unclear why.
> select range_id, start_key, end_key, lease_holder, lease_holder_locality from [show ranges from database kv with details] where lease_holder_locality not like '%rack=0';

# However, if we move leases to a different node, it will take several minutes before they're moved back to the preferences.
> alter range relocate lease to 5 for select range_id from [show ranges from database kv];

> select range_id, start_key, end_key, lease_holder, lease_holder_locality from [show ranges from database kv with details] where lease_holder_locality not like '%rack=0';

# Remember to use --racks 3 when restarting n4.
$ roachprod start local:4 --racks 3
```

Jira issue: CRDB-29399

Epic CRDB-27235

### PR DESCRIPTION
**Pull request by erikgrinaker**
When a leaseholder is lost, any surviving replica may acquire the lease, even if it violates lease preferences. There are two main reasons for this: we need to elect a new Raft leader who will acquire the lease, which is agnostic to lease preferences, and there may not even be any surviving replicas that satisfy the lease preferences at all, so we don't want to keep the range unavailable while we try to figure this out (considering e.g. network timeouts can delay this for many seconds).

However, after acquiring a lease, we rely on the replicate queue to transfer the lease back to a replica that conforms with the preferences, which can take several minutes. In multi-region clusters, this can cause severe latency degradation if the lease is acquired in a remote region.

This patch will detect lease preference violations when a replica acquires a new lease, and eagerly enqueue it in the replicate queue for transfer (if possible).

Resolves #106100.
Epic: none

Release note (bug fix): When losing a leaseholder and using lease preferences, the lease can be acquired by any other replica (regardless of lease preferences) in order to restore availability as soon as possible. The new leaseholder will now immediately check if it violates the lease preferences, and attempt to transfer the lease to a replica that satisfies the preferences if possible.

### CODE REVIEW

**Comment by erikgrinaker** [comment]
It turns out the replicate queue isn't doing anything when I enqueue these ranges.

```
I230704 14:03:17.081396 513 kv/kvserver/replica_proposal.go:395 ⋮ [T1,n5,s5,r588/4:‹/Table/106/1/70{48830…-67259…}›,raft] 30256  new range lease repl=(n5,s5):4 seq=43 start=1688479397.072916182,0 epo=17 pro=1688479397.077098474,0 following repl=(n5,s5):4 seq=42 start=1688479397.072916182,0 exp=1688479403.072851248,0 pro=1688479397.072851248,0
I230704 14:03:17.081545 513 kv/kvserver/replica_proposal.go:559 ⋮ [T1,n5,s5,r588/4:‹/Table/106/1/70{48830…-67259…}›,raft] 30261  acquired lease violates lease preferences, enqueueing for transfer [lease=repl=(n5,s5):4 seq=43 start=1688479397.072916182,0 epo=17 pro=1688479397.077098474,0 preferences=[{[‹+rack=0›]}]]
I230704 14:03:17.081591 513 kv/kvserver/replica_proposal.go:562 ⋮ [T1,n5,s5,r588/4:‹/Table/106/1/70{48830…-67259…}›,raft] 30262  Add
I230704 14:03:17.236849 18410 kv/kvserver/queue.go:989 ⋮ [T1,n5,replicate,s5,r588/4:‹/Table/106/1/70{48830…-67259…}›] 30919  processing replica
I230704 14:03:17.236873 18410 kv/kvserver/queue.go:1023 ⋮ [T1,n5,replicate,s5,r588/4:‹/Table/106/1/70{48830…-67259…}›] 30920  processing...
I230704 14:03:17.237519 18410 kv/kvserver/replicate_queue.go:848 ⋮ [T1,n5,replicate,s5,r588/4:‹/Table/106/1/70{48830…-67259…}›] 30921  planned action=‹consider rebalance› op=plan.AllocationNoop
I230704 14:03:17.237542 18410 kv/kvserver/queue.go:1033 ⋮ [T1,n5,replicate,s5,r588/4:‹/Table/106/1/70{48830…-67259…}›] 30922  processing... done
I230704 14:03:17.237556 18410 kv/kvserver/queue.go:942 ⋮ [T1,n5,replicate,s5,r588/4:‹/Table/106/1/70{48830…-67259…}›] 30923  done 726.202µs
```

This is unexpected to me. `ShouldPlanChange` seems to expect the queue to transfer violating leases too, but it doesn't appear to actually do so.

https://github.com/cockroachdb/cockroach/blob/db9239cd1857e28eda73c5337575bbf16f4208e0/pkg/kv/kvserver/allocator/plan/replicate.go#L199-L211

@kvoli @andrewbaptist Can you help me figure out how this is all wired up? Where do we enforce lease preferences?

**Comment by erikgrinaker** [comment]
I think this was broken in 22.2.  In 22.1, `AllocatorConsiderRebalance` would fall through to a `shedLease()` call:

https://github.com/cockroachdb/cockroach/blob/d9930b15ad5fe844ab2450cb1f0c37e3cd37b8e5/pkg/kv/kvserver/replicate_queue.go#L1368-L1387

In 22.2, it doesn't:

https://github.com/cockroachdb/cockroach/blob/1353b644059256764d132a62b46b83d54387b1c7/pkg/kv/kvserver/replicate_queue.go#L1690-L1710

This logic was removed in #85219.

**Comment by erikgrinaker** [comment]
>However, we do also enqueue it when we acquire leadership, so why isn't it transferring it then?

First, we're hitting the `MaybeAddAsync` semaphore limit of 20.

https://github.com/cockroachdb/cockroach/blob/2b91c3829270eb512c5380201c26a3d838fc567a/pkg/kv/kvserver/queue.go#L467-L469

After increasing that, the `MaybeAdd` is failing because we _just_ became leader, and haven't received any info from our followers yet, so they're all in `StateProbe`.

I suppose one approach here would be to just keep requeueing these replicas as long as their lease violates the preferences.

**Comment by erikgrinaker** [comment]
Just to confirm, when I disable the `excludeReplicasInNeedOfSnapshots` checks, leases immediately move back to their preferred regions with this patch.

**Review by kvoli — COMMENTED** [review]
> [@kvoli](https://github.com/kvoli) [@andrewbaptist](https://github.com/andrewbaptist) Can you help me figure out how this is all wired up? Where do we enforce lease preferences?

I think you found it. The lease is only checked for transfer in the `ConsiderRebalance` action, and only if there were no rebalance opportunities. Effectively making lease preference enforcement a lower priority than rebalancing.

> I suppose one approach here would be to just keep requeueing these replicas as long as their lease violates the preferences.

We discussed earlier, we could add a check in `PlanOneChange` which returns a leaseholder not leader error marked as a purgatory error:
https://github.com/cockroachdb/cockroach/blob/972c37959e31fc46c71679b39fbd5cfa04be5fc8/pkg/kv/kvserver/queue.go#L119-L119

The replica will then be retried every 1 minute by default:

https://github.com/cockroachdb/cockroach/blob/972c37959e31fc46c71679b39fbd5cfa04be5fc8/pkg/kv/kvserver/replicate_queue.go#L74-L78

> Reviewed 7 of 7 files at r1, 7 of 7 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-:-NZaoqnYDNJ4o9WofqaY:bgbqmg9)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-NZab78y0wsyXhQcwq_a):*
Should this commit be here?
___
*[`pkg/kv/kvserver/replicate_queue.go` line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-NZanp8v8Xic-JHikuIF:-NZanp8v8Xic-JHikuIG:bg49dgp) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ecf875622c971a99918a40e65eaf23c25919a4/pkg/kv/kvserver/replicate_queue.go#L84)):*
> ```Go
> 	replicateQueueTimerDuration = 0 // zero duration to process replication greedily
> 
> 	replicateQueuePriorityHigh = 1000 // see AllocatorAction.Priority
> ```

How did you settle on this priority? Is it deliberately the same as removing a dead voter?

https://github.com/cockroachdb/cockroach/blob/972c37959e31fc46c71679b39fbd5cfa04be5fc8/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L254-L259

For context - resolving a violated constraint with the right number of voters+non-voters is done at `AllocatorConsiderRebalance` priority level, `0`.

**Review by erikgrinaker — COMMENTED** [review]
Placing the replicas in purgatory worked great, thanks for the tip! It actually succeeded in immediately moving all 1000 leases back to the preferred locations, because purgatory will eagerly retry replicas when we add to it. Previously it would only manage about 800 leases or so, the remaining 200 failed because they weren't the Raft leader yet.

I added on a commit. Does the overall direction here make sense to you? If so, I'll clean this up and add some tests.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-:-NZbfUPmEME1-jVqi5Fi:b-ef2pa2)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @kvoli)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-NZab78y0wsyXhQcwq_a):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

Should this commit be here?
</blockquote></details>

No, this was just added while testing because of #106097. Removed it now, since it repros more easily with `ALTER RANGE RELOCATE` anyway.
___
*[`pkg/kv/kvserver/replicate_queue.go` line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-NZanp8v8Xic-JHikuIF:-NZbi9jR9BlcbggQ9kfA:bs1wtqu) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ecf875622c971a99918a40e65eaf23c25919a4/pkg/kv/kvserver/replicate_queue.go#L84)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

How did you settle on this priority? Is it deliberately the same as removing a dead voter?

https://github.com/cockroachdb/cockroach/blob/972c37959e31fc46c71679b39fbd5cfa04be5fc8/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L254-L259

For context - resolving a violated constraint with the right number of voters+non-voters is done at `AllocatorConsiderRebalance` priority level, `0`.
</blockquote></details>

It was mostly arbitrarily. I just wanted to make sure it didn't end up at the bottom of the pile, since this is pretty important.

**Review by kvoli — COMMENTED** [review]
Overall direction makes sense to me. 

It may be worthwhile looking into the overhead of checking lease preferences during acquisition and also if there's no "live" stores which satisfy the preference, so every replica ends up in purgatory. I've rarely seen more than 1-3 lease preferences per range but the conjunction checks doing string comparison might be noticeable? 


Left a question on the priority.

> Reviewed 10 of 10 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-:-NZfklmB3WcZQXAOUlsP:b-rbkj)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-NZanp8v8Xic-JHikuIF:-NZfjKFV0eoAVUbxa9TZ:b-j14jac) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ecf875622c971a99918a40e65eaf23c25919a4/pkg/kv/kvserver/replicate_queue.go#L84)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

It was mostly arbitrarily. I just wanted to make sure it didn't end up at the bottom of the pile, since this is pretty important.
</blockquote></details>

During voter up-replication (decommissioning, general upreplication, dead node), lease preferences may still not be enforced because they are sitting behind ranges which need to be up-replicated.

Is this fine? It is certainly better than before.

**Review by erikgrinaker — COMMENTED** [review]
>overhead of checking lease preferences during acquisition

I think this is negligible considering the other work we do during acquisition.

>if there's no "live" stores which satisfy the preference, so every replica ends up in purgatory

Yeah, this is the bit I'm worried about. Consider e.g. someone setting a bogus `+foo` preference, which will put all replicas in purgatory forever. I may extend the check to at least see if the preferences can be satisfied at all (assuming all nodes are live), and maybe also to omit it if they can't be satisfied currently because all valid targets are unavailable. In the latter case I think it would be beneficial to put it in purgatory, to recover as soon as the nodes come back online, but it's certainly worth checking the overhead here -- and maybe even skip that bit in the backport.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-:-NZfoG6O6qZyKGwFFPVc:b-ikaky7)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-NZanp8v8Xic-JHikuIF:-NZfp7Oh7LTXDkFGVQfk:b5axi9m) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ecf875622c971a99918a40e65eaf23c25919a4/pkg/kv/kvserver/replicate_queue.go#L84)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

During voter up-replication (decommissioning, general upreplication, dead node), lease preferences may still not be enforced because they are sitting behind ranges which need to be up-replicated.

Is this fine? It is certainly better than before. 
</blockquote></details>

Yeah, I feel like we may want to move this to the top, considering lease transfers are cheap. Wdyt? On the other hand, we certainly don't want to starve out upreplication, since it leaves us vulnerable to quorum loss.

**Review by kvoli — COMMENTED** [review]
> I think this is negligible considering the other work we do during acquisition.

Good to know.

> I may extend the check to at least see if the preferences can be satisfied at all (assuming all nodes are live), and maybe also to omit it if they can't be satisfied currently because all valid targets are unavailable.

That is a good idea. Another case is where there are no existing voter stores which satisfy the preference, but there are other stores which do. There is no logic which will rebalance replicas in order to then transfer the lease for satisfying a preference. So purgatory in this case wouldn't be too helpful. 

https://github.com/cockroachdb/cockroach/blob/17814d828a41eba4c4e96c5986b4a3c76c45b190/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2811-L2813

Perhaps we could scope the purgatory criteria to just when there are replicas in need of a snapshot? 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-:-NZg4XBw5ulfKzE-TCW_:b-xcgz0l)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-NZanp8v8Xic-JHikuIF:-NZg31YbB4JWWqAuNZbg:btgtqn) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ecf875622c971a99918a40e65eaf23c25919a4/pkg/kv/kvserver/replicate_queue.go#L84)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yeah, I feel like we may want to move this to the top, considering lease transfers are cheap. Wdyt? On the other hand, we certainly don't want to starve out upreplication, since it leaves us vulnerable to quorum loss.
</blockquote></details>

It should be cheap and quick normally, but this feels like a change that requires more extensive testing if pursued. I don't think we can reason that it will be fine without trying to break it.

Do you plan to backport this part of the change?

**Review by erikgrinaker — COMMENTED** [review]
>Perhaps we could scope the purgatory criteria to just when there are replicas in need of a snapshot?

I started with that, but the plumbing got a bit annoying, and I figured we'd want to eagerly try to get them back to the preferred regions as soon as they recovered anyway. But it might make sense for a backport, and we can be more eager for 23.2.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-:-NZg9LAZCKb30RgPuEeC:bgxo79t)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @kvoli)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-NZanp8v8Xic-JHikuIF:-NZg9ACJDfLgfCX-ON-g:bboslup) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ecf875622c971a99918a40e65eaf23c25919a4/pkg/kv/kvserver/replicate_queue.go#L84)):*
<details><summary><i>Previously, kvoli (Austen) wrote…</i></summary><blockquote>

It should be cheap and quick normally, but this feels like a change that requires more extensive testing if pursued. I don't think we can reason that it will be fine without trying to break it.

Do you plan to backport this part of the change?


</blockquote></details>

I was, but we can also use priority 0 if we feel like that's safer, and bump the priority for 23.2. Probably better.

**Review by kvoli — COMMENTED** [review]
Commented on the line where the purgatory error is created.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-:-NZkpxZJBeXGbJlIx0zW:b-btnuzi)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker)

___
*[`pkg/kv/kvserver/replicate_queue.go` line 84 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-NZanp8v8Xic-JHikuIF:-NZki-e83oJfaByMuf4z:b-y4ypfj) ([raw file](https://github.com/cockroachdb/cockroach/blob/03ecf875622c971a99918a40e65eaf23c25919a4/pkg/kv/kvserver/replicate_queue.go#L84)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

I was, but we can also use priority 0 if we feel like that's safer, and bump the priority for 23.2. Probably better.
</blockquote></details>

Using priority 0 SGTM.  That is the priority which is currently assigned to lease preference violation:

https://github.com/cockroachdb/cockroach/blob/938e484e82e9256b128387c920d96591c704c9d9/pkg/kv/kvserver/allocator/plan/replicate.go#L210-L210
___
*[`pkg/kv/kvserver/allocator/plan/replicate.go` line 952 at r6](https://reviewable.io/reviews/cockroachdb/cockroach/106079#-NZkqHRJ-DyQwxjQsI0q:-NZkqHRJ-DyQwxjQsI0r:b-w4rbmd) ([raw file](https://github.com/cockroachdb/cockroach/blob/bb49030f34c4173479b3006eb7e93a08c5fc64e0/pkg/kv/kvserver/allocator/plan/replicate.go#L952)):*
> ```Go
> 		// leadership, which prevents us from finding appropriate lease targets
> 		// since we can't determine if any are behind.
> 		if repl.LeaseViolatesPreferences(ctx) {
> ```

Continuing the discussion about purgatory criteria here.

An alternative could be:

Checking `repl.LeaseViolatesPreferencs` and most of `allocator.leaseholderShouldMoveDueToPreferences`

https://github.com/cockroachdb/cockroach/blob/938e484e82e9256b128387c920d96591c704c9d9/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2133-L2136

We don't want to include the filtering on replicas:

Suspect replicas:

https://github.com/cockroachdb/cockroach/blob/938e484e82e9256b128387c920d96591c704c9d9/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2166-L2169

Replicas in need of a snapshot:

https://github.com/cockroachdb/cockroach/blob/938e484e82e9256b128387c920d96591c704c9d9/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2173-L2177

Excluding draining/dead stores but not suspect stores is doable but annoying using the storepool. 

There's only the option to exclude both suspect and draining, but not just draining. Perhaps it would be fine to include draining stores in the criteria or ignore both.
 
So a purgatory error is returned when the lease violates the preferences and there is an existing voter replica, on a store which is not dead/suspect/draining/unknown (or just dead/draining/unknown - see above) and satisfies the preferences.

We could add an option to `allocator.ShouldTransferLease` which disables checking for replicas in need of a snapshot (not ideal but seems simple):

https://github.com/cockroachdb/cockroach/blob/938e484e82e9256b128387c920d96591c704c9d9/pkg/kv/kvserver/allocator/allocatorimpl/allocator.go#L2489-L2489

**Comment by erikgrinaker** [comment]
Closing in favor of #107507.

**Pull request closed without merging**
