### PR TITLE
colexec: fix projections of AND and OR operators when NULLs are present

### LINKED ISSUE #40913: colexec: problems with AND and OR operators
Currently, we have some issues with AND and OR logical operators when they are used as projecitons:
- [x] AND doesn't follow the short-circuiting approach
```
statement ok
DROP TABLE IF EXISTS t; CREATE TABLE t (k INT PRIMARY KEY, a INT, b INT)

statement ok
INSERT INTO t VALUES (1, NULL, NULL), (2, NULL, 1), (3, 1, NULL), (4, 2, 0), (5, 3, 3)

# Test AND short-circuiting projection logic (check that the right side is not
# evaluated when the left side is false).
query B
SELECT a <> 2 AND 3 / b = 1 FROM t ORDER BY k
----
NULL
false
NULL
false
true
```
- [x] OR expression is replaced by CASE operator that is not fully equivalent to the desired expression when nulls are present.

### PR DESCRIPTION
**Pull request by yuzefovich**
**colexec: minor clean up of vec comparators**

Release justification: Category 1: Non-production code changes.

**colexec: fix projections of AND and OR operators when NULLs are present**

Previously, AND projection operator didn't follow the short-circuiting
logic, so it could return incorrect results. Also, the OR expression
was replaced by CASE operator, but it is not an equivalent change when
NULLs are present. This commit adds a new projOrOp operator to handle
the OR expressions.

The idea to handle the short-circuiting logic is similar to what caseOp
does: a logical operator has an input and two projection chains. First,
it runs the left chain on the input batch. Then, it "subtracts" the
tuples for which we know the result of logical operation based only on
the left side projection (e.g. if the left side is false and we're
doing AND operation, then the result is also false) and runs the right
side projection only on the remaining tuples (i.e. those that were not
"subtracted"). Next, it restores the original selection vector and
populates the result of the logical operation.

Release justification: Category 2: Bug fixes and low-risk updates to
new functionality.

Addresses: #40634.
Fixes: #40913.

Release note: None

### CODE REVIEW

**Comment by yuzefovich** [comment]
Currently, the newly added OR test is failing because we never return NULL when OR'ing two things. I don't immediately see whether it's a problem of CASE operator or of the idea of replacing OR with CASE (I feel like the latter). Thoughts?

**Comment by yuzefovich** [comment]
I wrote a separate operator for OR, so it is RFAL.

**Comment by yuzefovich** [comment]
#40927 should go in first.

**Comment by yuzefovich** [comment]
It is now RFAL.

**Comment by yuzefovich** [comment]
Friendly ping.

I merged a PR to tell sqlsmith about AND and OR expressions support in the vectorized, so ideally we would merge this today so that output of sqlsmith didn't contain the known problems this PR addresses.

**Comment by yuzefovich** [comment]
Please give this guy a look. We definitely need to merge this for 19.2 release because this problem can occur with `auto` setting.

**Comment by jordanlewis** [comment]
@solongordon @rafiss @asubiotto please take a look. This should be added to the release blockers list if it is a release blocker.

**Comment by yuzefovich** [comment]
I'm not sure whether it qualifies as a release blocker - it is not a stability problem, rather a correctness one that the vectorized engine introduced (I guess I'd think it is a release blocker).

**Review by asubiotto — COMMENTED** [review]
Nice work, sorry for not reviewing this but I assume my review is not needed unless I'm added to the `Reviewers`.

> Reviewed 2 of 2 files at r1, 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-:-LpoqLrHDed-bIfukPGO:b-uhhref)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-LponeRK06APEPEEqfH8:-LponeRK06APEPEEqfH9:b-l08odo) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/colexec/and_or_projection_tmpl.go#L96)):*
> ```Go
> }
> 
> func (o *_OP_LOWERProjOp) Next(ctx context.Context) coldata.Batch {
> ```

It might be nice to add the commit message explaining what's going on as a comment somewhere around here.
___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lpomypp5HDfGTT4O43f:-Lpomypp5HDfGTT4O43g:bwmgcd5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/colexec/and_or_projection_tmpl.go#L148)):*
> ```Go
> 		batch.SetSelection(true)
> 		sel := batch.Selection()
> 		var curIdx uint16
> ```

nit: could extract `curIdx` and `SetLength` below in both branches
___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lpoo7et3Hvl2SqYd0F5:-Lpoo7et3Hvl2SqYd0F6:b-bws2o5) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/colexec/and_or_projection_tmpl.go#L180)):*
> ```Go
> 	outputCol := batch.ColVec(o.outputIdx)
> 
> 	rightColVals := rightCol.Bool()
> ```

Maybe add a comment saying that this is where we actually evaluate the expressions if necessary
___
*[pkg/sql/colexec/execplan.go, line 976 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-LpopZd91TGGMf9nbFyO:-LpopZd91TGGMf9nbFyP:b-46c3cr) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/colexec/execplan.go#L976)):*
> ```Go
> 		// the CASE operator. (b should not be evaluated if a is true.)
> 		caseExpr, err := tree.NewTypedCaseExpr(
> 			nil,
> ```

nit: comment the `nil`
___
*[pkg/sql/colexec/execplan.go, line 1216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lpoq9M318cxm_5kRtMO:-Lpoq9M318cxm_5kRtMP:b8c0lb) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/colexec/execplan.go#L1216)):*
> ```Go
> 	case *tree.OrExpr:
> 		// Add a new boolean column that ORs the two output columns.
> 		resultIdx = len(columnTypes)
> ```

Seems to be repeated code between this and the `AND` case, consider extracting it.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 947 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lpooun_-oWuU9qCmiDb:-Lpooun_-oWuU9qCmiDc:bqa54t8) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/logictest/testdata/logic_test/vectorize#L947)):*
> ```
> 
> statement ok
> INSERT INTO t VALUES (1, NULL, NULL), (2, NULL, 1), (3, 1, NULL), (4, 2, 0), (5, 3, 3)
> ```

I wonder if we should add these tests to a new `vectorize_expr` file for tests that aren't covered by `TestEval`, I don't think adding more tests to this file will be sustainable for long.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 978 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-LpopGhn48_Mxz0SjYKo:-LpopGhn48_Mxz0SjYKp:bgn4j3a) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/logictest/testdata/logic_test/vectorize#L978)):*
> ```
> true
> 
> # Test OR short-circuiting selectiong logic (check that the right side is not
> ```

nit: `s/selectiong/selection`

**Review by yuzefovich — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40847)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @rafiss, and @solongordon)

___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 96 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-LponeRK06APEPEEqfH8:-LqHgpqk3Z0R_cAgXIW7:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/colexec/and_or_projection_tmpl.go#L96)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

It might be nice to add the commit message explaining what's going on as a comment somewhere around here.
</blockquote></details>

Done.
___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 148 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lpomypp5HDfGTT4O43f:-LqHhG3m6ePiZl7ZcdDf:bo3vl6y) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/colexec/and_or_projection_tmpl.go#L148)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: could extract `curIdx` and `SetLength` below in both branches
</blockquote></details>

Thanks, done.
___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 180 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lpoo7et3Hvl2SqYd0F5:-LqHhb9T0beRuA5MZt9M:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/colexec/and_or_projection_tmpl.go#L180)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Maybe add a comment saying that this is where we actually evaluate the expressions if necessary
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execplan.go, line 976 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-LpopZd91TGGMf9nbFyO:-LqHhk_e6MN0S9LohmMa:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/colexec/execplan.go#L976)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: comment the `nil`
</blockquote></details>

Done.
___
*[pkg/sql/colexec/execplan.go, line 1216 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lpoq9M318cxm_5kRtMO:-LqHkaikEdMhWxD--9hW:bfbq99i) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/colexec/execplan.go#L1216)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

Seems to be repeated code between this and the `AND` case, consider extracting it.
</blockquote></details>

Good point, done.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 947 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lpooun_-oWuU9qCmiDb:-LqHlHyQ062nn1ELDI1j:b-om7gzq) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/logictest/testdata/logic_test/vectorize#L947)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

I wonder if we should add these tests to a new `vectorize_expr` file for tests that aren't covered by `TestEval`, I don't think adding more tests to this file will be sustainable for long.
</blockquote></details>

I agree, `vectorize` is almost 1k lines now. Done.
___
*[pkg/sql/logictest/testdata/logic_test/vectorize, line 978 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-LpopGhn48_Mxz0SjYKo:-LqHl-bY6smuvCXERdJw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/e67f16efbbad332c25b59454e4ec85e6b12a6baf/pkg/sql/logictest/testdata/logic_test/vectorize#L978)):*
<details><summary><i>Previously, asubiotto (Alfonso Subiotto Marqués) wrote…</i></summary><blockquote>

nit: `s/selectiong/selection`
</blockquote></details>

Done.

**Review by jordanlewis — APPROVED** [review]
:lgtm:

Any benchmarks?

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-:-LqcB7347V49SCTO9_2w:b-gsvfj0)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @asubiotto, @jordanlewis, @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 77 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-LqbTl1-8YhEV75b6hIm:-LqbTl1-8YhEV75b6hIn:b-k3ac88) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb12fdeee3d073079e4e485366c0a17520288f9/pkg/sql/colexec/and_or_projection_tmpl.go#L77)):*
> ```Go
> }
> 
> func (o *_OP_LOWERProjOp) Child(nth int) execinfra.OpNode {
> ```

I don't think this will work unless you make sure the left and right op chains terminate, otherwise you'll have duplicate entries in explain.

We probably need to think about how to make the explain outputs more helpful soon, but for now just make sure that all the chains terminate before hitting duplicates.
___
*[pkg/sql/logictest/testdata/logic_test/tpch_vec, line 881 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lqbs1jX3O0dyLE0MMtm:-Lqbs1jX3O0dyLE0MMtn:b-ffl984) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb12fdeee3d073079e4e485366c0a17520288f9/pkg/sql/logictest/testdata/logic_test/tpch_vec#L881)):*
> ```
>               ├ *colexec.constBoolOp
>               │ └ *colexec.orProjOp
>               │   ├ *colexec.andProjOp
> ```

How come only 2 children are shown here? I thought these would have 3?

**Review by yuzefovich — COMMENTED** [review]
I'll look into adding benchmarks tomorrow, but please take a look at the change to EXPLAIN (VEC).

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-:-LqclIYbC3Wf3DgWMoNU:b-q6xm51)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @jordanlewis, @rafiss, and @solongordon)

___
*[pkg/sql/colexec/and_or_projection_tmpl.go, line 77 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-LqbTl1-8YhEV75b6hIm:-LqcReV00XE8cZuntIDC:b-fbw1c1) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb12fdeee3d073079e4e485366c0a17520288f9/pkg/sql/colexec/and_or_projection_tmpl.go#L77)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

I don't think this will work unless you make sure the left and right op chains terminate, otherwise you'll have duplicate entries in explain.

We probably need to think about how to make the explain outputs more helpful soon, but for now just make sure that all the chains terminate before hitting duplicates.
</blockquote></details>

Hm, I think you're right. I added another commit to address that.
___
*[pkg/sql/logictest/testdata/logic_test/tpch_vec, line 881 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lqbs1jX3O0dyLE0MMtm:-LqcVPYcBgmYuy6kz343:b-cf2t2r) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb12fdeee3d073079e4e485366c0a17520288f9/pkg/sql/logictest/testdata/logic_test/tpch_vec#L881)):*
<details><summary><i>Previously, jordanlewis (Jordan Lewis) wrote…</i></summary><blockquote>

How come only 2 children are shown here? I thought these would have 3?
</blockquote></details>

Huh, good eye. Yes, there are three children, but one of them is a chain that starts with `bufferOp` which is marked as `NonExplainable` and `ZeroInputNode`, so the full main chain is not shown at all. I've just added another commit that addresses this issue (as well as duplicate handling).

**Comment by yuzefovich** [comment]
Added the benchmarks:
```
BenchmarkLogicalProjOp/AND,useSel=true,hasNulls=true-12         	  500000	      4256 ns/op	1924.38 MB/s
BenchmarkLogicalProjOp/AND,useSel=true,hasNulls=false-12        	  300000	      4794 ns/op	1708.49 MB/s
BenchmarkLogicalProjOp/AND,useSel=false,hasNulls=true-12        	  300000	      5469 ns/op	1497.65 MB/s
BenchmarkLogicalProjOp/AND,useSel=false,hasNulls=false-12       	 1000000	      1884 ns/op	4347.86 MB/s
BenchmarkLogicalProjOp/OR,useSel=true,hasNulls=true-12          	  300000	      4514 ns/op	1814.60 MB/s
BenchmarkLogicalProjOp/OR,useSel=true,hasNulls=false-12         	  300000	      5055 ns/op	1620.25 MB/s
BenchmarkLogicalProjOp/OR,useSel=false,hasNulls=true-12         	  300000	      4366 ns/op	1876.11 MB/s
BenchmarkLogicalProjOp/OR,useSel=false,hasNulls=false-12        	 1000000	      2359 ns/op	3471.97 MB/s
```

**Review by jordanlewis — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40847)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @rafiss, @solongordon, and @yuzefovich)

___
*[pkg/sql/logictest/testdata/logic_test/tpch_vec, line 881 at r4](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-Lqbs1jX3O0dyLE0MMtm:-LqhI5104_gpKcHAVH-y:bg8sl9x) ([raw file](https://github.com/cockroachdb/cockroach/blob/2fb12fdeee3d073079e4e485366c0a17520288f9/pkg/sql/logictest/testdata/logic_test/tpch_vec#L881)):*
<details><summary><i>Previously, yuzefovich wrote…</i></summary><blockquote>

Huh, good eye. Yes, there are three children, but one of them is a chain that starts with `bufferOp` which is marked as `NonExplainable` and `ZeroInputNode`, so the full main chain is not shown at all. I've just added another commit that addresses this issue (as well as duplicate handling).
</blockquote></details>

Great this looks more sensible. Thanks.

**Comment by yuzefovich** [comment]
@asubiotto do you want to take another quick look at this PR?

**Review by asubiotto — APPROVED** [review]
:lgtm: 

> Reviewed 13 of 13 files at r5, 13 of 13 files at r6, 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/40847#-:-Lqq5MH30gK7v-L6wcGJ:bg7igkv)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @asubiotto, @rafiss, @solongordon, and @yuzefovich)

**Comment by yuzefovich** [comment]
Thanks for the reviews!

bors r+

**Pull request merged**
