### PR TITLE
storage: improve tracing during GC

### PR DESCRIPTION
**Pull request by tbg**
See #15756.

### CODE REVIEW

**Comment by tamird** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[pkg/storage/gc_queue.go, line 505 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15812#-KjiXueBLwd96NWTYG8E:-KjiXueBLwd96NWTYG8F:b-nmj0pe) ([raw file](https://github.com/cockroachdb/cockroach/blob/324537b984ebac9acc7cb90604a21d83867407ee/pkg/storage/gc_queue.go#L505)):*
> ```Go
> 	// resolution and values after the MVCC metadata, and possible
> 	// intent, are sent for garbage collection.
> 	log.Event(ctx, "iterating through range")
> ```

nit: put this on the `for ; ; iter.Next() {` line? (under the comment, for consistency)

---

*[pkg/storage/gc_queue.go, line 588 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15812#-KjiY3XfTB2w3Sld2IJF:-KjiY3XfTB2w3Sld2IJG:b-7ykdxa) ([raw file](https://github.com/cockroachdb/cockroach/blob/324537b984ebac9acc7cb90604a21d83867407ee/pkg/storage/gc_queue.go#L588)):*
> ```Go
> 	gcKeys = append(gcKeys, localRangeKeys...)
> 
> 	log.Eventf(ctx, "pushing up to %d transactions (concurrency %d)", len(txnMap), gcTaskLimit)
> ```

put this under the comment below, for consistency with the two other `log.Eventf`s you added below.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15812#-:-KjiYCXI1G2z897rDhPa:bnfp4nl)*

**Comment by tamird** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15812)*

**Comment by tschottdorf** [comment]
Review status: 1 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[pkg/storage/gc_queue.go, line 505 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15812#-KjiXueBLwd96NWTYG8E:-KjiY_YCPLg6JOeFK0Fx:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/324537b984ebac9acc7cb90604a21d83867407ee/pkg/storage/gc_queue.go#L505)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

nit: put this on the `for ; ; iter.Next() {` line? (under the comment, for consistency)
</blockquote></details>

Done.

---

*[pkg/storage/gc_queue.go, line 588 at r1](https://reviewable.io:443/reviews/cockroachdb/cockroach/15812#-KjiY3XfTB2w3Sld2IJF:-KjiYdzQiheDgT6RIftM:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/324537b984ebac9acc7cb90604a21d83867407ee/pkg/storage/gc_queue.go#L588)):*
<details><summary><i>Previously, tamird (Tamir Duberstein) wrote…</i></summary><blockquote>

put this under the comment below, for consistency with the two other `log.Eventf`s you added below.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15812)*

**Comment by tamird** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15812)*

**Comment by petermattis** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cockroachdb/cockroach/15812#-:-KjidcD9Bmvl8A1y0EvI:bnfp4nl)*

**Pull request merged**
