### PR TITLE
.github: project automation for admission control

### PR DESCRIPTION
**Pull request by nicktrav**
Add GitHub Action automation to move issues labelled as `{A,T}-admission-control` to the Admission Control project.

Alphabetize projects.

Release note: None.

Epic: None.

### CODE REVIEW

**Review by sumeerbhola — APPROVED** [review]
:lgtm_strong: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111351#-:-NfMYlpj1rvTff2GvwBW:b-yncq6h)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Review by sumeerbhola — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111351)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nicktrav)

___
*[`.github/workflows/add-issues-to-project.yml` line 25 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/111351#-NfMZ-x0-GqbhU9hYE61:-NfMZ-x0-GqbhU9hYE62:b9oghcl) ([raw file](https://github.com/cockroachdb/cockroach/blob/8e9522bbb2e96575acbb37fefb23b0935ed0dd3d/.github/workflows/add-issues-to-project.yml#L25)):*
> ```YAML
>           project-url: https://github.com/orgs/cockroachdb/projects/32
>           github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
>           labeled: A-admission-control,T-admission-control
> ```

how will this go into the Triage category?

**Comment by nicktrav** [comment]
> how will this go into the Triage category?

Good question. I was confused by this too. Turns out there is a "Workflow" for that board that will assign a "Status" of "Triage" to issues added to the project.

See here: https://github.com/orgs/cockroachdb/projects/32/workflows

I have tested this workflow with an issue, and it worked as expected.

**Comment by nicktrav** [comment]
TFTR!

bors r=sumeerbhola

**Review by sumeerbhola — COMMENTED** [review]
> Turns out there is a "Workflow" for that board that will assign a "Status" of "Triage" to issues added to the project.

Interesting. I didn't add that Workflow when adding the Triage column.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/111351#-:-NfMr1bt6hjSuGtC48yD:b-7ljlb)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @nicktrav)

**Pull request merged**
