### PR TITLE
tsearch: add ts_rank functionality

### PR DESCRIPTION
**Pull request by jordanlewis**
Updates: #41288
Epic: CRDB-22357
All but the last commit are from #92966, #97677, and #97685

    This commit adds ts_rank, the family of builtins that allow ranking of
    text search results. The function takes a tsquery and a tsvector and
    returns a float that indicates how good the match is. The function can
    be modified by passing in a custom array of weights that matches the
    text search weights A, B, C, and D, and a bitmask that controls the
    ranking behavior in various detailed ways.

    See the excellent Postgres documentation here for details:
    https://www.postgresql.org/docs/current/textsearch-controls.html

    Release note (sql change): add the ts_rank function for ranking text
    search query results

### CODE REVIEW

**Review by rytaft — COMMENTED** [review]
> Reviewed 9 of 9 files at r1, 2 of 2 files at r2, 25 of 25 files at r3, 14 of 14 files at r4, 9 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @jordanlewis, and @rafiss)

___
*[`pkg/sql/sem/builtins/tsearch_builtins.go` line 338 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJe1pq1xo2qmYX4s5A:-NPJe1pq1xo2qmYX4s5B:bgg85u7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/sql/sem/builtins/tsearch_builtins.go#L338)):*
> ```Go
> 	ret := make([]float32, 4)
> 	if arr.Len() < len(ret) {
> 		return ret, pgerror.New(pgcode.ArraySubscript, "array of weight is too short")
> ```

do you want to give a hint that length 4 is expected?
___
*[`pkg/util/tsearch/rank.go` line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJf8ar4XO3bzr7rFa0:-NPJeoavD0eL-vQcuaeC:bp9qjuv) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L24)):*
> ```Go
> 
> // Bitmask for the normalization integer. These define different ranking
> // behaviors. They're defined in Postgres in tsrank.c.
> ```

I looked at that file, but it doesn't make things much clearer. Can you provide any high level comments about what these are?
___
*[`pkg/util/tsearch/rank.go` line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJeGygAiTPnma_LwHz:-NPJeGygAiTPnma_LwI-:b-g0u4y9) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L38)):*
> ```Go
> )
> 
> func cntLen(v TSVector) int {
> ```

nit: add a function comment
___
*[`pkg/util/tsearch/rank.go` line 55 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJfOOg4eA-qXjOxJSf:-NPJfOOg4eA-qXjOxJSg:b8e3s9l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L55)):*
> ```Go
> // tsvector lexeme weights D, C, B, and A. The method parameter is a bitmask
> // defining different ranking behaviors, defined in the rankBehavior type. See
> // the Postgres documentation for more details.
> ```

is there a link?
___
*[`pkg/util/tsearch/rank.go` line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJfcU_C7ntMpQ08TzQ:-NPJfcU_C7ntMpQ08TzR:b-1lvflx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L71)):*
> ```Go
> 	}
> 	if res < 0 {
> 		res = 1e-20
> ```

nit: what does this constant mean?
___
*[`pkg/util/tsearch/rank.go` line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJfoOS8Xkc-6PS3aMS:-NPJfoOS8Xkc-6PS3aMT:b78km5l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L83)):*
> ```Go
> 		}
> 	}
> 	// RANK_NORM_EXTDIST not applicable
> ```

why not?
___
*[`pkg/util/tsearch/rank.go` line 120 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJgIHnEOC7J9StKmS4:-NPJgIHnEOC7J9StKmS5:b-sdbuua) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L120)):*
> ```Go
> 		return leafNodes[i].term.lexeme < leafNodes[j].term.lexeme
> 	})
> 	// Then distinct: (wouldn't it be nice if Go had generics?)
> ```

It does now... does that change anything here?
___
*[`pkg/util/tsearch/rank.go` line 135 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJghV-EJTEr6CIaRPl:-NPJghV-EJTEr6CIaRPm:b-njyhj5) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L135)):*
> ```Go
> }
> 
> func findRankMatches(
> ```

nit: add a function comment. What are the parameters?
___
*[`pkg/util/tsearch/rank.go` line 158 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJh5W2BV5FL2wzzZZg:-NPJh5W2BV5FL2wzzZZh:b-f2fobq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L158)):*
> ```Go
> }
> 
> func rankOr(weights [4]float32, v TSVector, q TSQuery) float32 {
> ```

add a function comment
___
*[`pkg/util/tsearch/rank.go` line 187 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJhV1J0oF9W2xagyax:-NPJhV1J0oF9W2xagyay:b1c1zj6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L187)):*
> ```Go
> 		// wi - should be sorted desc,
> 		// don't sort for now, just choose maximum weight. This should be corrected
> 		// Oleg Bartunov
> ```

Does this make sense to you? I'm scratching my head...
___
*[`pkg/util/tsearch/rank.go` line 196 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJh7tp8mutE2O32y2O:-NPJh7tp8mutE2O32y2P:b-f2fobq) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L196)):*
> ```Go
> }
> 
> func rankAnd(weights [4]float32, v TSVector, q TSQuery) float32 {
> ```

add a function comment
___
*[`pkg/sql/logictest/testdata/logic_test/tsvector` line 323 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJjCo478JkHq95nPnx:-NPJjCo478JkHq95nPny:b38awom) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/sql/logictest/testdata/logic_test/tsvector#L323)):*
> ```
> ----
> 'ari':6 'base':3,13 'concept':17 'data':12,21 'form':10 'introduc':24 'model':2 'n':5 'normal':9 'relat':7,14 'sublanguag':22 'univers':20                 0.075990885
> '2':3 'appli':15 'certain':4 'consist':22 'discuss':13 'infer':11 'logic':10 'model':27 'oper':5 'problem':18 'redund':20 'relat':7 'section':2 'user':25  0.06079271
> ```

How about testing the other overloads of `ts_rank`?

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97697)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @DrewKimball, @rafiss, and @rytaft)

___
*[`pkg/sql/sem/builtins/tsearch_builtins.go` line 338 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJe1pq1xo2qmYX4s5A:-NQYPlbM5Ga5plRBzUyL:b-tezkcc) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/sql/sem/builtins/tsearch_builtins.go#L338)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

do you want to give a hint that length 4 is expected?
</blockquote></details>

I'm copying the inadequate Postgres message here. I suppose we can do better, it probably won't break compatibility... Done
___
*[`pkg/util/tsearch/rank.go` line 24 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJf8ar4XO3bzr7rFa0:-NQYPyJ-ELlbkoCjWve2:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L24)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

I looked at that file, but it doesn't make things much clearer. Can you provide any high level comments about what these are?
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/rank.go` line 38 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJeGygAiTPnma_LwHz:-NQYRMZ_4KJ2JKNzf6E0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L38)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: add a function comment
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/rank.go` line 55 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJfOOg4eA-qXjOxJSf:-NQYRNGs7xFtX8coYywq:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L55)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

is there a link?
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/rank.go` line 71 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJfcU_C7ntMpQ08TzQ:-NQYRiTp-ccW6S3GxEcU:bv4idu8) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L71)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

nit: what does this constant mean?
</blockquote></details>

I have no idea, it's not documented in the Postgres source. I copied this verbatim, I really have no idea what it does. I'll clarify this fact in the code, I wish I had something better to say here.
___
*[`pkg/util/tsearch/rank.go` line 83 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJfoOS8Xkc-6PS3aMS:-NQYSrwh1VSlzn-rf6ql:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L83)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

why not?
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/rank.go` line 120 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJgIHnEOC7J9StKmS4:-NQYTnt211bX4JJlxYxL:b7c7c8l) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L120)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

It does now... does that change anything here?
</blockquote></details>

We still don't have access to x/exp/slices at this Go version which implements slices.Compact, once that's added we can replace a whole bunch of copypasta that looks just like this throughout the codebase. I'll file an issue.
___
*[`pkg/util/tsearch/rank.go` line 158 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJh5W2BV5FL2wzzZZg:-NQYXeeX21drUtai8xGQ:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L158)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

add a function comment
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/rank.go` line 187 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJhV1J0oF9W2xagyax:-NQYY5a8EX6YjUM070eJ:b-w9y7ok) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L187)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

Does this make sense to you? I'm scratching my head...
</blockquote></details>

No, I unfortunately have no idea what this means. I figured I'd just include it in case it helps somebody, lol.
___
*[`pkg/util/tsearch/rank.go` line 196 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJh7tp8mutE2O32y2O:-NQYYBZ26JJ4ifcRRkCi:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/util/tsearch/rank.go#L196)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

add a function comment
</blockquote></details>

Done.
___
*[`pkg/sql/logictest/testdata/logic_test/tsvector` line 323 at r5](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NPJjCo478JkHq95nPnx:-NQYbH1kBI_cdQHYQZAW:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/8de220ec65692ad68cc6eeff79f92b730e09dcde/pkg/sql/logictest/testdata/logic_test/tsvector#L323)):*
<details><summary><i>Previously, rytaft (Rebecca Taft) wrote…</i></summary><blockquote>

How about testing the other overloads of `ts_rank`?
</blockquote></details>

Done.

**Review by DrewKimball — COMMENTED** [review]
:lgtm: Only have a couple nits.

> Reviewed 1 of 2 files at r2, 42 of 42 files at r6, 31 of 31 files at r7, 16 of 16 files at r8, 9 of 10 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-:-NQbXKolBiM01Le5iLIA:b-afpbui)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @jordanlewis, @rafiss, and @rytaft)

___
*[`pkg/util/tsearch/tsvector.go` line 339 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NQbFzjd7pI2pHlsekKm:-NQbFzjd7pI2pHlsekKn:b-ak09jt) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c11d5cecea3f280b2788811e84a314253b668c9/pkg/util/tsearch/tsvector.go#L339)):*
> ```Go
> // routines like to_tsvector and to_tsquery.
> // It can return false in the second parameter to indicate a stopword was found.
> func TSLexize(config string, token string) (lexeme string, notAStopWord bool, err error) {
> ```

[super nit] The negative in `notAStopWord` feels confusing, why not just `stopWord` and return false by default?
___
*[`pkg/util/tsearch/tsvector.go` line 376 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NQbH4p48Xz-AQsojTOS:-NQbH4p48Xz-AQsojTOT:b31g0g2) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c11d5cecea3f280b2788811e84a314253b668c9/pkg/util/tsearch/tsvector.go#L376)):*
> ```Go
> 		pos := i + 1
> 		if i > maxTSVectorPosition {
> 			pos = maxTSVectorPosition
> ```

[nit] Could you add a comment 
```
// Postgres silently truncates positions larger than 16383 to 16383.
``` 
to mirror `tsVectorLexer.lex`?

**Review by rytaft — APPROVED** [review]
:lgtm:

> Reviewed 42 of 42 files at r6, 31 of 31 files at r7, 16 of 16 files at r8, 5 of 10 files at r9, 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-:-NR-sgzME_YEb-xxcCKG:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (and 1 stale) (waiting on @jordanlewis and @rafiss)

**Review by jordanlewis — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97697)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball, @rafiss, and @rytaft)

___
*[`pkg/util/tsearch/tsvector.go` line 339 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NQbFzjd7pI2pHlsekKm:-NR3GCnO0J7I-bgPX0c0:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c11d5cecea3f280b2788811e84a314253b668c9/pkg/util/tsearch/tsvector.go#L339)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[super nit] The negative in `notAStopWord` feels confusing, why not just `stopWord` and return false by default?
</blockquote></details>

Done.
___
*[`pkg/util/tsearch/tsvector.go` line 376 at r9](https://reviewable.io/reviews/cockroachdb/cockroach/97697#-NQbH4p48Xz-AQsojTOS:-NR3GD--CkwE1oToQa-h:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/1c11d5cecea3f280b2788811e84a314253b668c9/pkg/util/tsearch/tsvector.go#L376)):*
<details><summary><i>Previously, DrewKimball (Drew Kimball) wrote…</i></summary><blockquote>

[nit] Could you add a comment 
```
// Postgres silently truncates positions larger than 16383 to 16383.
``` 
to mirror `tsVectorLexer.lex`?
</blockquote></details>

Done.

**Review by rytaft — APPROVED** [review]
> Reviewed 38 of 38 files at r11, 33 of 33 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/97697)* status: :shipit: complete! 0 of 0 LGTMs obtained (and 2 stale) (waiting on @DrewKimball and @rafiss)

**Pull request merged**
