### PR TITLE
workload: give each kvOp a separate sql.Conn

### PR DESCRIPTION
**Pull request by nvb**
In #26178, we saw that throughput hit a cliff while running `kv` at
high concurrency levels. We spent a while debugging the issue, but
nothing stood out in the `cockroach` process. Eventually, I installed
pprof http handlers in `workload` (#30810). The CPU and heap profiles
looked fine but the mutex profile revealed that **99.94%** of mutex
contention was in `sql.(*Rows).Next`.

It turns out that this method manipulates a lock that's scoped to
the same degree as its prepared statement. Since `readStmt` was
prepared on the `sql.DB`, all kvOps were contending on the same lock
in `sql.(*Rows).Next`.

The fix is to give each `kvOp` its own `sql.Conn` and prepare the
statement with a connection-level scope. There are probably other places
in `workload` that could use the same kind of change.

Before this change, `kv100 --concurrency=400` in the configuration
discussed in #26178 topped out at around 80,000 qps. After this change,
it tops out at around 250,000 qps.

Release note: None

### CODE REVIEW

**Review by benesch — APPROVED** [review]
omg :man_facepalming: nice find!

Is it possible for other workloads to be suffering from the same sql.DB internal contention?

:lgtm_strong:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30811#-:-LNhUe09ERVdh8oxoVkd:b-vctzhf)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
> Is it possible for other workloads to be suffering from the same sql.DB internal contention?

Very possible! We should get #30810 in and then do an audit.

**Review by a-robinson — APPROVED** [review]
Hilarious. It's good to hear it's just a client issue!

**Comment by tschottdorf** [comment]
🙈 that's ridiculous. Personally, I'd add a comment in the code for posterity.

**Review by petermattis — APPROVED** [review]
Nice find! TIL about `sql.Stmt.mu`. 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/30811#-:-LNjDESL6hejQPqXUXr2:b-ho9wpa)* status: :shipit: complete! 1 of 0 LGTMs obtained

**Comment by nvanbenschoten** [comment]
> Personally, I'd add a comment in the code for posterity.

Done.

TFTRs!

bors r+

**Comment by RaduBerinde** [comment]
___
*[pkg/workload/kv/kv.go, line 183 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/30811#-LNpKGJvBosLNSHvgdlM:-LNpKGJwEu-aqsgAf2xS:bf5k1y4) ([raw file](https://github.com/cockroachdb/cockroach/blob/b9ffacbc7778fdeda6f871d5fa617268a015b176/pkg/workload/kv/kv.go#L183)):*
> ```Go
> 			return workload.QueryLoad{}, err
> 		}
> 		writeStmt, err := db.PrepareContext(ctx, writeStmtStr)
> ```

@nvanbenschoten did you want `conn` here?

**Comment by nvanbenschoten** [comment]
> did you want conn here?

🤦‍♂️ yes. Thanks for catching that.

**Comment by mjibson** [comment]
Has anyone tried https://github.com/jackc/pgx in workload? I'm really curious if it is faster.

**Comment by RaduBerinde** [comment]
I tried using it as a driver for `sql.Database` (instead of `lib/pq`) and it was slower. I think we'd need to use their APIs directly to get better performance.

**Comment by mjibson** [comment]
Yes, using their API directly is what I should have specified in my suggestion.

**Pull request merged**
