### PR TITLE
democluster: fix global mode in multitenant cluster

### PR DESCRIPTION
**Pull request by aliher1911**
Previously when launching multitenant cluster with global option
server testing knobs didn't contain latency map.
Without map tenants will use plain grpc connections. This
is not working because latency injection needs both connection
sides to be aware as it uses extra header to negotiate delay.
This inconsistency was causing tenants stuck without being able
to talk to any nodes.
This change introduces latency map on tenants in demo cluster.

Release note (bug fix): cockroach demo could be launched
with --global and --multitenant=true options.

Fixes #72231

### CODE REVIEW

**Review by ajstorm — APPROVED** [review]
LGTM.  Thanks for taking this on!

While I don't think you need to take this on with this PR, it's worth noting that our testing around `--global` is pretty weak.  It would be nice if we had a test in `test_demo_global.tcl` which actually validated that the latency map was in effect.  Then, a change like this could validate that when switching tenants, it remains in effect.

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72750#-:-MoZBwT0E6jHR9Bj0XQN:bvca3sw)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

**Review by aliher1911 — COMMENTED** [review]
I see that `test_demo_global.tcl` now show tenants in output and checks for global pass. Do we have any way to validate actual latencies, like query latency pairs somehow? I can try to add those.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/72750#-:-MoZLXQXA32V_C9OhUJO:blyifkz)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @aliher1911)

**Comment by knz** [comment]
There's no testing of the global latency map today. This is a historical defect that came from the fact the global latency code was meant to be just an experiment and was productionized without adding the necessary testing.
Some discussion here: #63098

**Comment by aliher1911** [comment]
bors r=ajstorm

**Comment by otan** [comment]
> I see that test_demo_global.tcl now show tenants in output and checks for global pass.

wonder if it's worth adding a test for `--global --multitenant=false/true` for these and asserting tenant output pops up

**Pull request merged**
