### PR TITLE
kvserver: consider replica GC when leader loses quorum

### LINKED ISSUE #58376: kvserver: validate use of reset-quorum in the presence of other replicas
We removed the `TestResetQuorum/with-replicas-elsewhere` sub-test in #58253, one that should work. 
```
// TestResetQuorum tests the ResetQuorum method in various scenarios.
// We do this by starting a four-node cluster with a scratch range
// replicated to all nodes but n1. We then shut down nodes as necessary,
// to simulate partial or total data loss, check to see if the range is
// unavailable, and finally attempt to use ResetQuorum against it.
```

I've observed two failure modes when trying to revive it:
(i) A consistency check failure that finds missing keys
(ii) The older server holds onto the range lease, which doesn't let us ResetQuorum from elsewhere (n1), and the test times out (I was using a 30s ctx duration for my stress runs).

(ii) is more pressing, and masks failures for (i) as the test just hangs when trying to call ResetQuorum through n1. Attempts to transfer the range lease away using AdminLeaseTransfer also hang (cut off my investigation early, so don't know why). Bumping n4's liveness epoch forces the lease to be revoked, which does the trick, but it's worth investigating why AdminLeaseTransfer is unusable in this test setup. Separate from that, it's unclear why the consistency checker reports a failure. I've seen this happen in package wide tests (`make test PKG=./pkg/kv/kvserver`) where the entire package times out.

### PR DESCRIPTION
**Pull request by erikgrinaker**
The replica GC queue will normally wait 10 days before checking whether
a replica should be GCed (e.g. by looking up the range descriptor). If
the replica is considered suspect (e.g. when it is a Raft candidate),
the descriptor will be checked every second instead.

However, a leader was never considered suspect. This could cause a
situation where a leader who lost a quorum and was replaced via
`Node.ResetQuorum()` would cling onto the range until the 10 day GC
timeout expired and it finally checked the range descriptor.

This patch considers leaders who are not able to make progress suspect,
thereby checking the range descriptor every second and GCing the replica
if it has been removed from the descriptor. It also adds back a
`ResetQuorum` test case that was removed previously as it would fail in
this scenario.

Resolves #58376.

Release note (bug fix): A Raft leader who loses quorum will now
relinquish its range lease and remove the replica if the range is
recreated elsewhere, e.g. via `Node.ResetQuorum()`.

### CODE REVIEW

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @irfansharif)

___
*[pkg/kv/kvserver/replica_gc_queue.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVq5dwl8Qy3QfcCYOqX:-MVq5dwl8Qy3QfcCYOqY:b-98oan3) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0058c976d397a5ca4158a86cc848fadb12ceb0/pkg/kv/kvserver/replica_gc_queue.go#L168)):*
> ```Go
> 			}
> 		}
> 	} else if replDesc.GetType() != roachpb.VOTER_FULL {
> ```

@aayushshah15 this code (and the old code) mark non-voting replicas as suspect and check them eagerly. I assume this was not the intention. We should change this to `typ := replDesc.GetType(); typ != roachpb.VOTER_FULL && typ != roachpb.NON_VOTER`, right?

**Review by tbg — COMMENTED** [review]
Very nice. Could you add the other thing we discussed, namely forcing a consistency check on the range right after you've recovered? See `ForceConsistencyQueueProcess`. This would be particularly powerful if you also disabled the replicaGCQueue before that call (so that the old replica is still around when the consistency check happens) but I won't push for that.
It is concerning that Irfan saw consistency failures in the original issue, I don't think he made that up.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-:-MVq6Kcw3OcQ8DNiyFKk:bsf46sc)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @irfansharif)

**Review by tbg — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @irfansharif)

**Review by erikgrinaker — COMMENTED** [review]
Sure. I did do that "manually" while debugging this, and ran a bunch of stress tests, but never saw any evidence of consistency issues -- apart from log warnings that seemed entirely reasonable (I think because replicas were unavailable or something like that). Will update the tests and dig a bit more.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-:-MVq7bgD3oLnAz8Lt0Bg:bg9kgb4)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @irfansharif)

**Comment by aayushshah15** [comment]
___
*[pkg/kv/kvserver/replica_gc_queue.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVq5dwl8Qy3QfcCYOqX:-MVqVO8T0qX_zXLl6DLC:b-m5rg1l) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0058c976d397a5ca4158a86cc848fadb12ceb0/pkg/kv/kvserver/replica_gc_queue.go#L168)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

@aayushshah15 this code (and the old code) mark non-voting replicas as suspect and check them eagerly. I assume this was not the intention. We should change this to `typ := replDesc.GetType(); typ != roachpb.VOTER_FULL && typ != roachpb.NON_VOTER`, right?
</blockquote></details>


You're right. Would it be okay to make the change in this PR or should I be creating a new patch for it?

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

___
*[pkg/kv/kvserver/replica_gc_queue.go, line 168 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVq5dwl8Qy3QfcCYOqX:-MVqYRX2CsotZYOmdgDp:b-kczw6f) ([raw file](https://github.com/cockroachdb/cockroach/blob/9b0058c976d397a5ca4158a86cc848fadb12ceb0/pkg/kv/kvserver/replica_gc_queue.go#L168)):*
<details><summary><i>Previously, aayushshah15 (Aayush Shah) wrote…</i></summary><blockquote>

You're right. Would it be okay to make the change in this PR or should I be creating a new patch for it?
</blockquote></details>

I can include it in this PR, as a separate commit.

**Review by erikgrinaker — COMMENTED** [review]
> Could you add the other thing we discussed, namely forcing a consistency check on the range right after you've recovered? See ForceConsistencyQueueProcess. This would be particularly powerful if you also disabled the replicaGCQueue before that call (so that the old replica is still around when the consistency check happens) but I won't push for that.

So I ended up doing this by adding a non-voting replica to the mix, which (now) isn't considered suspect. I could've done this via testing knobs as well, but figured it'd be interesting to see how a non-voter behaves here. Consistency checks always pass (so far, anyway).

The non-voter will non-deterministically (rarely) GC its replica, so we don't assert anything about it except that any consistent reads will hit the reset replica. Might be interesting to try an inconsistent read as well, but didn't look into it yet.

I'm not sure what we'd really want the behavior of a non-voter to be. In the sort of scenario where ResetQuorum comes up, I'd imagine someone using follower reads for their app would actually want the non-voter to hang onto the replica for as long as possible.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-:-MVripaa3hGipbcXifxs:b142iyr)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @irfansharif and @tbg)

**Review by tbg — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker, @irfansharif, and @tbg)

___
*[pkg/kv/kvserver/replica_gc_queue.go, line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuJE0c2-Ua5wNSTrKo:-MVuJE0c2-Ua5wNSTrKp:bpjdrhy) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/replica_gc_queue.go#L174)):*
> ```Go
> 	} else if t := replDesc.GetType(); t != roachpb.VOTER_FULL && t != roachpb.NON_VOTER {
> 		isSuspect = true
> 	} else {
> ```

I wonder if there's another conditional missing here. If a replica doesn't know who the leader is, shouldn't it also be suspect? The NON_VOTER in this test should fall into that category - it's a learner, so it couldn't ever become candidate or leader, but conceivably it could clear its view of the leader when the heartbeats stop (though it certainly wouldn't work that way for a quiesced non voter). Maybe not worth adding too many drive-by bells and whistles here.
___
*[pkg/kv/kvserver/reset_quorum_test.go, line 196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuHKSVD-hDX-BKVrNq:-MVuHKSVD-hDX-BKVrNr:b-z28g4s) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/reset_quorum_test.go#L196)):*
> ```Go
> 
> 		// Wait for n2, n3, n4, and n5 liveness to expire.
> 		time.Sleep(livenessDuration)
> ```

Just for kicks, could you use the HybridLogicalClock to avoid the sleep as shown here:

https://github.com/cockroachdb/cockroach/blob/0b011511a852c30d1d4f8b09268db39c75e11a95/pkg/kv/kvserver/node_liveness_test.go#L313-L314
___
*[pkg/kv/kvserver/reset_quorum_test.go, line 258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuI6FB7PTUMy9Cms5v:-MVuI6FB7PTUMy9Cms5w:b-ysoobx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/reset_quorum_test.go#L258)):*
> ```Go
> 		checkConsistency(t, srv, tc.Server(n4), tc.Server(n5))
> 
> 		// Non-voting replica (n5) may or may not have been GCed, so we don't
> ```

The replica should *ultimately* be gc'ed, right? It's just that it might take ten days. This is at odds though with expecting it to always return the newest value, no? The comment here suggests that you are reading this value off the non-voting replica, but I think what in fact happens is that you read from the leaseholder (the reset replica) so it doesn't really test anything about the non-voter. If you checked for the latest value for `k` on the non-voting replica, you should see `original` (or find that the replica no longer exists), though you'd have to sneak past the NotLeaseholderError by going directly to the engine (or try to do follower reads).
It's actually interesting to think about how follower reads would work here. Would we erroneously serve stale follower reads here or would that replica not see new timestamps getting closed out? cc @andreimatei

**Review by tbg — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @erikgrinaker and @irfansharif)

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @irfansharif, and @tbg)

___
*[pkg/kv/kvserver/replica_gc_queue.go, line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuJE0c2-Ua5wNSTrKo:-MVuRJEOEQxlExT1a8_A:b-nt10yz) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/replica_gc_queue.go#L174)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

I wonder if there's another conditional missing here. If a replica doesn't know who the leader is, shouldn't it also be suspect? The NON_VOTER in this test should fall into that category - it's a learner, so it couldn't ever become candidate or leader, but conceivably it could clear its view of the leader when the heartbeats stop (though it certainly wouldn't work that way for a quiesced non voter). Maybe not worth adding too many drive-by bells and whistles here.
</blockquote></details>

Yeah, I was considering something like that as well. In typical ResetQuorum scenarios people are usually stressed out and want as few surprises as possible. The least surprising thing to do is probably to just GC all replicas. Are non-voters the only remaining stragglers, or are there other cases we should consider too?
___
*[pkg/kv/kvserver/reset_quorum_test.go, line 196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuHKSVD-hDX-BKVrNq:-MVuS0Tt-b9veclrLW7y:bfunpbm) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/reset_quorum_test.go#L196)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Just for kicks, could you use the HybridLogicalClock to avoid the sleep as shown here:

https://github.com/cockroachdb/cockroach/blob/0b011511a852c30d1d4f8b09268db39c75e11a95/pkg/kv/kvserver/node_liveness_test.go#L313-L314
</blockquote></details>

Tried this, but started seeing test failures (writes not taking effect and such). Probably because some processes rely on time flowing forwards.
___
*[pkg/kv/kvserver/reset_quorum_test.go, line 258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuI6FB7PTUMy9Cms5v:-MVuSLPH2coW6CRpPJ5k:b-3qtep6) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/reset_quorum_test.go#L258)):*
>The replica should ultimately be gc'ed, right? It's just that it might take ten days.

Yep.

> I think what in fact happens is that you read from the leaseholder (the reset replica) so it doesn't really test anything about the non-voter

Yeah, I wanted to test that the non-voter would actually pick up the new n1 leaseholder even though it's not in its own range descriptor (which has n2,n3,n4 as voters). Would be interesting to try a follower read, but we should probably just GC it.

**Review by tbg — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @erikgrinaker, and @irfansharif)

___
*[pkg/kv/kvserver/replica_gc_queue.go, line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuJE0c2-Ua5wNSTrKo:-MVud1C42TkWc7dm0PjU:b6h071n) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/replica_gc_queue.go#L174)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Yeah, I was considering something like that as well. In typical ResetQuorum scenarios people are usually stressed out and want as few surprises as possible. The least surprising thing to do is probably to just GC all replicas. Are non-voters the only remaining stragglers, or are there other cases we should consider too?
</blockquote></details>

Quiesced ranges in general are hard to GC in a timely way because nothing wakes them up. This could likely affect the non-voter in this test too. If it's quiesced (i.e. no raft heartbeats are sent to it before the outage) it isn't particularly concerned  about not hearing from the leader in a while. It is only after getting woken up (by a request that prompts a a lease acquisition, for example) that the heuristics here would kick in. We could reach out to all of the old replicas as part of `ResetQuorum`, but I'd be hesitant to do so in this PR.
___
*[pkg/kv/kvserver/reset_quorum_test.go, line 196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuHKSVD-hDX-BKVrNq:-MVucjqI2fOk3VQSOncJ:b-s7l31i) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/reset_quorum_test.go#L196)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

Tried this, but started seeing test failures (writes not taking effect and such). Probably because some processes rely on time flowing forwards.
</blockquote></details>

Can you give me a branch that shows this? This seems like a clear-cut case where this should work, and if it doesn't we should fix it.
___
*[pkg/kv/kvserver/reset_quorum_test.go, line 258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuI6FB7PTUMy9Cms5v:-MVucp5ACh786PnWCURv:b-i3d3ft) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/reset_quorum_test.go#L258)):*
<details><summary><i>Previously, erikgrinaker (Erik Grinaker) wrote…</i></summary><blockquote>

>The replica should ultimately be gc'ed, right? It's just that it might take ten days.

Yep.

> I think what in fact happens is that you read from the leaseholder (the reset replica) so it doesn't really test anything about the non-voter

Yeah, I wanted to test that the non-voter would actually pick up the new n1 leaseholder even though it's not in its own range descriptor (which has n2,n3,n4 as voters). Would be interesting to try a follower read, but we should probably just GC it.
</blockquote></details>

Oh, I see. I would make it clear when you're talking about the *node* the non-voter is on vs the non-voter itself. When you say "the non-voter" I consider the canonical interpretation of that to be the *replica* itself, but you're not touching that.

**Review by erikgrinaker — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @andreimatei, @irfansharif, and @tbg)

___
*[pkg/kv/kvserver/replica_gc_queue.go, line 174 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuJE0c2-Ua5wNSTrKo:-MVumAvK2inNz852H9uc:bj5ja0b) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/replica_gc_queue.go#L174)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Quiesced ranges in general are hard to GC in a timely way because nothing wakes them up. This could likely affect the non-voter in this test too. If it's quiesced (i.e. no raft heartbeats are sent to it before the outage) it isn't particularly concerned  about not hearing from the leader in a while. It is only after getting woken up (by a request that prompts a a lease acquisition, for example) that the heuristics here would kick in. We could reach out to all of the old replicas as part of `ResetQuorum`, but I'd be hesitant to do so in this PR.
</blockquote></details>

Good point, but we'd want to GC it once it wakes up though.
___
*[pkg/kv/kvserver/reset_quorum_test.go, line 196 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuHKSVD-hDX-BKVrNq:-MVulpAH0i9gnctTMqc5:b-qoph35) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/reset_quorum_test.go#L196)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Can you give me a branch that shows this? This seems like a clear-cut case where this should work, and if it doesn't we should fix it.
</blockquote></details>

Pushed it to a branch here:

https://github.com/erikgrinaker/cockroach/tree/resetquorum-manualclock-test

Fails on `make test PKG=./pkg/kv/kvserver TESTS=TestResetQuorum/with-leaseholder-elsewhere TESTFLAGS=-v` with `reset_quorum_test.go:140: key not empty, expected to be empty after resetting quorum`.
___
*[pkg/kv/kvserver/reset_quorum_test.go, line 258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuI6FB7PTUMy9Cms5v:-MVum7tm-eAIs0394Uyx:blk3rl7) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/reset_quorum_test.go#L258)):*
<details><summary><i>Previously, tbg (Tobias Grieger) wrote…</i></summary><blockquote>

Oh, I see. I would make it clear when you're talking about the *node* the non-voter is on vs the non-voter itself. When you say "the non-voter" I consider the canonical interpretation of that to be the *replica* itself, but you're not touching that.
</blockquote></details>

Got it, will try to be more precise.

**Comment by erikgrinaker** [comment]
bors r=tbg

Opened #62075 to follow up on suspect replica heuristics.

**Review by andreimatei — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/61977)* status: :shipit: complete! 0 of 0 LGTMs obtained

___
*[pkg/kv/kvserver/reset_quorum_test.go, line 258 at r3](https://reviewable.io/reviews/cockroachdb/cockroach/61977#-MVuI6FB7PTUMy9Cms5v:-MVvi3Ib-zM83gzLWa3l:b-mzqyzx) ([raw file](https://github.com/cockroachdb/cockroach/blob/8755b6bb06d4d5984db49beb9ded88545346310c/pkg/kv/kvserver/reset_quorum_test.go#L258)):*
> It's actually interesting to think about how follower reads would work here. Would we erroneously serve stale follower reads here or would that replica not see new timestamps getting closed out?

I couldn't immediately get enough context to understand the question. Can you describe the scenario if you still care?

**Comment by irfansharif** [comment]
I suspect this is worth backporting to 21.1 to let us use reset-quorum on 21.1 clusters.

**Pull request merged**
