### PR TITLE
insights: ingester

### LINKED ISSUE #81021: outliers: move processing off the hot path
Epic: CRDB-13544

Jira issue: CRDB-15395

### PR DESCRIPTION
**Pull request by matthewtodd**
Closes #81021.
    
Here we begin observing statements and transactions asynchronously, to
avoid slowing down the hot sql execution path as much as possible.
    
Release note: None

### CODE REVIEW

**Review by j82w — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85350)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w and @matthewtodd)

___
*[`pkg/sql/sqlstats/insights/ingester.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85350#-N8OcaW09brS121Z7lw8:-N8OcaW09brS121Z7lw9:b-gzse0k) ([raw file](https://github.com/cockroachdb/cockroach/blob/66744274022823ff7bbc2a1194f3df7ea79d74c5/pkg/sql/sqlstats/insights/ingester.go#L33)):*
> ```Go
> 
> type concurrentBufferIngester struct {
> 	guard struct {
> ```

What is the reason for using the ConcurrentBufferGuard instead of just a normal Channel? Channels are thread safe so I'm trying to understand what benefits it gives. 
___
*[`pkg/sql/sqlstats/insights/ingester.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85350#-N8ODzGAB_7tzR_UJNUr:-N8ODzGAB_7tzR_UJNUs:bcrwjq8) ([raw file](https://github.com/cockroachdb/cockroach/blob/66744274022823ff7bbc2a1194f3df7ea79d74c5/pkg/sql/sqlstats/insights/ingester.go#L39)):*
> ```Go
> 
> 	sink     chan *block
> 	delegate Registry
> ```

Would it be better to have a channel per a registry? That way if one is running slow or if the buffer is full it can skip that input for that registry and not impact the other registries.
___
*[`pkg/sql/sqlstats/insights/ingester.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85350#-N8OfVuHC7-iWGLDrPgT:-N8OfVuHC7-iWGLDrPgU:bhnr1jk) ([raw file](https://github.com/cockroachdb/cockroach/blob/66744274022823ff7bbc2a1194f3df7ea79d74c5/pkg/sql/sqlstats/insights/ingester.go#L92)):*
> ```Go
> 	sessionID clusterunique.ID, statement *Statement,
> ) {
> 	i.guard.AtomicWrite(func(writerIdx int64) {
> ```

Should there be a check if the buffer is full and log a message to avoid blocking to the registry is running to slow?

**Review by matthewtodd — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85350)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @j82w)

___
*[`pkg/sql/sqlstats/insights/ingester.go` line 33 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85350#-N8OcaW09brS121Z7lw8:-N9CFDJl2Gh2hJIYe4PP:b-wc8puo) ([raw file](https://github.com/cockroachdb/cockroach/blob/66744274022823ff7bbc2a1194f3df7ea79d74c5/pkg/sql/sqlstats/insights/ingester.go#L33)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

What is the reason for using the ConcurrentBufferGuard instead of just a normal Channel? Channels are thread safe so I'm trying to understand what benefits it gives. 
</blockquote></details>

Good question! A channel would be way simpler, but we're trying to be super fast here since we're on the SQL execution path. I ran some benchmarks, and the ConcurrentBufferGuard approach is about 7.5 times faster than just using a channel. (140ns/op vs. 1100ns/op on my laptop.)

There's a lot more goroutine coordination in the channel approach; ConcurrentBufferGuard is built around an atomic int and a read mutex, which is far lighter-weight.
___
*[`pkg/sql/sqlstats/insights/ingester.go` line 39 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85350#-N8ODzGAB_7tzR_UJNUr:-N9CH-ET3hxcPQD2SZki:b-39aeyi) ([raw file](https://github.com/cockroachdb/cockroach/blob/66744274022823ff7bbc2a1194f3df7ea79d74c5/pkg/sql/sqlstats/insights/ingester.go#L39)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Would it be better to have a channel per a registry? That way if one is running slow or if the buffer is full it can skip that input for that registry and not impact the other registries.
</blockquote></details>

There is only one Registry instance. I have been hoping that will be sufficient, since keeping the inner implementation "global" and single-threaded is easy to reason about and unit test. The hope for the ingester is to handle all the async / parallel work, feeding observations into it.

I think you're right, though, that there's perhaps more to understand and design for about how this thing behaves when it's overwhelmed. At the moment, some micro-benchmarking here shows level performance at 140ns/op with 1K concurrent sessions hammering the ingester, getting slightly slower at 10K concurrent sessions, so I feel confident enough to subject this thing to the roachtests as our next step.
___
*[`pkg/sql/sqlstats/insights/ingester.go` line 92 at r1](https://reviewable.io/reviews/cockroachdb/cockroach/85350#-N8OfVuHC7-iWGLDrPgT:-N9CJ18B1xf8QcETQnWy:b-ej1vum) ([raw file](https://github.com/cockroachdb/cockroach/blob/66744274022823ff7bbc2a1194f3df7ea79d74c5/pkg/sql/sqlstats/insights/ingester.go#L92)):*
<details><summary><i>Previously, j82w wrote…</i></summary><blockquote>

Should there be a check if the buffer is full and log a message to avoid blocking to the registry is running to slow?
</blockquote></details>

At this level, I think we can let the ConcurrentBufferGuard handle that for us. While it will lock to flush the buffer into the channel, I think we're okay with amortizing that cost. And, again, I think the micro-benchmarks here do give us some reasonable first-order confidence that the Registry has more than enough performance capacity to keep up.

But, yes, I think some safety releases probably make sense for us to experiment with next week.

**Review by j82w — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/85350#-:-N9CXHknEzANsgBpBQ0b:bnfp4nl)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @matthewtodd)

**Comment by renatolabs** [comment]
This change introduced a data race on `TestConsumeJoinToken`. I'm going to create a PR shortly to skip that test under race for the time being.

**Comment by msbutler** [comment]
This PR is also introducing a consistent data race in [my PR](https://github.com/cockroachdb/cockroach/pull/85852#pullrequestreview-1067432892) that was ready to merge until I rebased onto the commit in this PR. It seems like we should revert this PR, as it seems to be exposing the codebase to data races?

**Comment by matthewtodd** [comment]
I've just sent #85994 to disable this problematic codepath until I can get to the bottom of it. I'm sorry for the disruption!

**Comment by msbutler** [comment]
thanks!

**Pull request merged**
