### PR TITLE
sql: persist table locality metadata and display in SHOW CREATE TABLE

### PR DESCRIPTION
**Pull request by otan**
Refs: #57473

----

*sql: persist table locality metadata*

Release note (sql change): LOCALITY directives on CREATE TABLE are now
persisted onto the database.

*sql: display LOCALITY clause in SHOW CREATE TABLE*

Release note (sql change): Multi-region defined table localities now
display on the SHOW CREATE TABLE command.

### CODE REVIEW

**Review by ajstorm — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm and @otan)

___
*[pkg/sql/create_table.go, line 1727 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNsjq4A1U6KFel-tRsW:-MNsjq4BE2xSLseOvh1k:bpm5h6w) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/create_table.go#L1727)):*
> ```Go
> 			return nil, pgerror.New(
> 				pgcode.InvalidTableDefinition,
> 				"cannot set locality on table with no multi-region configuration on the database",
> ```

Nit: Can we simplify the error message to avoid the double negative?  Maybe something like "setting locality on table requires database to have one or more regions".  Also, are we able to add doc links to these error messages?  I've seen it in cli commands, but not in SQL command.  Would be super-helpful to users if we could show them a link to the relative docs here.
___
*[pkg/sql/create_table.go, line 1741 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNslRNF-obMlLKR0z9k:-MNslRNF-obMlLKR0z9l:b-50i2ax) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/create_table.go#L1741)):*
> ```Go
> 				RegionalByTable: &descpb.TableDescriptor_LocalityConfig_RegionalByTable{},
> 			}
> 			if n.Locality.TableRegion != "" {
> ```

Is there value in wrapping this region validation code in a separate function?  We seem to use it in several places.
___
*[pkg/sql/create_table.go, line 1741 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNsliyj0Q-Okskhot2k:-MNsliyj0Q-Okskhot2l:bhxkz23) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/create_table.go#L1741)):*
> ```Go
> 				RegionalByTable: &descpb.TableDescriptor_LocalityConfig_RegionalByTable{},
> 			}
> 			if n.Locality.TableRegion != "" {
> ```

Do we need an else branch here for the case where the user doesn't provide a region and we're going to default to the PRIMARY REGION?
___
*[pkg/sql/create_table.go, line 1753 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNslHC_ER7-1wM-3ZAm:-MNslHC_ER7-1wM-3ZAn:bvqlto3) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/create_table.go#L1753)):*
> ```Go
> 					return nil, pgerror.Newf(
> 						pgcode.InvalidTableDefinition,
> 						`region "%s" is not available on database "%s"`,
> ```

Nit: `region %s has not been added to database %s`?  "available" seems ambiguous to me.
___
*[pkg/sql/catalog/tabledesc/structured.go, line 1498 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNsneDIEKKdZXtnPVHf:-MNsneDIEKKdZXtnPVHg:b6j1rwr) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/catalog/tabledesc/structured.go#L1498)):*
> ```Go
> 			if !db.IsMultiRegion() {
> 				return errors.AssertionFailedf(
> 					"database %s is not multi-region enabled, but table %s has multi-region features",
> ```

Nit: Can we be more specific here?  "database %s is not multi-region enabled, but table %s has locality %s set"?
___
*[pkg/sql/catalog/tabledesc/structured.go, line 1520 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNso7b79XqjgFU7jp6V:-MNso7b79XqjgFU7jp6W:b-lrxphq) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/catalog/tabledesc/structured.go#L1520)):*
> ```Go
> 					if !contains {
> 						return errors.AssertionFailedf(
> 							"expected database %s to contain region %s as defined by REGIONAL BY TABLE on table %s",
> ```

Nit: Does it make sense to return the list of regions set on the database here?  I'm wondering about the case where for some reason we got into a state where the region set on the table is one character off from the region set on the database.

**Review by otan — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57513)* status: :shipit: complete! 0 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/create_table.go, line 1727 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNsjq4A1U6KFel-tRsW:-MNtf-M39hpyOMcluQK8:bed7k4z) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/create_table.go#L1727)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: Can we simplify the error message to avoid the double negative?  Maybe something like "setting locality on table requires database to have one or more regions".  Also, are we able to add doc links to these error messages?  I've seen it in cli commands, but not in SQL command.  Would be super-helpful to users if we could show them a link to the relative docs here.
</blockquote></details>

Done.

We can add docs links, but that'll have to come later when we have the docs page.
___
*[pkg/sql/create_table.go, line 1741 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNslRNF-obMlLKR0z9k:-MNthQPh3vay55Us8nlt:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/create_table.go#L1741)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Is there value in wrapping this region validation code in a separate function?  We seem to use it in several places.
</blockquote></details>

Done.
___
*[pkg/sql/create_table.go, line 1741 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNsliyj0Q-Okskhot2k:-MNthRizClXopX6L02TT:b-t6istu) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/create_table.go#L1741)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Do we need an else branch here for the case where the user doesn't provide a region and we're going to default to the PRIMARY REGION?
</blockquote></details>

This is implied by the `nil` `TableRegion` field.
___
*[pkg/sql/create_table.go, line 1753 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNslHC_ER7-1wM-3ZAm:-MNtoCGD51YFpVKm4vWw:b-896fix) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/create_table.go#L1753)):*
<details><summary><i>Previously, ajstorm wrote…</i></summary><blockquote>

Nit: `region %s has not been added to database %s`?  "available" seems ambiguous to me.
</blockquote></details>

Done.

**Review by ajstorm — APPROVED** [review]
Thanks for making the changes.  Code looks great!

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-:-MNyRql_9Tn9SLbzL2-Y:b-csb6ux)* status: :shipit: complete! 1 of 0 LGTMs obtained (waiting on @ajstorm)

___
*[pkg/sql/create_table.go, line 1741 at r2](https://reviewable.io/reviews/cockroachdb/cockroach/57513#-MNslRNF-obMlLKR0z9k:-MNyRiR1Ert--dqW8_8J:b-jji86y) ([raw file](https://github.com/cockroachdb/cockroach/blob/a710a366450564cb0f92c838b09b6c60a51efc6d/pkg/sql/create_table.go#L1741)):*
<details><summary><i>Previously, otan (Oliver Tan) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great, looks much better!

**Comment by otan** [comment]
thanks for the suggestions!

bors r=ajstorm

**Pull request merged**
